// Souffle - A Datalog Compiler
// Copyright (c) 2019, The Souffle Developers. All rights reserved
// Licensed under the Universal Permissive License v 1.0 as shown at:
// - https://opensource.org/licenses/UPL
// - <souffle root>/licenses/SOUFFLE-UPL.txt

.functor foo(number, symbol):number
.functor goo(symbol, number):number
.functor hoo():symbol
.functor ioo(number):symbol

.functor factorial(unsigned):unsigned
.functor rnd(float):number

.decl A(x:number)
A(@foo(1,"123")) :- true.
A(@goo("1234",2)) :- true.

.output A

.decl I(x:number) inline
I(1) :- 1 < 5.

.decl B(x:symbol)
B(@hoo()) :- true.

// Test functor use with inlined relations
B(@ioo(x)) :- I(x), I(@foo(x, @ioo(x))).

.output B

// Test functor use within a subloop
.decl C(x:number)
C(r) :- r = @foo(x, y), A(x), B(y).
.output C



// Test float and unsigned

.decl F(x:unsigned)
F(@factorial(3u)) :- true.
F(@factorial(5u)) :- true.
F(@factorial(10u)) :- true.
.output F

.decl R(i:number)
R(@rnd(-12.35)) :- true.
R(@rnd(-1.1231)) :- true.
R(@rnd(0.7)) :- true.
R(@rnd(0.2)) :- true.
.output R
