/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class map_string_string extends java.util.AbstractMap<String, String> {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected map_string_string(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(map_string_string obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SwigInterfaceJNI.delete_map_string_string(swigCPtr);
      }
      swigCPtr = 0;
    }
  }


  public int size() {
    return sizeImpl();
  }

  public boolean containsKey(java.lang.Object key) {
    if (!(key instanceof String)) {
      return false;
    }

    return containsImpl((String)key);
  }

  public String get(java.lang.Object key) {
    if (!(key instanceof String)) {
      return null;
    }

    Iterator itr = find((String) key);
    if (itr.isNot(end())) {
      return itr.getValue();
    }

    return null;
  }

  public String put(String key, String value) {
    Iterator itr = find((String) key);
    if (itr.isNot(end())) {
      String oldValue = itr.getValue();
      itr.setValue(value);
      return oldValue;
    } else {
      putUnchecked(key, value);
      return null;
    }
  }

  public String remove(java.lang.Object key) {
    if (!(key instanceof String)) {
      return null;
    }

    Iterator itr = find((String) key);
    if (itr.isNot(end())) {
      String oldValue = itr.getValue();
      removeUnchecked(itr);
      return oldValue;
    } else {
      return null;
    }
  }

  public java.util.Set<Entry<String, String>> entrySet() {
    java.util.Set<Entry<String, String>> setToReturn =
        new java.util.HashSet<Entry<String, String>>();

    Iterator itr = begin();
    final Iterator end = end();
    while (itr.isNot(end)) {
      setToReturn.add(new Entry<String, String>() {
        private Iterator iterator;

        private Entry<String, String> init(Iterator iterator) {
          this.iterator = iterator;
          return this;
        }

        public String getKey() {
          return iterator.getKey();
        }

        public String getValue() {
          return iterator.getValue();
        }

        public String setValue(String newValue) {
          String oldValue = iterator.getValue();
          iterator.setValue(newValue);
          return oldValue;
        }
      }.init(itr));
      itr = itr.getNextUnchecked();
    }

    return setToReturn;
  }

  public map_string_string() {
    this(SwigInterfaceJNI.new_map_string_string__SWIG_0(), true);
  }

  public map_string_string(map_string_string other) {
    this(SwigInterfaceJNI.new_map_string_string__SWIG_1(map_string_string.getCPtr(other), other), true);
  }

  static protected class Iterator {
    private transient long swigCPtr;
    protected transient boolean swigCMemOwn;
  
    protected Iterator(long cPtr, boolean cMemoryOwn) {
      swigCMemOwn = cMemoryOwn;
      swigCPtr = cPtr;
    }
  
    protected static long getCPtr(Iterator obj) {
      return (obj == null) ? 0 : obj.swigCPtr;
    }
  
    @SuppressWarnings("deprecation")
    protected void finalize() {
      delete();
    }
  
    public synchronized void delete() {
      if (swigCPtr != 0) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          SwigInterfaceJNI.delete_map_string_string_Iterator(swigCPtr);
        }
        swigCPtr = 0;
      }
    }
  
    private map_string_string.Iterator getNextUnchecked() {
      return new map_string_string.Iterator(SwigInterfaceJNI.map_string_string_Iterator_getNextUnchecked(swigCPtr, this), true);
    }
  
    private boolean isNot(map_string_string.Iterator other) {
      return SwigInterfaceJNI.map_string_string_Iterator_isNot(swigCPtr, this, map_string_string.Iterator.getCPtr(other), other);
    }
  
    private String getKey() {
      return SwigInterfaceJNI.map_string_string_Iterator_getKey(swigCPtr, this);
    }
  
    private String getValue() {
      return SwigInterfaceJNI.map_string_string_Iterator_getValue(swigCPtr, this);
    }
  
    private void setValue(String newValue) {
      SwigInterfaceJNI.map_string_string_Iterator_setValue(swigCPtr, this, newValue);
    }
  
  }

  public boolean isEmpty() {
    return SwigInterfaceJNI.map_string_string_isEmpty(swigCPtr, this);
  }

  public void clear() {
    SwigInterfaceJNI.map_string_string_clear(swigCPtr, this);
  }

  private map_string_string.Iterator find(String key) {
    return new map_string_string.Iterator(SwigInterfaceJNI.map_string_string_find(swigCPtr, this, key), true);
  }

  private map_string_string.Iterator begin() {
    return new map_string_string.Iterator(SwigInterfaceJNI.map_string_string_begin(swigCPtr, this), true);
  }

  private map_string_string.Iterator end() {
    return new map_string_string.Iterator(SwigInterfaceJNI.map_string_string_end(swigCPtr, this), true);
  }

  private int sizeImpl() {
    return SwigInterfaceJNI.map_string_string_sizeImpl(swigCPtr, this);
  }

  private boolean containsImpl(String key) {
    return SwigInterfaceJNI.map_string_string_containsImpl(swigCPtr, this, key);
  }

  private void putUnchecked(String key, String value) {
    SwigInterfaceJNI.map_string_string_putUnchecked(swigCPtr, this, key, value);
  }

  private void removeUnchecked(map_string_string.Iterator itr) {
    SwigInterfaceJNI.map_string_string_removeUnchecked(swigCPtr, this, map_string_string.Iterator.getCPtr(itr), itr);
  }

}
