/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class SwigInterfaceJNI {
  public final static native long new_map_string_string__SWIG_0();
  public final static native long new_map_string_string__SWIG_1(long jarg1, map_string_string jarg1_);
  public final static native long map_string_string_Iterator_getNextUnchecked(long jarg1, map_string_string.Iterator jarg1_);
  public final static native boolean map_string_string_Iterator_isNot(long jarg1, map_string_string.Iterator jarg1_, long jarg2, map_string_string.Iterator jarg2_);
  public final static native String map_string_string_Iterator_getKey(long jarg1, map_string_string.Iterator jarg1_);
  public final static native String map_string_string_Iterator_getValue(long jarg1, map_string_string.Iterator jarg1_);
  public final static native void map_string_string_Iterator_setValue(long jarg1, map_string_string.Iterator jarg1_, String jarg2);
  public final static native void delete_map_string_string_Iterator(long jarg1);
  public final static native boolean map_string_string_isEmpty(long jarg1, map_string_string jarg1_);
  public final static native void map_string_string_clear(long jarg1, map_string_string jarg1_);
  public final static native long map_string_string_find(long jarg1, map_string_string jarg1_, String jarg2);
  public final static native long map_string_string_begin(long jarg1, map_string_string jarg1_);
  public final static native long map_string_string_end(long jarg1, map_string_string jarg1_);
  public final static native int map_string_string_sizeImpl(long jarg1, map_string_string jarg1_);
  public final static native boolean map_string_string_containsImpl(long jarg1, map_string_string jarg1_, String jarg2);
  public final static native void map_string_string_putUnchecked(long jarg1, map_string_string jarg1_, String jarg2, String jarg3);
  public final static native void map_string_string_removeUnchecked(long jarg1, map_string_string jarg1_, long jarg2, map_string_string.Iterator jarg2_);
  public final static native void delete_map_string_string(long jarg1);
  public final static native void loadInput(long jarg1, map_string_string jarg1_, String jarg2, String jarg3, String jarg4);
  public final static native long new_SWIGSouffleProgram(long jarg1);
  public final static native void delete_SWIGSouffleProgram(long jarg1);
  public final static native void SWIGSouffleProgram_run(long jarg1, SWIGSouffleProgram jarg1_);
  public final static native void SWIGSouffleProgram_runAll(long jarg1, SWIGSouffleProgram jarg1_, String jarg2, String jarg3);
  public final static native void SWIGSouffleProgram_loadAll(long jarg1, SWIGSouffleProgram jarg1_, String jarg2);
  public final static native void SWIGSouffleProgram_printAll(long jarg1, SWIGSouffleProgram jarg1_, String jarg2);
  public final static native void SWIGSouffleProgram_dumpInputs__SWIG_0(long jarg1, SWIGSouffleProgram jarg1_, long jarg2);
  public final static native void SWIGSouffleProgram_dumpInputs__SWIG_1(long jarg1, SWIGSouffleProgram jarg1_);
  public final static native void SWIGSouffleProgram_dumpOutputs__SWIG_0(long jarg1, SWIGSouffleProgram jarg1_, long jarg2);
  public final static native void SWIGSouffleProgram_dumpOutputs__SWIG_1(long jarg1, SWIGSouffleProgram jarg1_);
  public final static native long newInstance(String jarg1);
}
