/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class SWIGSouffleProgram {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SWIGSouffleProgram(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SWIGSouffleProgram obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SwigInterfaceJNI.delete_SWIGSouffleProgram(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SWIGSouffleProgram(SWIGTYPE_p_souffle__SouffleProgram p) {
    this(SwigInterfaceJNI.new_SWIGSouffleProgram(SWIGTYPE_p_souffle__SouffleProgram.getCPtr(p)), true);
  }

  public void run() {
    SwigInterfaceJNI.SWIGSouffleProgram_run(swigCPtr, this);
  }

  public void runAll(String inputDirectory, String outputDirectory) {
    SwigInterfaceJNI.SWIGSouffleProgram_runAll(swigCPtr, this, inputDirectory, outputDirectory);
  }

  public void loadAll(String inputDirectory) {
    SwigInterfaceJNI.SWIGSouffleProgram_loadAll(swigCPtr, this, inputDirectory);
  }

  public void printAll(String outputDirectory) {
    SwigInterfaceJNI.SWIGSouffleProgram_printAll(swigCPtr, this, outputDirectory);
  }

  public void dumpInputs(SWIGTYPE_p_std__ostream out) {
    SwigInterfaceJNI.SWIGSouffleProgram_dumpInputs__SWIG_0(swigCPtr, this, SWIGTYPE_p_std__ostream.getCPtr(out));
  }

  public void dumpInputs() {
    SwigInterfaceJNI.SWIGSouffleProgram_dumpInputs__SWIG_1(swigCPtr, this);
  }

  public void dumpOutputs(SWIGTYPE_p_std__ostream out) {
    SwigInterfaceJNI.SWIGSouffleProgram_dumpOutputs__SWIG_0(swigCPtr, this, SWIGTYPE_p_std__ostream.getCPtr(out));
  }

  public void dumpOutputs() {
    SwigInterfaceJNI.SWIGSouffleProgram_dumpOutputs__SWIG_1(swigCPtr, this);
  }

}
