souffle: profile/Tui.h File Reference
Tui.h File Reference
#include "../ProfileEvent.h"
#include "HtmlGenerator.h"
#include "OutputProcessor.h"
#include "Reader.h"
#include "Table.h"
#include "UserInputReader.h"
#include <algorithm>
#include <chrono>
#include <cstdio>
#include <iostream>
#include <memory>
#include <string>
#include <thread>
#include <vector>
#include <dirent.h>
#include <sys/ioctl.h>
#include <sys/stat.h>
Data Structures
class souffle::profile::Tui
struct souffle::profile::Tui::Usage
Namespaces
souffle
Souffle - A Datalog Compiler Copyright (c) 2013, 2015, Oracle and/or its affiliates.
souffle::profile
Functions
std::stringstream & genJsonAtoms (std::stringstream &ss)
std::stringstream & genJsonConfiguration (std::stringstream &ss)
std::stringstream & souffle::genJsonRules (std::stringstream &ss, const std::string &name, size_t maxRows)
ss<< R"_("code": [)_";bool firstCol=true;while(getline(source_file, str)) { comma(firstCol, ",\");ss<< '"' << Tools::cleanJsonOut(str) << '"';} ss<< "],\";source_file.close();} auto usages=getUsageStats(100);auto beginTime=run-> souffle::getStarttime ()
Variables
souffle::else
ss<< R"_("usage": [)_";bool firstRow=true;Usage previousUsage=*usages.begin();previousUsage.time=beginTime;for(auto usage :usages) { comma(firstRow);ss<< '[';ss<<(usage.time - beginTime).count()/1000000.0<< ", ";ss<< 100.0 *(usage.usertime - previousUsage.usertime)/(usage.time - previousUsage.time)<< ", ";ss<< 100.0 *(usage.systemtime - previousUsage.systemtime)/(usage.time - previousUsage.time)<< ", ";ss<< usage.maxRSS *1024<< ", ";ss<< '"'; bool firstCol = true; for (auto& cur : out.getProgramRun()->getRelationsAtTime(previousUsage.time, usage.time)) { comma(firstCol); ss << cur-> souffle::getName ()
class souffle::profile::Tui souffle::profile::ss
Function Documentation
genJsonAtoms()
std::stringstream& genJsonAtoms (std::stringstream & ss)
Definition at line 532 of file Tui.h.
References souffle::profile::InputReader::appendTabCompletion(), souffle::profile::Tools::cleanJsonOut(), souffle::profile::Tools::cleanString(), souffle::profile::InputReader::clearTabCompletion(), souffle::test::count(), d, souffle::profile::Tools::file_exists(), souffle::profile::Tools::formatMemory(), souffle::profile::Tools::formatNum(), souffle::profile::Tools::formatTable(), souffle::profile::Tools::formatTime(), genJsonConfiguration(), souffle::profile::Tui::genJsonRelations(), souffle::genJsonRules(), souffle::profile::Tui::genJsonTop(), souffle::profile::OutputProcessor::getAtomTable(), souffle::ProfileEventSingleton::getDB(), souffle::profile::HtmlGenerator::getHtml(), souffle::profile::OutputProcessor::getProgramRun(), souffle::profile::OutputProcessor::getRelTable(), souffle::profile::Table::getRows(), souffle::profile::OutputProcessor::getRulTable(), souffle::profile::OutputProcessor::getVersionAtoms(), souffle::profile::OutputProcessor::getVersions(), i, souffle::ProfileEventSingleton::instance(), souffle::profile::Tui::iter, iteration, j, l, tinyformat::printf(), relation, souffle::profile::Tui::resultLimit, souffle::profile::Table::rows, rule, souffle::profile::Table::sort(), souffle::profile::Tools::split(), souffle::profile::ss, str, and souffle::toString().
genJsonConfiguration()
std::stringstream& genJsonConfiguration (std::stringstream & ss)
Definition at line 511 of file Tui.h.
References souffle::profile::Tools::cleanJsonOut(), souffle::ProfileEventSingleton::getDB(), souffle::ProfileEventSingleton::instance(), and souffle::profile::ss.
Referenced by genJsonAtoms().
{
         auto comma = [&ss](bool& first, const std::string& delimiter = ", ") {
             if (!first) {
                 ss << delimiter;
             } else {
                 first = false;
             }
         };
         // Add configuration key-value pairs
         ss << R"_("configuration": {)_";
         bool firstRow = true;
         for (auto& kvp :
                 ProfileEventSingleton::instance().getDB().getStringMap({"program", "configuration"})) {
             comma(firstRow);
             ss << '"' << kvp.first << R"_(": ")_" << Tools::cleanJsonOut(kvp.second) << '"';
         }
         ss << '}';
         return ss;
     }