souffle: souffle::MinimiseProgramTransformer::NormalisedClauseRepr Class Reference
souffle::MinimiseProgramTransformer::NormalisedClauseRepr Class Reference
Data Structures
struct NormalisedClauseElementRepr
Public Member Functions
const std::set< std::string > & getConstants () const
const std::vector< NormalisedClauseElementRepr > & getElements () const
const std::set< std::string > & getVariables () const
bool isFullyNormalised () const
NormalisedClauseRepr (const AstClause *clause)
Private Member Functions
void addClauseAtom (std::string qualifier, const AstAtom *atom)
Parse an atom with a preset name qualifier into the element list.
void addClauseBodyLiteral (const AstLiteral *lit)
Parse a body literal into the element list.
std::string normaliseArgument (const AstArgument *arg)
Return a normalised string repr of an argument.
Private Attributes
std::vector< NormalisedClauseElementRepr > clauseElements
std::set< std::string > constants {}
bool fullyNormalised {true}
std::set< std::string > variables {}
Detailed Description
Definition at line 56 of file MinimiseProgram.cpp.
Constructor & Destructor Documentation
NormalisedClauseRepr()
souffle::MinimiseProgramTransformer::NormalisedClauseRepr::NormalisedClauseRepr (const AstClause * clause) inline
Definition at line 63 of file MinimiseProgram.cpp.
References addClauseBodyLiteral(), clauseElements, souffle::AstAtom::getArguments(), souffle::AstClause::getBodyLiterals(), souffle::AstClause::getHead(), souffle::MinimiseProgramTransformer::NormalisedClauseRepr::NormalisedClauseElementRepr::name, and normaliseArgument().
Referenced by souffle::MinimiseProgramTransformer::areBijectivelyEquivalent().
{
         // head
         AstQualifiedName name("min:head");
         std::vector<std::string> headVars;
         for (const auto* arg : clause->getHead()->getArguments()) {
             headVars.push_back(normaliseArgument(arg));
         }
         clauseElements.push_back({.name = name, .params = headVars});
         // body
         for (const auto* lit : clause->getBodyLiterals()) {
             addClauseBodyLiteral(lit);
         }
     }
Member Function Documentation
addClauseAtom()
void souffle::MinimiseProgramTransformer::NormalisedClauseRepr::addClauseAtom (std::string qualifier, const AstAtom * atom) private
Parse an atom with a preset name qualifier into the element list.
Definition at line 116 of file MinimiseProgram.cpp.
References clauseElements, souffle::AstAtom::getArguments(), souffle::AstAtom::getQualifiedName(), souffle::MinimiseProgramTransformer::NormalisedClauseRepr::NormalisedClauseElementRepr::name, normaliseArgument(), and souffle::AstQualifiedName::prepend().
Referenced by addClauseBodyLiteral().
{
     AstQualifiedName name(atom->getQualifiedName());
     name.prepend(qualifier);
     std::vector<std::string> vars;
     for (const auto* arg : atom->getArguments()) {
         vars.push_back(normaliseArgument(arg));
     }
     clauseElements.push_back({.name = name, .params = vars});
 }
addClauseBodyLiteral()
void souffle::MinimiseProgramTransformer::NormalisedClauseRepr::addClauseBodyLiteral (const AstLiteral * lit) private
Parse a body literal into the element list.
Definition at line 128 of file MinimiseProgram.cpp.
References addClauseAtom(), clauseElements, fullyNormalised, souffle::MinimiseProgramTransformer::NormalisedClauseRepr::NormalisedClauseElementRepr::name, normaliseArgument(), souffle::AstQualifiedName::prepend(), souffle::toBinaryConstraintSymbol(), and souffle::toString().
Referenced by NormalisedClauseRepr().
{
     if (const auto* atom = dynamic_cast<const AstAtom*>(lit)) {
         addClauseAtom("@min:atom", atom);
     } else if (const auto* neg = dynamic_cast<const AstNegation*>(lit)) {
         addClauseAtom("@min:neg", neg->getAtom());
     } else if (const auto* bc = dynamic_cast<const AstBinaryConstraint*>(lit)) {
         AstQualifiedName name(toBinaryConstraintSymbol(bc->getOperator()));
         name.prepend("@min:operator");
         std::vector<std::string> vars;
         vars.push_back(normaliseArgument(bc->getLHS()));
         vars.push_back(normaliseArgument(bc->getRHS()));
         clauseElements.push_back({.name = name, .params = vars});
     } else {
         fullyNormalised = false;
         AstQualifiedName name(toString(*lit));
         name.prepend("@min:unhandled:lit");
         clauseElements.push_back({.name = name, .params = std::vector<std::string>()});
     }
 }
getConstants()
const std::set<std::string>& souffle::MinimiseProgramTransformer::NormalisedClauseRepr::getConstants () const inline
Definition at line 86 of file MinimiseProgram.cpp.
References constants.
Referenced by souffle::MinimiseProgramTransformer::areBijectivelyEquivalent(), and souffle::MinimiseProgramTransformer::isValidPermutation().
{
         return constants;
     }
getElements()
const std::vector<NormalisedClauseElementRepr>& souffle::MinimiseProgramTransformer::NormalisedClauseRepr::getElements () const inline
Definition at line 90 of file MinimiseProgram.cpp.
References clauseElements.
Referenced by souffle::MinimiseProgramTransformer::areBijectivelyEquivalent(), and souffle::MinimiseProgramTransformer::isValidPermutation().
{
         return clauseElements;
     }
getVariables()
const std::set<std::string>& souffle::MinimiseProgramTransformer::NormalisedClauseRepr::getVariables () const inline
Definition at line 82 of file MinimiseProgram.cpp.
References variables.
Referenced by souffle::MinimiseProgramTransformer::areBijectivelyEquivalent(), and souffle::MinimiseProgramTransformer::isValidPermutation().
{
         return variables;
     }
isFullyNormalised()
bool souffle::MinimiseProgramTransformer::NormalisedClauseRepr::isFullyNormalised () const inline
Definition at line 78 of file MinimiseProgram.cpp.
References fullyNormalised.
Referenced by souffle::MinimiseProgramTransformer::areBijectivelyEquivalent().
{
         return fullyNormalised;
     }
normaliseArgument()
std::string souffle::MinimiseProgramTransformer::NormalisedClauseRepr::normaliseArgument (const AstArgument * arg) private
Return a normalised string repr of an argument.
Definition at line 148 of file MinimiseProgram.cpp.
References constants, fullyNormalised, souffle::MinimiseProgramTransformer::NormalisedClauseRepr::NormalisedClauseElementRepr::name, and variables.
Referenced by addClauseAtom(), addClauseBodyLiteral(), and NormalisedClauseRepr().
{
     if (auto* stringCst = dynamic_cast<const AstStringConstant*>(arg)) {
         std::stringstream name;
         name << "@min:cst:str" << *stringCst;
         constants.insert(name.str());
         return name.str();
     } else if (auto* numericCst = dynamic_cast<const AstNumericConstant*>(arg)) {
         std::stringstream name;
         name << "@min:cst:num:" << *numericCst;
         constants.insert(name.str());
         return name.str();
     } else if (dynamic_cast<const AstNilConstant*>(arg) != nullptr) {
         constants.insert("@min:cst:nil");
         return "@min:cst:nil";
     } else if (auto* var = dynamic_cast<const AstVariable*>(arg)) {
         auto name = var->getName();
         variables.insert(name);
         return name;
     } else if (dynamic_cast<const AstUnnamedVariable*>(arg)) {
         static size_t countUnnamed = 0;
         std::stringstream name;
         name << "@min:unnamed:" << countUnnamed++;
         variables.insert(name.str());
         return name.str();
     } else {
         fullyNormalised = false;
         return "@min:unhandled:arg";
     }
 }
Field Documentation
clauseElements
std::vector<NormalisedClauseElementRepr> souffle::MinimiseProgramTransformer::NormalisedClauseRepr::clauseElements private
Definition at line 98 of file MinimiseProgram.cpp.
Referenced by addClauseAtom(), addClauseBodyLiteral(), getElements(), and NormalisedClauseRepr().
constants
std::set<std::string> souffle::MinimiseProgramTransformer::NormalisedClauseRepr::constants {} private
Definition at line 97 of file MinimiseProgram.cpp.
Referenced by getConstants(), and normaliseArgument().
fullyNormalised
bool souffle::MinimiseProgramTransformer::NormalisedClauseRepr::fullyNormalised {true} private
Definition at line 95 of file MinimiseProgram.cpp.
Referenced by addClauseBodyLiteral(), isFullyNormalised(), and normaliseArgument().
variables
std::set<std::string> souffle::MinimiseProgramTransformer::NormalisedClauseRepr::variables {} private
Definition at line 96 of file MinimiseProgram.cpp.
Referenced by getVariables(), and normaliseArgument().
The documentation for this class was generated from the following file:
ast/transform/MinimiseProgram.cpp