souffle: souffle::WriteStreamSQLite Class Reference
souffle::WriteStreamSQLite Class Reference
#include <WriteStreamSQLite.h>
Public Member Functions
WriteStreamSQLite (const std::map< std::string, std::string > &rwOperation, const SymbolTable &symbolTable, const RecordTable &recordTable)
~WriteStreamSQLite () override
Public Member Functions inherited from souffle::WriteStream
template<typename T >
void writeAll (const T &relation)
template<>
void writeNext (const RamDomain *tuple)
template<typename T >
void writeSize (const T &relation)
WriteStream (const std::map< std::string, std::string > &rwOperation, const SymbolTable &symbolTable, const RecordTable &recordTable)
Public Member Functions inherited from souffle::SerialisationStream< true >
virtual ~SerialisationStream ()=default
Protected Member Functions
void writeNextTuple (const RamDomain *tuple) override
void writeNullary () override
Protected Member Functions inherited from souffle::WriteStream
void outputRecord (std::ostream &destination, const RamDomain value, const std::string &name)
template<typename Tuple >
void writeNext (const Tuple tuple)
virtual void writeSize (std::size_t)
Protected Member Functions inherited from souffle::SerialisationStream< true >
SerialisationStream (RO< SymbolTable > &symTab, RO< RecordTable > &recTab, Json types, std::vector< std::string > relTypes, size_t auxArity=0)
SerialisationStream (RO< SymbolTable > &symTab, RO< RecordTable > &recTab, Json types)
SerialisationStream (RO< SymbolTable > &symTab, RO< RecordTable > &recTab, const std::map< std::string, std::string > &rwOperation)
Private Member Functions
void createRelationTable ()
void createRelationView ()
void createSymbolTable ()
void createTables ()
void executeSQL (const std::string &sql, sqlite3 *db)
uint64_t getSymbolTableID (int index)
uint64_t getSymbolTableIDFromDB (int index)
void openDB ()
void prepareInsertStatement ()
void prepareStatements ()
void prepareSymbolInsertStatement ()
void prepareSymbolSelectStatement ()
void throwError (const std::string &message)
Static Private Member Functions
static std::string getFileName (const std::map< std::string, std::string > &rwOperation)
Return given filename or construct from relation name.
Private Attributes
sqlite3 * db = nullptr
const std::string dbFilename
std::unordered_map< uint64_t, uint64_t > dbSymbolTable
sqlite3_stmt * insertStatement = nullptr
const std::string relationName
sqlite3_stmt * symbolInsertStatement = nullptr
sqlite3_stmt * symbolSelectStatement = nullptr
const std::string symbolTableName = "__SymbolTable"
Additional Inherited Members
Protected Types inherited from souffle::SerialisationStream< true >
using RO = std::conditional_t< readOnlyTables, const A, A >
Protected Attributes inherited from souffle::WriteStream
const bool summary
Protected Attributes inherited from souffle::SerialisationStream< true >
size_t arity
size_t auxiliaryArity
RO< RecordTable > & recordTable
RO< SymbolTable > & symbolTable
std::vector< std::string > typeAttributes
Json types
Detailed Description
Definition at line 36 of file WriteStreamSQLite.h.
Constructor & Destructor Documentation
WriteStreamSQLite()
souffle::WriteStreamSQLite::WriteStreamSQLite (const std::map< std::string, std::string > & rwOperation, const SymbolTable & symbolTable, const RecordTable & recordTable) inline
Definition at line 38 of file WriteStreamSQLite.h.
References createTables(), openDB(), and prepareStatements().
             : WriteStream(rwOperation, symbolTable, recordTable), dbFilename(getFileName(rwOperation)),
               relationName(rwOperation.at("name")) {
         openDB();
         createTables();
         prepareStatements();
         //        executeSQL("BEGIN TRANSACTION", db);
     }
~WriteStreamSQLite()
souffle::WriteStreamSQLite::~WriteStreamSQLite () inline override
Definition at line 48 of file WriteStreamSQLite.h.
References db, insertStatement, symbolInsertStatement, and symbolSelectStatement.
{
         sqlite3_finalize(insertStatement);
         sqlite3_finalize(symbolInsertStatement);
         sqlite3_finalize(symbolSelectStatement);
         sqlite3_close(db);
     }
Member Function Documentation
createRelationTable()
void souffle::WriteStreamSQLite::createRelationTable () inline private
Definition at line 196 of file WriteStreamSQLite.h.
References souffle::SerialisationStream< true >::arity, db, executeSQL(), i, and relationName.
Referenced by createTables().
{
         std::stringstream createTableText;
         createTableText << "CREATE TABLE IF NOT EXISTS '_" << relationName << "' (";
         if (arity > 0) {
             createTableText << "'0' INTEGER";
             for (unsigned int i = 1; i < arity; i++) {
                 createTableText << ",'" << std::to_string(i) << "' ";
                 createTableText << "INTEGER";
             }
         }
         createTableText << ");";
         executeSQL(createTableText.str(), db);
         executeSQL("DELETE FROM '_" + relationName + "';", db);
     }
createRelationView()
void souffle::WriteStreamSQLite::createRelationView () inline private
Definition at line 211 of file WriteStreamSQLite.h.
References souffle::SerialisationStream< true >::arity, db, executeSQL(), i, relationName, symbolTableName, and souffle::SerialisationStream< true >::typeAttributes.
Referenced by createTables().
{
         // Create view with symbol strings resolved
         std::stringstream createViewText;
         createViewText << "CREATE VIEW IF NOT EXISTS '" << relationName << "' AS ";
         std::stringstream projectionClause;
         std::stringstream fromClause;
         fromClause << "'_" << relationName << "'";
         std::stringstream whereClause;
         bool firstWhere = true;
         for (unsigned int i = 0; i < arity; i++) {
             std::string columnName = std::to_string(i);
             if (i != 0) {
                 projectionClause << ",";
             }
             if (typeAttributes.at(i)[0] == 's') {
                 projectionClause << "'_symtab_" << columnName << "'.symbol AS '" << columnName << "'";
                 fromClause << ",'" << symbolTableName << "' AS '_symtab_" << columnName << "'";
                 if (!firstWhere) {
                     whereClause << " AND ";
                 } else {
                     firstWhere = false;
                 }
                 whereClause << "'_" << relationName << "'.'" << columnName << "' = "
                             << "'_symtab_" << columnName << "'.id";
             } else {
                 projectionClause << "'_" << relationName << "'.'" << columnName << "'";
             }
         }
         createViewText << "SELECT " << projectionClause.str() << " FROM " << fromClause.str();
         if (!firstWhere) {
             createViewText << " WHERE " << whereClause.str();
         }
         createViewText << ";";
         executeSQL(createViewText.str(), db);
     }
createSymbolTable()
void souffle::WriteStreamSQLite::createSymbolTable () inline private
Definition at line 246 of file WriteStreamSQLite.h.
References db, executeSQL(), and symbolTableName.
Referenced by createTables().
{
         std::stringstream createTableText;
         createTableText << "CREATE TABLE IF NOT EXISTS '" << symbolTableName << "' ";
         createTableText << "(id INTEGER PRIMARY KEY, symbol TEXT UNIQUE);";
         executeSQL(createTableText.str(), db);
     }
createTables()
void souffle::WriteStreamSQLite::createTables () inline private
Definition at line 190 of file WriteStreamSQLite.h.
References createRelationTable(), createRelationView(), and createSymbolTable().
Referenced by WriteStreamSQLite().
{
         createRelationTable();
         createRelationView();
         createSymbolTable();
     }
executeSQL()
void souffle::WriteStreamSQLite::executeSQL (const std::string & sql, sqlite3 * db) inline private
Definition at line 83 of file WriteStreamSQLite.h.
Referenced by createRelationTable(), createRelationView(), createSymbolTable(), and openDB().
{
         assert(db && "Database connection is closed");
         char* errorMessage = nullptr;
         /* Execute SQL statement */
         int rc = sqlite3_exec(db, sql.c_str(), nullptr, nullptr, &errorMessage);
         if (rc != SQLITE_OK) {
             std::stringstream error;
             error << "SQLite error in sqlite3_exec: " << sqlite3_errmsg(db) << "\n";
             error << "SQL error: " << errorMessage << "\n";
             error << "SQL: " << sql << "\n";
             sqlite3_free(errorMessage);
             throw std::invalid_argument(error.str());
         }
     }
getFileName()
static std::string souffle::WriteStreamSQLite::getFileName (const std::map< std::string, std::string > & rwOperation) inline static private
Return given filename or construct from relation name.
Default name is [configured path]/[relation name].sqlite
Parameters
rwOperation map of IO configuration options
Returns
input filename
Definition at line 260 of file WriteStreamSQLite.h.
References souffle::getOr().
{
         // legacy support for SQLite prior to 2020-03-18
         // convert dbname to filename
         auto name = getOr(rwOperation, "dbname", rwOperation.at("name") + ".sqlite");
         name = getOr(rwOperation, "filename", name);
         if (name.front() != '/') {
             name = getOr(rwOperation, "output-dir", ".") + "/" + name;
         }
         return name;
     }
getSymbolTableID()
uint64_t souffle::WriteStreamSQLite::getSymbolTableID (int index) inline private
Definition at line 118 of file WriteStreamSQLite.h.
References db, dbSymbolTable, getSymbolTableIDFromDB(), symbolInsertStatement, souffle::SerialisationStream< true >::symbolTable, and throwError().
Referenced by writeNextTuple().
{
         if (dbSymbolTable.count(index) != 0) {
             return dbSymbolTable[index];
         }
         if (sqlite3_bind_text(symbolInsertStatement, 1, symbolTable.unsafeResolve(index).c_str(), -1,
                     SQLITE_TRANSIENT) != SQLITE_OK) {
             throwError("SQLite error in sqlite3_bind_text: ");
         }
         // Either the insert succeeds and we have a new row id or it already exists and a select is needed.
         uint64_t rowid;
         if (sqlite3_step(symbolInsertStatement) != SQLITE_DONE) {
             // The symbol already exists so select it.
             rowid = getSymbolTableIDFromDB(index);
         } else {
             rowid = sqlite3_last_insert_rowid(db);
         }
         sqlite3_clear_bindings(symbolInsertStatement);
         sqlite3_reset(symbolInsertStatement);
         dbSymbolTable[index] = rowid;
         return rowid;
     }
getSymbolTableIDFromDB()
uint64_t souffle::WriteStreamSQLite::getSymbolTableIDFromDB (int index) inline private
Definition at line 105 of file WriteStreamSQLite.h.
References symbolSelectStatement, souffle::SerialisationStream< true >::symbolTable, and throwError().
Referenced by getSymbolTableID().
{
         if (sqlite3_bind_text(symbolSelectStatement, 1, symbolTable.unsafeResolve(index).c_str(), -1,
                     SQLITE_TRANSIENT) != SQLITE_OK) {
             throwError("SQLite error in sqlite3_bind_text: ");
         }
         if (sqlite3_step(symbolSelectStatement) != SQLITE_ROW) {
             throwError("SQLite error in sqlite3_step: ");
         }
         uint64_t rowid = sqlite3_column_int64(symbolSelectStatement, 0);
         sqlite3_clear_bindings(symbolSelectStatement);
         sqlite3_reset(symbolSelectStatement);
         return rowid;
     }
openDB()
void souffle::WriteStreamSQLite::openDB () inline private
Definition at line 142 of file WriteStreamSQLite.h.
References db, dbFilename, executeSQL(), and throwError().
Referenced by WriteStreamSQLite().
                   {
         if (sqlite3_open(dbFilename.c_str(), &db) != SQLITE_OK) {
             throwError("SQLite error in sqlite3_open");
         }
         sqlite3_extended_result_codes(db, 1);
         executeSQL("PRAGMA synchronous = OFF", db);
         executeSQL("PRAGMA journal_mode = MEMORY", db);
     }
prepareInsertStatement()
void souffle::WriteStreamSQLite::prepareInsertStatement () inline private
Definition at line 176 of file WriteStreamSQLite.h.
References souffle::SerialisationStream< true >::arity, db, i, insertStatement, relationName, and throwError().
Referenced by prepareStatements().
{
         std::stringstream insertSQL;
         insertSQL << "INSERT INTO '_" << relationName << "' VALUES ";
         insertSQL << "(@V0";
         for (unsigned int i = 1; i < arity; i++) {
             insertSQL << ",@V" << i;
         }
         insertSQL << ");";
         const char* tail = nullptr;
         if (sqlite3_prepare_v2(db, insertSQL.str().c_str(), -1, &insertStatement, &tail) != SQLITE_OK) {
             throwError("SQLite error in sqlite3_prepare_v2: ");
         }
     }
prepareStatements()
void souffle::WriteStreamSQLite::prepareStatements () inline private
Definition at line 151 of file WriteStreamSQLite.h.
References prepareInsertStatement(), prepareSymbolInsertStatement(), and prepareSymbolSelectStatement().
Referenced by WriteStreamSQLite().
{
         prepareInsertStatement();
         prepareSymbolInsertStatement();
         prepareSymbolSelectStatement();
     }
prepareSymbolInsertStatement()
void souffle::WriteStreamSQLite::prepareSymbolInsertStatement () inline private
Definition at line 156 of file WriteStreamSQLite.h.
References db, symbolInsertStatement, symbolTableName, and throwError().
Referenced by prepareStatements().
{
         std::stringstream insertSQL;
         insertSQL << "INSERT INTO " << symbolTableName;
         insertSQL << " VALUES(null,@V0);";
         const char* tail = nullptr;
         if (sqlite3_prepare_v2(db, insertSQL.str().c_str(), -1, &symbolInsertStatement, &tail) != SQLITE_OK) {
             throwError("SQLite error in sqlite3_prepare_v2: ");
         }
     }
prepareSymbolSelectStatement()
void souffle::WriteStreamSQLite::prepareSymbolSelectStatement () inline private
Definition at line 166 of file WriteStreamSQLite.h.
References db, symbolSelectStatement, symbolTableName, and throwError().
Referenced by prepareStatements().
{
         std::stringstream selectSQL;
         selectSQL << "SELECT id FROM " << symbolTableName;
         selectSQL << " WHERE symbol = @V0;";
         const char* tail = nullptr;
         if (sqlite3_prepare_v2(db, selectSQL.str().c_str(), -1, &symbolSelectStatement, &tail) != SQLITE_OK) {
             throwError("SQLite error in sqlite3_prepare_v2: ");
         }
     }
throwError()
void souffle::WriteStreamSQLite::throwError (const std::string & message) inline private
Definition at line 99 of file WriteStreamSQLite.h.
References db.
Referenced by getSymbolTableID(), getSymbolTableIDFromDB(), openDB(), prepareInsertStatement(), prepareSymbolInsertStatement(), prepareSymbolSelectStatement(), and writeNextTuple().
{
         std::stringstream error;
         error << message << sqlite3_errmsg(db) << "\n";
         throw std::invalid_argument(error.str());
     }
writeNextTuple()
void souffle::WriteStreamSQLite::writeNextTuple (const RamDomain * tuple) inline override protected virtual
Implements souffle::WriteStream.
Definition at line 58 of file WriteStreamSQLite.h.
References souffle::SerialisationStream< true >::arity, getSymbolTableID(), i, insertStatement, throwError(), and souffle::SerialisationStream< true >::typeAttributes.
{
         for (size_t i = 0; i < arity; i++) {
             RamDomain value = 0;  // Silence warning
             switch (typeAttributes.at(i)[0]) {
                 case 's': value = getSymbolTableID(tuple[i]); break;
                 default: value = tuple[i]; break;
             }
 #if RAM_DOMAIN_SIZE == 64
             if (sqlite3_bind_int64(insertStatement, i + 1, value) != SQLITE_OK) {
 #else
             if (sqlite3_bind_int(insertStatement, i + 1, value) != SQLITE_OK) {
 #endif
                 throwError("SQLite error in sqlite3_bind_text: ");
             }
         }
         if (sqlite3_step(insertStatement) != SQLITE_DONE) {
             throwError("SQLite error in sqlite3_step: ");
         }
         sqlite3_clear_bindings(insertStatement);
         sqlite3_reset(insertStatement);
     }
writeNullary()
void souffle::WriteStreamSQLite::writeNullary () inline override protected virtual
Implements souffle::WriteStream.
Definition at line 56 of file WriteStreamSQLite.h.
 {}
Field Documentation
db
sqlite3* souffle::WriteStreamSQLite::db = nullptr private
Definition at line 280 of file WriteStreamSQLite.h.
Referenced by createRelationTable(), createRelationView(), createSymbolTable(), getSymbolTableID(), openDB(), prepareInsertStatement(), prepareSymbolInsertStatement(), prepareSymbolSelectStatement(), throwError(), and ~WriteStreamSQLite().
dbFilename
const std::string souffle::WriteStreamSQLite::dbFilename private
Definition at line 272 of file WriteStreamSQLite.h.
Referenced by openDB().
dbSymbolTable
std::unordered_map<uint64_t, uint64_t> souffle::WriteStreamSQLite::dbSymbolTable private
Definition at line 276 of file WriteStreamSQLite.h.
Referenced by getSymbolTableID().
insertStatement
sqlite3_stmt* souffle::WriteStreamSQLite::insertStatement = nullptr private
Definition at line 277 of file WriteStreamSQLite.h.
Referenced by prepareInsertStatement(), writeNextTuple(), and ~WriteStreamSQLite().
relationName
const std::string souffle::WriteStreamSQLite::relationName private
Definition at line 273 of file WriteStreamSQLite.h.
Referenced by createRelationTable(), createRelationView(), and prepareInsertStatement().
symbolInsertStatement
sqlite3_stmt* souffle::WriteStreamSQLite::symbolInsertStatement = nullptr private
Definition at line 278 of file WriteStreamSQLite.h.
Referenced by getSymbolTableID(), prepareSymbolInsertStatement(), and ~WriteStreamSQLite().
symbolSelectStatement
sqlite3_stmt* souffle::WriteStreamSQLite::symbolSelectStatement = nullptr private
Definition at line 279 of file WriteStreamSQLite.h.
Referenced by getSymbolTableIDFromDB(), prepareSymbolSelectStatement(), and ~WriteStreamSQLite().
symbolTableName
const std::string souffle::WriteStreamSQLite::symbolTableName = "__SymbolTable" private
Definition at line 274 of file WriteStreamSQLite.h.
Referenced by createRelationView(), createSymbolTable(), prepareSymbolInsertStatement(), and prepareSymbolSelectStatement().
The documentation for this class was generated from the following file:
WriteStreamSQLite.h