souffle: souffle::MetaTransformer Class Reference
souffle::MetaTransformer Class Reference abstract
Transformer that coordinates other sub-transformations.
#include <Meta.h>
Public Member Functions
bool applySubtransformer (AstTranslationUnit &translationUnit, AstTransformer *transformer)
MetaTransformer * clone () const override=0
virtual void disableTransformers (const std::set< std::string > &transforms)=0
virtual std::vector< AstTransformer * > getSubtransformers () const =0
virtual void setDebugReport ()=0
virtual void setVerbosity (bool verbose)=0
Public Member Functions inherited from souffle::AstTransformer
bool apply (AstTranslationUnit &translationUnit)
virtual std::string getName () const =0
virtual ~AstTransformer ()=default
Protected Attributes
bool verbose = false
Detailed Description
Transformer that coordinates other sub-transformations.
Definition at line 31 of file Meta.h.
Member Function Documentation
applySubtransformer()
bool souffle::MetaTransformer::applySubtransformer (AstTranslationUnit & translationUnit, AstTransformer * transformer)
Definition at line 23 of file Meta.cpp.
References souffle::AstTransformer::apply(), souffle::test::count(), souffle::AstTransformer::getName(), souffle::test::now(), and verbose.
Referenced by souffle::DebugReporter::transform(), souffle::FixpointTransformer::transform(), souffle::WhileTransformer::transform(), souffle::ConditionalTransformer::transform(), and souffle::PipelineTransformer::transform().
{
     auto start = std::chrono::high_resolution_clock::now();
     bool changed = transformer->apply(translationUnit);
     auto end = std::chrono::high_resolution_clock::now();
     if (verbose && (dynamic_cast<MetaTransformer*>(transformer) == nullptr)) {
         std::string changedString = changed ? "changed" : "unchanged";
         std::cout << transformer->getName() << " time: " << std::chrono::duration<double>(end - start).count()
                   << "sec [" << changedString << "]" << std::endl;
     }
     return changed;
 }
clone()
MetaTransformer* souffle::MetaTransformer::clone () const override pure virtual
Implements souffle::AstTransformer.
Implemented in souffle::PipelineTransformer, souffle::ConditionalTransformer, souffle::WhileTransformer, souffle::FixpointTransformer, souffle::DebugReporter, and souffle::NullTransformer.
disableTransformers()
virtual void souffle::MetaTransformer::disableTransformers (const std::set< std::string > & transforms) pure virtual
Implemented in souffle::PipelineTransformer, souffle::ConditionalTransformer, souffle::WhileTransformer, souffle::FixpointTransformer, souffle::DebugReporter, and souffle::NullTransformer.
getSubtransformers()
virtual std::vector<AstTransformer*> souffle::MetaTransformer::getSubtransformers () const pure virtual
Implemented in souffle::FixpointTransformer, souffle::PipelineTransformer, souffle::ConditionalTransformer, souffle::WhileTransformer, souffle::DebugReporter, and souffle::NullTransformer.
setDebugReport()
virtual void souffle::MetaTransformer::setDebugReport () pure virtual
Implemented in souffle::PipelineTransformer, souffle::ConditionalTransformer, souffle::WhileTransformer, souffle::DebugReporter, souffle::NullTransformer, and souffle::FixpointTransformer.
setVerbosity()
virtual void souffle::MetaTransformer::setVerbosity (bool verbose) pure virtual
Implemented in souffle::PipelineTransformer, souffle::ConditionalTransformer, souffle::WhileTransformer, souffle::FixpointTransformer, souffle::DebugReporter, and souffle::NullTransformer.
Field Documentation
verbose
bool souffle::MetaTransformer::verbose = false protected
Definition at line 33 of file Meta.h.
Referenced by applySubtransformer(), souffle::DebugReporter::setVerbosity(), souffle::FixpointTransformer::setVerbosity(), souffle::WhileTransformer::setVerbosity(), souffle::ConditionalTransformer::setVerbosity(), and souffle::PipelineTransformer::setVerbosity().
The documentation for this class was generated from the following files:
ast/transform/Meta.h
ast/transform/Meta.cpp