souffle: souffle::InterpreterIndex Class Reference
souffle::InterpreterIndex Class Reference abstract
An index is an abstraction of a data structure.
#include <InterpreterIndex.h>
Public Member Functions
virtual void clear ()=0
Clears the content of this index, turning it empty.
virtual bool contains (const TupleRef &tuple) const =0
Tests whether the given tuple is present in this index or not.
virtual bool contains (const TupleRef &low, const TupleRef &high) const =0
Tests whether this index contains any tuple within the given bounds.
virtual IndexViewPtr createView () const =0
Requests the creation of a view on this index.
virtual bool empty () const =0
Tests whether this index is empty or not.
virtual void extend (InterpreterIndex *)
Extend another index.
virtual size_t getArity () const =0
Obtains the arity of the given index.
virtual bool insert (const TupleRef &tuple)=0
Inserts a tuple into this index.
virtual void insert (const InterpreterIndex &src)=0
Inserts all elements of the given index.
virtual PartitionedStream partitionRange (const TupleRef &low, const TupleRef &high, int partitionCount) const =0
Returns a partitioned stream covering elements in the range [low,high)
virtual PartitionedStream partitionScan (int partitionCount) const =0
Returns a partitioned stream covering the entire index content.
virtual Stream range (const TupleRef &low, const TupleRef &high) const =0
Returns a stream covering elements in the range [low,high)
virtual Stream scan () const =0
Returns a stream covering the entire index content.
virtual std::size_t size () const =0
Obtains the number of elements stored in this index.
virtual ~InterpreterIndex ()=default
Detailed Description
An index is an abstraction of a data structure.
Definition at line 393 of file InterpreterIndex.h.
Constructor & Destructor Documentation
~InterpreterIndex()
virtual souffle::InterpreterIndex::~InterpreterIndex () virtual default
Member Function Documentation
clear()
virtual void souffle::InterpreterIndex::clear () pure virtual
Clears the content of this index, turning it empty.
Implemented in souffle::IndirectIndex, souffle::GenericIndex< Structure >, souffle::GenericIndex< EquivalenceRelation< t_tuple< 2 > > >, souffle::GenericIndex< Trie< Arity > >, souffle::GenericIndex< btree_set< t_tuple< Arity >, comparator< Arity > > >, souffle::GenericIndex< btree_set< t_tuple< Arity >, comparator< Arity >, std::allocator< t_tuple< Arity > >, 256, detail::default_strategy< t_tuple< Arity > >::type, comparator< Arity - 2 >, InterpreterProvenanceUpdater< Arity > > >, and souffle::NullaryIndex.
contains() [1/2]
virtual bool souffle::InterpreterIndex::contains (const TupleRef & tuple) const pure virtual
Tests whether the given tuple is present in this index or not.
Implemented in souffle::IndirectIndex, souffle::GenericIndex< Structure >, souffle::GenericIndex< EquivalenceRelation< t_tuple< 2 > > >, souffle::GenericIndex< Trie< Arity > >, souffle::GenericIndex< btree_set< t_tuple< Arity >, comparator< Arity > > >, souffle::GenericIndex< btree_set< t_tuple< Arity >, comparator< Arity >, std::allocator< t_tuple< Arity > >, 256, detail::default_strategy< t_tuple< Arity > >::type, comparator< Arity - 2 >, InterpreterProvenanceUpdater< Arity > > >, and souffle::NullaryIndex.
Referenced by souffle::InterpreterRelation::contains(), souffle::InterpreterRelation::exists(), and souffle::InterpreterIndirectRelation::insert().
contains() [2/2]
virtual bool souffle::InterpreterIndex::contains (const TupleRef & low, const TupleRef & high) const pure virtual
Tests whether this index contains any tuple within the given bounds.
Implemented in souffle::IndirectIndex, souffle::GenericIndex< Structure >, souffle::GenericIndex< EquivalenceRelation< t_tuple< 2 > > >, souffle::GenericIndex< Trie< Arity > >, souffle::GenericIndex< btree_set< t_tuple< Arity >, comparator< Arity > > >, souffle::GenericIndex< btree_set< t_tuple< Arity >, comparator< Arity >, std::allocator< t_tuple< Arity > >, 256, detail::default_strategy< t_tuple< Arity > >::type, comparator< Arity - 2 >, InterpreterProvenanceUpdater< Arity > > >, and souffle::NullaryIndex.
createView()
virtual IndexViewPtr souffle::InterpreterIndex::createView () const pure virtual
Requests the creation of a view on this index.
Implemented in souffle::IndirectIndex, souffle::GenericIndex< Structure >, souffle::GenericIndex< EquivalenceRelation< t_tuple< 2 > > >, souffle::GenericIndex< Trie< Arity > >, souffle::GenericIndex< btree_set< t_tuple< Arity >, comparator< Arity > > >, souffle::GenericIndex< btree_set< t_tuple< Arity >, comparator< Arity >, std::allocator< t_tuple< Arity > >, 256, detail::default_strategy< t_tuple< Arity > >::type, comparator< Arity - 2 >, InterpreterProvenanceUpdater< Arity > > >, and souffle::NullaryIndex.
empty()
virtual bool souffle::InterpreterIndex::empty () const pure virtual
Tests whether this index is empty or not.
Implemented in souffle::IndirectIndex, souffle::GenericIndex< Structure >, souffle::GenericIndex< EquivalenceRelation< t_tuple< 2 > > >, souffle::GenericIndex< Trie< Arity > >, souffle::GenericIndex< btree_set< t_tuple< Arity >, comparator< Arity > > >, souffle::GenericIndex< btree_set< t_tuple< Arity >, comparator< Arity >, std::allocator< t_tuple< Arity > >, 256, detail::default_strategy< t_tuple< Arity > >::type, comparator< Arity - 2 >, InterpreterProvenanceUpdater< Arity > > >, and souffle::NullaryIndex.
Referenced by souffle::InterpreterRelation::empty(), and souffle::NullaryIndex::insert().
extend()
virtual void souffle::InterpreterIndex::extend (InterpreterIndex *) inline virtual
Extend another index.
This should only affect on an EqrelIndex. Extend this index with another index, expanding this equivalence relation. The supplied relation is the old knowledge, whilst this relation only contains explicitly new knowledge. After this operation the "implicitly new tuples" are now explicitly inserted this relation.
Reimplemented in souffle::EqrelIndex.
Definition at line 472 of file InterpreterIndex.h.
Referenced by souffle::InterpreterEqRelation::extend().
 {}
getArity()
virtual size_t souffle::InterpreterIndex::getArity () const pure virtual
Obtains the arity of the given index.
Implemented in souffle::IndirectIndex, souffle::GenericIndex< Structure >, souffle::GenericIndex< EquivalenceRelation< t_tuple< 2 > > >, souffle::GenericIndex< Trie< Arity > >, souffle::GenericIndex< btree_set< t_tuple< Arity >, comparator< Arity > > >, souffle::GenericIndex< btree_set< t_tuple< Arity >, comparator< Arity >, std::allocator< t_tuple< Arity > >, 256, detail::default_strategy< t_tuple< Arity > >::type, comparator< Arity - 2 >, InterpreterProvenanceUpdater< Arity > > >, and souffle::NullaryIndex.
Referenced by souffle::NullaryIndex::insert().
insert() [1/2]
virtual bool souffle::InterpreterIndex::insert (const TupleRef & tuple) pure virtual
Inserts a tuple into this index.
Implemented in souffle::IndirectIndex, souffle::GenericIndex< Structure >, souffle::GenericIndex< EquivalenceRelation< t_tuple< 2 > > >, souffle::GenericIndex< Trie< Arity > >, souffle::GenericIndex< btree_set< t_tuple< Arity >, comparator< Arity > > >, souffle::GenericIndex< btree_set< t_tuple< Arity >, comparator< Arity >, std::allocator< t_tuple< Arity > >, 256, detail::default_strategy< t_tuple< Arity > >::type, comparator< Arity - 2 >, InterpreterProvenanceUpdater< Arity > > >, and souffle::NullaryIndex.
Referenced by souffle::InterpreterRelation::insert().
insert() [2/2]
virtual void souffle::InterpreterIndex::insert (const InterpreterIndex & src) pure virtual
Inserts all elements of the given index.
Implemented in souffle::IndirectIndex, souffle::GenericIndex< Structure >, souffle::GenericIndex< EquivalenceRelation< t_tuple< 2 > > >, souffle::GenericIndex< Trie< Arity > >, souffle::GenericIndex< btree_set< t_tuple< Arity >, comparator< Arity > > >, souffle::GenericIndex< btree_set< t_tuple< Arity >, comparator< Arity >, std::allocator< t_tuple< Arity > >, 256, detail::default_strategy< t_tuple< Arity > >::type, comparator< Arity - 2 >, InterpreterProvenanceUpdater< Arity > > >, and souffle::NullaryIndex.
partitionRange()
virtual PartitionedStream souffle::InterpreterIndex::partitionRange (const TupleRef & low, const TupleRef & high, int partitionCount) const pure virtual
Returns a partitioned stream covering elements in the range [low,high)
Implemented in souffle::IndirectIndex, souffle::GenericIndex< Structure >, souffle::GenericIndex< EquivalenceRelation< t_tuple< 2 > > >, souffle::GenericIndex< Trie< Arity > >, souffle::GenericIndex< btree_set< t_tuple< Arity >, comparator< Arity > > >, souffle::GenericIndex< btree_set< t_tuple< Arity >, comparator< Arity >, std::allocator< t_tuple< Arity > >, 256, detail::default_strategy< t_tuple< Arity > >::type, comparator< Arity - 2 >, InterpreterProvenanceUpdater< Arity > > >, and souffle::NullaryIndex.
partitionScan()
virtual PartitionedStream souffle::InterpreterIndex::partitionScan (int partitionCount) const pure virtual
Returns a partitioned stream covering the entire index content.
Implemented in souffle::IndirectIndex, souffle::GenericIndex< Structure >, souffle::GenericIndex< EquivalenceRelation< t_tuple< 2 > > >, souffle::GenericIndex< Trie< Arity > >, souffle::GenericIndex< btree_set< t_tuple< Arity >, comparator< Arity > > >, souffle::GenericIndex< btree_set< t_tuple< Arity >, comparator< Arity >, std::allocator< t_tuple< Arity > >, 256, detail::default_strategy< t_tuple< Arity > >::type, comparator< Arity - 2 >, InterpreterProvenanceUpdater< Arity > > >, and souffle::NullaryIndex.
Referenced by souffle::InterpreterRelation::partitionScan().
range()
virtual Stream souffle::InterpreterIndex::range (const TupleRef & low, const TupleRef & high) const pure virtual
Returns a stream covering elements in the range [low,high)
Implemented in souffle::IndirectIndex, souffle::GenericIndex< Structure >, souffle::GenericIndex< EquivalenceRelation< t_tuple< 2 > > >, souffle::GenericIndex< Trie< Arity > >, souffle::GenericIndex< btree_set< t_tuple< Arity >, comparator< Arity > > >, souffle::GenericIndex< btree_set< t_tuple< Arity >, comparator< Arity >, std::allocator< t_tuple< Arity > >, 256, detail::default_strategy< t_tuple< Arity > >::type, comparator< Arity - 2 >, InterpreterProvenanceUpdater< Arity > > >, and souffle::NullaryIndex.
scan()
virtual Stream souffle::InterpreterIndex::scan () const pure virtual
Returns a stream covering the entire index content.
Implemented in souffle::IndirectIndex, souffle::GenericIndex< Structure >, souffle::GenericIndex< EquivalenceRelation< t_tuple< 2 > > >, souffle::GenericIndex< Trie< Arity > >, souffle::GenericIndex< btree_set< t_tuple< Arity >, comparator< Arity > > >, souffle::GenericIndex< btree_set< t_tuple< Arity >, comparator< Arity >, std::allocator< t_tuple< Arity > >, 256, detail::default_strategy< t_tuple< Arity > >::type, comparator< Arity - 2 >, InterpreterProvenanceUpdater< Arity > > >, and souffle::NullaryIndex.
Referenced by souffle::GenericIndex< btree_set< t_tuple< Arity >, comparator< Arity >, std::allocator< t_tuple< Arity > >, 256, detail::default_strategy< t_tuple< Arity > >::type, comparator< Arity - 2 >, InterpreterProvenanceUpdater< Arity > > >::insert(), souffle::IndirectIndex::insert(), and souffle::InterpreterRelation::scan().
size()
virtual std::size_t souffle::InterpreterIndex::size () const pure virtual
Obtains the number of elements stored in this index.
Implemented in souffle::IndirectIndex, souffle::GenericIndex< Structure >, souffle::GenericIndex< EquivalenceRelation< t_tuple< 2 > > >, souffle::GenericIndex< Trie< Arity > >, souffle::GenericIndex< btree_set< t_tuple< Arity >, comparator< Arity > > >, souffle::GenericIndex< btree_set< t_tuple< Arity >, comparator< Arity >, std::allocator< t_tuple< Arity > >, 256, detail::default_strategy< t_tuple< Arity > >::type, comparator< Arity - 2 >, InterpreterProvenanceUpdater< Arity > > >, and souffle::NullaryIndex.
Referenced by souffle::InterpreterRelation::size().
The documentation for this class was generated from the following file:
interpreter/InterpreterIndex.h