souffle: souffle::RamListStatement Class Reference
souffle::RamListStatement Class Reference
Abstract class for a list of RAM statements.
#include <Statement.h>
Public Member Functions
void apply (const RamNodeMapper &map) override
Apply the mapper to all child nodes.
std::vector< const RamNode * > getChildNodes () const override
Obtain list of all embedded child nodes.
std::vector< RamStatement * > getStatements () const
Get statements.
RamListStatement ()=default
RamListStatement (std::vector< std::unique_ptr< RamStatement >> statements)
template<typename... Stmts>
RamListStatement (std::unique_ptr< Stmts > &&... stmts)
Public Member Functions inherited from souffle::RamStatement
RamStatement * clone () const override=0
Create a clone (i.e.
Public Member Functions inherited from souffle::RamNode
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
virtual void rewrite (const RamNode *oldNode, std::unique_ptr< RamNode > newNode)
Rewrite a child node.
virtual ~RamNode ()=default
Protected Member Functions
bool equal (const RamNode &node) const override
Equality check for two RAM nodes.
Protected Member Functions inherited from souffle::RamStatement
void print (std::ostream &os) const override
Print RAM node.
virtual void print (std::ostream &os, int tabpos) const =0
Pretty print with indentation.
Protected Attributes
std::vector< std::unique_ptr< RamStatement > > statements
ordered list of RAM statements
Additional Inherited Members
Static Protected Member Functions inherited from souffle::RamStatement
static void print (const RamStatement *statement, std::ostream &os, int tabpos)
Pretty print jump-bed.
Detailed Description
Abstract class for a list of RAM statements.
Definition at line 346 of file Statement.h.
Constructor & Destructor Documentation
RamListStatement() [1/3]
souffle::RamListStatement::RamListStatement () default
RamListStatement() [2/3]
souffle::RamListStatement::RamListStatement (std::vector< std::unique_ptr< RamStatement >> statements) inline
Definition at line 349 of file Statement.h.
             : statements(std::move(statements)) {}
RamListStatement() [3/3]
template<typename... Stmts> souffle::RamListStatement::RamListStatement (std::unique_ptr< Stmts > &&... stmts) inline
Definition at line 353 of file Statement.h.
{
         std::unique_ptr<RamStatement> tmp[] = {std::move(stmts)...};
         for (auto& cur : tmp) {
             assert(cur.get() != nullptr && "statement is a null-pointer");
             statements.emplace_back(std::move(cur));
         }
     }
Member Function Documentation
apply()
void souffle::RamListStatement::apply (const RamNodeMapper &) inline override virtual
Apply the mapper to all child nodes.
Reimplemented from souffle::RamNode.
Definition at line 374 of file Statement.h.
References souffle::map().
{
         for (auto& stmt : statements) {
             stmt = map(std::move(stmt));
         }
     }
equal()
bool souffle::RamListStatement::equal (const RamNode &) const inline override protected virtual
Equality check for two RAM nodes.
Default action is that nothing needs to be checked.
Reimplemented from souffle::RamNode.
Definition at line 381 of file Statement.h.
References souffle::equal_targets().
{
         const auto& other = static_cast<const RamListStatement&>(node);
         return equal_targets(statements, other.statements);
     }
getChildNodes()
std::vector<const RamNode*> souffle::RamListStatement::getChildNodes () const inline override virtual
Obtain list of all embedded child nodes.
Reimplemented from souffle::RamNode.
Definition at line 366 of file Statement.h.
{
         std::vector<const RamNode*> res;
         for (const auto& cur : statements) {
             res.push_back(cur.get());
         }
         return res;
     }
getStatements()
std::vector<RamStatement*> souffle::RamListStatement::getStatements () const inline
Get statements.
Definition at line 362 of file Statement.h.
References souffle::toPtrVector().
Referenced by souffle::Synthesiser::emitCode(), souffle::NodeGenerator::visitParallel(), and souffle::NodeGenerator::visitSequence().
{
         return toPtrVector(statements);
     }
Field Documentation
statements
std::vector<std::unique_ptr<RamStatement> > souffle::RamListStatement::statements protected
ordered list of RAM statements
Definition at line 388 of file Statement.h.
The documentation for this class was generated from the following file:
ram/Statement.h