souffle: souffle::SparseArray< T, BITS, merge_op, copy_op > Class Template Reference
souffle::SparseArray< T, BITS, merge_op, copy_op > Class Template Reference
A sparse array simulates an array associating to every element of uint32_t an element of a generic type T.
#include <Brie.h>
Data Structures
union Cell
The value stored in a single cell of a inner or leaf node.
struct FirstInfoSnapshot
A struct summarizing the state of the first node reference.
class iterator
The iterator type to be utilized to iterate over the non-default elements of this array.
struct Node
The node type of the internally maintained tree.
struct op_context
A struct to be utilized as a local, temporal context by client code to speed up the execution of various operations (optional parameter).
struct RootInfo
A struct describing all the information required by the container class to manage the wrapped up tree.
struct RootInfoSnapshot
A struct to cover a snapshot of the root node state.
Public Types
using atomic_value_type = std::atomic< value_type >
using index_type = key_type
using value_type = T
Public Member Functions
void addAll (const SparseArray &other)
Adds all the values stored in the given array to this array.
iterator begin () const
Obtains an iterator referencing the first non-default element or end in case there are no such elements.
void clear ()
Resets the content of this array to default values for each contained element.
void dump (bool detail=false, std::ostream &out=std::cout) const
A debug utility printing the internal structure of this sparse array to the given output stream.
bool empty () const
Tests whether this sparse array is empty, thus it only contains default-values, or not.
iterator end () const
An iterator referencing the position after the last non-default element.
iterator find (index_type i) const
An operation to obtain an iterator referencing an element addressed by the given index.
iterator find (index_type i, op_context &ctxt) const
An operation to obtain an iterator referencing an element addressed by the given index.
value_type & get (index_type i)
Obtains a mutable reference to the value addressed by the given index.
value_type & get (index_type i, op_context &ctxt)
Obtains a mutable reference to the value addressed by the given index.
atomic_value_type & getAtomic (index_type i)
Obtains a mutable reference to the atomic value addressed by the given index.
atomic_value_type & getAtomic (index_type i, op_context &ctxt)
Obtains a mutable reference to the atomic value addressed by the given index.
std::size_t getMemoryUsage () const
Computes the total memory usage of this data structure.
value_type lookup (index_type i) const
Obtains the value associated to index i – which might be the default value of the covered type if the value hasn't been defined previously.
value_type lookup (index_type i, op_context &ctxt) const
Obtains the value associated to index i – which might be the default value of the covered type if the value hasn't been defined previously.
iterator lowerBound (index_type i) const
An operation obtaining the smallest non-default element such that it's index is >= the given index.
iterator lowerBound (index_type i, op_context &) const
An operation obtaining the smallest non-default element such that it's index is >= the given index.
SparseArray & operator= (const SparseArray &other)
An assignment creating a deep copy of the handed in array structure (utilizing the copy functor provided as a template parameter).
SparseArray & operator= (SparseArray &&other)
An assignment operation taking over ownership from a r-value reference to a sparse array.
value_type operator[] (index_type i) const
Obtains the value associated to index i – which might be the default value of the covered type if the value hasn't been defined previously.
std::size_t size () const
Computes the number of non-empty elements within this sparse array.
SparseArray ()
A default constructor creating an empty sparse array.
SparseArray (const SparseArray &other)
A copy constructor for sparse arrays.
SparseArray (SparseArray &&other)
A r-value based copy constructor for sparse arrays.
void update (index_type i, const value_type &val)
Updates the value stored in cell i by the given value.
void update (index_type i, const value_type &val, op_context &ctxt)
Updates the value stored in cell i by the given value.
iterator upperBound (index_type i) const
An operation obtaining the smallest non-default element such that it's index is greater the given index.
iterator upperBound (index_type i, op_context &ctxt) const
An operation obtaining the smallest non-default element such that it's index is greater the given index.
~SparseArray ()
A destructor for sparse arrays clearing up the internally maintained data structure.
Private Types
using key_type = uint64_t
Private Member Functions
void clean ()
Conducts a cleanup of the internal tree structure.
void dump (bool detailed, std::ostream &out, const Node &node, int level, index_type offset, int indent=0) const
An internal debug utility printing the internal structure of this sparse array to the given output stream.
FirstInfoSnapshot getFirstInfo () const
Obtains a snapshot of the current first-node information.
uint64_t getFirstVersion () const
Obtains the current version number of the first node information.
Cell & getLeaf (index_type i, op_context &ctxt)
An internal function capable of navigating to a given leaf node entry.
RootInfoSnapshot getRootInfo () const
Obtains a snapshot of the current root information.
uint64_t getRootVersion () const
Obtains the current version of the root.
bool inBoundaries (index_type a) const
Tests whether the given index is covered by the boundaries defined by the hight and offset of the internally maintained tree.
void raiseLevel ()
Raises the level of this tree by one level.
void raiseLevel (RootInfoSnapshot &info)
Attempts to raise the height of this tree based on the given root node information and updates the root-info snapshot correspondingly.
bool tryUpdateFirstInfo (const FirstInfoSnapshot &info)
Updates the information stored regarding the first node in a concurrent setting utilizing a optimistic locking approach.
bool tryUpdateRootInfo (const RootInfoSnapshot &info)
Updates the current root information based on the handed in modified snapshot instance if the version number of the snapshot still corresponds to the current version.
Static Private Member Functions
static Node * clone (const Node *node, int level)
Clones the given node and all its sub-nodes.
static Node * findFirst (Node *node, int level)
Obtains the left-most leaf-node of the tree rooted by the given node with the given level.
static void freeNodes (Node *node, int level)
Destroys a node and all its sub-nodes recursively.
static index_type getIndex (RamDomain a, unsigned level)
Obtains the index within the arrays of cells of a given index on a given level of the internally maintained tree.
static index_type getLevelMask (unsigned level)
Computes the bit-mask to be applicable to obtain the offset of a node on a given tree level.
static std::size_t getMemoryUsage (const Node *node, int level)
Computes the memory usage of the given sub-tree.
static bool inBoundaries (index_type a, uint32_t levels, index_type offset)
Tests whether the given index is within the boundaries defined by the given tree hight and offset.
static void merge (const Node *parent, Node *&trg, const Node *src, int levels)
A static operation utilized internally for merging sub-trees recursively.
static Node * newNode ()
Creates new nodes and initializes them with 0.
Private Attributes
union {
volatile RootInfo synced
RootInfo unsynced
};
Static Private Attributes
static constexpr int BIT_PER_STEP = BITS
static constexpr key_type INDEX_MASK = NUM_CELLS - 1
static constexpr int NUM_CELLS = 1 << BIT_PER_STEP
Detailed Description
template<typename T, unsigned BITS = 6, typename merge_op = detail::default_merge<T>, typename copy_op = detail::identity<T>>
class souffle::SparseArray< T, BITS, merge_op, copy_op >
A sparse array simulates an array associating to every element of uint32_t an element of a generic type T.
Any non-defined element will be default-initialized utilizing the detail::default_factory functor.
Internally the array is organized as a balanced tree. The leaf level of the tree corresponds to the elements of the represented array. Inner nodes utilize individual bits of the indices to reference sub-trees. For efficiency reasons, only the minimal sub-tree required to cover all non-null / non-default values stored in the array is maintained. Furthermore, several levels of nodes are aggreated in a B-tree like fashion to inprove cache utilization and reduce the number of steps required for lookup and insert operations.
Template Parameters
T the type of the stored elements
BITS the number of bits consumed per node-level e.g. if it is set to 3, the resulting tree will be of a degree of 2^3=8, and thus 8 child-pointers will be stored in each inner node and as many values will be stored in each leaf node.
merge_op the functor to be utilized when merging the content of two instances of this type.
copy_op a functor to be applied to each stored value when copying an instance of this array. For instance, this is utilized by the trie implementation to create a clone of each sub-tree instead of preserving the original pointer.
Definition at line 128 of file Brie.h.
Member Typedef Documentation
atomic_value_type
template<typename T, unsigned BITS = 6, typename merge_op = detail::default_merge<T>, typename copy_op = detail::identity<T>> using souffle::SparseArray< T, BITS, merge_op, copy_op >::atomic_value_type = std::atomic<value_type>
Definition at line 144 of file Brie.h.
index_type
template<typename T, unsigned BITS = 6, typename merge_op = detail::default_merge<T>, typename copy_op = detail::identity<T>> using souffle::SparseArray< T, BITS, merge_op, copy_op >::index_type = key_type
Definition at line 138 of file Brie.h.
key_type
template<typename T, unsigned BITS = 6, typename merge_op = detail::default_merge<T>, typename copy_op = detail::identity<T>> using souffle::SparseArray< T, BITS, merge_op, copy_op >::key_type = uint64_t private
Definition at line 129 of file Brie.h.
value_type
template<typename T, unsigned BITS = 6, typename merge_op = detail::default_merge<T>, typename copy_op = detail::identity<T>> using souffle::SparseArray< T, BITS, merge_op, copy_op >::value_type = T
Definition at line 141 of file Brie.h.
Constructor & Destructor Documentation
SparseArray() [1/3]
template<typename T, unsigned BITS = 6, typename merge_op = detail::default_merge<T>, typename copy_op = detail::identity<T>> souffle::SparseArray< T, BITS, merge_op, copy_op >::SparseArray () inline
A default constructor creating an empty sparse array.
Definition at line 204 of file Brie.h.
 : unsynced(RootInfo{nullptr, 0, 0, nullptr, std::numeric_limits<index_type>::max()}) {}
SparseArray() [2/3]
template<typename T, unsigned BITS = 6, typename merge_op = detail::default_merge<T>, typename copy_op = detail::identity<T>> souffle::SparseArray< T, BITS, merge_op, copy_op >::SparseArray (const SparseArray< T, BITS, merge_op, copy_op > & other) inline
A copy constructor for sparse arrays.
It creates a deep copy of the data structure maintained by the handed in array instance.
Definition at line 211 of file Brie.h.
             : unsynced(RootInfo{clone(other.unsynced.root, other.unsynced.levels), other.unsynced.levels,
                       other.unsynced.offset, nullptr, other.unsynced.firstOffset}) {
         if (unsynced.root) {
             unsynced.root->parent = nullptr;
             unsynced.first = findFirst(unsynced.root, unsynced.levels);
         }
     }
SparseArray() [3/3]
template<typename T, unsigned BITS = 6, typename merge_op = detail::default_merge<T>, typename copy_op = detail::identity<T>> souffle::SparseArray< T, BITS, merge_op, copy_op >::SparseArray (SparseArray< T, BITS, merge_op, copy_op > && other) inline
A r-value based copy constructor for sparse arrays.
It takes over ownership of the structure maintained by the handed in array.
Definition at line 225 of file Brie.h.
             : unsynced(RootInfo{other.unsynced.root, other.unsynced.levels, other.unsynced.offset,
                       other.unsynced.first, other.unsynced.firstOffset}) {
         other.unsynced.root = nullptr;
         other.unsynced.levels = 0;
         other.unsynced.first = nullptr;
     }
~SparseArray()
template<typename T, unsigned BITS = 6, typename merge_op = detail::default_merge<T>, typename copy_op = detail::identity<T>> souffle::SparseArray< T, BITS, merge_op, copy_op >::~SparseArray () inline
A destructor for sparse arrays clearing up the internally maintained data structure.
Definition at line 237 of file Brie.h.
                    {
         clean();
     }
Member Function Documentation
addAll()
template<typename T, unsigned BITS = 6, typename merge_op = detail::default_merge<T>, typename copy_op = detail::identity<T>> void souffle::SparseArray< T, BITS, merge_op, copy_op >::addAll (const SparseArray< T, BITS, merge_op, copy_op > & other) inline
Adds all the values stored in the given array to this array.
Definition at line 827 of file Brie.h.
Referenced by souffle::SparseBitMap<>::addAll(), souffle::Trie< Arity >::insertAll(), and souffle::TEST().
{
         // skip if other is empty
         if (other.empty()) {
             return;
         }
         // special case: emptiness
         if (empty()) {
             // use assignment operator
             *this = other;
             return;
         }
         // adjust levels
         while (unsynced.levels < other.unsynced.levels || !inBoundaries(other.unsynced.offset)) {
             raiseLevel();
         }
         // navigate to root node equivalent of the other node in this tree
         auto level = unsynced.levels;
         Node** node = &unsynced.root;
         while (level > other.unsynced.levels) {
             // get X coordinate
             auto x = getIndex(other.unsynced.offset, level);
             // decrease level counter
             --level;
             // check next node
             Node*& next = (*node)->cell[x].ptr;
             if (!next) {
                 // create new sub-tree
                 next = newNode();
                 next->parent = *node;
             }
             // continue one level below
             node = &next;
         }
         // merge sub-branches from here
         merge((*node)->parent, *node, other.unsynced.root, level);
         // update first
         if (unsynced.firstOffset > other.unsynced.firstOffset) {
             unsynced.first = findFirst(*node, level);
             unsynced.firstOffset = other.unsynced.firstOffset;
         }
     }
begin()
template<typename T, unsigned BITS = 6, typename merge_op = detail::default_merge<T>, typename copy_op = detail::identity<T>> iterator souffle::SparseArray< T, BITS, merge_op, copy_op >::begin () const inline
Obtains an iterator referencing the first non-default element or end in case there are no such elements.
Definition at line 1032 of file Brie.h.
Referenced by souffle::SparseBitMap<>::begin(), souffle::Trie< Arity >::begin(), souffle::Trie< Arity >::getBeginCoreIterator(), souffle::Trie< Arity >::partition(), and souffle::TEST().
{
         return iterator(unsynced.first, unsynced.firstOffset);
     }
clean()
template<typename T, unsigned BITS = 6, typename merge_op = detail::default_merge<T>, typename copy_op = detail::identity<T>> void souffle::SparseArray< T, BITS, merge_op, copy_op >::clean () inline private
Conducts a cleanup of the internal tree structure.
Definition at line 1284 of file Brie.h.
                  {
         freeNodes(unsynced.root, unsynced.levels);
         unsynced.root = nullptr;
         unsynced.levels = 0;
     }
clear()
template<typename T, unsigned BITS = 6, typename merge_op = detail::default_merge<T>, typename copy_op = detail::identity<T>> void souffle::SparseArray< T, BITS, merge_op, copy_op >::clear () inline
Resets the content of this array to default values for each contained element.
Definition at line 357 of file Brie.h.
Referenced by souffle::SparseBitMap<>::clear().
                  {
         clean();
         unsynced.root = nullptr;
         unsynced.levels = 0;
         unsynced.first = nullptr;
         unsynced.firstOffset = std::numeric_limits<index_type>::max();
     }
clone()
template<typename T, unsigned BITS = 6, typename merge_op = detail::default_merge<T>, typename copy_op = detail::identity<T>> static Node* souffle::SparseArray< T, BITS, merge_op, copy_op >::clone (const Node * node, int level) inline static private
Clones the given node and all its sub-nodes.
Definition at line 1293 of file Brie.h.
{
         // support null-pointers
         if (node == nullptr) {
             return nullptr;
         }
         // create a clone
         auto* res = new Node();
         // handle leaf level
         if (level == 0) {
             copy_op copy;
             for (int i = 0; i < NUM_CELLS; i++) {
                 res->cell[i].value = copy(node->cell[i].value);
             }
             return res;
         }
         // for inner nodes clone each child
         for (int i = 0; i < NUM_CELLS; i++) {
             auto cur = clone(node->cell[i].ptr, level - 1);
             if (cur != nullptr) {
                 cur->parent = res;
             }
             res->cell[i].ptr = cur;
         }
         // done
         return res;
     }
dump() [1/2]
template<typename T, unsigned BITS = 6, typename merge_op = detail::default_merge<T>, typename copy_op = detail::identity<T>> void souffle::SparseArray< T, BITS, merge_op, copy_op >::dump (bool detailed, std::ostream & out, const Node & node, int level, index_type offset, int indent = 0) const inline private
An internal debug utility printing the internal structure of this sparse array to the given output stream.
Definition at line 1209 of file Brie.h.
Referenced by souffle::SparseBitMap<>::dump(), and souffle::TEST().
{
         auto x = getIndex(offset, level + 1);
         out << times("\t", indent) << x << ": Node " << &node << " on level " << level
             << " parent: " << node.parent << " -- range: " << offset << " - "
             << (offset + ~getLevelMask(level + 1)) << "\n";
         if (level == 0) {
             for (int i = 0; i < NUM_CELLS; i++) {
                 if (detailed || node.cell[i].value != value_type()) {
                     out << times("\t", indent + 1) << i << ": [" << (offset + i) << "] " << node.cell[i].value
                         << "\n";
                 }
             }
         } else {
             for (int i = 0; i < NUM_CELLS; i++) {
                 if (node.cell[i].ptr) {
                     dump(detailed, out, *node.cell[i].ptr, level - 1,
                             offset + (i * (index_type(1) << (level * BIT_PER_STEP))), indent + 1);
                 } else if (detailed) {
                     auto low = offset + (i * (1 << (level * BIT_PER_STEP)));
                     auto hig = low + ~getLevelMask(level);
                     out << times("\t", indent + 1) << i << ": empty range " << low << " - " << hig << "\n";
                 }
             }
         }
         out << "\n";
     }
dump() [2/2]
template<typename T, unsigned BITS = 6, typename merge_op = detail::default_merge<T>, typename copy_op = detail::identity<T>> void souffle::SparseArray< T, BITS, merge_op, copy_op >::dump (bool detail = false, std::ostream & out = std::cout) const inline
A debug utility printing the internal structure of this sparse array to the given output stream.
Definition at line 1242 of file Brie.h.
{
         if (!unsynced.root) {
             out << " - empty - \n";
             return;
         }
         out << "root:  " << unsynced.root << "\n";
         out << "offset: " << unsynced.offset << "\n";
         out << "first: " << unsynced.first << "\n";
         out << "fist offset: " << unsynced.firstOffset << "\n";
         dump(detail, out, *unsynced.root, unsynced.levels, unsynced.offset);
     }
empty()
template<typename T, unsigned BITS = 6, typename merge_op = detail::default_merge<T>, typename copy_op = detail::identity<T>> bool souffle::SparseArray< T, BITS, merge_op, copy_op >::empty () const inline
Tests whether this sparse array is empty, thus it only contains default-values, or not.
Definition at line 294 of file Brie.h.
Referenced by souffle::SparseArray< value_t, BITS, merge_op >::addAll(), souffle::SparseBitMap<>::empty(), souffle::Trie< Arity >::empty(), and souffle::TEST().
{
         return unsynced.root == nullptr;
     }
end()
template<typename T, unsigned BITS = 6, typename merge_op = detail::default_merge<T>, typename copy_op = detail::identity<T>> iterator souffle::SparseArray< T, BITS, merge_op, copy_op >::end () const inline
An iterator referencing the position after the last non-default element.
Definition at line 1039 of file Brie.h.
Referenced by souffle::Trie< Arity >::partition(), and souffle::TEST().
{
         return iterator();
     }
find() [1/2]
template<typename T, unsigned BITS = 6, typename merge_op = detail::default_merge<T>, typename copy_op = detail::identity<T>> iterator souffle::SparseArray< T, BITS, merge_op, copy_op >::find (index_type i) const inline
An operation to obtain an iterator referencing an element addressed by the given index.
If the corresponding element is a non-default value, a corresponding iterator will be returned. Otherwise end() will be returned.
Definition at line 1048 of file Brie.h.
Referenced by souffle::SparseBitMap<>::find(), and souffle::TEST().
{
         op_context ctxt;
         return find(i, ctxt);
     }
find() [2/2]
template<typename T, unsigned BITS = 6, typename merge_op = detail::default_merge<T>, typename copy_op = detail::identity<T>> iterator souffle::SparseArray< T, BITS, merge_op, copy_op >::find (index_type i, op_context & ctxt) const inline
An operation to obtain an iterator referencing an element addressed by the given index.
If the corresponding element is a non-default value, a corresponding iterator will be returned. Otherwise end() will be returned. A operation context can be provided for exploiting temporal locality.
Definition at line 1059 of file Brie.h.
{
         // check whether it is empty
         if (!unsynced.root) return end();
         // check boundaries
         if (!inBoundaries(i)) return end();
         // check context
         if (ctxt.lastNode && ctxt.lastIndex == (i & ~INDEX_MASK)) {
             Node* node = ctxt.lastNode;
             // check whether there is a proper entry
             value_type value = node->cell[i & INDEX_MASK].value;
             if (value == value_type{}) {
                 return end();
             }
             // return iterator pointing to value
             return iterator(node, std::make_pair(i, value));
         }
         // navigate to value
         Node* node = unsynced.root;
         unsigned level = unsynced.levels;
         while (level != 0) {
             // get X coordinate
             auto x = getIndex(i, level);
             // decrease level counter
             --level;
             // check next node
             Node* next = node->cell[x].ptr;
             // check next step
             if (!next) return end();
             // continue one level below
             node = next;
         }
         // register in context
         ctxt.lastNode = node;
         ctxt.lastIndex = (i & ~INDEX_MASK);
         // check whether there is a proper entry
         value_type value = node->cell[i & INDEX_MASK].value;
         if (value == value_type{}) {
             return end();
         }
         // return iterator pointing to cell
         return iterator(node, std::make_pair(i, value));
     }
findFirst()
template<typename T, unsigned BITS = 6, typename merge_op = detail::default_merge<T>, typename copy_op = detail::identity<T>> static Node* souffle::SparseArray< T, BITS, merge_op, copy_op >::findFirst (Node * node, int level) inline static private
Obtains the left-most leaf-node of the tree rooted by the given node with the given level.
Definition at line 1328 of file Brie.h.
{
         while (level > 0) {
             bool found = false;
             for (int i = 0; i < NUM_CELLS; i++) {
                 Node* cur = node->cell[i].ptr;
                 if (cur) {
                     node = cur;
                     --level;
                     found = true;
                     break;
                 }
             }
             assert(found && "No first node!");
         }
         return node;
     }
freeNodes()
template<typename T, unsigned BITS = 6, typename merge_op = detail::default_merge<T>, typename copy_op = detail::identity<T>> static void souffle::SparseArray< T, BITS, merge_op, copy_op >::freeNodes (Node * node, int level) inline static private
Destroys a node and all its sub-nodes recursively.
Definition at line 1271 of file Brie.h.
{
         if (!node) return;
         if (level != 0) {
             for (int i = 0; i < NUM_CELLS; i++) {
                 freeNodes(node->cell[i].ptr, level - 1);
             }
         }
         delete node;
     }
get() [1/2]
template<typename T, unsigned BITS = 6, typename merge_op = detail::default_merge<T>, typename copy_op = detail::identity<T>> value_type& souffle::SparseArray< T, BITS, merge_op, copy_op >::get (index_type i) inline
Obtains a mutable reference to the value addressed by the given index.
Parameters
i the index of the element to be addressed
Returns
a mutable reference to the corresponding element
Definition at line 529 of file Brie.h.
{
         op_context ctxt;
         return get(i, ctxt);
     }
get() [2/2]
template<typename T, unsigned BITS = 6, typename merge_op = detail::default_merge<T>, typename copy_op = detail::identity<T>> value_type& souffle::SparseArray< T, BITS, merge_op, copy_op >::get (index_type i, op_context & ctxt) inline
Obtains a mutable reference to the value addressed by the given index.
Parameters
i the index of the element to be addressed
ctxt a operation context to exploit state-less temporal locality
Returns
a mutable reference to the corresponding element
Definition at line 541 of file Brie.h.
{
         return getLeaf(i, ctxt).value;
     }
getAtomic() [1/2]
template<typename T, unsigned BITS = 6, typename merge_op = detail::default_merge<T>, typename copy_op = detail::identity<T>> atomic_value_type& souffle::SparseArray< T, BITS, merge_op, copy_op >::getAtomic (index_type i) inline
Obtains a mutable reference to the atomic value addressed by the given index.
Parameters
i the index of the element to be addressed
Returns
a mutable reference to the corresponding element
Definition at line 551 of file Brie.h.
Referenced by souffle::Trie< Arity >::insert_internal(), and souffle::SparseBitMap<>::set().
{
         op_context ctxt;
         return getAtomic(i, ctxt);
     }
getAtomic() [2/2]
template<typename T, unsigned BITS = 6, typename merge_op = detail::default_merge<T>, typename copy_op = detail::identity<T>> atomic_value_type& souffle::SparseArray< T, BITS, merge_op, copy_op >::getAtomic (index_type i, op_context & ctxt) inline
Obtains a mutable reference to the atomic value addressed by the given index.
Parameters
i the index of the element to be addressed
ctxt a operation context to exploit state-less temporal locality
Returns
a mutable reference to the corresponding element
Definition at line 563 of file Brie.h.
{
         return getLeaf(i, ctxt).avalue;
     }
getFirstInfo()
template<typename T, unsigned BITS = 6, typename merge_op = detail::default_merge<T>, typename copy_op = detail::identity<T>> FirstInfoSnapshot souffle::SparseArray< T, BITS, merge_op, copy_op >::getFirstInfo () const inline private
Obtains a snapshot of the current first-node information.
Definition at line 479 of file Brie.h.
{
         FirstInfoSnapshot res{};
         do {
             // first take the version
             do {
                 res.version = getFirstVersion();
             } while (res.version % 2);
             // collect the values
             res.node = synced.first;
             res.offset = synced.firstOffset;
         } while (res.version != getFirstVersion());
         // we got a consistent snapshot
         return res;
     }
getFirstVersion()
template<typename T, unsigned BITS = 6, typename merge_op = detail::default_merge<T>, typename copy_op = detail::identity<T>> uint64_t souffle::SparseArray< T, BITS, merge_op, copy_op >::getFirstVersion () const inline private
Obtains the current version number of the first node information.
Definition at line 471 of file Brie.h.
{
         // here it is assumed that the load of a 64-bit word is atomic
         return (uint64_t)synced.first;
     }
getIndex()
template<typename T, unsigned BITS = 6, typename merge_op = detail::default_merge<T>, typename copy_op = detail::identity<T>> static index_type souffle::SparseArray< T, BITS, merge_op, copy_op >::getIndex (RamDomain a, unsigned level) inline static private
Obtains the index within the arrays of cells of a given index on a given level of the internally maintained tree.
Definition at line 1430 of file Brie.h.
{
         return (a & (INDEX_MASK << (level * BIT_PER_STEP))) >> (level * BIT_PER_STEP);
     }
getLeaf()
template<typename T, unsigned BITS = 6, typename merge_op = detail::default_merge<T>, typename copy_op = detail::identity<T>> Cell& souffle::SparseArray< T, BITS, merge_op, copy_op >::getLeaf (index_type i, op_context & ctxt) inline private
An internal function capable of navigating to a given leaf node entry.
If the cell does not exist yet it will be created as a side-effect.
Parameters
i the index of the requested cell
ctxt a operation context to exploit state-less temporal locality
Returns
a reference to the requested cell
Definition at line 576 of file Brie.h.
{
         // check context
         if (ctxt.lastNode && (ctxt.lastIndex == (i & ~INDEX_MASK))) {
             // return reference to referenced
             return ctxt.lastNode->cell[i & INDEX_MASK];
         }
         // get snapshot of root
         auto info = getRootInfo();
         // check for emptiness
         if (info.root == nullptr) {
             // build new root node
             info.root = newNode();
             // initialize the new node
             info.root->parent = nullptr;
             info.offset = i & ~(INDEX_MASK);
             // try updating root information atomically
             if (tryUpdateRootInfo(info)) {
                 // success -- finish get call
                 // update first
                 auto firstInfo = getFirstInfo();
                 while (info.offset < firstInfo.offset) {
                     firstInfo.node = info.root;
                     firstInfo.offset = info.offset;
                     if (!tryUpdateFirstInfo(firstInfo)) {
                         // there was some concurrent update => check again
                         firstInfo = getFirstInfo();
                     }
                 }
                 // return reference to proper cell
                 return info.root->cell[i & INDEX_MASK];
             }
             // somebody else was faster => use standard insertion procedure
             delete info.root;
             // retrieve new root info
             info = getRootInfo();
             // make sure there is a root
             assert(info.root);
         }
         // for all other inserts
         //   - check boundary
         //   - navigate to node
         //   - insert value
         // check boundaries
         while (!inBoundaries(i, info.levels, info.offset)) {
             // boundaries need to be expanded by growing upwards
             raiseLevel(info);  // try raising level unless someone else did already
             // update root info
             info = getRootInfo();
         }
         // navigate to node
         Node* node = info.root;
         unsigned level = info.levels;
         while (level != 0) {
             // get X coordinate
             auto x = getIndex(i, level);
             // decrease level counter
             --level;
             // check next node
             std::atomic<Node*>& aNext = node->cell[x].aptr;
             Node* next = aNext;
             if (!next) {
                 // create new sub-tree
                 Node* newNext = newNode();
                 newNext->parent = node;
                 // try to update next
                 if (!aNext.compare_exchange_strong(next, newNext)) {
                     // some other thread was faster => use updated next
                     delete newNext;
                 } else {
                     // the locally created next is the new next
                     next = newNext;
                     // update first
                     if (level == 0) {
                         // compute offset of this node
                         auto off = i & ~INDEX_MASK;
                         // fast over-approximation of whether a update is necessary
                         if (off < unsynced.firstOffset) {
                             // update first reference if this one is the smallest
                             auto first_info = getFirstInfo();
                             while (off < first_info.offset) {
                                 first_info.node = next;
                                 first_info.offset = off;
                                 if (!tryUpdateFirstInfo(first_info)) {
                                     // there was some concurrent update => check again
                                     first_info = getFirstInfo();
                                 }
                             }
                         }
                     }
                 }
                 // now next should be defined
                 assert(next);
             }
             // continue one level below
             node = next;
         }
         // update context
         ctxt.lastIndex = (i & ~INDEX_MASK);
         ctxt.lastNode = node;
         // return reference to cell
         return node->cell[i & INDEX_MASK];
     }
getLevelMask()
template<typename T, unsigned BITS = 6, typename merge_op = detail::default_merge<T>, typename copy_op = detail::identity<T>> static index_type souffle::SparseArray< T, BITS, merge_op, copy_op >::getLevelMask (unsigned level) inline static private
Computes the bit-mask to be applicable to obtain the offset of a node on a given tree level.
Definition at line 1438 of file Brie.h.
{
         if (level > (sizeof(index_type) * 8 / BITS)) return 0;
         return (~(index_type(0)) << (level * BIT_PER_STEP));
     }
getMemoryUsage() [1/2]
template<typename T, unsigned BITS = 6, typename merge_op = detail::default_merge<T>, typename copy_op = detail::identity<T>> static std::size_t souffle::SparseArray< T, BITS, merge_op, copy_op >::getMemoryUsage (const Node * node, int level) inline static private
Computes the memory usage of the given sub-tree.
Definition at line 318 of file Brie.h.
Referenced by souffle::SparseBitMap<>::getMemoryUsage(), souffle::Trie< Arity >::getMemoryUsage(), and souffle::TEST().
{
         // support null-nodes
         if (!node) return 0;
         // add size of current node
         std::size_t res = sizeof(Node);
         // sum up memory usage of child nodes
         if (level > 0) {
             for (int i = 0; i < NUM_CELLS; i++) {
                 res += getMemoryUsage(node->cell[i].ptr, level - 1);
             }
         }
         // done
         return res;
     }
getMemoryUsage() [2/2]
template<typename T, unsigned BITS = 6, typename merge_op = detail::default_merge<T>, typename copy_op = detail::identity<T>> std::size_t souffle::SparseArray< T, BITS, merge_op, copy_op >::getMemoryUsage () const inline
Computes the total memory usage of this data structure.
Definition at line 340 of file Brie.h.
{
         // the memory of the wrapper class
         std::size_t res = sizeof(*this);
         // add nodes
         if (unsynced.root) {
             res += getMemoryUsage(unsynced.root, unsynced.levels);
         }
         // done
         return res;
     }
getRootInfo()
template<typename T, unsigned BITS = 6, typename merge_op = detail::default_merge<T>, typename copy_op = detail::identity<T>> RootInfoSnapshot souffle::SparseArray< T, BITS, merge_op, copy_op >::getRootInfo () const inline private
Obtains a snapshot of the current root information.
Definition at line 405 of file Brie.h.
{
         RootInfoSnapshot res{};
         do {
             // first take the mod counter
             do {
                 // if res.mod % 2 == 1 .. there is an update in progress
                 res.version = getRootVersion();
             } while (res.version % 2);
             // then the rest
             res.root = synced.root;
             res.levels = synced.levels;
             res.offset = synced.offset;
             // check consistency of obtained data (optimistic locking)
         } while (res.version != getRootVersion());
         // got a consistent snapshot
         return res;
     }
getRootVersion()
template<typename T, unsigned BITS = 6, typename merge_op = detail::default_merge<T>, typename copy_op = detail::identity<T>> uint64_t souffle::SparseArray< T, BITS, merge_op, copy_op >::getRootVersion () const inline private
Obtains the current version of the root.
Definition at line 397 of file Brie.h.
{
         // here it is assumed that the load of a 64-bit word is atomic
         return (uint64_t)synced.root;
     }
inBoundaries() [1/2]
template<typename T, unsigned BITS = 6, typename merge_op = detail::default_merge<T>, typename copy_op = detail::identity<T>> bool souffle::SparseArray< T, BITS, merge_op, copy_op >::inBoundaries (index_type a) const inline private
Tests whether the given index is covered by the boundaries defined by the hight and offset of the internally maintained tree.
Definition at line 1413 of file Brie.h.
{
         return inBoundaries(a, unsynced.levels, unsynced.offset);
     }
inBoundaries() [2/2]
template<typename T, unsigned BITS = 6, typename merge_op = detail::default_merge<T>, typename copy_op = detail::identity<T>> static bool souffle::SparseArray< T, BITS, merge_op, copy_op >::inBoundaries (index_type a, uint32_t levels, index_type offset) inline static private
Tests whether the given index is within the boundaries defined by the given tree hight and offset.
Definition at line 1421 of file Brie.h.
{
         auto mask = getLevelMask(levels + 1);
         return (a & mask) == offset;
     }
lookup() [1/2]
template<typename T, unsigned BITS = 6, typename merge_op = detail::default_merge<T>, typename copy_op = detail::identity<T>> value_type souffle::SparseArray< T, BITS, merge_op, copy_op >::lookup (index_type i) const inline
Obtains the value associated to index i – which might be the default value of the covered type if the value hasn't been defined previously.
Definition at line 731 of file Brie.h.
Referenced by souffle::Trie< Arity >::contains_internal(), and souffle::SparseBitMap<>::test().
{
         op_context ctxt;
         return lookup(i, ctxt);
     }
lookup() [2/2]
template<typename T, unsigned BITS = 6, typename merge_op = detail::default_merge<T>, typename copy_op = detail::identity<T>> value_type souffle::SparseArray< T, BITS, merge_op, copy_op >::lookup (index_type i, op_context & ctxt) const inline
Obtains the value associated to index i – which might be the default value of the covered type if the value hasn't been defined previously.
A operation context can be provided for exploiting temporal locality.
Definition at line 742 of file Brie.h.
{
         // check whether it is empty
         if (!unsynced.root) return souffle::detail::default_factory<value_type>()();
         // check boundaries
         if (!inBoundaries(i)) return souffle::detail::default_factory<value_type>()();
         // check context
         if (ctxt.lastNode && ctxt.lastIndex == (i & ~INDEX_MASK)) {
             return ctxt.lastNode->cell[i & INDEX_MASK].value;
         }
         // navigate to value
         Node* node = unsynced.root;
         unsigned level = unsynced.levels;
         while (level != 0) {
             // get X coordinate
             auto x = getIndex(i, level);
             // decrease level counter
             --level;
             // check next node
             Node* next = node->cell[x].ptr;
             // check next step
             if (!next) return souffle::detail::default_factory<value_type>()();
             // continue one level below
             node = next;
         }
         // remember context
         ctxt.lastIndex = (i & ~INDEX_MASK);
         ctxt.lastNode = node;
         // return reference to cell
         return node->cell[i & INDEX_MASK].value;
     }
lowerBound() [1/2]
template<typename T, unsigned BITS = 6, typename merge_op = detail::default_merge<T>, typename copy_op = detail::identity<T>> iterator souffle::SparseArray< T, BITS, merge_op, copy_op >::lowerBound (index_type i) const inline
An operation obtaining the smallest non-default element such that it's index is >= the given index.
Definition at line 1117 of file Brie.h.
Referenced by souffle::SparseBitMap<>::lower_bound(), and souffle::TEST().
{
         op_context ctxt;
         return lowerBound(i, ctxt);
     }
lowerBound() [2/2]
template<typename T, unsigned BITS = 6, typename merge_op = detail::default_merge<T>, typename copy_op = detail::identity<T>> iterator souffle::SparseArray< T, BITS, merge_op, copy_op >::lowerBound (index_type i, op_context &) const inline
An operation obtaining the smallest non-default element such that it's index is >= the given index.
A operation context can be provided for exploiting temporal locality.
Definition at line 1126 of file Brie.h.
{
         // check whether it is empty
         if (!unsynced.root) return end();
         // check boundaries
         if (!inBoundaries(i)) {
             // if it is on the lower end, return minimum result
             if (i < unsynced.offset) {
                 const auto& value = unsynced.first->cell[0].value;
                 auto res = iterator(unsynced.first, std::make_pair(unsynced.offset, value));
                 if (value == value_type()) {
                     ++res;
                 }
                 return res;
             }
             // otherwise it is on the high end, return end iterator
             return end();
         }
         // navigate to value
         Node* node = unsynced.root;
         unsigned level = unsynced.levels;
         while (true) {
             // get X coordinate
             auto x = getIndex(i, level);
             // check next node
             Node* next = node->cell[x].ptr;
             // check next step
             if (!next) {
                 if (x == NUM_CELLS - 1) {
                     ++level;
                     node = const_cast<Node*>(node->parent);
                     if (!node) return end();
                 }
                 // continue search
                 i = i & getLevelMask(level);
                 // find next higher value
                 i += 1ull << (BITS * level);
             } else {
                 if (level == 0) {
                     // found boundary
                     return iterator(node, std::make_pair(i, node->cell[x].value));
                 }
                 // decrease level counter
                 --level;
                 // continue one level below
                 node = next;
             }
         }
     }
merge()
template<typename T, unsigned BITS = 6, typename merge_op = detail::default_merge<T>, typename copy_op = detail::identity<T>> static void souffle::SparseArray< T, BITS, merge_op, copy_op >::merge (const Node * parent, Node *& trg, const Node * src, int levels) inline static private
A static operation utilized internally for merging sub-trees recursively.
Parameters
parent the parent node of the current merge operation
trg a reference to the pointer the cloned node should be stored to
src the node to be cloned
levels the height of the cloned node
Definition at line 791 of file Brie.h.
{
         // if other side is null => done
         if (src == nullptr) {
             return;
         }
         // if the trg sub-tree is empty, clone the corresponding branch
         if (trg == nullptr) {
             trg = clone(src, levels);
             if (trg != nullptr) {
                 trg->parent = parent;
             }
             return;  // done
         }
         // otherwise merge recursively
         // the leaf-node step
         if (levels == 0) {
             merge_op merg;
             for (int i = 0; i < NUM_CELLS; ++i) {
                 trg->cell[i].value = merg(trg->cell[i].value, src->cell[i].value);
             }
             return;
         }
         // the recursive step
         for (int i = 0; i < NUM_CELLS; ++i) {
             merge(trg, trg->cell[i].ptr, src->cell[i].ptr, levels - 1);
         }
     }
newNode()
template<typename T, unsigned BITS = 6, typename merge_op = detail::default_merge<T>, typename copy_op = detail::identity<T>> static Node* souffle::SparseArray< T, BITS, merge_op, copy_op >::newNode () inline static private
Creates new nodes and initializes them with 0.
Definition at line 1262 of file Brie.h.
{
         auto* res = new Node();
         std::memset(res->cell, 0, sizeof(Cell) * NUM_CELLS);
         return res;
     }
operator=() [1/2]
template<typename T, unsigned BITS = 6, typename merge_op = detail::default_merge<T>, typename copy_op = detail::identity<T>> SparseArray& souffle::SparseArray< T, BITS, merge_op, copy_op >::operator= (const SparseArray< T, BITS, merge_op, copy_op > & other) inline
An assignment creating a deep copy of the handed in array structure (utilizing the copy functor provided as a template parameter).
Definition at line 246 of file Brie.h.
{
         if (this == &other) return *this;
         // clean this one
         clean();
         // copy content
         unsynced.levels = other.unsynced.levels;
         unsynced.root = clone(other.unsynced.root, unsynced.levels);
         if (unsynced.root) {
             unsynced.root->parent = nullptr;
         }
         unsynced.offset = other.unsynced.offset;
         unsynced.first = (unsynced.root) ? findFirst(unsynced.root, unsynced.levels) : nullptr;
         unsynced.firstOffset = other.unsynced.firstOffset;
         // done
         return *this;
     }
operator=() [2/2]
template<typename T, unsigned BITS = 6, typename merge_op = detail::default_merge<T>, typename copy_op = detail::identity<T>> SparseArray& souffle::SparseArray< T, BITS, merge_op, copy_op >::operator= (SparseArray< T, BITS, merge_op, copy_op > && other) inline
An assignment operation taking over ownership from a r-value reference to a sparse array.
Definition at line 270 of file Brie.h.
{
         // clean this one
         clean();
         // harvest content
         unsynced.root = other.unsynced.root;
         unsynced.levels = other.unsynced.levels;
         unsynced.offset = other.unsynced.offset;
         unsynced.first = other.unsynced.first;
         unsynced.firstOffset = other.unsynced.firstOffset;
         // reset other
         other.unsynced.root = nullptr;
         other.unsynced.levels = 0;
         other.unsynced.first = nullptr;
         // done
         return *this;
     }
operator[]()
template<typename T, unsigned BITS = 6, typename merge_op = detail::default_merge<T>, typename copy_op = detail::identity<T>> value_type souffle::SparseArray< T, BITS, merge_op, copy_op >::operator[] (index_type i) const inline
Obtains the value associated to index i – which might be the default value of the covered type if the value hasn't been defined previously.
Definition at line 722 of file Brie.h.
{
         return lookup(i);
     }
raiseLevel() [1/2]
template<typename T, unsigned BITS = 6, typename merge_op = detail::default_merge<T>, typename copy_op = detail::identity<T>> void souffle::SparseArray< T, BITS, merge_op, copy_op >::raiseLevel () inline private
Raises the level of this tree by one level.
It does so by introducing a new root node and inserting the current root node as a child node.
Definition at line 1350 of file Brie.h.
                       {
         // something went wrong when we pass that line
         assert(unsynced.levels < (sizeof(index_type) * 8 / BITS) + 1);
         // create new root
         Node* node = newNode();
         node->parent = nullptr;
         // insert existing root as child
         auto x = getIndex(unsynced.offset, unsynced.levels + 1);
         node->cell[x].ptr = unsynced.root;
         // swap the root
         unsynced.root->parent = node;
         // update root
         unsynced.root = node;
         ++unsynced.levels;
         // update offset be removing additional bits
         unsynced.offset &= getLevelMask(unsynced.levels + 1);
     }
raiseLevel() [2/2]
template<typename T, unsigned BITS = 6, typename merge_op = detail::default_merge<T>, typename copy_op = detail::identity<T>> void souffle::SparseArray< T, BITS, merge_op, copy_op >::raiseLevel (RootInfoSnapshot & info) inline private
Attempts to raise the height of this tree based on the given root node information and updates the root-info snapshot correspondingly.
Definition at line 1377 of file Brie.h.
{
         // something went wrong when we pass that line
         assert(info.levels < (sizeof(index_type) * 8 / BITS) + 1);
         // create new root
         Node* newRoot = newNode();
         newRoot->parent = nullptr;
         // insert existing root as child
         auto x = getIndex(info.offset, info.levels + 1);
         newRoot->cell[x].ptr = info.root;
         // exchange the root in the info struct
         auto oldRoot = info.root;
         info.root = newRoot;
         // update level counter
         ++info.levels;
         // update offset
         info.offset &= getLevelMask(info.levels + 1);
         // try exchanging root info
         if (tryUpdateRootInfo(info)) {
             // success => final step, update parent of old root
             oldRoot->parent = info.root;
         } else {
             // throw away temporary new node
             delete newRoot;
         }
     }
size()
template<typename T, unsigned BITS = 6, typename merge_op = detail::default_merge<T>, typename copy_op = detail::identity<T>> std::size_t souffle::SparseArray< T, BITS, merge_op, copy_op >::size () const inline
Computes the number of non-empty elements within this sparse array.
Definition at line 302 of file Brie.h.
Referenced by souffle::Trie< Arity >::partition().
{
         // quick one for the empty map
         if (empty()) return 0;
         // count elements -- since maintaining is making inserts more expensive
         std::size_t res = 0;
         for (auto it = begin(); it != end(); ++it) {
             ++res;
         }
         return res;
     }
tryUpdateFirstInfo()
template<typename T, unsigned BITS = 6, typename merge_op = detail::default_merge<T>, typename copy_op = detail::identity<T>> bool souffle::SparseArray< T, BITS, merge_op, copy_op >::tryUpdateFirstInfo (const FirstInfoSnapshot & info) inline private
Updates the information stored regarding the first node in a concurrent setting utilizing a optimistic locking approach.
This is identical to the approach utilized for the root info.
Definition at line 502 of file Brie.h.
{
         // check mod counter
         uintptr_t version = info.version;
         // temporary update first pointer to point to uneven value (lock-out)
         if (!__sync_bool_compare_and_swap(&synced.first, (Node*)version, (Node*)(version + 1))) {
             return false;
         }
         // conduct update
         synced.firstOffset = info.offset;
         // update node pointer (and thus the version number)
         __sync_synchronize();
         synced.first = info.node;  // must be last (and atomic)
         // done
         return true;
     }
tryUpdateRootInfo()
template<typename T, unsigned BITS = 6, typename merge_op = detail::default_merge<T>, typename copy_op = detail::identity<T>> bool souffle::SparseArray< T, BITS, merge_op, copy_op >::tryUpdateRootInfo (const RootInfoSnapshot & info) inline private
Updates the current root information based on the handed in modified snapshot instance if the version number of the snapshot still corresponds to the current version.
Otherwise a concurrent update took place and the operation is aborted.
Parameters
info the updated information to be assigned to the active root-info data
Returns
true if successfully updated, false if aborted
Definition at line 435 of file Brie.h.
{
         // check mod counter
         uintptr_t version = info.version;
         // update root to invalid pointer (ending with 1)
         if (!__sync_bool_compare_and_swap(&synced.root, (Node*)version, (Node*)(version + 1))) {
             return false;
         }
         // conduct update
         synced.levels = info.levels;
         synced.offset = info.offset;
         // update root (and thus the version to enable future retrievals)
         __sync_synchronize();
         synced.root = info.root;
         // done
         return true;
     }
update() [1/2]
template<typename T, unsigned BITS = 6, typename merge_op = detail::default_merge<T>, typename copy_op = detail::identity<T>> void souffle::SparseArray< T, BITS, merge_op, copy_op >::update (index_type i, const value_type & val) inline
Updates the value stored in cell i by the given value.
Definition at line 704 of file Brie.h.
Referenced by souffle::TEST().
{
         op_context ctxt;
         update(i, val, ctxt);
     }
update() [2/2]
template<typename T, unsigned BITS = 6, typename merge_op = detail::default_merge<T>, typename copy_op = detail::identity<T>> void souffle::SparseArray< T, BITS, merge_op, copy_op >::update (index_type i, const value_type & val, op_context & ctxt) inline
Updates the value stored in cell i by the given value.
A operation context can be provided for exploiting temporal locality.
Definition at line 713 of file Brie.h.
{
         get(i, ctxt) = val;
     }
upperBound() [1/2]
template<typename T, unsigned BITS = 6, typename merge_op = detail::default_merge<T>, typename copy_op = detail::identity<T>> iterator souffle::SparseArray< T, BITS, merge_op, copy_op >::upperBound (index_type i) const inline
An operation obtaining the smallest non-default element such that it's index is greater the given index.
Definition at line 1188 of file Brie.h.
Referenced by souffle::TEST().
{
         op_context ctxt;
         return upperBound(i, ctxt);
     }
upperBound() [2/2]
template<typename T, unsigned BITS = 6, typename merge_op = detail::default_merge<T>, typename copy_op = detail::identity<T>> iterator souffle::SparseArray< T, BITS, merge_op, copy_op >::upperBound (index_type i, op_context & ctxt) const inline
An operation obtaining the smallest non-default element such that it's index is greater the given index.
A operation context can be provided for exploiting temporal locality.
Definition at line 1197 of file Brie.h.
{
         if (i == std::numeric_limits<index_type>::max()) {
             return end();
         }
         return lowerBound(i + 1, ctxt);
     }
Field Documentation
@1
union { ... }
BIT_PER_STEP
template<typename T, unsigned BITS = 6, typename merge_op = detail::default_merge<T>, typename copy_op = detail::identity<T>> constexpr int souffle::SparseArray< T, BITS, merge_op, copy_op >::BIT_PER_STEP = BITS static private
Definition at line 132 of file Brie.h.
INDEX_MASK
template<typename T, unsigned BITS = 6, typename merge_op = detail::default_merge<T>, typename copy_op = detail::identity<T>> constexpr key_type souffle::SparseArray< T, BITS, merge_op, copy_op >::INDEX_MASK = NUM_CELLS - 1 static private
Definition at line 134 of file Brie.h.
NUM_CELLS
template<typename T, unsigned BITS = 6, typename merge_op = detail::default_merge<T>, typename copy_op = detail::identity<T>> constexpr int souffle::SparseArray< T, BITS, merge_op, copy_op >::NUM_CELLS = 1 << BIT_PER_STEP static private
Definition at line 133 of file Brie.h.
synced
template<typename T, unsigned BITS = 6, typename merge_op = detail::default_merge<T>, typename copy_op = detail::identity<T>> volatile RootInfo souffle::SparseArray< T, BITS, merge_op, copy_op >::synced
Definition at line 197 of file Brie.h.
unsynced
template<typename T, unsigned BITS = 6, typename merge_op = detail::default_merge<T>, typename copy_op = detail::identity<T>> RootInfo souffle::SparseArray< T, BITS, merge_op, copy_op >::unsynced
Definition at line 196 of file Brie.h.
Referenced by souffle::SparseArray< value_t, BITS, merge_op >::addAll(), souffle::SparseArray< value_t, BITS, merge_op >::operator=(), and souffle::SparseArray< value_t, BITS, merge_op >::SparseArray().
The documentation for this class was generated from the following file:
Brie.h