souffle: souffle::profile::DataComparator Class Reference
souffle::profile::DataComparator Class Reference
#include <DataComparator.h>
Static Public Member Functions
static bool C_T (const std::shared_ptr< Row > &a, const std::shared_ptr< Row > &b)
Sort by copy time.
static bool ID (const std::shared_ptr< Row > &a, const std::shared_ptr< Row > &b)
Sort by ID.
static bool NAME (const std::shared_ptr< Row > &a, const std::shared_ptr< Row > &b)
Sort by name.
static bool NR_T (const std::shared_ptr< Row > &a, const std::shared_ptr< Row > &b)
Sort by non-recursive time.
static bool R_T (const std::shared_ptr< Row > &a, const std::shared_ptr< Row > &b)
Sort by recursive time.
static bool TIME (const std::shared_ptr< Row > &a, const std::shared_ptr< Row > &b)
Sort by total time.
static bool TUP (const std::shared_ptr< Row > &a, const std::shared_ptr< Row > &b)
Sort by tuple count.
Detailed Description
Definition at line 27 of file DataComparator.h.
Member Function Documentation
C_T()
static bool souffle::profile::DataComparator::C_T (const std::shared_ptr< Row > & a, const std::shared_ptr< Row > & b) inline static
Sort by copy time.
Definition at line 45 of file DataComparator.h.
Referenced by souffle::profile::Table::sort().
{
         return a->cells[3]->getDoubleVal() > b->cells[3]->getDoubleVal();
     }
ID()
static bool souffle::profile::DataComparator::ID (const std::shared_ptr< Row > & a, const std::shared_ptr< Row > & b) inline static
Sort by ID.
Definition at line 60 of file DataComparator.h.
Referenced by souffle::profile::Table::sort().
{
         return b->cells[6]->getStringVal() > a->cells[6]->getStringVal();
     }
NAME()
static bool souffle::profile::DataComparator::NAME (const std::shared_ptr< Row > & a, const std::shared_ptr< Row > & b) inline static
Sort by name.
Definition at line 55 of file DataComparator.h.
Referenced by souffle::profile::Table::sort().
{
         return b->cells[5]->getStringVal() > a->cells[5]->getStringVal();
     }
NR_T()
static bool souffle::profile::DataComparator::NR_T (const std::shared_ptr< Row > & a, const std::shared_ptr< Row > & b) inline static
Sort by non-recursive time.
Definition at line 35 of file DataComparator.h.
Referenced by souffle::profile::Table::sort().
{
         return a->cells[1]->getDoubleVal() > b->cells[1]->getDoubleVal();
     }
R_T()
static bool souffle::profile::DataComparator::R_T (const std::shared_ptr< Row > & a, const std::shared_ptr< Row > & b) inline static
Sort by recursive time.
Definition at line 40 of file DataComparator.h.
Referenced by souffle::profile::Table::sort().
{
         return a->cells[2]->getDoubleVal() > b->cells[2]->getDoubleVal();
     }
TIME()
static bool souffle::profile::DataComparator::TIME (const std::shared_ptr< Row > & a, const std::shared_ptr< Row > & b) inline static
Sort by total time.
Definition at line 30 of file DataComparator.h.
Referenced by souffle::profile::Table::sort().
{
         return a->cells[0]->getDoubleVal() > b->cells[0]->getDoubleVal();
     }
TUP()
static bool souffle::profile::DataComparator::TUP (const std::shared_ptr< Row > & a, const std::shared_ptr< Row > & b) inline static
Sort by tuple count.
Definition at line 50 of file DataComparator.h.
Referenced by souffle::profile::Table::sort().
{
         return b->cells[4]->getLongVal() < a->cells[4]->getLongVal();
     }
The documentation for this class was generated from the following file:
profile/DataComparator.h