souffle: souffle::AstQualifiedName Class Reference
souffle::AstQualifiedName Class Reference
Qualified Name class for fully/partially qualified names to identify objects in components.
#include <QualifiedName.h>
Public Member Functions
void append (std::string name)
append qualifiers
AstQualifiedName ()
AstQualifiedName (const std::string &name)
AstQualifiedName (const char *name)
AstQualifiedName (const std::vector< std::string > qualifiers)
AstQualifiedName (const AstQualifiedName &)=default
AstQualifiedName (AstQualifiedName &&)=default
bool empty () const
check for emptiness
const std::vector< std::string > & getQualifiers () const
get qualifiers
bool operator!= (const AstQualifiedName &other) const
bool operator< (const AstQualifiedName &other) const
AstQualifiedName & operator= (const AstQualifiedName &)=default
AstQualifiedName & operator= (AstQualifiedName &&)=default
bool operator== (const AstQualifiedName &other) const
void prepend (std::string name)
prepend qualifiers
void print (std::ostream &out) const
print qualified name
std::string toString () const
convert to a string separated by fullstop
Private Attributes
std::vector< std::string > qualifiers
Friends
std::ostream & operator<< (std::ostream &out, const AstQualifiedName &id)
Detailed Description
Qualified Name class for fully/partially qualified names to identify objects in components.
Definition at line 34 of file QualifiedName.h.
Constructor & Destructor Documentation
AstQualifiedName() [1/6]
souffle::AstQualifiedName::AstQualifiedName () inline
Definition at line 36 of file QualifiedName.h.
Referenced by AstQualifiedName().
 : qualifiers() {}
AstQualifiedName() [2/6]
souffle::AstQualifiedName::AstQualifiedName (const std::string & name) inline
Definition at line 37 of file QualifiedName.h.
 : qualifiers({name}) {}
AstQualifiedName() [3/6]
souffle::AstQualifiedName::AstQualifiedName (const char * name) inline
Definition at line 38 of file QualifiedName.h.
 : AstQualifiedName(std::string(name)) {}
AstQualifiedName() [4/6]
souffle::AstQualifiedName::AstQualifiedName (const std::vector< std::string > qualifiers) inline
Definition at line 39 of file QualifiedName.h.
References AstQualifiedName(), and operator=().
 : qualifiers(qualifiers) {}
AstQualifiedName() [5/6]
souffle::AstQualifiedName::AstQualifiedName (const AstQualifiedName &) default
AstQualifiedName() [6/6]
souffle::AstQualifiedName::AstQualifiedName (AstQualifiedName &&) default
Member Function Documentation
append()
void souffle::AstQualifiedName::append (std::string name) inline
append qualifiers
Definition at line 46 of file QualifiedName.h.
References qualifiers.
Referenced by souffle::AstSemanticCheckerImpl::AstSemanticCheckerImpl(), souffle::createAdornedIdentifier(), souffle::createMagicIdentifier(), souffle::createSubIdentifier(), and souffle::makeRelationName().
{
         qualifiers.push_back(std::move(name));
     }
empty()
bool souffle::AstQualifiedName::empty () const inline
check for emptiness
Definition at line 56 of file QualifiedName.h.
References qualifiers.
Referenced by souffle::AstComponentChecker::checkComponentNameReference(), and souffle::ComponentLookup::getComponent().
{
         return qualifiers.empty();
     }
getQualifiers()
const std::vector<std::string>& souffle::AstQualifiedName::getQualifiers () const inline
get qualifiers
Definition at line 61 of file QualifiedName.h.
References qualifiers.
Referenced by souffle::createAdornedIdentifier(), souffle::createMagicIdentifier(), souffle::createSubIdentifier(), souffle::extractAdornment(), souffle::IODefaultsTransformer::getRelationName(), souffle::IOAttributesTransformer::getRelationName(), souffle::isAggRel(), and souffle::MagicSetTransformer::transform().
{
         return qualifiers;
     }
operator!=()
bool souffle::AstQualifiedName::operator!= (const AstQualifiedName & other) const inline
Definition at line 76 of file QualifiedName.h.
{
         return !(*this == other);
     }
operator<()
bool souffle::AstQualifiedName::operator< (const AstQualifiedName & other) const inline
Definition at line 80 of file QualifiedName.h.
References qualifiers.
{
         return std::lexicographical_compare(
                 qualifiers.begin(), qualifiers.end(), other.qualifiers.begin(), other.qualifiers.end());
     }
operator=() [1/2]
AstQualifiedName& souffle::AstQualifiedName::operator= (const AstQualifiedName &) default
Referenced by AstQualifiedName().
operator=() [2/2]
AstQualifiedName& souffle::AstQualifiedName::operator= (AstQualifiedName &&) default
operator==()
bool souffle::AstQualifiedName::operator== (const AstQualifiedName & other) const inline
Definition at line 72 of file QualifiedName.h.
References qualifiers.
{
         return qualifiers == other.qualifiers;
     }
prepend()
void souffle::AstQualifiedName::prepend (std::string name) inline
prepend qualifiers
Definition at line 51 of file QualifiedName.h.
References qualifiers.
Referenced by souffle::MinimiseProgramTransformer::NormalisedClauseRepr::addClauseAtom(), souffle::MinimiseProgramTransformer::NormalisedClauseRepr::addClauseBodyLiteral(), and souffle::operator+().
{
         qualifiers.insert(qualifiers.begin(), std::move(name));
     }
print()
void souffle::AstQualifiedName::print (std::ostream & out) const inline
print qualified name
Definition at line 86 of file QualifiedName.h.
References souffle::join(), and qualifiers.
{
         out << join(qualifiers, ".");
     }
toString()
std::string souffle::AstQualifiedName::toString () const inline
convert to a string separated by fullstop
Definition at line 66 of file QualifiedName.h.
References souffle::join(), qualifiers, and souffle::profile::ss.
Referenced by souffle::AstToRamTranslator::getEvaluationArity(), souffle::AstProfileUseAnalysis::getRelationSize(), and souffle::AstProfileUseAnalysis::hasRelationSize().
{
         std::stringstream ss;
         ss << join(qualifiers, ".");
         return ss.str();
     }
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & out, const AstQualifiedName & id) friend
Definition at line 90 of file QualifiedName.h.
{
         id.print(out);
         return out;
     }
Field Documentation
qualifiers
std::vector<std::string> souffle::AstQualifiedName::qualifiers private
Definition at line 97 of file QualifiedName.h.
Referenced by append(), empty(), getQualifiers(), operator<(), operator==(), prepend(), print(), and toString().
The documentation for this class was generated from the following file:
ast/QualifiedName.h