souffle: souffle::PiggyList< T > Class Template Reference
souffle::PiggyList< T > Class Template Reference
#include <PiggyList.h>
Data Structures
class iterator
Public Member Functions
size_t append (T element)
iterator begin ()
void clear ()
Clear all elements from the PiggyList.
size_t createNode ()
iterator end ()
void freeList ()
Free the arrays allocated within the linked list nodes.
T & get (size_t index) const
Retrieve a reference to the stored value at index.
T * getBlock (size_t blocknum) const
PiggyList & operator= (const PiggyList &other)=delete
copy assign ctor
PiggyList ()
PiggyList (size_t initialbitsize)
PiggyList (const PiggyList &other)
copy constructor
PiggyList (PiggyList &&other)=delete
move constructor
size_t size () const
Well, returns the number of nodes exist within the list + number of nodes queued to be inserted The reason for this, is that there may be many nodes queued up that haven't had time to had containers created and updated.
~PiggyList ()
Data Fields
size_t allocsize = BLOCKSIZE
const size_t BLOCKBITS = 16ul
std::array< T *, max_conts > blockLookupTable = {}
const size_t BLOCKSIZE = (1ul << BLOCKBITS)
std::atomic< size_t > container_size = 0
std::atomic< size_t > m_size = 0
std::atomic< size_t > num_containers = 0
SpinLock sl
Static Public Attributes
static constexpr size_t max_conts = 64
Detailed Description
template<class T>
class souffle::PiggyList< T >
Definition at line 140 of file PiggyList.h.
Constructor & Destructor Documentation
PiggyList() [1/4]
template<class T> souffle::PiggyList< T >::PiggyList () inline
Definition at line 142 of file PiggyList.h.
 : num_containers(0), container_size(0), m_size(0) {}
PiggyList() [2/4]
template<class T> souffle::PiggyList< T >::PiggyList (size_t initialbitsize) inline
Definition at line 143 of file PiggyList.h.
             : BLOCKBITS(initialbitsize), num_containers(0), container_size(0), m_size(0) {}
PiggyList() [3/4]
template<class T> souffle::PiggyList< T >::PiggyList (const PiggyList< T > & other) inline
copy constructor
Definition at line 147 of file PiggyList.h.
                                       : BLOCKBITS(other.BLOCKBITS) {
         num_containers.store(other.num_containers.load());
         container_size.store(other.container_size.load());
         m_size.store(other.m_size.load());
         // copy each chunk from other into this
         // the size of the next container to allocate
         size_t cSize = BLOCKSIZE;
         for (size_t i = 0; i < other.num_containers; ++i) {
             this->blockLookupTable[i] = new T[cSize];
             std::memcpy(this->blockLookupTable[i], other.blockLookupTable[i], cSize * sizeof(T));
             cSize <<= 1;
         }
         // if this isn't the case, uhh
         assert((cSize >> 1) == container_size.load());
     }
PiggyList() [4/4]
template<class T> souffle::PiggyList< T >::PiggyList (PiggyList< T > && other) delete
move constructor
~PiggyList()
template<class T> souffle::PiggyList< T >::~PiggyList () inline
Definition at line 168 of file PiggyList.h.
                  {
         freeList();
     }
Member Function Documentation
append()
template<class T> size_t souffle::PiggyList< T >::append (T element) inline
Definition at line 186 of file PiggyList.h.
Referenced by souffle::EquivalenceRelation< t_tuple< 2 > >::genAllDisjointSetLists(), and souffle::test::TEST().
{
         size_t new_index = m_size.fetch_add(1, std::memory_order_acquire);
         // will this not fit?
         if (container_size < new_index + 1) {
             sl.lock();
             // check and add as many containers as required
             while (container_size < new_index + 1) {
                 blockLookupTable[num_containers] = new T[allocsize];
                 num_containers += 1;
                 container_size += allocsize;
                 // double the number elements that will be allocated next time
                 allocsize <<= 1;
             }
             sl.unlock();
         }
         this->get(new_index) = element;
         return new_index;
     }
begin()
template<class T> iterator souffle::PiggyList< T >::begin () inline
Definition at line 292 of file PiggyList.h.
Referenced by souffle::test::TEST().
                      {
         return iterator(this);
     }
clear()
template<class T> void souffle::PiggyList< T >::clear () inline
Clear all elements from the PiggyList.
Definition at line 243 of file PiggyList.h.
Referenced by souffle::DisjointSet::clear(), and souffle::test::TEST().
                  {
         freeList();
         m_size = 0;
         num_containers = 0;
         allocsize = BLOCKSIZE;
         container_size = 0;
     }
createNode()
template<class T> size_t souffle::PiggyList< T >::createNode () inline
Definition at line 207 of file PiggyList.h.
Referenced by souffle::DisjointSet::makeNode(), and souffle::test::TEST().
{
         size_t new_index = m_size.fetch_add(1, std::memory_order_acquire);
         // will this not fit?
         if (container_size < new_index + 1) {
             sl.lock();
             // check and add as many containers as required
             while (container_size < new_index + 1) {
                 blockLookupTable[num_containers] = new T[allocsize];
                 num_containers += 1;
                 container_size += allocsize;
                 // double the number elements that will be allocated next time
                 allocsize <<= 1;
             }
             sl.unlock();
         }
         return new_index;
     }
end()
template<class T> iterator souffle::PiggyList< T >::end () inline
Definition at line 295 of file PiggyList.h.
Referenced by souffle::test::TEST().
                    {
         return iterator(this, size());
     }
freeList()
template<class T> void souffle::PiggyList< T >::freeList () inline
Free the arrays allocated within the linked list nodes.
Definition at line 317 of file PiggyList.h.
                     {
         sl.lock();
         // we don't know which ones are taken up!
         for (size_t i = 0; i < num_containers; ++i) {
             delete[] blockLookupTable[i];
         }
         sl.unlock();
     }
get()
template<class T> T& souffle::PiggyList< T >::get (size_t index) const inline
Retrieve a reference to the stored value at index.
Parameters
index position to search
Returns
the value at index
Definition at line 232 of file PiggyList.h.
Referenced by souffle::DisjointSet::get(), souffle::EquivalenceRelation< t_tuple< 2 > >::insertAll(), souffle::DisjointSet::makeNode(), souffle::PiggyList< T >::iterator::operator*(), and souffle::test::TEST().
{
         // supa fast 2^16 size first block
         size_t nindex = index + BLOCKSIZE;
         size_t blockNum = (63 - __builtin_clzll(nindex));
         size_t blockInd = (nindex) & ((1 << blockNum) - 1);
         return this->getBlock(blockNum - BLOCKBITS)[blockInd];
     }
getBlock()
template<class T> T* souffle::PiggyList< T >::getBlock (size_t blocknum) const inline
Definition at line 182 of file PiggyList.h.
{
         return this->blockLookupTable[blocknum];
     }
operator=()
template<class T> PiggyList& souffle::PiggyList< T >::operator= (const PiggyList< T > & other) delete
copy assign ctor
size()
template<class T> size_t souffle::PiggyList< T >::size () const inline
Well, returns the number of nodes exist within the list + number of nodes queued to be inserted The reason for this, is that there may be many nodes queued up that haven't had time to had containers created and updated.
Returns
the number of nodes exist within the list + number of nodes queued to be inserted
Definition at line 178 of file PiggyList.h.
Referenced by souffle::EquivalenceRelation< t_tuple< 2 > >::genAllDisjointSetLists(), souffle::EquivalenceRelation< t_tuple< 2 > >::insertAll(), souffle::DisjointSet::size(), and souffle::test::TEST().
{
         return m_size.load();
     };
Field Documentation
allocsize
template<class T> size_t souffle::PiggyList< T >::allocsize = BLOCKSIZE
Definition at line 303 of file PiggyList.h.
BLOCKBITS
template<class T> const size_t souffle::PiggyList< T >::BLOCKBITS = 16ul
Definition at line 298 of file PiggyList.h.
blockLookupTable
template<class T> std::array<T*, max_conts> souffle::PiggyList< T >::blockLookupTable = {}
Definition at line 309 of file PiggyList.h.
Referenced by souffle::PiggyList< std::atomic< block_t > >::PiggyList().
BLOCKSIZE
template<class T> const size_t souffle::PiggyList< T >::BLOCKSIZE = (1ul << BLOCKBITS)
Definition at line 299 of file PiggyList.h.
container_size
template<class T> std::atomic<size_t> souffle::PiggyList< T >::container_size = 0
Definition at line 304 of file PiggyList.h.
Referenced by souffle::PiggyList< std::atomic< block_t > >::PiggyList().
m_size
template<class T> std::atomic<size_t> souffle::PiggyList< T >::m_size = 0
Definition at line 305 of file PiggyList.h.
Referenced by souffle::PiggyList< std::atomic< block_t > >::PiggyList().
max_conts
template<class T> constexpr size_t souffle::PiggyList< T >::max_conts = 64 static
Definition at line 308 of file PiggyList.h.
num_containers
template<class T> std::atomic<size_t> souffle::PiggyList< T >::num_containers = 0
Definition at line 302 of file PiggyList.h.
Referenced by souffle::PiggyList< std::atomic< block_t > >::PiggyList().
sl
template<class T> SpinLock souffle::PiggyList< T >::sl mutable
Definition at line 312 of file PiggyList.h.
The documentation for this class was generated from the following file:
PiggyList.h