souffle: souffle::IOSystem Class Reference
souffle::IOSystem Class Reference
#include <IOSystem.h>
Public Member Functions
std::unique_ptr< ReadStream > getReader (const std::map< std::string, std::string > &rwOperation, SymbolTable &symbolTable, RecordTable &recordTable) const
Return a new ReadStream.
std::unique_ptr< WriteStream > getWriter (const std::map< std::string, std::string > &rwOperation, const SymbolTable &symbolTable, const RecordTable &recordTable) const
Return a new WriteStream.
void registerReadStreamFactory (const std::shared_ptr< ReadStreamFactory > &factory)
void registerWriteStreamFactory (const std::shared_ptr< WriteStreamFactory > &factory)
~IOSystem ()=default
Static Public Member Functions
static IOSystem & getInstance ()
Private Member Functions
IOSystem ()
Private Attributes
std::map< std::string, std::shared_ptr< ReadStreamFactory > > inputFactories
std::map< std::string, std::shared_ptr< WriteStreamFactory > > outputFactories
Detailed Description
Definition at line 39 of file IOSystem.h.
Constructor & Destructor Documentation
~IOSystem()
souffle::IOSystem::~IOSystem () default
Referenced by getReader().
IOSystem()
souffle::IOSystem::IOSystem () inline private
Definition at line 79 of file IOSystem.h.
References registerReadStreamFactory(), and registerWriteStreamFactory().
                {
         registerReadStreamFactory(std::make_shared<ReadFileCSVFactory>());
         registerReadStreamFactory(std::make_shared<ReadCinCSVFactory>());
         registerReadStreamFactory(std::make_shared<ReadFileJSONFactory>());
         registerReadStreamFactory(std::make_shared<ReadCinJSONFactory>());
         registerWriteStreamFactory(std::make_shared<WriteFileCSVFactory>());
         registerWriteStreamFactory(std::make_shared<WriteCoutCSVFactory>());
         registerWriteStreamFactory(std::make_shared<WriteCoutPrintSizeFactory>());
         registerWriteStreamFactory(std::make_shared<WriteFileJSONFactory>());
         registerWriteStreamFactory(std::make_shared<WriteCoutJSONFactory>());
 #ifdef USE_SQLITE
         registerReadStreamFactory(std::make_shared<ReadSQLiteFactory>());
         registerWriteStreamFactory(std::make_shared<WriteSQLiteFactory>());
 #endif
     };
Member Function Documentation
getInstance()
static IOSystem& souffle::IOSystem::getInstance () inline static
Definition at line 41 of file IOSystem.h.
Referenced by souffle::InterpreterEngine::execute().
{
         static IOSystem singleton;
         return singleton;
     }
getReader()
std::unique_ptr<ReadStream> souffle::IOSystem::getReader (const std::map< std::string, std::string > & rwOperation, SymbolTable & symbolTable, RecordTable & recordTable) const inline
Return a new ReadStream.
Definition at line 68 of file IOSystem.h.
References inputFactories, and ~IOSystem().
Referenced by souffle::InterpreterEngine::execute().
{
         std::string ioType = rwOperation.at("IO");
         if (inputFactories.count(ioType) == 0) {
             throw std::invalid_argument("Requested input type <" + ioType + "> is not supported.");
         }
         return inputFactories.at(ioType)->getReader(rwOperation, symbolTable, recordTable);
     }
getWriter()
std::unique_ptr<WriteStream> souffle::IOSystem::getWriter (const std::map< std::string, std::string > & rwOperation, const SymbolTable & symbolTable, const RecordTable & recordTable) const inline
Return a new WriteStream.
Definition at line 57 of file IOSystem.h.
References outputFactories.
Referenced by souffle::InterpreterEngine::execute().
{
         std::string ioType = rwOperation.at("IO");
         if (outputFactories.count(ioType) == 0) {
             throw std::invalid_argument("Requested output type <" + ioType + "> is not supported.");
         }
         return outputFactories.at(ioType)->getWriter(rwOperation, symbolTable, recordTable);
     }
registerReadStreamFactory()
void souffle::IOSystem::registerReadStreamFactory (const std::shared_ptr< ReadStreamFactory > & factory) inline
Definition at line 50 of file IOSystem.h.
References inputFactories.
Referenced by IOSystem().
{
         inputFactories[factory->getName()] = factory;
     }
registerWriteStreamFactory()
void souffle::IOSystem::registerWriteStreamFactory (const std::shared_ptr< WriteStreamFactory > & factory) inline
Definition at line 46 of file IOSystem.h.
References outputFactories.
Referenced by IOSystem().
{
         outputFactories[factory->getName()] = factory;
     }
Field Documentation
inputFactories
std::map<std::string, std::shared_ptr<ReadStreamFactory> > souffle::IOSystem::inputFactories private
Definition at line 95 of file IOSystem.h.
Referenced by getReader(), and registerReadStreamFactory().
outputFactories
std::map<std::string, std::shared_ptr<WriteStreamFactory> > souffle::IOSystem::outputFactories private
Definition at line 93 of file IOSystem.h.
Referenced by getWriter(), and registerWriteStreamFactory().
The documentation for this class was generated from the following file:
IOSystem.h