souffle: souffle::RamNestedOperation Class Reference
souffle::RamNestedOperation Class Reference abstract
Abstract class for a nesting operations in a loop-nest.
#include <Operation.h>
Public Member Functions
void apply (const RamNodeMapper &map) override
Apply the mapper to all child nodes.
RamNestedOperation * clone () const override=0
Create a clone (i.e.
std::vector< const RamNode * > getChildNodes () const override
Obtain list of all embedded child nodes.
RamOperation & getOperation () const
Get nested operation.
const std::string & getProfileText () const
Get profile text.
RamNestedOperation (std::unique_ptr< RamOperation > nested, std::string profileText="")
Public Member Functions inherited from souffle::RamNode
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
virtual void rewrite (const RamNode *oldNode, std::unique_ptr< RamNode > newNode)
Rewrite a child node.
virtual ~RamNode ()=default
Protected Member Functions
bool equal (const RamNode &node) const override
Equality check for two RAM nodes.
void print (std::ostream &os, int tabpos) const override
Pretty print with indentation.
Protected Member Functions inherited from souffle::RamOperation
void print (std::ostream &os) const override
Print RAM node.
Protected Attributes
std::unique_ptr< RamOperation > nestedOperation
Nested operation.
const std::string profileText
Text used by the profiler.
Additional Inherited Members
Static Protected Member Functions inherited from souffle::RamOperation
static void print (const RamOperation *operation, std::ostream &os, int tabpos)
Pretty print jump-bed.
Detailed Description
Abstract class for a nesting operations in a loop-nest.
In the following example, the nested operation of "IF C1" is "IF C2":
QUERY
 ...
  IF C1
   IF C2
    ...
TODO (b-scholz): profile text is awkward; perhaps there is a better way of storing profile information for RAM operations since it is not always used for all RAM operations.
Definition at line 90 of file Operation.h.
Constructor & Destructor Documentation
RamNestedOperation()
souffle::RamNestedOperation::RamNestedOperation (std::unique_ptr< RamOperation > nested, std::string profileText = "") inline
Definition at line 92 of file Operation.h.
References souffle::RamOperation::clone().
             : nestedOperation(std::move(nested)), profileText(std::move(profileText)) {
         assert(nullptr != nestedOperation);
     }
Member Function Documentation
apply()
void souffle::RamNestedOperation::apply (const RamNodeMapper &) inline override virtual
Apply the mapper to all child nodes.
Reimplemented from souffle::RamNode.
Reimplemented in souffle::RamAbstractConditional, souffle::RamUnpackRecord, souffle::RamNestedIntrinsicOperator, souffle::RamIndexAggregate, souffle::RamAggregate, souffle::RamIndexChoice, souffle::RamChoice, souffle::RamIndexOperation, and souffle::RamRelationOperation.
Definition at line 113 of file Operation.h.
References souffle::map().
Referenced by souffle::RamRelationOperation::apply(), souffle::RamNestedIntrinsicOperator::apply(), souffle::RamUnpackRecord::apply(), souffle::RamAbstractConditional::apply(), and souffle::HoistConditionsTransformer::hoistConditions().
{
         nestedOperation = map(std::move(nestedOperation));
     }
clone()
RamNestedOperation* souffle::RamNestedOperation::clone () const override pure virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::RamOperation.
Implemented in souffle::RamBreak, souffle::RamFilter, souffle::RamAbstractConditional, souffle::RamUnpackRecord, souffle::RamNestedIntrinsicOperator, souffle::RamParallelIndexAggregate, souffle::RamIndexAggregate, souffle::RamParallelAggregate, souffle::RamAggregate, souffle::RamParallelIndexChoice, souffle::RamIndexChoice, souffle::RamParallelChoice, souffle::RamChoice, souffle::RamParallelIndexScan, souffle::RamIndexScan, souffle::RamIndexOperation, souffle::RamParallelScan, souffle::RamScan, souffle::RamRelationOperation, and souffle::RamTupleOperation.
equal()
bool souffle::RamNestedOperation::equal (const RamNode &) const inline override protected virtual
Equality check for two RAM nodes.
Default action is that nothing needs to be checked.
Reimplemented from souffle::RamNode.
Reimplemented in souffle::RamAbstractConditional, souffle::RamUnpackRecord, souffle::RamNestedIntrinsicOperator, souffle::RamIndexAggregate, souffle::RamAggregate, souffle::RamIndexChoice, souffle::RamChoice, souffle::RamIndexOperation, souffle::RamRelationOperation, and souffle::RamTupleOperation.
Definition at line 122 of file Operation.h.
References souffle::equal_ptr().
Referenced by souffle::RamTupleOperation::equal(), and souffle::RamAbstractConditional::equal().
{
         const auto& other = static_cast<const RamNestedOperation&>(node);
         return equal_ptr(nestedOperation, other.nestedOperation) && profileText == other.profileText;
     }
getChildNodes()
std::vector<const RamNode*> souffle::RamNestedOperation::getChildNodes () const inline override virtual
Obtain list of all embedded child nodes.
Reimplemented from souffle::RamNode.
Reimplemented in souffle::RamAbstractConditional, souffle::RamUnpackRecord, souffle::RamNestedIntrinsicOperator, souffle::RamIndexAggregate, souffle::RamAggregate, souffle::RamIndexChoice, souffle::RamChoice, souffle::RamIndexOperation, souffle::RamRelationOperation, and souffle::RamTupleOperation.
Definition at line 109 of file Operation.h.
Referenced by souffle::RamTupleOperation::getChildNodes(), and souffle::RamAbstractConditional::getChildNodes().
{
         return {nestedOperation.get()};
     }
getOperation()
RamOperation& souffle::RamNestedOperation::getOperation () const inline
Get nested operation.
Definition at line 100 of file Operation.h.
Referenced by souffle::CollapseFiltersTransformer::collapseFilters(), souffle::Synthesiser::emitCode(), souffle::MakeIndexTransformer::rewriteAggregate(), souffle::IfConversionTransformer::rewriteIndexScan(), souffle::ChoiceConversionTransformer::rewriteIndexScan(), souffle::MakeIndexTransformer::rewriteIndexScan(), souffle::ChoiceConversionTransformer::rewriteScan(), souffle::MakeIndexTransformer::rewriteScan(), souffle::NodeGenerator::visitNestedOperation(), and souffle::NodeGenerator::visitTupleOperation().
{
         return *nestedOperation;
     }
getProfileText()
const std::string& souffle::RamNestedOperation::getProfileText () const inline
Get profile text.
Definition at line 105 of file Operation.h.
Referenced by souffle::CollapseFiltersTransformer::collapseFilters(), souffle::Synthesiser::emitCode(), souffle::InterpreterEngine::executeMain(), souffle::IfConversionTransformer::rewriteIndexScan(), souffle::ChoiceConversionTransformer::rewriteIndexScan(), souffle::MakeIndexTransformer::rewriteIndexScan(), souffle::ChoiceConversionTransformer::rewriteScan(), and souffle::MakeIndexTransformer::rewriteScan().
{
         return profileText;
     }
print()
void souffle::RamNestedOperation::print (std::ostream & os, int tabpos) const inline override protected virtual
Pretty print with indentation.
Implements souffle::RamOperation.
Reimplemented in souffle::RamBreak, souffle::RamFilter, souffle::RamUnpackRecord, souffle::RamNestedIntrinsicOperator, souffle::RamParallelIndexAggregate, souffle::RamIndexAggregate, souffle::RamParallelAggregate, souffle::RamAggregate, souffle::RamParallelIndexChoice, souffle::RamIndexChoice, souffle::RamParallelChoice, souffle::RamChoice, souffle::RamParallelIndexScan, souffle::RamIndexScan, souffle::RamParallelScan, and souffle::RamScan.
Definition at line 118 of file Operation.h.
References souffle::RamOperation::print().
Referenced by souffle::RamScan::print(), souffle::RamParallelScan::print(), souffle::RamIndexScan::print(), souffle::RamParallelIndexScan::print(), souffle::RamChoice::print(), souffle::RamParallelChoice::print(), souffle::RamIndexChoice::print(), souffle::RamParallelIndexChoice::print(), souffle::RamAggregate::print(), souffle::RamParallelAggregate::print(), souffle::RamIndexAggregate::print(), souffle::RamParallelIndexAggregate::print(), souffle::RamNestedIntrinsicOperator::print(), souffle::RamUnpackRecord::print(), souffle::RamFilter::print(), and souffle::RamBreak::print().
{
         RamOperation::print(nestedOperation.get(), os, tabpos);
     }
Field Documentation
nestedOperation
std::unique_ptr<RamOperation> souffle::RamNestedOperation::nestedOperation protected
Nested operation.
Definition at line 128 of file Operation.h.
profileText
const std::string souffle::RamNestedOperation::profileText protected
Text used by the profiler.
Definition at line 131 of file Operation.h.
The documentation for this class was generated from the following file:
ram/Operation.h