souffle: souffle::AstTerm Class Reference
souffle::AstTerm Class Reference
Abstract Term.
#include <Term.h>
Public Member Functions
void addArgument (Own< AstArgument > arg)
add argument to argument list
void apply (const AstNodeMapper &map) override
Apply the mapper to all child nodes.
std::vector< AstArgument * > getArguments () const
get arguments
std::vector< const AstNode * > getChildNodes () const override
Obtain a list of all embedded AST child nodes.
Public Member Functions inherited from souffle::AstArgument
AstArgument * clone () const override=0
Create clone.
Public Member Functions inherited from souffle::AstNode
AstNode (SrcLocation loc={})
std::string extloc () const
Return source location of the syntactic element.
const SrcLocation & getSrcLoc () const
Return source location of the AstNode.
bool operator!= (const AstNode &other) const
Inequality check for two AST nodes.
bool operator== (const AstNode &other) const
Equivalence check for two AST nodes.
void setSrcLoc (SrcLocation l)
Set source location for the AstNode.
virtual ~AstNode ()=default
Protected Member Functions
template<typename... Operands>
AstTerm (Operands &&... operands)
template<typename... Operands>
AstTerm (SrcLocation loc, Operands &&... operands)
AstTerm (VecOwn< AstArgument > operands, SrcLocation loc={})
bool equal (const AstNode &node) const override
Abstract equality check for two AST nodes.
Protected Member Functions inherited from souffle::AstNode
virtual void print (std::ostream &os) const =0
Output to a given output stream.
Protected Attributes
VecOwn< AstArgument > args
Arguments.
Static Private Member Functions
template<typename... Operands>
static VecOwn< AstArgument > asVec (Operands... ops)
Detailed Description
Abstract Term.
Definition at line 33 of file Term.h.
Constructor & Destructor Documentation
AstTerm() [1/3]
template<typename... Operands> souffle::AstTerm::AstTerm (Operands &&... operands) inline protected
Definition at line 36 of file Term.h.
Referenced by souffle::AstRecordInit::AstRecordInit().
 : AstTerm(asVec(std::forward<Operands>(operands)...)) {}
AstTerm() [2/3]
template<typename... Operands> souffle::AstTerm::AstTerm (SrcLocation loc, Operands &&... operands) inline protected
Definition at line 39 of file Term.h.
             : AstTerm(asVec(std::forward<Operands>(operands)...), std::move(loc)) {}
AstTerm() [3/3]
souffle::AstTerm::AstTerm (VecOwn< AstArgument > operands, SrcLocation loc = {}) inline protected
Definition at line 42 of file Term.h.
References args.
                                                             {})
             : AstArgument(std::move(loc)), args(std::move(operands)) {}
Member Function Documentation
addArgument()
void souffle::AstTerm::addArgument (Own< AstArgument > arg) inline
add argument to argument list
Definition at line 52 of file Term.h.
References args.
{
         args.push_back(std::move(arg));
     }
apply()
void souffle::AstTerm::apply (const AstNodeMapper &) inline override virtual
Apply the mapper to all child nodes.
Reimplemented from souffle::AstNode.
Definition at line 64 of file Term.h.
References args, and souffle::map().
{
         for (auto& arg : args) {
             arg = map(std::move(arg));
         }
     }
asVec()
template<typename... Operands> static VecOwn<AstArgument> souffle::AstTerm::asVec (Operands... ops) inline static private
Definition at line 81 of file Term.h.
{
         Own<AstArgument> ary[] = {std::move(ops)...};
         VecOwn<AstArgument> xs;
         for (auto&& x : ary) {
             xs.push_back(std::move(x));
         }
         return xs;
     }
equal()
bool souffle::AstTerm::equal (const AstNode &) const inline override protected virtual
Abstract equality check for two AST nodes.
Reimplemented from souffle::AstNode.
Reimplemented in souffle::AstUserDefinedFunctor.
Definition at line 71 of file Term.h.
References args, and souffle::equal_targets().
Referenced by souffle::AstUserDefinedFunctor::equal(), and souffle::AstIntrinsicFunctor::equal().
{
         const auto& other = static_cast<const AstTerm&>(node);
         return equal_targets(args, other.args);
     }
getArguments()
std::vector<AstArgument*> souffle::AstTerm::getArguments () const inline
get arguments
Definition at line 47 of file Term.h.
References args, and souffle::toPtrVector().
Referenced by souffle::AstSemanticCheckerImpl::checkLiteral(), souffle::getGroundedTerms(), souffle::ResolveAliasesTransformer::removeComplexTermsInAtoms(), souffle::ResolveAliasesTransformer::resolveAliases(), souffle::AstToRamTranslator::translateValue(), souffle::validOverloads(), souffle::TypeConstraintsAnalysis::visitFunctor(), souffle::TypeChecker::visitIntrinsicFunctor(), souffle::TypeChecker::visitRecordInit(), souffle::TypeConstraintsAnalysis::visitRecordInit(), and souffle::TypeChecker::visitUserDefinedFunctor().
{
         return toPtrVector(args);
     }
getChildNodes()
std::vector<const AstNode*> souffle::AstTerm::getChildNodes () const inline override virtual
Obtain a list of all embedded AST child nodes.
Reimplemented from souffle::AstNode.
Definition at line 56 of file Term.h.
References args, and souffle::AstNode::getChildNodes().
{
         auto res = AstArgument::getChildNodes();
         for (auto& cur : args) {
             res.push_back(cur.get());
         }
         return res;
     }
Field Documentation
args
VecOwn<AstArgument> souffle::AstTerm::args protected
Arguments.
Definition at line 77 of file Term.h.
Referenced by addArgument(), apply(), AstTerm(), souffle::AstRecordInit::clone(), equal(), getArguments(), getChildNodes(), and souffle::AstRecordInit::print().
The documentation for this class was generated from the following file:
ast/Term.h