souffle: souffle::WriteFileCSV Class Reference
souffle::WriteFileCSV Class Reference
#include <WriteStreamCSV.h>
Public Member Functions
WriteFileCSV (const std::map< std::string, std::string > &rwOperation, const SymbolTable &symbolTable, const RecordTable &recordTable)
~WriteFileCSV () override=default
Public Member Functions inherited from souffle::WriteStream
template<typename T >
void writeAll (const T &relation)
template<>
void writeNext (const RamDomain *tuple)
template<typename T >
void writeSize (const T &relation)
WriteStream (const std::map< std::string, std::string > &rwOperation, const SymbolTable &symbolTable, const RecordTable &recordTable)
Public Member Functions inherited from souffle::SerialisationStream< true >
virtual ~SerialisationStream ()=default
Protected Member Functions
void writeNextTuple (const RamDomain *tuple) override
void writeNullary () override
Protected Member Functions inherited from souffle::WriteStreamCSV
void writeNextTupleCSV (std::ostream &destination, const RamDomain *tuple)
void writeNextTupleElement (std::ostream &destination, const std::string &type, RamDomain value)
WriteStreamCSV (const std::map< std::string, std::string > &rwOperation, const SymbolTable &symbolTable, const RecordTable &recordTable)
Protected Member Functions inherited from souffle::WriteStream
void outputRecord (std::ostream &destination, const RamDomain value, const std::string &name)
template<typename Tuple >
void writeNext (const Tuple tuple)
virtual void writeSize (std::size_t)
Protected Member Functions inherited from souffle::SerialisationStream< true >
SerialisationStream (RO< SymbolTable > &symTab, RO< RecordTable > &recTab, Json types, std::vector< std::string > relTypes, size_t auxArity=0)
SerialisationStream (RO< SymbolTable > &symTab, RO< RecordTable > &recTab, Json types)
SerialisationStream (RO< SymbolTable > &symTab, RO< RecordTable > &recTab, const std::map< std::string, std::string > &rwOperation)
Static Protected Member Functions
static std::string getFileName (const std::map< std::string, std::string > &rwOperation)
Return given filename or construct from relation name.
Protected Attributes
std::ofstream file
Protected Attributes inherited from souffle::WriteStreamCSV
const std::string delimiter
Protected Attributes inherited from souffle::WriteStream
const bool summary
Protected Attributes inherited from souffle::SerialisationStream< true >
size_t arity
size_t auxiliaryArity
RO< RecordTable > & recordTable
RO< SymbolTable > & symbolTable
std::vector< std::string > typeAttributes
Json types
Additional Inherited Members
Protected Types inherited from souffle::SerialisationStream< true >
using RO = std::conditional_t< readOnlyTables, const A, A >
Detailed Description
Definition at line 71 of file WriteStreamCSV.h.
Constructor & Destructor Documentation
WriteFileCSV()
souffle::WriteFileCSV::WriteFileCSV (const std::map< std::string, std::string > & rwOperation, const SymbolTable & symbolTable, const RecordTable & recordTable) inline
Definition at line 73 of file WriteStreamCSV.h.
References souffle::getOr().
             : WriteStreamCSV(rwOperation, symbolTable, recordTable),
               file(getFileName(rwOperation), std::ios::out | std::ios::binary) {
         if (getOr(rwOperation, "headers", "false") == "true") {
             file << rwOperation.at("attributeNames") << std::endl;
         }
         file << std::setprecision(std::numeric_limits<RamFloat>::max_digits10);
     }
~WriteFileCSV()
souffle::WriteFileCSV::~WriteFileCSV () override default
Member Function Documentation
getFileName()
static std::string souffle::WriteFileCSV::getFileName (const std::map< std::string, std::string > & rwOperation) inline static protected
Return given filename or construct from relation name.
Default name is [configured path]/[relation name].csv
Parameters
rwOperation map of IO configuration options
Returns
input filename
Definition at line 103 of file WriteStreamCSV.h.
References souffle::getOr(), souffle::SerialisationStream< true >::recordTable, souffle::SerialisationStream< true >::symbolTable, souffle::WriteStream::writeNextTuple(), souffle::WriteStreamCSV::writeNextTupleCSV(), souffle::WriteStream::writeNullary(), and souffle::WriteStreamCSV::WriteStreamCSV().
{
         auto name = getOr(rwOperation, "filename", rwOperation.at("name") + ".csv");
         if (name.front() != '/') {
             name = getOr(rwOperation, "output-dir", ".") + "/" + name;
         }
         return name;
     }
writeNextTuple()
void souffle::WriteFileCSV::writeNextTuple (const RamDomain * tuple) inline override protected virtual
Implements souffle::WriteStream.
Definition at line 92 of file WriteStreamCSV.h.
References souffle::WriteStreamCSV::writeNextTupleCSV().
{
         writeNextTupleCSV(file, tuple);
     }
writeNullary()
void souffle::WriteFileCSV::writeNullary () inline override protected virtual
Implements souffle::WriteStream.
Definition at line 88 of file WriteStreamCSV.h.
{
         file << "()\n";
     }
Field Documentation
file
std::ofstream souffle::WriteFileCSV::file protected
Definition at line 86 of file WriteStreamCSV.h.
The documentation for this class was generated from the following file:
WriteStreamCSV.h