souffle: souffle::AstExecutionPlan Class Reference
souffle::AstExecutionPlan Class Reference
The class utilized to model user-defined execution plans for various versions of clauses.
#include <ExecutionPlan.h>
Public Member Functions
void apply (const AstNodeMapper &map) override
Apply the mapper to all child nodes.
AstExecutionPlan * clone () const override
Create a clone (i.e.
std::vector< const AstNode * > getChildNodes () const override
Obtain a list of all embedded AST child nodes.
std::map< int, const AstExecutionOrder * > getOrders () const
get orders
void setOrderFor (int version, Own< AstExecutionOrder > plan)
updates execution order for rule version
Public Member Functions inherited from souffle::AstNode
AstNode (SrcLocation loc={})
std::string extloc () const
Return source location of the syntactic element.
const SrcLocation & getSrcLoc () const
Return source location of the AstNode.
bool operator!= (const AstNode &other) const
Inequality check for two AST nodes.
bool operator== (const AstNode &other) const
Equivalence check for two AST nodes.
void setSrcLoc (SrcLocation l)
Set source location for the AstNode.
virtual ~AstNode ()=default
Protected Member Functions
bool equal (const AstNode &node) const override
Abstract equality check for two AST nodes.
void print (std::ostream &out) const override
Output to a given output stream.
Private Attributes
std::map< int, Own< AstExecutionOrder > > plans
mapping versions of clauses to execution plans
Detailed Description
The class utilized to model user-defined execution plans for various versions of clauses.
Definition at line 37 of file ExecutionPlan.h.
Member Function Documentation
apply()
void souffle::AstExecutionPlan::apply (const AstNodeMapper &) inline override virtual
Apply the mapper to all child nodes.
Reimplemented from souffle::AstNode.
Definition at line 62 of file ExecutionPlan.h.
References souffle::map(), and plans.
{
         for (auto& plan : plans) {
             plan.second = map(std::move(plan.second));
         }
     }
clone()
AstExecutionPlan* souffle::AstExecutionPlan::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::AstNode.
Definition at line 53 of file ExecutionPlan.h.
References souffle::AstNode::getSrcLoc(), and plans.
{
         auto res = new AstExecutionPlan();
         res->setSrcLoc(getSrcLoc());
         for (auto& plan : plans) {
             res->setOrderFor(plan.first, Own<AstExecutionOrder>(plan.second->clone()));
         }
         return res;
     }
equal()
bool souffle::AstExecutionPlan::equal (const AstNode &) const inline override protected virtual
Abstract equality check for two AST nodes.
Reimplemented from souffle::AstNode.
Definition at line 85 of file ExecutionPlan.h.
References souffle::equal_targets(), and plans.
{
         const auto& other = static_cast<const AstExecutionPlan&>(node);
         return equal_targets(plans, other.plans);
     }
getChildNodes()
std::vector<const AstNode*> souffle::AstExecutionPlan::getChildNodes () const inline override virtual
Obtain a list of all embedded AST child nodes.
Reimplemented from souffle::AstNode.
Definition at line 68 of file ExecutionPlan.h.
References plans.
{
         std::vector<const AstNode*> childNodes;
         for (auto& plan : plans) {
             childNodes.push_back(plan.second.get());
         }
         return childNodes;
     }
getOrders()
std::map<int, const AstExecutionOrder*> souffle::AstExecutionPlan::getOrders () const inline
get orders
Definition at line 45 of file ExecutionPlan.h.
References plans.
Referenced by souffle::AstSemanticCheckerImpl::checkClause(), and souffle::AstToRamTranslator::ClauseTranslator::getReorderedClause().
{
         std::map<int, const AstExecutionOrder*> result;
         for (auto& plan : plans) {
             result.insert(std::make_pair(plan.first, plan.second.get()));
         }
         return result;
     }
print()
void souffle::AstExecutionPlan::print (std::ostream & os) const inline override protected virtual
Output to a given output stream.
Implements souffle::AstNode.
Definition at line 77 of file ExecutionPlan.h.
References souffle::join(), and plans.
{
         if (!plans.empty()) {
             out << " .plan ";
             out << join(plans, ", ",
                     [](std::ostream& os, const auto& arg) { os << arg.first << ":" << *arg.second; });
         }
     }
setOrderFor()
void souffle::AstExecutionPlan::setOrderFor (int version, Own< AstExecutionOrder > plan) inline
updates execution order for rule version
Definition at line 40 of file ExecutionPlan.h.
References plans.
{
         plans[version] = std::move(plan);
     }
Field Documentation
plans
std::map<int, Own<AstExecutionOrder> > souffle::AstExecutionPlan::plans private
mapping versions of clauses to execution plans
Definition at line 92 of file ExecutionPlan.h.
Referenced by apply(), clone(), equal(), getChildNodes(), getOrders(), print(), and setOrderFor().
The documentation for this class was generated from the following file:
ast/ExecutionPlan.h