souffle: souffle::RamAbstractConditional Class Reference
souffle::RamAbstractConditional Class Reference abstract
Abstract conditional statement.
#include <Operation.h>
Public Member Functions
void apply (const RamNodeMapper &map) override
Apply the mapper to all child nodes.
RamAbstractConditional * clone () const override=0
Create a clone (i.e.
std::vector< const RamNode * > getChildNodes () const override
Obtain list of all embedded child nodes.
const RamCondition & getCondition () const
Get condition that must be satisfied.
RamAbstractConditional (std::unique_ptr< RamCondition > cond, std::unique_ptr< RamOperation > nested, std::string profileText="")
Public Member Functions inherited from souffle::RamNestedOperation
RamOperation & getOperation () const
Get nested operation.
const std::string & getProfileText () const
Get profile text.
RamNestedOperation (std::unique_ptr< RamOperation > nested, std::string profileText="")
Public Member Functions inherited from souffle::RamNode
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
virtual void rewrite (const RamNode *oldNode, std::unique_ptr< RamNode > newNode)
Rewrite a child node.
virtual ~RamNode ()=default
Protected Member Functions
bool equal (const RamNode &node) const override
Equality check for two RAM nodes.
Protected Member Functions inherited from souffle::RamNestedOperation
void print (std::ostream &os, int tabpos) const override
Pretty print with indentation.
Protected Member Functions inherited from souffle::RamOperation
void print (std::ostream &os) const override
Print RAM node.
Protected Attributes
std::unique_ptr< RamCondition > condition
Condition.
Protected Attributes inherited from souffle::RamNestedOperation
std::unique_ptr< RamOperation > nestedOperation
Nested operation.
const std::string profileText
Text used by the profiler.
Additional Inherited Members
Static Protected Member Functions inherited from souffle::RamOperation
static void print (const RamOperation *operation, std::ostream &os, int tabpos)
Pretty print jump-bed.
Detailed Description
Abstract conditional statement.
Definition at line 1157 of file Operation.h.
Constructor & Destructor Documentation
RamAbstractConditional()
souffle::RamAbstractConditional::RamAbstractConditional (std::unique_ptr< RamCondition > cond, std::unique_ptr< RamOperation > nested, std::string profileText = "") inline
Definition at line 1159 of file Operation.h.
References souffle::RamOperation::clone().
             : RamNestedOperation(std::move(nested), std::move(profileText)), condition(std::move(cond)) {
         assert(condition != nullptr && "Condition is a null-pointer");
     }
Member Function Documentation
apply()
void souffle::RamAbstractConditional::apply (const RamNodeMapper &) inline override virtual
Apply the mapper to all child nodes.
Reimplemented from souffle::RamNestedOperation.
Definition at line 1179 of file Operation.h.
References souffle::RamNestedOperation::apply(), and souffle::map().
Referenced by souffle::CollapseFiltersTransformer::collapseFilters().
{
         RamNestedOperation::apply(map);
         condition = map(std::move(condition));
     }
clone()
RamAbstractConditional* souffle::RamAbstractConditional::clone () const override pure virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::RamNestedOperation.
Implemented in souffle::RamBreak, and souffle::RamFilter.
equal()
bool souffle::RamAbstractConditional::equal (const RamNode &) const inline override protected virtual
Equality check for two RAM nodes.
Default action is that nothing needs to be checked.
Reimplemented from souffle::RamNestedOperation.
Definition at line 1185 of file Operation.h.
References souffle::RamNestedOperation::equal(), and souffle::equal_ptr().
{
         const auto& other = static_cast<const RamAbstractConditional&>(node);
         return RamNestedOperation::equal(node) && equal_ptr(condition, other.condition);
     }
getChildNodes()
std::vector<const RamNode*> souffle::RamAbstractConditional::getChildNodes () const inline override virtual
Obtain list of all embedded child nodes.
Reimplemented from souffle::RamNestedOperation.
Definition at line 1173 of file Operation.h.
References souffle::RamNestedOperation::getChildNodes().
{
         auto res = RamNestedOperation::getChildNodes();
         res.push_back(condition.get());
         return res;
     }
getCondition()
const RamCondition& souffle::RamAbstractConditional::getCondition () const inline
Get condition that must be satisfied.
Definition at line 1168 of file Operation.h.
Referenced by souffle::Synthesiser::emitCode(), and souffle::RamLevelAnalysis::getLevel().
{
         assert(condition != nullptr && "condition of conditional operation is a null-pointer");
         return *condition;
     }
Field Documentation
condition
std::unique_ptr<RamCondition> souffle::RamAbstractConditional::condition protected
Condition.
Definition at line 1191 of file Operation.h.
The documentation for this class was generated from the following file:
ram/Operation.h