souffle: souffle::AstProfileUseAnalysis Class Reference
souffle::AstProfileUseAnalysis Class Reference
AstAnalysis that loads profile data and has a profile query interface.
#include <ProfileUse.h>
Public Member Functions
AstProfileUseAnalysis ()
size_t getRelationSize (const AstQualifiedName &rel)
Return size of relation in the profile.
bool hasRelationSize (const AstQualifiedName &rel)
Check whether the relation size exists in profile.
void print (std::ostream &os) const override
Output some profile information.
void run (const AstTranslationUnit &translationUnit) override
Run analysis.
Public Member Functions inherited from souffle::AstAnalysis
AstAnalysis (std::string identifier)
virtual const std::string & getName () const
get name of the analysis
virtual ~AstAnalysis ()=default
Static Public Attributes
static constexpr const char * name = "profile-use"
Name of analysis.
Private Attributes
std::shared_ptr< profile::ProgramRun > programRun
performance model of profile run
Additional Inherited Members
Protected Attributes inherited from souffle::AstAnalysis
const std::string identifier
Detailed Description
AstAnalysis that loads profile data and has a profile query interface.
Definition at line 34 of file ProfileUse.h.
Constructor & Destructor Documentation
AstProfileUseAnalysis()
souffle::AstProfileUseAnalysis::AstProfileUseAnalysis () inline
Definition at line 39 of file ProfileUse.h.
References getRelationSize(), hasRelationSize(), print(), and run().
             : AstAnalysis(name), programRun(std::make_shared<profile::ProgramRun>(profile::ProgramRun())) {}
Member Function Documentation
getRelationSize()
size_t souffle::AstProfileUseAnalysis::getRelationSize (const AstQualifiedName & rel)
Return size of relation in the profile.
Get relation size from profile.
Definition at line 56 of file ProfileUse.cpp.
References programRun, and souffle::AstQualifiedName::toString().
Referenced by AstProfileUseAnalysis().
{
     if (const auto* profRel = programRun->getRelation(rel.toString())) {
         return profRel->size();
     } else {
         return std::numeric_limits<size_t>::max();
     }
 }
hasRelationSize()
bool souffle::AstProfileUseAnalysis::hasRelationSize (const AstQualifiedName & rel)
Check whether the relation size exists in profile.
Check whether relation size is defined in profile.
Definition at line 49 of file ProfileUse.cpp.
References programRun, and souffle::AstQualifiedName::toString().
Referenced by AstProfileUseAnalysis().
{
     return programRun->getRelation(rel.toString()) != nullptr;
 }
print()
void souffle::AstProfileUseAnalysis::print (std::ostream & os) const override virtual
Output some profile information.
Print analysis.
Reimplemented from souffle::AstAnalysis.
Definition at line 44 of file ProfileUse.cpp.
Referenced by AstProfileUseAnalysis().
 {}
run()
void souffle::AstProfileUseAnalysis::run (const AstTranslationUnit & translationUnit) override virtual
Run analysis.
Run analysis, i.e., retrieve profile information.
Implements souffle::AstAnalysis.
Definition at line 34 of file ProfileUse.cpp.
References souffle::Global::config(), souffle::profile::Reader::processFile(), and programRun.
Referenced by AstProfileUseAnalysis().
{
     if (Global::config().has("profile-use")) {
         std::string filename = Global::config().get("profile-use");
         profile::Reader(filename, programRun).processFile();
     }
 }
Field Documentation
name
constexpr const char* souffle::AstProfileUseAnalysis::name = "profile-use" static
Name of analysis.
Definition at line 37 of file ProfileUse.h.
programRun
std::shared_ptr<profile::ProgramRun> souffle::AstProfileUseAnalysis::programRun private
performance model of profile run
Definition at line 56 of file ProfileUse.h.
Referenced by getRelationSize(), hasRelationSize(), and run().
The documentation for this class was generated from the following files:
ast/analysis/ProfileUse.h
ast/analysis/ProfileUse.cpp