souffle: souffle::RamBinRelationStatement Class Reference
souffle::RamBinRelationStatement Class Reference
Abstract class for a binary relation.
#include <Statement.h>
Public Member Functions
void apply (const RamNodeMapper &map) override
Apply the mapper to all child nodes.
std::vector< const RamNode * > getChildNodes () const override
Obtain list of all embedded child nodes.
const RamRelation & getFirstRelation () const
Get first relation.
const RamRelation & getSecondRelation () const
Get second relation.
RamBinRelationStatement (std::unique_ptr< RamRelationReference > f, std::unique_ptr< RamRelationReference > s)
Public Member Functions inherited from souffle::RamStatement
RamStatement * clone () const override=0
Create a clone (i.e.
Public Member Functions inherited from souffle::RamNode
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
virtual void rewrite (const RamNode *oldNode, std::unique_ptr< RamNode > newNode)
Rewrite a child node.
virtual ~RamNode ()=default
Protected Member Functions
bool equal (const RamNode &node) const override
Equality check for two RAM nodes.
Protected Member Functions inherited from souffle::RamStatement
void print (std::ostream &os) const override
Print RAM node.
virtual void print (std::ostream &os, int tabpos) const =0
Pretty print with indentation.
Protected Attributes
std::unique_ptr< RamRelationReference > first
first argument of binary statement
std::unique_ptr< RamRelationReference > second
second argument of binary statement
Additional Inherited Members
Static Protected Member Functions inherited from souffle::RamStatement
static void print (const RamStatement *statement, std::ostream &os, int tabpos)
Pretty print jump-bed.
Detailed Description
Abstract class for a binary relation.
Comprises two RamRelations
Definition at line 177 of file Statement.h.
Constructor & Destructor Documentation
RamBinRelationStatement()
souffle::RamBinRelationStatement::RamBinRelationStatement (std::unique_ptr< RamRelationReference > f, std::unique_ptr< RamRelationReference > s) inline
Definition at line 179 of file Statement.h.
References i.
             : first(std::move(f)), second(std::move(s)) {
         assert(first->get()->getArity() == second->get()->getArity() && "mismatching arities");
         assert(first != nullptr && "First relation is a null-pointer");
         assert(second != nullptr && "Second relation is a null-pointer");
         const auto& type1 = first->get()->getAttributeTypes();
         const auto& type2 = first->get()->getAttributeTypes();
         for (size_t i = 0; i < first->get()->getArity(); i++) {
             assert(type1[i] == type2[i] && "mismatching type");
         }
     }
Member Function Documentation
apply()
void souffle::RamBinRelationStatement::apply (const RamNodeMapper &) inline override virtual
Apply the mapper to all child nodes.
Reimplemented from souffle::RamNode.
Definition at line 206 of file Statement.h.
References souffle::map().
{
         first = map(std::move(first));
         second = map(std::move(second));
     }
equal()
bool souffle::RamBinRelationStatement::equal (const RamNode &) const inline override protected virtual
Equality check for two RAM nodes.
Default action is that nothing needs to be checked.
Reimplemented from souffle::RamNode.
Definition at line 212 of file Statement.h.
References souffle::equal_ptr().
{
         const auto& other = static_cast<const RamBinRelationStatement&>(node);
         return equal_ptr(first, other.first) && equal_ptr(second, other.second);
     }
getChildNodes()
std::vector<const RamNode*> souffle::RamBinRelationStatement::getChildNodes () const inline override virtual
Obtain list of all embedded child nodes.
Reimplemented from souffle::RamNode.
Definition at line 202 of file Statement.h.
{
         return {first.get(), second.get()};
     }
getFirstRelation()
const RamRelation& souffle::RamBinRelationStatement::getFirstRelation () const inline
Get first relation.
Definition at line 193 of file Statement.h.
Referenced by souffle::Synthesiser::emitCode(), souffle::NodeGenerator::visitExtend(), and souffle::NodeGenerator::visitSwap().
{
         return *first->get();
     }
getSecondRelation()
const RamRelation& souffle::RamBinRelationStatement::getSecondRelation () const inline
Get second relation.
Definition at line 198 of file Statement.h.
Referenced by souffle::Synthesiser::emitCode(), souffle::NodeGenerator::visitExtend(), and souffle::NodeGenerator::visitSwap().
{
         return *second->get();
     }
Field Documentation
first
std::unique_ptr<RamRelationReference> souffle::RamBinRelationStatement::first protected
first argument of binary statement
Definition at line 219 of file Statement.h.
second
std::unique_ptr<RamRelationReference> souffle::RamBinRelationStatement::second protected
second argument of binary statement
Definition at line 222 of file Statement.h.
The documentation for this class was generated from the following file:
ram/Statement.h