souffle: souffle::NormaliseConstraintsTransformer Class Reference
souffle::NormaliseConstraintsTransformer Class Reference
Transformation pass to normalise constraints.
#include <NormaliseConstraints.h>
Public Member Functions
NormaliseConstraintsTransformer * clone () const override
std::string getName () const override
Public Member Functions inherited from souffle::AstTransformer
bool apply (AstTranslationUnit &translationUnit)
virtual ~AstTransformer ()=default
Private Member Functions
bool transform (AstTranslationUnit &translationUnit) override
Detailed Description
Transformation pass to normalise constraints.
E.g.: a(x) :- b(x, 1). -> a(x) :- b(x, tmp0), tmp0=1.
Definition at line 31 of file NormaliseConstraints.h.
Member Function Documentation
clone()
NormaliseConstraintsTransformer* souffle::NormaliseConstraintsTransformer::clone () const inline override virtual
Implements souffle::AstTransformer.
Definition at line 37 of file NormaliseConstraints.h.
References transform().
{
         return new NormaliseConstraintsTransformer();
     }
getName()
std::string souffle::NormaliseConstraintsTransformer::getName () const inline override virtual
Implements souffle::AstTransformer.
Definition at line 33 of file NormaliseConstraints.h.
{
         return "NormaliseConstraintsTransformer";
     }
transform()
bool souffle::NormaliseConstraintsTransformer::transform (AstTranslationUnit & translationUnit) override private virtual
Implements souffle::AstTransformer.
Definition at line 41 of file NormaliseConstraints.cpp.
References souffle::clone(), souffle::EQ, souffle::FEQ, souffle::AstNumericConstant::Float, souffle::getClauses(), souffle::AstTranslationUnit::getProgram(), souffle::AstProgram::getRelations(), and souffle::isFact().
Referenced by clone().
{
     bool changed = false;
     // set a prefix for variables bound by magic-set for identification later
     // prepended by + to avoid conflict with user-defined variables
     static constexpr const char* boundPrefix = "+abdul";
     AstProgram& program = *translationUnit.getProgram();
     /* Create a node mapper that recursively replaces all constants and underscores
      * with named variables.
      *
      * The mapper keeps track of constraints that should be added to the original
      * clause it is being applied on in a given constraint set.
      */
     struct constraintNormaliser : public AstNodeMapper {
         std::set<AstBinaryConstraint*>& constraints;
         mutable int changeCount;
         constraintNormaliser(std::set<AstBinaryConstraint*>& constraints, int changeCount)
                 : constraints(constraints), changeCount(changeCount) {}
         bool hasChanged() const {
             return changeCount > 0;
         }
         int getChangeCount() const {
             return changeCount;
         }
         std::unique_ptr<AstNode> operator()(std::unique_ptr<AstNode> node) const override {
             if (auto* stringConstant = dynamic_cast<AstStringConstant*>(node.get())) {
                 // string constant found
                 changeCount++;
                 // create new variable name (with appropriate suffix)
                 std::string constantValue = stringConstant->getConstant();
                 std::stringstream newVariableName;
                 newVariableName << boundPrefix << changeCount << "_" << constantValue << "_s";
                 // create new constraint (+abdulX = constant)
                 auto newVariable = std::make_unique<AstVariable>(newVariableName.str());
                 constraints.insert(new AstBinaryConstraint(
                         BinaryConstraintOp::EQ, souffle::clone(newVariable), souffle::clone(stringConstant)));
                 // update constant to be the variable created
                 return newVariable;
             } else if (auto* numberConstant = dynamic_cast<AstNumericConstant*>(node.get())) {
                 // number constant found
                 changeCount++;
                 // create new variable name (with appropriate suffix)
                 std::stringstream newVariableName;
                 newVariableName << boundPrefix << changeCount << "_" << numberConstant->getConstant() << "_n";
                 assert(numberConstant->getType() && "numeric constant hasn't been poly-constrained");
                 auto opEq = *numberConstant->getType() == AstNumericConstant::Type::Float
                                     ? BinaryConstraintOp::FEQ
                                     : BinaryConstraintOp::EQ;
                 // create new constraint (+abdulX = constant)
                 auto newVariable = std::make_unique<AstVariable>(newVariableName.str());
                 constraints.insert(new AstBinaryConstraint(
                         opEq, souffle::clone(newVariable), souffle::clone(numberConstant)));
                 // update constant to be the variable created
                 return newVariable;
             } else if (dynamic_cast<AstUnnamedVariable*>(node.get()) != nullptr) {
                 // underscore found
                 changeCount++;
                 // create new variable name
                 std::stringstream newVariableName;
                 newVariableName << "+underscore" << changeCount;
                 return std::make_unique<AstVariable>(newVariableName.str());
             }
             node->apply(*this);
             return node;
         }
     };
     int changeCount = 0;  // number of constants and underscores seen so far
     // apply the change to all clauses in the program
     for (AstRelation* rel : program.getRelations()) {
         for (AstClause* clause : getClauses(program, *rel)) {
             if (isFact(*clause)) {
                 continue;  // don't normalise facts
             }
             std::set<AstBinaryConstraint*> constraints;
             constraintNormaliser update(constraints, changeCount);
             clause->apply(update);
             changeCount = update.getChangeCount();
             changed = changed || update.hasChanged();
             for (AstBinaryConstraint* constraint : constraints) {
                 clause->addToBody(std::unique_ptr<AstBinaryConstraint>(constraint));
             }
         }
     }
     return changed;
 }
The documentation for this class was generated from the following files:
ast/transform/NormaliseConstraints.h
ast/transform/NormaliseConstraints.cpp