souffle: souffle::RelationWrapper< id, RelType, TupleType, Arity, NumAuxAttributes > Class Template Reference
souffle::RelationWrapper< id, RelType, TupleType, Arity, NumAuxAttributes > Class Template Reference
Relation wrapper used internally in the generated Datalog program.
#include <CompiledSouffle.h>
Data Structures
class iterator_wrapper
Public Member Functions
iterator begin () const override
Return an iterator pointing to the first tuple of the relation.
bool contains (const tuple &arg) const override
Check whether a tuple exists in a relation.
iterator end () const override
Return an iterator pointing to next to the last tuple of the relation.
size_t getArity () const override
Return the arity of a relation.
const char * getAttrName (size_t arg) const override
Get the attribute name of a relation at the column specified by the parameter.
const char * getAttrType (size_t arg) const override
Get the attribute type of a relation at the column specified by the parameter.
size_t getAuxiliaryArity () const override
Return the number of auxiliary attributes.
std::string getName () const override
Get the name of a relation.
SymbolTable & getSymbolTable () const override
Get the symbol table of a relation.
void insert (const tuple &arg) override
Insert a new tuple into the relation.
void purge () override
Eliminate all the tuples in relation.
RelationWrapper (RelType &r, SymbolTable &s, std::string name, const std::array< const char *, Arity > &t, const std::array< const char *, Arity > &n)
std::size_t size () const override
Get the number of tuples in a relation.
Public Member Functions inherited from souffle::Relation
std::string getSignature ()
Get the signature of a relation.
virtual ~Relation ()=default
Destructor.
Private Attributes
std::string name
RelType & relation
SymbolTable & symTable
std::array< const char *, Arity > tupleName
std::array< const char *, Arity > tupleType
Detailed Description
template<uint32_t id, class RelType, class TupleType, size_t Arity, size_t NumAuxAttributes>
class souffle::RelationWrapper< id, RelType, TupleType, Arity, NumAuxAttributes >
Relation wrapper used internally in the generated Datalog program.
Definition at line 75 of file CompiledSouffle.h.
Constructor & Destructor Documentation
RelationWrapper()
template<uint32_t id, class RelType , class TupleType , size_t Arity, size_t NumAuxAttributes> souffle::RelationWrapper< id, RelType, TupleType, Arity, NumAuxAttributes >::RelationWrapper (RelType & r, SymbolTable & s, std::string name, const std::array< const char *, Arity > & t, const std::array< const char *, Arity > & n) inline
Definition at line 113 of file CompiledSouffle.h.
             : relation(r), symTable(s), name(std::move(name)), tupleType(t), tupleName(n) {}
Member Function Documentation
begin()
template<uint32_t id, class RelType , class TupleType , size_t Arity, size_t NumAuxAttributes> iterator souffle::RelationWrapper< id, RelType, TupleType, Arity, NumAuxAttributes >::begin () const inline override virtual
Return an iterator pointing to the first tuple of the relation.
This iterator is used to access the tuples of the relation.
Returns
Iterator
Implements souffle::Relation.
Definition at line 116 of file CompiledSouffle.h.
References souffle::RelationWrapper< id, RelType, TupleType, Arity, NumAuxAttributes >::iterator_wrapper::iterator_wrapper().
{
         return iterator(new iterator_wrapper(id, this, relation.begin()));
     }
contains()
template<uint32_t id, class RelType , class TupleType , size_t Arity, size_t NumAuxAttributes> bool souffle::RelationWrapper< id, RelType, TupleType, Arity, NumAuxAttributes >::contains (const tuple & t) const inline override virtual
Check whether a tuple exists in a relation.
The definition of contains has to be defined by the child class of relation class.
Parameters
t Reference to a tuple object
Returns
Boolean. True, if the tuple exists. False, otherwise
Implements souffle::Relation.
Definition at line 131 of file CompiledSouffle.h.
References i, souffle::tuple::size(), and souffle::RelationWrapper< id, RelType, TupleType, Arity, NumAuxAttributes >::iterator_wrapper::t.
Referenced by souffle::t_info< Arity >::contains(), and souffle::t_info< Arity >::insert().
{
         TupleType t;
         assert(arg.size() == Arity && "wrong tuple arity");
         for (size_t i = 0; i < Arity; i++) {
             t[i] = arg[i];
         }
         return relation.contains(t);
     }
end()
template<uint32_t id, class RelType , class TupleType , size_t Arity, size_t NumAuxAttributes> iterator souffle::RelationWrapper< id, RelType, TupleType, Arity, NumAuxAttributes >::end () const inline override virtual
Return an iterator pointing to next to the last tuple of the relation.
Returns
Iterator
Implements souffle::Relation.
Definition at line 119 of file CompiledSouffle.h.
References souffle::RelationWrapper< id, RelType, TupleType, Arity, NumAuxAttributes >::iterator_wrapper::iterator_wrapper().
{
         return iterator(new iterator_wrapper(id, this, relation.end()));
     }
getArity()
template<uint32_t id, class RelType , class TupleType , size_t Arity, size_t NumAuxAttributes> size_t souffle::RelationWrapper< id, RelType, TupleType, Arity, NumAuxAttributes >::getArity () const inline override virtual
Return the arity of a relation.
For example for a tuple (1 2) the arity is 2 and for a tuple (1 2 3) the arity is 3.
Returns
Arity of a relation (size_t)
Implements souffle::Relation.
Definition at line 153 of file CompiledSouffle.h.
{
         return Arity;
     }
getAttrName()
template<uint32_t id, class RelType , class TupleType , size_t Arity, size_t NumAuxAttributes> const char* souffle::RelationWrapper< id, RelType, TupleType, Arity, NumAuxAttributes >::getAttrName (size_t) const inline override virtual
Get the attribute name of a relation at the column specified by the parameter.
The attribute name is the name given to the type by the user in the .decl statement. For example, for ".decl edge (node1:Node, node2:Node)", the attribute names are node1 and node2.
Parameters
The index of the column starting starting from 0 (size_t)
Returns
The constant string of the attribute name
Implements souffle::Relation.
Definition at line 149 of file CompiledSouffle.h.
{
         assert(arg < Arity && "attribute out of bound");
         return tupleName[arg];
     }
getAttrType()
template<uint32_t id, class RelType , class TupleType , size_t Arity, size_t NumAuxAttributes> const char* souffle::RelationWrapper< id, RelType, TupleType, Arity, NumAuxAttributes >::getAttrType (size_t) const inline override virtual
Get the attribute type of a relation at the column specified by the parameter.
The attribute type is in the form "<primitive type>:<type name>". <primitive type>=""> can be s, f, u, or i standing for symbol, float, unsigned, and integer respectively, which are the primitive types in Souffle. <type name>=""> is the name given by the user in the Souffle program
Parameters
The index of the column starting starting from 0 (size_t)
Returns
The constant string of the attribute type
Implements souffle::Relation.
Definition at line 145 of file CompiledSouffle.h.
{
         assert(arg < Arity && "attribute out of bound");
         return tupleType[arg];
     }
getAuxiliaryArity()
template<uint32_t id, class RelType , class TupleType , size_t Arity, size_t NumAuxAttributes> size_t souffle::RelationWrapper< id, RelType, TupleType, Arity, NumAuxAttributes >::getAuxiliaryArity () const inline override virtual
Return the number of auxiliary attributes.
Auxiliary attributes are used for provenance and and other alternative evaluation strategies. They are stored as the last attributes of a tuple.
Returns
Number of auxiliary attributes of a relation (size_t)
Implements souffle::Relation.
Definition at line 156 of file CompiledSouffle.h.
{
         return NumAuxAttributes;
     }
getName()
template<uint32_t id, class RelType , class TupleType , size_t Arity, size_t NumAuxAttributes> std::string souffle::RelationWrapper< id, RelType, TupleType, Arity, NumAuxAttributes >::getName () const inline override virtual
Get the name of a relation.
Returns
The name of a relation (std::string)
Implements souffle::Relation.
Definition at line 142 of file CompiledSouffle.h.
References souffle::RelationWrapper< id, RelType, TupleType, Arity, NumAuxAttributes >::name.
{
         return name;
     }
getSymbolTable()
template<uint32_t id, class RelType , class TupleType , size_t Arity, size_t NumAuxAttributes> SymbolTable& souffle::RelationWrapper< id, RelType, TupleType, Arity, NumAuxAttributes >::getSymbolTable () const inline override virtual
Get the symbol table of a relation.
The symbols in a tuple to be stored into a relation are stored and assigned with a number in a table called symbol table. For example, to insert ("John","Student") to a relation, "John" and "Student" are stored in symbol table and they are assigned with number say 0 and 1. After this, instead of inserting ("John","Student"), (0, 1) is inserted. When accessing this tuple, 0 and 1 will be looked up in the table and replaced by "John" and "Student". This is done so to save memory space if same symbols are inserted many times. Symbol table has many rows where each row contains a symbol and its corresponding assigned number.
Returns
Reference to a symbolTable object
Implements souffle::Relation.
Definition at line 159 of file CompiledSouffle.h.
References souffle::RelationWrapper< id, RelType, TupleType, Arity, NumAuxAttributes >::symTable.
{
         return symTable;
     }
insert()
template<uint32_t id, class RelType , class TupleType , size_t Arity, size_t NumAuxAttributes> void souffle::RelationWrapper< id, RelType, TupleType, Arity, NumAuxAttributes >::insert (const tuple & t) inline override virtual
Insert a new tuple into the relation.
The definition of insert function has to be defined by the child class of relation class.
Parameters
t Reference to a tuple class object
Implements souffle::Relation.
Definition at line 122 of file CompiledSouffle.h.
References souffle::tuple::getRelation(), i, souffle::tuple::size(), and souffle::RelationWrapper< id, RelType, TupleType, Arity, NumAuxAttributes >::iterator_wrapper::t.
Referenced by souffle::t_info< Arity >::insert().
{
         TupleType t;
         assert(&arg.getRelation() == this && "wrong relation");
         assert(arg.size() == Arity && "wrong tuple arity");
         for (size_t i = 0; i < Arity; i++) {
             t[i] = arg[i];
         }
         relation.insert(t);
     }
purge()
template<uint32_t id, class RelType , class TupleType , size_t Arity, size_t NumAuxAttributes> void souffle::RelationWrapper< id, RelType, TupleType, Arity, NumAuxAttributes >::purge () inline override virtual
Eliminate all the tuples in relation.
Implements souffle::Relation.
Definition at line 164 of file CompiledSouffle.h.
{
         relation.purge();
     }
size()
template<uint32_t id, class RelType , class TupleType , size_t Arity, size_t NumAuxAttributes> std::size_t souffle::RelationWrapper< id, RelType, TupleType, Arity, NumAuxAttributes >::size () const inline override virtual
Get the number of tuples in a relation.
Returns
The number of tuples in a relation (std::size_t)
Implements souffle::Relation.
Definition at line 139 of file CompiledSouffle.h.
{
         return relation.size();
     }
Field Documentation
name
template<uint32_t id, class RelType , class TupleType , size_t Arity, size_t NumAuxAttributes> std::string souffle::RelationWrapper< id, RelType, TupleType, Arity, NumAuxAttributes >::name private
Definition at line 79 of file CompiledSouffle.h.
Referenced by souffle::RelationWrapper< id, RelType, TupleType, Arity, NumAuxAttributes >::getName().
relation
template<uint32_t id, class RelType , class TupleType , size_t Arity, size_t NumAuxAttributes> RelType& souffle::RelationWrapper< id, RelType, TupleType, Arity, NumAuxAttributes >::relation private
Definition at line 77 of file CompiledSouffle.h.
symTable
template<uint32_t id, class RelType , class TupleType , size_t Arity, size_t NumAuxAttributes> SymbolTable& souffle::RelationWrapper< id, RelType, TupleType, Arity, NumAuxAttributes >::symTable private
Definition at line 78 of file CompiledSouffle.h.
Referenced by souffle::RelationWrapper< id, RelType, TupleType, Arity, NumAuxAttributes >::getSymbolTable().
tupleName
template<uint32_t id, class RelType , class TupleType , size_t Arity, size_t NumAuxAttributes> std::array<const char*, Arity> souffle::RelationWrapper< id, RelType, TupleType, Arity, NumAuxAttributes >::tupleName private
Definition at line 81 of file CompiledSouffle.h.
tupleType
template<uint32_t id, class RelType , class TupleType , size_t Arity, size_t NumAuxAttributes> std::array<const char*, Arity> souffle::RelationWrapper< id, RelType, TupleType, Arity, NumAuxAttributes >::tupleType private
Definition at line 80 of file CompiledSouffle.h.
The documentation for this class was generated from the following file:
CompiledSouffle.h