souffle: souffle::BindingStore Class Reference
souffle::BindingStore Class Reference
#include <MagicSet.h>
Public Member Functions
void addBinding (const std::string &newVariableName, const AstArgument *arg)
void addVariableBoundComposite (const std::string &functorName)
AstArgument * cloneOriginalArgument (const std::string &argName) const
const std::set< std::string > & getVariableDependencies (const std::string &argName) const
bool isVariableBoundComposite (const std::string &functorName) const
Private Attributes
std::map< std::string, std::unique_ptr< AstArgument > > originalArguments
std::map< std::string, std::set< std::string > > varDependencies
std::set< std::string > variableBoundComposites
Detailed Description
Definition at line 154 of file MagicSet.h.
Member Function Documentation
addBinding()
void souffle::BindingStore::addBinding (const std::string & newVariableName, const AstArgument * arg) inline
Definition at line 169 of file MagicSet.h.
References souffle::clone(), souffle::AstVariable::getName(), and souffle::visitDepthFirst().
Referenced by souffle::bindComposites().
{
         originalArguments[newVariableName] = souffle::clone(arg);
         // find the variable dependencies
         std::set<std::string> dependencies;
         visitDepthFirst(*arg, [&](const AstVariable& var) { dependencies.insert(var.getName()); });
         varDependencies[newVariableName] = dependencies;
     }
addVariableBoundComposite()
void souffle::BindingStore::addVariableBoundComposite (const std::string & functorName) inline
Definition at line 178 of file MagicSet.h.
Referenced by souffle::isBoundComposite().
{
         variableBoundComposites.insert(functorName);
     }
cloneOriginalArgument()
AstArgument* souffle::BindingStore::cloneOriginalArgument (const std::string & argName) const inline
Definition at line 161 of file MagicSet.h.
References souffle::AstArgument::clone().
{
         return originalArguments.at(argName)->clone();
     }
getVariableDependencies()
const std::set<std::string>& souffle::BindingStore::getVariableDependencies (const std::string & argName) const inline
Definition at line 165 of file MagicSet.h.
Referenced by souffle::isBoundComposite().
{
         return varDependencies.at(argName);
     }
isVariableBoundComposite()
bool souffle::BindingStore::isVariableBoundComposite (const std::string & functorName) const inline
Definition at line 182 of file MagicSet.h.
{
         return (variableBoundComposites.find(functorName) != variableBoundComposites.end());
     }
Field Documentation
originalArguments
std::map<std::string, std::unique_ptr<AstArgument> > souffle::BindingStore::originalArguments private
Definition at line 156 of file MagicSet.h.
varDependencies
std::map<std::string, std::set<std::string> > souffle::BindingStore::varDependencies private
Definition at line 157 of file MagicSet.h.
variableBoundComposites
std::set<std::string> souffle::BindingStore::variableBoundComposites private
Definition at line 158 of file MagicSet.h.
The documentation for this class was generated from the following file:
ast/transform/MagicSet.h