souffle: souffle::WriteStreamJSON Class Reference
souffle::WriteStreamJSON Class Reference
#include <WriteStreamJSON.h>
Protected Member Functions
void writeNextTupleJSON (std::ostream &destination, const RamDomain *tuple)
void writeNextTupleList (std::ostream &destination, const std::string &name, const RamDomain value)
void writeNextTupleObject (std::ostream &destination, const std::string &name, const RamDomain value)
WriteStreamJSON (const std::map< std::string, std::string > &rwOperation, const SymbolTable &symbolTable, const RecordTable &recordTable)
Protected Member Functions inherited from souffle::WriteStream
void outputRecord (std::ostream &destination, const RamDomain value, const std::string &name)
template<typename Tuple >
void writeNext (const Tuple tuple)
virtual void writeNextTuple (const RamDomain *tuple)=0
virtual void writeNullary ()=0
virtual void writeSize (std::size_t)
Protected Member Functions inherited from souffle::SerialisationStream< true >
SerialisationStream (RO< SymbolTable > &symTab, RO< RecordTable > &recTab, Json types, std::vector< std::string > relTypes, size_t auxArity=0)
SerialisationStream (RO< SymbolTable > &symTab, RO< RecordTable > &recTab, Json types)
SerialisationStream (RO< SymbolTable > &symTab, RO< RecordTable > &recTab, const std::map< std::string, std::string > &rwOperation)
Protected Attributes
Json params
const bool useObjects
Protected Attributes inherited from souffle::WriteStream
const bool summary
Protected Attributes inherited from souffle::SerialisationStream< true >
size_t arity
size_t auxiliaryArity
RO< RecordTable > & recordTable
RO< SymbolTable > & symbolTable
std::vector< std::string > typeAttributes
Json types
Additional Inherited Members
Public Member Functions inherited from souffle::WriteStream
template<typename T >
void writeAll (const T &relation)
template<>
void writeNext (const RamDomain *tuple)
template<typename T >
void writeSize (const T &relation)
WriteStream (const std::map< std::string, std::string > &rwOperation, const SymbolTable &symbolTable, const RecordTable &recordTable)
Public Member Functions inherited from souffle::SerialisationStream< true >
virtual ~SerialisationStream ()=default
Protected Types inherited from souffle::SerialisationStream< true >
using RO = std::conditional_t< readOnlyTables, const A, A >
Detailed Description
Definition at line 33 of file WriteStreamJSON.h.
Constructor & Destructor Documentation
WriteStreamJSON()
souffle::WriteStreamJSON::WriteStreamJSON (const std::map< std::string, std::string > & rwOperation, const SymbolTable & symbolTable, const RecordTable & recordTable) inline protected
Definition at line 35 of file WriteStreamJSON.h.
References err, souffle::fatal(), params, json11::Json::parse(), and useObjects.
             : WriteStream(rwOperation, symbolTable, recordTable),
               useObjects(getOr(rwOperation, "format", "list") == "object") {
         if (useObjects) {
             std::string err;
             params = Json::parse(rwOperation.at("params"), err);
             if (err.length() > 0) {
                 fatal("cannot get internal param names: %s", err);
             }
         }
     };
Member Function Documentation
writeNextTupleJSON()
void souffle::WriteStreamJSON::writeNextTupleJSON (std::ostream & destination, const RamDomain * tuple) inline protected
Definition at line 51 of file WriteStreamJSON.h.
References souffle::SerialisationStream< true >::arity, json11::Json::dump(), souffle::SerialisationStream< true >::typeAttributes, writeNextTupleList(), and writeNextTupleObject().
Referenced by souffle::WriteFileJSON::writeNextTuple(), and souffle::WriteCoutJSON::writeNextTuple().
{
         std::vector<Json> result;
         if (useObjects)
             destination << "{";
         else
             destination << "[";
         for (size_t col = 0; col < arity; ++col) {
             if (col > 0) {
                 destination << ", ";
             }
             if (useObjects) {
                 destination << params["relation"]["params"][col].dump() << ": ";
                 writeNextTupleObject(destination, typeAttributes.at(col), tuple[col]);
             } else {
                 writeNextTupleList(destination, typeAttributes.at(col), tuple[col]);
             }
         }
         if (useObjects)
             destination << "}";
         else
             destination << "]";
     }
writeNextTupleList()
void souffle::WriteStreamJSON::writeNextTupleList (std::ostream & destination, const std::string & name, const RamDomain value) inline protected
Definition at line 78 of file WriteStreamJSON.h.
References json11::dump(), souffle::fatal(), i, json11::Json::long_value(), souffle::SerialisationStream< true >::recordTable, souffle::SerialisationStream< true >::symbolTable, and souffle::SerialisationStream< true >::types.
Referenced by writeNextTupleJSON().
{
         using ValueTuple = std::pair<const std::string, const RamDomain>;
         std::stack<std::variant<ValueTuple, std::string>> worklist;
         worklist.push(std::make_pair(name, value));
         // the Json11 output is not tail recursive, therefore highly inefficient for recursive record
         // in addition the JSON object is immutable, so has memory overhead
         while (!worklist.empty()) {
             std::variant<ValueTuple, std::string> curr = worklist.top();
             worklist.pop();
             if (std::holds_alternative<std::string>(curr)) {
                 destination << std::get<std::string>(curr);
                 continue;
             }
             const std::string& currType = std::get<ValueTuple>(curr).first;
             const RamDomain currValue = std::get<ValueTuple>(curr).second;
             assert(currType.length() > 2 && "Invalid type length");
             switch (currType[0]) {
                 // since some strings may need to be escaped, we use dump here
                 case 's': destination << Json(symbolTable.unsafeResolve(currValue)).dump(); break;
                 case 'i': destination << currValue; break;
                 case 'u': destination << (int)ramBitCast<RamUnsigned>(currValue); break;
                 case 'f': destination << ramBitCast<RamFloat>(currValue); break;
                 case 'r': {
                     auto&& recordInfo = types["records"][currType];
                     assert(!recordInfo.is_null() && "Missing record type information");
                     if (currValue == 0) {
                         destination << "null";
                         break;
                     }
                     auto&& recordTypes = recordInfo["types"];
                     const size_t recordArity = recordInfo["arity"].long_value();
                     const RamDomain* tuplePtr = recordTable.unpack(currValue, recordArity);
                     worklist.push("]");
                     for (auto i = (long long)(recordArity - 1); i >= 0; --i) {
                         if (i != (long long)(recordArity - 1)) {
                             worklist.push(", ");
                         }
                         const std::string& recordType = recordTypes[i].string_value();
                         const RamDomain recordValue = tuplePtr[i];
                         worklist.push(std::make_pair(recordType, recordValue));
                     }
                     worklist.push("[");
                     break;
                 }
                 default: fatal("unsupported type attribute: `%c`", currType[0]);
             }
         }
     }
writeNextTupleObject()
void souffle::WriteStreamJSON::writeNextTupleObject (std::ostream & destination, const std::string & name, const RamDomain value) inline protected
Definition at line 132 of file WriteStreamJSON.h.
References json11::dump(), souffle::fatal(), i, json11::Json::long_value(), souffle::SerialisationStream< true >::recordTable, souffle::SerialisationStream< true >::symbolTable, and souffle::SerialisationStream< true >::types.
Referenced by writeNextTupleJSON().
{
         using ValueTuple = std::pair<const std::string, const RamDomain>;
         std::stack<std::variant<ValueTuple, std::string>> worklist;
         worklist.push(std::make_pair(name, value));
         // the Json11 output is not tail recursive, therefore highly inefficient for recursive record
         // in addition the JSON object is immutable, so has memory overhead
         while (!worklist.empty()) {
             std::variant<ValueTuple, std::string> curr = worklist.top();
             worklist.pop();
             if (std::holds_alternative<std::string>(curr)) {
                 destination << std::get<std::string>(curr);
                 continue;
             }
             const std::string& currType = std::get<ValueTuple>(curr).first;
             const RamDomain currValue = std::get<ValueTuple>(curr).second;
             const std::string& typeName = currType.substr(2);
             assert(currType.length() > 2 && "Invalid type length");
             switch (currType[0]) {
                 // since some strings may need to be escaped, we use dump here
                 case 's': destination << Json(symbolTable.unsafeResolve(currValue)).dump(); break;
                 case 'i': destination << currValue; break;
                 case 'u': destination << (int)ramBitCast<RamUnsigned>(currValue); break;
                 case 'f': destination << ramBitCast<RamFloat>(currValue); break;
                 case 'r': {
                     auto&& recordInfo = types["records"][currType];
                     assert(!recordInfo.is_null() && "Missing record type information");
                     if (currValue == 0) {
                         destination << "null";
                         break;
                     }
                     auto&& recordTypes = recordInfo["types"];
                     const size_t recordArity = recordInfo["arity"].long_value();
                     const RamDomain* tuplePtr = recordTable.unpack(currValue, recordArity);
                     worklist.push("}");
                     for (auto i = (long long)(recordArity - 1); i >= 0; --i) {
                         if (i != (long long)(recordArity - 1)) {
                             worklist.push(", ");
                         }
                         const std::string& recordType = recordTypes[i].string_value();
                         const RamDomain recordValue = tuplePtr[i];
                         worklist.push(std::make_pair(recordType, recordValue));
                         worklist.push(": ");
                         auto&& recordParam = params["records"][typeName]["params"][i];
                         assert(recordParam.is_string());
                         worklist.push(recordParam.dump());
                     }
                     worklist.push("{");
                     break;
                 }
                 default: fatal("unsupported type attribute: `%c`", currType[0]);
             }
         }
     }
Field Documentation
params
Json souffle::WriteStreamJSON::params protected
Definition at line 49 of file WriteStreamJSON.h.
Referenced by WriteStreamJSON().
useObjects
const bool souffle::WriteStreamJSON::useObjects protected
Definition at line 46 of file WriteStreamJSON.h.
Referenced by WriteStreamJSON().
The documentation for this class was generated from the following file:
WriteStreamJSON.h