souffle: souffle::TypeEnvironment Class Reference
souffle::TypeEnvironment Class Reference
A type environment is a set of types.
#include <TypeSystem.h>
Public Member Functions
template<typename T , typename... Args>
T & createType (const AstQualifiedName &name, Args &&... args)
create type in this environment
const TypeSet & getConstantNumericTypes () const
const Type & getConstantType (TypeAttribute type) const
const TypeSet & getConstantTypes () const
const TypeSet & getPrimitiveTypes () const
const Type & getType (const AstQualifiedName &) const
TypeSet getTypes () const
bool isPrimitiveType (const AstQualifiedName &identifier) const
bool isPrimitiveType (const Type &type) const
bool isType (const AstQualifiedName &) const
bool isType (const Type &type) const
void print (std::ostream &out) const
TypeEnvironment ()=default
TypeEnvironment (const TypeEnvironment &)=delete
virtual ~TypeEnvironment ()=default
Private Member Functions
TypeSet initializeConstantTypes ()
TypeSet initializePrimitiveTypes ()
Private Attributes
const TypeSet constantNumericTypes
const TypeSet constantTypes = initializeConstantTypes()
const TypeSet primitiveTypes = initializePrimitiveTypes()
std::map< AstQualifiedName, std::unique_ptr< Type > > types
The list of covered types.
Friends
std::ostream & operator<< (std::ostream &out, const TypeEnvironment &environment)
Detailed Description
A type environment is a set of types.
It's main purpose is to provide an enumeration of all all types within a given program. Additionally, it manages the life cycle of type instances.
Definition at line 366 of file TypeSystem.h.
Constructor & Destructor Documentation
TypeEnvironment() [1/2]
souffle::TypeEnvironment::TypeEnvironment () default
TypeEnvironment() [2/2]
souffle::TypeEnvironment::TypeEnvironment (const TypeEnvironment &) delete
~TypeEnvironment()
virtual souffle::TypeEnvironment::~TypeEnvironment () virtual default
Member Function Documentation
createType()
template<typename T , typename... Args> T& souffle::TypeEnvironment::createType (const AstQualifiedName & name, Args &&... args) inline
create type in this environment
Definition at line 376 of file TypeSystem.h.
References souffle::getType(), souffle::Type::name, and types.
Referenced by souffle::test::TEST().
{
         assert(types.find(name) == types.end() && "Error: registering present type!");
         auto* newType = new T(*this, name, std::forward<Args>(args)...);
         types[name] = std::unique_ptr<Type>(newType);
         return *newType;
     }
getConstantNumericTypes()
const TypeSet& souffle::TypeEnvironment::getConstantNumericTypes () const inline
Definition at line 419 of file TypeSystem.h.
References souffle::Type::print().
Referenced by souffle::TypeConstraintsAnalysis::visitAggregator().
{
         return constantNumericTypes;
     }
getConstantType()
const Type& souffle::TypeEnvironment::getConstantType (TypeAttribute type) const inline
Definition at line 388 of file TypeSystem.h.
References souffle::fatal(), souffle::Float, souffle::getType(), souffle::Record, souffle::Signed, souffle::Symbol, and souffle::Unsigned.
Referenced by souffle::isOfKind(), souffle::TypeConstraintsAnalysis::visitAggregator(), souffle::TypeConstraintsAnalysis::visitCounter(), souffle::TypeConstraintsAnalysis::visitFunctor(), souffle::TypeConstraintsAnalysis::visitNumericConstant(), and souffle::TypeConstraintsAnalysis::visitStringConstant().
{
         switch (type) {
             case TypeAttribute::Signed: return getType("__numberConstant");
             case TypeAttribute::Unsigned: return getType("__unsignedConstant");
             case TypeAttribute::Float: return getType("__floatConstant");
             case TypeAttribute::Symbol: return getType("__symbolConstant");
             case TypeAttribute::Record: break;
         }
         fatal("There is no constant record type");
     }
getConstantTypes()
const TypeSet& souffle::TypeEnvironment::getConstantTypes () const inline
Definition at line 411 of file TypeSystem.h.
Referenced by souffle::TypeConstraintsAnalysis::visitSink().
{
         return constantTypes;
     }
getPrimitiveTypes()
const TypeSet& souffle::TypeEnvironment::getPrimitiveTypes () const inline
Definition at line 415 of file TypeSystem.h.
{
         return primitiveTypes;
     }
getType()
const Type & souffle::TypeEnvironment::getType (const AstQualifiedName & ident) const
Definition at line 73 of file TypeSystem.cpp.
References types.
Referenced by souffle::AstSemanticCheckerImpl::checkSubsetType(), souffle::TypeConstraintsAnalysis::iterateOverAtom(), souffle::test::TEST(), souffle::AstToRamTranslator::translateProgram(), souffle::TypeChecker::visitAtom(), and souffle::TypeConstraintsAnalysis::visitTypeCast().
{
     return *types.at(ident);
 }
getTypes()
TypeSet souffle::TypeEnvironment::getTypes () const inline
Definition at line 430 of file TypeSystem.h.
References types.
Referenced by souffle::haveCommonSupertype().
{
         TypeSet types;
         for (auto& type : types) {
             types.insert(type);
         }
         return types;
     }
initializeConstantTypes()
TypeSet souffle::TypeEnvironment::initializeConstantTypes () private
Definition at line 41 of file TypeSystem.cpp.
{
     auto& signedConstant = createType<ConstantType>("__numberConstant");
     auto& floatConstant = createType<ConstantType>("__floatConstant");
     auto& symbolConstant = createType<ConstantType>("__symbolConstant");
     auto& unsignedConstant = createType<ConstantType>("__unsignedConstant");
     return TypeSet(signedConstant, floatConstant, symbolConstant, unsignedConstant);
 }
initializePrimitiveTypes()
TypeSet souffle::TypeEnvironment::initializePrimitiveTypes () private
Definition at line 50 of file TypeSystem.cpp.
References CREATE_PRIMITIVE.
{
 #define CREATE_PRIMITIVE(TYPE)                    \
     auto& TYPE##Type = createType<PrimitiveType>( \
             #TYPE, static_cast<const ConstantType&>(getType("__" #TYPE "Constant")));
     CREATE_PRIMITIVE(number);
     CREATE_PRIMITIVE(float);
     CREATE_PRIMITIVE(symbol);
     CREATE_PRIMITIVE(unsigned);
     return TypeSet(numberType, floatType, symbolType, unsignedType);
 #undef CREATE_PRIMITIVE
 }
isPrimitiveType() [1/2]
bool souffle::TypeEnvironment::isPrimitiveType (const AstQualifiedName & identifier) const inline
Definition at line 400 of file TypeSystem.h.
References souffle::getType().
Referenced by souffle::AstSemanticCheckerImpl::checkRelationDeclaration(), souffle::AstSemanticCheckerImpl::checkType(), and souffle::AstSemanticCheckerImpl::checkUnionType().
{
         if (isType(identifier)) {
             return isPrimitiveType(getType(identifier));
         }
         return false;
     }
isPrimitiveType() [2/2]
bool souffle::TypeEnvironment::isPrimitiveType (const Type & type) const inline
Definition at line 407 of file TypeSystem.h.
{
         return primitiveTypes.contains(type);
     }
isType() [1/2]
bool souffle::TypeEnvironment::isType (const AstQualifiedName & ident) const
Definition at line 65 of file TypeSystem.cpp.
References types.
Referenced by souffle::AstSemanticCheckerImpl::checkRecordType(), souffle::AstSemanticCheckerImpl::checkSubsetType(), souffle::TypeConstraintsAnalysis::iterateOverAtom(), souffle::TypeChecker::visitAtom(), souffle::TypeChecker::visitTypeCast(), and souffle::TypeConstraintsAnalysis::visitTypeCast().
{
     return types.find(ident) != types.end();
 }
isType() [2/2]
bool souffle::TypeEnvironment::isType (const Type & type) const
Definition at line 69 of file TypeSystem.cpp.
References souffle::Type::getTypeEnvironment().
{
     return this == &type.getTypeEnvironment();
 }
print()
void souffle::TypeEnvironment::print (std::ostream & out) const
Definition at line 244 of file TypeSystem.cpp.
References types.
{
     out << "Types:\n";
     for (const auto& cur : types) {
         out << "\t" << *cur.second << "\n";
     }
 }
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & out, const TypeEnvironment & environment) friend
Definition at line 425 of file TypeSystem.h.
{
         environment.print(out);
         return out;
     }
Field Documentation
constantNumericTypes
const TypeSet souffle::TypeEnvironment::constantNumericTypes private
Initial value:
=
            TypeSet(getType("__numberConstant"), getType("__unsignedConstant"), getType("__floatConstant"))
Definition at line 446 of file TypeSystem.h.
constantTypes
const TypeSet souffle::TypeEnvironment::constantTypes = initializeConstantTypes() private
Definition at line 445 of file TypeSystem.h.
primitiveTypes
const TypeSet souffle::TypeEnvironment::primitiveTypes = initializePrimitiveTypes() private
Definition at line 449 of file TypeSystem.h.
types
std::map<AstQualifiedName, std::unique_ptr<Type> > souffle::TypeEnvironment::types private
The list of covered types.
Definition at line 443 of file TypeSystem.h.
The documentation for this class was generated from the following files:
ast/TypeSystem.h
ast/TypeSystem.cpp