souffle: souffle::RamIndexChoice Class Reference
souffle::RamIndexChoice Class Reference
Use an index to find a tuple in a relation such that a given condition holds.
#include <Operation.h>
Public Member Functions
void apply (const RamNodeMapper &map) override
Apply the mapper to all child nodes.
RamIndexChoice * clone () const override
Create a clone (i.e.
std::vector< const RamNode * > getChildNodes () const override
Obtain list of all embedded child nodes.
RamIndexChoice (std::unique_ptr< RamRelationReference > r, int ident, std::unique_ptr< RamCondition > cond, RamPattern queryPattern, std::unique_ptr< RamOperation > nested, std::string profileText="")
Public Member Functions inherited from souffle::RamIndexOperation
std::pair< std::vector< RamExpression * >, std::vector< RamExpression * > > getRangePattern () const
Get range pattern.
void printIndex (std::ostream &os) const
Helper method for printing.
RamIndexOperation (std::unique_ptr< RamRelationReference > r, int ident, RamPattern queryPattern, std::unique_ptr< RamOperation > nested, std::string profileText="")
Public Member Functions inherited from souffle::RamRelationOperation
const RamRelation & getRelation () const
Get search relation.
RamRelationOperation (std::unique_ptr< RamRelationReference > relRef, int ident, std::unique_ptr< RamOperation > nested, std::string profileText="")
Public Member Functions inherited from souffle::RamTupleOperation
int getTupleId () const
Get identifier.
RamTupleOperation (int ident, std::unique_ptr< RamOperation > nested, std::string profileText="")
void setTupleId (int id)
Set identifier.
Public Member Functions inherited from souffle::RamNestedOperation
RamOperation & getOperation () const
Get nested operation.
const std::string & getProfileText () const
Get profile text.
RamNestedOperation (std::unique_ptr< RamOperation > nested, std::string profileText="")
Public Member Functions inherited from souffle::RamNode
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
virtual void rewrite (const RamNode *oldNode, std::unique_ptr< RamNode > newNode)
Rewrite a child node.
virtual ~RamNode ()=default
Public Member Functions inherited from souffle::RamAbstractChoice
void apply (const RamNodeMapper &map)
std::vector< const RamNode * > getChildNodes () const
const RamCondition & getCondition () const
Getter for the condition.
RamAbstractChoice (std::unique_ptr< RamCondition > cond)
Protected Member Functions
bool equal (const RamNode &node) const override
Equality check for two RAM nodes.
void print (std::ostream &os, int tabpos) const override
Pretty print with indentation.
Protected Member Functions inherited from souffle::RamOperation
void print (std::ostream &os) const override
Print RAM node.
Protected Member Functions inherited from souffle::RamAbstractChoice
bool equal (const RamNode &node) const
Additional Inherited Members
Static Protected Member Functions inherited from souffle::RamOperation
static void print (const RamOperation *operation, std::ostream &os, int tabpos)
Pretty print jump-bed.
Protected Attributes inherited from souffle::RamIndexOperation
RamPattern queryPattern
Values of index per column of table (if indexable)
Protected Attributes inherited from souffle::RamRelationOperation
std::unique_ptr< RamRelationReference > relationRef
Search relation.
Protected Attributes inherited from souffle::RamTupleOperation
int identifier
Identifier for the tuple, corresponding to its position in the loop nest.
Protected Attributes inherited from souffle::RamNestedOperation
std::unique_ptr< RamOperation > nestedOperation
Nested operation.
const std::string profileText
Text used by the profiler.
Protected Attributes inherited from souffle::RamAbstractChoice
std::unique_ptr< RamCondition > condition
Condition for which a tuple in the relation may hold.
Detailed Description
Use an index to find a tuple in a relation such that a given condition holds.
Only one tuple is returned (if one exists), even if multiple tuples satisfying the condition exist.
For example:
QUERY
 ...
  CHOICE A AS t1 ON INDEX t1.x=10 AND t1.y = 20
  WHERE (t1.x, t1.y) NOT IN A
    ...
Definition at line 629 of file Operation.h.
Constructor & Destructor Documentation
RamIndexChoice()
souffle::RamIndexChoice::RamIndexChoice (std::unique_ptr< RamRelationReference > r, int ident, std::unique_ptr< RamCondition > cond, RamPattern queryPattern, std::unique_ptr< RamOperation > nested, std::string profileText = "") inline
Definition at line 631 of file Operation.h.
References souffle::AstRelation::getArity(), and souffle::getRelation().
             : RamIndexOperation(std::move(r), ident, std::move(queryPattern), std::move(nested),
                       std::move(profileText)),
               RamAbstractChoice(std::move(cond)) {
         assert(getRangePattern().first.size() == getRelation().getArity());
         assert(getRangePattern().second.size() == getRelation().getArity());
     }
Member Function Documentation
apply()
void souffle::RamIndexChoice::apply (const RamNodeMapper &) inline override virtual
Apply the mapper to all child nodes.
Reimplemented from souffle::RamIndexOperation.
Definition at line 640 of file Operation.h.
References souffle::RamRelationOperation::apply(), souffle::RamAbstractChoice::apply(), and souffle::map().
{
         RamRelationOperation::apply(map);
         for (auto& pattern : queryPattern.first) {
             pattern = map(std::move(pattern));
         }
         for (auto& pattern : queryPattern.second) {
             pattern = map(std::move(pattern));
         }
         RamAbstractChoice::apply(map);
     }
clone()
RamIndexChoice* souffle::RamIndexChoice::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Reimplemented from souffle::RamIndexOperation.
Reimplemented in souffle::RamParallelIndexChoice.
Definition at line 657 of file Operation.h.
References souffle::clone(), and i.
Referenced by souffle::test::TEST().
{
         RamPattern resQueryPattern;
         for (const auto& i : queryPattern.first) {
             resQueryPattern.first.emplace_back(i->clone());
         }
         for (const auto& i : queryPattern.second) {
             resQueryPattern.second.emplace_back(i->clone());
         }
         auto* res = new RamIndexChoice(souffle::clone(relationRef), getTupleId(), souffle::clone(condition),
                 std::move(resQueryPattern), souffle::clone(&getOperation()), getProfileText());
         return res;
     }
equal()
bool souffle::RamIndexChoice::equal (const RamNode &) const inline override protected virtual
Equality check for two RAM nodes.
Default action is that nothing needs to be checked.
Reimplemented from souffle::RamIndexOperation.
Definition at line 681 of file Operation.h.
References souffle::RamIndexOperation::equal(), and souffle::RamAbstractChoice::equal().
{
         const auto& other = static_cast<const RamIndexChoice&>(node);
         return RamIndexOperation::equal(other) && RamAbstractChoice::equal(other);
     }
getChildNodes()
std::vector<const RamNode*> souffle::RamIndexChoice::getChildNodes () const inline override virtual
Obtain list of all embedded child nodes.
Reimplemented from souffle::RamIndexOperation.
Definition at line 651 of file Operation.h.
References souffle::RamIndexOperation::getChildNodes(), and souffle::RamAbstractChoice::getChildNodes().
{
         auto res = RamIndexOperation::getChildNodes();
         res.push_back(RamAbstractChoice::getChildNodes().at(0));
         return res;
     }
print()
void souffle::RamIndexChoice::print (std::ostream & os, int tabpos) const inline override protected virtual
Pretty print with indentation.
Reimplemented from souffle::RamNestedOperation.
Reimplemented in souffle::RamParallelIndexChoice.
Definition at line 671 of file Operation.h.
References souffle::RamRelation::getName(), souffle::getRelation(), souffle::RamNestedOperation::print(), and souffle::times().
{
         const RamRelation& rel = getRelation();
         os << times(" ", tabpos);
         os << "CHOICE " << rel.getName() << " AS t" << getTupleId();
         printIndex(os);
         os << " WHERE " << getCondition();
         os << std::endl;
         RamIndexOperation::print(os, tabpos + 1);
     }
The documentation for this class was generated from the following file:
ram/Operation.h