souffle: souffle::PrecedenceGraphAnalysis Class Reference
souffle::PrecedenceGraphAnalysis Class Reference
Analysis pass computing the precedence graph of the relations of the datalog progam.
#include <PrecedenceGraph.h>
Public Member Functions
const Graph< const AstRelation *, AstNameComparison > & graph () const
PrecedenceGraphAnalysis ()
void print (std::ostream &os) const override
Output precedence graph in graphviz format to a given stream.
void run (const AstTranslationUnit &translationUnit) override
run analysis for a Ast translation unit
Public Member Functions inherited from souffle::AstAnalysis
AstAnalysis (std::string identifier)
virtual const std::string & getName () const
get name of the analysis
virtual ~AstAnalysis ()=default
Static Public Attributes
static constexpr const char * name = "precedence-graph"
Private Attributes
Graph< const AstRelation *, AstNameComparison > backingGraph
Adjacency list of precedence graph (determined by the dependencies of the relations)
Additional Inherited Members
Protected Attributes inherited from souffle::AstAnalysis
const std::string identifier
Detailed Description
Analysis pass computing the precedence graph of the relations of the datalog progam.
Definition at line 34 of file PrecedenceGraph.h.
Constructor & Destructor Documentation
PrecedenceGraphAnalysis()
souffle::PrecedenceGraphAnalysis::PrecedenceGraphAnalysis () inline
Definition at line 38 of file PrecedenceGraph.h.
References print(), and run().
 : AstAnalysis(name) {}
Member Function Documentation
graph()
const Graph<const AstRelation*, AstNameComparison>& souffle::PrecedenceGraphAnalysis::graph () const inline
Definition at line 45 of file PrecedenceGraph.h.
References backingGraph.
Referenced by souffle::findInlineCycle(), souffle::SCCGraphAnalysis::getExternalNonOutputPredecessorRelations(), souffle::SCCGraphAnalysis::getExternalOutputPredecessorRelations(), souffle::SCCGraphAnalysis::getExternalPredecessorRelations(), souffle::SCCGraphAnalysis::getInternalNonOutputRelationsWithExternalSuccessors(), souffle::SCCGraphAnalysis::getInternalRelationsWithExternalSuccessors(), souffle::SCCGraphAnalysis::getPredecessorSCCs(), souffle::SCCGraphAnalysis::getSuccessorSCCs(), souffle::SCCGraphAnalysis::isRecursive(), souffle::RedundantRelationsAnalysis::run(), souffle::SCCGraphAnalysis::run(), and souffle::SCCGraphAnalysis::scR().
{
         return backingGraph;
     }
print()
void souffle::PrecedenceGraphAnalysis::print (std::ostream & os) const override virtual
Output precedence graph in graphviz format to a given stream.
Reimplemented from souffle::AstAnalysis.
Definition at line 49 of file PrecedenceGraph.cpp.
References backingGraph, souffle::AstAnalysis::getName(), souffle::printHTMLGraph(), and souffle::profile::ss.
Referenced by PrecedenceGraphAnalysis().
{
     /* Print dependency graph */
     std::stringstream ss;
     ss << "digraph {\n";
     /* Print node of dependence graph */
     for (const AstRelation* rel : backingGraph.vertices()) {
         if (rel != nullptr) {
             ss << "\t\"" << rel->getQualifiedName() << "\" [label = \"" << rel->getQualifiedName()
                << "\"];\n";
         }
     }
     for (const AstRelation* rel : backingGraph.vertices()) {
         if (rel != nullptr) {
             for (const AstRelation* adjRel : backingGraph.successors(rel)) {
                 if (adjRel != nullptr) {
                     ss << "\t\"" << rel->getQualifiedName() << "\" -> \"" << adjRel->getQualifiedName()
                        << "\";\n";
                 }
             }
         }
     }
     ss << "}\n";
     printHTMLGraph(os, ss.str(), getName());
 }
run()
void souffle::PrecedenceGraphAnalysis::run (const AstTranslationUnit &) override virtual
run analysis for a Ast translation unit
Implements souffle::AstAnalysis.
Definition at line 32 of file PrecedenceGraph.cpp.
References backingGraph, souffle::getBodyRelations(), souffle::getClauses(), souffle::AstTranslationUnit::getProgram(), souffle::AstProgram::getRelations(), and relations.
Referenced by PrecedenceGraphAnalysis().
{
     /* Get relations */
     const AstProgram& program = *translationUnit.getProgram();
     std::vector<AstRelation*> relations = program.getRelations();
     for (AstRelation* r : relations) {
         backingGraph.insert(r);
         for (const auto& c : getClauses(program, *r)) {
             const std::set<const AstRelation*>& dependencies =
                     getBodyRelations(c, translationUnit.getProgram());
             for (auto source : dependencies) {
                 backingGraph.insert(source, r);
             }
         }
     }
 }
Field Documentation
backingGraph
Graph<const AstRelation*, AstNameComparison> souffle::PrecedenceGraphAnalysis::backingGraph private
Adjacency list of precedence graph (determined by the dependencies of the relations)
Definition at line 51 of file PrecedenceGraph.h.
Referenced by graph(), print(), and run().
name
constexpr const char* souffle::PrecedenceGraphAnalysis::name = "precedence-graph" static
Definition at line 36 of file PrecedenceGraph.h.
The documentation for this class was generated from the following files:
ast/analysis/PrecedenceGraph.h
ast/analysis/PrecedenceGraph.cpp