souffle: souffle::MinimiseProgramTransformer Class Reference
souffle::MinimiseProgramTransformer Class Reference
Transformation pass to remove equivalent rules.
#include <MinimiseProgram.h>
Data Structures
class NormalisedClauseRepr
Public Member Functions
MinimiseProgramTransformer * clone () const override
std::string getName () const override
Public Member Functions inherited from souffle::AstTransformer
bool apply (AstTranslationUnit &translationUnit)
virtual ~AstTransformer ()=default
Static Public Member Functions
static bool areBijectivelyEquivalent (const AstClause *left, const AstClause *right)
Private Member Functions
bool transform (AstTranslationUnit &translationUnit) override
Static Private Member Functions
static bool areBijectivelyEquivalent (const NormalisedClauseRepr &left, const NormalisedClauseRepr &right)
– Bijective Equivalence Helper Methods –
static bool isValidPermutation (const NormalisedClauseRepr &left, const NormalisedClauseRepr &right, const std::vector< unsigned int > &permutation)
static bool reduceClauseBodies (AstTranslationUnit &translationUnit)
Remove redundant literals within a clause.
static bool reduceLocallyEquivalentClauses (AstTranslationUnit &translationUnit)
– Sub-Transformations –
static bool reduceSingletonRelations (AstTranslationUnit &translationUnit)
Removes redundant singleton relations.
static bool removeRedundantClauses (AstTranslationUnit &translationUnit)
Remove clauses that are only satisfied if they are already satisfied.
Detailed Description
Transformation pass to remove equivalent rules.
Definition at line 31 of file MinimiseProgram.h.
Member Function Documentation
areBijectivelyEquivalent() [1/2]
bool souffle::MinimiseProgramTransformer::areBijectivelyEquivalent (const AstClause * left, const AstClause * right) static
Definition at line 376 of file MinimiseProgram.cpp.
References souffle::MinimiseProgramTransformer::NormalisedClauseRepr::NormalisedClauseRepr().
Referenced by clone(), getName(), reduceLocallyEquivalentClauses(), reduceSingletonRelations(), and souffle::test::TEST().
{
     auto normalisedLeft = NormalisedClauseRepr(leftClause);
     auto normalisedRight = NormalisedClauseRepr(rightClause);
     return areBijectivelyEquivalent(normalisedLeft, normalisedRight);
 }
areBijectivelyEquivalent() [2/2]
bool souffle::MinimiseProgramTransformer::areBijectivelyEquivalent (const NormalisedClauseRepr & left, const NormalisedClauseRepr & right) static private
– Bijective Equivalence Helper Methods –
Definition at line 314 of file MinimiseProgram.cpp.
References souffle::extractPermutations(), souffle::MinimiseProgramTransformer::NormalisedClauseRepr::getConstants(), souffle::MinimiseProgramTransformer::NormalisedClauseRepr::getElements(), souffle::MinimiseProgramTransformer::NormalisedClauseRepr::getVariables(), i, souffle::MinimiseProgramTransformer::NormalisedClauseRepr::isFullyNormalised(), isValidPermutation(), j, souffle::MinimiseProgramTransformer::NormalisedClauseRepr::NormalisedClauseElementRepr::name, and souffle::MinimiseProgramTransformer::NormalisedClauseRepr::NormalisedClauseElementRepr::params.
{
     const auto& leftElements = left.getElements();
     const auto& rightElements = right.getElements();
     const auto& leftVars = left.getVariables();
     const auto& rightVars = right.getVariables();
     // rules must be fully normalised
     if (!left.isFullyNormalised() || !right.isFullyNormalised()) {
         return false;
     }
     // rules must be the same length to be equal
     if (leftElements.size() != rightElements.size()) {
         return false;
     }
     // head atoms must have the same arity (names do not matter)
     if (leftElements[0].params.size() != rightElements[0].params.size()) {
         return false;
     }
     // rules must have the same number of distinct variables
     if (leftVars.size() != rightVars.size()) {
         return false;
     }
     // rules must have the exact same set of constants
     if (left.getConstants() != right.getConstants()) {
         return false;
     }
     // set up the n x n permutation matrix, where n is the number of clause elements
     size_t size = leftElements.size();
     auto permutationMatrix = std::vector<std::vector<unsigned int>>(size);
     for (auto& i : permutationMatrix) {
         i = std::vector<unsigned int>(size);
     }
     // create permutation matrix
     permutationMatrix[0][0] = 1;
     for (size_t i = 1; i < size; i++) {
         for (size_t j = 1; j < size; j++) {
             if (leftElements[i].name == rightElements[j].name) {
                 permutationMatrix[i][j] = 1;
             }
         }
     }
     // check if any of these permutations have valid variable mappings
     std::vector<std::vector<unsigned int>> permutations = extractPermutations(permutationMatrix);
     for (auto permutation : permutations) {
         if (isValidPermutation(left, right, permutation)) {
             // valid permutation with valid mapping
             // therefore, the two clauses are equivalent!
             return true;
         }
     }
     return false;
 }
clone()
MinimiseProgramTransformer* souffle::MinimiseProgramTransformer::clone () const inline override virtual
Implements souffle::AstTransformer.
Definition at line 40 of file MinimiseProgram.h.
References areBijectivelyEquivalent(), isValidPermutation(), reduceClauseBodies(), reduceLocallyEquivalentClauses(), reduceSingletonRelations(), removeRedundantClauses(), and transform().
{
         return new MinimiseProgramTransformer();
     }
getName()
std::string souffle::MinimiseProgramTransformer::getName () const inline override virtual
Implements souffle::AstTransformer.
Definition at line 33 of file MinimiseProgram.h.
References areBijectivelyEquivalent().
{
         return "MinimiseProgramTransformer";
     }
isValidPermutation()
bool souffle::MinimiseProgramTransformer::isValidPermutation (const NormalisedClauseRepr & left, const NormalisedClauseRepr & right, const std::vector< unsigned int > & permutation) static private
Definition at line 271 of file MinimiseProgram.cpp.
References souffle::MinimiseProgramTransformer::NormalisedClauseRepr::getConstants(), souffle::MinimiseProgramTransformer::NormalisedClauseRepr::getElements(), souffle::MinimiseProgramTransformer::NormalisedClauseRepr::getVariables(), i, and j.
Referenced by areBijectivelyEquivalent(), and clone().
{
     const auto& leftElements = left.getElements();
     const auto& rightElements = right.getElements();
     assert(leftElements.size() == rightElements.size() && "clauses should have equal size");
     size_t size = leftElements.size();
     std::map<std::string, std::string> variableMap;
     // Constants should be fixed to the identically-named constant
     for (const auto& cst : left.getConstants()) {
         variableMap[cst] = cst;
     }
     // Variables start off mapping to nothing
     for (const auto& var : left.getVariables()) {
         variableMap[var] = "";
     }
     // Pass through the all arguments in the first clause in sequence, mapping each to the corresponding
     // argument in the second clause under the literal permutation
     for (size_t i = 0; i < size; i++) {
         const auto& leftArgs = leftElements[i].params;
         const auto& rightArgs = rightElements[permutation[i]].params;
         for (size_t j = 0; j < leftArgs.size(); j++) {
             auto leftArg = leftArgs[j];
             auto rightArg = rightArgs[j];
             std::string currentMap = variableMap[leftArg];
             if (currentMap.empty()) {
                 // unassigned yet, so assign it appropriately
                 variableMap[leftArg] = rightArg;
             } else if (currentMap != rightArg) {
                 // inconsistent mapping!
                 // clauses cannot be equivalent under this permutation
                 return false;
             }
         }
     }
     return true;
 }
reduceClauseBodies()
bool souffle::MinimiseProgramTransformer::reduceClauseBodies (AstTranslationUnit & translationUnit) static private
Remove redundant literals within a clause.
Definition at line 531 of file MinimiseProgram.cpp.
References souffle::clone(), souffle::contains(), souffle::AstTranslationUnit::getProgram(), i, j, and souffle::AstProgram::removeClause().
Referenced by clone(), and transform().
{
     auto& program = *translationUnit.getProgram();
     std::set<std::unique_ptr<AstClause>> clausesToAdd;
     std::set<std::unique_ptr<AstClause>> clausesToRemove;
     for (const auto* clause : program.getClauses()) {
         auto bodyLiterals = clause->getBodyLiterals();
         std::set<size_t> redundantPositions;
         for (size_t i = 0; i < bodyLiterals.size(); i++) {
             for (size_t j = 0; j < i; j++) {
                 if (*bodyLiterals[i] == *bodyLiterals[j]) {
                     redundantPositions.insert(j);
                     break;
                 }
             }
         }
         if (!redundantPositions.empty()) {
             auto minimisedClause = std::make_unique<AstClause>();
             minimisedClause->setHead(souffle::clone(clause->getHead()));
             for (size_t i = 0; i < bodyLiterals.size(); i++) {
                 if (!contains(redundantPositions, i)) {
                     minimisedClause->addToBody(souffle::clone(bodyLiterals[i]));
                 }
             }
             clausesToAdd.insert(std::move(minimisedClause));
             clausesToRemove.insert(souffle::clone(clause));
         }
     }
     for (auto& clause : clausesToRemove) {
         program.removeClause(clause.get());
     }
     for (auto& clause : clausesToAdd) {
         program.addClause(souffle::clone(clause));
     }
     return !clausesToAdd.empty();
 }
reduceLocallyEquivalentClauses()
bool souffle::MinimiseProgramTransformer::reduceLocallyEquivalentClauses (AstTranslationUnit & translationUnit) static private
– Sub-Transformations –
Reduces locally-redundant clauses. A clause is locally-redundant if there is another clause within the same relation that computes the same set of tuples.
Definition at line 383 of file MinimiseProgram.cpp.
References areBijectivelyEquivalent(), souffle::getClauses(), souffle::AstTranslationUnit::getProgram(), souffle::AstProgram::getRelations(), and souffle::AstProgram::removeClause().
Referenced by clone(), and transform().
{
     AstProgram& program = *translationUnit.getProgram();
     std::vector<AstClause*> clausesToDelete;
     // split up each relation's rules into equivalence classes
     // TODO (azreika): consider turning this into an ast analysis instead
     for (AstRelation* rel : program.getRelations()) {
         std::vector<std::vector<AstClause*>> equivalenceClasses;
         for (AstClause* clause : getClauses(program, *rel)) {
             bool added = false;
             for (std::vector<AstClause*>& eqClass : equivalenceClasses) {
                 AstClause* rep = eqClass[0];
                 if (areBijectivelyEquivalent(rep, clause)) {
                     // clause belongs to an existing equivalence class, so delete it
                     eqClass.push_back(clause);
                     clausesToDelete.push_back(clause);
                     added = true;
                     break;
                 }
             }
             if (!added) {
                 // clause does not belong to any existing equivalence class, so keep it
                 std::vector<AstClause*> clauseToAdd = {clause};
                 equivalenceClasses.push_back(clauseToAdd);
             }
         }
     }
     // remove non-representative clauses
     for (auto clause : clausesToDelete) {
         program.removeClause(clause);
     }
     // changed iff any clauses were deleted
     return !clausesToDelete.empty();
 }
reduceSingletonRelations()
bool souffle::MinimiseProgramTransformer::reduceSingletonRelations (AstTranslationUnit & translationUnit) static private
Removes redundant singleton relations.
Singleton relations are relations with a single clause. A singleton relation is redundant if there exists another singleton relation that computes the same set of tuples.
Returns
true iff the program was changed
Definition at line 425 of file MinimiseProgram.cpp.
References souffle::AstProgram::apply(), areBijectivelyEquivalent(), souffle::clone(), souffle::AstTranslationUnit::getAnalysis(), souffle::getClauses(), souffle::AstClause::getHead(), souffle::AstTranslationUnit::getProgram(), souffle::AstAtom::getQualifiedName(), souffle::getRelation(), souffle::AstProgram::getRelations(), i, j, souffle::AstProgram::removeClause(), and souffle::AstProgram::removeRelation().
Referenced by clone(), and transform().
{
     // Note: This reduction is particularly useful in conjunction with the
     // body-partitioning transformation
     AstProgram& program = *translationUnit.getProgram();
     auto* ioTypes = translationUnit.getAnalysis<IOType>();
     // Find all singleton relations to consider
     std::vector<AstClause*> singletonRelationClauses;
     for (AstRelation* rel : program.getRelations()) {
         if (!ioTypes->isIO(rel) && getClauses(program, *rel).size() == 1) {
             AstClause* clause = getClauses(program, *rel)[0];
             singletonRelationClauses.push_back(clause);
         }
     }
     // Keep track of clauses found to be redundant
     std::set<AstClause*> redundantClauses;
     // Keep track of canonical relation name for each redundant clause
     std::map<AstQualifiedName, AstQualifiedName> canonicalName;
     // Check pairwise equivalence of each singleton relation
     for (size_t i = 0; i < singletonRelationClauses.size(); i++) {
         AstClause* first = singletonRelationClauses[i];
         if (redundantClauses.find(first) != redundantClauses.end()) {
             // Already found to be redundant, no need to check
             continue;
         }
         for (size_t j = i + 1; j < singletonRelationClauses.size(); j++) {
             AstClause* second = singletonRelationClauses[j];
             // Note: Bijective-equivalence check does not care about the head relation name
             if (areBijectivelyEquivalent(first, second)) {
                 AstQualifiedName firstName = first->getHead()->getQualifiedName();
                 AstQualifiedName secondName = second->getHead()->getQualifiedName();
                 redundantClauses.insert(second);
                 canonicalName.insert(std::pair(secondName, firstName));
             }
         }
     }
     // Remove redundant relation definitions
     for (AstClause* clause : redundantClauses) {
         auto relName = clause->getHead()->getQualifiedName();
         AstRelation* rel = getRelation(program, relName);
         assert(rel != nullptr && "relation does not exist in program");
         program.removeClause(clause);
         program.removeRelation(relName);
     }
     // Replace each redundant relation appearance with its canonical name
     struct replaceRedundantRelations : public AstNodeMapper {
         const std::map<AstQualifiedName, AstQualifiedName>& canonicalName;
         replaceRedundantRelations(const std::map<AstQualifiedName, AstQualifiedName>& canonicalName)
                 : canonicalName(canonicalName) {}
         std::unique_ptr<AstNode> operator()(std::unique_ptr<AstNode> node) const override {
             // Remove appearances from children nodes
             node->apply(*this);
             if (auto* atom = dynamic_cast<AstAtom*>(node.get())) {
                 auto pos = canonicalName.find(atom->getQualifiedName());
                 if (pos != canonicalName.end()) {
                     auto newAtom = souffle::clone(atom);
                     newAtom->setQualifiedName(pos->second);
                     return newAtom;
                 }
             }
             return node;
         }
     };
     replaceRedundantRelations update(canonicalName);
     program.apply(update);
     // Program was changed iff a relation was replaced
     return !canonicalName.empty();
 }
removeRedundantClauses()
bool souffle::MinimiseProgramTransformer::removeRedundantClauses (AstTranslationUnit & translationUnit) static private
Remove clauses that are only satisfied if they are already satisfied.
Definition at line 506 of file MinimiseProgram.cpp.
References souffle::clone(), souffle::AstTranslationUnit::getProgram(), and souffle::AstProgram::removeClause().
Referenced by clone(), and transform().
{
     auto& program = *translationUnit.getProgram();
     auto isRedundant = [&](const AstClause* clause) {
         const auto* head = clause->getHead();
         for (const auto* lit : clause->getBodyLiterals()) {
             if (*head == *lit) {
                 return true;
             }
         }
         return false;
     };
     std::set<std::unique_ptr<AstClause>> clausesToRemove;
     for (const auto* clause : program.getClauses()) {
         if (isRedundant(clause)) {
             clausesToRemove.insert(souffle::clone(clause));
         }
     }
     for (auto& clause : clausesToRemove) {
         program.removeClause(clause.get());
     }
     return !clausesToRemove.empty();
 }
transform()
bool souffle::MinimiseProgramTransformer::transform (AstTranslationUnit & translationUnit) override private virtual
Implements souffle::AstTransformer.
Definition at line 571 of file MinimiseProgram.cpp.
References reduceClauseBodies(), reduceLocallyEquivalentClauses(), reduceSingletonRelations(), and removeRedundantClauses().
Referenced by clone().
{
     bool changed = false;
     changed |= reduceClauseBodies(translationUnit);
     changed |= removeRedundantClauses(translationUnit);
     changed |= reduceLocallyEquivalentClauses(translationUnit);
     changed |= reduceSingletonRelations(translationUnit);
     return changed;
 }
The documentation for this class was generated from the following files:
ast/transform/MinimiseProgram.h
ast/transform/MinimiseProgram.cpp