souffle: souffle::RamAbstractChoice Class Reference
souffle::RamAbstractChoice Class Reference
Abstract class for a choice operation.
#include <Operation.h>
Public Member Functions
void apply (const RamNodeMapper &map)
std::vector< const RamNode * > getChildNodes () const
const RamCondition & getCondition () const
Getter for the condition.
RamAbstractChoice (std::unique_ptr< RamCondition > cond)
Protected Member Functions
bool equal (const RamNode &node) const
Protected Attributes
std::unique_ptr< RamCondition > condition
Condition for which a tuple in the relation may hold.
Detailed Description
Abstract class for a choice operation.
Finding a single tuple, if it exists, such that a condition holds.
Definition at line 496 of file Operation.h.
Constructor & Destructor Documentation
RamAbstractChoice()
souffle::RamAbstractChoice::RamAbstractChoice (std::unique_ptr< RamCondition > cond) inline
Definition at line 498 of file Operation.h.
                                                         : condition(std::move(cond)) {
         assert(condition != nullptr && "Condition is a null-pointer");
     }
Member Function Documentation
apply()
void souffle::RamAbstractChoice::apply (const RamNodeMapper & map) inline
Definition at line 508 of file Operation.h.
References souffle::map().
Referenced by souffle::RamChoice::apply(), and souffle::RamIndexChoice::apply().
{
         condition = map(std::move(condition));
     }
equal()
bool souffle::RamAbstractChoice::equal (const RamNode & node) const inline protected
Definition at line 517 of file Operation.h.
References souffle::equal_ptr().
Referenced by souffle::RamChoice::equal(), and souffle::RamIndexChoice::equal().
{
         const auto& other = dynamic_cast<const RamAbstractChoice&>(node);
         return equal_ptr(condition, other.condition);
     }
getChildNodes()
std::vector<const RamNode*> souffle::RamAbstractChoice::getChildNodes () const inline
Definition at line 512 of file Operation.h.
Referenced by souffle::RamChoice::getChildNodes(), and souffle::RamIndexChoice::getChildNodes().
{
         return {condition.get()};
     }
getCondition()
const RamCondition& souffle::RamAbstractChoice::getCondition () const inline
Getter for the condition.
Definition at line 503 of file Operation.h.
Referenced by souffle::Synthesiser::emitCode(), and souffle::RamLevelAnalysis::getLevel().
{
         assert(condition != nullptr && "condition of choice is a null-pointer");
         return *condition;
     }
Field Documentation
condition
std::unique_ptr<RamCondition> souffle::RamAbstractChoice::condition protected
Condition for which a tuple in the relation may hold.
Definition at line 523 of file Operation.h.
The documentation for this class was generated from the following file:
ram/Operation.h