souffle: souffle::RamNode Class Reference
souffle::RamNode Class Reference abstract
RamNode is a superclass for all RAM IR classes.
#include <Node.h>
Public Member Functions
virtual void apply (const RamNodeMapper &)
Apply the mapper to all child nodes.
virtual RamNode * clone () const =0
Create a clone (i.e.
virtual std::vector< const RamNode * > getChildNodes () const
Obtain list of all embedded child nodes.
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
virtual void rewrite (const RamNode *oldNode, std::unique_ptr< RamNode > newNode)
Rewrite a child node.
virtual ~RamNode ()=default
Protected Member Functions
virtual bool equal (const RamNode &) const
Equality check for two RAM nodes.
virtual void print (std::ostream &out=std::cout) const =0
Print RAM node.
Friends
std::ostream & operator<< (std::ostream &out, const RamNode &node)
Print RAM on a stream.
Detailed Description
RamNode is a superclass for all RAM IR classes.
Definition at line 96 of file Node.h.
Constructor & Destructor Documentation
~RamNode()
virtual souffle::RamNode::~RamNode () virtual default
Member Function Documentation
apply()
virtual void souffle::RamNode::apply (const RamNodeMapper &) inline virtual
Apply the mapper to all child nodes.
Reimplemented in souffle::RamSubroutineReturn, souffle::RamProject, souffle::RamAbstractConditional, souffle::RamUnpackRecord, souffle::RamNestedIntrinsicOperator, souffle::RamIndexAggregate, souffle::RamAggregate, souffle::RamDebugInfo, souffle::RamLogTimer, souffle::RamLogRelationTimer, souffle::RamIndexChoice, souffle::RamExit, souffle::RamChoice, souffle::RamLoop, souffle::RamPackRecord, souffle::RamEmptinessCheck, souffle::RamListStatement, souffle::RamQuery, souffle::RamIndexOperation, souffle::RamAbstractExistenceCheck, souffle::RamConstraint, souffle::RamBinRelationStatement, souffle::RamRelationOperation, souffle::RamNegation, souffle::RamProgram, souffle::RamConjunction, souffle::RamNestedOperation, souffle::RamRelationStatement, and souffle::RamAbstractOperator.
Definition at line 125 of file Node.h.
 {}
clone()
virtual RamNode* souffle::RamNode::clone () const pure virtual
Create a clone (i.e.
deep copy) of this node
Implemented in souffle::RamSubroutineReturn, souffle::RamProject, souffle::RamBreak, souffle::RamFilter, souffle::RamAbstractConditional, souffle::RamUnpackRecord, souffle::RamNestedIntrinsicOperator, souffle::RamParallelIndexAggregate, souffle::RamIndexAggregate, souffle::RamParallelAggregate, souffle::RamAggregate, souffle::RamCall, souffle::RamLogSize, souffle::RamDebugInfo, souffle::RamParallelIndexChoice, souffle::RamLogTimer, souffle::RamIndexChoice, souffle::RamLogRelationTimer, souffle::RamParallelChoice, souffle::RamChoice, souffle::RamExit, souffle::RamLoop, souffle::RamParallelIndexScan, souffle::RamSubroutineArgument, souffle::RamParallel, souffle::RamIndexScan, souffle::RamEmptinessCheck, souffle::RamSequence, souffle::RamPackRecord, souffle::RamUndefValue, souffle::RamProvenanceExistenceCheck, souffle::RamAutoIncrement, souffle::RamExistenceCheck, souffle::RamFloatConstant, souffle::RamIndexOperation, souffle::RamQuery, souffle::RamUnsignedConstant, souffle::RamSwap, souffle::RamSignedConstant, souffle::RamParallelScan, souffle::RamExtend, souffle::RamScan, souffle::RamConstraint, souffle::RamTupleElement, souffle::RamRelationOperation, souffle::RamNegation, souffle::RamRelationReference, souffle::RamUserDefinedOperator, souffle::RamClear, souffle::RamTupleOperation, souffle::RamIO, souffle::RamConjunction, souffle::RamIntrinsicOperator, souffle::RamProgram, souffle::RamNestedOperation, souffle::RamRelation, souffle::RamFalse, souffle::RamTrue, souffle::RamOperation, souffle::RamStatement, souffle::RamCondition, and souffle::RamExpression.
equal()
virtual bool souffle::RamNode::equal (const RamNode &) const inline protected virtual
Equality check for two RAM nodes.
Default action is that nothing needs to be checked.
Reimplemented in souffle::RamSubroutineReturn, souffle::RamProject, souffle::RamAbstractConditional, souffle::RamUnpackRecord, souffle::RamNestedIntrinsicOperator, souffle::RamIndexAggregate, souffle::RamAggregate, souffle::RamCall, souffle::RamLogSize, souffle::RamIndexChoice, souffle::RamChoice, souffle::RamExit, souffle::RamLoop, souffle::RamSubroutineArgument, souffle::RamPackRecord, souffle::RamEmptinessCheck, souffle::RamIndexOperation, souffle::RamListStatement, souffle::RamQuery, souffle::RamAbstractExistenceCheck, souffle::RamConstant, souffle::RamConstraint, souffle::RamTupleElement, souffle::RamBinRelationStatement, souffle::RamRelationOperation, souffle::RamNegation, souffle::RamUserDefinedOperator, souffle::RamRelationReference, souffle::RamTupleOperation, souffle::RamProgram, souffle::RamIO, souffle::RamConjunction, souffle::RamNestedOperation, souffle::RamIntrinsicOperator, souffle::RamRelation, souffle::RamRelationStatement, and souffle::RamAbstractOperator.
Definition at line 170 of file Node.h.
{
         return true;
     }
getChildNodes()
virtual std::vector<const RamNode*> souffle::RamNode::getChildNodes () const inline virtual
Obtain list of all embedded child nodes.
Reimplemented in souffle::RamSubroutineReturn, souffle::RamProject, souffle::RamAbstractConditional, souffle::RamUnpackRecord, souffle::RamNestedIntrinsicOperator, souffle::RamIndexAggregate, souffle::RamAggregate, souffle::RamDebugInfo, souffle::RamLogTimer, souffle::RamIndexChoice, souffle::RamLogRelationTimer, souffle::RamChoice, souffle::RamExit, souffle::RamLoop, souffle::RamEmptinessCheck, souffle::RamPackRecord, souffle::RamListStatement, souffle::RamQuery, souffle::RamIndexOperation, souffle::RamAbstractExistenceCheck, souffle::RamConstraint, souffle::RamBinRelationStatement, souffle::RamRelationOperation, souffle::RamNegation, souffle::RamTupleOperation, souffle::RamConjunction, souffle::RamNestedOperation, souffle::RamRelationStatement, souffle::RamProgram, and souffle::RamAbstractOperator.
Definition at line 148 of file Node.h.
Referenced by souffle::visitDepthFirstPreOrder().
{
         return {};
     }
operator!=()
bool souffle::RamNode::operator!= (const RamNode & other) const inline
Inequality check for two RAM nodes.
Definition at line 113 of file Node.h.
References souffle::clone().
{
         return !(*this == other);
     }
operator==()
bool souffle::RamNode::operator== (const RamNode & other) const inline
Equivalence check for two RAM nodes.
Definition at line 106 of file Node.h.
{
         return this == &other || (typeid(*this) == typeid(other) && equal(other));
     }
print()
virtual void souffle::RamNode::print (std::ostream & out = std::cout) const protected pure virtual
Print RAM node.
Implemented in souffle::RamSubroutineArgument, souffle::RamPackRecord, souffle::RamEmptinessCheck, souffle::RamProvenanceExistenceCheck, souffle::RamUndefValue, souffle::RamAutoIncrement, souffle::RamFloatConstant, souffle::RamUnsignedConstant, souffle::RamAbstractExistenceCheck, souffle::RamSignedConstant, souffle::RamConstraint, souffle::RamTupleElement, souffle::RamNegation, souffle::RamUserDefinedOperator, souffle::RamRelationReference, souffle::RamProgram, souffle::RamConjunction, souffle::RamIntrinsicOperator, souffle::RamRelation, souffle::RamFalse, souffle::RamTrue, souffle::RamOperation, and souffle::RamStatement.
rewrite()
virtual void souffle::RamNode::rewrite (const RamNode * oldNode, std::unique_ptr< RamNode > newNode) inline virtual
Rewrite a child node.
Definition at line 130 of file Node.h.
References souffle::makeLambdaRamMapper().
Referenced by souffle::HoistConditionsTransformer::hoistConditions().
{
         assert(oldNode != nullptr && "old node is a null-pointer");
         assert(newNode != nullptr && "new node is a null-pointer");
         std::function<std::unique_ptr<RamNode>(std::unique_ptr<RamNode>)> rewriter =
                 [&](std::unique_ptr<RamNode> node) -> std::unique_ptr<RamNode> {
             if (oldNode == node.get()) {
                 return std::move(newNode);
             } else {
                 node->apply(makeLambdaRamMapper(rewriter));
                 return node;
             }
         };
         apply(makeLambdaRamMapper(rewriter));
     };
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & out, const RamNode & node) friend
Print RAM on a stream.
Definition at line 155 of file Node.h.
{
         node.print(out);
         return out;
     }
The documentation for this class was generated from the following file:
ram/Node.h