souffle: souffle::LogStatement Class Reference
souffle::LogStatement Class Reference
#include <LogStatement.h>
Static Public Member Functions
static const std::string cRecursiveRelation (const std::string &relationName, const SrcLocation &srcLocation)
static const std::string nNonrecursiveRelation (const std::string &relationName, const SrcLocation &srcLocation)
static const std::string nNonrecursiveRule (const std::string &relationName, const SrcLocation &srcLocation, const std::string &datalogText)
static const std::string nRecursiveRelation (const std::string &relationName, const SrcLocation &srcLocation)
static const std::string nRecursiveRule (const std::string &relationName, const int version, const SrcLocation &srcLocation, const std::string &datalogText)
static const std::string pProofCounter (const std::string &relationName, const SrcLocation &srcLocation, const std::string &datalogText)
static const std::string runtime ()
static const std::string startDebug ()
static const std::string tNonrecursiveRelation (const std::string &relationName, const SrcLocation &srcLocation)
static const std::string tNonrecursiveRule (const std::string &relationName, const SrcLocation &srcLocation, const std::string &datalogText)
static const std::string tRecursiveRelation (const std::string &relationName, const SrcLocation &srcLocation)
static const std::string tRecursiveRule (const std::string &relationName, const int version, const SrcLocation &srcLocation, const std::string &datalogText)
static const std::string tRelationLoadTime (const std::string &relationName, const SrcLocation &srcLocation)
static const std::string tRelationSaveTime (const std::string &relationName, const SrcLocation &srcLocation)
Detailed Description
Definition at line 23 of file LogStatement.h.
Member Function Documentation
cRecursiveRelation()
static const std::string souffle::LogStatement::cRecursiveRelation (const std::string & relationName, const SrcLocation & srcLocation) inline static
Definition at line 106 of file LogStatement.h.
Referenced by souffle::AstToRamTranslator::translateRecursiveRelation().
{
         const char* messageType = "@c-recursive-relation";
         std::stringstream line;
         line << messageType << ";" << relationName << ";" << srcLocation << ";";
         return line.str();
     }
nNonrecursiveRelation()
static const std::string souffle::LogStatement::nNonrecursiveRelation (const std::string & relationName, const SrcLocation & srcLocation) inline static
Definition at line 48 of file LogStatement.h.
Referenced by souffle::AstToRamTranslator::translateNonRecursiveRelation().
{
         const char* messageType = "@n-nonrecursive-relation";
         std::stringstream line;
         line << messageType << ";" << relationName << ";" << srcLocation << ";";
         return line.str();
     }
nNonrecursiveRule()
static const std::string souffle::LogStatement::nNonrecursiveRule (const std::string & relationName, const SrcLocation & srcLocation, const std::string & datalogText) inline static
Definition at line 64 of file LogStatement.h.
Referenced by souffle::AstToRamTranslator::translateNonRecursiveRelation().
{
         const char* messageType = "@n-nonrecursive-rule";
         std::stringstream line;
         line << messageType << ";" << relationName << ";" << srcLocation << ";" << datalogText << ";";
         return line.str();
     }
nRecursiveRelation()
static const std::string souffle::LogStatement::nRecursiveRelation (const std::string & relationName, const SrcLocation & srcLocation) inline static
Definition at line 98 of file LogStatement.h.
Referenced by souffle::AstToRamTranslator::translateRecursiveRelation().
{
         const char* messageType = "@n-recursive-relation";
         std::stringstream line;
         line << messageType << ";" << relationName << ";" << srcLocation << ";";
         return line.str();
     }
nRecursiveRule()
static const std::string souffle::LogStatement::nRecursiveRule (const std::string & relationName, const int version, const SrcLocation & srcLocation, const std::string & datalogText) inline static
Definition at line 81 of file LogStatement.h.
Referenced by souffle::AstToRamTranslator::translateRecursiveRelation().
{
         const char* messageType = "@n-recursive-rule";
         std::stringstream line;
         line << messageType << ";" << relationName << ";" << version << ";" << srcLocation << ";"
              << datalogText << ";";
         return line.str();
     }
pProofCounter()
static const std::string souffle::LogStatement::pProofCounter (const std::string & relationName, const SrcLocation & srcLocation, const std::string & datalogText) inline static
Definition at line 114 of file LogStatement.h.
{
         // TODO (#590): the profiler should be modified to use this type of log message, as currently these
         // messages are ignored
         const char* messageType = "#p-proof-counter";
         std::stringstream line;
         line << messageType << ";" << relationName << ";" << srcLocation << ";" << datalogText << ";";
         // TODO (#590): the additional semicolon is added to maintain backwards compatibility and should
         // eventually be removed
         line << ";";
         return line.str();
     }
runtime()
static const std::string souffle::LogStatement::runtime () inline static
Definition at line 127 of file LogStatement.h.
Referenced by souffle::AstToRamTranslator::translateProgram().
{
         const char* messageType = "@runtime";
         std::stringstream line;
         line << messageType << ";";
         return line.str();
     }
startDebug()
static const std::string souffle::LogStatement::startDebug () inline static
Definition at line 134 of file LogStatement.h.
{
         const char* messageType = "@start-debug";
         std::stringstream line;
         line << messageType;
         return line.str();
     }
tNonrecursiveRelation()
static const std::string souffle::LogStatement::tNonrecursiveRelation (const std::string & relationName, const SrcLocation & srcLocation) inline static
Definition at line 25 of file LogStatement.h.
Referenced by souffle::AstToRamTranslator::translateNonRecursiveRelation().
{
         const char* messageType = "@t-nonrecursive-relation";
         std::stringstream line;
         line << messageType << ";" << relationName << ";" << srcLocation << ";";
         return line.str();
     }
tNonrecursiveRule()
static const std::string souffle::LogStatement::tNonrecursiveRule (const std::string & relationName, const SrcLocation & srcLocation, const std::string & datalogText) inline static
Definition at line 56 of file LogStatement.h.
Referenced by souffle::AstToRamTranslator::translateNonRecursiveRelation().
{
         const char* messageType = "@t-nonrecursive-rule";
         std::stringstream line;
         line << messageType << ";" << relationName << ";" << srcLocation << ";" << datalogText << ";";
         return line.str();
     }
tRecursiveRelation()
static const std::string souffle::LogStatement::tRecursiveRelation (const std::string & relationName, const SrcLocation & srcLocation) inline static
Definition at line 90 of file LogStatement.h.
Referenced by souffle::AstToRamTranslator::translateRecursiveRelation().
{
         const char* messageType = "@t-recursive-relation";
         std::stringstream line;
         line << messageType << ";" << relationName << ";" << srcLocation << ";";
         return line.str();
     }
tRecursiveRule()
static const std::string souffle::LogStatement::tRecursiveRule (const std::string & relationName, const int version, const SrcLocation & srcLocation, const std::string & datalogText) inline static
Definition at line 72 of file LogStatement.h.
Referenced by souffle::AstToRamTranslator::translateRecursiveRelation().
{
         const char* messageType = "@t-recursive-rule";
         std::stringstream line;
         line << messageType << ";" << relationName << ";" << version << ";" << srcLocation << ";"
              << datalogText << ";";
         return line.str();
     }
tRelationLoadTime()
static const std::string souffle::LogStatement::tRelationLoadTime (const std::string & relationName, const SrcLocation & srcLocation) inline static
Definition at line 32 of file LogStatement.h.
Referenced by souffle::AstToRamTranslator::translateProgram().
{
         const char* messageType = "@t-relation-loadtime";
         std::stringstream line;
         line << messageType << ";" << relationName << ";" << srcLocation << ";loadtime;";
         return line.str();
     }
tRelationSaveTime()
static const std::string souffle::LogStatement::tRelationSaveTime (const std::string & relationName, const SrcLocation & srcLocation) inline static
Definition at line 40 of file LogStatement.h.
Referenced by souffle::AstToRamTranslator::translateProgram().
{
         const char* messageType = "@t-relation-savetime";
         std::stringstream line;
         line << messageType << ";" << relationName << ";" << srcLocation << ";savetime;";
         return line.str();
     }
The documentation for this class was generated from the following file:
LogStatement.h