souffle: souffle::LRUCache< T, size > Class Template Reference
souffle::LRUCache< T, size > Class Template Reference
An Least-Recently-Used cache for arbitrary element types.
#include <CacheUtil.h>
Public Member Functions
void access (const T &val)
template<typename Op >
bool any (const Op &op) const
void clear (const T &val=T())
template<typename Op >
bool forEachInOrder (const Op &op) const
Iterates over the elements within this cache in LRU order.
LRUCache (const T &val=T())
Private Attributes
std::array< T, size > entries
std::size_t first {0}
std::size_t last {size - 1}
std::array< std::size_t, size > post
std::array< std::size_t, size > priv
Detailed Description
template<typename T, unsigned size = 1>
class souffle::LRUCache< T, size >
An Least-Recently-Used cache for arbitrary element types.
Elements can be signaled to be accessed and iterated through in their LRU order.
Definition at line 33 of file CacheUtil.h.
Constructor & Destructor Documentation
LRUCache()
template<typename T, unsigned size = 1> souffle::LRUCache< T, size >::LRUCache (const T & val = T()) inline
Definition at line 46 of file CacheUtil.h.
{
         for (unsigned i = 0; i < size; i++) {
             entries[i] = val;
             priv[i] = i - 1;
             post[i] = i + 1;
         }
         priv[first] = last;
         post[last] = first;
     }
Member Function Documentation
access()
template<typename T, unsigned size = 1> void souffle::LRUCache< T, size >::access (const T & val) inline
Definition at line 64 of file CacheUtil.h.
{
         // test whether it is contained
         for (std::size_t i = 0; i < size; i++) {
             if (entries[i] != val) {
                 continue;
             }
             // -- move this one to the front --
             // if it is the first, nothing to handle
             if (i == first) {
                 return;
             }
             // if this is the last, just first and last need to change
             if (i == last) {
                 auto tmp = last;
                 last = priv[last];
                 first = tmp;
                 return;
             }
             // otherwise we need to update the linked list
             // remove from current position
             post[priv[i]] = post[i];
             priv[post[i]] = priv[i];
             // insert in first position
             post[i] = first;
             priv[i] = last;
             priv[first] = i;
             post[last] = i;
             // update first pointer
             first = i;
             return;
         }
         // not present => drop last, make it first
         entries[last] = val;
         auto tmp = last;
         last = priv[last];
         first = tmp;
     }
any()
template<typename T, unsigned size = 1> template<typename Op > bool souffle::LRUCache< T, size >::any (const Op & op) const inline
Definition at line 130 of file CacheUtil.h.
{
         return forEachInOrder(op);
     }
clear()
template<typename T, unsigned size = 1> void souffle::LRUCache< T, size >::clear (const T & val = T()) inline
Definition at line 57 of file CacheUtil.h.
Referenced by souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::btree_operation_hints< size >::clear().
{
         for (auto& cur : entries) {
             cur = val;
         }
     }
forEachInOrder()
template<typename T, unsigned size = 1> template<typename Op > bool souffle::LRUCache< T, size >::forEachInOrder (const Op & op) const inline
Iterates over the elements within this cache in LRU order.
The operator is applied on each element. If the operation returns false, iteration is continued. If the operator return true, iteration is stopped – similar to the any operator.
Parameters
op the operator to be applied on every element
Returns
true if op returned true for any entry, false otherwise
Definition at line 119 of file CacheUtil.h.
Referenced by souffle::LRUCache< node *, size >::any(), souffle::LRUCache< T, 1 >::any(), and souffle::LRUCache< T, 0 >::any().
{
         std::size_t i = first;
         while (i != last) {
             if (op(entries[i])) return true;
             i = post[i];
         }
         return op(entries[i]);
     }
Field Documentation
entries
template<typename T, unsigned size = 1> std::array<T, size> souffle::LRUCache< T, size >::entries private
Definition at line 35 of file CacheUtil.h.
first
template<typename T, unsigned size = 1> std::size_t souffle::LRUCache< T, size >::first {0} private
Definition at line 41 of file CacheUtil.h.
Referenced by souffle::LRUCache< node *, size >::access(), souffle::LRUCache< node *, size >::forEachInOrder(), souffle::LRUCache< node *, size >::LRUCache(), and souffle::operator<<().
last
template<typename T, unsigned size = 1> std::size_t souffle::LRUCache< T, size >::last {size - 1} private
Definition at line 42 of file CacheUtil.h.
Referenced by souffle::LRUCache< node *, size >::access(), souffle::LRUCache< node *, size >::forEachInOrder(), and souffle::LRUCache< node *, size >::LRUCache().
post
template<typename T, unsigned size = 1> std::array<std::size_t, size> souffle::LRUCache< T, size >::post private
Definition at line 39 of file CacheUtil.h.
priv
template<typename T, unsigned size = 1> std::array<std::size_t, size> souffle::LRUCache< T, size >::priv private
Definition at line 38 of file CacheUtil.h.
The documentation for this class was generated from the following file:
utility/CacheUtil.h