souffle: souffle::ProfileEventSingleton::ProfileTimer Class Reference
souffle::ProfileEventSingleton::ProfileTimer Class Reference
Profile Timer.
Public Member Functions
ProfileTimer (uint32_t interval=10)
void resetTimerInterval (uint32_t interval=10)
Reset timer interval.
void start ()
start timer on the thread th
void stop ()
stop timer on the thread th
Private Member Functions
uint32_t getInterval ()
void increaseInterval ()
Increase value of time interval by factor of 2.
void run ()
run method for thread th
Private Attributes
std::condition_variable conditionVariable
std::atomic< uint32_t > runCount {0}
number of utilisation events
std::atomic< bool > running {false}
timer is running
uint32_t t
time interval between per utilisation read
std::thread th
thread timer runs on
std::mutex timerMutex
Detailed Description
Profile Timer.
Definition at line 140 of file ProfileEvent.h.
Constructor & Destructor Documentation
ProfileTimer()
souffle::ProfileEventSingleton::ProfileTimer::ProfileTimer (uint32_t interval = 10) inline
Definition at line 182 of file ProfileEvent.h.
 : t(interval) {}
Member Function Documentation
getInterval()
uint32_t souffle::ProfileEventSingleton::ProfileTimer::getInterval () inline private
Definition at line 166 of file ProfileEvent.h.
{
             return t;
         }
increaseInterval()
void souffle::ProfileEventSingleton::ProfileTimer::increaseInterval () inline private
Increase value of time interval by factor of 2.
Definition at line 171 of file ProfileEvent.h.
{
             // Don't increase time interval past 60 seconds
             if (t < 60000) {
                 t = t * 2;
             }
         }
resetTimerInterval()
void souffle::ProfileEventSingleton::ProfileTimer::resetTimerInterval (uint32_t interval = 10) inline
Reset timer interval.
The timer interval increases as the program executes. Resetting the interval is useful to ensure that detailed usage information is gathered even in long running programs, if desired.
Parameters
interval the size of the timing interval in milliseconds
Definition at line 216 of file ProfileEvent.h.
Referenced by souffle::ProfileEventSingleton::resetTimerInterval().
{
             t = interval;
             runCount = 0;
             conditionVariable.notify_all();
         }
run()
void souffle::ProfileEventSingleton::ProfileTimer::run () inline private
run method for thread th
Definition at line 158 of file ProfileEvent.h.
References souffle::ProfileEventSingleton::instance(), and souffle::ProfileEventSingleton::makeUtilisationEvent().
                    {
             ProfileEventSingleton::instance().makeUtilisationEvent("@utilisation");
             ++runCount;
             if (runCount % 128 == 0) {
                 increaseInterval();
             }
         }
start()
void souffle::ProfileEventSingleton::ProfileTimer::start () inline
start timer on the thread th
Definition at line 185 of file ProfileEvent.h.
Referenced by souffle::ProfileEventSingleton::startTimer().
                      {
             if (running) {
                 return;
             }
             running = true;
             th = std::thread([this]() {
                 while (running) {
                     run();
                     std::unique_lock<std::mutex> lock(timerMutex);
                     conditionVariable.wait_for(lock, std::chrono::milliseconds(getInterval()));
                 }
             });
         }
stop()
void souffle::ProfileEventSingleton::ProfileTimer::stop () inline
stop timer on the thread th
Definition at line 201 of file ProfileEvent.h.
Referenced by souffle::ProfileEventSingleton::stopTimer().
                     {
             running = false;
             conditionVariable.notify_all();
             if (th.joinable()) {
                 th.join();
             }
         }
Field Documentation
conditionVariable
std::condition_variable souffle::ProfileEventSingleton::ProfileTimer::conditionVariable private
Definition at line 151 of file ProfileEvent.h.
runCount
std::atomic<uint32_t> souffle::ProfileEventSingleton::ProfileTimer::runCount {0} private
number of utilisation events
Definition at line 155 of file ProfileEvent.h.
running
std::atomic<bool> souffle::ProfileEventSingleton::ProfileTimer::running {false} private
timer is running
Definition at line 146 of file ProfileEvent.h.
t
uint32_t souffle::ProfileEventSingleton::ProfileTimer::t private
time interval between per utilisation read
Definition at line 143 of file ProfileEvent.h.
th
std::thread souffle::ProfileEventSingleton::ProfileTimer::th private
thread timer runs on
Definition at line 149 of file ProfileEvent.h.
timerMutex
std::mutex souffle::ProfileEventSingleton::ProfileTimer::timerMutex private
Definition at line 152 of file ProfileEvent.h.
The documentation for this class was generated from the following file:
ProfileEvent.h