souffle: souffle::SubsetType Class Reference
souffle::SubsetType Class Reference
A type being a subset of another type.
#include <TypeSystem.h>
Public Member Functions
const Type & getBaseType () const
void print (std::ostream &out) const override
Public Member Functions inherited from souffle::Type
const AstQualifiedName & getName () const
const TypeEnvironment & getTypeEnvironment () const
bool operator!= (const Type &other) const
bool operator< (const Type &other) const
bool operator== (const Type &other) const
Type (const Type &other)=delete
virtual ~Type ()=default
Protected Member Functions
SubsetType (const TypeEnvironment &environment, const AstQualifiedName &name, const Type &base)
Protected Member Functions inherited from souffle::Type
Type (const TypeEnvironment &environment, AstQualifiedName name)
Private Attributes
const Type & baseType
Friends
class TypeEnvironment
Additional Inherited Members
Protected Attributes inherited from souffle::Type
const TypeEnvironment & environment
A reference to the type environment this type is associated to.
AstQualifiedName name
Detailed Description
A type being a subset of another type.
Definition at line 101 of file TypeSystem.h.
Constructor & Destructor Documentation
SubsetType()
souffle::SubsetType::SubsetType (const TypeEnvironment & environment, const AstQualifiedName & name, const Type & base) inline protected
Definition at line 110 of file TypeSystem.h.
             : Type(environment, name), baseType(base){};
Member Function Documentation
getBaseType()
const Type& souffle::SubsetType::getBaseType () const inline
Definition at line 105 of file TypeSystem.h.
Referenced by souffle::isOfRootType().
{
         return baseType;
     }
print()
void souffle::SubsetType::print (std::ostream & out) const override virtual
Reimplemented from souffle::Type.
Reimplemented in souffle::SubsetRecordType, and souffle::PrimitiveType.
Definition at line 26 of file TypeSystem.cpp.
References baseType, tinyformat::format(), and souffle::Type::getName().
Referenced by souffle::SubsetRecordType::print().
{
     out << tfm::format("%s <: %s", getName(), baseType.getName());
 }
Friends And Related Function Documentation
TypeEnvironment
friend class TypeEnvironment friend
Definition at line 111 of file TypeSystem.h.
Field Documentation
baseType
const Type& souffle::SubsetType::baseType private
Definition at line 116 of file TypeSystem.h.
Referenced by print().
The documentation for this class was generated from the following files:
ast/TypeSystem.h
ast/TypeSystem.cpp