souffle: souffle::profile::Tui Class Reference
souffle::profile::Tui Class Reference
#include <Tui.h>
Data Structures
struct Usage
Public Member Functions
std::stringstream & genJsonRelations (std::stringstream &ss, const std::string &name, size_t maxRows)
std::stringstream & genJsonTop (std::stringstream &ss)
ss<< R"_(], "copy_t": [)_";firstCol=true;for(auto &i :iter) { comma(firstCol);ss<< i-> getCopytime ().count()
ss<< R"_({"tot_t": [)_";firstCol=true;for(auto &i :iter) { comma(firstCol);ss<< i-> getRuntime ().count()
void runCommand (std::vector< std::string > c)
void runProf ()
ss<< R"_(], "tuples": [)_";firstCol=true;for(auto &i :iter) { comma(firstCol);ss<< i-> size ()
Tui (std::string filename, bool live, bool)
Tui ()
~Tui ()
Data Fields
ss<< "], ";std::vector< std::shared_ptr< Iteration > > iter
Private Attributes
bool alive = false
std::string f_name
InputReader linereader
bool loaded
OutputProcessor out
int precision = 3
std::shared_ptr< Reader > reader
Table relationTable
size_t resultLimit = 20000
Limit results shown. Default value chosen to approximate unlimited.
Table ruleTable
int sortColumn = 0
std::thread updater
Detailed Description
Definition at line 39 of file Tui.h.
Constructor & Destructor Documentation
Tui() [1/2]
souffle::profile::Tui::Tui (std::string filename, bool live, bool) inline
Definition at line 66 of file Tui.h.
References souffle::profile::OutputProcessor::getProgramRun().
{
         // Set a friendlier output size if we're being interacted with directly.
         if (live) {
             resultLimit = 20;
         }
         this->f_name = filename;
         const std::shared_ptr<ProgramRun>& run = out.getProgramRun();
         this->reader = std::make_shared<Reader>(filename, run);
         this->alive = false;
         updateDB();
         this->loaded = reader->isLoaded();
     }
Tui() [2/2]
souffle::profile::Tui::Tui () inline
Definition at line 82 of file Tui.h.
References souffle::profile::OutputProcessor::getProgramRun(), souffle::profile::InputReader::hasReceivedInput(), souffle::test::now(), and runCommand().
           {
         const std::shared_ptr<ProgramRun>& run = out.getProgramRun();
         this->reader = std::make_shared<Reader>(run);
         this->loaded = true;
         this->alive = true;
         updateDB();
         updater = std::thread([this]() {
             // Update the display every 30s. Check for input every 0.5s
             std::chrono::milliseconds interval(30000);
             auto nextUpdateTime = std::chrono::high_resolution_clock::now();
             do {
                 std::this_thread::sleep_for(std::chrono::milliseconds(500));
                 if (nextUpdateTime < std::chrono::high_resolution_clock::now()) {
                     runCommand({});
                     nextUpdateTime = std::chrono::high_resolution_clock::now() + interval;
                 }
             } while (reader->isLive() && !linereader.hasReceivedInput());
         });
     }
~Tui()
souffle::profile::Tui::~Tui () inline
Definition at line 102 of file Tui.h.
            {
         if (updater.joinable()) {
             updater.join();
         }
     }
Member Function Documentation
genJsonRelations()
std::stringstream& souffle::profile::Tui::genJsonRelations (std::stringstream & ss, const std::string & name, size_t maxRows) inline
Definition at line 252 of file Tui.h.
References souffle::profile::Tools::cleanJsonOut(), souffle::profile::OutputProcessor::getProgramRun(), souffle::profile::Table::getRows(), i, souffle::profile::ss, and souffle::toString().
Referenced by genJsonAtoms().
{
         const std::shared_ptr<ProgramRun>& run = out.getProgramRun();
         auto comma = [&ss](bool& first, const std::string& delimiter = ", ") {
             if (!first) {
                 ss << delimiter;
             } else {
                 first = false;
             }
         };
         ss << '"' << name << R"_(":{)_";
         bool firstRow = true;
         auto rows = relationTable.getRows();
         std::stable_sort(rows.begin(), rows.end(), [](std::shared_ptr<Row> left, std::shared_ptr<Row> right) {
             return (*left)[0]->getDoubleVal() > (*right)[0]->getDoubleVal();
         });
         maxRows = std::min(rows.size(), maxRows);
         for (size_t i = 0; i < maxRows; ++i) {
             comma(firstRow, ",\n");
             Row& row = *rows[i];
             ss << '"' << row[6]->toString(0) << R"_(": [)_";
             ss << '"' << Tools::cleanJsonOut(row[5]->toString(0)) << R"_(", )_";
             ss << '"' << Tools::cleanJsonOut(row[6]->toString(0)) << R"_(", )_";
             ss << row[0]->getDoubleVal() << ", ";
             ss << row[1]->getDoubleVal() << ", ";
             ss << row[2]->getDoubleVal() << ", ";
             ss << row[3]->getDoubleVal() << ", ";
             ss << row[4]->getLongVal() << ", ";
             ss << row[12]->getLongVal() << ", ";
             ss << '"' << Tools::cleanJsonOut(row[7]->toString(0)) << R"_(", [)_";
             bool firstCol = true;
             for (auto& _rel_row : ruleTable.getRows()) {
                 Row rel_row = *_rel_row;
                 if (rel_row[7]->toString(0) == row[5]->toString(0)) {
                     comma(firstCol);
                     ss << '"' << rel_row[6]->toString(0) << '"';
                 }
             }
genJsonTop()
std::stringstream& souffle::profile::Tui::genJsonTop (std::stringstream & ss) inline
Definition at line 241 of file Tui.h.
References souffle::test::count(), souffle::profile::OutputProcessor::getProgramRun(), and souffle::profile::ss.
Referenced by genJsonAtoms().
{
         const std::shared_ptr<ProgramRun>& run = out.getProgramRun();
         auto beginTime = run->getStarttime();
         auto endTime = run->getEndtime();
         ss << R"_({"top":[)_" << (endTime - beginTime).count() / 1000000.0 << "," << run->getTotalSize()
            << "," << run->getTotalLoadtime().count() / 1000000.0 << ","
            << run->getTotalSavetime().count() / 1000000.0 << "]";
         return ss;
     }
getCopytime()
ss<< R"_(], "copy_t": [)_"; firstCol = true; for (auto& i : iter) { comma(firstCol); ss << i-> souffle::profile::Tui::getCopytime ()
getRuntime()
ss<< R"_({"tot_t": [)_"; firstCol = true; for (auto& i : iter) { comma(firstCol); ss << i-> souffle::profile::Tui::getRuntime ()
runCommand()
void souffle::profile::Tui::runCommand (std::vector< std::string > c) inline
Definition at line 108 of file Tui.h.
References souffle::profile::OutputProcessor::getRelTable(), souffle::profile::OutputProcessor::getRulTable(), souffle::profile::InputReader::hasReceivedInput(), and tinyformat::printf().
Referenced by souffle::profile::Cli::parse(), runProf(), and Tui().
{
         if (linereader.hasReceivedInput() && c.empty()) {
             return;
         }
         if (!loaded) {
             std::cout << "Error: File cannot be loaded\n";
             return;
         }
         if (alive) {
             updateDB();
             // remake tables to get new data
             ruleTable = out.getRulTable();
             relationTable = out.getRelTable();
             setupTabCompletion();
         }
         // If we have not received any input yet in live mode then run top.
         if ((!linereader.hasReceivedInput() && c.empty())) {
             // Move up n lines and overwrite the previous top output.
             std::cout << "\x1b[3D";
             std::cout << "\x1b[27A";
             top();
             std::cout << "\x1b[B> ";
         } else if (c[0] == "top") {
             top();
         } else if (c[0] == "rel") {
             if (c.size() == 2) {
                 relRul(c[1]);
             } else if (c.size() == 1) {
                 rel(resultLimit);
             } else {
                 std::cout << "Invalid parameters to rel command.\n";
             }
         } else if (c[0] == "rul") {
             if (c.size() > 1) {
                 if (c.size() == 3 && c[1] == "id") {
                     std::printf("%7s%2s%s\n\n", "ID", "", "NAME");
                     id(c[2]);
                 } else if (c.size() == 2 && c[1] == "id") {
                     id("0");
                 } else if (c.size() == 2) {
                     verRul(c[1]);
                 } else {
                     std::cout << "Invalid parameters to rul command.\n";
                 }
             } else {
                 rul(resultLimit);
             }
         } else if (c[0] == "graph") {
             if (c.size() == 3 && c[1].find(".") == std::string::npos) {
                 iterRel(c[1], c[2]);
             } else if (c.size() == 3 && c[1].at(0) == 'C') {
                 iterRul(c[1], c[2]);
             } else if (c.size() == 4 && c[1] == "ver" && c[2].at(0) == 'C') {
                 verGraph(c[2], c[3]);
             } else {
                 std::cout << "Invalid parameters to graph command.\n";
             }
         } else if (c[0] == "memory") {
             memoryUsage();
         } else if (c[0] == "usage") {
             if (c.size() > 1) {
                 if (c[1][0] == 'R') {
                     usageRelation(c[1]);
                 } else {
                     usageRule(c[1]);
                 }
             } else {
                 usage();
             }
         } else if (c[0] == "help") {
             help();
         } else if (c[0] == "limit") {
             if (c.size() == 1) {
                 setResultLimit(20000);
             } else {
                 try {
                     setResultLimit(std::stoul(c[1]));
                 } catch (...) {
                     std::cout << "Invalid parameters to limit command.\n";
                 }
             }
         } else if (c[0] == "configuration") {
             configuration();
         } else {
             std::cout << "Unknown command. Use \"help\" for a list of commands.\n";
         }
     }
runProf()
void souffle::profile::Tui::runProf () inline
Definition at line 199 of file Tui.h.
References souffle::profile::InputReader::addHistory(), souffle::profile::InputReader::getInput(), souffle::input, runCommand(), souffle::profile::InputReader::setPrompt(), souffle::profile::Tools::split(), and souffle::profile::Tools::trimWhitespace().
Referenced by souffle::main(), and souffle::profile::Cli::parse().
                    {
         if (!loaded && !f_name.empty()) {
             std::cout << "Error: File cannot be floaded\n";
             return;
         }
         if (loaded) {
             std::cout << "SouffleProf\n";
             top();
         }
         linereader.setPrompt("\n> ");
         setupTabCompletion();
         while (true) {
             std::string untrimmedInput = linereader.getInput();
             std::string input = Tools::trimWhitespace(untrimmedInput);
             std::cout << std::endl;
             if (input.empty()) {
                 std::cout << "Unknown command. Type help for a list of commands.\n";
                 continue;
             }
             linereader.addHistory(input);
             std::vector<std::string> c = Tools::split(input, " ");
             if (c[0] == "q" || c[0] == "quit") {
                 quit();
                 break;
             } else if (c[0] == "sort") {
                 if (c.size() == 2 && std::stoi(c[1]) < 7) {
                     sortColumn = std::stoi(c[1]);
                 } else {
                     std::cout << "Invalid column, please select a number between 0 and 6.\n";
                 }
             } else {
                 runCommand(c);
             }
         }
     }
size()
ss<< R"_(], "tuples": [)_"; firstCol = true; for (auto& i : iter) { comma(firstCol); ss << i-> souffle::profile::Tui::size ()
Referenced by souffle::MainConfig::processArgs().
Field Documentation
alive
bool souffle::profile::Tui::alive = false private
Definition at line 44 of file Tui.h.
f_name
std::string souffle::profile::Tui::f_name private
Definition at line 43 of file Tui.h.
iter
ss<< "], "; std::vector<std::shared_ptr<Iteration> > souffle::profile::Tui::iter
Initial value:
=
                    run->getRelation(row[5]->toString(0))->getIterations()
Definition at line 295 of file Tui.h.
Referenced by genJsonAtoms().
linereader
InputReader souffle::profile::Tui::linereader private
Definition at line 51 of file Tui.h.
loaded
bool souffle::profile::Tui::loaded private
Definition at line 42 of file Tui.h.
out
OutputProcessor souffle::profile::Tui::out private
Definition at line 41 of file Tui.h.
precision
int souffle::profile::Tui::precision = 3 private
Definition at line 47 of file Tui.h.
reader
std::shared_ptr<Reader> souffle::profile::Tui::reader private
Definition at line 50 of file Tui.h.
relationTable
Table souffle::profile::Tui::relationTable private
Definition at line 48 of file Tui.h.
resultLimit
size_t souffle::profile::Tui::resultLimit = 20000 private
Limit results shown. Default value chosen to approximate unlimited.
Definition at line 53 of file Tui.h.
Referenced by genJsonAtoms().
ruleTable
Table souffle::profile::Tui::ruleTable private
Definition at line 49 of file Tui.h.
sortColumn
int souffle::profile::Tui::sortColumn = 0 private
Definition at line 46 of file Tui.h.
updater
std::thread souffle::profile::Tui::updater private
Definition at line 45 of file Tui.h.
The documentation for this class was generated from the following file:
profile/Tui.h