souffle: souffle::RamSequence Class Reference
souffle::RamSequence Class Reference
Sequence of RAM statements.
#include <Statement.h>
Public Member Functions
RamSequence * clone () const override
Create a clone (i.e.
RamSequence (std::vector< std::unique_ptr< RamStatement >> statements)
RamSequence ()
template<typename... Stmts>
RamSequence (std::unique_ptr< RamStatement > first, std::unique_ptr< Stmts >... rest)
Public Member Functions inherited from souffle::RamListStatement
void apply (const RamNodeMapper &map) override
Apply the mapper to all child nodes.
std::vector< const RamNode * > getChildNodes () const override
Obtain list of all embedded child nodes.
std::vector< RamStatement * > getStatements () const
Get statements.
RamListStatement ()=default
RamListStatement (std::vector< std::unique_ptr< RamStatement >> statements)
template<typename... Stmts>
RamListStatement (std::unique_ptr< Stmts > &&... stmts)
Public Member Functions inherited from souffle::RamNode
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
virtual void rewrite (const RamNode *oldNode, std::unique_ptr< RamNode > newNode)
Rewrite a child node.
virtual ~RamNode ()=default
Protected Member Functions
void print (std::ostream &os, int tabpos) const override
Pretty print with indentation.
Protected Member Functions inherited from souffle::RamListStatement
bool equal (const RamNode &node) const override
Equality check for two RAM nodes.
Protected Member Functions inherited from souffle::RamStatement
void print (std::ostream &os) const override
Print RAM node.
Additional Inherited Members
Static Protected Member Functions inherited from souffle::RamStatement
static void print (const RamStatement *statement, std::ostream &os, int tabpos)
Pretty print jump-bed.
Protected Attributes inherited from souffle::RamListStatement
std::vector< std::unique_ptr< RamStatement > > statements
ordered list of RAM statements
Detailed Description
Sequence of RAM statements.
Execute statement one by one from an ordered list of statements.
Definition at line 397 of file Statement.h.
Constructor & Destructor Documentation
RamSequence() [1/3]
souffle::RamSequence::RamSequence (std::vector< std::unique_ptr< RamStatement >> statements) inline
Definition at line 399 of file Statement.h.
             : RamListStatement(std::move(statements)) {}
RamSequence() [2/3]
souffle::RamSequence::RamSequence () inline
Definition at line 401 of file Statement.h.
 : RamListStatement() {}
RamSequence() [3/3]
template<typename... Stmts> souffle::RamSequence::RamSequence (std::unique_ptr< RamStatement > first, std::unique_ptr< Stmts >... rest) inline
Definition at line 403 of file Statement.h.
             : RamListStatement(std::move(first), std::move(rest)...) {}
Member Function Documentation
clone()
RamSequence* souffle::RamSequence::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::RamStatement.
Definition at line 406 of file Statement.h.
References souffle::clone().
Referenced by souffle::test::TEST().
{
         auto* res = new RamSequence();
         for (auto& cur : statements) {
             res->statements.push_back(souffle::clone(cur));
         }
         return res;
     }
print()
void souffle::RamSequence::print (std::ostream & os, int tabpos) const inline override protected virtual
Pretty print with indentation.
Implements souffle::RamStatement.
Definition at line 415 of file Statement.h.
References souffle::RamStatement::print().
{
         for (const auto& stmt : statements) {
             RamStatement::print(stmt.get(), os, tabpos);
         }
     }
The documentation for this class was generated from the following file:
ram/Statement.h