souffle: souffle::RamStatement Class Reference
souffle::RamStatement Class Reference abstract
Abstract class for RAM statements.
#include <Statement.h>
Public Member Functions
RamStatement * clone () const override=0
Create a clone (i.e.
Public Member Functions inherited from souffle::RamNode
virtual void apply (const RamNodeMapper &)
Apply the mapper to all child nodes.
virtual std::vector< const RamNode * > getChildNodes () const
Obtain list of all embedded child nodes.
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
virtual void rewrite (const RamNode *oldNode, std::unique_ptr< RamNode > newNode)
Rewrite a child node.
virtual ~RamNode ()=default
Protected Member Functions
void print (std::ostream &os) const override
Print RAM node.
virtual void print (std::ostream &os, int tabpos) const =0
Pretty print with indentation.
Protected Member Functions inherited from souffle::RamNode
virtual bool equal (const RamNode &) const
Equality check for two RAM nodes.
Static Protected Member Functions
static void print (const RamStatement *statement, std::ostream &os, int tabpos)
Pretty print jump-bed.
Friends
class RamProgram
Detailed Description
Abstract class for RAM statements.
Definition at line 43 of file Statement.h.
Member Function Documentation
clone()
RamStatement* souffle::RamStatement::clone () const override pure virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::RamNode.
Implemented in souffle::RamCall, souffle::RamLogSize, souffle::RamDebugInfo, souffle::RamLogTimer, souffle::RamLogRelationTimer, souffle::RamExit, souffle::RamLoop, souffle::RamParallel, souffle::RamSequence, souffle::RamQuery, souffle::RamSwap, souffle::RamExtend, souffle::RamClear, and souffle::RamIO.
print() [1/3]
void souffle::RamStatement::print (std::ostream & out) const inline override protected virtual
Print RAM node.
Implements souffle::RamNode.
Definition at line 48 of file Statement.h.
Referenced by print(), souffle::RamSequence::print(), souffle::RamParallel::print(), souffle::RamLoop::print(), souffle::RamLogRelationTimer::print(), souffle::RamLogTimer::print(), and souffle::RamDebugInfo::print().
{
         print(os, 0);
     }
print() [2/3]
virtual void souffle::RamStatement::print (std::ostream & os, int tabpos) const protected pure virtual
Pretty print with indentation.
Implemented in souffle::RamCall, souffle::RamLogSize, souffle::RamDebugInfo, souffle::RamLogTimer, souffle::RamLogRelationTimer, souffle::RamExit, souffle::RamLoop, souffle::RamParallel, souffle::RamSequence, souffle::RamQuery, souffle::RamSwap, souffle::RamExtend, souffle::RamClear, and souffle::RamIO.
print() [3/3]
static void souffle::RamStatement::print (const RamStatement * statement, std::ostream & os, int tabpos) inline static protected
Pretty print jump-bed.
Definition at line 55 of file Statement.h.
References print().
{
         assert(statement != nullptr && "statement is a null-pointer");
         statement->print(os, tabpos);
     }
Friends And Related Function Documentation
RamProgram
friend class RamProgram friend
Definition at line 60 of file Statement.h.
The documentation for this class was generated from the following file:
ram/Statement.h