souffle: souffle::ConditionalTransformer Class Reference
souffle::ConditionalTransformer Class Reference
Transformer that executes a sub-transformer iff a condition holds.
#include <Conditional.h>
Public Member Functions
ConditionalTransformer * clone () const override
ConditionalTransformer (std::function< bool()> cond, std::unique_ptr< AstTransformer > transformer)
ConditionalTransformer (bool cond, std::unique_ptr< AstTransformer > transformer)
void disableTransformers (const std::set< std::string > &transforms) override
std::string getName () const override
std::vector< AstTransformer * > getSubtransformers () const override
void setDebugReport () override
void setVerbosity (bool verbose) override
Public Member Functions inherited from souffle::MetaTransformer
bool applySubtransformer (AstTranslationUnit &translationUnit, AstTransformer *transformer)
Public Member Functions inherited from souffle::AstTransformer
bool apply (AstTranslationUnit &translationUnit)
virtual ~AstTransformer ()=default
Private Member Functions
bool transform (AstTranslationUnit &translationUnit) override
Private Attributes
std::function< bool()> condition
std::unique_ptr< AstTransformer > transformer
Additional Inherited Members
Protected Attributes inherited from souffle::MetaTransformer
bool verbose = false
Detailed Description
Transformer that executes a sub-transformer iff a condition holds.
Definition at line 38 of file Conditional.h.
Constructor & Destructor Documentation
ConditionalTransformer() [1/2]
souffle::ConditionalTransformer::ConditionalTransformer (std::function< bool()> cond, std::unique_ptr< AstTransformer > transformer) inline
Definition at line 40 of file Conditional.h.
Referenced by clone().
             : condition(std::move(cond)), transformer(std::move(transformer)) {}
ConditionalTransformer() [2/2]
souffle::ConditionalTransformer::ConditionalTransformer (bool cond, std::unique_ptr< AstTransformer > transformer) inline
Definition at line 43 of file Conditional.h.
References transformer.
             : condition([=]() { return cond; }), transformer(std::move(transformer)) {}
Member Function Documentation
clone()
ConditionalTransformer* souffle::ConditionalTransformer::clone () const inline override virtual
Implements souffle::MetaTransformer.
Definition at line 77 of file Conditional.h.
References souffle::clone(), condition, ConditionalTransformer(), and transformer.
{
         return new ConditionalTransformer(condition, souffle::clone(transformer));
     }
disableTransformers()
void souffle::ConditionalTransformer::disableTransformers (const std::set< std::string > & transforms) inline override virtual
Implements souffle::MetaTransformer.
Definition at line 65 of file Conditional.h.
References transformer.
{
         if (auto* mt = dynamic_cast<MetaTransformer*>(transformer.get())) {
             mt->disableTransformers(transforms);
         } else if (transforms.find(transformer->getName()) != transforms.end()) {
             transformer = std::make_unique<NullTransformer>();
         }
     }
getName()
std::string souffle::ConditionalTransformer::getName () const inline override virtual
Implements souffle::AstTransformer.
Definition at line 73 of file Conditional.h.
{
         return "ConditionalTransformer";
     }
getSubtransformers()
std::vector<AstTransformer*> souffle::ConditionalTransformer::getSubtransformers () const inline override virtual
Implements souffle::MetaTransformer.
Definition at line 46 of file Conditional.h.
References transformer.
{
         return {transformer.get()};
     }
setDebugReport()
void souffle::ConditionalTransformer::setDebugReport () inline override virtual
Implements souffle::MetaTransformer.
Definition at line 50 of file Conditional.h.
References transformer.
{
         if (auto* mt = dynamic_cast<MetaTransformer*>(transformer.get())) {
             mt->setDebugReport();
         } else {
             transformer = std::make_unique<DebugReporter>(std::move(transformer));
         }
     }
setVerbosity()
void souffle::ConditionalTransformer::setVerbosity (bool verbose) inline override virtual
Implements souffle::MetaTransformer.
Definition at line 58 of file Conditional.h.
References transformer, and souffle::MetaTransformer::verbose.
{
         this->verbose = verbose;
         if (auto* mt = dynamic_cast<MetaTransformer*>(transformer.get())) {
             mt->setVerbosity(verbose);
         }
     }
transform()
bool souffle::ConditionalTransformer::transform (AstTranslationUnit & translationUnit) inline override private virtual
Implements souffle::AstTransformer.
Definition at line 85 of file Conditional.h.
References souffle::MetaTransformer::applySubtransformer(), and condition.
{
         return condition() ? applySubtransformer(translationUnit, transformer.get()) : false;
     }
Field Documentation
condition
std::function<bool()> souffle::ConditionalTransformer::condition private
Definition at line 82 of file Conditional.h.
Referenced by clone(), and transform().
transformer
std::unique_ptr<AstTransformer> souffle::ConditionalTransformer::transformer private
Definition at line 83 of file Conditional.h.
Referenced by clone(), ConditionalTransformer(), disableTransformers(), getSubtransformers(), setDebugReport(), and setVerbosity().
The documentation for this class was generated from the following file:
ast/transform/Conditional.h