souffle: souffle::ReadWriteLock Class Reference
souffle::ReadWriteLock Class Reference
#include <ParallelUtil.h>
Public Member Functions
void downgrade_to_read ()
void end_read ()
void end_write ()
ReadWriteLock ()=default
void start_read ()
void start_write ()
bool try_upgrade_to_write ()
bool try_write ()
Detailed Description
Definition at line 500 of file ParallelUtil.h.
Constructor & Destructor Documentation
ReadWriteLock()
souffle::ReadWriteLock::ReadWriteLock () default
Member Function Documentation
downgrade_to_read()
void souffle::ReadWriteLock::downgrade_to_read () inline
Definition at line 520 of file ParallelUtil.h.
 {}
end_read()
void souffle::ReadWriteLock::end_read () inline
Definition at line 506 of file ParallelUtil.h.
Referenced by souffle::test::TEST().
 {}
end_write()
void souffle::ReadWriteLock::end_write () inline
Definition at line 514 of file ParallelUtil.h.
Referenced by souffle::test::TEST().
 {}
start_read()
void souffle::ReadWriteLock::start_read () inline
Definition at line 504 of file ParallelUtil.h.
Referenced by souffle::test::TEST().
 {}
start_write()
void souffle::ReadWriteLock::start_write () inline
Definition at line 508 of file ParallelUtil.h.
Referenced by souffle::test::TEST().
 {}
try_upgrade_to_write()
bool souffle::ReadWriteLock::try_upgrade_to_write () inline
Definition at line 516 of file ParallelUtil.h.
{
         return true;
     }
try_write()
bool souffle::ReadWriteLock::try_write () inline
Definition at line 510 of file ParallelUtil.h.
                      {
         return true;
     }
The documentation for this class was generated from the following file:
utility/ParallelUtil.h