souffle: souffle::AstComponentType Class Reference
souffle::AstComponentType Class Reference
A component type is.
#include <ComponentType.h>
Public Member Functions
AstComponentType (std::string name="", std::vector< AstQualifiedName > params={}, SrcLocation loc={})
AstComponentType * clone () const override
Create a clone (i.e.
const std::string & getName () const
get component name
const std::vector< AstQualifiedName > & getTypeParameters () const
get component type parameters
void setName (std::string n)
set component name
void setTypeParameters (const std::vector< AstQualifiedName > &params)
set component type parameters
Public Member Functions inherited from souffle::AstNode
virtual void apply (const AstNodeMapper &)
Apply the mapper to all child nodes.
AstNode (SrcLocation loc={})
std::string extloc () const
Return source location of the syntactic element.
virtual std::vector< const AstNode * > getChildNodes () const
Obtain a list of all embedded AST child nodes.
const SrcLocation & getSrcLoc () const
Return source location of the AstNode.
bool operator!= (const AstNode &other) const
Inequality check for two AST nodes.
bool operator== (const AstNode &other) const
Equivalence check for two AST nodes.
void setSrcLoc (SrcLocation l)
Set source location for the AstNode.
virtual ~AstNode ()=default
Protected Member Functions
bool equal (const AstNode &node) const override
Abstract equality check for two AST nodes.
void print (std::ostream &os) const override
Output to a given output stream.
Private Attributes
std::string name
component name
std::vector< AstQualifiedName > typeParams
component type parameters
Detailed Description
A component type is.
name < Type1, Type2, ... >
where name is the component name and < Type, Type, ... > is a list of component type parameters (either actual or formal).
Definition at line 38 of file ComponentType.h.
Constructor & Destructor Documentation
AstComponentType()
souffle::AstComponentType::AstComponentType (std::string name = "", std::vector< AstQualifiedName > params = {}, SrcLocation loc = {}) inline
Definition at line 40 of file ComponentType.h.
References souffle::AstNode::AstNode(), name, and typeParams.
Referenced by clone().
                                                                                {}, SrcLocation loc = {})
             : AstNode(std::move(loc)), name(std::move(name)), typeParams(std::move(params)) {}
Member Function Documentation
clone()
AstComponentType* souffle::AstComponentType::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::AstNode.
Definition at line 63 of file ComponentType.h.
References AstComponentType(), souffle::AstNode::getSrcLoc(), name, and typeParams.
{
         return new AstComponentType(name, typeParams, getSrcLoc());
     }
equal()
bool souffle::AstComponentType::equal (const AstNode &) const inline override protected virtual
Abstract equality check for two AST nodes.
Reimplemented from souffle::AstNode.
Definition at line 75 of file ComponentType.h.
References name, and typeParams.
{
         const auto& other = static_cast<const AstComponentType&>(node);
         return name == other.name && typeParams == other.typeParams;
     }
getName()
const std::string& souffle::AstComponentType::getName () const inline
get component name
Definition at line 44 of file ComponentType.h.
References name.
Referenced by souffle::AstComponentChecker::checkComponent(), and souffle::AstComponentChecker::checkComponentReference().
{
         return name;
     }
getTypeParameters()
const std::vector<AstQualifiedName>& souffle::AstComponentType::getTypeParameters () const inline
get component type parameters
Definition at line 54 of file ComponentType.h.
References typeParams.
Referenced by souffle::AstComponentChecker::checkComponent(), and souffle::AstComponentChecker::checkComponentReference().
{
         return typeParams;
     }
print()
void souffle::AstComponentType::print (std::ostream & os) const inline override protected virtual
Output to a given output stream.
Implements souffle::AstNode.
Definition at line 68 of file ComponentType.h.
References souffle::join(), name, and typeParams.
{
         os << name;
         if (!typeParams.empty()) {
             os << "<" << join(typeParams) << ">";
         }
     }
setName()
void souffle::AstComponentType::setName (std::string n) inline
set component name
Definition at line 49 of file ComponentType.h.
References name.
{
         name = std::move(n);
     }
setTypeParameters()
void souffle::AstComponentType::setTypeParameters (const std::vector< AstQualifiedName > & params) inline
set component type parameters
Definition at line 59 of file ComponentType.h.
References typeParams.
{
         typeParams = params;
     }
Field Documentation
name
std::string souffle::AstComponentType::name private
component name
Definition at line 82 of file ComponentType.h.
Referenced by AstComponentType(), clone(), equal(), getName(), print(), and setName().
typeParams
std::vector<AstQualifiedName> souffle::AstComponentType::typeParams private
component type parameters
Definition at line 85 of file ComponentType.h.
Referenced by AstComponentType(), clone(), equal(), getTypeParameters(), print(), and setTypeParameters().
The documentation for this class was generated from the following file:
ast/ComponentType.h