souffle: souffle::AstType Class Reference
souffle::AstType Class Reference abstract
#include <Type.h>
Public Member Functions
AstType (AstQualifiedName name={}, SrcLocation loc={})
AstType * clone () const override=0
Create a clone (i.e.
const AstQualifiedName & getQualifiedName () const
get type name
void setQualifiedName (AstQualifiedName name)
set type name
Public Member Functions inherited from souffle::AstNode
virtual void apply (const AstNodeMapper &)
Apply the mapper to all child nodes.
AstNode (SrcLocation loc={})
std::string extloc () const
Return source location of the syntactic element.
virtual std::vector< const AstNode * > getChildNodes () const
Obtain a list of all embedded AST child nodes.
const SrcLocation & getSrcLoc () const
Return source location of the AstNode.
bool operator!= (const AstNode &other) const
Inequality check for two AST nodes.
bool operator== (const AstNode &other) const
Equivalence check for two AST nodes.
void setSrcLoc (SrcLocation l)
Set source location for the AstNode.
virtual ~AstNode ()=default
Private Attributes
AstQualifiedName name
type name
Additional Inherited Members
Protected Member Functions inherited from souffle::AstNode
virtual bool equal (const AstNode &) const
Abstract equality check for two AST nodes.
virtual void print (std::ostream &os) const =0
Output to a given output stream.
Detailed Description
Definition at line 31 of file Type.h.
Constructor & Destructor Documentation
AstType()
souffle::AstType::AstType (AstQualifiedName name = {}, SrcLocation loc = {}) inline
Definition at line 33 of file Type.h.
References souffle::AstNode::AstNode(), and name.
Referenced by souffle::AstRecordType::AstRecordType(), souffle::AstSubsetType::AstSubsetType(), and souffle::AstUnionType::AstUnionType().
                                     {}, SrcLocation loc = {})
             : AstNode(std::move(loc)), name(std::move(name)) {}
Member Function Documentation
clone()
AstType* souffle::AstType::clone () const override pure virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::AstNode.
Implemented in souffle::AstRecordType, souffle::AstUnionType, and souffle::AstSubsetType.
Referenced by setQualifiedName().
getQualifiedName()
const AstQualifiedName& souffle::AstType::getQualifiedName () const inline
get type name
Definition at line 37 of file Type.h.
References name.
Referenced by souffle::AstSemanticCheckerImpl::checkRecordType(), souffle::AstSemanticCheckerImpl::checkSubsetType(), souffle::AstSemanticCheckerImpl::checkType(), souffle::AstSemanticCheckerImpl::checkUnionType(), souffle::AstSubsetType::clone(), souffle::AstUnionType::clone(), souffle::AstRecordType::clone(), souffle::AstSubsetType::equal(), souffle::AstUnionType::equal(), souffle::AstRecordType::equal(), souffle::AstSubsetType::print(), souffle::AstUnionType::print(), and souffle::AstRecordType::print().
{
         return name;
     }
setQualifiedName()
void souffle::AstType::setQualifiedName (AstQualifiedName name) inline
set type name
Definition at line 42 of file Type.h.
References clone().
{
         this->name = std::move(name);
     }
Field Documentation
name
AstQualifiedName souffle::AstType::name private
type name
Definition at line 50 of file Type.h.
Referenced by AstType(), and getQualifiedName().
The documentation for this class was generated from the following file:
ast/Type.h