souffle: souffle::SCCGraphAnalysis Class Reference
souffle::SCCGraphAnalysis Class Reference
Analysis pass computing the strongly connected component (SCC) graph for the datalog program.
#include <SCCGraph.h>
Public Member Functions
std::set< const AstRelation * > getExternalNonOutputPredecessorRelations (const size_t scc) const
Get all external non-output predecessor relations of a given SCC.
std::set< const AstRelation * > getExternalOutputPredecessorRelations (const size_t scc) const
Get all external output predecessor relations of a given SCC.
std::set< const AstRelation * > getExternalPredecessorRelations (const size_t scc) const
Get all external predecessor relations of a given SCC.
std::set< const AstRelation * > getInternalInputRelations (const size_t scc) const
Get all internal input relations of a given SCC.
std::set< const AstRelation * > getInternalNonOutputRelationsWithExternalSuccessors (const size_t scc) const
Get all internal non-output relations of a given SCC with external successors.
std::set< const AstRelation * > getInternalOutputRelations (const size_t scc) const
Get all internal output relations of a given SCC.
const std::set< const AstRelation * > & getInternalRelations (const size_t scc) const
Get all internal relations of a given SCC.
std::set< const AstRelation * > getInternalRelationsWithExternalSuccessors (const size_t scc) const
Get all internal relations of a given SCC with external successors.
size_t getNumberOfSCCs () const
Get the number of SCCs in the graph.
const std::set< size_t > & getPredecessorSCCs (const size_t scc) const
Get all predecessor SCCs of a given SCC.
std::set< size_t > getPredecessorSCCs (const AstRelation *relation) const
Get all SCCs containing a predecessor of a given relation.
size_t getSCC (const AstRelation *rel) const
Get the SCC of the given relation.
const std::set< size_t > & getSuccessorSCCs (const size_t scc) const
Get all successor SCCs of a given SCC.
std::set< size_t > getSuccessorSCCs (const AstRelation *relation) const
Get all SCCs containing a successor of a given relation.
bool isRecursive (const size_t scc) const
Return if the given SCC is recursive.
void print (std::ostream &os) const override
Print the SCC graph.
void run (const AstTranslationUnit &translationUnit) override
run analysis for a Ast translation unit
SCCGraphAnalysis ()
Public Member Functions inherited from souffle::AstAnalysis
AstAnalysis (std::string identifier)
virtual const std::string & getName () const
get name of the analysis
virtual ~AstAnalysis ()=default
Static Public Attributes
static constexpr const char * name = "scc-graph"
Private Member Functions
void scR (const AstRelation *relation, std::map< const AstRelation *, size_t > &preOrder, size_t &counter, std::stack< const AstRelation *> &S, std::stack< const AstRelation *> &P, size_t &numSCCs)
Recursive scR method for computing SCC.
Private Attributes
IOType * ioType = nullptr
PrecedenceGraphAnalysis * precedenceGraph = nullptr
std::vector< std::set< size_t > > predecessors
Predecessor set for the SCC graph.
std::map< const AstRelation *, size_t > relationToScc
Map from node number to SCC number.
std::vector< std::set< const AstRelation * > > sccToRelation
Relations contained in a SCC.
std::vector< std::set< size_t > > successors
Adjacency lists for the SCC graph.
Additional Inherited Members
Protected Attributes inherited from souffle::AstAnalysis
const std::string identifier
Detailed Description
Analysis pass computing the strongly connected component (SCC) graph for the datalog program.
Definition at line 41 of file SCCGraph.h.
Constructor & Destructor Documentation
SCCGraphAnalysis()
souffle::SCCGraphAnalysis::SCCGraphAnalysis () inline
Definition at line 45 of file SCCGraph.h.
References run().
 : AstAnalysis(name) {}
Member Function Documentation
getExternalNonOutputPredecessorRelations()
std::set<const AstRelation*> souffle::SCCGraphAnalysis::getExternalNonOutputPredecessorRelations (const size_t scc) const inline
Get all external non-output predecessor relations of a given SCC.
Definition at line 114 of file SCCGraph.h.
References getInternalRelations(), souffle::PrecedenceGraphAnalysis::graph(), ioType, souffle::IOType::isOutput(), precedenceGraph, relation, and relationToScc.
{
         std::set<const AstRelation*> externNonOutPreds;
         for (const auto& relation : getInternalRelations(scc)) {
             for (const auto& predecessor : precedenceGraph->graph().predecessors(relation)) {
                 if (relationToScc.at(predecessor) != scc && !ioType->isOutput(predecessor)) {
                     externNonOutPreds.insert(predecessor);
                 }
             }
         }
         return externNonOutPreds;
     }
getExternalOutputPredecessorRelations()
std::set<const AstRelation*> souffle::SCCGraphAnalysis::getExternalOutputPredecessorRelations (const size_t scc) const inline
Get all external output predecessor relations of a given SCC.
Definition at line 101 of file SCCGraph.h.
References getInternalRelations(), souffle::PrecedenceGraphAnalysis::graph(), ioType, souffle::IOType::isOutput(), precedenceGraph, relation, and relationToScc.
{
         std::set<const AstRelation*> externOutPreds;
         for (const auto& relation : getInternalRelations(scc)) {
             for (const auto& predecessor : precedenceGraph->graph().predecessors(relation)) {
                 if (relationToScc.at(predecessor) != scc && ioType->isOutput(predecessor)) {
                     externOutPreds.insert(predecessor);
                 }
             }
         }
         return externOutPreds;
     }
getExternalPredecessorRelations()
std::set<const AstRelation*> souffle::SCCGraphAnalysis::getExternalPredecessorRelations (const size_t scc) const inline
Get all external predecessor relations of a given SCC.
Definition at line 127 of file SCCGraph.h.
References getInternalRelations(), souffle::PrecedenceGraphAnalysis::graph(), precedenceGraph, relation, and relationToScc.
{
         std::set<const AstRelation*> externPreds;
         for (const auto& relation : getInternalRelations(scc)) {
             for (const auto& predecessor : precedenceGraph->graph().predecessors(relation)) {
                 if (relationToScc.at(predecessor) != scc) {
                     externPreds.insert(predecessor);
                 }
             }
         }
         return externPreds;
     }
getInternalInputRelations()
std::set<const AstRelation*> souffle::SCCGraphAnalysis::getInternalInputRelations (const size_t scc) const inline
Get all internal input relations of a given SCC.
Definition at line 181 of file SCCGraph.h.
References getInternalRelations(), ioType, souffle::IOType::isInput(), and relation.
{
         std::set<const AstRelation*> internIns;
         for (const auto& relation : getInternalRelations(scc)) {
             if (ioType->isInput(relation)) {
                 internIns.insert(relation);
             }
         }
         return internIns;
     }
getInternalNonOutputRelationsWithExternalSuccessors()
std::set<const AstRelation*> souffle::SCCGraphAnalysis::getInternalNonOutputRelationsWithExternalSuccessors (const size_t scc) const inline
Get all internal non-output relations of a given SCC with external successors.
Definition at line 165 of file SCCGraph.h.
References getInternalRelations(), souffle::PrecedenceGraphAnalysis::graph(), ioType, souffle::IOType::isOutput(), precedenceGraph, relation, and relationToScc.
{
         std::set<const AstRelation*> internNonOutsWithExternSuccs;
         for (const auto& relation : getInternalRelations(scc)) {
             if (!ioType->isOutput(relation)) {
                 for (const auto& successor : precedenceGraph->graph().successors(relation)) {
                     if (relationToScc.at(successor) != scc) {
                         internNonOutsWithExternSuccs.insert(relation);
                         break;
                     }
                 }
             }
         }
         return internNonOutsWithExternSuccs;
     }
getInternalOutputRelations()
std::set<const AstRelation*> souffle::SCCGraphAnalysis::getInternalOutputRelations (const size_t scc) const inline
Get all internal output relations of a given SCC.
Definition at line 140 of file SCCGraph.h.
References getInternalRelations(), ioType, souffle::IOType::isOutput(), and relation.
{
         std::set<const AstRelation*> internOuts;
         for (const auto& relation : getInternalRelations(scc)) {
             if (ioType->isOutput(relation)) {
                 internOuts.insert(relation);
             }
         }
         return internOuts;
     }
getInternalRelations()
const std::set<const AstRelation*>& souffle::SCCGraphAnalysis::getInternalRelations (const size_t scc) const inline
Get all internal relations of a given SCC.
Definition at line 96 of file SCCGraph.h.
References sccToRelation.
Referenced by souffle::AstSemanticCheckerImpl::AstSemanticCheckerImpl(), getExternalNonOutputPredecessorRelations(), getExternalOutputPredecessorRelations(), getExternalPredecessorRelations(), getInternalInputRelations(), getInternalNonOutputRelationsWithExternalSuccessors(), getInternalOutputRelations(), getInternalRelationsWithExternalSuccessors(), souffle::TopologicallySortedSCCGraphAnalysis::print(), and print().
{
         return sccToRelation.at(scc);
     }
getInternalRelationsWithExternalSuccessors()
std::set<const AstRelation*> souffle::SCCGraphAnalysis::getInternalRelationsWithExternalSuccessors (const size_t scc) const inline
Get all internal relations of a given SCC with external successors.
Definition at line 151 of file SCCGraph.h.
References getInternalRelations(), souffle::PrecedenceGraphAnalysis::graph(), precedenceGraph, relation, and relationToScc.
{
         std::set<const AstRelation*> internsWithExternSuccs;
         for (const auto& relation : getInternalRelations(scc)) {
             for (const auto& successor : precedenceGraph->graph().successors(relation)) {
                 if (relationToScc.at(successor) != scc) {
                     internsWithExternSuccs.insert(relation);
                     break;
                 }
             }
         }
         return internsWithExternSuccs;
     }
getNumberOfSCCs()
size_t souffle::SCCGraphAnalysis::getNumberOfSCCs () const inline
Get the number of SCCs in the graph.
Definition at line 50 of file SCCGraph.h.
References sccToRelation.
Referenced by print(), and souffle::TopologicallySortedSCCGraphAnalysis::run().
{
         return sccToRelation.size();
     }
getPredecessorSCCs() [1/2]
const std::set<size_t>& souffle::SCCGraphAnalysis::getPredecessorSCCs (const size_t scc) const inline
Get all predecessor SCCs of a given SCC.
Definition at line 65 of file SCCGraph.h.
References predecessors.
Referenced by souffle::TopologicallySortedSCCGraphAnalysis::computeTopologicalOrdering(), souffle::TopologicallySortedSCCGraphAnalysis::print(), souffle::TopologicallySortedSCCGraphAnalysis::run(), and souffle::TopologicallySortedSCCGraphAnalysis::topologicalOrderingCost().
{
         return predecessors.at(scc);
     }
getPredecessorSCCs() [2/2]
std::set<size_t> souffle::SCCGraphAnalysis::getPredecessorSCCs (const AstRelation * relation) const inline
Get all SCCs containing a predecessor of a given relation.
Definition at line 83 of file SCCGraph.h.
References souffle::PrecedenceGraphAnalysis::graph(), precedenceGraph, and relationToScc.
{
         std::set<size_t> predecessorSccs;
         const auto scc = relationToScc.at(relation);
         for (const auto& predecessor : precedenceGraph->graph().predecessors(relation)) {
             const auto predecessorScc = relationToScc.at(predecessor);
             if (predecessorScc != scc) {
                 predecessorSccs.insert(predecessorScc);
             }
         }
         return predecessorSccs;
     }
getSCC()
size_t souffle::SCCGraphAnalysis::getSCC (const AstRelation * rel) const inline
Get the SCC of the given relation.
Definition at line 55 of file SCCGraph.h.
References relationToScc.
Referenced by souffle::AstSemanticCheckerImpl::AstSemanticCheckerImpl().
{
         return relationToScc.at(rel);
     }
getSuccessorSCCs() [1/2]
const std::set<size_t>& souffle::SCCGraphAnalysis::getSuccessorSCCs (const size_t scc) const inline
Get all successor SCCs of a given SCC.
Definition at line 60 of file SCCGraph.h.
References successors.
Referenced by souffle::TopologicallySortedSCCGraphAnalysis::computeTopologicalOrdering(), souffle::TopologicallySortedSCCGraphAnalysis::print(), print(), souffle::TopologicallySortedSCCGraphAnalysis::run(), and souffle::TopologicallySortedSCCGraphAnalysis::topologicalOrderingCost().
{
         return successors.at(scc);
     }
getSuccessorSCCs() [2/2]
std::set<size_t> souffle::SCCGraphAnalysis::getSuccessorSCCs (const AstRelation * relation) const inline
Get all SCCs containing a successor of a given relation.
Definition at line 70 of file SCCGraph.h.
References souffle::PrecedenceGraphAnalysis::graph(), precedenceGraph, and relationToScc.
{
         std::set<size_t> successorSccs;
         const auto scc = relationToScc.at(relation);
         for (const auto& successor : precedenceGraph->graph().successors(relation)) {
             const auto successorScc = relationToScc.at(successor);
             if (successorScc != scc) {
                 successorSccs.insert(successorScc);
             }
         }
         return successorSccs;
     }
isRecursive()
bool souffle::SCCGraphAnalysis::isRecursive (const size_t scc) const inline
Return if the given SCC is recursive.
Definition at line 192 of file SCCGraph.h.
References souffle::PrecedenceGraphAnalysis::graph(), precedenceGraph, print(), and sccToRelation.
Referenced by souffle::AstSemanticCheckerImpl::AstSemanticCheckerImpl(), and souffle::RelationScheduleAnalysis::run().
{
         const std::set<const AstRelation*>& sccRelations = sccToRelation.at(scc);
         if (sccRelations.size() == 1) {
             const AstRelation* singleRelation = *sccRelations.begin();
             if (precedenceGraph->graph().predecessors(singleRelation).count(singleRelation) == 0u) {
                 return false;
             }
         }
         return true;
     }
print()
void souffle::SCCGraphAnalysis::print (std::ostream & os) const override virtual
Print the SCC graph.
Reimplemented from souffle::AstAnalysis.
Definition at line 116 of file SCCGraph.cpp.
References souffle::Global::config(), getInternalRelations(), souffle::AstAnalysis::getName(), getNumberOfSCCs(), souffle::AstRelation::getQualifiedName(), getSuccessorSCCs(), souffle::join(), name, souffle::printHTMLGraph(), and souffle::profile::ss.
Referenced by isRecursive().
{
     const std::string& name = Global::config().get("name");
     std::stringstream ss;
     /* Print SCC graph */
     ss << "digraph {" << std::endl;
     /* Print nodes of SCC graph */
     for (size_t scc = 0; scc < getNumberOfSCCs(); scc++) {
         ss << "\t" << name << "_" << scc << "[label = \"";
         ss << join(getInternalRelations(scc), ",\\n",
                 [](std::ostream& out, const AstRelation* rel) { out << rel->getQualifiedName(); });
         ss << "\" ];" << std::endl;
     }
     for (size_t scc = 0; scc < getNumberOfSCCs(); scc++) {
         for (auto succ : getSuccessorSCCs(scc)) {
             ss << "\t" << name << "_" << scc << " -> " << name << "_" << succ << ";" << std::endl;
         }
     }
     ss << "}";
     printHTMLGraph(os, ss.str(), getName());
 }
run()
void souffle::SCCGraphAnalysis::run (const AstTranslationUnit &) override virtual
run analysis for a Ast translation unit
Implements souffle::AstAnalysis.
Definition at line 36 of file SCCGraph.cpp.
References souffle::AstTranslationUnit::getAnalysis(), souffle::AstTranslationUnit::getProgram(), souffle::AstProgram::getRelations(), souffle::PrecedenceGraphAnalysis::graph(), ioType, precedenceGraph, predecessors, relation, relations, relationToScc, S, sccToRelation, scR(), and successors.
Referenced by SCCGraphAnalysis().
{
     precedenceGraph = translationUnit.getAnalysis<PrecedenceGraphAnalysis>();
     ioType = translationUnit.getAnalysis<IOType>();
     sccToRelation.clear();
     relationToScc.clear();
     predecessors.clear();
     successors.clear();
     /* Compute SCC */
     std::vector<AstRelation*> relations = translationUnit.getProgram()->getRelations();
     size_t counter = 0;
     size_t numSCCs = 0;
     std::stack<const AstRelation*> S;
     std::stack<const AstRelation*> P;
     std::map<const AstRelation*, size_t> preOrder;  // Pre-order number of a node (for Gabow's Algo)
     for (const AstRelation* relation : relations) {
         relationToScc[relation] = preOrder[relation] = (size_t)-1;
     }
     for (const AstRelation* relation : relations) {
         if (preOrder[relation] == (size_t)-1) {
             scR(relation, preOrder, counter, S, P, numSCCs);
         }
     }
     /* Build SCC graph */
     successors.resize(numSCCs);
     predecessors.resize(numSCCs);
     for (const AstRelation* u : relations) {
         for (const AstRelation* v : precedenceGraph->graph().predecessors(u)) {
             auto scc_u = relationToScc[u];
             auto scc_v = relationToScc[v];
             assert(scc_u < numSCCs && "Wrong range");
             assert(scc_v < numSCCs && "Wrong range");
             if (scc_u != scc_v) {
                 predecessors[scc_u].insert(scc_v);
                 successors[scc_v].insert(scc_u);
             }
         }
     }
     /* Store the relations for each SCC */
     sccToRelation.resize(numSCCs);
     for (const AstRelation* relation : relations) {
         sccToRelation[relationToScc[relation]].insert(relation);
     }
 }
scR()
void souffle::SCCGraphAnalysis::scR (const AstRelation * relation, std::map< const AstRelation *, size_t > & preOrder, size_t & counter, std::stack< const AstRelation *> & S, std::stack< const AstRelation *> & P, size_t & numSCCs) private
Recursive scR method for computing SCC.
Definition at line 86 of file SCCGraph.cpp.
References souffle::PrecedenceGraphAnalysis::graph(), precedenceGraph, and relationToScc.
Referenced by run().
{
     preOrder[w] = counter++;
     S.push(w);
     P.push(w);
     for (const AstRelation* t : precedenceGraph->graph().predecessors(w)) {
         if (preOrder[t] == (size_t)-1) {
             scR(t, preOrder, counter, S, P, numSCCs);
         } else if (relationToScc[t] == (size_t)-1) {
             while (preOrder[P.top()] > preOrder[t]) {
                 P.pop();
             }
         }
     }
     if (P.top() == w) {
         P.pop();
     } else {
         return;
     }
     const AstRelation* v;
     do {
         v = S.top();
         S.pop();
         relationToScc[v] = numSCCs;
     } while (v != w);
     numSCCs++;
 }
Field Documentation
ioType
IOType* souffle::SCCGraphAnalysis::ioType = nullptr private
Definition at line 225 of file SCCGraph.h.
Referenced by getExternalNonOutputPredecessorRelations(), getExternalOutputPredecessorRelations(), getInternalInputRelations(), getInternalNonOutputRelationsWithExternalSuccessors(), getInternalOutputRelations(), and run().
name
constexpr const char* souffle::SCCGraphAnalysis::name = "scc-graph" static
Definition at line 43 of file SCCGraph.h.
Referenced by print().
precedenceGraph
PrecedenceGraphAnalysis* souffle::SCCGraphAnalysis::precedenceGraph = nullptr private
Definition at line 207 of file SCCGraph.h.
Referenced by getExternalNonOutputPredecessorRelations(), getExternalOutputPredecessorRelations(), getExternalPredecessorRelations(), getInternalNonOutputRelationsWithExternalSuccessors(), getInternalRelationsWithExternalSuccessors(), getPredecessorSCCs(), getSuccessorSCCs(), isRecursive(), run(), and scR().
predecessors
std::vector<std::set<size_t> > souffle::SCCGraphAnalysis::predecessors private
Predecessor set for the SCC graph.
Definition at line 216 of file SCCGraph.h.
Referenced by getPredecessorSCCs(), and run().
relationToScc
std::map<const AstRelation*, size_t> souffle::SCCGraphAnalysis::relationToScc private
Map from node number to SCC number.
Definition at line 210 of file SCCGraph.h.
Referenced by getExternalNonOutputPredecessorRelations(), getExternalOutputPredecessorRelations(), getExternalPredecessorRelations(), getInternalNonOutputRelationsWithExternalSuccessors(), getInternalRelationsWithExternalSuccessors(), getPredecessorSCCs(), getSCC(), getSuccessorSCCs(), run(), and scR().
sccToRelation
std::vector<std::set<const AstRelation*> > souffle::SCCGraphAnalysis::sccToRelation private
Relations contained in a SCC.
Definition at line 219 of file SCCGraph.h.
Referenced by getInternalRelations(), getNumberOfSCCs(), isRecursive(), and run().
successors
std::vector<std::set<size_t> > souffle::SCCGraphAnalysis::successors private
Adjacency lists for the SCC graph.
Definition at line 213 of file SCCGraph.h.
Referenced by getSuccessorSCCs(), and run().
The documentation for this class was generated from the following files:
ast/analysis/SCCGraph.h
ast/analysis/SCCGraph.cpp