souffle: souffle::IODefaultsTransformer Class Reference
souffle::IODefaultsTransformer Class Reference
Transformation pass to set defaults for IO operations.
#include <IODefaults.h>
Public Member Functions
IODefaultsTransformer * clone () const override
std::string getName () const override
Public Member Functions inherited from souffle::AstTransformer
bool apply (AstTranslationUnit &translationUnit)
virtual ~AstTransformer ()=default
Private Member Functions
std::string getRelationName (const AstIO *node)
Get the relation name from the qualified name.
bool setDefaults (AstTranslationUnit &translationUnit)
Set IO defaults.
bool transform (AstTranslationUnit &translationUnit) override
Detailed Description
Transformation pass to set defaults for IO operations.
Definition at line 32 of file IODefaults.h.
Member Function Documentation
clone()
IODefaultsTransformer* souffle::IODefaultsTransformer::clone () const inline override virtual
Implements souffle::AstTransformer.
Definition at line 38 of file IODefaults.h.
{
         return new IODefaultsTransformer();
     }
getName()
std::string souffle::IODefaultsTransformer::getName () const inline override virtual
Implements souffle::AstTransformer.
Definition at line 34 of file IODefaults.h.
{
         return "IODefaultsTransformer";
     }
getRelationName()
std::string souffle::IODefaultsTransformer::getRelationName (const AstIO * node) inline private
Get the relation name from the qualified name.
Returns
Valid relation name from the concatenated qualified name.
Definition at line 118 of file IODefaults.h.
References souffle::AstIO::getQualifiedName(), souffle::AstQualifiedName::getQualifiers(), souffle::join(), and souffle::toString().
Referenced by setDefaults().
{
         return toString(join(node->getQualifiedName().getQualifiers(), "."));
     }
setDefaults()
bool souffle::IODefaultsTransformer::setDefaults (AstTranslationUnit & translationUnit) inline private
Set IO defaults.
If no IO type is specified, use 'file' If no name is set, use the relation name. Add the operation type to the directives list. If a global fact directory is specified, add to the directives list. If a global output directory is specified, add to the directives list. If stdout is requested at the command line ('-D-'), change all output to stdout. If a printsize operation is requested, set IO type and operation accordingly.
Parameters
translationUnit
Returns
true if any changes were made
Definition at line 65 of file IODefaults.h.
References souffle::Global::config(), souffle::AstProgram::getIOs(), souffle::AstTranslationUnit::getProgram(), getRelationName(), souffle::input, souffle::output, and souffle::printsize.
Referenced by transform().
{
         bool changed = false;
         AstProgram* program = translationUnit.getProgram();
         for (AstIO* io : program->getIOs()) {
             // Set a default IO of file
             if (!io->hasDirective("IO")) {
                 io->addDirective("IO", "file");
                 changed = true;
             }
             // Set the relation name
             if (!io->hasDirective("name")) {
                 io->addDirective("name", getRelationName(io));
                 changed = true;
             }
             // Set the operation type (input/output/printsize)
             if (!io->hasDirective("operation")) {
                 if (io->getType() == AstIoType::input) {
                     io->addDirective("operation", "input");
                     changed = true;
                     // Configure input directory
                     if (Global::config().has("fact-dir")) {
                         io->addDirective("fact-dir", Global::config().get("fact-dir"));
                     }
                 } else if (io->getType() == AstIoType::output) {
                     io->addDirective("operation", "output");
                     changed = true;
                     // Configure output directory
                     if (Global::config().has("output-dir")) {
                         if (Global::config().has("output-dir", "-")) {
                             io->addDirective("IO", "stdout");
                             io->addDirective("headers", "true");
                         } else {
                             io->addDirective("output-dir", Global::config().get("output-dir"));
                         }
                     }
                 } else if (io->getType() == AstIoType::printsize) {
                     io->addDirective("operation", "printsize");
                     io->addDirective("IO", "stdoutprintsize");
                     changed = true;
                 }
             }
         }
         return changed;
     }
transform()
bool souffle::IODefaultsTransformer::transform (AstTranslationUnit & translationUnit) inline override private virtual
Implements souffle::AstTransformer.
Definition at line 43 of file IODefaults.h.
References setDefaults().
{
         bool changed = false;
         changed |= setDefaults(translationUnit);
         return changed;
     }
The documentation for this class was generated from the following file:
ast/transform/IODefaults.h