souffle: souffle::RamParallelChoice Class Reference
souffle::RamParallelChoice Class Reference
#include <Operation.h>
Public Member Functions
RamParallelChoice * clone () const override
Create a clone (i.e.
RamParallelChoice (std::unique_ptr< RamRelationReference > rel, size_t ident, std::unique_ptr< RamCondition > cond, std::unique_ptr< RamOperation > nested, std::string profileText="")
Public Member Functions inherited from souffle::RamChoice
void apply (const RamNodeMapper &map) override
Apply the mapper to all child nodes.
std::vector< const RamNode * > getChildNodes () const override
Obtain list of all embedded child nodes.
RamChoice (std::unique_ptr< RamRelationReference > rel, size_t ident, std::unique_ptr< RamCondition > cond, std::unique_ptr< RamOperation > nested, std::string profileText="")
Public Member Functions inherited from souffle::RamRelationOperation
const RamRelation & getRelation () const
Get search relation.
RamRelationOperation (std::unique_ptr< RamRelationReference > relRef, int ident, std::unique_ptr< RamOperation > nested, std::string profileText="")
Public Member Functions inherited from souffle::RamTupleOperation
int getTupleId () const
Get identifier.
RamTupleOperation (int ident, std::unique_ptr< RamOperation > nested, std::string profileText="")
void setTupleId (int id)
Set identifier.
Public Member Functions inherited from souffle::RamNestedOperation
RamOperation & getOperation () const
Get nested operation.
const std::string & getProfileText () const
Get profile text.
RamNestedOperation (std::unique_ptr< RamOperation > nested, std::string profileText="")
Public Member Functions inherited from souffle::RamNode
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
virtual void rewrite (const RamNode *oldNode, std::unique_ptr< RamNode > newNode)
Rewrite a child node.
virtual ~RamNode ()=default
Public Member Functions inherited from souffle::RamAbstractChoice
void apply (const RamNodeMapper &map)
std::vector< const RamNode * > getChildNodes () const
const RamCondition & getCondition () const
Getter for the condition.
RamAbstractChoice (std::unique_ptr< RamCondition > cond)
Protected Member Functions
void print (std::ostream &os, int tabpos) const override
Pretty print with indentation.
Protected Member Functions inherited from souffle::RamChoice
bool equal (const RamNode &node) const override
Equality check for two RAM nodes.
Protected Member Functions inherited from souffle::RamOperation
void print (std::ostream &os) const override
Print RAM node.
Protected Member Functions inherited from souffle::RamAbstractChoice
bool equal (const RamNode &node) const
Additional Inherited Members
Static Protected Member Functions inherited from souffle::RamOperation
static void print (const RamOperation *operation, std::ostream &os, int tabpos)
Pretty print jump-bed.
Protected Attributes inherited from souffle::RamRelationOperation
std::unique_ptr< RamRelationReference > relationRef
Search relation.
Protected Attributes inherited from souffle::RamTupleOperation
int identifier
Identifier for the tuple, corresponding to its position in the loop nest.
Protected Attributes inherited from souffle::RamNestedOperation
std::unique_ptr< RamOperation > nestedOperation
Nested operation.
const std::string profileText
Text used by the profiler.
Protected Attributes inherited from souffle::RamAbstractChoice
std::unique_ptr< RamCondition > condition
Condition for which a tuple in the relation may hold.
Detailed Description
Definition at line 590 of file Operation.h.
Constructor & Destructor Documentation
RamParallelChoice()
souffle::RamParallelChoice::RamParallelChoice (std::unique_ptr< RamRelationReference > rel, size_t ident, std::unique_ptr< RamCondition > cond, std::unique_ptr< RamOperation > nested, std::string profileText = "") inline
Definition at line 592 of file Operation.h.
             : RamChoice(std::move(rel), ident, std::move(cond), std::move(nested), profileText) {}
Member Function Documentation
clone()
RamParallelChoice* souffle::RamParallelChoice::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Reimplemented from souffle::RamChoice.
Definition at line 597 of file Operation.h.
References souffle::clone().
Referenced by souffle::test::TEST().
{
         return new RamParallelChoice(souffle::clone(relationRef), getTupleId(), souffle::clone(condition),
                 souffle::clone(&getOperation()), getProfileText());
     }
print()
void souffle::RamParallelChoice::print (std::ostream & os, int tabpos) const inline override protected virtual
Pretty print with indentation.
Reimplemented from souffle::RamChoice.
Definition at line 603 of file Operation.h.
References souffle::getRelation(), souffle::RamNestedOperation::print(), and souffle::times().
{
         os << times(" ", tabpos);
         os << "PARALLEL CHOICE t" << getTupleId();
         os << " IN " << getRelation().getName();
         os << " WHERE " << getCondition();
         os << std::endl;
         RamRelationOperation::print(os, tabpos + 1);
     }
The documentation for this class was generated from the following file:
ram/Operation.h