souffle: souffle::RecursiveClausesAnalysis Class Reference
souffle::RecursiveClausesAnalysis Class Reference
Analysis pass identifying clauses which are recursive.
#include <RecursiveClauses.h>
Public Member Functions
void print (std::ostream &os) const override
print the analysis result in HTML format
bool recursive (const AstClause *clause) const
RecursiveClausesAnalysis ()
void run (const AstTranslationUnit &translationUnit) override
run analysis for a Ast translation unit
Public Member Functions inherited from souffle::AstAnalysis
AstAnalysis (std::string identifier)
virtual const std::string & getName () const
get name of the analysis
virtual ~AstAnalysis ()=default
Static Public Attributes
static constexpr const char * name = "recursive-clauses"
Private Member Functions
bool computeIsRecursive (const AstClause &clause, const AstTranslationUnit &translationUnit) const
Determines whether the given clause is recursive within the given program.
Private Attributes
std::set< const AstClause * > recursiveClauses
Additional Inherited Members
Protected Attributes inherited from souffle::AstAnalysis
const std::string identifier
Detailed Description
Analysis pass identifying clauses which are recursive.
Definition at line 34 of file RecursiveClauses.h.
Constructor & Destructor Documentation
RecursiveClausesAnalysis()
souffle::RecursiveClausesAnalysis::RecursiveClausesAnalysis () inline
Definition at line 38 of file RecursiveClauses.h.
References print(), and run().
 : AstAnalysis(name) {}
Member Function Documentation
computeIsRecursive()
bool souffle::RecursiveClausesAnalysis::computeIsRecursive (const AstClause & clause, const AstTranslationUnit & translationUnit) const private
Determines whether the given clause is recursive within the given program.
Definition at line 49 of file RecursiveClauses.cpp.
References souffle::AstTranslationUnit::getAnalysis(), souffle::getHeadRelation(), and souffle::AstTranslationUnit::getProgram().
Referenced by run().
{
     const auto& relationDetail = *translationUnit.getAnalysis<RelationDetailCacheAnalysis>();
     const AstProgram& program = *translationUnit.getProgram();
     // we want to reach the atom of the head through the body
     const AstRelation* trg = getHeadRelation(&clause, &program);
     std::set<const AstRelation*> reached;
     std::vector<const AstRelation*> worklist;
     // set up start list
     for (const auto* cur : getBodyLiterals<AstAtom>(clause)) {
         auto rel = relationDetail.getRelation(cur->getQualifiedName());
         if (rel == trg) {
             return true;
         }
         worklist.push_back(rel);
     }
     // process remaining elements
     while (!worklist.empty()) {
         // get next to process
         const AstRelation* cur = worklist.back();
         worklist.pop_back();
         // skip null pointers (errors in the input code)
         if (cur == nullptr) {
             continue;
         }
         // check whether this one has been checked before
         if (!reached.insert(cur).second) {
             continue;
         }
         // check all atoms in the relations
         for (const AstClause* cl : relationDetail.getClauses(cur)) {
             for (const AstAtom* at : getBodyLiterals<AstAtom>(*cl)) {
                 auto rel = relationDetail.getRelation(at->getQualifiedName());
                 if (rel == trg) {
                     return true;
                 }
                 worklist.push_back(rel);
             }
         }
     }
     // no cycles found
     return false;
 }
print()
void souffle::RecursiveClausesAnalysis::print (std::ostream &) const override virtual
print the analysis result in HTML format
Reimplemented from souffle::AstAnalysis.
Definition at line 45 of file RecursiveClauses.cpp.
References recursiveClauses.
Referenced by RecursiveClausesAnalysis().
{
     os << recursiveClauses << std::endl;
 }
recursive()
bool souffle::RecursiveClausesAnalysis::recursive (const AstClause * clause) const inline
Definition at line 44 of file RecursiveClauses.h.
References recursiveClauses.
Referenced by souffle::AstSemanticCheckerImpl::checkClause(), souffle::AstToRamTranslator::translateNonRecursiveRelation(), and souffle::AstToRamTranslator::translateRecursiveRelation().
{
         return recursiveClauses.count(clause) != 0u;
     }
run()
void souffle::RecursiveClausesAnalysis::run (const AstTranslationUnit &) override virtual
run analysis for a Ast translation unit
Implements souffle::AstAnalysis.
Definition at line 37 of file RecursiveClauses.cpp.
References computeIsRecursive(), souffle::AstTranslationUnit::getProgram(), recursiveClauses, and souffle::visitDepthFirst().
Referenced by RecursiveClausesAnalysis().
{
     visitDepthFirst(*translationUnit.getProgram(), [&](const AstClause& clause) {
         if (computeIsRecursive(clause, translationUnit)) {
             recursiveClauses.insert(&clause);
         }
     });
 }
Field Documentation
name
constexpr const char* souffle::RecursiveClausesAnalysis::name = "recursive-clauses" static
Definition at line 36 of file RecursiveClauses.h.
recursiveClauses
std::set<const AstClause*> souffle::RecursiveClausesAnalysis::recursiveClauses private
Definition at line 49 of file RecursiveClauses.h.
Referenced by print(), recursive(), and run().
The documentation for this class was generated from the following files:
ast/analysis/RecursiveClauses.h
ast/analysis/RecursiveClauses.cpp