souffle: souffle::RelationScheduleAnalysisStep Class Reference
souffle::RelationScheduleAnalysisStep Class Reference
A single step in a relation schedule, consisting of the relations computed in the step and the relations that are no longer required at that step.
#include <RelationSchedule.h>
Public Member Functions
const std::set< const AstRelation * > & computed () const
const std::set< const AstRelation * > & expired () const
void print (std::ostream &os) const
bool recursive () const
RelationScheduleAnalysisStep (std::set< const AstRelation *> computedRelations, std::set< const AstRelation *> expiredRelations, const bool isRecursive)
Private Attributes
std::set< const AstRelation * > computedRelations
std::set< const AstRelation * > expiredRelations
const bool isRecursive
Friends
std::ostream & operator<< (std::ostream &out, const RelationScheduleAnalysisStep &other)
Add support for printing nodes.
Detailed Description
A single step in a relation schedule, consisting of the relations computed in the step and the relations that are no longer required at that step.
Definition at line 39 of file RelationSchedule.h.
Constructor & Destructor Documentation
RelationScheduleAnalysisStep()
souffle::RelationScheduleAnalysisStep::RelationScheduleAnalysisStep (std::set< const AstRelation *> computedRelations, std::set< const AstRelation *> expiredRelations, const bool isRecursive) inline
Definition at line 41 of file RelationSchedule.h.
             : computedRelations(std::move(computedRelations)), expiredRelations(std::move(expiredRelations)),
               isRecursive(isRecursive) {}
Member Function Documentation
computed()
const std::set<const AstRelation*>& souffle::RelationScheduleAnalysisStep::computed () const inline
Definition at line 46 of file RelationSchedule.h.
References computedRelations.
Referenced by print().
{
         return computedRelations;
     }
expired()
const std::set<const AstRelation*>& souffle::RelationScheduleAnalysisStep::expired () const inline
Definition at line 50 of file RelationSchedule.h.
References expiredRelations.
Referenced by print().
{
         return expiredRelations;
     }
print()
void souffle::RelationScheduleAnalysisStep::print (std::ostream & os) const
Definition at line 35 of file RelationSchedule.cpp.
References computed(), expired(), and recursive().
Referenced by recursive(), and souffle::RelationScheduleAnalysis::schedule().
{
     os << "computed: ";
     for (const AstRelation* compRel : computed()) {
         os << compRel->getQualifiedName() << ", ";
     }
     os << "\nexpired: ";
     for (const AstRelation* compRel : expired()) {
         os << compRel->getQualifiedName() << ", ";
     }
     os << "\n";
     if (recursive()) {
         os << "recursive";
     } else {
         os << "not recursive";
     }
     os << "\n";
 }
recursive()
bool souffle::RelationScheduleAnalysisStep::recursive () const inline
Definition at line 54 of file RelationSchedule.h.
References isRecursive, and print().
Referenced by print().
{
         return isRecursive;
     }
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & out, const RelationScheduleAnalysisStep & other) friend
Add support for printing nodes.
Definition at line 61 of file RelationSchedule.h.
{
         other.print(out);
         return out;
     }
Field Documentation
computedRelations
std::set<const AstRelation*> souffle::RelationScheduleAnalysisStep::computedRelations private
Definition at line 67 of file RelationSchedule.h.
Referenced by computed(), and souffle::RelationScheduleAnalysis::run().
expiredRelations
std::set<const AstRelation*> souffle::RelationScheduleAnalysisStep::expiredRelations private
Definition at line 68 of file RelationSchedule.h.
Referenced by expired().
isRecursive
const bool souffle::RelationScheduleAnalysisStep::isRecursive private
Definition at line 69 of file RelationSchedule.h.
Referenced by recursive().
The documentation for this class was generated from the following files:
ast/analysis/RelationSchedule.h
ast/analysis/RelationSchedule.cpp