souffle: souffle::WhileTransformer Class Reference
souffle::WhileTransformer Class Reference
Transformer that repeatedly executes a sub-transformer while a condition is met.
#include <While.h>
Public Member Functions
WhileTransformer * clone () const override
void disableTransformers (const std::set< std::string > &transforms) override
std::string getName () const override
std::vector< AstTransformer * > getSubtransformers () const override
void setDebugReport () override
void setVerbosity (bool verbose) override
WhileTransformer (std::function< bool()> cond, std::unique_ptr< AstTransformer > transformer)
WhileTransformer (bool cond, std::unique_ptr< AstTransformer > transformer)
Public Member Functions inherited from souffle::MetaTransformer
bool applySubtransformer (AstTranslationUnit &translationUnit, AstTransformer *transformer)
Public Member Functions inherited from souffle::AstTransformer
bool apply (AstTranslationUnit &translationUnit)
virtual ~AstTransformer ()=default
Private Member Functions
bool transform (AstTranslationUnit &translationUnit) override
Private Attributes
std::function< bool()> condition
std::unique_ptr< AstTransformer > transformer
Additional Inherited Members
Protected Attributes inherited from souffle::MetaTransformer
bool verbose = false
Detailed Description
Transformer that repeatedly executes a sub-transformer while a condition is met.
Definition at line 36 of file While.h.
Constructor & Destructor Documentation
WhileTransformer() [1/2]
souffle::WhileTransformer::WhileTransformer (std::function< bool()> cond, std::unique_ptr< AstTransformer > transformer) inline
Definition at line 38 of file While.h.
Referenced by clone().
             : condition(std::move(cond)), transformer(std::move(transformer)) {}
WhileTransformer() [2/2]
souffle::WhileTransformer::WhileTransformer (bool cond, std::unique_ptr< AstTransformer > transformer) inline
Definition at line 41 of file While.h.
References transformer.
             : condition([=]() { return cond; }), transformer(std::move(transformer)) {}
Member Function Documentation
clone()
WhileTransformer* souffle::WhileTransformer::clone () const inline override virtual
Implements souffle::MetaTransformer.
Definition at line 74 of file While.h.
References souffle::clone(), condition, transformer, and WhileTransformer().
{
         return new WhileTransformer(condition, souffle::clone(transformer));
     }
disableTransformers()
void souffle::WhileTransformer::disableTransformers (const std::set< std::string > & transforms) inline override virtual
Implements souffle::MetaTransformer.
Definition at line 62 of file While.h.
References transformer.
{
         if (auto* mt = dynamic_cast<MetaTransformer*>(transformer.get())) {
             mt->disableTransformers(transforms);
         } else if (transforms.find(transformer->getName()) != transforms.end()) {
             transformer = std::make_unique<NullTransformer>();
         }
     }
getName()
std::string souffle::WhileTransformer::getName () const inline override virtual
Implements souffle::AstTransformer.
Definition at line 70 of file While.h.
{
         return "WhileTransformer";
     }
getSubtransformers()
std::vector<AstTransformer*> souffle::WhileTransformer::getSubtransformers () const inline override virtual
Implements souffle::MetaTransformer.
Definition at line 44 of file While.h.
References transformer.
{
         return {transformer.get()};
     }
setDebugReport()
void souffle::WhileTransformer::setDebugReport () inline override virtual
Implements souffle::MetaTransformer.
Definition at line 47 of file While.h.
References transformer.
{
         if (auto* mt = dynamic_cast<MetaTransformer*>(transformer.get())) {
             mt->setDebugReport();
         } else {
             transformer = std::make_unique<DebugReporter>(std::move(transformer));
         }
     }
setVerbosity()
void souffle::WhileTransformer::setVerbosity (bool verbose) inline override virtual
Implements souffle::MetaTransformer.
Definition at line 55 of file While.h.
References transformer, and souffle::MetaTransformer::verbose.
{
         this->verbose = verbose;
         if (auto* mt = dynamic_cast<MetaTransformer*>(transformer.get())) {
             mt->setVerbosity(verbose);
         }
     }
transform()
bool souffle::WhileTransformer::transform (AstTranslationUnit & translationUnit) inline override private virtual
Implements souffle::AstTransformer.
Definition at line 82 of file While.h.
References souffle::MetaTransformer::applySubtransformer(), and condition.
{
         bool changed = false;
         while (condition()) {
             changed |= applySubtransformer(translationUnit, transformer.get());
         }
         return changed;
     }
Field Documentation
condition
std::function<bool()> souffle::WhileTransformer::condition private
Definition at line 79 of file While.h.
Referenced by clone(), and transform().
transformer
std::unique_ptr<AstTransformer> souffle::WhileTransformer::transformer private
Definition at line 80 of file While.h.
Referenced by clone(), disableTransformers(), getSubtransformers(), setDebugReport(), setVerbosity(), and WhileTransformer().
The documentation for this class was generated from the following file:
ast/transform/While.h