souffle: souffle::RamComplexityAnalysis Class Reference
souffle::RamComplexityAnalysis Class Reference
A Ram Analysis for determining the number of relational operations in a condition / expression.
#include <ComplexityAnalysis.h>
Public Member Functions
int getComplexity (const RamNode *value) const
Get complexity of a RAM expression/condition.
RamComplexityAnalysis (const char *id)
void run (const RamTranslationUnit &) override
Run analysis for a RAM translation unit.
Public Member Functions inherited from souffle::RamAnalysis
virtual const std::string & getName () const
get name of the analysis
virtual void print (std::ostream &) const
Print the analysis result in HTML format.
RamAnalysis (const char *id)
virtual ~RamAnalysis ()=default
Static Public Attributes
static constexpr const char * name = "complexity-analysis"
Additional Inherited Members
Protected Attributes inherited from souffle::RamAnalysis
std::string identifier
name of analysis instance
Detailed Description
A Ram Analysis for determining the number of relational operations in a condition / expression.
Definition at line 34 of file ComplexityAnalysis.h.
Constructor & Destructor Documentation
RamComplexityAnalysis()
souffle::RamComplexityAnalysis::RamComplexityAnalysis (const char * id) inline
Definition at line 36 of file ComplexityAnalysis.h.
 : RamAnalysis(id) {}
Member Function Documentation
getComplexity()
int souffle::RamComplexityAnalysis::getComplexity (const RamNode * value) const
Get complexity of a RAM expression/condition.
Definition at line 27 of file ComplexityAnalysis.cpp.
References souffle::RamRelation::getArity(), souffle::RamConjunction::getLHS(), souffle::RamNegation::getOperand(), souffle::RamEmptinessCheck::getRelation(), and souffle::RamConjunction::getRHS().
Referenced by souffle::ReorderConditionsTransformer::reorderConditions(), and run().
{
     // visitor
     class ValueComplexityVisitor : public RamVisitor<int> {
     public:
         // conjunction
         int visitConjunction(const RamConjunction& conj) override {
             return visit(conj.getLHS()) + visit(conj.getRHS());
         }
         // negation
         int visitNegation(const RamNegation& neg) override {
             return visit(neg.getOperand());
         }
         // existence check
         int visitExistenceCheck(const RamExistenceCheck&) override {
             return 2;
         }
         // provenance existence check
         int visitProvenanceExistenceCheck(const RamProvenanceExistenceCheck&) override {
             return 2;
         }
         // emptiness check
         int visitEmptinessCheck(const RamEmptinessCheck& emptiness) override {
             // emptiness check for nullary relations is for free; others have weight one
             return (emptiness.getRelation().getArity() > 0) ? 1 : 0;
         }
         // default rule
         int visitNode(const RamNode&) override {
             return 0;
         }
     };
     assert((dynamic_cast<const RamExpression*>(node) != nullptr ||
                    dynamic_cast<const RamCondition*>(node) != nullptr) &&
             "not an expression/condition/operation");
     return ValueComplexityVisitor().visit(node);
 }
run()
void souffle::RamComplexityAnalysis::run (const RamTranslationUnit & translationUnit) inline override virtual
Run analysis for a RAM translation unit.
Implements souffle::RamAnalysis.
Definition at line 40 of file ComplexityAnalysis.h.
References getComplexity().
 {}
Field Documentation
name
constexpr const char* souffle::RamComplexityAnalysis::name = "complexity-analysis" static
Definition at line 38 of file ComplexityAnalysis.h.
The documentation for this class was generated from the following files:
ram/analysis/ComplexityAnalysis.h
ram/analysis/ComplexityAnalysis.cpp