souffle: souffle::AstExecutionPlanChecker Class Reference
souffle::AstExecutionPlanChecker Class Reference
#include <ExecutionPlanChecker.h>
Public Member Functions
AstExecutionPlanChecker * clone () const override
std::string getName () const override
Public Member Functions inherited from souffle::AstTransformer
bool apply (AstTranslationUnit &translationUnit)
virtual ~AstTransformer ()=default
Private Member Functions
bool transform (AstTranslationUnit &translationUnit) override
Detailed Description
Definition at line 26 of file ExecutionPlanChecker.h.
Member Function Documentation
clone()
AstExecutionPlanChecker* souffle::AstExecutionPlanChecker::clone () const inline override virtual
Implements souffle::AstTransformer.
Definition at line 32 of file ExecutionPlanChecker.h.
References transform().
{
         return new AstExecutionPlanChecker();
     }
getName()
std::string souffle::AstExecutionPlanChecker::getName () const inline override virtual
Implements souffle::AstTransformer.
Definition at line 28 of file ExecutionPlanChecker.h.
{
         return "AstExecutionPlanChecker";
     }
transform()
bool souffle::AstExecutionPlanChecker::transform (AstTranslationUnit & translationUnit) override private virtual
Implements souffle::AstTransformer.
Definition at line 36 of file ExecutionPlanChecker.cpp.
References souffle::Diagnostic::ERROR, souffle::AstTranslationUnit::getAnalysis(), souffle::getAtomRelation(), souffle::getClauses(), souffle::AstTranslationUnit::getErrorReport(), and souffle::AstTranslationUnit::getProgram().
Referenced by clone().
{
     auto* relationSchedule = translationUnit.getAnalysis<RelationScheduleAnalysis>();
     auto* recursiveClauses = translationUnit.getAnalysis<RecursiveClausesAnalysis>();
     auto&& report = translationUnit.getErrorReport();
     for (const RelationScheduleAnalysisStep& step : relationSchedule->schedule()) {
         const std::set<const AstRelation*>& scc = step.computed();
         for (const AstRelation* rel : scc) {
             for (const AstClause* clause : getClauses(*translationUnit.getProgram(), *rel)) {
                 if (!recursiveClauses->recursive(clause)) {
                     continue;
                 }
                 if (clause->getExecutionPlan() == nullptr) {
                     continue;
                 }
                 int version = 0;
                 for (const auto* atom : getBodyLiterals<AstAtom>(*clause)) {
                     if (scc.count(getAtomRelation(atom, translationUnit.getProgram())) != 0u) {
                         version++;
                     }
                 }
                 int maxVersion = -1;
                 for (auto const& cur : clause->getExecutionPlan()->getOrders()) {
                     maxVersion = std::max(cur.first, maxVersion);
                 }
                 if (version <= maxVersion) {
                     for (const auto& cur : clause->getExecutionPlan()->getOrders()) {
                         if (cur.first >= version) {
                             report.addDiagnostic(Diagnostic(Diagnostic::Type::ERROR,
                                     DiagnosticMessage(
                                             "execution plan for version " + std::to_string(cur.first),
                                             cur.second->getSrcLoc()),
                                     {DiagnosticMessage("only versions 0.." + std::to_string(version - 1) +
                                                        " permitted")}));
                         }
                     }
                 }
             }
         }
     }
     return false;
 }
The documentation for this class was generated from the following files:
ast/transform/ExecutionPlanChecker.h
ast/transform/ExecutionPlanChecker.cpp