souffle: souffle::Graph< Vertex, Compare > Class Template Reference
souffle::Graph< Vertex, Compare > Class Template Reference
A simple graph structure for graph-based operations.
#include <GraphUtils.h>
Public Member Functions
const std::set< Vertex, Compare > clique (const Vertex &vertex) const
Obtains the set of all vertices in the same clique than the given vertex.
bool contains (const Vertex &vertex) const
Determines whether the given vertex is present.
bool contains (const Vertex &from, const Vertex &to) const
Determines whether the given edge is present.
void insert (const Vertex &from, const Vertex &to)
Adds a new edge from the given vertex to the target vertex.
void insert (const Vertex &vertex)
Adds a vertex.
const std::set< Vertex, Compare > & predecessors (const Vertex &to) const
Returns the set of vertices the given vertex has edges from.
void print (std::ostream &out) const
Enables graphs to be printed (e.g.
bool reaches (const Vertex &from, const Vertex &to) const
Determines whether there is a directed path between the two vertices.
const std::set< Vertex, Compare > & successors (const Vertex &from) const
Returns the set of vertices the given vertex has edges to.
const std::set< Vertex, Compare > & vertices () const
Obtains a reference to the set of all vertices.
template<typename Lambda >
void visitDepthFirst (const Vertex &vertex, const Lambda &lambda) const
A generic utility for depth-first visits.
Private Member Functions
template<typename Lambda >
void visitDepthFirst (const Vertex &vertex, const Lambda &lambda, std::set< Vertex, Compare > &visited) const
The internal implementation of depth-first visits.
Private Attributes
std::map< Vertex, std::set< Vertex, Compare > > _predecessors
std::map< Vertex, std::set< Vertex, Compare > > _successors
std::set< Vertex, Compare > _vertices
Friends
std::ostream & operator<< (std::ostream &out, const Graph &g)
Detailed Description
template<typename Vertex, typename Compare = std::less<Vertex>>
class souffle::Graph< Vertex, Compare >
A simple graph structure for graph-based operations.
Definition at line 34 of file GraphUtils.h.
Member Function Documentation
clique()
template<typename Vertex, typename Compare = std::less<Vertex>> const std::set<Vertex, Compare> souffle::Graph< Vertex, Compare >::clique (const Vertex & vertex) const inline
Obtains the set of all vertices in the same clique than the given vertex.
Definition at line 105 of file GraphUtils.h.
{
         std::set<Vertex, Compare> res;
         res.insert(vertex);
         for (const auto& cur : vertices()) {
             if (reaches(vertex, cur) && reaches(cur, vertex)) {
                 res.insert(cur);
             }
         }
         return res;
     }
contains() [1/2]
template<typename Vertex, typename Compare = std::less<Vertex>> bool souffle::Graph< Vertex, Compare >::contains (const Vertex & vertex) const inline
Determines whether the given vertex is present.
Definition at line 73 of file GraphUtils.h.
Referenced by souffle::Graph< const souffle::AstRelation *, souffle::AstNameComparison >::reaches(), and souffle::test::TEST().
{
         return _vertices.find(vertex) != _vertices.end();
     }
contains() [2/2]
template<typename Vertex, typename Compare = std::less<Vertex>> bool souffle::Graph< Vertex, Compare >::contains (const Vertex & from, const Vertex & to) const inline
Determines whether the given edge is present.
Definition at line 78 of file GraphUtils.h.
{
         auto pos = _successors.find(from);
         if (pos == _successors.end()) {
             return false;
         }
         auto p2 = pos->second.find(to);
         return p2 != pos->second.end();
     }
insert() [1/2]
template<typename Vertex, typename Compare = std::less<Vertex>> void souffle::Graph< Vertex, Compare >::insert (const Vertex & from, const Vertex & to) inline
Adds a new edge from the given vertex to the target vertex.
Definition at line 39 of file GraphUtils.h.
Referenced by souffle::Graph< const souffle::AstRelation *, souffle::AstNameComparison >::insert(), souffle::test::TEST(), and souffle::ReduceExistentialsTransformer::transform().
{
         insert(from);
         insert(to);
         _successors[from].insert(to);
         _predecessors[to].insert(from);
     }
insert() [2/2]
template<typename Vertex, typename Compare = std::less<Vertex>> void souffle::Graph< Vertex, Compare >::insert (const Vertex & vertex) inline
Adds a vertex.
Definition at line 49 of file GraphUtils.h.
{
         auto iter = _vertices.insert(vertex);
         if (iter.second) {
             _successors.insert(std::make_pair(vertex, std::set<Vertex, Compare>()));
             _predecessors.insert(std::make_pair(vertex, std::set<Vertex, Compare>()));
         }
     }
predecessors()
template<typename Vertex, typename Compare = std::less<Vertex>> const std::set<Vertex, Compare>& souffle::Graph< Vertex, Compare >::predecessors (const Vertex & to) const inline
Returns the set of vertices the given vertex has edges from.
Definition at line 68 of file GraphUtils.h.
{
         return _predecessors.at(to);
     }
print()
template<typename Vertex, typename Compare = std::less<Vertex>> void souffle::Graph< Vertex, Compare >::print (std::ostream & out) const inline
Enables graphs to be printed (e.g.
for debugging)
Definition at line 124 of file GraphUtils.h.
{
         bool first = true;
         out << "{";
         for (const auto& cur : _successors) {
             for (const auto& trg : cur.second) {
                 if (!first) {
                     out << ",";
                 }
                 out << cur.first << "->" << trg;
                 first = false;
             }
         }
         out << "}";
     }
reaches()
template<typename Vertex, typename Compare = std::less<Vertex>> bool souffle::Graph< Vertex, Compare >::reaches (const Vertex & from, const Vertex & to) const inline
Determines whether there is a directed path between the two vertices.
Definition at line 88 of file GraphUtils.h.
Referenced by souffle::Graph< const souffle::AstRelation *, souffle::AstNameComparison >::clique(), and souffle::test::TEST().
{
         // quick check
         if (!contains(from) || !contains(to)) {
             return false;
         }
         // conduct a depth-first search starting at from
         bool found = false;
         bool first = true;
         visitDepthFirst(from, [&](const Vertex& cur) {
             found = !first && (found || cur == to);
             first = false;
         });
         return found;
     }
successors()
template<typename Vertex, typename Compare = std::less<Vertex>> const std::set<Vertex, Compare>& souffle::Graph< Vertex, Compare >::successors (const Vertex & from) const inline
Returns the set of vertices the given vertex has edges to.
Definition at line 63 of file GraphUtils.h.
{
         return _successors.at(from);
     }
vertices()
template<typename Vertex, typename Compare = std::less<Vertex>> const std::set<Vertex, Compare>& souffle::Graph< Vertex, Compare >::vertices () const inline
Obtains a reference to the set of all vertices.
Definition at line 58 of file GraphUtils.h.
Referenced by souffle::Graph< const souffle::AstRelation *, souffle::AstNameComparison >::clique().
{
         return _vertices;
     }
visitDepthFirst() [1/2]
template<typename Vertex, typename Compare = std::less<Vertex>> template<typename Lambda > void souffle::Graph< Vertex, Compare >::visitDepthFirst (const Vertex & vertex, const Lambda & lambda) const inline
A generic utility for depth-first visits.
Definition at line 118 of file GraphUtils.h.
Referenced by souffle::Graph< const souffle::AstRelation *, souffle::AstNameComparison >::reaches(), souffle::ReduceExistentialsTransformer::transform(), and souffle::Graph< const souffle::AstRelation *, souffle::AstNameComparison >::visitDepthFirst().
{
         std::set<Vertex, Compare> visited;
         visitDepthFirst(vertex, lambda, visited);
     }
visitDepthFirst() [2/2]
template<typename Vertex, typename Compare = std::less<Vertex>> template<typename Lambda > void souffle::Graph< Vertex, Compare >::visitDepthFirst (const Vertex & vertex, const Lambda & lambda, std::set< Vertex, Compare > & visited) const inline private
The internal implementation of depth-first visits.
Definition at line 152 of file GraphUtils.h.
{
         lambda(vertex);
         auto pos = _successors.find(vertex);
         if (pos == _successors.end()) {
             return;
         }
         for (const auto& cur : pos->second) {
             if (visited.insert(cur).second) {
                 visitDepthFirst(cur, lambda, visited);
             }
         }
     }
Friends And Related Function Documentation
operator<<
template<typename Vertex, typename Compare = std::less<Vertex>> std::ostream& operator<< (std::ostream & out, const Graph< Vertex, Compare > & g) friend
Definition at line 139 of file GraphUtils.h.
{
         g.print(out);
         return out;
     }
Field Documentation
_predecessors
template<typename Vertex, typename Compare = std::less<Vertex>> std::map<Vertex, std::set<Vertex, Compare> > souffle::Graph< Vertex, Compare >::_predecessors private
Definition at line 148 of file GraphUtils.h.
Referenced by souffle::Graph< const souffle::AstRelation *, souffle::AstNameComparison >::insert(), and souffle::Graph< const souffle::AstRelation *, souffle::AstNameComparison >::predecessors().
_successors
template<typename Vertex, typename Compare = std::less<Vertex>> std::map<Vertex, std::set<Vertex, Compare> > souffle::Graph< Vertex, Compare >::_successors private
Definition at line 147 of file GraphUtils.h.
Referenced by souffle::Graph< const souffle::AstRelation *, souffle::AstNameComparison >::contains(), souffle::Graph< const souffle::AstRelation *, souffle::AstNameComparison >::insert(), souffle::Graph< const souffle::AstRelation *, souffle::AstNameComparison >::print(), and souffle::Graph< const souffle::AstRelation *, souffle::AstNameComparison >::successors().
_vertices
template<typename Vertex, typename Compare = std::less<Vertex>> std::set<Vertex, Compare> souffle::Graph< Vertex, Compare >::_vertices private
Definition at line 146 of file GraphUtils.h.
Referenced by souffle::Graph< const souffle::AstRelation *, souffle::AstNameComparison >::contains(), souffle::Graph< const souffle::AstRelation *, souffle::AstNameComparison >::insert(), and souffle::Graph< const souffle::AstRelation *, souffle::AstNameComparison >::vertices().
The documentation for this class was generated from the following file:
GraphUtils.h