souffle: souffle::AstNilConstant Class Reference
souffle::AstNilConstant Class Reference
Nil Constant.
#include <NilConstant.h>
Public Member Functions
AstNilConstant (SrcLocation loc={})
AstNilConstant * clone () const override
Create clone.
Public Member Functions inherited from souffle::AstConstant
const std::string & getConstant () const
Public Member Functions inherited from souffle::AstNode
virtual void apply (const AstNodeMapper &)
Apply the mapper to all child nodes.
AstNode (SrcLocation loc={})
std::string extloc () const
Return source location of the syntactic element.
virtual std::vector< const AstNode * > getChildNodes () const
Obtain a list of all embedded AST child nodes.
const SrcLocation & getSrcLoc () const
Return source location of the AstNode.
bool operator!= (const AstNode &other) const
Inequality check for two AST nodes.
bool operator== (const AstNode &other) const
Equivalence check for two AST nodes.
void setSrcLoc (SrcLocation l)
Set source location for the AstNode.
virtual ~AstNode ()=default
Additional Inherited Members
Protected Member Functions inherited from souffle::AstConstant
AstConstant (std::string value, SrcLocation loc={})
bool equal (const AstNode &node) const override
Abstract equality check for two AST nodes.
void print (std::ostream &os) const override
Output to a given output stream.
Detailed Description
Nil Constant.
Definition at line 27 of file NilConstant.h.
Constructor & Destructor Documentation
AstNilConstant()
souffle::AstNilConstant::AstNilConstant (SrcLocation loc = {}) inline
Definition at line 29 of file NilConstant.h.
References souffle::AstConstant::AstConstant().
Referenced by clone().
 {}) : AstConstant("nil", std::move(loc)) {}
Member Function Documentation
clone()
AstNilConstant* souffle::AstNilConstant::clone () const inline override virtual
Create clone.
Implements souffle::AstConstant.
Definition at line 31 of file NilConstant.h.
References AstNilConstant(), and souffle::AstNode::getSrcLoc().
{
         return new AstNilConstant(getSrcLoc());
     }
The documentation for this class was generated from the following file:
ast/NilConstant.h