souffle: souffle::AstClause Class Reference
souffle::AstClause Class Reference
Intermediate representation of a datalog clause.
#include <Clause.h>
Public Member Functions
void addToBody (Own< AstLiteral > literal)
Add a Literal to the body of the clause.
void apply (const AstNodeMapper &map) override
Apply the mapper to all child nodes.
AstClause (Own< AstAtom > head={}, VecOwn< AstLiteral > bodyLiterals={}, Own< AstExecutionPlan > plan={}, SrcLocation loc={})
void clearExecutionPlan ()
Resets the execution plan.
AstClause * clone () const override
Create a clone (i.e.
std::vector< AstLiteral * > getBodyLiterals () const
Obtains a copy of the internally maintained body literals.
std::vector< const AstNode * > getChildNodes () const override
Obtain a list of all embedded AST child nodes.
const AstExecutionPlan * getExecutionPlan () const
Obtains the execution plan associated to this clause or null if there is none.
AstAtom * getHead () const
Return the atom that represents the head of the clause.
void setBodyLiterals (VecOwn< AstLiteral > body)
Set the bodyLiterals of clause to body.
void setExecutionPlan (Own< AstExecutionPlan > plan)
Updates the execution plan associated to this clause.
void setHead (Own< AstAtom > h)
Set the head of clause to h.
Public Member Functions inherited from souffle::AstNode
AstNode (SrcLocation loc={})
std::string extloc () const
Return source location of the syntactic element.
const SrcLocation & getSrcLoc () const
Return source location of the AstNode.
bool operator!= (const AstNode &other) const
Inequality check for two AST nodes.
bool operator== (const AstNode &other) const
Equivalence check for two AST nodes.
void setSrcLoc (SrcLocation l)
Set source location for the AstNode.
virtual ~AstNode ()=default
Protected Member Functions
bool equal (const AstNode &node) const override
Abstract equality check for two AST nodes.
void print (std::ostream &os) const override
Output to a given output stream.
Protected Attributes
VecOwn< AstLiteral > bodyLiterals
body literals of clause
Own< AstAtom > head
head of the clause
Own< AstExecutionPlan > plan
user defined execution plan (if not defined, plan is null)
Detailed Description
Intermediate representation of a datalog clause.
A clause can either be:
a fact - a clause with no body (e.g., X(a,b))
a rule - a clause with a head and a body (e.g., Y(a,b) -: X(a,b))
TODO (azreika): make clause abstract and split into two subclasses: Rule and Fact
Definition at line 46 of file Clause.h.
Constructor & Destructor Documentation
AstClause()
souffle::AstClause::AstClause (Own< AstAtom > head = {}, VecOwn< AstLiteral > bodyLiterals = {}, Own< AstExecutionPlan > plan = {}, SrcLocation loc = {}) inline
Definition at line 48 of file Clause.h.
References souffle::AstNode::AstNode(), bodyLiterals, head, and plan.
Referenced by clone().
                                   {}, VecOwn<AstLiteral> bodyLiterals = {}, Own<AstExecutionPlan> plan = {},
             SrcLocation loc = {})
             : AstNode(std::move(loc)), head(std::move(head)), bodyLiterals(std::move(bodyLiterals)),
               plan(std::move(plan)) {}
Member Function Documentation
addToBody()
void souffle::AstClause::addToBody (Own< AstLiteral > literal) inline
Add a Literal to the body of the clause.
Definition at line 54 of file Clause.h.
Referenced by souffle::AstSemanticCheckerImpl::checkAggregator(), souffle::getInlinedClause(), souffle::reorderAtoms(), souffle::RuleBody::toClauseBodies(), and souffle::MaterializeSingletonAggregationTransformer::transform().
{
         bodyLiterals.push_back(std::move(literal));
     }
apply()
void souffle::AstClause::apply (const AstNodeMapper &) inline override virtual
Apply the mapper to all child nodes.
Reimplemented from souffle::AstNode.
Definition at line 98 of file Clause.h.
References head, and souffle::map().
Referenced by souffle::ResolveAnonymousRecordsAliases::replaceNamedVariables(), souffle::ResolveAnonymousRecordsAliases::replaceUnnamedVariable(), and souffle::MaterializeSingletonAggregationTransformer::transform().
{
         head = map(std::move(head));
         for (auto& lit : bodyLiterals) {
             lit = map(std::move(lit));
         }
     }
clearExecutionPlan()
void souffle::AstClause::clearExecutionPlan () inline
Resets the execution plan.
Definition at line 89 of file Clause.h.
{
         plan = nullptr;
     }
clone()
AstClause* souffle::AstClause::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::AstNode.
Definition at line 93 of file Clause.h.
References AstClause(), souffle::clone(), souffle::AstNode::getSrcLoc(), and head.
Referenced by souffle::getInlinedClause(), souffle::AstToRamTranslator::ClauseTranslator::getReorderedClause(), souffle::ResolveAliasesTransformer::removeComplexTermsInAtoms(), souffle::separateDBs(), and souffle::MagicSetTransformer::transform().
{
         return new AstClause(
                 souffle::clone(head), souffle::clone(bodyLiterals), souffle::clone(plan), getSrcLoc());
     }
equal()
bool souffle::AstClause::equal (const AstNode &) const inline override protected virtual
Abstract equality check for two AST nodes.
Reimplemented from souffle::AstNode.
Definition at line 127 of file Clause.h.
References souffle::equal_ptr(), souffle::equal_targets(), and head.
{
         const auto& other = static_cast<const AstClause&>(node);
         return equal_ptr(head, other.head) && equal_targets(bodyLiterals, other.bodyLiterals) &&
                equal_ptr(plan, other.plan);
     }
getBodyLiterals()
std::vector<AstLiteral*> souffle::AstClause::getBodyLiterals () const inline
Obtains a copy of the internally maintained body literals.
Definition at line 74 of file Clause.h.
References souffle::toPtrVector().
Referenced by souffle::AstSemanticCheckerImpl::checkClause(), souffle::AstSemanticCheckerImpl::checkWitnessProblem(), souffle::AstToRamTranslator::ProvenanceClauseTranslator::createOperation(), souffle::ResolveAnonymousRecordsAliases::findVariablesRecordMapping(), souffle::getBodyRelations(), souffle::getInlinedClause(), souffle::isFact(), souffle::isRecursiveClause(), souffle::makeInfoRelation(), souffle::AstToRamTranslator::makeNegationSubproofSubroutine(), souffle::AstToRamTranslator::makeSubproofSubroutine(), souffle::MaterializeAggregationQueriesTransformer::materializeAggregationQueries(), souffle::MinimiseProgramTransformer::NormalisedClauseRepr::NormalisedClauseRepr(), souffle::ResolveAliasesTransformer::removeTrivialEquality(), souffle::reorderAtoms(), souffle::test::TEST(), souffle::MaterializeSingletonAggregationTransformer::transform(), souffle::PartitionBodyLiteralsTransformer::transform(), souffle::MagicSetTransformer::transform(), souffle::FoldAnonymousRecords::transformClause(), souffle::AstToRamTranslator::ClauseTranslator::translateClause(), and souffle::AstToRamTranslator::translateProgram().
{
         return toPtrVector(bodyLiterals);
     }
getChildNodes()
std::vector<const AstNode*> souffle::AstClause::getChildNodes () const inline override virtual
Obtain a list of all embedded AST child nodes.
Reimplemented from souffle::AstNode.
Definition at line 105 of file Clause.h.
References head.
{
         std::vector<const AstNode*> res = {head.get()};
         for (auto& cur : bodyLiterals) {
             res.push_back(cur.get());
         }
         return res;
     }
getExecutionPlan()
const AstExecutionPlan* souffle::AstClause::getExecutionPlan () const inline
Obtains the execution plan associated to this clause or null if there is none.
Definition at line 79 of file Clause.h.
Referenced by souffle::AstSemanticCheckerImpl::checkClause(), souffle::cloneHead(), souffle::AstToRamTranslator::ClauseTranslator::getReorderedClause(), and souffle::reorderClauseWithSips().
{
         return plan.get();
     }
getHead()
AstAtom* souffle::AstClause::getHead () const inline
Return the atom that represents the head of the clause.
Definition at line 69 of file Clause.h.
References head.
Referenced by souffle::AstSemanticCheckerImpl::checkClause(), souffle::AstSemanticCheckerImpl::checkFact(), souffle::AstSemanticCheckerImpl::checkWitnessProblem(), souffle::cloneHead(), souffle::TypeConstraintsAnalysis::collectConstraints(), souffle::AstToRamTranslator::ClauseTranslator::createCondition(), souffle::AstToRamTranslator::ClauseTranslator::createOperation(), souffle::getBodyRelations(), souffle::getClauseNum(), souffle::getGroundedTerms(), souffle::getHeadRelation(), souffle::getInlinedClause(), souffle::isFact(), souffle::isRecursiveClause(), souffle::isRule(), souffle::makeInfoRelation(), souffle::AstToRamTranslator::makeNegationSubproofSubroutine(), souffle::AstToRamTranslator::makeSubproofSubroutine(), souffle::MinimiseProgramTransformer::NormalisedClauseRepr::NormalisedClauseRepr(), souffle::MinimiseProgramTransformer::reduceSingletonRelations(), souffle::separateDBs(), souffle::test::TEST(), souffle::PartitionBodyLiteralsTransformer::transform(), souffle::MagicSetTransformer::transform(), souffle::AstToRamTranslator::ClauseTranslator::translateClause(), and souffle::AstToRamTranslator::translateProgram().
{
         return head.get();
     }
print()
void souffle::AstClause::print (std::ostream & os) const inline override protected virtual
Output to a given output stream.
Implements souffle::AstNode.
Definition at line 114 of file Clause.h.
References head, souffle::join(), and plan.
{
         if (head != nullptr) {
             os << *head;
         }
         if (!bodyLiterals.empty()) {
             os << " :- \n   " << join(bodyLiterals, ",\n   ");
         }
         os << ".";
         if (plan != nullptr) {
             os << *plan;
         }
     }
setBodyLiterals()
void souffle::AstClause::setBodyLiterals (VecOwn< AstLiteral > body) inline
Set the bodyLiterals of clause to body.
Definition at line 64 of file Clause.h.
{
         bodyLiterals = std::move(body);
     }
setExecutionPlan()
void souffle::AstClause::setExecutionPlan (Own< AstExecutionPlan > plan) inline
Updates the execution plan associated to this clause.
Definition at line 84 of file Clause.h.
{
         this->plan = std::move(plan);
     }
setHead()
void souffle::AstClause::setHead (Own< AstAtom > h) inline
Set the head of clause to h.
Definition at line 59 of file Clause.h.
References head.
{
         head = std::move(h);
     }
Field Documentation
bodyLiterals
VecOwn<AstLiteral> souffle::AstClause::bodyLiterals protected
body literals of clause
Definition at line 137 of file Clause.h.
Referenced by AstClause().
head
Own<AstAtom> souffle::AstClause::head protected
head of the clause
Definition at line 134 of file Clause.h.
Referenced by apply(), AstClause(), clone(), equal(), getChildNodes(), getHead(), print(), and setHead().
plan
Own<AstExecutionPlan> souffle::AstClause::plan protected
user defined execution plan (if not defined, plan is null)
Definition at line 140 of file Clause.h.
Referenced by AstClause(), and print().
The documentation for this class was generated from the following file:
ast/Clause.h