souffle: souffle::IndexedInequalityTransformer Class Reference
souffle::IndexedInequalityTransformer Class Reference
Removes Inequalities from Indexed Operations and replaces them with a Filter Operation and empty Indexed Operations are coverted to their Non-Indexed semantic equivalent.
#include <IndexedInequality.h>
Public Member Functions
std::string getName () const override
get name of the transformer
bool transformIndexToFilter (RamProgram &program)
Converts a box query into a corresponding partial box query operation.
Public Member Functions inherited from souffle::RamTransformer
bool apply (RamTranslationUnit &translationUnit)
apply the transformer to a translation unit translationUnit that will be transformed.
virtual ~RamTransformer ()=default
Protected Member Functions
bool transform (RamTranslationUnit &translationUnit) override
transform the translation unit / used by apply translationUnit that will be transformed.
Protected Attributes
RamIndexAnalysis * idxAnalysis
Detailed Description
Removes Inequalities from Indexed Operations and replaces them with a Filter Operation and empty Indexed Operations are coverted to their Non-Indexed semantic equivalent.
If there exists inequality constraints in an Indexed Operation, these constraints will be replaced with a semantically equivalent nested Filter Operation.
Furthermore, if after removing all of these inequality constraints from the Indexed Operation we may find that the Indexed Operation is empty (no constraints). This occurs in the case where an Indexed Operation is composed entirely of inequality constraints. In this situation, the Indexed Operation is empty and replaced with a semantically equivalent Operation. i.e. RamIndexScan -> RamScan
For example,
QUERY
 ...
 FOR t1 IN X ON INDEX t1.x < 10 AND t1.y > 20
   ... // t1 only has inequality constraints placed on it
will be rewritten to
QUERY
 ...
     FOR t1 in X ON INDEX // empty index since all inequalities have been removed
          IF t1.x < 10 AND t1.y > 20
              // replaced with a semantically equivalent filter
    ...
will be rewritten to
QUERY
 ...
     FOR t1 in X // RamScan instead of RamIndexScan
          IF t1.x < 10 AND t1.y > 20
              // replaced with a semantically equivalent filter
    ...
Definition at line 72 of file IndexedInequality.h.
Member Function Documentation
getName()
std::string souffle::IndexedInequalityTransformer::getName () const inline override virtual
get name of the transformer
Implements souffle::RamTransformer.
Definition at line 74 of file IndexedInequality.h.
References transformIndexToFilter().
{
         return "IndexedInequalityTransformer";
     }
transform()
bool souffle::IndexedInequalityTransformer::transform (RamTranslationUnit & translationUnit) inline override protected virtual
transform the translation unit / used by apply translationUnit that will be transformed.
flag reporting whether the RAM program has changed
Implements souffle::RamTransformer.
Definition at line 84 of file IndexedInequality.h.
References souffle::RamTranslationUnit::getAnalysis(), souffle::RamTranslationUnit::getProgram(), idxAnalysis, and transformIndexToFilter().
{
         idxAnalysis = translationUnit.getAnalysis<RamIndexAnalysis>();
         return transformIndexToFilter(translationUnit.getProgram());
     }
transformIndexToFilter()
bool souffle::IndexedInequalityTransformer::transformIndexToFilter (RamProgram & program)
Converts a box query into a corresponding partial box query operation.
This will turn every box query into a filter operation.
Definition at line 37 of file IndexedInequality.cpp.
References souffle::RamTransformer::apply(), souffle::clone(), souffle::fatal(), souffle::filter(), souffle::GE, souffle::RamIndexAnalysis::getIndexes(), i, idxAnalysis, souffle::isRamUndefValue(), souffle::LE, souffle::makeLambdaRamMapper(), p, and souffle::visitDepthFirst().
Referenced by getName(), and transform().
{
     bool changed = false;
     // helper for collecting conditions from filter operations
     auto addCondition = [](std::unique_ptr<RamCondition> condition,
                                 std::unique_ptr<RamCondition> c) -> std::unique_ptr<RamCondition> {
         if (condition == nullptr) {
             return c;
         } else {
             return std::make_unique<RamConjunction>(std::move(condition), std::move(c));
         }
     };
     visitDepthFirst(program, [&](const RamQuery& query) {
         std::function<std::unique_ptr<RamNode>(std::unique_ptr<RamNode>)> indexToFilterRewriter =
                 [&](std::unique_ptr<RamNode> node) -> std::unique_ptr<RamNode> {
             // find a RamIndexOperation
             if (const RamIndexOperation* indexOperation = dynamic_cast<RamIndexOperation*>(node.get())) {
                 auto attributesToDischarge =
                         idxAnalysis->getIndexes(indexOperation->getRelation()).getAttributesToDischarge();
                 auto pattern = indexOperation->getRangePattern();
                 std::unique_ptr<RamCondition> condition;
                 RamPattern updatedPattern;
                 for (RamExpression* p : indexOperation->getRangePattern().first) {
                     updatedPattern.first.emplace_back(p->clone());
                 }
                 for (RamExpression* p : indexOperation->getRangePattern().second) {
                     updatedPattern.second.emplace_back(p->clone());
                 }
                 for (auto i : attributesToDischarge) {
                     // move constraints out of the indexed inequality and into a conjuction
                     std::unique_ptr<RamConstraint> lowerBound;
                     std::unique_ptr<RamConstraint> upperBound;
                     changed = true;
                     if (!isRamUndefValue(pattern.first[i])) {
                         lowerBound = std::make_unique<RamConstraint>(BinaryConstraintOp::GE,
                                 std::make_unique<RamTupleElement>(indexOperation->getTupleId(), i),
                                 souffle::clone(pattern.first[i]));
                         condition = addCondition(std::move(condition), souffle::clone(lowerBound));
                     }
                     if (!isRamUndefValue(pattern.second[i])) {
                         upperBound = std::make_unique<RamConstraint>(BinaryConstraintOp::LE,
                                 std::make_unique<RamTupleElement>(indexOperation->getTupleId(), i),
                                 souffle::clone(pattern.second[i]));
                         condition = addCondition(std::move(condition), souffle::clone(upperBound));
                     }
                     // reset the bounds
                     updatedPattern.first[i] = std::make_unique<RamUndefValue>();
                     updatedPattern.second[i] = std::make_unique<RamUndefValue>();
                 }
                 if (condition) {
                     auto nestedOp = souffle::clone(&indexOperation->getOperation());
                     auto filter = std::make_unique<RamFilter>(std::move(condition), std::move(nestedOp));
                     // need to rewrite the node with the same index operation
                     if (const RamIndexScan* iscan = dynamic_cast<RamIndexScan*>(node.get())) {
                         node = std::make_unique<RamIndexScan>(
                                 std::make_unique<RamRelationReference>(&iscan->getRelation()),
                                 iscan->getTupleId(), std::move(updatedPattern), std::move(filter),
                                 iscan->getProfileText());
                     } else if (const RamParallelIndexScan* pscan =
                                        dynamic_cast<RamParallelIndexScan*>(node.get())) {
                         node = std::make_unique<RamParallelIndexScan>(
                                 std::make_unique<RamRelationReference>(&pscan->getRelation()),
                                 pscan->getTupleId(), std::move(updatedPattern), std::move(filter),
                                 pscan->getProfileText());
                     } else if (const RamIndexChoice* ichoice = dynamic_cast<RamIndexChoice*>(node.get())) {
                         node = std::make_unique<RamIndexChoice>(
                                 std::make_unique<RamRelationReference>(&ichoice->getRelation()),
                                 ichoice->getTupleId(), souffle::clone(&ichoice->getCondition()),
                                 std::move(updatedPattern), std::move(filter), ichoice->getProfileText());
                     } else if (const RamIndexAggregate* iagg = dynamic_cast<RamIndexAggregate*>(node.get())) {
                         node = std::make_unique<RamIndexAggregate>(std::move(filter), iagg->getFunction(),
                                 std::make_unique<RamRelationReference>(&iagg->getRelation()),
                                 souffle::clone(&iagg->getExpression()), souffle::clone(&iagg->getCondition()),
                                 std::move(updatedPattern), iagg->getTupleId());
                     } else {
                         fatal("New RamIndexOperation subclass found but not supported while making index.");
                     }
                 }
             }
             node->apply(makeLambdaRamMapper(indexToFilterRewriter));
             return node;
         };
         const_cast<RamQuery*>(&query)->apply(makeLambdaRamMapper(indexToFilterRewriter));
     });
     visitDepthFirst(program, [&](const RamQuery& query) {
         std::function<std::unique_ptr<RamNode>(std::unique_ptr<RamNode>)> removeEmptyIndexRewriter =
                 [&](std::unique_ptr<RamNode> node) -> std::unique_ptr<RamNode> {
             // find an IndexOperation
             if (const RamIndexOperation* indexOperation = dynamic_cast<RamIndexOperation*>(node.get())) {
                 auto pattern = indexOperation->getRangePattern();
                 size_t length = pattern.first.size();
                 bool foundRealIndexableOperation = false;
                 for (size_t i = 0; i < length; ++i) {
                     // if both bounds are undefined we don't have a box query
                     if (isRamUndefValue(pattern.first[i]) && isRamUndefValue(pattern.second[i])) {
                         continue;
                     }
                     // if lower and upper bounds are equal its also not a box query
                     if (*(pattern.first[i]) == *(pattern.second[i])) {
                         foundRealIndexableOperation = true;
                         break;
                     }
                 }
                 if (!foundRealIndexableOperation) {
                     // need to rewrite the node with a semantically equivalent operation to get rid of the
                     // index operation i.e. RamIndexScan with no indexable attributes -> RamScan
                     if (const RamIndexScan* iscan = dynamic_cast<RamIndexScan*>(node.get())) {
                         node = std::make_unique<RamScan>(
                                 std::make_unique<RamRelationReference>(&iscan->getRelation()),
                                 iscan->getTupleId(), souffle::clone(&iscan->getOperation()),
                                 iscan->getProfileText());
                     } else if (const RamParallelIndexScan* pscan =
                                        dynamic_cast<RamParallelIndexScan*>(node.get())) {
                         node = std::make_unique<RamParallelScan>(
                                 std::make_unique<RamRelationReference>(&pscan->getRelation()),
                                 pscan->getTupleId(), souffle::clone(&pscan->getOperation()),
                                 pscan->getProfileText());
                     } else if (const RamIndexChoice* ichoice = dynamic_cast<RamIndexChoice*>(node.get())) {
                         node = std::make_unique<RamChoice>(
                                 std::make_unique<RamRelationReference>(&ichoice->getRelation()),
                                 ichoice->getTupleId(), souffle::clone(&ichoice->getCondition()),
                                 souffle::clone(&ichoice->getOperation()), ichoice->getProfileText());
                     } else if (const RamIndexAggregate* iagg = dynamic_cast<RamIndexAggregate*>(node.get())) {
                         node = std::make_unique<RamAggregate>(souffle::clone(&iagg->getOperation()),
                                 iagg->getFunction(),
                                 std::make_unique<RamRelationReference>(&iagg->getRelation()),
                                 souffle::clone(&iagg->getExpression()), souffle::clone(&iagg->getCondition()),
                                 iagg->getTupleId());
                     } else {
                         fatal("New RamIndexOperation subclass found but not supported while transforming "
                               "index.");
                     }
                 }
             }
             node->apply(makeLambdaRamMapper(removeEmptyIndexRewriter));
             return node;
         };
         const_cast<RamQuery*>(&query)->apply(makeLambdaRamMapper(removeEmptyIndexRewriter));
     });
     return changed;
 }
Field Documentation
idxAnalysis
RamIndexAnalysis* souffle::IndexedInequalityTransformer::idxAnalysis protected
Definition at line 89 of file IndexedInequality.h.
Referenced by transform(), and transformIndexToFilter().
The documentation for this class was generated from the following files:
ram/transform/IndexedInequality.h
ram/transform/IndexedInequality.cpp