souffle: souffle::ReadStreamJSON Class Reference
souffle::ReadStreamJSON Class Reference
#include <ReadStreamJSON.h>
Public Member Functions
ReadStreamJSON (std::istream &file, const std::map< std::string, std::string > &rwOperation, SymbolTable &symbolTable, RecordTable &recordTable)
Public Member Functions inherited from souffle::ReadStream
template<typename T >
void readAll (T &relation)
Public Member Functions inherited from souffle::SerialisationStream< false >
virtual ~SerialisationStream ()=default
Protected Member Functions
RamDomain readNextElementList (const Json &source, const std::string &recordTypeName)
RamDomain readNextElementObject (const Json &source, const std::string &recordTypeName)
std::unique_ptr< RamDomain[]> readNextTuple () override
std::unique_ptr< RamDomain[]> readNextTupleList ()
std::unique_ptr< RamDomain[]> readNextTupleObject ()
Protected Member Functions inherited from souffle::ReadStream
void consumeChar (const std::string &str, char c, size_t &pos)
Read past given character, consuming any preceding whitespace.
void consumeWhiteSpace (const std::string &str, size_t &pos)
Advance position in the string until first non-whitespace character.
RamDomain readRecord (const std::string &source, const std::string &recordTypeName, size_t pos=0, size_t *charactersRead=nullptr)
Read a record from a string.
ReadStream (const std::map< std::string, std::string > &rwOperation, SymbolTable &symTab, RecordTable &recTab)
RamDomain readStringInRecord (const std::string &source, const size_t pos, size_t *charactersRead)
Protected Member Functions inherited from souffle::SerialisationStream< false >
SerialisationStream (RO< SymbolTable > &symTab, RO< RecordTable > &recTab, Json types, std::vector< std::string > relTypes, size_t auxArity=0)
SerialisationStream (RO< SymbolTable > &symTab, RO< RecordTable > &recTab, Json types)
SerialisationStream (RO< SymbolTable > &symTab, RO< RecordTable > &recTab, const std::map< std::string, std::string > &rwOperation)
Protected Attributes
std::istream & file
bool isInitialized
Json jsonSource
std::map< const std::string, const size_t > paramIndex
Json params
size_t pos
bool useObjects
Protected Attributes inherited from souffle::SerialisationStream< false >
size_t arity
size_t auxiliaryArity
RO< RecordTable > & recordTable
RO< SymbolTable > & symbolTable
std::vector< std::string > typeAttributes
Json types
Additional Inherited Members
Protected Types inherited from souffle::SerialisationStream< false >
using RO = std::conditional_t< readOnlyTables, const A, A >
Detailed Description
Definition at line 42 of file ReadStreamJSON.h.
Constructor & Destructor Documentation
ReadStreamJSON()
souffle::ReadStreamJSON::ReadStreamJSON (std::istream & file, const std::map< std::string, std::string > & rwOperation, SymbolTable & symbolTable, RecordTable & recordTable) inline
Definition at line 44 of file ReadStreamJSON.h.
References err, souffle::fatal(), params, and json11::Json::parse().
             : ReadStream(rwOperation, symbolTable, recordTable), file(file), pos(0), isInitialized(false) {
         std::string err;
         params = Json::parse(rwOperation.at("params"), err);
         if (err.length() > 0) {
             fatal("cannot get internal params: %s", err);
         }
     }
Member Function Documentation
readNextElementList()
RamDomain souffle::ReadStreamJSON::readNextElementList (const Json & source, const std::string & recordTypeName) inline protected
Definition at line 149 of file ReadStreamJSON.h.
References souffle::fatal(), i, json11::Json::int_value(), json11::Json::is_array(), json11::Json::is_null(), json11::Json::number_value(), souffle::SerialisationStream< false >::recordTable, souffle::SerialisationStream< false >::symbolTable, and souffle::SerialisationStream< false >::types.
Referenced by readNextTupleList().
{
         auto&& recordInfo = types["records"][recordTypeName];
         if (recordInfo.is_null()) {
             throw std::invalid_argument("Missing record type information: " + recordTypeName);
         }
         // Handle null case
         if (source.is_null()) {
             return 0;
         }
         assert(source.is_array() && "the input is not json array");
         auto&& recordTypes = recordInfo["types"];
         const size_t recordArity = recordInfo["arity"].long_value();
         std::vector<RamDomain> recordValues(recordArity);
         for (size_t i = 0; i < recordArity; ++i) {
             const std::string& recordType = recordTypes[i].string_value();
             switch (recordType[0]) {
                 case 's': {
                     recordValues[i] = symbolTable.unsafeLookup(source[i].string_value());
                     break;
                 }
                 case 'r': {
                     recordValues[i] = readNextElementList(source[i], recordType);
                     break;
                 }
                 case 'i': {
                     recordValues[i] = source[i].int_value();
                     break;
                 }
                 case 'u': {
                     recordValues[i] = source[i].int_value();
                     break;
                 }
                 case 'f': {
                     recordValues[i] = source[i].number_value();
                     break;
                 }
                 default: fatal("invalid type attribute");
             }
         }
         return recordTable.pack(recordValues.data(), recordValues.size());
     }
readNextElementObject()
RamDomain souffle::ReadStreamJSON::readNextElementObject (const Json & source, const std::string & recordTypeName) inline protected
Definition at line 245 of file ReadStreamJSON.h.
References souffle::fatal(), i, json11::Json::is_null(), json11::Json::is_object(), json11::Json::object_items(), souffle::SerialisationStream< false >::recordTable, souffle::SerialisationStream< false >::symbolTable, and souffle::SerialisationStream< false >::types.
Referenced by readNextTupleObject().
{
         auto&& recordInfo = types["records"][recordTypeName];
         const std::string recordName = recordTypeName.substr(2);
         std::map<const std::string, const size_t> recordIndex;
         size_t index_pos = 0;
         for (auto param : params["records"][recordName]["params"].array_items()) {
             recordIndex.insert(std::make_pair(param.string_value(), index_pos));
             index_pos++;
         }
         if (recordInfo.is_null()) {
             throw std::invalid_argument("Missing record type information: " + recordTypeName);
         }
         // Handle null case
         if (source.is_null()) {
             return 0;
         }
         assert(source.is_object() && "the input is not json object");
         auto&& recordTypes = recordInfo["types"];
         const size_t recordArity = recordInfo["arity"].long_value();
         std::vector<RamDomain> recordValues(recordArity);
         recordValues.reserve(recordIndex.size());
         for (auto readParam : source.object_items()) {
             // get the corresponding position by parameter name
             if (recordIndex.find(readParam.first) == recordIndex.end()) {
                 fatal("invalid parameter: %s", readParam.first);
             }
             size_t i = recordIndex.at(readParam.first);
             auto&& type = recordTypes[i].string_value();
             switch (type[0]) {
                 case 's': {
                     recordValues[i] = symbolTable.unsafeLookup(readParam.second.string_value());
                     break;
                 }
                 case 'r': {
                     recordValues[i] = readNextElementObject(readParam.second, type);
                     break;
                 }
                 case 'i': {
                     recordValues[i] = readParam.second.int_value();
                     break;
                 }
                 case 'u': {
                     recordValues[i] = readParam.second.int_value();
                     break;
                 }
                 case 'f': {
                     recordValues[i] = readParam.second.number_value();
                     break;
                 }
                 default: fatal("invalid type attribute: `%c`", type[0]);
             }
         }
         return recordTable.pack(recordValues.data(), recordValues.size());
     }
readNextTuple()
std::unique_ptr<RamDomain[]> souffle::ReadStreamJSON::readNextTuple () inline override protected virtual
Implements souffle::ReadStream.
Definition at line 63 of file ReadStreamJSON.h.
References souffle::fatal(), json11::Json::parse(), readNextTupleList(), and readNextTupleObject().
{
         // for some reasons we cannot initalized our json objects in constructor
         // otherwise it will segfault, so we initialize in the first call
         if (!isInitialized) {
             isInitialized = true;
             std::string error = "";
             std::string source(std::istreambuf_iterator<char>(file), {});
             jsonSource = Json::parse(source, error);
             // it should be wrapped by an extra array
             if (error.length() > 0 || !jsonSource.is_array()) {
                 fatal("cannot deserialize json because %s:\n%s", error, source);
             }
             // we only check the first one, since there are extra checks
             // in readNextTupleObject/readNextTupleList
             if (jsonSource[0].is_array()) {
                 useObjects = false;
             } else if (jsonSource[0].is_object()) {
                 useObjects = true;
                 size_t index_pos = 0;
                 for (auto param : params["relation"]["params"].array_items()) {
                     paramIndex.insert(std::make_pair(param.string_value(), index_pos));
                     index_pos++;
                 }
             } else {
                 fatal("the input is neither list nor object format");
             }
         }
         if (useObjects) {
             return readNextTupleObject();
         } else {
             return readNextTupleList();
         }
     }
readNextTupleList()
std::unique_ptr<RamDomain[]> souffle::ReadStreamJSON::readNextTupleList () inline protected
Definition at line 100 of file ReadStreamJSON.h.
References json11::Json::array_items(), souffle::fatal(), i, pos, readNextElementList(), souffle::SerialisationStream< false >::symbolTable, and souffle::SerialisationStream< false >::typeAttributes.
Referenced by readNextTuple().
{
         if (pos >= jsonSource.array_items().size()) {
             return nullptr;
         }
         std::unique_ptr<RamDomain[]> tuple = std::make_unique<RamDomain[]>(typeAttributes.size());
         const Json& jsonObj = jsonSource[pos];
         assert(jsonObj.is_array() && "the input is not json array");
         pos++;
         for (size_t i = 0; i < typeAttributes.size(); ++i) {
             try {
                 auto&& ty = typeAttributes.at(i);
                 switch (ty[0]) {
                     case 's': {
                         tuple[i] = symbolTable.unsafeLookup(jsonObj[i].string_value());
                         break;
                     }
                     case 'r': {
                         tuple[i] = readNextElementList(jsonObj[i], ty);
                         break;
                     }
                     case 'i': {
                         tuple[i] = jsonObj[i].int_value();
                         break;
                     }
                     case 'u': {
                         tuple[i] = jsonObj[i].int_value();
                         break;
                     }
                     case 'f': {
                         tuple[i] = jsonObj[i].number_value();
                         break;
                     }
                     default: fatal("invalid type attribute: `%c`", ty[0]);
                 }
             } catch (...) {
                 std::stringstream errorMessage;
                 if (jsonObj.is_array() && i < jsonObj.array_items().size()) {
                     errorMessage << "Error converting: " << jsonObj[i].dump();
                 } else {
                     errorMessage << "Invalid index: " << i;
                 }
                 throw std::invalid_argument(errorMessage.str());
             }
         }
         return tuple;
     }
readNextTupleObject()
std::unique_ptr<RamDomain[]> souffle::ReadStreamJSON::readNextTupleObject () inline protected
Definition at line 195 of file ReadStreamJSON.h.
References json11::Json::array_items(), souffle::fatal(), i, p, pos, readNextElementObject(), souffle::SerialisationStream< false >::symbolTable, and souffle::SerialisationStream< false >::typeAttributes.
Referenced by readNextTuple().
{
         if (pos >= jsonSource.array_items().size()) {
             return nullptr;
         }
         std::unique_ptr<RamDomain[]> tuple = std::make_unique<RamDomain[]>(typeAttributes.size());
         const Json& jsonObj = jsonSource[pos];
         assert(jsonObj.is_object() && "the input is not json object");
         pos++;
         for (auto p : jsonObj.object_items()) {
             try {
                 // get the corresponding position by parameter name
                 if (paramIndex.find(p.first) == paramIndex.end()) {
                     fatal("invalid parameter: %s", p.first);
                 }
                 size_t i = paramIndex.at(p.first);
                 auto&& ty = typeAttributes.at(i);
                 switch (ty[0]) {
                     case 's': {
                         tuple[i] = symbolTable.unsafeLookup(p.second.string_value());
                         break;
                     }
                     case 'r': {
                         tuple[i] = readNextElementObject(p.second, ty);
                         break;
                     }
                     case 'i': {
                         tuple[i] = p.second.int_value();
                         break;
                     }
                     case 'u': {
                         tuple[i] = p.second.int_value();
                         break;
                     }
                     case 'f': {
                         tuple[i] = p.second.number_value();
                         break;
                     }
                     default: fatal("invalid type attribute: `%c`", ty[0]);
                 }
             } catch (...) {
                 std::stringstream errorMessage;
                 errorMessage << "Error converting: " << p.second.dump();
                 throw std::invalid_argument(errorMessage.str());
             }
         }
         return tuple;
     }
Field Documentation
file
std::istream& souffle::ReadStreamJSON::file protected
Definition at line 55 of file ReadStreamJSON.h.
isInitialized
bool souffle::ReadStreamJSON::isInitialized protected
Definition at line 59 of file ReadStreamJSON.h.
jsonSource
Json souffle::ReadStreamJSON::jsonSource protected
Definition at line 57 of file ReadStreamJSON.h.
paramIndex
std::map<const std::string, const size_t> souffle::ReadStreamJSON::paramIndex protected
Definition at line 61 of file ReadStreamJSON.h.
params
Json souffle::ReadStreamJSON::params protected
Definition at line 58 of file ReadStreamJSON.h.
Referenced by ReadStreamJSON().
pos
size_t souffle::ReadStreamJSON::pos protected
Definition at line 56 of file ReadStreamJSON.h.
Referenced by readNextTupleList(), and readNextTupleObject().
useObjects
bool souffle::ReadStreamJSON::useObjects protected
Definition at line 60 of file ReadStreamJSON.h.
The documentation for this class was generated from the following file:
ReadStreamJSON.h