souffle: souffle::RamRelationReference Class Reference
souffle::RamRelationReference Class Reference
A RAM Relation in the RAM intermediate representation.
#include <Relation.h>
Public Member Functions
RamRelationReference * clone () const override
Create a clone (i.e.
const RamRelation * get () const
Get reference.
RamRelationReference (const RamRelation *relation)
Public Member Functions inherited from souffle::RamNode
virtual void apply (const RamNodeMapper &)
Apply the mapper to all child nodes.
virtual std::vector< const RamNode * > getChildNodes () const
Obtain list of all embedded child nodes.
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
virtual void rewrite (const RamNode *oldNode, std::unique_ptr< RamNode > newNode)
Rewrite a child node.
virtual ~RamNode ()=default
Protected Member Functions
bool equal (const RamNode &node) const override
Equality check for two RAM nodes.
void print (std::ostream &out) const override
Print RAM node.
Protected Attributes
const RamRelation * relation
Name of relation.
Detailed Description
A RAM Relation in the RAM intermediate representation.
Definition at line 151 of file Relation.h.
Constructor & Destructor Documentation
RamRelationReference()
souffle::RamRelationReference::RamRelationReference (const RamRelation * relation) inline
Definition at line 153 of file Relation.h.
                                                       : relation(relation) {
         assert(relation != nullptr && "null relation");
     }
Member Function Documentation
clone()
RamRelationReference* souffle::RamRelationReference::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::RamNode.
Definition at line 162 of file Relation.h.
References relation.
Referenced by souffle::test::TEST().
{
         return new RamRelationReference(relation);
     }
equal()
bool souffle::RamRelationReference::equal (const RamNode &) const inline override protected virtual
Equality check for two RAM nodes.
Default action is that nothing needs to be checked.
Reimplemented from souffle::RamNode.
Definition at line 171 of file Relation.h.
References souffle::equal_ptr(), and relation.
{
         const auto& other = static_cast<const RamRelationReference&>(node);
         return equal_ptr(relation, other.relation);
     }
get()
const RamRelation* souffle::RamRelationReference::get () const inline
Get reference.
Definition at line 158 of file Relation.h.
References relation.
Referenced by souffle::AstToRamTranslator::translateRecursiveRelation().
{
         return relation;
     }
print()
void souffle::RamRelationReference::print (std::ostream & out) const inline override protected virtual
Print RAM node.
Implements souffle::RamNode.
Definition at line 167 of file Relation.h.
References relation.
{
         out << relation->getName();
     }
Field Documentation
relation
const RamRelation* souffle::RamRelationReference::relation protected
Name of relation.
Definition at line 178 of file Relation.h.
The documentation for this class was generated from the following file:
ram/Relation.h