souffle: souffle::AstRecordType Class Reference
souffle::AstRecordType Class Reference
A record type aggregates a list of fields into a new type.
#include <RecordType.h>
Public Member Functions
void add (std::string name, AstQualifiedName type)
add field to record type
AstRecordType (AstQualifiedName name, VecOwn< AstAttribute > fields, SrcLocation loc={})
AstRecordType * clone () const override
Create a clone (i.e.
std::vector< AstAttribute * > getFields () const
get fields of record
void setFieldType (size_t idx, AstQualifiedName type)
set field type
Public Member Functions inherited from souffle::AstType
AstType (AstQualifiedName name={}, SrcLocation loc={})
const AstQualifiedName & getQualifiedName () const
get type name
void setQualifiedName (AstQualifiedName name)
set type name
Public Member Functions inherited from souffle::AstNode
virtual void apply (const AstNodeMapper &)
Apply the mapper to all child nodes.
AstNode (SrcLocation loc={})
std::string extloc () const
Return source location of the syntactic element.
virtual std::vector< const AstNode * > getChildNodes () const
Obtain a list of all embedded AST child nodes.
const SrcLocation & getSrcLoc () const
Return source location of the AstNode.
bool operator!= (const AstNode &other) const
Inequality check for two AST nodes.
bool operator== (const AstNode &other) const
Equivalence check for two AST nodes.
void setSrcLoc (SrcLocation l)
Set source location for the AstNode.
virtual ~AstNode ()=default
Protected Member Functions
bool equal (const AstNode &node) const override
Abstract equality check for two AST nodes.
void print (std::ostream &os) const override
Output to a given output stream.
Private Attributes
VecOwn< AstAttribute > fields
record fields
Detailed Description
A record type aggregates a list of fields into a new type.
Each record type has a name making it unique. Two record types are unrelated to all other types (they do not have any super or sub types).
Definition at line 42 of file RecordType.h.
Constructor & Destructor Documentation
AstRecordType()
souffle::AstRecordType::AstRecordType (AstQualifiedName name, VecOwn< AstAttribute > fields, SrcLocation loc = {}) inline
Definition at line 44 of file RecordType.h.
References souffle::AstType::AstType(), and fields.
Referenced by clone().
                                                                                         {})
             : AstType(std::move(name), std::move(loc)), fields(std::move(fields)) {}
Member Function Documentation
add()
void souffle::AstRecordType::add (std::string name, AstQualifiedName type) inline
add field to record type
Definition at line 48 of file RecordType.h.
{
         fields.push_back(mk<AstAttribute>(std::move(name), std::move(type)));
     }
clone()
AstRecordType* souffle::AstRecordType::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::AstType.
Definition at line 62 of file RecordType.h.
References AstRecordType(), souffle::clone(), souffle::AstType::getQualifiedName(), and souffle::AstNode::getSrcLoc().
{
         return new AstRecordType(getQualifiedName(), souffle::clone(fields), getSrcLoc());
     }
equal()
bool souffle::AstRecordType::equal (const AstNode &) const inline override protected virtual
Abstract equality check for two AST nodes.
Reimplemented from souffle::AstNode.
Definition at line 71 of file RecordType.h.
References souffle::equal_targets(), and souffle::AstType::getQualifiedName().
{
         const auto& other = dynamic_cast<const AstRecordType&>(node);
         return getQualifiedName() == other.getQualifiedName() && equal_targets(fields, other.fields);
     }
getFields()
std::vector<AstAttribute*> souffle::AstRecordType::getFields () const inline
get fields of record
Definition at line 53 of file RecordType.h.
References souffle::toPtrVector().
Referenced by souffle::AstSemanticCheckerImpl::checkRecordType().
{
         return toPtrVector(fields);
     }
print()
void souffle::AstRecordType::print (std::ostream & os) const inline override protected virtual
Output to a given output stream.
Implements souffle::AstNode.
Definition at line 67 of file RecordType.h.
References souffle::AstType::getQualifiedName(), and souffle::join().
{
         os << ".type " << getQualifiedName() << "= [" << join(fields, ", ") << "]";
     }
setFieldType()
void souffle::AstRecordType::setFieldType (size_t idx, AstQualifiedName type) inline
set field type
Definition at line 58 of file RecordType.h.
{
         fields.at(idx)->setTypeName(std::move(type));
     }
Field Documentation
fields
VecOwn<AstAttribute> souffle::AstRecordType::fields private
record fields
Definition at line 78 of file RecordType.h.
Referenced by AstRecordType().
The documentation for this class was generated from the following file:
ast/RecordType.h