souffle: souffle::CmdOptions Class Reference
souffle::CmdOptions Class Reference
A utility class for parsing command line arguments within generated query programs.
#include <CompiledOptions.h>
Public Member Functions
CmdOptions (const char *s, const char *id, const char *od, bool pe, const char *pfn, size_t nj)
const std::string & getInputFileDir () const
get input directory
size_t getNumJobs () const
get number of jobs
const std::string & getOutputFileDir () const
get output directory
const std::string & getProfileName () const
get filename of profile
const std::string & getSourceFileName () const
get source code name
bool isProfiling () const
is profiling switched on
bool parse (int argc, char **argv)
Parses the given command line parameters, handles -h help requests or errors and returns whether the parsing was successful or not.
Protected Attributes
std::string input_dir
fact directory
size_t num_jobs
number of threads
std::string output_dir
output directory
std::string profile_name
profile filename
bool profiling
profiling flag
std::string src
source file
Private Member Functions
bool existDir (const std::string &name) const
Check whether a directory exists in the file system.
bool existFile (const std::string &name) const
Check whether a file exists in the file system.
void printHelpPage (const std::string &exec_name) const
Prints the help page if it has been requested or there was a typo in the command line arguments.
Detailed Description
A utility class for parsing command line arguments within generated query programs.
Definition at line 33 of file CompiledOptions.h.
Constructor & Destructor Documentation
CmdOptions()
souffle::CmdOptions::CmdOptions (const char * s, const char * id, const char * od, bool pe, const char * pfn, size_t nj) inline
Definition at line 67 of file CompiledOptions.h.
             : src(s), input_dir(id), output_dir(od), profiling(pe), profile_name(pfn), num_jobs(nj) {}
Member Function Documentation
existDir()
bool souffle::CmdOptions::existDir (const std::string & name) const inline private
Check whether a directory exists in the file system.
Definition at line 246 of file CompiledOptions.h.
Referenced by parse().
{
         struct stat buffer;
         if (stat(name.c_str(), &buffer) == 0) {
             if ((buffer.st_mode & S_IFDIR) != 0) {
                 return true;
             }
         }
         return false;
     }
existFile()
bool souffle::CmdOptions::existFile (const std::string & name) const inline private
Check whether a file exists in the file system.
Definition at line 233 of file CompiledOptions.h.
{
         struct stat buffer;
         if (stat(name.c_str(), &buffer) == 0) {
             if ((buffer.st_mode & S_IFREG) != 0) {
                 return true;
             }
         }
         return false;
     }
getInputFileDir()
const std::string& souffle::CmdOptions::getInputFileDir () const inline
get input directory
Definition at line 80 of file CompiledOptions.h.
References input_dir.
{
         return input_dir;
     }
getNumJobs()
size_t souffle::CmdOptions::getNumJobs () const inline
get number of jobs
Definition at line 108 of file CompiledOptions.h.
References num_jobs.
{
         return num_jobs;
     }
getOutputFileDir()
const std::string& souffle::CmdOptions::getOutputFileDir () const inline
get output directory
Definition at line 87 of file CompiledOptions.h.
References output_dir.
{
         return output_dir;
     }
getProfileName()
const std::string& souffle::CmdOptions::getProfileName () const inline
get filename of profile
Definition at line 101 of file CompiledOptions.h.
References profile_name.
{
         return profile_name;
     }
getSourceFileName()
const std::string& souffle::CmdOptions::getSourceFileName () const inline
get source code name
Definition at line 73 of file CompiledOptions.h.
References src.
{
         return src;
     }
isProfiling()
bool souffle::CmdOptions::isProfiling () const inline
is profiling switched on
Definition at line 94 of file CompiledOptions.h.
References profiling.
{
         return profiling;
     }
parse()
bool souffle::CmdOptions::parse (int argc, char ** argv) inline
Parses the given command line parameters, handles -h help requests or errors and returns whether the parsing was successful or not.
Definition at line 116 of file CompiledOptions.h.
References existDir(), input_dir, output_dir, tinyformat::printf(), and printHelpPage().
{
         // get executable name
         std::string exec_name = "analysis";
         if (argc > 0) {
             exec_name = argv[0];
         }
         // local options
         std::string fact_dir = input_dir;
         std::string out_dir = output_dir;
 // avoid warning due to Solaris getopt.h
 #pragma GCC diagnostic push
 #pragma GCC diagnostic ignored "-Wwrite-strings"
         // long options
         option longOptions[] = {{"facts", true, nullptr, 'F'}, {"output", true, nullptr, 'D'},
                 {"profile", true, nullptr, 'p'}, {"jobs", true, nullptr, 'j'}, {"index", true, nullptr, 'i'},
                 // the terminal option -- needs to be null
                 {nullptr, false, nullptr, 0}};
 #pragma GCC diagnostic pop
         // check whether all options are fine
         bool ok = true;
         int c; /* command-line arguments processing */
         while ((c = getopt_long(argc, argv, "D:F:hp:j:i:", longOptions, nullptr)) != EOF) {
             switch (c) {
                 /* Fact directories */
                 case 'F':
                     if (!existDir(optarg)) {
                         printf("Fact directory %s does not exists!\n", optarg);
                         ok = false;
                     }
                     fact_dir = optarg;
                     break;
                 /* Output directory for resulting .csv files */
                 case 'D':
                     if (*optarg && !existDir(optarg)) {
                         printf("Output directory %s does not exists!\n", optarg);
                         ok = false;
                     }
                     out_dir = optarg;
                     break;
                 case 'p':
                     if (!profiling) {
                         std::cerr << "\nError: profiling was not enabled in compilation\n\n";
                         printHelpPage(exec_name);
                         exit(EXIT_FAILURE);
                     }
                     profile_name = optarg;
                     break;
                 case 'j':
 #ifdef _OPENMP
                     if (std::string(optarg) == "auto") {
                         num_jobs = 0;
                     } else {
                         int num = atoi(optarg);
                         if (num > 0) {
                             num_jobs = num;
                         } else {
                             std::cerr << "Invalid number of jobs [-j]: " << optarg << "\n";
                             ok = false;
                         }
                     }
 #else
                     std::cerr << "\nWarning: OpenMP was not enabled in compilation\n\n";
 #endif
                     break;
                 default: printHelpPage(exec_name); return false;
             }
         }
         // update member fields
         input_dir = fact_dir;
         output_dir = out_dir;
         // return success state
         return ok;
     }
printHelpPage()
void souffle::CmdOptions::printHelpPage (const std::string & exec_name) const inline private
Prints the help page if it has been requested or there was a typo in the command line arguments.
Definition at line 200 of file CompiledOptions.h.
Referenced by parse().
{
         std::cerr << "====================================================================\n";
         std::cerr << " Datalog Program: " << src << "\n";
         std::cerr << " Usage: " << exec_name << " [OPTION]\n\n";
         std::cerr << " Options:\n";
         std::cerr << "    -D <DIR>, --output=<DIR>     -- Specify directory for output relations\n";
         std::cerr << "                                    (default: " << output_dir << ")\n";
         std::cerr << "                                    (suppress output with \"\")\n";
         std::cerr << "    -F <DIR>, --facts=<DIR>      -- Specify directory for fact files\n";
         std::cerr << "                                    (default: " << input_dir << ")\n";
         if (profiling) {
             std::cerr << "    -p <file>, --profile=<file>  -- Specify filename for profiling\n";
             std::cerr << "                                    (default: " << profile_name << ")\n";
         }
 #ifdef _OPENMP
         std::cerr << "    -j <NUM>, --jobs=<NUM>       -- Specify number of threads\n";
         if (num_jobs > 0) {
             std::cerr << "                                    (default: " << num_jobs << ")\n";
         } else {
             std::cerr << "                                    (default: auto)\n";
         }
 #endif
         std::cerr << "    -h                           -- prints this help page.\n";
         std::cerr << "--------------------------------------------------------------------\n";
         std::cout << " Copyright (c) 2016-20 The Souffle Developers." << std::endl;
         std::cout << " Copyright (c) 2013-16 Oracle and/or its affiliates." << std::endl;
         std::cerr << " All rights reserved.\n";
         std::cerr << "====================================================================\n";
     }
Field Documentation
input_dir
std::string souffle::CmdOptions::input_dir protected
fact directory
Definition at line 43 of file CompiledOptions.h.
Referenced by getInputFileDir(), and parse().
num_jobs
size_t souffle::CmdOptions::num_jobs protected
number of threads
Definition at line 63 of file CompiledOptions.h.
Referenced by getNumJobs().
output_dir
std::string souffle::CmdOptions::output_dir protected
output directory
Definition at line 48 of file CompiledOptions.h.
Referenced by getOutputFileDir(), and parse().
profile_name
std::string souffle::CmdOptions::profile_name protected
profile filename
Definition at line 58 of file CompiledOptions.h.
Referenced by getProfileName().
profiling
bool souffle::CmdOptions::profiling protected
profiling flag
Definition at line 53 of file CompiledOptions.h.
Referenced by isProfiling().
src
std::string souffle::CmdOptions::src protected
source file
Definition at line 38 of file CompiledOptions.h.
Referenced by getSourceFileName().
The documentation for this class was generated from the following file:
CompiledOptions.h