souffle: souffle::profile::Cell< T > Class Template Reference
souffle::profile::Cell< T > Class Template Reference
#include <Cell.h>
Public Member Functions
Cell (T value)
~Cell () override=default
Public Member Functions inherited from souffle::profile::CellInterface
virtual double getDoubleVal () const =0
virtual long getLongVal () const =0
virtual std::string getStringVal () const =0
virtual std::chrono::microseconds getTimeVal () const =0
virtual std::string toString (int precision) const =0
virtual ~CellInterface ()=default
Private Attributes
const T value
Detailed Description
template<typename T>
class souffle::profile::Cell< T >
Definition at line 23 of file Cell.h.
Constructor & Destructor Documentation
Cell()
template<typename T > souffle::profile::Cell< T >::Cell (T value) inline
Definition at line 27 of file Cell.h.
References souffle::profile::Cell< T >::~Cell().
Referenced by souffle::profile::Cell< double >::toString().
 : value(value){};
~Cell()
template<typename T > souffle::profile::Cell< T >::~Cell () override default
Referenced by souffle::profile::Cell< T >::Cell().
Field Documentation
value
template<typename T > const T souffle::profile::Cell< T >::value private
Definition at line 24 of file Cell.h.
Referenced by souffle::profile::Cell< double >::getDoubleVal(), souffle::profile::Cell< long >::getLongVal(), souffle::profile::Cell< std::chrono::microseconds >::getTimeVal(), and souffle::profile::Cell< double >::toString().
The documentation for this class was generated from the following file:
profile/Cell.h