souffle: souffle::AstAnalysis Class Reference
souffle::AstAnalysis Class Reference abstract
Abstract class for a AST Analysis.
#include <Analysis.h>
Public Member Functions
AstAnalysis (std::string identifier)
virtual const std::string & getName () const
get name of the analysis
virtual void print (std::ostream &) const
print the analysis result in HTML format
virtual void run (const AstTranslationUnit &)=0
run analysis for a Ast translation unit
virtual ~AstAnalysis ()=default
Protected Attributes
const std::string identifier
Friends
std::ostream & operator<< (std::ostream &out, const AstAnalysis &other)
define output stream operator
Detailed Description
Abstract class for a AST Analysis.
Definition at line 30 of file Analysis.h.
Constructor & Destructor Documentation
AstAnalysis()
souffle::AstAnalysis::AstAnalysis (std::string identifier) inline
Definition at line 32 of file Analysis.h.
References run(), and ~AstAnalysis().
 : identifier(std::move(identifier)) {}
~AstAnalysis()
virtual souffle::AstAnalysis::~AstAnalysis () virtual default
Referenced by AstAnalysis().
Member Function Documentation
getName()
virtual const std::string& souffle::AstAnalysis::getName () const inline virtual
get name of the analysis
Definition at line 42 of file Analysis.h.
References identifier.
Referenced by souffle::PrecedenceGraphAnalysis::print(), and souffle::SCCGraphAnalysis::print().
{
         return identifier;
     }
print()
virtual void souffle::AstAnalysis::print (std::ostream &) const inline virtual
print the analysis result in HTML format
Reimplemented in souffle::SCCGraphAnalysis, souffle::Adornment, souffle::RelationScheduleAnalysis, souffle::TopologicallySortedSCCGraphAnalysis, souffle::AstProfileUseAnalysis, souffle::RelationDetailCacheAnalysis, souffle::PrecedenceGraphAnalysis, souffle::RedundantRelationsAnalysis, souffle::RecursiveClausesAnalysis, souffle::TypeAnalysis, souffle::TypeEnvironmentAnalysis, and souffle::IOType.
Definition at line 39 of file Analysis.h.
 {}
run()
virtual void souffle::AstAnalysis::run (const AstTranslationUnit &) pure virtual
run analysis for a Ast translation unit
Implemented in souffle::Adornment, souffle::ComponentLookup, souffle::RelationScheduleAnalysis, souffle::SCCGraphAnalysis, souffle::TopologicallySortedSCCGraphAnalysis, souffle::RelationDetailCacheAnalysis, souffle::AstProfileUseAnalysis, souffle::RedundantRelationsAnalysis, souffle::PrecedenceGraphAnalysis, souffle::RecursiveClausesAnalysis, souffle::TypeAnalysis, souffle::AuxiliaryArity, souffle::TypeEnvironmentAnalysis, and souffle::IOType.
Referenced by AstAnalysis().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & out, const AstAnalysis & other) friend
define output stream operator
Definition at line 47 of file Analysis.h.
{
         other.print(out);
         return out;
     }
Field Documentation
identifier
const std::string souffle::AstAnalysis::identifier protected
Definition at line 53 of file Analysis.h.
Referenced by getName().
The documentation for this class was generated from the following file:
ast/analysis/Analysis.h