souffle: souffle::InterpreterContext Class Reference
souffle::InterpreterContext Class Reference
Evaluation context for Interpreter operations.
#include <InterpreterContext.h>
Public Member Functions
void addReturnValue (RamDomain val)
Add subroutine return value.
RamDomain * allocateNewTuple (size_t size)
Allocate a tuple.
void createView (const InterpreterRelation &rel, size_t indexPos, size_t viewPos)
Create a view in the environment.
RamDomain getArgument (size_t i) const
Get subroutine Arguments.
const std::vector< RamDomain > & getArguments () const
Get subroutine Arguments.
std::vector< RamDomain > & getReturnValues () const
Get subroutine return value.
ViewPtr & getView (size_t id)
Return a view.
InterpreterContext (size_t size=0)
InterpreterContext (InterpreterContext &ctxt)
This constructor is used when program enter a new scope.
const RamDomain *& operator[] (size_t index)
const RamDomain *const & operator[] (size_t index) const
void setArguments (const std::vector< RamDomain > &a)
Set subroutine Arguments.
void setReturnValues (std::vector< RamDomain > &retVals)
Set subroutine return value.
virtual ~InterpreterContext ()=default
Private Types
using ViewPtr = std::unique_ptr< IndexView >
Private Attributes
std::vector< std::unique_ptr< RamDomain[]> > allocatedDataContainer
Allocated data
const std::vector< RamDomain > * args = nullptr
Subroutine arguments.
std::vector< const RamDomain * > data
Run-time value.
std::vector< RamDomain > * returnValues = nullptr
Subroutine return value.
std::vector< std::unique_ptr< IndexView > > views
Views.
Detailed Description
Evaluation context for Interpreter operations.
Definition at line 33 of file InterpreterContext.h.
Member Typedef Documentation
ViewPtr
using souffle::InterpreterContext::ViewPtr = std::unique_ptr<IndexView> private
Definition at line 34 of file InterpreterContext.h.
Constructor & Destructor Documentation
InterpreterContext() [1/2]
souffle::InterpreterContext::InterpreterContext (size_t size = 0) inline
Definition at line 48 of file InterpreterContext.h.
 : data(size) {}
InterpreterContext() [2/2]
souffle::InterpreterContext::InterpreterContext (InterpreterContext & ctxt) inline
This constructor is used when program enter a new scope.
Only Subroutine value needs to be copied
Definition at line 52 of file InterpreterContext.h.
References ~InterpreterContext().
 : returnValues(ctxt.returnValues), args(ctxt.args) {}
~InterpreterContext()
virtual souffle::InterpreterContext::~InterpreterContext () virtual default
Referenced by InterpreterContext().
Member Function Documentation
addReturnValue()
void souffle::InterpreterContext::addReturnValue (RamDomain val) inline
Add subroutine return value.
Definition at line 87 of file InterpreterContext.h.
Referenced by souffle::InterpreterEngine::execute().
{
         assert(returnValues != nullptr);
         returnValues->push_back(val);
     }
allocateNewTuple()
RamDomain* souffle::InterpreterContext::allocateNewTuple (size_t size) inline
Allocate a tuple.
allocatedDataContainer has the ownership of those tuples.
Definition at line 68 of file InterpreterContext.h.
{
         std::unique_ptr<RamDomain[]> newTuple(new RamDomain[size]);
         allocatedDataContainer.push_back(std::move(newTuple));
         // Return the reference as raw pointer.
         return allocatedDataContainer.back().get();
     }
createView()
void souffle::InterpreterContext::createView (const InterpreterRelation & rel, size_t indexPos, size_t viewPos) inline
Create a view in the environment.
Definition at line 109 of file InterpreterContext.h.
References souffle::InterpreterRelation::getView().
Referenced by souffle::InterpreterEngine::execute().
{
         ViewPtr view;
         if (views.size() < viewPos + 1) {
             views.resize(viewPos + 1);
         }
         views[viewPos] = rel.getView(indexPos);
     }
getArgument()
RamDomain souffle::InterpreterContext::getArgument (size_t i) const inline
Get subroutine Arguments.
Definition at line 103 of file InterpreterContext.h.
References i.
Referenced by souffle::InterpreterEngine::execute().
{
         assert(args != nullptr && i < args->size() && "argument out of range");
         return (*args)[i];
     }
getArguments()
const std::vector<RamDomain>& souffle::InterpreterContext::getArguments () const inline
Get subroutine Arguments.
Definition at line 93 of file InterpreterContext.h.
References args.
{
         return *args;
     }
getReturnValues()
std::vector<RamDomain>& souffle::InterpreterContext::getReturnValues () const inline
Get subroutine return value.
Definition at line 77 of file InterpreterContext.h.
References returnValues.
{
         return *returnValues;
     }
getView()
ViewPtr& souffle::InterpreterContext::getView (size_t id) inline
Return a view.
Definition at line 118 of file InterpreterContext.h.
Referenced by souffle::InterpreterEngine::execute().
{
         assert(id < views.size());
         return views[id];
     }
operator[]() [1/2]
const RamDomain*& souffle::InterpreterContext::operator[] (size_t index) inline
Definition at line 55 of file InterpreterContext.h.
{
         if (index >= data.size()) {
             data.resize((index + 1));
         }
         return data[index];
     }
operator[]() [2/2]
const RamDomain* const& souffle::InterpreterContext::operator[] (size_t index) const inline
Definition at line 62 of file InterpreterContext.h.
{
         return data[index];
     }
setArguments()
void souffle::InterpreterContext::setArguments (const std::vector< RamDomain > & a) inline
Set subroutine Arguments.
Definition at line 98 of file InterpreterContext.h.
Referenced by souffle::InterpreterEngine::executeSubroutine().
{
         args = &a;
     }
setReturnValues()
void souffle::InterpreterContext::setReturnValues (std::vector< RamDomain > & retVals) inline
Set subroutine return value.
Definition at line 82 of file InterpreterContext.h.
Referenced by souffle::InterpreterEngine::executeSubroutine().
{
         returnValues = &retVals;
     }
Field Documentation
allocatedDataContainer
std::vector<std::unique_ptr<RamDomain[]> > souffle::InterpreterContext::allocatedDataContainer private
Allocated data
Definition at line 43 of file InterpreterContext.h.
args
const std::vector<RamDomain>* souffle::InterpreterContext::args = nullptr private
Subroutine arguments.
Definition at line 41 of file InterpreterContext.h.
Referenced by getArguments().
data
std::vector<const RamDomain*> souffle::InterpreterContext::data private
Run-time value.
Definition at line 37 of file InterpreterContext.h.
returnValues
std::vector<RamDomain>* souffle::InterpreterContext::returnValues = nullptr private
Subroutine return value.
Definition at line 39 of file InterpreterContext.h.
Referenced by getReturnValues().
views
std::vector<std::unique_ptr<IndexView> > souffle::InterpreterContext::views private
Views.
Definition at line 45 of file InterpreterContext.h.
The documentation for this class was generated from the following file:
interpreter/InterpreterContext.h