souffle: souffle::Relation Class Reference
souffle::Relation Class Reference abstract
Object-oriented wrapper class for Souffle's templatized relations.
#include <SouffleInterface.h>
Data Structures
class iterator
Wrapper class for abstract iterator.
class iterator_base
Abstract iterator class.
Public Member Functions
virtual iterator begin () const =0
Return an iterator pointing to the first tuple of the relation.
virtual bool contains (const tuple &t) const =0
Check whether a tuple exists in a relation.
virtual iterator end () const =0
Return an iterator pointing to next to the last tuple of the relation.
virtual size_t getArity () const =0
Return the arity of a relation.
virtual const char * getAttrName (size_t) const =0
Get the attribute name of a relation at the column specified by the parameter.
virtual const char * getAttrType (size_t) const =0
Get the attribute type of a relation at the column specified by the parameter.
virtual size_t getAuxiliaryArity () const =0
Return the number of auxiliary attributes.
virtual std::string getName () const =0
Get the name of a relation.
std::string getSignature ()
Get the signature of a relation.
virtual SymbolTable & getSymbolTable () const =0
Get the symbol table of a relation.
virtual void insert (const tuple &t)=0
Insert a new tuple into the relation.
virtual void purge ()=0
Delete all the tuples in relation.
virtual std::size_t size () const =0
Get the number of tuples in a relation.
virtual ~Relation ()=default
Destructor.
Detailed Description
Object-oriented wrapper class for Souffle's templatized relations.
Index.
Intermediate representation of a datalog relation.
A relation has a name, types of its arguments, qualifier type, and dependencies to other relations.
An abstract class for performing indexed operations
Definition at line 41 of file SouffleInterface.h.
Constructor & Destructor Documentation
~Relation()
virtual souffle::Relation::~Relation () virtual default
Destructor.
Referenced by souffle::Relation::iterator_base::operator==().
Member Function Documentation
begin()
virtual iterator souffle::Relation::begin () const pure virtual
Return an iterator pointing to the first tuple of the relation.
This iterator is used to access the tuples of the relation.
Returns
Iterator
Implemented in souffle::RelationWrapper< id, RelType, TupleType, Arity, NumAuxAttributes >, and souffle::InterpreterRelInterface.
Referenced by souffle::ExplainProvenanceImpl::containsTuple(), and souffle::Relation::iterator::operator!=().
contains()
virtual bool souffle::Relation::contains (const tuple & t) const pure virtual
Check whether a tuple exists in a relation.
The definition of contains has to be defined by the child class of relation class.
Parameters
t Reference to a tuple object
Returns
Boolean. True, if the tuple exists. False, otherwise
Implemented in souffle::RelationWrapper< id, RelType, TupleType, Arity, NumAuxAttributes >, and souffle::InterpreterRelInterface.
Referenced by souffle::SouffleProgram::contains(), and souffle::Relation::iterator::operator!=().
end()
virtual iterator souffle::Relation::end () const pure virtual
Return an iterator pointing to next to the last tuple of the relation.
Returns
Iterator
Implemented in souffle::RelationWrapper< id, RelType, TupleType, Arity, NumAuxAttributes >, and souffle::InterpreterRelInterface.
Referenced by souffle::ExplainProvenanceImpl::containsTuple(), and souffle::Relation::iterator::operator!=().
getArity()
virtual size_t souffle::Relation::getArity () const pure virtual
Return the arity of a relation.
For example for a tuple (1 2) the arity is 2 and for a tuple (1 2 3) the arity is 3.
Returns
Arity of a relation (size_t)
Implemented in souffle::RelationWrapper< id, RelType, TupleType, Arity, NumAuxAttributes >, and souffle::InterpreterRelInterface.
Referenced by souffle::ExplainProvenanceImpl::explain(), getSignature(), souffle::Relation::iterator::operator!=(), souffle::ExplainProvenanceImpl::queryProcess(), and souffle::tuple::tuple().
getAttrName()
virtual const char* souffle::Relation::getAttrName (size_t) const pure virtual
Get the attribute name of a relation at the column specified by the parameter.
The attribute name is the name given to the type by the user in the .decl statement. For example, for ".decl edge (node1:Node, node2:Node)", the attribute names are node1 and node2.
Parameters
The index of the column starting starting from 0 (size_t)
Returns
The constant string of the attribute name
Implemented in souffle::RelationWrapper< id, RelType, TupleType, Arity, NumAuxAttributes >, and souffle::InterpreterRelInterface.
Referenced by souffle::Relation::iterator::operator!=().
getAttrType()
virtual const char* souffle::Relation::getAttrType (size_t) const pure virtual
Get the attribute type of a relation at the column specified by the parameter.
The attribute type is in the form "<primitive type>:<type name>". <primitive type>=""> can be s, f, u, or i standing for symbol, float, unsigned, and integer respectively, which are the primitive types in Souffle. <type name>=""> is the name given by the user in the Souffle program
Parameters
The index of the column starting starting from 0 (size_t)
Returns
The constant string of the attribute type
Implemented in souffle::RelationWrapper< id, RelType, TupleType, Arity, NumAuxAttributes >, and souffle::InterpreterRelInterface.
Referenced by getSignature(), souffle::Relation::iterator::operator!=(), souffle::tuple::operator<<(), souffle::tuple::operator>>(), and souffle::ExplainProvenanceImpl::queryProcess().
getAuxiliaryArity()
virtual size_t souffle::Relation::getAuxiliaryArity () const pure virtual
Return the number of auxiliary attributes.
Auxiliary attributes are used for provenance and and other alternative evaluation strategies. They are stored as the last attributes of a tuple.
Returns
Number of auxiliary attributes of a relation (size_t)
Implemented in souffle::RelationWrapper< id, RelType, TupleType, Arity, NumAuxAttributes >, and souffle::InterpreterRelInterface.
Referenced by souffle::ExplainProvenanceImpl::explain(), souffle::Relation::iterator::operator!=(), and souffle::ExplainProvenanceImpl::queryProcess().
getName()
virtual std::string souffle::Relation::getName () const pure virtual
Get the name of a relation.
Returns
The name of a relation (std::string)
Implemented in souffle::RelationWrapper< id, RelType, TupleType, Arity, NumAuxAttributes >, and souffle::InterpreterRelInterface.
Referenced by souffle::Relation::iterator::operator!=().
getSignature()
std::string souffle::Relation::getSignature () inline
Get the signature of a relation.
The signature is in the form <<primitive type 1>:<type name 1>,<primitive type 2>:<type name 2>...> for all the attributes in a relation. For example, <s:Node,s:Node>. The primitive type and type name are explained in getAttrType.
Returns
String of the signature of a relation
Definition at line 370 of file SouffleInterface.h.
References getArity(), getAttrType(), i, and purge().
{
         if (getArity() == 0) {
             return "<>";
         }
         std::string signature = "<" + std::string(getAttrType(0));
         for (size_t i = 1; i < getArity(); i++) {
             signature += "," + std::string(getAttrType(i));
         }
         signature += ">";
         return signature;
     }
getSymbolTable()
virtual SymbolTable& souffle::Relation::getSymbolTable () const pure virtual
Get the symbol table of a relation.
The symbols in a tuple to be stored into a relation are stored and assigned with a number in a table called symbol table. For example, to insert ("John","Student") to a relation, "John" and "Student" are stored in symbol table and they are assigned with number say 0 and 1. After this, instead of inserting ("John","Student"), (0, 1) is inserted. When accessing this tuple, 0 and 1 will be looked up in the table and replaced by "John" and "Student". This is done so to save memory space if same symbols are inserted many times. Symbol table has many rows where each row contains a symbol and its corresponding assigned number.
Returns
Reference to a symbolTable object
Implemented in souffle::RelationWrapper< id, RelType, TupleType, Arity, NumAuxAttributes >, and souffle::InterpreterRelInterface.
Referenced by souffle::SouffleProgram::executeSubroutine(), souffle::Relation::iterator::operator!=(), souffle::tuple::operator<<(), and souffle::tuple::operator>>().
insert()
virtual void souffle::Relation::insert (const tuple & t) pure virtual
Insert a new tuple into the relation.
The definition of insert function has to be defined by the child class of relation class.
Parameters
t Reference to a tuple class object
Implemented in souffle::RelationWrapper< id, RelType, TupleType, Arity, NumAuxAttributes >, and souffle::InterpreterRelInterface.
Referenced by souffle::SouffleProgram::insert(), souffle::Relation::iterator::operator!=(), and souffle::ExplainProvenanceImpl::queryProcess().
purge()
virtual void souffle::Relation::purge () pure virtual
Delete all the tuples in relation.
When purge() is called, it sets the head and tail of the table (table is a singly-linked list structure) to nullptr, and for every elements in the table, set the next element pointer points to the current element itself.
Implemented in souffle::RelationWrapper< id, RelType, TupleType, Arity, NumAuxAttributes >, and souffle::InterpreterRelInterface.
Referenced by getSignature().
size()
virtual std::size_t souffle::Relation::size () const pure virtual
Get the number of tuples in a relation.
Returns
The number of tuples in a relation (std::size_t)
Implemented in souffle::RelationWrapper< id, RelType, TupleType, Arity, NumAuxAttributes >, and souffle::InterpreterRelInterface.
Referenced by souffle::ExplainProvenanceImpl::measureRelation(), souffle::Relation::iterator::operator!=(), souffle::tuple::operator<<(), and souffle::tuple::operator>>().
The documentation for this class was generated from the following file:
SouffleInterface.h