souffle: souffle::EquivalenceRelation< TupleType > Class Template Reference
souffle::EquivalenceRelation< TupleType > Class Template Reference
#include <EquivalenceRelation.h>
Data Structures
class iterator
struct operation_hints
A collection of operation hints speeding up some of the involved operations by exploiting temporal locality.
Public Types
using element_type = TupleType
Public Member Functions
iterator anteriorIt (value_type anteriorVal) const
Creates an iterator that generates all pairs (A, X) for a given A, and X are elements within A's disjoint set.
iterator antpostit (value_type anteriorVal, value_type posteriorVal) const
Creates an iterator that generates the pair (A, B) for a given A and B.
iterator begin () const
iterator pointing to the beginning of the tuples, with no restrictions
void clear ()
Empty the relation.
iterator closure (value_type rep) const
Begin an iterator over all pairs within a single disjoint set - This is used for partition().
bool contains (value_type x, value_type y) const
Returns whether there exists a pair with these two nodes.
bool contains (const TupleType &tuple, operation_hints &) const
Returns whether there exists given tuple.
bool empty () const
Check emptiness.
void emptyPartition () const
iterator end () const
iterator pointing to the end of the tuples
EquivalenceRelation ()
void extend (const EquivalenceRelation< TupleType > &other)
Extend this relation with another relation, expanding this equivalence relation The supplied relation is the old knowledge, whilst this relation only contains explicitly new knowledge.
iterator find (const TupleType &, operation_hints &) const
iterator find (const TupleType &t) const
template<unsigned levels>
range< iterator > getBoundaries (const TupleType &entry) const
Obtains a range of elements matching the prefix of the given entry up to levels elements.
template<unsigned levels>
range< iterator > getBoundaries (const TupleType &entry, operation_hints &) const
Obtains a range of elements matching the prefix of the given entry up to levels elements.
bool insert (value_type x, value_type y)
Insert the two values symbolically as a binary relation.
bool insert (const TupleType &tuple)
Insert the tuple symbolically.
bool insert (value_type x, value_type y, operation_hints)
Insert the two values symbolically as a binary relation.
void insertAll (const EquivalenceRelation< TupleType > &other)
inserts all nodes from the other relation into this one
iterator lower_bound (const TupleType &entry, operation_hints &) const
Act similar to getBoundaries.
std::vector< souffle::range< iterator > > partition (size_t chunks) const
Generate an approximate number of iterators for parallel iteration The iterators returned are not necessarily equal in size, but in practise are approximately similarly sized Depending on the structure of the data, there can be more or less partitions returned than requested.
size_t size () const
Size of relation.
iterator upper_bound (const TupleType &, operation_hints &) const
This function is only here in order to unify interfaces in InterpreterIndex.
~EquivalenceRelation ()
Protected Member Functions
bool containsElement (value_type e) const
Private Types
using StatesBucket = StatesList *
using StatesList = souffle::PiggyList< value_type >
using StatesMap = souffle::LambdaBTreeSet< StorePair, std::function< StatesBucket(StorePair &)>, souffle::EqrelMapComparator< StorePair > >
using StorePair = std::pair< value_type, StatesBucket >
using value_type = typename TupleType::value_type
Private Member Functions
void genAllDisjointSetLists () const
Generate a cache of the sets such that they can be iterated over efficiently.
Private Attributes
StatesMap equivalencePartition
souffle::SparseDisjointSet< value_type > sds
std::shared_mutex statesLock
std::atomic< bool > statesMapStale
Detailed Description
template<typename TupleType>
class souffle::EquivalenceRelation< TupleType >
Definition at line 42 of file EquivalenceRelation.h.
Member Typedef Documentation
element_type
template<typename TupleType> using souffle::EquivalenceRelation< TupleType >::element_type = TupleType
Definition at line 54 of file EquivalenceRelation.h.
StatesBucket
template<typename TupleType> using souffle::EquivalenceRelation< TupleType >::StatesBucket = StatesList* private
Definition at line 48 of file EquivalenceRelation.h.
StatesList
template<typename TupleType> using souffle::EquivalenceRelation< TupleType >::StatesList = souffle::PiggyList<value_type> private
Definition at line 47 of file EquivalenceRelation.h.
StatesMap
template<typename TupleType> using souffle::EquivalenceRelation< TupleType >::StatesMap = souffle::LambdaBTreeSet<StorePair, std::function<StatesBucket(StorePair&)>, souffle::EqrelMapComparator<StorePair> > private
Definition at line 51 of file EquivalenceRelation.h.
StorePair
template<typename TupleType> using souffle::EquivalenceRelation< TupleType >::StorePair = std::pair<value_type, StatesBucket> private
Definition at line 49 of file EquivalenceRelation.h.
value_type
template<typename TupleType> using souffle::EquivalenceRelation< TupleType >::value_type = typename TupleType::value_type private
Definition at line 43 of file EquivalenceRelation.h.
Constructor & Destructor Documentation
EquivalenceRelation()
template<typename TupleType> souffle::EquivalenceRelation< TupleType >::EquivalenceRelation () inline
Definition at line 56 of file EquivalenceRelation.h.
 : statesMapStale(false){};
~EquivalenceRelation()
template<typename TupleType> souffle::EquivalenceRelation< TupleType >::~EquivalenceRelation () inline
Definition at line 57 of file EquivalenceRelation.h.
{
         emptyPartition();
     }
Member Function Documentation
anteriorIt()
template<typename TupleType> iterator souffle::EquivalenceRelation< TupleType >::anteriorIt (value_type anteriorVal) const inline
Creates an iterator that generates all pairs (A, X) for a given A, and X are elements within A's disjoint set.
Parameters
anteriorVal The first value of the tuple to be generated for
Returns
the iterator representing this.
Definition at line 582 of file EquivalenceRelation.h.
Referenced by souffle::EquivalenceRelation< t_tuple< 2 > >::getBoundaries(), souffle::EquivalenceRelation< t_tuple< 2 > >::lower_bound(), and souffle::EquivalenceRelation< t_tuple< 2 > >::partition().
{
         genAllDisjointSetLists();
         // locate the blocklist that the anterior val resides in
         auto found = equivalencePartition.find({sds.findNode(anteriorVal), nullptr});
         assert(found != equivalencePartition.end() && "iterator called on partition that doesn't exist");
         return iterator(this, anteriorVal, (*found).second);
     }
antpostit()
template<typename TupleType> iterator souffle::EquivalenceRelation< TupleType >::antpostit (value_type anteriorVal, value_type posteriorVal) const inline
Creates an iterator that generates the pair (A, B) for a given A and B.
If A and B don't exist, or aren't in the same set, then the end() iterator is returned.
Parameters
anteriorVal the A value of the tuple
posteriorVal the B value of the tuple
Returns
the iterator representing this
Definition at line 600 of file EquivalenceRelation.h.
Referenced by souffle::EquivalenceRelation< t_tuple< 2 > >::getBoundaries(), and souffle::EquivalenceRelation< t_tuple< 2 > >::lower_bound().
{
         // obv if they're in diff sets, then iteration for this pair just ends.
         if (!sds.sameSet(anteriorVal, posteriorVal)) return end();
         genAllDisjointSetLists();
         // locate the blocklist that the val resides in
         auto found = equivalencePartition.find({sds.findNode(posteriorVal), nullptr});
         assert(found != equivalencePartition.end() && "iterator called on partition that doesn't exist");
         return iterator(this, anteriorVal, posteriorVal, (*found).second);
     }
begin()
template<typename TupleType> iterator souffle::EquivalenceRelation< TupleType >::begin () const inline
iterator pointing to the beginning of the tuples, with no restrictions
Returns
the iterator that corresponds to the beginning of the binary relation
Definition at line 453 of file EquivalenceRelation.h.
Referenced by souffle::EquivalenceRelation< t_tuple< 2 > >::find(), souffle::EquivalenceRelation< t_tuple< 2 > >::getBoundaries(), souffle::EquivalenceRelation< t_tuple< 2 > >::lower_bound(), souffle::EquivalenceRelation< t_tuple< 2 > >::partition(), and souffle::test::TEST().
{
         genAllDisjointSetLists();
         return iterator(this);
     }
clear()
template<typename TupleType> void souffle::EquivalenceRelation< TupleType >::clear () inline
Empty the relation.
Definition at line 209 of file EquivalenceRelation.h.
Referenced by souffle::test::TEST().
                  {
         statesLock.lock();
         sds.clear();
         emptyPartition();
         statesLock.unlock();
     }
closure()
template<typename TupleType> iterator souffle::EquivalenceRelation< TupleType >::closure (value_type rep) const inline
Begin an iterator over all pairs within a single disjoint set - This is used for partition().
Parameters
rep the representative of (or element within) a disjoint set of which to generate all pairs
Returns
an iterator that will generate all pairs within the disjoint set
Definition at line 618 of file EquivalenceRelation.h.
Referenced by souffle::EquivalenceRelation< t_tuple< 2 > >::partition().
{
         genAllDisjointSetLists();
         // locate the blocklist that the val resides in
         auto found = equivalencePartition.find({sds.findNode(rep), nullptr});
         return iterator(this, (*found).second);
     }
contains() [1/2]
template<typename TupleType> bool souffle::EquivalenceRelation< TupleType >::contains (value_type x, value_type y) const inline
Returns whether there exists a pair with these two nodes.
Parameters
x front of pair
y back of pair
Definition at line 183 of file EquivalenceRelation.h.
Referenced by souffle::EquivalenceRelation< t_tuple< 2 > >::contains(), souffle::EquivalenceRelation< t_tuple< 2 > >::insert(), and souffle::test::TEST().
{
         return sds.contains(x, y);
     }
contains() [2/2]
template<typename TupleType> bool souffle::EquivalenceRelation< TupleType >::contains (const TupleType & tuple, operation_hints &) const inline
Returns whether there exists given tuple.
Parameters
tuple The tuple to search for.
Definition at line 191 of file EquivalenceRelation.h.
{
         return contains(tuple[0], tuple[1]);
     };
containsElement()
template<typename TupleType> bool souffle::EquivalenceRelation< TupleType >::containsElement (value_type e) const inline protected
Definition at line 680 of file EquivalenceRelation.h.
Referenced by souffle::EquivalenceRelation< t_tuple< 2 > >::extend().
{
         return this->sds.nodeExists(e);
     }
empty()
template<typename TupleType> bool souffle::EquivalenceRelation< TupleType >::empty () const inline
Check emptiness.
Definition at line 572 of file EquivalenceRelation.h.
{
         return this->size() == 0;
     }
emptyPartition()
template<typename TupleType> void souffle::EquivalenceRelation< TupleType >::emptyPartition () const inline
Definition at line 195 of file EquivalenceRelation.h.
Referenced by souffle::EquivalenceRelation< t_tuple< 2 > >::clear(), souffle::EquivalenceRelation< t_tuple< 2 > >::genAllDisjointSetLists(), and souffle::EquivalenceRelation< t_tuple< 2 > >::~EquivalenceRelation().
{
         // delete the beautiful values inside (they're raw ptrs, so they need to be.)
         for (auto& pair : equivalencePartition) {
             delete pair.second;
         }
         // invalidate it my dude
         this->statesMapStale.store(true, std::memory_order_relaxed);
         equivalencePartition.clear();
     }
end()
template<typename TupleType> iterator souffle::EquivalenceRelation< TupleType >::end () const inline
iterator pointing to the end of the tuples
Returns
the iterator which represents the end of the binary rel
Definition at line 462 of file EquivalenceRelation.h.
Referenced by souffle::EquivalenceRelation< t_tuple< 2 > >::antpostit(), souffle::EquivalenceRelation< t_tuple< 2 > >::extend(), souffle::EquivalenceRelation< t_tuple< 2 > >::getBoundaries(), souffle::EquivalenceRelation< t_tuple< 2 > >::lower_bound(), souffle::EquivalenceRelation< t_tuple< 2 > >::partition(), souffle::test::TEST(), and souffle::EquivalenceRelation< t_tuple< 2 > >::upper_bound().
{
         return iterator(this, true);
     }
extend()
template<typename TupleType> void souffle::EquivalenceRelation< TupleType >::extend (const EquivalenceRelation< TupleType > & other) inline
Extend this relation with another relation, expanding this equivalence relation The supplied relation is the old knowledge, whilst this relation only contains explicitly new knowledge.
After this operation the "implicitly new tuples" are now explicitly inserted this relation.
Definition at line 136 of file EquivalenceRelation.h.
{
         // nothing to extend if there's no new/original knowledge
         if (other.size() == 0 || this->size() == 0) return;
         this->genAllDisjointSetLists();
         other.genAllDisjointSetLists();
         std::set<value_type> repsCovered;
         // find all the disjoint sets that need to be added to this relation
         // that exist in other (and exist in this)
         {
             auto it = this->sds.sparseToDenseMap.begin();
             auto end = this->sds.sparseToDenseMap.end();
             value_type el;
             for (; it != end; ++it) {
                 std::tie(el, std::ignore) = *it;
                 if (other.containsElement(el)) {
                     value_type rep = other.sds.findNode(el);
                     if (repsCovered.count(rep) == 0) {
                         repsCovered.emplace(rep);
                     }
                 }
             }
         }
         // add the intersecting dj sets into this one
         {
             value_type el;
             value_type rep;
             auto it = other.sds.sparseToDenseMap.begin();
             auto end = other.sds.sparseToDenseMap.end();
             for (; it != end; ++it) {
                 std::tie(el, std::ignore) = *it;
                 rep = other.sds.findNode(el);
                 if (repsCovered.count(rep) != 0) {
                     this->insert(el, rep);
                 }
             }
         }
     }
find() [1/2]
template<typename TupleType> iterator souffle::EquivalenceRelation< TupleType >::find (const TupleType & , operation_hints &) const inline
Definition at line 669 of file EquivalenceRelation.h.
Referenced by souffle::EquivalenceRelation< t_tuple< 2 > >::find().
{
         throw std::runtime_error("error: find() is not compatible with equivalence relations");
         return begin();
     }
find() [2/2]
template<typename TupleType> iterator souffle::EquivalenceRelation< TupleType >::find (const TupleType & t) const inline
Definition at line 674 of file EquivalenceRelation.h.
{
         operation_hints context;
         return find(t, context);
     }
genAllDisjointSetLists()
template<typename TupleType> void souffle::EquivalenceRelation< TupleType >::genAllDisjointSetLists () const inline private
Generate a cache of the sets such that they can be iterated over efficiently.
Each set is partitioned into a PiggyList.
Definition at line 700 of file EquivalenceRelation.h.
Referenced by souffle::EquivalenceRelation< t_tuple< 2 > >::anteriorIt(), souffle::EquivalenceRelation< t_tuple< 2 > >::antpostit(), souffle::EquivalenceRelation< t_tuple< 2 > >::begin(), souffle::EquivalenceRelation< t_tuple< 2 > >::closure(), souffle::EquivalenceRelation< t_tuple< 2 > >::extend(), souffle::EquivalenceRelation< t_tuple< 2 > >::insertAll(), souffle::EquivalenceRelation< t_tuple< 2 > >::partition(), and souffle::EquivalenceRelation< t_tuple< 2 > >::size().
{
         statesLock.lock();
         // no need to generate again, already done.
         if (!this->statesMapStale.load(std::memory_order_acquire)) {
             statesLock.unlock();
             return;
         }
         // btree version
         emptyPartition();
         size_t dSetSize = this->sds.ds.a_blocks.size();
         for (size_t i = 0; i < dSetSize; ++i) {
             typename TupleType::value_type sparseVal = this->sds.toSparse(i);
             parent_t rep = this->sds.findNode(sparseVal);
             StorePair p = {rep, nullptr};
             StatesList* mapList = equivalencePartition.insert(p, [&](StorePair& sp) {
                 auto* r = new StatesList(1);
                 sp.second = r;
                 return r;
             });
             mapList->append(sparseVal);
         }
         statesMapStale.store(false, std::memory_order_release);
         statesLock.unlock();
     }
getBoundaries() [1/2]
template<typename TupleType> template<unsigned levels> range<iterator> souffle::EquivalenceRelation< TupleType >::getBoundaries (const TupleType & entry) const inline
Obtains a range of elements matching the prefix of the given entry up to levels elements.
Template Parameters
levels the length of the requested matching prefix
Parameters
entry the entry to be looking for
Returns
the corresponding range of matching elements
Definition at line 475 of file EquivalenceRelation.h.
Referenced by souffle::test::TEST().
{
         operation_hints ctxt;
         return getBoundaries<levels>(entry, ctxt);
     }
getBoundaries() [2/2]
template<typename TupleType> template<unsigned levels> range<iterator> souffle::EquivalenceRelation< TupleType >::getBoundaries (const TupleType & entry, operation_hints &) const inline
Obtains a range of elements matching the prefix of the given entry up to levels elements.
A operation context may be provided to exploit temporal locality.
Template Parameters
levels the length of the requested matching prefix
Parameters
entry the entry to be looking for
ctxt the operation context to be utilized
Returns
the corresponding range of matching elements
Definition at line 491 of file EquivalenceRelation.h.
{
         // if nothing is bound => just use begin and end
         if (levels == 0) return make_range(begin(), end());
         // as disjoint set is exactly two args (equiv relation)
         // we only need to handle these cases
         if (levels == 1) {
             // need to test if the entry actually exists
             if (!sds.nodeExists(entry[0])) return make_range(end(), end());
             // return an iterator over all (entry[0], _)
             return make_range(anteriorIt(entry[0]), end());
         }
         if (levels == 2) {
             // need to test if the entry actually exists
             if (!sds.contains(entry[0], entry[1])) return make_range(end(), end());
             // if so return an iterator containing exactly that node
             return make_range(antpostit(entry[0], entry[1]), end());
         }
         std::cerr << "invalid state, cannot search for >2 arg start point in getBoundaries, in 2 arg tuple "
                      "store\n";
         throw "invalid state, cannot search for >2 arg start point in getBoundaries, in 2 arg tuple store";
         return make_range(end(), end());
     }
insert() [1/3]
template<typename TupleType> bool souffle::EquivalenceRelation< TupleType >::insert (value_type x, value_type y) inline
Insert the two values symbolically as a binary relation.
Parameters
x node to be added/paired
y node to be added/paired
Returns
true if the pair is new to the data structure
Definition at line 78 of file EquivalenceRelation.h.
Referenced by souffle::EquivalenceRelation< t_tuple< 2 > >::extend(), souffle::EquivalenceRelation< t_tuple< 2 > >::insert(), and souffle::test::TEST().
{
         operation_hints z;
         return insert(x, y, z);
     };
insert() [2/3]
template<typename TupleType> bool souffle::EquivalenceRelation< TupleType >::insert (const TupleType & tuple) inline
Insert the tuple symbolically.
Parameters
tuple The tuple to be inserted
Returns
true if the tuple is new to the data structure
Definition at line 88 of file EquivalenceRelation.h.
{
         operation_hints hints;
         return insert(tuple[0], tuple[1], hints);
     };
insert() [3/3]
template<typename TupleType> bool souffle::EquivalenceRelation< TupleType >::insert (value_type x, value_type y, operation_hints) inline
Insert the two values symbolically as a binary relation.
Parameters
x node to be added/paired
y node to be added/paired
z the hints to where the pair should be inserted (not applicable atm)
Returns
true if the pair is new to the data structure
Definition at line 100 of file EquivalenceRelation.h.
{
         // indicate that iterators will have to generate on request
         this->statesMapStale.store(true, std::memory_order_relaxed);
         bool retval = contains(x, y);
         sds.unionNodes(x, y);
         return retval;
     }
insertAll()
template<typename TupleType> void souffle::EquivalenceRelation< TupleType >::insertAll (const EquivalenceRelation< TupleType > & other) inline
inserts all nodes from the other relation into this one
Parameters
other the binary relation from which to add elements from
Definition at line 112 of file EquivalenceRelation.h.
{
         other.genAllDisjointSetLists();
         // iterate over partitions at a time
         for (typename StatesMap::chunk it : other.equivalencePartition.getChunks(MAX_THREADS)) {
             for (auto& p : it) {
                 value_type rep = p.first;
                 StatesList& pl = *p.second;
                 const size_t ksize = pl.size();
                 for (size_t i = 0; i < ksize; ++i) {
                     this->sds.unionNodes(rep, pl.get(i));
                 }
             }
         }
         // invalidate iterators unconditionally
         this->statesMapStale.store(true, std::memory_order_relaxed);
     }
lower_bound()
template<typename TupleType> iterator souffle::EquivalenceRelation< TupleType >::lower_bound (const TupleType & entry, operation_hints &) const inline
Act similar to getBoundaries.
But non-static. This function should be used ONLY by interpreter, and its behavior is tightly coupling with InterpreterIndex. Do Not rely on this interface outside the interpreter.
Parameters
entry the entry to be looking for
Returns
the corresponding range of matching elements
Definition at line 530 of file EquivalenceRelation.h.
{
         if (entry[0] == MIN_RAM_SIGNED && entry[1] == MIN_RAM_SIGNED) {
             // Return an iterator over all tuples.
             return begin();
         }
         if (entry[0] != MIN_RAM_SIGNED && entry[1] == MIN_RAM_SIGNED) {
             // Return an iterator over all (entry[0], _)
             if (!sds.nodeExists(entry[0])) {
                 return end();
             }
             return anteriorIt(entry[0]);
         }
         if (entry[0] != MIN_RAM_SIGNED && entry[1] != MIN_RAM_SIGNED) {
             // Return an iterator point to the exact same node.
             if (!sds.contains(entry[0], entry[1])) {
                 return end();
             }
             return antpostit(entry[0], entry[1]);
         }
         return end();
     }
partition()
template<typename TupleType> std::vector<souffle::range<iterator> > souffle::EquivalenceRelation< TupleType >::partition (size_t chunks) const inline
Generate an approximate number of iterators for parallel iteration The iterators returned are not necessarily equal in size, but in practise are approximately similarly sized Depending on the structure of the data, there can be more or less partitions returned than requested.
Parameters
chunks the number of requested partitions
Returns
a list of the iterators as ranges
Definition at line 634 of file EquivalenceRelation.h.
Referenced by souffle::test::TEST().
{
         // generate all reps
         genAllDisjointSetLists();
         size_t numPairs = this->size();
         if (numPairs == 0) return {};
         if (numPairs == 1 || chunks <= 1) return {souffle::make_range(begin(), end())};
         // if there's more dj sets than requested chunks, then just return an iter per dj set
         std::vector<souffle::range<iterator>> ret;
         if (chunks <= equivalencePartition.size()) {
             for (auto& p : equivalencePartition) {
                 ret.push_back(souffle::make_range(closure(p.first), end()));
             }
             return ret;
         }
         // keep it simple stupid
         // just go through and if the size of the binrel is > numpairs/chunks, then generate an anteriorIt for
         // each
         const size_t perchunk = numPairs / chunks;
         for (const auto& itp : equivalencePartition) {
             const size_t s = itp.second->size();
             if (s * s > perchunk) {
                 for (const auto& i : *itp.second) {
                     ret.push_back(souffle::make_range(anteriorIt(i), end()));
                 }
             } else {
                 ret.push_back(souffle::make_range(closure(itp.first), end()));
             }
         }
         return ret;
     }
size()
template<typename TupleType> size_t souffle::EquivalenceRelation< TupleType >::size () const inline
Size of relation.
Returns
the sum of the number of pairs per disjoint set
Definition at line 222 of file EquivalenceRelation.h.
Referenced by souffle::EquivalenceRelation< t_tuple< 2 > >::empty(), souffle::EquivalenceRelation< t_tuple< 2 > >::extend(), souffle::EquivalenceRelation< t_tuple< 2 > >::partition(), and souffle::test::TEST().
{
         genAllDisjointSetLists();
         statesLock.lock_shared();
         size_t retVal = 0;
         for (auto& e : this->equivalencePartition) {
             const size_t s = e.second->size();
             retVal += s * s;
         }
         statesLock.unlock_shared();
         return retVal;
     }
upper_bound()
template<typename TupleType> iterator souffle::EquivalenceRelation< TupleType >::upper_bound (const TupleType & , operation_hints &) const inline
This function is only here in order to unify interfaces in InterpreterIndex.
Unlike the name suggestes, it omit the arguments and simply return the end iterator of the relation.
Parameters
omitted
Returns
the end iterator.
Definition at line 565 of file EquivalenceRelation.h.
{
         return end();
     }
Field Documentation
equivalencePartition
template<typename TupleType> StatesMap souffle::EquivalenceRelation< TupleType >::equivalencePartition mutable private
Definition at line 692 of file EquivalenceRelation.h.
Referenced by souffle::EquivalenceRelation< t_tuple< 2 > >::anteriorIt(), souffle::EquivalenceRelation< t_tuple< 2 > >::antpostit(), souffle::EquivalenceRelation< t_tuple< 2 > >::closure(), souffle::EquivalenceRelation< t_tuple< 2 > >::emptyPartition(), souffle::EquivalenceRelation< t_tuple< 2 > >::insertAll(), souffle::EquivalenceRelation< t_tuple< 2 > >::partition(), and souffle::EquivalenceRelation< t_tuple< 2 > >::size().
sds
template<typename TupleType> souffle::SparseDisjointSet<value_type> souffle::EquivalenceRelation< TupleType >::sds mutable private
Definition at line 687 of file EquivalenceRelation.h.
Referenced by souffle::EquivalenceRelation< t_tuple< 2 > >::anteriorIt(), souffle::EquivalenceRelation< t_tuple< 2 > >::antpostit(), souffle::EquivalenceRelation< t_tuple< 2 > >::clear(), souffle::EquivalenceRelation< t_tuple< 2 > >::closure(), souffle::EquivalenceRelation< t_tuple< 2 > >::contains(), souffle::EquivalenceRelation< t_tuple< 2 > >::containsElement(), souffle::EquivalenceRelation< t_tuple< 2 > >::extend(), souffle::EquivalenceRelation< t_tuple< 2 > >::getBoundaries(), souffle::EquivalenceRelation< t_tuple< 2 > >::insert(), souffle::EquivalenceRelation< t_tuple< 2 > >::insertAll(), and souffle::EquivalenceRelation< t_tuple< 2 > >::lower_bound().
statesLock
template<typename TupleType> std::shared_mutex souffle::EquivalenceRelation< TupleType >::statesLock mutable private
Definition at line 690 of file EquivalenceRelation.h.
Referenced by souffle::EquivalenceRelation< t_tuple< 2 > >::clear(), and souffle::EquivalenceRelation< t_tuple< 2 > >::size().
statesMapStale
template<typename TupleType> std::atomic<bool> souffle::EquivalenceRelation< TupleType >::statesMapStale mutable private
Definition at line 694 of file EquivalenceRelation.h.
Referenced by souffle::EquivalenceRelation< t_tuple< 2 > >::emptyPartition(), souffle::EquivalenceRelation< t_tuple< 2 > >::insert(), and souffle::EquivalenceRelation< t_tuple< 2 > >::insertAll().
The documentation for this class was generated from the following file:
EquivalenceRelation.h