souffle: souffle::AstComponentChecker Class Reference
souffle::AstComponentChecker Class Reference
#include <ComponentChecker.h>
Public Member Functions
AstComponentChecker * clone () const override
std::string getName () const override
~AstComponentChecker () override=default
Public Member Functions inherited from souffle::AstTransformer
bool apply (AstTranslationUnit &translationUnit)
virtual ~AstTransformer ()=default
Private Member Functions
bool transform (AstTranslationUnit &translationUnit) override
Static Private Member Functions
static void checkComponent (ErrorReport &report, const AstComponent *enclosingComponent, const ComponentLookup &componentLookup, const AstComponent &component, const TypeBinding &binding)
static void checkComponentInit (ErrorReport &report, const AstComponent *enclosingComponent, const ComponentLookup &componentLookup, const AstComponentInit &init, const TypeBinding &binding)
static const AstComponent * checkComponentNameReference (ErrorReport &report, const AstComponent *enclosingComponent, const ComponentLookup &componentLookup, const std::string &name, const SrcLocation &loc, const TypeBinding &binding)
static void checkComponentNamespaces (ErrorReport &report, const AstProgram &program)
static void checkComponentReference (ErrorReport &report, const AstComponent *enclosingComponent, const ComponentLookup &componentLookup, const AstComponentType &type, const SrcLocation &loc, const TypeBinding &binding)
static void checkComponents (ErrorReport &report, const AstProgram &program, const ComponentLookup &componentLookup)
Detailed Description
Definition at line 34 of file ComponentChecker.h.
Constructor & Destructor Documentation
~AstComponentChecker()
souffle::AstComponentChecker::~AstComponentChecker () override default
Member Function Documentation
checkComponent()
void souffle::AstComponentChecker::checkComponent (ErrorReport & report, const AstComponent * enclosingComponent, const ComponentLookup & componentLookup, const AstComponent & component, const TypeBinding & binding) static private
Definition at line 99 of file ComponentChecker.cpp.
References souffle::ErrorReport::addError(), base, checkComponentInit(), checkComponentReference(), souffle::TypeBinding::extend(), souffle::AstComponent::getBaseComponents(), souffle::ComponentLookup::getComponent(), souffle::AstComponent::getComponents(), souffle::AstComponent::getComponentType(), souffle::AstComponent::getInstantiations(), souffle::AstComponentType::getName(), souffle::AstComponent::getOverridden(), souffle::AstComponent::getRelations(), souffle::AstNode::getSrcLoc(), souffle::AstComponentType::getTypeParameters(), souffle::OVERRIDABLE, and relation.
Referenced by checkComponents(), and clone().
{
     // -- inheritance --
     // Update type binding:
     // Since we are not compiling, i.e. creating concrete instance of the
     // components with type parameters, we are only interested in whether
     // component references refer to existing components or some type parameter.
     // Type parameter for us here is unknown type that will be bound at the template
     // instantiation time.
     auto parentTypeParameters = component.getComponentType()->getTypeParameters();
     std::vector<AstQualifiedName> actualParams(parentTypeParameters.size(), "<type parameter>");
     TypeBinding activeBinding = binding.extend(parentTypeParameters, actualParams);
     // check parents of component
     for (const auto& cur : component.getBaseComponents()) {
         checkComponentReference(
                 report, enclosingComponent, componentLookup, *cur, component.getSrcLoc(), activeBinding);
         // Note: type parameters can also be atomic types like number, or anything defined through .type
         // The original semantic check permitted any identifier (existing or non-existing) to be actual
         // parameter
         // In order to maintain the compatibility, we do not check the actual parameters
         // for (const std::string& param : cur.getTypeParameters()) {
         //    checkComponentNameReference(report, scope, param, component.getSrcLoc(), activeBinding);
         //}
     }
     // get all parents
     std::set<const AstComponent*> parents;
     std::function<void(const AstComponent&)> collectParents = [&](const AstComponent& cur) {
         for (const auto& base : cur.getBaseComponents()) {
             auto c = componentLookup.getComponent(enclosingComponent, base->getName(), binding);
             if (c == nullptr) {
                 continue;
             }
             if (parents.insert(c).second) {
                 collectParents(*c);
             }
         }
     };
     collectParents(component);
     // check overrides
     for (const AstRelation* relation : component.getRelations()) {
         if (component.getOverridden().count(relation->getQualifiedName().getQualifiers()[0]) != 0u) {
             report.addError("Override of non-inherited relation " +
                                     relation->getQualifiedName().getQualifiers()[0] + " in component " +
                                     component.getComponentType()->getName(),
                     component.getSrcLoc());
         }
     }
     for (const AstComponent* parent : parents) {
         for (const AstRelation* relation : parent->getRelations()) {
             if ((component.getOverridden().count(relation->getQualifiedName().getQualifiers()[0]) != 0u) &&
                     !relation->hasQualifier(RelationQualifier::OVERRIDABLE)) {
                 report.addError("Override of non-overridable relation " +
                                         relation->getQualifiedName().getQualifiers()[0] + " in component " +
                                         component.getComponentType()->getName(),
                         component.getSrcLoc());
             }
         }
     }
     // check for a cycle
     if (parents.find(&component) != parents.end()) {
         report.addError(
                 "Invalid cycle in inheritance for component " + component.getComponentType()->getName(),
                 component.getSrcLoc());
     }
     // -- nested components --
     // check nested components
     for (const auto& cur : component.getComponents()) {
         checkComponent(report, &component, componentLookup, *cur, activeBinding);
     }
     // check nested instantiations
     for (const auto& cur : component.getInstantiations()) {
         checkComponentInit(report, &component, componentLookup, *cur, activeBinding);
     }
 }
checkComponentInit()
void souffle::AstComponentChecker::checkComponentInit (ErrorReport & report, const AstComponent * enclosingComponent, const ComponentLookup & componentLookup, const AstComponentInit & init, const TypeBinding & binding) static private
Definition at line 83 of file ComponentChecker.cpp.
References checkComponentReference(), souffle::AstComponentInit::getComponentType(), and souffle::AstNode::getSrcLoc().
Referenced by checkComponent(), checkComponents(), and clone().
{
     checkComponentReference(
             report, enclosingComponent, componentLookup, *init.getComponentType(), init.getSrcLoc(), binding);
     // Note: actual parameters can be atomic types like number, or anything declared with .type
     // The original semantic check permitted any identifier (existing or non-existing) to be actual parameter
     // In order to maintain the compatibility, we do not check the actual parameters
     // check the actual parameters:
     // const auto& actualParams = init.getComponentType().getTypeParameters();
     // for (const auto& param : actualParams) {
     //    checkComponentNameReference(report, scope, param, init.getSrcLoc(), binding);
     //}
 }
checkComponentNameReference()
const AstComponent * souffle::AstComponentChecker::checkComponentNameReference (ErrorReport & report, const AstComponent * enclosingComponent, const ComponentLookup & componentLookup, const std::string & name, const SrcLocation & loc, const TypeBinding & binding) static private
Definition at line 48 of file ComponentChecker.cpp.
References souffle::ErrorReport::addError(), souffle::AstQualifiedName::empty(), souffle::TypeBinding::find(), and souffle::ComponentLookup::getComponent().
Referenced by checkComponentReference(), and clone().
{
     const AstQualifiedName& forwarded = binding.find(name);
     if (!forwarded.empty()) {
         // for forwarded types we do not check anything, because we do not know
         // what the actual type will be
         return nullptr;
     }
     const AstComponent* c = componentLookup.getComponent(enclosingComponent, name, binding);
     if (c == nullptr) {
         report.addError("Referencing undefined component " + name, loc);
         return nullptr;
     }
     return c;
 }
checkComponentNamespaces()
void souffle::AstComponentChecker::checkComponentNamespaces (ErrorReport & report, const AstProgram & program) static private
Definition at line 196 of file ComponentChecker.cpp.
References souffle::ErrorReport::addError(), souffle::AstProgram::getComponentInstantiations(), souffle::AstProgram::getComponents(), souffle::AstProgram::getRelations(), souffle::AstProgram::getTypes(), and souffle::toString().
Referenced by clone(), and transform().
{
     std::map<std::string, SrcLocation> names;
     // Type and relation name error reporting performed by the AstSemanticChecker instead
     // Find all names and report redeclarations as we go.
     for (const auto& type : program.getTypes()) {
         const std::string name = toString(type->getQualifiedName());
         if (names.count(name) == 0u) {
             names[name] = type->getSrcLoc();
         }
     }
     for (const auto& rel : program.getRelations()) {
         const std::string name = toString(rel->getQualifiedName());
         if (names.count(name) == 0u) {
             names[name] = rel->getSrcLoc();
         }
     }
     // Note: Nested component and instance names are not obtained.
     for (const auto& comp : program.getComponents()) {
         const std::string name = toString(comp->getComponentType()->getName());
         if (names.count(name) != 0u) {
             report.addError("Name clash on component " + name, comp->getSrcLoc());
         } else {
             names[name] = comp->getSrcLoc();
         }
     }
     for (const auto& inst : program.getComponentInstantiations()) {
         const std::string name = toString(inst->getInstanceName());
         if (names.count(name) != 0u) {
             report.addError("Name clash on instantiation " + name, inst->getSrcLoc());
         } else {
             names[name] = inst->getSrcLoc();
         }
     }
 }
checkComponentReference()
void souffle::AstComponentChecker::checkComponentReference (ErrorReport & report, const AstComponent * enclosingComponent, const ComponentLookup & componentLookup, const AstComponentType & type, const SrcLocation & loc, const TypeBinding & binding) static private
Definition at line 67 of file ComponentChecker.cpp.
References souffle::ErrorReport::addError(), checkComponentNameReference(), souffle::AstComponent::getComponentType(), souffle::AstComponentType::getName(), and souffle::AstComponentType::getTypeParameters().
Referenced by checkComponent(), checkComponentInit(), and clone().
{
     // check whether targeted component exists
     const AstComponent* c = checkComponentNameReference(
             report, enclosingComponent, componentLookup, type.getName(), loc, binding);
     if (c == nullptr) {
         return;
     }
     // check number of type parameters
     if (c->getComponentType()->getTypeParameters().size() != type.getTypeParameters().size()) {
         report.addError("Invalid number of type parameters for component " + type.getName(), loc);
     }
 }
checkComponents()
void souffle::AstComponentChecker::checkComponents (ErrorReport & report, const AstProgram & program, const ComponentLookup & componentLookup) static private
Definition at line 184 of file ComponentChecker.cpp.
References checkComponent(), checkComponentInit(), souffle::AstProgram::getComponentInstantiations(), and souffle::AstProgram::getComponents().
Referenced by clone(), and transform().
{
     for (AstComponent* cur : program.getComponents()) {
         checkComponent(report, nullptr, componentLookup, *cur, TypeBinding());
     }
     for (AstComponentInit* cur : program.getComponentInstantiations()) {
         checkComponentInit(report, nullptr, componentLookup, *cur, TypeBinding());
     }
 }
clone()
AstComponentChecker* souffle::AstComponentChecker::clone () const inline override virtual
Implements souffle::AstTransformer.
Definition at line 42 of file ComponentChecker.h.
References checkComponent(), checkComponentInit(), checkComponentNameReference(), checkComponentNamespaces(), checkComponentReference(), checkComponents(), and transform().
{
         return new AstComponentChecker();
     }
getName()
std::string souffle::AstComponentChecker::getName () const inline override virtual
Implements souffle::AstTransformer.
Definition at line 38 of file ComponentChecker.h.
{
         return "AstComponentChecker";
     }
transform()
bool souffle::AstComponentChecker::transform (AstTranslationUnit & translationUnit) override private virtual
Implements souffle::AstTransformer.
Definition at line 39 of file ComponentChecker.cpp.
References checkComponentNamespaces(), checkComponents(), souffle::AstTranslationUnit::getAnalysis(), souffle::AstTranslationUnit::getErrorReport(), and souffle::AstTranslationUnit::getProgram().
Referenced by clone().
{
     AstProgram& program = *translationUnit.getProgram();
     ComponentLookup& componentLookup = *translationUnit.getAnalysis<ComponentLookup>();
     ErrorReport& report = translationUnit.getErrorReport();
     checkComponents(report, program, componentLookup);
     checkComponentNamespaces(report, program);
     return false;
 }
The documentation for this class was generated from the following files:
ast/transform/ComponentChecker.h
ast/transform/ComponentChecker.cpp