souffle: souffle::IfConversionTransformer Class Reference
souffle::IfConversionTransformer Class Reference
Convert IndexScan operations to Filter/Existence Checks.
#include <IfConversion.h>
Public Member Functions
bool convertIndexScans (RamProgram &program)
Apply if-conversion to the whole program.
std::string getName () const override
get name of the transformer
std::unique_ptr< RamOperation > rewriteIndexScan (const RamIndexScan *indexScan)
Rewrite IndexScan operations.
Public Member Functions inherited from souffle::RamTransformer
bool apply (RamTranslationUnit &translationUnit)
apply the transformer to a translation unit translationUnit that will be transformed.
virtual ~RamTransformer ()=default
Protected Member Functions
bool transform (RamTranslationUnit &translationUnit) override
transform the translation unit / used by apply translationUnit that will be transformed.
Detailed Description
Convert IndexScan operations to Filter/Existence Checks.
If there exists IndexScan operations in the RAM, and their tuples are not further used in subsequent operations, the IndexScan operations will be rewritten to Filter/Existence Checks.
For example,
QUERY
 ...
 FOR t1 IN X ON INDEX t1.x = 10 AND t1.y = 20
   ... // no occurrence of t1
will be rewritten to
QUERY
 ...
  IF (10,20) NOT IN A
    ...
Definition at line 55 of file IfConversion.h.
Member Function Documentation
convertIndexScans()
bool souffle::IfConversionTransformer::convertIndexScans (RamProgram & program)
Apply if-conversion to the whole program.
Parameters
RAM program
Returns
A flag indicating whether the RAM program has been changed.
Search for queries and rewrite their IndexScan operations if possible.
Definition at line 80 of file IfConversion.cpp.
References souffle::RamTransformer::apply(), souffle::makeLambdaRamMapper(), rewriteIndexScan(), and souffle::visitDepthFirst().
Referenced by getName(), and transform().
{
     bool changed = false;
     visitDepthFirst(program, [&](const RamQuery& query) {
         std::function<std::unique_ptr<RamNode>(std::unique_ptr<RamNode>)> scanRewriter =
                 [&](std::unique_ptr<RamNode> node) -> std::unique_ptr<RamNode> {
             if (const RamIndexScan* scan = dynamic_cast<RamIndexScan*>(node.get())) {
                 if (std::unique_ptr<RamOperation> op = rewriteIndexScan(scan)) {
                     changed = true;
                     node = std::move(op);
                 }
             }
             node->apply(makeLambdaRamMapper(scanRewriter));
             return node;
         };
         const_cast<RamQuery*>(&query)->apply(makeLambdaRamMapper(scanRewriter));
     });
     return changed;
 }
getName()
std::string souffle::IfConversionTransformer::getName () const inline override virtual
get name of the transformer
Implements souffle::RamTransformer.
Definition at line 57 of file IfConversion.h.
References convertIndexScans(), and rewriteIndexScan().
{
         return "IfConversionTransformer";
     }
rewriteIndexScan()
std::unique_ptr< RamOperation > souffle::IfConversionTransformer::rewriteIndexScan (const RamIndexScan * indexScan)
Rewrite IndexScan operations.
Parameters
indexScan An index operation
Returns
The old operation if the if-conversion fails; otherwise the filter/existence check
Rewrites IndexScan operations to a filter/existence check if the IndexScan's tuple is not used in a consecutive RAM operation
Definition at line 33 of file IfConversion.cpp.
References souffle::RamExpression::clone(), souffle::RamOperation::clone(), souffle::fatal(), souffle::RamRelation::getArity(), souffle::RamNestedOperation::getOperation(), souffle::RamNestedOperation::getProfileText(), souffle::RamIndexOperation::getRangePattern(), souffle::RamRelationOperation::getRelation(), souffle::RamTupleOperation::getTupleId(), souffle::RamTupleElement::getTupleId(), i, and souffle::visitDepthFirst().
Referenced by convertIndexScans(), and getName().
{
     // check whether tuple is used in subsequent operations
     bool tupleNotUsed = true;
     visitDepthFirst(*indexScan, [&](const RamTupleElement& element) {
         if (element.getTupleId() == indexScan->getTupleId()) {
             tupleNotUsed = false;
         }
     });
     // if not used, transform the IndexScan operation to an existence check
     if (tupleNotUsed) {
         // replace IndexScan with an Filter/Existence check
         std::vector<std::unique_ptr<RamExpression>> newValues;
         size_t arity = indexScan->getRelation().getArity();
         for (size_t i = 0; i < arity; ++i) {
             if (*(indexScan->getRangePattern().first[i]) != *(indexScan->getRangePattern().second[i])) {
                 fatal("Inequal upper and lower bounds not supported while rewriting index scan in "
                       "IfConversionTransformer");
             }
         }
         for (auto& cur : indexScan->getRangePattern().second) {
             RamExpression* val = nullptr;
             if (cur != nullptr) {
                 val = cur->clone();
             }
             newValues.emplace_back(val);
         }
         // check if there is a break statement nested in the Scan - if so, remove it
         RamOperation* newOp;
         if (const auto* breakOp = dynamic_cast<const RamBreak*>(&indexScan->getOperation())) {
             newOp = breakOp->getOperation().clone();
         } else {
             newOp = indexScan->getOperation().clone();
         }
         return std::make_unique<RamFilter>(
                 std::make_unique<RamExistenceCheck>(
                         std::make_unique<RamRelationReference>(&indexScan->getRelation()),
                         std::move(newValues)),
                 std::unique_ptr<RamOperation>(newOp), indexScan->getProfileText());
     }
     return nullptr;
 }
transform()
bool souffle::IfConversionTransformer::transform (RamTranslationUnit & translationUnit) inline override protected virtual
transform the translation unit / used by apply translationUnit that will be transformed.
flag reporting whether the RAM program has changed
Implements souffle::RamTransformer.
Definition at line 81 of file IfConversion.h.
References convertIndexScans(), and souffle::RamTranslationUnit::getProgram().
{
         return convertIndexScans(translationUnit.getProgram());
     }
The documentation for this class was generated from the following files:
ram/transform/IfConversion.h
ram/transform/IfConversion.cpp