souffle: souffle::RecordTable Class Reference
souffle::RecordTable Class Reference
#include <RecordTable.h>
Public Member Functions
RamDomain pack (RamDomain *tuple, size_t arity)
convert record to record reference
RecordTable ()=default
const RamDomain * unpack (RamDomain ref, size_t arity) const
convert record reference to a record
virtual ~RecordTable ()=default
Private Member Functions
RecordMap & lookupArity (size_t arity)
lookup RecordMap for a given arity; if it does not exist, create new RecordMap
Private Attributes
std::unordered_map< size_t, RecordMap > maps
Arity/RecordMap association.
Detailed Description
Definition at line 109 of file RecordTable.h.
Constructor & Destructor Documentation
RecordTable()
souffle::RecordTable::RecordTable () default
~RecordTable()
virtual souffle::RecordTable::~RecordTable () virtual default
Member Function Documentation
lookupArity()
RecordMap& souffle::RecordTable::lookupArity (size_t arity) inline private
lookup RecordMap for a given arity; if it does not exist, create new RecordMap
Definition at line 132 of file RecordTable.h.
{
         std::unordered_map<size_t, RecordMap>::iterator mapsIterator;
 #pragma omp critical(RecordTableGetForArity)
         {
             // This will create a new map if it doesn't exist yet.
             mapsIterator = maps.emplace(arity, arity).first;
         }
         return mapsIterator->second;
     }
pack()
RamDomain souffle::RecordTable::pack (RamDomain * tuple, size_t arity) inline
convert record to record reference
Definition at line 115 of file RecordTable.h.
Referenced by souffle::InterpreterEngine::execute(), souffle::pack(), and souffle::test::TEST().
{
         return lookupArity(arity).pack(tuple);
     }
unpack()
const RamDomain* souffle::RecordTable::unpack (RamDomain ref, size_t arity) const inline
convert record reference to a record
Definition at line 119 of file RecordTable.h.
Referenced by souffle::InterpreterEngine::execute(), and souffle::test::TEST().
{
         std::unordered_map<size_t, RecordMap>::const_iterator iter;
 #pragma omp critical(RecordTableGetForArity)
         {
             // Find a previously emplaced map
             iter = maps.find(arity);
         }
         assert(iter != maps.end() && "Attempting to unpack record for non-existing arity");
         return (iter->second).unpack(ref);
     }
Field Documentation
maps
std::unordered_map<size_t, RecordMap> souffle::RecordTable::maps private
Arity/RecordMap association.
Definition at line 143 of file RecordTable.h.
The documentation for this class was generated from the following file:
RecordTable.h