souffle: souffle::AstUserDefinedFunctorsTransformer Class Reference
souffle::AstUserDefinedFunctorsTransformer Class Reference
Transformation that passes the type information from user functors declaration to functors instances.
#include <UserDefinedFunctors.h>
Public Member Functions
AstUserDefinedFunctorsTransformer * clone () const override
std::string getName () const override
Public Member Functions inherited from souffle::AstTransformer
bool apply (AstTranslationUnit &translationUnit)
virtual ~AstTransformer ()=default
Private Member Functions
bool transform (AstTranslationUnit &translationUnit) override
Detailed Description
Transformation that passes the type information from user functors declaration to functors instances.
Definition at line 31 of file UserDefinedFunctors.h.
Member Function Documentation
clone()
AstUserDefinedFunctorsTransformer* souffle::AstUserDefinedFunctorsTransformer::clone () const inline override virtual
Implements souffle::AstTransformer.
Definition at line 37 of file UserDefinedFunctors.h.
References transform().
{
         return new AstUserDefinedFunctorsTransformer();
     }
getName()
std::string souffle::AstUserDefinedFunctorsTransformer::getName () const inline override virtual
Implements souffle::AstTransformer.
Definition at line 33 of file UserDefinedFunctors.h.
{
         return "AstUserDefinedFunctorsTransformer";
     }
transform()
bool souffle::AstUserDefinedFunctorsTransformer::transform (AstTranslationUnit & translationUnit) override private virtual
Implements souffle::AstTransformer.
Definition at line 30 of file UserDefinedFunctors.cpp.
References souffle::ErrorReport::addError(), souffle::AstProgram::apply(), souffle::AstFunctorDeclaration::getArgsTypes(), souffle::AstFunctorDeclaration::getArity(), souffle::AstTranslationUnit::getErrorReport(), souffle::getFunctorDeclaration(), souffle::AstTranslationUnit::getProgram(), and souffle::AstFunctorDeclaration::getReturnType().
Referenced by clone().
{
     struct UserFunctorRewriter : public AstNodeMapper {
         mutable bool changed{false};
         const AstProgram& program;
         ErrorReport& report;
         UserFunctorRewriter(const AstProgram& program, ErrorReport& report)
                 : program(program), report(report){};
         std::unique_ptr<AstNode> operator()(std::unique_ptr<AstNode> node) const override {
             node->apply(*this);
             if (auto* userFunctor = dynamic_cast<AstUserDefinedFunctor*>(node.get())) {
                 const AstFunctorDeclaration* functorDeclaration =
                         getFunctorDeclaration(program, userFunctor->getName());
                 // Check if the functor has been declared
                 if (functorDeclaration == nullptr) {
                     report.addError("User-defined functor hasn't been declared", userFunctor->getSrcLoc());
                     return node;
                 }
                 // Check arity correctness.
                 if (functorDeclaration->getArity() != userFunctor->getArguments().size()) {
                     report.addError("Mismatching number of arguments of functor", userFunctor->getSrcLoc());
                     return node;
                 }
                 // Set types of functor instance based on its declaration.
                 userFunctor->setTypes(
                         functorDeclaration->getArgsTypes(), functorDeclaration->getReturnType());
                 changed = true;
             }
             return node;
         }
     };
     UserFunctorRewriter update(*translationUnit.getProgram(), translationUnit.getErrorReport());
     translationUnit.getProgram()->apply(update);
     return update.changed;
 }
The documentation for this class was generated from the following files:
ast/transform/UserDefinedFunctors.h
ast/transform/UserDefinedFunctors.cpp