souffle: souffle::RamTranslationUnit Class Reference
souffle::RamTranslationUnit Class Reference
Translating a RAM program.
#include <TranslationUnit.h>
Public Member Functions
std::set< const RamAnalysis * > getAliveAnalyses () const
get the set of alive analyses of the translation unit
template<class Analysis >
Analysis * getAnalysis () const
templated method to compute/retrieve an analysis for a translation unit
DebugReport & getDebugReport ()
get debug report
const DebugReport & getDebugReport () const
get const debug report
ErrorReport & getErrorReport ()
get error report
const ErrorReport & getErrorReport () const
get error report
const RamProgram & getProgram () const
get the RAM Program of the translation unit
RamProgram & getProgram ()
get the RAM Program of the translation unit
souffle::SymbolTable & getSymbolTable ()
get symbol table
void invalidateAnalyses ()
throw away all alive analyses of the translation unit
RamTranslationUnit (std::unique_ptr< RamProgram > prog, SymbolTable sym, ErrorReport &e, DebugReport &d)
virtual ~RamTranslationUnit ()=default
Protected Attributes
std::map< std::string, std::unique_ptr< RamAnalysis > > analyses
DebugReport & debugReport
ErrorReport & errorReport
std::unique_ptr< RamProgram > program
souffle::SymbolTable symbolTable
Detailed Description
Translating a RAM program.
Comprises the program, symbol table, error report and debug report
Definition at line 42 of file TranslationUnit.h.
Constructor & Destructor Documentation
RamTranslationUnit()
souffle::RamTranslationUnit::RamTranslationUnit (std::unique_ptr< RamProgram > prog, SymbolTable sym, ErrorReport & e, DebugReport & d) inline
Definition at line 44 of file TranslationUnit.h.
References program, and ~RamTranslationUnit().
             : program(std::move(prog)), symbolTable(std::move(sym)), errorReport(e), debugReport(d) {
         assert(program != nullptr && "program is a null-pointer");
     }
~RamTranslationUnit()
virtual souffle::RamTranslationUnit::~RamTranslationUnit () virtual default
Referenced by RamTranslationUnit().
Member Function Documentation
getAliveAnalyses()
std::set<const RamAnalysis*> souffle::RamTranslationUnit::getAliveAnalyses () const inline
get the set of alive analyses of the translation unit
Definition at line 80 of file TranslationUnit.h.
References analyses.
{
         std::set<const RamAnalysis*> result;
         for (auto const& a : analyses) {
             result.insert(a.second.get());
         }
         return result;
     }
getAnalysis()
template<class Analysis > Analysis* souffle::RamTranslationUnit::getAnalysis () const inline
templated method to compute/retrieve an analysis for a translation unit
Definition at line 53 of file TranslationUnit.h.
References souffle::DebugReport::addSection(), analyses, souffle::Global::config(), and debugReport.
Referenced by souffle::Synthesiser::emitCode(), souffle::Synthesiser::generateCode(), souffle::ReportIndexTransformer::transform(), souffle::HoistAggregateTransformer::transform(), souffle::ReorderConditionsTransformer::transform(), souffle::IndexedInequalityTransformer::transform(), souffle::HoistConditionsTransformer::transform(), souffle::ChoiceConversionTransformer::transform(), and souffle::MakeIndexTransformer::transform().
{
         static const bool debug = Global::config().has("debug-report");
         std::string name = Analysis::name;
         auto it = analyses.find(name);
         if (it == analyses.end()) {
             // analysis does not exist yet, create instance and run it.
             auto analysis = std::make_unique<Analysis>(Analysis::name);
             analysis->run(*this);
             // output analysis in debug report
             if (debug) {
                 std::stringstream ramAnalysisStr;
                 ramAnalysisStr << *analysis;
                 if (!ramAnalysisStr.str().empty()) {
                     debugReport.addSection(
                             analysis->getName(), "RAM Analysis " + analysis->getName(), ramAnalysisStr.str());
                 }
             }
             // check it hasn't been created by someone else, and insert if not
             it = analyses.find(name);
             if (it == analyses.end()) {
                 analyses[name] = std::move(analysis);
             }
         }
         return dynamic_cast<Analysis*>(analyses[name].get());
     }
getDebugReport() [1/2]
DebugReport& souffle::RamTranslationUnit::getDebugReport () inline
get debug report
Definition at line 119 of file TranslationUnit.h.
References debugReport.
Referenced by souffle::RamTransformer::apply().
{
         return debugReport;
     }
getDebugReport() [2/2]
const DebugReport& souffle::RamTranslationUnit::getDebugReport () const inline
get const debug report
Definition at line 124 of file TranslationUnit.h.
References debugReport.
{
         return debugReport;
     }
getErrorReport() [1/2]
ErrorReport& souffle::RamTranslationUnit::getErrorReport () inline
get error report
Definition at line 109 of file TranslationUnit.h.
References errorReport.
Referenced by souffle::RamTransformer::apply().
{
         return errorReport;
     }
getErrorReport() [2/2]
const ErrorReport& souffle::RamTranslationUnit::getErrorReport () const inline
get error report
Definition at line 114 of file TranslationUnit.h.
References errorReport.
{
         return errorReport;
     }
getProgram() [1/2]
const RamProgram& souffle::RamTranslationUnit::getProgram () const inline
get the RAM Program of the translation unit
Definition at line 94 of file TranslationUnit.h.
References program.
Referenced by souffle::RamTransformer::apply(), souffle::Synthesiser::emitCode(), souffle::InterpreterEngine::executeMain(), souffle::InterpreterEngine::executeSubroutine(), souffle::Synthesiser::generateCode(), souffle::InterpreterEngine::generateIR(), souffle::RamIndexAnalysis::run(), souffle::HoistAggregateTransformer::transform(), souffle::ParallelTransformer::transform(), souffle::TupleIdTransformer::transform(), souffle::ExpandFilterTransformer::transform(), souffle::CollapseFiltersTransformer::transform(), souffle::EliminateDuplicatesTransformer::transform(), souffle::ReorderFilterBreak::transform(), souffle::ReorderConditionsTransformer::transform(), souffle::IfConversionTransformer::transform(), souffle::IndexedInequalityTransformer::transform(), souffle::HoistConditionsTransformer::transform(), souffle::ChoiceConversionTransformer::transform(), and souffle::MakeIndexTransformer::transform().
{
         return *program;
     }
getProgram() [2/2]
RamProgram& souffle::RamTranslationUnit::getProgram () inline
get the RAM Program of the translation unit
Definition at line 99 of file TranslationUnit.h.
References program.
{
         return *program;
     }
getSymbolTable()
souffle::SymbolTable& souffle::RamTranslationUnit::getSymbolTable () inline
get symbol table
Definition at line 104 of file TranslationUnit.h.
References symbolTable.
Referenced by souffle::Synthesiser::generateCode(), and souffle::InterpreterEngine::getSymbolTable().
{
         return symbolTable;
     }
invalidateAnalyses()
void souffle::RamTranslationUnit::invalidateAnalyses () inline
throw away all alive analyses of the translation unit
Definition at line 89 of file TranslationUnit.h.
References analyses.
Referenced by souffle::RamTransformer::apply().
{
         analyses.clear();
     }
Field Documentation
analyses
std::map<std::string, std::unique_ptr<RamAnalysis> > souffle::RamTranslationUnit::analyses mutable protected
Definition at line 130 of file TranslationUnit.h.
Referenced by getAliveAnalyses(), getAnalysis(), and invalidateAnalyses().
debugReport
DebugReport& souffle::RamTranslationUnit::debugReport protected
Definition at line 142 of file TranslationUnit.h.
Referenced by getAnalysis(), and getDebugReport().
errorReport
ErrorReport& souffle::RamTranslationUnit::errorReport protected
Definition at line 139 of file TranslationUnit.h.
Referenced by getErrorReport().
program
std::unique_ptr<RamProgram> souffle::RamTranslationUnit::program protected
Definition at line 133 of file TranslationUnit.h.
Referenced by getProgram(), and RamTranslationUnit().
symbolTable
souffle::SymbolTable souffle::RamTranslationUnit::symbolTable protected
Definition at line 136 of file TranslationUnit.h.
Referenced by getSymbolTable().
The documentation for this class was generated from the following file:
ram/TranslationUnit.h