souffle: souffle::RuleBody Class Reference
souffle::RuleBody Class Reference
#include <ParserUtils.h>
Data Structures
struct literal
Public Member Functions
void conjunct (RuleBody other)
void disjunct (RuleBody other)
RuleBody negated () const
RuleBody & operator= (RuleBody &&)=default
RuleBody ()=default
RuleBody (RuleBody &&)=default
VecOwn< AstClause > toClauseBodies () const
Static Public Member Functions
static RuleBody atom (Own< AstAtom > atom)
static RuleBody constraint (Own< AstConstraint > constraint)
static RuleBody getFalse ()
static RuleBody getTrue ()
Private Types
using clause = std::vector< literal >
Static Private Member Functions
static bool equal (const literal &a, const literal &b)
static bool equal (const clause &a, const clause &b)
static void insert (clause &cl, literal &&lit)
static void insert (std::vector< clause > &cnf, clause &&cls)
static bool isSubsetOf (const clause &a, const clause &b)
Private Attributes
std::vector< clause > dnf
Friends
std::ostream & operator<< (std::ostream &out, const RuleBody &body)
Detailed Description
Definition at line 33 of file ParserUtils.h.
Member Typedef Documentation
clause
using souffle::RuleBody::clause = std::vector<literal> private
Definition at line 75 of file ParserUtils.h.
Constructor & Destructor Documentation
RuleBody() [1/2]
souffle::RuleBody::RuleBody () default
Referenced by getFalse().
RuleBody() [2/2]
souffle::RuleBody::RuleBody (RuleBody &&) default
Member Function Documentation
atom()
RuleBody souffle::RuleBody::atom (Own< AstAtom > atom) static
Definition at line 133 of file ParserUtils.cpp.
References dnf.
Referenced by souffle::test::TEST(), and toClauseBodies().
{
     RuleBody body;
     body.dnf.push_back(clause());
     body.dnf.back().emplace_back(literal{false, std::move(atom)});
     return body;
 }
conjunct()
void souffle::RuleBody::conjunct (RuleBody other)
Definition at line 52 of file ParserUtils.cpp.
References dnf, insert(), and rhs.
Referenced by negated(), and souffle::test::TEST().
{
     // avoid making clones if possible
     if (dnf.size() == 1 && other.dnf.size() == 1) {
         for (auto&& rhs : other.dnf[0]) {
             insert(dnf[0], std::move(rhs));
         }
         return;
     }
     // compute the product of the disjunctions
     std::vector<clause> res;
     for (const auto& clauseA : dnf) {
         for (const auto& clauseB : other.dnf) {
             clause cur;
             for (const auto& lit : clauseA) {
                 cur.emplace_back(lit.clone());
             }
             for (const auto& lit : clauseB) {
                 insert(cur, lit.clone());
             }
             insert(res, std::move(cur));
         }
     }
     dnf = std::move(res);
 }
constraint()
RuleBody souffle::RuleBody::constraint (Own< AstConstraint > constraint) static
Definition at line 140 of file ParserUtils.cpp.
References dnf.
{
     RuleBody body;
     body.dnf.push_back(clause());
     body.dnf.back().emplace_back(literal{false, std::move(constraint)});
     return body;
 }
disjunct()
void souffle::RuleBody::disjunct (RuleBody other)
Definition at line 83 of file ParserUtils.cpp.
References dnf, and insert().
Referenced by souffle::test::TEST().
{
     // append the clauses of the other body to this body
     for (auto& cur : other.dnf) {
         insert(dnf, std::move(cur));
     }
 }
equal() [1/2]
bool souffle::RuleBody::equal (const literal & a, const literal & b) static private
Definition at line 158 of file ParserUtils.cpp.
References souffle::RuleBody::literal::atom, and souffle::RuleBody::literal::negated.
Referenced by equal(), insert(), and isSubsetOf().
{
     return a.negated == b.negated && *a.atom == *b.atom;
 }
equal() [2/2]
bool souffle::RuleBody::equal (const clause & a, const clause & b) static private
Definition at line 162 of file ParserUtils.cpp.
References equal(), i, and j.
{
     if (a.size() != b.size()) {
         return false;
     }
     for (const auto& i : a) {
         bool found = false;
         for (const auto& j : b) {
             if (equal(i, j)) {
                 found = true;
                 break;
             }
         }
         if (!found) {
             return false;
         }
     }
     return true;
 }
getFalse()
RuleBody souffle::RuleBody::getFalse () static
Definition at line 129 of file ParserUtils.cpp.
References RuleBody().
Referenced by souffle::test::TEST().
{
     return RuleBody();
 }
getTrue()
RuleBody souffle::RuleBody::getTrue () static
Definition at line 123 of file ParserUtils.cpp.
References dnf.
Referenced by negated(), and souffle::test::TEST().
{
     RuleBody body;
     body.dnf.push_back(clause());
     return body;
 }
insert() [1/2]
void souffle::RuleBody::insert (clause & cl, literal && lit) static private
Definition at line 200 of file ParserUtils.cpp.
References equal().
Referenced by conjunct(), and disjunct().
{
     for (const auto& cur : cl) {
         if (equal(cur, lit)) {
             return;
         }
     }
     cl.emplace_back(std::move(lit));
 }
insert() [2/2]
void souffle::RuleBody::insert (std::vector< clause > & cnf, clause && cls) static private
Definition at line 209 of file ParserUtils.cpp.
References isSubsetOf().
{
     for (const auto& cur : cnf) {
         if (isSubsetOf(cur, cls)) {
             return;
         }
     }
     std::vector<clause> res;
     for (auto& cur : cnf) {
         if (!isSubsetOf(cls, cur)) {
             res.push_back(std::move(cur));
         }
     }
     res.swap(cnf);
     cnf.push_back(std::move(cls));
 }
isSubsetOf()
bool souffle::RuleBody::isSubsetOf (const clause & a, const clause & b) static private
Definition at line 181 of file ParserUtils.cpp.
References equal(), i, and j.
Referenced by insert().
{
     if (a.size() > b.size()) {
         return false;
     }
     for (const auto& i : a) {
         bool found = false;
         for (const auto& j : b) {
             if (equal(i, j)) {
                 found = true;
                 break;
             }
         }
         if (!found) {
             return false;
         }
     }
     return true;
 }
negated()
RuleBody souffle::RuleBody::negated () const
Definition at line 36 of file ParserUtils.cpp.
References souffle::clone(), conjunct(), dnf, getTrue(), and souffle::RuleBody::literal::negated.
Referenced by souffle::test::TEST().
{
     RuleBody res = getTrue();
     for (const clause& cur : dnf) {
         RuleBody step;
         for (const literal& lit : cur) {
             step.dnf.push_back(clause());
             step.dnf.back().emplace_back(literal{!lit.negated, clone(lit.atom)});
         }
         res.conjunct(std::move(step));
     }
     return res;
 }
operator=()
RuleBody& souffle::RuleBody::operator= (RuleBody &&) default
toClauseBodies()
VecOwn< AstClause > souffle::RuleBody::toClauseBodies () const
Definition at line 90 of file ParserUtils.cpp.
References souffle::AstClause::addToBody(), atom(), base, souffle::clone(), dnf, and souffle::negateConstraintInPlace().
Referenced by souffle::test::TEST().
{
     // collect clause results
     VecOwn<AstClause> bodies;
     for (const clause& cur : dnf) {
         bodies.push_back(mk<AstClause>());
         AstClause& clause = *bodies.back();
         for (const literal& lit : cur) {
             // extract literal
             auto base = clone(lit.atom);
             // negate if necessary
             if (lit.negated) {
                 // negate
                 if (auto* atom = dynamic_cast<AstAtom*>(&*base)) {
                     base.release();
                     base = mk<AstNegation>(std::unique_ptr<AstAtom>(atom));
                     base->setSrcLoc(atom->getSrcLoc());
                 } else if (auto* cstr = dynamic_cast<AstConstraint*>(&*base)) {
                     negateConstraintInPlace(*cstr);
                 }
             }
             // add to result
             clause.addToBody(std::move(base));
         }
     }
     // done
     return bodies;
 }
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & out, const RuleBody & body) friend
Definition at line 147 of file ParserUtils.cpp.
{
     return out << join(body.dnf, ";", [](std::ostream& out, const RuleBody::clause& cur) {
         out << join(cur, ",", [](std::ostream& out, const RuleBody::literal& l) {
             if (l.negated) {
                 out << "!";
             }
             out << *l.atom;
         });
     });
 }
Field Documentation
dnf
std::vector<clause> souffle::RuleBody::dnf private
Definition at line 77 of file ParserUtils.h.
Referenced by atom(), conjunct(), constraint(), disjunct(), getTrue(), negated(), souffle::operator<<(), and toClauseBodies().
The documentation for this class was generated from the following files:
ast/ParserUtils.h
ast/ParserUtils.cpp