souffle: souffle::SparseDisjointSet< SparseDomain > Class Template Reference
souffle::SparseDisjointSet< SparseDomain > Class Template Reference
#include <UnionFind.h>
Public Member Functions
void clear ()
Remove all elements from this disjoint set.
bool contains (SparseDomain v1, SparseDomain v2)
SparseDomain findNode (SparseDomain x)
void makeNode (SparseDomain val)
bool nodeExists (const SparseDomain val) const
SparseDisjointSet & operator= (SparseDisjointSet &other)=delete
SparseDisjointSet & operator= (SparseDisjointSet &&other)=delete
bool sameSet (SparseDomain x, SparseDomain y)
std::size_t size ()
SparseDisjointSet ()=default
SparseDisjointSet (SparseDisjointSet &other)=delete
SparseDisjointSet (SparseDisjointSet &&other)=delete
parent_t toDense (const SparseDomain in)
Retrieve dense encoding, adding it in if non-existent.
const SparseDomain toSparse (const parent_t in) const
For the given dense value, return the associated sparse value Undefined behaviour if dense value not in set.
void unionNodes (SparseDomain x, SparseDomain y)
Private Types
using DenseMap = RandomInsertPiggyList< SparseDomain >
using PairStore = std::pair< SparseDomain, parent_t >
using SparseMap = LambdaBTreeSet< PairStore, std::function< parent_t(PairStore &)>, EqrelMapComparator< PairStore > >
Private Attributes
DenseMap denseToSparseMap
DisjointSet ds
SparseMap::operation_hints last_ins
SparseMap sparseToDenseMap
Friends
template<typename TupleType >
class EquivalenceRelation
Detailed Description
template<typename SparseDomain>
class souffle::SparseDisjointSet< SparseDomain >
Definition at line 252 of file UnionFind.h.
Member Typedef Documentation
DenseMap
template<typename SparseDomain> using souffle::SparseDisjointSet< SparseDomain >::DenseMap = RandomInsertPiggyList<SparseDomain> private
Definition at line 261 of file UnionFind.h.
PairStore
template<typename SparseDomain> using souffle::SparseDisjointSet< SparseDomain >::PairStore = std::pair<SparseDomain, parent_t> private
Definition at line 258 of file UnionFind.h.
SparseMap
template<typename SparseDomain> using souffle::SparseDisjointSet< SparseDomain >::SparseMap = LambdaBTreeSet<PairStore, std::function<parent_t(PairStore&)>, EqrelMapComparator<PairStore> > private
Definition at line 260 of file UnionFind.h.
Constructor & Destructor Documentation
SparseDisjointSet() [1/3]
template<typename SparseDomain> souffle::SparseDisjointSet< SparseDomain >::SparseDisjointSet () default
SparseDisjointSet() [2/3]
template<typename SparseDomain> souffle::SparseDisjointSet< SparseDomain >::SparseDisjointSet (SparseDisjointSet< SparseDomain > & other) delete
SparseDisjointSet() [3/3]
template<typename SparseDomain> souffle::SparseDisjointSet< SparseDomain >::SparseDisjointSet (SparseDisjointSet< SparseDomain > && other) delete
Member Function Documentation
clear()
template<typename SparseDomain> void souffle::SparseDisjointSet< SparseDomain >::clear () inline
Remove all elements from this disjoint set.
Definition at line 332 of file UnionFind.h.
Referenced by souffle::EquivalenceRelation< t_tuple< 2 > >::clear().
                  {
         ds.clear();
         sparseToDenseMap.clear();
         denseToSparseMap.clear();
     }
contains()
template<typename SparseDomain> bool souffle::SparseDisjointSet< SparseDomain >::contains (SparseDomain v1, SparseDomain v2) inline
Definition at line 349 of file UnionFind.h.
Referenced by souffle::EquivalenceRelation< t_tuple< 2 > >::contains(), souffle::EquivalenceRelation< t_tuple< 2 > >::getBoundaries(), souffle::EquivalenceRelation< t_tuple< 2 > >::lower_bound(), and souffle::test::TEST().
{
         if (nodeExists(v1) && nodeExists(v2)) {
             return sameSet(v1, v2);
         }
         return false;
     }
findNode()
template<typename SparseDomain> SparseDomain souffle::SparseDisjointSet< SparseDomain >::findNode (SparseDomain x) inline
Definition at line 317 of file UnionFind.h.
Referenced by souffle::EquivalenceRelation< t_tuple< 2 > >::anteriorIt(), souffle::EquivalenceRelation< t_tuple< 2 > >::antpostit(), souffle::EquivalenceRelation< t_tuple< 2 > >::closure(), souffle::EquivalenceRelation< t_tuple< 2 > >::extend(), and souffle::EquivalenceRelation< t_tuple< 2 > >::genAllDisjointSetLists().
{
         return toSparse(ds.findNode(toDense(x)));
     };
makeNode()
template<typename SparseDomain> void souffle::SparseDisjointSet< SparseDomain >::makeNode (SparseDomain val) inline
Definition at line 339 of file UnionFind.h.
Referenced by souffle::test::TEST().
{
         // dense has the behaviour of creating if not exists.
         toDense(val);
     };
nodeExists()
template<typename SparseDomain> bool souffle::SparseDisjointSet< SparseDomain >::nodeExists (const SparseDomain val) const inline
Definition at line 345 of file UnionFind.h.
Referenced by souffle::EquivalenceRelation< t_tuple< 2 > >::containsElement(), souffle::EquivalenceRelation< t_tuple< 2 > >::getBoundaries(), and souffle::EquivalenceRelation< t_tuple< 2 > >::lower_bound().
{
         return sparseToDenseMap.contains({val, -1});
     };
operator=() [1/2]
template<typename SparseDomain> SparseDisjointSet& souffle::SparseDisjointSet< SparseDomain >::operator= (SparseDisjointSet< SparseDomain > & other) delete
operator=() [2/2]
template<typename SparseDomain> SparseDisjointSet& souffle::SparseDisjointSet< SparseDomain >::operator= (SparseDisjointSet< SparseDomain > && other) delete
sameSet()
template<typename SparseDomain> bool souffle::SparseDisjointSet< SparseDomain >::sameSet (SparseDomain x, SparseDomain y) inline
Definition at line 313 of file UnionFind.h.
Referenced by souffle::EquivalenceRelation< t_tuple< 2 > >::antpostit().
{
         return ds.sameSet(toDense(x), toDense(y));
     };
size()
template<typename SparseDomain> std::size_t souffle::SparseDisjointSet< SparseDomain >::size () inline
Definition at line 325 of file UnionFind.h.
Referenced by souffle::test::TEST().
{
         return ds.size();
     };
toDense()
template<typename SparseDomain> parent_t souffle::SparseDisjointSet< SparseDomain >::toDense (const SparseDomain in) inline
Retrieve dense encoding, adding it in if non-existent.
Parameters
in the sparse value
Returns
the corresponding dense value
Definition at line 275 of file UnionFind.h.
Referenced by souffle::test::TEST().
{
         // insert into the mapping - if the key doesn't exist (in), the function will be called
         // and a dense value will be created for it
         PairStore p = {in, -1};
         return sparseToDenseMap.insert(p, [&](PairStore& p) {
             parent_t c2 = DisjointSet::b2p(this->ds.makeNode());
             this->denseToSparseMap.insertAt(c2, p.first);
             p.second = c2;
             return c2;
         });
     }
toSparse()
template<typename SparseDomain> const SparseDomain souffle::SparseDisjointSet< SparseDomain >::toSparse (const parent_t in) const inline
For the given dense value, return the associated sparse value Undefined behaviour if dense value not in set.
Parameters
in the supplied dense value
Returns
the sparse value from the denseToSparseMap
Definition at line 308 of file UnionFind.h.
Referenced by souffle::EquivalenceRelation< t_tuple< 2 > >::genAllDisjointSetLists().
{
         return denseToSparseMap.get(in);
     };
unionNodes()
template<typename SparseDomain> void souffle::SparseDisjointSet< SparseDomain >::unionNodes (SparseDomain x, SparseDomain y) inline
Definition at line 321 of file UnionFind.h.
Referenced by souffle::EquivalenceRelation< t_tuple< 2 > >::insert(), souffle::EquivalenceRelation< t_tuple< 2 > >::insertAll(), and souffle::test::TEST().
{
         ds.unionNodes(toDense(x), toDense(y));
     };
Friends And Related Function Documentation
EquivalenceRelation
template<typename SparseDomain> template<typename TupleType > friend class EquivalenceRelation friend
Definition at line 256 of file UnionFind.h.
Field Documentation
denseToSparseMap
template<typename SparseDomain> DenseMap souffle::SparseDisjointSet< SparseDomain >::denseToSparseMap private
Definition at line 267 of file UnionFind.h.
ds
template<typename SparseDomain> DisjointSet souffle::SparseDisjointSet< SparseDomain >::ds private
Definition at line 253 of file UnionFind.h.
Referenced by souffle::EquivalenceRelation< t_tuple< 2 > >::genAllDisjointSetLists().
last_ins
template<typename SparseDomain> SparseMap::operation_hints souffle::SparseDisjointSet< SparseDomain >::last_ins private
Definition at line 263 of file UnionFind.h.
sparseToDenseMap
template<typename SparseDomain> SparseMap souffle::SparseDisjointSet< SparseDomain >::sparseToDenseMap private
Definition at line 265 of file UnionFind.h.
Referenced by souffle::EquivalenceRelation< t_tuple< 2 > >::extend().
The documentation for this class was generated from the following file:
UnionFind.h