souffle: souffle::profile::EventProcessorSingleton Class Reference
souffle::profile::EventProcessorSingleton Class Reference
Event Processor Singleton.
#include <EventProcessor.h>
Public Member Functions
void process (ProfileDatabase &db, const char *txt,...)
process a profile event
void registerEventProcessor (const std::string &keyword, EventProcessor *processor)
register an event processor with its keyword
Static Public Member Functions
static EventProcessorSingleton & instance ()
get instance
Private Member Functions
std::string escape (const std::string &text)
Escape escape characters.
EventProcessorSingleton ()=default
Static Private Member Functions
static std::vector< std::string > split (std::string str, std::string split_str)
split string
static std::vector< std::string > splitSignature (std::string str)
split string separated by semi-colon
Private Attributes
std::map< std::string, EventProcessor * > registry
keyword / event processor mapping
Detailed Description
Event Processor Singleton.
Singleton that is the connection point for events
Definition at line 53 of file EventProcessor.h.
Constructor & Destructor Documentation
EventProcessorSingleton()
souffle::profile::EventProcessorSingleton::EventProcessorSingleton () private default
Member Function Documentation
escape()
std::string souffle::profile::EventProcessorSingleton::escape (const std::string & text) inline private
Escape escape characters.
Remove all escapes, then escape double quotes.
Definition at line 97 of file EventProcessor.h.
References str.
{
         std::string str(text);
         size_t start_pos = 0;
         // replace backslashes with double backslash
         while ((start_pos = str.find('\\', start_pos)) != std::string::npos) {
             if (start_pos == str.size()) {
                 break;
             }
             ++start_pos;
             if (str[start_pos] == 't' || str[start_pos] == '"' || str[start_pos] == '\\' ||
                     str[start_pos] == 'n' || str[start_pos] == ';') {
                 continue;
             }
             str.replace(start_pos - 1, 1, "\\\\");
             ++start_pos;
         }
         return str;
     }
instance()
static EventProcessorSingleton& souffle::profile::EventProcessorSingleton::instance () inline static
get instance
Definition at line 56 of file EventProcessor.h.
Referenced by souffle::profile::ConfigProcessor::ConfigProcessor(), souffle::profile::FrequencyAtomProcessor::FrequencyAtomProcessor(), souffle::ProfileEventSingleton::makeConfigRecord(), souffle::ProfileEventSingleton::makeQuantityEvent(), souffle::ProfileEventSingleton::makeTimeEvent(), souffle::ProfileEventSingleton::makeTimingEvent(), souffle::ProfileEventSingleton::makeUtilisationEvent(), souffle::profile::NonRecursiveRelationNumberProcessor::NonRecursiveRelationNumberProcessor(), souffle::profile::NonRecursiveRelationTimingProcessor::NonRecursiveRelationTimingProcessor(), souffle::profile::NonRecursiveRuleNumberProcessor::NonRecursiveRuleNumberProcessor(), souffle::profile::NonRecursiveRuleTimingProcessor::NonRecursiveRuleTimingProcessor(), souffle::profile::ProgramResourceUtilisationProcessor::ProgramResourceUtilisationProcessor(), souffle::profile::ProgramRuntimeProcessor::ProgramRuntimeProcessor(), souffle::profile::ProgramTimepointProcessor::ProgramTimepointProcessor(), souffle::profile::RecursiveRelationCopyTimingProcessor::RecursiveRelationCopyTimingProcessor(), souffle::profile::RecursiveRelationNumberProcessor::RecursiveRelationNumberProcessor(), souffle::profile::RecursiveRelationTimingProcessor::RecursiveRelationTimingProcessor(), souffle::profile::RecursiveRuleNumberProcessor::RecursiveRuleNumberProcessor(), souffle::profile::RecursiveRuleTimingProcessor::RecursiveRuleTimingProcessor(), souffle::profile::RelationIOTimingProcessor::RelationIOTimingProcessor(), souffle::profile::RelationReadsProcessor::RelationReadsProcessor(), and souffle::profile::TextProcessor::TextProcessor().
{
         static EventProcessorSingleton singleton;
         return singleton;
     }
process()
void souffle::profile::EventProcessorSingleton::process (ProfileDatabase & db, const char * txt, ...) inline
process a profile event
Definition at line 67 of file EventProcessor.h.
References souffle::escape().
Referenced by souffle::ProfileEventSingleton::makeConfigRecord(), souffle::ProfileEventSingleton::makeQuantityEvent(), souffle::ProfileEventSingleton::makeTimeEvent(), souffle::ProfileEventSingleton::makeTimingEvent(), and souffle::ProfileEventSingleton::makeUtilisationEvent().
{
         va_list args;
         va_start(args, txt);
         // escape signature
         std::string escapedText = escape(txt);
         // obtain event signature by splitting event text
         std::vector<std::string> eventSignature = splitSignature(escapedText);
         // invoke the event processor of the event
         const std::string& keyword = eventSignature[0];
         assert(eventSignature.size() > 0 && "no keyword in event description");
         assert(registry.find(keyword) != registry.end() && "EventProcessor not found!");
         registry[keyword]->process(db, eventSignature, args);
         // terminate access to variadic arguments
         va_end(args);
     }
registerEventProcessor()
void souffle::profile::EventProcessorSingleton::registerEventProcessor (const std::string & keyword, EventProcessor * processor) inline
register an event processor with its keyword
Definition at line 62 of file EventProcessor.h.
Referenced by souffle::profile::ConfigProcessor::ConfigProcessor(), souffle::profile::FrequencyAtomProcessor::FrequencyAtomProcessor(), souffle::profile::NonRecursiveRelationNumberProcessor::NonRecursiveRelationNumberProcessor(), souffle::profile::NonRecursiveRelationTimingProcessor::NonRecursiveRelationTimingProcessor(), souffle::profile::NonRecursiveRuleNumberProcessor::NonRecursiveRuleNumberProcessor(), souffle::profile::NonRecursiveRuleTimingProcessor::NonRecursiveRuleTimingProcessor(), souffle::profile::ProgramResourceUtilisationProcessor::ProgramResourceUtilisationProcessor(), souffle::profile::ProgramRuntimeProcessor::ProgramRuntimeProcessor(), souffle::profile::ProgramTimepointProcessor::ProgramTimepointProcessor(), souffle::profile::RecursiveRelationCopyTimingProcessor::RecursiveRelationCopyTimingProcessor(), souffle::profile::RecursiveRelationNumberProcessor::RecursiveRelationNumberProcessor(), souffle::profile::RecursiveRelationTimingProcessor::RecursiveRelationTimingProcessor(), souffle::profile::RecursiveRuleNumberProcessor::RecursiveRuleNumberProcessor(), souffle::profile::RecursiveRuleTimingProcessor::RecursiveRuleTimingProcessor(), souffle::profile::RelationIOTimingProcessor::RelationIOTimingProcessor(), souffle::profile::RelationReadsProcessor::RelationReadsProcessor(), and souffle::profile::TextProcessor::TextProcessor().
{
         registry[keyword] = processor;
     }
split()
static std::vector<std::string> souffle::profile::EventProcessorSingleton::split (std::string str, std::string split_str) inline static private
split string
Definition at line 117 of file EventProcessor.h.
References i, and j.
{
         // repeat value when splitting so "a   b" -> ["a","b"] not ["a","","","","b"]
         bool repeat = (split_str == " ");
         std::vector<std::string> elems;
         std::string temp;
         std::string hold;
         for (size_t i = 0; i < str.size(); i++) {
             if (repeat) {
                 if (str.at(i) == split_str.at(0)) {
                     while (str.at(++i) == split_str.at(0)) {
                         ;  // set i to be at the end of the search string
                     }
                     elems.push_back(temp);
                     temp = "";
                 }
                 temp += str.at(i);
             } else {
                 temp += str.at(i);
                 hold += str.at(i);
                 for (size_t j = 0; j < hold.size(); j++) {
                     if (hold[j] != split_str[j]) {
                         hold = "";
                     }
                 }
                 if (hold.size() == split_str.size()) {
                     elems.push_back(temp.substr(0, temp.size() - hold.size()));
                     hold = "";
                     temp = "";
                 }
             }
         }
         if (!temp.empty()) {
             elems.push_back(temp);
         }
         return elems;
     }
splitSignature()
static std::vector<std::string> souffle::profile::EventProcessorSingleton::splitSignature (std::string str) inline static private
split string separated by semi-colon
Definition at line 158 of file EventProcessor.h.
References i, j, and souffle::split().
{
         for (size_t i = 0; i < str.size(); i++) {
             if (i > 0 && str[i] == ';' && str[i - 1] == '\\') {
                 // I'm assuming this isn't a thing that will be naturally found in souffle profiler files
                 str[i - 1] = '\b';
                 str.erase(i--, 1);
             }
         }
         std::vector<std::string> result = split(str, ";");
         for (auto& i : result) {
             for (char& j : i) {
                 if (j == '\b') {
                     j = ';';
                 }
             }
         }
         return result;
     }
Field Documentation
registry
std::map<std::string, EventProcessor*> souffle::profile::EventProcessorSingleton::registry private
keyword / event processor mapping
Definition at line 88 of file EventProcessor.h.
The documentation for this class was generated from the following file:
EventProcessor.h