souffle: souffle::ReorderConditionsTransformer Class Reference
souffle::ReorderConditionsTransformer Class Reference
Reorders conjunctive terms depending on cost, i.e., cheap terms should be executed first.
#include <ReorderConditions.h>
Public Member Functions
std::string getName () const override
get name of the transformer
bool reorderConditions (RamProgram &program)
Reorder conjunctive terms in filter operations.
Public Member Functions inherited from souffle::RamTransformer
bool apply (RamTranslationUnit &translationUnit)
apply the transformer to a translation unit translationUnit that will be transformed.
virtual ~RamTransformer ()=default
Protected Member Functions
bool transform (RamTranslationUnit &translationUnit) override
transform the translation unit / used by apply translationUnit that will be transformed.
Protected Attributes
RamComplexityAnalysis * rca {nullptr}
Detailed Description
Reorders conjunctive terms depending on cost, i.e., cheap terms should be executed first.
For example ..
QUERY
 ...
  IF C(1) /\ C(2) /\ ... /\ C(N) then
   ...
will be rewritten to
QUERY
 ...
  IF C(i(1)) /\ C(i(2)) /\ ... /\ C(i(N)) then
    ...
where C(i(1)) <= C(i(2)) <= .... <= C(i(N)).
The terms are sorted according to their complexity class.
Definition at line 55 of file ReorderConditions.h.
Member Function Documentation
getName()
std::string souffle::ReorderConditionsTransformer::getName () const inline override virtual
get name of the transformer
Implements souffle::RamTransformer.
Definition at line 57 of file ReorderConditions.h.
References reorderConditions().
{
         return "ReorderConditionsTransformer";
     }
reorderConditions()
bool souffle::ReorderConditionsTransformer::reorderConditions (RamProgram & program)
Reorder conjunctive terms in filter operations.
Parameters
program Program that is transformed
Returns
Flag showing whether the program has been changed by the transformation
Definition at line 32 of file ReorderConditions.cpp.
References souffle::RamTransformer::apply(), b, souffle::clone(), souffle::filter(), souffle::RamComplexityAnalysis::getComplexity(), souffle::makeLambdaRamMapper(), rca, souffle::toCondition(), souffle::toConjunctionList(), and souffle::visitDepthFirst().
Referenced by getName(), and transform().
{
     bool changed = false;
     visitDepthFirst(program, [&](const RamQuery& query) {
         std::function<std::unique_ptr<RamNode>(std::unique_ptr<RamNode>)> filterRewriter =
                 [&](std::unique_ptr<RamNode> node) -> std::unique_ptr<RamNode> {
             if (const RamFilter* filter = dynamic_cast<RamFilter*>(node.get())) {
                 const RamCondition* condition = &filter->getCondition();
                 std::vector<std::unique_ptr<RamCondition>> sortedConds;
                 std::vector<std::unique_ptr<RamCondition>> condList = toConjunctionList(condition);
                 for (auto& cond : condList) {
                     sortedConds.emplace_back(cond->clone());
                 }
                 std::sort(sortedConds.begin(), sortedConds.end(),
                         [&](std::unique_ptr<RamCondition>& a, std::unique_ptr<RamCondition>& b) {
                             return rca->getComplexity(a.get()) < rca->getComplexity(b.get());
                         });
                 if (!std::equal(sortedConds.begin(), sortedConds.end(), condList.begin(),
                             [](std::unique_ptr<RamCondition>& a, std::unique_ptr<RamCondition>& b) {
                                 return *a == *b;
                             })) {
                     changed = true;
                     node = std::make_unique<RamFilter>(
                             std::unique_ptr<RamCondition>(toCondition(sortedConds)),
                             souffle::clone(&filter->getOperation()));
                 }
             }
             node->apply(makeLambdaRamMapper(filterRewriter));
             return node;
         };
         const_cast<RamQuery*>(&query)->apply(makeLambdaRamMapper(filterRewriter));
     });
     return changed;
 }
transform()
bool souffle::ReorderConditionsTransformer::transform (RamTranslationUnit & translationUnit) inline override protected virtual
transform the translation unit / used by apply translationUnit that will be transformed.
flag reporting whether the RAM program has changed
Implements souffle::RamTransformer.
Definition at line 72 of file ReorderConditions.h.
References souffle::RamTranslationUnit::getAnalysis(), souffle::RamTranslationUnit::getProgram(), rca, and reorderConditions().
{
         rca = translationUnit.getAnalysis<RamComplexityAnalysis>();
         return reorderConditions(translationUnit.getProgram());
     }
Field Documentation
rca
RamComplexityAnalysis* souffle::ReorderConditionsTransformer::rca {nullptr} protected
Definition at line 70 of file ReorderConditions.h.
Referenced by reorderConditions(), and transform().
The documentation for this class was generated from the following files:
ram/transform/ReorderConditions.h
ram/transform/ReorderConditions.cpp