souffle: souffle::profile::Table Class Reference
souffle::profile::Table Class Reference
#include <Table.h>
Public Member Functions
void addRow (std::shared_ptr< Row > row)
std::vector< std::shared_ptr< Row > > getRows ()
void sort (int col_num)
Table ()
Data Fields
std::vector< std::shared_ptr< Row > > rows
Detailed Description
Definition at line 23 of file Table.h.
Constructor & Destructor Documentation
Table()
souffle::profile::Table::Table () inline
Definition at line 27 of file Table.h.
 : rows() {}
Member Function Documentation
addRow()
void souffle::profile::Table::addRow (std::shared_ptr< Row > row) inline
Definition at line 29 of file Table.h.
Referenced by souffle::profile::OutputProcessor::getAtomTable(), souffle::profile::OutputProcessor::getRelTable(), souffle::profile::OutputProcessor::getRulTable(), souffle::profile::OutputProcessor::getSubrulTable(), souffle::profile::OutputProcessor::getVersionAtoms(), and souffle::profile::OutputProcessor::getVersions().
{
         rows.push_back(row);
     }
getRows()
std::vector<std::shared_ptr<Row> > souffle::profile::Table::getRows () inline
Definition at line 33 of file Table.h.
References rows.
Referenced by souffle::profile::Tools::formatTable(), genJsonAtoms(), souffle::profile::Tui::genJsonRelations(), and souffle::genJsonRules().
{
         return rows;
     }
sort()
void souffle::profile::Table::sort (int col_num) inline
Definition at line 37 of file Table.h.
References souffle::profile::DataComparator::C_T(), souffle::profile::DataComparator::ID(), souffle::profile::DataComparator::NAME(), souffle::profile::DataComparator::NR_T(), souffle::profile::DataComparator::R_T(), souffle::profile::DataComparator::TIME(), and souffle::profile::DataComparator::TUP().
Referenced by genJsonAtoms().
{
         switch (col_num) {
             case 1:
                 std::sort(rows.begin(), rows.end(), DataComparator::NR_T);
                 break;
             case 2:
                 std::sort(rows.begin(), rows.end(), DataComparator::R_T);
                 break;
             case 3:
                 std::sort(rows.begin(), rows.end(), DataComparator::C_T);
                 break;
             case 4:
                 std::sort(rows.begin(), rows.end(), DataComparator::TUP);
                 break;
             case 5:
                 std::sort(rows.begin(), rows.end(), DataComparator::ID);
                 break;
             case 6:
                 std::sort(rows.begin(), rows.end(), DataComparator::NAME);
                 break;
             case 0:
             default:  // if the col_num isn't defined use TIME
                 std::sort(rows.begin(), rows.end(), DataComparator::TIME);
                 break;
         }
     }
Field Documentation
rows
std::vector<std::shared_ptr<Row> > souffle::profile::Table::rows
Definition at line 25 of file Table.h.
Referenced by genJsonAtoms(), and getRows().
The documentation for this class was generated from the following file:
profile/Table.h