souffle: souffle::ConstConstraint Class Reference
souffle::ConstConstraint Class Reference
Constant constraints for values in query command.
#include <ExplainProvenance.h>
Public Member Functions
ConstConstraint ()=default
Constructor.
std::vector< std::pair< std::pair< size_t, size_t >, RamDomain > > & getConstraints ()
Get the constant constraint vector.
const std::vector< std::pair< std::pair< size_t, size_t >, RamDomain > > & getConstraints () const
void push_back (std::pair< std::pair< size_t, size_t >, RamDomain > constr)
Add constant constraint at the end of constConstrs vector.
bool verify (const std::vector< tuple > &product) const
Verify if the query product satisfies constant constraint.
~ConstConstraint ()=default
Destructor.
Private Attributes
std::vector< std::pair< std::pair< size_t, size_t >, RamDomain > > constConstrs
Detailed Description
Constant constraints for values in query command.
Definition at line 106 of file ExplainProvenance.h.
Constructor & Destructor Documentation
ConstConstraint()
souffle::ConstConstraint::ConstConstraint () default
Constructor.
~ConstConstraint()
souffle::ConstConstraint::~ConstConstraint () default
Destructor.
Member Function Documentation
getConstraints() [1/2]
std::vector<std::pair<std::pair<size_t, size_t>, RamDomain> >& souffle::ConstConstraint::getConstraints () inline
Get the constant constraint vector.
Definition at line 127 of file ExplainProvenance.h.
Referenced by souffle::ExplainProvenanceImpl::queryProcess().
{
         return constConstrs;
     }
getConstraints() [2/2]
const std::vector<std::pair<std::pair<size_t, size_t>, RamDomain> >& souffle::ConstConstraint::getConstraints () const inline
Definition at line 131 of file ExplainProvenance.h.
{
         return constConstrs;
     }
push_back()
void souffle::ConstConstraint::push_back (std::pair< std::pair< size_t, size_t >, RamDomain > constr) inline
Add constant constraint at the end of constConstrs vector.
Definition at line 115 of file ExplainProvenance.h.
Referenced by souffle::ExplainProvenanceImpl::queryProcess().
{
         constConstrs.push_back(constr);
     }
verify()
bool souffle::ConstConstraint::verify (const std::vector< tuple > & product) const inline
Verify if the query product satisfies constant constraint.
Definition at line 120 of file ExplainProvenance.h.
References souffle::all_of().
Referenced by souffle::ExplainProvenanceImpl::findQuerySolution().
{
         return std::all_of(constConstrs.begin(), constConstrs.end(), [&product](auto constr) {
             return product[constr.first.first][constr.first.second] == constr.second;
         });
     }
Field Documentation
constConstrs
std::vector<std::pair<std::pair<size_t, size_t>, RamDomain> > souffle::ConstConstraint::constConstrs private
Definition at line 136 of file ExplainProvenance.h.
The documentation for this class was generated from the following file:
ExplainProvenance.h