souffle: souffle::RemoveBooleanConstraintsTransformer Class Reference
souffle::RemoveBooleanConstraintsTransformer Class Reference
Transformation pass to remove constant boolean constraints Should be called after any transformation that may generate boolean constraints.
#include <RemoveBooleanConstraints.h>
Public Member Functions
RemoveBooleanConstraintsTransformer * clone () const override
std::string getName () const override
Public Member Functions inherited from souffle::AstTransformer
bool apply (AstTranslationUnit &translationUnit)
virtual ~AstTransformer ()=default
Private Member Functions
bool transform (AstTranslationUnit &translationUnit) override
Detailed Description
Transformation pass to remove constant boolean constraints Should be called after any transformation that may generate boolean constraints.
Definition at line 28 of file RemoveBooleanConstraints.h.
Member Function Documentation
clone()
RemoveBooleanConstraintsTransformer* souffle::RemoveBooleanConstraintsTransformer::clone () const inline override virtual
Implements souffle::AstTransformer.
Definition at line 34 of file RemoveBooleanConstraints.h.
References transform().
{
         return new RemoveBooleanConstraintsTransformer();
     }
getName()
std::string souffle::RemoveBooleanConstraintsTransformer::getName () const inline override virtual
Implements souffle::AstTransformer.
Definition at line 30 of file RemoveBooleanConstraints.h.
{
         return "RemoveBooleanConstraintsTransformer";
     }
transform()
bool souffle::RemoveBooleanConstraintsTransformer::transform (AstTranslationUnit & translationUnit) override private virtual
Implements souffle::AstTransformer.
Definition at line 38 of file RemoveBooleanConstraints.cpp.
References souffle::AstProgram::addClause(), souffle::AstProgram::apply(), souffle::clone(), souffle::cloneHead(), souffle::EQ, souffle::getClauses(), souffle::AstTranslationUnit::getProgram(), souffle::AstProgram::getRelations(), souffle::AstProgram::removeClause(), and souffle::visitDepthFirst().
Referenced by clone().
{
     AstProgram& program = *translationUnit.getProgram();
     // If any boolean constraints exist, they will be removed
     bool changed = false;
     visitDepthFirst(program, [&](const AstBooleanConstraint&) { changed = true; });
     // Remove true and false constant literals from all aggregators
     struct removeBools : public AstNodeMapper {
         std::unique_ptr<AstNode> operator()(std::unique_ptr<AstNode> node) const override {
             // Remove them from child nodes
             node->apply(*this);
             if (auto* aggr = dynamic_cast<AstAggregator*>(node.get())) {
                 bool containsTrue = false;
                 bool containsFalse = false;
                 // Check if aggregator body contains booleans.
                 for (AstLiteral* lit : aggr->getBodyLiterals()) {
                     if (auto* bc = dynamic_cast<AstBooleanConstraint*>(lit)) {
                         if (bc->isTrue()) {
                             containsTrue = true;
                         } else {
                             containsFalse = true;
                         }
                     }
                 }
                 // Only keep literals that aren't boolean constraints
                 if (containsFalse || containsTrue) {
                     auto replacementAggregator = souffle::clone(aggr);
                     std::vector<std::unique_ptr<AstLiteral>> newBody;
                     bool isEmpty = true;
                     // Don't bother copying over body literals if any are false
                     if (!containsFalse) {
                         for (AstLiteral* lit : aggr->getBodyLiterals()) {
                             // Don't add in boolean constraints
                             if (dynamic_cast<AstBooleanConstraint*>(lit) == nullptr) {
                                 isEmpty = false;
                                 newBody.push_back(souffle::clone(lit));
                             }
                         }
                         // If the body is still empty and the original body contains true add it now.
                         if (containsTrue && isEmpty) {
                             newBody.push_back(std::make_unique<AstBinaryConstraint>(BinaryConstraintOp::EQ,
                                     std::make_unique<AstNumericConstant>(1),
                                     std::make_unique<AstNumericConstant>(1)));
                             isEmpty = false;
                         }
                     }
                     if (containsFalse || isEmpty) {
                         // Empty aggregator body!
                         // Not currently handled, so add in a false literal in the body
                         // E.g. max x : { } =becomes=> max 1 : {0 = 1}
                         newBody.push_back(std::make_unique<AstBinaryConstraint>(BinaryConstraintOp::EQ,
                                 std::make_unique<AstNumericConstant>(0),
                                 std::make_unique<AstNumericConstant>(1)));
                     }
                     replacementAggregator->setBody(std::move(newBody));
                     return replacementAggregator;
                 }
             }
             // no false or true, so return the original node
             return node;
         }
     };
     removeBools update;
     program.apply(update);
     // Remove true and false constant literals from all clauses
     for (AstRelation* rel : program.getRelations()) {
         for (AstClause* clause : getClauses(program, *rel)) {
             bool containsTrue = false;
             bool containsFalse = false;
             for (AstLiteral* lit : clause->getBodyLiterals()) {
                 if (auto* bc = dynamic_cast<AstBooleanConstraint*>(lit)) {
                     bc->isTrue() ? containsTrue = true : containsFalse = true;
                 }
             }
             if (containsFalse) {
                 // Clause will always fail
                 program.removeClause(clause);
             } else if (containsTrue) {
                 auto replacementClause = std::unique_ptr<AstClause>(cloneHead(clause));
                 // Only keep non-'true' literals
                 for (AstLiteral* lit : clause->getBodyLiterals()) {
                     if (dynamic_cast<AstBooleanConstraint*>(lit) == nullptr) {
                         replacementClause->addToBody(souffle::clone(lit));
                     }
                 }
                 program.removeClause(clause);
                 program.addClause(std::move(replacementClause));
             }
         }
     }
     return changed;
 }
The documentation for this class was generated from the following files:
ast/transform/RemoveBooleanConstraints.h
ast/transform/RemoveBooleanConstraints.cpp