souffle: souffle::AstExecutionOrder Class Reference
souffle::AstExecutionOrder Class Reference
An execution order for atoms within a clause.
#include <ExecutionOrder.h>
Public Types
using ExecOrder = std::vector< unsigned int >
Public Member Functions
AstExecutionOrder (ExecOrder order={}, SrcLocation loc={})
AstExecutionOrder * clone () const override
Create a clone (i.e.
const ExecOrder & getOrder () const
get order
Public Member Functions inherited from souffle::AstNode
virtual void apply (const AstNodeMapper &)
Apply the mapper to all child nodes.
AstNode (SrcLocation loc={})
std::string extloc () const
Return source location of the syntactic element.
virtual std::vector< const AstNode * > getChildNodes () const
Obtain a list of all embedded AST child nodes.
const SrcLocation & getSrcLoc () const
Return source location of the AstNode.
bool operator!= (const AstNode &other) const
Inequality check for two AST nodes.
bool operator== (const AstNode &other) const
Equivalence check for two AST nodes.
void setSrcLoc (SrcLocation l)
Set source location for the AstNode.
virtual ~AstNode ()=default
Protected Member Functions
bool equal (const AstNode &node) const override
Abstract equality check for two AST nodes.
void print (std::ostream &out) const override
Output to a given output stream.
Private Attributes
ExecOrder order
literal order of body (starting from 1)
Detailed Description
An execution order for atoms within a clause.
Definition at line 32 of file ExecutionOrder.h.
Member Typedef Documentation
ExecOrder
using souffle::AstExecutionOrder::ExecOrder = std::vector<unsigned int>
Definition at line 34 of file ExecutionOrder.h.
Constructor & Destructor Documentation
AstExecutionOrder()
souffle::AstExecutionOrder::AstExecutionOrder (ExecOrder order = {}, SrcLocation loc = {}) inline
Definition at line 36 of file ExecutionOrder.h.
References order, and souffle::AstNode::setSrcLoc().
Referenced by clone().
                                         {}, SrcLocation loc = {}) : order(std::move(order)) {
         setSrcLoc(std::move(loc));
     }
Member Function Documentation
clone()
AstExecutionOrder* souffle::AstExecutionOrder::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::AstNode.
Definition at line 45 of file ExecutionOrder.h.
References AstExecutionOrder(), souffle::AstNode::getSrcLoc(), and order.
{
         return new AstExecutionOrder(order, getSrcLoc());
     }
equal()
bool souffle::AstExecutionOrder::equal (const AstNode &) const inline override protected virtual
Abstract equality check for two AST nodes.
Reimplemented from souffle::AstNode.
Definition at line 54 of file ExecutionOrder.h.
References order.
{
         const auto& other = static_cast<const AstExecutionOrder&>(node);
         return order == other.order;
     }
getOrder()
const ExecOrder& souffle::AstExecutionOrder::getOrder () const inline
get order
Definition at line 41 of file ExecutionOrder.h.
References order.
{
         return order;
     }
print()
void souffle::AstExecutionOrder::print (std::ostream & os) const inline override protected virtual
Output to a given output stream.
Implements souffle::AstNode.
Definition at line 50 of file ExecutionOrder.h.
References souffle::join(), and order.
{
         out << "(" << join(order) << ")";
     }
Field Documentation
order
ExecOrder souffle::AstExecutionOrder::order private
literal order of body (starting from 1)
Definition at line 61 of file ExecutionOrder.h.
Referenced by AstExecutionOrder(), clone(), equal(), getOrder(), and print().
The documentation for this class was generated from the following file:
ast/ExecutionOrder.h