souffle: souffle::SpinLock Class Reference
souffle::SpinLock Class Reference
A 'sequential' non-locking implementation for a spin lock.
#include <ParallelUtil.h>
Public Member Functions
void lock ()
SpinLock ()=default
bool try_lock ()
void unlock ()
Detailed Description
A 'sequential' non-locking implementation for a spin lock.
Definition at line 487 of file ParallelUtil.h.
Constructor & Destructor Documentation
SpinLock()
souffle::SpinLock::SpinLock () default
Member Function Documentation
lock()
void souffle::SpinLock::lock () inline
Definition at line 491 of file ParallelUtil.h.
Referenced by souffle::RandomInsertPiggyList< SparseDomain >::freeList(), souffle::PiggyList< std::atomic< block_t > >::freeList(), souffle::RandomInsertPiggyList< SparseDomain >::insertAt(), and souffle::test::TEST().
 {}
try_lock()
bool souffle::SpinLock::try_lock () inline
Definition at line 493 of file ParallelUtil.h.
                     {
         return true;
     }
unlock()
void souffle::SpinLock::unlock () inline
Definition at line 497 of file ParallelUtil.h.
Referenced by souffle::RandomInsertPiggyList< SparseDomain >::freeList(), souffle::PiggyList< std::atomic< block_t > >::freeList(), souffle::RandomInsertPiggyList< SparseDomain >::insertAt(), and souffle::test::TEST().
 {}
The documentation for this class was generated from the following file:
utility/ParallelUtil.h