souffle: souffle::TypeConstraintsAnalysis Class Reference
souffle::TypeConstraintsAnalysis Class Reference
Constraint analysis framework for types.
Public Member Functions
TypeConstraintsAnalysis (const TypeEnvironment &typeEnv, const AstProgram &program)
Public Member Functions inherited from souffle::AstConstraintAnalysis< TypeVar >
solution_type analyse (const AstClause &clause, std::ostream *debugOutput=nullptr)
Runs this constraint analysis on the given clause.
Public Member Functions inherited from souffle::AstVisitor< void >
void operator() (const AstNode &node, Params... args)
The main entry for the user allowing visitors to be utilized as functions.
virtual void visit (const AstNode &node, Params... args)
The main entry for a visit process conducting the dispatching of a visit to the various sub-types of AstNodes.
virtual ~AstVisitor ()=default
A virtual destructor.
Private Member Functions
void collectConstraints (const AstClause &clause) override
void iterateOverAtom (const AstAtom &atom, std::function< void(const AstArgument &, const Type &)> map)
Utility function.
void visitAggregator (const AstAggregator &agg) override
void visitAtom (const AstAtom &atom) override
void visitBinaryConstraint (const AstBinaryConstraint &rel) override
void visitCounter (const AstCounter &counter) override
void visitFunctor (const AstFunctor &fun) override
void visitNegation (const AstNegation &cur) override
void visitNumericConstant (const AstNumericConstant &constant) override
void visitRecordInit (const AstRecordInit &record) override
void visitSink (const AstAtom &atom)
void visitStringConstant (const AstStringConstant &cnst) override
void visitTypeCast (const AstTypeCast &typeCast) override
Private Attributes
const AstProgram & program
std::set< const AstAtom * > sinks
const TypeEnvironment & typeEnv
Additional Inherited Members
Public Types inherited from souffle::AstConstraintAnalysis< TypeVar >
using constraint_type = std::shared_ptr< Constraint< TypeVar > >
using solution_type = std::map< const AstArgument *, value_type >
using value_type = typename TypeVar ::property_space::value_type
Protected Member Functions inherited from souffle::AstConstraintAnalysis< TypeVar >
void addConstraint (const constraint_type &constraint)
Adds another constraint to the internally maintained list of constraints.
TypeVar getVar (const AstArgument &arg)
A utility function mapping an AstArgument to its associated analysis variable.
TypeVar getVar (const AstArgument *arg)
A utility function mapping an AstArgument to its associated analysis variable.
Protected Member Functions inherited from souffle::AstVisitor< void >
LINK (SubsetType, Type)
LINK (RecordType, Type)
LINK (UnionType, Type)
LINK (Type, Node)
LINK (Argument, Node)
LINK (Literal, Node)
LINK (ComponentType, Node)
LINK (ComponentInit, Node)
LINK (Component, Node)
LINK (Program, Node)
LINK (Attribute, Node)
LINK (Clause, Node)
LINK (Relation, Node)
LINK (Pragma, Node)
virtual void visitNode (const AstNode &, Params...)
The base case for all visitors – if no more specific overload was defined.
Protected Attributes inherited from souffle::AstConstraintAnalysis< TypeVar >
Assignment< TypeVar > assignment
Problem< TypeVar > constraints
The list of constraints making underlying this analysis.
std::map< std::string, TypeVar > variables
A map mapping variables to unique instances to facilitate the unification of variables.
Detailed Description
Constraint analysis framework for types.
The analysis operates on the concept of sinks and sources. If the atom is negated or is a head then it's a sink, and we can only extract the kind constraint from it Otherwise it is a source, and the type of the element must be a subtype of source attribute.
Definition at line 558 of file Type.cpp.
Constructor & Destructor Documentation
TypeConstraintsAnalysis()
souffle::TypeConstraintsAnalysis::TypeConstraintsAnalysis (const TypeEnvironment & typeEnv, const AstProgram & program) inline
Definition at line 560 of file Type.cpp.
             : typeEnv(typeEnv), program(program) {}
Member Function Documentation
collectConstraints()
void souffle::TypeConstraintsAnalysis::collectConstraints (const AstClause & clause) inline override private virtual
Reimplemented from souffle::AstConstraintAnalysis< TypeVar >.
Definition at line 570 of file Type.cpp.
References souffle::AstClause::getHead(), and souffle::visitDepthFirstPreOrder().
{
         sinks.insert(clause.getHead());
         visitDepthFirstPreOrder(clause, *this);
     }
iterateOverAtom()
void souffle::TypeConstraintsAnalysis::iterateOverAtom (const AstAtom & atom, std::function< void(const AstArgument &, const Type &)> map) inline private
Utility function.
Iterate over atoms valid pairs of (argument, type-attribute) and apply procedure map for its side-effects.
Definition at line 744 of file Type.cpp.
References souffle::AstAtom::getArguments(), souffle::getAtomRelation(), souffle::TypeEnvironment::getType(), i, souffle::TypeEnvironment::isType(), and souffle::map().
{
         // get relation
         auto rel = getAtomRelation(&atom, &program);
         if (rel == nullptr) {
             return;  // error in input program
         }
         auto atts = rel->getAttributes();
         auto args = atom.getArguments();
         if (atts.size() != args.size()) {
             return;  // error in input program
         }
         for (size_t i = 0; i < atts.size(); i++) {
             const auto& typeName = atts[i]->getTypeName();
             if (typeEnv.isType(typeName)) {
                 map(*args[i], typeEnv.getType(typeName));
             }
         }
     }
visitAggregator()
void souffle::TypeConstraintsAnalysis::visitAggregator (const AstAggregator & agg) inline override private
Definition at line 723 of file Type.cpp.
References souffle::COUNT, souffle::Float, souffle::TypeEnvironment::getConstantNumericTypes(), souffle::TypeEnvironment::getConstantType(), souffle::AstAggregator::getOperator(), souffle::AstAggregator::getTargetExpression(), souffle::isSubtypeOf(), souffle::MEAN, and souffle::Signed.
{
         if (agg.getOperator() == AggregateOp::COUNT) {
             addConstraint(isSubtypeOf(getVar(agg), typeEnv.getConstantType(TypeAttribute::Signed)));
         } else if (agg.getOperator() == AggregateOp::MEAN) {
             addConstraint(isSubtypeOf(getVar(agg), typeEnv.getConstantType(TypeAttribute::Float)));
         } else {
             addConstraint(hasSuperTypeInSet(getVar(agg), typeEnv.getConstantNumericTypes()));
         }
         // If there is a target expression - it should be of the same type as the aggregator.
         if (auto expr = agg.getTargetExpression()) {
             addConstraint(isSubtypeOf(getVar(expr), getVar(agg)));
             addConstraint(isSubtypeOf(getVar(agg), getVar(expr)));
         }
     }
visitAtom()
void souffle::TypeConstraintsAnalysis::visitAtom (const AstAtom & atom) inline override private
Definition at line 589 of file Type.cpp.
References souffle::contains(), and souffle::isSubtypeOf().
{
         if (contains(sinks, &atom)) {
             visitSink(atom);
             return;
         }
         iterateOverAtom(atom, [&](const AstArgument& argument, const Type& attributeType) {
             addConstraint(isSubtypeOf(getVar(argument), attributeType));
         });
     }
visitBinaryConstraint()
void souffle::TypeConstraintsAnalysis::visitBinaryConstraint (const AstBinaryConstraint & rel) inline override private
Definition at line 649 of file Type.cpp.
References souffle::AstBinaryConstraint::getLHS(), souffle::AstBinaryConstraint::getRHS(), souffle::isSubtypeOf(), lhs, and rhs.
{
         auto lhs = getVar(rel.getLHS());
         auto rhs = getVar(rel.getRHS());
         addConstraint(isSubtypeOf(lhs, rhs));
         addConstraint(isSubtypeOf(rhs, lhs));
     }
visitCounter()
void souffle::TypeConstraintsAnalysis::visitCounter (const AstCounter & counter) inline override private
Definition at line 695 of file Type.cpp.
References souffle::TypeEnvironment::getConstantType(), souffle::isSubtypeOf(), and souffle::Signed.
{
         addConstraint(isSubtypeOf(getVar(counter), typeEnv.getConstantType(TypeAttribute::Signed)));
     }
visitFunctor()
void souffle::TypeConstraintsAnalysis::visitFunctor (const AstFunctor & fun) inline override private
Definition at line 656 of file Type.cpp.
References souffle::functorBuiltIn(), souffle::AstFunctor::getArgType(), souffle::AstTerm::getArguments(), souffle::TypeEnvironment::getConstantType(), souffle::AstFunctor::getReturnType(), i, souffle::isInfixFunctorOp(), souffle::isSubtypeOf(), souffle::map(), and souffle::ORD.
{
         auto functorVar = getVar(fun);
         auto intrFun = as<AstIntrinsicFunctor>(fun);
         if (intrFun) {
             auto argVars = map(intrFun->getArguments(), [&](auto&& x) { return getVar(x); });
             // The type of the user-defined function might not be set at this stage.
             // If so then add overloads as alternatives
             if (!intrFun->getFunctionInfo())
                 addConstraint(satisfiesOverload(typeEnv, functorBuiltIn(intrFun->getFunction()), functorVar,
                         argVars, isInfixFunctorOp(intrFun->getFunction())));
             // In polymorphic case
             // We only require arguments to share a base type with a return type.
             // (instead of, for example, requiring them to be of the same type)
             // This approach is related to old type semantics
             // See #1296 and tests/semantic/type_system4
             if (isInfixFunctorOp(intrFun->getFunction())) {
                 for (auto&& var : argVars)
                     addConstraint(subtypesOfTheSameBaseType(var, functorVar));
                 return;
             }
             if (!intrFun->getFunctionInfo()) return;
         }
         // add a constraint for the return type of the functor
         addConstraint(isSubtypeOf(functorVar, typeEnv.getConstantType(fun.getReturnType())));
         // Special case. Ord returns the ram representation of any object.
         if (intrFun && intrFun->getFunctionInfo()->op == FunctorOp::ORD) return;
         auto arguments = fun.getArguments();
         for (size_t i = 0; i < arguments.size(); ++i) {
             addConstraint(isSubtypeOf(getVar(arguments[i]), typeEnv.getConstantType(fun.getArgType(i))));
         }
     }
visitNegation()
void souffle::TypeConstraintsAnalysis::visitNegation (const AstNegation & cur) inline override private
Definition at line 600 of file Type.cpp.
References souffle::AstNegation::getAtom().
{
         sinks.insert(cur.getAtom());
     }
visitNumericConstant()
void souffle::TypeConstraintsAnalysis::visitNumericConstant (const AstNumericConstant & constant) inline override private
Definition at line 608 of file Type.cpp.
References souffle::canBeParsedAsRamFloat(), souffle::canBeParsedAsRamSigned(), souffle::canBeParsedAsRamUnsigned(), souffle::Float, souffle::AstNumericConstant::Float, souffle::AstConstant::getConstant(), souffle::TypeEnvironment::getConstantType(), souffle::AstNumericConstant::getType(), souffle::TypeSet::insert(), souffle::AstNumericConstant::Int, souffle::Signed, souffle::AstNumericConstant::Uint, and souffle::Unsigned.
{
         TypeSet possibleTypes;
         // Check if the type is given.
         if (constant.getType().has_value()) {
             switch (*constant.getType()) {
                 // Insert a type, but only after checking that parsing is possible.
                 case AstNumericConstant::Type::Int:
                     if (canBeParsedAsRamSigned(constant.getConstant())) {
                         possibleTypes.insert(typeEnv.getConstantType(TypeAttribute::Signed));
                     }
                     break;
                 case AstNumericConstant::Type::Uint:
                     if (canBeParsedAsRamUnsigned(constant.getConstant())) {
                         possibleTypes.insert(typeEnv.getConstantType(TypeAttribute::Unsigned));
                     }
                     break;
                 case AstNumericConstant::Type::Float:
                     if (canBeParsedAsRamFloat(constant.getConstant())) {
                         possibleTypes.insert(typeEnv.getConstantType(TypeAttribute::Float));
                     }
                     break;
             }
             // Else: all numeric types that can be parsed are valid.
         } else {
             if (canBeParsedAsRamSigned(constant.getConstant())) {
                 possibleTypes.insert(typeEnv.getConstantType(TypeAttribute::Signed));
             }
             if (canBeParsedAsRamUnsigned(constant.getConstant())) {
                 possibleTypes.insert(typeEnv.getConstantType(TypeAttribute::Unsigned));
             }
             if (canBeParsedAsRamFloat(constant.getConstant())) {
                 possibleTypes.insert(typeEnv.getConstantType(TypeAttribute::Float));
             }
         }
         addConstraint(hasSuperTypeInSet(getVar(constant), possibleTypes));
     }
visitRecordInit()
void souffle::TypeConstraintsAnalysis::visitRecordInit (const AstRecordInit & record) inline override private
Definition at line 716 of file Type.cpp.
References souffle::AstTerm::getArguments(), and i.
{
         auto arguments = record.getArguments();
         for (size_t i = 0; i < arguments.size(); ++i) {
             addConstraint(isSubtypeOfComponent(getVar(arguments[i]), getVar(record), i));
         }
     }
visitSink()
void souffle::TypeConstraintsAnalysis::visitSink (const AstAtom & atom) inline private
Definition at line 575 of file Type.cpp.
References souffle::TypeEnvironment::getConstantTypes(), and souffle::isSubtypeOf().
{
         iterateOverAtom(atom, [&](const AstArgument& argument, const Type& attributeType) {
             if (isA<RecordType>(attributeType)) {
                 addConstraint(isSubtypeOf(getVar(argument), getBaseType(&attributeType)));
                 return;
             }
             for (auto& constantType : typeEnv.getConstantTypes()) {
                 if (isSubtypeOf(attributeType, constantType)) {
                     addConstraint(isSubtypeOf(getVar(argument), constantType));
                 }
             }
         });
     }
visitStringConstant()
void souffle::TypeConstraintsAnalysis::visitStringConstant (const AstStringConstant & cnst) inline override private
Definition at line 604 of file Type.cpp.
References souffle::TypeEnvironment::getConstantType(), souffle::isSubtypeOf(), and souffle::Symbol.
{
         addConstraint(isSubtypeOf(getVar(cnst), typeEnv.getConstantType(TypeAttribute::Symbol)));
     }
visitTypeCast()
void souffle::TypeConstraintsAnalysis::visitTypeCast (const AstTypeCast & typeCast) inline override private
Definition at line 699 of file Type.cpp.
References souffle::AstTypeCast::getType(), souffle::TypeEnvironment::getType(), souffle::AstTypeCast::getValue(), souffle::isSubtypeOf(), and souffle::TypeEnvironment::isType().
{
         auto& typeName = typeCast.getType();
         if (!typeEnv.isType(typeName)) {
             return;
         }
         addConstraint(isSubtypeOf(getVar(typeCast), typeEnv.getType(typeName)));
         // If we are dealing with a constant then its type must be deduced from the cast
         // Otherwise, expression like: to_string(as(2, float)) couldn't be typed.
         auto* value = typeCast.getValue();
         if (isA<AstConstant>(value)) {
             addConstraint(isSubtypeOf(getVar(*value), typeEnv.getType(typeName)));
         }
     }
Field Documentation
program
const AstProgram& souffle::TypeConstraintsAnalysis::program private
Definition at line 565 of file Type.cpp.
sinks
std::set<const AstAtom*> souffle::TypeConstraintsAnalysis::sinks private
Definition at line 568 of file Type.cpp.
typeEnv
const TypeEnvironment& souffle::TypeConstraintsAnalysis::typeEnv private
Definition at line 564 of file Type.cpp.
The documentation for this class was generated from the following file:
ast/analysis/Type.cpp