souffle: souffle::AstNumericConstant Class Reference
souffle::AstNumericConstant Class Reference
Numeric Constant.
#include <NumericConstant.h>
Public Types
enum Type { Type::Int, Type::Uint, Type::Float }
Public Member Functions
AstNumericConstant (RamSigned value)
AstNumericConstant (std::string constant, SrcLocation loc)
AstNumericConstant (std::string constant, std::optional< Type > type=std::nullopt, SrcLocation loc={})
AstNumericConstant * clone () const override
Create clone.
const std::optional< Type > & getType () const
void setType (Type newType)
Public Member Functions inherited from souffle::AstConstant
const std::string & getConstant () const
Public Member Functions inherited from souffle::AstNode
virtual void apply (const AstNodeMapper &)
Apply the mapper to all child nodes.
AstNode (SrcLocation loc={})
std::string extloc () const
Return source location of the syntactic element.
virtual std::vector< const AstNode * > getChildNodes () const
Obtain a list of all embedded AST child nodes.
const SrcLocation & getSrcLoc () const
Return source location of the AstNode.
bool operator!= (const AstNode &other) const
Inequality check for two AST nodes.
bool operator== (const AstNode &other) const
Equivalence check for two AST nodes.
void setSrcLoc (SrcLocation l)
Set source location for the AstNode.
virtual ~AstNode ()=default
Protected Member Functions
bool equal (const AstNode &node) const override
Abstract equality check for two AST nodes.
Protected Member Functions inherited from souffle::AstConstant
AstConstant (std::string value, SrcLocation loc={})
void print (std::ostream &os) const override
Output to a given output stream.
Private Attributes
std::optional< Type > type
Detailed Description
Numeric Constant.
The constant can be initialized with type. If this is the case, the typesystem will be forced to use it. Otherwise the type is inferred from context.
Definition at line 34 of file NumericConstant.h.
Member Enumeration Documentation
Type
enum souffle::AstNumericConstant::Type strong
Enumerator
Int
Uint
Float
Definition at line 36 of file NumericConstant.h.
 { Int, Uint, Float };
Constructor & Destructor Documentation
AstNumericConstant() [1/3]
souffle::AstNumericConstant::AstNumericConstant (RamSigned value) inline
Definition at line 38 of file NumericConstant.h.
Referenced by clone().
 : AstConstant(std::to_string(value)), type(Type::Int) {}
AstNumericConstant() [2/3]
souffle::AstNumericConstant::AstNumericConstant (std::string constant, SrcLocation loc) inline
Definition at line 40 of file NumericConstant.h.
References souffle::AstNode::setSrcLoc().
                                                             : AstConstant(std::move(constant)) {
         setSrcLoc(std::move(loc));
     }
AstNumericConstant() [3/3]
souffle::AstNumericConstant::AstNumericConstant (std::string constant, std::optional< Type > type = std::nullopt, SrcLocation loc = {}) inline
Definition at line 44 of file NumericConstant.h.
References souffle::AstConstant::AstConstant(), souffle::AstNode::setSrcLoc(), and type.
                                                                                                   {})
             : AstConstant(std::move(constant)), type(type) {
         setSrcLoc(std::move(loc));
     }
Member Function Documentation
clone()
AstNumericConstant* souffle::AstNumericConstant::clone () const inline override virtual
Create clone.
Implements souffle::AstConstant.
Definition at line 49 of file NumericConstant.h.
References AstNumericConstant(), souffle::AstConstant::getConstant(), souffle::AstNode::getSrcLoc(), and getType().
{
         auto* copy = new AstNumericConstant(getConstant(), getType());
         copy->setSrcLoc(getSrcLoc());
         return copy;
     }
equal()
bool souffle::AstNumericConstant::equal (const AstNode &) const inline override protected virtual
Abstract equality check for two AST nodes.
Reimplemented from souffle::AstConstant.
Definition at line 64 of file NumericConstant.h.
References souffle::AstConstant::equal(), and type.
{
         const auto& other = static_cast<const AstNumericConstant&>(node);
         return AstConstant::equal(node) && type == other.type;
     }
getType()
const std::optional<Type>& souffle::AstNumericConstant::getType () const inline
Definition at line 55 of file NumericConstant.h.
References type.
Referenced by clone(), souffle::AstToRamTranslator::translateValue(), souffle::TypeChecker::visitNumericConstant(), and souffle::TypeConstraintsAnalysis::visitNumericConstant().
{
         return type;
     }
setType()
void souffle::AstNumericConstant::setType (Type newType) inline
Definition at line 59 of file NumericConstant.h.
References type.
{
         type = newType;
     }
Field Documentation
type
std::optional<Type> souffle::AstNumericConstant::type private
Definition at line 70 of file NumericConstant.h.
Referenced by AstNumericConstant(), equal(), getType(), and setType().
The documentation for this class was generated from the following file:
ast/NumericConstant.h