souffle: souffle::RamExit Class Reference
souffle::RamExit Class Reference
Exit statement for a loop.
#include <Statement.h>
Public Member Functions
void apply (const RamNodeMapper &map) override
Apply the mapper to all child nodes.
RamExit * clone () const override
Create a clone (i.e.
std::vector< const RamNode * > getChildNodes () const override
Obtain list of all embedded child nodes.
const RamCondition & getCondition () const
Get exit condition.
RamExit (std::unique_ptr< RamCondition > c)
Public Member Functions inherited from souffle::RamNode
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
virtual void rewrite (const RamNode *oldNode, std::unique_ptr< RamNode > newNode)
Rewrite a child node.
virtual ~RamNode ()=default
Protected Member Functions
bool equal (const RamNode &node) const override
Equality check for two RAM nodes.
void print (std::ostream &os, int tabpos) const override
Pretty print with indentation.
Protected Member Functions inherited from souffle::RamStatement
void print (std::ostream &os) const override
Print RAM node.
Protected Attributes
std::unique_ptr< RamCondition > condition
exit condition
Additional Inherited Members
Static Protected Member Functions inherited from souffle::RamStatement
static void print (const RamStatement *statement, std::ostream &os, int tabpos)
Pretty print jump-bed.
Detailed Description
Exit statement for a loop.
Exits a loop if exit condition holds.
The following example will exit the loop given that A is the empty set:
EXIT (A = ∅)
Definition at line 530 of file Statement.h.
Constructor & Destructor Documentation
RamExit()
souffle::RamExit::RamExit (std::unique_ptr< RamCondition > c) inline
Definition at line 532 of file Statement.h.
                                            : condition(std::move(c)) {
         assert(condition && "condition is a nullptr");
     }
Member Function Documentation
apply()
void souffle::RamExit::apply (const RamNodeMapper &) inline override virtual
Apply the mapper to all child nodes.
Reimplemented from souffle::RamNode.
Definition at line 549 of file Statement.h.
References souffle::map().
{
         condition = map(std::move(condition));
     }
clone()
RamExit* souffle::RamExit::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::RamStatement.
Definition at line 545 of file Statement.h.
References souffle::clone().
Referenced by souffle::test::TEST().
{
         return new RamExit(souffle::clone(condition));
     }
equal()
bool souffle::RamExit::equal (const RamNode &) const inline override protected virtual
Equality check for two RAM nodes.
Default action is that nothing needs to be checked.
Reimplemented from souffle::RamNode.
Definition at line 558 of file Statement.h.
References souffle::equal_ptr().
{
         const auto& other = static_cast<const RamExit&>(node);
         return equal_ptr(condition, other.condition);
     }
getChildNodes()
std::vector<const RamNode*> souffle::RamExit::getChildNodes () const inline override virtual
Obtain list of all embedded child nodes.
Reimplemented from souffle::RamNode.
Definition at line 541 of file Statement.h.
{
         return {condition.get()};
     }
getCondition()
const RamCondition& souffle::RamExit::getCondition () const inline
Get exit condition.
Definition at line 537 of file Statement.h.
Referenced by souffle::Synthesiser::emitCode().
{
         return *condition;
     }
print()
void souffle::RamExit::print (std::ostream & os, int tabpos) const inline override protected virtual
Pretty print with indentation.
Implements souffle::RamStatement.
Definition at line 554 of file Statement.h.
References souffle::times().
{
         os << times(" ", tabpos) << "EXIT " << getCondition() << std::endl;
     }
Field Documentation
condition
std::unique_ptr<RamCondition> souffle::RamExit::condition protected
exit condition
Definition at line 564 of file Statement.h.
The documentation for this class was generated from the following file:
ram/Statement.h