souffle: souffle::ReadStream Class Reference
souffle::ReadStream Class Reference abstract
#include <ReadStream.h>
Public Member Functions
template<typename T >
void readAll (T &relation)
Public Member Functions inherited from souffle::SerialisationStream< false >
virtual ~SerialisationStream ()=default
Protected Member Functions
void consumeChar (const std::string &str, char c, size_t &pos)
Read past given character, consuming any preceding whitespace.
void consumeWhiteSpace (const std::string &str, size_t &pos)
Advance position in the string until first non-whitespace character.
virtual std::unique_ptr< RamDomain[]> readNextTuple ()=0
RamDomain readRecord (const std::string &source, const std::string &recordTypeName, size_t pos=0, size_t *charactersRead=nullptr)
Read a record from a string.
ReadStream (const std::map< std::string, std::string > &rwOperation, SymbolTable &symTab, RecordTable &recTab)
RamDomain readStringInRecord (const std::string &source, const size_t pos, size_t *charactersRead)
Protected Member Functions inherited from souffle::SerialisationStream< false >
SerialisationStream (RO< SymbolTable > &symTab, RO< RecordTable > &recTab, Json types, std::vector< std::string > relTypes, size_t auxArity=0)
SerialisationStream (RO< SymbolTable > &symTab, RO< RecordTable > &recTab, Json types)
SerialisationStream (RO< SymbolTable > &symTab, RO< RecordTable > &recTab, const std::map< std::string, std::string > &rwOperation)
Additional Inherited Members
Protected Types inherited from souffle::SerialisationStream< false >
using RO = std::conditional_t< readOnlyTables, const A, A >
Protected Attributes inherited from souffle::SerialisationStream< false >
size_t arity
size_t auxiliaryArity
RO< RecordTable > & recordTable
RO< SymbolTable > & symbolTable
std::vector< std::string > typeAttributes
Json types
Detailed Description
Definition at line 35 of file ReadStream.h.
Constructor & Destructor Documentation
ReadStream()
souffle::ReadStream::ReadStream (const std::map< std::string, std::string > & rwOperation, SymbolTable & symTab, RecordTable & recTab) inline protected
Definition at line 37 of file ReadStream.h.
             : SerialisationStream(symTab, recTab, rwOperation) {}
Member Function Documentation
consumeChar()
void souffle::ReadStream::consumeChar (const std::string & str, char c, size_t & pos) inline protected
Read past given character, consuming any preceding whitespace.
Definition at line 146 of file ReadStream.h.
References consumeWhiteSpace().
Referenced by readRecord().
{
         consumeWhiteSpace(str, pos);
         if (pos >= str.length()) {
             throw std::invalid_argument("Unexpected end of input in record");
         }
         if (str[pos] != c) {
             std::stringstream error;
             error << "Expected: \'" << c << "\', got: " << str[pos];
             throw std::invalid_argument(error.str());
         }
         ++pos;
     }
consumeWhiteSpace()
void souffle::ReadStream::consumeWhiteSpace (const std::string & str, size_t & pos) inline protected
Advance position in the string until first non-whitespace character.
Definition at line 162 of file ReadStream.h.
References readNextTuple().
Referenced by consumeChar(), and readRecord().
{
         while (pos < str.length() && std::isspace(static_cast<unsigned char>(str[pos]))) {
             ++pos;
         }
     }
readAll()
template<typename T > void souffle::ReadStream::readAll (T & relation) inline
Definition at line 43 of file ReadStream.h.
References readNextTuple(), and souffle::SerialisationStream< false >::symbolTable.
{
         auto lease = symbolTable.acquireLock();
         (void)lease;
         while (const auto next = readNextTuple()) {
             const RamDomain* ramDomain = next.get();
             relation.insert(ramDomain);
         }
     }
readNextTuple()
virtual std::unique_ptr<RamDomain[]> souffle::ReadStream::readNextTuple () protected pure virtual
Implemented in souffle::ReadFileCSV, souffle::ReadStreamCSV, souffle::ReadStreamJSON, and souffle::ReadStreamSQLite.
Referenced by consumeWhiteSpace(), and readAll().
readRecord()
RamDomain souffle::ReadStream::readRecord (const std::string & source, const std::string & recordTypeName, size_t pos = 0, size_t * charactersRead = nullptr) inline protected
Read a record from a string.
Parameters
source - string containing a record
recordTypeName - record type. pos - start parsing from this position.
consumed - if not nullptr: number of characters read.
Definition at line 62 of file ReadStream.h.
References consumeChar(), consumeWhiteSpace(), souffle::fatal(), i, souffle::ramBitCast(), souffle::RamFloatFromString(), souffle::RamSignedFromString(), souffle::RamUnsignedFromString(), readStringInRecord(), souffle::SerialisationStream< false >::recordTable, and souffle::SerialisationStream< false >::types.
Referenced by souffle::ReadStreamCSV::readNextTuple().
{
         const size_t initial_position = pos;
         // Check if record type information are present
         auto&& recordInfo = types["records"][recordTypeName];
         if (recordInfo.is_null()) {
             throw std::invalid_argument("Missing record type information: " + recordTypeName);
         }
         // Handle nil case
         consumeWhiteSpace(source, pos);
         if (source.substr(pos, 3) == "nil") {
             if (charactersRead != nullptr) {
                 *charactersRead = 3;
             }
             return 0;
         }
         auto&& recordTypes = recordInfo["types"];
         const size_t recordArity = recordInfo["arity"].long_value();
         std::vector<RamDomain> recordValues(recordArity);
         consumeChar(source, '[', pos);
         for (size_t i = 0; i < recordArity; ++i) {
             const std::string& recordType = recordTypes[i].string_value();
             size_t consumed = 0;
             if (i > 0) {
                 consumeChar(source, ',', pos);
             }
             consumeWhiteSpace(source, pos);
             switch (recordType[0]) {
                 case 's': {
                     recordValues[i] = readStringInRecord(source, pos, &consumed);
                     break;
                 }
                 case 'i': {
                     recordValues[i] = RamSignedFromString(source.substr(pos), &consumed);
                     break;
                 }
                 case 'u': {
                     recordValues[i] = ramBitCast(RamUnsignedFromString(source.substr(pos), &consumed));
                     break;
                 }
                 case 'f': {
                     recordValues[i] = ramBitCast(RamFloatFromString(source.substr(pos), &consumed));
                     break;
                 }
                 case 'r': {
                     recordValues[i] = readRecord(source, recordType, pos, &consumed);
                     break;
                 }
                 default: fatal("Invalid type attribute");
             }
             pos += consumed;
         }
         consumeChar(source, ']', pos);
         if (charactersRead != nullptr) {
             *charactersRead = pos - initial_position;
         }
         return recordTable.pack(recordValues.data(), recordValues.size());
     }
readStringInRecord()
RamDomain souffle::ReadStream::readStringInRecord (const std::string & source, const size_t pos, size_t * charactersRead) inline protected
Definition at line 130 of file ReadStream.h.
References str, and souffle::SerialisationStream< false >::symbolTable.
Referenced by readRecord().
{
         size_t endOfSymbol = source.find_first_of(",]", pos);
         if (endOfSymbol == std::string::npos) {
             throw std::invalid_argument("Unexpected end of input in record");
         }
         *charactersRead = endOfSymbol - pos;
         std::string str = source.substr(pos, *charactersRead);
         return symbolTable.unsafeLookup(str);
     }
The documentation for this class was generated from the following file:
ReadStream.h