souffle: souffle::AstNode Class Reference
souffle::AstNode Class Reference abstract
Abstract class for syntactic elements in a Datalog program.
#include <Node.h>
Public Member Functions
virtual void apply (const AstNodeMapper &)
Apply the mapper to all child nodes.
AstNode (SrcLocation loc={})
virtual AstNode * clone () const =0
Create a clone (i.e.
std::string extloc () const
Return source location of the syntactic element.
virtual std::vector< const AstNode * > getChildNodes () const
Obtain a list of all embedded AST child nodes.
const SrcLocation & getSrcLoc () const
Return source location of the AstNode.
bool operator!= (const AstNode &other) const
Inequality check for two AST nodes.
bool operator== (const AstNode &other) const
Equivalence check for two AST nodes.
void setSrcLoc (SrcLocation l)
Set source location for the AstNode.
virtual ~AstNode ()=default
Protected Member Functions
virtual bool equal (const AstNode &) const
Abstract equality check for two AST nodes.
virtual void print (std::ostream &os) const =0
Output to a given output stream.
Private Attributes
SrcLocation location
Source location of a syntactic element.
Friends
std::ostream & operator<< (std::ostream &out, const AstNode &node)
Print node onto an output stream.
Detailed Description
Abstract class for syntactic elements in a Datalog program.
Definition at line 34 of file Node.h.
Constructor & Destructor Documentation
AstNode()
souffle::AstNode::AstNode (SrcLocation loc = {}) inline
Definition at line 36 of file Node.h.
References location, and ~AstNode().
Referenced by souffle::AstAttribute::AstAttribute(), souffle::AstClause::AstClause(), souffle::AstComponentInit::AstComponentInit(), souffle::AstComponentType::AstComponentType(), souffle::AstFunctorDeclaration::AstFunctorDeclaration(), souffle::AstPragma::AstPragma(), and souffle::AstType::AstType().
 {}) : location(std::move(loc)){};
~AstNode()
virtual souffle::AstNode::~AstNode () virtual default
Referenced by AstNode().
Member Function Documentation
apply()
virtual void souffle::AstNode::apply (const AstNodeMapper &) inline virtual
Apply the mapper to all child nodes.
Reimplemented in souffle::AstProgram, souffle::AstComponent, souffle::AstRelation, souffle::AstClause, souffle::AstAggregator, souffle::AstAtom, souffle::AstBinaryConstraint, souffle::AstTypeCast, souffle::AstComponentInit, souffle::AstTerm, souffle::AstExecutionPlan, and souffle::AstNegation.
Definition at line 73 of file Node.h.
Referenced by souffle::renameVariables().
 {}
clone()
virtual AstNode* souffle::AstNode::clone () const pure virtual
Create a clone (i.e.
deep copy) of this node
Implemented in souffle::AstProgram, souffle::AstComponent, souffle::AstRelation, souffle::AstClause, souffle::AstIO, souffle::AstIntrinsicFunctor, souffle::AstAggregator, souffle::AstAtom, souffle::AstUserDefinedFunctor, souffle::AstFunctorDeclaration, souffle::AstBinaryConstraint, souffle::AstComponentType, souffle::AstRecordType, souffle::AstTypeCast, souffle::AstComponentInit, souffle::AstUnionType, souffle::AstAttribute, souffle::AstExecutionPlan, souffle::AstBooleanConstraint, souffle::AstNegation, souffle::AstNumericConstant, souffle::AstType, souffle::AstExecutionOrder, souffle::AstVariable, souffle::AstSubroutineArgument, souffle::AstProvenanceNegation, souffle::AstRecordInit, souffle::AstSubsetType, souffle::AstPragma, souffle::AstStringConstant, souffle::AstLiteral, souffle::AstArgument, souffle::AstConstant, souffle::AstFunctor, souffle::AstNilConstant, souffle::AstConstraint, souffle::AstCounter, and souffle::AstUnnamedVariable.
Referenced by operator!=().
equal()
virtual bool souffle::AstNode::equal (const AstNode &) const inline protected virtual
Abstract equality check for two AST nodes.
Reimplemented in souffle::AstProgram, souffle::AstComponent, souffle::AstRelation, souffle::AstClause, souffle::AstIO, souffle::AstAggregator, souffle::AstIntrinsicFunctor, souffle::AstAtom, souffle::AstFunctorDeclaration, souffle::AstExecutionPlan, souffle::AstUserDefinedFunctor, souffle::AstBinaryConstraint, souffle::AstComponentInit, souffle::AstComponentType, souffle::AstTypeCast, souffle::AstRecordType, souffle::AstTerm, souffle::AstUnionType, souffle::AstNegation, souffle::AstNumericConstant, souffle::AstAttribute, souffle::AstBooleanConstraint, souffle::AstExecutionOrder, souffle::AstVariable, souffle::AstPragma, souffle::AstSubsetType, souffle::AstSubroutineArgument, and souffle::AstConstant.
Definition at line 91 of file Node.h.
Referenced by operator==().
{
         return true;
     }
extloc()
std::string souffle::AstNode::extloc () const inline
Return source location of the syntactic element.
Definition at line 50 of file Node.h.
References souffle::SrcLocation::extloc(), and location.
{
         return location.extloc();
     }
getChildNodes()
virtual std::vector<const AstNode*> souffle::AstNode::getChildNodes () const inline virtual
Obtain a list of all embedded AST child nodes.
Reimplemented in souffle::AstProgram, souffle::AstComponent, souffle::AstRelation, souffle::AstClause, souffle::AstAtom, souffle::AstBinaryConstraint, souffle::AstAggregator, souffle::AstComponentInit, souffle::AstExecutionPlan, souffle::AstNegation, souffle::AstTerm, and souffle::AstTypeCast.
Definition at line 76 of file Node.h.
Referenced by souffle::AstSemanticCheckerImpl::checkInlining(), souffle::AstTypeCast::getChildNodes(), souffle::AstTerm::getChildNodes(), souffle::AstAggregator::getChildNodes(), souffle::visitDepthFirstPostOrder(), and souffle::visitDepthFirstPreOrder().
{
         return {};
     }
getSrcLoc()
const SrcLocation& souffle::AstNode::getSrcLoc () const inline
Return source location of the AstNode.
Definition at line 40 of file Node.h.
References location.
Referenced by souffle::ParserDriver::addIoFromDeprecatedTag(), souffle::AstSemanticCheckerImpl::AstSemanticCheckerImpl(), souffle::AstSemanticCheckerImpl::checkAggregator(), souffle::AstSemanticCheckerImpl::checkAtom(), souffle::AstSemanticCheckerImpl::checkClause(), souffle::AstComponentChecker::checkComponent(), souffle::AstComponentChecker::checkComponentInit(), souffle::AstSemanticCheckerImpl::checkInlining(), souffle::AstSemanticCheckerImpl::checkRelation(), souffle::AstSemanticCheckerImpl::checkRelationDeclaration(), souffle::AstSemanticCheckerImpl::checkSubsetType(), souffle::AstSemanticCheckerImpl::checkType(), souffle::AstSemanticCheckerImpl::checkUnionType(), souffle::AstCounter::clone(), souffle::AstUnnamedVariable::clone(), souffle::AstNilConstant::clone(), souffle::AstStringConstant::clone(), souffle::AstPragma::clone(), souffle::AstSubsetType::clone(), souffle::AstProvenanceNegation::clone(), souffle::AstRecordInit::clone(), souffle::AstSubroutineArgument::clone(), souffle::AstVariable::clone(), souffle::AstExecutionOrder::clone(), souffle::AstNumericConstant::clone(), souffle::AstBooleanConstraint::clone(), souffle::AstNegation::clone(), souffle::AstAttribute::clone(), souffle::AstExecutionPlan::clone(), souffle::AstUnionType::clone(), souffle::AstComponentInit::clone(), souffle::AstTypeCast::clone(), souffle::AstRecordType::clone(), souffle::AstComponentType::clone(), souffle::AstBinaryConstraint::clone(), souffle::AstFunctorDeclaration::clone(), souffle::AstUserDefinedFunctor::clone(), souffle::AstAtom::clone(), souffle::AstAggregator::clone(), souffle::AstIntrinsicFunctor::clone(), souffle::AstClause::clone(), souffle::AstRelation::clone(), souffle::cloneHead(), souffle::createNewRelation(), souffle::getInlinedAtom(), souffle::getInlinedClause(), souffle::ReduceExistentialsTransformer::transform(), souffle::PartitionBodyLiteralsTransformer::transform(), souffle::MagicSetTransformer::transform(), souffle::AstToRamTranslator::translateNonRecursiveRelation(), souffle::TypeChecker::visitAggregator(), souffle::TypeChecker::visitBinaryConstraint(), souffle::TypeChecker::visitIntrinsicFunctor(), souffle::TypeChecker::visitNilConstant(), souffle::TypeChecker::visitNumericConstant(), souffle::TypeChecker::visitRecordInit(), souffle::TypeChecker::visitStringConstant(), souffle::TypeChecker::visitTypeCast(), souffle::TypeChecker::visitUserDefinedFunctor(), and souffle::TypeChecker::visitVariable().
{
         return location;
     }
operator!=()
bool souffle::AstNode::operator!= (const AstNode & other) const inline
Inequality check for two AST nodes.
Definition at line 65 of file Node.h.
References clone().
{
         return !(*this == other);
     }
operator==()
bool souffle::AstNode::operator== (const AstNode & other) const inline
Equivalence check for two AST nodes.
Definition at line 55 of file Node.h.
References equal().
{
         if (this == &other) {
             return true;
         } else if (typeid(*this) == typeid(*&other)) {
             return equal(other);
         }
         return false;
     }
print()
virtual void souffle::AstNode::print (std::ostream & os) const protected pure virtual
Output to a given output stream.
Implemented in souffle::AstProgram, souffle::AstComponent, souffle::AstRelation, souffle::AstClause, souffle::AstIO, souffle::AstAggregator, souffle::AstAtom, souffle::AstIntrinsicFunctor, souffle::AstUserDefinedFunctor, souffle::AstBinaryConstraint, souffle::AstExecutionPlan, souffle::AstComponentInit, souffle::AstFunctorDeclaration, souffle::AstTypeCast, souffle::AstComponentType, souffle::AstRecordType, souffle::AstUnionType, souffle::AstNegation, souffle::AstAttribute, souffle::AstBooleanConstraint, souffle::AstExecutionOrder, souffle::AstVariable, souffle::AstPragma, souffle::AstSubsetType, souffle::AstSubroutineArgument, souffle::AstProvenanceNegation, souffle::AstRecordInit, souffle::AstStringConstant, souffle::AstConstant, souffle::AstCounter, and souffle::AstUnnamedVariable.
setSrcLoc()
void souffle::AstNode::setSrcLoc (SrcLocation l) inline
Set source location for the AstNode.
Definition at line 45 of file Node.h.
References location.
Referenced by souffle::AstExecutionOrder::AstExecutionOrder(), souffle::AstNumericConstant::AstNumericConstant(), souffle::AstRelation::AstRelation(), souffle::AstStringConstant::AstStringConstant(), souffle::getInlinedArgument(), and souffle::MagicSetTransformer::transform().
{
         location = std::move(l);
     }
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & out, const AstNode & node) friend
Print node onto an output stream.
Definition at line 81 of file Node.h.
{
         node.print(out);
         return out;
     }
Field Documentation
location
SrcLocation souffle::AstNode::location private
Source location of a syntactic element.
Definition at line 97 of file Node.h.
Referenced by AstNode(), extloc(), getSrcLoc(), and setSrcLoc().
The documentation for this class was generated from the following file:
ast/Node.h