souffle: souffle::MagicSetTransformer Class Reference
souffle::MagicSetTransformer Class Reference
Magic Set Transformation.
#include <MagicSet.h>
Public Member Functions
MagicSetTransformer * clone () const override
std::string getName () const override
Public Member Functions inherited from souffle::AstTransformer
bool apply (AstTranslationUnit &translationUnit)
virtual ~AstTransformer ()=default
Private Member Functions
bool transform (AstTranslationUnit &translationUnit) override
Detailed Description
Magic Set Transformation.
Definition at line 46 of file MagicSet.h.
Member Function Documentation
clone()
MagicSetTransformer* souffle::MagicSetTransformer::clone () const inline override virtual
Implements souffle::AstTransformer.
Definition at line 52 of file MagicSet.h.
References transform().
{
         return new MagicSetTransformer();
     }
getName()
std::string souffle::MagicSetTransformer::getName () const inline override virtual
Implements souffle::AstTransformer.
Definition at line 48 of file MagicSet.h.
{
         return "MagicSetTransformer";
     }
transform()
bool souffle::MagicSetTransformer::transform (AstTranslationUnit & translationUnit) override private virtual
Implements souffle::AstTransformer.
Definition at line 1053 of file MagicSet.cpp.
References souffle::AstRelation::addAttribute(), souffle::AstProgram::addClause(), souffle::AstProgram::addRelation(), souffle::AstClause::clone(), souffle::clone(), souffle::contains(), souffle::createAdornedIdentifier(), souffle::createMagicIdentifier(), souffle::createMagicRelation(), souffle::createNewRelation(), souffle::createSubIdentifier(), souffle::EQ, souffle::extractConstant(), souffle::AstTranslationUnit::getAnalysis(), souffle::AstAtom::getArguments(), souffle::AstRelation::getArity(), souffle::AstRelation::getAttributes(), souffle::AstClause::getBodyLiterals(), souffle::getEndpoint(), souffle::AstClause::getHead(), souffle::AstProgram::getIOs(), souffle::AstTranslationUnit::getProgram(), souffle::AstAtom::getQualifiedName(), souffle::AstQualifiedName::getQualifiers(), souffle::getRelation(), souffle::AstRelation::getRepresentation(), souffle::AstNode::getSrcLoc(), souffle::getString(), souffle::hasPrefix(), i, souffle::input, souffle::isAggRel(), j, k, souffle::nextSrcLoc(), relation, souffle::AstProgram::removeRelation(), souffle::reorderAdornment(), souffle::reorderAtoms(), souffle::reorderOrdering(), souffle::replaceUnderscores(), souffle::separateDBs(), souffle::AstAtom::setQualifiedName(), souffle::AstRelation::setQualifiedName(), souffle::AstNode::setSrcLoc(), and souffle::visitDepthFirst().
Referenced by clone().
{
     AstProgram* program = translationUnit.getProgram();
     auto* ioTypes = translationUnit.getAnalysis<IOType>();
     separateDBs(program);  // make EDB int IDB = empty
     auto* adornment = translationUnit.getAnalysis<Adornment>();  // perform adornment
     const BindingStore& compositeBindings = adornment->getBindings();
     // edb/idb handling
     std::vector<std::vector<AdornedClause>> allAdornedClauses = adornment->getAdornedClauses();
     std::set<AstQualifiedName> negatedAtoms = adornment->getNegatedAtoms();
     std::set<AstQualifiedName> ignoredAtoms = adornment->getIgnoredAtoms();
     std::set<AstQualifiedName> oldIdb = adornment->getIDB();
     std::set<AstQualifiedName> newIdb;
     // additions
     std::vector<AstQualifiedName> newQueryNames;
     std::vector<AstClause*> newClauses;
     // output handling
     std::vector<AstQualifiedName> outputQueries = adornment->getRelations();
     // ignore negated atoms
     for (AstQualifiedName relation : negatedAtoms) {
         ignoredAtoms.insert(relation);
     }
     // perform magic set algorithm for each output
     for (size_t querynum = 0; querynum < outputQueries.size(); querynum++) {
         AstQualifiedName outputQuery = outputQueries[querynum];
         std::vector<AdornedClause> adornedClauses = allAdornedClauses[querynum];
         AstRelation* originalOutputRelation = getRelation(*program, outputQuery);
         // add a relation for the output query
         // mN_outputname_ff...f()
         auto* magicOutputRelation = new AstRelation();
         std::string frepeat = std::string(originalOutputRelation->getArity(), 'f');
         AstQualifiedName magicOutputName =
                 createMagicIdentifier(createAdornedIdentifier(outputQuery, frepeat), querynum);
         magicOutputRelation->setQualifiedName(magicOutputName);
         newQueryNames.push_back(magicOutputName);
         // add the new relation to the program
         program->addRelation(std::unique_ptr<AstRelation>(magicOutputRelation));
         // add an empty fact to the program
         // i.e. mN_outputname_ff...f().
         auto* outputFact = new AstClause();
         outputFact->setSrcLoc(nextSrcLoc(originalOutputRelation->getSrcLoc()));
         outputFact->setHead(std::make_unique<AstAtom>(magicOutputName));
         program->addClause(std::unique_ptr<AstClause>(outputFact));
         // perform the magic transformation based on the adornment for this output query
         for (AdornedClause adornedClause : adornedClauses) {
             AstClause* clause = adornedClause.getClause();
             AstQualifiedName originalName = clause->getHead()->getQualifiedName();
             // dont perform the magic transformation on ignored relations
             if (contains(ignoredAtoms, originalName)) {
                 continue;
             }
             // find the adorned version of this relation
             std::string headAdornment = adornedClause.getHeadAdornment();
             AstQualifiedName newRelName = createAdornedIdentifier(originalName, headAdornment);
             AstRelation* adornedRelation = getRelation(*program, newRelName);
             // check if adorned relation already created previously
             if (adornedRelation == nullptr) {
                 // adorned relation not created yet, so
                 // create the relation with the new adornment
                 AstRelation* originalRelation = getRelation(*program, originalName);
                 AstRelation* newRelation = createNewRelation(originalRelation, newRelName);
                 // add the created adorned relation to the program
                 program->addRelation(std::unique_ptr<AstRelation>(newRelation));
                 // copy over input directives to new adorned relation
                 // also - update input directives to correctly use default fact file names
                 if (ioTypes->isInput(originalRelation)) {
                     for (AstIO* io : program->getIOs()) {
                         if (io->getQualifiedName() != originalName || io->getType() != AstIoType::input) {
                             continue;
                         }
                         io->setQualifiedName(newRelName);
                         if (!io->hasDirective("IO")) {
                             io->addDirective("IO", "file");
                         }
                         if (io->getDirective("IO") == "file" && !io->hasDirective("filename")) {
                             io->addDirective("filename", originalName.getQualifiers()[0] + ".facts");
                         }
                     }
                 }
                 adornedRelation = newRelation;
             }
             // create the adorned version of this clause
             AstClause* newClause = clause->clone();
             newClause->getHead()->setQualifiedName(newRelName);
             // reorder atoms based on SIPS ordering
             AstClause* tmp = reorderAtoms(newClause, reorderOrdering(adornedClause.getOrdering()));
             delete newClause;
             newClause = tmp;
             // get corresponding adornments for each body atom
             std::vector<std::string> bodyAdornment =
                     reorderAdornment(adornedClause.getBodyAdornment(), adornedClause.getOrdering());
             // set the name of each IDB pred in the clause to be the adorned version
             int atomsSeen = 0;
             for (AstLiteral* lit : newClause->getBodyLiterals()) {
                 if (dynamic_cast<AstAtom*>(lit) != nullptr) {
                     auto* bodyAtom = dynamic_cast<AstAtom*>(lit);
                     AstQualifiedName atomName = bodyAtom->getQualifiedName();
                     // note that all atoms in the original clause were adorned,
                     // but only the IDB atom adornments should be added here
                     if (contains(oldIdb, atomName)) {
                         if (!contains(ignoredAtoms, atomName)) {
                             // ignored atoms should not be changed
                             AstQualifiedName newAtomName =
                                     createAdornedIdentifier(atomName, bodyAdornment[atomsSeen]);
                             bodyAtom->setQualifiedName(newAtomName);
                             newIdb.insert(newAtomName);
                         } else {
                             newIdb.insert(atomName);
                         }
                     }
                     atomsSeen++;
                 }
             }
             // Add the set of magic rules for this clause C = A^a :- A1^a1, A2^a2, ..., An^an
             // -- For each clause C = A^a :- A1^a1, A2^a2, ..., An^an
             // -- -- For each IDB literal A_i in the body of C
             // -- -- -- Add mag(Ai^ai) :- mag(A^a), A1^a1, ..., Ai-1^ai-1 to the program
             std::vector<AstAtom*> body = getBodyLiterals<AstAtom>(*newClause);
             for (size_t i = 0; i < body.size(); i++) {
                 AstAtom* currentLiteral = body[i];
                 // only care about atoms in the body
                 if (dynamic_cast<AstAtom*>(currentLiteral) != nullptr) {
                     auto* atom = dynamic_cast<AstAtom*>(currentLiteral);
                     AstQualifiedName atomName = atom->getQualifiedName();
                     // only IDB atoms that are not being ignored matter
                     if (contains(newIdb, atomName) && !contains(ignoredAtoms, atomName)) {
                         std::string currAdornment = bodyAdornment[i];
                         // generate the name of the magic version of this adorned literal
                         AstQualifiedName newAtomName = createMagicIdentifier(atomName, querynum);
                         // if the magic version does not exist, create it
                         if (getRelation(*program, newAtomName) == nullptr) {
                             auto* magicRelation = new AstRelation();
                             magicRelation->setQualifiedName(newAtomName);
                             // find out the original name of the relation (pre-adornment)
                             std::string baseAtomName = atomName.getQualifiers()[0];
                             int endpt = getEndpoint(baseAtomName);
                             AstQualifiedName originalRelationName = createSubIdentifier(
                                     atomName, 0, endpt - 1);  // get rid of the extra + at the end
                             AstRelation* originalRelation = getRelation(*program, originalRelationName);
                             // copy over the (bound) attributes from the original relation
                             int argcount = 0;
                             for (AstAttribute* attr : originalRelation->getAttributes()) {
                                 if (currAdornment[argcount] == 'b') {
                                     magicRelation->addAttribute(souffle::clone(attr));
                                 }
                                 argcount++;
                             }
                             // copy over internal representation
                             magicRelation->setRepresentation(originalRelation->getRepresentation());
                             // add the new magic relation to the program
                             program->addRelation(std::unique_ptr<AstRelation>(magicRelation));
                         }
                         // start setting up the magic rule
                         auto* magicClause = new AstClause();
                         magicClause->setSrcLoc(nextSrcLoc(atom->getSrcLoc()));
                         // create the head of the magic rule
                         auto* magicHead = new AstAtom(newAtomName);
                         // copy over (bound) arguments from the original atom
                         int argCount = 0;
                         for (AstArgument* arg : atom->getArguments()) {
                             if (currAdornment[argCount] == 'b') {
                                 magicHead->addArgument(souffle::clone(arg));
                             }
                             argCount++;
                         }
                         // head complete!
                         magicClause->setHead(std::unique_ptr<AstAtom>(magicHead));
                         // -- create the body --
                         // create the first body argument (mag(origClauseHead^adornment))
                         AstQualifiedName magPredName =
                                 createMagicIdentifier(newClause->getHead()->getQualifiedName(), querynum);
                         auto* addedMagicPred = new AstAtom(magPredName);
                         // create the relation if it does not exist
                         if (getRelation(*program, magPredName) == nullptr) {
                             AstRelation* originalRelation =
                                     getRelation(*program, newClause->getHead()->getQualifiedName());
                             AstRelation* newMagicRelation =
                                     createMagicRelation(originalRelation, magPredName);
                             // add the new relation to the prgoram
                             program->addRelation(std::unique_ptr<AstRelation>(newMagicRelation));
                         }
                         // add (bound) arguments to the magic predicate from the clause head
                         argCount = 0;
                         for (AstArgument* arg : newClause->getHead()->getArguments()) {
                             if (headAdornment[argCount] == 'b') {
                                 addedMagicPred->addArgument(souffle::clone(arg));
                             }
                             argCount++;
                         }
                         // first argument complete!
                         magicClause->addToBody(std::unique_ptr<AstAtom>(addedMagicPred));
                         // add the rest of the necessary arguments
                         for (size_t j = 0; j < i; j++) {
                             magicClause->addToBody(souffle::clone(body[j]));
                         }
                         // restore memorised bindings for all composite arguments
                         std::vector<const AstArgument*> compositeArguments;
                         visitDepthFirst(*magicClause, [&](const AstArgument& argument) {
                             std::string argName = getString(&argument);
                             if (hasPrefix(argName, "+functor") || hasPrefix(argName, "+record")) {
                                 compositeArguments.push_back(&argument);
                             }
                         });
                         for (const AstArgument* compositeArgument : compositeArguments) {
                             std::string argName = getString(compositeArgument);
                             // if the composite argument was bound only because all
                             // of its constituent variables were bound, then bind
                             // the composite variable to the original argument
                             if (compositeBindings.isVariableBoundComposite(argName)) {
                                 AstArgument* originalArgument =
                                         compositeBindings.cloneOriginalArgument(argName);
                                 magicClause->addToBody(std::make_unique<AstBinaryConstraint>(
                                         BinaryConstraintOp::EQ, souffle::clone(compositeArgument),
                                         std::unique_ptr<AstArgument>(originalArgument)));
                             }
                         }
                         // restore bindings for normalised constants
                         std::vector<const AstVariable*> clauseVariables;
                         visitDepthFirst(*magicClause,
                                 [&](const AstVariable& variable) { clauseVariables.push_back(&variable); });
                         for (const AstVariable* var : clauseVariables) {
                             std::string varName = getString(var);
                             // all normalised constants begin with "+abdul" (see AstTransforms.cpp)
                             // +abdulX_variablevalue_Y
                             if (hasPrefix(varName, "+abdul")) {
                                 AstArgument* embeddedConstant = extractConstant(varName);
                                 // add the constraint to the body of the clause
                                 magicClause->addToBody(std::make_unique<AstBinaryConstraint>(
                                         BinaryConstraintOp::EQ, souffle::clone(var),
                                         std::unique_ptr<AstArgument>(embeddedConstant)));
                             }
                         }
                         // magic rule done! add it to the program
                         program->addClause(std::unique_ptr<AstClause>(magicClause));
                     }
                 }
             }
             // -- replace with H :- mag(H), T --
             size_t originalNumAtoms = getBodyLiterals<AstAtom>(*newClause).size();
             // create the first argument of this new clause
             const AstAtom* newClauseHead = newClause->getHead();
             AstQualifiedName newMag = createMagicIdentifier(newClauseHead->getQualifiedName(), querynum);
             auto* newMagAtom = new AstAtom(newMag);
             // copy over the bound arguments from the head
             std::vector<AstArgument*> args = newClauseHead->getArguments();
             for (size_t k = 0; k < args.size(); k++) {
                 if (headAdornment[k] == 'b') {
                     newMagAtom->addArgument(souffle::clone(args[k]));
                 }
             }
             // add it to the end of the clause
             newClause->addToBody(std::unique_ptr<AstAtom>(newMagAtom));
             // move the new magic argument to the front of the clause,
             // pushing all the rest up one position
             std::vector<unsigned int> newClauseOrder(originalNumAtoms + 1);
             for (size_t k = 0; k < originalNumAtoms; k++) {
                 newClauseOrder[k] = k + 1;
             }
             newClauseOrder[originalNumAtoms] = 0;
             tmp = reorderAtoms(newClause, reorderOrdering(newClauseOrder));
             delete newClause;
             newClause = tmp;
             // add the clause to the program and the set of new clauses
             newClause->setSrcLoc(nextSrcLoc(newClause->getSrcLoc()));
             newClauses.push_back(newClause);
             program->addClause(std::unique_ptr<AstClause>(newClause));
         }
     }
     for (AstQualifiedName relationName : oldIdb) {
         // do not delete negated atoms, ignored atoms, or atoms added by aggregate relations
         if (!(contains(ignoredAtoms, relationName) || contains(negatedAtoms, relationName) ||
                     isAggRel(relationName))) {
             program->removeRelation(relationName);
         }
     }
     // add the new output relations
     // in particular, need to rename the adorned output back to the original name
     for (size_t i = 0; i < outputQueries.size(); i++) {
         AstQualifiedName oldName = outputQueries[i];
         AstQualifiedName newName = newQueryNames[i];
         // get the original adorned relation
         std::string newBaseName = newName.getQualifiers()[0];
         size_t prefixpoint = newBaseName.find("_");
         AstQualifiedName newRelationName =
                 createSubIdentifier(newName, prefixpoint + 1, newBaseName.size() - (prefixpoint + 1));
         AstRelation* adornedRelation = getRelation(*program, newRelationName);
         if (adornedRelation == nullptr) {
             continue;
         }
         AstRelation* outputRelation = getRelation(*program, oldName);
         // if the corresponding output relation does not exist yet, create it
         if (outputRelation == nullptr) {
             outputRelation = new AstRelation();
             outputRelation->setSrcLoc(nextSrcLoc(adornedRelation->getSrcLoc()));
             // copy over the attributes from the existing adorned version
             for (AstAttribute* attr : adornedRelation->getAttributes()) {
                 outputRelation->addAttribute(souffle::clone(attr));
             }
             // rename it back to its original name
             outputRelation->setQualifiedName(oldName);
             // add the new output to the program
             program->addRelation(std::unique_ptr<AstRelation>(outputRelation));
         }
         // rules need to be the same
         // easy fix:
         //    oldname(arg1...argn) :- newname(arg1...argn)
         auto* headatom = new AstAtom(oldName);
         auto* bodyatom = new AstAtom(newRelationName);
         for (size_t j = 0; j < adornedRelation->getArity(); j++) {
             std::stringstream argName;
             argName.str("");
             argName << "arg" << j;
             headatom->addArgument(std::make_unique<AstVariable>(argName.str()));
             bodyatom->addArgument(std::make_unique<AstVariable>(argName.str()));
         }
         // add the clause to the program
         auto* referringClause = new AstClause();
         referringClause->setSrcLoc(nextSrcLoc(outputRelation->getSrcLoc()));
         referringClause->setHead(std::unique_ptr<AstAtom>(headatom));
         referringClause->addToBody(std::unique_ptr<AstAtom>(bodyatom));
         program->addClause(std::unique_ptr<AstClause>(referringClause));
     }
     // replace all "+underscoreX" variables with actual underscores
     replaceUnderscores(program);
     // done!
     return true;
 }
The documentation for this class was generated from the following files:
ast/transform/MagicSet.h
ast/transform/MagicSet.cpp