souffle: souffle::ParallelTransformer Class Reference
souffle::ParallelTransformer Class Reference
Transforms Choice/IndexChoice/IndexScan/Scan into parallel versions.
#include <Parallel.h>
Public Member Functions
std::string getName () const override
get name of the transformer
bool parallelizeOperations (RamProgram &program)
Parallelize operations.
Public Member Functions inherited from souffle::RamTransformer
bool apply (RamTranslationUnit &translationUnit)
apply the transformer to a translation unit translationUnit that will be transformed.
virtual ~RamTransformer ()=default
Protected Member Functions
bool transform (RamTranslationUnit &translationUnit) override
transform the translation unit / used by apply translationUnit that will be transformed.
Detailed Description
Transforms Choice/IndexChoice/IndexScan/Scan into parallel versions.
For example ..
QUERY
  FOR t0 in A
   ...
will be rewritten to
QUERY
  PARALLEL FOR t0 in A
   ...
Definition at line 46 of file Parallel.h.
Member Function Documentation
getName()
std::string souffle::ParallelTransformer::getName () const inline override virtual
get name of the transformer
Implements souffle::RamTransformer.
Definition at line 48 of file Parallel.h.
References parallelizeOperations().
{
         return "ParallelTransformer";
     }
parallelizeOperations()
bool souffle::ParallelTransformer::parallelizeOperations (RamProgram & program)
Parallelize operations.
Parameters
program Program that is transformed
Returns
Flag showing whether the program has been changed by the transformation
Definition at line 32 of file Parallel.cpp.
References souffle::RamTransformer::apply(), souffle::clone(), souffle::makeLambdaRamMapper(), and souffle::visitDepthFirst().
Referenced by getName(), and transform().
{
     bool changed = false;
     // parallelize the most outer loop only
     // most outer loops can be scan/choice/indexScan/indexChoice
     visitDepthFirst(program, [&](const RamQuery& query) {
         std::function<std::unique_ptr<RamNode>(std::unique_ptr<RamNode>)> parallelRewriter =
                 [&](std::unique_ptr<RamNode> node) -> std::unique_ptr<RamNode> {
             if (const RamScan* scan = dynamic_cast<RamScan*>(node.get())) {
                 if (scan->getTupleId() == 0 && scan->getRelation().getArity() > 0) {
                     if (nullptr == dynamic_cast<RamProject*>(&scan->getOperation())) {
                         changed = true;
                         return std::make_unique<RamParallelScan>(
                                 std::make_unique<RamRelationReference>(&scan->getRelation()),
                                 scan->getTupleId(), souffle::clone(&scan->getOperation()),
                                 scan->getProfileText());
                     }
                 }
             } else if (const RamChoice* choice = dynamic_cast<RamChoice*>(node.get())) {
                 if (choice->getTupleId() == 0) {
                     changed = true;
                     return std::make_unique<RamParallelChoice>(
                             std::make_unique<RamRelationReference>(&choice->getRelation()),
                             choice->getTupleId(), souffle::clone(&choice->getCondition()),
                             souffle::clone(&choice->getOperation()), choice->getProfileText());
                 }
             } else if (const RamIndexScan* indexScan = dynamic_cast<RamIndexScan*>(node.get())) {
                 if (indexScan->getTupleId() == 0) {
                     changed = true;
                     const RamRelation& rel = indexScan->getRelation();
                     RamPattern queryPattern = clone(indexScan->getRangePattern());
                     return std::make_unique<RamParallelIndexScan>(
                             std::make_unique<RamRelationReference>(&rel), indexScan->getTupleId(),
                             std::move(queryPattern), souffle::clone(&indexScan->getOperation()),
                             indexScan->getProfileText());
                 }
             } else if (const RamIndexChoice* indexChoice = dynamic_cast<RamIndexChoice*>(node.get())) {
                 if (indexChoice->getTupleId() == 0) {
                     changed = true;
                     const RamRelation& rel = indexChoice->getRelation();
                     RamPattern queryPattern = clone(indexChoice->getRangePattern());
                     return std::make_unique<RamParallelIndexChoice>(
                             std::make_unique<RamRelationReference>(&rel), indexChoice->getTupleId(),
                             souffle::clone(&indexChoice->getCondition()), std::move(queryPattern),
                             souffle::clone(&indexChoice->getOperation()), indexChoice->getProfileText());
                 }
             } else if (const RamAggregate* aggregate = dynamic_cast<RamAggregate*>(node.get())) {
                 if (aggregate->getTupleId() == 0 && !aggregate->getRelation().isNullary()) {
                     changed = true;
                     const RamRelation& rel = aggregate->getRelation();
                     return std::make_unique<RamParallelAggregate>(
                             std::unique_ptr<RamOperation>(aggregate->getOperation().clone()),
                             aggregate->getFunction(), std::make_unique<RamRelationReference>(&rel),
                             std::unique_ptr<RamExpression>(aggregate->getExpression().clone()),
                             std::unique_ptr<RamCondition>(aggregate->getCondition().clone()),
                             aggregate->getTupleId());
                 }
             } else if (const RamIndexAggregate* indexAggregate =
                                dynamic_cast<RamIndexAggregate*>(node.get())) {
                 if (indexAggregate->getTupleId() == 0 && !indexAggregate->getRelation().isNullary()) {
                     changed = true;
                     const RamRelation& rel = indexAggregate->getRelation();
                     RamPattern queryPattern = clone(indexAggregate->getRangePattern());
                     return std::make_unique<RamParallelIndexAggregate>(
                             std::unique_ptr<RamOperation>(indexAggregate->getOperation().clone()),
                             indexAggregate->getFunction(), std::make_unique<RamRelationReference>(&rel),
                             std::unique_ptr<RamExpression>(indexAggregate->getExpression().clone()),
                             std::unique_ptr<RamCondition>(indexAggregate->getCondition().clone()),
                             std::move(queryPattern), indexAggregate->getTupleId());
                 }
             }
             node->apply(makeLambdaRamMapper(parallelRewriter));
             return node;
         };
         const_cast<RamQuery*>(&query)->apply(makeLambdaRamMapper(parallelRewriter));
     });
     return changed;
 }
transform()
bool souffle::ParallelTransformer::transform (RamTranslationUnit & translationUnit) inline override protected virtual
transform the translation unit / used by apply translationUnit that will be transformed.
flag reporting whether the RAM program has changed
Implements souffle::RamTransformer.
Definition at line 60 of file Parallel.h.
References souffle::RamTranslationUnit::getProgram(), and parallelizeOperations().
{
         return parallelizeOperations(translationUnit.getProgram());
     }
The documentation for this class was generated from the following files:
ram/transform/Parallel.h
ram/transform/Parallel.cpp