souffle: souffle::RemoveTypecastsTransformer Class Reference
souffle::RemoveTypecastsTransformer Class Reference
Transformation to remove typecasts.
#include <RemoveTypecasts.h>
Public Member Functions
RemoveTypecastsTransformer * clone () const override
std::string getName () const override
Public Member Functions inherited from souffle::AstTransformer
bool apply (AstTranslationUnit &translationUnit)
virtual ~AstTransformer ()=default
Private Member Functions
bool transform (AstTranslationUnit &translationUnit) override
Detailed Description
Transformation to remove typecasts.
Definition at line 29 of file RemoveTypecasts.h.
Member Function Documentation
clone()
RemoveTypecastsTransformer* souffle::RemoveTypecastsTransformer::clone () const inline override virtual
Implements souffle::AstTransformer.
Definition at line 38 of file RemoveTypecasts.h.
{
         return new RemoveTypecastsTransformer();
     }
getName()
std::string souffle::RemoveTypecastsTransformer::getName () const inline override virtual
Implements souffle::AstTransformer.
Definition at line 34 of file RemoveTypecasts.h.
{
         return "RemoveTypecastsTransformer";
     }
transform()
bool souffle::RemoveTypecastsTransformer::transform (AstTranslationUnit & translationUnit) override private virtual
Implements souffle::AstTransformer.
Definition at line 27 of file RemoveTypecasts.cpp.
References souffle::AstProgram::apply(), souffle::clone(), and souffle::AstTranslationUnit::getProgram().
{
     struct TypecastRemover : public AstNodeMapper {
         mutable bool changed{false};
         std::unique_ptr<AstNode> operator()(std::unique_ptr<AstNode> node) const override {
             // remove sub-typecasts first
             node->apply(*this);
             // if current node is a typecast, replace with the value directly
             if (auto* cast = dynamic_cast<AstTypeCast*>(node.get())) {
                 changed = true;
                 return souffle::clone(cast->getValue());
             }
             // otherwise, return the original node
             return node;
         }
     };
     TypecastRemover update;
     translationUnit.getProgram()->apply(update);
     return update.changed;
 }
The documentation for this class was generated from the following files:
ast/transform/RemoveTypecasts.h
ast/transform/RemoveTypecasts.cpp