souffle: souffle::IndirectIndex Class Reference
souffle::IndirectIndex Class Reference
Data Structures
struct comparator
struct IndirectIndexView
class Source
Public Types
using AttributeIndex = uint32_t
using AttributeOrder = std::vector< AttributeIndex >
using Hints = typename index_set::operation_hints
using index_set = btree_multiset< TupleRef, comparator, std::allocator< TupleRef >, 512 >
Public Member Functions
void clear () override
Clears the content of this index, turning it empty.
bool contains (const TupleRef &tuple) const override
Tests whether the given tuple is present in this index or not.
bool contains (const TupleRef &low, const TupleRef &high) const override
Tests whether this index contains any tuple within the given bounds.
IndexViewPtr createView () const override
Requests the creation of a view on this index.
bool empty () const override
Tests whether this index is empty or not.
size_t getArity () const override
Obtains the arity of the given index.
IndirectIndex (AttributeOrder order)
bool insert (const TupleRef &tuple) override
Inserts a tuple into this index.
void insert (const InterpreterIndex &src) override
Inserts all elements of the given index.
PartitionedStream partitionRange (const TupleRef &low, const TupleRef &high, int) const override
Returns a partitioned stream covering elements in the range [low,high)
PartitionedStream partitionScan (int) const override
Returns a partitioned stream covering the entire index content.
Stream range (const TupleRef &low, const TupleRef &high) const override
Returns a stream covering elements in the range [low,high)
Stream scan () const override
Returns a stream covering the entire index content.
size_t size () const override
Obtains the number of elements stored in this index.
Public Member Functions inherited from souffle::InterpreterIndex
virtual void extend (InterpreterIndex *)
Extend another index.
virtual ~InterpreterIndex ()=default
Private Attributes
size_t arity
Arity as the relation arity, not necessary the order size in indirect index.
index_set::btree_operation_hints< 1 > operation_hints
Operation hints.
index_set set
set storing tuple pointers of table
const AttributeOrder theOrder
retain the index order used to construct an object of this class
Detailed Description
Definition at line 469 of file InterpreterIndex.cpp.
Member Typedef Documentation
AttributeIndex
using souffle::IndirectIndex::AttributeIndex = uint32_t
Definition at line 471 of file InterpreterIndex.cpp.
AttributeOrder
using souffle::IndirectIndex::AttributeOrder = std::vector<AttributeIndex>
Definition at line 472 of file InterpreterIndex.cpp.
Hints
using souffle::IndirectIndex::Hints = typename index_set::operation_hints
Definition at line 511 of file InterpreterIndex.cpp.
index_set
using souffle::IndirectIndex::index_set = btree_multiset<TupleRef, comparator, std::allocator<TupleRef>, 512>
Definition at line 510 of file InterpreterIndex.cpp.
Constructor & Destructor Documentation
IndirectIndex()
souffle::IndirectIndex::IndirectIndex (AttributeOrder order) inline
Definition at line 578 of file InterpreterIndex.cpp.
             : theOrder(std::move(order)), set(comparator(theOrder), comparator(theOrder)),
               arity(order.size()) {}
Member Function Documentation
clear()
void souffle::IndirectIndex::clear () inline override virtual
Clears the content of this index, turning it empty.
Implements souffle::InterpreterIndex.
Definition at line 638 of file InterpreterIndex.cpp.
{
         set.clear();
     }
contains() [1/2]
bool souffle::IndirectIndex::contains (const TupleRef & tuple) const inline override virtual
Tests whether the given tuple is present in this index or not.
Implements souffle::InterpreterIndex.
Definition at line 608 of file InterpreterIndex.cpp.
References souffle::IndirectIndex::IndirectIndexView::contains().
{
         return IndirectIndexView(*this).contains(tuple);
     }
contains() [2/2]
bool souffle::IndirectIndex::contains (const TupleRef & low, const TupleRef & high) const inline override virtual
Tests whether this index contains any tuple within the given bounds.
Implements souffle::InterpreterIndex.
Definition at line 612 of file InterpreterIndex.cpp.
References souffle::IndirectIndex::IndirectIndexView::contains().
{
         return IndirectIndexView(*this).contains(low, high);
     }
createView()
IndexViewPtr souffle::IndirectIndex::createView () const inline override virtual
Requests the creation of a view on this index.
Implements souffle::InterpreterIndex.
Definition at line 582 of file InterpreterIndex.cpp.
{
         return std::make_unique<IndirectIndexView>(*this);
     }
empty()
bool souffle::IndirectIndex::empty () const inline override virtual
Tests whether this index is empty or not.
Implements souffle::InterpreterIndex.
Definition at line 590 of file InterpreterIndex.cpp.
{
         return set.empty();
     }
getArity()
size_t souffle::IndirectIndex::getArity () const inline override virtual
Obtains the arity of the given index.
Implements souffle::InterpreterIndex.
Definition at line 586 of file InterpreterIndex.cpp.
Referenced by souffle::IndirectIndex::IndirectIndexView::getArity().
{
         return arity;
     };
insert() [1/2]
bool souffle::IndirectIndex::insert (const TupleRef & tuple) inline override virtual
Inserts a tuple into this index.
Implements souffle::InterpreterIndex.
Definition at line 598 of file InterpreterIndex.cpp.
{
         return set.insert(tuple, operation_hints);
     }
insert() [2/2]
void souffle::IndirectIndex::insert (const InterpreterIndex & src) inline override virtual
Inserts all elements of the given index.
Implements souffle::InterpreterIndex.
Definition at line 602 of file InterpreterIndex.cpp.
References souffle::InterpreterIndex::scan().
{
         for (const auto& cur : src.scan()) {
             insert(cur);
         }
     }
partitionRange()
PartitionedStream souffle::IndirectIndex::partitionRange (const TupleRef & low, const TupleRef & high, int partitionCount) const inline override virtual
Returns a partitioned stream covering elements in the range [low,high)
Implements souffle::InterpreterIndex.
Definition at line 631 of file InterpreterIndex.cpp.
{
         assert(false && "Does only produce a single subset!");
         std::vector<Stream> res;
         res.push_back(range(low, high));
         return res;
     }
partitionScan()
PartitionedStream souffle::IndirectIndex::partitionScan (int partitionCount) const inline override virtual
Returns a partitioned stream covering the entire index content.
Implements souffle::InterpreterIndex.
Definition at line 620 of file InterpreterIndex.cpp.
{
         assert(false && "Does only produce a single subset!");
         std::vector<Stream> res;
         res.push_back(scan());
         return res;
     }
range()
Stream souffle::IndirectIndex::range (const TupleRef & low, const TupleRef & high) const inline override virtual
Returns a stream covering elements in the range [low,high)
Implements souffle::InterpreterIndex.
Definition at line 627 of file InterpreterIndex.cpp.
References souffle::IndirectIndex::IndirectIndexView::range().
{
         return IndirectIndexView(*this).range(low, high);
     }
scan()
Stream souffle::IndirectIndex::scan () const inline override virtual
Returns a stream covering the entire index content.
Implements souffle::InterpreterIndex.
Definition at line 616 of file InterpreterIndex.cpp.
{
         return std::make_unique<Source>(set.begin(), set.end());
     }
size()
size_t souffle::IndirectIndex::size () const inline override virtual
Obtains the number of elements stored in this index.
Implements souffle::InterpreterIndex.
Definition at line 594 of file InterpreterIndex.cpp.
{
         return set.size();
     }
Field Documentation
arity
size_t souffle::IndirectIndex::arity private
Arity as the relation arity, not necessary the order size in indirect index.
Definition at line 653 of file InterpreterIndex.cpp.
operation_hints
index_set::btree_operation_hints<1> souffle::IndirectIndex::operation_hints private
Operation hints.
Definition at line 650 of file InterpreterIndex.cpp.
set
index_set souffle::IndirectIndex::set private
set storing tuple pointers of table
Definition at line 647 of file InterpreterIndex.cpp.
Referenced by souffle::IndirectIndex::IndirectIndexView::contains(), and souffle::IndirectIndex::IndirectIndexView::range().
theOrder
const AttributeOrder souffle::IndirectIndex::theOrder private
retain the index order used to construct an object of this class
Definition at line 644 of file InterpreterIndex.cpp.
The documentation for this class was generated from the following file:
interpreter/InterpreterIndex.cpp