souffle: souffle::InterpreterRelInterface::iterator_base Class Reference
souffle::InterpreterRelInterface::iterator_base Class Reference
Iterator wrapper class.
#include <InterpreterProgInterface.h>
Public Member Functions
iterator_base * clone () const override
Clone iterator.
iterator_base (uint32_t arg_id, const InterpreterRelInterface *r, InterpreterRelation::Iterator i)
tuple & operator* () override
Get current tuple.
void operator++ () override
Increment iterator.
~iterator_base () override=default
Destructor.
Public Member Functions inherited from souffle::Relation::iterator_base
virtual uint32_t getId () const
Get the ID of the iterator_base object.
iterator_base (uint32_t arg_id)
Constructor.
bool operator== (const iterator_base &o) const
Overload the "==" operator.
Protected Member Functions
bool equal (const Relation::iterator_base &o) const override
Check equivalence.
Private Attributes
InterpreterRelation::Iterator it
const InterpreterRelInterface * ramRelationInterface
tuple tup
Additional Inherited Members
Protected Attributes inherited from souffle::Relation::iterator_base
uint32_t id
Required for identifying type of iterator (NB: LLVM has no typeinfo).
Detailed Description
Iterator wrapper class.
Definition at line 123 of file InterpreterProgInterface.h.
Constructor & Destructor Documentation
iterator_base()
souffle::InterpreterRelInterface::iterator_base::iterator_base (uint32_t arg_id, const InterpreterRelInterface * r, InterpreterRelation::Iterator i) inline
Definition at line 125 of file InterpreterProgInterface.h.
References ~iterator_base().
                 : Relation::iterator_base(arg_id), ramRelationInterface(r), it(std::move(i)), tup(r) {}
~iterator_base()
souffle::InterpreterRelInterface::iterator_base::~iterator_base () override virtual default
Destructor.
Reimplemented from souffle::Relation::iterator_base.
Referenced by iterator_base().
Member Function Documentation
clone()
iterator_base* souffle::InterpreterRelInterface::iterator_base::clone () const inline override virtual
Clone iterator.
Implements souffle::Relation::iterator_base.
Definition at line 166 of file InterpreterProgInterface.h.
References souffle::Relation::iterator_base::getId(), it, and ramRelationInterface.
{
             return new InterpreterRelInterface::iterator_base(getId(), ramRelationInterface, it);
         }
equal()
bool souffle::InterpreterRelInterface::iterator_base::equal (const Relation::iterator_base & o) const inline override protected virtual
Check equivalence.
Implements souffle::Relation::iterator_base.
Definition at line 172 of file InterpreterProgInterface.h.
References e, it, o, and ramRelationInterface.
{
             try {
                 auto& iter = dynamic_cast<const InterpreterRelInterface::iterator_base&>(o);
                 return ramRelationInterface == iter.ramRelationInterface && it == iter.it;
             } catch (const std::bad_cast& e) {
                 return false;
             }
         }
operator*()
tuple& souffle::InterpreterRelInterface::iterator_base::operator* () inline override virtual
Get current tuple.
Implements souffle::Relation::iterator_base.
Definition at line 135 of file InterpreterProgInterface.h.
References souffle::InterpreterRelInterface::getArity(), souffle::InterpreterRelInterface::getAttrType(), souffle::InterpreterRelInterface::getSymbolTable(), i, it, ramRelationInterface, souffle::SymbolTable::resolve(), souffle::tuple::rewind(), and tup.
{
             // set tuple stream to first element
             tup.rewind();
             // construct the tuple to return
             for (size_t i = 0; i < ramRelationInterface->getArity(); i++) {
                 switch (*(ramRelationInterface->getAttrType(i))) {
                     case 's': {
                         std::string s = ramRelationInterface->getSymbolTable().resolve((*it)[i]);
                         tup << s;
                         break;
                     }
                     case 'f': {
                         tup << ramBitCast<RamFloat>((*it)[i]);
                         break;
                     }
                     case 'u': {
                         tup << ramBitCast<RamUnsigned>((*it)[i]);
                         break;
                     }
                     default: {
                         tup << (*it)[i];
                         break;
                     }
                 }
             }
             tup.rewind();
             return tup;
         }
operator++()
void souffle::InterpreterRelInterface::iterator_base::operator++ () inline override virtual
Increment iterator.
Implements souffle::Relation::iterator_base.
Definition at line 130 of file InterpreterProgInterface.h.
References it.
{
             ++it;
         }
Field Documentation
it
InterpreterRelation::Iterator souffle::InterpreterRelInterface::iterator_base::it private
Definition at line 183 of file InterpreterProgInterface.h.
Referenced by clone(), equal(), operator*(), and operator++().
ramRelationInterface
const InterpreterRelInterface* souffle::InterpreterRelInterface::iterator_base::ramRelationInterface private
Definition at line 182 of file InterpreterProgInterface.h.
Referenced by clone(), equal(), and operator*().
tup
tuple souffle::InterpreterRelInterface::iterator_base::tup private
Definition at line 184 of file InterpreterProgInterface.h.
Referenced by operator*().
The documentation for this class was generated from the following file:
interpreter/InterpreterProgInterface.h