souffle: souffle::AstSubroutineArgument Class Reference
souffle::AstSubroutineArgument Class Reference
Subroutine Argument.
#include <SubroutineArgument.h>
Public Member Functions
AstSubroutineArgument (size_t index, SrcLocation loc={})
AstSubroutineArgument * clone () const override
Create clone.
size_t getNumber () const
Return argument index.
Public Member Functions inherited from souffle::AstNode
virtual void apply (const AstNodeMapper &)
Apply the mapper to all child nodes.
AstNode (SrcLocation loc={})
std::string extloc () const
Return source location of the syntactic element.
virtual std::vector< const AstNode * > getChildNodes () const
Obtain a list of all embedded AST child nodes.
const SrcLocation & getSrcLoc () const
Return source location of the AstNode.
bool operator!= (const AstNode &other) const
Inequality check for two AST nodes.
bool operator== (const AstNode &other) const
Equivalence check for two AST nodes.
void setSrcLoc (SrcLocation l)
Set source location for the AstNode.
virtual ~AstNode ()=default
Protected Member Functions
bool equal (const AstNode &node) const override
Abstract equality check for two AST nodes.
void print (std::ostream &os) const override
Output to a given output stream.
Private Attributes
size_t index
Index of argument in argument list.
Detailed Description
Subroutine Argument.
Definition at line 30 of file SubroutineArgument.h.
Constructor & Destructor Documentation
AstSubroutineArgument()
souffle::AstSubroutineArgument::AstSubroutineArgument (size_t index, SrcLocation loc = {}) inline
Definition at line 32 of file SubroutineArgument.h.
References index.
Referenced by clone().
 {}) : AstArgument(std::move(loc)), index(index) {}
Member Function Documentation
clone()
AstSubroutineArgument* souffle::AstSubroutineArgument::clone () const inline override virtual
Create clone.
Implements souffle::AstArgument.
Definition at line 39 of file SubroutineArgument.h.
References AstSubroutineArgument(), and souffle::AstNode::getSrcLoc().
{
         return new AstSubroutineArgument(index, getSrcLoc());
     }
equal()
bool souffle::AstSubroutineArgument::equal (const AstNode &) const inline override protected virtual
Abstract equality check for two AST nodes.
Reimplemented from souffle::AstNode.
Definition at line 48 of file SubroutineArgument.h.
References index.
{
         const auto& other = static_cast<const AstSubroutineArgument&>(node);
         return index == other.index;
     }
getNumber()
size_t souffle::AstSubroutineArgument::getNumber () const inline
Return argument index.
Definition at line 35 of file SubroutineArgument.h.
References index.
Referenced by souffle::AstToRamTranslator::translateValue().
{
         return index;
     }
print()
void souffle::AstSubroutineArgument::print (std::ostream & os) const inline override protected virtual
Output to a given output stream.
Implements souffle::AstNode.
Definition at line 44 of file SubroutineArgument.h.
References index.
{
         os << "arg_" << index;
     }
Field Documentation
index
size_t souffle::AstSubroutineArgument::index private
Index of argument in argument list.
Definition at line 55 of file SubroutineArgument.h.
Referenced by AstSubroutineArgument(), equal(), getNumber(), and print().
The documentation for this class was generated from the following file:
ast/SubroutineArgument.h