souffle: souffle::profile::CellInterface Class Reference
souffle::profile::CellInterface Class Reference abstract
#include <CellInterface.h>
Public Member Functions
virtual double getDoubleVal () const =0
virtual long getLongVal () const =0
virtual std::string getStringVal () const =0
virtual std::chrono::microseconds getTimeVal () const =0
virtual std::string toString (int precision) const =0
virtual ~CellInterface ()=default
Detailed Description
Definition at line 17 of file CellInterface.h.
Constructor & Destructor Documentation
~CellInterface()
virtual souffle::profile::CellInterface::~CellInterface () virtual default
Member Function Documentation
getDoubleVal()
virtual double souffle::profile::CellInterface::getDoubleVal () const pure virtual
Implemented in souffle::profile::Cell< void >, souffle::profile::Cell< long >, souffle::profile::Cell< double >, and souffle::profile::Cell< std::chrono::microseconds >.
Referenced by souffle::profile::Cell< double >::toString().
getLongVal()
virtual long souffle::profile::CellInterface::getLongVal () const pure virtual
Implemented in souffle::profile::Cell< void >, souffle::profile::Cell< long >, souffle::profile::Cell< double >, and souffle::profile::Cell< std::chrono::microseconds >.
Referenced by souffle::profile::Cell< double >::toString().
getStringVal()
virtual std::string souffle::profile::CellInterface::getStringVal () const pure virtual
Implemented in souffle::profile::Cell< void >, souffle::profile::Cell< long >, souffle::profile::Cell< double >, and souffle::profile::Cell< std::chrono::microseconds >.
Referenced by souffle::profile::Cell< double >::toString().
getTimeVal()
virtual std::chrono::microseconds souffle::profile::CellInterface::getTimeVal () const pure virtual
Implemented in souffle::profile::Cell< void >, souffle::profile::Cell< long >, souffle::profile::Cell< double >, and souffle::profile::Cell< std::chrono::microseconds >.
Referenced by souffle::profile::Cell< double >::toString().
toString()
virtual std::string souffle::profile::CellInterface::toString (int precision) const pure virtual
Implemented in souffle::profile::Cell< void >, souffle::profile::Cell< long >, souffle::profile::Cell< double >, and souffle::profile::Cell< std::chrono::microseconds >.
Referenced by souffle::profile::Cell< double >::toString().
The documentation for this class was generated from the following file:
profile/CellInterface.h