souffle: souffle::RamAnalysis Class Reference
souffle::RamAnalysis Class Reference abstract
Abstract class for a RAM Analysis.
#include <Analysis.h>
Public Member Functions
virtual const std::string & getName () const
get name of the analysis
virtual void print (std::ostream &) const
Print the analysis result in HTML format.
RamAnalysis (const char *id)
virtual void run (const RamTranslationUnit &translationUnit)=0
Run analysis for a RAM translation unit.
virtual ~RamAnalysis ()=default
Protected Attributes
std::string identifier
name of analysis instance
Friends
std::ostream & operator<< (std::ostream &out, const RamAnalysis &other)
define output stream operator
Detailed Description
Abstract class for a RAM Analysis.
Definition at line 30 of file Analysis.h.
Constructor & Destructor Documentation
RamAnalysis()
souffle::RamAnalysis::RamAnalysis (const char * id) inline
Definition at line 32 of file Analysis.h.
References ~RamAnalysis().
 : identifier(id) {}
~RamAnalysis()
virtual souffle::RamAnalysis::~RamAnalysis () virtual default
Referenced by RamAnalysis().
Member Function Documentation
getName()
virtual const std::string& souffle::RamAnalysis::getName () const inline virtual
get name of the analysis
Definition at line 36 of file Analysis.h.
References identifier, and run().
{
         return identifier;
     }
print()
virtual void souffle::RamAnalysis::print (std::ostream &) const inline virtual
Print the analysis result in HTML format.
Reimplemented in souffle::RamIndexAnalysis.
Definition at line 44 of file Analysis.h.
 {}
run()
virtual void souffle::RamAnalysis::run (const RamTranslationUnit & translationUnit) pure virtual
Run analysis for a RAM translation unit.
Implemented in souffle::RamIndexAnalysis, souffle::RamLevelAnalysis, and souffle::RamComplexityAnalysis.
Referenced by getName().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & out, const RamAnalysis & other) friend
define output stream operator
Definition at line 47 of file Analysis.h.
{
         other.print(out);
         return out;
     }
Field Documentation
identifier
std::string souffle::RamAnalysis::identifier protected
name of analysis instance
Definition at line 54 of file Analysis.h.
Referenced by getName().
The documentation for this class was generated from the following file:
ram/analysis/Analysis.h