souffle: souffle::TypeEnvironmentAnalysis Class Reference
souffle::TypeEnvironmentAnalysis Class Reference
#include <TypeEnvironment.h>
Public Member Functions
const std::set< AstQualifiedName > & getPrimitiveTypesInUnion (const AstQualifiedName &identifier) const
const TypeEnvironment & getTypeEnvironment () const
bool isCyclic (const AstQualifiedName &identifier) const
void print (std::ostream &os) const override
print the analysis result in HTML format
void run (const AstTranslationUnit &translationUnit) override
run analysis for a Ast translation unit
TypeEnvironmentAnalysis ()
Public Member Functions inherited from souffle::AstAnalysis
AstAnalysis (std::string identifier)
virtual const std::string & getName () const
get name of the analysis
virtual ~AstAnalysis ()=default
Static Public Attributes
static constexpr const char * name = "type-environment"
Private Member Functions
const Type * createType (const AstQualifiedName &typeName, const std::map< AstQualifiedName, const AstType *> &nameToAstType)
Recursively create a type in env, that is first create its base types and then the type itself.
Private Attributes
std::set< AstQualifiedName > cyclicTypes
TypeEnvironment env
std::map< AstQualifiedName, std::set< AstQualifiedName > > primitiveTypesInUnions
Additional Inherited Members
Protected Attributes inherited from souffle::AstAnalysis
const std::string identifier
Detailed Description
Definition at line 31 of file TypeEnvironment.h.
Constructor & Destructor Documentation
TypeEnvironmentAnalysis()
souffle::TypeEnvironmentAnalysis::TypeEnvironmentAnalysis () inline
Definition at line 35 of file TypeEnvironment.h.
References print(), and run().
 : AstAnalysis(name) {}
Member Function Documentation
createType()
const Type * souffle::TypeEnvironmentAnalysis::createType (const AstQualifiedName & typeName, const std::map< AstQualifiedName, const AstType *> & nameToAstType) private
Recursively create a type in env, that is first create its base types and then the type itself.
Definition at line 136 of file TypeEnvironment.cpp.
References souffle::fatal(), tinyformat::format(), and souffle::RecordType::setFields().
Referenced by run().
{
     // base case
     if (env.isType(typeName)) {
         return &env.getType(typeName);
     }
     // Handle undeclared type in the definition of another type.
     auto iterToType = nameToAstType.find(typeName);
     if (iterToType == nameToAstType.end()) {
         return nullptr;
     }
     const auto& astType = iterToType->second;
     if (isA<AstSubsetType>(astType)) {
         // First create a base type.
         auto* baseType = createType(as<AstSubsetType>(astType)->getBaseType(), nameToAstType);
         if (baseType == nullptr) {
             return nullptr;
         }
         // Subset of a record is a special case.
         if (isA<RecordType>(baseType)) {
             return &env.createType<SubsetRecordType>(typeName, *as<RecordType>(baseType));
         }
         return &env.createType<SubsetType>(typeName, *baseType);
     } else if (isA<AstUnionType>(astType)) {
         // Create all elements and then the type itself
         std::vector<const Type*> elements;
         for (const auto& element : as<AstUnionType>(astType)->getTypes()) {
             auto* elementType = createType(element, nameToAstType);
             if (elementType == nullptr) {
                 return nullptr;
             }
             elements.push_back(elementType);
         }
         return &env.createType<UnionType>(typeName, elements);
     } else if (isA<AstRecordType>(astType)) {
         // Create anonymous base type first.
         // The types need to be initialized upfront,
         // because we may have mutually recursive record definitions.
         auto& recordBase = env.createType<RecordType>(tfm::format("__%sConstant", typeName));
         auto& recordType = env.createType<SubsetRecordType>(typeName, recordBase);
         std::vector<const Type*> elements;
         for (const auto* field : as<AstRecordType>(astType)->getFields()) {
             if (field->getTypeName() == typeName) {
                 elements.push_back(&recordBase);
                 continue;
             }
             auto* elementType = createType(field->getTypeName(), nameToAstType);
             if (elementType == nullptr) {
                 return nullptr;
             }
             elements.push_back(elementType);
         }
         recordBase.setFields(elements);
         std::replace(elements.begin(), elements.end(), dynamic_cast<Type*>(&recordBase),
                 dynamic_cast<Type*>(&recordType));
         recordType.setFields(std::move(elements));
         return &recordType;
     } else {
         fatal("unsupported type construct: %s", typeid(*astType).name());
     }
 }
getPrimitiveTypesInUnion()
const std::set<AstQualifiedName>& souffle::TypeEnvironmentAnalysis::getPrimitiveTypesInUnion (const AstQualifiedName & identifier) const inline
Definition at line 45 of file TypeEnvironment.h.
References primitiveTypesInUnions.
Referenced by souffle::AstSemanticCheckerImpl::checkUnionType().
{
         return primitiveTypesInUnions.at(identifier);
     }
getTypeEnvironment()
const TypeEnvironment& souffle::TypeEnvironmentAnalysis::getTypeEnvironment () const inline
Definition at line 41 of file TypeEnvironment.h.
References env.
{
         return env;
     }
isCyclic()
bool souffle::TypeEnvironmentAnalysis::isCyclic (const AstQualifiedName & identifier) const inline
Definition at line 49 of file TypeEnvironment.h.
References souffle::contains(), and cyclicTypes.
Referenced by souffle::AstSemanticCheckerImpl::checkSubsetType(), souffle::AstSemanticCheckerImpl::checkUnionType(), and run().
{
         return contains(cyclicTypes, identifier);
     }
print()
void souffle::TypeEnvironmentAnalysis::print (std::ostream &) const override virtual
print the analysis result in HTML format
Reimplemented from souffle::AstAnalysis.
Definition at line 210 of file TypeEnvironment.cpp.
Referenced by TypeEnvironmentAnalysis().
{
     env.print(os);
 }
run()
void souffle::TypeEnvironmentAnalysis::run (const AstTranslationUnit &) override virtual
run analysis for a Ast translation unit
Implements souffle::AstAnalysis.
Definition at line 110 of file TypeEnvironment.cpp.
References createType(), souffle::AstTranslationUnit::getProgram(), souffle::AstProgram::getTypes(), and isCyclic().
Referenced by TypeEnvironmentAnalysis().
{
     const AstProgram& program = *translationUnit.getProgram();
     auto rawProgramTypes = program.getTypes();
     Graph<AstQualifiedName> typeDependencyGraph{createTypeDependencyGraph(rawProgramTypes)};
     cyclicTypes = analyseCyclicTypes(typeDependencyGraph, rawProgramTypes);
     primitiveTypesInUnions = analysePrimitiveTypesInUnion(typeDependencyGraph, rawProgramTypes, env);
     std::map<AstQualifiedName, const AstType*> nameToAstType;
     // Filter redefined primitive types and cyclic types.
     std::vector<AstType*> programTypes;
     for (auto* type : program.getTypes()) {
         if (env.isType(type->getQualifiedName()) || isCyclic(type->getQualifiedName())) {
             continue;
         }
         programTypes.push_back(type);
         nameToAstType.insert({type->getQualifiedName(), type});
     }
     for (const auto* astType : programTypes) {
         createType(astType->getQualifiedName(), nameToAstType);
     }
 }
Field Documentation
cyclicTypes
std::set<AstQualifiedName> souffle::TypeEnvironmentAnalysis::cyclicTypes private
Definition at line 56 of file TypeEnvironment.h.
Referenced by isCyclic().
env
TypeEnvironment souffle::TypeEnvironmentAnalysis::env private
Definition at line 54 of file TypeEnvironment.h.
Referenced by getTypeEnvironment().
name
constexpr const char* souffle::TypeEnvironmentAnalysis::name = "type-environment" static
Definition at line 33 of file TypeEnvironment.h.
primitiveTypesInUnions
std::map<AstQualifiedName, std::set<AstQualifiedName> > souffle::TypeEnvironmentAnalysis::primitiveTypesInUnions private
Definition at line 55 of file TypeEnvironment.h.
Referenced by getPrimitiveTypesInUnion().
The documentation for this class was generated from the following files:
ast/analysis/TypeEnvironment.h
ast/analysis/TypeEnvironment.cpp