souffle: souffle::t_info< Arity > Class Template Reference
souffle::t_info< Arity > Class Template Reference
info relations
#include <CompiledSouffle.h>
Data Structures
struct context
class iterator
Public Types
using t_tuple = Tuple< RamDomain, Arity >
Public Member Functions
iterator begin () const
bool contains (const t_tuple &t) const
bool contains (const t_tuple &t, context &) const
context createContext ()
bool empty () const
iterator end () const
void insert (const t_tuple &t)
void insert (const t_tuple &t, context &)
void insert (const RamDomain *ramDomain)
void printHintStatistics (std::ostream &, std::string) const
void purge ()
std::size_t size () const
t_info ()=default
Private Attributes
std::vector< Tuple< RamDomain, Arity > > data
Lock insert_lock
Detailed Description
template<int Arity>
class souffle::t_info< Arity >
info relations
Definition at line 246 of file CompiledSouffle.h.
Member Typedef Documentation
t_tuple
template<int Arity> using souffle::t_info< Arity >::t_tuple = Tuple<RamDomain, Arity>
Definition at line 253 of file CompiledSouffle.h.
Constructor & Destructor Documentation
t_info()
template<int Arity> souffle::t_info< Arity >::t_info () default
Member Function Documentation
begin()
template<int Arity> iterator souffle::t_info< Arity >::begin () const inline
Definition at line 281 of file CompiledSouffle.h.
{
         return iterator(data.begin());
     }
contains() [1/2]
template<int Arity> bool souffle::t_info< Arity >::contains (const t_tuple & t) const inline
Definition at line 306 of file CompiledSouffle.h.
References o.
{
         for (const auto& o : data) {
             if (t == o) {
                 return true;
             }
         }
         return false;
     }
contains() [2/2]
template<int Arity> bool souffle::t_info< Arity >::contains (const t_tuple & t, context &) const inline
Definition at line 314 of file CompiledSouffle.h.
References souffle::RelationWrapper< id, RelType, TupleType, Arity, NumAuxAttributes >::contains().
{
         return contains(t);
     }
createContext()
template<int Arity> context souffle::t_info< Arity >::createContext () inline
Definition at line 255 of file CompiledSouffle.h.
{
         return context();
     }
empty()
template<int Arity> bool souffle::t_info< Arity >::empty () const inline
Definition at line 320 of file CompiledSouffle.h.
{
         return data.size() == 0;
     }
end()
template<int Arity> iterator souffle::t_info< Arity >::end () const inline
Definition at line 284 of file CompiledSouffle.h.
{
         return iterator(data.end());
     }
insert() [1/3]
template<int Arity> void souffle::t_info< Arity >::insert (const t_tuple & t) inline
Definition at line 287 of file CompiledSouffle.h.
References souffle::RelationWrapper< id, RelType, TupleType, Arity, NumAuxAttributes >::contains(), souffle::Lock::lock(), and souffle::Lock::unlock().
{
         insert_lock.lock();
         if (!contains(t)) {
             data.push_back(t);
         }
         insert_lock.unlock();
     }
insert() [2/3]
template<int Arity> void souffle::t_info< Arity >::insert (const t_tuple & t, context &) inline
Definition at line 294 of file CompiledSouffle.h.
References souffle::RelationWrapper< id, RelType, TupleType, Arity, NumAuxAttributes >::insert().
{
         insert(t);
     }
insert() [3/3]
template<int Arity> void souffle::t_info< Arity >::insert (const RamDomain * ramDomain) inline
Definition at line 297 of file CompiledSouffle.h.
References souffle::Tuple< Domain, _arity >::data, i, souffle::Lock::lock(), souffle::RelationWrapper< id, RelType, TupleType, Arity, NumAuxAttributes >::iterator_wrapper::t, and souffle::Lock::unlock().
{
         insert_lock.lock();
         t_tuple t;
         for (size_t i = 0; i < Arity; ++i) {
             t.data[i] = ramDomain[i];
         }
         data.push_back(t);
         insert_lock.unlock();
     }
printHintStatistics()
template<int Arity> void souffle::t_info< Arity >::printHintStatistics (std::ostream & , std::string) const inline
Definition at line 326 of file CompiledSouffle.h.
 {}
purge()
template<int Arity> void souffle::t_info< Arity >::purge () inline
Definition at line 323 of file CompiledSouffle.h.
                  {
         data.clear();
     }
size()
template<int Arity> std::size_t souffle::t_info< Arity >::size () const inline
Definition at line 317 of file CompiledSouffle.h.
{
         return data.size();
     }
Field Documentation
data
template<int Arity> std::vector<Tuple<RamDomain, Arity> > souffle::t_info< Arity >::data private
Definition at line 248 of file CompiledSouffle.h.
insert_lock
template<int Arity> Lock souffle::t_info< Arity >::insert_lock private
Definition at line 249 of file CompiledSouffle.h.
The documentation for this class was generated from the following file:
CompiledSouffle.h