souffle: souffle::WriteStreamCSV Class Reference
souffle::WriteStreamCSV Class Reference
#include <WriteStreamCSV.h>
Protected Member Functions
void writeNextTupleCSV (std::ostream &destination, const RamDomain *tuple)
void writeNextTupleElement (std::ostream &destination, const std::string &type, RamDomain value)
WriteStreamCSV (const std::map< std::string, std::string > &rwOperation, const SymbolTable &symbolTable, const RecordTable &recordTable)
Protected Member Functions inherited from souffle::WriteStream
void outputRecord (std::ostream &destination, const RamDomain value, const std::string &name)
template<typename Tuple >
void writeNext (const Tuple tuple)
virtual void writeNextTuple (const RamDomain *tuple)=0
virtual void writeNullary ()=0
virtual void writeSize (std::size_t)
Protected Member Functions inherited from souffle::SerialisationStream< true >
SerialisationStream (RO< SymbolTable > &symTab, RO< RecordTable > &recTab, Json types, std::vector< std::string > relTypes, size_t auxArity=0)
SerialisationStream (RO< SymbolTable > &symTab, RO< RecordTable > &recTab, Json types)
SerialisationStream (RO< SymbolTable > &symTab, RO< RecordTable > &recTab, const std::map< std::string, std::string > &rwOperation)
Protected Attributes
const std::string delimiter
Protected Attributes inherited from souffle::WriteStream
const bool summary
Protected Attributes inherited from souffle::SerialisationStream< true >
size_t arity
size_t auxiliaryArity
RO< RecordTable > & recordTable
RO< SymbolTable > & symbolTable
std::vector< std::string > typeAttributes
Json types
Additional Inherited Members
Public Member Functions inherited from souffle::WriteStream
template<typename T >
void writeAll (const T &relation)
template<>
void writeNext (const RamDomain *tuple)
template<typename T >
void writeSize (const T &relation)
WriteStream (const std::map< std::string, std::string > &rwOperation, const SymbolTable &symbolTable, const RecordTable &recordTable)
Public Member Functions inherited from souffle::SerialisationStream< true >
virtual ~SerialisationStream ()=default
Protected Types inherited from souffle::SerialisationStream< true >
using RO = std::conditional_t< readOnlyTables, const A, A >
Detailed Description
Definition at line 39 of file WriteStreamCSV.h.
Constructor & Destructor Documentation
WriteStreamCSV()
souffle::WriteStreamCSV::WriteStreamCSV (const std::map< std::string, std::string > & rwOperation, const SymbolTable & symbolTable, const RecordTable & recordTable) inline protected
Definition at line 41 of file WriteStreamCSV.h.
Referenced by souffle::WriteFileCSV::getFileName().
             : WriteStream(rwOperation, symbolTable, recordTable),
               delimiter(getOr(rwOperation, "delimiter", "\t")){};
Member Function Documentation
writeNextTupleCSV()
void souffle::WriteStreamCSV::writeNextTupleCSV (std::ostream & destination, const RamDomain * tuple) inline protected
Definition at line 48 of file WriteStreamCSV.h.
References souffle::SerialisationStream< true >::arity, delimiter, souffle::SerialisationStream< true >::typeAttributes, and writeNextTupleElement().
Referenced by souffle::WriteFileCSV::getFileName(), souffle::WriteFileCSV::writeNextTuple(), and souffle::WriteCoutCSV::writeNextTuple().
{
         writeNextTupleElement(destination, typeAttributes.at(0), tuple[0]);
         for (size_t col = 1; col < arity; ++col) {
             destination << delimiter;
             writeNextTupleElement(destination, typeAttributes.at(col), tuple[col]);
         }
         destination << "\n";
     }
writeNextTupleElement()
void souffle::WriteStreamCSV::writeNextTupleElement (std::ostream & destination, const std::string & type, RamDomain value) inline protected
Definition at line 59 of file WriteStreamCSV.h.
References souffle::fatal(), souffle::WriteStream::outputRecord(), and souffle::SerialisationStream< true >::symbolTable.
Referenced by writeNextTupleCSV().
{
         switch (type[0]) {
             case 's': destination << symbolTable.unsafeResolve(value); break;
             case 'i': destination << value; break;
             case 'u': destination << ramBitCast<RamUnsigned>(value); break;
             case 'f': destination << ramBitCast<RamFloat>(value); break;
             case 'r': outputRecord(destination, value, type); break;
             default: fatal("unsupported type attribute: `%c`", type[0]);
         }
     }
Field Documentation
delimiter
const std::string souffle::WriteStreamCSV::delimiter protected
Definition at line 44 of file WriteStreamCSV.h.
Referenced by writeNextTupleCSV().
The documentation for this class was generated from the following file:
WriteStreamCSV.h