souffle: souffle::Relation::iterator Class Reference
souffle::Relation::iterator Class Reference
Wrapper class for abstract iterator.
#include <SouffleInterface.h>
Public Member Functions
iterator ()=default
Constructor.
iterator (iterator &&arg)=default
Move constructor.
iterator (iterator_base *arg)
Constructor.
iterator (const iterator &o)
Constructor.
bool operator!= (const iterator &o) const
Overload the "!=" operator.
tuple & operator* () const
Overload the "*" operator.
iterator & operator++ ()
Overload the "++" operator.
iterator & operator= (const iterator &o)
Overload the "=" operator.
iterator & operator= (iterator &&o)
bool operator== (const iterator &o) const
Overload the "==" operator.
~iterator ()=default
Destructor.
Protected Attributes
std::unique_ptr< iterator_base > iter = nullptr
Detailed Description
Wrapper class for abstract iterator.
Users must use iterator class to access the tuples stored in a relation.
Definition at line 147 of file SouffleInterface.h.
Constructor & Destructor Documentation
iterator() [1/4]
souffle::Relation::iterator::iterator () default
Constructor.
iterator() [2/4]
souffle::Relation::iterator::iterator (iterator && arg) default
Move constructor.
The new iterator now has ownerhsip of the iterator base.
Parameters
arg lvalue reference to an iterator object
iterator() [3/4]
souffle::Relation::iterator::iterator (iterator_base * arg) inline
Constructor.
Initialise this iterator with a given iterator base
The new iterator has ownership of the iterator base.
Parameters
arg An iterator_base class pointer
Definition at line 179 of file SouffleInterface.h.
 : iter(arg) {}
~iterator()
souffle::Relation::iterator::~iterator () default
Destructor.
The iterator_base instance iter is pointing is destructed.
iterator() [4/4]
souffle::Relation::iterator::iterator (const iterator & o) inline
Constructor.
Initialise the iter to be the clone of arg.
Parameters
o Reference to an iterator object
Definition at line 195 of file SouffleInterface.h.
 : iter(o.iter->clone()) {}
Member Function Documentation
operator!=()
bool souffle::Relation::iterator::operator!= (const iterator & o) const inline
Overload the "!=" operator.
Check if the iterator object o is not the same as the current object.
Parameters
o Reference to a iterator object
Returns
Boolean. True, if they are not the same. False, otherwise
Definition at line 258 of file SouffleInterface.h.
References souffle::Relation::begin(), souffle::Relation::contains(), souffle::Relation::end(), souffle::Relation::getArity(), souffle::Relation::getAttrName(), souffle::Relation::getAttrType(), souffle::Relation::getAuxiliaryArity(), souffle::Relation::getName(), souffle::Relation::getSymbolTable(), souffle::Relation::insert(), o, and souffle::Relation::size().
{
             return !(*this == o);
         }
operator*()
tuple& souffle::Relation::iterator::operator* () const inline
Overload the "*" operator.
This will return the tuple that the iterator is pointing to.
Returns
Reference to a tuple object
Definition at line 233 of file SouffleInterface.h.
{
             return *(*iter);
         }
operator++()
iterator& souffle::Relation::iterator::operator++ () inline
Overload the "++" operator.
Increment the iterator_base object that iter is pointing to so that iterator_base object points to next tuple.
Returns
Reference to the iterator object which points to the next tuple in a relation
Definition at line 220 of file SouffleInterface.h.
{
             ++(*iter);
             return *this;
         }
operator=() [1/2]
iterator& souffle::Relation::iterator::operator= (const iterator & o) inline
Overload the "=" operator.
The original iterator_base instance is destructed.
Definition at line 202 of file SouffleInterface.h.
References iter.
{
             iter.reset(o.iter->clone());
             return *this;
         }
operator=() [2/2]
iterator& souffle::Relation::iterator::operator= (iterator && o) inline
Definition at line 207 of file SouffleInterface.h.
References o.
{
             iter.swap(o.iter);
             return *this;
         }
operator==()
bool souffle::Relation::iterator::operator== (const iterator & o) const inline
Overload the "==" operator.
Check if either the iter of o and the iter of current object are the same or the corresponding iterator_base objects are the same.
Parameters
o Reference to a iterator object
Returns
Boolean. True, if either of them is true. False, otherwise
Definition at line 246 of file SouffleInterface.h.
References iter.
{
             return (iter == o.iter) || (*iter == *o.iter);
         }
Field Documentation
iter
std::unique_ptr<iterator_base> souffle::Relation::iterator::iter = nullptr protected
Definition at line 153 of file SouffleInterface.h.
Referenced by operator=(), and operator==().
The documentation for this class was generated from the following file:
SouffleInterface.h