souffle: souffle::NullaryIndex Class Reference
souffle::NullaryIndex Class Reference
An index wrapper for nullary indexes.
Data Structures
struct NullaryIndexView
class Source
Public Member Functions
void clear () override
Clears the content of this index, turning it empty.
bool contains (const TupleRef &tuple) const override
Tests whether the given tuple is present in this index or not.
bool contains (const TupleRef &, const TupleRef &) const override
Tests whether this index contains any tuple within the given bounds.
IndexViewPtr createView () const override
Requests the creation of a view on this index.
bool empty () const override
Tests whether this index is empty or not.
size_t getArity () const override
Obtains the arity of the given index.
bool insert (const TupleRef &tuple) override
Inserts a tuple into this index.
void insert (const InterpreterIndex &src) override
Inserts all elements of the given index.
PartitionedStream partitionRange (const TupleRef &low, const TupleRef &high, int) const override
Returns a partitioned stream covering elements in the range [low,high)
PartitionedStream partitionScan (int) const override
Returns a partitioned stream covering the entire index content.
Stream range (const TupleRef &, const TupleRef &) const override
Returns a stream covering elements in the range [low,high)
Stream scan () const override
Returns a stream covering the entire index content.
std::size_t size () const override
Obtains the number of elements stored in this index.
Public Member Functions inherited from souffle::InterpreterIndex
virtual void extend (InterpreterIndex *)
Extend another index.
virtual ~InterpreterIndex ()=default
Private Attributes
std::atomic< bool > present = false
Detailed Description
An index wrapper for nullary indexes.
For those, no complex nested data structure is required.
Definition at line 180 of file InterpreterIndex.cpp.
Member Function Documentation
clear()
void souffle::NullaryIndex::clear () inline override virtual
Clears the content of this index, turning it empty.
Implements souffle::InterpreterIndex.
Definition at line 294 of file InterpreterIndex.cpp.
{
         present = false;
     }
contains() [1/2]
bool souffle::NullaryIndex::contains (const TupleRef & tuple) const inline override virtual
Tests whether the given tuple is present in this index or not.
Implements souffle::InterpreterIndex.
Definition at line 265 of file InterpreterIndex.cpp.
References souffle::TupleRef::size().
Referenced by souffle::NullaryIndex::NullaryIndexView::contains().
{
         assert(tuple.size() == 0);
         return present;
     }
contains() [2/2]
bool souffle::NullaryIndex::contains (const TupleRef & low, const TupleRef & high) const inline override virtual
Tests whether this index contains any tuple within the given bounds.
Implements souffle::InterpreterIndex.
Definition at line 270 of file InterpreterIndex.cpp.
{
         return present;
     }
createView()
IndexViewPtr souffle::NullaryIndex::createView () const inline override virtual
Requests the creation of a view on this index.
Implements souffle::InterpreterIndex.
Definition at line 249 of file InterpreterIndex.cpp.
{
         return std::make_unique<NullaryIndexView>(*this);
     }
empty()
bool souffle::NullaryIndex::empty () const inline override virtual
Tests whether this index is empty or not.
Implements souffle::InterpreterIndex.
Definition at line 241 of file InterpreterIndex.cpp.
{
         return !present;
     }
getArity()
size_t souffle::NullaryIndex::getArity () const inline override virtual
Obtains the arity of the given index.
Implements souffle::InterpreterIndex.
Definition at line 237 of file InterpreterIndex.cpp.
{
         return 0;
     }
insert() [1/2]
bool souffle::NullaryIndex::insert (const TupleRef & tuple) inline override virtual
Inserts a tuple into this index.
Implements souffle::InterpreterIndex.
Definition at line 253 of file InterpreterIndex.cpp.
References souffle::TupleRef::size().
{
         assert(tuple.size() == 0);
         bool res = present;
         present = true;
         return res;
     }
insert() [2/2]
void souffle::NullaryIndex::insert (const InterpreterIndex & src) inline override virtual
Inserts all elements of the given index.
Implements souffle::InterpreterIndex.
Definition at line 260 of file InterpreterIndex.cpp.
References souffle::InterpreterIndex::empty(), and souffle::InterpreterIndex::getArity().
{
         assert(src.getArity() == 0);
         present = present | !src.empty();
     }
partitionRange()
PartitionedStream souffle::NullaryIndex::partitionRange (const TupleRef & low, const TupleRef & high, int partitionCount) const inline override virtual
Returns a partitioned stream covering elements in the range [low,high)
Implements souffle::InterpreterIndex.
Definition at line 288 of file InterpreterIndex.cpp.
{
         std::vector<Stream> res;
         res.push_back(range(low, high));
         return res;
     }
partitionScan()
PartitionedStream souffle::NullaryIndex::partitionScan (int partitionCount) const inline override virtual
Returns a partitioned stream covering the entire index content.
Implements souffle::InterpreterIndex.
Definition at line 278 of file InterpreterIndex.cpp.
{
         std::vector<Stream> res;
         res.push_back(scan());
         return res;
     }
range()
Stream souffle::NullaryIndex::range (const TupleRef & low, const TupleRef & high) const inline override virtual
Returns a stream covering elements in the range [low,high)
Implements souffle::InterpreterIndex.
Definition at line 284 of file InterpreterIndex.cpp.
Referenced by souffle::NullaryIndex::NullaryIndexView::range().
{
         return scan();
     }
scan()
Stream souffle::NullaryIndex::scan () const inline override virtual
Returns a stream covering the entire index content.
Implements souffle::InterpreterIndex.
Definition at line 274 of file InterpreterIndex.cpp.
{
         return std::make_unique<Source>(present);
     }
size()
std::size_t souffle::NullaryIndex::size () const inline override virtual
Obtains the number of elements stored in this index.
Implements souffle::InterpreterIndex.
Definition at line 245 of file InterpreterIndex.cpp.
{
         return present ? 1 : 0;
     }
Field Documentation
present
std::atomic<bool> souffle::NullaryIndex::present = false private
Definition at line 182 of file InterpreterIndex.cpp.
The documentation for this class was generated from the following file:
interpreter/InterpreterIndex.cpp