souffle: souffle::RemoveRedundantSumsTransformer Class Reference
souffle::RemoveRedundantSumsTransformer Class Reference
Transformation pass to remove expressions of the form sum k : { ...
#include <RemoveRedundantSums.h>
Public Member Functions
RemoveRedundantSumsTransformer * clone () const override
std::string getName () const override
Public Member Functions inherited from souffle::AstTransformer
bool apply (AstTranslationUnit &translationUnit)
virtual ~AstTransformer ()=default
Private Member Functions
bool transform (AstTranslationUnit &translationUnit) override
Detailed Description
Transformation pass to remove expressions of the form sum k : { ...
} and replace them with k * count : { ... } where k is a constant.
Definition at line 30 of file RemoveRedundantSums.h.
Member Function Documentation
clone()
RemoveRedundantSumsTransformer* souffle::RemoveRedundantSumsTransformer::clone () const inline override virtual
Implements souffle::AstTransformer.
Definition at line 36 of file RemoveRedundantSums.h.
References transform().
{
         return new RemoveRedundantSumsTransformer();
     }
getName()
std::string souffle::RemoveRedundantSumsTransformer::getName () const inline override virtual
Implements souffle::AstTransformer.
Definition at line 32 of file RemoveRedundantSums.h.
{
         return "RemoveRedundantSumsTransformer";
     }
transform()
bool souffle::RemoveRedundantSumsTransformer::transform (AstTranslationUnit & translationUnit) override private virtual
Implements souffle::AstTransformer.
Definition at line 34 of file RemoveRedundantSums.cpp.
References souffle::AstProgram::apply(), souffle::clone(), souffle::test::count(), souffle::COUNT, souffle::AstTranslationUnit::getProgram(), and souffle::SUM.
Referenced by clone().
{
     struct ReplaceSumWithCount : public AstNodeMapper {
         ReplaceSumWithCount() = default;
         std::unique_ptr<AstNode> operator()(std::unique_ptr<AstNode> node) const override {
             // Apply to all aggregates of the form
             // sum k : { .. } where k is a constant
             if (auto* agg = dynamic_cast<AstAggregator*>(node.get())) {
                 if (agg->getOperator() == AggregateOp::SUM) {
                     if (const auto* constant =
                                     dynamic_cast<const AstNumericConstant*>(agg->getTargetExpression())) {
                         changed = true;
                         // Then construct the new thing to replace it with
                         auto count = std::make_unique<AstAggregator>(AggregateOp::COUNT);
                         // Duplicate the body of the aggregate
                         std::vector<std::unique_ptr<AstLiteral>> newBody;
                         for (const auto& lit : agg->getBodyLiterals()) {
                             newBody.push_back(souffle::clone(lit));
                         }
                         count->setBody(std::move(newBody));
                         auto number = souffle::clone(constant);
                         // Now it's constant * count : { ... }
                         auto result = std::make_unique<AstIntrinsicFunctor>(
                                 "*", std::move(number), std::move(count));
                         return result;
                     }
                 }
             }
             node->apply(*this);
             return node;
         }
         // variables
         mutable bool changed = false;
     };
     ReplaceSumWithCount update;
     translationUnit.getProgram()->apply(update);
     return update.changed;
 }
The documentation for this class was generated from the following files:
ast/transform/RemoveRedundantSums.h
ast/transform/RemoveRedundantSums.cpp