souffle: souffle::InterpreterRelInterface Class Reference
souffle::InterpreterRelInterface Class Reference
Wrapper class for interpreter relations.
#include <InterpreterProgInterface.h>
Data Structures
class iterator_base
Iterator wrapper class.
Public Member Functions
iterator begin () const override
Iterator to first tuple.
bool contains (const tuple &t) const override
Check whether tuple exists.
iterator end () const override
Iterator to last tuple.
size_t getArity () const override
Get arity.
const char * getAttrName (size_t idx) const override
Get attribute name.
const char * getAttrType (size_t idx) const override
Get attribute type.
size_t getAuxiliaryArity () const override
Get arity.
std::string getName () const override
Get name.
SymbolTable & getSymbolTable () const override
Get symbol table.
void insert (const tuple &t) override
Insert tuple.
InterpreterRelInterface (InterpreterRelation &r, SymbolTable &s, std::string n, std::vector< std::string > t, std::vector< std::string > an, uint32_t i)
void purge () override
Eliminate all the tuples in relation.
std::size_t size () const override
Get number of tuples in relation.
~InterpreterRelInterface () override=default
Public Member Functions inherited from souffle::Relation
std::string getSignature ()
Get the signature of a relation.
virtual ~Relation ()=default
Destructor.
Private Attributes
std::vector< std::string > attrNames
Attribute Names.
uint32_t id
Unique id for wrapper.
std::string name
Name of relation.
InterpreterRelation & relation
Wrapped interpreter relation.
SymbolTable & symTable
Symbol table.
std::vector< std::string > types
Attribute type.
Detailed Description
Wrapper class for interpreter relations.
Definition at line 47 of file InterpreterProgInterface.h.
Constructor & Destructor Documentation
InterpreterRelInterface()
souffle::InterpreterRelInterface::InterpreterRelInterface (InterpreterRelation & r, SymbolTable & s, std::string n, std::vector< std::string > t, std::vector< std::string > an, uint32_t i) inline
Definition at line 49 of file InterpreterProgInterface.h.
References ~InterpreterRelInterface().
             : relation(r), symTable(s), name(std::move(n)), types(std::move(t)), attrNames(std::move(an)),
               id(i) {}
~InterpreterRelInterface()
souffle::InterpreterRelInterface::~InterpreterRelInterface () override default
Referenced by InterpreterRelInterface().
Member Function Documentation
begin()
iterator souffle::InterpreterRelInterface::begin () const inline override virtual
Iterator to first tuple.
Implements souffle::Relation.
Definition at line 66 of file InterpreterProgInterface.h.
References souffle::InterpreterRelation::begin(), and relation.
{
         return InterpreterRelInterface::iterator(
                 new InterpreterRelInterface::iterator_base(id, this, relation.begin()));
     }
contains()
bool souffle::InterpreterRelInterface::contains (const tuple & t) const inline override virtual
Check whether tuple exists.
Implements souffle::Relation.
Definition at line 61 of file InterpreterProgInterface.h.
References souffle::InterpreterRelation::contains(), souffle::tuple::data, relation, and souffle::tuple::size().
{
         return relation.contains(TupleRef(&t.data[0], t.size()));
     }
end()
iterator souffle::InterpreterRelInterface::end () const inline override virtual
Iterator to last tuple.
Implements souffle::Relation.
Definition at line 72 of file InterpreterProgInterface.h.
References souffle::InterpreterRelation::end(), and relation.
{
         return InterpreterRelInterface::iterator(
                 new InterpreterRelInterface::iterator_base(id, this, relation.end()));
     }
getArity()
size_t souffle::InterpreterRelInterface::getArity () const inline override virtual
Get arity.
Implements souffle::Relation.
Definition at line 83 of file InterpreterProgInterface.h.
References souffle::InterpreterRelation::getArity(), and relation.
Referenced by getAttrName(), getAttrType(), and souffle::InterpreterRelInterface::iterator_base::operator*().
{
         return relation.getArity();
     }
getAttrName()
const char* souffle::InterpreterRelInterface::getAttrName (size_t idx) const inline override virtual
Get attribute name.
Implements souffle::Relation.
Definition at line 104 of file InterpreterProgInterface.h.
References attrNames, and getArity().
{
         assert(idx < getArity() && "exceeded tuple size");
         return attrNames[idx].c_str();
     }
getAttrType()
const char* souffle::InterpreterRelInterface::getAttrType (size_t idx) const inline override virtual
Get attribute type.
Implements souffle::Relation.
Definition at line 98 of file InterpreterProgInterface.h.
References getArity(), and types.
Referenced by souffle::InterpreterRelInterface::iterator_base::operator*().
{
         assert(idx < getArity() && "exceeded tuple size");
         return types[idx].c_str();
     }
getAuxiliaryArity()
size_t souffle::InterpreterRelInterface::getAuxiliaryArity () const inline override virtual
Get arity.
Implements souffle::Relation.
Definition at line 88 of file InterpreterProgInterface.h.
References souffle::InterpreterRelation::getAuxiliaryArity(), and relation.
{
         return relation.getAuxiliaryArity();
     }
getName()
std::string souffle::InterpreterRelInterface::getName () const inline override virtual
Get name.
Implements souffle::Relation.
Definition at line 78 of file InterpreterProgInterface.h.
References name.
{
         return name;
     }
getSymbolTable()
SymbolTable& souffle::InterpreterRelInterface::getSymbolTable () const inline override virtual
Get symbol table.
Implements souffle::Relation.
Definition at line 93 of file InterpreterProgInterface.h.
References symTable.
Referenced by souffle::InterpreterRelInterface::iterator_base::operator*().
{
         return symTable;
     }
insert()
void souffle::InterpreterRelInterface::insert (const tuple & t) inline override virtual
Insert tuple.
Implements souffle::Relation.
Definition at line 56 of file InterpreterProgInterface.h.
References souffle::tuple::data, souffle::InterpreterRelation::insert(), and relation.
Referenced by souffle::test::TEST().
{
         relation.insert(t.data);
     }
purge()
void souffle::InterpreterRelInterface::purge () inline override virtual
Eliminate all the tuples in relation.
Implements souffle::Relation.
Definition at line 115 of file InterpreterProgInterface.h.
References souffle::InterpreterRelation::purge(), and relation.
{
         relation.purge();
     }
size()
std::size_t souffle::InterpreterRelInterface::size () const inline override virtual
Get number of tuples in relation.
Implements souffle::Relation.
Definition at line 110 of file InterpreterProgInterface.h.
References relation, and souffle::InterpreterRelation::size().
{
         return relation.size();
     }
Field Documentation
attrNames
std::vector<std::string> souffle::InterpreterRelInterface::attrNames private
Attribute Names.
Definition at line 201 of file InterpreterProgInterface.h.
Referenced by getAttrName(), and souffle::InterpreterProgInterface::InterpreterProgInterface().
id
uint32_t souffle::InterpreterRelInterface::id private
Unique id for wrapper.
Definition at line 204 of file InterpreterProgInterface.h.
name
std::string souffle::InterpreterRelInterface::name private
Name of relation.
Definition at line 195 of file InterpreterProgInterface.h.
Referenced by getName(), and souffle::InterpreterProgInterface::InterpreterProgInterface().
relation
InterpreterRelation& souffle::InterpreterRelInterface::relation private
Wrapped interpreter relation.
Definition at line 189 of file InterpreterProgInterface.h.
Referenced by begin(), contains(), end(), getArity(), getAuxiliaryArity(), insert(), purge(), and size().
symTable
SymbolTable& souffle::InterpreterRelInterface::symTable private
Symbol table.
Definition at line 192 of file InterpreterProgInterface.h.
Referenced by getSymbolTable(), and souffle::InterpreterProgInterface::getSymbolTable().
types
std::vector<std::string> souffle::InterpreterRelInterface::types private
Attribute type.
Definition at line 198 of file InterpreterProgInterface.h.
Referenced by getAttrType(), and souffle::InterpreterProgInterface::InterpreterProgInterface().
The documentation for this class was generated from the following file:
interpreter/InterpreterProgInterface.h