souffle: souffle::AstUnionType Class Reference
souffle::AstUnionType Class Reference
A union type combines multiple types into a new super type.
#include <UnionType.h>
Public Member Functions
void add (AstQualifiedName type)
Adds another element type.
AstUnionType (AstQualifiedName name, std::vector< AstQualifiedName > types, SrcLocation loc={})
AstUnionType * clone () const override
Create a clone (i.e.
const std::vector< AstQualifiedName > & getTypes () const
Obtains a reference to the list element types.
void setVariantType (size_t idx, AstQualifiedName type)
Set variant type.
Public Member Functions inherited from souffle::AstType
AstType (AstQualifiedName name={}, SrcLocation loc={})
const AstQualifiedName & getQualifiedName () const
get type name
void setQualifiedName (AstQualifiedName name)
set type name
Public Member Functions inherited from souffle::AstNode
virtual void apply (const AstNodeMapper &)
Apply the mapper to all child nodes.
AstNode (SrcLocation loc={})
std::string extloc () const
Return source location of the syntactic element.
virtual std::vector< const AstNode * > getChildNodes () const
Obtain a list of all embedded AST child nodes.
const SrcLocation & getSrcLoc () const
Return source location of the AstNode.
bool operator!= (const AstNode &other) const
Inequality check for two AST nodes.
bool operator== (const AstNode &other) const
Equivalence check for two AST nodes.
void setSrcLoc (SrcLocation l)
Set source location for the AstNode.
virtual ~AstNode ()=default
Protected Member Functions
bool equal (const AstNode &node) const override
Abstract equality check for two AST nodes.
void print (std::ostream &os) const override
Output to a given output stream.
Private Attributes
std::vector< AstQualifiedName > types
The list of types aggregated by this union type.
Detailed Description
A union type combines multiple types into a new super type.
Each of the enumerated types become a sub-type of the new union type.
Definition at line 38 of file UnionType.h.
Constructor & Destructor Documentation
AstUnionType()
souffle::AstUnionType::AstUnionType (AstQualifiedName name, std::vector< AstQualifiedName > types, SrcLocation loc = {}) inline
Definition at line 40 of file UnionType.h.
References souffle::AstType::AstType(), and types.
Referenced by clone().
                                                                                              {})
             : AstType(std::move(name), std::move(loc)), types(std::move(types)) {}
Member Function Documentation
add()
void souffle::AstUnionType::add (AstQualifiedName type) inline
Adds another element type.
Definition at line 49 of file UnionType.h.
{
         types.push_back(std::move(type));
     }
clone()
AstUnionType* souffle::AstUnionType::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::AstType.
Definition at line 58 of file UnionType.h.
References AstUnionType(), souffle::AstType::getQualifiedName(), and souffle::AstNode::getSrcLoc().
{
         return new AstUnionType(getQualifiedName(), types, getSrcLoc());
     }
equal()
bool souffle::AstUnionType::equal (const AstNode &) const inline override protected virtual
Abstract equality check for two AST nodes.
Reimplemented from souffle::AstNode.
Definition at line 67 of file UnionType.h.
References souffle::AstType::getQualifiedName().
{
         const auto& other = static_cast<const AstUnionType&>(node);
         return getQualifiedName() == other.getQualifiedName() && types == other.types;
     }
getTypes()
const std::vector<AstQualifiedName>& souffle::AstUnionType::getTypes () const inline
Obtains a reference to the list element types.
Definition at line 44 of file UnionType.h.
References types.
Referenced by souffle::AstSemanticCheckerImpl::checkUnionType().
{
         return types;
     }
print()
void souffle::AstUnionType::print (std::ostream & os) const inline override protected virtual
Output to a given output stream.
Implements souffle::AstNode.
Definition at line 63 of file UnionType.h.
References souffle::AstType::getQualifiedName(), and souffle::join().
{
         os << ".type " << getQualifiedName() << " = " << join(types, " | ");
     }
setVariantType()
void souffle::AstUnionType::setVariantType (size_t idx, AstQualifiedName type) inline
Set variant type.
Definition at line 54 of file UnionType.h.
{
         types.at(idx) = std::move(type);
     }
Field Documentation
types
std::vector<AstQualifiedName> souffle::AstUnionType::types private
The list of types aggregated by this union type.
Definition at line 74 of file UnionType.h.
Referenced by AstUnionType(), and getTypes().
The documentation for this class was generated from the following file:
ast/UnionType.h