souffle: souffle::AstToRamTranslator::ValueIndex Class Reference
souffle::AstToRamTranslator::ValueIndex Class Reference
A class indexing the location of variables and record references within a loop nest resulting from the conversion of a rule.
Public Member Functions
void addVarReference (const AstVariable &var, const Location &l)
void addVarReference (const AstVariable &var, int ident, int pos, std::unique_ptr< RamRelationReference > rel=nullptr)
const Location & getDefinitionPoint (const AstVariable &var) const
const Location & getDefinitionPoint (const AstRecordInit &init) const
const Location & getGeneratorLoc (const AstArgument &arg) const
const variable_reference_map & getVariableReferences () const
bool isDefined (const AstVariable &var) const
bool isGenerator (const int level) const
bool isSomethingDefinedOn (int level) const
void print (std::ostream &out) const
void setGeneratorLoc (const AstArgument &agg, const Location &loc)
void setRecordDefinition (const AstRecordInit &init, const Location &l)
void setRecordDefinition (const AstRecordInit &init, int ident, int pos, std::unique_ptr< RamRelationReference > rel=nullptr)
Private Types
using generator_location_map = std::vector< std::pair< const AstArgument *, Location > >
A map from generative AstArguments to storage locations.
using record_definition_map = std::map< const AstRecordInit *, Location >
The type mapping record init expressions to their definition points, hence the point where they get grounded/bound.
using variable_reference_map = std::map< std::string, std::set< Location > >
The type mapping variables (referenced by their names) to the locations where they are used.
Private Attributes
generator_location_map arg_generator_locations
The level of a nested ram operation that is handling a generator operation.
record_definition_map record_definitions
The index of record definition points.
variable_reference_map var_references
The index of variable accesses.
Friends
std::ostream & operator<< (std::ostream &out, const ValueIndex &index) __attribute__((unused))
Detailed Description
A class indexing the location of variables and record references within a loop nest resulting from the conversion of a rule.
Definition at line 151 of file AstToRamTranslator.h.
Member Typedef Documentation
generator_location_map
using souffle::AstToRamTranslator::ValueIndex::generator_location_map = std::vector<std::pair<const AstArgument*, Location> > private
A map from generative AstArguments to storage locations.
Note, since in this case AstArgument are indexed by their values (not their address) no standard map can be utilized. (By-value indexing induces an ad-hoc form of CSE.)
Definition at line 170 of file AstToRamTranslator.h.
record_definition_map
using souffle::AstToRamTranslator::ValueIndex::record_definition_map = std::map<const AstRecordInit*, Location> private
The type mapping record init expressions to their definition points, hence the point where they get grounded/bound.
Definition at line 162 of file AstToRamTranslator.h.
variable_reference_map
using souffle::AstToRamTranslator::ValueIndex::variable_reference_map = std::map<std::string, std::set<Location> > private
The type mapping variables (referenced by their names) to the locations where they are used.
Definition at line 156 of file AstToRamTranslator.h.
Member Function Documentation
addVarReference() [1/2]
void souffle::AstToRamTranslator::ValueIndex::addVarReference (const AstVariable & var, const Location & l) inline
Definition at line 184 of file AstToRamTranslator.h.
References souffle::AstVariable::getName().
{
             std::set<Location>& locs = var_references[var.getName()];
             locs.insert(l);
         }
addVarReference() [2/2]
void souffle::AstToRamTranslator::ValueIndex::addVarReference (const AstVariable & var, int ident, int pos, std::unique_ptr< RamRelationReference > rel = nullptr) inline
Definition at line 189 of file AstToRamTranslator.h.
References souffle::AstToRamTranslator::Location::Location().
{
             addVarReference(var, Location({ident, pos, std::move(rel)}));
         }
getDefinitionPoint() [1/2]
const Location& souffle::AstToRamTranslator::ValueIndex::getDefinitionPoint (const AstVariable & var) const inline
Definition at line 198 of file AstToRamTranslator.h.
References souffle::AstVariable::getName().
Referenced by souffle::AstToRamTranslator::translateValue().
{
             auto pos = var_references.find(var.getName());
             assert(pos != var_references.end() && "Undefined variable referenced!");
             return *pos->second.begin();
         }
getDefinitionPoint() [2/2]
const Location& souffle::AstToRamTranslator::ValueIndex::getDefinitionPoint (const AstRecordInit & init) const inline
Definition at line 221 of file AstToRamTranslator.h.
References souffle::fatal().
{
             auto pos = record_definitions.find(&init);
             if (pos != record_definitions.end()) {
                 return pos->second;
             }
             fatal("requested location for undefined record!");
         }
getGeneratorLoc()
const Location& souffle::AstToRamTranslator::ValueIndex::getGeneratorLoc (const AstArgument & arg) const inline
Definition at line 236 of file AstToRamTranslator.h.
References souffle::fatal().
Referenced by souffle::AstToRamTranslator::translateValue().
{
             // search list
             for (const auto& cur : arg_generator_locations) {
                 if (*cur.first == arg) {
                     return cur.second;
                 }
             }
             fatal("arg `%s` has no generator location", arg);
         }
getVariableReferences()
const variable_reference_map& souffle::AstToRamTranslator::ValueIndex::getVariableReferences () const inline
Definition at line 204 of file AstToRamTranslator.h.
{
             return var_references;
         }
isDefined()
bool souffle::AstToRamTranslator::ValueIndex::isDefined (const AstVariable & var) const inline
Definition at line 194 of file AstToRamTranslator.h.
References souffle::AstVariable::getName().
Referenced by souffle::AstToRamTranslator::translateValue().
{
             return var_references.find(var.getName()) != var_references.end();
         }
isGenerator()
bool souffle::AstToRamTranslator::ValueIndex::isGenerator (const int level) const inline
Definition at line 249 of file AstToRamTranslator.h.
References souffle::any_of().
{
             // check for aggregator definitions
             return any_of(arg_generator_locations,
                     [&level](const auto& location) { return location.second.identifier == level; });
         }
isSomethingDefinedOn()
bool souffle::AstToRamTranslator::ValueIndex::isSomethingDefinedOn (int level) const inline
Definition at line 255 of file AstToRamTranslator.h.
{
             // check for variable definitions
             for (const auto& cur : var_references) {
                 if (cur.second.begin()->identifier == level) {
                     return true;
                 }
             }
             // check for record definitions
             for (const auto& cur : record_definitions) {
                 if (cur.second.identifier == level) {
                     return true;
                 }
             }
             // nothing defined on this level
             return false;
         }
print()
void souffle::AstToRamTranslator::ValueIndex::print (std::ostream & out) const inline
Definition at line 272 of file AstToRamTranslator.h.
References souffle::join().
{
             out << "Variables:\n\t";
             out << join(var_references, "\n\t");
         }
setGeneratorLoc()
void souffle::AstToRamTranslator::ValueIndex::setGeneratorLoc (const AstArgument & agg, const Location & loc) inline
Definition at line 232 of file AstToRamTranslator.h.
{
             arg_generator_locations.push_back(std::make_pair(&agg, loc));
         }
setRecordDefinition() [1/2]
void souffle::AstToRamTranslator::ValueIndex::setRecordDefinition (const AstRecordInit & init, const Location & l) inline
Definition at line 212 of file AstToRamTranslator.h.
References l.
{
             record_definitions[&init] = l;
         }
setRecordDefinition() [2/2]
void souffle::AstToRamTranslator::ValueIndex::setRecordDefinition (const AstRecordInit & init, int ident, int pos, std::unique_ptr< RamRelationReference > rel = nullptr) inline
Definition at line 216 of file AstToRamTranslator.h.
References souffle::AstToRamTranslator::Location::Location().
{
             setRecordDefinition(init, Location({ident, pos, std::move(rel)}));
         }
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & out, const ValueIndex & index) friend
Definition at line 277 of file AstToRamTranslator.h.
{
             index.print(out);
             return out;
         }
Field Documentation
arg_generator_locations
generator_location_map souffle::AstToRamTranslator::ValueIndex::arg_generator_locations private
The level of a nested ram operation that is handling a generator operation.
Definition at line 179 of file AstToRamTranslator.h.
record_definitions
record_definition_map souffle::AstToRamTranslator::ValueIndex::record_definitions private
The index of record definition points.
Definition at line 176 of file AstToRamTranslator.h.
var_references
variable_reference_map souffle::AstToRamTranslator::ValueIndex::var_references private
The index of variable accesses.
Definition at line 173 of file AstToRamTranslator.h.
The documentation for this class was generated from the following file:
AstToRamTranslator.h