souffle: souffle::Relation::iterator_base Class Reference
souffle::Relation::iterator_base Class Reference abstract
Abstract iterator class.
#include <SouffleInterface.h>
Public Member Functions
virtual iterator_base * clone () const =0
Clone the iterator_base.
virtual uint32_t getId () const
Get the ID of the iterator_base object.
iterator_base (uint32_t arg_id)
Constructor.
virtual tuple & operator* ()=0
Overload the "*" operator.
virtual void operator++ ()=0
Overload the "++" operator.
bool operator== (const iterator_base &o) const
Overload the "==" operator.
virtual ~iterator_base ()=default
Destructor.
Protected Member Functions
virtual bool equal (const iterator_base &o) const =0
Check if the passed-in object of o is the the same as the current iterator_base.
Protected Attributes
uint32_t id
Required for identifying type of iterator (NB: LLVM has no typeinfo).
Detailed Description
Abstract iterator class.
When tuples are inserted into a relation, they will be stored contiguously. Intially, the iterator_base of a relation will point to the first tuple inserted. iterator_base can be moved to point to the next tuple until the end. The tuple iterator_base is pointing to can be accessed. However, users can not use this to access tuples since iterator class is protected. Instead, they should use the public class - iterator which interacts with iterator_base.
Definition at line 53 of file SouffleInterface.h.
Constructor & Destructor Documentation
iterator_base()
souffle::Relation::iterator_base::iterator_base (uint32_t arg_id) inline
Constructor.
Create an instance of iterator_base and set its ID to be arg_id.
Parameters
arg_id ID of an iterator object (unit32_t)
Definition at line 80 of file SouffleInterface.h.
References operator*(), operator++(), and ~iterator_base().
 : id(arg_id) {}
~iterator_base()
virtual souffle::Relation::iterator_base::~iterator_base () virtual default
Destructor.
Reimplemented in souffle::InterpreterRelInterface::iterator_base.
Referenced by iterator_base().
Member Function Documentation
clone()
virtual iterator_base* souffle::Relation::iterator_base::clone () const pure virtual
Clone the iterator_base.
The definition of clone has to be defined by the child class of iterator_base.
Returns
An iterator_base pointer
Implemented in souffle::InterpreterRelInterface::iterator_base.
Referenced by operator==().
equal()
virtual bool souffle::Relation::iterator_base::equal (const iterator_base & o) const protected pure virtual
Check if the passed-in object of o is the the same as the current iterator_base.
TODO (Honghyw) : Provide a clear documentation of what equal function does.
Parameters
o Reference to an object of the iterator_base class
Returns
A boolean value. If two iterator_base are the same return true. Otherwise return false
Implemented in souffle::InterpreterRelInterface::iterator_base.
Referenced by operator==().
getId()
virtual uint32_t souffle::Relation::iterator_base::getId () const inline virtual
Get the ID of the iterator_base object.
Returns
ID of the iterator_base object (unit32_t)
Definition at line 69 of file SouffleInterface.h.
References id.
Referenced by souffle::InterpreterRelInterface::iterator_base::clone(), and operator==().
{
             return id;
         }
operator*()
virtual tuple& souffle::Relation::iterator_base::operator* () pure virtual
Overload the "*" operator.
Return the tuple that is pointed to by the iterator_base. The definition of this overloading has to be defined by the child class of iterator_base.
Returns
tuple Reference to a tuple object
Implemented in souffle::InterpreterRelInterface::iterator_base.
Referenced by iterator_base().
operator++()
virtual void souffle::Relation::iterator_base::operator++ () pure virtual
Overload the "++" operator.
Increment the iterator_base so that the iterator_base will now point to the next tuple. The definition of this overloading has to be defined by the child class of iterator_base.
Implemented in souffle::InterpreterRelInterface::iterator_base.
Referenced by iterator_base().
operator==()
bool souffle::Relation::iterator_base::operator== (const iterator_base & o) const inline
Overload the "==" operator.
Parameters
o Reference to an object of the iterator_base class
Returns
A boolean value, if the ID of o is the same as the ID of the current object and equal(o) returns true. Otherwise return false
Definition at line 112 of file SouffleInterface.h.
References clone(), equal(), getId(), o, and souffle::Relation::~Relation().
{
             return this->getId() == o.getId() && equal(o);
         }
Field Documentation
id
uint32_t souffle::Relation::iterator_base::id protected
Required for identifying type of iterator (NB: LLVM has no typeinfo).
TODO (Honghyw) : Provide a clear documentation of what id is used for.
Definition at line 61 of file SouffleInterface.h.
Referenced by getId().
The documentation for this class was generated from the following file:
SouffleInterface.h