souffle: souffle::RedundantRelationsAnalysis Class Reference
souffle::RedundantRelationsAnalysis Class Reference
Analysis pass identifying relations which do not contribute to the computation of the output relations.
#include <RedundantRelations.h>
Public Member Functions
const std::set< const AstRelation * > & getRedundantRelations () const
void print (std::ostream &os) const override
print the analysis result in HTML format
RedundantRelationsAnalysis ()
void run (const AstTranslationUnit &translationUnit) override
run analysis for a Ast translation unit
Public Member Functions inherited from souffle::AstAnalysis
AstAnalysis (std::string identifier)
virtual const std::string & getName () const
get name of the analysis
virtual ~AstAnalysis ()=default
Static Public Attributes
static constexpr const char * name = "redundant-relations"
Private Attributes
PrecedenceGraphAnalysis * precedenceGraph = nullptr
std::set< const AstRelation * > redundantRelations
Additional Inherited Members
Protected Attributes inherited from souffle::AstAnalysis
const std::string identifier
Detailed Description
Analysis pass identifying relations which do not contribute to the computation of the output relations.
Definition at line 35 of file RedundantRelations.h.
Constructor & Destructor Documentation
RedundantRelationsAnalysis()
souffle::RedundantRelationsAnalysis::RedundantRelationsAnalysis () inline
Definition at line 39 of file RedundantRelations.h.
References print(), and run().
 : AstAnalysis(name) {}
Member Function Documentation
getRedundantRelations()
const std::set<const AstRelation*>& souffle::RedundantRelationsAnalysis::getRedundantRelations () const inline
Definition at line 45 of file RedundantRelations.h.
References redundantRelations.
Referenced by souffle::RemoveRedundantRelationsTransformer::transform().
{
         return redundantRelations;
     }
print()
void souffle::RedundantRelationsAnalysis::print (std::ostream &) const override virtual
print the analysis result in HTML format
Reimplemented from souffle::AstAnalysis.
Definition at line 74 of file RedundantRelations.cpp.
References redundantRelations.
Referenced by RedundantRelationsAnalysis().
{
     os << redundantRelations << std::endl;
 }
run()
void souffle::RedundantRelationsAnalysis::run (const AstTranslationUnit &) override virtual
run analysis for a Ast translation unit
Implements souffle::AstAnalysis.
Definition at line 33 of file RedundantRelations.cpp.
References souffle::AstTranslationUnit::getAnalysis(), souffle::AstTranslationUnit::getProgram(), souffle::AstProgram::getRelations(), souffle::PrecedenceGraphAnalysis::graph(), precedenceGraph, redundantRelations, and relations.
Referenced by RedundantRelationsAnalysis().
{
     precedenceGraph = translationUnit.getAnalysis<PrecedenceGraphAnalysis>();
     std::set<const AstRelation*> work;
     std::set<const AstRelation*> notRedundant;
     auto* ioType = translationUnit.getAnalysis<IOType>();
     const std::vector<AstRelation*>& relations = translationUnit.getProgram()->getRelations();
     /* Add all output relations to the work set */
     for (const AstRelation* r : relations) {
         if (ioType->isOutput(r)) {
             work.insert(r);
         }
     }
     /* Find all relations which are not redundant for the computations of the
        output relations. */
     while (!work.empty()) {
         /* Chose one element in the work set and add it to notRedundant */
         const AstRelation* u = *(work.begin());
         work.erase(work.begin());
         notRedundant.insert(u);
         /* Find all predecessors of u and add them to the worklist
             if they are not in the set notRedundant */
         for (const AstRelation* predecessor : precedenceGraph->graph().predecessors(u)) {
             if (notRedundant.count(predecessor) == 0u) {
                 work.insert(predecessor);
             }
         }
     }
     /* All remaining relations are redundant. */
     redundantRelations.clear();
     for (const AstRelation* r : relations) {
         if (notRedundant.count(r) == 0u) {
             redundantRelations.insert(r);
         }
     }
 }
Field Documentation
name
constexpr const char* souffle::RedundantRelationsAnalysis::name = "redundant-relations" static
Definition at line 37 of file RedundantRelations.h.
precedenceGraph
PrecedenceGraphAnalysis* souffle::RedundantRelationsAnalysis::precedenceGraph = nullptr private
Definition at line 50 of file RedundantRelations.h.
Referenced by run().
redundantRelations
std::set<const AstRelation*> souffle::RedundantRelationsAnalysis::redundantRelations private
Definition at line 52 of file RedundantRelations.h.
Referenced by getRedundantRelations(), print(), and run().
The documentation for this class was generated from the following files:
ast/analysis/RedundantRelations.h
ast/analysis/RedundantRelations.cpp