souffle: souffle::SearchSignature Class Reference
souffle::SearchSignature Class Reference
search signature of a RAM operation; each bit represents an attribute of a relation.
#include <IndexAnalysis.h>
Public Member Functions
size_t arity () const
bool empty () const
bool isStrictSubset (const SearchSignature &other) const
bool operator< (const SearchSignature &other) const
bool operator== (const SearchSignature &other) const
AttributeConstraint operator[] (std::size_t pos) const
SearchSignature (size_t arity)
SearchSignature & set (size_t pos, AttributeConstraint constraint)
Static Public Member Functions
static SearchSignature getDelta (const SearchSignature &lhs, const SearchSignature &rhs)
static SearchSignature getFullSearchSignature (size_t arity)
Private Attributes
std::vector< AttributeConstraint > constraints
Friends
std::ostream & operator<< (std::ostream &out, const SearchSignature &signature)
Detailed Description
search signature of a RAM operation; each bit represents an attribute of a relation.
A one represents that the attribute has an assigned value; a zero represents that no value exists (i.e. attribute is unbounded) in the search.
Definition at line 51 of file IndexAnalysis.h.
Constructor & Destructor Documentation
SearchSignature()
souffle::SearchSignature::SearchSignature (size_t arity) inline explicit
Definition at line 53 of file IndexAnalysis.h.
 : constraints(arity, AttributeConstraint::None) {}
Member Function Documentation
arity()
size_t souffle::SearchSignature::arity () const inline
Definition at line 55 of file IndexAnalysis.h.
Referenced by souffle::MinIndexSelection::card(), souffle::NodeGenerator::encodeIndexPos(), getDelta(), and souffle::MinIndexSelection::insertIndex().
{
         return constraints.size();
     }
empty()
bool souffle::SearchSignature::empty () const inline
Definition at line 90 of file IndexAnalysis.h.
References i, and souffle::None.
Referenced by souffle::MinIndexSelection::addSearch(), and souffle::NodeGenerator::encodeIndexPos().
{
         size_t len = constraints.size();
         for (size_t i = 0; i < len; ++i) {
             if (constraints[i] != AttributeConstraint::None) {
                 return false;
             }
         }
         return true;
     }
getDelta()
static SearchSignature souffle::SearchSignature::getDelta (const SearchSignature & lhs, const SearchSignature & rhs) inline static
Definition at line 112 of file IndexAnalysis.h.
References arity(), constraints, i, and souffle::None.
Referenced by souffle::MinIndexSelection::solve().
{
         assert(lhs.arity() == rhs.arity());
         SearchSignature delta(lhs.arity());
         for (size_t i = 0; i < lhs.arity(); ++i) {
             // if constraints are the same then delta is nothing
             if (lhs.constraints[i] == rhs.constraints[i]) {
                 delta.constraints[i] = AttributeConstraint::None;
                 continue;
             }
             // if rhs has no constraint then delta has lhs constraint
             if (rhs.constraints[i] == AttributeConstraint::None) {
                 delta.constraints[i] = lhs.constraints[i];
                 continue;
             }
             assert(false && "lhs and rhs should not have inequal/equal pair constraints");
         }
         return delta;
     }
getFullSearchSignature()
static SearchSignature souffle::SearchSignature::getFullSearchSignature (size_t arity) inline static
Definition at line 133 of file IndexAnalysis.h.
References constraints, souffle::Equal, and i.
Referenced by souffle::NodeGenerator::encodeIndexPos(), souffle::RamIndexAnalysis::getSearchSignature(), and souffle::MinIndexSelection::insertDefaultTotalIndex().
{
         SearchSignature res(arity);
         for (size_t i = 0; i < arity; ++i) {
             res.constraints[i] = AttributeConstraint::Equal;
         }
         return res;
     }
isStrictSubset()
bool souffle::SearchSignature::isStrictSubset (const SearchSignature & other) const inline
Definition at line 100 of file IndexAnalysis.h.
References constraints, i, and souffle::None.
{
         assert(constraints.size() == other.constraints.size());
         size_t len = constraints.size();
         for (size_t i = 0; i < len; ++i) {
             if ((constraints[i] != AttributeConstraint::None) &&
                     (other.constraints[i] == AttributeConstraint::None)) {
                 return false;
             }
         }
         return constraints != other.constraints;
     }
operator<()
bool souffle::SearchSignature::operator< (const SearchSignature & other) const inline
Definition at line 66 of file IndexAnalysis.h.
References constraints, and i.
{
         assert(constraints.size() == other.constraints.size());
         size_t len = constraints.size();
         for (size_t i = 0; i < len; ++i) {
             size_t index = len - i - 1;  // get right to left index order
             // if ours has a constraint and other's has a constraint then it is smaller
             if (constraints[index] < other.constraints[index]) {
                 return true;
             }
             // if ours has a constraint and other's has no constraint then it is larger
             else if (constraints[index] > other.constraints[index]) {
                 return false;
             }
         }
         return false;
     }
operator==()
bool souffle::SearchSignature::operator== (const SearchSignature & other) const inline
Definition at line 85 of file IndexAnalysis.h.
References constraints.
{
         assert(constraints.size() == other.constraints.size());
         return constraints == other.constraints;
     }
operator[]()
AttributeConstraint souffle::SearchSignature::operator[] (std::size_t pos) const inline
Definition at line 60 of file IndexAnalysis.h.
{
         assert(pos < constraints.size());
         return constraints[pos];
     }
set()
SearchSignature& souffle::SearchSignature::set (size_t pos, AttributeConstraint constraint) inline
Definition at line 142 of file IndexAnalysis.h.
References souffle::operator<<().
Referenced by souffle::SynthesiserEqrelRelation::generateTypeStruct(), souffle::RamIndexAnalysis::getSearchSignature(), souffle::RamIndexAnalysis::print(), souffle::setBits(), and souffle::TEST().
{
         assert(pos < constraints.size());
         constraints[pos] = constraint;
         return *this;
     }
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & out, const SearchSignature & signature) friend
Definition at line 154 of file IndexAnalysis.h.
{
     size_t len = signature.constraints.size();
     for (size_t i = 0; i < len; ++i) {
         switch (signature.constraints[len - 1 - i]) {
             case AttributeConstraint::None: out << 0; break;
             case AttributeConstraint::Equal: out << 1; break;
             case AttributeConstraint::Inequal: out << 2; break;
         }
     }
     return out;
 }
Field Documentation
constraints
std::vector<AttributeConstraint> souffle::SearchSignature::constraints private
Definition at line 151 of file IndexAnalysis.h.
Referenced by getDelta(), getFullSearchSignature(), isStrictSubset(), operator<(), souffle::operator<<(), and operator==().
The documentation for this class was generated from the following file:
ram/analysis/IndexAnalysis.h