souffle: souffle::profile::ProgramTimepointProcessor Class Reference
souffle::profile::ProgramTimepointProcessor Class Reference
Program Run Event Processor.
#include <EventProcessor.h>
Public Member Functions
void process (ProfileDatabase &db, const std::vector< std::string > &signature, va_list &args) override
process event input
ProgramTimepointProcessor ()
Public Member Functions inherited from souffle::profile::EventProcessor
virtual ~EventProcessor ()=default
Detailed Description
Program Run Event Processor.
Definition at line 430 of file EventProcessor.h.
Constructor & Destructor Documentation
ProgramTimepointProcessor()
souffle::profile::ProgramTimepointProcessor::ProgramTimepointProcessor () inline
Definition at line 432 of file EventProcessor.h.
References souffle::profile::EventProcessorSingleton::instance(), and souffle::profile::EventProcessorSingleton::registerEventProcessor().
{
         EventProcessorSingleton::instance().registerEventProcessor("@time", this);
     }
Member Function Documentation
process()
void souffle::profile::ProgramTimepointProcessor::process (ProfileDatabase & db, const std::vector< std::string > & signature, va_list & args) inline override virtual
process event input
Reimplemented from souffle::profile::EventProcessor.
Definition at line 436 of file EventProcessor.h.
References souffle::profile::programTimepointProcessor, and souffle::test::time().
{
         microseconds time = va_arg(args, microseconds);
         auto path = signature;
         path[0] = "program";
         db.addTimeEntry(path, time);
     }
The documentation for this class was generated from the following file:
EventProcessor.h