souffle: souffle::RamSwap Class Reference
souffle::RamSwap Class Reference
Swap operation with respect to two relations.
#include <Statement.h>
Public Member Functions
RamSwap * clone () const override
Create a clone (i.e.
RamSwap (std::unique_ptr< RamRelationReference > f, std::unique_ptr< RamRelationReference > s)
Public Member Functions inherited from souffle::RamBinRelationStatement
void apply (const RamNodeMapper &map) override
Apply the mapper to all child nodes.
std::vector< const RamNode * > getChildNodes () const override
Obtain list of all embedded child nodes.
const RamRelation & getFirstRelation () const
Get first relation.
const RamRelation & getSecondRelation () const
Get second relation.
RamBinRelationStatement (std::unique_ptr< RamRelationReference > f, std::unique_ptr< RamRelationReference > s)
Public Member Functions inherited from souffle::RamNode
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
virtual void rewrite (const RamNode *oldNode, std::unique_ptr< RamNode > newNode)
Rewrite a child node.
virtual ~RamNode ()=default
Protected Member Functions
void print (std::ostream &os, int tabpos) const override
Pretty print with indentation.
Protected Member Functions inherited from souffle::RamBinRelationStatement
bool equal (const RamNode &node) const override
Equality check for two RAM nodes.
Protected Member Functions inherited from souffle::RamStatement
void print (std::ostream &os) const override
Print RAM node.
Additional Inherited Members
Static Protected Member Functions inherited from souffle::RamStatement
static void print (const RamStatement *statement, std::ostream &os, int tabpos)
Pretty print jump-bed.
Protected Attributes inherited from souffle::RamBinRelationStatement
std::unique_ptr< RamRelationReference > first
first argument of binary statement
std::unique_ptr< RamRelationReference > second
second argument of binary statement
Detailed Description
Swap operation with respect to two relations.
Swaps the contents of the two relations
For example:
SWAP(A, B)
Definition at line 273 of file Statement.h.
Constructor & Destructor Documentation
RamSwap()
souffle::RamSwap::RamSwap (std::unique_ptr< RamRelationReference > f, std::unique_ptr< RamRelationReference > s) inline
Definition at line 275 of file Statement.h.
             : RamBinRelationStatement(std::move(f), std::move(s)) {}
Member Function Documentation
clone()
RamSwap* souffle::RamSwap::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::RamStatement.
Definition at line 278 of file Statement.h.
References souffle::clone().
Referenced by souffle::test::TEST().
{
         return new RamSwap(souffle::clone(first), souffle::clone(second));
     }
print()
void souffle::RamSwap::print (std::ostream & os, int tabpos) const inline override protected virtual
Pretty print with indentation.
Implements souffle::RamStatement.
Definition at line 283 of file Statement.h.
References souffle::times().
{
         os << times(" ", tabpos);
         os << "SWAP (" << getFirstRelation().getName() << ", " << getSecondRelation().getName() << ")";
         os << std::endl;
     }
The documentation for this class was generated from the following file:
ram/Statement.h