souffle: souffle::profile::ProgramRun Class Reference
souffle::profile::ProgramRun Class Reference
#include <ProgramRun.h>
Public Member Functions
std::string formatNum (int precision, long number) const
std::vector< std::vector< std::string > > formatTable (Table &table, int precision) const
std::string formatTime (std::chrono::microseconds runtime) const
std::chrono::microseconds getEndtime () const
const Relation * getRelation (const std::string &name) const
const std::unordered_map< std::string, std::shared_ptr< Relation > > & getRelationMap () const
std::set< std::shared_ptr< Relation > > getRelationsAtTime (std::chrono::microseconds start, std::chrono::microseconds end) const
std::string getRuntime () const
std::chrono::microseconds getStarttime () const
std::chrono::microseconds getTotalCopyTime () const
std::chrono::microseconds getTotalLoadtime () const
size_t getTotalRecursiveSize () const
std::chrono::microseconds getTotalSavetime () const
size_t getTotalSize () const
std::chrono::microseconds getTotalTime () const
ProgramRun ()
void setEndtime (std::chrono::microseconds time)
void setRelationMap (std::unordered_map< std::string, std::shared_ptr< Relation >> &relationMap)
void setStarttime (std::chrono::microseconds time)
std::string toString ()
Private Attributes
std::chrono::microseconds endTime {0}
std::unordered_map< std::string, std::shared_ptr< Relation > > relationMap
std::chrono::microseconds startTime {0}
Detailed Description
Definition at line 29 of file ProgramRun.h.
Constructor & Destructor Documentation
ProgramRun()
souffle::profile::ProgramRun::ProgramRun () inline
Definition at line 36 of file ProgramRun.h.
 : relationMap() {}
Member Function Documentation
formatNum()
std::string souffle::profile::ProgramRun::formatNum (int precision, long number) const inline
Definition at line 148 of file ProgramRun.h.
References souffle::profile::Tools::formatNum().
{
         return Tools::formatNum(precision, number);
     }
formatTable()
std::vector<std::vector<std::string> > souffle::profile::ProgramRun::formatTable (Table & table, int precision) const inline
Definition at line 152 of file ProgramRun.h.
References souffle::profile::Tools::formatTable().
{
         return Tools::formatTable(table, precision);
     }
formatTime()
std::string souffle::profile::ProgramRun::formatTime (std::chrono::microseconds runtime) const inline
Definition at line 144 of file ProgramRun.h.
References souffle::profile::Tools::formatTime().
Referenced by getRuntime().
{
         return Tools::formatTime(runtime);
     }
getEndtime()
std::chrono::microseconds souffle::profile::ProgramRun::getEndtime () const inline
Definition at line 74 of file ProgramRun.h.
References endTime.
{
         return endTime;
     }
getRelation()
const Relation* souffle::profile::ProgramRun::getRelation (const std::string & name) const inline
Definition at line 126 of file ProgramRun.h.
{
         if (relationMap.find(name) != relationMap.end()) {
             return &(*relationMap.at(name));
         }
         return nullptr;
     }
getRelationMap()
const std::unordered_map<std::string, std::shared_ptr<Relation> >& souffle::profile::ProgramRun::getRelationMap () const inline
Definition at line 59 of file ProgramRun.h.
References relationMap.
{
         return relationMap;
     }
getRelationsAtTime()
std::set<std::shared_ptr<Relation> > souffle::profile::ProgramRun::getRelationsAtTime (std::chrono::microseconds start, std::chrono::microseconds end) const inline
Definition at line 133 of file ProgramRun.h.
{
         std::set<std::shared_ptr<Relation>> result;
         for (auto& cur : relationMap) {
             if (cur.second->getStarttime() <= end && cur.second->getEndtime() >= start) {
                 result.insert(cur.second);
             }
         }
         return result;
     }
getRuntime()
std::string souffle::profile::ProgramRun::getRuntime () const inline
Definition at line 63 of file ProgramRun.h.
References endTime, formatTime(), and startTime.
Referenced by toString().
{
         if (startTime == endTime) {
             return "--";
         }
         return formatTime(endTime - startTime);
     }
getStarttime()
std::chrono::microseconds souffle::profile::ProgramRun::getStarttime () const inline
Definition at line 70 of file ProgramRun.h.
References startTime.
{
         return startTime;
     }
getTotalCopyTime()
std::chrono::microseconds souffle::profile::ProgramRun::getTotalCopyTime () const inline
Definition at line 110 of file ProgramRun.h.
{
         std::chrono::microseconds result{0};
         for (auto& item : relationMap) {
             result += item.second->getCopyTime();
         }
         return result;
     }
getTotalLoadtime()
std::chrono::microseconds souffle::profile::ProgramRun::getTotalLoadtime () const inline
Definition at line 78 of file ProgramRun.h.
{
         std::chrono::microseconds result{0};
         for (auto& item : relationMap) {
             result += item.second->getLoadtime();
         }
         return result;
     }
getTotalRecursiveSize()
size_t souffle::profile::ProgramRun::getTotalRecursiveSize () const inline
Definition at line 102 of file ProgramRun.h.
{
         size_t result = 0;
         for (auto& item : relationMap) {
             result += item.second->getTotalRecursiveRuleSize();
         }
         return result;
     }
getTotalSavetime()
std::chrono::microseconds souffle::profile::ProgramRun::getTotalSavetime () const inline
Definition at line 86 of file ProgramRun.h.
{
         std::chrono::microseconds result{0};
         for (auto& item : relationMap) {
             result += item.second->getSavetime();
         }
         return result;
     }
getTotalSize()
size_t souffle::profile::ProgramRun::getTotalSize () const inline
Definition at line 94 of file ProgramRun.h.
{
         size_t result = 0;
         for (auto& item : relationMap) {
             result += item.second->size();
         }
         return result;
     }
getTotalTime()
std::chrono::microseconds souffle::profile::ProgramRun::getTotalTime () const inline
Definition at line 118 of file ProgramRun.h.
{
         std::chrono::microseconds result{0};
         for (auto& item : relationMap) {
             result += item.second->getRecTime();
         }
         return result;
     }
setEndtime()
void souffle::profile::ProgramRun::setEndtime (std::chrono::microseconds time) inline
Definition at line 42 of file ProgramRun.h.
References endTime, and souffle::test::time().
{
         endTime = time;
     }
setRelationMap()
void souffle::profile::ProgramRun::setRelationMap (std::unordered_map< std::string, std::shared_ptr< Relation >> & relationMap) inline
Definition at line 46 of file ProgramRun.h.
References relationMap.
{
         this->relationMap = relationMap;
     }
setStarttime()
void souffle::profile::ProgramRun::setStarttime (std::chrono::microseconds time) inline
Definition at line 38 of file ProgramRun.h.
References startTime, and souffle::test::time().
{
         startTime = time;
     }
toString()
std::string souffle::profile::ProgramRun::toString () inline
Definition at line 50 of file ProgramRun.h.
References getRuntime(), and souffle::output.
{
         std::ostringstream output;
         output << "ProgramRun:" << getRuntime() << "\nRelations:\n";
         for (auto& r : relationMap) {
             output << r.second->toString() << "\n";
         }
         return output.str();
     }
Field Documentation
endTime
std::chrono::microseconds souffle::profile::ProgramRun::endTime {0} private
Definition at line 33 of file ProgramRun.h.
Referenced by getEndtime(), getRuntime(), and setEndtime().
relationMap
std::unordered_map<std::string, std::shared_ptr<Relation> > souffle::profile::ProgramRun::relationMap private
Definition at line 31 of file ProgramRun.h.
Referenced by getRelationMap(), and setRelationMap().
startTime
std::chrono::microseconds souffle::profile::ProgramRun::startTime {0} private
Definition at line 32 of file ProgramRun.h.
Referenced by getRuntime(), getStarttime(), and setStarttime().
The documentation for this class was generated from the following file:
profile/ProgramRun.h