souffle: souffle::Logger Class Reference
souffle::Logger Class Reference
The class utilized to times for the souffle profiling tool.
#include <Logger.h>
Public Member Functions
Logger (std::string label, size_t iteration)
Logger (std::string label, size_t iteration, std::function< size_t()> size)
~Logger ()
Private Attributes
size_t iteration
std::string label
size_t preSize
std::function< size_t()> size
time_point start
size_t startMaxRSS
Detailed Description
The class utilized to times for the souffle profiling tool.
This class is utilized by both – the interpreted and compiled version – to conduct the corresponding measurements.
To far, only execution times are logged. More events, e.g. the number of processed tuples may be added in the future.
Definition at line 38 of file Logger.h.
Constructor & Destructor Documentation
Logger() [1/2]
souffle::Logger::Logger (std::string label, size_t iteration) inline
Definition at line 40 of file Logger.h.
 : Logger(label, iteration, []() { return 0; }) {}
Logger() [2/2]
souffle::Logger::Logger (std::string label, size_t iteration, std::function< size_t()> size) inline
Definition at line 42 of file Logger.h.
References souffle::ProfileEventSingleton::instance(), souffle::ProfileEventSingleton::resetTimerInterval(), and startMaxRSS.
             : label(std::move(label)), start(now()), iteration(iteration), size(size), preSize(size()) {
         struct rusage ru {};
         getrusage(RUSAGE_SELF, &ru);
         startMaxRSS = ru.ru_maxrss;
         // Assume that if we are logging the progress of an event then we care about usage during that time.
         ProfileEventSingleton::instance().resetTimerInterval();
     }
~Logger()
souffle::Logger::~Logger () inline
Definition at line 51 of file Logger.h.
References souffle::ProfileEventSingleton::instance(), souffle::ProfileEventSingleton::makeTimingEvent(), souffle::now(), preSize, size, start, and startMaxRSS.
               {
         struct rusage ru {};
         getrusage(RUSAGE_SELF, &ru);
         size_t endMaxRSS = ru.ru_maxrss;
         ProfileEventSingleton::instance().makeTimingEvent(
                 label, start, now(), startMaxRSS, endMaxRSS, size() - preSize, iteration);
     }
Field Documentation
iteration
size_t souffle::Logger::iteration private
Definition at line 63 of file Logger.h.
label
std::string souffle::Logger::label private
Definition at line 60 of file Logger.h.
preSize
size_t souffle::Logger::preSize private
Definition at line 65 of file Logger.h.
Referenced by ~Logger().
size
std::function<size_t()> souffle::Logger::size private
Definition at line 64 of file Logger.h.
Referenced by ~Logger().
start
time_point souffle::Logger::start private
Definition at line 61 of file Logger.h.
Referenced by ~Logger().
startMaxRSS
size_t souffle::Logger::startMaxRSS private
Definition at line 62 of file Logger.h.
Referenced by Logger(), and ~Logger().
The documentation for this class was generated from the following file:
Logger.h