souffle: souffle::AstBinaryConstraint Class Reference
souffle::AstBinaryConstraint Class Reference
Subclass of Constraint that represents a binary constraint e.g., x = y.
#include <BinaryConstraint.h>
Public Member Functions
void apply (const AstNodeMapper &map) override
Apply the mapper to all child nodes.
AstBinaryConstraint (BinaryConstraintOp o, Own< AstArgument > ls, Own< AstArgument > rs, SrcLocation loc={})
AstBinaryConstraint * clone () const override
Create a clone (i.e.
std::vector< const AstNode * > getChildNodes () const override
Obtain a list of all embedded AST child nodes.
AstArgument * getLHS () const
get LHS argument
BinaryConstraintOp getOperator () const
get binary operator
AstArgument * getRHS () const
get RHS argument
void setOperator (BinaryConstraintOp op)
set binary operator
Public Member Functions inherited from souffle::AstNode
AstNode (SrcLocation loc={})
std::string extloc () const
Return source location of the syntactic element.
const SrcLocation & getSrcLoc () const
Return source location of the AstNode.
bool operator!= (const AstNode &other) const
Inequality check for two AST nodes.
bool operator== (const AstNode &other) const
Equivalence check for two AST nodes.
void setSrcLoc (SrcLocation l)
Set source location for the AstNode.
virtual ~AstNode ()=default
Protected Member Functions
bool equal (const AstNode &node) const override
Abstract equality check for two AST nodes.
void print (std::ostream &os) const override
Output to a given output stream.
Protected Attributes
Own< AstArgument > lhs
left-hand side of binary constraint
BinaryConstraintOp operation
constraint operator
Own< AstArgument > rhs
right-hand side of binary constraint
Detailed Description
Subclass of Constraint that represents a binary constraint e.g., x = y.
Definition at line 41 of file BinaryConstraint.h.
Constructor & Destructor Documentation
AstBinaryConstraint()
souffle::AstBinaryConstraint::AstBinaryConstraint (BinaryConstraintOp o, Own< AstArgument > ls, Own< AstArgument > rs, SrcLocation loc = {}) inline
Definition at line 43 of file BinaryConstraint.h.
References lhs, operation, and rhs.
Referenced by clone().
                                                                                                           {})
             : AstConstraint(std::move(loc)), operation(o), lhs(std::move(ls)), rhs(std::move(rs)) {}
Member Function Documentation
apply()
void souffle::AstBinaryConstraint::apply (const AstNodeMapper &) inline override virtual
Apply the mapper to all child nodes.
Reimplemented from souffle::AstNode.
Definition at line 70 of file BinaryConstraint.h.
References lhs, souffle::map(), and rhs.
{
         lhs = map(std::move(lhs));
         rhs = map(std::move(rhs));
     }
clone()
AstBinaryConstraint* souffle::AstBinaryConstraint::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::AstConstraint.
Definition at line 66 of file BinaryConstraint.h.
References AstBinaryConstraint(), souffle::clone(), souffle::AstNode::getSrcLoc(), lhs, operation, and rhs.
{
         return new AstBinaryConstraint(operation, souffle::clone(lhs), souffle::clone(rhs), getSrcLoc());
     }
equal()
bool souffle::AstBinaryConstraint::equal (const AstNode &) const inline override protected virtual
Abstract equality check for two AST nodes.
Reimplemented from souffle::AstNode.
Definition at line 84 of file BinaryConstraint.h.
References souffle::equal_ptr(), lhs, operation, and rhs.
{
         assert(nullptr != dynamic_cast<const AstBinaryConstraint*>(&node));
         const auto& other = static_cast<const AstBinaryConstraint&>(node);
         return operation == other.operation && equal_ptr(lhs, other.lhs) && equal_ptr(rhs, other.rhs);
     }
getChildNodes()
std::vector<const AstNode*> souffle::AstBinaryConstraint::getChildNodes () const inline override virtual
Obtain a list of all embedded AST child nodes.
Reimplemented from souffle::AstNode.
Definition at line 75 of file BinaryConstraint.h.
References lhs, and rhs.
{
         return {lhs.get(), rhs.get()};
     }
getLHS()
AstArgument* souffle::AstBinaryConstraint::getLHS () const inline
get LHS argument
Definition at line 47 of file BinaryConstraint.h.
References lhs.
Referenced by souffle::FoldAnonymousRecords::expandRecordBinaryConstraint(), souffle::getGroundedTerms(), souffle::FoldAnonymousRecords::isValidRecordConstraint(), souffle::ResolveAliasesTransformer::resolveAliases(), souffle::AstToRamTranslator::translateConstraint(), souffle::TypeChecker::visitBinaryConstraint(), and souffle::TypeConstraintsAnalysis::visitBinaryConstraint().
{
         return lhs.get();
     }
getOperator()
BinaryConstraintOp souffle::AstBinaryConstraint::getOperator () const inline
get binary operator
Definition at line 57 of file BinaryConstraint.h.
References operation.
Referenced by souffle::FoldAnonymousRecords::expandRecordBinaryConstraint(), souffle::getGroundedTerms(), souffle::ResolveAliasesTransformer::resolveAliases(), souffle::FoldAnonymousRecords::transformClause(), souffle::AstToRamTranslator::translateConstraint(), and souffle::TypeChecker::visitBinaryConstraint().
{
         return operation;
     }
getRHS()
AstArgument* souffle::AstBinaryConstraint::getRHS () const inline
get RHS argument
Definition at line 52 of file BinaryConstraint.h.
References rhs.
Referenced by souffle::FoldAnonymousRecords::expandRecordBinaryConstraint(), souffle::getGroundedTerms(), souffle::ResolveAliasesTransformer::resolveAliases(), souffle::AstToRamTranslator::translateConstraint(), souffle::TypeChecker::visitBinaryConstraint(), and souffle::TypeConstraintsAnalysis::visitBinaryConstraint().
{
         return rhs.get();
     }
print()
void souffle::AstBinaryConstraint::print (std::ostream & os) const inline override protected virtual
Output to a given output stream.
Implements souffle::AstNode.
Definition at line 80 of file BinaryConstraint.h.
References lhs, operation, and rhs.
{
         os << *lhs << " " << operation << " " << *rhs;
     }
setOperator()
void souffle::AstBinaryConstraint::setOperator (BinaryConstraintOp op) inline
set binary operator
Definition at line 62 of file BinaryConstraint.h.
References operation.
{
         operation = op;
     }
Field Documentation
lhs
Own<AstArgument> souffle::AstBinaryConstraint::lhs protected
left-hand side of binary constraint
Definition at line 94 of file BinaryConstraint.h.
Referenced by apply(), AstBinaryConstraint(), clone(), equal(), getChildNodes(), getLHS(), and print().
operation
BinaryConstraintOp souffle::AstBinaryConstraint::operation protected
constraint operator
Definition at line 91 of file BinaryConstraint.h.
Referenced by AstBinaryConstraint(), clone(), equal(), getOperator(), print(), and setOperator().
rhs
Own<AstArgument> souffle::AstBinaryConstraint::rhs protected
right-hand side of binary constraint
Definition at line 97 of file BinaryConstraint.h.
Referenced by apply(), AstBinaryConstraint(), clone(), equal(), getChildNodes(), getRHS(), and print().
The documentation for this class was generated from the following file:
ast/BinaryConstraint.h