souffle: souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::iterator Class Reference
souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::iterator Class Reference
The iterator type to be utilized for scanning through btree instances.
#include <BTree.h>
Public Member Functions
iterator ()
iterator (node const *cur, field_index_type pos)
iterator (const iterator &other)
bool operator!= (const iterator &other) const
const Key & operator* () const
iterator & operator++ ()
iterator & operator= (const iterator &other)
bool operator== (const iterator &other) const
void print (std::ostream &out=std::cout) const
Private Attributes
node const * cur
field_index_type pos = 0
Detailed Description
template<typename Key, typename Comparator, typename Allocator, unsigned blockSize, typename SearchStrategy, bool isSet, typename WeakComparator = Comparator, typename Updater = detail::updater<Key>>
class souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::iterator
The iterator type to be utilized for scanning through btree instances.
Definition at line 1096 of file BTree.h.
Constructor & Destructor Documentation
iterator() [1/3]
template<typename Key, typename Comparator, typename Allocator, unsigned blockSize, typename SearchStrategy, bool isSet, typename WeakComparator = Comparator, typename Updater = detail::updater<Key>> souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::iterator::iterator () inline
Definition at line 1105 of file BTree.h.
 : cur(nullptr) {}
iterator() [2/3]
template<typename Key, typename Comparator, typename Allocator, unsigned blockSize, typename SearchStrategy, bool isSet, typename WeakComparator = Comparator, typename Updater = detail::updater<Key>> souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::iterator::iterator (node const * cur, field_index_type pos) inline
Definition at line 1108 of file BTree.h.
 : cur(cur), pos(pos) {}
iterator() [3/3]
template<typename Key, typename Comparator, typename Allocator, unsigned blockSize, typename SearchStrategy, bool isSet, typename WeakComparator = Comparator, typename Updater = detail::updater<Key>> souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::iterator::iterator (const iterator & other) inline
Definition at line 1111 of file BTree.h.
 : cur(other.cur), pos(other.pos) {}
Member Function Documentation
operator!=()
template<typename Key, typename Comparator, typename Allocator, unsigned blockSize, typename SearchStrategy, bool isSet, typename WeakComparator = Comparator, typename Updater = detail::updater<Key>> bool souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::iterator::operator!= (const iterator & other) const inline
Definition at line 1126 of file BTree.h.
{
             return !(*this == other);
         }
operator*()
template<typename Key, typename Comparator, typename Allocator, unsigned blockSize, typename SearchStrategy, bool isSet, typename WeakComparator = Comparator, typename Updater = detail::updater<Key>> const Key& souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::iterator::operator* () const inline
Definition at line 1131 of file BTree.h.
References souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::node::keys.
{
             return cur->keys[pos];
         }
operator++()
template<typename Key, typename Comparator, typename Allocator, unsigned blockSize, typename SearchStrategy, bool isSet, typename WeakComparator = Comparator, typename Updater = detail::updater<Key>> iterator& souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::iterator::operator++ () inline
Definition at line 1136 of file BTree.h.
References souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::node::getChildren(), souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::base::getNumElements(), souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::base::getParent(), souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::base::getPositionInParent(), souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::node::isEmpty(), souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::base::isInner(), and souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::base::isLeaf().
{
             // the quick mode -- if in a leaf and there are elements left
             if (cur->isLeaf() && ++pos < cur->getNumElements()) {
                 return *this;
             }
             // otherwise it is a bit more tricky
             // A) currently in an inner node => go to the left-most child
             if (cur->isInner()) {
                 cur = cur->getChildren()[pos + 1];
                 while (!cur->isLeaf()) {
                     cur = cur->getChildren()[0];
                 }
                 pos = 0;
                 // nodes may be empty due to biased insertion
                 if (!cur->isEmpty()) {
                     return *this;
                 }
             }
             // B) we are at the right-most element of a leaf => go to next inner node
             assert(cur->isLeaf());
             assert(pos == cur->getNumElements());
             while (cur != nullptr && pos == cur->getNumElements()) {
                 pos = cur->getPositionInParent();
                 cur = cur->getParent();
             }
             return *this;
         }
operator=()
template<typename Key, typename Comparator, typename Allocator, unsigned blockSize, typename SearchStrategy, bool isSet, typename WeakComparator = Comparator, typename Updater = detail::updater<Key>> iterator& souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::iterator::operator= (const iterator & other) inline
Definition at line 1114 of file BTree.h.
References souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::iterator::cur, and souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::iterator::pos.
{
             cur = other.cur;
             pos = other.pos;
             return *this;
         }
operator==()
template<typename Key, typename Comparator, typename Allocator, unsigned blockSize, typename SearchStrategy, bool isSet, typename WeakComparator = Comparator, typename Updater = detail::updater<Key>> bool souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::iterator::operator== (const iterator & other) const inline
Definition at line 1121 of file BTree.h.
References souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::iterator::cur, and souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::iterator::pos.
{
             return cur == other.cur && pos == other.pos;
         }
print()
template<typename Key, typename Comparator, typename Allocator, unsigned blockSize, typename SearchStrategy, bool isSet, typename WeakComparator = Comparator, typename Updater = detail::updater<Key>> void souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::iterator::print (std::ostream & out = std::cout) const inline
Definition at line 1170 of file BTree.h.
{
             out << cur << "[" << (int)pos << "]";
         }
Field Documentation
cur
template<typename Key, typename Comparator, typename Allocator, unsigned blockSize, typename SearchStrategy, bool isSet, typename WeakComparator = Comparator, typename Updater = detail::updater<Key>> node const* souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::iterator::cur private
Definition at line 1098 of file BTree.h.
Referenced by souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::iterator::operator=(), and souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::iterator::operator==().
pos
template<typename Key, typename Comparator, typename Allocator, unsigned blockSize, typename SearchStrategy, bool isSet, typename WeakComparator = Comparator, typename Updater = detail::updater<Key>> field_index_type souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::iterator::pos = 0 private
Definition at line 1101 of file BTree.h.
Referenced by souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::iterator::operator=(), and souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::iterator::operator==().
The documentation for this class was generated from the following file:
BTree.h