souffle: SWIGSouffleProgram Class Reference
SWIGSouffleProgram Class Reference
Abstract base class for generated Datalog programs.
#include <SwigInterface.h>
Public Member Functions
void dumpInputs (std::ostream &out=std::cout)
Calls the corresponding method souffle::SouffleProgram::dumpInputs in SouffleInterface.h.
void dumpOutputs (std::ostream &out=std::cout)
Calls the corresponding method souffle::SouffleProgram::dumpOutputs in SouffleInterface.h.
void loadAll (const std::string &inputDirectory)
Calls the corresponding method souffle::SouffleProgram::loadAll in SouffleInterface.h.
void printAll (const std::string &outputDirectory)
Calls the corresponding method souffle::SouffleProgram::printAll in SouffleInterface.h.
void run ()
Calls the corresponding method souffle::SouffleProgram::run in SouffleInterface.h.
void runAll (const std::string &inputDirectory, const std::string &outputDirectory)
Calls the corresponding method souffle::SouffleProgram::runAll in SouffleInterface.h.
SWIGSouffleProgram (souffle::SouffleProgram *program)
virtual ~SWIGSouffleProgram ()
Private Attributes
souffle::SouffleProgram * program
pointer to SouffleProgram to invoke functions from SouffleInterface.h
Detailed Description
Abstract base class for generated Datalog programs.
Definition at line 26 of file SwigInterface.h.
Constructor & Destructor Documentation
SWIGSouffleProgram()
SWIGSouffleProgram::SWIGSouffleProgram (souffle::SouffleProgram * program) inline
Definition at line 33 of file SwigInterface.h.
Referenced by newInstance().
 : program(program) {}
~SWIGSouffleProgram()
virtual SWIGSouffleProgram::~SWIGSouffleProgram () inline virtual
Definition at line 35 of file SwigInterface.h.
References program.
{
         delete program;
     }
Member Function Documentation
dumpInputs()
void SWIGSouffleProgram::dumpInputs (std::ostream & out = std::cout) inline
Calls the corresponding method souffle::SouffleProgram::dumpInputs in SouffleInterface.h.
Definition at line 70 of file SwigInterface.h.
References souffle::SouffleProgram::dumpInputs().
{
         program->dumpInputs(out);
     }
dumpOutputs()
void SWIGSouffleProgram::dumpOutputs (std::ostream & out = std::cout) inline
Calls the corresponding method souffle::SouffleProgram::dumpOutputs in SouffleInterface.h.
Definition at line 77 of file SwigInterface.h.
References souffle::SouffleProgram::dumpOutputs().
{
         program->dumpOutputs(out);
     }
loadAll()
void SWIGSouffleProgram::loadAll (const std::string & inputDirectory) inline
Calls the corresponding method souffle::SouffleProgram::loadAll in SouffleInterface.h.
Definition at line 56 of file SwigInterface.h.
References souffle::SouffleProgram::loadAll().
{
         program->loadAll(inputDirectory);
     }
printAll()
void SWIGSouffleProgram::printAll (const std::string & outputDirectory) inline
Calls the corresponding method souffle::SouffleProgram::printAll in SouffleInterface.h.
Definition at line 63 of file SwigInterface.h.
References souffle::SouffleProgram::printAll().
{
         program->printAll(outputDirectory);
     }
run()
void SWIGSouffleProgram::run () inline
Calls the corresponding method souffle::SouffleProgram::run in SouffleInterface.h.
Definition at line 42 of file SwigInterface.h.
References souffle::SouffleProgram::run().
                {
         program->run();
     }
runAll()
void SWIGSouffleProgram::runAll (const std::string & inputDirectory, const std::string & outputDirectory) inline
Calls the corresponding method souffle::SouffleProgram::runAll in SouffleInterface.h.
Definition at line 49 of file SwigInterface.h.
References souffle::SouffleProgram::runAll().
{
         program->runAll(inputDirectory, outputDirectory);
     }
Field Documentation
program
souffle::SouffleProgram* SWIGSouffleProgram::program private
pointer to SouffleProgram to invoke functions from SouffleInterface.h
Definition at line 30 of file SwigInterface.h.
Referenced by ~SWIGSouffleProgram().
The documentation for this class was generated from the following file:
swig/SwigInterface.h