souffle: souffle::AstRecordInit Class Reference
souffle::AstRecordInit Class Reference
Record.
#include <RecordInit.h>
Public Member Functions
AstRecordInit (VecOwn< AstArgument > operands={}, SrcLocation loc={})
AstRecordInit * clone () const override
Create clone.
Public Member Functions inherited from souffle::AstTerm
void addArgument (Own< AstArgument > arg)
add argument to argument list
void apply (const AstNodeMapper &map) override
Apply the mapper to all child nodes.
std::vector< AstArgument * > getArguments () const
get arguments
std::vector< const AstNode * > getChildNodes () const override
Obtain a list of all embedded AST child nodes.
Public Member Functions inherited from souffle::AstNode
AstNode (SrcLocation loc={})
std::string extloc () const
Return source location of the syntactic element.
const SrcLocation & getSrcLoc () const
Return source location of the AstNode.
bool operator!= (const AstNode &other) const
Inequality check for two AST nodes.
bool operator== (const AstNode &other) const
Equivalence check for two AST nodes.
void setSrcLoc (SrcLocation l)
Set source location for the AstNode.
virtual ~AstNode ()=default
Protected Member Functions
void print (std::ostream &os) const override
Output to a given output stream.
Protected Member Functions inherited from souffle::AstTerm
template<typename... Operands>
AstTerm (Operands &&... operands)
template<typename... Operands>
AstTerm (SrcLocation loc, Operands &&... operands)
AstTerm (VecOwn< AstArgument > operands, SrcLocation loc={})
bool equal (const AstNode &node) const override
Abstract equality check for two AST nodes.
Additional Inherited Members
Protected Attributes inherited from souffle::AstTerm
VecOwn< AstArgument > args
Arguments.
Detailed Description
Record.
Definition at line 33 of file RecordInit.h.
Constructor & Destructor Documentation
AstRecordInit()
souffle::AstRecordInit::AstRecordInit (VecOwn< AstArgument > operands = {}, SrcLocation loc = {}) inline
Definition at line 35 of file RecordInit.h.
References souffle::AstTerm::AstTerm().
Referenced by clone().
                                                  {}, SrcLocation loc = {})
             : AstTerm(std::move(operands), std::move(loc)) {}
Member Function Documentation
clone()
AstRecordInit* souffle::AstRecordInit::clone () const inline override virtual
Create clone.
Implements souffle::AstArgument.
Definition at line 38 of file RecordInit.h.
References souffle::AstTerm::args, AstRecordInit(), souffle::clone(), and souffle::AstNode::getSrcLoc().
{
         return new AstRecordInit(souffle::clone(args), getSrcLoc());
     }
print()
void souffle::AstRecordInit::print (std::ostream & os) const inline override protected virtual
Output to a given output stream.
Implements souffle::AstNode.
Definition at line 43 of file RecordInit.h.
References souffle::AstTerm::args, and souffle::join().
{
         os << "[" << join(args) << "]";
     }
The documentation for this class was generated from the following file:
ast/RecordInit.h