souffle: json11::JsonValue Class Reference
json11::JsonValue Class Reference abstract
#include <json11.h>
Protected Member Functions
virtual const Json::array & array_items () const
virtual bool bool_value () const
virtual void dump (std::string &out) const =0
virtual bool equals (const JsonValue *other) const =0
virtual int int_value () const
virtual bool less (const JsonValue *other) const =0
virtual long long long_value () const
virtual double number_value () const
virtual const Json::object & object_items () const
virtual const Json & operator[] (size_t i) const
virtual const Json & operator[] (const std::string &key) const
virtual const std::string & string_value () const
virtual Json::Type type () const =0
virtual ~JsonValue ()=default
Friends
class Json
class JsonDouble
class JsonInt
Detailed Description
Definition at line 244 of file json11.h.
Constructor & Destructor Documentation
~JsonValue()
virtual json11::JsonValue::~JsonValue () protected virtual default
Member Function Documentation
array_items()
const std::vector< Json > & json11::JsonValue::array_items () const inline protected virtual
Reimplemented in json11::JsonArray.
Definition at line 581 of file json11.h.
References json11::Statics::empty_vector, and json11::statics().
{
     return statics().empty_vector;
 }
bool_value()
bool json11::JsonValue::bool_value () const inline protected virtual
Reimplemented in json11::JsonBoolean.
Definition at line 575 of file json11.h.
{
     return false;
 }
dump()
virtual void json11::JsonValue::dump (std::string & out) const protected pure virtual
Implemented in json11::Value< tag, T >, json11::Value< Json::OBJECT, Json::object >, json11::Value< Json::ARRAY, Json::array >, json11::Value< Json::NUL, NullStruct >, json11::Value< Json::NUMBER, long long >, json11::Value< Json::NUMBER, double >, json11::Value< Json::BOOL, bool >, and json11::Value< Json::STRING, std::string >.
equals()
virtual bool json11::JsonValue::equals (const JsonValue * other) const protected pure virtual
Implemented in json11::JsonInt, json11::JsonDouble, json11::Value< tag, T >, json11::Value< Json::OBJECT, Json::object >, json11::Value< Json::ARRAY, Json::array >, json11::Value< Json::NUL, NullStruct >, json11::Value< Json::NUMBER, long long >, json11::Value< Json::NUMBER, double >, json11::Value< Json::BOOL, bool >, and json11::Value< Json::STRING, std::string >.
int_value()
int json11::JsonValue::int_value () const inline protected virtual
Reimplemented in json11::JsonInt, and json11::JsonDouble.
Definition at line 569 of file json11.h.
{
     return 0;
 }
less()
virtual bool json11::JsonValue::less (const JsonValue * other) const protected pure virtual
Implemented in json11::JsonInt, json11::JsonDouble, json11::Value< tag, T >, json11::Value< Json::OBJECT, Json::object >, json11::Value< Json::ARRAY, Json::array >, json11::Value< Json::NUL, NullStruct >, json11::Value< Json::NUMBER, long long >, json11::Value< Json::NUMBER, double >, json11::Value< Json::BOOL, bool >, and json11::Value< Json::STRING, std::string >.
long_value()
long long json11::JsonValue::long_value () const inline protected virtual
Reimplemented in json11::JsonInt, and json11::JsonDouble.
Definition at line 572 of file json11.h.
{
     return 0;
 }
number_value()
double json11::JsonValue::number_value () const inline protected virtual
Reimplemented in json11::JsonInt, and json11::JsonDouble.
Definition at line 566 of file json11.h.
Referenced by json11::JsonDouble::equals(), json11::JsonInt::equals(), json11::JsonDouble::less(), and json11::JsonInt::less().
{
     return 0;
 }
object_items()
const std::map< std::string, Json > & json11::JsonValue::object_items () const inline protected virtual
Reimplemented in json11::JsonObject.
Definition at line 584 of file json11.h.
References json11::Statics::empty_map, and json11::statics().
{
     return statics().empty_map;
 }
operator[]() [1/2]
const Json & json11::JsonValue::operator[] (size_t i) const inline protected virtual
Reimplemented in json11::JsonArray.
Definition at line 587 of file json11.h.
References json11::static_null().
{
     return static_null();
 }
operator[]() [2/2]
const Json & json11::JsonValue::operator[] (const std::string & key) const inline protected virtual
Reimplemented in json11::JsonObject.
Definition at line 590 of file json11.h.
References json11::static_null().
{
     return static_null();
 }
string_value()
const std::string & json11::JsonValue::string_value () const inline protected virtual
Reimplemented in json11::JsonString.
Definition at line 578 of file json11.h.
References json11::Statics::empty_string, and json11::statics().
{
     return statics().empty_string;
 }
type()
virtual Json::Type json11::JsonValue::type () const protected pure virtual
Implemented in json11::Value< tag, T >, json11::Value< Json::OBJECT, Json::object >, json11::Value< Json::ARRAY, Json::array >, json11::Value< Json::NUL, NullStruct >, json11::Value< Json::NUMBER, long long >, json11::Value< Json::NUMBER, double >, json11::Value< Json::BOOL, bool >, and json11::Value< Json::STRING, std::string >.
Friends And Related Function Documentation
Json
friend class Json friend
Definition at line 246 of file json11.h.
JsonDouble
friend class JsonDouble friend
Definition at line 248 of file json11.h.
JsonInt
friend class JsonInt friend
Definition at line 247 of file json11.h.
The documentation for this class was generated from the following file:
json11.h