souffle: souffle::AstToRamTranslator::ClauseTranslator Class Reference
souffle::AstToRamTranslator::ClauseTranslator Class Reference
translate AST clause to RAM code
Public Member Functions
ClauseTranslator (AstToRamTranslator &translator)
std::unique_ptr< RamStatement > translateClause (const AstClause &clause, const AstClause &originalClause, const int version=0)
generate RAM code for a clause
Protected Member Functions
virtual std::unique_ptr< RamCondition > createCondition (const AstClause &originalClause)
virtual std::unique_ptr< RamOperation > createOperation (const AstClause &clause)
std::unique_ptr< RamOperation > filterByConstraints (size_t level, const std::vector< AstArgument *> &args, std::unique_ptr< RamOperation > op, bool constrainByFunctors=true)
translate RAM code for a constant value
Protected Attributes
const AuxiliaryArity * auxArityAnalysis
int level = 0
AstToRamTranslator & translator
ValueIndex valueIndex
Private Types
using arg_list = std::vector< AstArgument * >
Private Member Functions
void createValueIndex (const AstClause &clause)
index values in rule
arg_list * getArgList (const AstNode *curNode, std::map< const AstNode *, std::unique_ptr< arg_list >> &nodeArgs) const
std::unique_ptr< AstClause > getReorderedClause (const AstClause &clause, const int version) const
void indexValues (const AstNode *curNode, std::map< const AstNode *, std::unique_ptr< arg_list >> &nodeArgs, std::map< const arg_list *, int > &arg_level, RamRelationReference *relation)
Private Attributes
std::vector< const AstArgument * > generators
std::vector< const AstNode * > op_nesting
Detailed Description
translate AST clause to RAM code
Definition at line 333 of file AstToRamTranslator.h.
Member Typedef Documentation
arg_list
using souffle::AstToRamTranslator::ClauseTranslator::arg_list = std::vector<AstArgument*> private
Definition at line 335 of file AstToRamTranslator.h.
Constructor & Destructor Documentation
ClauseTranslator()
souffle::AstToRamTranslator::ClauseTranslator::ClauseTranslator (AstToRamTranslator & translator) inline
Definition at line 372 of file AstToRamTranslator.h.
                 : translator(translator), auxArityAnalysis(translator.auxArityAnalysis) {}
Member Function Documentation
createCondition()
std::unique_ptr< RamCondition > souffle::AstToRamTranslator::ClauseTranslator::createCondition (const AstClause & originalClause) protected virtual
Reimplemented in souffle::AstToRamTranslator::ProvenanceClauseTranslator.
Definition at line 557 of file AstToRamTranslator.cpp.
References souffle::AstClause::getHead().
{
     const auto head = originalClause.getHead();
     // add stopping criteria for nullary relations
     // (if it contains already the null tuple, don't re-compute)
     if (head->getArity() == 0) {
         return std::make_unique<RamEmptinessCheck>(translator.translateRelation(head));
     }
     return nullptr;
 }
createOperation()
std::unique_ptr< RamOperation > souffle::AstToRamTranslator::ClauseTranslator::createOperation (const AstClause & clause) protected virtual
Reimplemented in souffle::AstToRamTranslator::ProvenanceClauseTranslator.
Definition at line 505 of file AstToRamTranslator.cpp.
References souffle::AstClause::getHead().
{
     const auto head = clause.getHead();
     std::vector<std::unique_ptr<RamExpression>> values;
     for (AstArgument* arg : head->getArguments()) {
         values.push_back(translator.translateValue(arg, valueIndex));
     }
     std::unique_ptr<RamOperation> project =
             std::make_unique<RamProject>(translator.translateRelation(head), std::move(values));
     if (head->getArity() == 0) {
         project = std::make_unique<RamFilter>(
                 std::make_unique<RamEmptinessCheck>(translator.translateRelation(head)), std::move(project));
     }
     // build up insertion call
     return project;  // start with innermost
 }
createValueIndex()
void souffle::AstToRamTranslator::ClauseTranslator::createValueIndex (const AstClause & clause) private
index values in rule
Definition at line 445 of file AstToRamTranslator.cpp.
References souffle::any_of(), souffle::AstAtom::getArguments(), and souffle::visitDepthFirstPostOrder().
{
     for (const auto* atom : getBodyLiterals<AstAtom>(clause)) {
         // std::map<const arg_list*, int> arg_level;
         std::map<const AstNode*, std::unique_ptr<arg_list>> nodeArgs;
         std::map<const arg_list*, int> arg_level;
         nodeArgs[atom] = std::make_unique<arg_list>(atom->getArguments());
         // the atom is obtained at the current level
         // increment nesting level for the atom
         arg_level[nodeArgs[atom].get()] = level++;
         op_nesting.push_back(atom);
         indexValues(atom, nodeArgs, arg_level, translator.translateRelation(atom).get());
     }
     // add aggregation functions
     visitDepthFirstPostOrder(clause, [&](const AstArgument& arg) {
         // returns the write-location for this generator (or none if an equiv arg was already seen)
         auto addGenerator = [&]() -> std::optional<int> {
             // The by-value compare means that we're effectively doing CSE for any
             // generator args during code-gen. This is a weird place to do this.
             if (any_of(generators, [&](auto* x) { return *x == arg; })) return {};
             generators.push_back(&arg);
             int aggLoc = level++;
             valueIndex.setGeneratorLoc(arg, Location({aggLoc, 0}));
             return aggLoc;
         };
         if (auto agg = dynamic_cast<const AstAggregator*>(&arg)) {
             if (auto aggLoc = addGenerator()) {
                 // bind aggregator variables to locations
                 const AstAtom* atom = nullptr;
                 for (auto lit : agg->getBodyLiterals()) {
                     if (atom == nullptr) {
                         atom = dynamic_cast<const AstAtom*>(lit);
                     } else {
                         break;
                     }
                 }
                 if (atom != nullptr) {
                     size_t pos = 0;
                     for (auto* arg : atom->getArguments()) {
                         if (const auto* var = dynamic_cast<const AstVariable*>(arg)) {
                             valueIndex.addVarReference(
                                     *var, *aggLoc, (int)pos, translator.translateRelation(atom));
                         }
                         ++pos;
                     }
                 }
             }
         }
         auto func = dynamic_cast<const AstIntrinsicFunctor*>(&arg);
         if (func && func->getFunctionInfo()->multipleResults) {
             addGenerator();
         }
     });
 }
filterByConstraints()
std::unique_ptr< RamOperation > souffle::AstToRamTranslator::ClauseTranslator::filterByConstraints (size_t level, const std::vector< AstArgument *> & args, std::unique_ptr< RamOperation > op, bool constrainByFunctors = true) protected
translate RAM code for a constant value
Definition at line 574 of file AstToRamTranslator.cpp.
References souffle::EQ, souffle::FEQ, souffle::Float, souffle::AstNumericConstant::Float, and rhs.
{
     size_t pos = 0;
     auto mkFilter = [&](bool isFloatArg, std::unique_ptr<RamExpression> rhs) {
         return std::make_unique<RamFilter>(
                 std::make_unique<RamConstraint>(isFloatArg ? BinaryConstraintOp::FEQ : BinaryConstraintOp::EQ,
                         std::make_unique<RamTupleElement>(level, pos), std::move(rhs)),
                 std::move(op));
     };
     for (auto* a : args) {
         if (auto* c = dynamic_cast<const AstConstant*>(a)) {
             auto* const c_num = dynamic_cast<const AstNumericConstant*>(c);
             assert((!c_num || c_num->getType()) && "numeric constant wasn't bound to a type");
             op = mkFilter(c_num && *c_num->getType() == AstNumericConstant::Type::Float,
                     translator.translateConstant(*c));
         } else if (auto* func = dynamic_cast<const AstFunctor*>(a)) {
             if (constrainByFunctors) {
                 op = mkFilter(func->getReturnType() == TypeAttribute::Float,
                         translator.translateValue(func, valueIndex));
             }
         }
         ++pos;
     }
     return op;
 }
getArgList()
AstToRamTranslator::ClauseTranslator::arg_list * souffle::AstToRamTranslator::ClauseTranslator::getArgList (const AstNode * curNode, std::map< const AstNode *, std::unique_ptr< arg_list >> & nodeArgs) const private
Definition at line 398 of file AstToRamTranslator.cpp.
References souffle::fatal().
{
     if (nodeArgs.count(curNode) == 0u) {
         if (auto rec = dynamic_cast<const AstRecordInit*>(curNode)) {
             nodeArgs[curNode] = std::make_unique<arg_list>(rec->getArguments());
         } else if (auto atom = dynamic_cast<const AstAtom*>(curNode)) {
             nodeArgs[curNode] = std::make_unique<arg_list>(atom->getArguments());
         } else {
             fatal("node type doesn't have arguments!");
         }
     }
     return nodeArgs[curNode].get();
 }
getReorderedClause()
std::unique_ptr< AstClause > souffle::AstToRamTranslator::ClauseTranslator::getReorderedClause (const AstClause & clause, const int version) const private
Definition at line 365 of file AstToRamTranslator.cpp.
References souffle::AstClause::clone(), souffle::AstClause::getExecutionPlan(), souffle::AstExecutionPlan::getOrders(), i, and souffle::reorderAtoms().
{
     const auto plan = clause.getExecutionPlan();
     // check whether there is an imposed order constraint
     if (plan == nullptr) {
         return nullptr;
     }
     auto orders = plan->getOrders();
     if (orders.find(version) == orders.end()) {
         return nullptr;
     }
     // get the imposed order
     const auto& order = orders[version];
     // create a copy and fix order
     std::unique_ptr<AstClause> reorderedClause(clause.clone());
     // Change order to start at zero
     std::vector<unsigned int> newOrder(order->getOrder().size());
     std::transform(order->getOrder().begin(), order->getOrder().end(), newOrder.begin(),
             [](unsigned int i) -> unsigned int { return i - 1; });
     // re-order atoms
     reorderedClause.reset(reorderAtoms(reorderedClause.get(), newOrder));
     // clear other order and fix plan
     reorderedClause->clearExecutionPlan();
     return reorderedClause;
 }
indexValues()
void souffle::AstToRamTranslator::ClauseTranslator::indexValues (const AstNode * curNode, std::map< const AstNode *, std::unique_ptr< arg_list >> & nodeArgs, std::map< const arg_list *, int > & arg_level, RamRelationReference * relation) private
Definition at line 412 of file AstToRamTranslator.cpp.
References souffle::clone().
{
     arg_list* cur = getArgList(curNode, nodeArgs);
     for (size_t pos = 0; pos < cur->size(); ++pos) {
         // get argument
         auto& arg = (*cur)[pos];
         // check for variable references
         if (auto var = dynamic_cast<const AstVariable*>(arg)) {
             if (pos < relation->get()->getArity()) {
                 valueIndex.addVarReference(*var, arg_level[cur], pos, souffle::clone(relation));
             } else {
                 valueIndex.addVarReference(*var, arg_level[cur], pos);
             }
         }
         // check for nested records
         if (auto rec = dynamic_cast<const AstRecordInit*>(arg)) {
             // introduce new nesting level for unpack
             op_nesting.push_back(rec);
             arg_level[getArgList(rec, nodeArgs)] = level++;
             // register location of record
             valueIndex.setRecordDefinition(*rec, arg_level[cur], pos);
             // resolve nested components
             indexValues(rec, nodeArgs, arg_level, relation);
         }
     }
 }
translateClause()
std::unique_ptr< RamStatement > souffle::AstToRamTranslator::ClauseTranslator::translateClause (const AstClause & clause, const AstClause & originalClause, const int version = 0)
generate RAM code for a clause
Definition at line 605 of file AstToRamTranslator.cpp.
References souffle::Global::config(), souffle::EQ, souffle::fatal(), souffle::FRANGE, souffle::AstAtom::getArguments(), souffle::AstAtom::getArity(), souffle::AstClause::getBodyLiterals(), souffle::AstClause::getHead(), souffle::AstAtom::getQualifiedName(), souffle::AstToRamTranslator::Location::identifier, souffle::isFact(), souffle::isRamUndefValue(), souffle::isRule(), souffle::AstToRamTranslator::makeRamTupleElement(), souffle::RANGE, souffle::profile::ss, souffle::stringify(), souffle::toString(), and souffle::URANGE.
Referenced by souffle::AstToRamTranslator::makeSubproofSubroutine(), souffle::AstToRamTranslator::translateNonRecursiveRelation(), and souffle::AstToRamTranslator::translateRecursiveRelation().
{
     if (auto reorderedClause = getReorderedClause(clause, version)) {
         // translate reordered clause
         return translateClause(*reorderedClause, originalClause, version);
     }
     // get extract some details
     const AstAtom* head = clause.getHead();
     // handle facts
     if (isFact(clause)) {
         // translate arguments
         std::vector<std::unique_ptr<RamExpression>> values;
         for (auto& arg : head->getArguments()) {
             values.push_back(translator.translateValue(arg, ValueIndex()));
         }
         // create a fact statement
         return std::make_unique<RamQuery>(
                 std::make_unique<RamProject>(translator.translateRelation(head), std::move(values)));
     }
     // the rest should be rules
     assert(isRule(clause));
     createValueIndex(clause);
     // -- create RAM statement --
     std::unique_ptr<RamOperation> op = createOperation(clause);
     /* add equivalence constraints imposed by variable binding */
     for (const auto& cur : valueIndex.getVariableReferences()) {
         // the first appearance
         const Location& first = *cur.second.begin();
         // all other appearances
         for (const Location& loc : cur.second) {
             if (first != loc && !valueIndex.isGenerator(loc.identifier)) {
                 // FIXME: equiv' for float types (`FEQ`)
                 op = std::make_unique<RamFilter>(
                         std::make_unique<RamConstraint>(
                                 BinaryConstraintOp::EQ, makeRamTupleElement(first), makeRamTupleElement(loc)),
                         std::move(op));
             }
         }
     }
     /* add conditions caused by atoms, negations, and binary relations */
     for (const auto& lit : clause.getBodyLiterals()) {
         if (auto condition = translator.translateConstraint(lit, valueIndex)) {
             op = std::make_unique<RamFilter>(std::move(condition), std::move(op));
         }
     }
     // add aggregator conditions
     size_t curLevel = op_nesting.size() - 1;
     for (auto it = op_nesting.rbegin(); it != op_nesting.rend(); ++it, --curLevel) {
         const AstNode* cur = *it;
         if (const auto* atom = dynamic_cast<const AstAtom*>(cur)) {
             // add constraints
             size_t pos = 0;
             for (auto arg : atom->getArguments()) {
                 if (auto* agg = dynamic_cast<AstAggregator*>(arg)) {
                     auto loc = valueIndex.getGeneratorLoc(*agg);
                     // FIXME: equiv' for float types (`FEQ`)
                     op = std::make_unique<RamFilter>(std::make_unique<RamConstraint>(BinaryConstraintOp::EQ,
                                                              std::make_unique<RamTupleElement>(curLevel, pos),
                                                              makeRamTupleElement(loc)),
                             std::move(op));
                 }
                 ++pos;
             }
         }
     }
     // add generator levels
     --level;
     for (auto* cur : reverse(generators)) {
         if (auto agg = dynamic_cast<const AstAggregator*>(cur)) {
             // condition for aggregate and helper function to add terms
             std::unique_ptr<RamCondition> aggCond;
             auto addAggCondition = [&](std::unique_ptr<RamCondition> arg) {
                 aggCond = aggCond ? std::make_unique<RamConjunction>(std::move(aggCond), std::move(arg))
                                   : std::move(arg);
             };
             // translate constraints of sub-clause
             for (auto&& lit : agg->getBodyLiterals()) {
                 if (auto newCondition = translator.translateConstraint(lit, valueIndex)) {
                     addAggCondition(std::move(newCondition));
                 }
             }
             // get the first predicate of the sub-clause
             // NB: at most one atom is permitted in a sub-clause
             const AstAtom* atom = nullptr;
             for (auto&& lit : agg->getBodyLiterals()) {
                 if (atom == nullptr) {
                     atom = dynamic_cast<const AstAtom*>(lit);
                 } else {
                     assert(dynamic_cast<const AstAtom*>(lit) == nullptr &&
                             "Unsupported complex aggregation body encountered!");
                 }
             }
             // translate arguments's of atom (if exists) to conditions
             if (atom != nullptr) {
                 size_t pos = 0;
                 auto addAggEqCondition = [&](std::unique_ptr<RamExpression> value) {
                     if (isRamUndefValue(value.get())) return;
                     // FIXME: equiv' for float types (`FEQ`)
                     addAggCondition(std::make_unique<RamConstraint>(BinaryConstraintOp::EQ,
                             std::make_unique<RamTupleElement>(level, pos), std::move(value)));
                 };
                 for (auto* arg : atom->getArguments()) {
                     // variable bindings are issued differently since we don't want self
                     // referential variable bindings
                     if (auto* var = dynamic_cast<const AstVariable*>(arg)) {
                         for (auto&& loc : valueIndex.getVariableReferences().find(var->getName())->second) {
                             if (level != loc.identifier || (int)pos != loc.element) {
                                 addAggEqCondition(makeRamTupleElement(loc));
                                 break;
                             }
                         }
                     } else if (auto value = translator.translateValue(arg, valueIndex)) {
                         addAggEqCondition(std::move(value));
                     }
                     ++pos;
                 }
             }
             // translate aggregate expression
             auto expr = translator.translateValue(agg->getTargetExpression(), valueIndex);
             // add Ram-Aggregation layer
             op = std::make_unique<RamAggregate>(std::move(op), agg->getOperator(),
                     translator.translateRelation(atom),
                     expr ? std::move(expr) : std::make_unique<RamUndefValue>(),
                     aggCond ? std::move(aggCond) : std::make_unique<RamTrue>(), level);
         } else if (const auto* func = dynamic_cast<const AstIntrinsicFunctor*>(cur)) {
             std::vector<std::unique_ptr<RamExpression>> args;
             for (auto&& x : func->getArguments()) {
                 args.push_back(translator.translateValue(x, valueIndex));
             }
             auto func_op = [&]() -> RamNestedIntrinsicOp {
                 switch (func->getFunctionInfo()->op) {
                     case FunctorOp::RANGE: return RamNestedIntrinsicOp::RANGE;
                     case FunctorOp::URANGE: return RamNestedIntrinsicOp::URANGE;
                     case FunctorOp::FRANGE: return RamNestedIntrinsicOp::FRANGE;
                     default:
                         assert(func->getFunctionInfo()->multipleResults);
                         fatal("missing case handler or bad code-gen");
                 }
             };
             op = std::make_unique<RamNestedIntrinsicOperator>(
                     func_op(), std::move(args), std::move(op), level);
         }
         --level;
     }
     // build operation bottom-up
     while (!op_nesting.empty()) {
         // get next operator
         const AstNode* cur = op_nesting.back();
         op_nesting.pop_back();
         // get current nesting level
         auto level = op_nesting.size();
         if (const auto* atom = dynamic_cast<const AstAtom*>(cur)) {
             // add constraints
             // TODO: do we wish to enable constraints by header functor? record inits do so...
             op = filterByConstraints(level, atom->getArguments(), std::move(op), false);
             // check whether all arguments are unnamed variables
             bool isAllArgsUnnamed = true;
             for (auto* argument : atom->getArguments()) {
                 if (dynamic_cast<AstUnnamedVariable*>(argument) == nullptr) {
                     isAllArgsUnnamed = false;
                 }
             }
             // add check for emptiness for an atom
             op = std::make_unique<RamFilter>(
                     std::make_unique<RamNegation>(
                             std::make_unique<RamEmptinessCheck>(translator.translateRelation(atom))),
                     std::move(op));
             // add a scan level
             if (atom->getArity() != 0 && !isAllArgsUnnamed) {
                 if (head->getArity() == 0) {
                     op = std::make_unique<RamBreak>(
                             std::make_unique<RamNegation>(
                                     std::make_unique<RamEmptinessCheck>(translator.translateRelation(head))),
                             std::move(op));
                 }
                 if (Global::config().has("profile")) {
                     std::stringstream ss;
                     ss << head->getQualifiedName();
                     ss.str("");
                     ss << "@frequency-atom" << ';';
                     ss << originalClause.getHead()->getQualifiedName() << ';';
                     ss << version << ';';
                     ss << stringify(toString(clause)) << ';';
                     ss << stringify(toString(*atom)) << ';';
                     ss << stringify(toString(originalClause)) << ';';
                     ss << level << ';';
                     op = std::make_unique<RamScan>(
                             translator.translateRelation(atom), level, std::move(op), ss.str());
                 } else {
                     op = std::make_unique<RamScan>(translator.translateRelation(atom), level, std::move(op));
                 }
             }
             // TODO: support constants in nested records!
         } else if (const auto* rec = dynamic_cast<const AstRecordInit*>(cur)) {
             // add constant constraints
             op = filterByConstraints(level, rec->getArguments(), std::move(op));
             // add an unpack level
             const Location& loc = valueIndex.getDefinitionPoint(*rec);
             op = std::make_unique<RamUnpackRecord>(
                     std::move(op), level, makeRamTupleElement(loc), rec->getArguments().size());
         } else {
             fatal("Unsupported AST node for creation of scan-level!");
         }
     }
     /* generate the final RAM Insert statement */
     std::unique_ptr<RamCondition> cond = createCondition(originalClause);
     if (cond != nullptr) {
         return std::make_unique<RamQuery>(std::make_unique<RamFilter>(std::move(cond), std::move(op)));
     } else {
         return std::make_unique<RamQuery>(std::move(op));
     }
 }
Field Documentation
auxArityAnalysis
const AuxiliaryArity* souffle::AstToRamTranslator::ClauseTranslator::auxArityAnalysis protected
Definition at line 369 of file AstToRamTranslator.h.
generators
std::vector<const AstArgument*> souffle::AstToRamTranslator::ClauseTranslator::generators private
Definition at line 337 of file AstToRamTranslator.h.
level
int souffle::AstToRamTranslator::ClauseTranslator::level = 0 protected
Definition at line 360 of file AstToRamTranslator.h.
op_nesting
std::vector<const AstNode*> souffle::AstToRamTranslator::ClauseTranslator::op_nesting private
Definition at line 340 of file AstToRamTranslator.h.
translator
AstToRamTranslator& souffle::AstToRamTranslator::ClauseTranslator::translator protected
Definition at line 354 of file AstToRamTranslator.h.
valueIndex
ValueIndex souffle::AstToRamTranslator::ClauseTranslator::valueIndex protected
Definition at line 357 of file AstToRamTranslator.h.
The documentation for this class was generated from the following files:
AstToRamTranslator.h
AstToRamTranslator.cpp