souffle: souffle::AstTranslationUnit Class Reference
souffle::AstTranslationUnit Class Reference
AstTranslationUnit class.
#include <TranslationUnit.h>
Public Member Functions
AstTranslationUnit (std::unique_ptr< AstProgram > program, ErrorReport &e, DebugReport &d)
template<class Analysis >
Analysis * getAnalysis () const
get analysis: analysis is generated on the fly if not present
DebugReport & getDebugReport ()
get debug report
const DebugReport & getDebugReport () const
get debug report
ErrorReport & getErrorReport ()
get error report
const ErrorReport & getErrorReport () const
get error report
AstProgram * getProgram ()
get the AST program
const AstProgram * getProgram () const
get the AST program
void invalidateAnalyses ()
destroy all cached analyses of translation unit
virtual ~AstTranslationUnit ()=default
Private Attributes
std::map< std::string, std::unique_ptr< AstAnalysis > > analyses
cached analyses
DebugReport & debugReport
HTML debug report.
ErrorReport & errorReport
Error report capturing errors while compiling.
std::unique_ptr< AstProgram > program
AST program.
Detailed Description
AstTranslationUnit class.
Definition at line 40 of file TranslationUnit.h.
Constructor & Destructor Documentation
AstTranslationUnit()
souffle::AstTranslationUnit::AstTranslationUnit (std::unique_ptr< AstProgram > program, ErrorReport & e, DebugReport & d) inline
Definition at line 42 of file TranslationUnit.h.
References ~AstTranslationUnit().
             : program(std::move(program)), errorReport(e), debugReport(d) {}
~AstTranslationUnit()
virtual souffle::AstTranslationUnit::~AstTranslationUnit () virtual default
Referenced by AstTranslationUnit().
Member Function Documentation
getAnalysis()
template<class Analysis > Analysis* souffle::AstTranslationUnit::getAnalysis () const inline
get analysis: analysis is generated on the fly if not present
Definition at line 49 of file TranslationUnit.h.
References souffle::DebugReport::addSection(), analyses, souffle::Global::config(), debugReport, and souffle::profile::ss.
Referenced by souffle::RecursiveClausesAnalysis::computeIsRecursive(), souffle::RelationScheduleAnalysis::computeRelationExpirySchedule(), souffle::ResolveAnonymousRecordsAliases::findVariablesRecordMapping(), souffle::getGroundedTerms(), souffle::IOAttributesTransformer::getRecordsTypes(), souffle::MaterializeAggregationQueriesTransformer::materializeAggregationQueries(), souffle::MinimiseProgramTransformer::reduceSingletonRelations(), souffle::RemoveEmptyRelationsTransformer::removeEmptyRelations(), souffle::RemoveRelationCopiesTransformer::removeRelationCopies(), souffle::TypeAnalysis::run(), souffle::RedundantRelationsAnalysis::run(), souffle::TopologicallySortedSCCGraphAnalysis::run(), souffle::SCCGraphAnalysis::run(), souffle::RelationScheduleAnalysis::run(), souffle::Adornment::run(), souffle::IOAttributesTransformer::setAttributeNames(), souffle::IOAttributesTransformer::setAttributeParams(), souffle::IOAttributesTransformer::setAttributeTypes(), souffle::ComponentInstantiationTransformer::transform(), souffle::AstExecutionPlanChecker::transform(), souffle::RemoveRedundantRelationsTransformer::transform(), souffle::ReorderLiteralsTransformer::transform(), souffle::ReduceExistentialsTransformer::transform(), souffle::PolymorphicObjectsTransformer::transform(), souffle::AstComponentChecker::transform(), souffle::MagicSetTransformer::transform(), and souffle::AstToRamTranslator::translateProgram().
{
         static const bool debug = Global::config().has("debug-report");
         std::string name = Analysis::name;
         auto it = analyses.find(name);
         if (it == analyses.end()) {
             // analysis does not exist yet, create instance and run it.
             analyses[name] = std::make_unique<Analysis>();
             analyses[name]->run(*this);
             if (debug) {
                 std::stringstream ss;
                 analyses[name]->print(ss);
                 if (nullptr == dynamic_cast<PrecedenceGraphAnalysis*>(analyses[name].get()) &&
                         nullptr == dynamic_cast<SCCGraphAnalysis*>(analyses[name].get())) {
                     debugReport.addSection(name, "Ast Analysis [" + name + "]", ss.str());
                 } else {
                     debugReport.addSection(
                             DebugReportSection(name, "Ast Analysis [" + name + "]", {}, ss.str()));
                 }
             }
         }
         return dynamic_cast<Analysis*>(analyses[name].get());
     }
getDebugReport() [1/2]
DebugReport& souffle::AstTranslationUnit::getDebugReport () inline
get debug report
Definition at line 98 of file TranslationUnit.h.
References debugReport.
Referenced by souffle::DebugReporter::generateDebugReport(), souffle::DebugReporter::transform(), and souffle::AstToRamTranslator::translateUnit().
{
         return debugReport;
     }
getDebugReport() [2/2]
const DebugReport& souffle::AstTranslationUnit::getDebugReport () const inline
get debug report
Definition at line 103 of file TranslationUnit.h.
References debugReport.
{
         return debugReport;
     }
getErrorReport() [1/2]
ErrorReport& souffle::AstTranslationUnit::getErrorReport () inline
get error report
Definition at line 83 of file TranslationUnit.h.
References errorReport.
Referenced by souffle::AstTransformer::apply(), souffle::AstSemanticCheckerImpl::checkAggregator(), souffle::ComponentInstantiationTransformer::transform(), souffle::AstExecutionPlanChecker::transform(), souffle::AstUserDefinedFunctorsTransformer::transform(), souffle::PolymorphicObjectsTransformer::transform(), souffle::AstComponentChecker::transform(), souffle::AstToRamTranslator::translateUnit(), and souffle::GroundedTermsChecker::verify().
{
         return errorReport;
     }
getErrorReport() [2/2]
const ErrorReport& souffle::AstTranslationUnit::getErrorReport () const inline
get error report
Definition at line 88 of file TranslationUnit.h.
References errorReport.
{
         return errorReport;
     }
getProgram() [1/2]
AstProgram* souffle::AstTranslationUnit::getProgram () inline
get the AST program
Definition at line 73 of file TranslationUnit.h.
References program.
Referenced by souffle::AstSemanticCheckerImpl::checkAggregator(), souffle::RecursiveClausesAnalysis::computeIsRecursive(), souffle::DebugReporter::generateDebugReport(), souffle::IOAttributesTransformer::getRecordsParams(), souffle::IOAttributesTransformer::getRecordsTypes(), souffle::makeInfoRelation(), souffle::MaterializeAggregationQueriesTransformer::materializeAggregationQueries(), souffle::MinimiseProgramTransformer::reduceClauseBodies(), souffle::MinimiseProgramTransformer::reduceLocallyEquivalentClauses(), souffle::MinimiseProgramTransformer::reduceSingletonRelations(), souffle::RemoveEmptyRelationsTransformer::removeEmptyRelations(), souffle::RemoveEmptyRelationsTransformer::removeEmptyRelationUses(), souffle::MinimiseProgramTransformer::removeRedundantClauses(), souffle::RemoveRelationCopiesTransformer::removeRelationCopies(), souffle::IOType::run(), souffle::TypeEnvironmentAnalysis::run(), souffle::AuxiliaryArity::run(), souffle::TypeAnalysis::run(), souffle::PrecedenceGraphAnalysis::run(), souffle::RecursiveClausesAnalysis::run(), souffle::RedundantRelationsAnalysis::run(), souffle::RelationDetailCacheAnalysis::run(), souffle::SCCGraphAnalysis::run(), souffle::ComponentLookup::run(), souffle::TypeChecker::run(), souffle::Adornment::run(), souffle::IOAttributesTransformer::setAttributeNames(), souffle::IOAttributesTransformer::setAttributeParams(), souffle::IOAttributesTransformer::setAttributeTypes(), souffle::IODefaultsTransformer::setDefaults(), souffle::RemoveTypecastsTransformer::transform(), souffle::ComponentInstantiationTransformer::transform(), souffle::AstPragmaChecker::transform(), souffle::AstExecutionPlanChecker::transform(), souffle::RemoveRedundantRelationsTransformer::transform(), souffle::UniqueAggregationVariablesTransformer::transform(), souffle::ReorderLiteralsTransformer::transform(), souffle::RemoveBooleanConstraintsTransformer::transform(), souffle::InlineRelationsTransformer::transform(), souffle::ReplaceSingletonVariablesTransformer::transform(), souffle::RemoveRedundantSumsTransformer::transform(), souffle::NormaliseConstraintsTransformer::transform(), souffle::ReduceExistentialsTransformer::transform(), souffle::AstUserDefinedFunctorsTransformer::transform(), souffle::PolymorphicObjectsTransformer::transform(), souffle::NameUnnamedVariablesTransformer::transform(), souffle::MaterializeSingletonAggregationTransformer::transform(), souffle::AstComponentChecker::transform(), souffle::ResolveAnonymousRecordsAliases::transform(), souffle::PartitionBodyLiteralsTransformer::transform(), souffle::MagicSetTransformer::transform(), souffle::FoldAnonymousRecords::transform(), souffle::ResolveAliasesTransformer::transform(), souffle::DebugReporter::transform(), souffle::ProvenanceTransformer::transformMaxHeight(), souffle::AstToRamTranslator::translateUnit(), and souffle::GroundedTermsChecker::verify().
{
         return program.get();
     }
getProgram() [2/2]
const AstProgram* souffle::AstTranslationUnit::getProgram () const inline
get the AST program
Definition at line 78 of file TranslationUnit.h.
References program.
{
         return program.get();
     }
invalidateAnalyses()
void souffle::AstTranslationUnit::invalidateAnalyses () inline
destroy all cached analyses of translation unit
Definition at line 93 of file TranslationUnit.h.
References analyses.
Referenced by souffle::AstTransformer::apply().
{
         analyses.clear();
     }
Field Documentation
analyses
std::map<std::string, std::unique_ptr<AstAnalysis> > souffle::AstTranslationUnit::analyses mutable private
cached analyses
Definition at line 109 of file TranslationUnit.h.
Referenced by getAnalysis(), and invalidateAnalyses().
debugReport
DebugReport& souffle::AstTranslationUnit::debugReport private
HTML debug report.
Definition at line 118 of file TranslationUnit.h.
Referenced by getAnalysis(), and getDebugReport().
errorReport
ErrorReport& souffle::AstTranslationUnit::errorReport private
Error report capturing errors while compiling.
Definition at line 115 of file TranslationUnit.h.
Referenced by getErrorReport().
program
std::unique_ptr<AstProgram> souffle::AstTranslationUnit::program private
AST program.
Definition at line 112 of file TranslationUnit.h.
Referenced by getProgram().
The documentation for this class was generated from the following file:
ast/TranslationUnit.h