souffle: souffle::ReadFileCSV Class Reference
souffle::ReadFileCSV Class Reference
#include <ReadStreamCSV.h>
Public Member Functions
ReadFileCSV (const std::map< std::string, std::string > &rwOperation, SymbolTable &symbolTable, RecordTable &recordTable)
std::unique_ptr< RamDomain[]> readNextTuple () override
Read and return the next tuple.
~ReadFileCSV () override=default
Public Member Functions inherited from souffle::ReadStreamCSV
ReadStreamCSV (std::istream &file, const std::map< std::string, std::string > &rwOperation, SymbolTable &symbolTable, RecordTable &recordTable)
Public Member Functions inherited from souffle::ReadStream
template<typename T >
void readAll (T &relation)
Public Member Functions inherited from souffle::SerialisationStream< false >
virtual ~SerialisationStream ()=default
Static Protected Member Functions
static std::string getFileName (const std::map< std::string, std::string > &rwOperation)
Return given filename or construct from relation name.
Protected Attributes
std::string baseName
std::ifstream fileHandle
Protected Attributes inherited from souffle::ReadStreamCSV
const std::string delimiter
std::istream & file
std::map< int, int > inputMap
size_t lineNumber
Protected Attributes inherited from souffle::SerialisationStream< false >
size_t arity
size_t auxiliaryArity
RO< RecordTable > & recordTable
RO< SymbolTable > & symbolTable
std::vector< std::string > typeAttributes
Json types
Additional Inherited Members
Protected Types inherited from souffle::SerialisationStream< false >
using RO = std::conditional_t< readOnlyTables, const A, A >
Protected Member Functions inherited from souffle::ReadStreamCSV
std::map< int, int > getInputColumnMap (const std::map< std::string, std::string > &rwOperation, const unsigned arity_) const
std::string nextElement (const std::string &line, size_t &start, size_t &end)
RamUnsigned readRamUnsigned (const std::string &element, size_t &charactersRead)
Read an unsigned element.
Protected Member Functions inherited from souffle::ReadStream
void consumeChar (const std::string &str, char c, size_t &pos)
Read past given character, consuming any preceding whitespace.
void consumeWhiteSpace (const std::string &str, size_t &pos)
Advance position in the string until first non-whitespace character.
RamDomain readRecord (const std::string &source, const std::string &recordTypeName, size_t pos=0, size_t *charactersRead=nullptr)
Read a record from a string.
ReadStream (const std::map< std::string, std::string > &rwOperation, SymbolTable &symTab, RecordTable &recTab)
RamDomain readStringInRecord (const std::string &source, const size_t pos, size_t *charactersRead)
Protected Member Functions inherited from souffle::SerialisationStream< false >
SerialisationStream (RO< SymbolTable > &symTab, RO< RecordTable > &recTab, Json types, std::vector< std::string > relTypes, size_t auxArity=0)
SerialisationStream (RO< SymbolTable > &symTab, RO< RecordTable > &recTab, Json types)
SerialisationStream (RO< SymbolTable > &symTab, RO< RecordTable > &recTab, const std::map< std::string, std::string > &rwOperation)
Detailed Description
Definition at line 239 of file ReadStreamCSV.h.
Constructor & Destructor Documentation
ReadFileCSV()
souffle::ReadFileCSV::ReadFileCSV (const std::map< std::string, std::string > & rwOperation, SymbolTable & symbolTable, RecordTable & recordTable) inline
Definition at line 241 of file ReadStreamCSV.h.
References souffle::baseName(), souffle::ReadStreamCSV::file, and souffle::getOr().
             : ReadStreamCSV(fileHandle, rwOperation, symbolTable, recordTable),
               baseName(souffle::baseName(getFileName(rwOperation))),
               fileHandle(getFileName(rwOperation), std::ios::in | std::ios::binary) {
         if (!fileHandle.is_open()) {
             throw std::invalid_argument("Cannot open fact file " + baseName + "\n");
         }
         // Strip headers if we're using them
         if (getOr(rwOperation, "headers", "false") == "true") {
             std::string line;
             getline(file, line);
         }
     }
~ReadFileCSV()
souffle::ReadFileCSV::~ReadFileCSV () override default
Member Function Documentation
getFileName()
static std::string souffle::ReadFileCSV::getFileName (const std::map< std::string, std::string > & rwOperation) inline static protected
Return given filename or construct from relation name.
Default name is [configured path]/[relation name].facts
Parameters
rwOperation map of IO configuration options
Returns
input filename
Definition at line 283 of file ReadStreamCSV.h.
References souffle::getOr().
{
         auto name = getOr(rwOperation, "filename", rwOperation.at("name") + ".facts");
         if (name.front() != '/') {
             name = getOr(rwOperation, "fact-dir", ".") + "/" + name;
         }
         return name;
     }
readNextTuple()
std::unique_ptr<RamDomain[]> souffle::ReadFileCSV::readNextTuple () inline override virtual
Read and return the next tuple.
Returns nullptr if no tuple was readable.
Returns
Reimplemented from souffle::ReadStreamCSV.
Definition at line 262 of file ReadStreamCSV.h.
References souffle::baseName(), e, and souffle::ReadStreamCSV::readNextTuple().
{
         try {
             return ReadStreamCSV::readNextTuple();
         } catch (std::exception& e) {
             std::stringstream errorMessage;
             errorMessage << e.what();
             errorMessage << "cannot parse fact file " << baseName << "!\n";
             throw std::invalid_argument(errorMessage.str());
         }
     }
Field Documentation
baseName
std::string souffle::ReadFileCSV::baseName protected
Definition at line 291 of file ReadStreamCSV.h.
fileHandle
std::ifstream souffle::ReadFileCSV::fileHandle protected
Definition at line 295 of file ReadStreamCSV.h.
The documentation for this class was generated from the following file:
ReadStreamCSV.h