souffle: souffle::SynthesiserRelation Class Reference
souffle::SynthesiserRelation Class Reference abstract
#include <SynthesiserRelation.h>
Public Member Functions
virtual void computeIndices ()=0
Compute the final list of indices to be used.
virtual void generateTypeStruct (std::ostream &out)=0
Generate relation type struct.
size_t getArity () const
Get arity of relation.
const std::string & getDataStructure () const
Get data structure of relation.
MinIndexSelection::OrderCollection getIndices () const
Get list of indices used for relation, guaranteed that original indices in MinIndexSelection come before any generated indices.
const MinIndexSelection & getMinIndexSelection () const
Get stored MinIndexSelection.
std::set< int > getProvenenceIndexNumbers () const
const RamRelation & getRamRelation () const
Get stored RamRelation.
virtual std::string getTypeName ()=0
Print type name.
SynthesiserRelation (const RamRelation &rel, const MinIndexSelection &indices, const bool isProvenance=false)
virtual ~SynthesiserRelation ()=default
Static Public Member Functions
static std::unique_ptr< SynthesiserRelation > getSynthesiserRelation (const RamRelation &ramRel, const MinIndexSelection &indexSet, bool isProvenance)
Factory method to generate a SynthesiserRelation.
Protected Attributes
MinIndexSelection::OrderCollection computedIndices
The final list of indices used.
std::string dataStructure
The data structure used for the relation.
const MinIndexSelection & indices
Indices used for this relation.
const bool isProvenance
Is this relation used with provenance.
size_t masterIndex = -1
The number of the master index.
std::set< int > provenanceIndexNumbers
The list of indices added for provenance computation.
const RamRelation & relation
Ram relation referred to by this.
Detailed Description
Definition at line 21 of file SynthesiserRelation.h.
Constructor & Destructor Documentation
SynthesiserRelation()
souffle::SynthesiserRelation::SynthesiserRelation (const RamRelation & rel, const MinIndexSelection & indices, const bool isProvenance = false) inline
Definition at line 23 of file SynthesiserRelation.h.
References computeIndices(), and ~SynthesiserRelation().
             : relation(rel), indices(indices), isProvenance(isProvenance) {}
~SynthesiserRelation()
virtual souffle::SynthesiserRelation::~SynthesiserRelation () virtual default
Referenced by SynthesiserRelation().
Member Function Documentation
computeIndices()
virtual void souffle::SynthesiserRelation::computeIndices () pure virtual
Compute the final list of indices to be used.
Implemented in souffle::SynthesiserEqrelRelation, souffle::SynthesiserBrieRelation, souffle::SynthesiserIndirectRelation, souffle::SynthesiserDirectRelation, souffle::SynthesiserInfoRelation, and souffle::SynthesiserNullaryRelation.
Referenced by getSynthesiserRelation(), souffle::SynthesiserBrieRelation::SynthesiserBrieRelation(), souffle::SynthesiserDirectRelation::SynthesiserDirectRelation(), souffle::SynthesiserEqrelRelation::SynthesiserEqrelRelation(), souffle::SynthesiserIndirectRelation::SynthesiserIndirectRelation(), souffle::SynthesiserInfoRelation::SynthesiserInfoRelation(), souffle::SynthesiserNullaryRelation::SynthesiserNullaryRelation(), and SynthesiserRelation().
generateTypeStruct()
virtual void souffle::SynthesiserRelation::generateTypeStruct (std::ostream & out) pure virtual
Generate relation type struct.
Implemented in souffle::SynthesiserEqrelRelation, souffle::SynthesiserBrieRelation, souffle::SynthesiserIndirectRelation, souffle::SynthesiserDirectRelation, souffle::SynthesiserInfoRelation, and souffle::SynthesiserNullaryRelation.
Referenced by getRamRelation(), souffle::SynthesiserBrieRelation::SynthesiserBrieRelation(), souffle::SynthesiserDirectRelation::SynthesiserDirectRelation(), souffle::SynthesiserEqrelRelation::SynthesiserEqrelRelation(), souffle::SynthesiserIndirectRelation::SynthesiserIndirectRelation(), souffle::SynthesiserInfoRelation::SynthesiserInfoRelation(), and souffle::SynthesiserNullaryRelation::SynthesiserNullaryRelation().
getArity()
size_t souffle::SynthesiserRelation::getArity () const inline
Get arity of relation.
Definition at line 33 of file SynthesiserRelation.h.
References souffle::RamRelation::getArity(), and relation.
Referenced by souffle::SynthesiserDirectRelation::computeIndices(), souffle::SynthesiserIndirectRelation::computeIndices(), souffle::SynthesiserBrieRelation::computeIndices(), souffle::SynthesiserDirectRelation::generateTypeStruct(), souffle::SynthesiserIndirectRelation::generateTypeStruct(), souffle::SynthesiserBrieRelation::generateTypeStruct(), souffle::SynthesiserInfoRelation::getTypeName(), souffle::SynthesiserDirectRelation::getTypeName(), souffle::SynthesiserIndirectRelation::getTypeName(), and souffle::SynthesiserBrieRelation::getTypeName().
{
         return relation.getArity();
     }
getDataStructure()
const std::string& souffle::SynthesiserRelation::getDataStructure () const inline
Get data structure of relation.
Definition at line 38 of file SynthesiserRelation.h.
References dataStructure.
{
         return dataStructure;
     }
getIndices()
MinIndexSelection::OrderCollection souffle::SynthesiserRelation::getIndices () const inline
Get list of indices used for relation, guaranteed that original indices in MinIndexSelection come before any generated indices.
Definition at line 45 of file SynthesiserRelation.h.
References computedIndices.
Referenced by souffle::SynthesiserDirectRelation::generateTypeStruct(), souffle::SynthesiserIndirectRelation::generateTypeStruct(), souffle::SynthesiserBrieRelation::generateTypeStruct(), souffle::SynthesiserEqrelRelation::generateTypeStruct(), souffle::SynthesiserDirectRelation::getTypeName(), souffle::SynthesiserIndirectRelation::getTypeName(), and souffle::SynthesiserBrieRelation::getTypeName().
{
         return computedIndices;
     }
getMinIndexSelection()
const MinIndexSelection& souffle::SynthesiserRelation::getMinIndexSelection () const inline
Get stored MinIndexSelection.
Definition at line 54 of file SynthesiserRelation.h.
References indices.
Referenced by souffle::SynthesiserDirectRelation::generateTypeStruct(), souffle::SynthesiserIndirectRelation::generateTypeStruct(), souffle::SynthesiserBrieRelation::generateTypeStruct(), souffle::SynthesiserDirectRelation::getTypeName(), souffle::SynthesiserIndirectRelation::getTypeName(), and souffle::SynthesiserBrieRelation::getTypeName().
{
         return indices;
     }
getProvenenceIndexNumbers()
std::set<int> souffle::SynthesiserRelation::getProvenenceIndexNumbers () const inline
Definition at line 49 of file SynthesiserRelation.h.
References provenanceIndexNumbers.
{
         return provenanceIndexNumbers;
     }
getRamRelation()
const RamRelation& souffle::SynthesiserRelation::getRamRelation () const inline
Get stored RamRelation.
Definition at line 59 of file SynthesiserRelation.h.
References generateTypeStruct(), getSynthesiserRelation(), getTypeName(), isProvenance, and relation.
{
         return relation;
     }
getSynthesiserRelation()
std::unique_ptr< SynthesiserRelation > souffle::SynthesiserRelation::getSynthesiserRelation (const RamRelation & ramRel, const MinIndexSelection & indexSet, bool isProvenance) static
Factory method to generate a SynthesiserRelation.
Definition at line 25 of file SynthesiserRelation.cpp.
References souffle::BRIE, souffle::BTREE, computeIndices(), souffle::EQREL, souffle::RamRelation::getArity(), souffle::RamRelation::getRepresentation(), souffle::INFO, and souffle::RamRelation::isNullary().
Referenced by souffle::Synthesiser::generateCode(), and getRamRelation().
{
     SynthesiserRelation* rel;
     // Handle the qualifier in souffle code
     if (isProvenance) {
         rel = new SynthesiserDirectRelation(ramRel, indexSet, isProvenance);
     } else if (ramRel.isNullary()) {
         rel = new SynthesiserNullaryRelation(ramRel, indexSet, isProvenance);
     } else if (ramRel.getRepresentation() == RelationRepresentation::BTREE) {
         rel = new SynthesiserDirectRelation(ramRel, indexSet, isProvenance);
     } else if (ramRel.getRepresentation() == RelationRepresentation::BRIE) {
         rel = new SynthesiserBrieRelation(ramRel, indexSet, isProvenance);
     } else if (ramRel.getRepresentation() == RelationRepresentation::EQREL) {
         rel = new SynthesiserEqrelRelation(ramRel, indexSet, isProvenance);
     } else if (ramRel.getRepresentation() == RelationRepresentation::INFO) {
         rel = new SynthesiserInfoRelation(ramRel, indexSet, isProvenance);
     } else {
         // Handle the data structure command line flag
         if (ramRel.getArity() > 6) {
             rel = new SynthesiserIndirectRelation(ramRel, indexSet, isProvenance);
         } else {
             rel = new SynthesiserDirectRelation(ramRel, indexSet, isProvenance);
         }
     }
     assert(rel != nullptr && "relation type not specified");
     // generate index set
     rel->computeIndices();
     return std::unique_ptr<SynthesiserRelation>(rel);
 }
getTypeName()
virtual std::string souffle::SynthesiserRelation::getTypeName () pure virtual
Print type name.
Implemented in souffle::SynthesiserEqrelRelation, souffle::SynthesiserBrieRelation, souffle::SynthesiserIndirectRelation, souffle::SynthesiserDirectRelation, souffle::SynthesiserInfoRelation, and souffle::SynthesiserNullaryRelation.
Referenced by souffle::SynthesiserDirectRelation::generateTypeStruct(), souffle::SynthesiserIndirectRelation::generateTypeStruct(), souffle::SynthesiserBrieRelation::generateTypeStruct(), souffle::SynthesiserEqrelRelation::generateTypeStruct(), getRamRelation(), souffle::SynthesiserBrieRelation::SynthesiserBrieRelation(), souffle::SynthesiserDirectRelation::SynthesiserDirectRelation(), souffle::SynthesiserEqrelRelation::SynthesiserEqrelRelation(), souffle::SynthesiserIndirectRelation::SynthesiserIndirectRelation(), souffle::SynthesiserInfoRelation::SynthesiserInfoRelation(), and souffle::SynthesiserNullaryRelation::SynthesiserNullaryRelation().
Field Documentation
computedIndices
MinIndexSelection::OrderCollection souffle::SynthesiserRelation::computedIndices protected
The final list of indices used.
Definition at line 84 of file SynthesiserRelation.h.
Referenced by souffle::SynthesiserNullaryRelation::computeIndices(), souffle::SynthesiserInfoRelation::computeIndices(), souffle::SynthesiserDirectRelation::computeIndices(), souffle::SynthesiserIndirectRelation::computeIndices(), souffle::SynthesiserBrieRelation::computeIndices(), souffle::SynthesiserEqrelRelation::computeIndices(), and getIndices().
dataStructure
std::string souffle::SynthesiserRelation::dataStructure protected
The data structure used for the relation.
Definition at line 81 of file SynthesiserRelation.h.
Referenced by getDataStructure().
indices
const MinIndexSelection& souffle::SynthesiserRelation::indices protected
Indices used for this relation.
Definition at line 78 of file SynthesiserRelation.h.
Referenced by souffle::SynthesiserDirectRelation::computeIndices(), souffle::SynthesiserIndirectRelation::computeIndices(), souffle::SynthesiserBrieRelation::computeIndices(), and getMinIndexSelection().
isProvenance
const bool souffle::SynthesiserRelation::isProvenance protected
Is this relation used with provenance.
Definition at line 93 of file SynthesiserRelation.h.
Referenced by souffle::SynthesiserDirectRelation::computeIndices(), souffle::SynthesiserIndirectRelation::computeIndices(), souffle::SynthesiserBrieRelation::computeIndices(), souffle::SynthesiserEqrelRelation::computeIndices(), souffle::SynthesiserDirectRelation::generateTypeStruct(), and getRamRelation().
masterIndex
size_t souffle::SynthesiserRelation::masterIndex = -1 protected
The number of the master index.
Definition at line 90 of file SynthesiserRelation.h.
Referenced by souffle::SynthesiserDirectRelation::computeIndices(), souffle::SynthesiserIndirectRelation::computeIndices(), souffle::SynthesiserBrieRelation::computeIndices(), souffle::SynthesiserEqrelRelation::computeIndices(), souffle::SynthesiserDirectRelation::generateTypeStruct(), souffle::SynthesiserIndirectRelation::generateTypeStruct(), souffle::SynthesiserBrieRelation::generateTypeStruct(), and souffle::SynthesiserEqrelRelation::generateTypeStruct().
provenanceIndexNumbers
std::set<int> souffle::SynthesiserRelation::provenanceIndexNumbers protected
The list of indices added for provenance computation.
Definition at line 87 of file SynthesiserRelation.h.
Referenced by souffle::SynthesiserDirectRelation::generateTypeStruct(), and getProvenenceIndexNumbers().
relation
const RamRelation& souffle::SynthesiserRelation::relation protected
Ram relation referred to by this.
Definition at line 75 of file SynthesiserRelation.h.
Referenced by souffle::SynthesiserDirectRelation::computeIndices(), souffle::SynthesiserDirectRelation::generateTypeStruct(), getArity(), and getRamRelation().
The documentation for this class was generated from the following files:
synthesiser/SynthesiserRelation.h
synthesiser/SynthesiserRelation.cpp