souffle: souffle::AstTypeCast Class Reference
souffle::AstTypeCast Class Reference
An argument capable of casting a value of one type into another.
#include <TypeCast.h>
Public Member Functions
void apply (const AstNodeMapper &map) override
Apply the mapper to all child nodes.
AstTypeCast (Own< AstArgument > value, AstQualifiedName type, SrcLocation loc={})
AstTypeCast * clone () const override
Create clone.
std::vector< const AstNode * > getChildNodes () const override
Obtain a list of all embedded AST child nodes.
const AstQualifiedName & getType () const
Get type.
AstArgument * getValue () const
Get value.
void setType (const AstQualifiedName &type)
Set type.
Public Member Functions inherited from souffle::AstNode
AstNode (SrcLocation loc={})
std::string extloc () const
Return source location of the syntactic element.
const SrcLocation & getSrcLoc () const
Return source location of the AstNode.
bool operator!= (const AstNode &other) const
Inequality check for two AST nodes.
bool operator== (const AstNode &other) const
Equivalence check for two AST nodes.
void setSrcLoc (SrcLocation l)
Set source location for the AstNode.
virtual ~AstNode ()=default
Protected Member Functions
bool equal (const AstNode &node) const override
Abstract equality check for two AST nodes.
void print (std::ostream &os) const override
Output to a given output stream.
Protected Attributes
AstQualifiedName type
The target type name.
Own< AstArgument > value
The value to be casted.
Detailed Description
An argument capable of casting a value of one type into another.
Definition at line 35 of file TypeCast.h.
Constructor & Destructor Documentation
AstTypeCast()
souffle::AstTypeCast::AstTypeCast (Own< AstArgument > value, AstQualifiedName type, SrcLocation loc = {}) inline
Definition at line 37 of file TypeCast.h.
References type, and value.
Referenced by clone().
                                                                                  {})
             : AstArgument(std::move(loc)), value(std::move(value)), type(std::move(type)) {}
Member Function Documentation
apply()
void souffle::AstTypeCast::apply (const AstNodeMapper &) inline override virtual
Apply the mapper to all child nodes.
Reimplemented from souffle::AstNode.
Definition at line 65 of file TypeCast.h.
References souffle::map().
{
         value = map(std::move(value));
     }
clone()
AstTypeCast* souffle::AstTypeCast::clone () const inline override virtual
Create clone.
Implements souffle::AstArgument.
Definition at line 61 of file TypeCast.h.
References AstTypeCast(), souffle::clone(), and souffle::AstNode::getSrcLoc().
{
         return new AstTypeCast(souffle::clone(value), type, getSrcLoc());
     }
equal()
bool souffle::AstTypeCast::equal (const AstNode &) const inline override protected virtual
Abstract equality check for two AST nodes.
Reimplemented from souffle::AstNode.
Definition at line 74 of file TypeCast.h.
References souffle::equal_ptr().
{
         const auto& other = static_cast<const AstTypeCast&>(node);
         return type == other.type && equal_ptr(value, other.value);
     }
getChildNodes()
std::vector<const AstNode*> souffle::AstTypeCast::getChildNodes () const inline override virtual
Obtain a list of all embedded AST child nodes.
Reimplemented from souffle::AstNode.
Definition at line 55 of file TypeCast.h.
References souffle::AstNode::getChildNodes().
{
         auto res = AstArgument::getChildNodes();
         res.push_back(value.get());
         return res;
     }
getType()
const AstQualifiedName& souffle::AstTypeCast::getType () const inline
Get type.
Definition at line 46 of file TypeCast.h.
References type.
Referenced by souffle::TypeChecker::visitTypeCast(), and souffle::TypeConstraintsAnalysis::visitTypeCast().
{
         return type;
     }
getValue()
AstArgument* souffle::AstTypeCast::getValue () const inline
Get value.
Definition at line 41 of file TypeCast.h.
Referenced by souffle::getGroundedTerms(), souffle::TypeChecker::visitTypeCast(), and souffle::TypeConstraintsAnalysis::visitTypeCast().
{
         return value.get();
     }
print()
void souffle::AstTypeCast::print (std::ostream & os) const inline override protected virtual
Output to a given output stream.
Implements souffle::AstNode.
Definition at line 70 of file TypeCast.h.
{
         os << "as(" << *value << "," << type << ")";
     }
setType()
void souffle::AstTypeCast::setType (const AstQualifiedName & type) inline
Set type.
Definition at line 51 of file TypeCast.h.
References type.
{
         this->type = type;
     }
Field Documentation
type
AstQualifiedName souffle::AstTypeCast::type protected
The target type name.
Definition at line 83 of file TypeCast.h.
Referenced by AstTypeCast(), getType(), and setType().
value
Own<AstArgument> souffle::AstTypeCast::value protected
The value to be casted.
Definition at line 80 of file TypeCast.h.
Referenced by AstTypeCast().
The documentation for this class was generated from the following file:
ast/TypeCast.h