souffle: souffle::ReadStreamCSV Class Reference
souffle::ReadStreamCSV Class Reference
#include <ReadStreamCSV.h>
Public Member Functions
ReadStreamCSV (std::istream &file, const std::map< std::string, std::string > &rwOperation, SymbolTable &symbolTable, RecordTable &recordTable)
Public Member Functions inherited from souffle::ReadStream
template<typename T >
void readAll (T &relation)
Public Member Functions inherited from souffle::SerialisationStream< false >
virtual ~SerialisationStream ()=default
Protected Member Functions
std::map< int, int > getInputColumnMap (const std::map< std::string, std::string > &rwOperation, const unsigned arity_) const
std::string nextElement (const std::string &line, size_t &start, size_t &end)
std::unique_ptr< RamDomain[]> readNextTuple () override
Read and return the next tuple.
RamUnsigned readRamUnsigned (const std::string &element, size_t &charactersRead)
Read an unsigned element.
Protected Member Functions inherited from souffle::ReadStream
void consumeChar (const std::string &str, char c, size_t &pos)
Read past given character, consuming any preceding whitespace.
void consumeWhiteSpace (const std::string &str, size_t &pos)
Advance position in the string until first non-whitespace character.
RamDomain readRecord (const std::string &source, const std::string &recordTypeName, size_t pos=0, size_t *charactersRead=nullptr)
Read a record from a string.
ReadStream (const std::map< std::string, std::string > &rwOperation, SymbolTable &symTab, RecordTable &recTab)
RamDomain readStringInRecord (const std::string &source, const size_t pos, size_t *charactersRead)
Protected Member Functions inherited from souffle::SerialisationStream< false >
SerialisationStream (RO< SymbolTable > &symTab, RO< RecordTable > &recTab, Json types, std::vector< std::string > relTypes, size_t auxArity=0)
SerialisationStream (RO< SymbolTable > &symTab, RO< RecordTable > &recTab, Json types)
SerialisationStream (RO< SymbolTable > &symTab, RO< RecordTable > &recTab, const std::map< std::string, std::string > &rwOperation)
Protected Attributes
const std::string delimiter
std::istream & file
std::map< int, int > inputMap
size_t lineNumber
Protected Attributes inherited from souffle::SerialisationStream< false >
size_t arity
size_t auxiliaryArity
RO< RecordTable > & recordTable
RO< SymbolTable > & symbolTable
std::vector< std::string > typeAttributes
Json types
Additional Inherited Members
Protected Types inherited from souffle::SerialisationStream< false >
using RO = std::conditional_t< readOnlyTables, const A, A >
Detailed Description
Definition at line 45 of file ReadStreamCSV.h.
Constructor & Destructor Documentation
ReadStreamCSV()
souffle::ReadStreamCSV::ReadStreamCSV (std::istream & file, const std::map< std::string, std::string > & rwOperation, SymbolTable & symbolTable, RecordTable & recordTable) inline
Definition at line 47 of file ReadStreamCSV.h.
References souffle::SerialisationStream< false >::arity, and inputMap.
             : ReadStream(rwOperation, symbolTable, recordTable),
               delimiter(getOr(rwOperation, "delimiter", "\t")), file(file), lineNumber(0),
               inputMap(getInputColumnMap(rwOperation, arity)) {
         while (inputMap.size() < arity) {
             int size = static_cast<int>(inputMap.size());
             inputMap[size] = size;
         }
     }
Member Function Documentation
getInputColumnMap()
std::map<int, int> souffle::ReadStreamCSV::getInputColumnMap (const std::map< std::string, std::string > & rwOperation, const unsigned arity_) const inline protected
Definition at line 209 of file ReadStreamCSV.h.
References souffle::getOr().
{
         std::string columnString = getOr(rwOperation, "columns", "");
         std::map<int, int> inputColumnMap;
         if (!columnString.empty()) {
             std::istringstream iss(columnString);
             std::string mapping;
             int index = 0;
             while (std::getline(iss, mapping, ':')) {
                 inputColumnMap[stoi(mapping)] = index++;
             }
             if (inputColumnMap.size() < arity_) {
                 throw std::invalid_argument("Invalid column set was given: <" + columnString + ">");
             }
         } else {
             while (inputColumnMap.size() < arity_) {
                 int size = static_cast<int>(inputColumnMap.size());
                 inputColumnMap[size] = size;
             }
         }
         return inputColumnMap;
     }
nextElement()
std::string souffle::ReadStreamCSV::nextElement (const std::string & line, size_t & start, size_t & end) inline protected
Definition at line 155 of file ReadStreamCSV.h.
References delimiter, and lineNumber.
Referenced by readNextTuple().
{
         std::string element;
         // Handle record/tuple delimiter coincidence.
         if (delimiter.find(',') != std::string::npos) {
             int record_parens = 0;
             size_t next_delimiter = line.find(delimiter, start);
             // Find first delimiter after the record.
             while (end < std::min(next_delimiter, line.length()) || record_parens != 0) {
                 // Track the number of parenthesis.
                 if (line[end] == '[') {
                     ++record_parens;
                 } else if (line[end] == ']') {
                     --record_parens;
                 }
                 // Check for unbalanced parenthesis.
                 if (record_parens < 0) {
                     break;
                 };
                 ++end;
                 // Find a next delimiter if the old one is invalid.
                 // But only if inside the unbalance parenthesis.
                 if (end == next_delimiter && record_parens != 0) {
                     next_delimiter = line.find(delimiter, end);
                 }
             }
             // Handle the end-of-the-line case where parenthesis are unbalanced.
             if (record_parens != 0) {
                 std::stringstream errorMessage;
                 errorMessage << "Unbalanced record parenthesis " << lineNumber << "; ";
                 throw std::invalid_argument(errorMessage.str());
             }
         } else {
             end = std::min(line.find(delimiter, start), line.length());
         }
         // Check for missing value.
         if (start > end) {
             std::stringstream errorMessage;
             errorMessage << "Values missing in line " << lineNumber << "; ";
             throw std::invalid_argument(errorMessage.str());
         }
         element = line.substr(start, end - start);
         start = end + delimiter.size();
         return element;
     }
readNextTuple()
std::unique_ptr<RamDomain[]> souffle::ReadStreamCSV::readNextTuple () inline override protected virtual
Read and return the next tuple.
Returns nullptr if no tuple was readable.
Returns
Implements souffle::ReadStream.
Reimplemented in souffle::ReadFileCSV.
Definition at line 65 of file ReadStreamCSV.h.
References souffle::SerialisationStream< false >::arity, delimiter, souffle::fatal(), file, inputMap, lineNumber, nextElement(), souffle::ramBitCast(), souffle::RamFloatFromString(), souffle::RamSignedFromString(), readRamUnsigned(), souffle::ReadStream::readRecord(), souffle::SerialisationStream< false >::symbolTable, and souffle::SerialisationStream< false >::typeAttributes.
Referenced by souffle::ReadFileCSV::readNextTuple().
{
         if (file.eof()) {
             return nullptr;
         }
         std::string line;
         std::unique_ptr<RamDomain[]> tuple = std::make_unique<RamDomain[]>(typeAttributes.size());
         if (!getline(file, line)) {
             return nullptr;
         }
         // Handle Windows line endings on non-Windows systems
         if (!line.empty() && line.back() == '\r') {
             line = line.substr(0, line.length() - 1);
         }
         ++lineNumber;
         size_t start = 0;
         size_t end = 0;
         size_t columnsFilled = 0;
         for (uint32_t column = 0; columnsFilled < arity; column++) {
             size_t charactersRead = 0;
             std::string element = nextElement(line, start, end);
             if (inputMap.count(column) == 0) {
                 continue;
             }
             ++columnsFilled;
             try {
                 auto&& ty = typeAttributes.at(inputMap[column]);
                 switch (ty[0]) {
                     case 's': {
                         tuple[inputMap[column]] = symbolTable.unsafeLookup(element);
                         charactersRead = element.size();
                         break;
                     }
                     case 'r': {
                         tuple[inputMap[column]] = readRecord(element, ty, 0, &charactersRead);
                         break;
                     }
                     case 'i': {
                         tuple[inputMap[column]] = RamSignedFromString(element, &charactersRead);
                         break;
                     }
                     case 'u': {
                         tuple[inputMap[column]] = ramBitCast(readRamUnsigned(element, charactersRead));
                         break;
                     }
                     case 'f': {
                         tuple[inputMap[column]] = ramBitCast(RamFloatFromString(element, &charactersRead));
                         break;
                     }
                     default: fatal("invalid type attribute: `%c`", ty[0]);
                 }
                 // Check if everything was read.
                 if (charactersRead != element.size()) {
                     throw std::invalid_argument(
                             "Expected: " + delimiter + " or \\n. Got: " + element[charactersRead]);
                 }
             } catch (...) {
                 std::stringstream errorMessage;
                 errorMessage << "Error converting <" + element + "> in column " << column + 1 << " in line "
                              << lineNumber << "; ";
                 throw std::invalid_argument(errorMessage.str());
             }
         }
         return tuple;
     }
readRamUnsigned()
RamUnsigned souffle::ReadStreamCSV::readRamUnsigned (const std::string & element, size_t & charactersRead) inline protected
Read an unsigned element.
Possible bases are 2, 10, 16 Base is indicated by the first two chars.
Definition at line 138 of file ReadStreamCSV.h.
References souffle::isPrefix(), and souffle::RamUnsignedFromString().
Referenced by readNextTuple().
{
         // Sanity check
         assert(element.size() > 0);
         RamSigned value = 0;
         // Check prefix and parse the input.
         if (isPrefix("0b", element)) {
             value = RamUnsignedFromString(element, &charactersRead, 2);
         } else if (isPrefix("0x", element)) {
             value = RamUnsignedFromString(element, &charactersRead, 16);
         } else {
             value = RamUnsignedFromString(element, &charactersRead);
         }
         return value;
     }
Field Documentation
delimiter
const std::string souffle::ReadStreamCSV::delimiter protected
Definition at line 233 of file ReadStreamCSV.h.
Referenced by nextElement(), and readNextTuple().
file
std::istream& souffle::ReadStreamCSV::file protected
Definition at line 234 of file ReadStreamCSV.h.
Referenced by souffle::ReadFileCSV::ReadFileCSV(), and readNextTuple().
inputMap
std::map<int, int> souffle::ReadStreamCSV::inputMap protected
Definition at line 236 of file ReadStreamCSV.h.
Referenced by readNextTuple(), and ReadStreamCSV().
lineNumber
size_t souffle::ReadStreamCSV::lineNumber protected
Definition at line 235 of file ReadStreamCSV.h.
Referenced by nextElement(), and readNextTuple().
The documentation for this class was generated from the following file:
ReadStreamCSV.h