souffle: souffle::AstProgram Class Reference
souffle::AstProgram Class Reference
Intermediate representation of a datalog program that consists of relations, clauses and types.
#include <Program.h>
Public Member Functions
void addClause (Own< AstClause > clause)
add a clause
void addRelation (Own< AstRelation > r)
void apply (const AstNodeMapper &map) override
Apply the mapper to all child nodes.
AstProgram * clone () const override
Create a clone (i.e.
std::vector< const AstNode * > getChildNodes () const override
Obtain a list of all embedded AST child nodes.
std::vector< AstClause * > getClauses () const
get clauses
std::vector< AstComponentInit * > getComponentInstantiations () const
get component instantiation
std::vector< AstComponent * > getComponents () const
get components
std::vector< AstFunctorDeclaration * > getFunctorDeclarations () const
get functor declarations
std::vector< AstIO * > getIOs () const
get io directives
const VecOwn< AstPragma > & getPragmaDirectives () const
get pragma directives
std::vector< AstRelation * > getRelations () const
get relations
std::vector< AstType * > getTypes () const
get types
bool removeClause (const AstClause *clause)
remove a clause
bool removeIO (const AstIO *io)
remove an io
bool removeRelation (const AstQualifiedName &name)
remove relation
void setClauses (VecOwn< AstClause > newClauses)
Public Member Functions inherited from souffle::AstNode
AstNode (SrcLocation loc={})
std::string extloc () const
Return source location of the syntactic element.
const SrcLocation & getSrcLoc () const
Return source location of the AstNode.
bool operator!= (const AstNode &other) const
Inequality check for two AST nodes.
bool operator== (const AstNode &other) const
Equivalence check for two AST nodes.
void setSrcLoc (SrcLocation l)
Set source location for the AstNode.
virtual ~AstNode ()=default
Protected Member Functions
void addComponent (Own< AstComponent > c)
add component
void addFunctorDeclaration (Own< souffle::AstFunctorDeclaration > f)
add functor
void addInstantiation (Own< AstComponentInit > i)
add component instantiation
void addIO (Own< AstIO > directive)
add IO directive
void addPragma (Own< AstPragma > pragma)
add a pragma
void addType (Own< AstType > type)
bool equal (const AstNode &node) const override
Abstract equality check for two AST nodes.
void print (std::ostream &os) const override
Output to a given output stream.
Protected Attributes
VecOwn< AstClause > clauses
Program clauses.
VecOwn< AstComponent > components
Program components.
VecOwn< AstFunctorDeclaration > functors
External Functors.
VecOwn< AstComponentInit > instantiations
Component instantiations.
VecOwn< AstIO > ios
IO statements.
VecOwn< AstPragma > pragmaDirectives
Pragmas.
VecOwn< AstRelation > relations
Program relations.
VecOwn< AstType > types
Program types.
Friends
class ComponentInstantiationTransformer
class ParserDriver
Detailed Description
Intermediate representation of a datalog program that consists of relations, clauses and types.
Definition at line 48 of file Program.h.
Member Function Documentation
addClause()
void souffle::AstProgram::addClause (Own< AstClause > clause) inline
add a clause
Definition at line 105 of file Program.h.
References clauses.
Referenced by souffle::makeInfoRelation(), souffle::MaterializeAggregationQueriesTransformer::materializeAggregationQueries(), souffle::MaterializeAggregationQueriesTransformer::needsMaterializedRelation(), souffle::normaliseInlinedHeads(), souffle::RemoveEmptyRelationsTransformer::removeEmptyRelationUses(), souffle::separateDBs(), souffle::ReorderLiteralsTransformer::transform(), souffle::RemoveBooleanConstraintsTransformer::transform(), souffle::InlineRelationsTransformer::transform(), souffle::ReduceExistentialsTransformer::transform(), souffle::MaterializeSingletonAggregationTransformer::transform(), souffle::PartitionBodyLiteralsTransformer::transform(), souffle::MagicSetTransformer::transform(), souffle::ResolveAliasesTransformer::transform(), and souffle::transformEqrelRelation().
{
         assert(clause != nullptr && "Undefined clause");
         assert(clause->getHead() != nullptr && "Undefined head of the clause");
         clauses.push_back(std::move(clause));
     }
addComponent()
void souffle::AstProgram::addComponent (Own< AstComponent > c) inline protected
add component
Definition at line 286 of file Program.h.
References components.
{
         components.push_back(std::move(c));
     }
addFunctorDeclaration()
void souffle::AstProgram::addFunctorDeclaration (Own< souffle::AstFunctorDeclaration > f) inline protected
add functor
Definition at line 280 of file Program.h.
References functors, and souffle::getFunctorDeclaration().
{
         assert(getFunctorDeclaration(*this, f->getName()) == nullptr && "Redefinition of functor!");
         functors.push_back(std::move(f));
     }
addInstantiation()
void souffle::AstProgram::addInstantiation (Own< AstComponentInit > i) inline protected
add component instantiation
Definition at line 291 of file Program.h.
References instantiations.
{
         instantiations.push_back(std::move(i));
     }
addIO()
void souffle::AstProgram::addIO (Own< AstIO > directive) inline protected
add IO directive
Definition at line 268 of file Program.h.
References ios.
{
         assert(directive && "NULL IO directive");
         ios.push_back(std::move(directive));
     }
addPragma()
void souffle::AstProgram::addPragma (Own< AstPragma > pragma) inline protected
add a pragma
Definition at line 274 of file Program.h.
References pragmaDirectives.
{
         assert(pragma && "NULL IO directive");
         pragmaDirectives.push_back(std::move(pragma));
     }
addRelation()
void souffle::AstProgram::addRelation (Own< AstRelation > r) inline
Definition at line 81 of file Program.h.
References souffle::getRelation(), and relations.
Referenced by souffle::MaterializeAggregationQueriesTransformer::materializeAggregationQueries(), souffle::MaterializeAggregationQueriesTransformer::needsMaterializedRelation(), souffle::separateDBs(), souffle::ReduceExistentialsTransformer::transform(), souffle::MaterializeSingletonAggregationTransformer::transform(), souffle::PartitionBodyLiteralsTransformer::transform(), and souffle::MagicSetTransformer::transform().
{
         assert(getRelation(*this, r->getQualifiedName()) == nullptr && "Redefinition of relation!");
         relations.push_back(std::move(r));
     }
addType()
void souffle::AstProgram::addType (Own< AstType > type) inline protected
Definition at line 262 of file Program.h.
References souffle::getType(), and types.
{
         assert(getType(*this, type->getQualifiedName()) == nullptr && "Redefinition of type!");
         types.push_back(std::move(type));
     }
apply()
void souffle::AstProgram::apply (const AstNodeMapper &) inline override virtual
Apply the mapper to all child nodes.
Reimplemented from souffle::AstNode.
Definition at line 156 of file Program.h.
References clauses, components, functors, instantiations, ios, souffle::map(), pragmaDirectives, relations, and types.
Referenced by souffle::nameInlinedUnderscores(), souffle::MinimiseProgramTransformer::reduceSingletonRelations(), souffle::RemoveTypecastsTransformer::transform(), souffle::RemoveBooleanConstraintsTransformer::transform(), souffle::RemoveRedundantSumsTransformer::transform(), souffle::ReduceExistentialsTransformer::transform(), souffle::AstUserDefinedFunctorsTransformer::transform(), souffle::PolymorphicObjectsTransformer::transform(), and souffle::NameUnnamedVariablesTransformer::transform().
{
         for (auto& cur : pragmaDirectives) {
             cur = map(std::move(cur));
         }
         for (auto& cur : components) {
             cur = map(std::move(cur));
         }
         for (auto& cur : instantiations) {
             cur = map(std::move(cur));
         }
         for (auto& cur : functors) {
             cur = map(std::move(cur));
         }
         for (auto& cur : types) {
             cur = map(std::move(cur));
         }
         for (auto& cur : relations) {
             cur = map(std::move(cur));
         }
         for (auto& cur : clauses) {
             cur = map(std::move(cur));
         }
         for (auto& cur : ios) {
             cur = map(std::move(cur));
         }
     }
clone()
AstProgram* souffle::AstProgram::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::AstNode.
Definition at line 143 of file Program.h.
References clauses, souffle::clone(), components, functors, instantiations, ios, pragmaDirectives, relations, and types.
{
         auto res = new AstProgram();
         res->pragmaDirectives = souffle::clone(pragmaDirectives);
         res->components = souffle::clone(components);
         res->instantiations = souffle::clone(instantiations);
         res->types = souffle::clone(types);
         res->functors = souffle::clone(functors);
         res->relations = souffle::clone(relations);
         res->clauses = souffle::clone(clauses);
         res->ios = souffle::clone(ios);
         return res;
     }
equal()
bool souffle::AstProgram::equal (const AstNode &) const inline override protected virtual
Abstract equality check for two AST nodes.
Reimplemented from souffle::AstNode.
Definition at line 228 of file Program.h.
References clauses, components, souffle::equal_targets(), functors, instantiations, ios, pragmaDirectives, relations, and types.
{
         const auto& other = static_cast<const AstProgram&>(node);
         if (!equal_targets(pragmaDirectives, other.pragmaDirectives)) {
             return false;
         }
         if (!equal_targets(components, other.components)) {
             return false;
         }
         if (!equal_targets(instantiations, other.instantiations)) {
             return false;
         }
         if (!equal_targets(functors, other.functors)) {
             return false;
         }
         if (!equal_targets(types, other.types)) {
             return false;
         }
         if (!equal_targets(relations, other.relations)) {
             return false;
         }
         if (!equal_targets(clauses, other.clauses)) {
             return false;
         }
         if (!equal_targets(ios, other.ios)) {
             return false;
         }
         return true;
     }
getChildNodes()
std::vector<const AstNode*> souffle::AstProgram::getChildNodes () const inline override virtual
Obtain a list of all embedded AST child nodes.
Reimplemented from souffle::AstNode.
Definition at line 183 of file Program.h.
References clauses, components, functors, instantiations, ios, pragmaDirectives, relations, and types.
{
         std::vector<const AstNode*> res;
         for (const auto& cur : pragmaDirectives) {
             res.push_back(cur.get());
         }
         for (const auto& cur : components) {
             res.push_back(cur.get());
         }
         for (const auto& cur : instantiations) {
             res.push_back(cur.get());
         }
         for (const auto& cur : functors) {
             res.push_back(cur.get());
         }
         for (const auto& cur : types) {
             res.push_back(cur.get());
         }
         for (const auto& cur : relations) {
             res.push_back(cur.get());
         }
         for (const auto& cur : clauses) {
             res.push_back(cur.get());
         }
         for (const auto& cur : ios) {
             res.push_back(cur.get());
         }
         return res;
     }
getClauses()
std::vector<AstClause*> souffle::AstProgram::getClauses () const inline
get clauses
Definition at line 61 of file Program.h.
References clauses, and souffle::toPtrVector().
Referenced by souffle::AstSemanticCheckerImpl::AstSemanticCheckerImpl(), souffle::getClauses(), souffle::TypeAnalysis::run(), souffle::TypeChecker::run(), souffle::ResolveAnonymousRecordsAliases::transform(), and souffle::FoldAnonymousRecords::transform().
{
         return toPtrVector(clauses);
     }
getComponentInstantiations()
std::vector<AstComponentInit*> souffle::AstProgram::getComponentInstantiations () const inline
get component instantiation
Definition at line 139 of file Program.h.
References instantiations, and souffle::toPtrVector().
Referenced by souffle::AstComponentChecker::checkComponentNamespaces(), and souffle::AstComponentChecker::checkComponents().
{
         return toPtrVector(instantiations);
     }
getComponents()
std::vector<AstComponent*> souffle::AstProgram::getComponents () const inline
get components
Definition at line 134 of file Program.h.
References components, and souffle::toPtrVector().
Referenced by souffle::AstComponentChecker::checkComponentNamespaces(), souffle::AstComponentChecker::checkComponents(), and souffle::ComponentLookup::run().
{
         return toPtrVector(components);
     }
getFunctorDeclarations()
std::vector<AstFunctorDeclaration*> souffle::AstProgram::getFunctorDeclarations () const inline
get functor declarations
Definition at line 66 of file Program.h.
References functors, and souffle::toPtrVector().
Referenced by souffle::getFunctorDeclaration().
{
         return toPtrVector(functors);
     }
getIOs()
std::vector<AstIO*> souffle::AstProgram::getIOs () const inline
get io directives
Definition at line 71 of file Program.h.
References ios, and souffle::toPtrVector().
Referenced by souffle::AstSemanticCheckerImpl::checkIO(), souffle::AstToRamTranslator::getInputDirectives(), souffle::getIOs(), souffle::AstToRamTranslator::getOutputDirectives(), souffle::IOAttributesTransformer::setAttributeNames(), souffle::IOAttributesTransformer::setAttributeParams(), souffle::IOAttributesTransformer::setAttributeTypes(), souffle::IODefaultsTransformer::setDefaults(), and souffle::MagicSetTransformer::transform().
{
         return toPtrVector(ios);
     }
getPragmaDirectives()
const VecOwn<AstPragma>& souffle::AstProgram::getPragmaDirectives () const inline
get pragma directives
Definition at line 76 of file Program.h.
References pragmaDirectives.
{
         return pragmaDirectives;
     }
getRelations()
std::vector<AstRelation*> souffle::AstProgram::getRelations () const inline
get relations
Definition at line 56 of file Program.h.
References relations, and souffle::toPtrVector().
Referenced by souffle::addBackwardDependencies(), souffle::addIgnoredRelations(), souffle::AstSemanticCheckerImpl::AstSemanticCheckerImpl(), souffle::bindComposites(), souffle::AstComponentChecker::checkComponentNamespaces(), souffle::AstSemanticCheckerImpl::checkInlining(), souffle::AstSemanticCheckerImpl::checkNamespaces(), souffle::getRelation(), souffle::nameInlinedUnderscores(), souffle::normaliseInlinedHeads(), souffle::MinimiseProgramTransformer::reduceLocallyEquivalentClauses(), souffle::MinimiseProgramTransformer::reduceSingletonRelations(), souffle::RemoveEmptyRelationsTransformer::removeEmptyRelations(), souffle::replaceUnderscores(), souffle::PrecedenceGraphAnalysis::run(), souffle::RedundantRelationsAnalysis::run(), souffle::SCCGraphAnalysis::run(), souffle::Adornment::run(), souffle::separateDBs(), souffle::test::TEST(), souffle::ReorderLiteralsTransformer::transform(), souffle::RemoveBooleanConstraintsTransformer::transform(), souffle::InlineRelationsTransformer::transform(), souffle::ReplaceSingletonVariablesTransformer::transform(), souffle::ReduceExistentialsTransformer::transform(), souffle::NormaliseConstraintsTransformer::transform(), and souffle::NameUnnamedVariablesTransformer::transform().
{
         return toPtrVector(relations);
     }
getTypes()
std::vector<AstType*> souffle::AstProgram::getTypes () const inline
get types
Definition at line 51 of file Program.h.
References souffle::toPtrVector(), and types.
Referenced by souffle::AstSemanticCheckerImpl::AstSemanticCheckerImpl(), souffle::AstComponentChecker::checkComponentNamespaces(), souffle::AstSemanticCheckerImpl::checkNamespaces(), souffle::AstSemanticCheckerImpl::checkUnionType(), souffle::IOAttributesTransformer::getRecordsParams(), souffle::IOAttributesTransformer::getRecordsTypes(), souffle::getType(), and souffle::TypeEnvironmentAnalysis::run().
{
         return toPtrVector(types);
     }
print()
void souffle::AstProgram::print (std::ostream & os) const inline override protected virtual
Output to a given output stream.
Implements souffle::AstNode.
Definition at line 213 of file Program.h.
References clauses, components, functors, instantiations, ios, souffle::join(), pragmaDirectives, relations, and types.
{
         auto show = [&](auto&& xs, char const* sep = "\n") {
             if (!xs.empty()) os << join(xs, sep) << "\n";
         };
         show(pragmaDirectives, "\n\n");
         show(components);
         show(instantiations);
         show(types);
         show(functors);
         show(relations);
         show(clauses, "\n\n");
         show(ios, "\n\n");
     }
removeClause()
bool souffle::AstProgram::removeClause (const AstClause * clause) inline
remove a clause
Definition at line 112 of file Program.h.
References clauses.
Referenced by souffle::normaliseInlinedHeads(), souffle::MinimiseProgramTransformer::reduceClauseBodies(), souffle::MinimiseProgramTransformer::reduceLocallyEquivalentClauses(), souffle::MinimiseProgramTransformer::reduceSingletonRelations(), souffle::RemoveEmptyRelationsTransformer::removeEmptyRelationUses(), souffle::MinimiseProgramTransformer::removeRedundantClauses(), souffle::removeRelationClauses(), souffle::ReorderLiteralsTransformer::transform(), souffle::RemoveBooleanConstraintsTransformer::transform(), souffle::InlineRelationsTransformer::transform(), souffle::PartitionBodyLiteralsTransformer::transform(), and souffle::ResolveAliasesTransformer::transform().
{
         for (auto it = clauses.begin(); it != clauses.end(); it++) {
             if (**it == *clause) {
                 clauses.erase(it);
                 return true;
             }
         }
         return false;
     }
removeIO()
bool souffle::AstProgram::removeIO (const AstIO * io) inline
remove an io
Definition at line 123 of file Program.h.
References ios.
Referenced by souffle::removeRelationIOs().
{
         for (auto it = ios.begin(); it != ios.end(); it++) {
             if (**it == *io) {
                 ios.erase(it);
                 return true;
             }
         }
         return false;
     }
removeRelation()
bool souffle::AstProgram::removeRelation (const AstQualifiedName & name) inline
remove relation
Definition at line 87 of file Program.h.
References relations, souffle::removeRelationClauses(), and souffle::removeRelationIOs().
Referenced by souffle::MinimiseProgramTransformer::reduceSingletonRelations(), souffle::RemoveEmptyRelationsTransformer::removeEmptyRelations(), souffle::RemoveRedundantRelationsTransformer::transform(), and souffle::MagicSetTransformer::transform().
{
         for (auto it = relations.begin(); it != relations.end(); it++) {
             const auto& rel = *it;
             if (rel->getQualifiedName() == name) {
                 removeRelationClauses(*this, name);
                 removeRelationIOs(*this, name);
                 relations.erase(it);
                 return true;
             }
         }
         return false;
     }
setClauses()
void souffle::AstProgram::setClauses (VecOwn< AstClause > newClauses) inline
Definition at line 100 of file Program.h.
References clauses.
Referenced by souffle::FoldAnonymousRecords::transform().
{
         clauses = std::move(newClauses);
     }
Friends And Related Function Documentation
ComponentInstantiationTransformer
friend class ComponentInstantiationTransformer friend
Definition at line 258 of file Program.h.
ParserDriver
friend class ParserDriver friend
Definition at line 259 of file Program.h.
Field Documentation
clauses
VecOwn<AstClause> souffle::AstProgram::clauses protected
Program clauses.
Definition at line 305 of file Program.h.
Referenced by addClause(), apply(), clone(), equal(), getChildNodes(), getClauses(), print(), removeClause(), setClauses(), and souffle::ComponentInstantiationTransformer::transform().
components
VecOwn<AstComponent> souffle::AstProgram::components protected
Program components.
Definition at line 311 of file Program.h.
Referenced by addComponent(), apply(), clone(), equal(), getChildNodes(), getComponents(), print(), and souffle::ComponentInstantiationTransformer::transform().
functors
VecOwn<AstFunctorDeclaration> souffle::AstProgram::functors protected
External Functors.
Definition at line 302 of file Program.h.
Referenced by addFunctorDeclaration(), apply(), clone(), equal(), getChildNodes(), getFunctorDeclarations(), and print().
instantiations
VecOwn<AstComponentInit> souffle::AstProgram::instantiations protected
Component instantiations.
Definition at line 314 of file Program.h.
Referenced by addInstantiation(), apply(), clone(), equal(), getChildNodes(), getComponentInstantiations(), print(), and souffle::ComponentInstantiationTransformer::transform().
ios
VecOwn<AstIO> souffle::AstProgram::ios protected
IO statements.
Definition at line 308 of file Program.h.
Referenced by addIO(), apply(), clone(), equal(), getChildNodes(), getIOs(), print(), removeIO(), and souffle::ComponentInstantiationTransformer::transform().
pragmaDirectives
VecOwn<AstPragma> souffle::AstProgram::pragmaDirectives protected
Pragmas.
Definition at line 317 of file Program.h.
Referenced by addPragma(), apply(), clone(), equal(), getChildNodes(), getPragmaDirectives(), and print().
relations
VecOwn<AstRelation> souffle::AstProgram::relations protected
Program relations.
Definition at line 299 of file Program.h.
Referenced by addRelation(), apply(), clone(), equal(), getChildNodes(), getRelations(), print(), removeRelation(), and souffle::ComponentInstantiationTransformer::transform().
types
VecOwn<AstType> souffle::AstProgram::types protected
Program types.
Definition at line 296 of file Program.h.
Referenced by addType(), apply(), clone(), equal(), getChildNodes(), getTypes(), print(), and souffle::ComponentInstantiationTransformer::transform().
The documentation for this class was generated from the following file:
ast/Program.h