souffle: souffle::TupleRef Class Reference
souffle::TupleRef Class Reference
A type-erased reference to tuples.
#include <InterpreterIndex.h>
Public Member Functions
template<std::size_t Arity>
const Tuple< RamDomain, Arity > & asTuple () const
const RamDomain * getBase () const
bool operator== (const TupleRef &other) const
const RamDomain & operator[] (std::size_t i) const
Provides access to tuple components.
std::size_t size () const
Obtains the arity of the referenced tuple.
TupleRef ()=default
TupleRef (const RamDomain *base, std::size_t arity)
Creates a tuple reference from some externally maintained.
template<std::size_t Arity>
TupleRef (const Tuple< RamDomain, Arity > &tuple)
A constructor supporting the implicit conversion of a tuple into a reference.
TupleRef (const DynTuple &tuple)
Private Attributes
std::size_t arity = 0
const RamDomain * base = nullptr
Friends
std::ostream & operator<< (std::ostream &out, TupleRef ref)
Detailed Description
A type-erased reference to tuples.
The reference does not own the referenced data. It is thus very light-weight to create and forward.
Definition at line 60 of file InterpreterIndex.h.
Constructor & Destructor Documentation
TupleRef() [1/4]
souffle::TupleRef::TupleRef () default
TupleRef() [2/4]
souffle::TupleRef::TupleRef (const RamDomain * base, std::size_t arity) inline
Creates a tuple reference from some externally maintained.
Definition at line 73 of file InterpreterIndex.h.
 : base(base), arity(arity) {}
TupleRef() [3/4]
template<std::size_t Arity> souffle::TupleRef::TupleRef (const Tuple< RamDomain, Arity > & tuple) inline
A constructor supporting the implicit conversion of a tuple into a reference.
Definition at line 80 of file InterpreterIndex.h.
 : TupleRef(&tuple[0], Arity) {}
TupleRef() [4/4]
souffle::TupleRef::TupleRef (const DynTuple & tuple) inline
Definition at line 82 of file InterpreterIndex.h.
 : TupleRef(&tuple[0], tuple.size()) {}
Member Function Documentation
asTuple()
template<std::size_t Arity> const Tuple<RamDomain, Arity>& souffle::TupleRef::asTuple () const inline
Definition at line 85 of file InterpreterIndex.h.
References base.
Referenced by souffle::GenericIndex< btree_set< t_tuple< Arity >, comparator< Arity >, std::allocator< t_tuple< Arity > >, 256, detail::default_strategy< t_tuple< Arity > >::type, comparator< Arity - 2 >, InterpreterProvenanceUpdater< Arity > > >::bounds(), souffle::GenericIndex< Structure >::GenericIndexView::contains(), and souffle::GenericIndex< btree_set< t_tuple< Arity >, comparator< Arity >, std::allocator< t_tuple< Arity > >, 256, detail::default_strategy< t_tuple< Arity > >::type, comparator< Arity - 2 >, InterpreterProvenanceUpdater< Arity > > >::insert().
{
         assert(arity == Arity);
         return *reinterpret_cast<const Tuple<RamDomain, Arity>*>(base);
     }
getBase()
const RamDomain* souffle::TupleRef::getBase () const inline
Definition at line 100 of file InterpreterIndex.h.
References base.
{
         return base;
     }
operator==()
bool souffle::TupleRef::operator== (const TupleRef & other) const inline
Definition at line 111 of file InterpreterIndex.h.
References arity, i, and souffle::operator<<().
{
         if (arity != other.arity) {
             return false;
         }
         for (size_t i = 0; i < arity; ++i) {
             if (base[i] != other[i]) {
                 return false;
             }
         }
         return true;
     }
operator[]()
const RamDomain& souffle::TupleRef::operator[] (std::size_t i) const inline
Provides access to tuple components.
Definition at line 107 of file InterpreterIndex.h.
References i.
{
         return base[i];
     }
size()
std::size_t souffle::TupleRef::size () const inline
Obtains the arity of the referenced tuple.
Definition at line 93 of file InterpreterIndex.h.
Referenced by souffle::NullaryIndex::contains(), souffle::NullaryIndex::insert(), and souffle::operator<<().
{
         return arity;
     }
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & out, TupleRef ref) friend
Definition at line 118 of file InterpreterIndex.cpp.
{
     out << "[";
     for (std::size_t i = 0; i < ref.size(); i++) {
         if (i > 0) {
             out << ',';
         }
         out << ref[i];
     }
     return out << "]";
 }
Field Documentation
arity
std::size_t souffle::TupleRef::arity = 0 private
Definition at line 65 of file InterpreterIndex.h.
Referenced by operator==().
base
const RamDomain* souffle::TupleRef::base = nullptr private
Definition at line 62 of file InterpreterIndex.h.
The documentation for this class was generated from the following file:
interpreter/InterpreterIndex.h