souffle: souffle::tuple Class Reference
souffle::tuple Class Reference
Defines a tuple for the OO interface such that relations with varying columns can be accessed.
#include <SouffleInterface.h>
Public Member Functions
decltype(array) ::iterator begin ()
Iterator for direct access to tuple's data.
const Relation & getRelation () const
Get the reference to the relation to which the tuple belongs.
tuple & operator<< (const std::string &str)
Set the "current element" of the tuple to the given string, then increment the index giving the current element.
tuple & operator<< (RamSigned integer)
Set the "current element" of the tuple to the given int, then increment the index giving the current element.
tuple & operator<< (RamUnsigned uint)
Set the "current element" of the tuple to the given uint, then increment the index giving the current element.
tuple & operator<< (RamFloat ramFloat)
Set the "current element" of the tuple to the given float, then increment the index giving the current element.
tuple & operator>> (std::string &str)
Get the "current element" of the tuple as a string, then increment the index giving the current element.
tuple & operator>> (RamSigned &integer)
Get the "current element" of the tuple as a int, then increment the index giving the current element.
tuple & operator>> (RamUnsigned &uint)
Get the "current element" of the tuple as a unsigned, then increment the index giving the current element.
tuple & operator>> (RamFloat &ramFloat)
Get the "current element" of the tuple as a float, then increment the index giving the current element.
RamDomain & operator[] (size_t idx)
Overload the operator [].
const RamDomain & operator[] (size_t idx) const
Overload the operator [].
void rewind ()
Reset the index giving the "current element" of the tuple to zero.
size_t size () const
Return the number of elements in the tuple.
tuple (const Relation *r)
Constructor.
tuple (const tuple &t)
Constructor.
tuple (const Relation *relation, std::initializer_list< RamDomain > tupleList)
Construct using initialisation list.
Data Fields
const RamDomain * data = nullptr
Allows printing using WriteStream.
Private Attributes
std::vector< RamDomain > array
Dynamic array used to store the elements in a tuple.
size_t pos
pos shows what the current position of a tuple is.
const Relation & relation
The relation to which the tuple belongs.
Detailed Description
Defines a tuple for the OO interface such that relations with varying columns can be accessed.
Tuples are stored in relations. In Souffle, one row of data to be stored into a relation is represented as a tuple. For example if we have a relation called dog with attributes name, colour and age which are string, string and interger type respectively. One row of data a relation to be stored can be (mydog, black, 3). However, this is not directly stored as a tuple. There will be a symbol table storing the actual content and associate them with numbers (For example, |1|mydog| |2|black| |3|3|). And when this row of data is stored as a tuple, (1, 2, 3) will be stored.
Definition at line 405 of file SouffleInterface.h.
Constructor & Destructor Documentation
tuple() [1/3]
souffle::tuple::tuple (const Relation * r) inline
Constructor.
Tuples are constructed here by passing a relation, then may be subsequently inserted into that same passed relation. The passed relation pointer will be stored within the tuple instance, while the arity of the relation will be used to initialize the vector holding the elements of the tuple. Where such an element is of integer type, it will be stored directly within the vector. Otherwise, if the element is of a string type, the index of that string within the associated symbol table will be stored instead. The tuple also stores the index of some "current" element, referred to as its position. The constructor initially sets this position to the first (zeroth) element of the tuple, while subsequent methods of this class use that position for element access and modification.
Parameters
r Relation pointer pointing to a relation
Definition at line 442 of file SouffleInterface.h.
 : relation(*r), array(r->getArity()), pos(0), data(array.data()) {}
tuple() [2/3]
souffle::tuple::tuple (const tuple & t) inline
Constructor.
Tuples are constructed here by passing a tuple. The relation to which the passed tuple belongs to will be stored. The array of the passed tuple, which stores the elements will be stroed. The pos will be set to be the same as the pos of passed tuple. belongs to.
Parameters
Reference to a tuple object.
Definition at line 455 of file SouffleInterface.h.
 : relation(t.relation), array(t.array), pos(t.pos), data(array.data()) {}
tuple() [3/3]
souffle::tuple::tuple (const Relation * relation, std::initializer_list< RamDomain > tupleList) inline
Construct using initialisation list.
Definition at line 645 of file SouffleInterface.h.
References souffle::Relation::getArity().
             : relation(*relation), array(tupleList), pos(tupleList.size()), data(array.data()) {
         assert(tupleList.size() == relation->getArity() && "tuple arity does not match relation arity");
     }
Member Function Documentation
begin()
decltype(array) ::iterator souffle::tuple::begin () inline
Iterator for direct access to tuple's data.
See also
Relation::iteraor::begin()
Definition at line 638 of file SouffleInterface.h.
{
         return array.begin();
     }
getRelation()
const Relation& souffle::tuple::getRelation () const inline
Get the reference to the relation to which the tuple belongs.
Returns
Reference to a relation.
Definition at line 467 of file SouffleInterface.h.
References relation.
Referenced by souffle::RelationWrapper< id, RelType, TupleType, Arity, NumAuxAttributes >::insert().
{
         return relation;
     }
operator<<() [1/4]
tuple& souffle::tuple::operator<< (const std::string & str) inline
Set the "current element" of the tuple to the given string, then increment the index giving the current element.
Parameters
str Symbol to be added (std::string)
Returns
Reference to the tuple
Definition at line 526 of file SouffleInterface.h.
References souffle::Relation::getAttrType(), souffle::Relation::getSymbolTable(), souffle::SymbolTable::lookup(), and souffle::Relation::size().
{
         assert(pos < size() && "exceeded tuple's size");
         assert(*relation.getAttrType(pos) == 's' && "wrong element type");
         array[pos++] = relation.getSymbolTable().lookup(str);
         return *this;
     }
operator<<() [2/4]
tuple& souffle::tuple::operator<< (RamSigned integer) inline
Set the "current element" of the tuple to the given int, then increment the index giving the current element.
Parameters
integer Integer to be added
Returns
Reference to the tuple
Definition at line 540 of file SouffleInterface.h.
References souffle::Relation::getAttrType(), and souffle::Relation::size().
{
         assert(pos < size() && "exceeded tuple's size");
         assert((*relation.getAttrType(pos) == 'i' || *relation.getAttrType(pos) == 'r') &&
                 "wrong element type");
         array[pos++] = integer;
         return *this;
     }
operator<<() [3/4]
tuple& souffle::tuple::operator<< (RamUnsigned uint) inline
Set the "current element" of the tuple to the given uint, then increment the index giving the current element.
Parameters
uint Unsigned number to be added
Returns
Reference to the tuple
Definition at line 555 of file SouffleInterface.h.
References souffle::Relation::getAttrType(), souffle::ramBitCast(), and souffle::Relation::size().
{
         assert(pos < size() && "exceeded tuple's size");
         assert((*relation.getAttrType(pos) == 'u') && "wrong element type");
         array[pos++] = ramBitCast(uint);
         return *this;
     }
operator<<() [4/4]
tuple& souffle::tuple::operator<< (RamFloat ramFloat) inline
Set the "current element" of the tuple to the given float, then increment the index giving the current element.
Parameters
float float to be added
Returns
Reference to the tuple
Definition at line 569 of file SouffleInterface.h.
References souffle::Relation::getAttrType(), souffle::ramBitCast(), and souffle::Relation::size().
{
         assert(pos < size() && "exceeded tuple's size");
         assert((*relation.getAttrType(pos) == 'f') && "wrong element type");
         array[pos++] = ramBitCast(ramFloat);
         return *this;
     }
operator>>() [1/4]
tuple& souffle::tuple::operator>> (std::string & str) inline
Get the "current element" of the tuple as a string, then increment the index giving the current element.
Parameters
str Symbol to be loaded from the tuple(std::string)
Returns
Reference to the tuple
Definition at line 583 of file SouffleInterface.h.
References souffle::Relation::getAttrType(), souffle::Relation::getSymbolTable(), souffle::SymbolTable::resolve(), and souffle::Relation::size().
{
         assert(pos < size() && "exceeded tuple's size");
         assert(*relation.getAttrType(pos) == 's' && "wrong element type");
         str = relation.getSymbolTable().resolve(array[pos++]);
         return *this;
     }
operator>>() [2/4]
tuple& souffle::tuple::operator>> (RamSigned & integer) inline
Get the "current element" of the tuple as a int, then increment the index giving the current element.
Parameters
integer Integer to be loaded from the tuple
Returns
Reference to the tuple
Definition at line 597 of file SouffleInterface.h.
References souffle::Relation::getAttrType(), and souffle::Relation::size().
{
         assert(pos < size() && "exceeded tuple's size");
         assert((*relation.getAttrType(pos) == 'i' || *relation.getAttrType(pos) == 'r') &&
                 "wrong element type");
         integer = ramBitCast<RamSigned>(array[pos++]);
         return *this;
     }
operator>>() [3/4]
tuple& souffle::tuple::operator>> (RamUnsigned & uint) inline
Get the "current element" of the tuple as a unsigned, then increment the index giving the current element.
Parameters
uint Unsigned number to be loaded from the tuple
Returns
Reference to the tuple
Definition at line 612 of file SouffleInterface.h.
References souffle::Relation::getAttrType(), and souffle::Relation::size().
{
         assert(pos < size() && "exceeded tuple's size");
         assert((*relation.getAttrType(pos) == 'u') && "wrong element type");
         uint = ramBitCast<RamUnsigned>(array[pos++]);
         return *this;
     }
operator>>() [4/4]
tuple& souffle::tuple::operator>> (RamFloat & ramFloat) inline
Get the "current element" of the tuple as a float, then increment the index giving the current element.
Parameters
ramFloat Float to be loaded from the tuple
Returns
Reference to the tuple
Definition at line 626 of file SouffleInterface.h.
References souffle::Relation::getAttrType(), and souffle::Relation::size().
{
         assert(pos < size() && "exceeded tuple's size");
         assert((*relation.getAttrType(pos) == 'f') && "wrong element type");
         ramFloat = ramBitCast<RamFloat>(array[pos++]);
         return *this;
     }
operator[]() [1/2]
RamDomain& souffle::tuple::operator[] (size_t idx) inline
Overload the operator [].
Direct access to tuple elements via index and return the element in idx position of a tuple.
TODO (Honghyw) : This interface should be hidden and only be used by friendly classes such as iterators; users should not use this interface.
Parameters
idx This is the idx of element in a tuple (size_t).
Definition at line 492 of file SouffleInterface.h.
{
         return array[idx];
     }
operator[]() [2/2]
const RamDomain& souffle::tuple::operator[] (size_t idx) const inline
Overload the operator [].
Direct access to tuple elements via index and Return the element in idx position of a tuple. The returned element can not be changed.
TODO (Honghyw) : This interface should be hidden and only be used by friendly classes such as iterators; users should not use this interface.
Parameters
idx This is the idx of element in a tuple (size_t).
Definition at line 508 of file SouffleInterface.h.
{
         return array[idx];
     }
rewind()
void souffle::tuple::rewind () inline
Reset the index giving the "current element" of the tuple to zero.
Definition at line 515 of file SouffleInterface.h.
Referenced by souffle::RelationWrapper< id, RelType, TupleType, Arity, NumAuxAttributes >::iterator_wrapper::operator*(), and souffle::InterpreterRelInterface::iterator_base::operator*().
                   {
         pos = 0;
     }
size()
size_t souffle::tuple::size () const inline
Return the number of elements in the tuple.
Returns
the number of elements in the tuple (size_t).
Definition at line 476 of file SouffleInterface.h.
Referenced by souffle::InterpreterRelInterface::contains(), souffle::RelationWrapper< id, RelType, TupleType, Arity, NumAuxAttributes >::contains(), and souffle::RelationWrapper< id, RelType, TupleType, Arity, NumAuxAttributes >::insert().
{
         return array.size();
     }
Field Documentation
array
std::vector<RamDomain> souffle::tuple::array private
Dynamic array used to store the elements in a tuple.
Definition at line 414 of file SouffleInterface.h.
data
const RamDomain* souffle::tuple::data = nullptr
Allows printing using WriteStream.
Definition at line 460 of file SouffleInterface.h.
Referenced by souffle::InterpreterRelInterface::contains(), souffle::InterpreterEngine::execute(), and souffle::InterpreterRelInterface::insert().
pos
size_t souffle::tuple::pos private
pos shows what the current position of a tuple is.
Initially, pos is 0 meaning we are at the head of the tuple. If we have an empty tuple and try to insert things, pos lets us know where to insert the element. After the element is inserted, pos will be incremented by 1. If we have a tuple with content, pos lets us know where to read the element. After we have read one element, pos will be incremented by 1. pos also helps to make sure we access an insert a tuple within the bound by making sure pos never exceeds the arity of the relation.
Definition at line 425 of file SouffleInterface.h.
relation
const Relation& souffle::tuple::relation private
The relation to which the tuple belongs.
Definition at line 409 of file SouffleInterface.h.
The documentation for this class was generated from the following file:
SouffleInterface.h