souffle: souffle::RamTupleOperation Class Reference
souffle::RamTupleOperation Class Reference abstract
Abstract class for relation searches and lookups.
#include <Operation.h>
Public Member Functions
RamTupleOperation * clone () const override=0
Create a clone (i.e.
std::vector< const RamNode * > getChildNodes () const override
Obtain list of all embedded child nodes.
int getTupleId () const
Get identifier.
RamTupleOperation (int ident, std::unique_ptr< RamOperation > nested, std::string profileText="")
void setTupleId (int id)
Set identifier.
Public Member Functions inherited from souffle::RamNestedOperation
void apply (const RamNodeMapper &map) override
Apply the mapper to all child nodes.
RamOperation & getOperation () const
Get nested operation.
const std::string & getProfileText () const
Get profile text.
RamNestedOperation (std::unique_ptr< RamOperation > nested, std::string profileText="")
Public Member Functions inherited from souffle::RamNode
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
virtual void rewrite (const RamNode *oldNode, std::unique_ptr< RamNode > newNode)
Rewrite a child node.
virtual ~RamNode ()=default
Protected Member Functions
bool equal (const RamNode &node) const override
Equality check for two RAM nodes.
Protected Member Functions inherited from souffle::RamNestedOperation
void print (std::ostream &os, int tabpos) const override
Pretty print with indentation.
Protected Member Functions inherited from souffle::RamOperation
void print (std::ostream &os) const override
Print RAM node.
Protected Attributes
int identifier
Identifier for the tuple, corresponding to its position in the loop nest.
Protected Attributes inherited from souffle::RamNestedOperation
std::unique_ptr< RamOperation > nestedOperation
Nested operation.
const std::string profileText
Text used by the profiler.
Additional Inherited Members
Static Protected Member Functions inherited from souffle::RamOperation
static void print (const RamOperation *operation, std::ostream &os, int tabpos)
Pretty print jump-bed.
Detailed Description
Abstract class for relation searches and lookups.
Definition at line 138 of file Operation.h.
Constructor & Destructor Documentation
RamTupleOperation()
souffle::RamTupleOperation::RamTupleOperation (int ident, std::unique_ptr< RamOperation > nested, std::string profileText = "") inline
Definition at line 140 of file Operation.h.
References souffle::RamOperation::clone().
             : RamNestedOperation(std::move(nested), std::move(profileText)), identifier(ident) {}
Member Function Documentation
clone()
RamTupleOperation* souffle::RamTupleOperation::clone () const override pure virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::RamNestedOperation.
Implemented in souffle::RamUnpackRecord, souffle::RamNestedIntrinsicOperator, souffle::RamParallelIndexAggregate, souffle::RamIndexAggregate, souffle::RamParallelAggregate, souffle::RamAggregate, souffle::RamParallelIndexChoice, souffle::RamIndexChoice, souffle::RamParallelChoice, souffle::RamChoice, souffle::RamParallelIndexScan, souffle::RamIndexScan, souffle::RamIndexOperation, souffle::RamParallelScan, souffle::RamScan, and souffle::RamRelationOperation.
equal()
bool souffle::RamTupleOperation::equal (const RamNode &) const inline override protected virtual
Equality check for two RAM nodes.
Default action is that nothing needs to be checked.
Reimplemented from souffle::RamNestedOperation.
Reimplemented in souffle::RamUnpackRecord, souffle::RamNestedIntrinsicOperator, souffle::RamIndexAggregate, souffle::RamAggregate, souffle::RamIndexChoice, souffle::RamChoice, souffle::RamIndexOperation, and souffle::RamRelationOperation.
Definition at line 160 of file Operation.h.
References souffle::RamNestedOperation::equal(), and souffle::identifier().
Referenced by souffle::RamRelationOperation::equal(), souffle::RamNestedIntrinsicOperator::equal(), and souffle::RamUnpackRecord::equal().
{
         const auto& other = static_cast<const RamTupleOperation&>(node);
         return RamNestedOperation::equal(other) && identifier == other.identifier;
     }
getChildNodes()
std::vector<const RamNode*> souffle::RamTupleOperation::getChildNodes () const inline override virtual
Obtain list of all embedded child nodes.
Reimplemented from souffle::RamNestedOperation.
Reimplemented in souffle::RamUnpackRecord, souffle::RamNestedIntrinsicOperator, souffle::RamIndexAggregate, souffle::RamAggregate, souffle::RamIndexChoice, souffle::RamChoice, souffle::RamIndexOperation, and souffle::RamRelationOperation.
Definition at line 155 of file Operation.h.
References souffle::RamNestedOperation::getChildNodes().
Referenced by souffle::RamRelationOperation::getChildNodes(), souffle::RamNestedIntrinsicOperator::getChildNodes(), and souffle::RamUnpackRecord::getChildNodes().
{
         return RamNestedOperation::getChildNodes();
     }
getTupleId()
int souffle::RamTupleOperation::getTupleId () const inline
Get identifier.
Definition at line 146 of file Operation.h.
References souffle::identifier().
Referenced by souffle::Synthesiser::emitCode(), souffle::HoistConditionsTransformer::hoistConditions(), souffle::TupleIdTransformer::reorderOperations(), souffle::MakeIndexTransformer::rewriteAggregate(), souffle::IfConversionTransformer::rewriteIndexScan(), souffle::ChoiceConversionTransformer::rewriteIndexScan(), souffle::MakeIndexTransformer::rewriteIndexScan(), souffle::ChoiceConversionTransformer::rewriteScan(), and souffle::MakeIndexTransformer::rewriteScan().
{
         return identifier;
     }
setTupleId()
void souffle::RamTupleOperation::setTupleId (int id) inline
Set identifier.
Definition at line 151 of file Operation.h.
References souffle::identifier().
{
         identifier = id;
     }
Field Documentation
identifier
int souffle::RamTupleOperation::identifier protected
Identifier for the tuple, corresponding to its position in the loop nest.
Definition at line 169 of file Operation.h.
The documentation for this class was generated from the following file:
ram/Operation.h