souffle: souffle::ProgramFactory Class Reference
souffle::ProgramFactory Class Reference abstract
Abstract program factory class.
#include <SouffleInterface.h>
Public Member Functions
virtual ~ProgramFactory ()=default
Destructor.
Static Public Member Functions
static SouffleProgram * newInstance (const std::string &name)
Create an instance by finding the name of the program factory, return nullptr if the instance not found.
Protected Member Functions
virtual SouffleProgram * newInstance ()=0
Create new instance (abstract).
ProgramFactory (std::string name)
Constructor.
Static Protected Member Functions
static ProgramFactory * find (const std::string &factoryName)
Find a factory by its name, return the fatory if found, return nullptr if the factory not found.
static void registerFactory (ProgramFactory *factory)
Create and insert a factory into the factoryReg map.
Protected Attributes
ProgramFactory * link = nullptr
Singly linked-list to store all program factories Note that STL data-structures are not possible due to "static initialization order fiasco (problem)".
std::string name
The name of factory.
Static Private Member Functions
static std::map< std::string, ProgramFactory * > & getFactoryRegistry ()
Helper method for creating a factory map, which map key is the name of the program factory, map value is the pointer of the ProgramFactory.
Detailed Description
Abstract program factory class.
Definition at line 956 of file SouffleInterface.h.
Constructor & Destructor Documentation
ProgramFactory()
souffle::ProgramFactory::ProgramFactory (std::string name) inline protected
Constructor.
Constructor adds factory to static singly-linked list for registration.
Definition at line 982 of file SouffleInterface.h.
                                    : name(std::move(name)) {
         registerFactory(this);
     }
~ProgramFactory()
virtual souffle::ProgramFactory::~ProgramFactory () virtual default
Destructor.
Destructor of ProgramFactory.
Member Function Documentation
find()
static ProgramFactory* souffle::ProgramFactory::find (const std::string & factoryName) inline static protected
Find a factory by its name, return the fatory if found, return nullptr if the factory not found.
Parameters
factoryName The factory name (const std::string)
Returns
The pointer of the target program factory, or null pointer if the program factory not found (ProgramFactory*)
Definition at line 1021 of file SouffleInterface.h.
{
         const auto& reg = getFactoryRegistry();
         auto pos = reg.find(factoryName);
         return (pos == reg.end()) ? nullptr : pos->second;
     }
getFactoryRegistry()
static std::map<std::string, ProgramFactory*>& souffle::ProgramFactory::getFactoryRegistry () inline static private
Helper method for creating a factory map, which map key is the name of the program factory, map value is the pointer of the ProgramFactory.
TODO (NubKel) : Improve documentation of use and interaction between inline and static, here and for the whole class.
Returns
The factory registration map (std::map)
Definition at line 996 of file SouffleInterface.h.
{
         static std::map<std::string, ProgramFactory*> factoryReg;
         return factoryReg;
     }
newInstance() [1/2]
virtual SouffleProgram* souffle::ProgramFactory::newInstance () protected pure virtual
Create new instance (abstract).
Referenced by souffle::getInstance(), newInstance(), and newInstance().
newInstance() [2/2]
static SouffleProgram* souffle::ProgramFactory::newInstance (const std::string & name) inline static
Create an instance by finding the name of the program factory, return nullptr if the instance not found.
Parameters
name Instance name (const std::string)
Returns
The new instance(SouffleProgram*), or null pointer if the instance not found
Definition at line 1047 of file SouffleInterface.h.
References newInstance().
{
         ProgramFactory* factory = find(name);
         if (factory != nullptr) {
             return factory->newInstance();
         } else {
             return nullptr;
         }
     }
registerFactory()
static void souffle::ProgramFactory::registerFactory (ProgramFactory * factory) inline static protected
Create and insert a factory into the factoryReg map.
Parameters
factory Pointer of the program factory (ProgramFactory*)
Definition at line 1007 of file SouffleInterface.h.
References name.
{
         auto& entry = getFactoryRegistry()[factory->name];
         assert(!entry && "double-linked/defined souffle analyis");
         entry = factory;
     }
Field Documentation
link
ProgramFactory* souffle::ProgramFactory::link = nullptr protected
Singly linked-list to store all program factories Note that STL data-structures are not possible due to "static initialization order fiasco (problem)".
(The problem of the order static objects get initialized, causing effect such as program access static variables before they initialized.) The static container needs to be a primitive type such as pointer set to NULL. Link to next factory.
Definition at line 968 of file SouffleInterface.h.
name
std::string souffle::ProgramFactory::name protected
The name of factory.
Definition at line 973 of file SouffleInterface.h.
Referenced by registerFactory().
The documentation for this class was generated from the following file:
SouffleInterface.h