souffle: souffle::RamLogSize Class Reference
souffle::RamLogSize Class Reference
Log relation size and a logging message.
#include <Statement.h>
Public Member Functions
RamLogSize * clone () const override
Create a clone (i.e.
const std::string & getMessage () const
Get logging message.
RamLogSize (std::unique_ptr< RamRelationReference > relRef, std::string message)
Public Member Functions inherited from souffle::RamRelationStatement
void apply (const RamNodeMapper &map) override
Apply the mapper to all child nodes.
std::vector< const RamNode * > getChildNodes () const override
Obtain list of all embedded child nodes.
const RamRelation & getRelation () const
Get RAM relation.
RamRelationStatement (std::unique_ptr< RamRelationReference > relRef)
Public Member Functions inherited from souffle::RamNode
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
virtual void rewrite (const RamNode *oldNode, std::unique_ptr< RamNode > newNode)
Rewrite a child node.
virtual ~RamNode ()=default
Protected Member Functions
bool equal (const RamNode &node) const override
Equality check for two RAM nodes.
void print (std::ostream &os, int tabpos) const override
Pretty print with indentation.
Protected Member Functions inherited from souffle::RamStatement
void print (std::ostream &os) const override
Print RAM node.
Protected Attributes
std::string message
logging message
Protected Attributes inherited from souffle::RamRelationStatement
std::unique_ptr< RamRelationReference > relationRef
Relation reference.
Additional Inherited Members
Static Protected Member Functions inherited from souffle::RamStatement
static void print (const RamStatement *statement, std::ostream &os, int tabpos)
Pretty print jump-bed.
Detailed Description
Log relation size and a logging message.
Definition at line 743 of file Statement.h.
Constructor & Destructor Documentation
RamLogSize()
souffle::RamLogSize::RamLogSize (std::unique_ptr< RamRelationReference > relRef, std::string message) inline
Definition at line 745 of file Statement.h.
             : RamRelationStatement(std::move(relRef)), message(std::move(message)) {}
Member Function Documentation
clone()
RamLogSize* souffle::RamLogSize::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::RamStatement.
Definition at line 753 of file Statement.h.
References souffle::clone().
Referenced by souffle::test::TEST().
{
         return new RamLogSize(souffle::clone(relationRef), message);
     }
equal()
bool souffle::RamLogSize::equal (const RamNode &) const inline override protected virtual
Equality check for two RAM nodes.
Default action is that nothing needs to be checked.
Reimplemented from souffle::RamRelationStatement.
Definition at line 765 of file Statement.h.
References souffle::RamRelationStatement::equal().
{
         const auto& other = static_cast<const RamLogSize&>(node);
         return RamRelationStatement::equal(other) && message == other.message;
     }
getMessage()
const std::string& souffle::RamLogSize::getMessage () const inline
Get logging message.
Definition at line 749 of file Statement.h.
Referenced by souffle::Synthesiser::emitCode().
{
         return message;
     }
print()
void souffle::RamLogSize::print (std::ostream & os, int tabpos) const inline override protected virtual
Pretty print with indentation.
Implements souffle::RamStatement.
Definition at line 758 of file Statement.h.
References souffle::getRelation(), souffle::stringify(), and souffle::times().
{
         os << times(" ", tabpos) << "LOGSIZE " << getRelation().getName();
         os << " TEXT "
            << "\"" << stringify(message) << "\"";
         os << std::endl;
     }
Field Documentation
message
std::string souffle::RamLogSize::message protected
logging message
Definition at line 771 of file Statement.h.
The documentation for this class was generated from the following file:
ram/Statement.h