souffle: souffle::RamNestedIntrinsicOperator Class Reference
souffle::RamNestedIntrinsicOperator Class Reference
Effectively identical to RamIntrinsicOperator, except it can produce multiple results.
#include <Operation.h>
Public Member Functions
void apply (const RamNodeMapper &map) override
Apply the mapper to all child nodes.
RamNestedIntrinsicOperator * clone () const override
Create a clone (i.e.
std::vector< RamExpression * > getArguments () const
std::vector< const RamNode * > getChildNodes () const override
Obtain list of all embedded child nodes.
RamNestedIntrinsicOp getFunction () const
RamNestedIntrinsicOperator (RamNestedIntrinsicOp op, std::vector< std::unique_ptr< RamExpression >> args, std::unique_ptr< RamOperation > nested, int ident)
Public Member Functions inherited from souffle::RamTupleOperation
int getTupleId () const
Get identifier.
RamTupleOperation (int ident, std::unique_ptr< RamOperation > nested, std::string profileText="")
void setTupleId (int id)
Set identifier.
Public Member Functions inherited from souffle::RamNestedOperation
RamOperation & getOperation () const
Get nested operation.
const std::string & getProfileText () const
Get profile text.
RamNestedOperation (std::unique_ptr< RamOperation > nested, std::string profileText="")
Public Member Functions inherited from souffle::RamNode
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
virtual void rewrite (const RamNode *oldNode, std::unique_ptr< RamNode > newNode)
Rewrite a child node.
virtual ~RamNode ()=default
Protected Member Functions
bool equal (const RamNode &node) const override
Equality check for two RAM nodes.
void print (std::ostream &os, int tabpos) const override
Pretty print with indentation.
Protected Member Functions inherited from souffle::RamOperation
void print (std::ostream &os) const override
Print RAM node.
Protected Attributes
std::vector< std::unique_ptr< RamExpression > > args
RamNestedIntrinsicOp op
Protected Attributes inherited from souffle::RamTupleOperation
int identifier
Identifier for the tuple, corresponding to its position in the loop nest.
Protected Attributes inherited from souffle::RamNestedOperation
std::unique_ptr< RamOperation > nestedOperation
Nested operation.
const std::string profileText
Text used by the profiler.
Additional Inherited Members
Static Protected Member Functions inherited from souffle::RamOperation
static void print (const RamOperation *operation, std::ostream &os, int tabpos)
Pretty print jump-bed.
Detailed Description
Effectively identical to RamIntrinsicOperator, except it can produce multiple results.
For example:
RANGE(t0.0, t0.1, t0.2) INTO t1
Definition at line 1036 of file Operation.h.
Constructor & Destructor Documentation
RamNestedIntrinsicOperator()
souffle::RamNestedIntrinsicOperator::RamNestedIntrinsicOperator (RamNestedIntrinsicOp op, std::vector< std::unique_ptr< RamExpression >> args, std::unique_ptr< RamOperation > nested, int ident) inline
Definition at line 1038 of file Operation.h.
             : RamTupleOperation(ident, std::move(nested)), args(std::move(args)), op(op) {}
Member Function Documentation
apply()
void souffle::RamNestedIntrinsicOperator::apply (const RamNodeMapper &) inline override virtual
Apply the mapper to all child nodes.
Reimplemented from souffle::RamNestedOperation.
Definition at line 1063 of file Operation.h.
References souffle::RamNestedOperation::apply(), and souffle::map().
{
         RamTupleOperation::apply(map);
         for (auto&& x : args) {
             x = map(std::move(x));
         }
     }
clone()
RamNestedIntrinsicOperator* souffle::RamNestedIntrinsicOperator::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::RamTupleOperation.
Definition at line 1058 of file Operation.h.
References souffle::clone().
{
         return new RamNestedIntrinsicOperator(
                 op, souffle::clone(args), souffle::clone(&getOperation()), getTupleId());
     }
equal()
bool souffle::RamNestedIntrinsicOperator::equal (const RamNode &) const inline override protected virtual
Equality check for two RAM nodes.
Default action is that nothing needs to be checked.
Reimplemented from souffle::RamTupleOperation.
Definition at line 1078 of file Operation.h.
References souffle::RamTupleOperation::equal(), and souffle::equal_targets().
{
         auto&& other = static_cast<const RamNestedIntrinsicOperator&>(node);
         return RamTupleOperation::equal(node) && op == other.op && equal_targets(args, other.args);
     }
getArguments()
std::vector<RamExpression*> souffle::RamNestedIntrinsicOperator::getArguments () const inline
Definition at line 1046 of file Operation.h.
References souffle::toPtrVector().
Referenced by souffle::Synthesiser::emitCode(), and souffle::NodeGenerator::visitNestedIntrinsicOperator().
{
         return toPtrVector(args);
     }
getChildNodes()
std::vector<const RamNode*> souffle::RamNestedIntrinsicOperator::getChildNodes () const inline override virtual
Obtain list of all embedded child nodes.
Reimplemented from souffle::RamTupleOperation.
Definition at line 1050 of file Operation.h.
References souffle::RamTupleOperation::getChildNodes().
{
         auto res = RamTupleOperation::getChildNodes();
         for (auto&& x : args) {
             res.push_back(x.get());
         }
         return res;
     }
getFunction()
RamNestedIntrinsicOp souffle::RamNestedIntrinsicOperator::getFunction () const inline
Definition at line 1042 of file Operation.h.
Referenced by souffle::Synthesiser::emitCode().
{
         return op;
     }
print()
void souffle::RamNestedIntrinsicOperator::print (std::ostream & os, int tabpos) const inline override protected virtual
Pretty print with indentation.
Reimplemented from souffle::RamNestedOperation.
Definition at line 1071 of file Operation.h.
References souffle::join(), souffle::RamNestedOperation::print(), and souffle::times().
{
         os << times(" ", tabpos);
         os << op << "(" << join(args, ",", print_deref<std::unique_ptr<RamExpression>>()) << ") INTO t"
            << getTupleId() << "\n";
         RamNestedOperation::print(os, tabpos + 1);
     }
Field Documentation
args
std::vector<std::unique_ptr<RamExpression> > souffle::RamNestedIntrinsicOperator::args protected
Definition at line 1083 of file Operation.h.
op
RamNestedIntrinsicOp souffle::RamNestedIntrinsicOperator::op protected
Definition at line 1084 of file Operation.h.
The documentation for this class was generated from the following file:
ram/Operation.h