souffle: souffle::profile::ProgramResourceUtilisationProcessor Class Reference
souffle::profile::ProgramResourceUtilisationProcessor Class Reference
Program Resource Utilisation Event Processor.
#include <EventProcessor.h>
Public Member Functions
void process (ProfileDatabase &db, const std::vector< std::string > &, va_list &args) override
process event input
ProgramResourceUtilisationProcessor ()
Public Member Functions inherited from souffle::profile::EventProcessor
virtual ~EventProcessor ()=default
Detailed Description
Program Resource Utilisation Event Processor.
Definition at line 464 of file EventProcessor.h.
Constructor & Destructor Documentation
ProgramResourceUtilisationProcessor()
souffle::profile::ProgramResourceUtilisationProcessor::ProgramResourceUtilisationProcessor () inline
Definition at line 466 of file EventProcessor.h.
References souffle::profile::EventProcessorSingleton::instance(), and souffle::profile::EventProcessorSingleton::registerEventProcessor().
{
         EventProcessorSingleton::instance().registerEventProcessor("@utilisation", this);
     }
Member Function Documentation
process()
void souffle::profile::ProgramResourceUtilisationProcessor::process (ProfileDatabase & db, const std::vector< std::string > & , va_list & args) inline override virtual
process event input
Reimplemented from souffle::profile::EventProcessor.
Definition at line 470 of file EventProcessor.h.
References souffle::profile::programResourceUtilisationProcessor, and souffle::test::time().
{
         microseconds time = va_arg(args, microseconds);
         uint64_t systemTime = va_arg(args, uint64_t);
         uint64_t userTime = va_arg(args, uint64_t);
         size_t maxRSS = va_arg(args, size_t);
         std::string timeString = std::to_string(time.count());
         db.addSizeEntry({"program", "usage", "timepoint", timeString, "systemtime"}, systemTime);
         db.addSizeEntry({"program", "usage", "timepoint", timeString, "usertime"}, userTime);
         db.addSizeEntry({"program", "usage", "timepoint", timeString, "maxRSS"}, maxRSS);
     }
The documentation for this class was generated from the following file:
EventProcessor.h