souffle: souffle::DiagnosticMessage Class Reference
souffle::DiagnosticMessage Class Reference
#include <ErrorReport.h>
Public Member Functions
DiagnosticMessage (std::string message, SrcLocation location)
DiagnosticMessage (std::string message)
const SrcLocation & getLocation () const
const std::string & getMessage () const
bool hasLocation () const
void print (std::ostream &out) const
Private Attributes
bool hasLoc
SrcLocation location
std::string message
Friends
std::ostream & operator<< (std::ostream &out, const DiagnosticMessage &diagnosticMessage)
Detailed Description
Definition at line 30 of file ErrorReport.h.
Constructor & Destructor Documentation
DiagnosticMessage() [1/2]
souffle::DiagnosticMessage::DiagnosticMessage (std::string message, SrcLocation location) inline
Definition at line 32 of file ErrorReport.h.
Referenced by souffle::ErrorReport::addError(), and souffle::ErrorReport::addWarning().
             : message(std::move(message)), hasLoc(true), location(std::move(location)) {}
DiagnosticMessage() [2/2]
souffle::DiagnosticMessage::DiagnosticMessage (std::string message) inline
Definition at line 35 of file ErrorReport.h.
 : message(std::move(message)), hasLoc(false) {}
Member Function Documentation
getLocation()
const SrcLocation& souffle::DiagnosticMessage::getLocation () const inline
Definition at line 41 of file ErrorReport.h.
References hasLoc, and location.
Referenced by souffle::Diagnostic::operator<().
{
         assert(hasLoc);
         return location;
     }
getMessage()
const std::string& souffle::DiagnosticMessage::getMessage () const inline
Definition at line 37 of file ErrorReport.h.
References message.
Referenced by souffle::Diagnostic::operator<().
{
         return message;
     }
hasLocation()
bool souffle::DiagnosticMessage::hasLocation () const inline
Definition at line 46 of file ErrorReport.h.
References hasLoc.
Referenced by souffle::Diagnostic::operator<().
{
         return hasLoc;
     }
print()
void souffle::DiagnosticMessage::print (std::ostream & out) const inline
Definition at line 50 of file ErrorReport.h.
References souffle::SrcLocation::extloc(), hasLoc, location, and message.
{
         out << message;
         if (hasLoc) {
             out << " in " << location.extloc();
         }
         out << "\n";
     }
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & out, const DiagnosticMessage & diagnosticMessage) friend
Definition at line 58 of file ErrorReport.h.
{
         diagnosticMessage.print(out);
         return out;
     }
Field Documentation
hasLoc
bool souffle::DiagnosticMessage::hasLoc private
Definition at line 65 of file ErrorReport.h.
Referenced by getLocation(), hasLocation(), and print().
location
SrcLocation souffle::DiagnosticMessage::location private
Definition at line 66 of file ErrorReport.h.
Referenced by getLocation(), and print().
message
std::string souffle::DiagnosticMessage::message private
Definition at line 64 of file ErrorReport.h.
Referenced by getMessage(), and print().
The documentation for this class was generated from the following file:
ErrorReport.h