souffle: souffle::PipelineTransformer Class Reference
souffle::PipelineTransformer Class Reference
Transformer that holds an arbitrary number of sub-transformations.
#include <Pipeline.h>
Public Member Functions
PipelineTransformer * clone () const override
void disableTransformers (const std::set< std::string > &transforms) override
std::string getName () const override
std::vector< AstTransformer * > getSubtransformers () const override
template<typename... Args>
PipelineTransformer (Args... args)
PipelineTransformer (std::vector< std::unique_ptr< AstTransformer >> pipeline)
void setDebugReport () override
void setVerbosity (bool verbose) override
Public Member Functions inherited from souffle::MetaTransformer
bool applySubtransformer (AstTranslationUnit &translationUnit, AstTransformer *transformer)
Public Member Functions inherited from souffle::AstTransformer
bool apply (AstTranslationUnit &translationUnit)
virtual ~AstTransformer ()=default
Private Member Functions
bool transform (AstTranslationUnit &translationUnit) override
Private Attributes
std::vector< std::unique_ptr< AstTransformer > > pipeline
Additional Inherited Members
Protected Attributes inherited from souffle::MetaTransformer
bool verbose = false
Detailed Description
Transformer that holds an arbitrary number of sub-transformations.
Definition at line 36 of file Pipeline.h.
Constructor & Destructor Documentation
PipelineTransformer() [1/2]
template<typename... Args> souffle::PipelineTransformer::PipelineTransformer (Args... args) inline
Definition at line 39 of file Pipeline.h.
References pipeline.
Referenced by clone().
{
         std::unique_ptr<AstTransformer> tmp[] = {std::move(args)...};
         for (auto& cur : tmp) {
             pipeline.push_back(std::move(cur));
         }
     }
PipelineTransformer() [2/2]
souffle::PipelineTransformer::PipelineTransformer (std::vector< std::unique_ptr< AstTransformer >> pipeline) inline
Definition at line 46 of file Pipeline.h.
             : pipeline(std::move(pipeline)) {}
Member Function Documentation
clone()
PipelineTransformer* souffle::PipelineTransformer::clone () const inline override virtual
Implements souffle::MetaTransformer.
Definition at line 86 of file Pipeline.h.
References souffle::clone(), pipeline, and PipelineTransformer().
{
         std::vector<std::unique_ptr<AstTransformer>> transformers;
         for (const auto& transformer : pipeline) {
             transformers.push_back(souffle::clone(transformer));
         }
         return new PipelineTransformer(std::move(transformers));
     }
disableTransformers()
void souffle::PipelineTransformer::disableTransformers (const std::set< std::string > & transforms) inline override virtual
Implements souffle::MetaTransformer.
Definition at line 72 of file Pipeline.h.
References i, and pipeline.
{
         for (auto& i : pipeline) {
             if (auto* mt = dynamic_cast<MetaTransformer*>(i.get())) {
                 mt->disableTransformers(transforms);
             } else if (transforms.find(i->getName()) != transforms.end()) {
                 i = std::make_unique<NullTransformer>();
             }
         }
     }
getName()
std::string souffle::PipelineTransformer::getName () const inline override virtual
Implements souffle::AstTransformer.
Definition at line 82 of file Pipeline.h.
{
         return "PipelineTransformer";
     }
getSubtransformers()
std::vector<AstTransformer*> souffle::PipelineTransformer::getSubtransformers () const inline override virtual
Implements souffle::MetaTransformer.
Definition at line 49 of file Pipeline.h.
References pipeline, and souffle::toPtrVector().
{
         return toPtrVector(pipeline);
     }
setDebugReport()
void souffle::PipelineTransformer::setDebugReport () inline override virtual
Implements souffle::MetaTransformer.
Definition at line 53 of file Pipeline.h.
References i, and pipeline.
{
         for (auto& i : pipeline) {
             if (auto* mt = dynamic_cast<MetaTransformer*>(i.get())) {
                 mt->setDebugReport();
             } else {
                 i = std::make_unique<DebugReporter>(std::move(i));
             }
         }
     }
setVerbosity()
void souffle::PipelineTransformer::setVerbosity (bool verbose) inline override virtual
Implements souffle::MetaTransformer.
Definition at line 63 of file Pipeline.h.
References pipeline, and souffle::MetaTransformer::verbose.
{
         this->verbose = verbose;
         for (auto& cur : pipeline) {
             if (auto* mt = dynamic_cast<MetaTransformer*>(cur.get())) {
                 mt->setVerbosity(verbose);
             }
         }
     }
transform()
bool souffle::PipelineTransformer::transform (AstTranslationUnit & translationUnit) inline override private virtual
Implements souffle::AstTransformer.
Definition at line 96 of file Pipeline.h.
References souffle::MetaTransformer::applySubtransformer().
{
         bool changed = false;
         for (auto& transformer : pipeline) {
             changed |= applySubtransformer(translationUnit, transformer.get());
         }
         return changed;
     }
Field Documentation
pipeline
std::vector<std::unique_ptr<AstTransformer> > souffle::PipelineTransformer::pipeline private
Definition at line 95 of file Pipeline.h.
Referenced by clone(), disableTransformers(), getSubtransformers(), PipelineTransformer(), setDebugReport(), and setVerbosity().
The documentation for this class was generated from the following file:
ast/transform/Pipeline.h