souffle: souffle::MaterializeSingletonAggregationTransformer Class Reference
souffle::MaterializeSingletonAggregationTransformer Class Reference
Replaces literals containing single-valued aggregates with a synthesised relation.
#include <MaterializeSingletonAggregation.h>
Public Member Functions
MaterializeSingletonAggregationTransformer * clone () const override
std::string getName () const override
Public Member Functions inherited from souffle::AstTransformer
bool apply (AstTranslationUnit &translationUnit)
virtual ~AstTransformer ()=default
Private Member Functions
bool transform (AstTranslationUnit &translationUnit) override
Static Private Member Functions
static std::string findUniqueAggregateRelationName (const AstProgram &program)
findUniqueAggregateRelationName returns a synthesised aggregate relation name that hasn't appeared in the given clause.
static std::string findUniqueVariableName (const AstClause &clause)
findUniqueVariableName returns a variable name that hasn't appeared in the given clause.
static bool isSingleValued (const AstAggregator &agg, const AstClause &clause)
Determines whether an aggregate is single-valued, ie the aggregate does not depend on the outer scope.
Detailed Description
Replaces literals containing single-valued aggregates with a synthesised relation.
Definition at line 34 of file MaterializeSingletonAggregation.h.
Member Function Documentation
clone()
MaterializeSingletonAggregationTransformer* souffle::MaterializeSingletonAggregationTransformer::clone () const inline override virtual
Implements souffle::AstTransformer.
Definition at line 40 of file MaterializeSingletonAggregation.h.
References findUniqueAggregateRelationName(), findUniqueVariableName(), isSingleValued(), and transform().
{
         return new MaterializeSingletonAggregationTransformer();
     }
findUniqueAggregateRelationName()
std::string souffle::MaterializeSingletonAggregationTransformer::findUniqueAggregateRelationName (const AstProgram & program) static private
findUniqueAggregateRelationName returns a synthesised aggregate relation name that hasn't appeared in the given clause.
Definition at line 55 of file MaterializeSingletonAggregation.cpp.
References souffle::getRelation(), and souffle::toString().
Referenced by clone(), and transform().
{
     static int counter = 0;
     auto candidate = "__agg_rel_" + toString(counter++);
     while (getRelation(program, candidate) != nullptr) {
         candidate = "__agg_rel_" + toString(counter++);
     }
     return candidate;
 }
findUniqueVariableName()
std::string souffle::MaterializeSingletonAggregationTransformer::findUniqueVariableName (const AstClause & clause) static private
findUniqueVariableName returns a variable name that hasn't appeared in the given clause.
Definition at line 44 of file MaterializeSingletonAggregation.cpp.
References souffle::AstVariable::getName(), souffle::toString(), and souffle::visitDepthFirst().
Referenced by clone(), and transform().
{
     static int counter = 0;
     std::set<std::string> variableNames;
     visitDepthFirst(clause, [&](const AstVariable& variable) { variableNames.insert(variable.getName()); });
     std::string candidateVariableName = "z";  // completely arbitrary
     while (variableNames.find(candidateVariableName) != variableNames.end()) {
         candidateVariableName = "z" + toString(counter++);
     }
     return candidateVariableName;
 }
getName()
std::string souffle::MaterializeSingletonAggregationTransformer::getName () const inline override virtual
Implements souffle::AstTransformer.
Definition at line 36 of file MaterializeSingletonAggregation.h.
{
         return "MaterializeSingletonAggregationTransformer";
     }
isSingleValued()
bool souffle::MaterializeSingletonAggregationTransformer::isSingleValued (const AstAggregator & agg, const AstClause & clause) static private
Determines whether an aggregate is single-valued, ie the aggregate does not depend on the outer scope.
Definition at line 142 of file MaterializeSingletonAggregation.cpp.
References souffle::AstVariable::getName(), and souffle::visitDepthFirst().
Referenced by clone(), and transform().
{
     std::map<std::string, int> occurrences;
     visitDepthFirst(clause, [&](const AstVariable& v) {
         if (occurrences.find(v.getName()) == occurrences.end()) {
             occurrences[v.getName()] = 0;
         }
         occurrences[v.getName()] = occurrences[v.getName()] + 1;
     });
     std::set<std::string> aggVariables;
     visitDepthFirst(agg, [&](const AstVariable& v) {
         aggVariables.insert(v.getName());
         occurrences[v.getName()] = occurrences[v.getName()] - 1;
     });
     for (std::string variableName : aggVariables) {
         if (occurrences[variableName] != 0) {
             return false;
         }
     }
     return true;
 }
transform()
bool souffle::MaterializeSingletonAggregationTransformer::transform (AstTranslationUnit & translationUnit) override private virtual
Implements souffle::AstTransformer.
Definition at line 65 of file MaterializeSingletonAggregation.cpp.
References souffle::AstProgram::addClause(), souffle::AstProgram::addRelation(), souffle::AstClause::addToBody(), souffle::AstClause::apply(), souffle::clone(), souffle::EQ, findUniqueAggregateRelationName(), findUniqueVariableName(), souffle::AstClause::getBodyLiterals(), souffle::AstTranslationUnit::getProgram(), isSingleValued(), and souffle::visitDepthFirst().
Referenced by clone().
{
     AstProgram& program = *translationUnit.getProgram();
     std::set<std::pair<AstAggregator*, AstClause*>> pairs;
     // collect references to clause / aggregate pairs
     visitDepthFirst(program, [&](const AstClause& clause) {
         visitDepthFirst(clause, [&](const AstAggregator& agg) {
             // if the aggregate isn't single valued
             // (ie it relies on a grounding from the outer scope)
             // or it's the only atom in the clause, then there's no point materialising it!
             if (!isSingleValued(agg, clause) || clause.getBodyLiterals().size() == 1) {
                 return;
             }
             auto* foundAggregate = const_cast<AstAggregator*>(&agg);
             auto* foundClause = const_cast<AstClause*>(&clause);
             pairs.insert(std::make_pair(foundAggregate, foundClause));
         });
     });
     for (auto pair : pairs) {
         // Clone the aggregate that we're going to be deleting.
         auto aggregate = souffle::clone(pair.first);
         AstClause* clause = pair.second;
         // synthesise an aggregate relation
         // __agg_rel_0()
         auto aggRel = std::make_unique<AstRelation>();
         auto aggHead = std::make_unique<AstAtom>();
         auto aggClause = std::make_unique<AstClause>();
         std::string aggRelName = findUniqueAggregateRelationName(program);
         aggRel->setQualifiedName(aggRelName);
         aggHead->setQualifiedName(aggRelName);
         // create a synthesised variable to replace the aggregate term!
         std::string variableName = findUniqueVariableName(*clause);
         auto variable = std::make_unique<AstVariable>(variableName);
         // __agg_rel_0(z) :- ...
         aggHead->addArgument(souffle::clone(variable));
         aggRel->addAttribute(std::make_unique<AstAttribute>(variableName, "number"));
         aggClause->setHead(souffle::clone(aggHead));
         //    A(x) :- x = sum .., B(x).
         // -> A(x) :- x = z, B(x), __agg_rel_0(z).
         auto equalityLiteral = std::make_unique<AstBinaryConstraint>(
                 BinaryConstraintOp::EQ, souffle::clone(variable), souffle::clone(aggregate));
         // __agg_rel_0(z) :- z = sum ...
         aggClause->addToBody(std::move(equalityLiteral));
         program.addRelation(std::move(aggRel));
         program.addClause(std::move(aggClause));
         // the only thing left to do is just replace the aggregate terms in the original
         // clause with the synthesised variable
         struct replaceAggregate : public AstNodeMapper {
             const AstAggregator& aggregate;
             const std::unique_ptr<AstVariable> variable;
             replaceAggregate(const AstAggregator& aggregate, std::unique_ptr<AstVariable> variable)
                     : aggregate(aggregate), variable(std::move(variable)) {}
             std::unique_ptr<AstNode> operator()(std::unique_ptr<AstNode> node) const override {
                 assert(node != nullptr);
                 if (auto* current = dynamic_cast<AstAggregator*>(node.get())) {
                     if (*current == aggregate) {
                         auto replacement = souffle::clone(variable);
                         assert(replacement != nullptr);
                         return replacement;
                     }
                 }
                 node->apply(*this);
                 assert(node != nullptr);
                 return node;
             }
         };
         replaceAggregate update(*aggregate, std::move(variable));
         clause->apply(update);
         clause->addToBody(std::move(aggHead));
     }
     return pairs.size() > 0;
 }
The documentation for this class was generated from the following files:
ast/transform/MaterializeSingletonAggregation.h
ast/transform/MaterializeSingletonAggregation.cpp