souffle: souffle::RamClear Class Reference
souffle::RamClear Class Reference
Delete tuples of a relation.
#include <Statement.h>
Public Member Functions
RamClear * clone () const override
Create a clone (i.e.
RamClear (std::unique_ptr< RamRelationReference > relRef)
Public Member Functions inherited from souffle::RamRelationStatement
void apply (const RamNodeMapper &map) override
Apply the mapper to all child nodes.
std::vector< const RamNode * > getChildNodes () const override
Obtain list of all embedded child nodes.
const RamRelation & getRelation () const
Get RAM relation.
RamRelationStatement (std::unique_ptr< RamRelationReference > relRef)
Public Member Functions inherited from souffle::RamNode
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
virtual void rewrite (const RamNode *oldNode, std::unique_ptr< RamNode > newNode)
Rewrite a child node.
virtual ~RamNode ()=default
Protected Member Functions
void print (std::ostream &os, int tabpos) const override
Pretty print with indentation.
Protected Member Functions inherited from souffle::RamRelationStatement
bool equal (const RamNode &node) const override
Equality check for two RAM nodes.
Protected Member Functions inherited from souffle::RamStatement
void print (std::ostream &os) const override
Print RAM node.
Additional Inherited Members
Static Protected Member Functions inherited from souffle::RamStatement
static void print (const RamStatement *statement, std::ostream &os, int tabpos)
Pretty print jump-bed.
Protected Attributes inherited from souffle::RamRelationStatement
std::unique_ptr< RamRelationReference > relationRef
Relation reference.
Detailed Description
Delete tuples of a relation.
This retains the target relation, but cleans its content
For example:
CLEAR A
Definition at line 153 of file Statement.h.
Constructor & Destructor Documentation
RamClear()
souffle::RamClear::RamClear (std::unique_ptr< RamRelationReference > relRef) inline
Definition at line 155 of file Statement.h.
 : RamRelationStatement(std::move(relRef)) {}
Member Function Documentation
clone()
RamClear* souffle::RamClear::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::RamStatement.
Definition at line 157 of file Statement.h.
References souffle::clone().
Referenced by souffle::test::TEST().
{
         return new RamClear(souffle::clone(relationRef));
     }
print()
void souffle::RamClear::print (std::ostream & os, int tabpos) const inline override protected virtual
Pretty print with indentation.
Implements souffle::RamStatement.
Definition at line 162 of file Statement.h.
References souffle::RamRelation::getName(), souffle::getRelation(), and souffle::times().
{
         const RamRelation& rel = getRelation();
         os << times(" ", tabpos);
         os << "CLEAR ";
         os << rel.getName();
         os << std::endl;
     }
The documentation for this class was generated from the following file:
ram/Statement.h