souffle: souffle::ReadStreamSQLite Class Reference
souffle::ReadStreamSQLite Class Reference
#include <ReadStreamSQLite.h>
Public Member Functions
ReadStreamSQLite (const std::map< std::string, std::string > &rwOperation, SymbolTable &symbolTable, RecordTable &recordTable)
~ReadStreamSQLite () override
Public Member Functions inherited from souffle::ReadStream
template<typename T >
void readAll (T &relation)
Public Member Functions inherited from souffle::SerialisationStream< false >
virtual ~SerialisationStream ()=default
Protected Member Functions
void checkTableExists ()
void executeSQL (const std::string &sql)
void openDB ()
void prepareSelectStatement ()
std::unique_ptr< RamDomain[]> readNextTuple () override
Read and return the next tuple.
void throwError (const std::string &message)
Protected Member Functions inherited from souffle::ReadStream
void consumeChar (const std::string &str, char c, size_t &pos)
Read past given character, consuming any preceding whitespace.
void consumeWhiteSpace (const std::string &str, size_t &pos)
Advance position in the string until first non-whitespace character.
RamDomain readRecord (const std::string &source, const std::string &recordTypeName, size_t pos=0, size_t *charactersRead=nullptr)
Read a record from a string.
ReadStream (const std::map< std::string, std::string > &rwOperation, SymbolTable &symTab, RecordTable &recTab)
RamDomain readStringInRecord (const std::string &source, const size_t pos, size_t *charactersRead)
Protected Member Functions inherited from souffle::SerialisationStream< false >
SerialisationStream (RO< SymbolTable > &symTab, RO< RecordTable > &recTab, Json types, std::vector< std::string > relTypes, size_t auxArity=0)
SerialisationStream (RO< SymbolTable > &symTab, RO< RecordTable > &recTab, Json types)
SerialisationStream (RO< SymbolTable > &symTab, RO< RecordTable > &recTab, const std::map< std::string, std::string > &rwOperation)
Static Protected Member Functions
static std::string getFileName (const std::map< std::string, std::string > &rwOperation)
Return given filename or construct from relation name.
Protected Attributes
sqlite3 * db = nullptr
const std::string dbFilename
const std::string relationName
sqlite3_stmt * selectStatement = nullptr
Protected Attributes inherited from souffle::SerialisationStream< false >
size_t arity
size_t auxiliaryArity
RO< RecordTable > & recordTable
RO< SymbolTable > & symbolTable
std::vector< std::string > typeAttributes
Json types
Additional Inherited Members
Protected Types inherited from souffle::SerialisationStream< false >
using RO = std::conditional_t< readOnlyTables, const A, A >
Detailed Description
Definition at line 35 of file ReadStreamSQLite.h.
Constructor & Destructor Documentation
ReadStreamSQLite()
souffle::ReadStreamSQLite::ReadStreamSQLite (const std::map< std::string, std::string > & rwOperation, SymbolTable & symbolTable, RecordTable & recordTable) inline
Definition at line 37 of file ReadStreamSQLite.h.
References checkTableExists(), openDB(), and prepareSelectStatement().
             : ReadStream(rwOperation, symbolTable, recordTable), dbFilename(getFileName(rwOperation)),
               relationName(rwOperation.at("name")) {
         openDB();
         checkTableExists();
         prepareSelectStatement();
     }
~ReadStreamSQLite()
souffle::ReadStreamSQLite::~ReadStreamSQLite () inline override
Definition at line 46 of file ReadStreamSQLite.h.
References db, and selectStatement.
{
         sqlite3_finalize(selectStatement);
         sqlite3_close(db);
     }
Member Function Documentation
checkTableExists()
void souffle::ReadStreamSQLite::checkTableExists () inline protected
Definition at line 133 of file ReadStreamSQLite.h.
References souffle::test::count(), db, dbFilename, relationName, and throwError().
Referenced by ReadStreamSQLite().
{
         sqlite3_stmt* tableStatement;
         std::stringstream selectSQL;
         selectSQL << "SELECT count(*) FROM sqlite_master WHERE type IN ('table', 'view') AND ";
         selectSQL << " name = '" << relationName << "';";
         const char* tail = nullptr;
         if (sqlite3_prepare_v2(db, selectSQL.str().c_str(), -1, &tableStatement, &tail) != SQLITE_OK) {
             throwError("SQLite error in sqlite3_prepare_v2: ");
         }
         if (sqlite3_step(tableStatement) == SQLITE_ROW) {
             int count = sqlite3_column_int(tableStatement, 0);
             if (count > 0) {
                 sqlite3_finalize(tableStatement);
                 return;
             }
         }
         sqlite3_finalize(tableStatement);
         throw std::invalid_argument(
                 "Required table or view does not exist in " + dbFilename + " for relation " + relationName);
     }
executeSQL()
void souffle::ReadStreamSQLite::executeSQL (const std::string & sql) inline protected
Definition at line 93 of file ReadStreamSQLite.h.
References db.
Referenced by openDB().
{
         assert(db && "Database connection is closed");
         char* errorMessage = nullptr;
         /* Execute SQL statement */
         int rc = sqlite3_exec(db, sql.c_str(), nullptr, nullptr, &errorMessage);
         if (rc != SQLITE_OK) {
             std::stringstream error;
             error << "SQLite error in sqlite3_exec: " << sqlite3_errmsg(db) << "\n";
             error << "SQL error: " << errorMessage << "\n";
             error << "SQL: " << sql << "\n";
             sqlite3_free(errorMessage);
             throw std::invalid_argument(error.str());
         }
     }
getFileName()
static std::string souffle::ReadStreamSQLite::getFileName (const std::map< std::string, std::string > & rwOperation) inline static protected
Return given filename or construct from relation name.
Default name is [configured path]/[relation name].sqlite
Parameters
rwOperation map of IO configuration options
Returns
input filename
Definition at line 163 of file ReadStreamSQLite.h.
References souffle::getOr().
{
         // legacy support for SQLite prior to 2020-03-18
         // convert dbname to filename
         auto name = getOr(rwOperation, "dbname", rwOperation.at("name") + ".sqlite");
         name = getOr(rwOperation, "filename", name);
         if (name.front() != '/') {
             name = getOr(rwOperation, "fact-dir", ".") + "/" + name;
         }
         return name;
     }
openDB()
void souffle::ReadStreamSQLite::openDB () inline protected
Definition at line 124 of file ReadStreamSQLite.h.
References db, dbFilename, executeSQL(), and throwError().
Referenced by ReadStreamSQLite().
                   {
         if (sqlite3_open(dbFilename.c_str(), &db) != SQLITE_OK) {
             throwError("SQLite error in sqlite3_open: ");
         }
         sqlite3_extended_result_codes(db, 1);
         executeSQL("PRAGMA synchronous = OFF");
         executeSQL("PRAGMA journal_mode = MEMORY");
     }
prepareSelectStatement()
void souffle::ReadStreamSQLite::prepareSelectStatement () inline protected
Definition at line 115 of file ReadStreamSQLite.h.
References db, relationName, selectStatement, and throwError().
Referenced by ReadStreamSQLite().
{
         std::stringstream selectSQL;
         selectSQL << "SELECT * FROM '" << relationName << "'";
         const char* tail = nullptr;
         if (sqlite3_prepare_v2(db, selectSQL.str().c_str(), -1, &selectStatement, &tail) != SQLITE_OK) {
             throwError("SQLite error in sqlite3_prepare_v2: ");
         }
     }
readNextTuple()
std::unique_ptr<RamDomain[]> souffle::ReadStreamSQLite::readNextTuple () inline override protected virtual
Read and return the next tuple.
Returns nullptr if no tuple was readable.
Returns
Implements souffle::ReadStream.
Definition at line 58 of file ReadStreamSQLite.h.
References souffle::SerialisationStream< false >::arity, souffle::SerialisationStream< false >::auxiliaryArity, souffle::fatal(), souffle::RamSignedFromString(), selectStatement, souffle::SerialisationStream< false >::symbolTable, and souffle::SerialisationStream< false >::typeAttributes.
{
         if (sqlite3_step(selectStatement) != SQLITE_ROW) {
             return nullptr;
         }
         std::unique_ptr<RamDomain[]> tuple = std::make_unique<RamDomain[]>(arity + auxiliaryArity);
         uint32_t column;
         for (column = 0; column < arity; column++) {
             std::string element(reinterpret_cast<const char*>(sqlite3_column_text(selectStatement, column)));
             if (element.empty()) {
                 element = "n/a";
             }
             try {
                 auto&& ty = typeAttributes.at(column);
                 switch (ty[0]) {
                     case 's': tuple[column] = symbolTable.unsafeLookup(element); break;
                     case 'i':
                     case 'u':
                     case 'f':
                     case 'r': tuple[column] = RamSignedFromString(element); break;
                     default: fatal("invalid type attribute: `%c`", ty[0]);
                 }
             } catch (...) {
                 std::stringstream errorMessage;
                 errorMessage << "Error converting number in column " << (column) + 1;
                 throw std::invalid_argument(errorMessage.str());
             }
         }
         return tuple;
     }
throwError()
void souffle::ReadStreamSQLite::throwError (const std::string & message) inline protected
Definition at line 109 of file ReadStreamSQLite.h.
References db.
Referenced by checkTableExists(), openDB(), and prepareSelectStatement().
{
         std::stringstream error;
         error << message << sqlite3_errmsg(db) << "\n";
         throw std::invalid_argument(error.str());
     }
Field Documentation
db
sqlite3* souffle::ReadStreamSQLite::db = nullptr protected
Definition at line 178 of file ReadStreamSQLite.h.
Referenced by checkTableExists(), executeSQL(), openDB(), prepareSelectStatement(), throwError(), and ~ReadStreamSQLite().
dbFilename
const std::string souffle::ReadStreamSQLite::dbFilename protected
Definition at line 175 of file ReadStreamSQLite.h.
Referenced by checkTableExists(), and openDB().
relationName
const std::string souffle::ReadStreamSQLite::relationName protected
Definition at line 176 of file ReadStreamSQLite.h.
Referenced by checkTableExists(), and prepareSelectStatement().
selectStatement
sqlite3_stmt* souffle::ReadStreamSQLite::selectStatement = nullptr protected
Definition at line 177 of file ReadStreamSQLite.h.
Referenced by prepareSelectStatement(), readNextTuple(), and ~ReadStreamSQLite().
The documentation for this class was generated from the following file:
ReadStreamSQLite.h