souffle: souffle::RamIndexAnalysis Class Reference
souffle::RamIndexAnalysis Class Reference
#include <IndexAnalysis.h>
Public Member Functions
MinIndexSelection & getIndexes (const RamRelation &rel)
get the minimal index cover for a relation
MinIndexSelection & getIndexes (const std::string &relName)
get the minimal index cover for a relation
SearchSignature getSearchSignature (const RamIndexOperation *search) const
Get index signature for an Ram IndexOperation operation
SearchSignature getSearchSignature (const RamExistenceCheck *existCheck) const
Get the index signature for an existence check
SearchSignature getSearchSignature (const RamProvenanceExistenceCheck *existCheck) const
Get the index signature for a provenance existence check
SearchSignature getSearchSignature (const RamRelation *ramRel) const
Get the default index signature for a relation (the total-order index)
bool isTotalSignature (const RamAbstractExistenceCheck *existCheck) const
index signature of existence check resembles a total index
void print (std::ostream &os) const override
Print the analysis result in HTML format.
RamIndexAnalysis (const char *id)
void run (const RamTranslationUnit &translationUnit) override
Run analysis for a RAM translation unit.
Public Member Functions inherited from souffle::RamAnalysis
virtual const std::string & getName () const
get name of the analysis
RamAnalysis (const char *id)
virtual ~RamAnalysis ()=default
Static Public Attributes
static constexpr const char * name = "index-analysis"
Private Attributes
std::map< const RamRelation *, MinIndexSelection > minIndexCover
minimal index cover for relations, i.e., maps a relation to a set of indexes
Additional Inherited Members
Protected Attributes inherited from souffle::RamAnalysis
std::string identifier
name of analysis instance
Detailed Description
Definition at line 441 of file IndexAnalysis.h.
Constructor & Destructor Documentation
RamIndexAnalysis()
souffle::RamIndexAnalysis::RamIndexAnalysis (const char * id) inline
Definition at line 443 of file IndexAnalysis.h.
 : RamAnalysis(id) {}
Member Function Documentation
getIndexes() [1/2]
MinIndexSelection & souffle::RamIndexAnalysis::getIndexes (const RamRelation & rel)
get the minimal index cover for a relation
Parameters
relation
Returns
set of indexes of the minimal index cover
Definition at line 321 of file IndexAnalysis.cpp.
Referenced by souffle::NodeGenerator::encodeIndexPos(), souffle::NodeGenerator::encodeRelation(), and souffle::IndexedInequalityTransformer::transformIndexToFilter().
{
     auto pos = minIndexCover.find(&rel);
     if (pos != minIndexCover.end()) {
         return pos->second;
     } else {
         auto ret = minIndexCover.insert(std::make_pair(&rel, MinIndexSelection()));
         assert(ret.second);
         return ret.first->second;
     }
 }
getIndexes() [2/2]
MinIndexSelection& souffle::RamIndexAnalysis::getIndexes (const std::string & relName)
get the minimal index cover for a relation
Parameters
relation name
Returns
set of indexes of the minimal index cover
getSearchSignature() [1/4]
SearchSignature souffle::RamIndexAnalysis::getSearchSignature (const RamIndexOperation * search) const
Get index signature for an Ram IndexOperation operation
Parameters
Index-relation-search operation
Returns
Index signature of operation
Definition at line 388 of file IndexAnalysis.cpp.
References souffle::Equal, souffle::RamRelation::getArity(), souffle::RamIndexOperation::getRangePattern(), souffle::RamRelationOperation::getRelation(), i, souffle::Inequal, souffle::isRamUndefValue(), souffle::None, and souffle::SearchSignature::set().
Referenced by souffle::Synthesiser::emitCode(), and souffle::NodeGenerator::encodeIndexPos().
{
     size_t arity = search->getRelation().getArity();
     auto lower = search->getRangePattern().first;
     auto upper = search->getRangePattern().second;
     SearchSignature keys(arity);
     for (size_t i = 0; i < arity; ++i) {
         // if both bounds are undefined
         if (isRamUndefValue(lower[i]) && isRamUndefValue(upper[i])) {
             keys.set(i, AttributeConstraint::None);
             // if bounds are equal we have an equality
         } else if (*lower[i] == *upper[i]) {
             keys.set(i, AttributeConstraint::Equal);
         } else {
             keys.set(i, AttributeConstraint::Inequal);
         }
     }
     return keys;
 }
getSearchSignature() [2/4]
SearchSignature souffle::RamIndexAnalysis::getSearchSignature (const RamExistenceCheck * existCheck) const
Get the index signature for an existence check
Parameters
Existence check
Returns
index signature of existence check
Definition at line 431 of file IndexAnalysis.cpp.
References souffle::RamRelation::getArity(), souffle::RamAbstractExistenceCheck::getRelation(), and souffle::RamAbstractExistenceCheck::getValues().
{
     return searchSignature(existCheck->getRelation().getArity(), existCheck->getValues());
 }
getSearchSignature() [3/4]
SearchSignature souffle::RamIndexAnalysis::getSearchSignature (const RamProvenanceExistenceCheck * existCheck) const
Get the index signature for a provenance existence check
Parameters
Provenance-existence check
Returns
index signature of provenance-existence check
Definition at line 409 of file IndexAnalysis.cpp.
References souffle::Equal, souffle::RamRelation::getAuxiliaryArity(), souffle::RamAbstractExistenceCheck::getRelation(), souffle::RamAbstractExistenceCheck::getValues(), i, souffle::isRamUndefValue(), souffle::None, and souffle::SearchSignature::set().
{
     const auto values = provExistCheck->getValues();
     auto auxiliaryArity = provExistCheck->getRelation().getAuxiliaryArity();
     SearchSignature keys(values.size());
     // all payload attributes should be equalities
     for (size_t i = 0; i < values.size() - auxiliaryArity; i++) {
         if (!isRamUndefValue(values[i])) {
             keys.set(i, AttributeConstraint::Equal);
         }
     }
     // all auxiliary attributes should be free
     for (size_t i = values.size() - auxiliaryArity; i < values.size(); i++) {
         keys.set(i, AttributeConstraint::None);
     }
     return keys;
 }
getSearchSignature() [4/4]
SearchSignature souffle::RamIndexAnalysis::getSearchSignature (const RamRelation * ramRel) const
Get the default index signature for a relation (the total-order index)
Parameters
ramRel RAM-relation
Returns
total full-signature of the relation
Definition at line 435 of file IndexAnalysis.cpp.
References souffle::RamRelation::getArity(), and souffle::SearchSignature::getFullSearchSignature().
{
     return SearchSignature::getFullSearchSignature(ramRel->getArity());
 }
isTotalSignature()
bool souffle::RamIndexAnalysis::isTotalSignature (const RamAbstractExistenceCheck * existCheck) const
index signature of existence check resembles a total index
Parameters
(provenance) existence check
isTotalSignature returns true if all elements of a tuple are used for the the existence check.
Definition at line 439 of file IndexAnalysis.cpp.
References souffle::RamAbstractExistenceCheck::getValues(), and souffle::isRamUndefValue().
Referenced by souffle::Synthesiser::emitCode().
{
     for (const auto& cur : existCheck->getValues()) {
         if (isRamUndefValue(cur)) {
             return false;
         }
     }
     return true;
 }
print()
void souffle::RamIndexAnalysis::print (std::ostream &) const override virtual
Print the analysis result in HTML format.
Reimplemented from souffle::RamAnalysis.
Definition at line 332 of file IndexAnalysis.cpp.
References souffle::Equal, souffle::MinIndexSelection::getAllOrders(), souffle::RamRelation::getArity(), souffle::RamRelation::getAttributeNames(), souffle::RamRelation::getName(), souffle::MinIndexSelection::getSearches(), i, souffle::isRamUndefValue(), souffle::None, and souffle::SearchSignature::set().
{
     for (auto& cur : minIndexCover) {
         const RamRelation& rel = *cur.first;
         const MinIndexSelection& indexes = cur.second;
         const std::string& relName = rel.getName();
         /* Print searches */
         os << "Relation " << relName << "\n";
         os << "\tNumber of Primitive Searches: " << indexes.getSearches().size() << "\n";
         const auto& attrib = rel.getAttributeNames();
         size_t arity = rel.getArity();
         /* print searches */
         for (auto& cols : indexes.getSearches()) {
             os << "\t\t";
             for (size_t i = 0; i < arity; i++) {
                 if (cols[i] != AttributeConstraint::None) {
                     os << attrib[i] << " ";
                 }
             }
             os << "\n";
         }
         os << "\tNumber of Indexes: " << indexes.getAllOrders().size() << "\n";
         for (auto& order : indexes.getAllOrders()) {
             os << "\t\t";
             for (auto& i : order) {
                 os << attrib[i] << " ";
             }
             os << "\n";
         }
     }
 }
run()
void souffle::RamIndexAnalysis::run (const RamTranslationUnit & translationUnit) override virtual
Run analysis for a RAM translation unit.
Implements souffle::RamAnalysis.
Definition at line 254 of file IndexAnalysis.cpp.
References souffle::MinIndexSelection::addSearch(), souffle::MinIndexSelection::getAllOrders(), souffle::RamTranslationUnit::getProgram(), souffle::MinIndexSelection::getSearches(), souffle::MinIndexSelection::insertDefaultTotalIndex(), souffle::MinIndexSelection::solve(), and souffle::visitDepthFirst().
{
     // After complete:
     // 1. All relations should have at least one index (for full-order search).
     // 2. Two relations involved in a swap operation will have same set of indices.
     // 3. A 0-arity relation will have only one index where LexOrder is defined as empty. A comparator using
     // an empty order should regard all elements as equal and therefore only allow one arbitrary tuple to be
     // inserted.
     //
     // TODO:
     // 0-arity relation in a provenance program still need to be revisited.
     // visit all nodes to collect searches of each relation
     visitDepthFirst(translationUnit.getProgram(), [&](const RamNode& node) {
         if (const auto* indexSearch = dynamic_cast<const RamIndexOperation*>(&node)) {
             MinIndexSelection& indexes = getIndexes(indexSearch->getRelation());
             indexes.addSearch(getSearchSignature(indexSearch));
         } else if (const auto* exists = dynamic_cast<const RamExistenceCheck*>(&node)) {
             MinIndexSelection& indexes = getIndexes(exists->getRelation());
             indexes.addSearch(getSearchSignature(exists));
         } else if (const auto* provExists = dynamic_cast<const RamProvenanceExistenceCheck*>(&node)) {
             MinIndexSelection& indexes = getIndexes(provExists->getRelation());
             indexes.addSearch(getSearchSignature(provExists));
         } else if (const auto* ramRel = dynamic_cast<const RamRelation*>(&node)) {
             MinIndexSelection& indexes = getIndexes(*ramRel);
             indexes.addSearch(getSearchSignature(ramRel));
         }
     });
     // A swap happen between rel A and rel B indicates A should include all indices of B, vice versa.
     visitDepthFirst(translationUnit.getProgram(), [&](const RamSwap& swap) {
         // Note: this naive approach will not work if there exists chain or cyclic swapping.
         // e.g.  swap(relA, relB) swap(relB, relC) swap(relC, relA)
         // One need to keep merging the search set until a fixed point where no more index is introduced
         // in any of the relation in a complete iteration.
         //
         // Currently RAM does not have such situation.
         const RamRelation& relA = swap.getFirstRelation();
         const RamRelation& relB = swap.getSecondRelation();
         MinIndexSelection& indexesA = getIndexes(relA);
         MinIndexSelection& indexesB = getIndexes(relB);
         // Add all searchSignature of A into B
         for (const auto& signature : indexesA.getSearches()) {
             indexesB.addSearch(signature);
         }
         // Add all searchSignature of B into A
         for (const auto& signature : indexesB.getSearches()) {
             indexesA.addSearch(signature);
         }
     });
     // find optimal indexes for relations
     for (auto& cur : minIndexCover) {
         MinIndexSelection& indexes = cur.second;
         indexes.solve();
     }
     // Only case where indexSet is still empty is when relation has arity == 0
     for (auto& cur : minIndexCover) {
         MinIndexSelection& indexes = cur.second;
         if (indexes.getAllOrders().empty()) {
             indexes.insertDefaultTotalIndex(0);
         }
     }
 }
Field Documentation
minIndexCover
std::map<const RamRelation*, MinIndexSelection> souffle::RamIndexAnalysis::minIndexCover private
minimal index cover for relations, i.e., maps a relation to a set of indexes
Definition at line 506 of file IndexAnalysis.h.
name
constexpr const char* souffle::RamIndexAnalysis::name = "index-analysis" static
Definition at line 445 of file IndexAnalysis.h.
The documentation for this class was generated from the following files:
ram/analysis/IndexAnalysis.h
ram/analysis/IndexAnalysis.cpp