souffle: souffle::Adornment Class Reference
souffle::Adornment Class Reference
#include <MagicSet.h>
Public Member Functions
Adornment ()
const std::vector< std::vector< AdornedClause > > & getAdornedClauses () const
const BindingStore & getBindings () const
const std::set< AstQualifiedName > & getEDB () const
const std::set< AstQualifiedName > & getIDB () const
const std::set< AstQualifiedName > & getIgnoredAtoms () const
const std::set< AstQualifiedName > & getNegatedAtoms () const
const std::vector< AstQualifiedName > & getRelations () const
void print (std::ostream &os) const override
print the analysis result in HTML format
void run (const AstTranslationUnit &translationUnit) override
run analysis for a Ast translation unit
~Adornment () override=default
Public Member Functions inherited from souffle::AstAnalysis
AstAnalysis (std::string identifier)
virtual const std::string & getName () const
get name of the analysis
virtual ~AstAnalysis ()=default
Static Public Attributes
static constexpr const char * name = "adorned-clauses"
Private Attributes
std::vector< std::vector< AdornedClause > > adornmentClauses
std::set< AstQualifiedName > adornmentEdb
std::set< AstQualifiedName > adornmentIdb
std::vector< AstQualifiedName > adornmentRelations
BindingStore bindings
std::set< AstQualifiedName > ignoredAtoms
std::set< AstQualifiedName > negatedAtoms
Additional Inherited Members
Protected Attributes inherited from souffle::AstAnalysis
const std::string identifier
Detailed Description
Definition at line 187 of file MagicSet.h.
Constructor & Destructor Documentation
Adornment()
souffle::Adornment::Adornment () inline
Definition at line 191 of file MagicSet.h.
 : AstAnalysis(name) {}
~Adornment()
souffle::Adornment::~Adornment () override default
Member Function Documentation
getAdornedClauses()
const std::vector<std::vector<AdornedClause> >& souffle::Adornment::getAdornedClauses () const inline
Definition at line 199 of file MagicSet.h.
{
         return adornmentClauses;
     }
getBindings()
const BindingStore& souffle::Adornment::getBindings () const inline
Definition at line 223 of file MagicSet.h.
{
         return bindings;
     }
getEDB()
const std::set<AstQualifiedName>& souffle::Adornment::getEDB () const inline
Definition at line 207 of file MagicSet.h.
{
         return adornmentEdb;
     }
getIDB()
const std::set<AstQualifiedName>& souffle::Adornment::getIDB () const inline
Definition at line 211 of file MagicSet.h.
{
         return adornmentIdb;
     }
getIgnoredAtoms()
const std::set<AstQualifiedName>& souffle::Adornment::getIgnoredAtoms () const inline
Definition at line 219 of file MagicSet.h.
{
         return ignoredAtoms;
     }
getNegatedAtoms()
const std::set<AstQualifiedName>& souffle::Adornment::getNegatedAtoms () const inline
Definition at line 215 of file MagicSet.h.
{
         return negatedAtoms;
     }
getRelations()
const std::vector<AstQualifiedName>& souffle::Adornment::getRelations () const inline
Definition at line 203 of file MagicSet.h.
{
         return adornmentRelations;
     }
print()
void souffle::Adornment::print (std::ostream &) const override virtual
print the analysis result in HTML format
Reimplemented from souffle::AstAnalysis.
Definition at line 885 of file MagicSet.cpp.
References clauses, and i.
{
     for (size_t i = 0; i < adornmentClauses.size(); i++) {
         std::vector<AdornedClause> clauses = adornmentClauses[i];
         os << "Output " << i + 1 << ": " << adornmentRelations[i] << std::endl;
         for (AdornedClause clause : clauses) {
             os << clause << std::endl;
         }
         os << std::endl;
     }
 }
run()
void souffle::Adornment::run (const AstTranslationUnit &) override virtual
run analysis for a Ast translation unit
Implements souffle::AstAnalysis.
Definition at line 698 of file MagicSet.cpp.
References souffle::addAggregators(), souffle::addForwardDependencies(), souffle::addIgnoredRelations(), souffle::bindArguments(), souffle::bindComposites(), souffle::contains(), souffle::containsAggregators(), souffle::AdornedPredicate::getAdornment(), souffle::AstTranslationUnit::getAnalysis(), souffle::AstAtom::getArguments(), souffle::AstRelation::getArity(), souffle::AstNegation::getAtom(), souffle::getClauses(), souffle::getNextAtomSIPS(), souffle::AstTranslationUnit::getProgram(), souffle::AstAtom::getQualifiedName(), souffle::AdornedPredicate::getQualifiedName(), souffle::getRelation(), souffle::AstProgram::getRelations(), souffle::getString(), souffle::isBindingConstraint(), souffle::isEqConstraint(), souffle::isFact(), lhs, rhs, and souffle::visitDepthFirst().
{
     // -------------
     // --- Setup ---
     // -------------
     const AstProgram* program = translationUnit.getProgram();
     auto* ioTypes = translationUnit.getAnalysis<IOType>();
     // normalises and tracks bindings of composite arguments (namely records and functors)
     BindingStore compositeBindings = bindComposites(program);
     // set up IDB/EDB and the output queries
     std::vector<AstQualifiedName> outputQueries;
     std::vector<std::vector<AdornedClause>> adornedProgram;
     // sort out the relations in the program into EDB/IDB and find computed relations
     for (AstRelation* rel : program->getRelations()) {
         AstQualifiedName relName = rel->getQualifiedName();
         // find computed relations for the topdown part
         if (ioTypes->isOutput(rel)) {
             outputQueries.push_back(rel->getQualifiedName());
             // add relation to adornment
             adornmentRelations.push_back(rel->getQualifiedName());
         }
         // check whether edb or idb
         bool is_edb = true;
         for (AstClause* clause : getClauses(*program, *rel)) {
             if (!isFact(*clause)) {
                 is_edb = false;
                 break;
             }
         }
         if (is_edb) {
             adornmentEdb.insert(relName);
         } else {
             adornmentIdb.insert(relName);
         }
     }
     // find all negated literals
     visitDepthFirst(*program, [&](const AstNegation& negation) {
         negatedAtoms.insert(negation.getAtom()->getQualifiedName());
     });
     // add the relations needed for negated relations to be computed
     negatedAtoms = addForwardDependencies(program, negatedAtoms);
     // find atoms that should be ignored
     for (AstRelation* rel : program->getRelations()) {
         for (AstClause* clause : getClauses(*program, *rel)) {
             // ignore atoms that have rules containing aggregators
             if (containsAggregators(clause)) {
                 ignoredAtoms.insert(clause->getHead()->getQualifiedName());
             }
             // ignore all atoms used inside an aggregator within the clause
             ignoredAtoms = addAggregators(clause, ignoredAtoms);
         }
     }
     // find atoms that should be ignored based on magic-transform option
     ignoredAtoms = addIgnoredRelations(program, ignoredAtoms);
     // if a relation is ignored, then all the atoms in its bodies need to be ignored
     ignoredAtoms = addForwardDependencies(program, ignoredAtoms);
     // -----------------
     // --- Adornment ---
     // -----------------
     // begin adornment algorithm
     // adornment is performed for each output query separately
     for (auto outputQuery : outputQueries) {
         std::vector<AdornedPredicate> currentPredicates;
         std::set<AdornedPredicate> seenPredicates;
         std::vector<AdornedClause> adornedClauses;
         // create an adorned predicate of the form outputName_ff..f
         size_t arity = getRelation(*program, outputQuery)->getArity();
         std::string frepeat = std::string(arity, 'f');  // #fs = #args
         AdornedPredicate outputPredicate(outputQuery, frepeat);
         currentPredicates.push_back(outputPredicate);
         seenPredicates.insert(outputPredicate);
         // keep going through the remaining predicates that need to be adorned
         while (!currentPredicates.empty()) {
             // pop out the first element
             AdornedPredicate currPredicate = currentPredicates[0];
             currentPredicates.erase(currentPredicates.begin());
             // don't bother adorning ignored predicates
             if (contains(ignoredAtoms, currPredicate.getQualifiedName())) {
                 continue;
             }
             // go through and adorn all IDB clauses defining the relation
             AstRelation* rel = getRelation(*program, currPredicate.getQualifiedName());
             for (AstClause* clause : getClauses(*program, *rel)) {
                 if (isFact(*clause)) {
                     continue;
                 }
                 size_t numAtoms = getBodyLiterals<AstAtom>(*clause).size();
                 std::vector<std::string> clauseAtomAdornments(numAtoms);
                 std::vector<unsigned int> ordering(numAtoms);
                 std::set<std::string> boundArgs;
                 // mark all bound arguments in the head as bound
                 AstAtom* clauseHead = clause->getHead();
                 std::string headAdornment = currPredicate.getAdornment();
                 std::vector<AstArgument*> headArguments = clauseHead->getArguments();
                 for (size_t argnum = 0; argnum < headArguments.size(); argnum++) {
                     if (headAdornment[argnum] == 'b') {
                         std::string name = getString(headArguments[argnum]);
                         boundArgs.insert(name);
                     }
                 }
                 // mark all bound arguments from the body
                 for (const auto* bc : getBodyLiterals<AstBinaryConstraint>(*clause)) {
                     BinaryConstraintOp op = bc->getOperator();
                     if (!isEqConstraint(op)) {
                         continue;
                     }
                     // have an equality constraint
                     AstArgument* lhs = bc->getLHS();
                     AstArgument* rhs = bc->getRHS();
                     if (isBindingConstraint(lhs, rhs, boundArgs)) {
                         boundArgs.insert(getString(lhs));
                     }
                     if (isBindingConstraint(rhs, lhs, boundArgs)) {
                         boundArgs.insert(getString(rhs));
                     }
                 }
                 std::vector<AstAtom*> atoms = getBodyLiterals<AstAtom>(*clause);
                 int atomsAdorned = 0;
                 int atomsTotal = atoms.size();
                 while (atomsAdorned < atomsTotal) {
                     // get the next body atom to adorn based on our SIPS
                     int currIndex = getNextAtomSIPS(atoms, boundArgs, adornmentEdb, compositeBindings);
                     AstAtom* currAtom = atoms[currIndex];
                     AstQualifiedName atomName = currAtom->getQualifiedName();
                     // compute the adornment pattern of this atom, and
                     // add all its arguments to the list of bound args
                     std::pair<std::string, std::set<std::string>> result =
                             bindArguments(currAtom, boundArgs, compositeBindings);
                     std::string atomAdornment = result.first;
                     boundArgs = result.second;
                     // check if we've already dealt with this adornment before
                     if (!contains(seenPredicates, atomName, atomAdornment)) {
                         // not seen before, so push it onto the computation list
                         // and mark it as seen
                         currentPredicates.push_back(AdornedPredicate(atomName, atomAdornment));
                         seenPredicates.insert(AdornedPredicate(atomName, atomAdornment));
                     }
                     clauseAtomAdornments[currIndex] = atomAdornment;  // store the adornment
                     ordering[currIndex] = atomsAdorned;               // mark what atom number this is
                     atoms[currIndex] = nullptr;                       // mark as done
                     atomsAdorned++;
                 }
                 // adornment of this clause is complete - add it to the list of
                 // adorned clauses
                 adornedClauses.push_back(
                         AdornedClause(clause, headAdornment, clauseAtomAdornments, ordering));
             }
         }
         // add the list of adorned clauses matching the current output relation
         adornmentClauses.push_back(adornedClauses);
     }
     this->bindings = std::move(compositeBindings);
 }
Field Documentation
adornmentClauses
std::vector<std::vector<AdornedClause> > souffle::Adornment::adornmentClauses private
Definition at line 228 of file MagicSet.h.
adornmentEdb
std::set<AstQualifiedName> souffle::Adornment::adornmentEdb private
Definition at line 230 of file MagicSet.h.
adornmentIdb
std::set<AstQualifiedName> souffle::Adornment::adornmentIdb private
Definition at line 231 of file MagicSet.h.
adornmentRelations
std::vector<AstQualifiedName> souffle::Adornment::adornmentRelations private
Definition at line 229 of file MagicSet.h.
bindings
BindingStore souffle::Adornment::bindings private
Definition at line 234 of file MagicSet.h.
ignoredAtoms
std::set<AstQualifiedName> souffle::Adornment::ignoredAtoms private
Definition at line 233 of file MagicSet.h.
name
constexpr const char* souffle::Adornment::name = "adorned-clauses" static
Definition at line 189 of file MagicSet.h.
negatedAtoms
std::set<AstQualifiedName> souffle::Adornment::negatedAtoms private
Definition at line 232 of file MagicSet.h.
The documentation for this class was generated from the following files:
ast/transform/MagicSet.h
ast/transform/MagicSet.cpp