souffle: souffle::profile::HtmlGenerator Class Reference
souffle::profile::HtmlGenerator Class Reference
#include <HtmlGenerator.h>
Static Public Member Functions
static std::string getHtml (std::string json)
Static Protected Member Functions
static std::string getFirstHalf ()
static std::string getSecondHalf ()
static std::string wrapCss (const std::string &css)
static std::string wrapJs (const std::string &js)
Detailed Description
Definition at line 32 of file HtmlGenerator.h.
Member Function Documentation
getFirstHalf()
static std::string souffle::profile::HtmlGenerator::getFirstHalf () inline static protected
Definition at line 39 of file HtmlGenerator.h.
References souffle::profile::html::cssChartist, souffle::profile::html::cssStyle, souffle::profile::html::htmlBodyTop, souffle::profile::html::htmlHeadBottom, souffle::profile::html::htmlHeadTop, souffle::profile::ss, and wrapCss().
Referenced by getHtml().
{
         std::stringstream ss;
         ss << html::htmlHeadTop << HtmlGenerator::wrapCss(html::cssChartist) << wrapCss(html::cssStyle)
            << html::htmlHeadBottom << html::htmlBodyTop << "<script>data=";
         return ss.str();
     }
getHtml()
static std::string souffle::profile::HtmlGenerator::getHtml (std::string json) inline static
Definition at line 34 of file HtmlGenerator.h.
References getFirstHalf(), and getSecondHalf().
Referenced by genJsonAtoms().
{
         return getFirstHalf() + json + getSecondHalf();
     }
getSecondHalf()
static std::string souffle::profile::HtmlGenerator::getSecondHalf () inline static protected
Definition at line 45 of file HtmlGenerator.h.
References souffle::profile::html::htmlBodyBottom, souffle::profile::html::jsChartistPlugin, souffle::profile::html::jsMain, souffle::profile::html::jsTableSort, souffle::profile::html::jsUtil, souffle::profile::ss, and wrapJs().
Referenced by getHtml().
{
         std::stringstream ss;
         ss << "</script>" << wrapJs(html::jsTableSort) << wrapJs(html::jsChartistMin)
            << wrapJs(html::jsChartistPlugin) << wrapJs(html::jsUtil) << wrapJs(html::jsMain)
            << html::htmlBodyBottom;
         return ss.str();
     }
wrapCss()
static std::string souffle::profile::HtmlGenerator::wrapCss (const std::string & css) inline static protected
Definition at line 52 of file HtmlGenerator.h.
Referenced by getFirstHalf().
{
         return "<style>" + css + "</style>";
     }
wrapJs()
static std::string souffle::profile::HtmlGenerator::wrapJs (const std::string & js) inline static protected
Definition at line 55 of file HtmlGenerator.h.
Referenced by getSecondHalf().
{
         return "<script>" + js + "</script>";
     }
The documentation for this class was generated from the following file:
profile/HtmlGenerator.h