souffle: souffle::SrcLocation Class Reference
souffle::SrcLocation Class Reference
A class describing a range in an input file.
#include <SrcLocation.h>
Data Structures
struct Point
A class locating a single point in an input file.
Public Member Functions
std::string extloc () const
An extended string describing this location in a end-user friendly way.
bool operator< (const SrcLocation &other) const
A comparison for source locations.
void print (std::ostream &out) const
void setFilename (std::string filename)
Data Fields
Point end = {}
The End location.
std::vector< std::string > filenames
The file referred to.
Point start = {}
The start location.
Friends
std::ostream & operator<< (std::ostream &out, const SrcLocation &range)
Enables ranges to be printed.
Detailed Description
A class describing a range in an input file.
Definition at line 26 of file SrcLocation.h.
Member Function Documentation
extloc()
std::string souffle::SrcLocation::extloc () const
An extended string describing this location in a end-user friendly way.
Definition at line 87 of file SrcLocation.cpp.
References souffle::baseName(), souffle::SrcLocation::Point::column, filenames, souffle::getCurrentFilename(), i, souffle::SrcLocation::Point::line, and start.
Referenced by souffle::AstNode::extloc(), and souffle::DiagnosticMessage::print().
{
     std::string filename = getCurrentFilename(filenames);
     std::ifstream in(filename);
     std::stringstream s;
     if (in.is_open()) {
         s << "file " << baseName(filename) << " at line " << start.line << "\n";
         for (int i = 0; i < start.line - 1; ++i) {
             in.ignore(std::numeric_limits<std::streamsize>::max(), '\n');
         }
         int c;
         int lineLen = 0;
         int offsetColumn = start.column;
         bool prevWhitespace = false;
         bool afterFirstNonSpace = false;
         while ((c = in.get()) != '\n' && c != EOF) {
             s << (char)c;
             lineLen++;
             // Offset column to account for C preprocessor having reduced
             // consecutive non-leading whitespace chars to a single space.
             if (std::isspace(c) != 0) {
                 if (afterFirstNonSpace && prevWhitespace && offsetColumn >= lineLen) {
                     offsetColumn++;
                 }
                 prevWhitespace = true;
             } else {
                 prevWhitespace = false;
                 afterFirstNonSpace = true;
             }
         }
         lineLen++;  // Add new line
         in.close();
         s << "\n";
         for (int i = 1; i <= lineLen; i++) {
             char ch = (i == offsetColumn) ? '^' : '-';
             s << ch;
         }
         in.close();
     } else {
         s << filename << ":" << start.line << ":" << start.column;
     }
     return s.str();
 }
operator<()
bool souffle::SrcLocation::operator< (const SrcLocation & other) const
A comparison for source locations.
Definition at line 48 of file SrcLocation.cpp.
References end, filenames, souffle::getCurrentFilename(), and start.
{
     // Translate filename stack into current files
     std::string filename = getCurrentFilename(filenames);
     std::string otherFilename = getCurrentFilename(other.filenames);
     if (filename < otherFilename) {
         return true;
     }
     if (filename > otherFilename) {
         return false;
     }
     if (start < other.start) {
         return true;
     }
     if (start > other.start) {
         return false;
     }
     if (end < other.end) {
         return true;
     }
     return false;
 }
print()
void souffle::SrcLocation::print (std::ostream & out) const
Definition at line 131 of file SrcLocation.cpp.
References end, filenames, souffle::getCurrentFilename(), and start.
{
     out << getCurrentFilename(filenames) << " [" << start << "-" << end << "]";
 }
setFilename()
void souffle::SrcLocation::setFilename (std::string filename)
Definition at line 72 of file SrcLocation.cpp.
References filenames.
{
     if (filenames.empty()) {
         filenames.emplace_back(filename);
         return;
     }
     if (filenames.back() == filename) {
         return;
     }
     if (filenames.size() > 1 && filenames.at(filenames.size() - 2) == filename) {
         filenames.pop_back();
         return;
     }
     filenames.emplace_back(filename);
 }
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & out, const SrcLocation & range) friend
Enables ranges to be printed.
Definition at line 76 of file SrcLocation.h.
{
         range.print(out);
         return out;
     }
Field Documentation
end
Point souffle::SrcLocation::end = {}
The End location.
Definition at line 63 of file SrcLocation.h.
Referenced by souffle::nextSrcLoc(), operator<(), and print().
filenames
std::vector<std::string> souffle::SrcLocation::filenames
The file referred to.
Definition at line 57 of file SrcLocation.h.
Referenced by extloc(), souffle::nextSrcLoc(), operator<(), print(), and setFilename().
start
Point souffle::SrcLocation::start = {}
The start location.
Definition at line 60 of file SrcLocation.h.
Referenced by extloc(), souffle::nextSrcLoc(), operator<(), and print().
The documentation for this class was generated from the following files:
SrcLocation.h
SrcLocation.cpp