souffle: souffle::profile::InputReader Class Reference
souffle::profile::InputReader Class Reference
#include <UserInputReader.h>
Public Member Functions
void addHistory (std::string hist)
void appendTabCompletion (std::vector< std::string > commands)
void appendTabCompletion (std::string command)
void backspace ()
void clearHistory ()
void clearPrompt (size_t text_len)
void clearTabCompletion ()
std::string getInput ()
bool hasReceivedInput ()
void historyDown ()
void historyUp ()
InputReader ()
InputReader (const InputReader &other)=default
void moveCursor (char direction)
void moveCursorLeft ()
void moveCursorRight ()
void readchar ()
void setPrompt (std::string prompt)
void showFullText (const std::string &text)
void tabComplete ()
Private Attributes
char current_char = 0
std::string current_hist_val
std::vector< std::string > current_tab_completes
std::string current_tab_val
size_t cursor_pos = 0
size_t hist_pos = 0
std::vector< std::string > history
bool in_history = false
bool in_tab_complete = false
bool inputReceived = false
size_t original_hist_cursor_pos = 0
std::string original_hist_val
std::string original_tab_val
std::string output
std::string prompt = "Input: "
std::vector< std::string > tab_completion
size_t tab_pos = 0
Detailed Description
Definition at line 24 of file UserInputReader.h.
Constructor & Destructor Documentation
InputReader() [1/2]
souffle::profile::InputReader::InputReader () inline
Definition at line 45 of file UserInputReader.h.
References clearHistory(), and clearTabCompletion().
                   {
         clearTabCompletion();
         clearHistory();
     }
InputReader() [2/2]
souffle::profile::InputReader::InputReader (const InputReader & other) default
Member Function Documentation
addHistory()
void souffle::profile::InputReader::addHistory (std::string hist) inline
Definition at line 202 of file UserInputReader.h.
Referenced by souffle::profile::Tui::runProf().
{
         if (history.size() > 0) {
             // only add to history if the last command wasn't the same
             if (hist == history.at(history.size() - 1)) {
                 return;
             }
         }
         history.push_back(hist);
     }
appendTabCompletion() [1/2]
void souffle::profile::InputReader::appendTabCompletion (std::vector< std::string > commands) inline
Definition at line 145 of file UserInputReader.h.
Referenced by genJsonAtoms().
{
         tab_completion.insert(std::end(tab_completion), std::begin(commands), std::end(commands));
     }
appendTabCompletion() [2/2]
void souffle::profile::InputReader::appendTabCompletion (std::string command) inline
Definition at line 148 of file UserInputReader.h.
{
         tab_completion.push_back(command);
     }
backspace()
void souffle::profile::InputReader::backspace () inline
Definition at line 298 of file UserInputReader.h.
References moveCursorLeft(), and showFullText().
Referenced by getInput().
                      {
         if (cursor_pos > 0) {
             output.erase(output.begin() + cursor_pos - 1);
             moveCursorLeft();
             showFullText(output);
         }
     }
clearHistory()
void souffle::profile::InputReader::clearHistory () inline
Definition at line 154 of file UserInputReader.h.
Referenced by InputReader().
{
         history = std::vector<std::string>();
     }
clearPrompt()
void souffle::profile::InputReader::clearPrompt (size_t text_len) inline
Definition at line 305 of file UserInputReader.h.
References i.
Referenced by historyDown(), historyUp(), showFullText(), and tabComplete().
{
         for (size_t i = cursor_pos; i < text_len + 1; i++) {
             std::cout << (char)27 << "[C" << std::flush;
         }
         for (size_t i = 0; i < text_len + 1; i++) {
             std::cout << "\b \b" << std::flush;
         }
     }
clearTabCompletion()
void souffle::profile::InputReader::clearTabCompletion () inline
Definition at line 151 of file UserInputReader.h.
Referenced by genJsonAtoms(), and InputReader().
{
         tab_completion = std::vector<std::string>();
     }
getInput()
std::string souffle::profile::InputReader::getInput () inline
Definition at line 80 of file UserInputReader.h.
References backspace(), current_hist_val, current_tab_val, moveCursor(), output, readchar(), showFullText(), and tabComplete().
Referenced by souffle::profile::Tui::runProf().
{
         output = "";
         current_char = 0;
         cursor_pos = 0;
         hist_pos = 0;
         tab_pos = 0;
         in_tab_complete = false;
         in_history = false;
         std::cout << this->prompt << std::flush;
         readchar();
         inputReceived = true;
         bool escaped = false;
         bool arrow_key = false;
         while (current_char != '\n') {
             if (arrow_key) {
                 moveCursor(current_char);
                 escaped = false;
                 arrow_key = false;
             } else if (escaped) {
                 if (current_char == '[') {
                     arrow_key = true;
                 }
             } else {
                 if (current_char == 27) {  // esc char for arrow keys
                     escaped = true;
                 } else if (current_char == '\t') {
                     tabComplete();
                 } else {
                     if (in_history) {
                         output = current_hist_val;
                         in_history = false;
                     } else if (in_tab_complete) {
                         output = current_tab_val;
                         in_tab_complete = false;
                     }
                     if (current_char == 127) {
                         backspace();
                     } else {
                         output.insert(output.begin() + (cursor_pos++), current_char);
                         std::cout << current_char << std::flush;
                         showFullText(output);
                     }
                 }
             }
             readchar();
         }
         if (in_history) {
             return current_hist_val;
         }
         if (in_tab_complete) {
             return current_tab_val;
         }
         return output;
     }
hasReceivedInput()
bool souffle::profile::InputReader::hasReceivedInput () inline
Definition at line 52 of file UserInputReader.h.
References inputReceived.
Referenced by souffle::profile::Tui::runCommand(), and souffle::profile::Tui::Tui().
{
         return inputReceived;
     }
historyDown()
void souffle::profile::InputReader::historyDown () inline
Definition at line 241 of file UserInputReader.h.
References clearPrompt(), and original_hist_cursor_pos.
Referenced by moveCursor().
{
         if (in_history) {
             clearPrompt(current_hist_val.size());
             if (hist_pos + 1 < history.size()) {
                 hist_pos++;
                 current_hist_val = history.at((unsigned)hist_pos);
                 cursor_pos = current_hist_val.size();
                 std::cout << current_hist_val << std::flush;
             } else {
                 in_history = false;
                 cursor_pos = original_hist_cursor_pos;
                 std::cout << original_hist_val << std::flush;
             }
         } else {
             std::cout << '\a' << std::flush;
         }
     }
historyUp()
void souffle::profile::InputReader::historyUp () inline
Definition at line 211 of file UserInputReader.h.
References clearPrompt(), current_tab_val, cursor_pos, and output.
Referenced by moveCursor().
                      {
         if (history.empty()) {
             std::cout << '\a' << std::flush;
             return;
         }
         if (in_tab_complete) {
             output = current_tab_val;
             in_tab_complete = false;
         }
         if (!in_history) {
             original_hist_val = output;
             original_hist_cursor_pos = cursor_pos;
             in_history = true;
             clearPrompt(output.size());
             hist_pos = history.size() - 1;
             current_hist_val = history.back();
             cursor_pos = current_hist_val.size();
             std::cout << current_hist_val << std::flush;
         } else {
             if (hist_pos > 0) {
                 hist_pos--;
                 clearPrompt(current_hist_val.size());
                 current_hist_val = history.at((unsigned)hist_pos);
                 cursor_pos = current_hist_val.size();
                 std::cout << current_hist_val << std::flush;
             } else {
                 std::cout << '\a' << std::flush;
             }
         }
     }
moveCursor()
void souffle::profile::InputReader::moveCursor (char direction) inline
Definition at line 258 of file UserInputReader.h.
References historyDown(), historyUp(), moveCursorLeft(), and moveCursorRight().
Referenced by getInput().
{
         switch (direction) {
             case 'A':
                 historyUp();
                 break;
             case 'B':
                 historyDown();
                 break;
             case 'C':
                 moveCursorRight();
                 break;
             case 'D':
                 moveCursorLeft();
                 break;
             default:
                 break;
         }
     }
moveCursorLeft()
void souffle::profile::InputReader::moveCursorLeft () inline
Definition at line 292 of file UserInputReader.h.
Referenced by backspace(), and moveCursor().
{
         if (cursor_pos > 0) {
             cursor_pos--;
             std::cout << (char)27 << '[' << 'D' << std::flush;
         }
     }
moveCursorRight()
void souffle::profile::InputReader::moveCursorRight () inline
Definition at line 276 of file UserInputReader.h.
Referenced by moveCursor().
{
         if (in_history) {
             if (cursor_pos < current_hist_val.size()) {
                 cursor_pos++;
                 std::cout << (char)27 << '[' << 'C' << std::flush;
             }
         } else if (in_tab_complete) {
             if (cursor_pos < current_tab_val.size()) {
                 cursor_pos++;
                 std::cout << (char)27 << '[' << 'C' << std::flush;
             }
         } else if (cursor_pos < output.size()) {
             cursor_pos++;
             std::cout << (char)27 << '[' << 'C' << std::flush;
         }
     }
readchar()
void souffle::profile::InputReader::readchar () inline
Definition at line 56 of file UserInputReader.h.
Referenced by getInput().
                     {
         char buf = 0;
         struct termios old = {};
         if (tcgetattr(0, &old) < 0) {
             perror("tcsetattr()");
         }
         old.c_lflag &= ~ICANON;
         old.c_lflag &= ~ECHO;
         old.c_cc[VMIN] = 1;
         old.c_cc[VTIME] = 0;
         if (tcsetattr(0, TCSANOW, &old) < 0) {
             perror("tcsetattr ICANON");
         }
         if (::read(0, &buf, 1) < 0) {
             perror("read()");
         }
         old.c_lflag |= ICANON;
         old.c_lflag |= ECHO;
         if (tcsetattr(0, TCSADRAIN, &old) < 0) {
             perror("tcsetattr ~ICANON");
         }
         current_char = buf;
     }
setPrompt()
void souffle::profile::InputReader::setPrompt (std::string prompt) inline
Definition at line 142 of file UserInputReader.h.
References prompt.
Referenced by souffle::profile::Tui::runProf().
{
         this->prompt = prompt;
     }
showFullText()
void souffle::profile::InputReader::showFullText (const std::string & text) inline
Definition at line 313 of file UserInputReader.h.
References clearPrompt(), and i.
Referenced by backspace(), and getInput().
{
         clearPrompt(text.size());
         for (char i : text) {
             std::cout << i << std::flush;
         }
         for (size_t i = cursor_pos; i < text.size(); i++) {
             std::cout << "\b" << std::flush;
         }
     }
tabComplete()
void souffle::profile::InputReader::tabComplete () inline
Definition at line 157 of file UserInputReader.h.
References clearPrompt(), current_hist_val, original_tab_val, and output.
Referenced by getInput().
{
         if (in_history) {
             output = current_hist_val;
             in_history = false;
         }
         if (!in_tab_complete) {
             current_tab_completes = std::vector<std::string>();
             original_tab_val = output;
             bool found_tab = false;
             for (auto& a : tab_completion) {
                 if (a.find(original_tab_val) == 0) {
                     current_tab_completes.push_back(a);
                     found_tab = true;
                 }
             }
             if (!found_tab) {
                 std::cout << '\a' << std::flush;
                 return;
             } else {
                 in_tab_complete = true;
                 tab_pos = 0;
                 current_tab_val = current_tab_completes.at((unsigned)tab_pos);
                 clearPrompt(output.size());
                 cursor_pos = current_tab_val.size();
                 std::cout << current_tab_val << std::flush;
             }
         } else {
             if (tab_pos + 1 >= current_tab_completes.size()) {
                 clearPrompt(current_tab_val.size());
                 current_tab_val = original_tab_val;
                 in_tab_complete = false;
                 cursor_pos = output.size();
                 std::cout << output << std::flush;
             } else {
                 tab_pos++;
                 clearPrompt(current_tab_val.size());
                 current_tab_val = current_tab_completes.at((unsigned)tab_pos);
                 cursor_pos = current_tab_val.size();
                 std::cout << current_tab_val << std::flush;
             }
         }
     }
Field Documentation
current_char
char souffle::profile::InputReader::current_char = 0 private
Definition at line 30 of file UserInputReader.h.
current_hist_val
std::string souffle::profile::InputReader::current_hist_val private
Definition at line 37 of file UserInputReader.h.
Referenced by getInput(), and tabComplete().
current_tab_completes
std::vector<std::string> souffle::profile::InputReader::current_tab_completes private
Definition at line 40 of file UserInputReader.h.
current_tab_val
std::string souffle::profile::InputReader::current_tab_val private
Definition at line 38 of file UserInputReader.h.
Referenced by getInput(), and historyUp().
cursor_pos
size_t souffle::profile::InputReader::cursor_pos = 0 private
Definition at line 31 of file UserInputReader.h.
Referenced by historyUp().
hist_pos
size_t souffle::profile::InputReader::hist_pos = 0 private
Definition at line 32 of file UserInputReader.h.
history
std::vector<std::string> souffle::profile::InputReader::history private
Definition at line 28 of file UserInputReader.h.
in_history
bool souffle::profile::InputReader::in_history = false private
Definition at line 35 of file UserInputReader.h.
in_tab_complete
bool souffle::profile::InputReader::in_tab_complete = false private
Definition at line 34 of file UserInputReader.h.
inputReceived
bool souffle::profile::InputReader::inputReceived = false private
Definition at line 42 of file UserInputReader.h.
Referenced by hasReceivedInput().
original_hist_cursor_pos
size_t souffle::profile::InputReader::original_hist_cursor_pos = 0 private
Definition at line 41 of file UserInputReader.h.
Referenced by historyDown().
original_hist_val
std::string souffle::profile::InputReader::original_hist_val private
Definition at line 36 of file UserInputReader.h.
original_tab_val
std::string souffle::profile::InputReader::original_tab_val private
Definition at line 39 of file UserInputReader.h.
Referenced by tabComplete().
output
std::string souffle::profile::InputReader::output private
Definition at line 29 of file UserInputReader.h.
Referenced by getInput(), historyUp(), and tabComplete().
prompt
std::string souffle::profile::InputReader::prompt = "Input: " private
Definition at line 26 of file UserInputReader.h.
Referenced by setPrompt().
tab_completion
std::vector<std::string> souffle::profile::InputReader::tab_completion private
Definition at line 27 of file UserInputReader.h.
tab_pos
size_t souffle::profile::InputReader::tab_pos = 0 private
Definition at line 33 of file UserInputReader.h.
The documentation for this class was generated from the following file:
profile/UserInputReader.h