souffle: souffle::RamRelation Class Reference
souffle::RamRelation Class Reference
A RAM Relation in the RAM intermediate representation.
#include <Relation.h>
Public Member Functions
RamRelation * clone () const override
Create a clone (i.e.
unsigned getArity () const
Get arity of relation.
const std::vector< std::string > & getAttributeNames () const
Get attribute names.
const std::vector< std::string > & getAttributeTypes () const
Get attribute types.
unsigned getAuxiliaryArity () const
Get number of auxiliary attributes.
const std::string & getName () const
Get name.
RelationRepresentation getRepresentation () const
Relation representation type.
bool isNullary () const
Is nullary relation.
bool isTemp () const
Is temporary relation (for semi-naive evaluation)
bool operator< (const RamRelation &other) const
Compare two relations via their name.
RamRelation (std::string name, size_t arity, size_t auxiliaryArity, std::vector< std::string > attributeNames, std::vector< std::string > attributeTypes, RelationRepresentation representation)
Public Member Functions inherited from souffle::RamNode
virtual void apply (const RamNodeMapper &)
Apply the mapper to all child nodes.
virtual std::vector< const RamNode * > getChildNodes () const
Obtain list of all embedded child nodes.
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
virtual void rewrite (const RamNode *oldNode, std::unique_ptr< RamNode > newNode)
Rewrite a child node.
virtual ~RamNode ()=default
Protected Member Functions
bool equal (const RamNode &node) const override
Equality check for two RAM nodes.
void print (std::ostream &out) const override
Print RAM node.
Protected Attributes
const size_t arity
Arity, i.e., number of attributes.
const std::vector< std::string > attributeNames
Name of attributes.
const std::vector< std::string > attributeTypes
Type of attributes.
const size_t auxiliaryArity
Number of auxiliary attributes (e.g.
const std::string name
Name of relation.
const RelationRepresentation representation
Data-structure representation.
Detailed Description
A RAM Relation in the RAM intermediate representation.
Definition at line 35 of file Relation.h.
Constructor & Destructor Documentation
RamRelation()
souffle::RamRelation::RamRelation (std::string name, size_t arity, size_t auxiliaryArity, std::vector< std::string > attributeNames, std::vector< std::string > attributeTypes, RelationRepresentation representation) inline
Definition at line 37 of file Relation.h.
References arity, and i.
Referenced by clone().
             : representation(representation), name(std::move(name)), arity(arity),
               auxiliaryArity(auxiliaryArity), attributeNames(std::move(attributeNames)),
               attributeTypes(std::move(attributeTypes)) {
         assert(this->attributeNames.size() == arity && "arity mismatch for attributes");
         assert(this->attributeTypes.size() == arity && "arity mismatch for types");
         for (std::size_t i = 0; i < arity; i++) {
             assert(!this->attributeNames[i].empty() && "no attribute name specified");
             assert(!this->attributeTypes[i].empty() && "no attribute type specified");
         }
     }
Member Function Documentation
clone()
RamRelation* souffle::RamRelation::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::RamNode.
Definition at line 96 of file Relation.h.
References arity, attributeNames, attributeTypes, auxiliaryArity, name, RamRelation(), and representation.
Referenced by souffle::test::TEST().
{
         return new RamRelation(name, arity, auxiliaryArity, attributeNames, attributeTypes, representation);
     }
equal()
bool souffle::RamRelation::equal (const RamNode &) const inline override protected virtual
Equality check for two RAM nodes.
Default action is that nothing needs to be checked.
Reimplemented from souffle::RamNode.
Definition at line 119 of file Relation.h.
References arity, attributeNames, attributeTypes, auxiliaryArity, name, and representation.
{
         assert(nullptr != dynamic_cast<const RamRelation*>(&node));
         const auto& other = static_cast<const RamRelation&>(node);
         return representation == other.representation && name == other.name && arity == other.arity &&
                auxiliaryArity == other.auxiliaryArity && attributeNames == other.attributeNames &&
                attributeTypes == other.attributeTypes;
     }
getArity()
unsigned souffle::RamRelation::getArity () const inline
Get arity of relation.
Definition at line 82 of file Relation.h.
References arity.
Referenced by souffle::Synthesiser::emitCode(), souffle::SynthesiserRelation::getArity(), souffle::RamComplexityAnalysis::getComplexity(), souffle::NodeGenerator::getExistenceSuperInstInfo(), souffle::NodeGenerator::getIndexSuperInstInfo(), souffle::NodeGenerator::getProjectSuperInstInfo(), souffle::RamIndexAnalysis::getSearchSignature(), souffle::SynthesiserRelation::getSynthesiserRelation(), souffle::RamIndexAnalysis::print(), souffle::MakeIndexTransformer::rewriteAggregate(), souffle::IfConversionTransformer::rewriteIndexScan(), souffle::MakeIndexTransformer::rewriteScan(), and souffle::AstToRamTranslator::translateRecursiveRelation().
{
         return arity;
     }
getAttributeNames()
const std::vector<std::string>& souffle::RamRelation::getAttributeNames () const inline
Get attribute names.
Definition at line 62 of file Relation.h.
References attributeNames.
Referenced by souffle::InterpreterProgInterface::InterpreterProgInterface(), and souffle::RamIndexAnalysis::print().
{
         return attributeNames;
     }
getAttributeTypes()
const std::vector<std::string>& souffle::RamRelation::getAttributeTypes () const inline
Get attribute types.
Definition at line 57 of file Relation.h.
References attributeTypes.
Referenced by souffle::InterpreterProgInterface::InterpreterProgInterface().
{
         return attributeTypes;
     }
getAuxiliaryArity()
unsigned souffle::RamRelation::getAuxiliaryArity () const inline
Get number of auxiliary attributes.
Definition at line 87 of file Relation.h.
References auxiliaryArity.
Referenced by souffle::SynthesiserDirectRelation::computeIndices(), souffle::SynthesiserDirectRelation::generateTypeStruct(), and souffle::RamIndexAnalysis::getSearchSignature().
{
         return auxiliaryArity;
     }
getName()
const std::string& souffle::RamRelation::getName () const inline
Get name.
Definition at line 52 of file Relation.h.
References name.
Referenced by souffle::Synthesiser::generateCode(), souffle::Synthesiser::getRelationName(), souffle::InterpreterProgInterface::InterpreterProgInterface(), souffle::RamIO::print(), souffle::RamClear::print(), souffle::RamIndexScan::print(), souffle::RamIndexAnalysis::print(), souffle::RamParallelIndexScan::print(), souffle::RamIndexChoice::print(), and souffle::RamParallelIndexChoice::print().
{
         return name;
     }
getRepresentation()
RelationRepresentation souffle::RamRelation::getRepresentation () const inline
Relation representation type.
Definition at line 72 of file Relation.h.
References representation.
Referenced by souffle::SynthesiserRelation::getSynthesiserRelation(), and souffle::AstToRamTranslator::translateRecursiveRelation().
{
         return representation;
     }
isNullary()
bool souffle::RamRelation::isNullary () const inline
Is nullary relation.
Definition at line 67 of file Relation.h.
References arity.
Referenced by souffle::SynthesiserRelation::getSynthesiserRelation().
{
         return arity == 0;
     }
isTemp()
bool souffle::RamRelation::isTemp () const inline
Is temporary relation (for semi-naive evaluation)
Definition at line 77 of file Relation.h.
References name.
Referenced by souffle::Synthesiser::emitCode().
{
         return name.at(0) == '@';
     }
operator<()
bool souffle::RamRelation::operator< (const RamRelation & other) const inline
Compare two relations via their name.
Definition at line 92 of file Relation.h.
References name.
{
         return name < other.name;
     }
print()
void souffle::RamRelation::print (std::ostream & out) const inline override protected virtual
Print RAM node.
Implements souffle::RamNode.
Definition at line 101 of file Relation.h.
References arity, attributeNames, attributeTypes, auxiliaryArity, i, name, and representation.
{
         out << name;
         if (arity > 0) {
             out << "(" << attributeNames[0] << ":" << attributeTypes[0];
             for (unsigned i = 1; i < arity; i++) {
                 out << ",";
                 out << attributeNames[i] << ":" << attributeTypes[i];
                 if (i >= arity - auxiliaryArity) {
                     out << " auxiliary";
                 }
             }
             out << ")";
             out << " " << representation;
         } else {
             out << " nullary";
         }
     }
Field Documentation
arity
const size_t souffle::RamRelation::arity protected
Arity, i.e., number of attributes.
Definition at line 135 of file Relation.h.
Referenced by clone(), equal(), getArity(), isNullary(), print(), and RamRelation().
attributeNames
const std::vector<std::string> souffle::RamRelation::attributeNames protected
Name of attributes.
Definition at line 141 of file Relation.h.
Referenced by clone(), equal(), getAttributeNames(), and print().
attributeTypes
const std::vector<std::string> souffle::RamRelation::attributeTypes protected
Type of attributes.
Definition at line 144 of file Relation.h.
Referenced by clone(), equal(), getAttributeTypes(), and print().
auxiliaryArity
const size_t souffle::RamRelation::auxiliaryArity protected
Number of auxiliary attributes (e.g.
provenance attributes etc)
Definition at line 138 of file Relation.h.
Referenced by clone(), equal(), getAuxiliaryArity(), and print().
name
const std::string souffle::RamRelation::name protected
Name of relation.
Definition at line 132 of file Relation.h.
Referenced by clone(), equal(), getName(), isTemp(), operator<(), and print().
representation
const RelationRepresentation souffle::RamRelation::representation protected
Data-structure representation.
Definition at line 129 of file Relation.h.
Referenced by clone(), equal(), getRepresentation(), and print().
The documentation for this class was generated from the following file:
ram/Relation.h