souffle: souffle::RamConjunction Class Reference
souffle::RamConjunction Class Reference
A conjunction of conditions.
#include <Condition.h>
Public Member Functions
void apply (const RamNodeMapper &map) override
Apply the mapper to all child nodes.
RamConjunction * clone () const override
Create a clone (i.e.
std::vector< const RamNode * > getChildNodes () const override
Obtain list of all embedded child nodes.
const RamCondition & getLHS () const
Get left-hand side of conjunction.
const RamCondition & getRHS () const
Get right-hand side of conjunction.
RamConjunction (std::unique_ptr< RamCondition > l, std::unique_ptr< RamCondition > r)
Public Member Functions inherited from souffle::RamNode
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
virtual void rewrite (const RamNode *oldNode, std::unique_ptr< RamNode > newNode)
Rewrite a child node.
virtual ~RamNode ()=default
Protected Member Functions
bool equal (const RamNode &node) const override
Equality check for two RAM nodes.
void print (std::ostream &os) const override
Print RAM node.
Protected Attributes
std::unique_ptr< RamCondition > lhs
Left-hand side of conjunction.
std::unique_ptr< RamCondition > rhs
Right-hand side of conjunction.
Detailed Description
A conjunction of conditions.
Condition of the form "LHS and RHS", where LHS and RHS are conditions
For example:
C1 AND C2 AND C3
Is a RamConjunction, which may have LHS "C1" and RHS "C2 AND C3"
Definition at line 94 of file Condition.h.
Constructor & Destructor Documentation
RamConjunction()
souffle::RamConjunction::RamConjunction (std::unique_ptr< RamCondition > l, std::unique_ptr< RamCondition > r) inline
Definition at line 96 of file Condition.h.
References lhs, and rhs.
             : lhs(std::move(l)), rhs(std::move(r)) {
         assert(lhs != nullptr && "left-hand side of conjunction is a nullptr");
         assert(rhs != nullptr && "right-hand side of conjunction is a nullptr");
     }
Member Function Documentation
apply()
void souffle::RamConjunction::apply (const RamNodeMapper &) inline override virtual
Apply the mapper to all child nodes.
Reimplemented from souffle::RamNode.
Definition at line 120 of file Condition.h.
References lhs, souffle::map(), and rhs.
{
         lhs = map(std::move(lhs));
         rhs = map(std::move(rhs));
     }
clone()
RamConjunction* souffle::RamConjunction::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::RamCondition.
Definition at line 116 of file Condition.h.
References souffle::clone(), lhs, and rhs.
{
         return new RamConjunction(souffle::clone(lhs), souffle::clone(rhs));
     }
equal()
bool souffle::RamConjunction::equal (const RamNode &) const inline override protected virtual
Equality check for two RAM nodes.
Default action is that nothing needs to be checked.
Reimplemented from souffle::RamNode.
Definition at line 130 of file Condition.h.
References souffle::equal_ptr(), lhs, and rhs.
{
         const auto& other = static_cast<const RamConjunction&>(node);
         return equal_ptr(lhs, other.lhs) && equal_ptr(rhs, other.rhs);
     }
getChildNodes()
std::vector<const RamNode*> souffle::RamConjunction::getChildNodes () const inline override virtual
Obtain list of all embedded child nodes.
Reimplemented from souffle::RamNode.
Definition at line 112 of file Condition.h.
References lhs, and rhs.
{
         return {lhs.get(), rhs.get()};
     }
getLHS()
const RamCondition& souffle::RamConjunction::getLHS () const inline
Get left-hand side of conjunction.
Definition at line 103 of file Condition.h.
References lhs.
Referenced by souffle::Synthesiser::emitCode(), souffle::RamComplexityAnalysis::getComplexity(), and souffle::RamLevelAnalysis::getLevel().
{
         return *lhs;
     }
getRHS()
const RamCondition& souffle::RamConjunction::getRHS () const inline
Get right-hand side of conjunction.
Definition at line 108 of file Condition.h.
References rhs.
Referenced by souffle::Synthesiser::emitCode(), souffle::RamComplexityAnalysis::getComplexity(), and souffle::RamLevelAnalysis::getLevel().
{
         return *rhs;
     }
print()
void souffle::RamConjunction::print (std::ostream & out) const inline override protected virtual
Print RAM node.
Implements souffle::RamNode.
Definition at line 126 of file Condition.h.
References lhs, and rhs.
{
         os << "(" << *lhs << " AND " << *rhs << ")";
     }
Field Documentation
lhs
std::unique_ptr<RamCondition> souffle::RamConjunction::lhs protected
Left-hand side of conjunction.
Definition at line 136 of file Condition.h.
rhs
std::unique_ptr<RamCondition> souffle::RamConjunction::rhs protected
Right-hand side of conjunction.
Definition at line 139 of file Condition.h.
The documentation for this class was generated from the following file:
ram/Condition.h