souffle: souffle::RamCall Class Reference
souffle::RamCall Class Reference
Call a subroutine.
#include <Statement.h>
Public Member Functions
RamCall * clone () const override
Create a clone (i.e.
const std::string & getName () const
Get call name.
RamCall (std::string name)
Public Member Functions inherited from souffle::RamNode
virtual void apply (const RamNodeMapper &)
Apply the mapper to all child nodes.
virtual std::vector< const RamNode * > getChildNodes () const
Obtain list of all embedded child nodes.
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
virtual void rewrite (const RamNode *oldNode, std::unique_ptr< RamNode > newNode)
Rewrite a child node.
virtual ~RamNode ()=default
Protected Member Functions
bool equal (const RamNode &node) const override
Equality check for two RAM nodes.
void print (std::ostream &os, int tabpos) const override
Pretty print with indentation.
Protected Member Functions inherited from souffle::RamStatement
void print (std::ostream &os) const override
Print RAM node.
Protected Attributes
std::string name
name of subroutine
Additional Inherited Members
Static Protected Member Functions inherited from souffle::RamStatement
static void print (const RamStatement *statement, std::ostream &os, int tabpos)
Pretty print jump-bed.
Detailed Description
Call a subroutine.
Calls a subroutine
The following example shows how subroutine A is invoked
CALL A
Definition at line 786 of file Statement.h.
Constructor & Destructor Documentation
RamCall()
souffle::RamCall::RamCall (std::string name) inline
Definition at line 788 of file Statement.h.
 : name(std::move(name)) {}
Member Function Documentation
clone()
RamCall* souffle::RamCall::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::RamStatement.
Definition at line 795 of file Statement.h.
{
         return new RamCall(name);
     }
equal()
bool souffle::RamCall::equal (const RamNode &) const inline override protected virtual
Equality check for two RAM nodes.
Default action is that nothing needs to be checked.
Reimplemented from souffle::RamNode.
Definition at line 804 of file Statement.h.
References name.
{
         const auto& other = static_cast<const RamCall&>(node);
         return name == other.name;
     }
getName()
const std::string& souffle::RamCall::getName () const inline
Get call name.
Definition at line 791 of file Statement.h.
Referenced by souffle::Synthesiser::emitCode(), and souffle::NodeGenerator::visitCall().
{
         return name;
     }
print()
void souffle::RamCall::print (std::ostream & os, int tabpos) const inline override protected virtual
Pretty print with indentation.
Implements souffle::RamStatement.
Definition at line 800 of file Statement.h.
References souffle::times().
{
         os << times(" ", tabpos) << "CALL " << name << std::endl;
     }
Field Documentation
name
std::string souffle::RamCall::name protected
name of subroutine
Definition at line 810 of file Statement.h.
Referenced by equal().
The documentation for this class was generated from the following file:
ram/Statement.h