souffle: souffle::AstPragmaChecker Class Reference
souffle::AstPragmaChecker Class Reference
#include <PragmaChecker.h>
Public Member Functions
AstPragmaChecker * clone () const override
std::string getName () const override
Public Member Functions inherited from souffle::AstTransformer
bool apply (AstTranslationUnit &translationUnit)
virtual ~AstTransformer ()=default
Private Member Functions
bool transform (AstTranslationUnit &) override
Detailed Description
Definition at line 25 of file PragmaChecker.h.
Member Function Documentation
clone()
AstPragmaChecker* souffle::AstPragmaChecker::clone () const inline override virtual
Implements souffle::AstTransformer.
Definition at line 31 of file PragmaChecker.h.
References transform().
{
         return new AstPragmaChecker();
     }
getName()
std::string souffle::AstPragmaChecker::getName () const inline override virtual
Implements souffle::AstTransformer.
Definition at line 27 of file PragmaChecker.h.
{
         return "AstPragmaChecker";
     }
transform()
bool souffle::AstPragmaChecker::transform (AstTranslationUnit & translationUnit) override private virtual
Implements souffle::AstTransformer.
Definition at line 27 of file PragmaChecker.cpp.
References souffle::Global::config(), souffle::AstPragma::getkvp(), souffle::AstTranslationUnit::getProgram(), and souffle::visitDepthFirst().
Referenced by clone().
{
     bool changed = false;
     AstProgram* program = translationUnit.getProgram();
     // Take in pragma options from the datalog file
     visitDepthFirst(*program, [&](const AstPragma& pragma) {
         std::pair<std::string, std::string> kvp = pragma.getkvp();
         // Command line options take precedence
         if (!Global::config().has(kvp.first)) {
             changed = true;
             Global::config().set(kvp.first, kvp.second);
         }
     });
     return changed;
 }
The documentation for this class was generated from the following files:
ast/transform/PragmaChecker.h
ast/transform/PragmaChecker.cpp