souffle: souffle::RamExtend Class Reference
souffle::RamExtend Class Reference
Extend equivalence relation.
#include <Statement.h>
Public Member Functions
RamExtend * clone () const override
Create a clone (i.e.
const RamRelation & getSourceRelation () const
Get source relation.
const RamRelation & getTargetRelation () const
Get target relation.
RamExtend (std::unique_ptr< RamRelationReference > tRef, std::unique_ptr< RamRelationReference > sRef)
Public Member Functions inherited from souffle::RamBinRelationStatement
void apply (const RamNodeMapper &map) override
Apply the mapper to all child nodes.
std::vector< const RamNode * > getChildNodes () const override
Obtain list of all embedded child nodes.
const RamRelation & getFirstRelation () const
Get first relation.
const RamRelation & getSecondRelation () const
Get second relation.
RamBinRelationStatement (std::unique_ptr< RamRelationReference > f, std::unique_ptr< RamRelationReference > s)
Public Member Functions inherited from souffle::RamNode
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
virtual void rewrite (const RamNode *oldNode, std::unique_ptr< RamNode > newNode)
Rewrite a child node.
virtual ~RamNode ()=default
Protected Member Functions
void print (std::ostream &os, int tabpos) const override
Pretty print with indentation.
Protected Member Functions inherited from souffle::RamBinRelationStatement
bool equal (const RamNode &node) const override
Equality check for two RAM nodes.
Protected Member Functions inherited from souffle::RamStatement
void print (std::ostream &os) const override
Print RAM node.
Additional Inherited Members
Static Protected Member Functions inherited from souffle::RamStatement
static void print (const RamStatement *statement, std::ostream &os, int tabpos)
Pretty print jump-bed.
Protected Attributes inherited from souffle::RamBinRelationStatement
std::unique_ptr< RamRelationReference > first
first argument of binary statement
std::unique_ptr< RamRelationReference > second
second argument of binary statement
Detailed Description
Extend equivalence relation.
The following example merges A into B:
EXTEND B WITH A
Definition at line 234 of file Statement.h.
Constructor & Destructor Documentation
RamExtend()
souffle::RamExtend::RamExtend (std::unique_ptr< RamRelationReference > tRef, std::unique_ptr< RamRelationReference > sRef) inline
Definition at line 236 of file Statement.h.
             : RamBinRelationStatement(std::move(sRef), std::move(tRef)) {}
Member Function Documentation
clone()
RamExtend* souffle::RamExtend::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::RamStatement.
Definition at line 249 of file Statement.h.
References souffle::clone().
Referenced by souffle::test::TEST().
{
         auto* res = new RamExtend(souffle::clone(second), souffle::clone(first));
         return res;
     }
getSourceRelation()
const RamRelation& souffle::RamExtend::getSourceRelation () const inline
Get source relation.
Definition at line 240 of file Statement.h.
Referenced by souffle::Synthesiser::emitCode().
{
         return getFirstRelation();
     }
getTargetRelation()
const RamRelation& souffle::RamExtend::getTargetRelation () const inline
Get target relation.
Definition at line 245 of file Statement.h.
Referenced by souffle::Synthesiser::emitCode().
{
         return getSecondRelation();
     }
print()
void souffle::RamExtend::print (std::ostream & os, int tabpos) const inline override protected virtual
Pretty print with indentation.
Implements souffle::RamStatement.
Definition at line 255 of file Statement.h.
References souffle::times().
{
         os << times(" ", tabpos);
         os << "EXTEND " << getTargetRelation().getName() << " WITH " << getSourceRelation().getName();
         os << std::endl;
     }
The documentation for this class was generated from the following file:
ram/Statement.h