souffle: souffle::SparseBitMap< BITS > Class Template Reference
souffle::SparseBitMap< BITS > Class Template Reference
A sparse bit-map is a bit map virtually assigning a bit value to every value if the uint32_t domain.
#include <Brie.h>
Data Structures
class iterator
An iterator iterating over all indices set to 1.
struct merge_op
Public Types
using index_type = typename data_store_t::index_type
using op_context = typename data_store_t::op_context
Public Member Functions
void addAll (const SparseBitMap &other)
Sets all bits set in other to 1 within this bit map.
iterator begin () const
Obtains an iterator pointing to the first index set to 1.
void clear ()
Resets all contained bits to 0.
void dump (bool detail=false, std::ostream &out=std::cout) const
A debugging utility printing the internal structure of this map to the given output stream.
bool empty () const
iterator end () const
Returns an iterator referencing the position after the last set bit.
iterator find (index_type i) const
Obtains an iterator referencing the position i if the corresponding bit is set, end() otherwise.
iterator find (index_type i, op_context &ctxt) const
Obtains an iterator referencing the position i if the corresponding bit is set, end() otherwise.
std::size_t getMemoryUsage () const
Computes the total memory usage of this data structure.
const data_store_t & getStore () const
Provides write-protected access to the internal store for running analysis on the data structure.
iterator lower_bound (index_type i) const
Locates an iterator to the first element in this sparse bit map not less than the given index.
SparseBitMap & operator= (const SparseBitMap &)=default
SparseBitMap & operator= (SparseBitMap &&)=default
bool operator[] (index_type i) const
Determines the whether the bit addressed by i is set or not.
bool set (index_type i)
Sets the bit addressed by i to 1.
bool set (index_type i, op_context &ctxt)
Sets the bit addressed by i to 1.
std::size_t size () const
Determines the number of bits set.
SparseBitMap ()=default
SparseBitMap (const SparseBitMap &)=default
SparseBitMap (SparseBitMap &&)=default
bool test (index_type i) const
Determines the whether the bit addressed by i is set or not.
bool test (index_type i, op_context &ctxt) const
Determines the whether the bit addressed by i is set or not.
iterator upper_bound (index_type i) const
Locates an iterator to the first element in this sparse bit map than is greater than the given index.
Private Types
using atomic_value_t = typename data_store_t::atomic_value_type
using data_store_t = SparseArray< value_t, BITS, merge_op >
using value_t = uint64_t
Private Attributes
data_store_t store
Static Private Attributes
static constexpr short BITS_PER_ENTRY = sizeof(value_t) * 8
static constexpr uint64_t LEAF_INDEX_MASK = BITS_PER_ENTRY - 1
static constexpr short LEAF_INDEX_WIDTH = static_cast<short>(__builtin_ctz(BITS_PER_ENTRY))
Detailed Description
template<unsigned BITS = 4>
class souffle::SparseBitMap< BITS >
A sparse bit-map is a bit map virtually assigning a bit value to every value if the uint32_t domain.
However, only 1-bits are stored utilizing a nested sparse array structure.
Template Parameters
BITS similar to the BITS parameter of the sparse array type
Definition at line 1452 of file Brie.h.
Member Typedef Documentation
atomic_value_t
template<unsigned BITS = 4> using souffle::SparseBitMap< BITS >::atomic_value_t = typename data_store_t::atomic_value_type private
Definition at line 1465 of file Brie.h.
data_store_t
template<unsigned BITS = 4> using souffle::SparseBitMap< BITS >::data_store_t = SparseArray<value_t, BITS, merge_op> private
Definition at line 1464 of file Brie.h.
index_type
template<unsigned BITS = 4> using souffle::SparseBitMap< BITS >::index_type = typename data_store_t::index_type
Definition at line 1474 of file Brie.h.
op_context
template<unsigned BITS = 4> using souffle::SparseBitMap< BITS >::op_context = typename data_store_t::op_context
Definition at line 1502 of file Brie.h.
value_t
template<unsigned BITS = 4> using souffle::SparseBitMap< BITS >::value_t = uint64_t private
Definition at line 1454 of file Brie.h.
Constructor & Destructor Documentation
SparseBitMap() [1/3]
template<unsigned BITS = 4> souffle::SparseBitMap< BITS >::SparseBitMap () default
SparseBitMap() [2/3]
template<unsigned BITS = 4> souffle::SparseBitMap< BITS >::SparseBitMap (const SparseBitMap< BITS > &) default
SparseBitMap() [3/3]
template<unsigned BITS = 4> souffle::SparseBitMap< BITS >::SparseBitMap (SparseBitMap< BITS > &&) default
Member Function Documentation
addAll()
template<unsigned BITS = 4> void souffle::SparseBitMap< BITS >::addAll (const SparseBitMap< BITS > & other) inline
Sets all bits set in other to 1 within this bit map.
Definition at line 1603 of file Brie.h.
Referenced by souffle::Trie< 1u >::insertAll().
{
         // nothing to do if it is a self-assignment
         if (this == &other) return;
         // merge the sparse store
         store.addAll(other.store);
     }
begin()
template<unsigned BITS = 4> iterator souffle::SparseBitMap< BITS >::begin () const inline
Obtains an iterator pointing to the first index set to 1.
If there is no such bit, end() will be returned.
Definition at line 1731 of file Brie.h.
Referenced by souffle::Trie< 1u >::begin(), souffle::Trie< 1u >::getBeginCoreIterator(), souffle::detail::fix_first< Pos, Dim >::operator()(), souffle::detail::fix_binding< 0, Pos, Dim >::operator()(), and souffle::Trie< 1u >::partition().
{
         auto it = store.begin();
         if (it.isEnd()) return end();
         return iterator(it);
     }
clear()
template<unsigned BITS = 4> void souffle::SparseBitMap< BITS >::clear () inline
Resets all contained bits to 0.
Definition at line 1576 of file Brie.h.
Referenced by souffle::Trie< 1u >::clear().
                  {
         store.clear();
     }
dump()
template<unsigned BITS = 4> void souffle::SparseBitMap< BITS >::dump (bool detail = false, std::ostream & out = std::cout) const inline
A debugging utility printing the internal structure of this map to the given output stream.
Definition at line 1821 of file Brie.h.
{
         store.dump(detail, out);
     }
empty()
template<unsigned BITS = 4> bool souffle::SparseBitMap< BITS >::empty () const inline
Definition at line 1497 of file Brie.h.
Referenced by souffle::Trie< 1u >::begin(), and souffle::Trie< 1u >::empty().
{
         return store.empty();
     }
end()
template<unsigned BITS = 4> iterator souffle::SparseBitMap< BITS >::end () const inline
Returns an iterator referencing the position after the last set bit.
Definition at line 1740 of file Brie.h.
Referenced by souffle::Trie< 1u >::getBoundaries(), souffle::detail::fix_binding< Len, Pos, Dim >::operator()(), souffle::detail::fix_lower_bound< Pos, Dim >::operator()(), souffle::detail::fix_upper_bound< Pos, Dim >::operator()(), souffle::Trie< 1u >::partition(), and souffle::TEST().
{
         return iterator();
     }
find() [1/2]
template<unsigned BITS = 4> iterator souffle::SparseBitMap< BITS >::find (index_type i) const inline
Obtains an iterator referencing the position i if the corresponding bit is set, end() otherwise.
Definition at line 1748 of file Brie.h.
Referenced by souffle::Trie< 1u >::getBoundaries(), souffle::detail::fix_binding< Len, Pos, Dim >::operator()(), and souffle::TEST().
{
         op_context ctxt;
         return find(i, ctxt);
     }
find() [2/2]
template<unsigned BITS = 4> iterator souffle::SparseBitMap< BITS >::find (index_type i, op_context & ctxt) const inline
Obtains an iterator referencing the position i if the corresponding bit is set, end() otherwise.
An operation context can be provided to exploit temporal locality.
Definition at line 1758 of file Brie.h.
{
         // check prefix part
         auto it = store.find(i >> LEAF_INDEX_WIDTH, ctxt);
         if (it.isEnd()) return end();
         // check bit-set part
         uint64_t mask = iterator::toMask(it->second);
         if (!(mask & (1llu << (i & LEAF_INDEX_MASK)))) return end();
         // OK, it is there => create iterator
         mask &= ((1ull << (i & LEAF_INDEX_MASK)) - 1);  // remove all bits before pos i
         return iterator(it, mask, i);
     }
getMemoryUsage()
template<unsigned BITS = 4> std::size_t souffle::SparseBitMap< BITS >::getMemoryUsage () const inline
Computes the total memory usage of this data structure.
Definition at line 1595 of file Brie.h.
Referenced by souffle::Trie< 1u >::getMemoryUsage().
{
         // compute the total memory usage
         return sizeof(*this) - sizeof(data_store_t) + store.getMemoryUsage();
     }
getStore()
template<unsigned BITS = 4> const data_store_t& souffle::SparseBitMap< BITS >::getStore () const inline
Provides write-protected access to the internal store for running analysis on the data structure.
Definition at line 1829 of file Brie.h.
{
         return store;
     }
lower_bound()
template<unsigned BITS = 4> iterator souffle::SparseBitMap< BITS >::lower_bound (index_type i) const inline
Locates an iterator to the first element in this sparse bit map not less than the given index.
Definition at line 1776 of file Brie.h.
Referenced by souffle::Trie< 1u >::lower_bound(), and souffle::detail::fix_lower_bound< Pos, Dim >::operator()().
{
         auto it = store.lowerBound(i >> LEAF_INDEX_WIDTH);
         if (it.isEnd()) return end();
         // check bit-set part
         uint64_t mask = iterator::toMask(it->second);
         // if there is no bit remaining in this mask, check next mask.
         if (!(mask & ((~uint64_t(0)) << (i & LEAF_INDEX_MASK)))) {
             index_type next = ((i >> LEAF_INDEX_WIDTH) + 1) << LEAF_INDEX_WIDTH;
             if (next < i) return end();
             return lower_bound(next);
         }
         // there are bits left, use least significant bit of those
         if (it->first == i >> LEAF_INDEX_WIDTH) {
             mask &= ((~uint64_t(0)) << (i & LEAF_INDEX_MASK));  // remove all bits before pos i
         }
         // compute value represented by least significant bit
         index_type pos = __builtin_ctzll(mask);
         // remove this bit as well
         mask = mask & ~(1ull << pos);
         // construct value of this located bit
         index_type val = (it->first << LEAF_INDEX_WIDTH) | pos;
         return iterator(it, mask, val);
     }
operator=() [1/2]
template<unsigned BITS = 4> SparseBitMap& souffle::SparseBitMap< BITS >::operator= (const SparseBitMap< BITS > &) default
operator=() [2/2]
template<unsigned BITS = 4> SparseBitMap& souffle::SparseBitMap< BITS >::operator= (SparseBitMap< BITS > &&) default
operator[]()
template<unsigned BITS = 4> bool souffle::SparseBitMap< BITS >::operator[] (index_type i) const inline
Determines the whether the bit addressed by i is set or not.
Definition at line 1569 of file Brie.h.
{
         return test(i);
     }
set() [1/2]
template<unsigned BITS = 4> bool souffle::SparseBitMap< BITS >::set (index_type i) inline
Sets the bit addressed by i to 1.
Definition at line 1507 of file Brie.h.
Referenced by souffle::Trie< 1u >::insert_internal(), and souffle::TEST().
{
         op_context ctxt;
         return set(i, ctxt);
     }
set() [2/2]
template<unsigned BITS = 4> bool souffle::SparseBitMap< BITS >::set (index_type i, op_context & ctxt) inline
Sets the bit addressed by i to 1.
A context for exploiting temporal locality can be provided.
Definition at line 1516 of file Brie.h.
{
         atomic_value_t& val = store.getAtomic(i >> LEAF_INDEX_WIDTH, ctxt);
         value_t bit = (1ull << (i & LEAF_INDEX_MASK));
 #ifdef __GNUC__
 #if __GNUC__ >= 7
         // In GCC >= 7 the usage of fetch_or causes a bug that needs further investigation
         // For now, this two-instruction based implementation provides a fix that does
         // not sacrifice too much performance.
         while (true) {
             auto order = std::memory_order::memory_order_relaxed;
             // load current value
             value_t old = val.load(order);
             // if bit is already set => we are done
             if (old & bit) return false;
             // set the bit, if failed, repeat
             if (!val.compare_exchange_strong(old, old | bit, order, order)) continue;
             // it worked, new bit added
             return true;
         }
 #endif
 #endif
         value_t old = val.fetch_or(bit, std::memory_order::memory_order_relaxed);
         return (old & bit) == 0u;
     }
size()
template<unsigned BITS = 4> std::size_t souffle::SparseBitMap< BITS >::size () const inline
Determines the number of bits set.
Definition at line 1583 of file Brie.h.
Referenced by souffle::Trie< 1u >::partition(), souffle::Trie< 1u >::size(), and souffle::TEST().
{
         // this is computed on demand to keep the set operation simple.
         std::size_t res = 0;
         for (const auto& cur : store) {
             res += __builtin_popcountll(cur.second);
         }
         return res;
     }
test() [1/2]
template<unsigned BITS = 4> bool souffle::SparseBitMap< BITS >::test (index_type i) const inline
Determines the whether the bit addressed by i is set or not.
Definition at line 1552 of file Brie.h.
Referenced by souffle::Trie< 1u >::contains_internal(), and souffle::TEST().
{
         op_context ctxt;
         return test(i, ctxt);
     }
test() [2/2]
template<unsigned BITS = 4> bool souffle::SparseBitMap< BITS >::test (index_type i, op_context & ctxt) const inline
Determines the whether the bit addressed by i is set or not.
A context for exploiting temporal locality can be provided.
Definition at line 1561 of file Brie.h.
{
         value_t bit = (1ull << (i & LEAF_INDEX_MASK));
         return store.lookup(i >> LEAF_INDEX_WIDTH, ctxt) & bit;
     }
upper_bound()
template<unsigned BITS = 4> iterator souffle::SparseBitMap< BITS >::upper_bound (index_type i) const inline
Locates an iterator to the first element in this sparse bit map than is greater than the given index.
Definition at line 1810 of file Brie.h.
Referenced by souffle::detail::fix_upper_bound< Pos, Dim >::operator()(), and souffle::Trie< 1u >::upper_bound().
{
         if (i == std::numeric_limits<index_type>::max()) {
             return end();
         }
         return lower_bound(i + 1);
     }
Field Documentation
BITS_PER_ENTRY
template<unsigned BITS = 4> constexpr short souffle::SparseBitMap< BITS >::BITS_PER_ENTRY = sizeof(value_t) * 8 static private
Definition at line 1468 of file Brie.h.
LEAF_INDEX_MASK
template<unsigned BITS = 4> constexpr uint64_t souffle::SparseBitMap< BITS >::LEAF_INDEX_MASK = BITS_PER_ENTRY - 1 static private
Definition at line 1470 of file Brie.h.
LEAF_INDEX_WIDTH
template<unsigned BITS = 4> constexpr short souffle::SparseBitMap< BITS >::LEAF_INDEX_WIDTH = static_cast<short>(__builtin_ctz(BITS_PER_ENTRY)) static private
Definition at line 1469 of file Brie.h.
store
template<unsigned BITS = 4> data_store_t souffle::SparseBitMap< BITS >::store private
Definition at line 1478 of file Brie.h.
Referenced by souffle::SparseBitMap<>::addAll().
The documentation for this class was generated from the following file:
Brie.h