souffle: souffle::TestMaxMatching Class Reference
souffle::TestMaxMatching Class Reference
Public Member Functions
TestMaxMatching ()
Public Member Functions inherited from souffle::MaxMatching
void addEdge (Node u, Node v)
add an edge to the bi-partite graph
int getNumMatchings () const
get number of matches in the solution
const Matchings & solve ()
solve the maximum matching problem
Additional Inherited Members
Public Types inherited from souffle::MaxMatching
using Distance = int
using Matchings = std::map< Node, Node, std::greater< Node > >
Matching represent a solution of the matching, i.e., which node in the bi-partite graph maps to another node.
using Node = uint32_t
using Nodes = std::set< Node, std::greater< Node > >
Data Fields inherited from souffle::MaxMatching
const Distance InfiniteDistance = -1
const Node NullVertex = 0
Protected Member Functions inherited from souffle::MaxMatching
bool bfSearch ()
perform a breadth first search in the graph
bool dfSearch (Node u)
perform a depth first search in the graph
Distance getDistance (Node v)
get distance of a node
Node getMatch (Node v)
get match for a search signature
Detailed Description
Definition at line 26 of file max_matching_test.cpp.
Constructor & Destructor Documentation
TestMaxMatching()
souffle::TestMaxMatching::TestMaxMatching () inline
Definition at line 28 of file max_matching_test.cpp.
References souffle::MaxMatching::addEdge(), EXPECT_EQ, souffle::MaxMatching::getNumMatchings(), souffle::MaxMatching::match, souffle::MaxMatching::solve(), and souffle::TEST().
 : MaxMatching() {}
The documentation for this class was generated from the following file:
tests/max_matching_test.cpp