souffle: souffle::ResolveAnonymousRecordsAliases Class Reference
souffle::ResolveAnonymousRecordsAliases Class Reference
Transformer resolving aliases for anonymous records.
#include <ResolveAnonymousRecordsAliases.h>
Public Member Functions
ResolveAnonymousRecordsAliases * clone () const override
std::string getName () const override
Public Member Functions inherited from souffle::AstTransformer
bool apply (AstTranslationUnit &translationUnit)
virtual ~AstTransformer ()=default
Private Member Functions
std::map< std::string, const AstRecordInit * > findVariablesRecordMapping (AstTranslationUnit &, const AstClause &)
For each variable equal to some anonymous record, assign a value of that record.
bool replaceNamedVariables (AstTranslationUnit &, AstClause &)
Use mapping found by findVariablesRecordMapping to substitute a records for each variable that operates on records.
bool replaceUnnamedVariable (AstClause &)
For unnamed variables, replace each equation _ op record with true.
bool transform (AstTranslationUnit &translationUnit) override
Detailed Description
Transformer resolving aliases for anonymous records.
The transformer works by searching the clause for equalities of the form a = [...], where a is an anonymous record, and replacing all occurrences of a with the RHS.
The transformer is to be called in conjunction with FoldAnonymousRecords.
Definition at line 36 of file ResolveAnonymousRecordsAliases.h.
Member Function Documentation
clone()
ResolveAnonymousRecordsAliases* souffle::ResolveAnonymousRecordsAliases::clone () const inline override virtual
Implements souffle::AstTransformer.
Definition at line 42 of file ResolveAnonymousRecordsAliases.h.
References findVariablesRecordMapping(), replaceNamedVariables(), replaceUnnamedVariable(), and transform().
{
         return new ResolveAnonymousRecordsAliases();
     }
findVariablesRecordMapping()
std::map< std::string, const AstRecordInit * > souffle::ResolveAnonymousRecordsAliases::findVariablesRecordMapping (AstTranslationUnit & tu, const AstClause & clause) private
For each variable equal to some anonymous record, assign a value of that record.
Definition at line 40 of file ResolveAnonymousRecordsAliases.cpp.
References souffle::AstTranslationUnit::getAnalysis(), souffle::AstClause::getBodyLiterals(), souffle::getGroundedTerms(), souffle::AstVariable::getName(), and souffle::isEqConstraint().
Referenced by clone(), and replaceNamedVariables().
{
     std::map<std::string, const AstRecordInit*> variableRecordMap;
     auto isVariable = [](AstNode* node) -> bool { return dynamic_cast<AstVariable*>(node) != nullptr; };
     auto isRecord = [](AstNode* node) -> bool { return dynamic_cast<AstRecordInit*>(node) != nullptr; };
     auto& typeAnalysis = *tu.getAnalysis<TypeAnalysis>();
     auto groundedTerms = getGroundedTerms(tu, clause);
     for (auto* literal : clause.getBodyLiterals()) {
         if (auto constraint = dynamic_cast<AstBinaryConstraint*>(literal)) {
             if (!isEqConstraint(constraint->getOperator())) {
                 continue;
             }
             auto left = constraint->getLHS();
             auto right = constraint->getRHS();
             if (!isVariable(left) && !isVariable(right)) {
                 continue;
             }
             if (!isRecord(left) && !isRecord(right)) {
                 continue;
             }
             // TODO (darth_tytus): This should change in the future.
             // Currently type system assigns to anonymous records {- All types - }
             // which is inelegant.
             if (!typeAnalysis.getTypes(left).isAll()) {
                 continue;
             }
             auto* variable = static_cast<AstVariable*>(isVariable(left) ? left : right);
             const auto& variableName = variable->getName();
             if (!groundedTerms.find(variable)->second) {
                 continue;
             }
             // We are interested only in the first mapping.
             if (variableRecordMap.find(variableName) != variableRecordMap.end()) {
                 continue;
             }
             auto* record = static_cast<AstRecordInit*>(isRecord(left) ? left : right);
             variableRecordMap.insert({variableName, record});
         }
     }
     return variableRecordMap;
 }
getName()
std::string souffle::ResolveAnonymousRecordsAliases::getName () const inline override virtual
Implements souffle::AstTransformer.
Definition at line 38 of file ResolveAnonymousRecordsAliases.h.
{
         return "FoldAnonymousRecords";
     }
replaceNamedVariables()
bool souffle::ResolveAnonymousRecordsAliases::replaceNamedVariables (AstTranslationUnit & tu, AstClause & clause) private
Use mapping found by findVariablesRecordMapping to substitute a records for each variable that operates on records.
Definition at line 95 of file ResolveAnonymousRecordsAliases.cpp.
References souffle::AstClause::apply(), souffle::clone(), and findVariablesRecordMapping().
Referenced by clone(), and transform().
{
     struct ReplaceVariables : public AstNodeMapper {
         std::map<std::string, const AstRecordInit*> varToRecordMap;
         ReplaceVariables(std::map<std::string, const AstRecordInit*> varToRecordMap)
                 : varToRecordMap(std::move(varToRecordMap)){};
         std::unique_ptr<AstNode> operator()(std::unique_ptr<AstNode> node) const override {
             if (auto variable = dynamic_cast<AstVariable*>(node.get())) {
                 auto iteratorToRecord = varToRecordMap.find(variable->getName());
                 if (iteratorToRecord != varToRecordMap.end()) {
                     return souffle::clone(iteratorToRecord->second);
                 }
             }
             node->apply(*this);
             return node;
         }
     };
     auto variableToRecordMap = findVariablesRecordMapping(tu, clause);
     bool changed = variableToRecordMap.size() > 0;
     if (changed) {
         ReplaceVariables update(std::move(variableToRecordMap));
         clause.apply(update);
     }
     return changed;
 }
replaceUnnamedVariable()
bool souffle::ResolveAnonymousRecordsAliases::replaceUnnamedVariable (AstClause & clause) private
For unnamed variables, replace each equation _ op record with true.
Definition at line 125 of file ResolveAnonymousRecordsAliases.cpp.
References souffle::AstClause::apply(), and souffle::isEqConstraint().
Referenced by clone(), and transform().
{
     struct ReplaceUnnamed : public AstNodeMapper {
         mutable bool changed{false};
         ReplaceUnnamed() = default;
         std::unique_ptr<AstNode> operator()(std::unique_ptr<AstNode> node) const override {
             auto isUnnamed = [](AstNode* node) -> bool {
                 return dynamic_cast<AstUnnamedVariable*>(node) != nullptr;
             };
             auto isRecord = [](AstNode* node) -> bool {
                 return dynamic_cast<AstRecordInit*>(node) != nullptr;
             };
             if (auto constraint = dynamic_cast<AstBinaryConstraint*>(node.get())) {
                 auto left = constraint->getLHS();
                 auto right = constraint->getRHS();
                 bool hasUnnamed = isUnnamed(left) || isUnnamed(right);
                 bool hasRecord = isRecord(left) || isRecord(right);
                 auto op = constraint->getOperator();
                 if (hasUnnamed && hasRecord && isEqConstraint(op)) {
                     return std::make_unique<AstBooleanConstraint>(true);
                 }
             }
             node->apply(*this);
             return node;
         }
     };
     ReplaceUnnamed update;
     clause.apply(update);
     return update.changed;
 }
transform()
bool souffle::ResolveAnonymousRecordsAliases::transform (AstTranslationUnit & translationUnit) override private virtual
Implements souffle::AstTransformer.
Definition at line 161 of file ResolveAnonymousRecordsAliases.cpp.
References souffle::AstProgram::getClauses(), souffle::AstTranslationUnit::getProgram(), replaceNamedVariables(), and replaceUnnamedVariable().
Referenced by clone().
{
     bool changed = false;
     for (auto* clause : translationUnit.getProgram()->getClauses()) {
         changed |= replaceNamedVariables(translationUnit, *clause);
         changed |= replaceUnnamedVariable(*clause);
     }
     return changed;
 }
The documentation for this class was generated from the following files:
ast/transform/ResolveAnonymousRecordsAliases.h
ast/transform/ResolveAnonymousRecordsAliases.cpp