souffle: souffle::MaxMatching Class Reference
souffle::MaxMatching Class Reference
Computes a maximum matching with Hopcroft-Karp algorithm
#include <IndexAnalysis.h>
Public Types
using Distance = int
using Matchings = std::map< Node, Node, std::greater< Node > >
Matching represent a solution of the matching, i.e., which node in the bi-partite graph maps to another node.
using Node = uint32_t
using Nodes = std::set< Node, std::greater< Node > >
Public Member Functions
void addEdge (Node u, Node v)
add an edge to the bi-partite graph
int getNumMatchings () const
get number of matches in the solution
const Matchings & solve ()
solve the maximum matching problem
Data Fields
const Distance InfiniteDistance = -1
const Node NullVertex = 0
Protected Member Functions
bool bfSearch ()
perform a breadth first search in the graph
bool dfSearch (Node u)
perform a depth first search in the graph
Distance getDistance (Node v)
get distance of a node
Node getMatch (Node v)
get match for a search signature
Private Types
using DistanceMap = std::map< Node, Distance >
distance function of nodes
using Edges = std::set< Node >
Edges in the bi-partite graph.
using Graph = std::map< Node, Edges >
Bi-partite graph of instance.
Private Attributes
DistanceMap distance
Graph graph
Matchings match
Detailed Description
Computes a maximum matching with Hopcroft-Karp algorithm
This class is a helper class for RamIndexAnalysis.
This implements a standard maximum matching algorithm for a bi-partite graph also known as a marriage problem. Given a set of edges in a bi-partite graph select a subset of edges that each node in the bi-partite graph has at most one adjacent edge associated with.
The nodes of the bi-partite graph represent index-signatures stemming from RAM operations and RAM existence checks for a relation. A relation between two nodes represent whether an index operation subsumes another operation.
Source: http://en.wikipedia.org/wiki/Hopcroft%E2%80%93Karp_algorithm#Pseudocode
Definition at line 183 of file IndexAnalysis.h.
Member Typedef Documentation
Distance
using souffle::MaxMatching::Distance = int
Definition at line 189 of file IndexAnalysis.h.
DistanceMap
using souffle::MaxMatching::DistanceMap = std::map<Node, Distance> private
distance function of nodes
Definition at line 259 of file IndexAnalysis.h.
Edges
using souffle::MaxMatching::Edges = std::set<Node> private
Edges in the bi-partite graph.
Definition at line 251 of file IndexAnalysis.h.
Graph
using souffle::MaxMatching::Graph = std::map<Node, Edges> private
Bi-partite graph of instance.
Definition at line 255 of file IndexAnalysis.h.
Matchings
using souffle::MaxMatching::Matchings = std::map<Node, Node, std::greater<Node> >
Matching represent a solution of the matching, i.e., which node in the bi-partite graph maps to another node.
If no map exist for a node, there is no adjacent edge exists for that node.
Definition at line 195 of file IndexAnalysis.h.
Node
using souffle::MaxMatching::Node = uint32_t
Definition at line 185 of file IndexAnalysis.h.
Nodes
using souffle::MaxMatching::Nodes = std::set<Node, std::greater<Node> >
Definition at line 187 of file IndexAnalysis.h.
Member Function Documentation
addEdge()
void souffle::MaxMatching::addEdge (Node u, Node v)
add an edge to the bi-partite graph
Parameters
u search signature
v subsuming search signature
Definition at line 37 of file IndexAnalysis.cpp.
References graph.
Referenced by souffle::TestMaxMatching::TestMaxMatching().
{
     assert(u >= 1 && v >= 1 && "Nodes must be greater than or equal to 1");
     if (graph.find(u) == graph.end()) {
         Edges vals;
         vals.insert(v);
         graph.insert(make_pair(u, vals));
     } else {
         graph[u].insert(v);
     }
 }
bfSearch()
bool souffle::MaxMatching::bfSearch () protected
perform a breadth first search in the graph
Definition at line 64 of file IndexAnalysis.cpp.
References distance, getDistance(), getMatch(), graph, InfiniteDistance, and NullVertex.
Referenced by solve().
{
     Node u;
     std::queue<Node> bfQueue;
     // Build layers
     for (auto& it : graph) {
         if (getMatch(it.first) == NullVertex) {
             distance[it.first] = 0;
             bfQueue.push(it.first);
         } else {
             distance[it.first] = InfiniteDistance;
         }
     }
     distance[NullVertex] = InfiniteDistance;
     while (!bfQueue.empty()) {
         u = bfQueue.front();
         bfQueue.pop();
         assert(u != NullVertex);
         const Edges& children = graph[u];
         for (auto it : children) {
             Node mv = getMatch(it);
             if (getDistance(mv) == InfiniteDistance) {
                 distance[mv] = getDistance(u) + 1;
                 if (mv != NullVertex) {
                     bfQueue.push(mv);
                 }
             }
         }
     }
     return (getDistance(NullVertex) != InfiniteDistance);
 }
dfSearch()
bool souffle::MaxMatching::dfSearch (Node u) protected
perform a depth first search in the graph
Parameters
u search signature
Definition at line 96 of file IndexAnalysis.cpp.
References distance, getDistance(), getMatch(), graph, InfiniteDistance, and match.
Referenced by solve().
{
     if (u != 0) {
         Edges& children = graph[u];
         for (auto v : children) {
             if (getDistance(getMatch(v)) == getDistance(u) + 1) {
                 if (dfSearch(getMatch(v))) {
                     match[u] = v;
                     match[v] = u;
                     return true;
                 }
             }
         }
         distance[u] = InfiniteDistance;
         return false;
     }
     return true;
 }
getDistance()
MaxMatching::Distance souffle::MaxMatching::getDistance (Node v) protected
get distance of a node
Definition at line 56 of file IndexAnalysis.cpp.
References distance, and InfiniteDistance.
Referenced by bfSearch(), and dfSearch().
{
     auto it = distance.find(v);
     if (it == distance.end()) {
         return InfiniteDistance;
     }
     return it->second;
 }
getMatch()
MaxMatching::Node souffle::MaxMatching::getMatch (Node v) protected
get match for a search signature
Parameters
v search signature
Definition at line 48 of file IndexAnalysis.cpp.
References match, and NullVertex.
Referenced by bfSearch(), dfSearch(), and solve().
{
     auto it = match.find(v);
     if (it == match.end()) {
         return NullVertex;
     }
     return it->second;
 }
getNumMatchings()
int souffle::MaxMatching::getNumMatchings () const inline
get number of matches in the solution
Returns
number of matches
Definition at line 213 of file IndexAnalysis.h.
Referenced by souffle::TestAutoIndex::getNumMatchings(), and souffle::TestMaxMatching::TestMaxMatching().
{
         return match.size() / 2;
     }
solve()
const MaxMatching::Matchings & souffle::MaxMatching::solve ()
solve the maximum matching problem
Returns
returns the matching
Definition at line 115 of file IndexAnalysis.cpp.
References bfSearch(), dfSearch(), getMatch(), graph, match, and NullVertex.
Referenced by souffle::TestMaxMatching::TestMaxMatching().
{
     while (bfSearch()) {
         for (auto& it : graph) {
             if (getMatch(it.first) == NullVertex) {
                 dfSearch(it.first);
             }
         }
     }
     return match;
 }
Field Documentation
distance
DistanceMap souffle::MaxMatching::distance private
Definition at line 263 of file IndexAnalysis.h.
Referenced by bfSearch(), dfSearch(), and getDistance().
graph
Graph souffle::MaxMatching::graph private
Definition at line 262 of file IndexAnalysis.h.
Referenced by addEdge(), bfSearch(), dfSearch(), and solve().
InfiniteDistance
const Distance souffle::MaxMatching::InfiniteDistance = -1
Definition at line 201 of file IndexAnalysis.h.
Referenced by bfSearch(), dfSearch(), and getDistance().
match
Matchings souffle::MaxMatching::match private
Definition at line 261 of file IndexAnalysis.h.
Referenced by dfSearch(), getMatch(), solve(), and souffle::TestMaxMatching::TestMaxMatching().
NullVertex
const Node souffle::MaxMatching::NullVertex = 0
Definition at line 198 of file IndexAnalysis.h.
Referenced by bfSearch(), getMatch(), and solve().
The documentation for this class was generated from the following files:
ram/analysis/IndexAnalysis.h
ram/analysis/IndexAnalysis.cpp