souffle: souffle::TypeAnalysis Class Reference
souffle::TypeAnalysis Class Reference
#include <Type.h>
Public Member Functions
TypeSet const & getTypes (const AstArgument *argument) const
Get the computed types for the given argument.
void print (std::ostream &os) const override
print the analysis result in HTML format
void run (const AstTranslationUnit &translationUnit) override
run analysis for a Ast translation unit
TypeAnalysis ()
Public Member Functions inherited from souffle::AstAnalysis
AstAnalysis (std::string identifier)
virtual const std::string & getName () const
get name of the analysis
virtual ~AstAnalysis ()=default
Static Public Member Functions
static std::map< const AstArgument *, TypeSet > analyseTypes (const TypeEnvironment &, const AstClause &, const AstProgram &, std::ostream *=nullptr)
Analyse the given clause and computes for each contained argument a set of potential types.
Static Public Attributes
static constexpr const char * name = "type-analysis"
Private Attributes
std::stringstream analysisLogs
std::vector< std::unique_ptr< AstClause > > annotatedClauses
std::map< const AstArgument *, TypeSet > argumentTypes
Additional Inherited Members
Protected Attributes inherited from souffle::AstAnalysis
const std::string identifier
Detailed Description
Definition at line 34 of file Type.h.
Constructor & Destructor Documentation
TypeAnalysis()
souffle::TypeAnalysis::TypeAnalysis () inline
Definition at line 38 of file Type.h.
References print(), and run().
 : AstAnalysis(name) {}
Member Function Documentation
analyseTypes()
std::map< const AstArgument *, TypeSet > souffle::TypeAnalysis::analyseTypes (const TypeEnvironment & typeEnv, const AstClause & clause, const AstProgram & program, std::ostream * logs = nullptr) static
Analyse the given clause and computes for each contained argument a set of potential types.
If the set associated to an argument is empty, no consistent typing can be found and the rule can not be properly typed.
Parameters
env a typing environment describing the set of available types
clause the clause to be typed
program the program
Returns
a map mapping each contained argument to a a set of types
Definition at line 766 of file Type.cpp.
References souffle::AstConstraintAnalysis< AnalysisVar >::analyse().
Referenced by getTypes(), and souffle::MaterializeAggregationQueriesTransformer::materializeAggregationQueries().
{
     return TypeConstraintsAnalysis(typeEnv, program).analyse(clause, logs);
 }
getTypes()
TypeSet const& souffle::TypeAnalysis::getTypes (const AstArgument * argument) const inline
Get the computed types for the given argument.
Definition at line 47 of file Type.h.
References analyseTypes(), and argumentTypes.
Referenced by souffle::PolymorphicObjectsTransformer::transform(), souffle::validOverloads(), souffle::TypeChecker::visitAggregator(), souffle::TypeChecker::visitAtom(), souffle::TypeChecker::visitBinaryConstraint(), souffle::TypeChecker::visitNilConstant(), souffle::TypeChecker::visitNumericConstant(), souffle::TypeChecker::visitRecordInit(), souffle::TypeChecker::visitStringConstant(), souffle::TypeChecker::visitTypeCast(), souffle::TypeChecker::visitUserDefinedFunctor(), and souffle::TypeChecker::visitVariable().
{
         return argumentTypes.at(argument);
     }
print()
void souffle::TypeAnalysis::print (std::ostream &) const override virtual
print the analysis result in HTML format
Reimplemented from souffle::AstAnalysis.
Definition at line 771 of file Type.cpp.
Referenced by TypeAnalysis().
{
     os << "-- Analysis logs --" << std::endl;
     os << analysisLogs.str() << std::endl;
     os << "-- Result --" << std::endl;
     for (const auto& cur : annotatedClauses) {
         os << *cur << std::endl;
     }
 }
run()
void souffle::TypeAnalysis::run (const AstTranslationUnit &) override virtual
run analysis for a Ast translation unit
Implements souffle::AstAnalysis.
Definition at line 780 of file Type.cpp.
References souffle::Global::config(), souffle::createAnnotatedClause(), souffle::AstTranslationUnit::getAnalysis(), souffle::AstProgram::getClauses(), and souffle::AstTranslationUnit::getProgram().
Referenced by TypeAnalysis().
{
     // Check if debugging information is being generated
     std::ostream* debugStream = nullptr;
     if (Global::config().has("debug-report") || Global::config().has("show", "type-analysis")) {
         debugStream = &analysisLogs;
     }
     const auto& program = *translationUnit.getProgram();
     auto& typeEnv = translationUnit.getAnalysis<TypeEnvironmentAnalysis>()->getTypeEnvironment();
     // Analyse types, clause by clause.
     for (const AstClause* clause : program.getClauses()) {
         auto clauseArgumentTypes = analyseTypes(typeEnv, *clause, program, debugStream);
         argumentTypes.insert(clauseArgumentTypes.begin(), clauseArgumentTypes.end());
         if (debugStream != nullptr) {
             // Store an annotated clause for printing purposes
             annotatedClauses.emplace_back(createAnnotatedClause(clause, clauseArgumentTypes));
         }
     }
 }
Field Documentation
analysisLogs
std::stringstream souffle::TypeAnalysis::analysisLogs private
Definition at line 67 of file Type.h.
annotatedClauses
std::vector<std::unique_ptr<AstClause> > souffle::TypeAnalysis::annotatedClauses private
Definition at line 66 of file Type.h.
argumentTypes
std::map<const AstArgument*, TypeSet> souffle::TypeAnalysis::argumentTypes private
Definition at line 65 of file Type.h.
Referenced by getTypes().
name
constexpr const char* souffle::TypeAnalysis::name = "type-analysis" static
Definition at line 36 of file Type.h.
The documentation for this class was generated from the following files:
ast/analysis/Type.h
ast/analysis/Type.cpp