souffle: souffle::RamLevelAnalysis Class Reference
souffle::RamLevelAnalysis Class Reference
A Ram Analysis for determining the level of a expression/condition.
#include <LevelAnalysis.h>
Public Member Functions
int getLevel (const RamNode *value) const
Get level of a RAM expression/condition.
RamLevelAnalysis (const char *id)
void run (const RamTranslationUnit &) override
Run analysis for a RAM translation unit.
Public Member Functions inherited from souffle::RamAnalysis
virtual const std::string & getName () const
get name of the analysis
virtual void print (std::ostream &) const
Print the analysis result in HTML format.
RamAnalysis (const char *id)
virtual ~RamAnalysis ()=default
Static Public Attributes
static constexpr const char * name = "level-analysis"
Additional Inherited Members
Protected Attributes inherited from souffle::RamAnalysis
std::string identifier
name of analysis instance
Detailed Description
A Ram Analysis for determining the level of a expression/condition.
The expression is determined by the TupleElement of an expression/condition with the highest tuple-id number. Note in the implementation we assume that the tuple-id of RamTupleOperation operations are ordered, i.e., the most-outer loop has the smallest tuple-id and the most inner-loop has the largest tuple-id number.
If an expression/condition does not contain an TupleElement accessing an element of a tuple, the analysis yields -1 for denoting that the expression/condition can be executed outside of the loop-nest, i.e., the expression/condition is independent of data stemming from relations.
Definition at line 42 of file LevelAnalysis.h.
Constructor & Destructor Documentation
RamLevelAnalysis()
souffle::RamLevelAnalysis::RamLevelAnalysis (const char * id) inline
Definition at line 44 of file LevelAnalysis.h.
 : RamAnalysis(id) {}
Member Function Documentation
getLevel()
int souffle::RamLevelAnalysis::getLevel (const RamNode * value) const
Get level of a RAM expression/condition.
Definition at line 31 of file LevelAnalysis.cpp.
References b, souffle::fatal(), souffle::filter(), souffle::RamAbstractOperator::getArguments(), souffle::RamPackRecord::getArguments(), souffle::RamAbstractChoice::getCondition(), souffle::RamAbstractAggregate::getCondition(), souffle::RamAbstractConditional::getCondition(), souffle::RamAbstractAggregate::getExpression(), souffle::RamUnpackRecord::getExpression(), souffle::RamConjunction::getLHS(), souffle::RamConstraint::getLHS(), souffle::RamNegation::getOperand(), souffle::RamIndexOperation::getRangePattern(), souffle::RamConjunction::getRHS(), souffle::RamConstraint::getRHS(), souffle::RamTupleElement::getTupleId(), souffle::RamAbstractExistenceCheck::getValues(), souffle::RamProject::getValues(), souffle::RamSubroutineReturn::getValues(), and souffle::pack().
Referenced by souffle::MakeIndexTransformer::getLowerUpperExpression(), souffle::HoistAggregateTransformer::hoistAggregate(), souffle::HoistConditionsTransformer::hoistConditions(), souffle::ChoiceConversionTransformer::rewriteIndexScan(), souffle::ChoiceConversionTransformer::rewriteScan(), and run().
{
     // visitor
     class ValueLevelVisitor : public RamVisitor<int> {
     public:
         // number
         int visitConstant(const RamConstant&) override {
             return -1;
         }
         // true
         int visitTrue(const RamTrue&) override {
             return -1;
         }
         // false
         int visitFalse(const RamFalse&) override {
             return -1;
         }
         // tuple element access
         int visitTupleElement(const RamTupleElement& elem) override {
             return elem.getTupleId();
         }
         // scan
         int visitScan(const RamScan&) override {
             return -1;
         }
         // index scan
         int visitIndexScan(const RamIndexScan& indexScan) override {
             int level = -1;
             for (auto& index : indexScan.getRangePattern().first) {
                 level = std::max(level, visit(index));
             }
             for (auto& index : indexScan.getRangePattern().second) {
                 level = std::max(level, visit(index));
             }
             return level;
         }
         // choice
         int visitChoice(const RamChoice& choice) override {
             return std::max(-1, visit(choice.getCondition()));
         }
         // index choice
         int visitIndexChoice(const RamIndexChoice& indexChoice) override {
             int level = -1;
             for (auto& index : indexChoice.getRangePattern().first) {
                 level = std::max(level, visit(index));
             }
             for (auto& index : indexChoice.getRangePattern().second) {
                 level = std::max(level, visit(index));
             }
             return std::max(level, visit(indexChoice.getCondition()));
         }
         // aggregate
         int visitAggregate(const RamAggregate& aggregate) override {
             return std::max(visit(aggregate.getExpression()), visit(aggregate.getCondition()));
         }
         // index aggregate
         int visitIndexAggregate(const RamIndexAggregate& indexAggregate) override {
             int level = -1;
             for (auto& index : indexAggregate.getRangePattern().first) {
                 level = std::max(level, visit(index));
             }
             for (auto& index : indexAggregate.getRangePattern().second) {
                 level = std::max(level, visit(index));
             }
             level = std::max(visit(indexAggregate.getExpression()), level);
             return std::max(level, visit(indexAggregate.getCondition()));
         }
         // unpack record
         int visitUnpackRecord(const RamUnpackRecord& unpack) override {
             return visit(unpack.getExpression());
         }
         // filter
         int visitFilter(const RamFilter& filter) override {
             return visit(filter.getCondition());
         }
         // break
         int visitBreak(const RamBreak& b) override {
             return visit(b.getCondition());
         }
         // project
         int visitProject(const RamProject& project) override {
             int level = -1;
             for (auto& exp : project.getValues()) {
                 level = std::max(level, visit(exp));
             }
             return level;
         }
         // return
         int visitSubroutineReturn(const RamSubroutineReturn& ret) override {
             int level = -1;
             for (auto& exp : ret.getValues()) {
                 level = std::max(level, visit(exp));
             }
             return level;
         }
         // auto increment
         int visitAutoIncrement(const RamAutoIncrement&) override {
             return -1;
         }
         // undef value
         int visitUndefValue(const RamUndefValue&) override {
             return -1;
         }
         // intrinsic functors
         int visitIntrinsicOperator(const RamIntrinsicOperator& op) override {
             int level = -1;
             for (const auto& arg : op.getArguments()) {
                 level = std::max(level, visit(arg));
             }
             return level;
         }
         // pack operator
         int visitPackRecord(const RamPackRecord& pack) override {
             int level = -1;
             for (const auto& arg : pack.getArguments()) {
                 level = std::max(level, visit(arg));
             }
             return level;
         }
         // argument
         int visitSubroutineArgument(const RamSubroutineArgument&) override {
             return -1;
         }
         // user defined operator
         int visitUserDefinedOperator(const RamUserDefinedOperator& op) override {
             int level = -1;
             for (const auto& arg : op.getArguments()) {
                 level = std::max(level, visit(arg));
             }
             return level;
         }
         // conjunction
         int visitConjunction(const RamConjunction& conj) override {
             return std::max(visit(conj.getLHS()), visit(conj.getRHS()));
         }
         // negation
         int visitNegation(const RamNegation& neg) override {
             return visit(neg.getOperand());
         }
         // constraint
         int visitConstraint(const RamConstraint& binRel) override {
             return std::max(visit(binRel.getLHS()), visit(binRel.getRHS()));
         }
         // existence check
         int visitExistenceCheck(const RamExistenceCheck& exists) override {
             int level = -1;
             for (const auto& cur : exists.getValues()) {
                 level = std::max(level, visit(cur));
             }
             return level;
         }
         // provenance existence check
         int visitProvenanceExistenceCheck(const RamProvenanceExistenceCheck& provExists) override {
             int level = -1;
             for (const auto& cur : provExists.getValues()) {
                 level = std::max(level, visit(cur));
             }
             return level;
         }
         // emptiness check
         int visitEmptinessCheck(const RamEmptinessCheck&) override {
             return -1;  // can be in the top level
         }
         // default rule
         int visitNode(const RamNode&) override {
             fatal("RamNode not implemented!");
         }
     };
     assert((dynamic_cast<const RamExpression*>(node) != nullptr ||
                    dynamic_cast<const RamCondition*>(node) != nullptr ||
                    dynamic_cast<const RamOperation*>(node) != nullptr) &&
             "not an expression/condition/operation");
     return ValueLevelVisitor().visit(node);
 }
run()
void souffle::RamLevelAnalysis::run (const RamTranslationUnit & translationUnit) inline override virtual
Run analysis for a RAM translation unit.
Implements souffle::RamAnalysis.
Definition at line 48 of file LevelAnalysis.h.
References getLevel().
 {}
Field Documentation
name
constexpr const char* souffle::RamLevelAnalysis::name = "level-analysis" static
Definition at line 46 of file LevelAnalysis.h.
The documentation for this class was generated from the following files:
ram/analysis/LevelAnalysis.h
ram/analysis/LevelAnalysis.cpp