souffle: souffle::RamIO Class Reference
souffle::RamIO Class Reference
I/O statement for a relation.
#include <Statement.h>
Public Member Functions
RamIO * clone () const override
Create a clone (i.e.
const std::string get (const std::string &key) const
value of I/O directive
const std::map< std::string, std::string > & getDirectives () const
get I/O directives
RamIO (std::unique_ptr< RamRelationReference > relRef, std::map< std::string, std::string > directives)
Public Member Functions inherited from souffle::RamRelationStatement
void apply (const RamNodeMapper &map) override
Apply the mapper to all child nodes.
std::vector< const RamNode * > getChildNodes () const override
Obtain list of all embedded child nodes.
const RamRelation & getRelation () const
Get RAM relation.
RamRelationStatement (std::unique_ptr< RamRelationReference > relRef)
Public Member Functions inherited from souffle::RamNode
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
virtual void rewrite (const RamNode *oldNode, std::unique_ptr< RamNode > newNode)
Rewrite a child node.
virtual ~RamNode ()=default
Protected Member Functions
bool equal (const RamNode &node) const override
Equality check for two RAM nodes.
void print (std::ostream &os, int tabpos) const override
Pretty print with indentation.
Protected Member Functions inherited from souffle::RamStatement
void print (std::ostream &os) const override
Print RAM node.
Protected Attributes
std::map< std::string, std::string > directives
IO directives.
Protected Attributes inherited from souffle::RamRelationStatement
std::unique_ptr< RamRelationReference > relationRef
Relation reference.
Additional Inherited Members
Static Protected Member Functions inherited from souffle::RamStatement
static void print (const RamStatement *statement, std::ostream &os, int tabpos)
Pretty print jump-bed.
Detailed Description
I/O statement for a relation.
I/O operation for a relation, e.g., input/output/printsize
Definition at line 103 of file Statement.h.
Constructor & Destructor Documentation
RamIO()
souffle::RamIO::RamIO (std::unique_ptr< RamRelationReference > relRef, std::map< std::string, std::string > directives) inline
Definition at line 105 of file Statement.h.
             : RamRelationStatement(std::move(relRef)), directives(std::move(directives)) {}
Member Function Documentation
clone()
RamIO* souffle::RamIO::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::RamStatement.
Definition at line 118 of file Statement.h.
References souffle::clone().
Referenced by souffle::test::TEST().
{
         return new RamIO(souffle::clone(relationRef), directives);
     }
equal()
bool souffle::RamIO::equal (const RamNode &) const inline override protected virtual
Equality check for two RAM nodes.
Default action is that nothing needs to be checked.
Reimplemented from souffle::RamRelationStatement.
Definition at line 133 of file Statement.h.
References souffle::RamRelationStatement::equal().
{
         const auto& other = static_cast<const RamIO&>(node);
         return RamRelationStatement::equal(other) && directives == other.directives;
     }
get()
const std::string souffle::RamIO::get (const std::string & key) const inline
value of I/O directive
Definition at line 114 of file Statement.h.
Referenced by souffle::Synthesiser::emitCode(), souffle::Synthesiser::generateCode(), and souffle::InterpreterProgInterface::InterpreterProgInterface().
{
         return directives.at(key);
     }
getDirectives()
const std::map<std::string, std::string>& souffle::RamIO::getDirectives () const inline
get I/O directives
Definition at line 109 of file Statement.h.
Referenced by souffle::Synthesiser::emitCode().
{
         return directives;
     }
print()
void souffle::RamIO::print (std::ostream & os, int tabpos) const inline override protected virtual
Pretty print with indentation.
Implements souffle::RamStatement.
Definition at line 123 of file Statement.h.
References souffle::escape(), souffle::RamRelation::getName(), souffle::getRelation(), souffle::join(), and souffle::times().
{
         const RamRelation& rel = getRelation();
         os << times(" ", tabpos);
         os << "IO " << rel.getName() << " (";
         os << join(directives, ",", [](std::ostream& out, const auto& arg) {
             out << arg.first << "=\"" << escape(arg.second) << "\"";
         });
         os << ")" << std::endl;
     };
Field Documentation
directives
std::map<std::string, std::string> souffle::RamIO::directives protected
IO directives.
Definition at line 139 of file Statement.h.
The documentation for this class was generated from the following file:
ram/Statement.h