souffle: souffle::AstBooleanConstraint Class Reference
souffle::AstBooleanConstraint Class Reference
Boolean Constraint.
#include <BooleanConstraint.h>
Public Member Functions
AstBooleanConstraint (bool truthValue, SrcLocation loc={})
AstBooleanConstraint * clone () const override
Create a clone (i.e.
bool isTrue () const
check whether constraint holds
void set (bool value)
set truth value
Public Member Functions inherited from souffle::AstNode
virtual void apply (const AstNodeMapper &)
Apply the mapper to all child nodes.
AstNode (SrcLocation loc={})
std::string extloc () const
Return source location of the syntactic element.
virtual std::vector< const AstNode * > getChildNodes () const
Obtain a list of all embedded AST child nodes.
const SrcLocation & getSrcLoc () const
Return source location of the AstNode.
bool operator!= (const AstNode &other) const
Inequality check for two AST nodes.
bool operator== (const AstNode &other) const
Equivalence check for two AST nodes.
void setSrcLoc (SrcLocation l)
Set source location for the AstNode.
virtual ~AstNode ()=default
Protected Member Functions
bool equal (const AstNode &node) const override
Abstract equality check for two AST nodes.
void print (std::ostream &os) const override
Output to a given output stream.
Protected Attributes
bool truthValue
truth value
Detailed Description
Boolean Constraint.
Representing either 'true' or 'false' values
Definition at line 34 of file BooleanConstraint.h.
Constructor & Destructor Documentation
AstBooleanConstraint()
souffle::AstBooleanConstraint::AstBooleanConstraint (bool truthValue, SrcLocation loc = {}) inline
Definition at line 36 of file BooleanConstraint.h.
References truthValue.
Referenced by clone().
                                                             {})
             : AstConstraint(std::move(loc)), truthValue(truthValue) {}
Member Function Documentation
clone()
AstBooleanConstraint* souffle::AstBooleanConstraint::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::AstConstraint.
Definition at line 49 of file BooleanConstraint.h.
References AstBooleanConstraint(), and souffle::AstNode::getSrcLoc().
{
         return new AstBooleanConstraint(truthValue, getSrcLoc());
     }
equal()
bool souffle::AstBooleanConstraint::equal (const AstNode &) const inline override protected virtual
Abstract equality check for two AST nodes.
Reimplemented from souffle::AstNode.
Definition at line 58 of file BooleanConstraint.h.
References truthValue.
{
         assert(nullptr != dynamic_cast<const AstBooleanConstraint*>(&node));
         const auto& other = static_cast<const AstBooleanConstraint&>(node);
         return truthValue == other.truthValue;
     }
isTrue()
bool souffle::AstBooleanConstraint::isTrue () const inline
check whether constraint holds
Definition at line 40 of file BooleanConstraint.h.
References truthValue.
{
         return truthValue;
     }
print()
void souffle::AstBooleanConstraint::print (std::ostream & os) const inline override protected virtual
Output to a given output stream.
Implements souffle::AstNode.
Definition at line 54 of file BooleanConstraint.h.
{
         os << (truthValue ? "true" : "false");
     }
set()
void souffle::AstBooleanConstraint::set (bool value) inline
set truth value
Definition at line 45 of file BooleanConstraint.h.
{
         truthValue = value;
     }
Field Documentation
truthValue
bool souffle::AstBooleanConstraint::truthValue protected
truth value
Definition at line 65 of file BooleanConstraint.h.
Referenced by AstBooleanConstraint(), equal(), and isTrue().
The documentation for this class was generated from the following file:
ast/BooleanConstraint.h