souffle: souffle::NameUnnamedVariablesTransformer Class Reference
souffle::NameUnnamedVariablesTransformer Class Reference
Transformation pass to replace unnamed variables with singletons.
#include <NameUnnamedVariables.h>
Public Member Functions
NameUnnamedVariablesTransformer * clone () const override
std::string getName () const override
Public Member Functions inherited from souffle::AstTransformer
bool apply (AstTranslationUnit &translationUnit)
virtual ~AstTransformer ()=default
Private Member Functions
bool transform (AstTranslationUnit &translationUnit) override
Detailed Description
Transformation pass to replace unnamed variables with singletons.
E.g.: a() :- b(_). -> a() :- b(x).
Definition at line 33 of file NameUnnamedVariables.h.
Member Function Documentation
clone()
NameUnnamedVariablesTransformer* souffle::NameUnnamedVariablesTransformer::clone () const inline override virtual
Implements souffle::AstTransformer.
Definition at line 39 of file NameUnnamedVariables.h.
References transform().
{
         return new NameUnnamedVariablesTransformer();
     }
getName()
std::string souffle::NameUnnamedVariablesTransformer::getName () const inline override virtual
Implements souffle::AstTransformer.
Definition at line 35 of file NameUnnamedVariables.h.
{
         return "NameUnnamedVariablesTransformer";
     }
transform()
bool souffle::NameUnnamedVariablesTransformer::transform (AstTranslationUnit & translationUnit) override private virtual
Implements souffle::AstTransformer.
Definition at line 32 of file NameUnnamedVariables.cpp.
References souffle::AstProgram::apply(), souffle::getClauses(), souffle::AstTranslationUnit::getProgram(), and souffle::AstProgram::getRelations().
Referenced by clone().
{
     bool changed = false;
     static constexpr const char* boundPrefix = "+underscore";
     static size_t underscoreCount = 0;
     struct nameVariables : public AstNodeMapper {
         mutable bool changed = false;
         nameVariables() = default;
         std::unique_ptr<AstNode> operator()(std::unique_ptr<AstNode> node) const override {
             if (dynamic_cast<AstUnnamedVariable*>(node.get()) != nullptr) {
                 changed = true;
                 std::stringstream name;
                 name << boundPrefix << "_" << underscoreCount++;
                 return std::make_unique<AstVariable>(name.str());
             }
             node->apply(*this);
             return node;
         }
     };
     AstProgram& program = *translationUnit.getProgram();
     for (AstRelation* rel : program.getRelations()) {
         for (AstClause* clause : getClauses(program, *rel)) {
             nameVariables update;
             clause->apply(update);
             changed |= update.changed;
         }
     }
     return changed;
 }
The documentation for this class was generated from the following files:
ast/transform/NameUnnamedVariables.h
ast/transform/NameUnnamedVariables.cpp