souffle: souffle::ComponentLookup Class Reference
souffle::ComponentLookup Class Reference
#include <ComponentLookup.h>
Public Member Functions
ComponentLookup ()
const AstComponent * getComponent (const AstComponent *scope, const std::string &name, const TypeBinding &activeBinding) const
Performs a lookup operation for a component with the given name within the addressed scope.
void run (const AstTranslationUnit &translationUnit) override
run analysis for a Ast translation unit
Public Member Functions inherited from souffle::AstAnalysis
AstAnalysis (std::string identifier)
virtual const std::string & getName () const
get name of the analysis
virtual void print (std::ostream &) const
print the analysis result in HTML format
virtual ~AstAnalysis ()=default
Static Public Attributes
static constexpr const char * name = "component-lookup"
Private Attributes
std::map< const AstComponent *, const AstComponent * > enclosingComponent
std::set< const AstComponent * > globalScopeComponents
std::map< const AstComponent *, std::set< const AstComponent * > > nestedComponents
Additional Inherited Members
Protected Attributes inherited from souffle::AstAnalysis
const std::string identifier
Detailed Description
Definition at line 76 of file ComponentLookup.h.
Constructor & Destructor Documentation
ComponentLookup()
souffle::ComponentLookup::ComponentLookup () inline
Definition at line 80 of file ComponentLookup.h.
 : AstAnalysis(name) {}
Member Function Documentation
getComponent()
const AstComponent * souffle::ComponentLookup::getComponent (const AstComponent * scope, const std::string & name, const TypeBinding & activeBinding) const
Performs a lookup operation for a component with the given name within the addressed scope.
Parameters
scope the component scope to lookup in (null for global scope)
name the name of the component to be looking for
Returns
a pointer to the obtained component or null if there is no such component.
Definition at line 42 of file ComponentLookup.cpp.
References souffle::AstQualifiedName::empty(), enclosingComponent, souffle::TypeBinding::find(), souffle::AstComponent::getComponents(), globalScopeComponents, name, and souffle::toString().
Referenced by souffle::AstComponentChecker::checkComponent(), and souffle::AstComponentChecker::checkComponentNameReference().
{
     // forward according to binding (we do not do this recursively on purpose)
     AstQualifiedName boundName = activeBinding.find(name);
     if (boundName.empty()) {
         // compName is not bound to anything => just just compName
         boundName = name;
     }
     // search nested scopes bottom up
     const AstComponent* searchScope = scope;
     while (searchScope != nullptr) {
         for (const AstComponent* cur : searchScope->getComponents()) {
             if (cur->getComponentType()->getName() == toString(boundName)) {
                 return cur;
             }
         }
         auto found = enclosingComponent.find(searchScope);
         if (found != enclosingComponent.end()) {
             searchScope = found->second;
         } else {
             searchScope = nullptr;
             break;
         }
     }
     // check global scope
     for (const AstComponent* cur : globalScopeComponents) {
         if (cur->getComponentType()->getName() == toString(boundName)) {
             return cur;
         }
     }
     // no such component in scope
     return nullptr;
 }
run()
void souffle::ComponentLookup::run (const AstTranslationUnit &) override virtual
run analysis for a Ast translation unit
Implements souffle::AstAnalysis.
Definition at line 27 of file ComponentLookup.cpp.
References enclosingComponent, souffle::AstComponent::getComponents(), souffle::AstProgram::getComponents(), souffle::AstTranslationUnit::getProgram(), globalScopeComponents, nestedComponents, and souffle::visitDepthFirst().
{
     const AstProgram* program = translationUnit.getProgram();
     for (AstComponent* component : program->getComponents()) {
         globalScopeComponents.insert(component);
         enclosingComponent[component] = nullptr;
     }
     visitDepthFirst(*program, [&](const AstComponent& cur) {
         nestedComponents[&cur];
         for (AstComponent* nestedComponent : cur.getComponents()) {
             nestedComponents[&cur].insert(nestedComponent);
             enclosingComponent[nestedComponent] = &cur;
         }
     });
 }
Field Documentation
enclosingComponent
std::map<const AstComponent*, const AstComponent*> souffle::ComponentLookup::enclosingComponent private
Definition at line 100 of file ComponentLookup.h.
Referenced by getComponent(), and run().
globalScopeComponents
std::set<const AstComponent*> souffle::ComponentLookup::globalScopeComponents private
Definition at line 96 of file ComponentLookup.h.
Referenced by getComponent(), and run().
name
constexpr const char* souffle::ComponentLookup::name = "component-lookup" static
Definition at line 78 of file ComponentLookup.h.
Referenced by getComponent().
nestedComponents
std::map<const AstComponent*, std::set<const AstComponent*> > souffle::ComponentLookup::nestedComponents private
Definition at line 98 of file ComponentLookup.h.
Referenced by run().
The documentation for this class was generated from the following files:
ast/analysis/ComponentLookup.h
ast/analysis/ComponentLookup.cpp