souffle: souffle::SynthesiserInfoRelation Class Reference
souffle::SynthesiserInfoRelation Class Reference
#include <SynthesiserRelation.h>
Public Member Functions
void computeIndices () override
Generate index set for a info relation, which should be empty.
void generateTypeStruct (std::ostream &out) override
Generate type struct of a info relation, which is empty, the actual implementation is in CompiledSouffle.h.
std::string getTypeName () override
Generate type name of a info relation.
SynthesiserInfoRelation (const RamRelation &ramRel, const MinIndexSelection &indexSet, bool isProvenance)
Public Member Functions inherited from souffle::SynthesiserRelation
size_t getArity () const
Get arity of relation.
const std::string & getDataStructure () const
Get data structure of relation.
MinIndexSelection::OrderCollection getIndices () const
Get list of indices used for relation, guaranteed that original indices in MinIndexSelection come before any generated indices.
const MinIndexSelection & getMinIndexSelection () const
Get stored MinIndexSelection.
std::set< int > getProvenenceIndexNumbers () const
const RamRelation & getRamRelation () const
Get stored RamRelation.
SynthesiserRelation (const RamRelation &rel, const MinIndexSelection &indices, const bool isProvenance=false)
virtual ~SynthesiserRelation ()=default
Additional Inherited Members
Static Public Member Functions inherited from souffle::SynthesiserRelation
static std::unique_ptr< SynthesiserRelation > getSynthesiserRelation (const RamRelation &ramRel, const MinIndexSelection &indexSet, bool isProvenance)
Factory method to generate a SynthesiserRelation.
Protected Attributes inherited from souffle::SynthesiserRelation
MinIndexSelection::OrderCollection computedIndices
The final list of indices used.
std::string dataStructure
The data structure used for the relation.
const MinIndexSelection & indices
Indices used for this relation.
const bool isProvenance
Is this relation used with provenance.
size_t masterIndex = -1
The number of the master index.
std::set< int > provenanceIndexNumbers
The list of indices added for provenance computation.
const RamRelation & relation
Ram relation referred to by this.
Detailed Description
Definition at line 107 of file SynthesiserRelation.h.
Constructor & Destructor Documentation
SynthesiserInfoRelation()
souffle::SynthesiserInfoRelation::SynthesiserInfoRelation (const RamRelation & ramRel, const MinIndexSelection & indexSet, bool isProvenance) inline
Definition at line 109 of file SynthesiserRelation.h.
References souffle::SynthesiserRelation::computeIndices(), souffle::SynthesiserRelation::generateTypeStruct(), and souffle::SynthesiserRelation::getTypeName().
             : SynthesiserRelation(ramRel, indexSet, isProvenance) {}
Member Function Documentation
computeIndices()
void souffle::SynthesiserInfoRelation::computeIndices () override virtual
Generate index set for a info relation, which should be empty.
Implements souffle::SynthesiserRelation.
Definition at line 62 of file SynthesiserRelation.cpp.
References souffle::SynthesiserRelation::computedIndices.
{
     computedIndices = {};
 }
generateTypeStruct()
void souffle::SynthesiserInfoRelation::generateTypeStruct (std::ostream & out) override virtual
Generate type struct of a info relation, which is empty, the actual implementation is in CompiledSouffle.h.
Implements souffle::SynthesiserRelation.
Definition at line 73 of file SynthesiserRelation.cpp.
{
     return;
 }
getTypeName()
std::string souffle::SynthesiserInfoRelation::getTypeName () override virtual
Generate type name of a info relation.
Implements souffle::SynthesiserRelation.
Definition at line 67 of file SynthesiserRelation.cpp.
References souffle::SynthesiserRelation::getArity().
{
     return "t_info<" + std::to_string(getArity()) + ">";
 }
The documentation for this class was generated from the following files:
synthesiser/SynthesiserRelation.h
synthesiser/SynthesiserRelation.cpp