souffle: souffle::ResolveAliasesTransformer Class Reference
souffle::ResolveAliasesTransformer Class Reference
Transformation pass to eliminate grounded aliases.
#include <ResolveAliases.h>
Public Member Functions
ResolveAliasesTransformer * clone () const override
std::string getName () const override
Public Member Functions inherited from souffle::AstTransformer
bool apply (AstTranslationUnit &translationUnit)
virtual ~AstTransformer ()=default
Static Public Member Functions
static std::unique_ptr< AstClause > removeComplexTermsInAtoms (const AstClause &clause)
Removes complex terms in atoms, replacing them with constrained variables.
static std::unique_ptr< AstClause > removeTrivialEquality (const AstClause &clause)
Removes trivial equalities of the form t = t from the given clause.
static std::unique_ptr< AstClause > resolveAliases (const AstClause &clause)
Converts the given clause into a version without variables aliasing grounded variables.
Private Member Functions
bool transform (AstTranslationUnit &translationUnit) override
Detailed Description
Transformation pass to eliminate grounded aliases.
e.g. resolve: a(r) , r = [x,y] => a(x,y) e.g. resolve: a(x) , !b(y) , y = x => a(x) , !b(x)
Definition at line 31 of file ResolveAliases.h.
Member Function Documentation
clone()
ResolveAliasesTransformer* souffle::ResolveAliasesTransformer::clone () const inline override virtual
Implements souffle::AstTransformer.
Definition at line 62 of file ResolveAliases.h.
References transform().
{
         return new ResolveAliasesTransformer();
     }
getName()
std::string souffle::ResolveAliasesTransformer::getName () const inline override virtual
Implements souffle::AstTransformer.
Definition at line 33 of file ResolveAliases.h.
References removeComplexTermsInAtoms(), removeTrivialEquality(), and resolveAliases().
{
         return "ResolveAliasesTransformer";
     }
removeComplexTermsInAtoms()
std::unique_ptr< AstClause > souffle::ResolveAliasesTransformer::removeComplexTermsInAtoms (const AstClause & clause) static
Removes complex terms in atoms, replacing them with constrained variables.
Parameters
clause the clause to be processed
Returns
a modified clone of the processed clause
Definition at line 371 of file ResolveAliases.cpp.
References souffle::any_of(), souffle::AstClause::clone(), souffle::clone(), souffle::EQ, souffle::AstTerm::getArguments(), souffle::map(), souffle::toString(), and souffle::visitDepthFirst().
Referenced by getName().
{
     std::unique_ptr<AstClause> res(clause.clone());
     // get list of atoms
     std::vector<AstAtom*> atoms = getBodyLiterals<AstAtom>(*res);
     // find all functors in atoms
     std::vector<const AstArgument*> terms;
     for (const AstAtom* atom : atoms) {
         for (const AstArgument* arg : atom->getArguments()) {
             // ignore if not a functor
             if (dynamic_cast<const AstFunctor*>(arg) == nullptr) {
                 continue;
             }
             // add this functor if not seen yet
             if (!any_of(terms, [&](const AstArgument* cur) { return *cur == *arg; })) {
                 terms.push_back(arg);
             }
         }
     }
     // find all functors in records too
     visitDepthFirst(atoms, [&](const AstRecordInit& rec) {
         for (const AstArgument* arg : rec.getArguments()) {
             // ignore if not a functor
             if (dynamic_cast<const AstFunctor*>(arg) == nullptr) {
                 continue;
             }
             // add this functor if not seen yet
             if (!any_of(terms, [&](const AstArgument* cur) { return *cur == *arg; })) {
                 terms.push_back(arg);
             }
         }
     });
     // substitute them with new variables (a real map would compare pointers)
     using substitution_map =
             std::vector<std::pair<std::unique_ptr<AstArgument>, std::unique_ptr<AstVariable>>>;
     substitution_map termToVar;
     static int varCounter = 0;
     for (const AstArgument* arg : terms) {
         // create a new mapping for this term
         auto term = souffle::clone(arg);
         auto newVariable = std::make_unique<AstVariable>(" _tmp_" + toString(varCounter++));
         termToVar.push_back(std::make_pair(std::move(term), std::move(newVariable)));
     }
     // apply mapping to replace the terms with the variables
     struct Update : public AstNodeMapper {
         const substitution_map& map;
         Update(const substitution_map& map) : map(map) {}
         std::unique_ptr<AstNode> operator()(std::unique_ptr<AstNode> node) const override {
             // check whether node needs to be replaced
             for (const auto& pair : map) {
                 auto& term = pair.first;
                 auto& variable = pair.second;
                 if (*term == *node) {
                     return souffle::clone(variable);
                 }
             }
             // continue recursively
             node->apply(*this);
             return node;
         }
     };
     // update atoms
     Update update(termToVar);
     for (AstAtom* atom : atoms) {
         atom->apply(update);
     }
     // add the necessary variable constraints to the clause
     for (const auto& pair : termToVar) {
         auto& term = pair.first;
         auto& variable = pair.second;
         res->addToBody(std::make_unique<AstBinaryConstraint>(
                 BinaryConstraintOp::EQ, souffle::clone(variable), souffle::clone(term)));
     }
     return res;
 }
removeTrivialEquality()
std::unique_ptr< AstClause > souffle::ResolveAliasesTransformer::removeTrivialEquality (const AstClause & clause) static
Removes trivial equalities of the form t = t from the given clause.
Parameters
clause the clause to be processed
Returns
a modified clone of the given clause
Definition at line 350 of file ResolveAliases.cpp.
References souffle::clone(), souffle::cloneHead(), souffle::AstClause::getBodyLiterals(), and souffle::isEqConstraint().
Referenced by getName(), and souffle::test::TEST().
{
     std::unique_ptr<AstClause> res(cloneHead(&clause));
     // add all literals, except filtering out t = t constraints
     for (AstLiteral* literal : clause.getBodyLiterals()) {
         if (auto* constraint = dynamic_cast<AstBinaryConstraint*>(literal)) {
             // TODO: don't filter out `FEQ` constraints, since `x = x` can fail when `x` is a NaN
             if (isEqConstraint(constraint->getOperator())) {
                 if (*constraint->getLHS() == *constraint->getRHS()) {
                     continue;  // skip this one
                 }
             }
         }
         res->addToBody(souffle::clone(literal));
     }
     // done
     return res;
 }
resolveAliases()
std::unique_ptr< AstClause > souffle::ResolveAliasesTransformer::resolveAliases (const AstClause & clause) static
Converts the given clause into a version without variables aliasing grounded variables.
Parameters
clause the clause to be processed
Returns
a modified clone of the processed clause
Definition at line 208 of file ResolveAliases.cpp.
References b, souffle::clone(), souffle::AstTerm::getArguments(), souffle::AstBinaryConstraint::getLHS(), souffle::AstBinaryConstraint::getOperator(), souffle::AstBinaryConstraint::getRHS(), i, souffle::isEqConstraint(), lhs, rhs, and souffle::visitDepthFirst().
Referenced by getName(), and souffle::test::TEST().
{
     // -- utilities --
     // tests whether something is a variable
     auto isVar = [&](const AstArgument& arg) { return dynamic_cast<const AstVariable*>(&arg) != nullptr; };
     // tests whether something is a record
     auto isRec = [&](const AstArgument& arg) { return dynamic_cast<const AstRecordInit*>(&arg) != nullptr; };
     // tests whether a value `a` occurs in a term `b`
     auto occurs = [](const AstArgument& a, const AstArgument& b) {
         bool res = false;
         visitDepthFirst(b, [&](const AstArgument& arg) { res = (res || (arg == a)); });
         return res;
     };
     // variables appearing as functorless arguments in atoms or records should not
     // be resolved
     std::set<std::string> baseGroundedVariables;
     for (const auto* atom : getBodyLiterals<AstAtom>(clause)) {
         for (const AstArgument* arg : atom->getArguments()) {
             if (const auto* var = dynamic_cast<const AstVariable*>(arg)) {
                 baseGroundedVariables.insert(var->getName());
             }
         }
         visitDepthFirst(*atom, [&](const AstRecordInit& rec) {
             for (const AstArgument* arg : rec.getArguments()) {
                 if (const auto* var = dynamic_cast<const AstVariable*>(arg)) {
                     baseGroundedVariables.insert(var->getName());
                 }
             }
         });
     }
     // I) extract equations
     std::vector<Equation> equations;
     visitDepthFirst(clause, [&](const AstBinaryConstraint& constraint) {
         if (isEqConstraint(constraint.getOperator())) {
             equations.push_back(Equation(constraint.getLHS(), constraint.getRHS()));
         }
     });
     // II) compute unifying substitution
     Substitution substitution;
     // a utility for processing newly identified mappings
     auto newMapping = [&](const std::string& var, const AstArgument* term) {
         // found a new substitution
         Substitution newMapping(var, term);
         // apply substitution to all remaining equations
         for (auto& equation : equations) {
             equation.apply(newMapping);
         }
         // add mapping v -> t to substitution
         substitution.append(newMapping);
     };
     while (!equations.empty()) {
         // get next equation to compute
         Equation equation = equations.back();
         equations.pop_back();
         // shortcuts for left/right
         const AstArgument& lhs = *equation.lhs;
         const AstArgument& rhs = *equation.rhs;
         // #1:  t = t   => skip
         if (lhs == rhs) {
             continue;
         }
         // #2:  [..] = [..]  => decompose
         if (isRec(lhs) && isRec(rhs)) {
             // get arguments
             const auto& lhs_args = static_cast<const AstRecordInit&>(lhs).getArguments();
             const auto& rhs_args = static_cast<const AstRecordInit&>(rhs).getArguments();
             // make sure sizes are identical
             assert(lhs_args.size() == rhs_args.size() && "Record lengths not equal");
             // create new equalities
             for (size_t i = 0; i < lhs_args.size(); i++) {
                 equations.push_back(Equation(lhs_args[i], rhs_args[i]));
             }
             continue;
         }
         // #3:  neither is a variable    => skip
         if (!isVar(lhs) && !isVar(rhs)) {
             continue;
         }
         // #4:  v = w    => add mapping
         if (isVar(lhs) && isVar(rhs)) {
             auto& var = static_cast<const AstVariable&>(lhs);
             newMapping(var.getName(), &rhs);
             continue;
         }
         // #5:  t = v   => swap
         if (!isVar(lhs)) {
             equations.push_back(Equation(rhs, lhs));
             continue;
         }
         // now we know lhs is a variable
         assert(isVar(lhs));
         // therefore, we have v = t
         const auto& v = static_cast<const AstVariable&>(lhs);
         const AstArgument& t = rhs;
         // #6:  v occurs in t   => skip
         if (occurs(v, t)) {
             continue;
         }
         assert(!occurs(v, t));
         // #7:  t is a record   => add mapping
         if (isRec(t)) {
             newMapping(v.getName(), &t);
             continue;
         }
         // #8:  v is already grounded   => skip
         auto pos = baseGroundedVariables.find(v.getName());
         if (pos != baseGroundedVariables.end()) {
             continue;
         }
         // add new mapping
         newMapping(v.getName(), &t);
     }
     // III) compute resulting clause
     return substitution(souffle::clone(&clause));
 }
transform()
bool souffle::ResolveAliasesTransformer::transform (AstTranslationUnit & translationUnit) override private virtual
Implements souffle::AstTransformer.
Definition at line 462 of file ResolveAliases.cpp.
References souffle::AstProgram::addClause(), clauses, souffle::getClauses(), souffle::AstTranslationUnit::getProgram(), souffle::AstProgram::removeClause(), and souffle::visitDepthFirst().
Referenced by clone().
{
     bool changed = false;
     AstProgram& program = *translationUnit.getProgram();
     // get all clauses
     std::vector<const AstClause*> clauses;
     visitDepthFirst(program, [&](const AstRelation& rel) {
         for (const auto& clause : getClauses(program, rel)) {
             clauses.push_back(clause);
         }
     });
     // clean all clauses
     for (const AstClause* clause : clauses) {
         // -- Step 1 --
         // get rid of aliases
         std::unique_ptr<AstClause> noAlias = resolveAliases(*clause);
         // clean up equalities
         std::unique_ptr<AstClause> cleaned = removeTrivialEquality(*noAlias);
         // -- Step 2 --
         // restore simple terms in atoms
         std::unique_ptr<AstClause> normalised = removeComplexTermsInAtoms(*cleaned);
         // swap if changed
         if (*normalised != *clause) {
             changed = true;
             program.removeClause(clause);
             program.addClause(std::move(normalised));
         }
     }
     return changed;
 }
The documentation for this class was generated from the following files:
ast/transform/ResolveAliases.h
ast/transform/ResolveAliases.cpp