souffle: souffle::AstIntrinsicFunctor Class Reference
souffle::AstIntrinsicFunctor Class Reference
Intrinsic Functor.
#include <IntrinsicFunctor.h>
Public Member Functions
template<typename... Operands>
AstIntrinsicFunctor (std::string op, Operands &&... operands)
template<typename... Operands>
AstIntrinsicFunctor (SrcLocation loc, std::string op, Operands &&... operands)
AstIntrinsicFunctor (std::string op, VecOwn< AstArgument > args, SrcLocation loc={})
AstIntrinsicFunctor * clone () const override
Create clone.
TypeAttribute getArgType (const size_t arg) const override
get type of the functor argument
const std::string & getFunction () const
get function
const IntrinsicFunctor * getFunctionInfo () const
TypeAttribute getReturnType () const override
get the return type of the functor.
void setFunction (std::string functor)
set function
void setFunctionInfo (const IntrinsicFunctor &info)
Public Member Functions inherited from souffle::AstTerm
void addArgument (Own< AstArgument > arg)
add argument to argument list
void apply (const AstNodeMapper &map) override
Apply the mapper to all child nodes.
std::vector< AstArgument * > getArguments () const
get arguments
std::vector< const AstNode * > getChildNodes () const override
Obtain a list of all embedded AST child nodes.
Public Member Functions inherited from souffle::AstNode
AstNode (SrcLocation loc={})
std::string extloc () const
Return source location of the syntactic element.
const SrcLocation & getSrcLoc () const
Return source location of the AstNode.
bool operator!= (const AstNode &other) const
Inequality check for two AST nodes.
bool operator== (const AstNode &other) const
Equivalence check for two AST nodes.
void setSrcLoc (SrcLocation l)
Set source location for the AstNode.
virtual ~AstNode ()=default
Protected Member Functions
AstIntrinsicFunctor (std::string op, const IntrinsicFunctor *info, VecOwn< AstArgument > args, SrcLocation loc={})
bool equal (const AstNode &node) const override
Abstract equality check for two AST nodes.
void print (std::ostream &os) const override
Output to a given output stream.
Protected Member Functions inherited from souffle::AstTerm
template<typename... Operands>
AstTerm (Operands &&... operands)
template<typename... Operands>
AstTerm (SrcLocation loc, Operands &&... operands)
AstTerm (VecOwn< AstArgument > operands, SrcLocation loc={})
bool equal (const AstNode &node) const override
Abstract equality check for two AST nodes.
Protected Attributes
std::string function
Function.
const IntrinsicFunctor * info = nullptr
Protected Attributes inherited from souffle::AstTerm
VecOwn< AstArgument > args
Arguments.
Detailed Description
Intrinsic Functor.
Definition at line 37 of file IntrinsicFunctor.h.
Constructor & Destructor Documentation
AstIntrinsicFunctor() [1/4]
template<typename... Operands> souffle::AstIntrinsicFunctor::AstIntrinsicFunctor (std::string op, Operands &&... operands) inline
Definition at line 40 of file IntrinsicFunctor.h.
Referenced by clone().
             : AstFunctor(std::forward<Operands>(operands)...), function(std::move(op)) {}
AstIntrinsicFunctor() [2/4]
template<typename... Operands> souffle::AstIntrinsicFunctor::AstIntrinsicFunctor (SrcLocation loc, std::string op, Operands &&... operands) inline
Definition at line 44 of file IntrinsicFunctor.h.
             : AstFunctor(std::move(loc), std::forward<Operands>(operands)...), function(std::move(op)) {}
AstIntrinsicFunctor() [3/4]
souffle::AstIntrinsicFunctor::AstIntrinsicFunctor (std::string op, VecOwn< AstArgument > args, SrcLocation loc = {}) inline
Definition at line 47 of file IntrinsicFunctor.h.
                                                                                   {})
             : AstFunctor(std::move(args), std::move(loc)), function(std::move(op)) {}
AstIntrinsicFunctor() [4/4]
souffle::AstIntrinsicFunctor::AstIntrinsicFunctor (std::string op, const IntrinsicFunctor * info, VecOwn< AstArgument > args, SrcLocation loc = {}) inline protected
Definition at line 85 of file IntrinsicFunctor.h.
References info, and souffle::IntrinsicFunctor::symbol.
                                                                                                     {})
             : AstFunctor(std::move(args), std::move(loc)), function(std::move(op)), info(info) {
         assert((!info || info->symbol == function) && "functor info must match symbol");
     }
Member Function Documentation
clone()
AstIntrinsicFunctor* souffle::AstIntrinsicFunctor::clone () const inline override virtual
Create clone.
Implements souffle::AstFunctor.
Definition at line 80 of file IntrinsicFunctor.h.
References AstIntrinsicFunctor(), souffle::clone(), souffle::AstNode::getSrcLoc(), and info.
{
         return new AstIntrinsicFunctor(function, info, souffle::clone(args), getSrcLoc());
     }
equal()
bool souffle::AstIntrinsicFunctor::equal (const AstNode &) const inline override protected virtual
Abstract equality check for two AST nodes.
Reimplemented from souffle::AstNode.
Definition at line 100 of file IntrinsicFunctor.h.
References souffle::AstTerm::equal(), and function.
{
         const auto& other = static_cast<const AstIntrinsicFunctor&>(node);
         return function == other.function && info == other.info && AstFunctor::equal(node);
     }
getArgType()
TypeAttribute souffle::AstIntrinsicFunctor::getArgType (const size_t arg) const inline override virtual
get type of the functor argument
Implements souffle::AstFunctor.
Definition at line 75 of file IntrinsicFunctor.h.
References info, souffle::IntrinsicFunctor::params, and souffle::IntrinsicFunctor::variadic.
{
         assert(info && "functor info not yet available");
         return info->params.at(info->variadic ? 0 : arg);
     }
getFunction()
const std::string& souffle::AstIntrinsicFunctor::getFunction () const inline
get function
Definition at line 51 of file IntrinsicFunctor.h.
Referenced by souffle::validOverloads(), and souffle::TypeChecker::visitIntrinsicFunctor().
{
         return function;
     }
getFunctionInfo()
const IntrinsicFunctor* souffle::AstIntrinsicFunctor::getFunctionInfo () const inline
Definition at line 60 of file IntrinsicFunctor.h.
References info.
Referenced by souffle::isFact(), souffle::AstToRamTranslator::translateValue(), and souffle::TypeChecker::visitIntrinsicFunctor().
{
         return info;
     }
getReturnType()
TypeAttribute souffle::AstIntrinsicFunctor::getReturnType () const inline override virtual
get the return type of the functor.
Implements souffle::AstFunctor.
Definition at line 69 of file IntrinsicFunctor.h.
References info, and souffle::IntrinsicFunctor::result.
{
         assert(info && "functor info not yet available");
         return info->result;
     }
print()
void souffle::AstIntrinsicFunctor::print (std::ostream & os) const inline override protected virtual
Output to a given output stream.
Implements souffle::AstNode.
Definition at line 91 of file IntrinsicFunctor.h.
References souffle::isInfixFunctorOp(), and souffle::join().
{
         if (isInfixFunctorOp(function)) {
             os << "(" << join(args, function) << ")";
         } else {
             os << function;
             os << "(" << join(args) << ")";
         }
     }
setFunction()
void souffle::AstIntrinsicFunctor::setFunction (std::string functor) inline
set function
Definition at line 56 of file IntrinsicFunctor.h.
{
         function = std::move(functor);
     }
setFunctionInfo()
void souffle::AstIntrinsicFunctor::setFunctionInfo (const IntrinsicFunctor & info) inline
Definition at line 64 of file IntrinsicFunctor.h.
References info.
{
         this->info = &info;
     }
Field Documentation
function
std::string souffle::AstIntrinsicFunctor::function protected
Function.
Definition at line 106 of file IntrinsicFunctor.h.
Referenced by equal().
info
const IntrinsicFunctor* souffle::AstIntrinsicFunctor::info = nullptr protected
Definition at line 107 of file IntrinsicFunctor.h.
Referenced by AstIntrinsicFunctor(), clone(), getArgType(), getFunctionInfo(), getReturnType(), and setFunctionInfo().
The documentation for this class was generated from the following file:
ast/IntrinsicFunctor.h