souffle: souffle::RamPackRecord Class Reference
souffle::RamPackRecord Class Reference
Packs a record's arguments into a reference.
#include <Expression.h>
Public Member Functions
void apply (const RamNodeMapper &map) override
Apply the mapper to all child nodes.
RamPackRecord * clone () const override
Create a clone (i.e.
std::vector< RamExpression * > getArguments () const
Get record arguments.
std::vector< const RamNode * > getChildNodes () const override
Obtain list of all embedded child nodes.
RamPackRecord (std::vector< std::unique_ptr< RamExpression >> args)
Public Member Functions inherited from souffle::RamNode
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
virtual void rewrite (const RamNode *oldNode, std::unique_ptr< RamNode > newNode)
Rewrite a child node.
virtual ~RamNode ()=default
Protected Member Functions
bool equal (const RamNode &node) const override
Equality check for two RAM nodes.
void print (std::ostream &os) const override
Print RAM node.
Protected Attributes
std::vector< std::unique_ptr< RamExpression > > arguments
Arguments.
Detailed Description
Packs a record's arguments into a reference.
Definition at line 384 of file Expression.h.
Constructor & Destructor Documentation
RamPackRecord()
souffle::RamPackRecord::RamPackRecord (std::vector< std::unique_ptr< RamExpression >> args) inline
Definition at line 386 of file Expression.h.
                                                                 : arguments(std::move(args)) {
         for (const auto& arg : arguments) {
             assert(arg != nullptr && "argument is a null-pointer");
         }
     }
Member Function Documentation
apply()
void souffle::RamPackRecord::apply (const RamNodeMapper &) inline override virtual
Apply the mapper to all child nodes.
Reimplemented from souffle::RamNode.
Definition at line 413 of file Expression.h.
References souffle::map().
{
         for (auto& arg : arguments) {
             arg = map(std::move(arg));
         }
     }
clone()
RamPackRecord* souffle::RamPackRecord::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::RamExpression.
Definition at line 405 of file Expression.h.
References arguments.
Referenced by souffle::test::TEST().
{
         auto* res = new RamPackRecord({});
         for (auto& cur : arguments) {
             res->arguments.emplace_back(cur->clone());
         }
         return res;
     }
equal()
bool souffle::RamPackRecord::equal (const RamNode &) const inline override protected virtual
Equality check for two RAM nodes.
Default action is that nothing needs to be checked.
Reimplemented from souffle::RamNode.
Definition at line 426 of file Expression.h.
References souffle::equal_targets().
{
         const auto& other = static_cast<const RamPackRecord&>(node);
         return equal_targets(arguments, other.arguments);
     }
getArguments()
std::vector<RamExpression*> souffle::RamPackRecord::getArguments () const inline
Get record arguments.
Definition at line 393 of file Expression.h.
References souffle::toPtrVector().
Referenced by souffle::Synthesiser::emitCode(), souffle::RamLevelAnalysis::getLevel(), and souffle::NodeGenerator::visitPackRecord().
{
         return toPtrVector(arguments);
     }
getChildNodes()
std::vector<const RamNode*> souffle::RamPackRecord::getChildNodes () const inline override virtual
Obtain list of all embedded child nodes.
Reimplemented from souffle::RamNode.
Definition at line 397 of file Expression.h.
{
         std::vector<const RamNode*> res;
         for (const auto& cur : arguments) {
             res.push_back(cur.get());
         }
         return res;
     }
print()
void souffle::RamPackRecord::print (std::ostream & out) const inline override protected virtual
Print RAM node.
Implements souffle::RamNode.
Definition at line 420 of file Expression.h.
References souffle::join().
{
         os << "[" << join(arguments, ",", [](std::ostream& out, const std::unique_ptr<RamExpression>& arg) {
             out << *arg;
         }) << "]";
     }
Field Documentation
arguments
std::vector<std::unique_ptr<RamExpression> > souffle::RamPackRecord::arguments protected
Arguments.
Definition at line 432 of file Expression.h.
Referenced by clone().
The documentation for this class was generated from the following file:
ram/Expression.h