souffle: souffle::ReplaceSingletonVariablesTransformer Class Reference
souffle::ReplaceSingletonVariablesTransformer Class Reference
Transformation pass to replace singleton variables with unnamed variables.
#include <ReplaceSingletonVariables.h>
Public Member Functions
ReplaceSingletonVariablesTransformer * clone () const override
std::string getName () const override
Public Member Functions inherited from souffle::AstTransformer
bool apply (AstTranslationUnit &translationUnit)
virtual ~AstTransformer ()=default
Private Member Functions
bool transform (AstTranslationUnit &translationUnit) override
Detailed Description
Transformation pass to replace singleton variables with unnamed variables.
E.g.: a() :- b(x). -> a() :- b(_).
Definition at line 29 of file ReplaceSingletonVariables.h.
Member Function Documentation
clone()
ReplaceSingletonVariablesTransformer* souffle::ReplaceSingletonVariablesTransformer::clone () const inline override virtual
Implements souffle::AstTransformer.
Definition at line 35 of file ReplaceSingletonVariables.h.
References transform().
{
         return new ReplaceSingletonVariablesTransformer();
     }
getName()
std::string souffle::ReplaceSingletonVariablesTransformer::getName () const inline override virtual
Implements souffle::AstTransformer.
Definition at line 31 of file ReplaceSingletonVariables.h.
{
         return "ReplaceSingletonVariablesTransformer";
     }
transform()
bool souffle::ReplaceSingletonVariablesTransformer::transform (AstTranslationUnit & translationUnit) override private virtual
Implements souffle::AstTransformer.
Definition at line 34 of file ReplaceSingletonVariables.cpp.
References souffle::getClauses(), souffle::AstVariable::getName(), souffle::AstTranslationUnit::getProgram(), souffle::AstProgram::getRelations(), and souffle::visitDepthFirst().
Referenced by clone().
{
     bool changed = false;
     AstProgram& program = *translationUnit.getProgram();
     // Node-mapper to replace a set of singletons with unnamed variables
     struct replaceSingletons : public AstNodeMapper {
         std::set<std::string>& singletons;
         replaceSingletons(std::set<std::string>& singletons) : singletons(singletons) {}
         std::unique_ptr<AstNode> operator()(std::unique_ptr<AstNode> node) const override {
             if (auto* var = dynamic_cast<AstVariable*>(node.get())) {
                 if (singletons.find(var->getName()) != singletons.end()) {
                     return std::make_unique<AstUnnamedVariable>();
                 }
             }
             node->apply(*this);
             return node;
         }
     };
     for (AstRelation* rel : program.getRelations()) {
         for (AstClause* clause : getClauses(program, *rel)) {
             std::set<std::string> nonsingletons;
             std::set<std::string> vars;
             visitDepthFirst(*clause, [&](const AstVariable& var) {
                 const std::string& name = var.getName();
                 if (vars.find(name) != vars.end()) {
                     // Variable seen before, so not a singleton variable
                     nonsingletons.insert(name);
                 } else {
                     vars.insert(name);
                 }
             });
             std::set<std::string> ignoredVars;
             // Don't unname singleton variables occurring in records.
             // TODO (azreika): remove this check once issue #420 is fixed
             std::set<std::string> recordVars;
             visitDepthFirst(*clause, [&](const AstRecordInit& rec) {
                 visitDepthFirst(rec, [&](const AstVariable& var) { ignoredVars.insert(var.getName()); });
             });
             // Don't unname singleton variables occuring in constraints.
             std::set<std::string> constraintVars;
             visitDepthFirst(*clause, [&](const AstConstraint& cons) {
                 visitDepthFirst(cons, [&](const AstVariable& var) { ignoredVars.insert(var.getName()); });
             });
             std::set<std::string> singletons;
             for (auto& var : vars) {
                 if ((nonsingletons.find(var) == nonsingletons.end()) &&
                         (ignoredVars.find(var) == ignoredVars.end())) {
                     changed = true;
                     singletons.insert(var);
                 }
             }
             // Replace the singletons found with underscores
             replaceSingletons update(singletons);
             clause->apply(update);
         }
     }
     return changed;
 }
The documentation for this class was generated from the following files:
ast/transform/ReplaceSingletonVariables.h
ast/transform/ReplaceSingletonVariables.cpp