souffle: souffle::InterpreterRelation Class Reference
souffle::InterpreterRelation Class Reference
A relation, composed of a collection of indexes.
#include <InterpreterRelation.h>
Data Structures
class Iterator
Support for-each iteration for InterpreterRelation.
Public Types
using Attribute = uint32_t
using AttributeSet = std::set< Attribute >
Public Member Functions
Iterator begin () const
bool contains (const TupleRef &tuple) const
Tests whether this relation contains the given tuple.
bool contains (const size_t &indexPos, const TupleRef &low, const TupleRef &high) const
Tests whether this relation contains any element between the given boundaries.
bool empty () const
Check if the relation is empty.
Iterator end () const
bool exists (const TupleRef &tuple) const
Check if a tuple exists in relation.
virtual void extend (const InterpreterRelation &rel)
Extend another relation.
size_t getArity () const
Return arity.
const std::vector< std::string > & getAttributeTypes () const
Return the attribute types.
size_t getAuxiliaryArity () const
Return arity.
size_t getLevel () const
Return the level of the relation.
const std::string & getName () const
Return the relation name.
IndexViewPtr getView (const size_t &indexPos) const
Obtains a view on an index of this relation, facilitating hint-supported accesses.
virtual bool insert (const TupleRef &tuple)
Add the given tuple to this relation.
virtual bool insert (const RamDomain *tuple)
Add the given tuple to this relation.
void insert (const InterpreterRelation &other)
Add all entries of the given relation to this relation.
InterpreterRelation (std::size_t arity, std::size_t auxiliaryArity, std::string name, std::vector< std::string > attributeTypes, const MinIndexSelection &orderSet, IndexFactory factory=&createBTreeIndex)
Creates a relation, build all necessary indexes.
InterpreterRelation (InterpreterRelation &other)=delete
PartitionedStream partitionRange (const size_t &indexPos, const TupleRef &low, const TupleRef &high, size_t partitionCount) const
Obtains a partitioned stream list for parallel computation.
PartitionedStream partitionScan (size_t partitionCount) const
Obtains a partitioned stream list for parallel computation.
virtual void purge ()
Clear all indexes.
Stream range (const size_t &indexPos, const TupleRef &low, const TupleRef &high) const
Obtains a stream covering the interval between the two given entries.
void removeIndex (const size_t &indexPos)
Drops an index from the maintained indexes.
Stream scan () const
Obtains a stream to scan the entire relation.
void setLevel (size_t level)
Set level.
size_t size () const
Return number of tuples in relation (full-order)
void swap (InterpreterRelation &other)
Swaps the content of this and the given relation, including the installed indexes.
virtual ~InterpreterRelation ()=default
Protected Attributes
const size_t arity
std::vector< std::string > attributeTypes
size_t auxiliaryArity
std::vector< std::unique_ptr< InterpreterIndex > > indexes
size_t level = 0
InterpreterIndex * main
std::string relName
Detailed Description
A relation, composed of a collection of indexes.
Definition at line 36 of file InterpreterRelation.h.
Member Typedef Documentation
Attribute
using souffle::InterpreterRelation::Attribute = uint32_t
Definition at line 38 of file InterpreterRelation.h.
AttributeSet
using souffle::InterpreterRelation::AttributeSet = std::set<Attribute>
Definition at line 39 of file InterpreterRelation.h.
Constructor & Destructor Documentation
InterpreterRelation() [1/2]
souffle::InterpreterRelation::InterpreterRelation (std::size_t arity, std::size_t auxiliaryArity, std::string name, std::vector< std::string > attributeTypes, const MinIndexSelection & orderSet, IndexFactory factory = &createBTreeIndex)
Creates a relation, build all necessary indexes.
Definition at line 26 of file InterpreterRelation.cpp.
References arity, end(), souffle::MinIndexSelection::getAllOrders(), i, indexes, and main.
         : relName(std::move(name)), arity(arity), auxiliaryArity(auxiliaryArity),
           attributeTypes(std::move(attributeTypes)) {
     for (auto order : orderSet.getAllOrders()) {
         // Expand the order to a total order
         AttributeSet set{order.begin(), order.end()};
         for (std::size_t i = 0; i < arity; ++i) {
             if (set.find(i) == set.end()) {
                 order.push_back(i);
             }
         }
         indexes.push_back(factory(Order(order)));
     }
     // Use the first index as default main index
     main = indexes[0].get();
 }
InterpreterRelation() [2/2]
souffle::InterpreterRelation::InterpreterRelation (InterpreterRelation & other) delete
~InterpreterRelation()
virtual souffle::InterpreterRelation::~InterpreterRelation () virtual default
Member Function Documentation
begin()
Iterator souffle::InterpreterRelation::begin () const inline
Definition at line 84 of file InterpreterRelation.h.
References souffle::InterpreterRelation::Iterator::Iterator().
Referenced by souffle::InterpreterRelInterface::begin().
{
         return Iterator(*this);
     }
contains() [1/2]
bool souffle::InterpreterRelation::contains (const TupleRef & tuple) const
Tests whether this relation contains the given tuple.
Definition at line 77 of file InterpreterRelation.cpp.
References souffle::InterpreterIndex::contains(), and main.
Referenced by souffle::InterpreterRelInterface::contains(), and insert().
{
     return main->contains(tuple);
 }
contains() [2/2]
bool souffle::InterpreterRelation::contains (const size_t & indexPos, const TupleRef & low, const TupleRef & high) const
Tests whether this relation contains any element between the given boundaries.
Definition at line 81 of file InterpreterRelation.cpp.
References indexes.
{
     return indexes[indexPos]->contains(low, high);
 }
empty()
bool souffle::InterpreterRelation::empty () const
Check if the relation is empty.
Definition at line 128 of file InterpreterRelation.cpp.
References souffle::InterpreterIndex::empty(), and main.
Referenced by souffle::InterpreterEngine::execute(), and getArity().
{
     return main->empty();
 }
end()
Iterator souffle::InterpreterRelation::end () const inline
Definition at line 88 of file InterpreterRelation.h.
References getView(), insert(), souffle::InterpreterRelation::Iterator::Iterator(), and removeIndex().
Referenced by souffle::InterpreterRelInterface::end(), and InterpreterRelation().
{
         return Iterator();
     }
exists()
bool souffle::InterpreterRelation::exists (const TupleRef & tuple) const
Check if a tuple exists in relation.
Definition at line 138 of file InterpreterRelation.cpp.
References souffle::InterpreterIndex::contains(), and main.
Referenced by getArity().
{
     return main->contains(tuple);
 }
extend()
void souffle::InterpreterRelation::extend (const InterpreterRelation & rel) virtual
Extend another relation.
Reimplemented in souffle::InterpreterEqRelation.
Definition at line 142 of file InterpreterRelation.cpp.
Referenced by souffle::InterpreterEngine::execute(), and getArity().
 {}
getArity()
size_t souffle::InterpreterRelation::getArity () const inline
Return arity.
Definition at line 182 of file InterpreterRelation.h.
References arity, empty(), exists(), extend(), getAuxiliaryArity(), purge(), and size().
Referenced by souffle::InterpreterEngine::execute(), and souffle::InterpreterRelInterface::getArity().
{
         return arity;
     }
getAttributeTypes()
const std::vector< std::string > & souffle::InterpreterRelation::getAttributeTypes () const
Return the attribute types.
Definition at line 116 of file InterpreterRelation.cpp.
References attributeTypes.
Referenced by setLevel().
{
     return this->attributeTypes;
 }
getAuxiliaryArity()
size_t souffle::InterpreterRelation::getAuxiliaryArity () const
Return arity.
Definition at line 120 of file InterpreterRelation.cpp.
References auxiliaryArity.
Referenced by getArity(), and souffle::InterpreterRelInterface::getAuxiliaryArity().
{
     return auxiliaryArity;
 }
getLevel()
size_t souffle::InterpreterRelation::getLevel () const
Return the level of the relation.
Definition at line 108 of file InterpreterRelation.cpp.
References level.
Referenced by setLevel().
{
     return this->level;
 }
getName()
const std::string & souffle::InterpreterRelation::getName () const
Return the relation name.
Definition at line 112 of file InterpreterRelation.cpp.
References relName.
Referenced by setLevel().
{
     return this->relName;
 }
getView()
IndexViewPtr souffle::InterpreterRelation::getView (const size_t & indexPos) const
Obtains a view on an index of this relation, facilitating hint-supported accesses.
Definition at line 52 of file InterpreterRelation.cpp.
References indexes.
Referenced by souffle::InterpreterContext::createView(), and end().
{
     assert(indexPos < indexes.size());
     return indexes[indexPos]->createView();
 }
insert() [1/3]
bool souffle::InterpreterRelation::insert (const TupleRef & tuple) virtual
Add the given tuple to this relation.
Reimplemented in souffle::InterpreterIndirectRelation.
Definition at line 57 of file InterpreterRelation.cpp.
References indexes, souffle::InterpreterIndex::insert(), and main.
Referenced by end(), souffle::InterpreterEngine::execute(), souffle::InterpreterRelInterface::insert(), and insert().
{
     if (!main->insert(tuple)) {
         return false;
     }
     for (const auto& cur : indexes) {
         if (cur.get() == main) {
             continue;
         }
         cur->insert(tuple);
     }
     return true;
 }
insert() [2/3]
virtual bool souffle::InterpreterRelation::insert (const RamDomain * tuple) inline virtual
Add the given tuple to this relation.
Reimplemented in souffle::InterpreterIndirectRelation.
Definition at line 111 of file InterpreterRelation.h.
References arity, contains(), high, insert(), low, partitionRange(), partitionScan(), range(), scan(), and swap().
{
         return insert(TupleRef(tuple, arity));
     }
insert() [3/3]
void souffle::InterpreterRelation::insert (const InterpreterRelation & other)
Add all entries of the given relation to this relation.
Definition at line 70 of file InterpreterRelation.cpp.
References insert(), and scan().
{
     // TODO: cover this in a smarter way
     for (const auto& cur : other.scan()) {
         insert(cur);
     }
 }
partitionRange()
PartitionedStream souffle::InterpreterRelation::partitionRange (const size_t & indexPos, const TupleRef & low, const TupleRef & high, size_t partitionCount) const
Obtains a partitioned stream list for parallel computation.
Definition at line 98 of file InterpreterRelation.cpp.
References indexes.
Referenced by insert().
{
     auto& pos = indexes[indexPos];
     return pos->partitionRange(low, high, partitionCount);
 }
partitionScan()
PartitionedStream souffle::InterpreterRelation::partitionScan (size_t partitionCount) const
Obtains a partitioned stream list for parallel computation.
Definition at line 89 of file InterpreterRelation.cpp.
References main, and souffle::InterpreterIndex::partitionScan().
Referenced by souffle::InterpreterEngine::execute(), and insert().
{
     return main->partitionScan(partitionCount);
 }
purge()
void souffle::InterpreterRelation::purge () virtual
Clear all indexes.
Reimplemented in souffle::InterpreterIndirectRelation.
Definition at line 132 of file InterpreterRelation.cpp.
References indexes.
Referenced by souffle::InterpreterEngine::execute(), getArity(), and souffle::InterpreterRelInterface::purge().
{
     for (auto& index : indexes) {
         index->clear();
     }
 }
range()
Stream souffle::InterpreterRelation::range (const size_t & indexPos, const TupleRef & low, const TupleRef & high) const
Obtains a stream covering the interval between the two given entries.
Definition at line 93 of file InterpreterRelation.cpp.
References indexes.
Referenced by insert().
{
     auto& pos = indexes[indexPos];
     return pos->range(low, high);
 }
removeIndex()
void souffle::InterpreterRelation::removeIndex (const size_t & indexPos)
Drops an index from the maintained indexes.
All but one index may be removed.
Definition at line 46 of file InterpreterRelation.cpp.
References indexes.
Referenced by end().
{
     // All but one index can be removed, default full index can't be removed.
     assert(indexes.size() > 1 || indexPos != 0);
     indexes[indexPos].reset(nullptr);
 }
scan()
Stream souffle::InterpreterRelation::scan () const
Obtains a stream to scan the entire relation.
Definition at line 85 of file InterpreterRelation.cpp.
References main, and souffle::InterpreterIndex::scan().
Referenced by souffle::InterpreterEngine::execute(), and insert().
{
     return main->scan();
 }
setLevel()
void souffle::InterpreterRelation::setLevel (size_t level) inline
Set level.
Definition at line 160 of file InterpreterRelation.h.
References getAttributeTypes(), getLevel(), getName(), and level.
{
         this->level = level;
     }
size()
size_t souffle::InterpreterRelation::size () const
Return number of tuples in relation (full-order)
Definition at line 124 of file InterpreterRelation.cpp.
References main, and souffle::InterpreterIndex::size().
Referenced by souffle::InterpreterEngine::execute(), getArity(), and souffle::InterpreterRelInterface::size().
{
     return main->size();
 }
swap()
void souffle::InterpreterRelation::swap (InterpreterRelation & other)
Swaps the content of this and the given relation, including the installed indexes.
Definition at line 104 of file InterpreterRelation.cpp.
References indexes.
Referenced by insert().
{
     indexes.swap(other.indexes);
 }
Field Documentation
arity
const size_t souffle::InterpreterRelation::arity protected
Definition at line 221 of file InterpreterRelation.h.
Referenced by getArity(), insert(), souffle::InterpreterIndirectRelation::insert(), and InterpreterRelation().
attributeTypes
std::vector<std::string> souffle::InterpreterRelation::attributeTypes protected
Definition at line 227 of file InterpreterRelation.h.
Referenced by getAttributeTypes().
auxiliaryArity
size_t souffle::InterpreterRelation::auxiliaryArity protected
Definition at line 224 of file InterpreterRelation.h.
Referenced by getAuxiliaryArity().
indexes
std::vector<std::unique_ptr<InterpreterIndex> > souffle::InterpreterRelation::indexes protected
Definition at line 230 of file InterpreterRelation.h.
Referenced by contains(), getView(), insert(), souffle::InterpreterIndirectRelation::insert(), souffle::InterpreterEqRelation::InterpreterEqRelation(), InterpreterRelation(), partitionRange(), purge(), souffle::InterpreterIndirectRelation::purge(), range(), removeIndex(), and swap().
level
size_t souffle::InterpreterRelation::level = 0 protected
Definition at line 236 of file InterpreterRelation.h.
Referenced by getLevel(), and setLevel().
main
InterpreterIndex* souffle::InterpreterRelation::main protected
Definition at line 233 of file InterpreterRelation.h.
Referenced by contains(), empty(), exists(), souffle::InterpreterEqRelation::extend(), insert(), souffle::InterpreterIndirectRelation::insert(), InterpreterRelation(), partitionScan(), scan(), and size().
relName
std::string souffle::InterpreterRelation::relName protected
Definition at line 218 of file InterpreterRelation.h.
Referenced by getName().
The documentation for this class was generated from the following files:
interpreter/InterpreterRelation.h
interpreter/InterpreterRelation.cpp