souffle: json11::Json Class Reference
json11::Json Class Reference final
#include <json11.h>
Public Types
using array = std::vector< Json >
using object = std::map< std::string, Json >
using shape = std::initializer_list< std::pair< std::string, Type > >
enum Type {
NUL, NUMBER, BOOL, STRING,
ARRAY, OBJECT
}
Public Member Functions
const array & array_items () const
bool bool_value () const
void dump (std::string &out) const
std::string dump () const
bool has_shape (const shape &types, std::string &err) const
int int_value () const
bool is_array () const
bool is_bool () const
bool is_null () const
bool is_number () const
bool is_object () const
bool is_string () const
Json () noexcept
Json (std::nullptr_t) noexcept
Json (double value)
Json (long long value)
Json (bool value)
Json (const std::string &value)
Json (std::string &&value)
Json (const char *value)
Json (const array &values)
Json (array &&values)
Json (const object &values)
Json (object &&values)
template<class T , class = decltype(&T::to_json)>
Json (const T &t)
template<class M , typename std::enable_if< std::is_constructible< std::string, decltype(std::declval< M >().begin() ->first)>::value &&std::is_constructible< Json, decltype(std::declval< M >().begin() -> second>
Json (const M &m)
template<class V , typename std::enable_if< std::is_constructible< Json, decltype(*std::declval< V >().begin())>::value, int >::type = 0>
Json (const V &v)
Json (void *)=delete
long long long_value () const
double number_value () const
const object & object_items () const
bool operator!= (const Json &rhs) const
bool operator< (const Json &rhs) const
bool operator<= (const Json &rhs) const
bool operator== (const Json &rhs) const
bool operator> (const Json &rhs) const
bool operator>= (const Json &rhs) const
const Json & operator[] (size_t i) const
const Json & operator[] (const std::string &key) const
const std::string & string_value () const
Type type () const
Static Public Member Functions
static Json parse (const std::string &in, std::string &err, JsonParse strategy=JsonParse::STANDARD)
static Json parse (const char *in, std::string &err, JsonParse strategy=JsonParse::STANDARD)
static std::vector< Json > parse_multi (const std::string &in, std::string::size_type &parser_stop_pos, std::string &err, JsonParse strategy=JsonParse::STANDARD)
static std::vector< Json > parse_multi (const std::string &in, std::string &err, JsonParse strategy=JsonParse::STANDARD)
Private Attributes
std::shared_ptr< JsonValue > m_ptr
Detailed Description
Definition at line 86 of file json11.h.
Member Typedef Documentation
array
using json11::Json::array = std::vector<Json>
Definition at line 92 of file json11.h.
object
using json11::Json::object = std::map<std::string, Json>
Definition at line 93 of file json11.h.
shape
using json11::Json::shape = std::initializer_list<std::pair<std::string, Type> >
Definition at line 222 of file json11.h.
Member Enumeration Documentation
Type
enum json11::Json::Type
Enumerator
NUL
NUMBER
BOOL
STRING
ARRAY
OBJECT
Definition at line 89 of file json11.h.
 { NUL, NUMBER, BOOL, STRING, ARRAY, OBJECT };
Constructor & Destructor Documentation
Json() [1/16]
json11::Json::Json () inline noexcept
Definition at line 518 of file json11.h.
Referenced by Json(), and parse().
 : m_ptr(statics().null) {}
Json() [2/16]
json11::Json::Json (std::nullptr_t) inline noexcept
Definition at line 519 of file json11.h.
 : m_ptr(statics().null) {}
Json() [3/16]
json11::Json::Json (double value) inline
Definition at line 520 of file json11.h.
 : m_ptr(std::make_shared<JsonDouble>(value)) {}
Json() [4/16]
json11::Json::Json (long long value) inline
Definition at line 521 of file json11.h.
 : m_ptr(std::make_shared<JsonInt>(value)) {}
Json() [5/16]
json11::Json::Json (bool value) inline
Definition at line 522 of file json11.h.
 : m_ptr(value ? statics().t : statics().f) {}
Json() [6/16]
json11::Json::Json (const std::string & value) inline
Definition at line 523 of file json11.h.
 : m_ptr(std::make_shared<JsonString>(value)) {}
Json() [7/16]
json11::Json::Json (std::string && value) inline
Definition at line 524 of file json11.h.
 : m_ptr(std::make_shared<JsonString>(std::move(value))) {}
Json() [8/16]
json11::Json::Json (const char * value) inline
Definition at line 525 of file json11.h.
 : m_ptr(std::make_shared<JsonString>(value)) {}
Json() [9/16]
json11::Json::Json (const array & values) inline
Definition at line 526 of file json11.h.
 : m_ptr(std::make_shared<JsonArray>(values)) {}
Json() [10/16]
json11::Json::Json (Json::array && values) inline
Definition at line 527 of file json11.h.
 : m_ptr(std::make_shared<JsonArray>(std::move(values))) {}
Json() [11/16]
json11::Json::Json (const object & values) inline
Definition at line 528 of file json11.h.
 : m_ptr(std::make_shared<JsonObject>(values)) {}
Json() [12/16]
json11::Json::Json (Json::object && values) inline
Definition at line 529 of file json11.h.
 : m_ptr(std::make_shared<JsonObject>(std::move(values))) {}
Json() [13/16]
template<class T , class = decltype(&T::to_json)> json11::Json::Json (const T & t) inline
Definition at line 111 of file json11.h.
References type().
 : Json(t.to_json()) {}
Json() [14/16]
template<class M , typename std::enable_if< std::is_constructible< std::string, decltype(std::declval< M >().begin() ->first)>::value &&std::is_constructible< Json, decltype(std::declval< M >().begin() -> second> json11::Json::Json (const M & m) inline
Definition at line 119 of file json11.h.
References type().
 : Json(object(m.begin(), m.end())) {}
Json() [15/16]
template<class V , typename std::enable_if< std::is_constructible< Json, decltype(*std::declval< V >().begin())>::value, int >::type = 0> json11::Json::Json (const V & v) inline
Definition at line 125 of file json11.h.
References Json(), and type().
 : Json(array(v.begin(), v.end())) {}
Json() [16/16]
json11::Json::Json (void *) delete
Member Function Documentation
array_items()
const std::vector< Json > & json11::Json::array_items () const inline
Definition at line 553 of file json11.h.
References m_ptr.
Referenced by is_object(), souffle::ReadStreamJSON::readNextTupleList(), and souffle::ReadStreamJSON::readNextTupleObject().
{
     return m_ptr->array_items();
 }
bool_value()
bool json11::Json::bool_value () const inline
Definition at line 547 of file json11.h.
References m_ptr.
Referenced by is_object().
{
     return m_ptr->bool_value();
 }
dump() [1/2]
void json11::Json::dump (std::string & out) const inline
Definition at line 369 of file json11.h.
References m_ptr.
Referenced by souffle::WriteStreamJSON::writeNextTupleJSON().
{
     m_ptr->dump(out);
 }
dump() [2/2]
std::string json11::Json::dump () const inline
Definition at line 176 of file json11.h.
References err, parse(), json11::STANDARD, and strategy.
Referenced by json11::dump(), has_shape(), and is_object().
{
         std::string out;
         dump(out);
         return out;
     }
has_shape()
bool json11::Json::has_shape (const shape & types, std::string & err) const inline
Definition at line 223 of file json11.h.
References dump(), and is_object().
{
         if (!is_object()) {
             err = "expected JSON object, got " + dump();
             return false;
         }
         for (auto& item : types) {
             if ((*this)[item.first].type() != item.second) {
                 err = "bad type for " + item.first + " in " + dump();
                 return false;
             }
         }
         return true;
     }
int_value()
int json11::Json::int_value () const inline
Definition at line 541 of file json11.h.
References m_ptr.
Referenced by is_object(), and souffle::ReadStreamJSON::readNextElementList().
{
     return m_ptr->int_value();
 }
is_array()
bool json11::Json::is_array () const inline
Definition at line 146 of file json11.h.
References ARRAY, and type().
Referenced by souffle::ReadStreamJSON::readNextElementList().
{
         return type() == ARRAY;
     }
is_bool()
bool json11::Json::is_bool () const inline
Definition at line 140 of file json11.h.
References BOOL, and type().
{
         return type() == BOOL;
     }
is_null()
bool json11::Json::is_null () const inline
Definition at line 134 of file json11.h.
References NUL, and type().
Referenced by souffle::IOAttributesTransformer::getRecordsParams(), souffle::IOAttributesTransformer::getRecordsTypes(), souffle::ReadStreamJSON::readNextElementList(), and souffle::ReadStreamJSON::readNextElementObject().
{
         return type() == NUL;
     }
is_number()
bool json11::Json::is_number () const inline
Definition at line 137 of file json11.h.
References NUMBER, and type().
{
         return type() == NUMBER;
     }
is_object()
bool json11::Json::is_object () const inline
Definition at line 149 of file json11.h.
References array_items(), bool_value(), dump(), i, int_value(), long_value(), number_value(), OBJECT, object_items(), operator[](), string_value(), and type().
Referenced by has_shape(), and souffle::ReadStreamJSON::readNextElementObject().
{
         return type() == OBJECT;
     }
is_string()
bool json11::Json::is_string () const inline
Definition at line 143 of file json11.h.
References STRING, and type().
{
         return type() == STRING;
     }
long_value()
long long json11::Json::long_value () const inline
Definition at line 544 of file json11.h.
References m_ptr.
Referenced by is_object(), souffle::WriteStream::outputRecord(), souffle::WriteStreamJSON::writeNextTupleList(), and souffle::WriteStreamJSON::writeNextTupleObject().
{
     return m_ptr->long_value();
 }
number_value()
double json11::Json::number_value () const inline
Definition at line 538 of file json11.h.
References m_ptr.
Referenced by is_object(), and souffle::ReadStreamJSON::readNextElementList().
{
     return m_ptr->number_value();
 }
object_items()
const std::map< std::string, Json > & json11::Json::object_items () const inline
Definition at line 556 of file json11.h.
References m_ptr.
Referenced by is_object(), and souffle::ReadStreamJSON::readNextElementObject().
{
     return m_ptr->object_items();
 }
operator!=()
bool json11::Json::operator!= (const Json & rhs) const inline
Definition at line 204 of file json11.h.
References rhs.
{
         return !(*this == rhs);
     }
operator<()
bool json11::Json::operator< (const Json & rhs) const inline
Definition at line 620 of file json11.h.
References m_ptr.
Referenced by parse_multi().
{
     if (m_ptr == other.m_ptr) {
         return false;
     }
     if (m_ptr->type() != other.m_ptr->type()) {
         return m_ptr->type() < other.m_ptr->type();
     }
     return m_ptr->less(other.m_ptr.get());
 }
operator<=()
bool json11::Json::operator<= (const Json & rhs) const inline
Definition at line 207 of file json11.h.
{
         return !(rhs < *this);
     }
operator==()
bool json11::Json::operator== (const Json & rhs) const inline
Definition at line 609 of file json11.h.
References m_ptr.
Referenced by parse_multi().
{
     if (m_ptr == other.m_ptr) {
         return true;
     }
     if (m_ptr->type() != other.m_ptr->type()) {
         return false;
     }
     return m_ptr->equals(other.m_ptr.get());
 }
operator>()
bool json11::Json::operator> (const Json & rhs) const inline
Definition at line 210 of file json11.h.
{
         return (rhs < *this);
     }
operator>=()
bool json11::Json::operator>= (const Json & rhs) const inline
Definition at line 213 of file json11.h.
References rhs.
{
         return !(*this < rhs);
     }
operator[]() [1/2]
const Json & json11::Json::operator[] (size_t i) const inline
Definition at line 559 of file json11.h.
References i, and m_ptr.
Referenced by json11::JsonArray::array_items(), is_object(), and json11::JsonObject::object_items().
{
     return (*m_ptr)[i];
 }
operator[]() [2/2]
const Json & json11::Json::operator[] (const std::string & key) const inline
Definition at line 562 of file json11.h.
References m_ptr.
{
     return (*m_ptr)[key];
 }
parse() [1/2]
Json json11::Json::parse (const std::string & in, std::string & err, JsonParse strategy = JsonParse::STANDARD) inline static
Definition at line 1070 of file json11.h.
References err, json11::esc(), and Json().
Referenced by dump(), parse(), souffle::ReadStreamJSON::readNextTuple(), souffle::ReadStreamJSON::ReadStreamJSON(), souffle::SerialisationStream< true >::SerialisationStream(), and souffle::WriteStreamJSON::WriteStreamJSON().
{
     JsonParser parser{in, 0, err, false, strategy};
     Json result = parser.parse_json(0);
     // Check for any trailing garbage
     parser.consume_garbage();
     if (parser.failed) {
         return Json();
     }
     if (parser.i != in.size()) {
         return parser.fail("unexpected trailing " + esc(in[parser.i]));
     }
     return result;
 }
parse() [2/2]
static Json json11::Json::parse (const char * in, std::string & err, JsonParse strategy = JsonParse::STANDARD) inline static
Definition at line 185 of file json11.h.
References parse(), parse_multi(), json11::STANDARD, and strategy.
{
         if (in == nullptr) {
             err = "null input";
             return nullptr;
         }
         return parse(std::string(in), err, strategy);
     }
parse_multi() [1/2]
static std::vector<Json> json11::Json::parse_multi (const std::string & in, std::string::size_type & parser_stop_pos, std::string & err, JsonParse strategy = JsonParse::STANDARD) static
Referenced by parse(), and parse_multi().
parse_multi() [2/2]
static std::vector<Json> json11::Json::parse_multi (const std::string & in, std::string & err, JsonParse strategy = JsonParse::STANDARD) inline static
Definition at line 196 of file json11.h.
References operator<(), operator==(), parse_multi(), rhs, and strategy.
{
         std::string::size_type parser_stop_pos;
         return parse_multi(in, parser_stop_pos, err, strategy);
     }
string_value()
const std::string & json11::Json::string_value () const inline
Definition at line 550 of file json11.h.
References m_ptr.
Referenced by is_object().
{
     return m_ptr->string_value();
 }
type()
Json::Type json11::Json::type () const inline
Definition at line 535 of file json11.h.
References m_ptr.
Referenced by is_array(), is_bool(), is_null(), is_number(), is_object(), is_string(), and Json().
{
     return m_ptr->type();
 }
Field Documentation
m_ptr
std::shared_ptr<JsonValue> json11::Json::m_ptr private
Definition at line 240 of file json11.h.
Referenced by array_items(), bool_value(), dump(), int_value(), long_value(), number_value(), object_items(), operator<(), operator==(), operator[](), string_value(), and type().
The documentation for this class was generated from the following file:
json11.h