souffle: souffle::AstUserDefinedFunctor Class Reference
souffle::AstUserDefinedFunctor Class Reference
User-Defined Functor.
#include <UserDefinedFunctor.h>
Public Member Functions
AstUserDefinedFunctor (std::string name)
AstUserDefinedFunctor (std::string name, VecOwn< AstArgument > args, SrcLocation loc={})
AstUserDefinedFunctor * clone () const override
Create clone.
const std::vector< TypeAttribute > & getArgsTypes () const
TypeAttribute getArgType (const size_t arg) const override
get type of the functor argument
const std::string & getName () const
get name
TypeAttribute getReturnType () const override
get type of the functor argument
void setTypes (std::vector< TypeAttribute > argumentsTypes, TypeAttribute retType)
Public Member Functions inherited from souffle::AstTerm
void addArgument (Own< AstArgument > arg)
add argument to argument list
void apply (const AstNodeMapper &map) override
Apply the mapper to all child nodes.
std::vector< AstArgument * > getArguments () const
get arguments
std::vector< const AstNode * > getChildNodes () const override
Obtain a list of all embedded AST child nodes.
Public Member Functions inherited from souffle::AstNode
AstNode (SrcLocation loc={})
std::string extloc () const
Return source location of the syntactic element.
const SrcLocation & getSrcLoc () const
Return source location of the AstNode.
bool operator!= (const AstNode &other) const
Inequality check for two AST nodes.
bool operator== (const AstNode &other) const
Equivalence check for two AST nodes.
void setSrcLoc (SrcLocation l)
Set source location for the AstNode.
virtual ~AstNode ()=default
Protected Member Functions
bool equal (const AstNode &node) const override
Abstract equality check for two AST nodes.
void print (std::ostream &os) const override
Output to a given output stream.
Protected Member Functions inherited from souffle::AstTerm
template<typename... Operands>
AstTerm (Operands &&... operands)
template<typename... Operands>
AstTerm (SrcLocation loc, Operands &&... operands)
AstTerm (VecOwn< AstArgument > operands, SrcLocation loc={})
Protected Attributes
std::optional< std::vector< TypeAttribute > > argTypes
const std::string name
name of user-defined functor
std::optional< TypeAttribute > returnType
Protected Attributes inherited from souffle::AstTerm
VecOwn< AstArgument > args
Arguments.
Detailed Description
User-Defined Functor.
Definition at line 39 of file UserDefinedFunctor.h.
Constructor & Destructor Documentation
AstUserDefinedFunctor() [1/2]
souffle::AstUserDefinedFunctor::AstUserDefinedFunctor (std::string name) inline explicit
Definition at line 41 of file UserDefinedFunctor.h.
References name.
Referenced by clone().
 : AstFunctor({}, {}), name(std::move(name)){};
AstUserDefinedFunctor() [2/2]
souffle::AstUserDefinedFunctor::AstUserDefinedFunctor (std::string name, VecOwn< AstArgument > args, SrcLocation loc = {}) inline
Definition at line 43 of file UserDefinedFunctor.h.
References name.
                                                                                       {})
             : AstFunctor(std::move(args), std::move(loc)), name(std::move(name)){};
Member Function Documentation
clone()
AstUserDefinedFunctor* souffle::AstUserDefinedFunctor::clone () const inline override virtual
Create clone.
Implements souffle::AstFunctor.
Definition at line 71 of file UserDefinedFunctor.h.
References argTypes, AstUserDefinedFunctor(), souffle::clone(), souffle::AstNode::getSrcLoc(), and returnType.
{
         auto res = new AstUserDefinedFunctor(name, souffle::clone(args), getSrcLoc());
         // Only copy types if they have already been set.
         if (returnType.has_value()) {
             res->setTypes(argTypes.value(), returnType.value());
         }
         return res;
     }
equal()
bool souffle::AstUserDefinedFunctor::equal (const AstNode &) const inline override protected virtual
Abstract equality check for two AST nodes.
Reimplemented from souffle::AstTerm.
Definition at line 85 of file UserDefinedFunctor.h.
References souffle::AstTerm::equal(), and name.
{
         const auto& other = static_cast<const AstUserDefinedFunctor&>(node);
         return name == other.name && AstFunctor::equal(node);
     }
getArgsTypes()
const std::vector<TypeAttribute>& souffle::AstUserDefinedFunctor::getArgsTypes () const inline
Definition at line 67 of file UserDefinedFunctor.h.
References argTypes.
Referenced by souffle::AstToRamTranslator::translateValue().
{
         return argTypes.value();
     }
getArgType()
TypeAttribute souffle::AstUserDefinedFunctor::getArgType (const size_t arg) const inline override virtual
get type of the functor argument
Implements souffle::AstFunctor.
Definition at line 52 of file UserDefinedFunctor.h.
References argTypes.
Referenced by souffle::TypeChecker::visitUserDefinedFunctor().
{
         return argTypes->at(arg);
     }
getName()
const std::string& souffle::AstUserDefinedFunctor::getName () const inline
get name
Definition at line 47 of file UserDefinedFunctor.h.
References name.
Referenced by souffle::AstToRamTranslator::translateValue().
{
         return name;
     }
getReturnType()
TypeAttribute souffle::AstUserDefinedFunctor::getReturnType () const inline override virtual
get type of the functor argument
Implements souffle::AstFunctor.
Definition at line 57 of file UserDefinedFunctor.h.
References returnType.
Referenced by souffle::AstToRamTranslator::translateValue(), and souffle::TypeChecker::visitUserDefinedFunctor().
{
         return returnType.value();
     }
print()
void souffle::AstUserDefinedFunctor::print (std::ostream & os) const inline override protected virtual
Output to a given output stream.
Implements souffle::AstNode.
Definition at line 81 of file UserDefinedFunctor.h.
References souffle::join().
{
         os << '@' << name << "(" << join(args) << ")";
     }
setTypes()
void souffle::AstUserDefinedFunctor::setTypes (std::vector< TypeAttribute > argumentsTypes, TypeAttribute retType) inline
Definition at line 61 of file UserDefinedFunctor.h.
References argTypes, and returnType.
{
         assert(argumentsTypes.size() == args.size() && "Size of types must match size of arguments");
         argTypes = std::move(argumentsTypes);
         returnType = retType;
     }
Field Documentation
argTypes
std::optional<std::vector<TypeAttribute> > souffle::AstUserDefinedFunctor::argTypes protected
Definition at line 90 of file UserDefinedFunctor.h.
Referenced by clone(), getArgsTypes(), getArgType(), and setTypes().
name
const std::string souffle::AstUserDefinedFunctor::name protected
name of user-defined functor
Definition at line 94 of file UserDefinedFunctor.h.
Referenced by AstUserDefinedFunctor(), equal(), and getName().
returnType
std::optional<TypeAttribute> souffle::AstUserDefinedFunctor::returnType protected
Definition at line 91 of file UserDefinedFunctor.h.
Referenced by clone(), getReturnType(), and setTypes().
The documentation for this class was generated from the following file:
ast/UserDefinedFunctor.h