souffle: souffle::profile::Cell< double > Class Template Reference
souffle::profile::Cell< double > Class Template Reference
#include <Cell.h>
Public Member Functions
Cell (double value)
double getDoubleVal () const override
long getLongVal () const override
std::string getStringVal () const override
std::chrono::microseconds getTimeVal () const override
std::string toString (int) const override
Public Member Functions inherited from souffle::profile::CellInterface
virtual ~CellInterface ()=default
Private Attributes
const double value
Detailed Description
template<>
class souffle::profile::Cell< double >
Definition at line 57 of file Cell.h.
Constructor & Destructor Documentation
Cell()
souffle::profile::Cell< double >::Cell (double value) inline
Definition at line 61 of file Cell.h.
 : value(value){};
Member Function Documentation
getDoubleVal()
double souffle::profile::Cell< double >::getDoubleVal () const inline override virtual
Implements souffle::profile::CellInterface.
Definition at line 62 of file Cell.h.
References souffle::profile::Cell< T >::value.
{
         return value;
     }
getLongVal()
long souffle::profile::Cell< double >::getLongVal () const inline override virtual
Implements souffle::profile::CellInterface.
Definition at line 65 of file Cell.h.
{
         std::cerr << "getting long on double cell\n";
         throw this;
     }
getStringVal()
std::string souffle::profile::Cell< double >::getStringVal () const inline override virtual
Implements souffle::profile::CellInterface.
Definition at line 69 of file Cell.h.
{
         std::cerr << "getting string on double cell\n";
         throw this;
     }
getTimeVal()
std::chrono::microseconds souffle::profile::Cell< double >::getTimeVal () const inline override virtual
Implements souffle::profile::CellInterface.
Definition at line 73 of file Cell.h.
{
         std::cerr << "getting time on double cell\n";
         throw this;
     }
toString()
std::string souffle::profile::Cell< double >::toString (int) const inline override virtual
Implements souffle::profile::CellInterface.
Definition at line 77 of file Cell.h.
References souffle::profile::Cell< T >::Cell(), souffle::profile::Tools::cleanString(), souffle::profile::Tools::formatNum(), souffle::profile::CellInterface::getDoubleVal(), souffle::profile::CellInterface::getLongVal(), souffle::profile::CellInterface::getStringVal(), souffle::profile::CellInterface::getTimeVal(), souffle::profile::CellInterface::toString(), and souffle::profile::Cell< T >::value.
{
         return Tools::formatNum(value);
     }
Field Documentation
value
const double souffle::profile::Cell< double >::value private
Definition at line 58 of file Cell.h.
The documentation for this class was generated from the following file:
profile/Cell.h