souffle: souffle::AstAttribute Class Reference
souffle::AstAttribute Class Reference
Intermediate representation of an attribute which stores the name and the type of an attribute.
#include <Attribute.h>
Public Member Functions
AstAttribute (std::string n, AstQualifiedName t, SrcLocation loc={})
AstAttribute * clone () const override
Create a clone (i.e.
const std::string & getName () const
get attribute name
const AstQualifiedName & getTypeName () const
get type name
void setTypeName (AstQualifiedName name)
set type name
Public Member Functions inherited from souffle::AstNode
virtual void apply (const AstNodeMapper &)
Apply the mapper to all child nodes.
AstNode (SrcLocation loc={})
std::string extloc () const
Return source location of the syntactic element.
virtual std::vector< const AstNode * > getChildNodes () const
Obtain a list of all embedded AST child nodes.
const SrcLocation & getSrcLoc () const
Return source location of the AstNode.
bool operator!= (const AstNode &other) const
Inequality check for two AST nodes.
bool operator== (const AstNode &other) const
Equivalence check for two AST nodes.
void setSrcLoc (SrcLocation l)
Set source location for the AstNode.
virtual ~AstNode ()=default
Protected Member Functions
bool equal (const AstNode &node) const override
Abstract equality check for two AST nodes.
void print (std::ostream &os) const override
Output to a given output stream.
Private Attributes
std::string name
Attribute name.
AstQualifiedName typeName
Type name.
Detailed Description
Intermediate representation of an attribute which stores the name and the type of an attribute.
Attribute has the only name attribute
Definition at line 33 of file Attribute.h.
Constructor & Destructor Documentation
AstAttribute()
souffle::AstAttribute::AstAttribute (std::string n, AstQualifiedName t, SrcLocation loc = {}) inline
Definition at line 35 of file Attribute.h.
References souffle::AstNode::AstNode(), name, and typeName.
Referenced by clone().
                                                                     {})
             : AstNode(std::move(loc)), name(std::move(n)), typeName(std::move(t)) {}
Member Function Documentation
clone()
AstAttribute* souffle::AstAttribute::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::AstNode.
Definition at line 53 of file Attribute.h.
References AstAttribute(), souffle::AstNode::getSrcLoc(), name, and typeName.
{
         return new AstAttribute(name, typeName, getSrcLoc());
     }
equal()
bool souffle::AstAttribute::equal (const AstNode &) const inline override protected virtual
Abstract equality check for two AST nodes.
Reimplemented from souffle::AstNode.
Definition at line 62 of file Attribute.h.
References name, and typeName.
{
         const auto& other = static_cast<const AstAttribute&>(node);
         return name == other.name && typeName == other.typeName;
     }
getName()
const std::string& souffle::AstAttribute::getName () const inline
get attribute name
Definition at line 39 of file Attribute.h.
References name.
Referenced by souffle::AstSemanticCheckerImpl::checkRelationDeclaration().
{
         return name;
     }
getTypeName()
const AstQualifiedName& souffle::AstAttribute::getTypeName () const inline
get type name
Definition at line 44 of file Attribute.h.
References typeName.
Referenced by souffle::AstSemanticCheckerImpl::checkRelationDeclaration().
{
         return typeName;
     }
print()
void souffle::AstAttribute::print (std::ostream & os) const inline override protected virtual
Output to a given output stream.
Implements souffle::AstNode.
Definition at line 58 of file Attribute.h.
References name, and typeName.
{
         os << name << ":" << typeName;
     }
setTypeName()
void souffle::AstAttribute::setTypeName (AstQualifiedName name) inline
set type name
Definition at line 49 of file Attribute.h.
References typeName.
{
         typeName = std::move(name);
     }
Field Documentation
name
std::string souffle::AstAttribute::name private
Attribute name.
Definition at line 69 of file Attribute.h.
Referenced by AstAttribute(), clone(), equal(), getName(), and print().
typeName
AstQualifiedName souffle::AstAttribute::typeName private
Type name.
Definition at line 72 of file Attribute.h.
Referenced by AstAttribute(), clone(), equal(), getTypeName(), print(), and setTypeName().
The documentation for this class was generated from the following file:
ast/Attribute.h