souffle: souffle::DisjointSet Class Reference
souffle::DisjointSet Class Reference
Structure that emulates a Disjoint Set, i.e.
#include <UnionFind.h>
Public Member Functions
void clear ()
Clears the DisjointSet of all nodes Invalidates all iterators.
DisjointSet ()=default
DisjointSet (DisjointSet &other)=delete
DisjointSet (DisjointSet &&other)=delete
parent_t findNode (parent_t x)
Equivalent to the find() function in union/find Find the highest ancestor of the provided node - flattening as we go.
std::atomic< block_t > & get (parent_t node) const
Yield reference to the node by its node index.
block_t makeNode ()
Create a node with its parent as itself, rank 0.
DisjointSet & operator= (DisjointSet &ds)=delete
DisjointSet & operator= (DisjointSet &&ds)=delete
bool sameSet (parent_t x, parent_t y)
Check whether the two indices are in the same set.
size_t size ()
Return the number of elements in this disjoint set (not the number of pairs)
void unionNodes (parent_t x, parent_t y)
Union the two specified index nodes.
Static Public Member Functions
static parent_t b2p (const block_t inblock)
Extract parent from block.
static rank_t b2r (const block_t inblock)
Extract rank from block.
static block_t pr2b (const parent_t parent, const rank_t rank)
Yield a block given parent and rank.
Private Member Functions
bool updateRoot (const parent_t x, const rank_t oldrank, const parent_t y, const rank_t newrank)
Update the root of the tree of which x is, to have y as the base instead.
Private Attributes
PiggyList< std::atomic< block_t > > a_blocks
Friends
template<typename TupleType >
class EquivalenceRelation
Detailed Description
Structure that emulates a Disjoint Set, i.e.
a data structure that supports efficient union-find operations
Definition at line 48 of file UnionFind.h.
Constructor & Destructor Documentation
DisjointSet() [1/3]
souffle::DisjointSet::DisjointSet () default
DisjointSet() [2/3]
souffle::DisjointSet::DisjointSet (DisjointSet & other) delete
DisjointSet() [3/3]
souffle::DisjointSet::DisjointSet (DisjointSet && other) delete
Member Function Documentation
b2p()
static parent_t souffle::DisjointSet::b2p (const block_t inblock) inline static
Extract parent from block.
Parameters
inblock the block to be masked
Returns
The parent_t contained in the upper half of block_t
Definition at line 206 of file UnionFind.h.
References souffle::split_size.
Referenced by findNode(), sameSet(), souffle::test::TEST(), souffle::SparseDisjointSet< value_type >::toDense(), and updateRoot().
{
         return (parent_t)(inblock >> split_size);
     };
b2r()
static rank_t souffle::DisjointSet::b2r (const block_t inblock) inline static
Extract rank from block.
Parameters
inblock the block to be masked
Returns
the rank_t contained in the lower half of block_t
Definition at line 215 of file UnionFind.h.
References souffle::rank_mask.
Referenced by findNode(), souffle::test::TEST(), unionNodes(), and updateRoot().
{
         return (rank_t)(inblock & rank_mask);
     };
clear()
void souffle::DisjointSet::clear () inline
Clears the DisjointSet of all nodes Invalidates all iterators.
Definition at line 134 of file UnionFind.h.
References souffle::PiggyList< T >::clear().
Referenced by souffle::SparseDisjointSet< value_type >::clear(), and souffle::test::TEST().
                  {
         a_blocks.clear();
     }
findNode()
parent_t souffle::DisjointSet::findNode (parent_t x) inline
Equivalent to the find() function in union/find Find the highest ancestor of the provided node - flattening as we go.
Parameters
x the node to find the parent of, whilst flattening its set-tree
Returns
The parent of x
Definition at line 91 of file UnionFind.h.
References b2p(), b2r(), and pr2b().
Referenced by souffle::SparseDisjointSet< value_type >::findNode(), sameSet(), souffle::test::TEST(), and unionNodes().
{
         // while x's parent is not itself
         while (x != b2p(get(x))) {
             block_t xState = get(x);
             // yield x's parent's parent
             parent_t newParent = b2p(get(b2p(xState)));
             // construct block out of the original rank and the new parent
             block_t newState = pr2b(newParent, b2r(xState));
             this->get(x).compare_exchange_strong(xState, newState);
             x = newParent;
         }
         return x;
     }
get()
std::atomic<block_t>& souffle::DisjointSet::get (parent_t node) const inline
Yield reference to the node by its node index.
Parameters
node node to be searched
Returns
the parent block of the specified node
Definition at line 80 of file UnionFind.h.
References souffle::PiggyList< T >::get().
{
         auto& ret = a_blocks.get(node);
         return ret;
     };
makeNode()
block_t souffle::DisjointSet::makeNode () inline
Create a node with its parent as itself, rank 0.
Returns
the newly created block
Definition at line 192 of file UnionFind.h.
References souffle::PiggyList< T >::createNode(), souffle::PiggyList< T >::get(), and pr2b().
Referenced by souffle::test::TEST(), and souffle::SparseDisjointSet< value_type >::toDense().
{
         // make node and find out where we've added it
         size_t nodeDetails = a_blocks.createNode();
         a_blocks.get(nodeDetails).store(pr2b(nodeDetails, 0));
         return a_blocks.get(nodeDetails).load();
     };
operator=() [1/2]
DisjointSet& souffle::DisjointSet::operator= (DisjointSet & ds) delete
Referenced by souffle::SparseDisjointSet< value_type >::toDense().
operator=() [2/2]
DisjointSet& souffle::DisjointSet::operator= (DisjointSet && ds) delete
pr2b()
static block_t souffle::DisjointSet::pr2b (const parent_t parent, const rank_t rank) inline static
Yield a block given parent and rank.
Parameters
parent the top half bits
rank the lower half bits
Returns
the resultant block after merge
Definition at line 225 of file UnionFind.h.
Referenced by findNode(), makeNode(), and updateRoot().
{
         return (((block_t)parent) << split_size) | rank;
     };
sameSet()
bool souffle::DisjointSet::sameSet (parent_t x, parent_t y) inline
Check whether the two indices are in the same set.
Parameters
x node to be checked
y node to be checked
Returns
where the two indices are in the same set
Definition at line 144 of file UnionFind.h.
References b2p(), and findNode().
Referenced by souffle::SparseDisjointSet< value_type >::contains(), souffle::SparseDisjointSet< value_type >::sameSet(), and souffle::test::TEST().
{
         while (true) {
             x = findNode(x);
             y = findNode(y);
             if (x == y) return true;
             // if x's parent is itself, they are not the same set
             if (b2p(get(x)) == x) return false;
         }
     }
size()
size_t souffle::DisjointSet::size () inline
Return the number of elements in this disjoint set (not the number of pairs)
Definition at line 70 of file UnionFind.h.
References souffle::PiggyList< T >::size().
Referenced by souffle::SparseDisjointSet< value_type >::size(), and souffle::test::TEST().
{
         auto sz = a_blocks.size();
         return sz;
     };
unionNodes()
void souffle::DisjointSet::unionNodes (parent_t x, parent_t y) inline
Union the two specified index nodes.
Parameters
x node to be unioned
y node to be unioned
Definition at line 159 of file UnionFind.h.
References b2r(), findNode(), and updateRoot().
Referenced by souffle::test::TEST(), and souffle::SparseDisjointSet< value_type >::unionNodes().
{
         while (true) {
             x = findNode(x);
             y = findNode(y);
             // no need to union if both already in same set
             if (x == y) return;
             rank_t xrank = b2r(get(x));
             rank_t yrank = b2r(get(y));
             // if x comes before y (better rank or earlier & equal node)
             if (xrank > yrank || ((xrank == yrank) && x > y)) {
                 std::swap(x, y);
                 std::swap(xrank, yrank);
             }
             // join the trees together
             // perhaps we can optimise the use of compare_exchange_strong here, as we're in a pessimistic loop
             if (!updateRoot(x, xrank, y, yrank)) {
                 continue;
             }
             // make sure that the ranks are orderable
             if (xrank == yrank) {
                 updateRoot(y, yrank, y, yrank + 1);
             }
             break;
         }
     }
updateRoot()
bool souffle::DisjointSet::updateRoot (const parent_t x, const rank_t oldrank, const parent_t y, const rank_t newrank) inline private
Update the root of the tree of which x is, to have y as the base instead.
Parameters
x : old root
oldrank : old root rank
y : new root
newrank : new root rank
Returns
Whether the update succeeded (fails if another root update/union has been perfomed in the interim)
Definition at line 117 of file UnionFind.h.
References b2p(), b2r(), and pr2b().
Referenced by unionNodes().
{
         block_t oldState = get(x);
         parent_t nextN = b2p(oldState);
         rank_t rankN = b2r(oldState);
         if (nextN != x || rankN != oldrank) return false;
         // set the parent and rank of the new record
         block_t newVal = pr2b(y, newrank);
         return this->get(x).compare_exchange_strong(oldState, newVal);
     }
Friends And Related Function Documentation
EquivalenceRelation
template<typename TupleType > friend class EquivalenceRelation friend
Definition at line 50 of file UnionFind.h.
Field Documentation
a_blocks
PiggyList<std::atomic<block_t> > souffle::DisjointSet::a_blocks private
Definition at line 52 of file UnionFind.h.
Referenced by souffle::EquivalenceRelation< t_tuple< 2 > >::genAllDisjointSetLists().
The documentation for this class was generated from the following file:
UnionFind.h