souffle: souffle::FixpointTransformer Class Reference
souffle::FixpointTransformer Class Reference
Transformer that repeatedly executes a sub-transformer until no changes are made.
#include <Fixpoint.h>
Public Member Functions
FixpointTransformer * clone () const override
void disableTransformers (const std::set< std::string > &transforms) override
FixpointTransformer (std::unique_ptr< AstTransformer > transformer)
std::string getName () const override
std::vector< AstTransformer * > getSubtransformers () const override
void setDebugReport () override
void setVerbosity (bool verbose) override
Public Member Functions inherited from souffle::MetaTransformer
bool applySubtransformer (AstTranslationUnit &translationUnit, AstTransformer *transformer)
Public Member Functions inherited from souffle::AstTransformer
bool apply (AstTranslationUnit &translationUnit)
virtual ~AstTransformer ()=default
Private Member Functions
bool transform (AstTranslationUnit &translationUnit) override
Private Attributes
std::unique_ptr< AstTransformer > transformer
Additional Inherited Members
Protected Attributes inherited from souffle::MetaTransformer
bool verbose = false
Detailed Description
Transformer that repeatedly executes a sub-transformer until no changes are made.
Definition at line 37 of file Fixpoint.h.
Constructor & Destructor Documentation
FixpointTransformer()
souffle::FixpointTransformer::FixpointTransformer (std::unique_ptr< AstTransformer > transformer) inline
Definition at line 39 of file Fixpoint.h.
Referenced by clone().
 : transformer(std::move(transformer)) {}
Member Function Documentation
clone()
FixpointTransformer* souffle::FixpointTransformer::clone () const inline override virtual
Implements souffle::MetaTransformer.
Definition at line 72 of file Fixpoint.h.
References souffle::clone(), FixpointTransformer(), and transformer.
{
         return new FixpointTransformer(souffle::clone(transformer));
     }
disableTransformers()
void souffle::FixpointTransformer::disableTransformers (const std::set< std::string > & transforms) inline override virtual
Implements souffle::MetaTransformer.
Definition at line 60 of file Fixpoint.h.
References transformer.
{
         if (auto* mt = dynamic_cast<MetaTransformer*>(transformer.get())) {
             mt->disableTransformers(transforms);
         } else if (transforms.find(transformer->getName()) != transforms.end()) {
             transformer = std::make_unique<NullTransformer>();
         }
     }
getName()
std::string souffle::FixpointTransformer::getName () const inline override virtual
Implements souffle::AstTransformer.
Definition at line 68 of file Fixpoint.h.
{
         return "FixpointTransformer";
     }
getSubtransformers()
std::vector<AstTransformer*> souffle::FixpointTransformer::getSubtransformers () const inline override virtual
Implements souffle::MetaTransformer.
Definition at line 49 of file Fixpoint.h.
References transformer.
{
         return {transformer.get()};
     }
setDebugReport()
void souffle::FixpointTransformer::setDebugReport () inline override virtual
Implements souffle::MetaTransformer.
Definition at line 41 of file Fixpoint.h.
References transformer.
{
         if (auto* mt = dynamic_cast<MetaTransformer*>(transformer.get())) {
             mt->setDebugReport();
         } else {
             transformer = std::make_unique<DebugReporter>(std::move(transformer));
         }
     }
setVerbosity()
void souffle::FixpointTransformer::setVerbosity (bool verbose) inline override virtual
Implements souffle::MetaTransformer.
Definition at line 53 of file Fixpoint.h.
References transformer, and souffle::MetaTransformer::verbose.
{
         this->verbose = verbose;
         if (auto* mt = dynamic_cast<MetaTransformer*>(transformer.get())) {
             mt->setVerbosity(verbose);
         }
     }
transform()
bool souffle::FixpointTransformer::transform (AstTranslationUnit & translationUnit) inline override private virtual
Implements souffle::AstTransformer.
Definition at line 78 of file Fixpoint.h.
References souffle::MetaTransformer::applySubtransformer().
{
         bool changed = false;
         while (applySubtransformer(translationUnit, transformer.get())) {
             changed = true;
         }
         return changed;
     }
Field Documentation
transformer
std::unique_ptr<AstTransformer> souffle::FixpointTransformer::transformer private
Definition at line 77 of file Fixpoint.h.
Referenced by clone(), disableTransformers(), getSubtransformers(), setDebugReport(), and setVerbosity().
The documentation for this class was generated from the following file:
ast/transform/Fixpoint.h