souffle: souffle::AstStringConstant Class Reference
souffle::AstStringConstant Class Reference
String Constant.
#include <StringConstant.h>
Public Member Functions
AstStringConstant (std::string value, SrcLocation loc={})
AstStringConstant * clone () const override
Create clone.
Public Member Functions inherited from souffle::AstConstant
const std::string & getConstant () const
Public Member Functions inherited from souffle::AstNode
virtual void apply (const AstNodeMapper &)
Apply the mapper to all child nodes.
AstNode (SrcLocation loc={})
std::string extloc () const
Return source location of the syntactic element.
virtual std::vector< const AstNode * > getChildNodes () const
Obtain a list of all embedded AST child nodes.
const SrcLocation & getSrcLoc () const
Return source location of the AstNode.
bool operator!= (const AstNode &other) const
Inequality check for two AST nodes.
bool operator== (const AstNode &other) const
Equivalence check for two AST nodes.
void setSrcLoc (SrcLocation l)
Set source location for the AstNode.
virtual ~AstNode ()=default
Protected Member Functions
void print (std::ostream &os) const override
Output to a given output stream.
Protected Member Functions inherited from souffle::AstConstant
AstConstant (std::string value, SrcLocation loc={})
bool equal (const AstNode &node) const override
Abstract equality check for two AST nodes.
Detailed Description
String Constant.
Definition at line 28 of file StringConstant.h.
Constructor & Destructor Documentation
AstStringConstant()
souffle::AstStringConstant::AstStringConstant (std::string value, SrcLocation loc = {}) inline explicit
Definition at line 30 of file StringConstant.h.
References souffle::AstConstant::AstConstant(), and souffle::AstNode::setSrcLoc().
Referenced by clone().
                                                                   {}) : AstConstant(std::move(value)) {
         setSrcLoc(std::move(loc));
     }
Member Function Documentation
clone()
AstStringConstant* souffle::AstStringConstant::clone () const inline override virtual
Create clone.
Implements souffle::AstConstant.
Definition at line 34 of file StringConstant.h.
References AstStringConstant(), souffle::AstConstant::getConstant(), and souffle::AstNode::getSrcLoc().
{
         auto* res = new AstStringConstant(getConstant());
         res->setSrcLoc(getSrcLoc());
         return res;
     }
print()
void souffle::AstStringConstant::print (std::ostream & os) const inline override protected virtual
Output to a given output stream.
Reimplemented from souffle::AstConstant.
Definition at line 41 of file StringConstant.h.
References souffle::AstConstant::getConstant().
{
         os << "\"" << getConstant() << "\"";
     }
The documentation for this class was generated from the following file:
ast/StringConstant.h