souffle: souffle::Type Class Reference
souffle::Type Class Reference
An abstract base class for types to be covered within a type environment.
#include <TypeSystem.h>
Public Member Functions
const AstQualifiedName & getName () const
const TypeEnvironment & getTypeEnvironment () const
bool operator!= (const Type &other) const
bool operator< (const Type &other) const
bool operator== (const Type &other) const
virtual void print (std::ostream &out) const
Type (const Type &other)=delete
virtual ~Type ()=default
Protected Member Functions
Type (const TypeEnvironment &environment, AstQualifiedName name)
Protected Attributes
const TypeEnvironment & environment
A reference to the type environment this type is associated to.
AstQualifiedName name
Friends
std::ostream & operator<< (std::ostream &out, const Type &t)
Detailed Description
An abstract base class for types to be covered within a type environment.
An abstract base class for types within the AST.
Definition at line 43 of file TypeSystem.h.
Constructor & Destructor Documentation
Type() [1/2]
souffle::Type::Type (const Type & other) delete
Referenced by souffle::RecordType::RecordType(), and souffle::UnionType::UnionType().
~Type()
virtual souffle::Type::~Type () virtual default
Type() [2/2]
souffle::Type::Type (const TypeEnvironment & environment, AstQualifiedName name) inline protected
Definition at line 78 of file TypeSystem.h.
             : environment(environment), name(std::move(name)) {}
Member Function Documentation
getName()
const AstQualifiedName& souffle::Type::getName () const inline
Definition at line 49 of file TypeSystem.h.
References name.
Referenced by souffle::getTypeQualifier(), souffle::SubsetType::print(), souffle::UnionType::print(), souffle::RecordType::print(), and souffle::TypeSet::print().
{
         return name;
     }
getTypeEnvironment()
const TypeEnvironment& souffle::Type::getTypeEnvironment () const inline
Definition at line 53 of file TypeSystem.h.
References environment.
Referenced by souffle::getGreatestCommonSubtypes(), souffle::haveCommonSupertype(), souffle::isOfKind(), souffle::isSubtypeOf(), and souffle::TypeEnvironment::isType().
{
         return environment;
     }
operator!=()
bool souffle::Type::operator!= (const Type & other) const inline
Definition at line 61 of file TypeSystem.h.
{
         return !(*this == other);
     }
operator<()
bool souffle::Type::operator< (const Type & other) const inline
Definition at line 65 of file TypeSystem.h.
References name.
{
         return name < other.name;
     }
operator==()
bool souffle::Type::operator== (const Type & other) const inline
Definition at line 57 of file TypeSystem.h.
{
         return this == &other;
     }
print()
virtual void souffle::Type::print (std::ostream & out) const inline virtual
Reimplemented in souffle::SubsetRecordType, souffle::RecordType, souffle::UnionType, souffle::PrimitiveType, and souffle::SubsetType.
Definition at line 69 of file TypeSystem.h.
References name.
Referenced by souffle::TypeEnvironment::getConstantNumericTypes(), souffle::RecordType::getFields(), and souffle::UnionType::setElements().
{
         out << name;
     }
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & out, const Type & t) friend
Definition at line 73 of file TypeSystem.h.
{
         return t.print(out), out;
     }
Field Documentation
environment
const TypeEnvironment& souffle::Type::environment protected
A reference to the type environment this type is associated to.
Definition at line 82 of file TypeSystem.h.
Referenced by getTypeEnvironment().
name
AstQualifiedName souffle::Type::name protected
Definition at line 84 of file TypeSystem.h.
Referenced by souffle::TypeEnvironment::createType(), getName(), operator<(), print(), and souffle::PrimitiveType::print().
The documentation for this class was generated from the following file:
ast/TypeSystem.h