souffle: souffle::SynthesiserIndirectRelation Class Reference
souffle::SynthesiserIndirectRelation Class Reference
#include <SynthesiserRelation.h>
Public Member Functions
void computeIndices () override
Generate index set for a indirect indexed relation.
void generateTypeStruct (std::ostream &out) override
Generate type struct of a indirect indexed relation.
std::string getTypeName () override
Generate type name of a indirect indexed relation.
SynthesiserIndirectRelation (const RamRelation &ramRel, const MinIndexSelection &indexSet, bool isProvenance)
Public Member Functions inherited from souffle::SynthesiserRelation
size_t getArity () const
Get arity of relation.
const std::string & getDataStructure () const
Get data structure of relation.
MinIndexSelection::OrderCollection getIndices () const
Get list of indices used for relation, guaranteed that original indices in MinIndexSelection come before any generated indices.
const MinIndexSelection & getMinIndexSelection () const
Get stored MinIndexSelection.
std::set< int > getProvenenceIndexNumbers () const
const RamRelation & getRamRelation () const
Get stored RamRelation.
SynthesiserRelation (const RamRelation &rel, const MinIndexSelection &indices, const bool isProvenance=false)
virtual ~SynthesiserRelation ()=default
Additional Inherited Members
Static Public Member Functions inherited from souffle::SynthesiserRelation
static std::unique_ptr< SynthesiserRelation > getSynthesiserRelation (const RamRelation &ramRel, const MinIndexSelection &indexSet, bool isProvenance)
Factory method to generate a SynthesiserRelation.
Protected Attributes inherited from souffle::SynthesiserRelation
MinIndexSelection::OrderCollection computedIndices
The final list of indices used.
std::string dataStructure
The data structure used for the relation.
const MinIndexSelection & indices
Indices used for this relation.
const bool isProvenance
Is this relation used with provenance.
size_t masterIndex = -1
The number of the master index.
std::set< int > provenanceIndexNumbers
The list of indices added for provenance computation.
const RamRelation & relation
Ram relation referred to by this.
Detailed Description
Definition at line 127 of file SynthesiserRelation.h.
Constructor & Destructor Documentation
SynthesiserIndirectRelation()
souffle::SynthesiserIndirectRelation::SynthesiserIndirectRelation (const RamRelation & ramRel, const MinIndexSelection & indexSet, bool isProvenance) inline
Definition at line 129 of file SynthesiserRelation.h.
References souffle::SynthesiserRelation::computeIndices(), souffle::SynthesiserRelation::generateTypeStruct(), and souffle::SynthesiserRelation::getTypeName().
             : SynthesiserRelation(ramRel, indexSet, isProvenance) {}
Member Function Documentation
computeIndices()
void souffle::SynthesiserIndirectRelation::computeIndices () override virtual
Generate index set for a indirect indexed relation.
Implements souffle::SynthesiserRelation.
Definition at line 455 of file SynthesiserRelation.cpp.
References souffle::SynthesiserRelation::computedIndices, souffle::MinIndexSelection::getAllOrders(), souffle::SynthesiserRelation::getArity(), i, souffle::SynthesiserRelation::indices, souffle::SynthesiserRelation::isProvenance, and souffle::SynthesiserRelation::masterIndex.
{
     assert(!isProvenance && "indirect indexes cannot used for provenance");
     // Generate and set indices
     MinIndexSelection::OrderCollection inds = indices.getAllOrders();
     // generate a full index if no indices exist
     assert(!inds.empty() && "no full index in relation");
     // check for full index
     for (size_t i = 0; i < inds.size(); i++) {
         auto& ind = inds[i];
         if (ind.size() == getArity()) {
             masterIndex = i;
             break;
         }
     }
     assert(masterIndex < inds.size() && "no full index in relation");
     computedIndices = inds;
 }
generateTypeStruct()
void souffle::SynthesiserIndirectRelation::generateTypeStruct (std::ostream & out) override virtual
Generate type struct of a indirect indexed relation.
Implements souffle::SynthesiserRelation.
Definition at line 493 of file SynthesiserRelation.cpp.
References souffle::MinIndexSelection::getAllOrders(), souffle::SynthesiserRelation::getArity(), souffle::SynthesiserRelation::getIndices(), souffle::MinIndexSelection::getLexOrder(), souffle::SynthesiserRelation::getMinIndexSelection(), souffle::SynthesiserRelation::getTypeName(), i, souffle::join(), souffle::SynthesiserRelation::masterIndex, and souffle::None.
{
     size_t arity = getArity();
     const auto& inds = getIndices();
     size_t numIndexes = inds.size();
     std::map<MinIndexSelection::LexOrder, int> indexToNumMap;
     // struct definition
     out << "struct " << getTypeName() << " {\n";
     // stored tuple type
     out << "using t_tuple = Tuple<RamDomain, " << arity << ">;\n";
     // table and lock required for storing actual data for indirect indices
     out << "Table<t_tuple> dataTable;\n";
     out << "Lock insert_lock;\n";
     // btree types
     for (size_t i = 0; i < inds.size(); i++) {
         auto ind = inds[i];
         if (i < getMinIndexSelection().getAllOrders().size()) {
             indexToNumMap[getMinIndexSelection().getAllOrders()[i]] = i;
         }
         std::string comparator = "t_comparator_" + std::to_string(i);
         out << "struct " << comparator << "{\n";
         out << " int operator()(const t_tuple *a, const t_tuple *b) const {\n";
         out << "  return ";
         std::function<void(size_t)> gencmp = [&](size_t i) {
             size_t attrib = ind[i];
             out << "((*a)[" << attrib << "] < (*b)[" << attrib << "]) ? -1 : (((*a)[" << attrib << "] > (*b)["
                 << attrib << "]) ? 1 :(";
             if (i + 1 < ind.size()) {
                 gencmp(i + 1);
             } else {
                 out << "0";
             }
             out << "))";
         };
         gencmp(0);
         out << ";\n }\n";
         out << "bool less(const t_tuple *a, const t_tuple *b) const {\n";
         out << "  return ";
         std::function<void(size_t)> genless = [&](size_t i) {
             size_t attrib = ind[i];
             out << " (*a)[" << attrib << "] < (*b)[" << attrib << "]";
             if (i + 1 < ind.size()) {
                 out << "|| ((*a)[" << attrib << "] == (*b)[" << attrib << "] && (";
                 genless(i + 1);
                 out << "))";
             }
         };
         genless(0);
         out << ";\n }\n";
         out << "bool equal(const t_tuple *a, const t_tuple *b) const {\n";
         out << "return ";
         std::function<void(size_t)> geneq = [&](size_t i) {
             size_t attrib = ind[i];
             out << "(*a)[" << attrib << "] == (*b)[" << attrib << "]";
             if (i + 1 < ind.size()) {
                 out << "&&";
                 geneq(i + 1);
             }
         };
         geneq(0);
         out << ";\n }\n";
         out << "};\n";
         if (ind.size() == arity) {
             out << "using t_ind_" << i << " = btree_set<const t_tuple*," << comparator << ">;\n";
         } else {
             out << "using t_ind_" << i << " = btree_multiset<const t_tuple*," << comparator << ">;\n";
         }
         out << "t_ind_" << i << " ind_" << i << ";\n";
     }
     // typedef deref iterators
     for (size_t i = 0; i < numIndexes; i++) {
         out << "using iterator_" << i << " = IterDerefWrapper<typename t_ind_" << i << "::iterator>;\n";
     }
     out << "using iterator = iterator_" << masterIndex << ";\n";
     // Create a struct storing the context hints for each index
     out << "struct context {\n";
     for (size_t i = 0; i < numIndexes; i++) {
         out << "t_ind_" << i << "::operation_hints hints_" << i << ";\n";
     }
     out << "};\n";
     out << "context createContext() { return context(); }\n";
     // insert methods
     out << "bool insert(const t_tuple& t) {\n";
     out << "context h;\n";
     out << "return insert(t, h);\n";
     out << "}\n";
     out << "bool insert(const t_tuple& t, context& h) {\n";
     out << "const t_tuple* masterCopy = nullptr;\n";
     out << "{\n";
     out << "auto lease = insert_lock.acquire();\n";
     out << "if (contains(t, h)) return false;\n";
     out << "masterCopy = &dataTable.insert(t);\n";
     out << "ind_" << masterIndex << ".insert(masterCopy, h.hints_" << masterIndex << ");\n";
     out << "}\n";
     for (size_t i = 0; i < numIndexes; i++) {
         if (i != masterIndex) {
             out << "ind_" << i << ".insert(masterCopy, h.hints_" << i << ");\n";
         }
     }
     out << "return true;\n";
     out << "}\n";
     out << "bool insert(const RamDomain* ramDomain) {\n";
     out << "RamDomain data[" << arity << "];\n";
     out << "std::copy(ramDomain, ramDomain + " << arity << ", data);\n";
     out << "const t_tuple& tuple = reinterpret_cast<const t_tuple&>(data);\n";
     out << "context h;\n";
     out << "return insert(tuple, h);\n";
     out << "}\n";  // end of insert(RamDomain*)
     std::vector<std::string> decls;
     std::vector<std::string> params;
     for (size_t i = 0; i < arity; i++) {
         decls.push_back("RamDomain a" + std::to_string(i));
         params.push_back("a" + std::to_string(i));
     }
     out << "bool insert(" << join(decls, ",") << ") {\n";
     out << "RamDomain data[" << arity << "] = {" << join(params, ",") << "};\n";
     out << "return insert(data);\n";
     out << "}\n";  // end of insert(RamDomain x1, RamDomain x2, ...)
     // contains methods
     out << "bool contains(const t_tuple& t, context& h) const {\n";
     out << "return ind_" << masterIndex << ".contains(&t, h.hints_" << masterIndex << ");\n";
     out << "}\n";
     out << "bool contains(const t_tuple& t) const {\n";
     out << "context h;\n";
     out << "return contains(t, h);\n";
     out << "}\n";
     // size method
     out << "std::size_t size() const {\n";
     out << "return ind_" << masterIndex << ".size();\n";
     out << "}\n";
     // find methods
     out << "iterator find(const t_tuple& t, context& h) const {\n";
     out << "return ind_" << masterIndex << ".find(&t, h.hints_" << masterIndex << ");\n";
     out << "}\n";
     out << "iterator find(const t_tuple& t) const {\n";
     out << "context h;\n";
     out << "return find(t, h);\n";
     out << "}\n";
     // empty lowerUpperRange method
     out << "range<iterator> lowerUpperRange_0(const t_tuple& lower, const t_tuple& upper, context& h) const "
            "{\n";
     out << "return range<iterator>(ind_" << masterIndex << ".begin(),ind_" << masterIndex << ".end());\n";
     out << "}\n";
     out << "range<iterator> lowerUpperRange_0(const t_tuple& lower, const t_tuple& upper) const {\n";
     out << "return range<iterator>(ind_" << masterIndex << ".begin(),ind_" << masterIndex << ".end());\n";
     out << "}\n";
     // lowerUpperRange methods for each pattern which is used to search this relation
     for (auto search : getMinIndexSelection().getSearches()) {
         auto& lexOrder = getMinIndexSelection().getLexOrder(search);
         size_t indNum = indexToNumMap[lexOrder];
         out << "range<iterator_" << indNum << "> lowerUpperRange_" << search;
         out << "(const t_tuple& lower, const t_tuple& upper, context& h) const {\n";
         // count size of search pattern
         size_t indSize = 0;
         for (size_t column = 0; column < arity; column++) {
             if (search[column] != AttributeConstraint::None) {
                 indSize++;
             }
         }
         // use the more efficient find() method if the search pattern is full
         if (indSize == arity) {
             out << "auto pos = find(lower, h);\n";
             out << "auto fin = end();\n";
             out << "if (pos != fin) {fin = pos; ++fin;}\n";
             out << "return make_range(pos, fin);\n";
         } else {
             // generate lower and upper bounds for range search
             out << "t_tuple low(lower); t_tuple high(lower);\n";
             // check which indices to pad out
             for (size_t column = 0; column < arity; column++) {
                 // if bit number column is not set
                 if (search[column] == AttributeConstraint::None) {
                     out << "low[" << column << "] = MIN_RAM_SIGNED;\n";
                     out << "high[" << column << "] = MAX_RAM_SIGNED;\n";
                 }
             }
             out << "return range<iterator_" << indNum << ">(ind_" << indNum << ".lower_bound(&low, h.hints_"
                 << indNum << "), ind_" << indNum << ".upper_bound(&high, h.hints_" << indNum << "));\n";
         }
         out << "}\n";
         out << "range<iterator_" << indNum << "> lowerUpperRange_" << search;
         out << "(const t_tuple& lower, const t_tuple& upper) const {\n";
         out << "context h;\n";
         out << "return lowerUpperRange_" << search << "(lower, upper, h);\n";
         out << "}\n";
     }
     // empty method
     out << "bool empty() const {\n";
     out << "return ind_" << masterIndex << ".empty();\n";
     out << "}\n";
     // partition method
     out << "std::vector<range<iterator>> partition() const {\n";
     out << "std::vector<range<iterator>> res;\n";
     out << "for (const auto& cur : ind_" << masterIndex << ".getChunks(400)) {\n";
     out << "    res.push_back(make_range(derefIter(cur.begin()), derefIter(cur.end())));\n";
     out << "}\n";
     out << "return res;\n";
     out << "}\n";
     // purge method
     out << "void purge() {\n";
     for (size_t i = 0; i < numIndexes; i++) {
         out << "ind_" << i << ".clear();\n";
     }
     out << "dataTable.clear();\n";
     out << "}\n";
     // begin and end iterators
     out << "iterator begin() const {\n";
     out << "return ind_" << masterIndex << ".begin();\n";
     out << "}\n";
     out << "iterator end() const {\n";
     out << "return ind_" << masterIndex << ".end();\n";
     out << "}\n";
     // printStatistics method
     out << "void printStatistics(std::ostream& o) const {\n";
     for (size_t i = 0; i < numIndexes; i++) {
         out << "o << \" arity " << arity << " indirect b-tree index " << i << " lex-order " << inds[i]
             << "\\n\";\n";
         out << "ind_" << i << ".printStats(o);\n";
     }
     out << "}\n";
     // end struct
     out << "};\n";
 }
getTypeName()
std::string souffle::SynthesiserIndirectRelation::getTypeName () override virtual
Generate type name of a indirect indexed relation.
Implements souffle::SynthesiserRelation.
Definition at line 477 of file SynthesiserRelation.cpp.
References souffle::SynthesiserRelation::getArity(), souffle::SynthesiserRelation::getIndices(), souffle::SynthesiserRelation::getMinIndexSelection(), and souffle::join().
{
     std::stringstream res;
     res << "t_btree_" << getArity();
     for (auto& ind : getIndices()) {
         res << "__" << join(ind, "_");
     }
     for (auto& search : getMinIndexSelection().getSearches()) {
         res << "__" << search;
     }
     return res.str();
 }
The documentation for this class was generated from the following files:
synthesiser/SynthesiserRelation.h
synthesiser/SynthesiserRelation.cpp