souffle: souffle::AstPragma Class Reference
souffle::AstPragma Class Reference
Representation of a global option.
#include <Pragma.h>
Public Member Functions
AstPragma (std::string key, std::string value, SrcLocation loc={})
AstPragma * clone () const override
Create a clone (i.e.
std::pair< std::string, std::string > getkvp () const
Public Member Functions inherited from souffle::AstNode
virtual void apply (const AstNodeMapper &)
Apply the mapper to all child nodes.
AstNode (SrcLocation loc={})
std::string extloc () const
Return source location of the syntactic element.
virtual std::vector< const AstNode * > getChildNodes () const
Obtain a list of all embedded AST child nodes.
const SrcLocation & getSrcLoc () const
Return source location of the AstNode.
bool operator!= (const AstNode &other) const
Inequality check for two AST nodes.
bool operator== (const AstNode &other) const
Equivalence check for two AST nodes.
void setSrcLoc (SrcLocation l)
Set source location for the AstNode.
virtual ~AstNode ()=default
Protected Member Functions
bool equal (const AstNode &node) const override
Abstract equality check for two AST nodes.
void print (std::ostream &os) const override
Output to a given output stream.
Protected Attributes
std::string key
Name of the key.
std::string value
Value.
Detailed Description
Representation of a global option.
Definition at line 31 of file Pragma.h.
Constructor & Destructor Documentation
AstPragma()
souffle::AstPragma::AstPragma (std::string key, std::string value, SrcLocation loc = {}) inline
Definition at line 33 of file Pragma.h.
References souffle::AstNode::AstNode(), key, and value.
Referenced by clone().
                                                                 {})
             : AstNode(std::move(loc)), key(std::move(key)), value(std::move(value)) {}
Member Function Documentation
clone()
AstPragma* souffle::AstPragma::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::AstNode.
Definition at line 36 of file Pragma.h.
References AstPragma(), and souffle::AstNode::getSrcLoc().
{
         return new AstPragma(key, value, getSrcLoc());
     }
equal()
bool souffle::AstPragma::equal (const AstNode &) const inline override protected virtual
Abstract equality check for two AST nodes.
Reimplemented from souffle::AstNode.
Definition at line 50 of file Pragma.h.
References key, and value.
{
         const auto& other = static_cast<const AstPragma&>(node);
         return other.key == key && other.value == value;
     }
getkvp()
std::pair<std::string, std::string> souffle::AstPragma::getkvp () const inline
Definition at line 41 of file Pragma.h.
References key, and value.
Referenced by souffle::AstPragmaChecker::transform().
{
         return std::pair<std::string, std::string>(key, value);
     }
print()
void souffle::AstPragma::print (std::ostream & os) const inline override protected virtual
Output to a given output stream.
Implements souffle::AstNode.
Definition at line 46 of file Pragma.h.
{
         os << ".pragma " << key << " " << value << "\n";
     }
Field Documentation
key
std::string souffle::AstPragma::key protected
Name of the key.
Definition at line 56 of file Pragma.h.
Referenced by AstPragma(), equal(), and getkvp().
value
std::string souffle::AstPragma::value protected
Value.
Definition at line 59 of file Pragma.h.
Referenced by AstPragma(), equal(), and getkvp().
The documentation for this class was generated from the following file:
ast/Pragma.h