souffle: souffle::profile::OutputProcessor Class Reference
souffle::profile::OutputProcessor Class Reference
#include <OutputProcessor.h>
Public Member Functions
Table getAtomTable (std::string strRel, std::string strRul) const
const std::shared_ptr< ProgramRun > & getProgramRun () const
Table getRelTable () const
Table getRulTable () const
Table getSubrulTable (std::string strRel, std::string strRul) const
Table getVersionAtoms (std::string strRel, std::string strRul, int version) const
Table getVersions (std::string strRel, std::string strRul) const
OutputProcessor ()
Private Attributes
std::shared_ptr< ProgramRun > programRun
Detailed Description
Definition at line 31 of file OutputProcessor.h.
Constructor & Destructor Documentation
OutputProcessor()
souffle::profile::OutputProcessor::OutputProcessor () inline
Definition at line 36 of file OutputProcessor.h.
                       {
         programRun = std::make_shared<ProgramRun>(ProgramRun());
     }
Member Function Documentation
getAtomTable()
Table souffle::profile::OutputProcessor::getAtomTable (std::string strRel, std::string strRul) const inline
Definition at line 196 of file OutputProcessor.h.
References souffle::profile::Table::addRow(), programRun, and rule.
Referenced by genJsonAtoms(), and getProgramRun().
{
     const std::unordered_map<std::string, std::shared_ptr<Relation>>& relationMap =
             programRun->getRelationMap();
     Table table;
     for (auto& current : relationMap) {
         std::shared_ptr<Relation> rel = current.second;
         if (rel->getId() != strRel) {
             continue;
         }
         for (auto& current : rel->getRuleMap()) {
             std::shared_ptr<Rule> rule = current.second;
             if (rule->getId() != strRul) {
                 continue;
             }
             for (auto& atom : rule->getAtoms()) {
                 Row row(4);
                 row[0] = std::make_shared<Cell<std::string>>(atom.rule);
                 row[1] = std::make_shared<Cell<std::string>>(atom.identifier);
                 row[2] = std::make_shared<Cell<long>>(atom.level);
                 row[3] = std::make_shared<Cell<long>>(atom.frequency);
                 table.addRow(std::make_shared<Row>(row));
             }
         }
     }
     return table;
 }
getProgramRun()
const std::shared_ptr<ProgramRun>& souffle::profile::OutputProcessor::getProgramRun () const inline
Definition at line 40 of file OutputProcessor.h.
References getAtomTable(), getRelTable(), getRulTable(), getSubrulTable(), getVersionAtoms(), getVersions(), and programRun.
Referenced by genJsonAtoms(), souffle::profile::Tui::genJsonRelations(), souffle::genJsonRules(), souffle::profile::Tui::genJsonTop(), and souffle::profile::Tui::Tui().
{
         return programRun;
     }
getRelTable()
Table souffle::profile::OutputProcessor::getRelTable () const inline
Definition at line 74 of file OutputProcessor.h.
References souffle::profile::Table::addRow(), and programRun.
Referenced by genJsonAtoms(), getProgramRun(), and souffle::profile::Tui::runCommand().
{
     const std::unordered_map<std::string, std::shared_ptr<Relation>>& relationMap =
             programRun->getRelationMap();
     Table table;
     for (auto& rel : relationMap) {
         std::shared_ptr<Relation> r = rel.second;
         Row row(13);
         auto total_time = r->getNonRecTime() + r->getRecTime() + r->getCopyTime();
         row[0] = std::make_shared<Cell<std::chrono::microseconds>>(total_time);
         row[1] = std::make_shared<Cell<std::chrono::microseconds>>(r->getNonRecTime());
         row[2] = std::make_shared<Cell<std::chrono::microseconds>>(r->getRecTime());
         row[3] = std::make_shared<Cell<std::chrono::microseconds>>(r->getCopyTime());
         row[4] = std::make_shared<Cell<long>>(r->size());
         row[5] = std::make_shared<Cell<std::string>>(r->getName());
         row[6] = std::make_shared<Cell<std::string>>(r->getId());
         row[7] = std::make_shared<Cell<std::string>>(r->getLocator());
         if (total_time.count() != 0) {
             row[8] = std::make_shared<Cell<long>>(r->size() / (total_time.count() / 1000000.0));
         } else {
             row[8] = std::make_shared<Cell<long>>(r->size());
         }
         row[9] = std::make_shared<Cell<std::chrono::microseconds>>(r->getLoadtime());
         row[10] = std::make_shared<Cell<std::chrono::microseconds>>(r->getSavetime());
         row[11] = std::make_shared<Cell<long>>(r->getMaxRSSDiff());
         row[12] = std::make_shared<Cell<long>>(r->getReads());
         table.addRow(std::make_shared<Row>(row));
     }
     return table;
 }
getRulTable()
Table souffle::profile::OutputProcessor::getRulTable () const inline
Definition at line 118 of file OutputProcessor.h.
References souffle::profile::Table::addRow(), programRun, and rule.
Referenced by genJsonAtoms(), getProgramRun(), and souffle::profile::Tui::runCommand().
{
     const std::unordered_map<std::string, std::shared_ptr<Relation>>& relationMap =
             programRun->getRelationMap();
     std::unordered_map<std::string, std::shared_ptr<Row>> ruleMap;
     for (auto& rel : relationMap) {
         for (auto& current : rel.second->getRuleMap()) {
             Row row(11);
             std::shared_ptr<Rule> rule = current.second;
             row[0] = std::make_shared<Cell<std::chrono::microseconds>>(rule->getRuntime());
             row[1] = std::make_shared<Cell<std::chrono::microseconds>>(rule->getRuntime());
             row[2] = std::make_shared<Cell<std::chrono::microseconds>>(std::chrono::microseconds(0));
             row[3] = std::make_shared<Cell<std::chrono::microseconds>>(std::chrono::microseconds(0));
             row[4] = std::make_shared<Cell<long>>(rule->size());
             row[5] = std::make_shared<Cell<std::string>>(rule->getName());
             row[6] = std::make_shared<Cell<std::string>>(rule->getId());
             row[7] = std::make_shared<Cell<std::string>>(rel.second->getName());
             row[8] = std::make_shared<Cell<long>>(0);
             row[10] = std::make_shared<Cell<std::string>>(rule->getLocator());
             ruleMap.emplace(rule->getName(), std::make_shared<Row>(row));
         }
         for (auto& iter : rel.second->getIterations()) {
             for (auto& current : iter->getRules()) {
                 std::shared_ptr<Rule> rule = current.second;
                 if (ruleMap.find(rule->getName()) != ruleMap.end()) {
                     Row row = *ruleMap[rule->getName()];
                     row[2] = std::make_shared<Cell<std::chrono::microseconds>>(
                             row[2]->getTimeVal() + rule->getRuntime());
                     row[4] = std::make_shared<Cell<long>>(row[4]->getLongVal() + rule->size());
                     row[0] = std::make_shared<Cell<std::chrono::microseconds>>(
                             row[0]->getTimeVal() + rule->getRuntime());
                     ruleMap[rule->getName()] = std::make_shared<Row>(row);
                 } else {
                     Row row(11);
                     row[0] = std::make_shared<Cell<std::chrono::microseconds>>(rule->getRuntime());
                     row[1] = std::make_shared<Cell<std::chrono::microseconds>>(std::chrono::microseconds(0));
                     row[2] = std::make_shared<Cell<std::chrono::microseconds>>(rule->getRuntime());
                     row[3] = std::make_shared<Cell<std::chrono::microseconds>>(std::chrono::microseconds(0));
                     row[4] = std::make_shared<Cell<long>>(rule->size());
                     row[5] = std::make_shared<Cell<std::string>>(rule->getName());
                     row[6] = std::make_shared<Cell<std::string>>(rule->getId());
                     row[7] = std::make_shared<Cell<std::string>>(rel.second->getName());
                     row[8] = std::make_shared<Cell<long>>(rule->getVersion());
                     row[10] = std::make_shared<Cell<std::string>>(rule->getLocator());
                     ruleMap[rule->getName()] = std::make_shared<Row>(row);
                 }
             }
         }
         for (auto& current : ruleMap) {
             std::shared_ptr<Row> row = current.second;
             Row t = *row;
             std::chrono::microseconds val = t[1]->getTimeVal() + t[2]->getTimeVal() + t[3]->getTimeVal();
             t[0] = std::make_shared<Cell<std::chrono::microseconds>>(val);
             if (t[0]->getTimeVal().count() != 0) {
                 t[9] = std::make_shared<Cell<double>>(t[4]->getLongVal() / (t[0]->getDoubleVal() * 1000));
             } else {
                 t[9] = std::make_shared<Cell<double>>(t[4]->getLongVal() / 1.0);
             }
             current.second = std::make_shared<Row>(t);
         }
     }
     Table table;
     for (auto& current : ruleMap) {
         table.addRow(current.second);
     }
     return table;
 }
getSubrulTable()
Table souffle::profile::OutputProcessor::getSubrulTable (std::string strRel, std::string strRul) const inline
Definition at line 231 of file OutputProcessor.h.
References souffle::profile::Table::addRow(), programRun, and rule.
Referenced by getProgramRun().
{
     const std::unordered_map<std::string, std::shared_ptr<Relation>>& relationMap =
             programRun->getRelationMap();
     Table table;
     for (auto& current : relationMap) {
         std::shared_ptr<Relation> rel = current.second;
         if (rel->getId() != strRel) {
             continue;
         }
         for (auto& current : rel->getRuleMap()) {
             std::shared_ptr<Rule> rule = current.second;
             if (rule->getId() != strRul) {
                 continue;
             }
             for (auto& atom : rule->getAtoms()) {
                 Row row(1);
                 row[0] = std::make_shared<Cell<std::string>>(atom.rule);
                 table.addRow(std::make_shared<Row>(row));
             }
         }
     }
     return table;
 }
getVersionAtoms()
Table souffle::profile::OutputProcessor::getVersionAtoms (std::string strRel, std::string strRul, int version) const inline
Definition at line 342 of file OutputProcessor.h.
References souffle::profile::Table::addRow(), programRun, and rule.
Referenced by genJsonAtoms(), and getProgramRun().
{
     const std::unordered_map<std::string, std::shared_ptr<Relation>>& relationMap =
             programRun->getRelationMap();
     Table table;
     std::shared_ptr<Relation> rel;
     for (auto& current : relationMap) {
         if (current.second->getId() == strRel) {
             rel = current.second;
             break;
         }
     }
     if (rel == nullptr) {
         return table;
     }
     for (auto& iter : rel->getIterations()) {
         for (auto& current : iter->getRules()) {
             std::shared_ptr<Rule> rule = current.second;
             if (rule->getLocator() == srcLocator && rule->getVersion() == version) {
                 for (auto& atom : rule->getAtoms()) {
                     Row row(4);
                     row[0] = std::make_shared<Cell<std::string>>(atom.rule);
                     row[1] = std::make_shared<Cell<std::string>>(atom.identifier);
                     row[2] = std::make_shared<Cell<long>>(atom.level);
                     row[3] = std::make_shared<Cell<long>>(atom.frequency);
                     table.addRow(std::make_shared<Row>(row));
                 }
             }
         }
     }
     return table;
 }
getVersions()
Table souffle::profile::OutputProcessor::getVersions (std::string strRel, std::string strRul) const inline
Definition at line 273 of file OutputProcessor.h.
References souffle::profile::Table::addRow(), programRun, and rule.
Referenced by genJsonAtoms(), souffle::genJsonRules(), and getProgramRun().
{
     const std::unordered_map<std::string, std::shared_ptr<Relation>>& relationMap =
             programRun->getRelationMap();
     Table table;
     std::shared_ptr<Relation> rel;
     for (auto& current : relationMap) {
         if (current.second->getId() == strRel) {
             rel = current.second;
             break;
         }
     }
     if (rel == nullptr) {
         return table;
     }
     std::unordered_map<std::string, std::shared_ptr<Row>> ruleMap;
     for (auto& iter : rel->getIterations()) {
         for (auto& current : iter->getRules()) {
             std::shared_ptr<Rule> rule = current.second;
             if (rule->getId() == strRul) {
                 std::string strTemp =
                         rule->getName() + rule->getLocator() + std::to_string(rule->getVersion());
                 if (ruleMap.find(strTemp) != ruleMap.end()) {
                     Row row = *ruleMap[strTemp];
                     row[2] = std::make_shared<Cell<std::chrono::microseconds>>(
                             row[2]->getTimeVal() + rule->getRuntime());
                     row[4] = std::make_shared<Cell<long>>(row[4]->getLongVal() + rule->size());
                     row[0] = std::make_shared<Cell<std::chrono::microseconds>>(rule->getRuntime());
                     ruleMap[strTemp] = std::make_shared<Row>(row);
                 } else {
                     Row row(10);
                     row[1] = std::make_shared<Cell<std::chrono::microseconds>>(std::chrono::microseconds(0));
                     row[2] = std::make_shared<Cell<std::chrono::microseconds>>(rule->getRuntime());
                     row[3] = std::make_shared<Cell<std::chrono::microseconds>>(std::chrono::microseconds(0));
                     row[4] = std::make_shared<Cell<long>>(rule->size());
                     row[5] = std::make_shared<Cell<std::string>>(rule->getName());
                     row[6] = std::make_shared<Cell<std::string>>(rule->getId());
                     row[7] = std::make_shared<Cell<std::string>>(rel->getName());
                     row[8] = std::make_shared<Cell<long>>(rule->getVersion());
                     row[9] = std::make_shared<Cell<std::string>>(rule->getLocator());
                     row[0] = std::make_shared<Cell<std::chrono::microseconds>>(rule->getRuntime());
                     ruleMap[strTemp] = std::make_shared<Row>(row);
                 }
             }
         }
     }
     for (auto row : ruleMap) {
         Row t = *row.second;
         t[0] = std::make_shared<Cell<std::chrono::microseconds>>(
                 t[1]->getTimeVal() + t[2]->getTimeVal() + t[3]->getTimeVal());
         ruleMap[row.first] = std::make_shared<Row>(t);
     }
     for (auto& current : ruleMap) {
         table.addRow(current.second);
     }
     return table;
 }
Field Documentation
programRun
std::shared_ptr<ProgramRun> souffle::profile::OutputProcessor::programRun private
Definition at line 33 of file OutputProcessor.h.
Referenced by getAtomTable(), getProgramRun(), getRelTable(), getRulTable(), getSubrulTable(), getVersionAtoms(), and getVersions().
The documentation for this class was generated from the following file:
profile/OutputProcessor.h