souffle: souffle::AstConstant Class Reference
souffle::AstConstant Class Reference abstract
Abstract Constant.
#include <Constant.h>
Public Member Functions
AstConstant * clone () const override=0
Create clone.
const std::string & getConstant () const
Public Member Functions inherited from souffle::AstNode
virtual void apply (const AstNodeMapper &)
Apply the mapper to all child nodes.
AstNode (SrcLocation loc={})
std::string extloc () const
Return source location of the syntactic element.
virtual std::vector< const AstNode * > getChildNodes () const
Obtain a list of all embedded AST child nodes.
const SrcLocation & getSrcLoc () const
Return source location of the AstNode.
bool operator!= (const AstNode &other) const
Inequality check for two AST nodes.
bool operator== (const AstNode &other) const
Equivalence check for two AST nodes.
void setSrcLoc (SrcLocation l)
Set source location for the AstNode.
virtual ~AstNode ()=default
Protected Member Functions
AstConstant (std::string value, SrcLocation loc={})
bool equal (const AstNode &node) const override
Abstract equality check for two AST nodes.
void print (std::ostream &os) const override
Output to a given output stream.
Private Attributes
const std::string constant
Detailed Description
Abstract Constant.
Definition at line 29 of file Constant.h.
Constructor & Destructor Documentation
AstConstant()
souffle::AstConstant::AstConstant (std::string value, SrcLocation loc = {}) inline protected
Definition at line 48 of file Constant.h.
Referenced by souffle::AstNilConstant::AstNilConstant(), souffle::AstNumericConstant::AstNumericConstant(), and souffle::AstStringConstant::AstStringConstant().
                                                    {})
             : AstArgument(std::move(loc)), constant(std::move(value)){};
Member Function Documentation
clone()
AstConstant* souffle::AstConstant::clone () const override pure virtual
Create clone.
Implements souffle::AstArgument.
Implemented in souffle::AstNumericConstant, souffle::AstStringConstant, and souffle::AstNilConstant.
equal()
bool souffle::AstConstant::equal (const AstNode &) const inline override protected virtual
Abstract equality check for two AST nodes.
Reimplemented from souffle::AstNode.
Reimplemented in souffle::AstNumericConstant.
Definition at line 43 of file Constant.h.
References constant.
Referenced by souffle::AstNumericConstant::equal().
{
         const auto& other = static_cast<const AstConstant&>(node);
         return constant == other.constant;
     }
getConstant()
const std::string& souffle::AstConstant::getConstant () const inline
Returns
String representation of Constant
Definition at line 34 of file Constant.h.
References constant.
Referenced by souffle::AstStringConstant::clone(), souffle::AstNumericConstant::clone(), print(), souffle::AstStringConstant::print(), souffle::AstToRamTranslator::translateValue(), and souffle::TypeConstraintsAnalysis::visitNumericConstant().
{
         return constant;
     }
print()
void souffle::AstConstant::print (std::ostream & os) const inline override protected virtual
Output to a given output stream.
Implements souffle::AstNode.
Reimplemented in souffle::AstStringConstant.
Definition at line 39 of file Constant.h.
References getConstant().
{
         os << getConstant();
     }
Field Documentation
constant
const std::string souffle::AstConstant::constant private
Definition at line 49 of file Constant.h.
Referenced by equal(), and getConstant().
The documentation for this class was generated from the following file:
ast/Constant.h