souffle: souffle::InterpreterIndirectRelation Class Reference
souffle::InterpreterIndirectRelation Class Reference
Interpreter Indirect Relation.
#include <InterpreterRelation.h>
Public Member Functions
bool insert (const TupleRef &tuple) override
Insert tuple.
bool insert (const RamDomain *tuple) override
Add the given tuple to this relation.
InterpreterIndirectRelation (size_t arity, size_t auxiliaryArity, const std::string &relName, const std::vector< std::string > &attributeTypes, const MinIndexSelection &orderSet)
void purge () override
Clear all indexes.
Public Member Functions inherited from souffle::InterpreterRelation
Iterator begin () const
bool contains (const TupleRef &tuple) const
Tests whether this relation contains the given tuple.
bool contains (const size_t &indexPos, const TupleRef &low, const TupleRef &high) const
Tests whether this relation contains any element between the given boundaries.
bool empty () const
Check if the relation is empty.
Iterator end () const
bool exists (const TupleRef &tuple) const
Check if a tuple exists in relation.
virtual void extend (const InterpreterRelation &rel)
Extend another relation.
size_t getArity () const
Return arity.
const std::vector< std::string > & getAttributeTypes () const
Return the attribute types.
size_t getAuxiliaryArity () const
Return arity.
size_t getLevel () const
Return the level of the relation.
const std::string & getName () const
Return the relation name.
IndexViewPtr getView (const size_t &indexPos) const
Obtains a view on an index of this relation, facilitating hint-supported accesses.
void insert (const InterpreterRelation &other)
Add all entries of the given relation to this relation.
InterpreterRelation (std::size_t arity, std::size_t auxiliaryArity, std::string name, std::vector< std::string > attributeTypes, const MinIndexSelection &orderSet, IndexFactory factory=&createBTreeIndex)
Creates a relation, build all necessary indexes.
InterpreterRelation (InterpreterRelation &other)=delete
PartitionedStream partitionRange (const size_t &indexPos, const TupleRef &low, const TupleRef &high, size_t partitionCount) const
Obtains a partitioned stream list for parallel computation.
PartitionedStream partitionScan (size_t partitionCount) const
Obtains a partitioned stream list for parallel computation.
Stream range (const size_t &indexPos, const TupleRef &low, const TupleRef &high) const
Obtains a stream covering the interval between the two given entries.
void removeIndex (const size_t &indexPos)
Drops an index from the maintained indexes.
Stream scan () const
Obtains a stream to scan the entire relation.
void setLevel (size_t level)
Set level.
size_t size () const
Return number of tuples in relation (full-order)
void swap (InterpreterRelation &other)
Swaps the content of this and the given relation, including the installed indexes.
virtual ~InterpreterRelation ()=default
Private Attributes
std::deque< std::unique_ptr< RamDomain[]> > blockList
size_t numTuples = 0
Static Private Attributes
static const int BLOCK_SIZE = 1024
Size of blocks containing tuples.
Additional Inherited Members
Public Types inherited from souffle::InterpreterRelation
using Attribute = uint32_t
using AttributeSet = std::set< Attribute >
Protected Attributes inherited from souffle::InterpreterRelation
const size_t arity
std::vector< std::string > attributeTypes
size_t auxiliaryArity
std::vector< std::unique_ptr< InterpreterIndex > > indexes
size_t level = 0
InterpreterIndex * main
std::string relName
Detailed Description
Interpreter Indirect Relation.
Definition at line 254 of file InterpreterRelation.h.
Constructor & Destructor Documentation
InterpreterIndirectRelation()
souffle::InterpreterIndirectRelation::InterpreterIndirectRelation (size_t arity, size_t auxiliaryArity, const std::string & relName, const std::vector< std::string > & attributeTypes, const MinIndexSelection & orderSet)
Definition at line 157 of file InterpreterRelation.cpp.
         : InterpreterRelation(arity, auxiliaryArity, name, attributeTypes, orderSet, createIndirectIndex) {}
Member Function Documentation
insert() [1/2]
bool souffle::InterpreterIndirectRelation::insert (const TupleRef & tuple) override virtual
Insert tuple.
Reimplemented from souffle::InterpreterRelation.
Definition at line 162 of file InterpreterRelation.cpp.
References souffle::InterpreterRelation::arity, BLOCK_SIZE, blockList, souffle::InterpreterIndex::contains(), i, souffle::InterpreterRelation::indexes, souffle::InterpreterRelation::main, and numTuples.
Referenced by insert().
{
     if (main->contains(tuple)) {
         return false;
     }
     int blockIndex = numTuples / (BLOCK_SIZE / arity);
     int tupleIndex = (numTuples % (BLOCK_SIZE / arity)) * arity;
     if (tupleIndex == 0) {
         blockList.push_back(std::make_unique<RamDomain[]>(BLOCK_SIZE));
     }
     RamDomain* newTuple = &blockList[blockIndex][tupleIndex];
     for (size_t i = 0; i < arity; ++i) {
         newTuple[i] = tuple[i];
     }
     // update all indexes with new tuple
     for (auto& cur : indexes) {
         cur->insert(TupleRef(newTuple, arity));
     }
     // increment relation size
     numTuples++;
     return true;
 }
insert() [2/2]
bool souffle::InterpreterIndirectRelation::insert (const RamDomain * tuple) override virtual
Add the given tuple to this relation.
Reimplemented from souffle::InterpreterRelation.
Definition at line 190 of file InterpreterRelation.cpp.
References souffle::InterpreterRelation::arity, and insert().
{
     return this->insert(TupleRef(tuple, arity));
 }
purge()
void souffle::InterpreterIndirectRelation::purge () override virtual
Clear all indexes.
Reimplemented from souffle::InterpreterRelation.
Definition at line 194 of file InterpreterRelation.cpp.
References blockList, souffle::InterpreterRelation::indexes, and numTuples.
{
     blockList.clear();
     for (auto& cur : indexes) {
         cur->clear();
     }
     numTuples = 0;
 }
Field Documentation
BLOCK_SIZE
const int souffle::InterpreterIndirectRelation::BLOCK_SIZE = 1024 static private
Size of blocks containing tuples.
Definition at line 268 of file InterpreterRelation.h.
Referenced by insert().
blockList
std::deque<std::unique_ptr<RamDomain[]> > souffle::InterpreterIndirectRelation::blockList private
Definition at line 270 of file InterpreterRelation.h.
Referenced by insert(), and purge().
numTuples
size_t souffle::InterpreterIndirectRelation::numTuples = 0 private
Definition at line 272 of file InterpreterRelation.h.
Referenced by insert(), and purge().
The documentation for this class was generated from the following files:
interpreter/InterpreterRelation.h
interpreter/InterpreterRelation.cpp