souffle: souffle::RamParallelScan Class Reference
souffle::RamParallelScan Class Reference
Iterate all tuples of a relation in parallel.
#include <Operation.h>
Public Member Functions
RamParallelScan * clone () const override
Create a clone (i.e.
RamParallelScan (std::unique_ptr< RamRelationReference > rel, int ident, std::unique_ptr< RamOperation > nested, std::string profileText="")
Public Member Functions inherited from souffle::RamScan
RamScan (std::unique_ptr< RamRelationReference > rel, int ident, std::unique_ptr< RamOperation > nested, std::string profileText="")
Public Member Functions inherited from souffle::RamRelationOperation
void apply (const RamNodeMapper &map) override
Apply the mapper to all child nodes.
std::vector< const RamNode * > getChildNodes () const override
Obtain list of all embedded child nodes.
const RamRelation & getRelation () const
Get search relation.
RamRelationOperation (std::unique_ptr< RamRelationReference > relRef, int ident, std::unique_ptr< RamOperation > nested, std::string profileText="")
Public Member Functions inherited from souffle::RamTupleOperation
int getTupleId () const
Get identifier.
RamTupleOperation (int ident, std::unique_ptr< RamOperation > nested, std::string profileText="")
void setTupleId (int id)
Set identifier.
Public Member Functions inherited from souffle::RamNestedOperation
RamOperation & getOperation () const
Get nested operation.
const std::string & getProfileText () const
Get profile text.
RamNestedOperation (std::unique_ptr< RamOperation > nested, std::string profileText="")
Public Member Functions inherited from souffle::RamNode
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
virtual void rewrite (const RamNode *oldNode, std::unique_ptr< RamNode > newNode)
Rewrite a child node.
virtual ~RamNode ()=default
Protected Member Functions
void print (std::ostream &os, int tabpos) const override
Pretty print with indentation.
Protected Member Functions inherited from souffle::RamRelationOperation
bool equal (const RamNode &node) const override
Equality check for two RAM nodes.
Protected Member Functions inherited from souffle::RamOperation
void print (std::ostream &os) const override
Print RAM node.
Additional Inherited Members
Static Protected Member Functions inherited from souffle::RamOperation
static void print (const RamOperation *operation, std::ostream &os, int tabpos)
Pretty print jump-bed.
Protected Attributes inherited from souffle::RamRelationOperation
std::unique_ptr< RamRelationReference > relationRef
Search relation.
Protected Attributes inherited from souffle::RamTupleOperation
int identifier
Identifier for the tuple, corresponding to its position in the loop nest.
Protected Attributes inherited from souffle::RamNestedOperation
std::unique_ptr< RamOperation > nestedOperation
Nested operation.
const std::string profileText
Text used by the profiler.
Detailed Description
Iterate all tuples of a relation in parallel.
An example:
QUERY
 ...
 PARALLEL FOR t0 IN A
   ...
Definition at line 260 of file Operation.h.
Constructor & Destructor Documentation
RamParallelScan()
souffle::RamParallelScan::RamParallelScan (std::unique_ptr< RamRelationReference > rel, int ident, std::unique_ptr< RamOperation > nested, std::string profileText = "") inline
Definition at line 262 of file Operation.h.
             : RamScan(std::move(rel), ident, std::move(nested), profileText) {}
Member Function Documentation
clone()
RamParallelScan* souffle::RamParallelScan::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Reimplemented from souffle::RamScan.
Definition at line 266 of file Operation.h.
References souffle::clone().
Referenced by souffle::test::TEST().
{
         return new RamParallelScan(
                 souffle::clone(relationRef), getTupleId(), souffle::clone(&getOperation()), getProfileText());
     }
print()
void souffle::RamParallelScan::print (std::ostream & os, int tabpos) const inline override protected virtual
Pretty print with indentation.
Reimplemented from souffle::RamScan.
Definition at line 272 of file Operation.h.
References souffle::getRelation(), souffle::RamNestedOperation::print(), and souffle::times().
{
         os << times(" ", tabpos);
         os << "PARALLEL FOR t" << getTupleId();
         os << " IN " << getRelation().getName() << std::endl;
         RamRelationOperation::print(os, tabpos + 1);
     }
The documentation for this class was generated from the following file:
ram/Operation.h