souffle: souffle::Diagnostic Class Reference
souffle::Diagnostic Class Reference
#include <ErrorReport.h>
Public Types
enum Type { Type::ERROR, Type::WARNING }
Public Member Functions
Diagnostic (Type type, DiagnosticMessage primaryMessage, std::vector< DiagnosticMessage > additionalMessages)
Diagnostic (Type type, DiagnosticMessage primaryMessage)
const std::vector< DiagnosticMessage > & getAdditionalMessages () const
const DiagnosticMessage & getPrimaryMessage () const
Type getType () const
bool operator< (const Diagnostic &other) const
void print (std::ostream &out) const
Private Attributes
std::vector< DiagnosticMessage > additionalMessages
DiagnosticMessage primaryMessage
Type type
Friends
std::ostream & operator<< (std::ostream &out, const Diagnostic &diagnostic)
Detailed Description
Definition at line 69 of file ErrorReport.h.
Member Enumeration Documentation
Type
enum souffle::Diagnostic::Type strong
Enumerator
ERROR
WARNING
Definition at line 71 of file ErrorReport.h.
 { ERROR, WARNING };
Constructor & Destructor Documentation
Diagnostic() [1/2]
souffle::Diagnostic::Diagnostic (Type type, DiagnosticMessage primaryMessage, std::vector< DiagnosticMessage > additionalMessages) inline
Definition at line 73 of file ErrorReport.h.
             : type(type), primaryMessage(std::move(primaryMessage)),
               additionalMessages(std::move(additionalMessages)) {}
Diagnostic() [2/2]
souffle::Diagnostic::Diagnostic (Type type, DiagnosticMessage primaryMessage) inline
Definition at line 77 of file ErrorReport.h.
             : type(type), primaryMessage(std::move(primaryMessage)) {}
Member Function Documentation
getAdditionalMessages()
const std::vector<DiagnosticMessage>& souffle::Diagnostic::getAdditionalMessages () const inline
Definition at line 88 of file ErrorReport.h.
{
         return additionalMessages;
     }
getPrimaryMessage()
const DiagnosticMessage& souffle::Diagnostic::getPrimaryMessage () const inline
Definition at line 84 of file ErrorReport.h.
{
         return primaryMessage;
     }
getType()
Type souffle::Diagnostic::getType () const inline
Definition at line 80 of file ErrorReport.h.
Referenced by operator<().
{
         return type;
     }
operator<()
bool souffle::Diagnostic::operator< (const Diagnostic & other) const inline
Definition at line 105 of file ErrorReport.h.
References souffle::DiagnosticMessage::getLocation(), souffle::DiagnosticMessage::getMessage(), getType(), souffle::DiagnosticMessage::hasLocation(), and primaryMessage.
{
         if (primaryMessage.hasLocation() && !other.primaryMessage.hasLocation()) {
             return true;
         }
         if (other.primaryMessage.hasLocation() && !primaryMessage.hasLocation()) {
             return false;
         }
         if (primaryMessage.hasLocation() && other.primaryMessage.hasLocation()) {
             if (primaryMessage.getLocation() < other.primaryMessage.getLocation()) {
                 return true;
             }
             if (other.primaryMessage.getLocation() < primaryMessage.getLocation()) {
                 return false;
             }
         }
         if (type == Type::ERROR && other.getType() == Type::WARNING) {
             return true;
         }
         if (other.getType() == Type::ERROR && type == Type::WARNING) {
             return false;
         }
         if (primaryMessage.getMessage() < other.primaryMessage.getMessage()) {
             return true;
         }
         if (other.primaryMessage.getMessage() < primaryMessage.getMessage()) {
             return false;
         }
         return false;
     }
print()
void souffle::Diagnostic::print (std::ostream & out) const inline
Definition at line 92 of file ErrorReport.h.
{
         out << (type == Type::ERROR ? "Error: " : "Warning: ");
         out << primaryMessage;
         for (const DiagnosticMessage& additionalMessage : additionalMessages) {
             out << additionalMessage;
         }
     }
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & out, const Diagnostic & diagnostic) friend
Definition at line 100 of file ErrorReport.h.
{
         diagnostic.print(out);
         return out;
     }
Field Documentation
additionalMessages
std::vector<DiagnosticMessage> souffle::Diagnostic::additionalMessages private
Definition at line 142 of file ErrorReport.h.
primaryMessage
DiagnosticMessage souffle::Diagnostic::primaryMessage private
Definition at line 141 of file ErrorReport.h.
Referenced by operator<().
type
Type souffle::Diagnostic::type private
Definition at line 140 of file ErrorReport.h.
The documentation for this class was generated from the following file:
ErrorReport.h