souffle: souffle::ReduceExistentialsTransformer Class Reference
souffle::ReduceExistentialsTransformer Class Reference
Transformation pass to reduce unnecessary computation for relations that only appear in the form A(_,...,_).
#include <ReduceExistentials.h>
Public Member Functions
ReduceExistentialsTransformer * clone () const override
std::string getName () const override
Public Member Functions inherited from souffle::AstTransformer
bool apply (AstTranslationUnit &translationUnit)
virtual ~AstTransformer ()=default
Private Member Functions
bool transform (AstTranslationUnit &translationUnit) override
Detailed Description
Transformation pass to reduce unnecessary computation for relations that only appear in the form A(_,...,_).
Definition at line 31 of file ReduceExistentials.h.
Member Function Documentation
clone()
ReduceExistentialsTransformer* souffle::ReduceExistentialsTransformer::clone () const inline override virtual
Implements souffle::AstTransformer.
Definition at line 37 of file ReduceExistentials.h.
References transform().
{
         return new ReduceExistentialsTransformer();
     }
getName()
std::string souffle::ReduceExistentialsTransformer::getName () const inline override virtual
Implements souffle::AstTransformer.
Definition at line 33 of file ReduceExistentials.h.
{
         return "ReduceExistentialsTransformer";
     }
transform()
bool souffle::ReduceExistentialsTransformer::transform (AstTranslationUnit & translationUnit) override private virtual
Implements souffle::AstTransformer.
Definition at line 44 of file ReduceExistentials.cpp.
References souffle::AstProgram::addClause(), souffle::AstProgram::addRelation(), souffle::AstProgram::apply(), souffle::clone(), souffle::DEFAULT, souffle::EQREL, souffle::AstTranslationUnit::getAnalysis(), souffle::getClauses(), souffle::AstTranslationUnit::getProgram(), souffle::AstAtom::getQualifiedName(), souffle::getRelation(), souffle::AstProgram::getRelations(), souffle::AstNode::getSrcLoc(), souffle::Graph< Vertex, Compare >::insert(), souffle::isRecursiveClause(), relation, relations, souffle::Graph< Vertex, Compare >::visitDepthFirst(), and souffle::visitDepthFirst().
Referenced by clone().
{
     AstProgram& program = *translationUnit.getProgram();
     // Checks whether an atom is of the form a(_,_,...,_)
     auto isExistentialAtom = [&](const AstAtom& atom) {
         for (AstArgument* arg : atom.getArguments()) {
             if (dynamic_cast<AstUnnamedVariable*>(arg) == nullptr) {
                 return false;
             }
         }
         return true;
     };
     // Construct a dependency graph G where:
     // - Each relation is a node
     // - An edge (a,b) exists iff a uses b "non-existentially" in one of its *recursive* clauses
     // This way, a relation can be transformed into an existential form
     // if and only if all its predecessors can also be transformed.
     Graph<AstQualifiedName> relationGraph = Graph<AstQualifiedName>();
     // Add in the nodes
     for (AstRelation* relation : program.getRelations()) {
         relationGraph.insert(relation->getQualifiedName());
     }
     // Keep track of all relations that cannot be transformed
     std::set<AstQualifiedName> minimalIrreducibleRelations;
     auto* ioType = translationUnit.getAnalysis<IOType>();
     for (AstRelation* relation : program.getRelations()) {
         // No I/O relations can be transformed
         if (ioType->isIO(relation)) {
             minimalIrreducibleRelations.insert(relation->getQualifiedName());
         }
         for (AstClause* clause : getClauses(program, *relation)) {
             bool recursive = isRecursiveClause(*clause);
             visitDepthFirst(*clause, [&](const AstAtom& atom) {
                 if (atom.getQualifiedName() == clause->getHead()->getQualifiedName()) {
                     return;
                 }
                 if (!isExistentialAtom(atom)) {
                     if (recursive) {
                         // Clause is recursive, so add an edge to the dependency graph
                         relationGraph.insert(clause->getHead()->getQualifiedName(), atom.getQualifiedName());
                     } else {
                         // Non-existential apperance in a non-recursive clause, so
                         // it's out of the picture
                         minimalIrreducibleRelations.insert(atom.getQualifiedName());
                     }
                 }
             });
         }
     }
     // TODO (see issue #564): Don't transform relations appearing in aggregators
     //                        due to aggregator issues with unnamed variables.
     visitDepthFirst(program, [&](const AstAggregator& aggr) {
         visitDepthFirst(aggr,
                 [&](const AstAtom& atom) { minimalIrreducibleRelations.insert(atom.getQualifiedName()); });
     });
     // Run a DFS from each 'bad' source
     // A node is reachable in a DFS from an irreducible node if and only if it is
     // also an irreducible node
     std::set<AstQualifiedName> irreducibleRelations;
     for (AstQualifiedName relationName : minimalIrreducibleRelations) {
         relationGraph.visitDepthFirst(
                 relationName, [&](const AstQualifiedName& subRel) { irreducibleRelations.insert(subRel); });
     }
     // All other relations are necessarily existential
     std::set<AstQualifiedName> existentialRelations;
     for (AstRelation* relation : program.getRelations()) {
         if (!getClauses(program, *relation).empty() && relation->getArity() != 0 &&
                 irreducibleRelations.find(relation->getQualifiedName()) == irreducibleRelations.end()) {
             existentialRelations.insert(relation->getQualifiedName());
         }
     }
     // Reduce the existential relations
     for (AstQualifiedName relationName : existentialRelations) {
         AstRelation* originalRelation = getRelation(program, relationName);
         std::stringstream newRelationName;
         newRelationName << "+?exists_" << relationName;
         auto newRelation = std::make_unique<AstRelation>();
         newRelation->setQualifiedName(newRelationName.str());
         newRelation->setSrcLoc(originalRelation->getSrcLoc());
         // EqRel relations require two arguments, so remove it from the qualifier
         if (newRelation->getRepresentation() == RelationRepresentation::EQREL) {
             newRelation->setRepresentation(RelationRepresentation::DEFAULT);
         }
         // Keep all non-recursive clauses
         for (AstClause* clause : getClauses(program, *originalRelation)) {
             if (!isRecursiveClause(*clause)) {
                 auto newClause = std::make_unique<AstClause>();
                 newClause->setSrcLoc(clause->getSrcLoc());
                 if (const AstExecutionPlan* plan = clause->getExecutionPlan()) {
                     newClause->setExecutionPlan(souffle::clone(plan));
                 }
                 newClause->setHead(std::make_unique<AstAtom>(newRelationName.str()));
                 for (AstLiteral* lit : clause->getBodyLiterals()) {
                     newClause->addToBody(souffle::clone(lit));
                 }
                 program.addClause(std::move(newClause));
             }
         }
         program.addRelation(std::move(newRelation));
     }
     // Mapper that renames the occurrences of marked relations with their existential
     // counterparts
     struct renameExistentials : public AstNodeMapper {
         const std::set<AstQualifiedName>& relations;
         renameExistentials(std::set<AstQualifiedName>& relations) : relations(relations) {}
         std::unique_ptr<AstNode> operator()(std::unique_ptr<AstNode> node) const override {
             if (auto* clause = dynamic_cast<AstClause*>(node.get())) {
                 if (relations.find(clause->getHead()->getQualifiedName()) != relations.end()) {
                     // Clause is going to be removed, so don't rename it
                     return node;
                 }
             } else if (auto* atom = dynamic_cast<AstAtom*>(node.get())) {
                 if (relations.find(atom->getQualifiedName()) != relations.end()) {
                     // Relation is now existential, so rename it
                     std::stringstream newName;
                     newName << "+?exists_" << atom->getQualifiedName();
                     return std::make_unique<AstAtom>(newName.str());
                 }
             }
             node->apply(*this);
             return node;
         }
     };
     renameExistentials update(existentialRelations);
     program.apply(update);
     bool changed = !existentialRelations.empty();
     return changed;
 }
The documentation for this class was generated from the following files:
ast/transform/ReduceExistentials.h
ast/transform/ReduceExistentials.cpp