souffle: souffle::ErrorReport Class Reference
souffle::ErrorReport Class Reference
#include <ErrorReport.h>
Public Member Functions
void addDiagnostic (const Diagnostic &diagnostic)
void addError (const std::string &message, SrcLocation location)
Adds an error with the given message and location.
void addWarning (const std::string &message, SrcLocation location)
Adds a warning with the given message and location.
ErrorReport (bool nowarn=false)
ErrorReport (const ErrorReport &other)=default
void exitIfErrors ()
unsigned getNumErrors () const
unsigned getNumIssues () const
unsigned getNumWarnings () const
void print (std::ostream &out) const
Private Attributes
std::set< Diagnostic > diagnostics
bool nowarn
Friends
std::ostream & operator<< (std::ostream &out, const ErrorReport &report)
Detailed Description
Definition at line 145 of file ErrorReport.h.
Constructor & Destructor Documentation
ErrorReport() [1/2]
souffle::ErrorReport::ErrorReport (bool nowarn = false) inline
Definition at line 147 of file ErrorReport.h.
 : nowarn(nowarn) {}
ErrorReport() [2/2]
souffle::ErrorReport::ErrorReport (const ErrorReport & other) default
Member Function Documentation
addDiagnostic()
void souffle::ErrorReport::addDiagnostic (const Diagnostic & diagnostic) inline
Definition at line 179 of file ErrorReport.h.
Referenced by souffle::AstSemanticCheckerImpl::AstSemanticCheckerImpl(), and souffle::TypeChecker::visitAtom().
{
         diagnostics.insert(diagnostic);
     }
addError()
void souffle::ErrorReport::addError (const std::string & message, SrcLocation location) inline
Adds an error with the given message and location.
Definition at line 166 of file ErrorReport.h.
References souffle::DiagnosticMessage::DiagnosticMessage(), and souffle::Diagnostic::ERROR.
Referenced by souffle::AstSemanticCheckerImpl::checkAggregator(), souffle::AstSemanticCheckerImpl::checkAtom(), souffle::AstSemanticCheckerImpl::checkClause(), souffle::AstComponentChecker::checkComponent(), souffle::AstComponentChecker::checkComponentNameReference(), souffle::AstComponentChecker::checkComponentNamespaces(), souffle::AstComponentChecker::checkComponentReference(), souffle::AstSemanticCheckerImpl::checkFact(), souffle::AstSemanticCheckerImpl::checkInlining(), souffle::AstSemanticCheckerImpl::checkIO(), souffle::AstSemanticCheckerImpl::checkLiteral(), souffle::AstSemanticCheckerImpl::checkNamespaces(), souffle::AstSemanticCheckerImpl::checkRecordType(), souffle::AstSemanticCheckerImpl::checkRelation(), souffle::AstSemanticCheckerImpl::checkRelationDeclaration(), souffle::AstSemanticCheckerImpl::checkSubsetType(), souffle::AstSemanticCheckerImpl::checkType(), souffle::AstSemanticCheckerImpl::checkUnionType(), souffle::AstSemanticCheckerImpl::checkWitnessProblem(), souffle::AstUserDefinedFunctorsTransformer::transform(), souffle::TypeChecker::visitAggregator(), souffle::TypeChecker::visitBinaryConstraint(), souffle::TypeChecker::visitIntrinsicFunctor(), souffle::TypeChecker::visitNilConstant(), souffle::TypeChecker::visitNumericConstant(), souffle::TypeChecker::visitRecordInit(), souffle::TypeChecker::visitStringConstant(), souffle::TypeChecker::visitTypeCast(), souffle::TypeChecker::visitUserDefinedFunctor(), and souffle::TypeChecker::visitVariable().
{
         diagnostics.insert(
                 Diagnostic(Diagnostic::Type::ERROR, DiagnosticMessage(message, std::move(location))));
     }
addWarning()
void souffle::ErrorReport::addWarning (const std::string & message, SrcLocation location) inline
Adds a warning with the given message and location.
Definition at line 172 of file ErrorReport.h.
References souffle::DiagnosticMessage::DiagnosticMessage(), and souffle::Diagnostic::WARNING.
Referenced by souffle::AstSemanticCheckerImpl::checkClause(), souffle::AstSemanticCheckerImpl::checkComplexRule(), and souffle::AstSemanticCheckerImpl::checkRelation().
{
         if (!nowarn) {
             diagnostics.insert(
                     Diagnostic(Diagnostic::Type::WARNING, DiagnosticMessage(message, std::move(location))));
         }
     }
exitIfErrors()
void souffle::ErrorReport::exitIfErrors () inline
Definition at line 183 of file ErrorReport.h.
Referenced by souffle::AstTransformer::apply().
{
         if (getNumErrors() == 0) {
             return;
         }
         std::cerr << *this << getNumErrors() << " errors generated, evaluation aborted\n";
         exit(EXIT_FAILURE);
     }
getNumErrors()
unsigned souffle::ErrorReport::getNumErrors () const inline
Definition at line 151 of file ErrorReport.h.
References d, and souffle::Diagnostic::ERROR.
Referenced by souffle::RamTransformer::apply().
{
         return std::count_if(diagnostics.begin(), diagnostics.end(),
                 [](Diagnostic d) -> bool { return d.getType() == Diagnostic::Type::ERROR; });
     }
getNumIssues()
unsigned souffle::ErrorReport::getNumIssues () const inline
Definition at line 161 of file ErrorReport.h.
{
         return diagnostics.size();
     }
getNumWarnings()
unsigned souffle::ErrorReport::getNumWarnings () const inline
Definition at line 156 of file ErrorReport.h.
References d, and souffle::Diagnostic::WARNING.
{
         return std::count_if(diagnostics.begin(), diagnostics.end(),
                 [](Diagnostic d) -> bool { return d.getType() == Diagnostic::Type::WARNING; });
     }
print()
void souffle::ErrorReport::print (std::ostream & out) const inline
Definition at line 192 of file ErrorReport.h.
{
         for (const Diagnostic& diagnostic : diagnostics) {
             out << diagnostic;
         }
     }
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & out, const ErrorReport & report) friend
Definition at line 198 of file ErrorReport.h.
{
         report.print(out);
         return out;
     }
Field Documentation
diagnostics
std::set<Diagnostic> souffle::ErrorReport::diagnostics private
Definition at line 204 of file ErrorReport.h.
nowarn
bool souffle::ErrorReport::nowarn private
Definition at line 205 of file ErrorReport.h.
The documentation for this class was generated from the following file:
ErrorReport.h