souffle: souffle::RelationDetailCacheAnalysis Class Reference
souffle::RelationDetailCacheAnalysis Class Reference
Analysis pass mapping identifiers with relations and clauses.
#include <RelationDetailCache.h>
Public Member Functions
std::set< AstClause * > getClauses (const AstRelation *rel) const
std::set< AstClause * > getClauses (const AstQualifiedName &name) const
AstRelation * getRelation (const AstQualifiedName &name) const
void print (std::ostream &os) const override
print the analysis result in HTML format
RelationDetailCacheAnalysis ()
void run (const AstTranslationUnit &translationUnit) override
run analysis for a Ast translation unit
Public Member Functions inherited from souffle::AstAnalysis
AstAnalysis (std::string identifier)
virtual const std::string & getName () const
get name of the analysis
virtual ~AstAnalysis ()=default
Static Public Attributes
static constexpr const char * name = "relation-detail"
Private Attributes
std::map< AstQualifiedName, std::set< AstClause * > > nameToClauses
std::map< AstQualifiedName, AstRelation * > nameToRelation
Additional Inherited Members
Protected Attributes inherited from souffle::AstAnalysis
const std::string identifier
Detailed Description
Analysis pass mapping identifiers with relations and clauses.
Definition at line 38 of file RelationDetailCache.h.
Constructor & Destructor Documentation
RelationDetailCacheAnalysis()
souffle::RelationDetailCacheAnalysis::RelationDetailCacheAnalysis () inline
Definition at line 42 of file RelationDetailCache.h.
References print(), and run().
 : AstAnalysis(name) {}
Member Function Documentation
getClauses() [1/2]
std::set<AstClause*> souffle::RelationDetailCacheAnalysis::getClauses (const AstRelation * rel) const inline
Definition at line 55 of file RelationDetailCache.h.
References souffle::AstRelation::getQualifiedName().
{
         assert(rel != nullptr && "invalid relation");
         return getClauses(rel->getQualifiedName());
     }
getClauses() [2/2]
std::set<AstClause*> souffle::RelationDetailCacheAnalysis::getClauses (const AstQualifiedName & name) const inline
Definition at line 60 of file RelationDetailCache.h.
References nameToClauses.
{
         if (nameToClauses.find(name) != nameToClauses.end()) {
             return nameToClauses.at(name);
         }
         return std::set<AstClause*>();
     }
getRelation()
AstRelation* souffle::RelationDetailCacheAnalysis::getRelation (const AstQualifiedName & name) const inline
Definition at line 48 of file RelationDetailCache.h.
References nameToRelation.
Referenced by souffle::getGroundedTerms().
{
         if (nameToRelation.find(name) != nameToRelation.end()) {
             return nameToRelation.at(name);
         }
         return nullptr;
     }
print()
void souffle::RelationDetailCacheAnalysis::print (std::ostream &) const override virtual
print the analysis result in HTML format
Reimplemented from souffle::AstAnalysis.
Definition at line 48 of file RelationDetailCache.cpp.
References nameToClauses.
Referenced by RelationDetailCacheAnalysis().
{
     for (const auto& pair : nameToClauses) {
         os << "--" << pair.first << "--";
         os << std::endl;
         for (const auto* clause : pair.second) {
             os << *clause << std::endl;
         }
         os << std::endl;
     }
 }
run()
void souffle::RelationDetailCacheAnalysis::run (const AstTranslationUnit &) override virtual
run analysis for a Ast translation unit
Implements souffle::AstAnalysis.
Definition at line 33 of file RelationDetailCache.cpp.
References souffle::AstTranslationUnit::getProgram(), nameToClauses, and nameToRelation.
Referenced by RelationDetailCacheAnalysis().
{
     const auto& program = *translationUnit.getProgram();
     for (auto* rel : program.getRelations()) {
         nameToRelation[rel->getQualifiedName()] = rel;
         nameToClauses[rel->getQualifiedName()] = std::set<AstClause*>();
     }
     for (auto* clause : program.getClauses()) {
         const auto& relationName = clause->getHead()->getQualifiedName();
         if (nameToClauses.find(relationName) == nameToClauses.end()) {
             nameToClauses[relationName] = std::set<AstClause*>();
         }
         nameToClauses.at(relationName).insert(clause);
     }
 }
Field Documentation
name
constexpr const char* souffle::RelationDetailCacheAnalysis::name = "relation-detail" static
Definition at line 40 of file RelationDetailCache.h.
nameToClauses
std::map<AstQualifiedName, std::set<AstClause*> > souffle::RelationDetailCacheAnalysis::nameToClauses private
Definition at line 69 of file RelationDetailCache.h.
Referenced by getClauses(), print(), and run().
nameToRelation
std::map<AstQualifiedName, AstRelation*> souffle::RelationDetailCacheAnalysis::nameToRelation private
Definition at line 68 of file RelationDetailCache.h.
Referenced by getRelation(), and run().
The documentation for this class was generated from the following files:
ast/analysis/RelationDetailCache.h
ast/analysis/RelationDetailCache.cpp