souffle: souffle::RemoveRedundantRelationsTransformer Class Reference
souffle::RemoveRedundantRelationsTransformer Class Reference
Transformation pass to remove relations which are redundant (do not contribute to output).
#include <RemoveRedundantRelations.h>
Public Member Functions
RemoveRedundantRelationsTransformer * clone () const override
std::string getName () const override
Public Member Functions inherited from souffle::AstTransformer
bool apply (AstTranslationUnit &translationUnit)
virtual ~AstTransformer ()=default
Private Member Functions
bool transform (AstTranslationUnit &translationUnit) override
Detailed Description
Transformation pass to remove relations which are redundant (do not contribute to output).
Definition at line 27 of file RemoveRedundantRelations.h.
Member Function Documentation
clone()
RemoveRedundantRelationsTransformer* souffle::RemoveRedundantRelationsTransformer::clone () const inline override virtual
Implements souffle::AstTransformer.
Definition at line 33 of file RemoveRedundantRelations.h.
References transform().
{
         return new RemoveRedundantRelationsTransformer();
     }
getName()
std::string souffle::RemoveRedundantRelationsTransformer::getName () const inline override virtual
Implements souffle::AstTransformer.
Definition at line 29 of file RemoveRedundantRelations.h.
{
         return "RemoveRedundantRelationsTransformer";
     }
transform()
bool souffle::RemoveRedundantRelationsTransformer::transform (AstTranslationUnit & translationUnit) override private virtual
Implements souffle::AstTransformer.
Definition at line 24 of file RemoveRedundantRelations.cpp.
References souffle::AstTranslationUnit::getAnalysis(), souffle::AstTranslationUnit::getProgram(), souffle::RedundantRelationsAnalysis::getRedundantRelations(), and souffle::AstProgram::removeRelation().
Referenced by clone().
{
     bool changed = false;
     auto* redundantRelationsAnalysis = translationUnit.getAnalysis<RedundantRelationsAnalysis>();
     const std::set<const AstRelation*>& redundantRelations =
             redundantRelationsAnalysis->getRedundantRelations();
     if (!redundantRelations.empty()) {
         for (auto rel : redundantRelations) {
             translationUnit.getProgram()->removeRelation(rel->getQualifiedName());
             changed = true;
         }
     }
     return changed;
 }
The documentation for this class was generated from the following files:
ast/transform/RemoveRedundantRelations.h
ast/transform/RemoveRedundantRelations.cpp