souffle: souffle::AstAtom Class Reference
souffle::AstAtom Class Reference
Subclass of Literal that represents the use of a relation either in the head or in the body of a Clause, e.g., parent(x,y).
#include <Atom.h>
Public Member Functions
void addArgument (Own< AstArgument > arg)
add argument to the atom
void apply (const AstNodeMapper &map) override
Apply the mapper to all child nodes.
AstAtom (AstQualifiedName name={}, VecOwn< AstArgument > args={}, SrcLocation loc={})
AstAtom * clone () const override
Create a clone (i.e.
std::vector< AstArgument * > getArguments () const
get arguments
size_t getArity () const
get arity of the atom
std::vector< const AstNode * > getChildNodes () const override
Obtain a list of all embedded AST child nodes.
const AstQualifiedName & getQualifiedName () const
get qualified name
void setQualifiedName (AstQualifiedName n)
set qualified name
Public Member Functions inherited from souffle::AstNode
AstNode (SrcLocation loc={})
std::string extloc () const
Return source location of the syntactic element.
const SrcLocation & getSrcLoc () const
Return source location of the AstNode.
bool operator!= (const AstNode &other) const
Inequality check for two AST nodes.
bool operator== (const AstNode &other) const
Equivalence check for two AST nodes.
void setSrcLoc (SrcLocation l)
Set source location for the AstNode.
virtual ~AstNode ()=default
Protected Member Functions
bool equal (const AstNode &node) const override
Abstract equality check for two AST nodes.
void print (std::ostream &os) const override
Output to a given output stream.
Protected Attributes
VecOwn< AstArgument > arguments
arguments
AstQualifiedName name
name
Detailed Description
Subclass of Literal that represents the use of a relation either in the head or in the body of a Clause, e.g., parent(x,y).
The arguments of the atom can be variables or constants.
Definition at line 42 of file Atom.h.
Constructor & Destructor Documentation
AstAtom()
souffle::AstAtom::AstAtom (AstQualifiedName name = {}, VecOwn< AstArgument > args = {}, SrcLocation loc = {}) inline
Definition at line 44 of file Atom.h.
References arguments, and name.
Referenced by clone().
                                     {}, VecOwn<AstArgument> args = {}, SrcLocation loc = {})
             : AstLiteral(std::move(loc)), name(std::move(name)), arguments(std::move(args)) {}
Member Function Documentation
addArgument()
void souffle::AstAtom::addArgument (Own< AstArgument > arg) inline
add argument to the atom
Definition at line 63 of file Atom.h.
References arguments.
Referenced by souffle::AstSemanticCheckerImpl::checkWitnessProblem(), and souffle::transformEqrelRelation().
{
         arguments.push_back(std::move(arg));
     }
apply()
void souffle::AstAtom::apply (const AstNodeMapper &) inline override virtual
Apply the mapper to all child nodes.
Reimplemented from souffle::AstNode.
Definition at line 76 of file Atom.h.
References arguments, and souffle::map().
{
         for (auto& arg : arguments) {
             arg = map(std::move(arg));
         }
     }
clone()
AstAtom* souffle::AstAtom::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::AstLiteral.
Definition at line 72 of file Atom.h.
References arguments, AstAtom(), souffle::clone(), souffle::AstNode::getSrcLoc(), and name.
Referenced by souffle::negateLiteral().
{
         return new AstAtom(name, souffle::clone(arguments), getSrcLoc());
     }
equal()
bool souffle::AstAtom::equal (const AstNode &) const inline override protected virtual
Abstract equality check for two AST nodes.
Reimplemented from souffle::AstNode.
Definition at line 95 of file Atom.h.
References arguments, souffle::equal_targets(), and name.
{
         const auto& other = static_cast<const AstAtom&>(node);
         return name == other.name && equal_targets(arguments, other.arguments);
     }
getArguments()
std::vector<AstArgument*> souffle::AstAtom::getArguments () const inline
get arguments
Definition at line 68 of file Atom.h.
References arguments, and souffle::toPtrVector().
Referenced by souffle::MinimiseProgramTransformer::NormalisedClauseRepr::addClauseAtom(), souffle::applySips(), souffle::bindArguments(), souffle::AstSemanticCheckerImpl::checkAtom(), souffle::AstSemanticCheckerImpl::checkFact(), souffle::AstToRamTranslator::ClauseTranslator::createValueIndex(), souffle::getBodyRelations(), souffle::getGroundedTerms(), souffle::getInlinedAtom(), souffle::getNextAtomMaxBoundSIPS(), souffle::getNextAtomMaxRatioSIPS(), souffle::hasBoundArgument(), souffle::isProposition(), souffle::TypeConstraintsAnalysis::iterateOverAtom(), souffle::makeInfoRelation(), souffle::MinimiseProgramTransformer::NormalisedClauseRepr::NormalisedClauseRepr(), souffle::numBoundArguments(), souffle::RemoveRelationCopiesTransformer::removeRelationCopies(), souffle::Adornment::run(), souffle::test::TEST(), souffle::MagicSetTransformer::transform(), souffle::AstToRamTranslator::ClauseTranslator::translateClause(), souffle::unifyAtoms(), and souffle::TypeChecker::visitAtom().
{
         return toPtrVector(arguments);
     }
getArity()
size_t souffle::AstAtom::getArity () const inline
get arity of the atom
Definition at line 53 of file Atom.h.
References arguments.
Referenced by souffle::AstSemanticCheckerImpl::checkAtom(), souffle::getNextAtomMaxRatioSIPS(), souffle::getSipsFunction(), souffle::ReorderLiteralsTransformer::transform(), and souffle::AstToRamTranslator::ClauseTranslator::translateClause().
{
         return arguments.size();
     }
getChildNodes()
std::vector<const AstNode*> souffle::AstAtom::getChildNodes () const inline override virtual
Obtain a list of all embedded AST child nodes.
Reimplemented from souffle::AstNode.
Definition at line 82 of file Atom.h.
References arguments.
{
         std::vector<const AstNode*> res;
         for (auto& cur : arguments) {
             res.push_back(cur.get());
         }
         return res;
     }
getQualifiedName()
const AstQualifiedName& souffle::AstAtom::getQualifiedName () const inline
get qualified name
Definition at line 48 of file Atom.h.
References name.
Referenced by souffle::addAggregators(), souffle::addBackwardDependencies(), souffle::MinimiseProgramTransformer::NormalisedClauseRepr::addClauseAtom(), souffle::addForwardDependencies(), souffle::AstSemanticCheckerImpl::checkAtom(), souffle::AstSemanticCheckerImpl::checkFact(), souffle::AstSemanticCheckerImpl::checkInlining(), souffle::containsInlinedAtom(), souffle::formNegatedLiterals(), souffle::AuxiliaryArity::getArity(), souffle::getAtomRelation(), souffle::getClauseNum(), souffle::AstToRamTranslator::getEvaluationArity(), souffle::getInlinedAtom(), souffle::getNextAtomMaxBoundSIPS(), souffle::getNextAtomNaiveSIPS(), souffle::isRecursiveClause(), souffle::makeInfoRelation(), print(), souffle::MinimiseProgramTransformer::reduceSingletonRelations(), souffle::RemoveRelationCopiesTransformer::removeRelationCopies(), souffle::Adornment::run(), souffle::ReorderLiteralsTransformer::transform(), souffle::ReduceExistentialsTransformer::transform(), souffle::MagicSetTransformer::transform(), souffle::AstToRamTranslator::ClauseTranslator::translateClause(), souffle::AstToRamTranslator::translateProgram(), and souffle::AstToRamTranslator::translateRelation().
{
         return name;
     }
print()
void souffle::AstAtom::print (std::ostream & os) const inline override protected virtual
Output to a given output stream.
Implements souffle::AstNode.
Definition at line 91 of file Atom.h.
References arguments, getQualifiedName(), and souffle::join().
{
         os << getQualifiedName() << "(" << join(arguments) << ")";
     }
setQualifiedName()
void souffle::AstAtom::setQualifiedName (AstQualifiedName n) inline
set qualified name
Definition at line 58 of file Atom.h.
References name.
Referenced by souffle::MaterializeAggregationQueriesTransformer::needsMaterializedRelation(), souffle::separateDBs(), and souffle::MagicSetTransformer::transform().
{
         name = std::move(n);
     }
Field Documentation
arguments
VecOwn<AstArgument> souffle::AstAtom::arguments protected
arguments
Definition at line 104 of file Atom.h.
Referenced by addArgument(), apply(), AstAtom(), clone(), equal(), getArguments(), getArity(), getChildNodes(), and print().
name
AstQualifiedName souffle::AstAtom::name protected
name
Definition at line 101 of file Atom.h.
Referenced by AstAtom(), clone(), equal(), getQualifiedName(), and setQualifiedName().
The documentation for this class was generated from the following file:
ast/Atom.h