souffle: souffle::AstIO Class Reference
souffle::AstIO Class Reference
I/O operation has a type (input/output/printsize), qualified relation name, and I/O directives.
#include <IO.h>
Public Member Functions
void addDirective (const std::string &key, std::string value)
add new I/O directive
AstIO (AstIoType type, AstQualifiedName name, SrcLocation loc={})
AstIO * clone () const override
Create a clone (i.e.
const std::string & getDirective (const std::string &key) const
get value of I/O directive
const std::map< std::string, std::string > & getDirectives () const
get I/O-directive map
const AstQualifiedName & getQualifiedName () const
get relation name
AstIoType getType () const
get I/O type
bool hasDirective (const std::string &key) const
check for I/O directive
void setQualifiedName (AstQualifiedName name)
set relation name
void setType (AstIoType type)
set I/O type
Public Member Functions inherited from souffle::AstNode
virtual void apply (const AstNodeMapper &)
Apply the mapper to all child nodes.
AstNode (SrcLocation loc={})
std::string extloc () const
Return source location of the syntactic element.
virtual std::vector< const AstNode * > getChildNodes () const
Obtain a list of all embedded AST child nodes.
const SrcLocation & getSrcLoc () const
Return source location of the AstNode.
bool operator!= (const AstNode &other) const
Inequality check for two AST nodes.
bool operator== (const AstNode &other) const
Equivalence check for two AST nodes.
void setSrcLoc (SrcLocation l)
Set source location for the AstNode.
virtual ~AstNode ()=default
Protected Member Functions
bool equal (const AstNode &node) const override
Abstract equality check for two AST nodes.
void print (std::ostream &os) const override
Output to a given output stream.
Protected Attributes
std::map< std::string, std::string > directives
I/O directives.
AstQualifiedName name
relation name of I/O operation
AstIoType type
type of I/O operation
Detailed Description
I/O operation has a type (input/output/printsize), qualified relation name, and I/O directives.
Definition at line 48 of file IO.h.
Constructor & Destructor Documentation
AstIO()
souffle::AstIO::AstIO (AstIoType type, AstQualifiedName name, SrcLocation loc = {}) inline
Definition at line 50 of file IO.h.
                                                                    {})
             : AstNode(std::move(loc)), type(type), name(std::move(name)) {}
Member Function Documentation
addDirective()
void souffle::AstIO::addDirective (const std::string & key, std::string value) inline
add new I/O directive
Definition at line 79 of file IO.h.
{
         directives[key] = std::move(value);
     }
clone()
AstIO* souffle::AstIO::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::AstNode.
Definition at line 93 of file IO.h.
{
         auto res = new AstIO(type, name, getSrcLoc());
         res->directives = directives;
         return res;
     }
equal()
bool souffle::AstIO::equal (const AstNode &) const inline override protected virtual
Abstract equality check for two AST nodes.
Reimplemented from souffle::AstNode.
Definition at line 109 of file IO.h.
References type.
{
         const auto& other = static_cast<const AstIO&>(node);
         return other.type == type && other.name == name && other.directives == directives;
     }
getDirective()
const std::string& souffle::AstIO::getDirective (const std::string & key) const inline
get value of I/O directive
Definition at line 74 of file IO.h.
{
         return directives.at(key);
     }
getDirectives()
const std::map<std::string, std::string>& souffle::AstIO::getDirectives () const inline
get I/O-directive map
Definition at line 89 of file IO.h.
{
         return directives;
     }
getQualifiedName()
const AstQualifiedName& souffle::AstIO::getQualifiedName () const inline
get relation name
Definition at line 64 of file IO.h.
Referenced by souffle::IODefaultsTransformer::getRelationName(), souffle::IOAttributesTransformer::getRelationName(), and souffle::IOType::run().
{
         return name;
     }
getType()
AstIoType souffle::AstIO::getType () const inline
get I/O type
Definition at line 54 of file IO.h.
Referenced by souffle::IOType::run().
{
         return type;
     }
hasDirective()
bool souffle::AstIO::hasDirective (const std::string & key) const inline
check for I/O directive
Definition at line 84 of file IO.h.
{
         return directives.find(key) != directives.end();
     }
print()
void souffle::AstIO::print (std::ostream & os) const inline override protected virtual
Output to a given output stream.
Implements souffle::AstNode.
Definition at line 100 of file IO.h.
References souffle::join().
{
         os << "." << type << " " << name;
         if (!directives.empty()) {
             os << "(" << join(directives, ",", [](std::ostream& out, const auto& arg) {
                 out << arg.first << "=\"" << arg.second << "\"";
             }) << ")";
         }
     }
setQualifiedName()
void souffle::AstIO::setQualifiedName (AstQualifiedName name) inline
set relation name
Definition at line 69 of file IO.h.
{
         this->name = std::move(name);
     }
setType()
void souffle::AstIO::setType (AstIoType type) inline
set I/O type
Definition at line 59 of file IO.h.
{
         this->type = type;
     }
Field Documentation
directives
std::map<std::string, std::string> souffle::AstIO::directives protected
I/O directives.
Definition at line 121 of file IO.h.
name
AstQualifiedName souffle::AstIO::name protected
relation name of I/O operation
Definition at line 118 of file IO.h.
type
AstIoType souffle::AstIO::type protected
type of I/O operation
Definition at line 115 of file IO.h.
Referenced by equal().
The documentation for this class was generated from the following file:
ast/IO.h