souffle: souffle::UniqueAggregationVariablesTransformer Class Reference
souffle::UniqueAggregationVariablesTransformer Class Reference
Transformation pass to rename aggregation variables to make them unique.
#include <UniqueAggregationVariables.h>
Public Member Functions
UniqueAggregationVariablesTransformer * clone () const override
std::string getName () const override
Public Member Functions inherited from souffle::AstTransformer
bool apply (AstTranslationUnit &translationUnit)
virtual ~AstTransformer ()=default
Private Member Functions
bool transform (AstTranslationUnit &translationUnit) override
Detailed Description
Transformation pass to rename aggregation variables to make them unique.
Definition at line 27 of file UniqueAggregationVariables.h.
Member Function Documentation
clone()
UniqueAggregationVariablesTransformer* souffle::UniqueAggregationVariablesTransformer::clone () const inline override virtual
Implements souffle::AstTransformer.
Definition at line 33 of file UniqueAggregationVariables.h.
References transform().
{
         return new UniqueAggregationVariablesTransformer();
     }
getName()
std::string souffle::UniqueAggregationVariablesTransformer::getName () const inline override virtual
Implements souffle::AstTransformer.
Definition at line 29 of file UniqueAggregationVariables.h.
{
         return "UniqueAggregationVariablesTransformer";
     }
transform()
bool souffle::UniqueAggregationVariablesTransformer::transform (AstTranslationUnit & translationUnit) override private virtual
Implements souffle::AstTransformer.
Definition at line 28 of file UniqueAggregationVariables.cpp.
References souffle::AstVariable::getName(), souffle::AstTranslationUnit::getProgram(), souffle::toString(), souffle::visitDepthFirst(), and souffle::visitDepthFirstPostOrder().
Referenced by clone().
{
     bool changed = false;
     // make variables in aggregates unique
     int aggNumber = 0;
     visitDepthFirstPostOrder(*translationUnit.getProgram(), [&](const AstAggregator& agg) {
         // only applicable for aggregates with target expression
         if (agg.getTargetExpression() == nullptr) {
             return;
         }
         // get all variables in the target expression
         std::set<std::string> names;
         visitDepthFirst(
                 *agg.getTargetExpression(), [&](const AstVariable& var) { names.insert(var.getName()); });
         // rename them
         visitDepthFirst(agg, [&](const AstVariable& var) {
             auto pos = names.find(var.getName());
             if (pos == names.end()) {
                 return;
             }
             const_cast<AstVariable&>(var).setName(" " + var.getName() + toString(aggNumber));
             changed = true;
         });
         // increment aggregation number
         aggNumber++;
     });
     return changed;
 }
The documentation for this class was generated from the following files:
ast/transform/UniqueAggregationVariables.h
ast/transform/UniqueAggregationVariables.cpp