souffle: souffle::RamUnpackRecord Class Reference
souffle::RamUnpackRecord Class Reference
Record lookup.
#include <Operation.h>
Public Member Functions
void apply (const RamNodeMapper &map) override
Apply the mapper to all child nodes.
RamUnpackRecord * clone () const override
Create a clone (i.e.
std::size_t getArity () const
Get arity of record.
std::vector< const RamNode * > getChildNodes () const override
Obtain list of all embedded child nodes.
const RamExpression & getExpression () const
Get record expression.
RamUnpackRecord (std::unique_ptr< RamOperation > nested, int ident, std::unique_ptr< RamExpression > expr, size_t arity)
Public Member Functions inherited from souffle::RamTupleOperation
int getTupleId () const
Get identifier.
RamTupleOperation (int ident, std::unique_ptr< RamOperation > nested, std::string profileText="")
void setTupleId (int id)
Set identifier.
Public Member Functions inherited from souffle::RamNestedOperation
RamOperation & getOperation () const
Get nested operation.
const std::string & getProfileText () const
Get profile text.
RamNestedOperation (std::unique_ptr< RamOperation > nested, std::string profileText="")
Public Member Functions inherited from souffle::RamNode
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
virtual void rewrite (const RamNode *oldNode, std::unique_ptr< RamNode > newNode)
Rewrite a child node.
virtual ~RamNode ()=default
Protected Member Functions
bool equal (const RamNode &node) const override
Equality check for two RAM nodes.
void print (std::ostream &os, int tabpos) const override
Pretty print with indentation.
Protected Member Functions inherited from souffle::RamOperation
void print (std::ostream &os) const override
Print RAM node.
Protected Attributes
const size_t arity
Arity of the unpacked tuple.
std::unique_ptr< RamExpression > expression
Expression for record reference.
Protected Attributes inherited from souffle::RamTupleOperation
int identifier
Identifier for the tuple, corresponding to its position in the loop nest.
Protected Attributes inherited from souffle::RamNestedOperation
std::unique_ptr< RamOperation > nestedOperation
Nested operation.
const std::string profileText
Text used by the profiler.
Additional Inherited Members
Static Protected Member Functions inherited from souffle::RamOperation
static void print (const RamOperation *operation, std::ostream &os, int tabpos)
Pretty print jump-bed.
Detailed Description
Record lookup.
Looks up a record with respect to an expression
For example:
UNPACK t0.0 INTO t1
Definition at line 1098 of file Operation.h.
Constructor & Destructor Documentation
RamUnpackRecord()
souffle::RamUnpackRecord::RamUnpackRecord (std::unique_ptr< RamOperation > nested, int ident, std::unique_ptr< RamExpression > expr, size_t arity) inline
Definition at line 1100 of file Operation.h.
             : RamTupleOperation(ident, std::move(nested)), expression(std::move(expr)), arity(arity) {
         assert(expression != nullptr && "Expression is a null-pointer");
     }
Member Function Documentation
apply()
void souffle::RamUnpackRecord::apply (const RamNodeMapper &) inline override virtual
Apply the mapper to all child nodes.
Reimplemented from souffle::RamNestedOperation.
Definition at line 1128 of file Operation.h.
References souffle::RamNestedOperation::apply(), and souffle::map().
{
         RamTupleOperation::apply(map);
         expression = map(std::move(expression));
     }
clone()
RamUnpackRecord* souffle::RamUnpackRecord::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::RamTupleOperation.
Definition at line 1123 of file Operation.h.
References souffle::clone().
Referenced by souffle::test::TEST().
{
         return new RamUnpackRecord(
                 souffle::clone(&getOperation()), getTupleId(), souffle::clone(&getExpression()), arity);
     }
equal()
bool souffle::RamUnpackRecord::equal (const RamNode &) const inline override protected virtual
Equality check for two RAM nodes.
Default action is that nothing needs to be checked.
Reimplemented from souffle::RamTupleOperation.
Definition at line 1140 of file Operation.h.
References souffle::RamTupleOperation::equal(), and souffle::equal_ptr().
{
         const auto& other = static_cast<const RamUnpackRecord&>(node);
         return RamTupleOperation::equal(other) && equal_ptr(expression, other.expression) &&
                arity == other.arity;
     }
getArity()
std::size_t souffle::RamUnpackRecord::getArity () const inline
Get arity of record.
Definition at line 1113 of file Operation.h.
Referenced by souffle::Synthesiser::emitCode().
{
         return arity;
     }
getChildNodes()
std::vector<const RamNode*> souffle::RamUnpackRecord::getChildNodes () const inline override virtual
Obtain list of all embedded child nodes.
Reimplemented from souffle::RamTupleOperation.
Definition at line 1117 of file Operation.h.
References souffle::RamTupleOperation::getChildNodes().
{
         auto res = RamTupleOperation::getChildNodes();
         res.push_back(expression.get());
         return res;
     }
getExpression()
const RamExpression& souffle::RamUnpackRecord::getExpression () const inline
Get record expression.
Definition at line 1107 of file Operation.h.
Referenced by souffle::Synthesiser::emitCode(), and souffle::RamLevelAnalysis::getLevel().
{
         assert(expression != nullptr && "Expression of unpack-record is a null-pointer");
         return *expression;
     }
print()
void souffle::RamUnpackRecord::print (std::ostream & os, int tabpos) const inline override protected virtual
Pretty print with indentation.
Reimplemented from souffle::RamNestedOperation.
Definition at line 1134 of file Operation.h.
References souffle::RamNestedOperation::print(), and souffle::times().
{
         os << times(" ", tabpos);
         os << "UNPACK t" << getTupleId() << " FROM " << *expression << "\n";
         RamNestedOperation::print(os, tabpos + 1);
     }
Field Documentation
arity
const size_t souffle::RamUnpackRecord::arity protected
Arity of the unpacked tuple.
Definition at line 1150 of file Operation.h.
expression
std::unique_ptr<RamExpression> souffle::RamUnpackRecord::expression protected
Expression for record reference.
Definition at line 1147 of file Operation.h.
The documentation for this class was generated from the following file:
ram/Operation.h