souffle: souffle::UnionType Class Reference
souffle::UnionType Class Reference
A union type combining a list of types into a new, aggregated type.
#include <TypeSystem.h>
Public Member Functions
const std::vector< const Type * > & getElementTypes () const
void print (std::ostream &out) const override
void setElements (std::vector< const Type *> elements)
Public Member Functions inherited from souffle::Type
const AstQualifiedName & getName () const
const TypeEnvironment & getTypeEnvironment () const
bool operator!= (const Type &other) const
bool operator< (const Type &other) const
bool operator== (const Type &other) const
Type (const Type &other)=delete
virtual ~Type ()=default
Protected Member Functions
UnionType (const TypeEnvironment &environment, const AstQualifiedName &name, std::vector< const Type *> elementTypes={})
Protected Member Functions inherited from souffle::Type
Type (const TypeEnvironment &environment, AstQualifiedName name)
Protected Attributes
std::vector< const Type * > elementTypes
Protected Attributes inherited from souffle::Type
const TypeEnvironment & environment
A reference to the type environment this type is associated to.
AstQualifiedName name
Friends
class TypeEnvironment
Detailed Description
A union type combining a list of types into a new, aggregated type.
Definition at line 139 of file TypeSystem.h.
Constructor & Destructor Documentation
UnionType()
souffle::UnionType::UnionType (const TypeEnvironment & environment, const AstQualifiedName & name, std::vector< const Type *> elementTypes = {}) inline protected
Definition at line 155 of file TypeSystem.h.
References souffle::Type::Type().
                                                   {})
             : Type(environment, name), elementTypes(std::move(elementTypes)) {}
Member Function Documentation
getElementTypes()
const std::vector<const Type*>& souffle::UnionType::getElementTypes () const inline
Definition at line 141 of file TypeSystem.h.
Referenced by souffle::getGreatestCommonSubtypes(), souffle::getTypeQualifier(), and souffle::isOfRootType().
{
         return elementTypes;
     }
print()
void souffle::UnionType::print (std::ostream & out) const override virtual
Reimplemented from souffle::Type.
Definition at line 30 of file TypeSystem.cpp.
References tinyformat::format(), souffle::Type::getName(), and souffle::join().
{
     out << tfm::format("%s = %s", getName(),
             join(elementTypes, " | ", [](std::ostream& out, const Type* type) { out << type->getName(); }));
 }
setElements()
void souffle::UnionType::setElements (std::vector< const Type *> elements) inline
Definition at line 145 of file TypeSystem.h.
References souffle::Type::print().
Referenced by souffle::test::TEST().
{
         elementTypes = std::move(elements);
     }
Friends And Related Function Documentation
TypeEnvironment
friend class TypeEnvironment friend
Definition at line 152 of file TypeSystem.h.
Field Documentation
elementTypes
std::vector<const Type*> souffle::UnionType::elementTypes protected
Definition at line 153 of file TypeSystem.h.
The documentation for this class was generated from the following files:
ast/TypeSystem.h
ast/TypeSystem.cpp