souffle: souffle::OptimisticReadWriteLock Class Reference
souffle::OptimisticReadWriteLock Class Reference
A 'sequential' non-locking implementation for an optimistic r/w lock.
#include <ParallelUtil.h>
Data Structures
class Lease
Public Member Functions
void abort_write ()
bool end_read (const Lease &)
void end_write ()
bool is_write_locked () const
OptimisticReadWriteLock ()=default
Lease start_read ()
void start_write ()
bool try_start_write ()
bool try_upgrade_to_write (const Lease &)
bool validate (const Lease &)
Detailed Description
A 'sequential' non-locking implementation for an optimistic r/w lock.
Definition at line 526 of file ParallelUtil.h.
Constructor & Destructor Documentation
OptimisticReadWriteLock()
souffle::OptimisticReadWriteLock::OptimisticReadWriteLock () default
Member Function Documentation
abort_write()
void souffle::OptimisticReadWriteLock::abort_write () inline
Definition at line 554 of file ParallelUtil.h.
Referenced by souffle::detail::LambdaBTree< PairStore, EqrelMapComparator< PairStore >, std::allocator< PairStore >, 256, typename detail::default_strategy< PairStore >::type, true, std::function< parent_t(PairStore &)> >::insert(), and souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, true, WeakComparator, Updater >::insert().
 {}
end_read()
bool souffle::OptimisticReadWriteLock::end_read (const Lease &) inline
Definition at line 540 of file ParallelUtil.h.
Referenced by souffle::detail::LambdaBTree< PairStore, EqrelMapComparator< PairStore >, std::allocator< PairStore >, 256, typename detail::default_strategy< PairStore >::type, true, std::function< parent_t(PairStore &)> >::insert(), souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, true, WeakComparator, Updater >::insert(), and souffle::test::TEST().
{
         return true;
     }
end_write()
void souffle::OptimisticReadWriteLock::end_write () inline
Definition at line 556 of file ParallelUtil.h.
Referenced by souffle::detail::LambdaBTree< PairStore, EqrelMapComparator< PairStore >, std::allocator< PairStore >, 256, typename detail::default_strategy< PairStore >::type, true, std::function< parent_t(PairStore &)> >::insert(), souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, true, WeakComparator, Updater >::insert(), and souffle::test::TEST().
 {}
is_write_locked()
bool souffle::OptimisticReadWriteLock::is_write_locked () const inline
Definition at line 558 of file ParallelUtil.h.
Referenced by souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::node::getSplitPoint(), souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::node::insert_inner(), souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::node::rebalance_or_split(), and souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::node::split().
{
         return true;
     }
start_read()
Lease souffle::OptimisticReadWriteLock::start_read () inline
Definition at line 532 of file ParallelUtil.h.
Referenced by souffle::detail::LambdaBTree< PairStore, EqrelMapComparator< PairStore >, std::allocator< PairStore >, 256, typename detail::default_strategy< PairStore >::type, true, std::function< parent_t(PairStore &)> >::insert(), souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, true, WeakComparator, Updater >::insert(), and souffle::test::TEST().
{
         return Lease();
     }
start_write()
void souffle::OptimisticReadWriteLock::start_write () inline
Definition at line 544 of file ParallelUtil.h.
Referenced by souffle::detail::LambdaBTree< PairStore, EqrelMapComparator< PairStore >, std::allocator< PairStore >, 256, typename detail::default_strategy< PairStore >::type, true, std::function< parent_t(PairStore &)> >::insert(), souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, true, WeakComparator, Updater >::insert(), and souffle::test::TEST().
 {}
try_start_write()
bool souffle::OptimisticReadWriteLock::try_start_write () inline
Definition at line 546 of file ParallelUtil.h.
Referenced by souffle::detail::LambdaBTree< PairStore, EqrelMapComparator< PairStore >, std::allocator< PairStore >, 256, typename detail::default_strategy< PairStore >::type, true, std::function< parent_t(PairStore &)> >::insert(), and souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, true, WeakComparator, Updater >::insert().
{
         return true;
     }
try_upgrade_to_write()
bool souffle::OptimisticReadWriteLock::try_upgrade_to_write (const Lease &) inline
Definition at line 550 of file ParallelUtil.h.
{
         return true;
     }
validate()
bool souffle::OptimisticReadWriteLock::validate (const Lease &) inline
Definition at line 536 of file ParallelUtil.h.
{
         return true;
     }
The documentation for this class was generated from the following file:
utility/ParallelUtil.h