souffle: souffle::NodeGenerator Class Reference
souffle::NodeGenerator Class Reference
#include <InterpreterGenerator.h>
Public Member Functions
NodePtr generateTree (const RamNode &root, const RamProgram &program)
Generate the tree based on given entry.
RelationHandle & getRelationHandle (const size_t idx)
Return relation handle from given index.
std::vector< std::unique_ptr< RelationHandle > > & getRelations ()
Move relation map.
NodeGenerator (RamIndexAnalysis *isa)
NodePtr visitAggregate (const RamAggregate &aggregate) override
NodePtr visitAutoIncrement (const RamAutoIncrement &inc) override
NodePtr visitBreak (const RamBreak &breakOp) override
NodePtr visitCall (const RamCall &call) override
NodePtr visitChoice (const RamChoice &choice) override
NodePtr visitClear (const RamClear &clear) override
NodePtr visitConjunction (const RamConjunction &conj) override
NodePtr visitConstant (const RamConstant &num) override
NodePtr visitConstraint (const RamConstraint &relOp) override
NodePtr visitDebugInfo (const RamDebugInfo &dbg) override
NodePtr visitEmptinessCheck (const RamEmptinessCheck &emptiness) override
NodePtr visitExistenceCheck (const RamExistenceCheck &exists) override
NodePtr visitExit (const RamExit &exit) override
NodePtr visitExtend (const RamExtend &extend) override
NodePtr visitFalse (const RamFalse &lfalse) override
NodePtr visitFilter (const RamFilter &filter) override
NodePtr visitIndexAggregate (const RamIndexAggregate &aggregate) override
NodePtr visitIndexChoice (const RamIndexChoice &choice) override
NodePtr visitIndexScan (const RamIndexScan &scan) override
NodePtr visitIntrinsicOperator (const RamIntrinsicOperator &op) override
NodePtr visitIO (const RamIO &io) override
NodePtr visitLogRelationTimer (const RamLogRelationTimer &timer) override
NodePtr visitLogSize (const RamLogSize &size) override
NodePtr visitLogTimer (const RamLogTimer &timer) override
NodePtr visitLoop (const RamLoop &loop) override
NodePtr visitNegation (const RamNegation &neg) override
NodePtr visitNestedIntrinsicOperator (const RamNestedIntrinsicOperator &op) override
NodePtr visitNestedOperation (const RamNestedOperation &nested) override
NodePtr visitNode (const RamNode &node) override
NodePtr visitPackRecord (const RamPackRecord &pr) override
NodePtr visitParallel (const RamParallel &parallel) override
NodePtr visitParallelAggregate (const RamParallelAggregate &aggregate) override
NodePtr visitParallelChoice (const RamParallelChoice &pchoice) override
NodePtr visitParallelIndexAggregate (const RamParallelIndexAggregate &aggregate) override
NodePtr visitParallelIndexChoice (const RamParallelIndexChoice &ichoice) override
NodePtr visitParallelIndexScan (const RamParallelIndexScan &piscan) override
NodePtr visitParallelScan (const RamParallelScan &pScan) override
NodePtr visitProject (const RamProject &project) override
NodePtr visitProvenanceExistenceCheck (const RamProvenanceExistenceCheck &provExists) override
NodePtr visitQuery (const RamQuery &query) override
NodePtr visitScan (const RamScan &scan) override
NodePtr visitSequence (const RamSequence &seq) override
NodePtr visitSubroutineArgument (const RamSubroutineArgument &arg) override
NodePtr visitSubroutineReturn (const RamSubroutineReturn &ret) override
NodePtr visitSwap (const RamSwap &swap) override
NodePtr visitTrue (const RamTrue &ltrue) override
NodePtr visitTupleElement (const RamTupleElement &access) override
NodePtr visitTupleOperation (const RamTupleOperation &search) override
NodePtr visitUndefValue (const RamUndefValue &) override
NodePtr visitUnpackRecord (const RamUnpackRecord &lookup) override
NodePtr visitUserDefinedOperator (const RamUserDefinedOperator &op) override
Public Member Functions inherited from souffle::RamVisitor< std::unique_ptr< InterpreterNode > >
std::unique_ptr< InterpreterNode > operator() (const RamNode &node, Params... args)
The main entry for the user allowing visitors to be utilized as functions.
std::unique_ptr< InterpreterNode > operator() (const RamNode *node, Params... args)
The main entry for the user allowing visitors to be utilized as functions.
virtual std::unique_ptr< InterpreterNode > visit (const RamNode &node, Params... args)
The main entry for a visit process conducting the dispatching of a visit to the various sub-types of RamNodes.
virtual std::unique_ptr< InterpreterNode > visit (const RamNode *node, Params... args)
virtual ~RamVisitor ()=default
A virtual destructor.
Private Types
using NodePtr = std::unique_ptr< InterpreterNode >
using NodePtrVec = std::vector< NodePtr >
using RelationHandle = std::unique_ptr< InterpreterRelation >
Private Member Functions
void createRelation (const RamRelation &id, const MinIndexSelection &orderSet, const size_t idx)
Create and add relation into the runtime environment.
template<class RamNode >
size_t encodeIndexPos (RamNode &node)
Return operation index id from the result of indexAnalysis.
size_t encodeRelation (const RamRelation &rel)
Encode and create the relation, return the relation id.
size_t encodeView (const RamNode *node)
Encode and return the View id of an operation.
NodePtrVec findAllViews (const RamNode &node)
Find all operations under the root node that requires a view.
InterpreterSuperInstruction getExistenceSuperInstInfo (const RamAbstractExistenceCheck &exist)
Encode and return the super-instruction information about an existence check operation.
InterpreterSuperInstruction getIndexSuperInstInfo (const RamIndexOperation &ramIndex)
Encode and return the super-instruction information about a index operation.
size_t getNewRelId ()
Get a valid relation id for encoding.
size_t getNextViewId ()
Get a valid view id for encoding.
InterpreterSuperInstruction getProjectSuperInstInfo (const RamProject &exist)
Encode and return the super-instruction information about a project operation.
const RamRelation & getRelationRefForView (const RamNode *node)
Return the associated relation of a operation which requires a view.
void newQueryBlock ()
Reset view allocation system, since view's life time is within each query.
bool requireView (const RamNode *node)
Return true if the given operation requires a view.
std::vector< const RamCondition * > toConjunctionList (const RamCondition *condition)
Convert terms of a conjunction to a list.
Private Attributes
std::unordered_map< const RamNode *, size_t > indexTable
Environment encoding, store a mapping from RamNode to its operation index id.
RamIndexAnalysis * isa
Used by index encoding.
const bool isProvenance
If generating a provenance program.
std::shared_ptr< InterpreterPreamble > parentQueryPreamble = nullptr
Points to the current preamble during the generation.
const bool profileEnabled
If profile is enable in this program.
RamProgram * program
RamProgram.
std::vector< std::unique_ptr< RelationHandle > > relations
Symbol table for relations.
size_t relId = 0
Next available location to encode a relation.
std::unordered_map< const RamRelation *, size_t > relTable
Environment encoding, store a mapping from RamRelation to its id.
size_t viewId = 0
Next available location to encode View.
std::unordered_map< const RamNode *, size_t > viewTable
Environment encoding, store a mapping from RamNode to its View id.
Additional Inherited Members
Protected Member Functions inherited from souffle::RamVisitor< std::unique_ptr< InterpreterNode > >
LINK (IO, RelationStatement)
LINK (Query, Statement)
LINK (Clear, RelationStatement)
LINK (LogSize, RelationStatement)
LINK (RelationStatement, Statement)
LINK (Swap, BinRelationStatement)
LINK (Extend, BinRelationStatement)
LINK (BinRelationStatement, Statement)
LINK (Sequence, ListStatement)
LINK (Loop, Statement)
LINK (Parallel, ListStatement)
LINK (ListStatement, Statement)
LINK (Exit, Statement)
LINK (LogTimer, Statement)
LINK (LogRelationTimer, Statement)
LINK (DebugInfo, Statement)
LINK (Call, Statement)
LINK (Statement, Node)
LINK (Project, Operation)
LINK (SubroutineReturn, Operation)
LINK (UnpackRecord, TupleOperation)
LINK (Scan, RelationOperation)
LINK (ParallelScan, Scan)
LINK (IndexScan, IndexOperation)
LINK (ParallelIndexScan, IndexScan)
LINK (Choice, RelationOperation)
LINK (ParallelChoice, Choice)
LINK (IndexChoice, IndexOperation)
LINK (ParallelIndexChoice, IndexChoice)
LINK (RelationOperation, TupleOperation)
LINK (Aggregate, RelationOperation)
LINK (ParallelAggregate, Aggregate)
LINK (IndexAggregate, IndexOperation)
LINK (ParallelIndexAggregate, IndexAggregate)
LINK (IndexOperation, RelationOperation)
LINK (TupleOperation, NestedOperation)
LINK (Filter, AbstractConditional)
LINK (Break, AbstractConditional)
LINK (AbstractConditional, NestedOperation)
LINK (NestedOperation, Operation)
LINK (Operation, Node)
LINK (True, Condition)
LINK (False, Condition)
LINK (Conjunction, Condition)
LINK (Negation, Condition)
LINK (Constraint, Condition)
LINK (ProvenanceExistenceCheck, AbstractExistenceCheck)
LINK (ExistenceCheck, AbstractExistenceCheck)
LINK (EmptinessCheck, Condition)
LINK (AbstractExistenceCheck, Condition)
LINK (Condition, Node)
LINK (SignedConstant, Constant)
LINK (UnsignedConstant, Constant)
LINK (FloatConstant, Constant)
LINK (Constant, Expression)
LINK (UndefValue, Expression)
LINK (TupleElement, Expression)
LINK (IntrinsicOperator, AbstractOperator)
LINK (UserDefinedOperator, AbstractOperator)
LINK (AbstractOperator, Expression)
LINK (AutoIncrement, Expression)
LINK (PackRecord, Expression)
LINK (SubroutineArgument, Expression)
LINK (Expression, Node)
LINK (Program, Node)
LINK (Relation, Node)
LINK (RelationReference, Node)
virtual std::unique_ptr< InterpreterNode > visitNode (const RamNode &, Params...)
The base case for all visitors – if no more specific overload was defined.
Detailed Description
Definition at line 54 of file InterpreterGenerator.h.
Member Typedef Documentation
NodePtr
using souffle::NodeGenerator::NodePtr = std::unique_ptr<InterpreterNode> private
Definition at line 55 of file InterpreterGenerator.h.
NodePtrVec
using souffle::NodeGenerator::NodePtrVec = std::vector<NodePtr> private
Definition at line 56 of file InterpreterGenerator.h.
RelationHandle
using souffle::NodeGenerator::RelationHandle = std::unique_ptr<InterpreterRelation> private
Definition at line 57 of file InterpreterGenerator.h.
Constructor & Destructor Documentation
NodeGenerator()
souffle::NodeGenerator::NodeGenerator (RamIndexAnalysis * isa) inline
Definition at line 60 of file InterpreterGenerator.h.
             : isa(isa), isProvenance(Global::config().has("provenance")),
               profileEnabled(Global::config().has("profile")) {}
Member Function Documentation
createRelation()
void souffle::NodeGenerator::createRelation (const RamRelation & id, const MinIndexSelection & orderSet, const size_t idx) inline private
Create and add relation into the runtime environment.
Definition at line 639 of file InterpreterGenerator.h.
References souffle::createBTreeProvenanceIndex(), and souffle::EQREL.
Referenced by encodeRelation().
{
         RelationHandle res;
         if (relations.size() < idx + 1) {
             relations.resize(idx + 1);
         }
         if (id.getRepresentation() == RelationRepresentation::EQREL) {
             res = std::make_unique<InterpreterEqRelation>(id.getArity(), id.getAuxiliaryArity(), id.getName(),
                     std::vector<std::string>(), orderSet);
         } else {
             if (isProvenance) {
                 res = std::make_unique<InterpreterRelation>(id.getArity(), id.getAuxiliaryArity(),
                         id.getName(), std::vector<std::string>(), orderSet, createBTreeProvenanceIndex);
             } else {
                 res = std::make_unique<InterpreterRelation>(id.getArity(), id.getAuxiliaryArity(),
                         id.getName(), std::vector<std::string>(), orderSet);
             }
         }
         relations[idx] = std::make_unique<RelationHandle>(std::move(res));
     }
encodeIndexPos()
template<class RamNode > size_t souffle::NodeGenerator::encodeIndexPos (RamNode & node) inline private
Return operation index id from the result of indexAnalysis.
Definition at line 536 of file InterpreterGenerator.h.
References souffle::SearchSignature::arity(), souffle::SearchSignature::empty(), souffle::SearchSignature::getFullSearchSignature(), souffle::RamIndexAnalysis::getIndexes(), souffle::MinIndexSelection::getLexOrderNum(), souffle::RamIndexAnalysis::getSearchSignature(), and i.
Referenced by generateTree(), visitParallelIndexChoice(), and visitParallelIndexScan().
{
         const MinIndexSelection& orderSet = isa->getIndexes(node.getRelation());
         SearchSignature signature = isa->getSearchSignature(&node);
         // A zero signature is equivalent as a full order signature.
         if (signature.empty()) {
             signature = SearchSignature::getFullSearchSignature(signature.arity());
         }
         auto i = orderSet.getLexOrderNum(signature);
         indexTable[&node] = i;
         return i;
     };
encodeRelation()
size_t souffle::NodeGenerator::encodeRelation (const RamRelation & rel) inline private
Encode and create the relation, return the relation id.
Definition at line 560 of file InterpreterGenerator.h.
References createRelation(), souffle::RamIndexAnalysis::getIndexes(), and getNewRelId().
Referenced by visitAggregate(), visitChoice(), visitClear(), visitEmptinessCheck(), visitExtend(), visitIndexAggregate(), visitIO(), visitLogRelationTimer(), visitLogSize(), visitParallelAggregate(), visitParallelChoice(), visitParallelIndexAggregate(), visitParallelIndexChoice(), visitParallelIndexScan(), visitParallelScan(), visitProject(), visitQuery(), visitScan(), and visitSwap().
{
         auto pos = relTable.find(&rel);
         if (pos != relTable.end()) {
             return pos->second;
         }
         size_t id = getNewRelId();
         relTable[&rel] = id;
         createRelation(rel, isa->getIndexes(rel), id);
         return id;
     }
encodeView()
size_t souffle::NodeGenerator::encodeView (const RamNode * node) inline private
Encode and return the View id of an operation.
Definition at line 549 of file InterpreterGenerator.h.
References getNextViewId().
Referenced by generateTree(), visitExistenceCheck(), visitIndexAggregate(), visitIndexChoice(), visitIndexScan(), visitParallelIndexAggregate(), visitProvenanceExistenceCheck(), and visitQuery().
{
         auto pos = viewTable.find(node);
         if (pos != viewTable.end()) {
             return pos->second;
         }
         size_t id = getNextViewId();
         viewTable[node] = id;
         return id;
     }
findAllViews()
NodePtrVec souffle::NodeGenerator::findAllViews (const RamNode & node) inline private
Find all operations under the root node that requires a view.
Return a list of InterpreterNodes.
Definition at line 575 of file InterpreterGenerator.h.
References requireView(), souffle::RamVisitor< std::unique_ptr< InterpreterNode > >::visit(), and souffle::visitDepthFirst().
{
         NodePtrVec res;
         visitDepthFirst(node, [&](const RamNode& node) {
             if (requireView(&node)) {
                 res.push_back(visit(node));
             };
         });
         return res;
     }
generateTree()
NodePtr souffle::NodeGenerator::generateTree (const RamNode & root, const RamProgram & program) inline
Generate the tree based on given entry.
Return a NodePtr to the root.
Definition at line 68 of file InterpreterGenerator.h.
References encodeIndexPos(), encodeView(), newQueryBlock(), program, souffle::RamVisitor< std::unique_ptr< InterpreterNode > >::visit(), and souffle::visitDepthFirst().
Referenced by souffle::InterpreterEngine::generateIR().
{
         this->program = const_cast<RamProgram*>(&program);
         // Encode all relation, indexPos and viewId.
         visitDepthFirst(root, [&](const RamNode& node) {
             if (dynamic_cast<const RamQuery*>(&node) != nullptr) {
                 newQueryBlock();
             }
             if (const auto* indexSearch = dynamic_cast<const RamIndexOperation*>(&node)) {
                 encodeIndexPos(*indexSearch);
                 encodeView(indexSearch);
             } else if (const auto* exists = dynamic_cast<const RamExistenceCheck*>(&node)) {
                 encodeIndexPos(*exists);
                 encodeView(exists);
             } else if (const auto* provExists = dynamic_cast<const RamProvenanceExistenceCheck*>(&node)) {
                 encodeIndexPos(*provExists);
                 encodeView(provExists);
             }
         });
         // Parse program
         return visit(root);
     }
getExistenceSuperInstInfo()
InterpreterSuperInstruction souffle::NodeGenerator::getExistenceSuperInstInfo (const RamAbstractExistenceCheck & exist) inline private
Encode and return the super-instruction information about an existence check operation.
Definition at line 725 of file InterpreterGenerator.h.
References souffle::InterpreterSuperInstruction::exprFirst, souffle::InterpreterSuperInstruction::first, souffle::RamRelation::getArity(), souffle::RamAbstractExistenceCheck::getRelation(), souffle::RamAbstractExistenceCheck::getValues(), i, souffle::isRamUndefValue(), souffle::MAX_RAM_SIGNED, souffle::MIN_RAM_SIGNED, souffle::InterpreterSuperInstruction::second, souffle::InterpreterSuperInstruction::tupleFirst, and souffle::RamVisitor< std::unique_ptr< InterpreterNode > >::visit().
Referenced by visitExistenceCheck(), and visitProvenanceExistenceCheck().
{
         size_t arity = exist.getRelation().getArity();
         InterpreterSuperInstruction superOp(arity);
         const auto& children = exist.getValues();
         for (size_t i = 0; i < arity; ++i) {
             auto& child = children[i];
             // Unbounded
             if (isRamUndefValue(child)) {
                 superOp.first[i] = MIN_RAM_SIGNED;
                 superOp.second[i] = MAX_RAM_SIGNED;
                 continue;
             }
             // Constant
             if (dynamic_cast<RamConstant*>(child) != nullptr) {
                 superOp.first[i] = dynamic_cast<RamConstant*>(child)->getConstant();
                 superOp.second[i] = superOp.first[i];
                 continue;
             }
             // TupleElement
             if (dynamic_cast<RamTupleElement*>(child) != nullptr) {
                 auto tuple = dynamic_cast<RamTupleElement*>(child);
                 superOp.tupleFirst.push_back({i, (size_t)tuple->getTupleId(), tuple->getElement()});
                 continue;
             }
             // Generic expression
             superOp.exprFirst.push_back(std::pair<size_t, std::unique_ptr<InterpreterNode>>(i, visit(child)));
         }
         return superOp;
     }
getIndexSuperInstInfo()
InterpreterSuperInstruction souffle::NodeGenerator::getIndexSuperInstInfo (const RamIndexOperation & ramIndex) inline private
Encode and return the super-instruction information about a index operation.
Definition at line 662 of file InterpreterGenerator.h.
References souffle::InterpreterSuperInstruction::exprFirst, souffle::InterpreterSuperInstruction::exprSecond, souffle::InterpreterSuperInstruction::first, souffle::RamRelation::getArity(), souffle::RamIndexOperation::getRangePattern(), souffle::RamRelationOperation::getRelation(), i, souffle::isRamUndefValue(), low, souffle::MAX_RAM_SIGNED, souffle::MIN_RAM_SIGNED, souffle::InterpreterSuperInstruction::second, souffle::InterpreterSuperInstruction::tupleFirst, souffle::InterpreterSuperInstruction::tupleSecond, and souffle::RamVisitor< std::unique_ptr< InterpreterNode > >::visit().
Referenced by visitIndexAggregate(), visitIndexChoice(), visitIndexScan(), visitParallelIndexAggregate(), visitParallelIndexChoice(), and visitParallelIndexScan().
{
         size_t arity = ramIndex.getRelation().getArity();
         InterpreterSuperInstruction indexOperation(arity);
         const auto& first = ramIndex.getRangePattern().first;
         for (size_t i = 0; i < arity; ++i) {
             auto& low = first[i];
             // Unbounded
             if (isRamUndefValue(low)) {
                 indexOperation.first[i] = MIN_RAM_SIGNED;
                 continue;
             }
             // Constant
             if (dynamic_cast<RamConstant*>(low) != nullptr) {
                 indexOperation.first[i] = dynamic_cast<RamConstant*>(low)->getConstant();
                 continue;
             }
             // TupleElement
             if (dynamic_cast<RamTupleElement*>(low) != nullptr) {
                 auto lowTuple = dynamic_cast<RamTupleElement*>(low);
                 indexOperation.tupleFirst.push_back(
                         {i, (size_t)lowTuple->getTupleId(), lowTuple->getElement()});
                 continue;
             }
             // Generic expression
             indexOperation.exprFirst.push_back(
                     std::pair<size_t, std::unique_ptr<InterpreterNode>>(i, visit(low)));
         }
         const auto& second = ramIndex.getRangePattern().second;
         for (size_t i = 0; i < arity; ++i) {
             auto& hig = second[i];
             // Unbounded
             if (isRamUndefValue(hig)) {
                 indexOperation.second[i] = MAX_RAM_SIGNED;
                 continue;
             }
             // Constant
             if (dynamic_cast<RamConstant*>(hig) != nullptr) {
                 indexOperation.second[i] = dynamic_cast<RamConstant*>(hig)->getConstant();
                 continue;
             }
             // TupleElement
             if (dynamic_cast<RamTupleElement*>(hig) != nullptr) {
                 auto highTuple = dynamic_cast<RamTupleElement*>(hig);
                 indexOperation.tupleSecond.push_back(
                         {i, (size_t)highTuple->getTupleId(), highTuple->getElement()});
                 continue;
             }
             // Generic expression
             indexOperation.exprSecond.push_back(
                     std::pair<size_t, std::unique_ptr<InterpreterNode>>(i, visit(hig)));
         }
         return indexOperation;
     }
getNewRelId()
size_t souffle::NodeGenerator::getNewRelId () inline private
Get a valid relation id for encoding.
Definition at line 525 of file InterpreterGenerator.h.
Referenced by encodeRelation().
{
         return relId++;
     }
getNextViewId()
size_t souffle::NodeGenerator::getNextViewId () inline private
Get a valid view id for encoding.
Definition at line 530 of file InterpreterGenerator.h.
Referenced by encodeView().
{
         return viewId++;
     }
getProjectSuperInstInfo()
InterpreterSuperInstruction souffle::NodeGenerator::getProjectSuperInstInfo (const RamProject & exist) inline private
Encode and return the super-instruction information about a project operation.
Definition at line 761 of file InterpreterGenerator.h.
References souffle::InterpreterSuperInstruction::exprFirst, souffle::InterpreterSuperInstruction::first, souffle::RamRelation::getArity(), souffle::RamProject::getRelation(), souffle::RamProject::getValues(), i, souffle::InterpreterSuperInstruction::tupleFirst, and souffle::RamVisitor< std::unique_ptr< InterpreterNode > >::visit().
Referenced by visitProject().
{
         size_t arity = exist.getRelation().getArity();
         InterpreterSuperInstruction superOp(arity);
         const auto& children = exist.getValues();
         for (size_t i = 0; i < arity; ++i) {
             auto& child = children[i];
             // Constant
             if (dynamic_cast<RamConstant*>(child) != nullptr) {
                 superOp.first[i] = dynamic_cast<RamConstant*>(child)->getConstant();
                 continue;
             }
             // TupleElement
             if (dynamic_cast<RamTupleElement*>(child) != nullptr) {
                 auto tuple = dynamic_cast<RamTupleElement*>(child);
                 superOp.tupleFirst.push_back({i, (size_t)tuple->getTupleId(), tuple->getElement()});
                 continue;
             }
             // Generic expression
             superOp.exprFirst.push_back(std::pair<size_t, std::unique_ptr<InterpreterNode>>(i, visit(child)));
         }
         return superOp;
     }
getRelationHandle()
RelationHandle& souffle::NodeGenerator::getRelationHandle (const size_t idx) inline
Return relation handle from given index.
Definition at line 489 of file InterpreterGenerator.h.
References relations.
Referenced by souffle::InterpreterEngine::getRelationHandle().
{
         return *relations[idx];
     }
getRelationRefForView()
const RamRelation& souffle::NodeGenerator::getRelationRefForView (const RamNode * node) inline private
Return the associated relation of a operation which requires a view.
This function assume the operation does requires a view.
Definition at line 601 of file InterpreterGenerator.h.
References souffle::fatal().
Referenced by visitQuery().
{
         if (const auto* exist = dynamic_cast<const RamAbstractExistenceCheck*>(node)) {
             return exist->getRelation();
         } else if (const auto* index = dynamic_cast<const RamIndexOperation*>(node)) {
             return index->getRelation();
         }
         fatal("The RamNode does not require a view.");
     }
getRelations()
std::vector<std::unique_ptr<RelationHandle> >& souffle::NodeGenerator::getRelations () inline
Move relation map.
Definition at line 484 of file InterpreterGenerator.h.
References relations.
Referenced by souffle::InterpreterEngine::getRelationMap().
{
         return relations;
     }
newQueryBlock()
void souffle::NodeGenerator::newQueryBlock () inline private
Reset view allocation system, since view's life time is within each query.
Definition at line 519 of file InterpreterGenerator.h.
Referenced by generateTree().
{
         viewTable.clear();
         viewId = 0;
     }
requireView()
bool souffle::NodeGenerator::requireView (const RamNode * node) inline private
Return true if the given operation requires a view.
Definition at line 588 of file InterpreterGenerator.h.
Referenced by findAllViews(), and visitQuery().
{
         if (dynamic_cast<const RamAbstractExistenceCheck*>(node) != nullptr) {
             return true;
         } else if (dynamic_cast<const RamIndexOperation*>(node) != nullptr) {
             return true;
         }
         return false;
     }
toConjunctionList()
std::vector<const RamCondition*> souffle::NodeGenerator::toConjunctionList (const RamCondition * condition) inline private
Convert terms of a conjunction to a list.
Convert a condition of the format C1 /\ C2 /\ ... /\ Cn to a list {C1, C2, ..., Cn}.
Definition at line 617 of file InterpreterGenerator.h.
Referenced by visitQuery().
{
         std::vector<const RamCondition*> conditionList;
         std::queue<const RamCondition*> conditionsToProcess;
         if (condition != nullptr) {
             conditionsToProcess.push(condition);
             while (!conditionsToProcess.empty()) {
                 condition = conditionsToProcess.front();
                 conditionsToProcess.pop();
                 if (const auto* ramConj = dynamic_cast<const RamConjunction*>(condition)) {
                     conditionsToProcess.push(&ramConj->getLHS());
                     conditionsToProcess.push(&ramConj->getRHS());
                 } else {
                     conditionList.emplace_back(condition);
                 }
             }
         }
         return conditionList;
     }
visitAggregate()
NodePtr souffle::NodeGenerator::visitAggregate (const RamAggregate & aggregate) inline override
Definition at line 274 of file InterpreterGenerator.h.
References encodeRelation(), souffle::RamRelationOperation::getRelation(), souffle::I_Aggregate, relations, relId, souffle::RamVisitor< std::unique_ptr< InterpreterNode > >::visit(), and visitTupleOperation().
{
         size_t relId = encodeRelation(aggregate.getRelation());
         auto rel = relations[relId].get();
         return std::make_unique<InterpreterAggregate>(I_Aggregate, &aggregate, rel,
                 visit(aggregate.getExpression()), visit(aggregate.getCondition()),
                 visitTupleOperation(aggregate));
     }
visitAutoIncrement()
NodePtr souffle::NodeGenerator::visitAutoIncrement (const RamAutoIncrement & inc) inline override
Definition at line 98 of file InterpreterGenerator.h.
References souffle::I_AutoIncrement.
{
         return std::make_unique<InterpreterAutoIncrement>(I_AutoIncrement, &inc);
     }
visitBreak()
NodePtr souffle::NodeGenerator::visitBreak (const RamBreak & breakOp) inline override
Definition at line 312 of file InterpreterGenerator.h.
References souffle::I_Break, and souffle::RamVisitor< std::unique_ptr< InterpreterNode > >::visit().
{
         return std::make_unique<InterpreterBreak>(
                 I_Break, &breakOp, visit(breakOp.getCondition()), visit(breakOp.getOperation()));
     }
visitCall()
NodePtr souffle::NodeGenerator::visitCall (const RamCall & call) inline override
Definition at line 363 of file InterpreterGenerator.h.
References souffle::RamCall::getName(), souffle::RamProgram::getSubroutines(), souffle::I_Call, and program.
{
         // translate a subroutine name to an index
         // the index is used to identify the subroutine
         // in the interpreter. The index is stored in the
         // data array of the InterpreterNode as the first
         // entry.
         auto subs = program->getSubroutines();
         size_t subroutineId = distance(subs.begin(), subs.find(call.getName()));
         return std::make_unique<InterpreterCall>(I_Call, &call, subroutineId);
     }
visitChoice()
NodePtr souffle::NodeGenerator::visitChoice (const RamChoice & choice) inline override
Definition at line 235 of file InterpreterGenerator.h.
References encodeRelation(), souffle::RamRelationOperation::getRelation(), souffle::I_Choice, relations, relId, souffle::RamVisitor< std::unique_ptr< InterpreterNode > >::visit(), and visitTupleOperation().
{
         size_t relId = encodeRelation(choice.getRelation());
         auto rel = relations[relId].get();
         return std::make_unique<InterpreterChoice>(
                 I_Choice, &choice, rel, visit(choice.getCondition()), visitTupleOperation(choice));
     }
visitClear()
NodePtr souffle::NodeGenerator::visitClear (const RamClear & clear) inline override
Definition at line 395 of file InterpreterGenerator.h.
References encodeRelation(), souffle::RamRelationStatement::getRelation(), souffle::I_Clear, relations, and relId.
{
         size_t relId = encodeRelation(clear.getRelation());
         auto rel = relations[relId].get();
         return std::make_unique<InterpreterClear>(I_Clear, &clear, rel);
     }
visitConjunction()
NodePtr souffle::NodeGenerator::visitConjunction (const RamConjunction & conj) inline override
Definition at line 150 of file InterpreterGenerator.h.
References souffle::I_Conjunction, and souffle::RamVisitor< std::unique_ptr< InterpreterNode > >::visit().
{
         return std::make_unique<InterpreterConjunction>(
                 I_Conjunction, &conj, visit(conj.getLHS()), visit(conj.getRHS()));
     }
visitConstant()
NodePtr souffle::NodeGenerator::visitConstant (const RamConstant & num) inline override
Definition at line 90 of file InterpreterGenerator.h.
References souffle::I_Constant.
{
         return std::make_unique<InterpreterConstant>(I_Constant, &num);
     }
visitConstraint()
NodePtr souffle::NodeGenerator::visitConstraint (const RamConstraint & relOp) inline override
Definition at line 185 of file InterpreterGenerator.h.
References souffle::I_Constraint, and souffle::RamVisitor< std::unique_ptr< InterpreterNode > >::visit().
{
         return std::make_unique<InterpreterConstraint>(
                 I_Constraint, &relOp, visit(relOp.getLHS()), visit(relOp.getRHS()));
     }
visitDebugInfo()
NodePtr souffle::NodeGenerator::visitDebugInfo (const RamDebugInfo & dbg) inline override
Definition at line 389 of file InterpreterGenerator.h.
References souffle::RamAbstractLog::getStatement(), souffle::I_DebugInfo, and souffle::RamVisitor< std::unique_ptr< InterpreterNode > >::visit().
{
         NodePtrVec children;
         children.push_back(visit(dbg.getStatement()));
         return std::make_unique<InterpreterDebugInfo>(I_DebugInfo, &dbg, visit(dbg.getStatement()));
     }
visitEmptinessCheck()
NodePtr souffle::NodeGenerator::visitEmptinessCheck (const RamEmptinessCheck & emptiness) inline override
Definition at line 159 of file InterpreterGenerator.h.
References encodeRelation(), souffle::RamEmptinessCheck::getRelation(), souffle::I_EmptinessCheck, relations, and relId.
{
         size_t relId = encodeRelation(emptiness.getRelation());
         auto rel = relations[relId].get();
         return std::make_unique<InterpreterEmptinessCheck>(I_EmptinessCheck, &emptiness, rel);
     }
visitExistenceCheck()
NodePtr souffle::NodeGenerator::visitExistenceCheck (const RamExistenceCheck & exists) inline override
Definition at line 165 of file InterpreterGenerator.h.
References encodeView(), getExistenceSuperInstInfo(), souffle::RamAbstractExistenceCheck::getValues(), souffle::I_ExistenceCheck, and souffle::isRamUndefValue().
{
         InterpreterSuperInstruction superOp = getExistenceSuperInstInfo(exists);
         // Check if the search signature is a total signature
         bool isTotal = true;
         for (const auto& cur : exists.getValues()) {
             if (isRamUndefValue(cur)) {
                 isTotal = false;
             }
         }
         return std::make_unique<InterpreterExistenceCheck>(
                 I_ExistenceCheck, &exists, isTotal, encodeView(&exists), std::move(superOp));
     }
visitExit()
NodePtr souffle::NodeGenerator::visitExit (const RamExit & exit) inline override
Definition at line 359 of file InterpreterGenerator.h.
References souffle::I_Exit, and souffle::RamVisitor< std::unique_ptr< InterpreterNode > >::visit().
{
         return std::make_unique<InterpreterExit>(I_Exit, &exit, visit(exit.getCondition()));
     }
visitExtend()
NodePtr souffle::NodeGenerator::visitExtend (const RamExtend & extend) inline override
Definition at line 462 of file InterpreterGenerator.h.
References encodeRelation(), souffle::RamBinRelationStatement::getFirstRelation(), souffle::RamBinRelationStatement::getSecondRelation(), and souffle::I_Extend.
{
         size_t src = encodeRelation(extend.getFirstRelation());
         size_t target = encodeRelation(extend.getSecondRelation());
         return std::make_unique<InterpreterExtend>(I_Extend, &extend, src, target);
     }
visitFalse()
NodePtr souffle::NodeGenerator::visitFalse (const RamFalse & lfalse) inline override
Definition at line 146 of file InterpreterGenerator.h.
References souffle::I_False.
{
         return std::make_unique<InterpreterFalse>(I_False, &lfalse);
     }
visitFilter()
NodePtr souffle::NodeGenerator::visitFilter (const RamFilter & filter) inline override
Definition at line 317 of file InterpreterGenerator.h.
References souffle::filter(), souffle::I_Filter, and souffle::RamVisitor< std::unique_ptr< InterpreterNode > >::visit().
{
         return std::make_unique<InterpreterFilter>(
                 I_Filter, &filter, visit(filter.getCondition()), visit(filter.getOperation()));
     }
visitIndexAggregate()
NodePtr souffle::NodeGenerator::visitIndexAggregate (const RamIndexAggregate & aggregate) inline override
Definition at line 292 of file InterpreterGenerator.h.
References encodeRelation(), encodeView(), getIndexSuperInstInfo(), souffle::RamRelationOperation::getRelation(), souffle::I_IndexAggregate, relations, relId, souffle::RamVisitor< std::unique_ptr< InterpreterNode > >::visit(), and visitTupleOperation().
{
         InterpreterSuperInstruction indexOperation = getIndexSuperInstInfo(aggregate);
         size_t relId = encodeRelation(aggregate.getRelation());
         auto rel = relations[relId].get();
         return std::make_unique<InterpreterIndexAggregate>(I_IndexAggregate, &aggregate, rel,
                 visit(aggregate.getExpression()), visit(aggregate.getCondition()),
                 visitTupleOperation(aggregate), encodeView(&aggregate), std::move(indexOperation));
     }
visitIndexChoice()
NodePtr souffle::NodeGenerator::visitIndexChoice (const RamIndexChoice & choice) inline override
Definition at line 251 of file InterpreterGenerator.h.
References encodeView(), getIndexSuperInstInfo(), souffle::I_IndexChoice, souffle::RamVisitor< std::unique_ptr< InterpreterNode > >::visit(), and visitTupleOperation().
{
         InterpreterSuperInstruction indexOperation = getIndexSuperInstInfo(choice);
         return std::make_unique<InterpreterIndexChoice>(I_IndexChoice, &choice, nullptr,
                 visit(choice.getCondition()), visitTupleOperation(choice), encodeView(&choice),
                 std::move(indexOperation));
     }
visitIndexScan()
NodePtr souffle::NodeGenerator::visitIndexScan (const RamIndexScan & scan) inline override
Definition at line 217 of file InterpreterGenerator.h.
References encodeView(), getIndexSuperInstInfo(), souffle::I_IndexScan, and visitTupleOperation().
{
         InterpreterSuperInstruction indexOperation = getIndexSuperInstInfo(scan);
         NodePtrVec children;
         children.push_back(visitTupleOperation(scan));
         return std::make_unique<InterpreterIndexScan>(I_IndexScan, &scan, nullptr, visitTupleOperation(scan),
                 encodeView(&scan), std::move(indexOperation));
     }
visitIntrinsicOperator()
NodePtr souffle::NodeGenerator::visitIntrinsicOperator (const RamIntrinsicOperator & op) inline override
Definition at line 102 of file InterpreterGenerator.h.
References souffle::RamAbstractOperator::getArguments(), souffle::I_IntrinsicOperator, and souffle::RamVisitor< std::unique_ptr< InterpreterNode > >::visit().
{
         NodePtrVec children;
         for (const auto& arg : op.getArguments()) {
             children.push_back(visit(arg));
         }
         return std::make_unique<InterpreterIntrinsicOperator>(I_IntrinsicOperator, &op, std::move(children));
     }
visitIO()
NodePtr souffle::NodeGenerator::visitIO (const RamIO & io) inline override
Definition at line 407 of file InterpreterGenerator.h.
References encodeRelation(), souffle::RamRelationStatement::getRelation(), souffle::I_IO, relations, and relId.
{
         size_t relId = encodeRelation(io.getRelation());
         auto rel = relations[relId].get();
         return std::make_unique<InterpreterIO>(I_IO, &io, rel);
     }
visitLogRelationTimer()
NodePtr souffle::NodeGenerator::visitLogRelationTimer (const RamLogRelationTimer & timer) inline override
Definition at line 374 of file InterpreterGenerator.h.
References encodeRelation(), souffle::RamRelationStatement::getRelation(), souffle::RamAbstractLog::getStatement(), souffle::I_LogRelationTimer, relations, relId, and souffle::RamVisitor< std::unique_ptr< InterpreterNode > >::visit().
{
         size_t relId = encodeRelation(timer.getRelation());
         auto rel = relations[relId].get();
         NodePtrVec children;
         children.push_back(visit(timer.getStatement()));
         return std::make_unique<InterpreterLogRelationTimer>(
                 I_LogRelationTimer, &timer, visit(timer.getStatement()), rel);
     }
visitLogSize()
NodePtr souffle::NodeGenerator::visitLogSize (const RamLogSize & size) inline override
Definition at line 401 of file InterpreterGenerator.h.
References encodeRelation(), souffle::RamRelationStatement::getRelation(), souffle::I_LogSize, relations, and relId.
{
         size_t relId = encodeRelation(size.getRelation());
         auto rel = relations[relId].get();
         return std::make_unique<InterpreterLogSize>(I_LogSize, &size, rel);
     }
visitLogTimer()
NodePtr souffle::NodeGenerator::visitLogTimer (const RamLogTimer & timer) inline override
Definition at line 383 of file InterpreterGenerator.h.
References souffle::RamAbstractLog::getStatement(), souffle::I_LogTimer, and souffle::RamVisitor< std::unique_ptr< InterpreterNode > >::visit().
{
         NodePtrVec children;
         children.push_back(visit(timer.getStatement()));
         return std::make_unique<InterpreterLogTimer>(I_LogTimer, &timer, visit(timer.getStatement()));
     }
visitLoop()
NodePtr souffle::NodeGenerator::visitLoop (const RamLoop & loop) inline override
Definition at line 355 of file InterpreterGenerator.h.
References souffle::I_Loop, and souffle::RamVisitor< std::unique_ptr< InterpreterNode > >::visit().
{
         return std::make_unique<InterpreterLoop>(I_Loop, &loop, visit(loop.getBody()));
     }
visitNegation()
NodePtr souffle::NodeGenerator::visitNegation (const RamNegation & neg) inline override
Definition at line 155 of file InterpreterGenerator.h.
References souffle::I_Negation, and souffle::RamVisitor< std::unique_ptr< InterpreterNode > >::visit().
{
         return std::make_unique<InterpreterNegation>(I_Negation, &neg, visit(neg.getOperand()));
     }
visitNestedIntrinsicOperator()
NodePtr souffle::NodeGenerator::visitNestedIntrinsicOperator (const RamNestedIntrinsicOperator & op) inline override
Definition at line 119 of file InterpreterGenerator.h.
References souffle::RamNestedIntrinsicOperator::getArguments(), souffle::I_NestedIntrinsicOperator, souffle::RamVisitor< std::unique_ptr< InterpreterNode > >::visit(), and visitTupleOperation().
{
         NodePtrVec children;
         for (auto&& arg : op.getArguments()) {
             children.push_back(visit(arg));
         }
         children.push_back(visitTupleOperation(op));
         return std::make_unique<InterpreterNestedIntrinsicOperator>(
                 I_NestedIntrinsicOperator, &op, std::move(children));
     }
visitNestedOperation()
NodePtr souffle::NodeGenerator::visitNestedOperation (const RamNestedOperation & nested) inline override
Definition at line 190 of file InterpreterGenerator.h.
References souffle::RamNestedOperation::getOperation(), and souffle::RamVisitor< std::unique_ptr< InterpreterNode > >::visit().
{
         return visit(nested.getOperation());
     }
visitNode()
NodePtr souffle::NodeGenerator::visitNode (const RamNode & node) inline override
Definition at line 478 of file InterpreterGenerator.h.
References souffle::fatal().
{
         fatal("unsupported node type: %s", typeid(node).name());
     }
visitPackRecord()
NodePtr souffle::NodeGenerator::visitPackRecord (const RamPackRecord & pr) inline override
Definition at line 129 of file InterpreterGenerator.h.
References souffle::RamPackRecord::getArguments(), souffle::I_PackRecord, and souffle::RamVisitor< std::unique_ptr< InterpreterNode > >::visit().
{
         NodePtrVec children;
         for (const auto& arg : pr.getArguments()) {
             children.push_back(visit(arg));
         }
         return std::make_unique<InterpreterPackRecord>(I_PackRecord, &pr, std::move(children));
     }
visitParallel()
NodePtr souffle::NodeGenerator::visitParallel (const RamParallel & parallel) inline override
Definition at line 346 of file InterpreterGenerator.h.
References souffle::RamListStatement::getStatements(), souffle::I_Parallel, and souffle::RamVisitor< std::unique_ptr< InterpreterNode > >::visit().
{
         // Parallel statements are executed in sequence for now.
         NodePtrVec children;
         for (const auto& value : parallel.getStatements()) {
             children.push_back(visit(value));
         }
         return std::make_unique<InterpreterParallel>(I_Parallel, &parallel, std::move(children));
     }
visitParallelAggregate()
NodePtr souffle::NodeGenerator::visitParallelAggregate (const RamParallelAggregate & aggregate) inline override
Definition at line 282 of file InterpreterGenerator.h.
References encodeRelation(), souffle::RamRelationOperation::getRelation(), souffle::I_ParallelAggregate, parentQueryPreamble, relations, relId, souffle::RamVisitor< std::unique_ptr< InterpreterNode > >::visit(), and visitTupleOperation().
{
         size_t relId = encodeRelation(aggregate.getRelation());
         auto rel = relations[relId].get();
         auto res = std::make_unique<InterpreterParallelAggregate>(I_ParallelAggregate, &aggregate, rel,
                 visit(aggregate.getExpression()), visit(aggregate.getCondition()),
                 visitTupleOperation(aggregate));
         res->setPreamble(parentQueryPreamble);
         return res;
     }
visitParallelChoice()
NodePtr souffle::NodeGenerator::visitParallelChoice (const RamParallelChoice & pchoice) inline override
Definition at line 242 of file InterpreterGenerator.h.
References encodeRelation(), souffle::RamRelationOperation::getRelation(), souffle::I_ParallelChoice, parentQueryPreamble, relations, relId, souffle::RamVisitor< std::unique_ptr< InterpreterNode > >::visit(), and visitTupleOperation().
{
         size_t relId = encodeRelation(pchoice.getRelation());
         auto rel = relations[relId].get();
         auto res = std::make_unique<InterpreterParallelChoice>(
                 I_ParallelChoice, &pchoice, rel, visit(pchoice.getCondition()), visitTupleOperation(pchoice));
         res->setPreamble(parentQueryPreamble);
         return res;
     }
visitParallelIndexAggregate()
NodePtr souffle::NodeGenerator::visitParallelIndexAggregate (const RamParallelIndexAggregate & aggregate) inline override
Definition at line 301 of file InterpreterGenerator.h.
References encodeRelation(), encodeView(), getIndexSuperInstInfo(), souffle::RamRelationOperation::getRelation(), souffle::I_ParallelIndexAggregate, parentQueryPreamble, relations, relId, souffle::RamVisitor< std::unique_ptr< InterpreterNode > >::visit(), and visitTupleOperation().
{
         InterpreterSuperInstruction indexOperation = getIndexSuperInstInfo(aggregate);
         size_t relId = encodeRelation(aggregate.getRelation());
         auto rel = relations[relId].get();
         auto res = std::make_unique<InterpreterParallelIndexAggregate>(I_ParallelIndexAggregate, &aggregate,
                 rel, visit(aggregate.getExpression()), visit(aggregate.getCondition()),
                 visitTupleOperation(aggregate), encodeView(&aggregate), std::move(indexOperation));
         res->setPreamble(parentQueryPreamble);
         return res;
     }
visitParallelIndexChoice()
NodePtr souffle::NodeGenerator::visitParallelIndexChoice (const RamParallelIndexChoice & ichoice) inline override
Definition at line 258 of file InterpreterGenerator.h.
References encodeIndexPos(), encodeRelation(), getIndexSuperInstInfo(), souffle::RamRelationOperation::getRelation(), souffle::I_ParallelIndexChoice, parentQueryPreamble, relations, relId, and souffle::RamVisitor< std::unique_ptr< InterpreterNode > >::visit().
{
         InterpreterSuperInstruction indexOperation = getIndexSuperInstInfo(ichoice);
         size_t relId = encodeRelation(ichoice.getRelation());
         auto rel = relations[relId].get();
         auto res = std::make_unique<InterpreterParallelIndexChoice>(I_ParallelIndexChoice, &ichoice, rel,
                 visit(ichoice.getCondition()), visit(ichoice.getOperation()), encodeIndexPos(ichoice),
                 std::move(indexOperation));
         res->setPreamble(parentQueryPreamble);
         return res;
     }
visitParallelIndexScan()
NodePtr souffle::NodeGenerator::visitParallelIndexScan (const RamParallelIndexScan & piscan) inline override
Definition at line 225 of file InterpreterGenerator.h.
References encodeIndexPos(), encodeRelation(), getIndexSuperInstInfo(), souffle::RamRelationOperation::getRelation(), souffle::I_ParallelIndexScan, parentQueryPreamble, relations, relId, and visitTupleOperation().
{
         size_t relId = encodeRelation(piscan.getRelation());
         auto rel = relations[relId].get();
         InterpreterSuperInstruction indexOperation = getIndexSuperInstInfo(piscan);
         auto res = std::make_unique<InterpreterParallelIndexScan>(I_ParallelIndexScan, &piscan, rel,
                 visitTupleOperation(piscan), encodeIndexPos(piscan), std::move(indexOperation));
         res->setPreamble(parentQueryPreamble);
         return res;
     }
visitParallelScan()
NodePtr souffle::NodeGenerator::visitParallelScan (const RamParallelScan & pScan) inline override
Definition at line 208 of file InterpreterGenerator.h.
References encodeRelation(), souffle::RamRelationOperation::getRelation(), souffle::I_ParallelScan, parentQueryPreamble, relations, relId, and visitTupleOperation().
{
         size_t relId = encodeRelation(pScan.getRelation());
         auto rel = relations[relId].get();
         auto res = std::make_unique<InterpreterParallelScan>(
                 I_ParallelScan, &pScan, rel, visitTupleOperation(pScan));
         res->setPreamble(parentQueryPreamble);
         return res;
     }
visitProject()
NodePtr souffle::NodeGenerator::visitProject (const RamProject & project) inline override
Definition at line 322 of file InterpreterGenerator.h.
References encodeRelation(), getProjectSuperInstInfo(), souffle::RamProject::getRelation(), souffle::I_Project, relations, and relId.
{
         InterpreterSuperInstruction superOp = getProjectSuperInstInfo(project);
         size_t relId = encodeRelation(project.getRelation());
         auto rel = relations[relId].get();
         return std::make_unique<InterpreterProject>(I_Project, &project, rel, std::move(superOp));
     }
visitProvenanceExistenceCheck()
NodePtr souffle::NodeGenerator::visitProvenanceExistenceCheck (const RamProvenanceExistenceCheck & provExists) inline override
Definition at line 178 of file InterpreterGenerator.h.
References encodeView(), getExistenceSuperInstInfo(), souffle::I_ProvenanceExistenceCheck, and souffle::RamVisitor< std::unique_ptr< InterpreterNode > >::visit().
{
         InterpreterSuperInstruction superOp = getExistenceSuperInstInfo(provExists);
         return std::make_unique<InterpreterProvenanceExistenceCheck>(I_ProvenanceExistenceCheck, &provExists,
                 visit(provExists.getChildNodes().back()), encodeView(&provExists), std::move(superOp));
     }
visitQuery()
NodePtr souffle::NodeGenerator::visitQuery (const RamQuery & query) inline override
Definition at line 413 of file InterpreterGenerator.h.
References encodeRelation(), encodeView(), souffle::filter(), souffle::RamQuery::getOperation(), getRelationRefForView(), souffle::I_Query, indexTable, parentQueryPreamble, requireView(), toConjunctionList(), souffle::RamVisitor< std::unique_ptr< InterpreterNode > >::visit(), and souffle::visitDepthFirst().
{
         std::shared_ptr<InterpreterPreamble> preamble = std::make_shared<InterpreterPreamble>();
         parentQueryPreamble = preamble;
         // split terms of conditions of outer-most filter operation
         // into terms that require a context and terms that
         // do not require a view
         const RamOperation* next = &query.getOperation();
         std::vector<const RamCondition*> freeOfView;
         if (const auto* filter = dynamic_cast<const RamFilter*>(&query.getOperation())) {
             next = &filter->getOperation();
             // Check terms of outer filter operation whether they can be pushed before
             // the view-generation for speed improvements
             auto conditions = toConjunctionList(&filter->getCondition());
             for (auto const& cur : conditions) {
                 bool needView = false;
                 visitDepthFirst(*cur, [&](const RamNode& node) {
                     if (requireView(&node)) {
                         needView = true;
                         const auto& rel = getRelationRefForView(&node);
                         preamble->addViewInfoForFilter(
                                 encodeRelation(rel), indexTable[&node], encodeView(&node));
                     }
                 });
                 if (needView) {
                     preamble->addViewOperationForFilter(visit(*cur));
                 } else {
                     preamble->addViewFreeOperationForFilter(visit(*cur));
                 }
             }
         }
         visitDepthFirst(*next, [&](const RamNode& node) {
             if (requireView(&node)) {
                 const auto& rel = getRelationRefForView(&node);
                 preamble->addViewInfoForNested(encodeRelation(rel), indexTable[&node], encodeView(&node));
             };
         });
         visitDepthFirst(*next, [&](const RamAbstractParallel&) { preamble->isParallel = true; });
         NodePtrVec children;
         children.push_back(visit(*next));
         auto res = std::make_unique<InterpreterQuery>(I_Query, &query, visit(*next));
         res->setPreamble(parentQueryPreamble);
         return res;
     }
visitScan()
NodePtr souffle::NodeGenerator::visitScan (const RamScan & scan) inline override
Definition at line 202 of file InterpreterGenerator.h.
References encodeRelation(), souffle::RamRelationOperation::getRelation(), souffle::I_Scan, relations, relId, and visitTupleOperation().
{
         size_t relId = encodeRelation(scan.getRelation());
         auto rel = relations[relId].get();
         return std::make_unique<InterpreterScan>(I_Scan, &scan, rel, visitTupleOperation(scan));
     }
visitSequence()
NodePtr souffle::NodeGenerator::visitSequence (const RamSequence & seq) inline override
Definition at line 338 of file InterpreterGenerator.h.
References souffle::RamListStatement::getStatements(), souffle::I_Sequence, and souffle::RamVisitor< std::unique_ptr< InterpreterNode > >::visit().
{
         NodePtrVec children;
         for (const auto& value : seq.getStatements()) {
             children.push_back(visit(value));
         }
         return std::make_unique<InterpreterSequence>(I_Sequence, &seq, std::move(children));
     }
visitSubroutineArgument()
NodePtr souffle::NodeGenerator::visitSubroutineArgument (const RamSubroutineArgument & arg) inline override
Definition at line 137 of file InterpreterGenerator.h.
References souffle::I_SubroutineArgument.
{
         return std::make_unique<InterpreterSubroutineArgument>(I_SubroutineArgument, &arg);
     }
visitSubroutineReturn()
NodePtr souffle::NodeGenerator::visitSubroutineReturn (const RamSubroutineReturn & ret) inline override
Definition at line 330 of file InterpreterGenerator.h.
References souffle::RamSubroutineReturn::getValues(), souffle::I_SubroutineReturn, and souffle::RamVisitor< std::unique_ptr< InterpreterNode > >::visit().
{
         NodePtrVec children;
         for (const auto& value : ret.getValues()) {
             children.push_back(visit(value));
         }
         return std::make_unique<InterpreterSubroutineReturn>(I_SubroutineReturn, &ret, std::move(children));
     }
visitSwap()
NodePtr souffle::NodeGenerator::visitSwap (const RamSwap & swap) inline override
Definition at line 468 of file InterpreterGenerator.h.
References encodeRelation(), souffle::RamBinRelationStatement::getFirstRelation(), souffle::RamBinRelationStatement::getSecondRelation(), and souffle::I_Swap.
{
         size_t src = encodeRelation(swap.getFirstRelation());
         size_t target = encodeRelation(swap.getSecondRelation());
         return std::make_unique<InterpreterSwap>(I_Swap, &swap, src, target);
     }
visitTrue()
NodePtr souffle::NodeGenerator::visitTrue (const RamTrue & ltrue) inline override
Definition at line 142 of file InterpreterGenerator.h.
References souffle::I_True.
{
         return std::make_unique<InterpreterTrue>(I_True, &ltrue);
     }
visitTupleElement()
NodePtr souffle::NodeGenerator::visitTupleElement (const RamTupleElement & access) inline override
Definition at line 94 of file InterpreterGenerator.h.
References souffle::I_TupleElement.
{
         return std::make_unique<InterpreterTupleElement>(I_TupleElement, &access);
     }
visitTupleOperation()
NodePtr souffle::NodeGenerator::visitTupleOperation (const RamTupleOperation & search) inline override
Definition at line 194 of file InterpreterGenerator.h.
References souffle::RamNestedOperation::getOperation(), souffle::I_TupleOperation, profileEnabled, and souffle::RamVisitor< std::unique_ptr< InterpreterNode > >::visit().
Referenced by visitAggregate(), visitChoice(), visitIndexAggregate(), visitIndexChoice(), visitIndexScan(), visitNestedIntrinsicOperator(), visitParallelAggregate(), visitParallelChoice(), visitParallelIndexAggregate(), visitParallelIndexScan(), visitParallelScan(), visitScan(), and visitUnpackRecord().
{
         if (profileEnabled) {
             return std::make_unique<InterpreterTupleOperation>(
                     I_TupleOperation, &search, visit(search.getOperation()));
         }
         return visit(search.getOperation());
     }
visitUndefValue()
NodePtr souffle::NodeGenerator::visitUndefValue (const RamUndefValue &) inline override
Definition at line 474 of file InterpreterGenerator.h.
{
         return nullptr;
     }
visitUnpackRecord()
NodePtr souffle::NodeGenerator::visitUnpackRecord (const RamUnpackRecord & lookup) inline override
Definition at line 269 of file InterpreterGenerator.h.
References souffle::I_UnpackRecord, souffle::RamVisitor< std::unique_ptr< InterpreterNode > >::visit(), and visitTupleOperation().
                                                                       {  // get reference
         return std::make_unique<InterpreterUnpackRecord>(
                 I_UnpackRecord, &lookup, visit(lookup.getExpression()), visitTupleOperation(lookup));
     }
visitUserDefinedOperator()
NodePtr souffle::NodeGenerator::visitUserDefinedOperator (const RamUserDefinedOperator & op) inline override
Definition at line 110 of file InterpreterGenerator.h.
References souffle::RamAbstractOperator::getArguments(), souffle::I_UserDefinedOperator, and souffle::RamVisitor< std::unique_ptr< InterpreterNode > >::visit().
{
         NodePtrVec children;
         for (const auto& arg : op.getArguments()) {
             children.push_back(visit(arg));
         }
         return std::make_unique<InterpreterUserDefinedOperator>(
                 I_UserDefinedOperator, &op, std::move(children));
     }
Field Documentation
indexTable
std::unordered_map<const RamNode*, size_t> souffle::NodeGenerator::indexTable private
Environment encoding, store a mapping from RamNode to its operation index id.
Definition at line 495 of file InterpreterGenerator.h.
Referenced by visitQuery().
isa
RamIndexAnalysis* souffle::NodeGenerator::isa private
Used by index encoding.
Definition at line 497 of file InterpreterGenerator.h.
isProvenance
const bool souffle::NodeGenerator::isProvenance private
If generating a provenance program.
Definition at line 512 of file InterpreterGenerator.h.
parentQueryPreamble
std::shared_ptr<InterpreterPreamble> souffle::NodeGenerator::parentQueryPreamble = nullptr private
Points to the current preamble during the generation.
It is used to passing preamble between parent query and its nested parallel operation.
Definition at line 500 of file InterpreterGenerator.h.
Referenced by visitParallelAggregate(), visitParallelChoice(), visitParallelIndexAggregate(), visitParallelIndexChoice(), visitParallelIndexScan(), visitParallelScan(), and visitQuery().
profileEnabled
const bool souffle::NodeGenerator::profileEnabled private
If profile is enable in this program.
Definition at line 514 of file InterpreterGenerator.h.
Referenced by visitTupleOperation().
program
RamProgram* souffle::NodeGenerator::program private
RamProgram.
Definition at line 516 of file InterpreterGenerator.h.
Referenced by generateTree(), and visitCall().
relations
std::vector<std::unique_ptr<RelationHandle> > souffle::NodeGenerator::relations private
Symbol table for relations.
Definition at line 510 of file InterpreterGenerator.h.
Referenced by getRelationHandle(), getRelations(), visitAggregate(), visitChoice(), visitClear(), visitEmptinessCheck(), visitIndexAggregate(), visitIO(), visitLogRelationTimer(), visitLogSize(), visitParallelAggregate(), visitParallelChoice(), visitParallelIndexAggregate(), visitParallelIndexChoice(), visitParallelIndexScan(), visitParallelScan(), visitProject(), and visitScan().
relId
size_t souffle::NodeGenerator::relId = 0 private
Next available location to encode a relation.
Definition at line 504 of file InterpreterGenerator.h.
Referenced by visitAggregate(), visitChoice(), visitClear(), visitEmptinessCheck(), visitIndexAggregate(), visitIO(), visitLogRelationTimer(), visitLogSize(), visitParallelAggregate(), visitParallelChoice(), visitParallelIndexAggregate(), visitParallelIndexChoice(), visitParallelIndexScan(), visitParallelScan(), visitProject(), and visitScan().
relTable
std::unordered_map<const RamRelation*, size_t> souffle::NodeGenerator::relTable private
Environment encoding, store a mapping from RamRelation to its id.
Definition at line 508 of file InterpreterGenerator.h.
viewId
size_t souffle::NodeGenerator::viewId = 0 private
Next available location to encode View.
Definition at line 502 of file InterpreterGenerator.h.
viewTable
std::unordered_map<const RamNode*, size_t> souffle::NodeGenerator::viewTable private
Environment encoding, store a mapping from RamNode to its View id.
Definition at line 506 of file InterpreterGenerator.h.
The documentation for this class was generated from the following file:
interpreter/InterpreterGenerator.h