souffle: souffle::ReorderFilterBreak Class Reference
souffle::ReorderFilterBreak Class Reference
#include <ReorderFilterBreak.h>
Public Member Functions
std::string getName () const override
get name of the transformer
bool reorderFilterBreak (RamProgram &program)
reorder filter-break nesting to break-filter nesting
Public Member Functions inherited from souffle::RamTransformer
bool apply (RamTranslationUnit &translationUnit)
apply the transformer to a translation unit translationUnit that will be transformed.
virtual ~RamTransformer ()=default
Protected Member Functions
bool transform (RamTranslationUnit &translationUnit) override
transform the translation unit / used by apply translationUnit that will be transformed.
Detailed Description
Definition at line 50 of file ReorderFilterBreak.h.
Member Function Documentation
getName()
std::string souffle::ReorderFilterBreak::getName () const inline override virtual
get name of the transformer
Implements souffle::RamTransformer.
Definition at line 52 of file ReorderFilterBreak.h.
References reorderFilterBreak().
{
         return "ReorderFilterBreak";
     }
reorderFilterBreak()
bool souffle::ReorderFilterBreak::reorderFilterBreak (RamProgram & program)
reorder filter-break nesting to break-filter nesting
Parameters
program Program that is transform
Returns
Flag showing whether the program has been changed by the transformation
Definition at line 29 of file ReorderFilterBreak.cpp.
References souffle::RamTransformer::apply(), souffle::RamProgram::apply(), souffle::clone(), souffle::filter(), souffle::makeLambdaRamMapper(), and souffle::visitDepthFirst().
Referenced by getName(), and transform().
{
     bool changed = false;
     visitDepthFirst(program, [&](const RamQuery& query) {
         std::function<std::unique_ptr<RamNode>(std::unique_ptr<RamNode>)> filterRewriter =
                 [&](std::unique_ptr<RamNode> node) -> std::unique_ptr<RamNode> {
             // find filter-break nesting
             if (const RamFilter* filter = dynamic_cast<RamFilter*>(node.get())) {
                 if (const RamBreak* br = dynamic_cast<RamBreak*>(&filter->getOperation())) {
                     changed = true;
                     // convert to break-filter nesting
                     node = std::make_unique<RamBreak>(souffle::clone(&br->getCondition()),
                             std::make_unique<RamFilter>(souffle::clone(&filter->getCondition()),
                                     souffle::clone(&br->getOperation())));
                 }
             }
             node->apply(makeLambdaRamMapper(filterRewriter));
             return node;
         };
         const_cast<RamQuery*>(&query)->apply(makeLambdaRamMapper(filterRewriter));
     });
     return changed;
 }
transform()
bool souffle::ReorderFilterBreak::transform (RamTranslationUnit & translationUnit) inline override protected virtual
transform the translation unit / used by apply translationUnit that will be transformed.
flag reporting whether the RAM program has changed
Implements souffle::RamTransformer.
Definition at line 64 of file ReorderFilterBreak.h.
References souffle::RamTranslationUnit::getProgram(), and reorderFilterBreak().
{
         return reorderFilterBreak(translationUnit.getProgram());
     }
The documentation for this class was generated from the following files:
ram/transform/ReorderFilterBreak.h
ram/transform/ReorderFilterBreak.cpp