souffle: souffle::test Namespace Reference
souffle::test Namespace Reference
Data Structures
struct reserver
struct reserver< std::unordered_set< A, B, C, D > >
Typedefs
using Entry = std::tuple< int, int >
using EqRel = souffle::EquivalenceRelation< Tuple< RamDomain, 2 > >
typedef souffle::LambdaBTreeSet< TestPair, std::function< TestPair::second_type(TestPair &)>, souffle::EqrelMapComparator< TestPair > > TestLambdaTree
typedef std::pair< size_t, size_t > TestPair
using time_point = std::chrono::high_resolution_clock::time_point
Functions
template<typename C >
int count (const C &c)
long duration (const time_point &start, const time_point &end)
RamDomain evalBinary (FunctorOp functor, RamDomain arg1, RamDomain arg2)
Evaluate a binary operator.
RamDomain evalExpression (std::unique_ptr< RamExpression > expression, SymbolTable &symTab)
Function to evaluate a single RamExpression.
RamDomain evalExpression (std::unique_ptr< RamExpression > expression)
Function to evaluate a single RamExpression.
RamDomain evalMultiArg (FunctorOp functor, std::vector< std::unique_ptr< RamExpression >> args, SymbolTable &symTab)
RamDomain evalMultiArg (FunctorOp functor, std::vector< std::unique_ptr< RamExpression >> args)
RamDomain evalUnary (FunctorOp functor, RamDomain arg1)
Evaluate a single argument expression.
std::vector< Entry > getData (unsigned numEntries)
bool isNotSubtypeOf (const Type &a, const Type &b)
std::unique_ptr< AstTranslationUnit > makeATU (std::string program=".decl A,B,C(x:number)")
std::unique_ptr< AstClause > makeClause (std::string name, std::unique_ptr< AstArgument > headArgument)
std::unique_ptr< AstClause > makeClauseA (std::unique_ptr< AstArgument > headArgument)
std::unique_ptr< AstTranslationUnit > makePrintedATU (std::unique_ptr< AstTranslationUnit > &tu)
time_point now ()
TEST (ParallelUtils, SpinLock)
TEST (RamRelation, CloneAndEquals)
TEST (randomConversions, RamSigned)
TEST (TypeSystem, Basic)
TEST (SymbolTable, Basics)
TEST (Graph, Basic)
TEST (Relation0, Construction)
TEST (RamIntrinsicOperator, CloneAndEquals)
TEST (Constraints, Basic)
TEST (RamTrue, CloneAndEquals)
TEST (RamScan, CloneAndEquals)
TEST (RuleBody, Basic)
TEST (Pack, Tuple)
TEST (Table, Basic)
TEST (RamIO1, CloneAndEquals)
TEST (RamRelationRepresentation, CloneAndEquals)
TEST (AstTransformers, GroundTermPropagation)
TEST (EqRelTest, Scoping)
TEST (randomConversions, RamUnsigned)
TEST (RandomInsertPiggyTest, Scoping)
Piggy List that allows creation at arbitrary elements.
TEST (ParallelUtils, ReadWriteLock)
TEST (SymbolTable, Copy)
TEST (RamFalse, CloneAndEquals)
TEST (TypeSystem, isNumberType)
TEST (Relation1, Construction)
TEST (EqRelTest, Basic)
TEST (RuleBody, Negation)
TEST (RandomInsertPiggyTest, Insertion)
TEST (AstUtils, Grounded)
TEST (Table, Stress)
TEST (PackUnpack, Tuple)
TEST (RamClear, CloneAndEquals)
TEST (RamParallelScan, CloneAndEquals)
TEST (BTreeMultiSet, Basic)
TEST (AstProgram, Parse)
TEST (RamConjunction, CloneAndEquals)
TEST (randomConversions, RamFloat)
TEST (BTreeSet, Basic)
TEST (AstPrint, NilConstant)
TEST (RandomInsertPiggyTest, DoubleClear)
TEST (RamUserDefinedOperator, CloneAndEquals)
TEST (Basic, Iteration)
TEST (ParallelUtils, OptimisticReadWriteLock)
TEST (RamExtend, CloneAndEquals)
TEST (AstPrint, NumberConstant)
TEST (SymbolTable, Assign)
TEST (AstTransformers, GroundTermPropagation2)
TEST (EqRelTest, Clear)
TEST (AstPrint, StringConstant)
TEST (RamIndexScan, CloneAndEquals)
TEST (RuleBody, ClauseBodyExtraction)
TEST (RamSwap, CloneAndEquals)
TEST (TypeSystem, isSubtypeOf_Basic)
TEST (PackUnpack, Vector)
TEST (RamTupleElement, CloneAndEquals)
TEST (AstPrint, Variable)
TEST (Independence, Iteration)
TEST (SymbolTable, Inserts)
TEST (RamNegation, CloneAndEquals)
TEST (AstTransformers, ResolveGroundedAliases)
TEST (EqRelTest, Duplicates)
TEST (RamQuery, CloneAndEquals)
TEST (AstUtils, GroundedRecords)
TEST (PiggyTest, Scoping)
Regular Old Piggy List.
TEST (AstPrint, UnnamedVariable)
TEST (IO_store, FloatSimple)
TEST (RamSignedConstant, CloneAndEquals)
TEST (PiggyTest, Append)
TEST (AstPrint, Counter)
TEST (RamSignedConstant, ArithmeticEvaluation)
TEST (RamConstraint, CloneAndEquals)
TEST (RamAutoIncrement, CloneAndEquals)
TEST (AstPrint, AggregatorMin)
TEST (Unary, Neg)
TEST (IO_store, Signed)
TEST (AstTransformers, ResolveAliasesWithTermsInAtoms)
TEST (RamParallelIndexScan, CloneAndEquals)
TEST (EqRelTest, TransitivityTest)
TEST (IndependentMoving, Iteration)
TEST (AstProgram, RemoveClause)
test removeClause, addRelation and removeRelation
TEST (Unary, FloatNeg)
TEST (RamUndefValue, CloneAndEquals)
TEST (PiggyTest, ElementCreation)
TEST (Unary, BinaryNot)
TEST (TypeSystem, isSubtypeOf_Records)
TEST (AstPrint, AggregatorMax)
TEST (AstUtils, ReorderClauseAtoms)
TEST (PiggyTest, Iteration)
TEST (AstProgram, AppendAstRelation)
TEST (RamPackRecord, CloneAndEquals)
TEST (Unary, UnsignedBinaryNot)
TEST (EqRelTest, PairwiseIncremental)
TEST (IndependentCopying, Iteration)
TEST (PiggyTest, CopyCtor)
TEST (Unary, LogicalNeg)
TEST (AstProgram, RemoveAstRelation)
TEST (RamExistenceCheck, CloneAndEquals)
TEST (AstPrint, AggregatorCount)
TEST (TypeSystem, GreatestCommonSubtype)
TEST (IO_store, Float)
TEST (BTreeMultiSet, Duplicates)
TEST (Unary, UnsignedLogicalNeg)
TEST (AstTransformers, RemoveRelationCopies)
Test that copies of relations are removed by RemoveRelationCopiesTransformer.
TEST (RamChoice, CloneAndEquals)
TEST (RamSequence, CloneAndEquals)
TEST (AstPrint, AggregatorSum)
TEST (Unary, SingedTpUnsigned)
TEST (EqRelTest, PairwiseDecremental)
TEST (BTreeSet, Duplicates)
TEST (BTreeMultiSet, Incremental)
TEST (Unary, UnsignedToSigned)
TEST (BTreeMultiSet, Decremental)
TEST (Unary, SignedToFloat)
TEST (BTreeSet, Incremental)
TEST (EqRelTest, Shuffled)
TEST (RamSubrountineArgument, CloneAndEquals)
TEST (IO_store, Unsigned)
TEST (RamProvenanceExistCheck, CloneAndEquals)
TEST (Unary, FloatToSigned)
TEST (BTreeMultiSet, Shuffled)
TEST (PiggyTest, DoubleClear)
TEST (AstTransformers, RemoveRelationCopiesOutput)
Test that copies of relations are removed by RemoveRelationCopiesTransformer.
TEST (Unary, UnsignedToFloat)
TEST (RamParallelChoice, CloneAndEquals)
TEST (RamParallel, CloneAndEquals)
TEST (Unary, FloatToUnsigned)
TEST (BTreeSet, Decremental)
TEST (BTreeMultiSet, IteratorEmpty)
TEST (Binary, SignedAdd)
TEST (EqRelTest, Extend)
TEST (BTreeMultiSet, IteratorBasic)
TEST (TypeSystem, complexSubsetTypes)
TEST (IO_store, SignedChangedDelimiter)
TEST (Binary, UnsignedAdd)
TEST (BTreeSet, Shuffled)
TEST (AstTransformers, CheckClausalEquivalence)
Test the equivalence (or lack of equivalence) of clauses using the MinimiseProgramTransfomer.
TEST (RamEmptinessCheck, CloneAndEquals)
TEST (TypeSystem, RecordSubsets)
TEST (RamIndexChoice, CloneAndEquals)
TEST (Binary, FloatAdd)
TEST (BTreeMultiSet, IteratorStress)
TEST (TypeSystem, EquivTypes)
TEST (RamLoop, CloneAndEquals)
TEST (DjTest, Scoping)
The underlying Disjoint Set (essentially Anderson '91 Find-Union, but dynamic)
TEST (BTreeSet, Copy)
TEST (Binary, SignedSub)
TEST (DjTest, MakeNode)
TEST (Binary, UnsignedSub)
TEST (BTreeMultiSet, BoundaryTest)
TEST (DjTest, TestUnion)
TEST (EqRelTest, Merge)
TEST (RamiParallelIndexChoice, CloneAndEquals)
TEST (Binary, FloatSub)
TEST (RamExit, CloneAndEquals)
TEST (Binary, SignedMul)
TEST (IO_store, MixedTypes)
TEST (DjTest, Clear)
TEST (BTreeSet, Merge)
TEST (RamLogRelationTimer, CloneAndEquals)
TEST (Binary, UnsignedMul)
TEST (BTreeMultiSet, BoundaryEmpty)
TEST (AstTransformers, RemoveClauseRedundancies)
Test the removal of redundancies within clauses using the MinimiseProgramTransformer.
TEST (Binary, FloatMul)
TEST (RamAggregate, CloneAndEquals)
TEST (BTreeSet, IteratorEmpty)
TEST (RamLogTimer, CloneAndEquals)
TEST (BTreeSet, IteratorBasic)
TEST (BTreeMultiSet, Load)
TEST (Binary, SignedDiv)
TEST (EqRelTest, IterEmpty)
TEST (RamIndexAggregate, CloneAndEquals)
TEST (SparseDjTest, Scoping)
The SparseDisjointSet that is used by the EquivalenceRelation.
TEST (EqRelTest, IterBasic)
TEST (RamDebugInfo, CloneAndEquals)
TEST (Binary, UnsignedDiv)
TEST (SparseDjTest, MakeNode)
TEST (BTreeMultiSet, Clear)
TEST (BTreeSet, IteratorStress)
TEST (Binary, FloatDiv)
TEST (SparseDjTest, TestUnion)
TEST (EqRelTest, IterRange)
TEST (IO_load, Signed)
TEST (Binary, SignedExp)
TEST (RamUnpackedRecord, CloneAndEquals)
TEST (BTreeSet, BoundaryTest)
TEST (SparseDjTest, SignedData)
TEST (Binary, UnsignedExp)
TEST (Binary, FloatExp)
TEST (RamFilter, CloneAndEquals)
TEST (RamLogSize, CloneAndEquals)
TEST (BTreeSet, BoundaryEmpty)
TEST (Binary, SignedMod)
TEST (IO_load, Float)
TEST (Binary, UnsignedMod)
TEST (RamBreak, CloneAndEquals)
TEST (BTreeSet, Load)
TEST (Binary, SignedBinaryAnd)
TEST (Binary, UnsignedBinaryAnd)
TEST (RamProject, CloneAndEquals)
TEST (EqRelTest, IterPartition)
TEST (BTreeSet, Clear)
TEST (Performance, Basic)
TEST (Binary, SignedBinaryOr)
TEST (RamSubroutineReturn, CloneAndEquals)
TEST (BTreeSet, ChunkSplit)
TEST (LambdaBTreeTest, Scoping)
The LambdaBTree - essentially a ripoff to the Btree, but allows a function to be called on successful insert.
TEST (Binary, UnsignedBinaryOr)
TEST (LambdaBTreeTest, Insert)
TEST (IO_load, Unsigned)
TEST (Performance, Load)
TEST (Binary, SignedBinaryXor)
TEST (EqRelTest, Scaling)
TEST (Binary, UnsignedBinaryXor)
TEST (BTreeSet, ChunkSplitStress)
TEST (Binary, SignedLogicalAnd)
TEST (Binary, UnsignedLogicalAnd)
TEST (Binary, SignedLogicalOr)
TEST (IO_load, MixedTypesLoad)
TEST (Binary, UnsignedLogicalOr)
TEST (MultiArg, Max)
TEST (MultiArg, UnsignedMax)
TEST (MultiArg, FloatMax)
TEST (MultiArg, SymbolMax)
TEST (MultiArg, Min)
TEST (MultiArg, UnsignedMin)
TEST (MultiArg, FloatMin)
TEST (MultiArg, SymbolMin)
TEST (BTreeSet, Parallel)
TESTASTCLONEANDEQUAL (Program, R"(.decl r(a:number,b:number,c:number,d:number) .decl s(x:symbol) .decl a(x:number) s("xxx"). r(X,Y,Z,W) :- a(X), 10 = Y, Y = Z, 8 + W = 12 + 14. r(z + 2, x, y, a) :- s(b), b = to_string(a), z = x, a = y, x = 2, a = 2 + x.)")
TESTASTCLONEANDEQUAL (Record, R"(.type N <: symbol .type R = [ a : N, B : N ] .decl r (r : R) .decl s (r : N) s(x) :- r([x,y]).)")
TESTASTCLONEANDEQUAL (SimpleTypes, R"(.type A <: symbol .type B <: symbol .type U = A | B .decl a (x : A) .decl b (x : B) .decl u (x : U) a(X) :- u(X). b(X) :- u(X). u(X) :- u(X). a(X) :- b(X). a(X) :- b(Y).)")
TESTASTCLONEANDEQUAL (ComplexTypes, R"(.type A <: symbol .type B <: number .type U = B .decl a (x : A) .decl b (x : B) .decl u (x : U) a(X) :- X < 10. b(X) :- X < 10. u(X) :- X < 10.)")
TESTASTCLONEANDEQUAL (ChainedTypes, R"(.type D <: symbol .type C = D .type B = C .type A = B .decl R1(x:A,y:B) .decl R2(x:C,y:D) .decl R4(x:A) output R4(x) :- R2(x,x),R1(x,x).)")
TESTASTCLONEANDEQUAL (NestedAggregates, R"(.type D <: symbol .decl r(x:D) r(x) :- r(y), x=cat(cat(x,x),x).)")
TESTASTCLONEANDEQUAL (RelationCopies, R"(.type D = number .decl a(a:D,b:D) .decl b(a:D,b:D) .decl c(a:D,b:D) .decl d(a:D,b:D) a(1,2). b(x,y) :- a(x,y). c(x,y) :- b(x,y). d(x,y) :- b(x,y), c(y,x).)")
const std::string testInterpreterStore (std::vector< std::string > attribs, std::vector< std::string > attribsTypes, std::vector< std::unique_ptr< RamExpression >> exprs)
template<typename Op >
long time (const std::string &name, const Op &operation)
Typedef Documentation
Entry
typedef std::tuple< int, int > souffle::test::Entry
Definition at line 385 of file btree_multiset_test.cpp.
EqRel
using souffle::test::EqRel = typedef souffle::EquivalenceRelation<Tuple<RamDomain, 2> >
Definition at line 45 of file binary_relation_test.cpp.
TestLambdaTree
typedef souffle::LambdaBTreeSet<TestPair, std::function<TestPair::second_type(TestPair&)>, souffle::EqrelMapComparator<TestPair> > souffle::test::TestLambdaTree
Definition at line 500 of file eqrel_datastructure_test.cpp.
TestPair
typedef std::pair<size_t, size_t> souffle::test::TestPair
Definition at line 497 of file eqrel_datastructure_test.cpp.
time_point
typedef std::chrono::high_resolution_clock::time_point souffle::test::time_point
Definition at line 400 of file btree_multiset_test.cpp.
Function Documentation
count()
template<typename C > int souffle::test::count (const C & c)
Definition at line 28 of file table_test.cpp.
Referenced by souffle::RamTransformer::apply(), souffle::MetaTransformer::applySubtransformer(), souffle::ReadStreamSQLite::checkTableExists(), duration(), souffle::duration_in_ns(), souffle::duration_in_us(), souffle::DebugReportSection::generateUniqueID(), genJsonAtoms(), souffle::profile::Tui::genJsonTop(), souffle::detail::binary_search::lower_bound(), souffle::main(), souffle::MaterializeAggregationQueriesTransformer::materializeAggregationQueries(), souffle::numBoundArguments(), souffle::detail::binary_search::operator()(), TEST(), souffle::TEST(), souffle::RemoveRedundantSumsTransformer::transform(), souffle::DebugReporter::transform(), souffle::AstToRamTranslator::translateUnit(), and souffle::detail::binary_search::upper_bound().
                       {
     int res = 0;
     for (auto it = c.begin(); it != c.end(); ++it) {
         res++;
     }
     return res;
 }
duration()
long souffle::test::duration (const time_point & start, const time_point & end)
Definition at line 406 of file btree_multiset_test.cpp.
References count().
Referenced by souffle::ExplainProvenanceImpl::measureRelation(), TEST(), and time().
{
     return std::chrono::duration_cast<std::chrono::milliseconds>(end - start).count();
 }
evalBinary()
RamDomain souffle::test::evalBinary (FunctorOp functor, RamDomain arg1, RamDomain arg2)
Evaluate a binary operator.
Definition at line 103 of file ram_arithmetic_test.cpp.
References evalMultiArg().
Referenced by TEST().
{
     std::vector<std::unique_ptr<RamExpression>> args;
     args.push_back(std::make_unique<RamSignedConstant>(arg1));
     args.push_back(std::make_unique<RamSignedConstant>(arg2));
     return evalMultiArg(functor, std::move(args));
 }
evalExpression() [1/2]
RamDomain souffle::test::evalExpression (std::unique_ptr< RamExpression > expression, SymbolTable & symTab)
Function to evaluate a single RamExpression.
Definition at line 47 of file ram_arithmetic_test.cpp.
References souffle::Global::config().
Referenced by evalExpression(), evalMultiArg(), and TEST().
{
     // Set up RamProgram and translation unit
     std::vector<std::unique_ptr<RamExpression>> returnValues;
     returnValues.emplace_back(std::move(expression));
     Global::config().set("jobs", "1");
     std::unique_ptr<RamStatement> query =
             std::make_unique<RamQuery>(std::make_unique<RamSubroutineReturn>(std::move(returnValues)));
     std::map<std::string, std::unique_ptr<RamStatement>> subs;
     subs.insert(std::make_pair("test", std::move(query)));
     std::vector<std::unique_ptr<RamRelation>> rels;
     std::unique_ptr<RamProgram> prog =
             std::make_unique<RamProgram>(std::move(rels), std::make_unique<RamSequence>(), std::move(subs));
     ErrorReport errReport;
     DebugReport debugReport;
     RamTranslationUnit translationUnit(std::move(prog), symTab, errReport, debugReport);
     // configure and execute interpreter
     std::unique_ptr<InterpreterEngine> interpreter = std::make_unique<InterpreterEngine>(translationUnit);
     std::string name("test");
     std::vector<RamDomain> ret;
     interpreter->executeSubroutine(name, {}, ret);
     return ret.at(0);
 }
evalExpression() [2/2]
RamDomain souffle::test::evalExpression (std::unique_ptr< RamExpression > expression)
Function to evaluate a single RamExpression.
Definition at line 79 of file ram_arithmetic_test.cpp.
References evalExpression().
{
     SymbolTable symTab;
     return evalExpression(std::move(expression), symTab);
 }
evalMultiArg() [1/2]
RamDomain souffle::test::evalMultiArg (FunctorOp functor, std::vector< std::unique_ptr< RamExpression >> args, SymbolTable & symTab)
Definition at line 84 of file ram_arithmetic_test.cpp.
References evalExpression().
Referenced by evalBinary(), evalMultiArg(), evalUnary(), and TEST().
{
     return evalExpression(std::make_unique<RamIntrinsicOperator>(functor, std::move(args)), symTab);
 }
evalMultiArg() [2/2]
RamDomain souffle::test::evalMultiArg (FunctorOp functor, std::vector< std::unique_ptr< RamExpression >> args)
Definition at line 89 of file ram_arithmetic_test.cpp.
References evalMultiArg().
{
     SymbolTable symTab;
     return evalMultiArg(functor, std::move(args), symTab);
 }
evalUnary()
RamDomain souffle::test::evalUnary (FunctorOp functor, RamDomain arg1)
Evaluate a single argument expression.
Definition at line 95 of file ram_arithmetic_test.cpp.
References evalMultiArg().
Referenced by TEST().
{
     std::vector<std::unique_ptr<RamExpression>> args;
     args.push_back(std::make_unique<RamSignedConstant>(arg1));
     return evalMultiArg(functor, std::move(args));
 }
getData()
std::vector< Entry > souffle::test::getData (unsigned numEntries)
Definition at line 387 of file btree_multiset_test.cpp.
References i, and k.
Referenced by TEST().
{
     std::vector<Entry> res(numEntries);
     int k = 0;
     for (unsigned i = 0; i < numEntries; i++) {
         res[k++] = Entry(i / 100, i % 100);
     }
     std::random_device rd;
     std::mt19937 generator(rd());
     shuffle(res.begin(), res.end(), generator);
     return res;
 }
isNotSubtypeOf()
bool souffle::test::isNotSubtypeOf (const Type & a, const Type & b)
Definition at line 80 of file type_system_test.cpp.
References souffle::isSubtypeOf().
Referenced by TEST().
{
     return !isSubtypeOf(a, b);
 }
makeATU()
std::unique_ptr< AstTranslationUnit > souffle::test::makeATU (std::string program = ".decl A,B,C(x:number)") inline
Definition at line 40 of file ast_print_test.cpp.
References d, e, and souffle::ParserDriver::parseTranslationUnit().
Referenced by makePrintedATU(), and TEST().
                                                                                    :number)") {
     ErrorReport e;
     DebugReport d;
     return ParserDriver::parseTranslationUnit(program, e, d);
 }
makeClause()
std::unique_ptr<AstClause> souffle::test::makeClause (std::string name, std::unique_ptr< AstArgument > headArgument) inline
Definition at line 49 of file ast_program_test.cpp.
{
     auto headAtom = std::make_unique<AstAtom>(name);
     headAtom->addArgument(std::move(headArgument));
     auto clause = std::make_unique<AstClause>();
     clause->setHead(std::move(headAtom));
     return clause;
 }
makeClauseA()
std::unique_ptr<AstClause> souffle::test::makeClauseA (std::unique_ptr< AstArgument > headArgument) inline
Definition at line 52 of file ast_print_test.cpp.
Referenced by TEST().
{
     auto headAtom = std::make_unique<AstAtom>("A");
     headAtom->addArgument(std::move(headArgument));
     auto clause = std::make_unique<AstClause>();
     clause->setHead(std::move(headAtom));
     return clause;
 }
makePrintedATU()
std::unique_ptr<AstTranslationUnit> souffle::test::makePrintedATU (std::unique_ptr< AstTranslationUnit > & tu) inline
Definition at line 46 of file ast_print_test.cpp.
References makeATU(), and souffle::profile::ss.
Referenced by TEST().
{
     std::stringstream ss;
     ss << *tu->getProgram();
     return makeATU(ss.str());
 }
now()
time_point souffle::test::now ()
Definition at line 402 of file btree_multiset_test.cpp.
Referenced by souffle::RamTransformer::apply(), souffle::MetaTransformer::applySubtransformer(), souffle::main(), souffle::ExplainProvenanceImpl::measureRelation(), TEST(), time(), souffle::DebugReporter::transform(), souffle::AstToRamTranslator::translateUnit(), and souffle::profile::Tui::Tui().
                  {
     return std::chrono::high_resolution_clock::now();
 }
TEST() [1/228]
souffle::test::TEST (ParallelUtils , SpinLock)
Definition at line 26 of file parallel_utils_test.cpp.
References EXPECT_EQ, i, souffle::SpinLock::lock(), and souffle::SpinLock::unlock().
{
     const int N = 1000000;
     SpinLock lock;
     volatile int c = 0;
 #pragma omp parallel for num_threads(4)
     for (int i = 0; i < N; i++) {
         lock.lock();
         c++;
         lock.unlock();
     }
     EXPECT_EQ(N, c);
 }
TEST() [2/228]
souffle::test::TEST (RamRelation , CloneAndEquals)
Definition at line 27 of file ram_relation_equal_clone_test.cpp.
References b, souffle::RamRelation::clone(), souffle::DEFAULT, EXPECT_EQ, and EXPECT_NE.
{
     RamRelation a("A", 4, 1, {"a", "b", "c", "d"}, {"i", "i", "i", "i"}, RelationRepresentation::DEFAULT);
     RamRelation b("A", 4, 1, {"a", "b", "c", "d"}, {"i", "i", "i", "i"}, RelationRepresentation::DEFAULT);
     EXPECT_EQ(a, b);
     EXPECT_NE(&a, &b);
     RamRelation* c = a.clone();
     EXPECT_EQ(a, *c);
     EXPECT_NE(&a, c);
     delete c;
 }
TEST() [3/228]
souffle::test::TEST (randomConversions , RamSigned)
Definition at line 27 of file ram_type_conversion_test.cpp.
References EXPECT_EQ, i, NUMBER_OF_CONVERSION_TESTS, and souffle::ramBitCast().
{
     std::mt19937 randomGenerator(3);
     std::uniform_int_distribution<RamDomain> dist(-100, 100);
     for (int i = 0; i < NUMBER_OF_CONVERSION_TESTS; ++i) {
         RamDomain randomNumber = dist(randomGenerator);
         // Test float casting
         EXPECT_EQ(randomNumber, ramBitCast(ramBitCast<RamFloat>(randomNumber)));
         // Test signed casting
         EXPECT_EQ(randomNumber, ramBitCast(ramBitCast<RamUnsigned>(randomNumber)));
     }
 }
TEST() [4/228]
souffle::test::TEST (TypeSystem , Basic)
Definition at line 27 of file type_system_test.cpp.
References souffle::TypeEnvironment::createType(), EXPECT_EQ, souffle::TypeEnvironment::getType(), souffle::toString(), and souffle::toVector().
{
     TypeEnvironment env;
     const Type& A = env.createType<SubsetType>("A", env.getType("number"));
     const Type& B = env.createType<SubsetType>("B", env.getType("symbol"));
     auto& U = env.createType<UnionType>("U", toVector(&A, &B));
     auto& R = env.createType<RecordType>("R");
     R.setFields(toVector(&A, &B));
     EXPECT_EQ("A <: number", toString(A));
     EXPECT_EQ("B <: symbol", toString(B));
     EXPECT_EQ("U = A | B", toString(U));
     EXPECT_EQ("R = (A, B)", toString(R));
 }
TEST() [5/228]
souffle::test::TEST (SymbolTable , Basics)
Definition at line 29 of file symbol_table_test.cpp.
References EXPECT_EQ, EXPECT_STREQ, souffle::SymbolTable::insert(), souffle::SymbolTable::lookup(), and souffle::SymbolTable::resolve().
{
     SymbolTable table;
     table.insert("Hello");
     EXPECT_STREQ("Hello", table.resolve(table.lookup(table.resolve(table.lookup("Hello")))));
     EXPECT_EQ(table.lookup("Hello"), table.lookup(table.resolve(table.lookup("Hello"))));
     EXPECT_STREQ("Hello", table.resolve(table.lookup(table.resolve(table.lookup("Hello")))));
     EXPECT_EQ(table.lookup("Hello"),
             table.lookup(table.resolve(table.lookup(table.resolve(table.lookup("Hello"))))));
 }
TEST() [6/228]
souffle::test::TEST (Graph , Basic)
Definition at line 30 of file graph_utils_test.cpp.
References souffle::Graph< Vertex, Compare >::contains(), EXPECT_EQ, EXPECT_FALSE, EXPECT_TRUE, souffle::Graph< Vertex, Compare >::insert(), souffle::Graph< Vertex, Compare >::reaches(), and souffle::toString().
                    {
     Graph<int> g;
     EXPECT_FALSE(g.contains(1));
     EXPECT_FALSE(g.contains(2));
     EXPECT_FALSE(g.contains(3));
     EXPECT_FALSE(g.contains(1, 2));
     EXPECT_FALSE(g.contains(1, 3));
     EXPECT_FALSE(g.contains(2, 3));
     EXPECT_FALSE(g.reaches(1, 1));
     EXPECT_FALSE(g.reaches(1, 2));
     EXPECT_FALSE(g.reaches(1, 3));
     EXPECT_FALSE(g.reaches(2, 1));
     EXPECT_FALSE(g.reaches(2, 2));
     EXPECT_FALSE(g.reaches(2, 3));
     EXPECT_FALSE(g.reaches(3, 1));
     EXPECT_FALSE(g.reaches(3, 2));
     EXPECT_FALSE(g.reaches(3, 3));
     g.insert(1, 2);
     EXPECT_TRUE(g.contains(1));
     EXPECT_TRUE(g.contains(2));
     EXPECT_FALSE(g.contains(3));
     EXPECT_TRUE(g.contains(1, 2));
     EXPECT_FALSE(g.contains(1, 3));
     EXPECT_FALSE(g.contains(2, 3));
     EXPECT_FALSE(g.reaches(1, 1));
     EXPECT_TRUE(g.reaches(1, 2));
     EXPECT_FALSE(g.reaches(1, 3));
     EXPECT_FALSE(g.reaches(2, 1));
     EXPECT_FALSE(g.reaches(2, 2));
     EXPECT_FALSE(g.reaches(2, 3));
     EXPECT_FALSE(g.reaches(3, 1));
     EXPECT_FALSE(g.reaches(3, 2));
     EXPECT_FALSE(g.reaches(3, 3));
     g.insert(2, 3);
     EXPECT_TRUE(g.contains(1));
     EXPECT_TRUE(g.contains(2));
     EXPECT_TRUE(g.contains(3));
     EXPECT_TRUE(g.contains(1, 2));
     EXPECT_FALSE(g.contains(1, 3));
     EXPECT_TRUE(g.contains(2, 3));
     EXPECT_FALSE(g.reaches(1, 1));
     EXPECT_TRUE(g.reaches(1, 2));
     EXPECT_TRUE(g.reaches(1, 3));
     EXPECT_FALSE(g.reaches(2, 1));
     EXPECT_FALSE(g.reaches(2, 2));
     EXPECT_TRUE(g.reaches(2, 3));
     EXPECT_FALSE(g.reaches(3, 1));
     EXPECT_FALSE(g.reaches(3, 2));
     EXPECT_FALSE(g.reaches(3, 3));
     g.insert(3, 1);
     EXPECT_TRUE(g.contains(1));
     EXPECT_TRUE(g.contains(2));
     EXPECT_TRUE(g.contains(3));
     EXPECT_TRUE(g.contains(1, 2));
     EXPECT_FALSE(g.contains(1, 3));
     EXPECT_TRUE(g.contains(2, 3));
     EXPECT_TRUE(g.reaches(1, 1));
     EXPECT_TRUE(g.reaches(1, 2));
     EXPECT_TRUE(g.reaches(1, 3));
     EXPECT_TRUE(g.reaches(2, 1));
     EXPECT_TRUE(g.reaches(2, 2));
     EXPECT_TRUE(g.reaches(2, 3));
     EXPECT_TRUE(g.reaches(3, 1));
     EXPECT_TRUE(g.reaches(3, 2));
     EXPECT_TRUE(g.reaches(3, 3));
     EXPECT_EQ("{1->2,2->3,3->1}", toString(g));
 }
TEST() [7/228]
souffle::test::TEST (Relation0 , Construction)
Definition at line 30 of file interpreter_relation_test.cpp.
References EXPECT_EQ, and souffle::MinIndexSelection::insertDefaultTotalIndex().
{
     // create a nullary relation
     SymbolTable symbolTable;
     MinIndexSelection order{};
     order.insertDefaultTotalIndex(0);
     InterpreterRelation rel(0, 0, "test", {}, order);
     InterpreterRelInterface relInt(rel, symbolTable, "test", {}, {}, 0);
     // add some values
     EXPECT_EQ(0, rel.size());
     relInt.insert(tuple(&relInt, {}));
     EXPECT_EQ(1, rel.size());
     relInt.insert(tuple(&relInt, {}));
     EXPECT_EQ(1, rel.size());
 }
TEST() [8/228]
souffle::test::TEST (RamIntrinsicOperator , CloneAndEquals)
Definition at line 31 of file ram_expression_equal_clone_test.cpp.
References souffle::ADD, b, souffle::RamIntrinsicOperator::clone(), d, e, EXPECT_EQ, EXPECT_NE, and souffle::NEG.
{
     // ADD(number(1), number(2))
     std::vector<std::unique_ptr<RamExpression>> a_args;
     a_args.emplace_back(new RamSignedConstant(1));
     a_args.emplace_back(new RamSignedConstant(2));
     RamIntrinsicOperator a(FunctorOp::ADD, std::move(a_args));
     std::vector<std::unique_ptr<RamExpression>> b_args;
     b_args.emplace_back(new RamSignedConstant(1));
     b_args.emplace_back(new RamSignedConstant(2));
     RamIntrinsicOperator b(FunctorOp::ADD, std::move(b_args));
     EXPECT_EQ(a, b);
     EXPECT_NE(&a, &b);
     RamIntrinsicOperator* aClone = a.clone();
     EXPECT_EQ(a, *aClone);
     EXPECT_NE(&a, aClone);
     delete aClone;
     // NEG(number(1))
     std::vector<std::unique_ptr<RamExpression>> d_args;
     d_args.emplace_back(new RamSignedConstant(1));
     RamIntrinsicOperator d(FunctorOp::NEG, std::move(d_args));
     std::vector<std::unique_ptr<RamExpression>> e_args;
     e_args.emplace_back(new RamSignedConstant(1));
     RamIntrinsicOperator e(FunctorOp::NEG, std::move(e_args));
     EXPECT_EQ(d, e);
     EXPECT_NE(&d, &e);
     RamIntrinsicOperator* dClone = d.clone();
     EXPECT_EQ(d, *dClone);
     EXPECT_NE(&d, dClone);
     delete dClone;
 }
TEST() [9/228]
souffle::test::TEST (Constraints , Basic)
Definition at line 32 of file constraints_test.cpp.
References souffle::Problem< Var >::add(), EXPECT_EQ, p, souffle::Problem< Var >::solve(), souffle::sub(), and souffle::toString().
{
     using Vars = Variable<string, set_property_space<int>>;
     Vars A("A");
     Vars B("B");
     Problem<Vars> p;
     // check empty problem
     EXPECT_EQ("{}", toString(p));
     EXPECT_EQ("{}", toString(p.solve()));
     // add a constraint
     p.add(sub(A, B));
     EXPECT_EQ("{\n\tA  B\n}", toString(p));
     EXPECT_EQ("{A->{},B->{}}", toString(p.solve()));
     // add another constraints
     std::set<int> s = {1, 2};
     p.add(sub(s, A));
     EXPECT_EQ("{\n\tA  B,\n\t{1,2}  A\n}", toString(p));
     EXPECT_EQ("{A->{1,2},B->{1,2}}", toString(p.solve()));
     // and one more
     std::set<int> s2 = {3};
     p.add(sub(s2, B));
     EXPECT_EQ("{\n\tA  B,\n\t{1,2}  A,\n\t{3}  B\n}", toString(p));
     EXPECT_EQ("{A->{1,2},B->{1,2,3}}", toString(p.solve()));
 }
TEST() [10/228]
souffle::test::TEST (RamTrue , CloneAndEquals)
Definition at line 33 of file ram_condition_equal_clone_test.cpp.
References b, souffle::RamTrue::clone(), EXPECT_EQ, and EXPECT_NE.
{
     RamTrue a;
     RamTrue b;
     EXPECT_EQ(a, b);
     EXPECT_NE(&a, &b);
     RamTrue* c = a.clone();
     EXPECT_EQ(a, *c);
     EXPECT_NE(&a, c);
     delete c;
 }
TEST() [11/228]
souffle::test::TEST (RamScan , CloneAndEquals)
Definition at line 33 of file ram_operation_equal_clone_test.cpp.
References b, souffle::RamScan::clone(), souffle::DEFAULT, EXPECT_EQ, and EXPECT_NE.
{
     RamRelation A("A", 1, 1, {"x"}, {"i"}, RelationRepresentation::DEFAULT);
     // FOR t0 in A
     //  RETURN number(0)
     std::vector<std::unique_ptr<RamExpression>> a_return_args;
     a_return_args.emplace_back(new RamSignedConstant(0));
     auto a_return = std::make_unique<RamSubroutineReturn>(std::move(a_return_args));
     RamScan a(std::make_unique<RamRelationReference>(&A), 0, std::move(a_return), "RamScan test");
     std::vector<std::unique_ptr<RamExpression>> b_return_args;
     b_return_args.emplace_back(new RamSignedConstant(0));
     auto b_return = std::make_unique<RamSubroutineReturn>(std::move(b_return_args));
     RamScan b(std::make_unique<RamRelationReference>(&A), 0, std::move(b_return), "RamScan test");
     EXPECT_EQ(a, b);
     EXPECT_NE(&a, &b);
     RamScan* c = a.clone();
     EXPECT_EQ(a, *c);
     EXPECT_NE(&a, c);
     delete c;
 }
TEST() [12/228]
souffle::test::TEST (RuleBody , Basic)
Definition at line 34 of file ast_parser_utils_test.cpp.
References souffle::RuleBody::atom(), EXPECT_EQ, and souffle::toString().
Referenced by TEST().
                       {
     RuleBody body;
     // start with an A
     auto a = RuleBody::atom(mk<AstAtom>("A"));
     EXPECT_EQ("A()", toString(a));
     a.conjunct(RuleBody::atom(mk<AstAtom>("B")));
     EXPECT_EQ("A(),B()", toString(a));
     a.disjunct(RuleBody::atom(mk<AstAtom>("C")));
     EXPECT_EQ("A(),B();C()", toString(a));
 }
TEST() [13/228]
souffle::test::TEST (Pack , Tuple)
Definition at line 35 of file record_table_test.cpp.
References EXPECT_EQ, i, souffle::pack(), and souffle::RecordTable::unpack().
                   {
     RecordTable recordTable;
     const Tuple<RamDomain, 3> tuple = {{1, 2, 3}};
     RamDomain ref = pack(recordTable, tuple);
     const RamDomain* ptr = recordTable.unpack(ref, 3);
     for (size_t i = 0; i < 3; ++i) {
         EXPECT_EQ(tuple[i], ptr[i]);
     }
 }
TEST() [14/228]
souffle::test::TEST (Table , Basic)
Definition at line 36 of file table_test.cpp.
References count(), souffle::Table< T, blockSize >::empty(), EXPECT_EQ, EXPECT_FALSE, EXPECT_TRUE, souffle::Table< T, blockSize >::insert(), and souffle::Table< T, blockSize >::size().
                    {
     Table<int> table;
     EXPECT_TRUE(table.empty());
     EXPECT_EQ(0, table.size());
     EXPECT_EQ(0, count(table));
     table.insert(1);
     EXPECT_FALSE(table.empty());
     EXPECT_EQ(1, table.size());
     EXPECT_EQ(1, count(table));
 }
TEST() [15/228]
souffle::test::TEST (RamIO1 , CloneAndEquals)
Definition at line 38 of file ram_statement_equal_clone_test.cpp.
References b, souffle::RamIO::clone(), souffle::DEFAULT, EXPECT_EQ, and EXPECT_NE.
{
     // IO A ()
     RamRelation A("A", 1, 1, {"x"}, {"i"}, RelationRepresentation::DEFAULT);
     std::map<std::string, std::string> ioEmptyA;
     std::map<std::string, std::string> ioEmptyB;
     RamIO a(std::make_unique<RamRelationReference>(&A), std::move(ioEmptyA));
     RamIO b(std::make_unique<RamRelationReference>(&A), std::move(ioEmptyB));
     EXPECT_EQ(a, b);
     EXPECT_NE(&a, &b);
     RamIO* c = a.clone();
     EXPECT_EQ(a, *c);
     EXPECT_NE(&a, c);
     delete c;
 }
TEST() [16/228]
souffle::test::TEST (RamRelationRepresentation , CloneAndEquals)
Definition at line 39 of file ram_relation_equal_clone_test.cpp.
References b, souffle::RamRelationReference::clone(), souffle::DEFAULT, EXPECT_EQ, and EXPECT_NE.
{
     RamRelation A("A", 1, 1, {"a"}, {"i"}, RelationRepresentation::DEFAULT);
     RamRelationReference a(&A);
     RamRelationReference b(&A);
     EXPECT_EQ(a, b);
     EXPECT_NE(&a, &b);
     RamRelationReference* c = a.clone();
     EXPECT_EQ(a, *c);
     EXPECT_NE(&a, c);
     delete c;
 }
TEST() [17/228]
souffle::test::TEST (AstTransformers , GroundTermPropagation)
Definition at line 39 of file ast_transformers_test.cpp.
References EXPECT_EQ, souffle::getClauses(), souffle::ParserDriver::parseTranslationUnit(), souffle::ResolveAliasesTransformer::removeTrivialEquality(), souffle::ResolveAliasesTransformer::resolveAliases(), and souffle::toString().
{
     ErrorReport errorReport;
     DebugReport debugReport;
     // load some test program
     std::unique_ptr<AstTranslationUnit> tu = ParserDriver::parseTranslationUnit(
             R"(
                 .type D <: symbol
                 .decl p(a:D,b:D)
                 p(a,b) :- p(x,y), r = [x,y], s = r, s = [w,v], [w,v] = [a,b].
             )",
             errorReport, debugReport);
     AstProgram& program = *tu->getProgram();
     // check types in clauses
     AstClause* a = getClauses(program, "p")[0];
     EXPECT_EQ("p(a,b) :- \n   p(x,y),\n   r = [x,y],\n   s = r,\n   s = [w,v],\n   [w,v] = [a,b].",
             toString(*a));
     std::unique_ptr<AstClause> res = ResolveAliasesTransformer::resolveAliases(*a);
     std::unique_ptr<AstClause> cleaned = ResolveAliasesTransformer::removeTrivialEquality(*res);
     EXPECT_EQ(
             "p(x,y) :- \n   p(x,y),\n   [x,y] = [x,y],\n   [x,y] = [x,y],\n   [x,y] = [x,y],\n   [x,y] = "
             "[x,y].",
             toString(*res));
     EXPECT_EQ("p(x,y) :- \n   p(x,y).", toString(*cleaned));
 }
TEST() [18/228]
souffle::test::TEST (EqRelTest , Scoping)
Definition at line 40 of file binary_relation_test.cpp.
{
     // simply test that namespaces were setup correctly
     souffle::EquivalenceRelation<souffle::Tuple<RamDomain, 2>> br;
 }
TEST() [19/228]
souffle::test::TEST (randomConversions , RamUnsigned)
Definition at line 42 of file ram_type_conversion_test.cpp.
References EXPECT_EQ, i, and NUMBER_OF_CONVERSION_TESTS.
{
     std::mt19937 randomGenerator(3);
     std::uniform_int_distribution<RamUnsigned> dist(0, 1000);
     for (int i = 0; i < NUMBER_OF_CONVERSION_TESTS; ++i) {
         RamUnsigned randomNumber = dist(randomGenerator);
         // Test float casting
         EXPECT_EQ(randomNumber, ramBitCast<RamUnsigned>(ramBitCast<RamFloat>(randomNumber)));
         // Test signed casting
         EXPECT_EQ(randomNumber, ramBitCast<RamUnsigned>(ramBitCast<RamDomain>(randomNumber)));
     }
 }
TEST() [20/228]
souffle::test::TEST (RandomInsertPiggyTest , Scoping)
Piggy List that allows creation at arbitrary elements.
Definition at line 43 of file eqrel_datastructure_test.cpp.
{
     // simply test that namespaces were setup correctly (compile time)
     souffle::RandomInsertPiggyList<size_t> pl;
 }
TEST() [21/228]
souffle::test::TEST (ParallelUtils , ReadWriteLock)
Definition at line 43 of file parallel_utils_test.cpp.
References souffle::ReadWriteLock::end_read(), souffle::ReadWriteLock::end_write(), EXPECT_EQ, i, souffle::ReadWriteLock::start_read(), and souffle::ReadWriteLock::start_write().
{
     const int N = 1000000;
     const int K = 10;
     ReadWriteLock lock;
     volatile int c = 0;
 #pragma omp parallel for num_threads(4)
     for (int i = 0; i < N; i++) {
         if (i % K == 0) {  // 10% write probability
             lock.start_write();
             c++;
             lock.end_write();
         } else {
             lock.start_read();
             // nothing to do here ..
             lock.end_read();
         }
     }
     EXPECT_EQ(N / K, c);
 }
TEST() [22/228]
souffle::test::TEST (SymbolTable , Copy)
Definition at line 44 of file symbol_table_test.cpp.
References b, EXPECT_EQ, and EXPECT_STREQ.
{
     auto* a = new SymbolTable();
     a->insert("Hello");
     auto* b = new SymbolTable(*a);
     size_t a_idx = a->lookup("Hello");
     size_t b_idx = b->lookup("Hello");
     // hash should be the same
     EXPECT_EQ(a_idx, b_idx);
     EXPECT_STREQ("Hello", a->resolve(a_idx));
     EXPECT_STREQ("Hello", b->resolve(b_idx));
     // should be the same actual string
     EXPECT_STREQ(a->resolve(a_idx), b->resolve(b_idx));
     // b should survive
     delete a;
     EXPECT_STREQ("Hello", b->resolve(b_idx));
     delete b;
 }
TEST() [23/228]
souffle::test::TEST (RamFalse , CloneAndEquals)
Definition at line 45 of file ram_condition_equal_clone_test.cpp.
References b, souffle::RamFalse::clone(), EXPECT_EQ, and EXPECT_NE.
{
     RamFalse a;
     RamFalse b;
     EXPECT_EQ(a, b);
     EXPECT_NE(&a, &b);
     RamFalse* c = a.clone();
     EXPECT_EQ(a, *c);
     EXPECT_NE(&a, c);
     delete c;
 }
TEST() [24/228]
souffle::test::TEST (TypeSystem , isNumberType)
Definition at line 45 of file type_system_test.cpp.
References souffle::TypeEnvironment::createType(), EXPECT_FALSE, EXPECT_TRUE, souffle::TypeEnvironment::getType(), souffle::isOfKind(), souffle::Signed, souffle::Symbol, and souffle::toVector().
{
     TypeEnvironment env;
     const Type& N = env.getType("number");
     const Type& A = env.createType<SubsetType>("A", env.getType("number"));
     const Type& B = env.createType<SubsetType>("B", env.getType("number"));
     const Type& C = env.createType<SubsetType>("C", env.getType("symbol"));
     EXPECT_TRUE(isOfKind(N, TypeAttribute::Signed));
     EXPECT_TRUE(isOfKind(A, TypeAttribute::Signed));
     EXPECT_TRUE(isOfKind(B, TypeAttribute::Signed));
     EXPECT_TRUE(isOfKind(C, TypeAttribute::Symbol));
     EXPECT_FALSE(isOfKind(N, TypeAttribute::Symbol));
     EXPECT_FALSE(isOfKind(A, TypeAttribute::Symbol));
     EXPECT_FALSE(isOfKind(B, TypeAttribute::Symbol));
     EXPECT_FALSE(isOfKind(C, TypeAttribute::Signed));
     // check the union type
     {
         const Type& U = env.createType<UnionType>("U", toVector(&A, &B));
         EXPECT_TRUE(isOfKind(U, TypeAttribute::Signed));
         EXPECT_FALSE(isOfKind(U, TypeAttribute::Symbol));
         const Type& U2 = env.createType<UnionType>("U2", toVector(&A, &B, &C));
         EXPECT_FALSE(isOfKind(U2, TypeAttribute::Signed));
         EXPECT_FALSE(isOfKind(U2, TypeAttribute::Symbol));
     }
     {
         const Type& U3 = env.createType<UnionType>("U3", toVector(&A));
         EXPECT_TRUE(isOfKind(U3, TypeAttribute::Signed));
     }
 }
TEST() [25/228]
souffle::test::TEST (Relation1 , Construction)
Definition at line 46 of file interpreter_relation_test.cpp.
References EXPECT_EQ, and souffle::MinIndexSelection::insertDefaultTotalIndex().
{
     // create a single attribute relation
     SymbolTable symbolTable;
     MinIndexSelection order{};
     order.insertDefaultTotalIndex(1);
     InterpreterRelation rel(1, 0, "test", {"i"}, order);
     InterpreterRelInterface relInt(rel, symbolTable, "test", {"i"}, {"i"}, 0);
     tuple d1(&relInt, {1});
     // add some values
     EXPECT_EQ(0, rel.size());
     relInt.insert(d1);
     EXPECT_EQ(1, rel.size());
     relInt.insert(tuple(&relInt, {2}));
     EXPECT_EQ(2, rel.size());
     relInt.insert(tuple(&relInt, {3}));
     EXPECT_EQ(3, rel.size());
     relInt.insert(tuple(&relInt, {4}));
     EXPECT_EQ(4, rel.size());
 }
TEST() [26/228]
souffle::test::TEST (EqRelTest , Basic)
Definition at line 47 of file binary_relation_test.cpp.
References souffle::EquivalenceRelation< TupleType >::contains(), count(), EXPECT_EQ, EXPECT_FALSE, EXPECT_TRUE, testutil::ignore(), souffle::EquivalenceRelation< TupleType >::insert(), and souffle::EquivalenceRelation< TupleType >::size().
{
     EqRel br;
     // empty bin rel should be exactly that
     EXPECT_EQ(br.size(), 0);
     EXPECT_FALSE(br.contains(1, 2));
     EXPECT_FALSE(br.contains(0, 0));
     // test implicit rules
     br.insert(1, 2);
     EXPECT_EQ(br.size(), 4);
     EXPECT_TRUE(br.contains(1, 2));
     EXPECT_TRUE(br.contains(2, 1));
     EXPECT_TRUE(br.contains(1, 1));
     EXPECT_TRUE(br.contains(2, 2));
     // test insert of exactly one pair
     br.insert(3, 3);
     EXPECT_EQ(br.size(), 5);
     EXPECT_TRUE(br.contains(3, 3));
     EXPECT_FALSE(br.contains(1, 3));
     EXPECT_FALSE(br.contains(3, 2));
     size_t count = 0;
     for (auto x : br) {
         ++count;
         testutil::ignore(x);
     }
     EXPECT_EQ(count, br.size());
 }
TEST() [27/228]
souffle::test::TEST (RuleBody , Negation)
Definition at line 48 of file ast_parser_utils_test.cpp.
References souffle::RuleBody::atom(), souffle::RuleBody::conjunct(), souffle::RuleBody::disjunct(), EXPECT_EQ, souffle::RuleBody::getFalse(), souffle::RuleBody::getTrue(), souffle::RuleBody::negated(), and souffle::toString().
{
     RuleBody body = RuleBody::getTrue();
     RuleBody AB = RuleBody::getTrue();
     AB.conjunct(RuleBody::atom(mk<AstAtom>("A")));
     AB.conjunct(RuleBody::atom(mk<AstAtom>("B")));
     EXPECT_EQ("A(),B()", toString(AB));
     RuleBody CD = RuleBody::getTrue();
     CD.conjunct(RuleBody::atom(mk<AstAtom>("C")));
     CD.conjunct(RuleBody::atom(mk<AstAtom>("D")));
     EXPECT_EQ("C(),D()", toString(CD));
     RuleBody EF = RuleBody::getTrue();
     EF.conjunct(RuleBody::atom(mk<AstAtom>("E")));
     EF.conjunct(RuleBody::atom(mk<AstAtom>("F")));
     EXPECT_EQ("E(),F()", toString(EF));
     RuleBody full = RuleBody::getFalse();
     full.disjunct(std::move(AB));
     full.disjunct(std::move(CD));
     full.disjunct(std::move(EF));
     EXPECT_EQ("A(),B();C(),D();E(),F()", toString(full));
     full = full.negated();
     EXPECT_EQ(
             "!A(),!C(),!E();!A(),!C(),!F();!A(),!D(),!E();!A(),!D(),!F();!B(),!C(),!E();!B(),!C(),!F();!B(),!"
             "D(),!E();!B(),!D(),!F()",
             toString(full));
     full = full.negated();
     EXPECT_EQ("A(),B();C(),D();E(),F()", toString(full));
 }
TEST() [28/228]
souffle::test::TEST (RandomInsertPiggyTest , Insertion)
Definition at line 48 of file eqrel_datastructure_test.cpp.
References EXPECT_EQ, souffle::RandomInsertPiggyList< T >::get(), souffle::RandomInsertPiggyList< T >::insertAt(), and souffle::RandomInsertPiggyList< T >::size().
{
     // insert a bunch of stuff and check the size is valid?
     souffle::RandomInsertPiggyList<size_t> pl;
     EXPECT_EQ(pl.size(), 0);
     pl.insertAt(0, 99);
     EXPECT_EQ(pl.get(0), 99);
     EXPECT_EQ(pl.size(), 1);
     pl.insertAt(1000, 33);
     EXPECT_EQ(pl.get(1000), 33);
     EXPECT_EQ(pl.size(), 2);
 }
TEST() [29/228]
souffle::test::TEST (AstUtils , Grounded)
Definition at line 49 of file ast_utils_test.cpp.
References b, souffle::EQ, EXPECT_EQ, EXPECT_FALSE, EXPECT_TRUE, souffle::getGroundedTerms(), and souffle::toString().
{
     // create an example clause:
     auto clause = std::make_unique<AstClause>();
     // something like:
     //   r(X,Y,Z) :- a(X), X = Y, !b(Z).
     // r(X,Y,Z)
     auto* head = new AstAtom("r");
     head->addArgument(std::unique_ptr<AstArgument>(new AstVariable("X")));
     head->addArgument(std::unique_ptr<AstArgument>(new AstVariable("Y")));
     head->addArgument(std::unique_ptr<AstArgument>(new AstVariable("Z")));
     clause->setHead(std::unique_ptr<AstAtom>(head));
     // a(X)
     auto* a = new AstAtom("a");
     a->addArgument(std::unique_ptr<AstArgument>(new AstVariable("X")));
     clause->addToBody(std::unique_ptr<AstLiteral>(a));
     // X = Y
     AstLiteral* e1 = new AstBinaryConstraint(BinaryConstraintOp::EQ,
             std::unique_ptr<AstArgument>(new AstVariable("X")),
             std::unique_ptr<AstArgument>(new AstVariable("Y")));
     clause->addToBody(std::unique_ptr<AstLiteral>(e1));
     // !b(Z)
     auto* b = new AstAtom("b");
     b->addArgument(std::unique_ptr<AstArgument>(new AstVariable("Z")));
     auto* neg = new AstNegation(std::unique_ptr<AstAtom>(b));
     clause->addToBody(std::unique_ptr<AstLiteral>(neg));
     // check construction
     EXPECT_EQ("r(X,Y,Z) :- \n   a(X),\n   X = Y,\n   !b(Z).", toString(*clause));
     auto program = std::make_unique<AstProgram>();
     program->addClause(std::move(clause));
     DebugReport dbgReport;
     ErrorReport errReport;
     AstTranslationUnit tu{std::move(program), errReport, dbgReport};
     // obtain groundness
     auto isGrounded = getGroundedTerms(tu, *tu.getProgram()->getClauses()[0]);
     auto args = head->getArguments();
     // check selected sub-terms
     EXPECT_TRUE(isGrounded[args[0]]);   // X
     EXPECT_TRUE(isGrounded[args[1]]);   // Y
     EXPECT_FALSE(isGrounded[args[2]]);  // Z
 }
TEST() [30/228]
souffle::test::TEST (Table , Stress)
Definition at line 49 of file table_test.cpp.
References EXPECT_EQ, i, souffle::Table< T, blockSize >::insert(), j, and souffle::Table< T, blockSize >::size().
                     {
     for (int i = 0; i < 10000; ++i) {
         Table<int> table;
         for (int j = 0; j < i; ++j) {
             table.insert(j);
         }
         EXPECT_EQ((size_t)i, table.size());
         int last = -1;
         for (const auto& cur : table) {
             EXPECT_EQ(last + 1, cur);
             last = cur;
         }
         EXPECT_EQ(last + 1, i);
     }
 }
TEST() [31/228]
souffle::test::TEST (PackUnpack , Tuple)
Definition at line 51 of file record_table_test.cpp.
References EXPECT_EQ, i, NUMBER_OF_TESTS, souffle::pack(), and souffle::RecordTable::unpack().
{
     constexpr size_t tupleSize = 3;
     using tupleType = Tuple<RamDomain, tupleSize>;
     RecordTable recordTable;
     // Setup random number generation
     std::default_random_engine randomGenerator(3);
     std::uniform_int_distribution<RamDomain> distribution(
             std::numeric_limits<RamDomain>::lowest(), std::numeric_limits<RamDomain>::max());
     auto random = std::bind(distribution, randomGenerator);
     // Tuples that will be packed
     std::vector<tupleType> toPack(NUMBER_OF_TESTS);
     // Tuple reference after they are packed.
     std::vector<RamDomain> tupleRef(NUMBER_OF_TESTS);
     // Generate and pack the tuples
     for (size_t i = 0; i < NUMBER_OF_TESTS; ++i) {
         toPack[i] = {{random(), random(), random()}};
         tupleRef[i] = pack(recordTable, toPack[i]);
     }
     // unpack and test
     for (size_t i = 0; i < NUMBER_OF_TESTS; ++i) {
         auto unpacked = recordTable.unpack(tupleRef[i], tupleSize);
         tupleType cmp = {unpacked[0], unpacked[1], unpacked[2]};
         EXPECT_EQ(toPack[i], cmp);
     }
 }
TEST() [32/228]
souffle::test::TEST (RamClear , CloneAndEquals)
Definition at line 54 of file ram_statement_equal_clone_test.cpp.
References b, souffle::RamClear::clone(), souffle::DEFAULT, EXPECT_EQ, and EXPECT_NE.
{
     // CLEAR A
     RamRelation A("A", 1, 1, {"x"}, {"i"}, RelationRepresentation::DEFAULT);
     RamClear a(std::make_unique<RamRelationReference>(&A));
     RamClear b(std::make_unique<RamRelationReference>(&A));
     EXPECT_EQ(a, b);
     EXPECT_NE(&a, &b);
     RamClear* c = a.clone();
     EXPECT_EQ(a, *c);
     EXPECT_NE(&a, c);
     delete c;
 }
TEST() [33/228]
souffle::test::TEST (RamParallelScan , CloneAndEquals)
Definition at line 56 of file ram_operation_equal_clone_test.cpp.
References b, souffle::RamParallelScan::clone(), souffle::DEFAULT, EXPECT_EQ, and EXPECT_NE.
{
     RamRelation A("A", 1, 1, {"x"}, {"i"}, RelationRepresentation::DEFAULT);
     // PARALLEL FOR t0 in A
     //  RETURN number(0)
     std::vector<std::unique_ptr<RamExpression>> a_return_args;
     a_return_args.emplace_back(new RamSignedConstant(0));
     auto a_return = std::make_unique<RamSubroutineReturn>(std::move(a_return_args));
     RamParallelScan a(
             std::make_unique<RamRelationReference>(&A), 0, std::move(a_return), "RamParallelScan test");
     std::vector<std::unique_ptr<RamExpression>> b_return_args;
     b_return_args.emplace_back(new RamSignedConstant(0));
     auto b_return = std::make_unique<RamSubroutineReturn>(std::move(b_return_args));
     RamParallelScan b(
             std::make_unique<RamRelationReference>(&A), 0, std::move(b_return), "RamParallelScan test");
     EXPECT_EQ(a, b);
     EXPECT_NE(&a, &b);
     RamParallelScan* c = a.clone();
     EXPECT_EQ(a, *c);
     EXPECT_NE(&a, c);
     delete c;
 }
TEST() [34/228]
souffle::test::TEST (BTreeMultiSet , Basic)
Definition at line 56 of file btree_multiset_test.cpp.
References DEBUG, EXPECT_EQ, EXPECT_FALSE, and EXPECT_TRUE.
{
     const bool DEBUG = false;
     using test_set = btree_multiset<int, detail::comparator<int>, std::allocator<int>, 16>;
     test_set t;
     EXPECT_EQ(3, test_set::max_keys_per_node);
     // check initial conditions
     EXPECT_EQ(0u, t.size());
     EXPECT_FALSE(t.contains(10));
     EXPECT_FALSE(t.contains(12));
     EXPECT_FALSE(t.contains(14));
     EXPECT_EQ(0, t.getDepth());
     EXPECT_EQ(0, t.getNumNodes());
     if (DEBUG) t.printTree();
     // add an element
     t.insert(12);
     if (DEBUG) {
         t.printTree();
         std::cout << "\n";
     }
     EXPECT_EQ(1u, t.size());
     EXPECT_FALSE(t.contains(10));
     EXPECT_TRUE(t.contains(12));
     EXPECT_FALSE(t.contains(14));
     EXPECT_EQ(1, t.getDepth());
     EXPECT_EQ(1, t.getNumNodes());
     // add a larger element
     t.insert(14);
     if (DEBUG) {
         t.printTree();
         std::cout << "\n";
     }
     EXPECT_EQ(2u, t.size());
     EXPECT_FALSE(t.contains(10));
     EXPECT_TRUE(t.contains(12));
     EXPECT_TRUE(t.contains(14));
     EXPECT_EQ(1, t.getDepth());
     EXPECT_EQ(1, t.getNumNodes());
     // add a smaller element
     t.insert(10);
     if (DEBUG) {
         t.printTree();
         std::cout << "\n";
     }
     EXPECT_EQ(3u, t.size());
     EXPECT_TRUE(t.contains(10));
     EXPECT_TRUE(t.contains(12));
     EXPECT_TRUE(t.contains(14));
     EXPECT_EQ(1, t.getDepth());
     EXPECT_EQ(1, t.getNumNodes());
     // cause a split
     t.insert(11);
     if (DEBUG) {
         t.printTree();
         std::cout << "\n";
     }
     EXPECT_EQ(4u, t.size());
     EXPECT_TRUE(t.contains(10));
     EXPECT_TRUE(t.contains(11));
     EXPECT_TRUE(t.contains(12));
     EXPECT_TRUE(t.contains(14));
     if (DEBUG) {
         t.printTree();
         std::cout << "\n";
     }
     t.insert(12);
     EXPECT_EQ(5u, t.size());
     t.insert(12);
     EXPECT_EQ(6u, t.size());
     if (DEBUG) {
         t.printTree();
         std::cout << "\n";
     }
     t.insert(15);
     if (DEBUG) {
         t.printTree();
         std::cout << "\n";
     }
     t.insert(16);
     if (DEBUG) {
         t.printTree();
         std::cout << "\n";
     }
 }
TEST() [35/228]
souffle::test::TEST (AstProgram , Parse)
Definition at line 57 of file ast_program_test.cpp.
References d, e, EXPECT_EQ, EXPECT_FALSE, EXPECT_TRUE, souffle::getRelation(), and souffle::ParserDriver::parseTranslationUnit().
{
     ErrorReport e;
     DebugReport d;
     // check the empty program
     std::unique_ptr<AstTranslationUnit> empty = ParserDriver::parseTranslationUnit("", e, d);
     EXPECT_TRUE(empty->getProgram()->getTypes().empty());
     EXPECT_TRUE(empty->getProgram()->getRelations().empty());
     // check something simple
     std::unique_ptr<AstTranslationUnit> tu = ParserDriver::parseTranslationUnit(
             R"(
                    .type Node <: symbol
                    .decl e ( a : Node , b : Node )
                    .decl r ( from : Node , to : Node )
                    r(X,Y) :- e(X,Y).
                    r(X,Z) :- r(X,Y), r(Y,Z).
             )",
             e, d);
     auto* prog = tu->getProgram();
     std::cout << *prog << "\n";
     EXPECT_EQ(1, prog->getTypes().size());
     EXPECT_EQ(2, prog->getRelations().size());
     EXPECT_TRUE(getRelation(*prog, "e"));
     EXPECT_TRUE(getRelation(*prog, "r"));
     EXPECT_FALSE(getRelation(*prog, "n"));
 }
TEST() [36/228]
souffle::test::TEST (RamConjunction , CloneAndEquals)
Definition at line 57 of file ram_condition_equal_clone_test.cpp.
References b, d, e, EXPECT_EQ, and EXPECT_NE.
{
     // true /\ false
     auto a = std::make_unique<RamConjunction>(std::make_unique<RamTrue>(), std::make_unique<RamFalse>());
     auto b = std::make_unique<RamConjunction>(std::make_unique<RamTrue>(), std::make_unique<RamFalse>());
     EXPECT_EQ(*a, *b);
     EXPECT_NE(a, b);
     std::unique_ptr<RamConjunction> c(a->clone());
     EXPECT_EQ(*a, *c);
     EXPECT_NE(a, c);
     // true /\ (false /\ true)
     auto d = std::make_unique<RamConjunction>(std::make_unique<RamTrue>(),
             std::make_unique<RamConjunction>(std::make_unique<RamFalse>(), std::make_unique<RamTrue>()));
     auto e = std::make_unique<RamConjunction>(std::make_unique<RamTrue>(),
             std::make_unique<RamConjunction>(std::make_unique<RamFalse>(), std::make_unique<RamTrue>()));
     EXPECT_EQ(*d, *e);
     EXPECT_NE(d, e);
     std::unique_ptr<RamConjunction> f(d->clone());
     EXPECT_EQ(*d, *f);
     EXPECT_NE(d, f);
     // (true /\ false) /\ (true /\ (false /\ true))
     auto a_conj_d = std::make_unique<RamConjunction>(std::move(a), std::move(d));
     auto b_conj_e = std::make_unique<RamConjunction>(std::move(b), std::move(e));
     EXPECT_EQ(*a_conj_d, *b_conj_e);
     EXPECT_NE(a_conj_d, b_conj_e);
     auto c_conj_f = std::make_unique<RamConjunction>(std::move(c), std::move(f));
     EXPECT_EQ(*c_conj_f, *a_conj_d);
     EXPECT_EQ(*c_conj_f, *b_conj_e);
     EXPECT_NE(c_conj_f, a_conj_d);
     EXPECT_NE(c_conj_f, b_conj_e);
     std::unique_ptr<RamConjunction> a_conj_d_copy(a_conj_d->clone());
     EXPECT_EQ(*a_conj_d, *a_conj_d_copy);
     EXPECT_NE(a_conj_d, a_conj_d_copy);
 }
TEST() [37/228]
souffle::test::TEST (randomConversions , RamFloat)
Definition at line 57 of file ram_type_conversion_test.cpp.
References EXPECT_EQ, i, and NUMBER_OF_CONVERSION_TESTS.
{
     std::mt19937 randomGenerator(3);
     std::uniform_real_distribution<RamFloat> dist(-100.0, 100.0);
     for (int i = 0; i < NUMBER_OF_CONVERSION_TESTS; ++i) {
         RamFloat randomNumber = dist(randomGenerator);
         // Test signed casting
         EXPECT_EQ(randomNumber, ramBitCast<RamFloat>(ramBitCast<RamDomain>(randomNumber)));
         // Test unsigned casting
         EXPECT_EQ(randomNumber, ramBitCast<RamFloat>(ramBitCast<RamUnsigned>(randomNumber)));
     }
 }
TEST() [38/228]
souffle::test::TEST (BTreeSet , Basic)
Definition at line 60 of file btree_set_test.cpp.
References DEBUG, EXPECT_EQ, EXPECT_FALSE, and EXPECT_TRUE.
                       {
     const bool DEBUG = false;
     using test_set = btree_set<int, detail::comparator<int>, std::allocator<int>, 16>;
     test_set t;
     EXPECT_EQ(3, test_set::max_keys_per_node);
     // check initial conditions
     EXPECT_EQ(0u, t.size());
     EXPECT_FALSE(t.contains(10));
     EXPECT_FALSE(t.contains(12));
     EXPECT_FALSE(t.contains(14));
     EXPECT_EQ(0, t.getDepth());
     EXPECT_EQ(0, t.getNumNodes());
     if (DEBUG) t.printTree();
     // add an element
     t.insert(12);
     if (DEBUG) {
         t.printTree();
         std::cout << "\n";
     }
     EXPECT_EQ(1u, t.size());
     EXPECT_FALSE(t.contains(10));
     EXPECT_TRUE(t.contains(12));
     EXPECT_FALSE(t.contains(14));
     EXPECT_EQ(1, t.getDepth());
     EXPECT_EQ(1, t.getNumNodes());
     // add a larger element
     t.insert(14);
     if (DEBUG) {
         t.printTree();
         std::cout << "\n";
     }
     EXPECT_EQ(2u, t.size());
     EXPECT_FALSE(t.contains(10));
     EXPECT_TRUE(t.contains(12));
     EXPECT_TRUE(t.contains(14));
     EXPECT_EQ(1, t.getDepth());
     EXPECT_EQ(1, t.getNumNodes());
     // add a smaller element
     t.insert(10);
     if (DEBUG) {
         t.printTree();
         std::cout << "\n";
     }
     EXPECT_EQ(3u, t.size());
     EXPECT_TRUE(t.contains(10));
     EXPECT_TRUE(t.contains(12));
     EXPECT_TRUE(t.contains(14));
     EXPECT_EQ(1, t.getDepth());
     EXPECT_EQ(1, t.getNumNodes());
     // cause a split
     t.insert(11);
     if (DEBUG) {
         t.printTree();
         std::cout << "\n";
     }
     EXPECT_EQ(4u, t.size());
     EXPECT_TRUE(t.contains(10));
     EXPECT_TRUE(t.contains(11));
     EXPECT_TRUE(t.contains(12));
     EXPECT_TRUE(t.contains(14));
     if (DEBUG) {
         t.printTree();
         std::cout << "\n";
     }
     EXPECT_EQ(4u, t.size());
     t.insert(12);
     EXPECT_EQ(4u, t.size());
     t.insert(12);
     EXPECT_EQ(4u, t.size());
     t.insert(10);
     EXPECT_EQ(4u, t.size());
     if (DEBUG) {
         t.printTree();
         std::cout << "\n";
     }
     t.insert(15);
     EXPECT_EQ(5u, t.size());
     EXPECT_EQ(2, t.getDepth());
     EXPECT_EQ(3, t.getNumNodes());
     if (DEBUG) {
         t.printTree();
         std::cout << "\n";
     }
     t.insert(16);
     EXPECT_EQ(6u, t.size());
     if (DEBUG) {
         t.printTree();
         std::cout << "\n";
     }
 }
TEST() [39/228]
souffle::test::TEST (AstPrint , NilConstant)
Definition at line 60 of file ast_print_test.cpp.
References EXPECT_EQ, makeATU(), makeClauseA(), and makePrintedATU().
{
     auto testArgument = std::make_unique<AstNilConstant>();
     auto tu1 = makeATU();
     tu1->getProgram()->addClause(makeClauseA(std::move(testArgument)));
     auto tu2 = makePrintedATU(tu1);
     EXPECT_EQ(*tu1->getProgram(), *tu2->getProgram());
 }
TEST() [40/228]
souffle::test::TEST (RandomInsertPiggyTest , DoubleClear)
Definition at line 62 of file eqrel_datastructure_test.cpp.
References souffle::RandomInsertPiggyList< T >::clear(), EXPECT_EQ, souffle::RandomInsertPiggyList< T >::get(), i, souffle::RandomInsertPiggyList< T >::insertAt(), souffle::RandomInsertPiggyList< T >::size(), and TEST().
{
     // err.. prior versions have had the bug where clear caused double-free errors (as we don't set the
     // container to null) This should *crash* the test-suite if this is the case, but I also try to check the
     // contents here
     souffle::RandomInsertPiggyList<size_t> pl;
     pl.insertAt(0, 3213);
     pl.insertAt(1, 3213);
     pl.insertAt(2, 3213);
     pl.insertAt(3, 3213);
     EXPECT_EQ(pl.size(), 4);
     pl.clear();
     EXPECT_EQ(pl.size(), 0);
     pl.clear();
     EXPECT_EQ(pl.size(), 0);
     pl.insertAt(0, 1);
     EXPECT_EQ(pl.size(), 1);
 }
TEST() [41/228]
souffle::test::TEST (RamUserDefinedOperator , CloneAndEquals)
Definition at line 67 of file ram_expression_equal_clone_test.cpp.
References b, souffle::RamUserDefinedOperator::clone(), EXPECT_EQ, EXPECT_NE, and souffle::Signed.
{
     // define binary functor NE check if two RamExpressions are not equal
     // NE(number(1), number(10))
     std::vector<std::unique_ptr<RamExpression>> a_args;
     a_args.emplace_back(new RamSignedConstant(1));
     a_args.emplace_back(new RamSignedConstant(10));
     RamUserDefinedOperator a(
             "NE", {TypeAttribute::Signed, TypeAttribute::Signed}, TypeAttribute::Signed, std::move(a_args));
     std::vector<std::unique_ptr<RamExpression>> b_args;
     b_args.emplace_back(new RamSignedConstant(1));
     b_args.emplace_back(new RamSignedConstant(10));
     RamUserDefinedOperator b(
             "NE", {TypeAttribute::Signed, TypeAttribute::Signed}, TypeAttribute::Signed, std::move(b_args));
     EXPECT_EQ(a, b);
     EXPECT_NE(&a, &b);
     RamUserDefinedOperator* aClone = a.clone();
     EXPECT_EQ(a, *aClone);
     EXPECT_NE(&a, aClone);
     delete aClone;
 }
TEST() [42/228]
souffle::test::TEST (Basic , Iteration)
Definition at line 67 of file interpreter_relation_test.cpp.
References count(), EXPECT_EQ, souffle::InterpreterRelInterface::insert(), and souffle::MinIndexSelection::insertDefaultTotalIndex().
{
     // create a relation
     SymbolTable symbolTable;
     MinIndexSelection order{};
     order.insertDefaultTotalIndex(1);
     InterpreterRelation rel(1, 0, "test", {"i"}, order);
     InterpreterRelInterface relInt(rel, symbolTable, "test", {"i"}, {"i"}, 0);
     // add some values
     relInt.insert(tuple(&relInt, {1}));
     relInt.insert(tuple(&relInt, {2}));
     relInt.insert(tuple(&relInt, {3}));
     relInt.insert(tuple(&relInt, {4}));
     // Iterate
     Relation::iterator it = relInt.begin();
     std::size_t count = 0;
     while (it != relInt.end()) {
         // Check the 'deref' doesn't crash
         auto value = (*it)[0];
         (void)value;
         ++it;
         ++count;
     }
     EXPECT_EQ(4, count);
 }
TEST() [43/228]
souffle::test::TEST (ParallelUtils , OptimisticReadWriteLock)
Definition at line 67 of file parallel_utils_test.cpp.
References souffle::OptimisticReadWriteLock::end_read(), souffle::OptimisticReadWriteLock::end_write(), EXPECT_EQ, EXPECT_TRUE, i, souffle::OptimisticReadWriteLock::start_read(), and souffle::OptimisticReadWriteLock::start_write().
{
     const int N = 1000000;
     const int K = 10;
     OptimisticReadWriteLock lock;
     volatile int c = 0;
 #pragma omp parallel for num_threads(4)
     for (int i = 0; i < N; i++) {
         if (i % K == 0) {  // 10% write probability
             lock.start_write();
             c++;
             c++;
             lock.end_write();
         } else {
             bool succ = false;
             do {
                 auto lease = lock.start_read();
                 // nothing to do here ..
                 int x = c;
                 succ = lock.end_read(lease);
                 EXPECT_TRUE((x % 2 == 0) || !succ);
             } while (!succ);
         }
     }
     EXPECT_EQ(2 * (N / K), c);
 }
TEST() [44/228]
souffle::test::TEST (RamExtend , CloneAndEquals)
Definition at line 68 of file ram_statement_equal_clone_test.cpp.
References b, souffle::RamExtend::clone(), souffle::DEFAULT, EXPECT_EQ, and EXPECT_NE.
{
     // MERGE B WITH A
     RamRelation A("A", 1, 1, {"x"}, {"i"}, RelationRepresentation::DEFAULT);
     RamRelation B("B", 1, 1, {"x"}, {"i"}, RelationRepresentation::DEFAULT);
     RamExtend a(std::make_unique<RamRelationReference>(&B), std::make_unique<RamRelationReference>(&A));
     RamExtend b(std::make_unique<RamRelationReference>(&B), std::make_unique<RamRelationReference>(&A));
     EXPECT_EQ(a, b);
     EXPECT_NE(&a, &b);
     RamExtend* c = a.clone();
     EXPECT_EQ(a, *c);
     EXPECT_NE(&a, c);
     delete c;
 }
TEST() [45/228]
souffle::test::TEST (AstPrint , NumberConstant)
Definition at line 69 of file ast_print_test.cpp.
References EXPECT_EQ, makeATU(), makeClauseA(), and makePrintedATU().
{
     auto testArgument = std::make_unique<AstNumericConstant>("2");
     EXPECT_EQ(testArgument, testArgument);
     auto tu1 = makeATU();
     tu1->getProgram()->addClause(makeClauseA(std::move(testArgument)));
     auto tu2 = makePrintedATU(tu1);
     EXPECT_EQ(*tu1->getProgram(), *tu2->getProgram());
 }
TEST() [46/228]
souffle::test::TEST (SymbolTable , Assign)
Definition at line 69 of file symbol_table_test.cpp.
References b, EXPECT_EQ, EXPECT_STREQ, souffle::SymbolTable::lookup(), and souffle::SymbolTable::resolve().
{
     auto* a = new SymbolTable();
     a->insert("Hello");
     SymbolTable b = *a;
     SymbolTable c;
     c = *a;
     size_t a_idx = a->lookup("Hello");
     size_t b_idx = b.lookup("Hello");
     size_t c_idx = c.lookup("Hello");
     // hash should be the same
     EXPECT_EQ(a_idx, b_idx);
     EXPECT_EQ(b_idx, c_idx);
     EXPECT_STREQ("Hello", a->resolve(a_idx));
     EXPECT_STREQ("Hello", b.resolve(b_idx));
     EXPECT_STREQ("Hello", c.resolve(c_idx));
     // b and c should survive
     delete a;
     EXPECT_STREQ("Hello", b.resolve(b_idx));
     EXPECT_STREQ("Hello", c.resolve(c_idx));
 }
TEST() [47/228]
souffle::test::TEST (AstTransformers , GroundTermPropagation2)
Definition at line 70 of file ast_transformers_test.cpp.
References EXPECT_EQ, souffle::getClauses(), souffle::ParserDriver::parseTranslationUnit(), souffle::ResolveAliasesTransformer::removeTrivialEquality(), souffle::ResolveAliasesTransformer::resolveAliases(), and souffle::toString().
{
     ErrorReport errorReport;
     DebugReport debugReport;
     // load some test program
     std::unique_ptr<AstTranslationUnit> tu = ParserDriver::parseTranslationUnit(
             R"(
                .type D <: symbol
                .decl p(a:D,b:D)
                p(a,b) :- p(x,y), x = y, x = a, y = b.
            )",
             errorReport, debugReport);
     AstProgram& program = *tu->getProgram();
     // check types in clauses
     AstClause* a = getClauses(program, "p")[0];
     EXPECT_EQ("p(a,b) :- \n   p(x,y),\n   x = y,\n   x = a,\n   y = b.", toString(*a));
     std::unique_ptr<AstClause> res = ResolveAliasesTransformer::resolveAliases(*a);
     std::unique_ptr<AstClause> cleaned = ResolveAliasesTransformer::removeTrivialEquality(*res);
     EXPECT_EQ("p(b,b) :- \n   p(b,b),\n   b = b,\n   b = b,\n   b = b.", toString(*res));
     EXPECT_EQ("p(b,b) :- \n   p(b,b).", toString(*cleaned));
 }
TEST() [48/228]
souffle::test::TEST (EqRelTest , Clear)
Definition at line 76 of file binary_relation_test.cpp.
References count(), EXPECT_EQ, testutil::ignore(), souffle::EquivalenceRelation< TupleType >::insert(), and souffle::EquivalenceRelation< TupleType >::size().
{
     EqRel br;
     br.insert(0, 44);
     br.insert(0, 1);
     EXPECT_EQ(9, br.size());
     size_t count = 0;
     for (auto x : br) {
         ++count;
         testutil::ignore(x);
     }
     EXPECT_EQ(count, br.size());
     br.clear();
     EXPECT_EQ(0, br.size());
     count = 0;
     for (auto x : br) {
         ++count;
         testutil::ignore(x);
     }
     EXPECT_EQ(count, br.size());
 }
TEST() [49/228]
souffle::test::TEST (AstPrint , StringConstant)
Definition at line 80 of file ast_print_test.cpp.
References d, e, EXPECT_EQ, makeClauseA(), makePrintedATU(), and souffle::ParserDriver::parseTranslationUnit().
{
     ErrorReport e;
     DebugReport d;
     auto testArgument = std::make_unique<AstStringConstant>("test string");
     auto tu1 = ParserDriver::parseTranslationUnit(".decl A,B,C(x:number)", e, d);
     tu1->getProgram()->addClause(makeClauseA(std::move(testArgument)));
     auto tu2 = makePrintedATU(tu1);
     EXPECT_EQ(*tu1->getProgram(), *tu2->getProgram());
 }
TEST() [50/228]
souffle::test::TEST (RamIndexScan , CloneAndEquals)
Definition at line 81 of file ram_operation_equal_clone_test.cpp.
References b, souffle::RamIndexScan::clone(), souffle::DEFAULT, EXPECT_EQ, and EXPECT_NE.
{
     RamRelation edge("edge", 2, 1, {"x", "y"}, {"i", "i"}, RelationRepresentation::DEFAULT);
     RamRelation vertex("vertex", 1, 1, {"x"}, {"i"}, RelationRepresentation::DEFAULT);
     // get vertices contain self loop
     // FOR t1 IN edge ON INDEX t1.x = t1.1 AND t1.y =
     //  PROJECT (t1.0) INTO vertex
     std::vector<std::unique_ptr<RamExpression>> a_project_args;
     a_project_args.emplace_back(new RamTupleElement(1, 0));
     auto a_project = std::make_unique<RamProject>(
             std::make_unique<RamRelationReference>(&vertex), std::move(a_project_args));
     RamPattern a_criteria;
     a_criteria.first.emplace_back(new RamTupleElement(1, 1));
     a_criteria.first.emplace_back(new RamUndefValue);
     a_criteria.second.emplace_back(new RamTupleElement(1, 1));
     a_criteria.second.emplace_back(new RamUndefValue);
     RamIndexScan a(std::make_unique<RamRelationReference>(&edge), 1, std::move(a_criteria),
             std::move(a_project), "RamIndexScan test");
     std::vector<std::unique_ptr<RamExpression>> b_project_args;
     b_project_args.emplace_back(new RamTupleElement(1, 0));
     auto b_project = std::make_unique<RamProject>(
             std::make_unique<RamRelationReference>(&vertex), std::move(b_project_args));
     RamPattern b_criteria;
     b_criteria.first.emplace_back(new RamTupleElement(1, 1));
     b_criteria.first.emplace_back(new RamUndefValue);
     b_criteria.second.emplace_back(new RamTupleElement(1, 1));
     b_criteria.second.emplace_back(new RamUndefValue);
     RamIndexScan b(std::make_unique<RamRelationReference>(&edge), 1, std::move(b_criteria),
             std::move(b_project), "RamIndexScan test");
     EXPECT_EQ(a, b);
     EXPECT_NE(&a, &b);
     RamIndexScan* c = a.clone();
     EXPECT_EQ(a, *c);
     EXPECT_NE(&a, c);
     delete c;
 }
TEST() [51/228]
souffle::test::TEST (RuleBody , ClauseBodyExtraction)
Definition at line 82 of file ast_parser_utils_test.cpp.
References souffle::RuleBody::atom(), souffle::RuleBody::conjunct(), souffle::RuleBody::disjunct(), EXPECT_EQ, souffle::RuleBody::getFalse(), souffle::RuleBody::getTrue(), souffle::RuleBody::toClauseBodies(), and souffle::toString().
{
     RuleBody body = RuleBody::getTrue();
     RuleBody AB = RuleBody::getTrue();
     AB.conjunct(RuleBody::atom(mk<AstAtom>("A")));
     AB.conjunct(RuleBody::atom(mk<AstAtom>("B")));
     EXPECT_EQ("A(),B()", toString(AB));
     RuleBody CD = RuleBody::getTrue();
     CD.conjunct(RuleBody::atom(mk<AstAtom>("C")));
     CD.conjunct(RuleBody::atom(mk<AstAtom>("D")));
     EXPECT_EQ("C(),D()", toString(CD));
     RuleBody EF = RuleBody::getTrue();
     EF.conjunct(RuleBody::atom(mk<AstAtom>("E")));
     EF.conjunct(RuleBody::atom(mk<AstAtom>("F")));
     EXPECT_EQ("E(),F()", toString(EF));
     RuleBody full = RuleBody::getFalse();
     full.disjunct(std::move(AB));
     full.disjunct(std::move(CD));
     full.disjunct(std::move(EF));
     EXPECT_EQ("A(),B();C(),D();E(),F()", toString(full));
     // extract the clause
     auto list = full.toClauseBodies();
     EXPECT_EQ(3, list.size());
     EXPECT_EQ(" :- \n   A(),\n   B().", toString(*list[0]));
     EXPECT_EQ(" :- \n   C(),\n   D().", toString(*list[1]));
     EXPECT_EQ(" :- \n   E(),\n   F().", toString(*list[2]));
 }
TEST() [52/228]
souffle::test::TEST (RamSwap , CloneAndEquals)
Definition at line 83 of file ram_statement_equal_clone_test.cpp.
References b, souffle::RamSwap::clone(), souffle::DEFAULT, EXPECT_EQ, and EXPECT_NE.
{
     // SWAP(A,B)
     RamRelation A("A", 1, 1, {"x"}, {"i"}, RelationRepresentation::DEFAULT);
     RamRelation B("B", 1, 1, {"x"}, {"i"}, RelationRepresentation::DEFAULT);
     RamSwap a(std::make_unique<RamRelationReference>(&A), std::make_unique<RamRelationReference>(&B));
     RamSwap b(std::make_unique<RamRelationReference>(&A), std::make_unique<RamRelationReference>(&B));
     EXPECT_EQ(a, b);
     EXPECT_NE(&a, &b);
     RamSwap* c = a.clone();
     EXPECT_EQ(a, *c);
     EXPECT_NE(&a, c);
     delete c;
 }
TEST() [53/228]
souffle::test::TEST (TypeSystem , isSubtypeOf_Basic)
Definition at line 84 of file type_system_test.cpp.
References souffle::TypeEnvironment::createType(), EXPECT_PRED2, souffle::TypeEnvironment::getType(), isNotSubtypeOf(), souffle::isSubtypeOf(), S, and souffle::toVector().
{
     TypeEnvironment env;
     // start with the two predefined types
     const Type& N = env.getType("number");
     const Type& S = env.getType("symbol");
     EXPECT_PRED2(isSubtypeOf, N, N);
     EXPECT_PRED2(isSubtypeOf, S, S);
     EXPECT_PRED2(isNotSubtypeOf, N, S);
     EXPECT_PRED2(isNotSubtypeOf, S, N);
     // check primitive type
     const Type& A = env.createType<SubsetType>("A", env.getType("number"));
     const Type& B = env.createType<SubsetType>("B", env.getType("number"));
     EXPECT_PRED2(isSubtypeOf, A, A);
     EXPECT_PRED2(isSubtypeOf, B, B);
     EXPECT_PRED2(isNotSubtypeOf, A, B);
     EXPECT_PRED2(isNotSubtypeOf, B, A);
     EXPECT_PRED2(isSubtypeOf, A, N);
     EXPECT_PRED2(isSubtypeOf, B, N);
     EXPECT_PRED2(isNotSubtypeOf, A, S);
     EXPECT_PRED2(isNotSubtypeOf, B, S);
     // check union types
     const Type& U = env.createType<UnionType>("U", toVector(&A, &B));
     EXPECT_PRED2(isSubtypeOf, U, U);
     EXPECT_PRED2(isSubtypeOf, A, U);
     EXPECT_PRED2(isSubtypeOf, B, U);
     EXPECT_PRED2(isSubtypeOf, U, N);
     EXPECT_PRED2(isNotSubtypeOf, U, A);
     EXPECT_PRED2(isNotSubtypeOf, U, B);
     EXPECT_PRED2(isNotSubtypeOf, N, U);
     auto& V = env.createType<UnionType>("V", toVector(&A, &B, &U));
     EXPECT_PRED2(isSubtypeOf, V, U);
     EXPECT_PRED2(isSubtypeOf, U, V);
 }
TEST() [54/228]
souffle::test::TEST (PackUnpack , Vector)
Definition at line 87 of file record_table_test.cpp.
References EXPECT_EQ, i, j, NUMBER_OF_TESTS, souffle::RecordTable::pack(), and souffle::RecordTable::unpack().
{
     constexpr size_t vectorSize = 10;
     RecordTable recordTable;
     // Tuples that will be packed
     std::vector<std::vector<RamDomain>> toPack(NUMBER_OF_TESTS);
     // Tuple reference after they are packed.
     std::vector<RamDomain> tupleRef(NUMBER_OF_TESTS);
     // Generate and pack the tuples
     for (size_t i = 0; i < NUMBER_OF_TESTS; ++i) {
         toPack[i] = testutil::generateRandomVector<RamDomain>(10);
         tupleRef[i] = recordTable.pack(toPack[i].data(), vectorSize);
         std::cerr << "Ref: " << tupleRef[i] << std::endl;
     }
     // unpack and test
     for (size_t i = 0; i < NUMBER_OF_TESTS; ++i) {
         const RamDomain* unpacked{recordTable.unpack(tupleRef[i], vectorSize)};
         for (size_t j = 0; j < vectorSize; ++j) {
             EXPECT_EQ(toPack[i][j], unpacked[j]);
         }
     }
 }
TEST() [55/228]
souffle::test::TEST (RamTupleElement , CloneAndEquals)
Definition at line 90 of file ram_expression_equal_clone_test.cpp.
References b, souffle::RamTupleElement::clone(), EXPECT_EQ, and EXPECT_NE.
{
     // t0.1
     RamTupleElement a(0, 1);
     RamTupleElement b(0, 1);
     EXPECT_EQ(a, b);
     EXPECT_NE(&a, &b);
     RamTupleElement* aClone = a.clone();
     EXPECT_EQ(a, *aClone);
     EXPECT_NE(&a, aClone);
     delete aClone;
 }
TEST() [56/228]
souffle::test::TEST (AstPrint , Variable)
Definition at line 91 of file ast_print_test.cpp.
References EXPECT_EQ, makeATU(), makeClauseA(), and makePrintedATU().
{
     auto testArgument = std::make_unique<AstVariable>("testVar");
     auto tu1 = makeATU();
     tu1->getProgram()->addClause(makeClauseA(std::move(testArgument)));
     auto tu2 = makePrintedATU(tu1);
     EXPECT_EQ(*tu1->getProgram(), *tu2->getProgram());
 }
TEST() [57/228]
souffle::test::TEST (Independence , Iteration)
Definition at line 94 of file interpreter_relation_test.cpp.
References EXPECT_EQ, souffle::InterpreterRelInterface::insert(), and souffle::MinIndexSelection::insertDefaultTotalIndex().
{
     // create a table
     SymbolTable symbolTable;
     MinIndexSelection order{};
     order.insertDefaultTotalIndex(1);
     InterpreterRelation rel(1, 0, "test", {"i"}, order);
     InterpreterRelInterface relInt(rel, symbolTable, "test", {"i"}, {"i"}, 0);
     // add a value
     relInt.insert(tuple(&relInt, {1}));
     // Test a iterator returns the correct value
     Relation::iterator it = relInt.begin();
     EXPECT_EQ(1, (*it)[0]);
     // Copy the iterator and modify the copy
     {
         Relation::iterator it2(it);
         EXPECT_EQ(1, (*it2)[0]);
         ++it2;
     }
     EXPECT_EQ(1, (*it)[0]);
     // Test that a new iterator is also valid
     Relation::iterator it3 = relInt.begin();
     EXPECT_EQ(1, (*it3)[0]);
 }
TEST() [58/228]
souffle::test::TEST (SymbolTable , Inserts)
Definition at line 96 of file symbol_table_test.cpp.
References souffle::duration_in_ns(), i, souffle::SymbolTable::insert(), n, and now().
{
     // whether to print the recorded times to stdout
     // should be false unless developing
     const bool ECHO_TIME = false;
     // type for very big number
     using T = unsigned long long;
     time_point start;
     time_point end;
     T n = 0;        // counter
     T N = 1000000;  // number of symbols to insert
     // T N = 10000000;   // larger tables for debugging/timing
     // T N = 100000000;  // larger tables for debugging/timing
     SymbolTable X;
     std::string x;
     std::vector<std::string> A;
     A.reserve(N);
     for (T i = 0; i < N; ++i) {
         x = std::to_string(i) + "string";
         A.push_back(x);
     }
     start = now();
     for (T i = 0; i < N; ++i) {
         X.insert(A[i]);  // insert one at a time
     }
     end = now();
     n = duration_in_ns(start, end);  // record the time
     if (ECHO_TIME) {
         std::cout << "Time to insert " << N << " new elements:      " << n << " ns" << std::endl;
     }
     // try inserting all the elements that were just inserted
     start = now();
     X.insert(A);
     end = now();
     n = duration_in_ns(start, end);
     if (ECHO_TIME) {
         std::cout << "Time to insert " << N << " existing elements: " << n << " ns" << std::endl;
     }
 }
TEST() [59/228]
souffle::test::TEST (RamNegation , CloneAndEquals)
Definition at line 97 of file ram_condition_equal_clone_test.cpp.
References b, d, EXPECT_EQ, and EXPECT_NE.
{
     auto a = std::make_unique<RamTrue>();
     auto neg_a = std::make_unique<RamNegation>(std::move(a));
     auto b = std::make_unique<RamTrue>();
     auto neg_b = std::make_unique<RamNegation>(std::move(b));
     EXPECT_EQ(*neg_a, *neg_b);
     EXPECT_NE(neg_a, neg_b);
     auto c = std::make_unique<RamFalse>();
     auto neg_neg_c = std::make_unique<RamNegation>(std::make_unique<RamNegation>(std::move(c)));
     auto d = std::make_unique<RamFalse>();
     auto neg_neg_d = std::make_unique<RamNegation>(std::make_unique<RamNegation>(std::move(d)));
     EXPECT_EQ(*neg_neg_c, *neg_neg_d);
     EXPECT_NE(neg_neg_c, neg_neg_d);
 }
TEST() [60/228]
souffle::test::TEST (AstTransformers , ResolveGroundedAliases)
Definition at line 97 of file ast_transformers_test.cpp.
References EXPECT_EQ, souffle::getClauses(), souffle::ParserDriver::parseTranslationUnit(), and souffle::toString().
{
     // load some test program
     ErrorReport errorReport;
     DebugReport debugReport;
     std::unique_ptr<AstTranslationUnit> tu = ParserDriver::parseTranslationUnit(
             R"(
                 .type D <: symbol
                 .decl p(a:D,b:D)
                 p(a,b) :- p(x,y), r = [x,y], s = r, s = [w,v], [w,v] = [a,b].
             )",
             errorReport, debugReport);
     AstProgram& program = *tu->getProgram();
     EXPECT_EQ("p(a,b) :- \n   p(x,y),\n   r = [x,y],\n   s = r,\n   s = [w,v],\n   [w,v] = [a,b].",
             toString(*getClauses(program, "p")[0]));
     std::make_unique<ResolveAliasesTransformer>()->apply(*tu);
     EXPECT_EQ("p(x,y) :- \n   p(x,y).", toString(*getClauses(program, "p")[0]));
 }
TEST() [61/228]
souffle::test::TEST (EqRelTest , Duplicates)
Definition at line 98 of file binary_relation_test.cpp.
References souffle::EquivalenceRelation< TupleType >::begin(), souffle::EquivalenceRelation< TupleType >::contains(), souffle::EquivalenceRelation< TupleType >::end(), EXPECT_EQ, EXPECT_FALSE, EXPECT_TRUE, i, souffle::EquivalenceRelation< TupleType >::insert(), and souffle::EquivalenceRelation< TupleType >::size().
{
     EqRel br;
     // test inserting same pair
     for (int i = 0; i < 10; ++i) {
         br.insert(0, 0);
     }
     EXPECT_EQ(br.size(), 1);
     for (int i = 0; i < 10; ++i) {
         EXPECT_TRUE(br.contains(0, 0));
     }
     EXPECT_EQ(br.size(), 1);
     EXPECT_FALSE(br.contains(1, 1));
     // check iteration of duplicate is fine
     Tuple<RamDomain, 2> tup{};
     tup[0] = 0;
     tup[1] = 0;
     auto x = br.begin();
     EXPECT_EQ(tup, *x);
     ++x;
     EXPECT_EQ(x, br.end());
 }
TEST() [62/228]
souffle::test::TEST (RamQuery , CloneAndEquals)
Definition at line 98 of file ram_statement_equal_clone_test.cpp.
References b, souffle::RamQuery::clone(), d, souffle::DEFAULT, e, souffle::EQ, EXPECT_EQ, and EXPECT_NE.
{
     RamRelation A("A", 3, 1, {"a", "b", "c"}, {"i", "s", "i"}, RelationRepresentation::DEFAULT);
     RamRelation B("B", 2, 1, {"a", "c"}, {"i", "i"}, RelationRepresentation::DEFAULT);
     /*
      * QUERY
      *  FOR t0 IN A
      *   PROJECT (t0.0, t0.2) INTO B
      */
     std::vector<std::unique_ptr<RamExpression>> a_expressions;
     a_expressions.emplace_back(new RamTupleElement(0, 0));
     a_expressions.emplace_back(new RamTupleElement(0, 2));
     auto a_project = std::make_unique<RamProject>(
             std::make_unique<RamRelationReference>(&B), std::move(a_expressions));
     auto a_scan = std::make_unique<RamScan>(
             std::make_unique<RamRelationReference>(&A), 0, std::move(a_project), "");
     std::vector<std::unique_ptr<RamExpression>> b_expressions;
     b_expressions.emplace_back(new RamTupleElement(0, 0));
     b_expressions.emplace_back(new RamTupleElement(0, 2));
     auto b_project = std::make_unique<RamProject>(
             std::make_unique<RamRelationReference>(&B), std::move(b_expressions));
     auto b_scan = std::make_unique<RamScan>(
             std::make_unique<RamRelationReference>(&A), 0, std::move(b_project), "");
     RamQuery a(std::move(a_scan));
     RamQuery b(std::move(b_scan));
     EXPECT_EQ(a, b);
     EXPECT_NE(&a, &b);
     RamQuery* c = a.clone();
     EXPECT_EQ(a, *c);
     EXPECT_NE(&a, c);
     delete c;
     /*
      * QUERY
      *  PARALLEL CHOICE t1 IN A WHERE (t1.0 = 0)
      *   RETURN (t1.2)
      */
     std::vector<std::unique_ptr<RamExpression>> d_return_value;
     d_return_value.emplace_back(new RamTupleElement(1, 0));
     auto d_return = std::make_unique<RamSubroutineReturn>(std::move(d_return_value));
     // condition t1.0 = 0
     auto d_cond = std::make_unique<RamConstraint>(BinaryConstraintOp::EQ,
             std::make_unique<RamTupleElement>(1, 0), std::make_unique<RamSignedConstant>(0));
     auto d_parallel_choice = std::make_unique<RamParallelChoice>(
             std::make_unique<RamRelationReference>(&A), 1, std::move(d_cond), std::move(d_return), "");
     std::vector<std::unique_ptr<RamExpression>> e_return_value;
     e_return_value.emplace_back(new RamTupleElement(1, 0));
     auto e_return = std::make_unique<RamSubroutineReturn>(std::move(e_return_value));
     // condition t1.0 = 0
     auto e_cond = std::make_unique<RamConstraint>(BinaryConstraintOp::EQ,
             std::make_unique<RamTupleElement>(1, 0), std::make_unique<RamSignedConstant>(0));
     auto e_parallel_choice = std::make_unique<RamParallelChoice>(
             std::make_unique<RamRelationReference>(&A), 1, std::move(e_cond), std::move(e_return), "");
     RamQuery d(std::move(d_parallel_choice));
     RamQuery e(std::move(e_parallel_choice));
     EXPECT_EQ(d, e);
     EXPECT_NE(&d, &e);
     RamQuery* f = d.clone();
     EXPECT_EQ(d, *f);
     EXPECT_NE(&d, f);
     delete f;
 }
TEST() [63/228]
souffle::test::TEST (AstUtils , GroundedRecords)
Definition at line 99 of file ast_utils_test.cpp.
References d, e, EXPECT_EQ, EXPECT_TRUE, souffle::AstAtom::getArguments(), souffle::AstClause::getBodyLiterals(), souffle::getClauses(), souffle::getGroundedTerms(), souffle::AstClause::getHead(), souffle::ParserDriver::parseTranslationUnit(), and souffle::toString().
{
     ErrorReport e;
     DebugReport d;
     std::unique_ptr<AstTranslationUnit> tu = ParserDriver::parseTranslationUnit(
             R"(
                  .type N <: symbol
                  .type R = [ a : N, B : N ]
                  .decl r ( r : R )
                  .decl s ( r : N )
                  s(x) :- r([x,y]).
             )",
             e, d);
     AstProgram& program = *tu->getProgram();
     AstClause* clause = getClauses(program, "s")[0];
     // check construction
     EXPECT_EQ("s(x) :- \n   r([x,y]).", toString(*clause));
     // obtain groundness
     auto isGrounded = getGroundedTerms(*tu, *clause);
     const AstAtom* s = clause->getHead();
     const auto* r = dynamic_cast<const AstAtom*>(clause->getBodyLiterals()[0]);
     EXPECT_TRUE(s);
     EXPECT_TRUE(r);
     // check selected sub-terms
     EXPECT_TRUE(isGrounded[s->getArguments()[0]]);
     EXPECT_TRUE(isGrounded[r->getArguments()[0]]);
 }
TEST() [64/228]
souffle::test::TEST (PiggyTest , Scoping)
Regular Old Piggy List.
Definition at line 99 of file eqrel_datastructure_test.cpp.
{
     // simply test that namespaces were setup correctly (compile time)
     souffle::PiggyList<size_t> pl;
 }
TEST() [65/228]
souffle::test::TEST (AstPrint , UnnamedVariable)
Definition at line 100 of file ast_print_test.cpp.
References EXPECT_EQ, makeATU(), makeClauseA(), and makePrintedATU().
{
     auto testArgument = std::make_unique<AstUnnamedVariable>();
     auto tu1 = makeATU();
     tu1->getProgram()->addClause(makeClauseA(std::move(testArgument)));
     auto tu2 = makePrintedATU(tu1);
     EXPECT_EQ(*tu1->getProgram(), *tu2->getProgram());
 }
TEST() [66/228]
souffle::test::TEST (IO_store , FloatSimple)
Definition at line 100 of file ram_relation_test.cpp.
References EXPECT_EQ, souffle::ramBitCast(), and testInterpreterStore().
{
     std::vector<std::string> attribs = {"a", "b"};
     std::vector<std::string> attribsTypes = {"f", "f"};
     std::vector<std::unique_ptr<RamExpression>> exprs;
     exprs.push_back(std::make_unique<RamSignedConstant>(ramBitCast(static_cast<RamFloat>(0.5))));
     exprs.push_back(std::make_unique<RamSignedConstant>(ramBitCast(static_cast<RamFloat>(0.5))));
     std::string expected = R"(---------------
 test
 ===============
 0.5 0.5
 ===============
 )";
     auto result = testInterpreterStore(attribs, attribsTypes, std::move(exprs));
     EXPECT_EQ(expected, result);
 }
TEST() [67/228]
souffle::test::TEST (RamSignedConstant , CloneAndEquals)
Definition at line 103 of file ram_expression_equal_clone_test.cpp.
References b, souffle::RamSignedConstant::clone(), EXPECT_EQ, and EXPECT_NE.
{
     // number(5)
     RamSignedConstant a(5);
     RamSignedConstant b(5);
     EXPECT_EQ(a, b);
     EXPECT_NE(&a, &b);
     RamSignedConstant* aClone = a.clone();
     EXPECT_EQ(a, *aClone);
     EXPECT_NE(&a, aClone);
     delete aClone;
 }
TEST() [68/228]
souffle::test::TEST (PiggyTest , Append)
Definition at line 104 of file eqrel_datastructure_test.cpp.
References souffle::PiggyList< T >::append(), EXPECT_EQ, souffle::PiggyList< T >::get(), i, and souffle::PiggyList< T >::size().
{
     souffle::PiggyList<size_t> pl;
     EXPECT_EQ(pl.size(), 0);
     pl.append(99);
     EXPECT_EQ(pl.size(), 1);
     pl.append(99);
     pl.append(99);
     EXPECT_EQ(pl.size(), 3);
     EXPECT_EQ(pl.get(0), 99);
     EXPECT_EQ(pl.get(1), 99);
     EXPECT_EQ(pl.get(2), 99);
     // larger than BLOCKSIZE
     constexpr size_t N = 10000;
     for (size_t i = 0; i < N; ++i) {
         pl.append(2);
     }
     EXPECT_EQ(pl.size(), N + 3);
     // make sure that all of our inserties are exacties
     for (size_t i = 3; i < N + 3; ++i) {
         EXPECT_EQ(pl.get(i), 2);
     }
 }
TEST() [69/228]
souffle::test::TEST (AstPrint , Counter)
Definition at line 109 of file ast_print_test.cpp.
References EXPECT_EQ, makeATU(), makeClauseA(), and makePrintedATU().
{
     auto testArgument = std::make_unique<AstCounter>();
     auto tu1 = makeATU();
     tu1->getProgram()->addClause(makeClauseA(std::move(testArgument)));
     auto tu2 = makePrintedATU(tu1);
     EXPECT_EQ(*tu1->getProgram(), *tu2->getProgram());
 }
TEST() [70/228]
souffle::test::TEST (RamSignedConstant , ArithmeticEvaluation)
Definition at line 111 of file ram_arithmetic_test.cpp.
References evalExpression(), and EXPECT_EQ.
{
     RamDomain num = 42;
     std::unique_ptr<RamExpression> expression = std::make_unique<RamSignedConstant>(num);
     RamDomain result = evalExpression(std::move(expression));
     EXPECT_EQ(result, num);
 }
TEST() [71/228]
souffle::test::TEST (RamConstraint , CloneAndEquals)
Definition at line 113 of file ram_condition_equal_clone_test.cpp.
References b, d, e, souffle::EQ, EXPECT_EQ, and EXPECT_NE.
{
     // constraint t0.1 = t1.0
     std::unique_ptr<RamExpression> a_lhs(new RamTupleElement(0, 1));
     std::unique_ptr<RamExpression> a_rhs(new RamTupleElement(1, 0));
     std::unique_ptr<RamConstraint> a(
             new RamConstraint(BinaryConstraintOp::EQ, std::move(a_lhs), std::move(a_rhs)));
     std::unique_ptr<RamExpression> b_lhs(new RamTupleElement(0, 1));
     std::unique_ptr<RamExpression> b_rhs(new RamTupleElement(1, 0));
     std::unique_ptr<RamConstraint> b(
             new RamConstraint(BinaryConstraintOp::EQ, std::move(b_lhs), std::move(b_rhs)));
     EXPECT_EQ(*a, *b);
     EXPECT_NE(a, b);
     std::unique_ptr<RamConstraint> c(a->clone());
     EXPECT_EQ(*a, *c);
     EXPECT_EQ(*b, *c);
     EXPECT_NE(a, c);
     EXPECT_NE(b, c);
     // constraint t2.0 >= 5
     std::unique_ptr<RamExpression> d_lhs(new RamTupleElement(2, 0));
     std::unique_ptr<RamExpression> d_rhs(new RamSignedConstant(5));
     std::unique_ptr<RamConstraint> d(
             new RamConstraint(BinaryConstraintOp::EQ, std::move(d_lhs), std::move(d_rhs)));
     std::unique_ptr<RamExpression> e_lhs(new RamTupleElement(2, 0));
     std::unique_ptr<RamExpression> e_rhs(new RamSignedConstant(5));
     std::unique_ptr<RamConstraint> e(
             new RamConstraint(BinaryConstraintOp::EQ, std::move(e_lhs), std::move(e_rhs)));
     EXPECT_EQ(*d, *e);
     EXPECT_NE(d, e);
     std::unique_ptr<RamConstraint> f(d->clone());
     EXPECT_EQ(*d, *f);
     EXPECT_EQ(*e, *f);
     EXPECT_NE(d, f);
     EXPECT_NE(e, f);
 }
TEST() [72/228]
souffle::test::TEST (RamAutoIncrement , CloneAndEquals)
Definition at line 116 of file ram_expression_equal_clone_test.cpp.
References b, souffle::RamAutoIncrement::clone(), EXPECT_EQ, and EXPECT_NE.
{
     RamAutoIncrement a;
     RamAutoIncrement b;
     EXPECT_EQ(a, b);
     EXPECT_NE(&a, &b);
     RamAutoIncrement* aClone = a.clone();
     EXPECT_EQ(a, *aClone);
     EXPECT_NE(&a, aClone);
     delete aClone;
 }
TEST() [73/228]
souffle::test::TEST (AstPrint , AggregatorMin)
Definition at line 118 of file ast_print_test.cpp.
References EXPECT_EQ, makeATU(), makeClauseA(), makePrintedATU(), and souffle::MIN.
{
     auto atom = std::make_unique<AstAtom>("B");
     atom->addArgument(std::make_unique<AstVariable>("x"));
     auto min = std::make_unique<AstAggregator>(AggregateOp::MIN, std::make_unique<AstVariable>("x"));
     std::vector<std::unique_ptr<AstLiteral>> body;
     body.push_back(std::make_unique<AstAtom>("B"));
     min->setBody(std::move(body));
     auto tu1 = makeATU();
     auto* prog1 = tu1->getProgram();
     prog1->addClause(makeClauseA(std::move(min)));
     auto tu2 = makePrintedATU(tu1);
     EXPECT_EQ(*tu1->getProgram(), *tu2->getProgram());
 }
TEST() [74/228]
souffle::test::TEST (Unary , Neg)
Definition at line 118 of file ram_arithmetic_test.cpp.
References evalUnary(), EXPECT_EQ, souffle::NEG, and TESTS_PER_OPERATION.
                  {
     for (RamDomain randomNumber : testutil::generateRandomVector<RamDomain>(TESTS_PER_OPERATION)) {
         EXPECT_EQ(evalUnary(FunctorOp::NEG, randomNumber), -randomNumber);
     }
 }
TEST() [75/228]
souffle::test::TEST (IO_store , Signed)
Definition at line 119 of file ram_relation_test.cpp.
References EXPECT_EQ, i, RANDOM_TESTS, and testInterpreterStore().
{
     std::vector<RamDomain> randomNumbers = testutil::generateRandomVector<RamDomain>(RANDOM_TESTS);
     // a0 a1 a2...
     std::vector<std::string> attribs(RANDOM_TESTS, "a");
     for (size_t i = 0; i < RANDOM_TESTS; ++i) {
         attribs[i].append(std::to_string(i));
     }
     std::vector<std::string> attribsTypes(RANDOM_TESTS, "i");
     std::vector<std::unique_ptr<RamExpression>> exprs;
     for (RamDomain i : randomNumbers) {
         exprs.push_back(std::make_unique<RamSignedConstant>(i));
     }
     std::stringstream expected;
     expected << "---------------"
              << "\n"
              << "test"
              << "\n"
              << "==============="
              << "\n"
              << randomNumbers[0];
     for (size_t i = 1; i < randomNumbers.size(); ++i) {
         expected << "\t" << randomNumbers[i];
     }
     expected << "\n"
              << "==============="
              << "\n";
     auto result = testInterpreterStore(attribs, attribsTypes, std::move(exprs));
     EXPECT_EQ(expected.str(), result);
 }
TEST() [76/228]
souffle::test::TEST (AstTransformers , ResolveAliasesWithTermsInAtoms)
Definition at line 120 of file ast_transformers_test.cpp.
References EXPECT_EQ, souffle::getClauses(), souffle::ParserDriver::parseTranslationUnit(), and souffle::toString().
{
     // load some test program
     ErrorReport errorReport;
     DebugReport debugReport;
     std::unique_ptr<AstTranslationUnit> tu = ParserDriver::parseTranslationUnit(
             R"(
                 .type D <: symbol
                 .decl p(a:D,b:D)
                 p(x,c) :- p(x,b), p(b,c), c = b+1, x=c+2.
             )",
             errorReport, debugReport);
     AstProgram& program = *tu->getProgram();
     EXPECT_EQ("p(x,c) :- \n   p(x,b),\n   p(b,c),\n   c = (b+1),\n   x = (c+2).",
             toString(*getClauses(program, "p")[0]));
     std::make_unique<ResolveAliasesTransformer>()->apply(*tu);
     EXPECT_EQ("p(x,c) :- \n   p(x,b),\n   p(b,c),\n   c = (b+1),\n   x = (c+2).",
             toString(*getClauses(program, "p")[0]));
 }
TEST() [77/228]
souffle::test::TEST (RamParallelIndexScan , CloneAndEquals)
Definition at line 121 of file ram_operation_equal_clone_test.cpp.
References b, souffle::RamParallelIndexScan::clone(), souffle::DEFAULT, EXPECT_EQ, and EXPECT_NE.
{
     RamRelation edge("edge", 2, 1, {"x", "y"}, {"i", "i"}, RelationRepresentation::DEFAULT);
     RamRelation new_edge("new_edge", 2, 1, {"x", "y"}, {"i", "i"}, RelationRepresentation::DEFAULT);
     // get edges direct to vertex 5
     // PARALLEL FOR t1 IN edge ON INDEX t1.x =  AND t1.y = 5
     //  PROJECT (t1.0, t1.1) INTO new_edge
     std::vector<std::unique_ptr<RamExpression>> a_project_args;
     a_project_args.emplace_back(new RamTupleElement(1, 0));
     a_project_args.emplace_back(new RamTupleElement(1, 1));
     auto a_project = std::make_unique<RamProject>(
             std::make_unique<RamRelationReference>(&new_edge), std::move(a_project_args));
     RamPattern a_criteria;
     a_criteria.first.emplace_back(new RamUndefValue);
     a_criteria.first.emplace_back(new RamSignedConstant(5));
     a_criteria.second.emplace_back(new RamUndefValue);
     a_criteria.second.emplace_back(new RamSignedConstant(5));
     RamParallelIndexScan a(std::make_unique<RamRelationReference>(&edge), 1, std::move(a_criteria),
             std::move(a_project), "RamParallelIndexScan test");
     std::vector<std::unique_ptr<RamExpression>> b_project_args;
     b_project_args.emplace_back(new RamTupleElement(1, 0));
     b_project_args.emplace_back(new RamTupleElement(1, 1));
     auto b_project = std::make_unique<RamProject>(
             std::make_unique<RamRelationReference>(&new_edge), std::move(b_project_args));
     RamPattern b_criteria;
     b_criteria.first.emplace_back(new RamUndefValue);
     b_criteria.first.emplace_back(new RamSignedConstant(5));
     b_criteria.second.emplace_back(new RamUndefValue);
     b_criteria.second.emplace_back(new RamSignedConstant(5));
     RamParallelIndexScan b(std::make_unique<RamRelationReference>(&edge), 1, std::move(b_criteria),
             std::move(b_project), "RamParallelIndexScan test");
     EXPECT_EQ(a, b);
     EXPECT_NE(&a, &b);
     RamParallelIndexScan* c = a.clone();
     EXPECT_EQ(a, *c);
     EXPECT_NE(&a, c);
     delete c;
 }
TEST() [78/228]
souffle::test::TEST (EqRelTest , TransitivityTest)
Definition at line 122 of file binary_relation_test.cpp.
References count(), EXPECT_EQ, EXPECT_TRUE, testutil::ignore(), souffle::EquivalenceRelation< TupleType >::insert(), and souffle::EquivalenceRelation< TupleType >::size().
{
     // test (a,b) && (b, c) => (a,c) etc
     EqRel br;
     br.insert(1, 2);
     br.insert(2, 3);
     EXPECT_EQ(br.size(), 9);
     size_t count = 0;
     for (auto x : br) {
         ++count;
         testutil::ignore(x);
     }
     EXPECT_EQ(count, br.size());
     EXPECT_TRUE(br.contains(1, 1));
     EXPECT_TRUE(br.contains(1, 2));
     EXPECT_TRUE(br.contains(1, 3));
     EXPECT_TRUE(br.contains(2, 1));
     EXPECT_TRUE(br.contains(2, 2));
     EXPECT_TRUE(br.contains(2, 3));
     EXPECT_TRUE(br.contains(3, 1));
     EXPECT_TRUE(br.contains(3, 2));
     EXPECT_TRUE(br.contains(3, 3));
 }
TEST() [79/228]
souffle::test::TEST (IndependentMoving , Iteration)
Definition at line 122 of file interpreter_relation_test.cpp.
References EXPECT_EQ, souffle::InterpreterRelInterface::insert(), and souffle::MinIndexSelection::insertDefaultTotalIndex().
{
     // create a table
     SymbolTable symbolTable;
     MinIndexSelection order{};
     order.insertDefaultTotalIndex(1);
     InterpreterRelation rel(1, 0, "test", {"i"}, order);
     InterpreterRelInterface relInt(rel, symbolTable, "test", {"i"}, {"i"}, 0);
     // add a value
     relInt.insert(tuple(&relInt, {1}));
     Relation::iterator it = relInt.begin();
     EXPECT_EQ(1, (*it)[0]);
     // Make a new iterator, move it to the first iterator, then let the new iterator go out of scope
     {
         Relation::iterator it2(relInt.begin());
         EXPECT_EQ(1, (*it2)[0]);
         it = std::move(it2);
     }
     EXPECT_EQ(1, (*it)[0]);
 }
TEST() [80/228]
souffle::test::TEST (AstProgram , RemoveClause)
test removeClause, addRelation and removeRelation
Definition at line 123 of file ast_program_test.cpp.
                           : symbol
                  .type B <: symbol
                  .type U = A | B
                  .decl a ( x : A )
                  .decl b ( x : B )
                  .decl u ( x : U )
                  a(X) :- u(X).
                  b(X) :- u(X).
                  u(X) :- u(X).
                  a(X) :- b(X).
TEST() [81/228]
souffle::test::TEST (Unary , FloatNeg)
Definition at line 124 of file ram_arithmetic_test.cpp.
References evalUnary(), EXPECT_EQ, souffle::FNEG, souffle::ramBitCast(), and TESTS_PER_OPERATION.
                       {
     FunctorOp functor = FunctorOp::FNEG;
     for (auto randomNumber : testutil::generateRandomVector<RamFloat>(TESTS_PER_OPERATION)) {
         auto result = evalUnary(functor, ramBitCast(randomNumber));
         EXPECT_EQ(ramBitCast<RamFloat>(result), -randomNumber);
     }
 }
TEST() [82/228]
souffle::test::TEST (RamUndefValue , CloneAndEquals)
Definition at line 128 of file ram_expression_equal_clone_test.cpp.
References b, souffle::RamUndefValue::clone(), EXPECT_EQ, and EXPECT_NE.
{
     RamUndefValue a;
     RamUndefValue b;
     EXPECT_EQ(a, b);
     EXPECT_NE(&a, &b);
     RamUndefValue* aClone = a.clone();
     EXPECT_EQ(a, *aClone);
     EXPECT_NE(&a, aClone);
     delete aClone;
 }
TEST() [83/228]
souffle::test::TEST (PiggyTest , ElementCreation)
Definition at line 129 of file eqrel_datastructure_test.cpp.
References souffle::PiggyList< T >::createNode(), EXPECT_EQ, souffle::PiggyList< T >::get(), and souffle::PiggyList< T >::size().
{
     // test that we can use makeNode() and set the values properly
     souffle::PiggyList<size_t> pl;
     pl.get(pl.createNode()) = 99;
     EXPECT_EQ(pl.size(), 1);
     EXPECT_EQ(pl.get(0), 99);
 }
TEST() [84/228]
souffle::test::TEST (Unary , BinaryNot)
Definition at line 133 of file ram_arithmetic_test.cpp.
References souffle::BNOT, evalUnary(), EXPECT_EQ, and TESTS_PER_OPERATION.
{
     FunctorOp functor = FunctorOp::BNOT;
     for (auto randomNumber : testutil::generateRandomVector<RamDomain>(TESTS_PER_OPERATION)) {
         EXPECT_EQ(evalUnary(functor, randomNumber), ~randomNumber);
     }
 }
TEST() [85/228]
souffle::test::TEST (TypeSystem , isSubtypeOf_Records)
Definition at line 134 of file type_system_test.cpp.
References souffle::TypeEnvironment::createType(), EXPECT_FALSE, souffle::TypeEnvironment::getType(), souffle::isSubtypeOf(), souffle::RecordType::setFields(), and souffle::toVector().
{
     TypeEnvironment env;
     const Type& A = env.createType<SubsetType>("A", env.getType("number"));
     const Type& B = env.createType<SubsetType>("B", env.getType("number"));
     auto& R1 = env.createType<RecordType>("R1");
     auto& R2 = env.createType<RecordType>("R2");
     EXPECT_FALSE(isSubtypeOf(R1, R2));
     EXPECT_FALSE(isSubtypeOf(R2, R1));
     R1.setFields(toVector(&A));
     R2.setFields(toVector(&B));
     EXPECT_FALSE(isSubtypeOf(R1, R2));
     EXPECT_FALSE(isSubtypeOf(R2, R1));
 }
TEST() [86/228]
souffle::test::TEST (AstPrint , AggregatorMax)
Definition at line 135 of file ast_print_test.cpp.
References EXPECT_EQ, makeATU(), makeClauseA(), makePrintedATU(), and souffle::MAX.
{
     auto atom = std::make_unique<AstAtom>("B");
     atom->addArgument(std::make_unique<AstVariable>("x"));
     auto max = std::make_unique<AstAggregator>(AggregateOp::MAX, std::make_unique<AstVariable>("x"));
     std::vector<std::unique_ptr<AstLiteral>> body;
     body.push_back(std::move(atom));
     max->setBody(std::move(body));
     auto tu1 = makeATU();
     auto* prog1 = tu1->getProgram();
     prog1->addClause(makeClauseA(std::move(max)));
     auto tu2 = makePrintedATU(tu1);
     EXPECT_EQ(*tu1->getProgram(), *tu2->getProgram());
 }
TEST() [87/228]
souffle::test::TEST (AstUtils , ReorderClauseAtoms)
Definition at line 136 of file ast_utils_test.cpp.
References clauses, d, e, EXPECT_EQ, EXPECT_NE, souffle::getClauses(), souffle::getRelation(), souffle::AstProgram::getRelations(), souffle::ParserDriver::parseTranslationUnit(), souffle::reorderAtoms(), and souffle::toString().
{
     ErrorReport e;
     DebugReport d;
     std::unique_ptr<AstTranslationUnit> tu = ParserDriver::parseTranslationUnit(
             R"(
                 .decl a,b,c,d,e(x:number)
                 a(x) :- b(x), c(x), 1 != 2, d(y), !e(z), c(z), e(x).
                 .output a()
             )",
             e, d);
     AstProgram& program = *tu->getProgram();
     EXPECT_EQ(5, program.getRelations().size());
     AstRelation* a = getRelation(program, "a");
     EXPECT_NE(a, nullptr);
     const auto& clauses = getClauses(program, *a);
     EXPECT_EQ(1, clauses.size());
     AstClause* clause = clauses[0];
     EXPECT_EQ("a(x) :- \n   b(x),\n   c(x),\n   1 != 2,\n   d(y),\n   !e(z),\n   c(z),\n   e(x).",
             toString(*clause));
     // Check trivial permutation
     std::unique_ptr<AstClause> reorderedClause0 =
             std::unique_ptr<AstClause>(reorderAtoms(clause, std::vector<unsigned int>({0, 1, 2, 3, 4})));
     EXPECT_EQ("a(x) :- \n   b(x),\n   c(x),\n   1 != 2,\n   d(y),\n   !e(z),\n   c(z),\n   e(x).",
             toString(*reorderedClause0));
     // Check more complex permutation
     std::unique_ptr<AstClause> reorderedClause1 =
             std::unique_ptr<AstClause>(reorderAtoms(clause, std::vector<unsigned int>({2, 3, 4, 1, 0})));
     EXPECT_EQ("a(x) :- \n   d(y),\n   c(z),\n   1 != 2,\n   e(x),\n   !e(z),\n   c(x),\n   b(x).",
             toString(*reorderedClause1));
 }
TEST() [88/228]
souffle::test::TEST (PiggyTest , Iteration)
Definition at line 137 of file eqrel_datastructure_test.cpp.
References souffle::PiggyList< T >::append(), e, EXPECT_EQ, and i.
{
     souffle::PiggyList<size_t> pl;
     constexpr size_t N = 10000;
     for (size_t i = 0; i < N; ++i) {
         pl.append(i);
     }
     size_t counter = 0;
     for (size_t e : pl) {
         EXPECT_EQ(e, counter++);
     }
 }
TEST() [89/228]
souffle::test::TEST (AstProgram , AppendAstRelation)
Definition at line 139 of file ast_program_test.cpp.
                           : symbol
                  .type B <: number
                  .type U = B
                  .decl a ( x : A )
TEST() [90/228]
souffle::test::TEST (RamPackRecord , CloneAndEquals)
Definition at line 140 of file ram_expression_equal_clone_test.cpp.
References b, souffle::RamPackRecord::clone(), d, e, EXPECT_EQ, and EXPECT_NE.
{
     // {number{10), number(5), , }
     std::vector<std::unique_ptr<RamExpression>> a_args;
     a_args.emplace_back(new RamSignedConstant(10));
     a_args.emplace_back(new RamSignedConstant(5));
     a_args.emplace_back(new RamUndefValue);
     a_args.emplace_back(new RamUndefValue);
     RamPackRecord a(std::move(a_args));
     std::vector<std::unique_ptr<RamExpression>> b_args;
     b_args.emplace_back(new RamSignedConstant(10));
     b_args.emplace_back(new RamSignedConstant(5));
     b_args.emplace_back(new RamUndefValue);
     b_args.emplace_back(new RamUndefValue);
     RamPackRecord b(std::move(b_args));
     EXPECT_EQ(a, b);
     EXPECT_NE(&a, &b);
     RamPackRecord* aClone = a.clone();
     EXPECT_EQ(a, *aClone);
     EXPECT_NE(&a, aClone);
     delete aClone;
     // {, {argument(1), number(0)}, t1.3}
     std::vector<std::unique_ptr<RamExpression>> d_args;
     d_args.emplace_back(new RamUndefValue);
     std::vector<std::unique_ptr<RamExpression>> d_record;
     d_record.emplace_back(new RamSubroutineArgument(1));
     d_record.emplace_back(new RamSignedConstant(5));
     d_args.emplace_back(new RamPackRecord(std::move(d_record)));
     d_args.emplace_back(new RamTupleElement(1, 3));
     RamPackRecord d(std::move(d_args));
     std::vector<std::unique_ptr<RamExpression>> e_args;
     e_args.emplace_back(new RamUndefValue);
     std::vector<std::unique_ptr<RamExpression>> e_record;
     e_record.emplace_back(new RamSubroutineArgument(1));
     e_record.emplace_back(new RamSignedConstant(5));
     e_args.emplace_back(new RamPackRecord(std::move(e_record)));
     e_args.emplace_back(new RamTupleElement(1, 3));
     RamPackRecord e(std::move(e_args));
     EXPECT_EQ(d, e);
     EXPECT_NE(&d, &e);
     RamPackRecord* dClone = d.clone();
     EXPECT_EQ(d, *dClone);
     EXPECT_NE(&d, dClone);
     delete dClone;
 }
TEST() [91/228]
souffle::test::TEST (Unary , UnsignedBinaryNot)
Definition at line 141 of file ram_arithmetic_test.cpp.
References evalUnary(), EXPECT_EQ, souffle::ramBitCast(), TESTS_PER_OPERATION, and souffle::UBNOT.
{
     FunctorOp functor = FunctorOp::UBNOT;
     for (auto randomNumber : testutil::generateRandomVector<RamUnsigned>(TESTS_PER_OPERATION)) {
         RamDomain result = evalUnary(functor, ramBitCast(randomNumber));
         EXPECT_EQ(ramBitCast<RamUnsigned>(result), ~randomNumber);
     }
 }
TEST() [92/228]
souffle::test::TEST (EqRelTest , PairwiseIncremental)
Definition at line 145 of file binary_relation_test.cpp.
References souffle::EquivalenceRelation< TupleType >::contains(), count(), EXPECT_EQ, EXPECT_TRUE, i, testutil::ignore(), souffle::EquivalenceRelation< TupleType >::insert(), and souffle::EquivalenceRelation< TupleType >::size().
{
     EqRel br;
     const size_t N = 100;
     // test inserting ascending pairs still isolates them
     for (size_t i = 1; i < N; ++i) {
         br.insert(i, i);
         EXPECT_TRUE(br.contains(i, i));
         br.insert(i + (N + 1), i);
         EXPECT_TRUE(br.contains(i, i + (N + 1)));
         EXPECT_TRUE(br.contains(i + (N + 1), i + (N + 1)));
         EXPECT_TRUE(br.contains(i + (N + 1), i));
     }
     EXPECT_EQ(br.size(), (N - 1) * 4);
     size_t count = 0;
     for (auto x : br) {
         ++count;
         testutil::ignore(x);
     }
     EXPECT_EQ(count, br.size());
 }
TEST() [93/228]
souffle::test::TEST (IndependentCopying , Iteration)
Definition at line 145 of file interpreter_relation_test.cpp.
References EXPECT_EQ, souffle::InterpreterRelInterface::insert(), and souffle::MinIndexSelection::insertDefaultTotalIndex().
{
     // create a table
     SymbolTable symbolTable;
     MinIndexSelection order{};
     order.insertDefaultTotalIndex(1);
     InterpreterRelation rel(1, 0, "test", {"i"}, order);
     InterpreterRelInterface relInt(rel, symbolTable, "test", {"i"}, {"i"}, 0);
     // add a value
     relInt.insert(tuple(&relInt, {1}));
     Relation::iterator it = relInt.begin();
     EXPECT_EQ(1, (*it)[0]);
     // Make a new iterator, copy it to the first iterator, then let the new iterator go out of scope
     {
         Relation::iterator it2(relInt.begin());
         EXPECT_EQ(1, (*it2)[0]);
         it = it2;
     }
     EXPECT_EQ(1, (*it)[0]);
 }
TEST() [94/228]
souffle::test::TEST (PiggyTest , CopyCtor)
Definition at line 149 of file eqrel_datastructure_test.cpp.
References souffle::PiggyList< T >::append(), souffle::PiggyList< T >::begin(), souffle::PiggyList< T >::clear(), souffle::PiggyList< T >::end(), EXPECT_EQ, EXPECT_FALSE, souffle::PiggyList< T >::get(), i, and souffle::PiggyList< T >::size().
{
     souffle::PiggyList<size_t> pl;
     constexpr size_t N = 10000;
     for (size_t i = 0; i < N; ++i) {
         pl.append(i);
     }
     souffle::PiggyList<size_t> pl2(pl);
     EXPECT_EQ(pl.size(), pl2.size());
     // check every element is equal and same order
     for (size_t i = 0; i < N; ++i) {
         EXPECT_EQ(pl.get(i), pl2.get(i));
         EXPECT_EQ(pl.get(i), i);
     }
     auto pl1It = pl.begin();
     auto pl2It = pl2.begin();
     while (true) {
         // yep, they both finished at the same time
         if (pl1It == pl.end() && pl2It == pl2.end()) {
             break;
         }
         // uhoh, they didn't both finish at the same time
         if (pl1It == pl.end() || pl2It == pl2.end()) {
             EXPECT_FALSE(true && "whoops, looks like the iterators are broken");
         }
         EXPECT_EQ(*pl1It, *pl2It);
         ++pl1It;
         ++pl2It;
     }
     // change contents of pl1 and makesure they don't change in pl2
     pl.get(2) = 99;
     EXPECT_EQ(pl.get(2), 99);
     EXPECT_EQ(pl2.get(2), 2);
     // check clearing one doesn't invalidate the other
     pl.clear();
     EXPECT_EQ(pl.size(), 0);
     EXPECT_EQ(pl2.size(), N);
     pl2.clear();
     EXPECT_EQ(pl.size(), 0);
     EXPECT_EQ(pl2.size(), 0);
 }
TEST() [95/228]
souffle::test::TEST (Unary , LogicalNeg)
Definition at line 150 of file ram_arithmetic_test.cpp.
References evalUnary(), EXPECT_EQ, souffle::LNOT, and TESTS_PER_OPERATION.
{
     FunctorOp functor = FunctorOp::LNOT;
     for (auto randomNumber : testutil::generateRandomVector<RamDomain>(TESTS_PER_OPERATION)) {
         EXPECT_EQ(evalUnary(functor, randomNumber), !randomNumber);
     }
 }
TEST() [96/228]
souffle::test::TEST (AstProgram , RemoveAstRelation)
Definition at line 150 of file ast_program_test.cpp.
                              : U )
                  a(X) :- X < 10.
                  b(X) :- X < 10.
                  u(X) :- X < 10.
             )");
TEST() [97/228]
souffle::test::TEST (RamExistenceCheck , CloneAndEquals)
Definition at line 151 of file ram_condition_equal_clone_test.cpp.
References b, souffle::BRIE, souffle::RamExistenceCheck::clone(), d, souffle::DEFAULT, e, EXPECT_EQ, and EXPECT_NE.
{
     // N(1) in relation N(x:number)
     RamRelation N("N", 1, 1, {"x"}, {"i"}, RelationRepresentation::DEFAULT);
     std::vector<std::unique_ptr<RamExpression>> tuple_a;
     tuple_a.emplace_back(new RamSignedConstant(1));
     RamExistenceCheck a(std::make_unique<RamRelationReference>(&N), std::move(tuple_a));
     std::vector<std::unique_ptr<RamExpression>> tuple_b;
     tuple_b.emplace_back(new RamSignedConstant(1));
     RamExistenceCheck b(std::make_unique<RamRelationReference>(&N), std::move(tuple_b));
     EXPECT_EQ(a, b);
     EXPECT_NE(&a, &b);
     RamExistenceCheck* c = a.clone();
     EXPECT_EQ(a, *c);
     EXPECT_EQ(b, *c);
     EXPECT_NE(&a, c);
     EXPECT_NE(&b, c);
     delete c;
     // edge(1,2) in relation edge(x:number,y:number)
     RamRelation edge("edge", 2, 1, {"x", "y"}, {"i", "i"}, RelationRepresentation::BRIE);
     std::vector<std::unique_ptr<RamExpression>> tuple_d;
     tuple_d.emplace_back(new RamSignedConstant(1));
     tuple_d.emplace_back(new RamSignedConstant(2));
     RamExistenceCheck d(std::make_unique<RamRelationReference>(&edge), std::move(tuple_d));
     std::vector<std::unique_ptr<RamExpression>> tuple_e;
     tuple_e.emplace_back(new RamSignedConstant(1));
     tuple_e.emplace_back(new RamSignedConstant(2));
     RamExistenceCheck e(std::make_unique<RamRelationReference>(&edge), std::move(tuple_e));
     EXPECT_EQ(d, e);
     EXPECT_NE(&d, &e);
     RamExistenceCheck* f = d.clone();
     EXPECT_EQ(d, *f);
     EXPECT_EQ(e, *f);
     EXPECT_NE(&d, f);
     EXPECT_NE(&e, f);
     delete f;
 }
TEST() [98/228]
souffle::test::TEST (AstPrint , AggregatorCount)
Definition at line 151 of file ast_print_test.cpp.
References count(), souffle::COUNT, EXPECT_EQ, makeATU(), makeClauseA(), and makePrintedATU().
{
     auto atom = std::make_unique<AstAtom>("B");
     atom->addArgument(std::make_unique<AstVariable>("x"));
     auto count = std::make_unique<AstAggregator>(AggregateOp::COUNT);
     std::vector<std::unique_ptr<AstLiteral>> body;
     body.push_back(std::move(atom));
     count->setBody(std::move(body));
     auto tu1 = makeATU();
     auto* prog1 = tu1->getProgram();
     prog1->addClause(makeClauseA(std::move(count)));
     auto tu2 = makePrintedATU(tu1);
     EXPECT_EQ(*tu1->getProgram(), *tu2->getProgram());
 }
TEST() [99/228]
souffle::test::TEST (TypeSystem , GreatestCommonSubtype)
Definition at line 153 of file type_system_test.cpp.
References souffle::TypeEnvironment::createType(), EXPECT_EQ, souffle::getGreatestCommonSubtypes(), souffle::TypeEnvironment::getType(), S, souffle::UnionType::setElements(), souffle::toString(), and souffle::toVector().
{
     TypeEnvironment env;
     const Type& N = env.getType("number");
     const Type& A = env.createType<SubsetType>("A", env.getType("number"));
     const Type& B = env.createType<SubsetType>("B", env.getType("number"));
     const Type& C = env.createType<SubsetType>("C", env.getType("symbol"));
     EXPECT_EQ("{number}", toString(getGreatestCommonSubtypes(N, N)));
     EXPECT_EQ("{A}", toString(getGreatestCommonSubtypes(A, A)));
     EXPECT_EQ("{B}", toString(getGreatestCommonSubtypes(B, B)));
     EXPECT_EQ("{C}", toString(getGreatestCommonSubtypes(C, C)));
     EXPECT_EQ("{}", toString(getGreatestCommonSubtypes(A, B)));
     EXPECT_EQ("{}", toString(getGreatestCommonSubtypes(A, C)));
     EXPECT_EQ("{}", toString(getGreatestCommonSubtypes(B, C)));
     EXPECT_EQ("{}", toString(getGreatestCommonSubtypes(A, B, C)));
     EXPECT_EQ("{A}", toString(getGreatestCommonSubtypes(A, N)));
     EXPECT_EQ("{A}", toString(getGreatestCommonSubtypes(N, A)));
     EXPECT_EQ("{B}", toString(getGreatestCommonSubtypes(B, N)));
     EXPECT_EQ("{B}", toString(getGreatestCommonSubtypes(N, B)));
     EXPECT_EQ("{}", toString(getGreatestCommonSubtypes(C, N)));
     EXPECT_EQ("{}", toString(getGreatestCommonSubtypes(N, C)));
     // // bring in unions
     auto& U = env.createType<UnionType>("U");
     auto& S = env.createType<UnionType>("S");
     U.setElements(toVector(&A));
     EXPECT_EQ("{S}", toString(getGreatestCommonSubtypes(U, S)));
     S.setElements(toVector(&A));
     EXPECT_EQ("{U}", toString(getGreatestCommonSubtypes(U, S)));
     U.setElements(toVector(&A, &B));
     EXPECT_EQ("{S}", toString(getGreatestCommonSubtypes(U, S)));
     EXPECT_EQ("{S}", toString(getGreatestCommonSubtypes(U, S, N)));
     S.setElements(toVector(&A, &B));
     EXPECT_EQ("{U}", toString(getGreatestCommonSubtypes(U, S)));
     EXPECT_EQ("{U}", toString(getGreatestCommonSubtypes(U, S, N)));
     // bring in a union of unions
     auto& R = env.createType<UnionType>("R");
     EXPECT_EQ("{R}", toString(getGreatestCommonSubtypes(U, R)));
     EXPECT_EQ("{R}", toString(getGreatestCommonSubtypes(S, R)));
     EXPECT_EQ("{R}", toString(getGreatestCommonSubtypes(U, R, N)));
     EXPECT_EQ("{R}", toString(getGreatestCommonSubtypes(S, R, N)));
     R.setElements(toVector(static_cast<const Type*>(&U)));  // R = U = S
     EXPECT_EQ("{U}", toString(getGreatestCommonSubtypes(U, R)));
     EXPECT_EQ("{S}", toString(getGreatestCommonSubtypes(S, R)));
     EXPECT_EQ("{U}", toString(getGreatestCommonSubtypes(U, R, N)));
     EXPECT_EQ("{S}", toString(getGreatestCommonSubtypes(S, R, N)));
     R.setElements(toVector(static_cast<const Type*>(&U), static_cast<const Type*>(&S)));
     EXPECT_EQ("{U}", toString(getGreatestCommonSubtypes(U, R)));
     EXPECT_EQ("{S}", toString(getGreatestCommonSubtypes(S, R)));
     EXPECT_EQ("{U}", toString(getGreatestCommonSubtypes(U, R, N)));
     EXPECT_EQ("{S}", toString(getGreatestCommonSubtypes(S, R, N)));
 }
TEST() [100/228]
souffle::test::TEST (IO_store , Float)
Definition at line 155 of file ram_relation_test.cpp.
References EXPECT_EQ, i, souffle::ramBitCast(), RANDOM_TESTS, and testInterpreterStore().
                       {
     std::vector<RamFloat> randomNumbers = testutil::generateRandomVector<RamFloat>(RANDOM_TESTS);
     // a0 a1 a2...
     std::vector<std::string> attribs(RANDOM_TESTS, "a");
     for (size_t i = 0; i < RANDOM_TESTS; ++i) {
         attribs[i].append(std::to_string(i));
     }
     std::vector<std::string> attribsTypes(RANDOM_TESTS, "f");
     std::vector<std::unique_ptr<RamExpression>> exprs;
     for (RamFloat f : randomNumbers) {
         exprs.push_back(std::make_unique<RamSignedConstant>(ramBitCast(f)));
     }
     std::stringstream expected;
     expected << std::setprecision(std::numeric_limits<RamFloat>::max_digits10);
     expected << "---------------"
              << "\n"
              << "test"
              << "\n"
              << "==============="
              << "\n"
              << randomNumbers[0];
     for (size_t i = 1; i < randomNumbers.size(); ++i) {
         expected << "\t" << randomNumbers[i];
     }
     expected << "\n"
              << "==============="
              << "\n";
     auto result = testInterpreterStore(attribs, attribsTypes, std::move(exprs));
     EXPECT_EQ(expected.str(), result);
 }
TEST() [101/228]
souffle::test::TEST (BTreeMultiSet , Duplicates)
Definition at line 157 of file btree_multiset_test.cpp.
References EXPECT_EQ, i, and souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::insert().
{
     using test_set = btree_multiset<int, detail::comparator<int>, std::allocator<int>, 16>;
     test_set t;
     for (int i = 0; i < 10; i++) {
         t.insert(0);
     }
     EXPECT_EQ(10, t.size());
     std::vector<int> data(t.begin(), t.end());
     EXPECT_EQ(10, data.size());
     for (int i = 0; i < 10; i++) {
         EXPECT_EQ(0, data[i]);
     }
 }
TEST() [102/228]
souffle::test::TEST (Unary , UnsignedLogicalNeg)
Definition at line 158 of file ram_arithmetic_test.cpp.
References evalUnary(), EXPECT_EQ, souffle::ramBitCast(), TESTS_PER_OPERATION, and souffle::ULNOT.
{
     FunctorOp functor = FunctorOp::ULNOT;
     for (auto randomNumber : testutil::generateRandomVector<RamUnsigned>(TESTS_PER_OPERATION)) {
         RamDomain result = evalUnary(functor, ramBitCast(randomNumber));
         EXPECT_EQ(ramBitCast<RamUnsigned>(result), static_cast<RamUnsigned>(!randomNumber));
     }
 }
TEST() [103/228]
souffle::test::TEST (AstTransformers , RemoveRelationCopies)
Test that copies of relations are removed by RemoveRelationCopiesTransformer.
A(1, 2). B(x, y) :- A(x, y). C(x, y) :- B(x, y). D(x, y) :- C(x, y).
-> D(x, y) :- A(x, y).
B and C can be removed
Definition at line 158 of file ast_transformers_test.cpp.
References EXPECT_EQ, souffle::AstProgram::getRelations(), souffle::ParserDriver::parseTranslationUnit(), and souffle::RemoveRelationCopiesTransformer::removeRelationCopies().
{
     ErrorReport errorReport;
     DebugReport debugReport;
     // load some test program
     std::unique_ptr<AstTranslationUnit> tu = ParserDriver::parseTranslationUnit(
             R"(
                 .type D = number
                 .decl a(a:D,b:D)
                 .decl b(a:D,b:D)
                 .decl c(a:D,b:D)
                 .decl d(a:D,b:D)
                 a(1,2).
                 b(x,y) :- a(x,y).
                 c(x,y) :- b(x,y).
                 d(x,y) :- b(x,y), c(y,x).
             )",
             errorReport, debugReport);
     AstProgram& program = *tu->getProgram();
     EXPECT_EQ(4, program.getRelations().size());
     RemoveRelationCopiesTransformer::removeRelationCopies(*tu);
     EXPECT_EQ(2, program.getRelations().size());
 }
TEST() [104/228]
souffle::test::TEST (RamChoice , CloneAndEquals)
Definition at line 163 of file ram_operation_equal_clone_test.cpp.
References b, souffle::RamChoice::clone(), souffle::DEFAULT, souffle::EQ, EXPECT_EQ, and EXPECT_NE.
{
     RamRelation edge("edge", 2, 1, {"x", "y"}, {"i", "i"}, RelationRepresentation::DEFAULT);
     // choose an edge not adjcent to vertex 5
     // CHOICE t1 IN edge WHERE NOT t1.0 = 5 AND NOT t1.1 = 5
     //  RETURN (t1.0, t1.1)
     std::vector<std::unique_ptr<RamExpression>> a_return_args;
     a_return_args.emplace_back(new RamTupleElement(1, 0));
     a_return_args.emplace_back(new RamTupleElement(1, 1));
     auto a_return = std::make_unique<RamSubroutineReturn>(std::move(a_return_args));
     auto a_constraint1 = std::make_unique<RamConstraint>(BinaryConstraintOp::EQ,
             std::make_unique<RamTupleElement>(1, 0), std::make_unique<RamSignedConstant>(5));
     auto a_neg1 = std::make_unique<RamNegation>(std::move(a_constraint1));
     auto a_constraint2 = std::make_unique<RamConstraint>(BinaryConstraintOp::EQ,
             std::make_unique<RamTupleElement>(1, 1), std::make_unique<RamSignedConstant>(5));
     auto a_neg2 = std::make_unique<RamNegation>(std::move(a_constraint2));
     auto a_cond = std::make_unique<RamConjunction>(std::move(a_neg1), std::move(a_neg2));
     RamChoice a(std::make_unique<RamRelationReference>(&edge), 1, std::move(a_cond), std::move(a_return),
             "RamChoice test");
     std::vector<std::unique_ptr<RamExpression>> b_return_args;
     b_return_args.emplace_back(new RamTupleElement(1, 0));
     b_return_args.emplace_back(new RamTupleElement(1, 1));
     auto b_return = std::make_unique<RamSubroutineReturn>(std::move(b_return_args));
     auto b_constraint1 = std::make_unique<RamConstraint>(BinaryConstraintOp::EQ,
             std::make_unique<RamTupleElement>(1, 0), std::make_unique<RamSignedConstant>(5));
     auto b_neg1 = std::make_unique<RamNegation>(std::move(b_constraint1));
     auto b_constraint2 = std::make_unique<RamConstraint>(BinaryConstraintOp::EQ,
             std::make_unique<RamTupleElement>(1, 1), std::make_unique<RamSignedConstant>(5));
     auto b_neg2 = std::make_unique<RamNegation>(std::move(b_constraint2));
     auto b_cond = std::make_unique<RamConjunction>(std::move(b_neg1), std::move(b_neg2));
     RamChoice b(std::make_unique<RamRelationReference>(&edge), 1, std::move(b_cond), std::move(b_return),
             "RamChoice test");
     EXPECT_EQ(a, b);
     EXPECT_NE(&a, &b);
     RamChoice* c = a.clone();
     EXPECT_EQ(a, *c);
     EXPECT_NE(&a, c);
     delete c;
 }
TEST() [105/228]
souffle::test::TEST (RamSequence , CloneAndEquals)
Definition at line 165 of file ram_statement_equal_clone_test.cpp.
References b, souffle::RamSequence::clone(), d, souffle::DEFAULT, e, EXPECT_EQ, EXPECT_NE, and i.
{
     // no statements in the sequence
     RamSequence a;
     RamSequence b;
     EXPECT_EQ(a, b);
     EXPECT_NE(&a, &b);
     RamSequence* c = a.clone();
     EXPECT_EQ(a, *c);
     EXPECT_NE(&a, c);
     delete c;
     RamRelation A("A", 1, 1, {"x"}, {"i"}, RelationRepresentation::DEFAULT);
     // one statement in the sequence
     // CLEAR A
     RamSequence d(std::make_unique<RamClear>(std::make_unique<RamRelationReference>(&A)));
     RamSequence e(std::make_unique<RamClear>(std::make_unique<RamRelationReference>(&A)));
     EXPECT_EQ(d, e);
     EXPECT_NE(&d, &e);
     RamSequence* f = d.clone();
     EXPECT_EQ(d, *f);
     EXPECT_NE(&d, f);
     delete f;
     // multiple statements in the sequence
     // IO A ()
     // CLEAR A
     std::map<std::string, std::string> g_load_IODir;
     std::map<std::string, std::string> h_load_IODir;
     RamSequence g(
             std::make_unique<RamIO>(std::make_unique<RamRelationReference>(&A), std::move(g_load_IODir)),
             std::make_unique<RamClear>(std::make_unique<RamRelationReference>(&A)));
     RamSequence h(
             std::make_unique<RamIO>(std::make_unique<RamRelationReference>(&A), std::move(h_load_IODir)),
             std::make_unique<RamClear>(std::make_unique<RamRelationReference>(&A)));
     EXPECT_EQ(g, h);
     EXPECT_NE(&g, &h);
     RamSequence* i = g.clone();
     EXPECT_EQ(g, *i);
     EXPECT_NE(&g, i);
     delete i;
 }
TEST() [106/228]
souffle::test::TEST (AstPrint , AggregatorSum)
Definition at line 167 of file ast_print_test.cpp.
References EXPECT_EQ, makeATU(), makeClauseA(), makePrintedATU(), and souffle::SUM.
{
     auto atom = std::make_unique<AstAtom>("B");
     atom->addArgument(std::make_unique<AstVariable>("x"));
     auto sum = std::make_unique<AstAggregator>(AggregateOp::SUM, std::make_unique<AstVariable>("x"));
     std::vector<std::unique_ptr<AstLiteral>> body;
     body.push_back(std::move(atom));
     sum->setBody(std::move(body));
     auto tu1 = makeATU();
     auto* prog1 = tu1->getProgram();
     prog1->addClause(makeClauseA(std::move(sum)));
     auto tu2 = makePrintedATU(tu1);
     EXPECT_EQ(*tu1->getProgram(), *tu2->getProgram());
 }
TEST() [107/228]
souffle::test::TEST (Unary , SingedTpUnsigned)
Definition at line 167 of file ram_arithmetic_test.cpp.
References evalUnary(), EXPECT_EQ, souffle::I2U, and TESTS_PER_OPERATION.
{
     FunctorOp functor = FunctorOp::I2U;
     for (auto randomNumber : testutil::generateRandomVector<RamDomain>(TESTS_PER_OPERATION)) {
         RamDomain result = evalUnary(functor, randomNumber);
         EXPECT_EQ(ramBitCast<RamUnsigned>(result), static_cast<RamUnsigned>(randomNumber));
     }
 }
TEST() [108/228]
souffle::test::TEST (EqRelTest , PairwiseDecremental)
Definition at line 167 of file binary_relation_test.cpp.
References souffle::EquivalenceRelation< TupleType >::contains(), count(), EXPECT_EQ, EXPECT_TRUE, i, testutil::ignore(), souffle::EquivalenceRelation< TupleType >::insert(), and souffle::EquivalenceRelation< TupleType >::size().
{
     EqRel br;
     const size_t N = 100;
     // test inserting descending pairs still isolates them
     for (size_t i = N; i > 1; --i) {
         br.insert(i, i);
         EXPECT_TRUE(br.contains(i, i));
         br.insert(i + (N + 1), i);
         EXPECT_TRUE(br.contains(i, i + (N + 1)));
         EXPECT_TRUE(br.contains(i + (N + 1), i + (N + 1)));
         EXPECT_TRUE(br.contains(i + (N + 1), i));
     }
     EXPECT_EQ(br.size(), (N - 1) * 4);
     size_t count = 0;
     for (auto x : br) {
         ++count;
         testutil::ignore(x);
     }
     EXPECT_EQ(count, br.size());
 }
TEST() [109/228]
souffle::test::TEST (BTreeSet , Duplicates)
Definition at line 170 of file btree_set_test.cpp.
References EXPECT_EQ, i, and souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::insert().
{
     using test_set = btree_set<int, detail::comparator<int>, std::allocator<int>, 16>;
     test_set t;
     for (int i = 0; i < 10; i++) {
         t.insert(0);
     }
     EXPECT_EQ(1, t.size());
     EXPECT_EQ(0, *t.begin());
     //        t.printTree();
 }
TEST() [110/228]
souffle::test::TEST (BTreeMultiSet , Incremental)
Definition at line 171 of file btree_multiset_test.cpp.
References EXPECT_EQ, i, souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::insert(), and j.
{
     using test_set = btree_multiset<int, detail::comparator<int>, std::allocator<int>, 16>;
     test_set t;
     int N = 1000;
     for (int i = 0; i < N; i++) {
         t.insert(i);
         for (int j = 0; j < N; j++) {
             EXPECT_EQ(j <= i, t.contains(j)) << "i=" << i << ", j=" << j;
         }
     }
 }
TEST() [111/228]
souffle::test::TEST (Unary , UnsignedToSigned)
Definition at line 176 of file ram_arithmetic_test.cpp.
References evalUnary(), EXPECT_EQ, souffle::ramBitCast(), TESTS_PER_OPERATION, and souffle::U2I.
{
     FunctorOp functor = FunctorOp::U2I;
     for (auto randomNumber : testutil::generateRandomVector<RamUnsigned>(TESTS_PER_OPERATION)) {
         RamDomain result = evalUnary(functor, ramBitCast(randomNumber));
         EXPECT_EQ(result, static_cast<RamDomain>(randomNumber));
     }
 }
TEST() [112/228]
souffle::test::TEST (BTreeMultiSet , Decremental)
Definition at line 183 of file btree_multiset_test.cpp.
References EXPECT_EQ, i, souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::insert(), and j.
{
     using test_set = btree_multiset<int, detail::comparator<int>, std::allocator<int>, 16>;
     test_set t;
     int N = 1000;
     for (int i = N; i >= 0; i--) {
         t.insert(i);
         for (int j = 0; j < N; j++) {
             EXPECT_EQ(j >= i, t.contains(j)) << "i=" << i << ", j=" << j;
         }
     }
 }
TEST() [113/228]
souffle::test::TEST (Unary , SignedToFloat)
Definition at line 185 of file ram_arithmetic_test.cpp.
References evalUnary(), EXPECT_EQ, souffle::I2F, souffle::ramBitCast(), and TESTS_PER_OPERATION.
{
     FunctorOp functor = FunctorOp::I2F;
     for (auto randomNumber : testutil::generateRandomVector<RamDomain>(TESTS_PER_OPERATION)) {
         RamDomain result = evalUnary(functor, ramBitCast(randomNumber));
         EXPECT_EQ(ramBitCast<RamFloat>(result), static_cast<RamFloat>(randomNumber));
     }
 }
TEST() [114/228]
souffle::test::TEST (BTreeSet , Incremental)
Definition at line 186 of file btree_set_test.cpp.
References EXPECT_EQ, i, souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::insert(), and j.
{
     using test_set = btree_set<int, detail::comparator<int>, std::allocator<int>, 16>;
     test_set t;
     int N = 1000;
     for (int i = 0; i < N; i++) {
         //        std::cout << "\nBefore:\n";
         //        t.printTree();
         //        std::cout << "\n";
         t.insert(i);
         //        std::cout << "\nAfter:\n";
         //        std::cout << "\n";
         //        t.printTree();
         //        std::cout << "\n";
         //        std::cout << "\n\n";
         for (int j = 0; j < N; j++) {
             EXPECT_EQ(j <= i, t.contains(j)) << "i=" << i << ", j=" << j;
         }
     }
     t.printStats();
 }
TEST() [115/228]
souffle::test::TEST (EqRelTest , Shuffled)
Definition at line 190 of file binary_relation_test.cpp.
References souffle::EquivalenceRelation< TupleType >::contains(), count(), EXPECT_EQ, EXPECT_TRUE, i, testutil::ignore(), souffle::EquivalenceRelation< TupleType >::insert(), and souffle::EquivalenceRelation< TupleType >::size().
{
     EqRel br;
     size_t N = 100;
     // test inserting data "out of order" keeps isolation
     std::vector<int> data;
     for (size_t i = 0; i < N; i++) {
         data.push_back(i);
     }
     std::random_device rd;
     std::mt19937 generator(rd());
     shuffle(data.begin(), data.end(), generator);
     for (auto x : data) {
         br.insert(x, x);
     }
     for (size_t i = 0; i < N; ++i) {
         EXPECT_TRUE(br.contains(i, i));
     }
     EXPECT_EQ(br.size(), N);
     // always check the iterator for size too
     size_t count = 0;
     for (auto x : br) {
         ++count;
         testutil::ignore(x);
     }
     EXPECT_EQ(count, br.size());
 }
TEST() [116/228]
souffle::test::TEST (RamSubrountineArgument , CloneAndEquals)
Definition at line 192 of file ram_expression_equal_clone_test.cpp.
References b, souffle::RamSubroutineArgument::clone(), EXPECT_EQ, and EXPECT_NE.
{
     RamSubroutineArgument a(2);
     RamSubroutineArgument b(2);
     EXPECT_EQ(a, b);
     EXPECT_NE(&a, &b);
     RamSubroutineArgument* aClone = a.clone();
     EXPECT_EQ(a, *aClone);
     EXPECT_NE(&a, aClone);
     delete aClone;
 }
TEST() [117/228]
souffle::test::TEST (IO_store , Unsigned)
Definition at line 193 of file ram_relation_test.cpp.
References EXPECT_EQ, i, souffle::ramBitCast(), RANDOM_TESTS, and testInterpreterStore().
{
     std::vector<RamUnsigned> randomNumbers = testutil::generateRandomVector<RamUnsigned>(RANDOM_TESTS);
     // a0 a1 a2...
     std::vector<std::string> attribs(RANDOM_TESTS, "a");
     for (size_t i = 0; i < RANDOM_TESTS; ++i) {
         attribs[i].append(std::to_string(i));
     }
     std::vector<std::string> attribsTypes(RANDOM_TESTS, "u");
     std::vector<std::unique_ptr<RamExpression>> exprs;
     for (RamUnsigned u : randomNumbers) {
         exprs.push_back(std::make_unique<RamSignedConstant>(ramBitCast(u)));
     }
     std::stringstream expected;
     expected << "---------------"
              << "\n"
              << "test"
              << "\n"
              << "==============="
              << "\n"
              << randomNumbers[0];
     for (size_t i = 1; i < randomNumbers.size(); ++i) {
         expected << "\t" << randomNumbers[i];
     }
     expected << "\n"
              << "==============="
              << "\n";
     auto result = testInterpreterStore(attribs, attribsTypes, std::move(exprs));
     EXPECT_EQ(expected.str(), result);
 }
TEST() [118/228]
souffle::test::TEST (RamProvenanceExistCheck , CloneAndEquals)
Definition at line 193 of file ram_condition_equal_clone_test.cpp.
References b, souffle::RamExistenceCheck::clone(), souffle::RamProvenanceExistenceCheck::clone(), d, souffle::DEFAULT, e, EXPECT_EQ, and EXPECT_NE.
{
     RamRelation N("N", 1, 1, {"x"}, {"i"}, RelationRepresentation::DEFAULT);
     std::vector<std::unique_ptr<RamExpression>> tuple_a;
     tuple_a.emplace_back(new RamSignedConstant(1));
     RamExistenceCheck a(std::make_unique<RamRelationReference>(&N), std::move(tuple_a));
     std::vector<std::unique_ptr<RamExpression>> tuple_b;
     tuple_b.emplace_back(new RamSignedConstant(1));
     RamExistenceCheck b(std::make_unique<RamRelationReference>(&N), std::move(tuple_b));
     EXPECT_EQ(a, b);
     EXPECT_NE(&a, &b);
     RamExistenceCheck* c = a.clone();
     EXPECT_EQ(a, *c);
     EXPECT_EQ(b, *c);
     EXPECT_NE(&a, c);
     EXPECT_NE(&b, c);
     delete c;
     // address(state:symbol, postCode:number, street:symbol)
     RamRelation address("address", 3, 1, {"state", "postCode", "street"}, {"s", "i", "s"},
             RelationRepresentation::DEFAULT);
     std::vector<std::unique_ptr<RamExpression>> tuple_d;
     tuple_d.emplace_back(new RamSignedConstant(0));
     tuple_d.emplace_back(new RamSignedConstant(2000));
     tuple_d.emplace_back(new RamSignedConstant(0));
     RamProvenanceExistenceCheck d(std::make_unique<RamRelationReference>(&address), std::move(tuple_d));
     std::vector<std::unique_ptr<RamExpression>> tuple_e;
     tuple_e.emplace_back(new RamSignedConstant(0));
     tuple_e.emplace_back(new RamSignedConstant(2000));
     tuple_e.emplace_back(new RamSignedConstant(0));
     RamProvenanceExistenceCheck e(std::make_unique<RamRelationReference>(&address), std::move(tuple_e));
     EXPECT_EQ(d, e);
     EXPECT_NE(&d, &e);
     RamProvenanceExistenceCheck* f = d.clone();
     EXPECT_EQ(d, *f);
     EXPECT_EQ(e, *f);
     EXPECT_NE(&d, f);
     EXPECT_NE(&e, f);
     delete f;
 }
TEST() [119/228]
souffle::test::TEST (Unary , FloatToSigned)
Definition at line 194 of file ram_arithmetic_test.cpp.
References evalUnary(), EXPECT_EQ, souffle::F2I, souffle::ramBitCast(), and TESTS_PER_OPERATION.
{
     FunctorOp functor = FunctorOp::F2I;
     for (auto randomNumber : testutil::generateRandomVector<RamFloat>(TESTS_PER_OPERATION)) {
         RamDomain result = evalUnary(functor, ramBitCast(randomNumber));
         EXPECT_EQ(result, static_cast<RamDomain>(randomNumber));
     }
 }
TEST() [120/228]
souffle::test::TEST (BTreeMultiSet , Shuffled)
Definition at line 195 of file btree_multiset_test.cpp.
References EXPECT_TRUE, and i.
{
     using test_set = btree_multiset<int, detail::comparator<int>, std::allocator<int>, 16>;
     test_set t;
     int N = 10000;
     std::vector<int> data;
     for (int i = 0; i < N; i++) {
         data.push_back(i);
     }
     std::random_device rd;
     std::mt19937 generator(rd());
     shuffle(data.begin(), data.end(), generator);
     for (int i = 0; i < N; i++) {
         t.insert(data[i]);
     }
     for (int i = 0; i < N; i++) {
         EXPECT_TRUE(t.contains(i)) << "i=" << i;
     }
 }
TEST() [121/228]
souffle::test::TEST (PiggyTest , DoubleClear)
Definition at line 199 of file eqrel_datastructure_test.cpp.
References souffle::PiggyList< T >::append(), souffle::PiggyList< T >::clear(), souffle::PiggyList< T >::createNode(), e, EXPECT_EQ, EXPECT_TRUE, souffle::PiggyList< T >::get(), i, souffle::PiggyList< T >::size(), and TEST().
{
     // err.. prior versions have had the bug where clear caused double-free errors (as we don't set the
     // container to null) This should *crash* the test-suite if this is the case, but I also try to check the
     // contents here
     souffle::PiggyList<size_t> pl;
     pl.append(3213);
     pl.append(3213);
     pl.append(3213);
     pl.append(3213);
     EXPECT_EQ(pl.size(), 4);
     pl.clear();
     EXPECT_EQ(pl.size(), 0);
     pl.clear();
     EXPECT_EQ(pl.size(), 0);
     pl.append(1);
     EXPECT_EQ(pl.size(), 1);
 }
TEST() [122/228]
souffle::test::TEST (AstTransformers , RemoveRelationCopiesOutput)
Test that copies of relations are removed by RemoveRelationCopiesTransformer.
A(1, 2). B(x, y) :- A(x, y). C(x, y) :- B(x, y). D(x, y) :- C(x, y). .output C
-> C(x, y) :- A(x, y). -> D(x, y) :- C(x, y).
B can be removed, but not C as C is output
Definition at line 203 of file ast_transformers_test.cpp.
References EXPECT_EQ, souffle::AstProgram::getRelations(), souffle::ParserDriver::parseTranslationUnit(), and souffle::RemoveRelationCopiesTransformer::removeRelationCopies().
{
     ErrorReport errorReport;
     DebugReport debugReport;
     // load some test program
     std::unique_ptr<AstTranslationUnit> tu = ParserDriver::parseTranslationUnit(
             R"(
                 .type D = number
                 .decl a(a:D,b:D)
                 .decl b(a:D,b:D)
                 .decl c(a:D,b:D)
                 .output c
                 .decl d(a:D,b:D)
                 a(1,2).
                 b(x,y) :- a(x,y).
                 c(x,y) :- b(x,y).
                 d(x,y) :- b(x,y), c(y,x).
             )",
             errorReport, debugReport);
     AstProgram& program = *tu->getProgram();
     EXPECT_EQ(4, program.getRelations().size());
     RemoveRelationCopiesTransformer::removeRelationCopies(*tu);
     EXPECT_EQ(3, program.getRelations().size());
 }
TEST() [123/228]
souffle::test::TEST (Unary , UnsignedToFloat)
Definition at line 203 of file ram_arithmetic_test.cpp.
References evalUnary(), EXPECT_EQ, souffle::ramBitCast(), TESTS_PER_OPERATION, and souffle::U2F.
{
     FunctorOp functor = FunctorOp::U2F;
     for (auto randomNumber : testutil::generateRandomVector<RamUnsigned>(TESTS_PER_OPERATION)) {
         RamDomain result = evalUnary(functor, ramBitCast(randomNumber));
         EXPECT_EQ(ramBitCast<RamFloat>(result), static_cast<RamFloat>(randomNumber));
     }
 }
TEST() [124/228]
souffle::test::TEST (RamParallelChoice , CloneAndEquals)
Definition at line 205 of file ram_operation_equal_clone_test.cpp.
References b, souffle::RamParallelChoice::clone(), souffle::DEFAULT, souffle::EQ, EXPECT_EQ, and EXPECT_NE.
{
     RamRelation edge("edge", 2, 1, {"x", "y"}, {"i", "i"}, RelationRepresentation::DEFAULT);
     // parallel choose an edge not adjcent to vertex 5
     // PARALLEL CHOICE t1 IN edge WHERE NOT t1.0 = 5 AND NOT t1.1 = 5
     //  RETURN (t1.0, t1.1)
     std::vector<std::unique_ptr<RamExpression>> a_return_args;
     a_return_args.emplace_back(new RamTupleElement(1, 0));
     a_return_args.emplace_back(new RamTupleElement(1, 1));
     auto a_return = std::make_unique<RamSubroutineReturn>(std::move(a_return_args));
     auto a_constraint1 = std::make_unique<RamConstraint>(BinaryConstraintOp::EQ,
             std::make_unique<RamTupleElement>(1, 0), std::make_unique<RamSignedConstant>(5));
     auto a_neg1 = std::make_unique<RamNegation>(std::move(a_constraint1));
     auto a_constraint2 = std::make_unique<RamConstraint>(BinaryConstraintOp::EQ,
             std::make_unique<RamTupleElement>(1, 1), std::make_unique<RamSignedConstant>(5));
     auto a_neg2 = std::make_unique<RamNegation>(std::move(a_constraint2));
     auto a_cond = std::make_unique<RamConjunction>(std::move(a_neg1), std::move(a_neg2));
     RamParallelChoice a(std::make_unique<RamRelationReference>(&edge), 1, std::move(a_cond),
             std::move(a_return), "RamParallelChoice test");
     std::vector<std::unique_ptr<RamExpression>> b_return_args;
     b_return_args.emplace_back(new RamTupleElement(1, 0));
     b_return_args.emplace_back(new RamTupleElement(1, 1));
     auto b_return = std::make_unique<RamSubroutineReturn>(std::move(b_return_args));
     auto b_constraint1 = std::make_unique<RamConstraint>(BinaryConstraintOp::EQ,
             std::make_unique<RamTupleElement>(1, 0), std::make_unique<RamSignedConstant>(5));
     auto b_neg1 = std::make_unique<RamNegation>(std::move(b_constraint1));
     auto b_constraint2 = std::make_unique<RamConstraint>(BinaryConstraintOp::EQ,
             std::make_unique<RamTupleElement>(1, 1), std::make_unique<RamSignedConstant>(5));
     auto b_neg2 = std::make_unique<RamNegation>(std::move(b_constraint2));
     auto b_cond = std::make_unique<RamConjunction>(std::move(b_neg1), std::move(b_neg2));
     RamParallelChoice b(std::make_unique<RamRelationReference>(&edge), 1, std::move(b_cond),
             std::move(b_return), "RamParallelChoice test");
     EXPECT_EQ(a, b);
     EXPECT_NE(&a, &b);
     RamParallelChoice* c = a.clone();
     EXPECT_EQ(a, *c);
     EXPECT_NE(&a, c);
     delete c;
 }
TEST() [125/228]
souffle::test::TEST (RamParallel , CloneAndEquals)
Definition at line 210 of file ram_statement_equal_clone_test.cpp.
References b, souffle::RamParallel::clone(), souffle::DEFAULT, EXPECT_EQ, EXPECT_NE, and souffle::GE.
{
     RamRelation A("A", 3, 1, {"a", "b", "c"}, {"i", "s", "i"}, RelationRepresentation::DEFAULT);
     RamRelation B("B", 2, 1, {"a", "c"}, {"i", "i"}, RelationRepresentation::DEFAULT);
     /* PARALLEL
      *  QUERY
      *   FOR t0 IN A
      *    IF (t0.0 > 0)
      *     PROJECT (t0.0, t0.2) INTO B
      * END PARALLEL
      * */
     std::vector<std::unique_ptr<RamExpression>> a_expressions;
     a_expressions.emplace_back(new RamTupleElement(0, 0));
     a_expressions.emplace_back(new RamTupleElement(0, 2));
     auto a_project = std::make_unique<RamProject>(
             std::make_unique<RamRelationReference>(&B), std::move(a_expressions));
     auto a_cond = std::make_unique<RamFilter>(
             std::make_unique<RamConstraint>(BinaryConstraintOp::GE, std::make_unique<RamTupleElement>(0, 0),
                     std::make_unique<RamSignedConstant>(0)),
             std::move(a_project), "");
     auto a_scan =
             std::make_unique<RamScan>(std::make_unique<RamRelationReference>(&A), 0, std::move(a_cond), "");
     auto a_query = std::make_unique<RamQuery>(std::move(a_scan));
     RamParallel a(std::move(a_query));
     std::vector<std::unique_ptr<RamExpression>> b_expressions;
     b_expressions.emplace_back(new RamTupleElement(0, 0));
     b_expressions.emplace_back(new RamTupleElement(0, 2));
     auto b_project = std::make_unique<RamProject>(
             std::make_unique<RamRelationReference>(&B), std::move(b_expressions));
     auto b_cond = std::make_unique<RamFilter>(
             std::make_unique<RamConstraint>(BinaryConstraintOp::GE, std::make_unique<RamTupleElement>(0, 0),
                     std::make_unique<RamSignedConstant>(0)),
             std::move(b_project), "");
     auto b_scan =
             std::make_unique<RamScan>(std::make_unique<RamRelationReference>(&A), 0, std::move(b_cond), "");
     auto b_query = std::make_unique<RamQuery>(std::move(b_scan));
     RamParallel b(std::move(b_query));
     EXPECT_EQ(a, b);
     EXPECT_NE(&a, &b);
     RamParallel* c = a.clone();
     EXPECT_EQ(a, *c);
     EXPECT_NE(&a, c);
     delete c;
 }
TEST() [126/228]
souffle::test::TEST (Unary , FloatToUnsigned)
Definition at line 212 of file ram_arithmetic_test.cpp.
References evalUnary(), EXPECT_EQ, souffle::F2U, souffle::ramBitCast(), and TESTS_PER_OPERATION.
{
     FunctorOp functor = FunctorOp::F2U;
     for (auto randomNumber : testutil::generateRandomVector<RamFloat>(TESTS_PER_OPERATION)) {
         RamDomain result = evalUnary(functor, ramBitCast(randomNumber));
         EXPECT_EQ(ramBitCast<RamUnsigned>(result), static_cast<RamUnsigned>(randomNumber));
     }
 }
TEST() [127/228]
souffle::test::TEST (BTreeSet , Decremental)
Definition at line 212 of file btree_set_test.cpp.
References EXPECT_EQ, i, souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::insert(), and j.
{
     using test_set = btree_set<int, detail::comparator<int>, std::allocator<int>, 16>;
     test_set t;
     int N = 1000;
     for (int i = N; i >= 0; i--) {
         //            std::cout << "\nBefore:\n";
         //            t.printTree();
         //            std::cout << "\n";
         t.insert(i);
         //            std::cout << "\nAfter:\n";
         //            t.printTree();
         //            std::cout << "\n";
         //            std::cout << "\n\n";
         for (int j = 0; j < N; j++) {
             EXPECT_EQ(j >= i, t.contains(j)) << "i=" << i << ", j=" << j;
         }
     }
 }
TEST() [128/228]
souffle::test::TEST (BTreeMultiSet , IteratorEmpty)
Definition at line 220 of file btree_multiset_test.cpp.
References EXPECT_EQ.
{
     using test_set = btree_multiset<int, detail::comparator<int>, std::allocator<int>, 16>;
     test_set t;
     EXPECT_EQ(t.begin(), t.end());
 }
TEST() [129/228]
souffle::test::TEST (Binary , SignedAdd)
Definition at line 221 of file ram_arithmetic_test.cpp.
References souffle::ADD, evalBinary(), EXPECT_EQ, i, and TESTS_PER_OPERATION.
{
     FunctorOp functor = FunctorOp::ADD;
     auto vecArg1 = testutil::generateRandomVector<RamDomain>(TESTS_PER_OPERATION);
     auto vecArg2 = testutil::generateRandomVector<RamDomain>(TESTS_PER_OPERATION);
     for (size_t i = 0; i < TESTS_PER_OPERATION; ++i) {
         RamDomain arg1 = vecArg1[i];
         RamDomain arg2 = vecArg2[i];
         RamDomain result = evalBinary(functor, arg1, arg2);
         EXPECT_EQ(result, arg1 + arg2);
     }
 }
TEST() [130/228]
souffle::test::TEST (EqRelTest , Extend)
Definition at line 223 of file binary_relation_test.cpp.
References EXPECT_EQ, EXPECT_FALSE, EXPECT_TRUE, souffle::EquivalenceRelation< TupleType >::insert(), and souffle::EquivalenceRelation< TupleType >::size().
{
     // test running extend for a relation
     // br is {{0,1,2,3,4,5,6}, {8,9}, {44, 70}, {11}}
     EqRel br;
     br.insert(0, 1);
     br.insert(0, 2);
     br.insert(0, 3);
     br.insert(0, 4);
     br.insert(0, 5);
     br.insert(0, 6);
     br.insert(8, 9);
     br.insert(44, 70);
     br.insert(11, 11);
     EXPECT_EQ(br.size(), (7 * 7) + (2 * 2) + (2 * 2) + (1 * 1));
     // br2 is {{0,8,33,99}, {68,69,70}, {101, 102}}
     EqRel br2;
     br2.insert(33, 8);
     br2.insert(33, 99);
     br2.insert(33, 0);
     br2.insert(69, 68);
     br2.insert(69, 70);
     br2.insert(101, 102);
     EXPECT_EQ(br2.size(), (4 * 4) + (3 * 3) + (2 * 2));
     // let's say br2 the new knowledge, so we must extend it to actually contain the implied knowledge from
     // new
     br2.extend(br);
     // it should contain {0,1,2,3,4,5,6,8,9,33,99}, {44, 68, 69, 70}, {101, 102}
     // shouldn't contain {11}.
     EXPECT_TRUE(br2.contains(0, 0));
     EXPECT_TRUE(br2.contains(0, 1));
     EXPECT_TRUE(br2.contains(1, 8));
     EXPECT_TRUE(br2.contains(9, 4));
     EXPECT_TRUE(br2.contains(33, 4));
     EXPECT_TRUE(br2.contains(33, 99));
     EXPECT_TRUE(br2.contains(68, 69));
     EXPECT_TRUE(br2.contains(70, 44));
     EXPECT_FALSE(br2.contains(11, 11));
     EXPECT_FALSE(br2.contains(0, 69));
     EXPECT_TRUE(br2.contains(101, 102));
     // check this hasn't changed size
     EXPECT_EQ(br.size(), (7 * 7) + (2 * 2) + (2 * 2) + (1 * 1));
     // check that it was properly extended
     EXPECT_EQ(br2.size(), (11 * 11) + (4 * 4) + (2 * 2));
 }
TEST() [131/228]
souffle::test::TEST (BTreeMultiSet , IteratorBasic)
Definition at line 227 of file btree_multiset_test.cpp.
References e, EXPECT_EQ, EXPECT_NE, i, and souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::insert().
{
     using test_set = btree_multiset<int, detail::comparator<int>, std::allocator<int>, 16>;
     test_set t;
     for (int i = 0; i < 10; i++) {
         t.insert(i);
     }
     //        t.printTree();
     auto it = t.begin();
     auto e = t.end();
     EXPECT_NE(it, e);
     int last = -1;
     for (int i : t) {
         EXPECT_EQ(last + 1, i);
         last = i;
     }
     EXPECT_EQ(last, 9);
 }
TEST() [132/228]
souffle::test::TEST (TypeSystem , complexSubsetTypes)
Definition at line 228 of file type_system_test.cpp.
References base, souffle::TypeEnvironment::createType(), EXPECT_EQ, EXPECT_PRED2, souffle::getGreatestCommonSubtypes(), souffle::TypeEnvironment::getType(), i, souffle::isSubtypeOf(), and souffle::toString().
{
     TypeEnvironment env;
     auto& A = env.createType<SubsetType>("A", env.getType("number"));
     auto& BfromA = env.createType<SubsetType>("B", A);
     auto& CfromA = env.createType<SubsetType>("C", A);
     EXPECT_EQ("{B}", toString(getGreatestCommonSubtypes(A, BfromA)));
     EXPECT_EQ("{C}", toString(getGreatestCommonSubtypes(A, CfromA)));
     EXPECT_EQ("{}", toString(getGreatestCommonSubtypes(A, BfromA, CfromA)));
     EXPECT_EQ("{}", toString(getGreatestCommonSubtypes(BfromA, CfromA)));
     auto* base = &env.createType<SubsetType>("B0", BfromA);
     for (size_t i = 1; i <= 10; ++i) {
         base = &env.createType<SubsetType>("B" + std::to_string(i), *base);
         EXPECT_PRED2(isSubtypeOf, *base, A);
     }
 }
TEST() [133/228]
souffle::test::TEST (IO_store , SignedChangedDelimiter)
Definition at line 230 of file ram_relation_test.cpp.
References souffle::BTREE, souffle::Global::config(), EXPECT_EQ, i, souffle::main(), RANDOM_TESTS, and types.
{
     std::vector<RamDomain> randomNumbers = testutil::generateRandomVector<RamDomain>(RANDOM_TESTS);
     const std::string delimiter{", "};
     Global::config().set("jobs", "1");
     std::vector<std::unique_ptr<RamRelation>> rels;
     // a0 a1 a2...
     std::vector<std::string> attribs(RANDOM_TESTS, "a");
     for (size_t i = 0; i < RANDOM_TESTS; ++i) {
         attribs[i].append(std::to_string(i));
     }
     std::vector<std::string> attribsTypes(RANDOM_TESTS, "i");
     std::unique_ptr<RamRelation> myrel = std::make_unique<RamRelation>(
             "test", RANDOM_TESTS, 0, attribs, attribsTypes, RelationRepresentation::BTREE);
     std::unique_ptr<RamRelationReference> ref1 = std::make_unique<RamRelationReference>(myrel.get());
     std::unique_ptr<RamRelationReference> ref2 = std::make_unique<RamRelationReference>(myrel.get());
     Json types = Json::object{
             {"relation", Json::object{{"arity", static_cast<long long>(attribsTypes.size())},
                                  {"auxArity", static_cast<long long>(0)},
                                  {"types", Json::array(attribsTypes.begin(), attribsTypes.end())}}}};
     std::map<std::string, std::string> dirs = {{"operation", "output"}, {"IO", "stdout"},
             {"attributeNames", "x\ty"}, {"name", "test"}, {"delimiter", delimiter}, {"types", types.dump()}};
     std::map<std::string, std::string> ioDirs = std::map<std::string, std::string>(dirs);
     std::vector<std::unique_ptr<RamExpression>> exprs;
     for (RamDomain i : randomNumbers) {
         exprs.push_back(std::make_unique<RamSignedConstant>(i));
     }
     std::unique_ptr<RamStatement> main = std::make_unique<RamSequence>(
             std::make_unique<RamQuery>(std::make_unique<RamProject>(std::move(ref1), std::move(exprs))),
             std::make_unique<RamIO>(std::move(ref2), ioDirs));
     rels.push_back(std::move(myrel));
     std::map<std::string, std::unique_ptr<RamStatement>> subs;
     std::unique_ptr<RamProgram> prog =
             std::make_unique<RamProgram>(std::move(rels), std::move(main), std::move(subs));
     SymbolTable symTab;
     ErrorReport errReport;
     DebugReport debugReport;
     RamTranslationUnit translationUnit(std::move(prog), symTab, errReport, debugReport);
     // configure and execute interpreter
     std::unique_ptr<InterpreterEngine> interpreter = std::make_unique<InterpreterEngine>(translationUnit);
     std::streambuf* oldCoutStreambuf = std::cout.rdbuf();
     std::ostringstream sout;
     std::cout.rdbuf(sout.rdbuf());
     interpreter->executeMain();
     std::cout.rdbuf(oldCoutStreambuf);
     std::stringstream expected;
     expected << "---------------"
              << "\n"
              << "test"
              << "\n"
              << "==============="
              << "\n"
              << randomNumbers[0];
     for (size_t i = 1; i < randomNumbers.size(); ++i) {
         expected << delimiter << randomNumbers[i];
     }
     expected << "\n"
              << "==============="
              << "\n";
     EXPECT_EQ(expected.str(), sout.str());
 }
TEST() [134/228]
souffle::test::TEST (Binary , UnsignedAdd)
Definition at line 235 of file ram_arithmetic_test.cpp.
References evalBinary(), EXPECT_EQ, i, souffle::ramBitCast(), TESTS_PER_OPERATION, and souffle::UADD.
{
     FunctorOp functor = FunctorOp::UADD;
     auto vecArg1 = testutil::generateRandomVector<RamUnsigned>(TESTS_PER_OPERATION);
     auto vecArg2 = testutil::generateRandomVector<RamUnsigned>(TESTS_PER_OPERATION);
     for (int i = 0; i < TESTS_PER_OPERATION; ++i) {
         RamUnsigned arg1 = vecArg1[i];
         RamUnsigned arg2 = vecArg2[i];
         RamDomain result = evalBinary(functor, ramBitCast(arg1), ramBitCast(arg2));
         EXPECT_EQ(ramBitCast<RamUnsigned>(result), arg1 + arg2);
     }
 }
TEST() [135/228]
souffle::test::TEST (BTreeSet , Shuffled)
Definition at line 235 of file btree_set_test.cpp.
References EXPECT_TRUE, and i.
{
     using test_set = btree_set<int, detail::comparator<int>, std::allocator<int>, 16>;
     test_set t;
     int N = 10000;
     std::vector<int> data;
     for (int i = 0; i < N; i++) {
         data.push_back(i);
     }
     std::random_device rd;
     std::mt19937 generator(rd());
     shuffle(data.begin(), data.end(), generator);
     for (int i = 0; i < N; i++) {
         t.insert(data[i]);
     }
     //        t.printTree();
     for (int i = 0; i < N; i++) {
         EXPECT_TRUE(t.contains(i)) << "i=" << i;
     }
 }
TEST() [136/228]
souffle::test::TEST (AstTransformers , CheckClausalEquivalence)
Test the equivalence (or lack of equivalence) of clauses using the MinimiseProgramTransfomer.
Definition at line 237 of file ast_transformers_test.cpp.
References souffle::MinimiseProgramTransformer::areBijectivelyEquivalent(), EXPECT_EQ, EXPECT_FALSE, EXPECT_TRUE, souffle::getClauses(), souffle::ParserDriver::parseTranslationUnit(), and souffle::toString().
{
     ErrorReport errorReport;
     DebugReport debugReport;
     std::unique_ptr<AstTranslationUnit> tu = ParserDriver::parseTranslationUnit(
             R"(
                 .decl A(x:number, y:number)
                 .decl B(x:number)
                 .decl C(x:number)
                 A(0,0).
                 A(0,0).
                 A(0,1).
                 B(1).
                 C(z) :- A(z,y), A(z,x), x != 3, x < y, !B(x), y > 3, B(y).
                 C(r) :- A(r,y), A(r,x), x != 3, x < y, !B(y), y > 3, B(y), B(x), x < y.
                 C(x) :- A(x,a), a != 3, !B(a), A(x,b), b > 3, B(c), a < b, c = b.
             )",
             errorReport, debugReport);
     const auto& program = *tu->getProgram();
     // Resolve aliases to remove trivial equalities
     std::make_unique<ResolveAliasesTransformer>()->apply(*tu);
     auto aClauses = getClauses(program, "A");
     auto bClauses = getClauses(program, "B");
     auto cClauses = getClauses(program, "C");
     EXPECT_EQ(3, aClauses.size());
     EXPECT_EQ("A(0,0).", toString(*aClauses[0]));
     EXPECT_EQ("A(0,0).", toString(*aClauses[1]));
     EXPECT_EQ("A(0,1).", toString(*aClauses[2]));
     EXPECT_EQ(1, bClauses.size());
     EXPECT_EQ("B(1).", toString(*bClauses[0]));
     EXPECT_EQ(3, cClauses.size());
     EXPECT_EQ("C(z) :- \n   A(z,y),\n   A(z,x),\n   x != 3,\n   x < y,\n   !B(x),\n   y > 3,\n   B(y).",
             toString(*cClauses[0]));
     EXPECT_EQ(
             "C(r) :- \n   A(r,y),\n   A(r,x),\n   x != 3,\n   x < y,\n   !B(y),\n   y > 3,\n   B(y),\n   "
             "B(x).",
             toString(*cClauses[1]));
     EXPECT_EQ("C(x) :- \n   A(x,a),\n   a != 3,\n   !B(a),\n   A(x,b),\n   b > 3,\n   B(b),\n   a < b.",
             toString(*cClauses[2]));
     // Check equivalence of these clauses
     // -- A
     EXPECT_TRUE(MinimiseProgramTransformer::areBijectivelyEquivalent(aClauses[0], aClauses[1]));
     EXPECT_TRUE(MinimiseProgramTransformer::areBijectivelyEquivalent(aClauses[1], aClauses[0]));
     EXPECT_FALSE(MinimiseProgramTransformer::areBijectivelyEquivalent(aClauses[1], aClauses[2]));
     EXPECT_FALSE(MinimiseProgramTransformer::areBijectivelyEquivalent(aClauses[0], aClauses[2]));
     // -- C
     EXPECT_TRUE(MinimiseProgramTransformer::areBijectivelyEquivalent(cClauses[0], cClauses[2]));
     EXPECT_FALSE(MinimiseProgramTransformer::areBijectivelyEquivalent(cClauses[0], cClauses[1]));
     EXPECT_FALSE(MinimiseProgramTransformer::areBijectivelyEquivalent(cClauses[2], cClauses[1]));
     // Make sure equivalent (and only equivalent) clauses are removed by the minimiser
     std::make_unique<MinimiseProgramTransformer>()->apply(*tu);
     auto aMinClauses = getClauses(program, "A");
     auto bMinClauses = getClauses(program, "B");
     auto cMinClauses = getClauses(program, "C");
     EXPECT_EQ(2, aMinClauses.size());
     EXPECT_EQ("A(0,0).", toString(*aMinClauses[0]));
     EXPECT_EQ("A(0,1).", toString(*aMinClauses[1]));
     EXPECT_EQ(1, bMinClauses.size());
     EXPECT_EQ("B(1).", toString(*bMinClauses[0]));
     EXPECT_EQ(2, cMinClauses.size());
     EXPECT_EQ("C(z) :- \n   A(z,y),\n   A(z,x),\n   x != 3,\n   x < y,\n   !B(x),\n   y > 3,\n   B(y).",
             toString(*cMinClauses[0]));
     EXPECT_EQ(
             "C(r) :- \n   A(r,y),\n   A(r,x),\n   x != 3,\n   x < y,\n   !B(y),\n   y > 3,\n   B(y),\n   "
             "B(x).",
             toString(*cMinClauses[1]));
 }
TEST() [137/228]
souffle::test::TEST (RamEmptinessCheck , CloneAndEquals)
Definition at line 237 of file ram_condition_equal_clone_test.cpp.
References b, souffle::RamEmptinessCheck::clone(), souffle::DEFAULT, EXPECT_EQ, and EXPECT_NE.
{
     // Check A(x:number)
     RamRelation A("A", 1, 1, {"x"}, {"i"}, RelationRepresentation::DEFAULT);
     RamEmptinessCheck a(std::make_unique<RamRelationReference>(&A));
     RamEmptinessCheck b(std::make_unique<RamRelationReference>(&A));
     EXPECT_EQ(a, b);
     EXPECT_NE(&a, &b);
     RamEmptinessCheck* c = a.clone();
     EXPECT_EQ(a, *c);
     EXPECT_EQ(b, *c);
     EXPECT_NE(&a, c);
     EXPECT_NE(&b, c);
     delete c;
 }
TEST() [138/228]
souffle::test::TEST (TypeSystem , RecordSubsets)
Definition at line 247 of file type_system_test.cpp.
References souffle::TypeEnvironment::createType(), EXPECT_EQ, EXPECT_PRED2, souffle::getGreatestCommonSubtypes(), souffle::isSubtypeOf(), and souffle::toString().
{
     TypeEnvironment env;
     auto& R = env.createType<RecordType>("R");
     auto& A = env.createType<SubsetType>("A", R);
     EXPECT_PRED2(isSubtypeOf, A, R);
     EXPECT_EQ("{A}", toString(getGreatestCommonSubtypes(A, R)));
 }
TEST() [139/228]
souffle::test::TEST (RamIndexChoice , CloneAndEquals)
Definition at line 247 of file ram_operation_equal_clone_test.cpp.
References b, souffle::RamIndexChoice::clone(), souffle::DEFAULT, souffle::EQ, EXPECT_EQ, and EXPECT_NE.
{
     RamRelation edge("edge", 2, 1, {"x", "y"}, {"i", "i"}, RelationRepresentation::DEFAULT);
     // FOR t1 IN edge ON INDEX t1.x = 5 AND t1.y =
     // WHERE NOT t1.1 = 5
     //  RETURN (t1.0, t1.1)
     std::vector<std::unique_ptr<RamExpression>> a_return_args;
     a_return_args.emplace_back(new RamTupleElement(1, 0));
     a_return_args.emplace_back(new RamTupleElement(1, 1));
     auto a_return = std::make_unique<RamSubroutineReturn>(std::move(a_return_args));
     auto a_constraint = std::make_unique<RamConstraint>(BinaryConstraintOp::EQ,
             std::make_unique<RamTupleElement>(1, 1), std::make_unique<RamSignedConstant>(5));
     auto a_neg = std::make_unique<RamNegation>(std::move(a_constraint));
     RamPattern a_criteria;
     a_criteria.first.emplace_back(new RamSignedConstant(5));
     a_criteria.first.emplace_back(new RamUndefValue);
     a_criteria.second.emplace_back(new RamSignedConstant(5));
     a_criteria.second.emplace_back(new RamUndefValue);
     RamIndexChoice a(std::make_unique<RamRelationReference>(&edge), 1, std::move(a_neg),
             std::move(a_criteria), std::move(a_return), "RamIndexChoice test");
     std::vector<std::unique_ptr<RamExpression>> b_return_args;
     b_return_args.emplace_back(new RamTupleElement(1, 0));
     b_return_args.emplace_back(new RamTupleElement(1, 1));
     auto b_return = std::make_unique<RamSubroutineReturn>(std::move(b_return_args));
     auto b_constraint = std::make_unique<RamConstraint>(BinaryConstraintOp::EQ,
             std::make_unique<RamTupleElement>(1, 1), std::make_unique<RamSignedConstant>(5));
     auto b_neg = std::make_unique<RamNegation>(std::move(b_constraint));
     RamPattern b_criteria;
     b_criteria.first.emplace_back(new RamSignedConstant(5));
     b_criteria.first.emplace_back(new RamUndefValue);
     b_criteria.second.emplace_back(new RamSignedConstant(5));
     b_criteria.second.emplace_back(new RamUndefValue);
     RamIndexChoice b(std::make_unique<RamRelationReference>(&edge), 1, std::move(b_neg),
             std::move(b_criteria), std::move(b_return), "RamIndexChoice test");
     EXPECT_EQ(a, b);
     EXPECT_NE(&a, &b);
     RamIndexChoice* c = a.clone();
     EXPECT_EQ(a, *c);
     EXPECT_NE(&a, c);
     delete c;
 }
TEST() [140/228]
souffle::test::TEST (Binary , FloatAdd)
Definition at line 249 of file ram_arithmetic_test.cpp.
References evalBinary(), EXPECT_EQ, souffle::FADD, i, souffle::ramBitCast(), and TESTS_PER_OPERATION.
{
     FunctorOp functor = FunctorOp::FADD;
     auto vecArg1 = testutil::generateRandomVector<RamFloat>(TESTS_PER_OPERATION);
     auto vecArg2 = testutil::generateRandomVector<RamFloat>(TESTS_PER_OPERATION);
     for (int i = 0; i < TESTS_PER_OPERATION; ++i) {
         auto arg1 = vecArg1[i];
         auto arg2 = vecArg2[i];
         RamDomain result = evalBinary(functor, ramBitCast(arg1), ramBitCast(arg2));
         EXPECT_EQ(ramBitCast<RamFloat>(result), arg1 + arg2);
     }
 }
TEST() [141/228]
souffle::test::TEST (BTreeMultiSet , IteratorStress)
Definition at line 250 of file btree_multiset_test.cpp.
References EXPECT_EQ, EXPECT_LT, and i.
{
     using test_set = btree_multiset<int, detail::comparator<int>, std::allocator<int>, 16>;
     test_set t;
     int N = 1000;
     std::vector<int> data;
     for (int i = 0; i < N; i++) {
         data.push_back(i);
     }
     std::random_device rd;
     std::mt19937 generator(rd());
     shuffle(data.begin(), data.end(), generator);
     for (int i = 0; i < N; i++) {
         EXPECT_EQ((size_t)i, t.size());
         int last = -1;
         for (int i : t) {
             EXPECT_LT(last, i);
             last = i;
         }
         t.insert(data[i]);
     }
 }
TEST() [142/228]
souffle::test::TEST (TypeSystem , EquivTypes)
Definition at line 258 of file type_system_test.cpp.
References souffle::areEquivalentTypes(), souffle::TypeEnvironment::createType(), EXPECT_TRUE, souffle::TypeEnvironment::getType(), and souffle::toVector().
{
     TypeEnvironment env;
     auto& A = env.createType<SubsetType>("A", env.getType("number"));
     auto& U = env.createType<UnionType>("U", toVector(dynamic_cast<const Type*>(&A)));
     EXPECT_TRUE(areEquivalentTypes(A, U));
 }
TEST() [143/228]
souffle::test::TEST (RamLoop , CloneAndEquals)
Definition at line 258 of file ram_statement_equal_clone_test.cpp.
References b, souffle::RamLoop::clone(), souffle::DEFAULT, souffle::EQ, EXPECT_EQ, and EXPECT_NE.
{
     RamRelation A("A", 1, 1, {"x"}, {"i"}, RelationRepresentation::DEFAULT);
     RamRelation B("B", 1, 1, {"x"}, {"i"}, RelationRepresentation::DEFAULT);
     /*
      * LOOP
      *  QUERY
      *   FOR t0 IN A
      *    IF t0.0 = 4 BREAK
      *    PROJECT (t0.0) INTO B
      * END LOOP
      * */
     std::vector<std::unique_ptr<RamExpression>> a_expressions;
     a_expressions.emplace_back(new RamTupleElement(0, 0));
     auto a_project = std::make_unique<RamProject>(
             std::make_unique<RamRelationReference>(&B), std::move(a_expressions));
     auto a_break = std::make_unique<RamBreak>(
             std::make_unique<RamConstraint>(BinaryConstraintOp::EQ, std::make_unique<RamTupleElement>(0, 0),
                     std::make_unique<RamSignedConstant>(4)),
             std::move(a_project), "");
     auto a_scan =
             std::make_unique<RamScan>(std::make_unique<RamRelationReference>(&A), 0, std::move(a_break), "");
     auto a_query = std::make_unique<RamQuery>(std::move(a_scan));
     RamLoop a(std::move(a_query));
     std::vector<std::unique_ptr<RamExpression>> b_expressions;
     b_expressions.emplace_back(new RamTupleElement(0, 0));
     auto b_project = std::make_unique<RamProject>(
             std::make_unique<RamRelationReference>(&B), std::move(b_expressions));
     auto b_break = std::make_unique<RamBreak>(
             std::make_unique<RamConstraint>(BinaryConstraintOp::EQ, std::make_unique<RamTupleElement>(0, 0),
                     std::make_unique<RamSignedConstant>(4)),
             std::move(b_project), "");
     auto b_scan =
             std::make_unique<RamScan>(std::make_unique<RamRelationReference>(&A), 0, std::move(b_break), "");
     auto b_query = std::make_unique<RamQuery>(std::move(b_scan));
     RamLoop b(std::move(b_query));
     EXPECT_EQ(a, b);
     EXPECT_NE(&a, &b);
     RamLoop* c = a.clone();
     EXPECT_EQ(a, *c);
     EXPECT_NE(&a, c);
     delete c;
 }
TEST() [144/228]
souffle::test::TEST (DjTest , Scoping)
The underlying Disjoint Set (essentially Anderson '91 Find-Union, but dynamic)
Definition at line 259 of file eqrel_datastructure_test.cpp.
                       {
     souffle::DisjointSet ds;
 }
TEST() [145/228]
souffle::test::TEST (BTreeSet , Copy)
Definition at line 262 of file btree_set_test.cpp.
References EXPECT_EQ, EXPECT_FALSE, EXPECT_NE, EXPECT_TRUE, and i.
                      {
     using test_set = btree_set<int>;
     test_set t;
     int N = 100000;
     std::vector<int> data;
     for (int i = 0; i < N; i++) {
         data.push_back(i);
     }
     std::random_device rd;
     std::mt19937 generator(rd());
     shuffle(data.begin(), data.end(), generator);
     for (int i = 0; i < N; i++) {
         t.insert(data[i]);
     }
     EXPECT_EQ((size_t)N, t.size());
     for (int i = 0; i < N; i++) {
         EXPECT_TRUE(t.find(i) != t.end()) << "i=" << i;
     }
     test_set t2;
     EXPECT_EQ((size_t)N, t.size());
     EXPECT_EQ(0, t2.size());
     t2 = t;
     EXPECT_EQ((size_t)N, t.size());
     EXPECT_EQ((size_t)N, t2.size());
     for (int i = 0; i < N; i++) {
         EXPECT_TRUE(t.find(i) != t.end()) << "i=" << i;
     }
     for (int i = 0; i < N; i++) {
         EXPECT_TRUE(t2.find(i) != t2.end()) << "i=" << i;
     }
     EXPECT_FALSE(t.find(N + 1) != t.end());
     EXPECT_FALSE(t2.find(N + 1) != t2.end());
     t2.insert(N + 1);
     EXPECT_FALSE(t.find(N + 1) != t.end());
     EXPECT_TRUE(t2.find(N + 1) != t2.end());
     for (int i = 0; i < N; i++) {
         EXPECT_NE(&*t.find(i), &*t2.find(i)) << "i=" << i;
     }
 }
TEST() [146/228]
souffle::test::TEST (Binary , SignedSub)
Definition at line 263 of file ram_arithmetic_test.cpp.
References evalBinary(), EXPECT_EQ, i, souffle::SUB, and TESTS_PER_OPERATION.
{
     FunctorOp functor = FunctorOp::SUB;
     auto vecArg1 = testutil::generateRandomVector<RamDomain>(TESTS_PER_OPERATION);
     auto vecArg2 = testutil::generateRandomVector<RamDomain>(TESTS_PER_OPERATION);
     for (int i = 0; i < TESTS_PER_OPERATION; ++i) {
         auto arg1 = vecArg1[i];
         auto arg2 = vecArg2[i];
         RamDomain result = evalBinary(functor, arg1, arg2);
         EXPECT_EQ(result, arg1 - arg2);
     }
 }
TEST() [147/228]
souffle::test::TEST (DjTest , MakeNode)
Definition at line 263 of file eqrel_datastructure_test.cpp.
References souffle::DisjointSet::b2p(), souffle::DisjointSet::b2r(), EXPECT_EQ, souffle::DisjointSet::makeNode(), n, and souffle::DisjointSet::size().
{
     souffle::DisjointSet ds;
     EXPECT_EQ(ds.size(), 0);
     souffle::block_t n = ds.makeNode();
     // parent should be itself
     EXPECT_EQ(DisjointSet::b2p(n), 0);
     // rank should be 0
     EXPECT_EQ(DisjointSet::b2r(n), 0);
     EXPECT_EQ(ds.size(), 1);
     souffle::block_t n2 = ds.makeNode();
     // parent should be itself
     EXPECT_EQ(DisjointSet::b2p(n2), 1);
     // rank should be 0
     EXPECT_EQ(DisjointSet::b2r(n2), 0);
     EXPECT_EQ(ds.size(), 2);
 }
TEST() [148/228]
souffle::test::TEST (Binary , UnsignedSub)
Definition at line 277 of file ram_arithmetic_test.cpp.
References evalBinary(), EXPECT_EQ, i, souffle::ramBitCast(), TESTS_PER_OPERATION, and souffle::USUB.
{
     FunctorOp functor = FunctorOp::USUB;
     auto vecArg1 = testutil::generateRandomVector<RamUnsigned>(TESTS_PER_OPERATION);
     auto vecArg2 = testutil::generateRandomVector<RamUnsigned>(TESTS_PER_OPERATION);
     for (int i = 0; i < TESTS_PER_OPERATION; ++i) {
         auto arg1 = vecArg1[i];
         auto arg2 = vecArg2[i];
         RamDomain result = evalBinary(functor, ramBitCast(arg1), ramBitCast(arg2));
         EXPECT_EQ(ramBitCast<RamUnsigned>(result), arg1 - arg2);
     }
 }
TEST() [149/228]
souffle::test::TEST (BTreeMultiSet , BoundaryTest)
Definition at line 279 of file btree_multiset_test.cpp.
References b, EXPECT_EQ, i, and souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::insert().
{
     using test_set = btree_multiset<int, detail::comparator<int>, std::allocator<int>, 16>;
     test_set t;
     for (int i = 0; i < 10; i++) {
         t.insert(i);
     }
     //        t.printTree();
     auto a = t.lower_bound(5);
     EXPECT_EQ(5, *a);
     auto b = t.upper_bound(5);
     EXPECT_EQ(6, *b);
     // add duplicates
     t.insert(5);
     t.insert(5);
     t.insert(5);
     //        t.printTree(); std::cout << "\n";
     // test again ..
     a = t.lower_bound(5);
     EXPECT_EQ(5, *a);
     b = t.upper_bound(5);
     EXPECT_EQ(6, *b);
     // check the distance
     EXPECT_EQ(5, *a);
     ++a;
     EXPECT_EQ(5, *a);
     ++a;
     EXPECT_EQ(5, *a);
     ++a;
     EXPECT_EQ(5, *a);
     ++a;
     EXPECT_EQ(6, *a);
 }
TEST() [150/228]
souffle::test::TEST (DjTest , TestUnion)
Definition at line 281 of file eqrel_datastructure_test.cpp.
References souffle::DisjointSet::b2p(), EXPECT_EQ, EXPECT_FALSE, EXPECT_TRUE, souffle::DisjointSet::makeNode(), souffle::DisjointSet::sameSet(), souffle::DisjointSet::size(), and souffle::DisjointSet::unionNodes().
{
     // check whether the unioning works to see if the elements are properly in the same set
     souffle::DisjointSet ds;
     parent_t n1 = DisjointSet::b2p(ds.makeNode());
     parent_t n2 = DisjointSet::b2p(ds.makeNode());
     parent_t n3 = DisjointSet::b2p(ds.makeNode());
     parent_t n4 = DisjointSet::b2p(ds.makeNode());
     parent_t n5 = DisjointSet::b2p(ds.makeNode());
     EXPECT_EQ(ds.size(), 5);
     // test running same set doesn't accidentally union them
     EXPECT_FALSE(ds.sameSet(n1, n2));
     EXPECT_FALSE(ds.sameSet(n1, n2));
     EXPECT_FALSE(ds.sameSet(n1, n2));
     EXPECT_FALSE(ds.sameSet(n1, n2));
     ds.unionNodes(n1, n2);
     EXPECT_TRUE(ds.sameSet(n1, n2));
     EXPECT_FALSE(ds.sameSet(n3, n2));
     ds.unionNodes(n3, n4);
     ds.unionNodes(n3, n5);
     ds.unionNodes(n1, n5);
     // ensure that nodes that weren't explicitly connected are in fact connected
     EXPECT_TRUE(ds.sameSet(n1, n4));
     // and their symmetric
     EXPECT_TRUE(ds.sameSet(n4, n1));
     // size shouldn't change
     EXPECT_EQ(ds.size(), 5);
 }
TEST() [151/228]
souffle::test::TEST (EqRelTest , Merge)
Definition at line 282 of file binary_relation_test.cpp.
References souffle::EquivalenceRelation< TupleType >::begin(), souffle::EquivalenceRelation< TupleType >::clear(), count(), souffle::EquivalenceRelation< TupleType >::end(), EXPECT_EQ, EXPECT_FALSE, i, testutil::ignore(), souffle::EquivalenceRelation< TupleType >::insert(), and souffle::EquivalenceRelation< TupleType >::size().
{
     // test insertAll isolates data
     EqRel br;
     int N = 100;
     std::vector<int> data;
     for (int i = 0; i < N; i++) {
         data.push_back(i);
     }
     std::random_device rd;
     std::mt19937 generator(rd());
     shuffle(data.begin(), data.end(), generator);
     for (int i = 0; i < N; i++) {
         br.insert(data[i], data[i]);
     }
     // also insert a joint pair
     br.insert(N - 1, N + 1);
     EXPECT_EQ((size_t)N + 3, br.size());
     EqRel br2;
     EXPECT_EQ(0, br2.size());
     size_t count = 0;
     for (auto x : br2) {
         ++count;
         testutil::ignore(x);
     }
     EXPECT_EQ(count, br2.size());
     br2.insertAll(br);
     EXPECT_EQ((size_t)N + 3, br2.size());
     EXPECT_EQ((size_t)N + 3, br.size());
     count = 0;
     for (auto x : br2) {
         ++count;
         testutil::ignore(x);
     }
     EXPECT_EQ(count, br2.size());
     br.clear();
     EXPECT_EQ((size_t)N + 3, br2.size());
     EXPECT_EQ(0, br.size());
     EXPECT_FALSE(br.begin() != br.end());
     count = 0;
     for (auto x : br) {
         ++count;
         testutil::ignore(x);
     }
     EXPECT_EQ(count, br.size());
     br2.clear();
     EXPECT_EQ(0, br2.size());
     EXPECT_EQ(0, br.size());
     count = 0;
     for (auto x : br2) {
         ++count;
         testutil::ignore(x);
     }
     EXPECT_EQ(count, br2.size());
 }
TEST() [152/228]
souffle::test::TEST (RamiParallelIndexChoice , CloneAndEquals)
Definition at line 290 of file ram_operation_equal_clone_test.cpp.
References b, souffle::RamParallelIndexChoice::clone(), souffle::DEFAULT, souffle::EQ, EXPECT_EQ, and EXPECT_NE.
{
     RamRelation edge("edge", 2, 1, {"x", "y"}, {"i", "i"}, RelationRepresentation::DEFAULT);
     // PARALLEL FOR t1 IN edge ON INDEX t1.x = 5 AND t1.y =
     // WHERE NOT t1.1 = 5
     //  RETURN (t1.0, t1.1)
     std::vector<std::unique_ptr<RamExpression>> a_return_args;
     a_return_args.emplace_back(new RamTupleElement(1, 0));
     a_return_args.emplace_back(new RamTupleElement(1, 1));
     auto a_return = std::make_unique<RamSubroutineReturn>(std::move(a_return_args));
     auto a_constraint = std::make_unique<RamConstraint>(BinaryConstraintOp::EQ,
             std::make_unique<RamTupleElement>(1, 1), std::make_unique<RamSignedConstant>(5));
     auto a_neg = std::make_unique<RamNegation>(std::move(a_constraint));
     RamPattern a_criteria;
     a_criteria.first.emplace_back(new RamSignedConstant(5));
     a_criteria.first.emplace_back(new RamUndefValue);
     a_criteria.second.emplace_back(new RamSignedConstant(5));
     a_criteria.second.emplace_back(new RamUndefValue);
     RamParallelIndexChoice a(std::make_unique<RamRelationReference>(&edge), 1, std::move(a_neg),
             std::move(a_criteria), std::move(a_return), "RamIndexChoice test");
     std::vector<std::unique_ptr<RamExpression>> b_return_args;
     b_return_args.emplace_back(new RamTupleElement(1, 0));
     b_return_args.emplace_back(new RamTupleElement(1, 1));
     auto b_return = std::make_unique<RamSubroutineReturn>(std::move(b_return_args));
     auto b_constraint = std::make_unique<RamConstraint>(BinaryConstraintOp::EQ,
             std::make_unique<RamTupleElement>(1, 1), std::make_unique<RamSignedConstant>(5));
     auto b_neg = std::make_unique<RamNegation>(std::move(b_constraint));
     RamPattern b_criteria;
     b_criteria.first.emplace_back(new RamSignedConstant(5));
     b_criteria.first.emplace_back(new RamUndefValue);
     b_criteria.second.emplace_back(new RamSignedConstant(5));
     b_criteria.second.emplace_back(new RamUndefValue);
     RamParallelIndexChoice b(std::make_unique<RamRelationReference>(&edge), 1, std::move(b_neg),
             std::move(b_criteria), std::move(b_return), "RamIndexChoice test");
     EXPECT_EQ(a, b);
     EXPECT_NE(&a, &b);
     RamParallelIndexChoice* c = a.clone();
     EXPECT_EQ(a, *c);
     EXPECT_NE(&a, c);
     delete c;
 }
TEST() [153/228]
souffle::test::TEST (Binary , FloatSub)
Definition at line 291 of file ram_arithmetic_test.cpp.
References evalBinary(), EXPECT_EQ, souffle::FSUB, i, souffle::ramBitCast(), and TESTS_PER_OPERATION.
{
     FunctorOp functor = FunctorOp::FSUB;
     auto vecArg1 = testutil::generateRandomVector<RamFloat>(TESTS_PER_OPERATION);
     auto vecArg2 = testutil::generateRandomVector<RamFloat>(TESTS_PER_OPERATION);
     for (int i = 0; i < TESTS_PER_OPERATION; ++i) {
         auto arg1 = vecArg1[i];
         auto arg2 = vecArg2[i];
         RamDomain result = evalBinary(functor, ramBitCast(arg1), ramBitCast(arg2));
         EXPECT_EQ(ramBitCast<RamFloat>(result), arg1 - arg2);
     }
 }
TEST() [154/228]
souffle::test::TEST (RamExit , CloneAndEquals)
Definition at line 302 of file ram_statement_equal_clone_test.cpp.
References b, souffle::RamExit::clone(), souffle::DEFAULT, EXPECT_EQ, and EXPECT_NE.
{
     RamRelation A("A", 1, 1, {"x"}, {"i"}, RelationRepresentation::DEFAULT);
     // EXIT (A = )
     RamExit a(std::make_unique<RamEmptinessCheck>(std::make_unique<RamRelationReference>(&A)));
     RamExit b(std::make_unique<RamEmptinessCheck>(std::make_unique<RamRelationReference>(&A)));
     EXPECT_EQ(a, b);
     EXPECT_NE(&a, &b);
     RamExit* c = a.clone();
     EXPECT_EQ(a, *c);
     EXPECT_NE(&a, c);
     delete c;
 }
TEST() [155/228]
souffle::test::TEST (Binary , SignedMul)
Definition at line 305 of file ram_arithmetic_test.cpp.
References evalBinary(), EXPECT_EQ, i, souffle::MUL, and TESTS_PER_OPERATION.
{
     FunctorOp functor = FunctorOp::MUL;
     auto vecArg1 = testutil::generateRandomVector<RamDomain>(TESTS_PER_OPERATION);
     auto vecArg2 = testutil::generateRandomVector<RamDomain>(TESTS_PER_OPERATION);
     for (int i = 0; i < TESTS_PER_OPERATION; ++i) {
         auto arg1 = vecArg1[i];
         auto arg2 = vecArg2[i];
         RamDomain result = evalBinary(functor, arg1, arg2);
         EXPECT_EQ(result, arg1 * arg2);
     }
 }
TEST() [156/228]
souffle::test::TEST (IO_store , MixedTypes)
Definition at line 311 of file ram_relation_test.cpp.
References souffle::BTREE, souffle::Global::config(), EXPECT_EQ, souffle::main(), souffle::ramBitCast(), and types.
{
     Global::config().set("jobs", "1");
     std::vector<std::unique_ptr<RamRelation>> rels;
     std::vector<std::string> attribs{"t", "o", "s", "i", "a"};
     std::vector<std::string> attribsTypes{"i", "u", "f", "f", "s"};
     std::unique_ptr<RamRelation> myrel =
             std::make_unique<RamRelation>("test", 5, 0, attribs, attribsTypes, RelationRepresentation::BTREE);
     std::unique_ptr<RamRelationReference> ref1 = std::make_unique<RamRelationReference>(myrel.get());
     std::unique_ptr<RamRelationReference> ref2 = std::make_unique<RamRelationReference>(myrel.get());
     Json types = Json::object{
             {"relation", Json::object{{"arity", static_cast<long long>(attribsTypes.size())},
                                  {"auxArity", static_cast<long long>(0)},
                                  {"types", Json::array(attribsTypes.begin(), attribsTypes.end())}}}};
     std::map<std::string, std::string> dirs = {{"operation", "output"}, {"IO", "stdout"},
             {"attributeNames", "x\ty"}, {"name", "test"}, {"types", types.dump()}};
     std::map<std::string, std::string> ioDirs = std::map<std::string, std::string>(dirs);
     SymbolTable symbolTable;
     ErrorReport errReport;
     DebugReport debugReport;
     std::vector<std::unique_ptr<RamExpression>> exprs;
     RamFloat floatValue = 27.75;
     exprs.push_back(std::make_unique<RamSignedConstant>(3));
     exprs.push_back(std::make_unique<RamSignedConstant>(ramBitCast(static_cast<RamUnsigned>(27))));
     exprs.push_back(std::make_unique<RamSignedConstant>(ramBitCast(static_cast<RamFloat>(floatValue))));
     exprs.push_back(std::make_unique<RamSignedConstant>(ramBitCast(static_cast<RamFloat>(floatValue))));
     exprs.push_back(std::make_unique<RamSignedConstant>(symbolTable.lookup("meow")));
     std::unique_ptr<RamStatement> main = std::make_unique<RamSequence>(
             std::make_unique<RamQuery>(std::make_unique<RamProject>(std::move(ref1), std::move(exprs))),
             std::make_unique<RamIO>(std::move(ref2), ioDirs));
     rels.push_back(std::move(myrel));
     std::map<std::string, std::unique_ptr<RamStatement>> subs;
     std::unique_ptr<RamProgram> prog =
             std::make_unique<RamProgram>(std::move(rels), std::move(main), std::move(subs));
     RamTranslationUnit translationUnit(std::move(prog), symbolTable, errReport, debugReport);
     // configure and execute interpreter
     std::unique_ptr<InterpreterEngine> interpreter = std::make_unique<InterpreterEngine>(translationUnit);
     std::streambuf* oldCoutStreambuf = std::cout.rdbuf();
     std::ostringstream sout;
     std::cout.rdbuf(sout.rdbuf());
     interpreter->executeMain();
     std::cout.rdbuf(oldCoutStreambuf);
     std::stringstream expected;
     expected << std::setprecision(std::numeric_limits<RamFloat>::max_digits10);
     expected << "---------------"
              << "\n"
              << "test"
              << "\n"
              << "==============="
              << "\n"
              << 3 << "\t" << 27 << "\t" << floatValue << "\t" << floatValue << "\t"
              << "meow"
              << "\n"
              << "==============="
              << "\n";
     EXPECT_EQ(expected.str(), sout.str());
 }
TEST() [157/228]
souffle::test::TEST (DjTest , Clear)
Definition at line 315 of file eqrel_datastructure_test.cpp.
References souffle::DisjointSet::clear(), EXPECT_EQ, souffle::DisjointSet::findNode(), i, souffle::DisjointSet::makeNode(), souffle::DisjointSet::size(), TEST(), and souffle::DisjointSet::unionNodes().
                     {
     souffle::DisjointSet ds;
     ds.clear();
     EXPECT_EQ(ds.size(), 0);
     // get ready 2 double free y'all
     for (size_t i = 0; i < 10000; ++i) {
         ds.makeNode();
     }
     ds.unionNodes(1, 2);
     ds.clear();
     ds.clear();
 }
TEST() [158/228]
souffle::test::TEST (BTreeSet , Merge)
Definition at line 315 of file btree_set_test.cpp.
References b, d, and EXPECT_NE.
                       {
     using test_set = btree_set<int>;
     test_set a;
     test_set b;
     a.insert(1);
     a.insert(2);
     a.insert(3);
     a.insert(4);
     b.insert(2);
     b.insert(4);
     b.insert(6);
     EXPECT_NE(a, b);
     test_set c = a;
     test_set d = b;
     EXPECT_NE(c, d);
 }
TEST() [159/228]
souffle::test::TEST (RamLogRelationTimer , CloneAndEquals)
Definition at line 316 of file ram_statement_equal_clone_test.cpp.
References b, souffle::RamLogRelationTimer::clone(), souffle::DEFAULT, EXPECT_EQ, and EXPECT_NE.
{
     RamRelation A("A", 1, 1, {"x"}, {"i"}, RelationRepresentation::DEFAULT);
     /*
      * START_TIMER ON A "file.dl [8:1-8:8]"
      *   IO A()
      * END_TIMER
      * */
     std::map<std::string, std::string> a_IODir;
     std::map<std::string, std::string> b_IODir;
     RamLogRelationTimer a(
             std::make_unique<RamIO>(std::make_unique<RamRelationReference>(&A), std::move(a_IODir)),
             "file.dl [8:1-8:8]", std::make_unique<RamRelationReference>(&A));
     RamLogRelationTimer b(
             std::make_unique<RamIO>(std::make_unique<RamRelationReference>(&A), std::move(b_IODir)),
             "file.dl [8:1-8:8]", std::make_unique<RamRelationReference>(&A));
     EXPECT_EQ(a, b);
     EXPECT_NE(&a, &b);
     RamLogRelationTimer* c = a.clone();
     EXPECT_EQ(a, *c);
     EXPECT_NE(&a, c);
     delete c;
 }
TEST() [160/228]
souffle::test::TEST (Binary , UnsignedMul)
Definition at line 319 of file ram_arithmetic_test.cpp.
References evalBinary(), EXPECT_EQ, i, souffle::ramBitCast(), TESTS_PER_OPERATION, and souffle::UMUL.
{
     FunctorOp functor = FunctorOp::UMUL;
     auto vecArg1 = testutil::generateRandomVector<RamUnsigned>(TESTS_PER_OPERATION);
     auto vecArg2 = testutil::generateRandomVector<RamUnsigned>(TESTS_PER_OPERATION);
     for (int i = 0; i < TESTS_PER_OPERATION; ++i) {
         auto arg1 = vecArg1[i];
         auto arg2 = vecArg2[i];
         RamDomain result = evalBinary(functor, ramBitCast(arg1), ramBitCast(arg2));
         EXPECT_EQ(ramBitCast<RamUnsigned>(result), arg1 * arg2);
     }
 }
TEST() [161/228]
souffle::test::TEST (BTreeMultiSet , BoundaryEmpty)
Definition at line 323 of file btree_multiset_test.cpp.
References EXPECT_EQ, and EXPECT_NE.
{
     using test_set = btree_multiset<int, detail::comparator<int>, std::allocator<int>, 16>;
     test_set t;
     EXPECT_EQ(t.end(), t.lower_bound(5));
     EXPECT_EQ(t.end(), t.upper_bound(5));
     t.insert(4);
     EXPECT_EQ(t.lower_bound(3), t.upper_bound(3));
     EXPECT_EQ(t.lower_bound(5), t.upper_bound(5));
     t.insert(6);
     EXPECT_EQ(t.lower_bound(3), t.upper_bound(3));
     EXPECT_EQ(t.lower_bound(5), t.upper_bound(5));
     t.insert(5);
     EXPECT_EQ(t.lower_bound(3), t.upper_bound(3));
     EXPECT_NE(t.lower_bound(5), t.upper_bound(5));
 }
TEST() [162/228]
souffle::test::TEST (AstTransformers , RemoveClauseRedundancies)
Test the removal of redundancies within clauses using the MinimiseProgramTransformer.
In particular, the removal of:
intraclausal literals equivalent to another literal in the body e.g. a(x) :- b(x), b(x), c(x). –> a(x) :- b(x), c(x).
clauses that are only trivially satisfiable e.g. a(x) :- a(x), x != 0. is only true if a(x) is already true
Definition at line 328 of file ast_transformers_test.cpp.
References EXPECT_EQ, souffle::getClauses(), souffle::getRelation(), souffle::ParserDriver::parseTranslationUnit(), and souffle::toString().
{
     ErrorReport errorReport;
     DebugReport debugReport;
     std::unique_ptr<AstTranslationUnit> tu = ParserDriver::parseTranslationUnit(
             R"(
                 .decl a,b,c(X:number)
                 a(0).
                 b(1).
                 c(X) :- b(X).
                 a(X) :- b(X), c(X).
                 a(X) :- a(X).
                 a(X) :- a(X), X != 1.
                 q(X) :- a(X).
                 .decl q(X:number)
                 .output q()
             )",
             errorReport, debugReport);
     const auto& program = *tu->getProgram();
     // Invoking the `RemoveRelationCopiesTransformer` to create some extra redundancy
     // In particular: The relation `c` will be replaced with `b` throughout, creating
     // the clause b(x) :- b(x).
     std::make_unique<RemoveRelationCopiesTransformer>()->apply(*tu);
     EXPECT_EQ(nullptr, getRelation(program, "c"));
     auto bIntermediateClauses = getClauses(program, "b");
     EXPECT_EQ(2, bIntermediateClauses.size());
     EXPECT_EQ("b(1).", toString(*bIntermediateClauses[0]));
     EXPECT_EQ("b(X) :- \n   b(X).", toString(*bIntermediateClauses[1]));
     // Attempt to minimise the program
     std::make_unique<MinimiseProgramTransformer>()->apply(*tu);
     EXPECT_EQ(3, program.getRelations().size());
     auto aClauses = getClauses(program, "a");
     EXPECT_EQ(2, aClauses.size());
     EXPECT_EQ("a(0).", toString(*aClauses[0]));
     EXPECT_EQ("a(X) :- \n   b(X).", toString(*aClauses[1]));
     auto bClauses = getClauses(program, "b");
     EXPECT_EQ(1, bClauses.size());
     EXPECT_EQ("b(1).", toString(*bClauses[0]));
     auto qClauses = getClauses(program, "q");
     EXPECT_EQ(1, qClauses.size());
     EXPECT_EQ("q(X) :- \n   a(X).", toString(*qClauses[0]));
 }
TEST() [163/228]
souffle::test::TEST (Binary , FloatMul)
Definition at line 333 of file ram_arithmetic_test.cpp.
References evalBinary(), EXPECT_EQ, souffle::FMUL, i, souffle::ramBitCast(), and TESTS_PER_OPERATION.
{
     FunctorOp functor = FunctorOp::FMUL;
     auto vecArg1 = testutil::generateRandomVector<RamFloat>(TESTS_PER_OPERATION);
     auto vecArg2 = testutil::generateRandomVector<RamFloat>(TESTS_PER_OPERATION);
     for (int i = 0; i < TESTS_PER_OPERATION; ++i) {
         auto arg1 = vecArg1[i];
         auto arg2 = vecArg2[i];
         RamDomain result = evalBinary(functor, ramBitCast(arg1), ramBitCast(arg2));
         EXPECT_EQ(ramBitCast<RamFloat>(result), arg1 * arg2);
     }
 }
TEST() [164/228]
souffle::test::TEST (RamAggregate , CloneAndEquals)
Definition at line 333 of file ram_operation_equal_clone_test.cpp.
References b, souffle::RamAggregate::clone(), souffle::COUNT, souffle::DEFAULT, EXPECT_EQ, and EXPECT_NE.
{
     RamRelation edge("edge", 2, 1, {"x", "y"}, {"i", "i"}, RelationRepresentation::DEFAULT);
     // t0.0 = COUNT FOR ALL t1 IN edge
     //  RETURN t0.0
     std::vector<std::unique_ptr<RamExpression>> a_return_args;
     a_return_args.emplace_back(new RamTupleElement(0, 0));
     auto a_return = std::make_unique<RamSubroutineReturn>(std::move(a_return_args));
     RamAggregate a(std::move(a_return), AggregateOp::COUNT, std::make_unique<RamRelationReference>(&edge),
             std::make_unique<RamTupleElement>(0, 0), std::make_unique<RamTrue>(), 1);
     std::vector<std::unique_ptr<RamExpression>> b_return_args;
     b_return_args.emplace_back(new RamTupleElement(0, 0));
     auto b_return = std::make_unique<RamSubroutineReturn>(std::move(b_return_args));
     RamAggregate b(std::move(b_return), AggregateOp::COUNT, std::make_unique<RamRelationReference>(&edge),
             std::make_unique<RamTupleElement>(0, 0), std::make_unique<RamTrue>(), 1);
     EXPECT_EQ(a, b);
     EXPECT_NE(&a, &b);
     RamAggregate* c = a.clone();
     EXPECT_EQ(a, *c);
     EXPECT_NE(&a, c);
     delete c;
 }
TEST() [165/228]
souffle::test::TEST (BTreeSet , IteratorEmpty)
Definition at line 338 of file btree_set_test.cpp.
References EXPECT_EQ.
{
     using test_set = btree_set<int, detail::comparator<int>, std::allocator<int>, 16>;
     test_set t;
     EXPECT_EQ(t.begin(), t.end());
 }
TEST() [166/228]
souffle::test::TEST (RamLogTimer , CloneAndEquals)
Definition at line 340 of file ram_statement_equal_clone_test.cpp.
References b, souffle::RamLogTimer::clone(), souffle::DEFAULT, EXPECT_EQ, and EXPECT_NE.
{
     RamRelation A("A", 1, 1, {"x"}, {"i"}, RelationRepresentation::DEFAULT);
     /*
      * START_TIMER "@runtime"
      *   IO .. (..)
      * END_TIMER
      * */
     std::map<std::string, std::string> a_IODir;
     std::map<std::string, std::string> b_IODir;
     RamLogTimer a(std::make_unique<RamIO>(std::make_unique<RamRelationReference>(&A), std::move(a_IODir)),
             "@runtime");
     RamLogTimer b(std::make_unique<RamIO>(std::make_unique<RamRelationReference>(&A), std::move(a_IODir)),
             "@runtime");
     EXPECT_EQ(a, b);
     EXPECT_NE(&a, &b);
     RamLogTimer* c = a.clone();
     EXPECT_EQ(a, *c);
     EXPECT_NE(&a, c);
     delete c;
 }
TEST() [167/228]
souffle::test::TEST (BTreeSet , IteratorBasic)
Definition at line 345 of file btree_set_test.cpp.
References e, EXPECT_EQ, EXPECT_NE, i, and souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::insert().
{
     using test_set = btree_set<int, detail::comparator<int>, std::allocator<int>, 16>;
     test_set t;
     int N = 10;
     for (int i = 0; i <= N; i++) {
         t.insert(i);
     }
     //        t.printTree();
     auto it = t.begin();
     auto e = t.end();
     EXPECT_NE(it, e);
     int last = -1;
     for (int i : t) {
         EXPECT_EQ(last + 1, i);
         last = i;
     }
     EXPECT_EQ(last, N);
 }
TEST() [168/228]
souffle::test::TEST (BTreeMultiSet , Load)
Definition at line 346 of file btree_multiset_test.cpp.
References EXPECT_EQ, EXPECT_TRUE, and i.
{
     using test_set = btree_multiset<int, detail::comparator<int>, std::allocator<int>, 16>;
     for (int N = 0; N < 100; N++) {
         // generate some ordered data
         std::vector<int> data;
         for (int i = 0; i < N; i++) {
             data.push_back(i);
         }
         auto t = test_set::load(data.begin(), data.end());
         EXPECT_EQ(data.size(), t.size());
         EXPECT_TRUE(t.check());
         int last = -1;
         for (int c : t) {
             EXPECT_EQ(last + 1, c);
             last = c;
         }
         EXPECT_EQ(last, N - 1);
     }
 }
TEST() [169/228]
souffle::test::TEST (Binary , SignedDiv)
Definition at line 347 of file ram_arithmetic_test.cpp.
References souffle::DIV, evalBinary(), EXPECT_EQ, i, and TESTS_PER_OPERATION.
{
     FunctorOp functor = FunctorOp::DIV;
     auto vecArg1 = testutil::generateRandomVector<RamDomain>(TESTS_PER_OPERATION);
     auto vecArg2 = testutil::generateRandomVector<RamDomain>(TESTS_PER_OPERATION);
     for (int i = 0; i < TESTS_PER_OPERATION; ++i) {
         auto arg1 = vecArg1[i];
         auto arg2 = vecArg2[i];
         if (arg2 != 0) {
             RamDomain result = evalBinary(functor, arg1, arg2);
             EXPECT_EQ(result, arg1 / arg2);
         }
     }
 }
TEST() [170/228]
souffle::test::TEST (EqRelTest , IterEmpty)
Definition at line 350 of file binary_relation_test.cpp.
References EXPECT_EQ, EXPECT_FALSE, and testutil::ignore().
{
     // test iterating over an empty binrel fails
     EqRel br;
     for (auto x : br) {
         EXPECT_FALSE(true);
         testutil::ignore(x);
     }
     EXPECT_EQ(0, br.size());
 }
TEST() [171/228]
souffle::test::TEST (RamIndexAggregate , CloneAndEquals)
Definition at line 357 of file ram_operation_equal_clone_test.cpp.
References b, souffle::RamIndexAggregate::clone(), souffle::DEFAULT, EXPECT_EQ, EXPECT_NE, souffle::GE, and souffle::MIN.
{
     RamRelation sqrt("sqrt", 2, 1, {"nth", "value"}, {"i", "i"}, RelationRepresentation::DEFAULT);
     // t0.0 = MIN t1.1 SEARCH t1 IN sqrt ON INDEX t1.0 =  AND t1.1 =
     // WHERE t1.1 > 80
     //  RETURN t0.0
     std::vector<std::unique_ptr<RamExpression>> a_return_args;
     a_return_args.emplace_back(new RamTupleElement(0, 0));
     auto a_return = std::make_unique<RamSubroutineReturn>(std::move(a_return_args));
     auto a_cond = std::make_unique<RamConstraint>(BinaryConstraintOp::GE,
             std::make_unique<RamTupleElement>(1, 1), std::make_unique<RamSignedConstant>(80));
     RamPattern a_criteria;
     a_criteria.first.emplace_back(new RamUndefValue);
     a_criteria.first.emplace_back(new RamUndefValue);
     a_criteria.second.emplace_back(new RamUndefValue);
     a_criteria.second.emplace_back(new RamUndefValue);
     RamIndexAggregate a(std::move(a_return), AggregateOp::MIN, std::make_unique<RamRelationReference>(&sqrt),
             std::make_unique<RamTupleElement>(1, 1), std::move(a_cond), std::move(a_criteria), 1);
     std::vector<std::unique_ptr<RamExpression>> b_return_args;
     b_return_args.emplace_back(new RamTupleElement(0, 0));
     auto b_return = std::make_unique<RamSubroutineReturn>(std::move(b_return_args));
     auto b_cond = std::make_unique<RamConstraint>(BinaryConstraintOp::GE,
             std::make_unique<RamTupleElement>(1, 1), std::make_unique<RamSignedConstant>(80));
     RamPattern b_criteria;
     b_criteria.first.emplace_back(new RamUndefValue);
     b_criteria.first.emplace_back(new RamUndefValue);
     b_criteria.second.emplace_back(new RamUndefValue);
     b_criteria.second.emplace_back(new RamUndefValue);
     RamIndexAggregate b(std::move(b_return), AggregateOp::MIN, std::make_unique<RamRelationReference>(&sqrt),
             std::make_unique<RamTupleElement>(1, 1), std::move(b_cond), std::move(b_criteria), 1);
     EXPECT_EQ(a, b);
     EXPECT_NE(&a, &b);
     RamIndexAggregate* c = a.clone();
     EXPECT_EQ(a, *c);
     EXPECT_NE(&a, c);
     delete c;
 }
TEST() [172/228]
souffle::test::TEST (SparseDjTest , Scoping)
The SparseDisjointSet that is used by the EquivalenceRelation.
Definition at line 360 of file eqrel_datastructure_test.cpp.
{
     souffle::SparseDisjointSet<size_t> sds;
 }
TEST() [173/228]
souffle::test::TEST (EqRelTest , IterBasic)
Definition at line 360 of file binary_relation_test.cpp.
References count(), EXPECT_EQ, testutil::ignore(), and souffle::EquivalenceRelation< TupleType >::insert().
{
     EqRel br;
     br.insert(0, 0);
     br.insert(1, 1);
     br.insert(2, 2);
     size_t count = 0;
     for (auto x : br) {
         ++count;
         testutil::ignore(x);
     }
     EXPECT_EQ(count, br.size());
     // merge one disjoint set
     br.insert(0, 1);
     count = 0;
     for (auto x : br) {
         ++count;
         testutil::ignore(x);
     }
     EXPECT_EQ(count, br.size());
 }
TEST() [174/228]
souffle::test::TEST (RamDebugInfo , CloneAndEquals)
Definition at line 362 of file ram_statement_equal_clone_test.cpp.
References souffle::ADD, b, souffle::RamDebugInfo::clone(), souffle::DEFAULT, EXPECT_EQ, and EXPECT_NE.
{
     RamRelation edge(
             "edge", 4, 1, {"src", "dest", "a", "b"}, {"i", "i", "i", "i"}, RelationRepresentation::DEFAULT);
     RamRelation path(
             "path", 4, 1, {"src", "dest", "a", "b"}, {"i", "i", "i", "i"}, RelationRepresentation::DEFAULT);
     /* BEGIN_DEBUG "path(x,y,1,(@level_num_0+1)) :- \n   edge(x,y,_,@level_num_0).\nin file /edge.dl
      * [17:1-17:26];" QUERY FOR t0 IN edge IF (NOT (edge = )) IF (NOT (t0.0,t0.1,,)  path) PROJECT (t0.0,
      * t0.1, number(1), (t0.3+number(1))) INTO path END DEBUG
      * */
     std::vector<std::unique_ptr<RamExpression>> a_project_list;
     a_project_list.emplace_back(new RamTupleElement(0, 0));
     a_project_list.emplace_back(new RamTupleElement(0, 1));
     a_project_list.emplace_back(new RamSignedConstant(1));
     std::vector<std::unique_ptr<RamExpression>> a_project_add;
     a_project_add.emplace_back(new RamTupleElement(0, 3));
     a_project_add.emplace_back(new RamSignedConstant(1));
     a_project_list.emplace_back(new RamIntrinsicOperator(FunctorOp::ADD, std::move(a_project_add)));
     auto a_project = std::make_unique<RamProject>(
             std::make_unique<RamRelationReference>(&path), std::move(a_project_list));
     std::vector<std::unique_ptr<RamExpression>> a_filter1_list;
     a_filter1_list.emplace_back(new RamTupleElement(0, 0));
     a_filter1_list.emplace_back(new RamTupleElement(0, 1));
     a_filter1_list.emplace_back(new RamUndefValue);
     a_filter1_list.emplace_back(new RamUndefValue);
     auto a_existence_check1 = std::make_unique<RamExistenceCheck>(
             std::make_unique<RamRelationReference>(&path), std::move(a_filter1_list));
     auto a_cond1 = std::make_unique<RamNegation>(std::move(a_existence_check1));
     auto a_filter1 = std::make_unique<RamFilter>(std::move(a_cond1), std::move(a_project), "");
     auto a_cond2 = std::make_unique<RamNegation>(
             std::make_unique<RamEmptinessCheck>(std::make_unique<RamRelationReference>(&edge)));
     auto a_filter2 = std::make_unique<RamFilter>(std::move(a_cond2), std::move(a_filter1), "");
     auto a_scan = std::make_unique<RamScan>(
             std::make_unique<RamRelationReference>(&edge), 0, std::move(a_filter2), "");
     auto a_query = std::make_unique<RamQuery>(std::move(a_scan));
     RamDebugInfo a(std::move(a_query),
             "path(x,y,1,(@level_num_0+1)) :- \n   edge(x,y,_,@level_num_0).\nin file /edge.dl [17:1-17:26];");
     std::vector<std::unique_ptr<RamExpression>> b_project_list;
     b_project_list.emplace_back(new RamTupleElement(0, 0));
     b_project_list.emplace_back(new RamTupleElement(0, 1));
     b_project_list.emplace_back(new RamSignedConstant(1));
     std::vector<std::unique_ptr<RamExpression>> b_project_add;
     b_project_add.emplace_back(new RamTupleElement(0, 3));
     b_project_add.emplace_back(new RamSignedConstant(1));
     b_project_list.emplace_back(new RamIntrinsicOperator(FunctorOp::ADD, std::move(b_project_add)));
     auto b_project = std::make_unique<RamProject>(
             std::make_unique<RamRelationReference>(&path), std::move(b_project_list));
     std::vector<std::unique_ptr<RamExpression>> b_filter1_list;
     b_filter1_list.emplace_back(new RamTupleElement(0, 0));
     b_filter1_list.emplace_back(new RamTupleElement(0, 1));
     b_filter1_list.emplace_back(new RamUndefValue);
     b_filter1_list.emplace_back(new RamUndefValue);
     auto b_existence_check1 = std::make_unique<RamExistenceCheck>(
             std::make_unique<RamRelationReference>(&path), std::move(b_filter1_list));
     auto b_cond1 = std::make_unique<RamNegation>(std::move(b_existence_check1));
     auto b_filter1 = std::make_unique<RamFilter>(std::move(b_cond1), std::move(b_project), "");
     auto b_cond2 = std::make_unique<RamNegation>(
             std::make_unique<RamEmptinessCheck>(std::make_unique<RamRelationReference>(&edge)));
     auto b_filter2 = std::make_unique<RamFilter>(std::move(b_cond2), std::move(b_filter1), "");
     auto b_scan = std::make_unique<RamScan>(
             std::make_unique<RamRelationReference>(&edge), 0, std::move(b_filter2), "");
     auto b_query = std::make_unique<RamQuery>(std::move(b_scan));
     RamDebugInfo b(std::move(b_query),
             "path(x,y,1,(@level_num_0+1)) :- \n   edge(x,y,_,@level_num_0).\nin file /edge.dl [17:1-17:26];");
     EXPECT_EQ(a, b);
     EXPECT_NE(&a, &b);
     RamDebugInfo* c = a.clone();
     EXPECT_EQ(a, *c);
     EXPECT_NE(&a, c);
     delete c;
 }
TEST() [175/228]
souffle::test::TEST (Binary , UnsignedDiv)
Definition at line 363 of file ram_arithmetic_test.cpp.
References evalBinary(), EXPECT_EQ, i, souffle::ramBitCast(), TESTS_PER_OPERATION, and souffle::UDIV.
{
     FunctorOp functor = FunctorOp::UDIV;
     auto vecArg1 = testutil::generateRandomVector<RamUnsigned>(TESTS_PER_OPERATION);
     auto vecArg2 = testutil::generateRandomVector<RamUnsigned>(TESTS_PER_OPERATION);
     for (int i = 0; i < TESTS_PER_OPERATION; ++i) {
         auto arg1 = vecArg1[i];
         auto arg2 = vecArg2[i];
         if (arg2 != 0) {
             RamDomain result = evalBinary(functor, ramBitCast(arg1), ramBitCast(arg2));
             EXPECT_EQ(ramBitCast<RamUnsigned>(result), arg1 / arg2);
         }
     }
 }
TEST() [176/228]
souffle::test::TEST (SparseDjTest , MakeNode)
Definition at line 364 of file eqrel_datastructure_test.cpp.
References EXPECT_EQ, i, souffle::SparseDisjointSet< SparseDomain >::makeNode(), and souffle::SparseDisjointSet< SparseDomain >::size().
{
     souffle::SparseDisjointSet<size_t> sds;
     EXPECT_EQ(sds.size(), 0);
     sds.makeNode(99);
     EXPECT_EQ(sds.size(), 1);
     // whilst this shouldn't happen in regular use, it *shouldn't* create a new node
     sds.makeNode(99);
     EXPECT_EQ(sds.size(), 1);
     constexpr size_t N = 10000;
     for (size_t i = 0; i < N; ++i) {
         sds.makeNode(i);
     }
     EXPECT_EQ(sds.size(), N);
 }
TEST() [177/228]
souffle::test::TEST (BTreeMultiSet , Clear)
Definition at line 368 of file btree_multiset_test.cpp.
References EXPECT_FALSE, and EXPECT_TRUE.
{
     using test_set = btree_multiset<int, detail::comparator<int>, std::allocator<int>, 16>;
     test_set t;
     EXPECT_TRUE(t.empty());
     t.insert(5);
     EXPECT_FALSE(t.empty());
     t.clear();
     EXPECT_TRUE(t.empty());
     t.clear();
     EXPECT_TRUE(t.empty());
 }
TEST() [178/228]
souffle::test::TEST (BTreeSet , IteratorStress)
Definition at line 370 of file btree_set_test.cpp.
References EXPECT_EQ, EXPECT_LT, and i.
{
     using test_set = btree_set<int, detail::comparator<int>, std::allocator<int>, 16>;
     test_set t;
     int N = 1000;
     std::vector<int> data;
     for (int i = 0; i < N; i++) {
         data.push_back(i);
     }
     std::random_device rd;
     std::mt19937 generator(rd());
     shuffle(data.begin(), data.end(), generator);
     int max = -1;
     for (int i = 0; i < N; i++) {
         EXPECT_EQ((size_t)i, t.size());
         int last = -1;
         for (int i : t) {
             EXPECT_LT(last, i);
             last = i;
         }
         EXPECT_EQ(last, max);
         t.insert(data[i]);
         max = (data[i] > max) ? data[i] : max;
     }
 }
TEST() [179/228]
souffle::test::TEST (Binary , FloatDiv)
Definition at line 379 of file ram_arithmetic_test.cpp.
References evalBinary(), EXPECT_EQ, souffle::FDIV, i, souffle::ramBitCast(), and TESTS_PER_OPERATION.
{
     FunctorOp functor = FunctorOp::FDIV;
     auto vecArg1 = testutil::generateRandomVector<RamFloat>(TESTS_PER_OPERATION);
     auto vecArg2 = testutil::generateRandomVector<RamFloat>(TESTS_PER_OPERATION);
     for (int i = 0; i < TESTS_PER_OPERATION; ++i) {
         auto arg1 = vecArg1[i];
         auto arg2 = vecArg2[i];
         if (arg2 != 0) {
             RamDomain result = evalBinary(functor, ramBitCast(arg1), ramBitCast(arg2));
             EXPECT_EQ(ramBitCast<RamFloat>(result), arg1 / arg2);
         }
     }
 }
TEST() [180/228]
souffle::test::TEST (SparseDjTest , TestUnion)
Definition at line 383 of file eqrel_datastructure_test.cpp.
References souffle::SparseDisjointSet< SparseDomain >::contains(), EXPECT_EQ, EXPECT_FALSE, EXPECT_TRUE, souffle::SparseDisjointSet< SparseDomain >::makeNode(), souffle::SparseDisjointSet< SparseDomain >::size(), and souffle::SparseDisjointSet< SparseDomain >::unionNodes().
{
     // check whether the unioning works to see if the elements are properly in the same set
     souffle::SparseDisjointSet<size_t> sds;
     sds.makeNode(20);
     sds.makeNode(32);
     EXPECT_FALSE(sds.contains(20, 32));
     sds.unionNodes(20, 32);
     EXPECT_TRUE(sds.contains(20, 32));
     EXPECT_EQ(sds.size(), 2);
     sds.makeNode(33);
     EXPECT_FALSE(sds.contains(20, 33));
     sds.unionNodes(32, 33);
     EXPECT_TRUE(sds.contains(20, 33));
     EXPECT_EQ(sds.size(), 3);
 }
TEST() [181/228]
souffle::test::TEST (EqRelTest , IterRange)
Definition at line 384 of file binary_relation_test.cpp.
References souffle::EquivalenceRelation< TupleType >::clear(), EXPECT_EQ, souffle::EquivalenceRelation< TupleType >::getBoundaries(), and souffle::EquivalenceRelation< TupleType >::insert().
{
     // write some tests to use that templated range for different indexes too
     EqRel br;
     br.insert(0, 1);
     br.insert(0, 2);
     br.insert(0, 3);
     br.insert(0, 4);
     br.insert(0, 5);
     br.insert(0, 6);
     br.insert(8, 9);
     br.insert(8, 10);
     // this should return an iterator covering (3, 0), (3, 1), ..., (3, 6), it's a (3, *) iterator
     auto rangeIt = br.getBoundaries<1>({{3, 18293018}});
     std::vector<size_t> posteriorsCovered;
     for (auto tup : rangeIt) {
         posteriorsCovered.push_back(tup[1]);
     }
     EXPECT_EQ(posteriorsCovered.size(), 7);
     // this should be of everything, so doesn't matter the args
     rangeIt = br.getBoundaries<0>({{332, 888}});
     posteriorsCovered.clear();
     for (auto tup : rangeIt) {
         posteriorsCovered.push_back(tup[1]);
     }
     EXPECT_EQ(posteriorsCovered.size(), (7 * 7) + (3 * 3));
     // and now iterate over two levels (exactly one pretty much)
     rangeIt = br.getBoundaries<2>({{2, 3}});
     posteriorsCovered.clear();
     for (auto tup : rangeIt) {
         posteriorsCovered.push_back(tup[1]);
     }
     EXPECT_EQ(posteriorsCovered.size(), 1);
     EXPECT_EQ(posteriorsCovered.front(), 3);
     // and now the same, but for levels 1 and two, stuff that doesn't exist
     rangeIt = br.getBoundaries<1>({{99, 99}});
     posteriorsCovered.clear();
     for (auto tup : rangeIt) {
         posteriorsCovered.push_back(tup[1]);
     }
     EXPECT_EQ(posteriorsCovered.size(), 0);
     rangeIt = br.getBoundaries<2>({{8, 1}});
     posteriorsCovered.clear();
     for (auto tup : rangeIt) {
         posteriorsCovered.push_back(tup[1]);
     }
     EXPECT_EQ(posteriorsCovered.size(), 0);
     // and now the same for an empty binary relation
     br.clear();
     // repeat the same, but notice that we expect the size to be 0 always
     {
         auto rangeIt = br.getBoundaries<1>({{3, 18293018}});
         std::vector<size_t> posteriorsCovered;
         for (auto tup : rangeIt) {
             posteriorsCovered.push_back(tup[1]);
         }
         EXPECT_EQ(posteriorsCovered.size(), 0);
         // this should be of everything, so doesn't matter the args
         rangeIt = br.getBoundaries<0>({{332, 888}});
         posteriorsCovered.clear();
         for (auto tup : rangeIt) {
             posteriorsCovered.push_back(tup[1]);
         }
         EXPECT_EQ(posteriorsCovered.size(), 0);
         // and now iterate over two levels (exactly one pretty much)
         rangeIt = br.getBoundaries<2>({{2, 3}});
         posteriorsCovered.clear();
         for (auto tup : rangeIt) {
             posteriorsCovered.push_back(tup[1]);
         }
         EXPECT_EQ(posteriorsCovered.size(), 0);
         // and now the same, but for levels 1 and two, stuff that doesn't exist
         rangeIt = br.getBoundaries<1>({{99, 99}});
         posteriorsCovered.clear();
         for (auto tup : rangeIt) {
             posteriorsCovered.push_back(tup[1]);
         }
         EXPECT_EQ(posteriorsCovered.size(), 0);
         rangeIt = br.getBoundaries<2>({{8, 1}});
         posteriorsCovered.clear();
         for (auto tup : rangeIt) {
             posteriorsCovered.push_back(tup[1]);
         }
         EXPECT_EQ(posteriorsCovered.size(), 0);
     }
 }
TEST() [182/228]
souffle::test::TEST (IO_load , Signed)
Definition at line 385 of file ram_relation_test.cpp.
References souffle::BTREE, souffle::Global::config(), EXPECT_EQ, souffle::main(), and types.
                       {
     std::streambuf* backupCin = std::cin.rdbuf();
     std::istringstream testInput("5 3");
     std::cin.rdbuf(testInput.rdbuf());
     Global::config().set("jobs", "1");
     std::vector<std::unique_ptr<RamRelation>> rels;
     std::vector<std::string> attribs = {"a", "b"};
     std::vector<std::string> attribsTypes = {"i", "i"};
     std::unique_ptr<RamRelation> myrel =
             std::make_unique<RamRelation>("test", 2, 0, attribs, attribsTypes, RelationRepresentation::BTREE);
     std::unique_ptr<RamRelationReference> ref1 = std::make_unique<RamRelationReference>(myrel.get());
     std::unique_ptr<RamRelationReference> ref2 = std::make_unique<RamRelationReference>(myrel.get());
     Json types = Json::object{
             {"relation", Json::object{{"arity", static_cast<long long>(attribsTypes.size())},
                                  {"auxArity", static_cast<long long>(0)},
                                  {"types", Json::array(attribsTypes.begin(), attribsTypes.end())}}}};
     std::map<std::string, std::string> readDirs = {{"operation", "input"}, {"IO", "stdin"},
             {"attributeNames", "x\ty"}, {"name", "test"}, {"types", types.dump()}};
     std::map<std::string, std::string> readIoDirs = std::map<std::string, std::string>(readDirs);
     std::map<std::string, std::string> writeDirs = {{"operation", "output"}, {"IO", "stdout"},
             {"attributeNames", "x\ty"}, {"name", "test"}, {"types", types.dump()}};
     std::map<std::string, std::string> writeIoDirs = std::map<std::string, std::string>(writeDirs);
     std::unique_ptr<RamStatement> main =
             std::make_unique<RamSequence>(std::make_unique<RamIO>(std::move(ref1), readIoDirs),
                     std::make_unique<RamIO>(std::move(ref2), writeIoDirs));
     rels.push_back(std::move(myrel));
     std::map<std::string, std::unique_ptr<RamStatement>> subs;
     std::unique_ptr<RamProgram> prog =
             std::make_unique<RamProgram>(std::move(rels), std::move(main), std::move(subs));
     SymbolTable symTab;
     ErrorReport errReport;
     DebugReport debugReport;
     RamTranslationUnit translationUnit(std::move(prog), symTab, errReport, debugReport);
     // configure and execute interpreter
     std::unique_ptr<InterpreterEngine> interpreter = std::make_unique<InterpreterEngine>(translationUnit);
     std::streambuf* oldCoutStreambuf = std::cout.rdbuf();
     std::ostringstream sout;
     std::cout.rdbuf(sout.rdbuf());
     interpreter->executeMain();
     std::cout.rdbuf(oldCoutStreambuf);
     std::string expected = R"(---------------
 test
 ===============
 5   3
 ===============
 )";
     EXPECT_EQ(expected, sout.str());
     std::cin.rdbuf(backupCin);
 }
TEST() [183/228]
souffle::test::TEST (Binary , SignedExp)
Definition at line 395 of file ram_arithmetic_test.cpp.
References evalBinary(), souffle::EXP, EXPECT_EQ, i, and TESTS_PER_OPERATION.
{
     FunctorOp functor = FunctorOp::EXP;
     auto vecArg1 = testutil::generateRandomVector<RamDomain>(TESTS_PER_OPERATION);
     auto vecArg2 = testutil::generateRandomVector<RamDomain>(TESTS_PER_OPERATION);
     for (int i = 0; i < TESTS_PER_OPERATION; ++i) {
         auto arg1 = vecArg1[i];
         auto arg2 = vecArg2[i];
         RamDomain result = evalBinary(functor, arg1, arg2);
         EXPECT_EQ(result, static_cast<RamDomain>(std::pow(arg1, arg2)));
     }
 }
TEST() [184/228]
souffle::test::TEST (RamUnpackedRecord , CloneAndEquals)
Definition at line 396 of file ram_operation_equal_clone_test.cpp.
References b, souffle::RamUnpackRecord::clone(), EXPECT_EQ, and EXPECT_NE.
{
     // UNPACK (t0.0, t0.2) INTO t1
     // RETURN number(0)
     std::vector<std::unique_ptr<RamExpression>> a_return_args;
     a_return_args.emplace_back(new RamSignedConstant(0));
     auto a_return = std::make_unique<RamSubroutineReturn>(std::move(a_return_args));
     std::vector<std::unique_ptr<RamExpression>> a_record_args;
     a_record_args.emplace_back(new RamTupleElement(0, 0));
     a_record_args.emplace_back(new RamTupleElement(0, 2));
     auto a_record = std::make_unique<RamPackRecord>(std::move(a_record_args));
     RamUnpackRecord a(std::move(a_return), 1, std::move(a_record), 2);
     std::vector<std::unique_ptr<RamExpression>> b_return_args;
     b_return_args.emplace_back(new RamSignedConstant(0));
     auto b_return = std::make_unique<RamSubroutineReturn>(std::move(b_return_args));
     std::vector<std::unique_ptr<RamExpression>> b_record_args;
     b_record_args.emplace_back(new RamTupleElement(0, 0));
     b_record_args.emplace_back(new RamTupleElement(0, 2));
     auto b_record = std::make_unique<RamPackRecord>(std::move(b_record_args));
     RamUnpackRecord b(std::move(b_return), 1, std::move(b_record), 2);
     EXPECT_EQ(a, b);
     EXPECT_NE(&a, &b);
     RamUnpackRecord* c = a.clone();
     EXPECT_EQ(a, *c);
     EXPECT_NE(&a, c);
     delete c;
 }
TEST() [185/228]
souffle::test::TEST (BTreeSet , BoundaryTest)
Definition at line 402 of file btree_set_test.cpp.
References b, EXPECT_EQ, i, and souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::insert().
{
     using test_set = btree_set<int, detail::comparator<int>, std::allocator<int>, 16>;
     test_set t;
     for (int i = 0; i < 10; i++) {
         t.insert(i);
     }
     //    t.printTree();
     auto a = t.lower_bound(5);
     EXPECT_EQ(5, *a);
     auto b = t.upper_bound(5);
     EXPECT_EQ(6, *b);
     // add duplicates
     t.insert(5);
     t.insert(5);
     t.insert(5);
     //    t.printTree(); std::cout << "\n";
     // test again ..
     a = t.lower_bound(5);
     EXPECT_EQ(5, *a);
     b = t.upper_bound(5);
     EXPECT_EQ(6, *b);
     // check the distance
     EXPECT_EQ(++a, b);
 }
TEST() [186/228]
souffle::test::TEST (SparseDjTest , SignedData)
Definition at line 403 of file eqrel_datastructure_test.cpp.
References souffle::PiggyList< T >::append(), b, souffle::SparseDisjointSet< SparseDomain >::contains(), EXPECT_EQ, EXPECT_TRUE, souffle::PiggyList< T >::get(), i, souffle::SparseDisjointSet< SparseDomain >::makeNode(), souffle::PiggyList< T >::size(), souffle::SparseDisjointSet< SparseDomain >::size(), TEST(), souffle::SparseDisjointSet< SparseDomain >::toDense(), and souffle::SparseDisjointSet< SparseDomain >::unionNodes().
{
     // test when the sparse dj set stores different signed-ness to the internally stored data
     souffle::SparseDisjointSet<ssize_t> sds;
     EXPECT_EQ(sds.size(), 0);
     sds.makeNode(9999);
     EXPECT_EQ(sds.size(), 1);
 }
TEST() [187/228]
souffle::test::TEST (Binary , UnsignedExp)
Definition at line 409 of file ram_arithmetic_test.cpp.
References evalBinary(), EXPECT_EQ, i, souffle::ramBitCast(), TESTS_PER_OPERATION, and souffle::UEXP.
{
     FunctorOp functor = FunctorOp::UEXP;
     auto vecArg1 = testutil::generateRandomVector<RamUnsigned>(TESTS_PER_OPERATION);
     auto vecArg2 = testutil::generateRandomVector<RamUnsigned>(TESTS_PER_OPERATION);
     for (int i = 0; i < TESTS_PER_OPERATION; ++i) {
         auto arg1 = vecArg1[i];
         auto arg2 = vecArg2[i];
         RamDomain result = evalBinary(functor, ramBitCast(arg1), ramBitCast(arg2));
         EXPECT_EQ(ramBitCast<RamUnsigned>(result), static_cast<RamUnsigned>(std::pow(arg1, arg2)));
     }
 }
TEST() [188/228]
souffle::test::TEST (Binary , FloatExp)
Definition at line 423 of file ram_arithmetic_test.cpp.
References evalBinary(), EXPECT_TRUE, souffle::FEXP, i, souffle::ramBitCast(), and TESTS_PER_OPERATION.
{
     FunctorOp functor = FunctorOp::FEXP;
     auto vecArg1 = testutil::generateRandomVector<RamFloat>(TESTS_PER_OPERATION);
     auto vecArg2 = testutil::generateRandomVector<RamFloat>(TESTS_PER_OPERATION);
     for (int i = 0; i < TESTS_PER_OPERATION; ++i) {
         auto arg1 = vecArg1[i];
         auto arg2 = vecArg2[i];
         auto result = ramBitCast<RamFloat>(evalBinary(functor, ramBitCast(arg1), ramBitCast(arg2)));
         auto expected = static_cast<RamFloat>(std::pow(arg1, arg2));
         EXPECT_TRUE((std::isnan(result) && std::isnan(expected)) || result == expected);
     }
 }
TEST() [189/228]
souffle::test::TEST (RamFilter , CloneAndEquals)
Definition at line 425 of file ram_operation_equal_clone_test.cpp.
References b, souffle::RamFilter::clone(), souffle::DEFAULT, EXPECT_EQ, and EXPECT_NE.
{
     RamRelation A("A", 1, 1, {"a"}, {"i"}, RelationRepresentation::DEFAULT);
     // IF (NOT t0.1 in A)
     // RETURN number(0)
     std::vector<std::unique_ptr<RamExpression>> a_return_args;
     a_return_args.emplace_back(new RamSignedConstant(0));
     auto a_return = std::make_unique<RamSubroutineReturn>(std::move(a_return_args));
     std::vector<std::unique_ptr<RamExpression>> a_existence_check_args;
     a_existence_check_args.emplace_back(new RamTupleElement(0, 1));
     auto a_existence_check = std::make_unique<RamExistenceCheck>(
             std::make_unique<RamRelationReference>(&A), std::move(a_existence_check_args));
     RamFilter a(std::make_unique<RamNegation>(std::move(a_existence_check)), std::move(a_return),
             "RamFilter test");
     std::vector<std::unique_ptr<RamExpression>> b_return_args;
     b_return_args.emplace_back(new RamSignedConstant(0));
     auto b_return = std::make_unique<RamSubroutineReturn>(std::move(b_return_args));
     std::vector<std::unique_ptr<RamExpression>> b_existence_check_args;
     b_existence_check_args.emplace_back(new RamTupleElement(0, 1));
     auto b_existence_check = std::make_unique<RamExistenceCheck>(
             std::make_unique<RamRelationReference>(&A), std::move(b_existence_check_args));
     RamFilter b(std::make_unique<RamNegation>(std::move(b_existence_check)), std::move(b_return),
             "RamFilter test");
     EXPECT_EQ(a, b);
     EXPECT_NE(&a, &b);
     RamFilter* c = a.clone();
     EXPECT_EQ(a, *c);
     EXPECT_NE(&a, c);
     delete c;
 }
TEST() [190/228]
souffle::test::TEST (RamLogSize , CloneAndEquals)
Definition at line 436 of file ram_statement_equal_clone_test.cpp.
References b, souffle::RamLogSize::clone(), souffle::DEFAULT, EXPECT_EQ, and EXPECT_NE.
{
     RamRelation A("A", 1, 1, {"x"}, {"i"}, RelationRepresentation::DEFAULT);
     RamLogSize a(std::make_unique<RamRelationReference>(&A), "Log message");
     RamLogSize b(std::make_unique<RamRelationReference>(&A), "Log message");
     EXPECT_EQ(a, b);
     EXPECT_NE(&a, &b);
     RamLogSize* c = a.clone();
     EXPECT_EQ(a, *c);
     EXPECT_NE(&a, c);
     delete c;
 }
TEST() [191/228]
souffle::test::TEST (BTreeSet , BoundaryEmpty)
Definition at line 438 of file btree_set_test.cpp.
References EXPECT_EQ, and EXPECT_NE.
{
     using test_set = btree_set<int, detail::comparator<int>, std::allocator<int>, 16>;
     test_set t;
     EXPECT_EQ(t.end(), t.lower_bound(5));
     EXPECT_EQ(t.end(), t.upper_bound(5));
     t.insert(4);
     EXPECT_EQ(t.lower_bound(3), t.upper_bound(3));
     EXPECT_EQ(t.lower_bound(5), t.upper_bound(5));
     t.insert(6);
     EXPECT_EQ(t.lower_bound(3), t.upper_bound(3));
     EXPECT_EQ(t.lower_bound(5), t.upper_bound(5));
     t.insert(5);
     EXPECT_EQ(t.lower_bound(3), t.upper_bound(3));
     EXPECT_NE(t.lower_bound(5), t.upper_bound(5));
 }
TEST() [192/228]
souffle::test::TEST (Binary , SignedMod)
Definition at line 438 of file ram_arithmetic_test.cpp.
References evalBinary(), EXPECT_EQ, i, souffle::MOD, and TESTS_PER_OPERATION.
{
     FunctorOp functor = FunctorOp::MOD;
     auto vecArg1 = testutil::generateRandomVector<RamDomain>(TESTS_PER_OPERATION);
     auto vecArg2 = testutil::generateRandomVector<RamDomain>(TESTS_PER_OPERATION);
     for (int i = 0; i < TESTS_PER_OPERATION; ++i) {
         auto arg1 = vecArg1[i];
         auto arg2 = vecArg2[i];
         RamDomain result = evalBinary(functor, arg1, arg2);
         EXPECT_EQ(result, arg1 % arg2);
     }
 }
TEST() [193/228]
souffle::test::TEST (IO_load , Float)
Definition at line 451 of file ram_relation_test.cpp.
References souffle::BTREE, souffle::Global::config(), EXPECT_EQ, souffle::main(), and types.
                      {
     std::streambuf* backupCin = std::cin.rdbuf();
     std::istringstream testInput("0.5   0.5");
     std::cin.rdbuf(testInput.rdbuf());
     Global::config().set("jobs", "1");
     std::vector<std::unique_ptr<RamRelation>> rels;
     std::vector<std::string> attribs = {"a", "b"};
     std::vector<std::string> attribsTypes = {"f", "f"};
     std::unique_ptr<RamRelation> myrel =
             std::make_unique<RamRelation>("test", 2, 0, attribs, attribsTypes, RelationRepresentation::BTREE);
     std::unique_ptr<RamRelationReference> ref1 = std::make_unique<RamRelationReference>(myrel.get());
     std::unique_ptr<RamRelationReference> ref2 = std::make_unique<RamRelationReference>(myrel.get());
     Json types = Json::object{
             {"relation", Json::object{{"arity", static_cast<long long>(attribsTypes.size())},
                                  {"auxArity", static_cast<long long>(0)},
                                  {"types", Json::array(attribsTypes.begin(), attribsTypes.end())}}}};
     std::map<std::string, std::string> readDirs = {{"operation", "input"}, {"IO", "stdin"},
             {"attributeNames", "x\ty"}, {"name", "test"}, {"types", types.dump()}};
     std::map<std::string, std::string> readIoDirs = std::map<std::string, std::string>(readDirs);
     std::map<std::string, std::string> writeDirs = {{"operation", "output"}, {"IO", "stdout"},
             {"attributeNames", "x\ty"}, {"name", "test"}, {"types", types.dump()}};
     std::map<std::string, std::string> writeIoDirs = std::map<std::string, std::string>(writeDirs);
     std::unique_ptr<RamStatement> main =
             std::make_unique<RamSequence>(std::make_unique<RamIO>(std::move(ref1), readIoDirs),
                     std::make_unique<RamIO>(std::move(ref2), writeIoDirs));
     rels.push_back(std::move(myrel));
     std::map<std::string, std::unique_ptr<RamStatement>> subs;
     std::unique_ptr<RamProgram> prog =
             std::make_unique<RamProgram>(std::move(rels), std::move(main), std::move(subs));
     SymbolTable symTab;
     ErrorReport errReport;
     DebugReport debugReport;
     RamTranslationUnit translationUnit(std::move(prog), symTab, errReport, debugReport);
     // configure and execute interpreter
     std::unique_ptr<InterpreterEngine> interpreter = std::make_unique<InterpreterEngine>(translationUnit);
     std::streambuf* oldCoutStreambuf = std::cout.rdbuf();
     std::ostringstream sout;
     std::cout.rdbuf(sout.rdbuf());
     interpreter->executeMain();
     std::cout.rdbuf(oldCoutStreambuf);
     std::string expected = R"(---------------
 test
 ===============
 0.5 0.5
 ===============
 )";
     EXPECT_EQ(expected, sout.str());
     std::cin.rdbuf(backupCin);
 }
TEST() [194/228]
souffle::test::TEST (Binary , UnsignedMod)
Definition at line 452 of file ram_arithmetic_test.cpp.
References evalBinary(), EXPECT_EQ, i, souffle::ramBitCast(), TESTS_PER_OPERATION, and souffle::UMOD.
{
     FunctorOp functor = FunctorOp::UMOD;
     auto vecArg1 = testutil::generateRandomVector<RamUnsigned>(TESTS_PER_OPERATION);
     auto vecArg2 = testutil::generateRandomVector<RamUnsigned>(TESTS_PER_OPERATION);
     for (int i = 0; i < TESTS_PER_OPERATION; ++i) {
         auto arg1 = vecArg1[i];
         auto arg2 = vecArg2[i];
         RamDomain result = evalBinary(functor, ramBitCast(arg1), ramBitCast(arg2));
         EXPECT_EQ(ramBitCast<RamUnsigned>(result), arg1 % arg2);
     }
 }
TEST() [195/228]
souffle::test::TEST (RamBreak , CloneAndEquals)
Definition at line 457 of file ram_operation_equal_clone_test.cpp.
References b, souffle::RamBreak::clone(), souffle::DEFAULT, EXPECT_EQ, and EXPECT_NE.
{
     RamRelation A("A", 1, 1, {"a"}, {"i"}, RelationRepresentation::DEFAULT);
     // IF (A = ) BREAK
     // RETURN number(0)
     std::vector<std::unique_ptr<RamExpression>> a_return_args;
     a_return_args.emplace_back(new RamSignedConstant(0));
     auto a_return = std::make_unique<RamSubroutineReturn>(std::move(a_return_args));
     RamBreak a(std::make_unique<RamEmptinessCheck>(std::make_unique<RamRelationReference>(&A)),
             std::move(a_return), "RamBreak test");
     std::vector<std::unique_ptr<RamExpression>> b_return_args;
     b_return_args.emplace_back(new RamSignedConstant(0));
     auto b_return = std::make_unique<RamSubroutineReturn>(std::move(b_return_args));
     RamBreak b(std::make_unique<RamEmptinessCheck>(std::make_unique<RamRelationReference>(&A)),
             std::move(b_return), "RamBreak test");
     EXPECT_EQ(a, b);
     EXPECT_NE(&a, &b);
     RamBreak* c = a.clone();
     EXPECT_EQ(a, *c);
     EXPECT_NE(&a, c);
     delete c;
 }
TEST() [196/228]
souffle::test::TEST (BTreeSet , Load)
Definition at line 461 of file btree_set_test.cpp.
References EXPECT_EQ, EXPECT_TRUE, and i.
                      {
     using test_set = btree_set<int, detail::comparator<int>, std::allocator<int>, 16>;
     for (int N = 0; N < 100; N++) {
         // generate some ordered data
         std::vector<int> data;
         for (int i = 0; i < N; i++) {
             data.push_back(i);
         }
         auto t = test_set::load(data.begin(), data.end());
         //        t.printTree();
         EXPECT_EQ(data.size(), t.size());
         EXPECT_TRUE(t.check());
         int last = -1;
         for (int c : t) {
             EXPECT_EQ(last + 1, c);
             last = c;
         }
         EXPECT_EQ(last, N - 1);
     }
 }
TEST() [197/228]
souffle::test::TEST (Binary , SignedBinaryAnd)
Definition at line 466 of file ram_arithmetic_test.cpp.
References souffle::BAND, evalBinary(), EXPECT_EQ, i, and TESTS_PER_OPERATION.
{
     FunctorOp functor = FunctorOp::BAND;
     auto vecArg1 = testutil::generateRandomVector<RamDomain>(TESTS_PER_OPERATION);
     auto vecArg2 = testutil::generateRandomVector<RamDomain>(TESTS_PER_OPERATION);
     for (int i = 0; i < TESTS_PER_OPERATION; ++i) {
         auto arg1 = vecArg1[i];
         auto arg2 = vecArg2[i];
         RamDomain result = evalBinary(functor, arg1, arg2);
         EXPECT_EQ(result, arg1 & arg2);
     }
 }
TEST() [198/228]
souffle::test::TEST (Binary , UnsignedBinaryAnd)
Definition at line 480 of file ram_arithmetic_test.cpp.
References evalBinary(), EXPECT_EQ, i, souffle::ramBitCast(), TESTS_PER_OPERATION, and souffle::UBAND.
{
     FunctorOp functor = FunctorOp::UBAND;
     auto vecArg1 = testutil::generateRandomVector<RamUnsigned>(TESTS_PER_OPERATION);
     auto vecArg2 = testutil::generateRandomVector<RamUnsigned>(TESTS_PER_OPERATION);
     for (int i = 0; i < TESTS_PER_OPERATION; ++i) {
         auto arg1 = vecArg1[i];
         auto arg2 = vecArg2[i];
         RamDomain result = evalBinary(functor, ramBitCast(arg1), ramBitCast(arg2));
         EXPECT_EQ(ramBitCast<RamUnsigned>(result), arg1 & arg2);
     }
 }
TEST() [199/228]
souffle::test::TEST (RamProject , CloneAndEquals)
Definition at line 481 of file ram_operation_equal_clone_test.cpp.
References b, souffle::RamProject::clone(), souffle::DEFAULT, EXPECT_EQ, and EXPECT_NE.
{
     RamRelation A("A", 2, 1, {"a", "b"}, {"i", "i"}, RelationRepresentation::DEFAULT);
     // PROJECT (t0.1, t0.3) INTO A
     std::vector<std::unique_ptr<RamExpression>> a_args;
     a_args.emplace_back(new RamTupleElement(0, 1));
     a_args.emplace_back(new RamTupleElement(0, 3));
     RamProject a(std::make_unique<RamRelationReference>(&A), std::move(a_args));
     std::vector<std::unique_ptr<RamExpression>> b_args;
     b_args.emplace_back(new RamTupleElement(0, 1));
     b_args.emplace_back(new RamTupleElement(0, 3));
     RamProject b(std::make_unique<RamRelationReference>(&A), std::move(b_args));
     EXPECT_EQ(a, b);
     EXPECT_NE(&a, &b);
     RamProject* c = a.clone();
     EXPECT_EQ(a, *c);
     EXPECT_NE(&a, c);
     delete c;
 }
TEST() [200/228]
souffle::test::TEST (EqRelTest , IterPartition)
Definition at line 483 of file binary_relation_test.cpp.
References souffle::EquivalenceRelation< TupleType >::clear(), EXPECT_EQ, EXPECT_TRUE, i, souffle::EquivalenceRelation< TupleType >::insert(), souffle::EquivalenceRelation< TupleType >::partition(), and souffle::EquivalenceRelation< TupleType >::size().
{
     // test that the union equals the input
     // test single set binary rel
     EqRel br;
     std::vector<std::pair<RamDomain, RamDomain>> values;
     RamDomain N = 1000;
     for (RamDomain i = 0; i < N; ++i) {
         br.insert(i, i + 1);
     }
     EXPECT_EQ(size_t((N + 1) * (N + 1)), br.size());
     auto chunks = br.partition(400);
     // we can't make too many assumptions..
     EXPECT_TRUE(chunks.size() > 0);
     for (auto chunk : chunks) {
         for (auto x : chunk) {
             values.push_back(std::make_pair(x[0], x[1]));
         }
     }
     EXPECT_EQ(br.size(), values.size());
     br.clear();
     values.clear();
     chunks.clear();
     // many disjoint sets (note, can't use N, because even & odd numbers don't work the same..)
     for (RamDomain i = 0; i < 1000; i += 2) {
         br.insert(i, i + 1);
     }
     EXPECT_EQ((size_t)4 * 1000 / 2, br.size());
     chunks = br.partition(400);
     for (auto chunk : chunks) {
         for (auto x : chunk) {
             values.push_back(std::make_pair(x[0], x[1]));
         }
     }
     EXPECT_EQ(br.size(), values.size());
 }
TEST() [201/228]
souffle::test::TEST (BTreeSet , Clear)
Definition at line 487 of file btree_set_test.cpp.
References EXPECT_FALSE, and EXPECT_TRUE.
                       {
     using test_set = btree_set<int, detail::comparator<int>, std::allocator<int>, 16>;
     test_set t;
     EXPECT_TRUE(t.empty());
     t.insert(5);
     EXPECT_FALSE(t.empty());
     t.clear();
     EXPECT_TRUE(t.empty());
     t.clear();
     EXPECT_TRUE(t.empty());
 }
TEST() [202/228]
souffle::test::TEST (Performance , Basic)
Definition at line 494 of file btree_multiset_test.cpp.
References checkPerformance, getData(), i, and time().
{
     int N = 1 << 18;
     // get list of tuples to be inserted
     std::cout << "Generating Test-Data ...\n";
     std::vector<Entry> in;
     std::vector<Entry> out;
     time("generating data", [&]() {
         auto data = getData(2 * N);
         for (std::size_t i = 0; i < data.size(); i += 2) {
             in.push_back(data[i]);
             out.push_back(data[i + 1]);
         }
     });
     using t1 = std::set<Entry>;
     checkPerformance(t1, " -- warm up -- ", in, out);
     using t2 = btree_multiset<Entry, detail::comparator<Entry>, std::allocator<Entry>, 256,
             detail::linear_search>;
     checkPerformance(t2, "souffle btree_multiset - 256 - linear", in, out);
     using t3 = btree_multiset<Entry, detail::comparator<Entry>, std::allocator<Entry>, 256,
             detail::binary_search>;
     checkPerformance(t3, "souffle btree_multiset - 256 - binary", in, out);
 }
TEST() [203/228]
souffle::test::TEST (Binary , SignedBinaryOr)
Definition at line 494 of file ram_arithmetic_test.cpp.
References souffle::BOR, evalBinary(), EXPECT_EQ, i, and TESTS_PER_OPERATION.
{
     FunctorOp functor = FunctorOp::BOR;
     auto vecArg1 = testutil::generateRandomVector<RamDomain>(TESTS_PER_OPERATION);
     auto vecArg2 = testutil::generateRandomVector<RamDomain>(TESTS_PER_OPERATION);
     for (int i = 0; i < TESTS_PER_OPERATION; ++i) {
         auto arg1 = vecArg1[i];
         auto arg2 = vecArg2[i];
         RamDomain result = evalBinary(functor, arg1, arg2);
         EXPECT_EQ(result, arg1 | arg2);
     }
 }
TEST() [204/228]
souffle::test::TEST (RamSubroutineReturn , CloneAndEquals)
Definition at line 502 of file ram_operation_equal_clone_test.cpp.
References b, souffle::RamSubroutineReturn::clone(), d, e, EXPECT_EQ, and EXPECT_NE.
{
     // RETURN (t0.1, t0.2)
     std::vector<std::unique_ptr<RamExpression>> a_args;
     a_args.emplace_back(new RamTupleElement(0, 1));
     a_args.emplace_back(new RamTupleElement(0, 2));
     RamSubroutineReturn a(std::move(a_args));
     std::vector<std::unique_ptr<RamExpression>> b_args;
     b_args.emplace_back(new RamTupleElement(0, 1));
     b_args.emplace_back(new RamTupleElement(0, 2));
     RamSubroutineReturn b(std::move(b_args));
     EXPECT_EQ(a, b);
     EXPECT_NE(&a, &b);
     RamSubroutineReturn* c = a.clone();
     EXPECT_EQ(a, *c);
     EXPECT_NE(&a, c);
     delete c;
     // RETURN (number(0))
     std::vector<std::unique_ptr<RamExpression>> d_args;
     d_args.emplace_back(new RamSignedConstant(0));
     RamSubroutineReturn d(std::move(d_args));
     std::vector<std::unique_ptr<RamExpression>> e_args;
     e_args.emplace_back(new RamSignedConstant(0));
     RamSubroutineReturn e(std::move(e_args));
     EXPECT_EQ(d, e);
     EXPECT_NE(&d, &e);
     RamSubroutineReturn* f = d.clone();
     EXPECT_EQ(d, *f);
     EXPECT_NE(&d, f);
     delete f;
 }
TEST() [205/228]
souffle::test::TEST (BTreeSet , ChunkSplit)
Definition at line 504 of file btree_set_test.cpp.
References EXPECT_EQ, i, and souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::insert().
{
     using test_set = btree_set<int, detail::comparator<int>, std::allocator<int>, 16>;
     test_set t;
     // TODO: test for empty
     for (int i = 0; i < 100; i++) {
         t.insert(i);
     }
     // split chunks
     auto chunks = t.getChunks(20);
     //        EXPECT_EQ(20, chunks.size());
     for (const auto& cur : chunks) {
         for (int i : cur) {
             std::cout << i << ", ";
         }
         std::cout << "\n";
     }
     int last = -1;
     for (const auto& cur : chunks) {
         for (auto i = cur.begin(); i != cur.end(); ++i) {
             EXPECT_EQ(last + 1, *i);
             last = *i;
         }
     }
 }
TEST() [206/228]
souffle::test::TEST (LambdaBTreeTest , Scoping)
The LambdaBTree - essentially a ripoff to the Btree, but allows a function to be called on successful insert.
I just am gonna test a subset of it, because I can argue that BTree already tests the basic stuff
Definition at line 505 of file eqrel_datastructure_test.cpp.
{
     // lambda btree set current has some hard coded stuff h1
     TestLambdaTree t;
 }
TEST() [207/228]
souffle::test::TEST (Binary , UnsignedBinaryOr)
Definition at line 508 of file ram_arithmetic_test.cpp.
References evalBinary(), EXPECT_EQ, i, souffle::ramBitCast(), TESTS_PER_OPERATION, and souffle::UBOR.
{
     FunctorOp functor = FunctorOp::UBOR;
     auto vecArg1 = testutil::generateRandomVector<RamUnsigned>(TESTS_PER_OPERATION);
     auto vecArg2 = testutil::generateRandomVector<RamUnsigned>(TESTS_PER_OPERATION);
     for (int i = 0; i < TESTS_PER_OPERATION; ++i) {
         auto arg1 = vecArg1[i];
         auto arg2 = vecArg2[i];
         RamDomain result = evalBinary(functor, ramBitCast(arg1), ramBitCast(arg2));
         EXPECT_EQ(ramBitCast<RamUnsigned>(result), arg1 | arg2);
     }
 }
TEST() [208/228]
souffle::test::TEST (LambdaBTreeTest , Insert)
Definition at line 510 of file eqrel_datastructure_test.cpp.
References b, souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::contains(), EXPECT_EQ, EXPECT_TRUE, souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::find(), i, souffle::detail::LambdaBTree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, Functor, WeakComparator, Updater >::insert(), p, souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::printTree(), souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::size(), and TEST().
{
     // insert some stuff and make sure the sideeffects are correct (as observed within the lambda), and also
     // that the elements are contained
     // the ticket machine that sets the second argument (for now our functor will just postincrent to assign)
     std::atomic<size_t> assigner(0);
     TestLambdaTree t;
     EXPECT_EQ(t.size(), 0);
     std::function<TestPair::second_type(TestPair&)> update_fn = [&](TestPair& tp) {
         tp.second = assigner.fetch_add(1);
         return tp.second;
     };
     TestPair toInsert = {55, -1};
     // inserting the ticketed value
     EXPECT_EQ(t.insert(toInsert, update_fn), 0);
     EXPECT_EQ(t.size(), 1);
     // the second argument should be ignored because its unknown until you fetch it!
     EXPECT_TRUE(t.contains({55, 1329139123}));
     // post increment of 0 is zero.
     EXPECT_EQ(((*t.find({55, 3232})).second), 0);
     TestPair insert2 = {43, 22};
     // insert should also return the value
     EXPECT_EQ(t.insert(insert2, update_fn), 1);
     EXPECT_TRUE(t.contains({43, 1329139123}));
     // post increment now should equal 1
     EXPECT_EQ(((*t.find({43, 3232})).second), 1);
     EXPECT_EQ(t.size(), 2);
     // now lets insert something that already exists (the anterior is all that matters)
     TestPair alreadyExistsPair = {55, 12313123};
     EXPECT_EQ(t.insert(alreadyExistsPair,
                       [&](TestPair&) {
                           EXPECT_TRUE(false &&
                                       "newly inserted function called for an element that already exists!");
                           // some dummy value
                           return 3223;
                       }),
             0);
     EXPECT_EQ(t.size(), 2);
 }
TEST() [209/228]
souffle::test::TEST (IO_load , Unsigned)
Definition at line 517 of file ram_relation_test.cpp.
References souffle::BTREE, souffle::Global::config(), EXPECT_EQ, souffle::main(), and types.
{
     std::streambuf* backupCin = std::cin.rdbuf();
     std::istringstream testInput("6 6");
     std::cin.rdbuf(testInput.rdbuf());
     Global::config().set("jobs", "1");
     std::vector<std::unique_ptr<RamRelation>> rels;
     std::vector<std::string> attribs = {"a", "b"};
     std::vector<std::string> attribsTypes = {"u", "u"};
     std::unique_ptr<RamRelation> myrel =
             std::make_unique<RamRelation>("test", 2, 0, attribs, attribsTypes, RelationRepresentation::BTREE);
     std::unique_ptr<RamRelationReference> ref1 = std::make_unique<RamRelationReference>(myrel.get());
     std::unique_ptr<RamRelationReference> ref2 = std::make_unique<RamRelationReference>(myrel.get());
     Json types = Json::object{
             {"relation", Json::object{{"arity", static_cast<long long>(attribsTypes.size())},
                                  {"auxArity", static_cast<long long>(0)},
                                  {"types", Json::array(attribsTypes.begin(), attribsTypes.end())}}}};
     std::map<std::string, std::string> readDirs = {{"operation", "input"}, {"IO", "stdin"},
             {"attributeNames", "x\ty"}, {"name", "test"}, {"types", types.dump()}};
     std::map<std::string, std::string> readIoDirs = std::map<std::string, std::string>(readDirs);
     std::map<std::string, std::string> writeDirs = {{"operation", "output"}, {"IO", "stdout"},
             {"attributeNames", "x\ty"}, {"name", "test"}, {"types", types.dump()}};
     std::map<std::string, std::string> writeIoDirs = std::map<std::string, std::string>(writeDirs);
     std::unique_ptr<RamStatement> main =
             std::make_unique<RamSequence>(std::make_unique<RamIO>(std::move(ref1), readIoDirs),
                     std::make_unique<RamIO>(std::move(ref2), writeIoDirs));
     rels.push_back(std::move(myrel));
     std::map<std::string, std::unique_ptr<RamStatement>> subs;
     std::unique_ptr<RamProgram> prog =
             std::make_unique<RamProgram>(std::move(rels), std::move(main), std::move(subs));
     SymbolTable symTab;
     ErrorReport errReport;
     DebugReport debugReport;
     RamTranslationUnit translationUnit(std::move(prog), symTab, errReport, debugReport);
     // configure and execute interpreter
     std::unique_ptr<InterpreterEngine> interpreter = std::make_unique<InterpreterEngine>(translationUnit);
     std::streambuf* oldCoutStreambuf = std::cout.rdbuf();
     std::ostringstream sout;
     std::cout.rdbuf(sout.rdbuf());
     interpreter->executeMain();
     std::cout.rdbuf(oldCoutStreambuf);
     std::string expected = R"(---------------
 test
 ===============
 6   6
 ===============
 )";
     EXPECT_EQ(expected, sout.str());
     std::cin.rdbuf(backupCin);
 }
TEST() [210/228]
souffle::test::TEST (Performance , Load)
Definition at line 519 of file btree_multiset_test.cpp.
References i, and time().
{
     int N = 1 << 20;
     std::vector<int> data;
     for (int i = 0; i < N; i++) {
         data.push_back(i);
     }
     // take time for conventional load
     time("conventional load", [&]() { btree_multiset<int> t(data.begin(), data.end()); });
     // take time for structured load
     time("bulk-load", [&]() { auto t = btree_multiset<int>::load(data.begin(), data.end()); });
 }
TEST() [211/228]
souffle::test::TEST (Binary , SignedBinaryXor)
Definition at line 522 of file ram_arithmetic_test.cpp.
References souffle::BXOR, evalBinary(), EXPECT_EQ, i, and TESTS_PER_OPERATION.
{
     FunctorOp functor = FunctorOp::BXOR;
     auto vecArg1 = testutil::generateRandomVector<RamDomain>(TESTS_PER_OPERATION);
     auto vecArg2 = testutil::generateRandomVector<RamDomain>(TESTS_PER_OPERATION);
     for (int i = 0; i < TESTS_PER_OPERATION; ++i) {
         auto arg1 = vecArg1[i];
         auto arg2 = vecArg2[i];
         RamDomain result = evalBinary(functor, arg1, arg2);
         EXPECT_EQ(result, arg1 ^ arg2);
     }
 }
TEST() [212/228]
souffle::test::TEST (EqRelTest , Scaling)
Definition at line 528 of file binary_relation_test.cpp.
References EXPECT_EQ, i, souffle::EquivalenceRelation< TupleType >::insert(), souffle::EquivalenceRelation< TupleType >::size(), and TEST().
{
     const int N = 100;
     EqRel br;
     for (int i = 0; i < N; ++i) {
         br.insert(i, i);
     }
     EXPECT_EQ(N, br.size());
 }
TEST() [213/228]
souffle::test::TEST (Binary , UnsignedBinaryXor)
Definition at line 536 of file ram_arithmetic_test.cpp.
References evalBinary(), EXPECT_EQ, i, souffle::ramBitCast(), TESTS_PER_OPERATION, and souffle::UBXOR.
{
     FunctorOp functor = FunctorOp::UBXOR;
     auto vecArg1 = testutil::generateRandomVector<RamUnsigned>(TESTS_PER_OPERATION);
     auto vecArg2 = testutil::generateRandomVector<RamUnsigned>(TESTS_PER_OPERATION);
     for (int i = 0; i < TESTS_PER_OPERATION; ++i) {
         auto arg1 = vecArg1[i];
         auto arg2 = vecArg2[i];
         RamDomain result = evalBinary(functor, ramBitCast(arg1), ramBitCast(arg2));
         EXPECT_EQ(ramBitCast<RamUnsigned>(result), arg1 ^ arg2);
     }
 }
TEST() [214/228]
souffle::test::TEST (BTreeSet , ChunkSplitStress)
Definition at line 536 of file btree_set_test.cpp.
References b, count(), duration(), EXPECT_EQ, getData(), i, j, k, now(), and time().
{
     using test_set = btree_set<int, detail::comparator<int>, std::allocator<int>, 16>;
     for (int i = 0; i < 1000; i++) {
         // generate random sequence
         std::vector<int> data;
         for (int j = 0; j < i; j++) {
             data.push_back(j);
         }
         std::random_device rd;
         std::mt19937 generator(rd());
         shuffle(data.begin(), data.end(), generator);
         // fill tree
         test_set t;
         for (int x : data) {
             t.insert(x);
         }
         for (int j = 1; j < 100; j++) {
             auto chunks = t.getChunks(j);
             //                EXPECT_LT(chunks.size(), j * 2);
             if (chunks.empty()) continue;
             // check covered range
             EXPECT_EQ(0, *chunks.front().begin());
             int last = -1;
             for (const auto& cur : chunks) {
                 for (auto it = cur.begin(); it != cur.end(); ++it) {
                     EXPECT_EQ(last + 1, *it);
                     last = *it;
                 }
             }
             EXPECT_EQ(i - 1, last);
         }
     }
 }
TEST() [215/228]
souffle::test::TEST (Binary , SignedLogicalAnd)
Definition at line 550 of file ram_arithmetic_test.cpp.
References evalBinary(), EXPECT_EQ, i, souffle::LAND, and TESTS_PER_OPERATION.
{
     FunctorOp functor = FunctorOp::LAND;
     auto vecArg1 = testutil::generateRandomVector<RamDomain>(TESTS_PER_OPERATION);
     auto vecArg2 = testutil::generateRandomVector<RamDomain>(TESTS_PER_OPERATION);
     for (int i = 0; i < TESTS_PER_OPERATION; ++i) {
         auto arg1 = vecArg1[i];
         auto arg2 = vecArg2[i];
         RamDomain result = evalBinary(functor, arg1, arg2);
         EXPECT_EQ(result, arg1 || arg2);
     }
 }
TEST() [216/228]
souffle::test::TEST (Binary , UnsignedLogicalAnd)
Definition at line 564 of file ram_arithmetic_test.cpp.
References evalBinary(), EXPECT_EQ, i, souffle::ramBitCast(), TESTS_PER_OPERATION, and souffle::ULAND.
{
     FunctorOp functor = FunctorOp::ULAND;
     auto vecArg1 = testutil::generateRandomVector<RamUnsigned>(TESTS_PER_OPERATION);
     auto vecArg2 = testutil::generateRandomVector<RamUnsigned>(TESTS_PER_OPERATION);
     for (int i = 0; i < TESTS_PER_OPERATION; ++i) {
         auto arg1 = vecArg1[i];
         auto arg2 = vecArg2[i];
         RamDomain result = evalBinary(functor, ramBitCast(arg1), ramBitCast(arg2));
         EXPECT_EQ(ramBitCast<RamUnsigned>(result), arg1 || arg2);
     }
 }
TEST() [217/228]
souffle::test::TEST (Binary , SignedLogicalOr)
Definition at line 578 of file ram_arithmetic_test.cpp.
References evalBinary(), EXPECT_EQ, i, souffle::LOR, and TESTS_PER_OPERATION.
{
     FunctorOp functor = FunctorOp::LOR;
     auto vecArg1 = testutil::generateRandomVector<RamDomain>(TESTS_PER_OPERATION);
     auto vecArg2 = testutil::generateRandomVector<RamDomain>(TESTS_PER_OPERATION);
     for (int i = 0; i < TESTS_PER_OPERATION; ++i) {
         auto arg1 = vecArg1[i];
         auto arg2 = vecArg2[i];
         RamDomain result = evalBinary(functor, arg1, arg2);
         EXPECT_EQ(result, arg1 || arg2);
     }
 }
TEST() [218/228]
souffle::test::TEST (IO_load , MixedTypesLoad)
Definition at line 583 of file ram_relation_test.cpp.
References souffle::BTREE, souffle::Global::config(), EXPECT_EQ, souffle::main(), and types.
{
     std::streambuf* backupCin = std::cin.rdbuf();
     std::istringstream testInput("meow  -3  3   0.5");
     std::cin.rdbuf(testInput.rdbuf());
     Global::config().set("jobs", "1");
     std::vector<std::unique_ptr<RamRelation>> rels;
     std::vector<std::string> attribs = {"l", "u", "b", "a"};
     std::vector<std::string> attribsTypes = {"s", "i", "u", "f"};
     std::unique_ptr<RamRelation> myrel =
             std::make_unique<RamRelation>("test", 4, 0, attribs, attribsTypes, RelationRepresentation::BTREE);
     std::unique_ptr<RamRelationReference> ref1 = std::make_unique<RamRelationReference>(myrel.get());
     std::unique_ptr<RamRelationReference> ref2 = std::make_unique<RamRelationReference>(myrel.get());
     Json types = Json::object{
             {"relation", Json::object{{"arity", static_cast<long long>(attribsTypes.size())},
                                  {"auxArity", static_cast<long long>(0)},
                                  {"types", Json::array(attribsTypes.begin(), attribsTypes.end())}}}};
     std::map<std::string, std::string> readDirs = {{"operation", "input"}, {"IO", "stdin"},
             {"attributeNames", "x\ty"}, {"name", "test"}, {"types", types.dump()}};
     std::map<std::string, std::string> readIoDirs = std::map<std::string, std::string>(readDirs);
     std::map<std::string, std::string> writeDirs = {{"operation", "output"}, {"IO", "stdout"},
             {"attributeNames", "x\ty"}, {"name", "test"}, {"types", types.dump()}};
     std::map<std::string, std::string> writeIoDirs = std::map<std::string, std::string>(writeDirs);
     std::unique_ptr<RamStatement> main =
             std::make_unique<RamSequence>(std::make_unique<RamIO>(std::move(ref1), readIoDirs),
                     std::make_unique<RamIO>(std::move(ref2), writeIoDirs));
     rels.push_back(std::move(myrel));
     std::map<std::string, std::unique_ptr<RamStatement>> subs;
     std::unique_ptr<RamProgram> prog =
             std::make_unique<RamProgram>(std::move(rels), std::move(main), std::move(subs));
     SymbolTable symTab;
     ErrorReport errReport;
     DebugReport debugReport;
     RamTranslationUnit translationUnit(std::move(prog), symTab, errReport, debugReport);
     // configure and execute interpreter
     std::unique_ptr<InterpreterEngine> interpreter = std::make_unique<InterpreterEngine>(translationUnit);
     std::streambuf* oldCoutStreambuf = std::cout.rdbuf();
     std::ostringstream sout;
     std::cout.rdbuf(sout.rdbuf());
     interpreter->executeMain();
     std::cout.rdbuf(oldCoutStreambuf);
     std::string expected = R"(---------------
 test
 ===============
 meow    -3  3   0.5
 ===============
 )";
     EXPECT_EQ(expected, sout.str());
     std::cin.rdbuf(backupCin);
 }
TEST() [219/228]
souffle::test::TEST (Binary , UnsignedLogicalOr)
Definition at line 592 of file ram_arithmetic_test.cpp.
References evalBinary(), EXPECT_EQ, i, souffle::ramBitCast(), TESTS_PER_OPERATION, and souffle::ULOR.
{
     FunctorOp functor = FunctorOp::ULOR;
     auto vecArg1 = testutil::generateRandomVector<RamUnsigned>(TESTS_PER_OPERATION);
     auto vecArg2 = testutil::generateRandomVector<RamUnsigned>(TESTS_PER_OPERATION);
     for (int i = 0; i < TESTS_PER_OPERATION; ++i) {
         auto arg1 = vecArg1[i];
         auto arg2 = vecArg2[i];
         RamDomain result = evalBinary(functor, ramBitCast(arg1), ramBitCast(arg2));
         EXPECT_EQ(ramBitCast<RamUnsigned>(result), arg1 || arg2);
     }
 }
TEST() [220/228]
souffle::test::TEST (MultiArg , Max)
Definition at line 606 of file ram_arithmetic_test.cpp.
References evalMultiArg(), EXPECT_EQ, i, and souffle::MAX.
                     {
     FunctorOp functor = FunctorOp::MAX;
     std::vector<std::unique_ptr<souffle::RamExpression>> args;
     for (RamDomain i = 0; i <= 50; ++i) {
         args.push_back(std::make_unique<RamSignedConstant>(i));
     }
     RamDomain result = evalMultiArg(functor, std::move(args));
     EXPECT_EQ(result, 50);
 }
TEST() [221/228]
souffle::test::TEST (MultiArg , UnsignedMax)
Definition at line 619 of file ram_arithmetic_test.cpp.
References evalMultiArg(), EXPECT_EQ, i, souffle::ramBitCast(), and souffle::UMAX.
{
     FunctorOp functor = FunctorOp::UMAX;
     std::vector<std::unique_ptr<souffle::RamExpression>> args;
     for (RamUnsigned i = 0; i <= 100; ++i) {
         args.push_back(std::make_unique<RamSignedConstant>(ramBitCast(i)));
     }
     RamDomain result = evalMultiArg(functor, std::move(args));
     EXPECT_EQ(ramBitCast<RamUnsigned>(result), 100);
 }
TEST() [222/228]
souffle::test::TEST (MultiArg , FloatMax)
Definition at line 632 of file ram_arithmetic_test.cpp.
References evalMultiArg(), EXPECT_EQ, souffle::FMAX, i, and souffle::ramBitCast().
{
     FunctorOp functor = FunctorOp::FMAX;
     std::vector<std::unique_ptr<souffle::RamExpression>> args;
     for (RamDomain i = -100; i <= 100; ++i) {
         args.push_back(std::make_unique<RamSignedConstant>(ramBitCast(static_cast<RamFloat>(i))));
     }
     RamDomain result = evalMultiArg(functor, std::move(args));
     EXPECT_EQ(ramBitCast<RamFloat>(result), static_cast<RamFloat>(100));
 }
TEST() [223/228]
souffle::test::TEST (MultiArg , SymbolMax)
Definition at line 645 of file ram_arithmetic_test.cpp.
References evalMultiArg(), EXPECT_EQ, i, souffle::SymbolTable::lookup(), souffle::SymbolTable::resolve(), and souffle::SMAX.
{
     FunctorOp functor = FunctorOp::SMAX;
     std::vector<std::unique_ptr<souffle::RamExpression>> args;
     SymbolTable symTab;
     for (RamDomain i = -100; i <= 100; ++i) {
         args.push_back(std::make_unique<RamSignedConstant>(symTab.lookup(std::to_string(i))));
     }
     auto&& result = symTab.resolve(evalMultiArg(functor, std::move(args), symTab));
     EXPECT_EQ(result, "99");
 }
TEST() [224/228]
souffle::test::TEST (MultiArg , Min)
Definition at line 660 of file ram_arithmetic_test.cpp.
References evalMultiArg(), EXPECT_EQ, i, and souffle::MIN.
                     {
     FunctorOp functor = FunctorOp::MIN;
     std::vector<std::unique_ptr<souffle::RamExpression>> args;
     for (RamDomain i = 0; i <= 50; ++i) {
         args.push_back(std::make_unique<RamSignedConstant>(i));
     }
     RamDomain result = evalMultiArg(functor, std::move(args));
     EXPECT_EQ(result, 0);
 }
TEST() [225/228]
souffle::test::TEST (MultiArg , UnsignedMin)
Definition at line 673 of file ram_arithmetic_test.cpp.
References evalMultiArg(), EXPECT_EQ, i, souffle::ramBitCast(), and souffle::UMIN.
{
     FunctorOp functor = FunctorOp::UMIN;
     std::vector<std::unique_ptr<souffle::RamExpression>> args;
     for (RamUnsigned i = 0; i <= 100; ++i) {
         args.push_back(std::make_unique<RamSignedConstant>(ramBitCast(i)));
     }
     RamDomain result = evalMultiArg(functor, std::move(args));
     EXPECT_EQ(ramBitCast<RamUnsigned>(result), 0);
 }
TEST() [226/228]
souffle::test::TEST (MultiArg , FloatMin)
Definition at line 686 of file ram_arithmetic_test.cpp.
References evalMultiArg(), EXPECT_EQ, souffle::FMIN, i, and souffle::ramBitCast().
{
     FunctorOp functor = FunctorOp::FMIN;
     std::vector<std::unique_ptr<souffle::RamExpression>> args;
     for (RamDomain i = -100; i <= 100; ++i) {
         args.push_back(std::make_unique<RamSignedConstant>(ramBitCast(static_cast<RamFloat>(i))));
     }
     RamDomain result = evalMultiArg(functor, std::move(args));
     EXPECT_EQ(ramBitCast<RamFloat>(result), static_cast<RamFloat>(-100));
 }
TEST() [227/228]
souffle::test::TEST (MultiArg , SymbolMin)
Definition at line 699 of file ram_arithmetic_test.cpp.
References evalMultiArg(), EXPECT_EQ, i, souffle::SymbolTable::lookup(), souffle::SymbolTable::resolve(), and souffle::SMIN.
{
     FunctorOp functor = FunctorOp::SMIN;
     std::vector<std::unique_ptr<souffle::RamExpression>> args;
     SymbolTable symTab;
     for (RamDomain i = -100; i <= 100; ++i) {
         args.push_back(std::make_unique<RamSignedConstant>(symTab.lookup(std::to_string(i))));
     }
     auto&& result = symTab.resolve(evalMultiArg(functor, std::move(args), symTab));
     EXPECT_EQ(result, "-1");
 }
TEST() [228/228]
souffle::test::TEST (BTreeSet , Parallel)
Definition at line 731 of file btree_set_test.cpp.
References count(), EXPECT_EQ, EXPECT_TRUE, souffle::filter(), i, and souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::insert().
{
     //        const int N = 600000000;
     //        const int N = 100000;
     //        const int N = 10000;
     const int N = 1000;
     //        const int N = 300;
     //        const int N = 100;
     // get a unordered list of test data
     using entry_t = int;
     std::vector<entry_t> list;
     btree_set<entry_t> filter;
     for (int i = 0; i < N; i++) {
         list.push_back(i);
     }
     // the number of times duplicates show up in the input set
     for (int dup = 1; dup < 4; dup++) {
         // now duplicate this list
         std::vector<entry_t> full;
         for (int i = 0; i < dup; i++) {
             for (const auto& cur : list) {
                 full.push_back(cur);
             }
         }
         // shuffle data
         std::random_device rd;
         std::mt19937 generator(rd());
         std::shuffle(full.begin(), full.end(), generator);
         // now insert all those values into a new set - in parallel
         btree_set<entry_t> res;
 #pragma omp parallel for  //  schedule(static,1)
         for (auto it = full.begin(); it < full.end(); ++it) {
             res.insert(*it);
         }
         EXPECT_TRUE(res.check());
         // check resulting values
         EXPECT_EQ(N, res.size());
         std::set<entry_t> should(full.begin(), full.end());
         std::set<entry_t> is(res.begin(), res.end());
         for (const auto& cur : should) {
             EXPECT_TRUE(res.contains(cur)) << "Missing: " << cur << "\n";
         }
         for (const auto& cur : res) {
             EXPECT_TRUE(should.find(cur) != should.end()) << "Additional: " << cur << "\n"
                                                           << "Contained: " << res.contains(cur) << "\n";
         }
         std::vector<entry_t> extra;
         for (const auto& cur : is) {
             if (should.find(cur) == should.end()) extra.push_back(cur);
         }
         EXPECT_TRUE(extra.empty()) << "Extra elments: " << extra << "\n";
         std::vector<entry_t> missing;
         for (const auto& cur : should) {
             if (is.find(cur) == is.end()) missing.push_back(cur);
         }
         EXPECT_TRUE(missing.empty()) << "Missing elments: " << missing << "\n";
         //                << "All Elements: " << should << "\n";
         EXPECT_EQ(N, should.size());
         EXPECT_EQ(N, is.size());
         EXPECT_EQ(should, is);
     }
 }
TESTASTCLONEANDEQUAL() [1/7]
souffle::test::TESTASTCLONEANDEQUAL (Program , R"(.decl r(a:number,b:number,c:number,d:number) .decl s(x:symbol) .decl a(x:number) s("xxx"). r(X,Y,Z,W) :- a(X), 10 = Y, Y = Z, 8 + W = 12 + 14. r(z + 2, x, y, a) :- s(b), b = to_string(a), z = x, a = y, x = 2, a = 2 + x.)")
TESTASTCLONEANDEQUAL() [2/7]
souffle::test::TESTASTCLONEANDEQUAL (Record , R"(.type N <: symbol .type R = [ a : N, B : N ] .decl r (r : R) .decl s (r : N) s(x) :- r([x,y]).)")
TESTASTCLONEANDEQUAL() [3/7]
souffle::test::TESTASTCLONEANDEQUAL (SimpleTypes , R"(.type A <: symbol .type B <: symbol .type U = A | B .decl a (x : A) .decl b (x : B) .decl u (x : U) a(X) :- u(X). b(X) :- u(X). u(X) :- u(X). a(X) :- b(X). a(X) :- b(Y).)")
TESTASTCLONEANDEQUAL() [4/7]
souffle::test::TESTASTCLONEANDEQUAL (ComplexTypes , R"(.type A <: symbol .type B <: number .type U = B .decl a (x : A) .decl b (x : B) .decl u (x : U) a(X) :- X < 10. b(X) :- X < 10. u(X) :- X < 10.)")
TESTASTCLONEANDEQUAL() [5/7]
souffle::test::TESTASTCLONEANDEQUAL (ChainedTypes , R"(.type D <: symbol .type C = D .type B = C .type A = B .decl R1(x:A,y:B) .decl R2(x:C,y:D) .decl R4(x:A) output R4(x) :- R2(x,x),R1(x,x).)")
TESTASTCLONEANDEQUAL() [6/7]
souffle::test::TESTASTCLONEANDEQUAL (NestedAggregates , R"(.type D <: symbol .decl r(x:D) r(x) :- r(y), x=cat(cat(x,x),x).)")
TESTASTCLONEANDEQUAL() [7/7]
souffle::test::TESTASTCLONEANDEQUAL (RelationCopies , R"(.type D = number .decl a(a:D,b:D) .decl b(a:D,b:D) .decl c(a:D,b:D) .decl d(a:D,b:D) a(1,2). b(x,y) :- a(x,y). c(x,y) :- b(x,y). d(x,y) :- b(x,y), c(y,x).)")
testInterpreterStore()
const std::string souffle::test::testInterpreterStore (std::vector< std::string > attribs, std::vector< std::string > attribsTypes, std::vector< std::unique_ptr< RamExpression >> exprs)
Definition at line 49 of file ram_relation_test.cpp.
References souffle::BTREE, souffle::Global::config(), souffle::main(), and types.
Referenced by TEST().
{
     Global::config().set("jobs", "1");
     const size_t arity = attribs.size();
     std::vector<std::unique_ptr<RamRelation>> rels;
     std::unique_ptr<RamRelation> myrel = std::make_unique<RamRelation>(
             "test", arity, 0, attribs, attribsTypes, RelationRepresentation::BTREE);
     std::unique_ptr<RamRelationReference> ref1 = std::make_unique<RamRelationReference>(myrel.get());
     std::unique_ptr<RamRelationReference> ref2 = std::make_unique<RamRelationReference>(myrel.get());
     Json types = Json::object{{"relation",
             Json::object{{"arity", static_cast<long long>(arity)}, {"auxArity", static_cast<long long>(0)},
                     {"types", Json::array(attribsTypes.begin(), attribsTypes.end())}}}};
     std::map<std::string, std::string> dirs = {{"operation", "output"}, {"IO", "stdout"},
             {"attributeNames", "x\ty"}, {"name", "test"}, {"types", types.dump()}};
     std::map<std::string, std::string> ioDirs = std::map<std::string, std::string>(dirs);
     std::unique_ptr<RamStatement> main = std::make_unique<RamSequence>(
             std::make_unique<RamQuery>(std::make_unique<RamProject>(std::move(ref1), std::move(exprs))),
             std::make_unique<RamIO>(std::move(ref2), ioDirs));
     rels.push_back(std::move(myrel));
     std::map<std::string, std::unique_ptr<RamStatement>> subs;
     std::unique_ptr<RamProgram> prog =
             std::make_unique<RamProgram>(std::move(rels), std::move(main), std::move(subs));
     SymbolTable symTab;
     ErrorReport errReport;
     DebugReport debugReport;
     RamTranslationUnit translationUnit(std::move(prog), symTab, errReport, debugReport);
     // configure and execute interpreter
     std::unique_ptr<InterpreterEngine> interpreter = std::make_unique<InterpreterEngine>(translationUnit);
     std::streambuf* oldCoutStreambuf = std::cout.rdbuf();
     std::ostringstream sout;
     std::cout.rdbuf(sout.rdbuf());
     interpreter->executeMain();
     std::cout.rdbuf(oldCoutStreambuf);
     return sout.str();
 }
time()
template<typename Op > long souffle::test::time (const std::string & name, const Op & operation)
Definition at line 411 of file btree_multiset_test.cpp.
References b, duration(), and now().
Referenced by souffle::main(), souffle::ProfileEventSingleton::makeUtilisationEvent(), souffle::profile::ProgramTimepointProcessor::process(), souffle::profile::ProgramResourceUtilisationProcessor::process(), souffle::profile::ProgramRun::setEndtime(), souffle::profile::Iteration::setEndtime(), souffle::profile::Rule::setEndtime(), souffle::profile::Relation::setEndtime(), souffle::profile::ProgramRun::setStarttime(), souffle::profile::Iteration::setStarttime(), souffle::profile::Rule::setStarttime(), souffle::profile::Relation::setStarttime(), TEST(), and TEST().
{
     std::cout << "\t" << std::setw(30) << std::setiosflags(std::ios::left) << name
               << std::resetiosflags(std::ios::left) << " ... " << std::flush;
     auto a = now();
     operation();
     auto b = now();
     auto time = duration(a, b);
     std::cout << " done [" << std::setw(5) << time << "ms]\n";
     return time;
 }