souffle: souffle::profile::Tools Namespace Reference
souffle::profile::Tools Namespace Reference
Functions
std::string cleanJsonOut (std::string value)
escape escapes and quotes, and remove surrounding quotes
std::string cleanJsonOut (double val)
Convert doubles to NaN or scientific notation.
std::string cleanString (std::string val)
Remove
and characters,
and sequence of two chars, and wrapping quotes.
bool file_exists (const std::string &name)
std::string formatMemory (uint64_t kbytes)
std::string formatNum (double amount)
std::string formatNum (int precision, int64_t amount)
std::vector< std::vector< std::string > > formatTable (Table table, int precision)
std::string formatTime (std::chrono::microseconds number)
std::vector< std::string > split (std::string toSplit, std::string delimiter)
split on the delimiter
std::string trimWhitespace (std::string str)
Variables
static const std::vector< std::string > abbreviations
Function Documentation
cleanJsonOut() [1/2]
std::string souffle::profile::Tools::cleanJsonOut (std::string value) inline
escape escapes and quotes, and remove surrounding quotes
Definition at line 247 of file StringUtils.h.
Referenced by genJsonAtoms(), genJsonConfiguration(), souffle::profile::Tui::genJsonRelations(), souffle::genJsonRules(), and TEST().
{
     if (value.size() >= 2) {
         if (value.at(0) == '"' && value.at(value.size() - 1) == '"') {
             value = value.substr(1, value.size() - 2);
         }
     }
     size_t start_pos = 0;
     while ((start_pos = value.find('\\', start_pos)) != std::string::npos) {
         value.replace(start_pos, 1, "\\\\");
         start_pos += 2;
     }
     start_pos = 0;
     while ((start_pos = value.find('"', start_pos)) != std::string::npos) {
         value.replace(start_pos, 1, "\\\"");
         start_pos += 2;
     }
     return value;
 }
cleanJsonOut() [2/2]
std::string souffle::profile::Tools::cleanJsonOut (double val) inline
Convert doubles to NaN or scientific notation.
Definition at line 268 of file StringUtils.h.
References souffle::profile::ss.
{
     if (std::isnan(val)) {
         return "NaN";
     }
     std::ostringstream ss;
     ss << std::scientific << std::setprecision(6) << val;
     return ss.str();
 }
cleanString()
std::string souffle::profile::Tools::cleanString (std::string val) inline
Remove
and characters,
and sequence of two chars, and wrapping quotes.
Definition at line 221 of file StringUtils.h.
Referenced by genJsonAtoms(), TEST(), and souffle::profile::Cell< double >::toString().
{
     if (val.size() < 2) {
         return val;
     }
     size_t start_pos = 0;
     while ((start_pos = val.find('\\', start_pos)) != std::string::npos) {
         val.erase(start_pos, 1);
         if (start_pos < val.size()) {
             if (val[start_pos] == 'n' || val[start_pos] == 't') {
                 val.replace(start_pos, 1, " ");
             }
         }
     }
     if (val.at(0) == '"' && val.at(val.size() - 1) == '"') {
         val = val.substr(1, val.size() - 2);
     }
     std::replace(val.begin(), val.end(), '\n', ' ');
     std::replace(val.begin(), val.end(), '\t', ' ');
     return val;
 }
file_exists()
bool souffle::profile::Tools::file_exists (const std::string & name) inline
Definition at line 211 of file StringUtils.h.
Referenced by genJsonAtoms().
{
     struct stat buffer = {};
     if (stat(name.c_str(), &buffer) == 0) {
         if ((buffer.st_mode & S_IFMT) != 0) {
             return true;
         }
     }
     return false;
 }
formatMemory()
std::string souffle::profile::Tools::formatMemory (uint64_t kbytes) inline
Definition at line 112 of file StringUtils.h.
Referenced by genJsonAtoms(), and TEST().
{
     if (kbytes < 1024L * 2) {
         return std::to_string(kbytes) + "kB";
     } else if (kbytes < 1024L * 1024 * 2) {
         return std::to_string(kbytes / 1024) + "MB";
     } else if (kbytes < 1024L * 1024 * 1024 * 2) {
         return std::to_string(kbytes / (1024 * 1024)) + "GB";
     }
     return std::to_string(kbytes / (1024 * 1024 * 1024)) + "TB";
 }
formatNum() [1/2]
std::string souffle::profile::Tools::formatNum (double amount) inline
Definition at line 40 of file StringUtils.h.
References souffle::profile::ss.
Referenced by souffle::profile::ProgramRun::formatNum(), genJsonAtoms(), TEST(), souffle::profile::Cell< double >::toString(), and souffle::profile::Cell< long >::toString().
{
     std::stringstream ss;
     ss << amount;
     return ss.str();
 }
formatNum() [2/2]
std::string souffle::profile::Tools::formatNum (int precision, int64_t amount) inline
Definition at line 46 of file StringUtils.h.
References abbreviations, and i.
{
     // assumes number is < 999*10^12
     if (amount == 0) {
         return "0";
     }
     if (precision <= 0) {
         return std::to_string(amount);
     }
     std::string result;
     if (amount < 1000) {
         return std::to_string(amount);
     }
     for (size_t i = 0; i < abbreviations.size(); ++i) {
         if (amount > std::pow(1000, i + 2)) {
             continue;
         }
         double r = amount / std::pow(1000, i + 1);
         result = std::to_string(r);
         if (r >= 100) {  // 1000 > result >= 100
             switch (precision) {
                 case 1:
                     result = result.substr(0, 1) + "00";
                     break;
                 case 2:
                     result = result.substr(0, 2) + "0";
                     break;
                 case 3:
                     result = result.substr(0, 3);
                     break;
                 default:
                     result = result.substr(0, precision + 1);
             }
         } else if (r >= 10) {  // 100 > result >= 10
             switch (precision) {
                 case 1:
                     result = result.substr(0, 1) + "0";
                     break;
                 case 2:
                     result = result.substr(0, 2);
                     break;
                 default:
                     result = result.substr(0, precision + 1);
             }
         } else {  // 10 > result > 0
             switch (precision) {
                 case 1:
                     result = result.substr(0, 1);
                     break;
                 default:
                     result = result.substr(0, precision + 1);
             }
         }
         result += abbreviations.at(i);
         return result;
     }
     // If we ever have integers too large to handle, fall back to this
     return std::to_string(amount);
 }
formatTable()
std::vector<std::vector<std::string> > souffle::profile::Tools::formatTable (Table table, int precision) inline
Definition at line 160 of file StringUtils.h.
References souffle::profile::Table::getRows().
Referenced by souffle::profile::ProgramRun::formatTable(), and genJsonAtoms().
{
     std::vector<std::vector<std::string>> result;
     for (auto& row : table.getRows()) {
         std::vector<std::string> result_row;
         for (auto& cell : row->getCells()) {
             if (cell != nullptr) {
                 result_row.push_back(cell->toString(precision));
             } else {
                 result_row.push_back("-");
             }
         }
         result.push_back(result_row);
     }
     return result;
 }
formatTime()
std::string souffle::profile::Tools::formatTime (std::chrono::microseconds number) inline
Definition at line 123 of file StringUtils.h.
Referenced by souffle::profile::ProgramRun::formatTime(), genJsonAtoms(), TEST(), and souffle::profile::Cell< std::chrono::microseconds >::toString().
{
     uint64_t sec = number.count() / 1000000;
     if (sec >= 100) {
         uint64_t min = std::floor(sec / 60);
         if (min >= 100) {
             uint64_t hours = std::floor(min / 60);
             if (hours >= 100) {
                 uint64_t days = std::floor(hours / 24);
                 return std::to_string(days) + "D";
             }
             return std::to_string(hours) + "h";
         }
         if (min < 10) {
             // temp should always be 1 digit long
             uint64_t temp = std::floor((sec - (min * 60.0)) * 10.0 / 6.0);
             return std::to_string(min) + "." + std::to_string(temp).substr(0, 1) + "m";
         }
         return std::to_string(min) + "m";
     } else if (sec >= 10) {
         return std::to_string(sec) + "s";
     } else if (number.count() >= 1000000) {
         std::string temp = std::to_string(number.count() / 100);
         return temp.substr(0, 1) + "." + temp.substr(1, 2) + "s";
     } else if (number.count() >= 100000) {
         std::string temp = std::to_string(number.count() / 1000);
         return "." + temp.substr(0, 3) + "s";
     } else if (number.count() >= 10000) {
         std::string temp = std::to_string(number.count() / 1000);
         return ".0" + temp.substr(0, 2) + "s";
     } else if (number.count() >= 1000) {
         std::string temp = std::to_string(number.count() / 1000);
         return ".00" + temp.substr(0, 1) + "s";
     }
     return ".000s";
 }
split()
std::vector<std::string> souffle::profile::Tools::split (std::string toSplit, std::string delimiter) inline
split on the delimiter
Definition at line 177 of file StringUtils.h.
Referenced by genJsonAtoms(), souffle::genJsonRules(), souffle::profile::Cli::parse(), souffle::profile::Tui::runProf(), and TEST().
{
     std::vector<std::string> elements;
     std::string::size_type lastPos = 0;
     auto pos = toSplit.find(delimiter, lastPos);
     while (pos != std::string::npos) {
         if (pos > 0) {
             std::string newElement = toSplit.substr(lastPos, pos - lastPos);
             elements.push_back(newElement);
         }
         lastPos = pos + delimiter.size();
         pos = toSplit.find(delimiter, lastPos);
     }
     if (lastPos < toSplit.size()) {
         elements.push_back(toSplit.substr(lastPos));
     }
     return elements;
 }
trimWhitespace()
std::string souffle::profile::Tools::trimWhitespace (std::string str) inline
Definition at line 197 of file StringUtils.h.
References str.
Referenced by souffle::profile::Tui::runProf(), and TEST().
{
     std::string whitespace = " \t";
     size_t first = str.find_first_not_of(whitespace);
     if (first != std::string::npos) {
         str.erase(0, first);
         size_t last = str.find_last_not_of(whitespace);
         str.erase(last + 1);
     } else {
         str.clear();
     }
     return str;
 }
Variable Documentation
abbreviations
const std::vector<std::string> souffle::profile::Tools::abbreviations static
Initial value:
{
        "K", "M", "B", "t", "q", "Q", "s", "S", "o", "n", "d", "U"}
Definition at line 37 of file StringUtils.h.
Referenced by formatNum().