souffle: json11 Namespace Reference
json11 Namespace Reference
Data Structures
class Json
class JsonArray
class JsonBoolean
class JsonDouble
class JsonInt
class JsonNull
class JsonObject
class JsonString
class JsonValue
struct NullStruct
struct Statics
class Value
Enumerations
enum JsonParse { STANDARD, COMMENTS }
Functions
static void dump (NullStruct, std::string &out)
static void dump (double value, std::string &out)
static void dump (long long value, std::string &out)
static void dump (bool value, std::string &out)
static void dump (const std::string &value, std::string &out)
static void dump (const Json::array &values, std::string &out)
static void dump (const Json::object &values, std::string &out)
static std::string esc (char c)
static bool in_range (long x, long lower, long upper)
std::vector< Json > parse_multi (const std::string &in, std::string::size_type &parser_stop_pos, std::string &err, JsonParse strategy)
static const Json & static_null ()
static const Statics & statics ()
Variables
static const int max_depth = 200
Enumeration Type Documentation
JsonParse
enum json11::JsonParse
Enumerator
STANDARD
COMMENTS
Definition at line 82 of file json11.h.
 { STANDARD, COMMENTS };
Function Documentation
dump() [1/7]
static void json11::dump (NullStruct , std::string & out) static
Definition at line 284 of file json11.h.
Referenced by json11::Value< Json::BOOL, bool >::dump(), souffle::SparseArray< value_t, BITS, merge_op >::dump(), souffle::WriteStreamJSON::writeNextTupleList(), and souffle::WriteStreamJSON::writeNextTupleObject().
{
     out += "null";
 }
dump() [2/7]
static void json11::dump (double value, std::string & out) static
Definition at line 288 of file json11.h.
{
     if (std::isfinite(value)) {
         char buf[32];
         snprintf(buf, sizeof buf, "%.17g", value);
         out += buf;
     } else {
         out += "null";
     }
 }
dump() [3/7]
static void json11::dump (long long value, std::string & out) static
Definition at line 298 of file json11.h.
{
     char buf[32];
     snprintf(buf, sizeof buf, "%lld", value);
     out += buf;
 }
dump() [4/7]
static void json11::dump (bool value, std::string & out) static
Definition at line 304 of file json11.h.
{
     out += value ? "true" : "false";
 }
dump() [5/7]
static void json11::dump (const std::string & value, std::string & out) static
Definition at line 308 of file json11.h.
References i.
{
     out += '"';
     for (size_t i = 0; i < value.length(); i++) {
         const char ch = value[i];
         if (ch == '\\') {
             out += "\\\\";
         } else if (ch == '"') {
             out += "\\\"";
         } else if (ch == '\b') {
             out += "\\b";
         } else if (ch == '\f') {
             out += "\\f";
         } else if (ch == '\n') {
             out += "\\n";
         } else if (ch == '\r') {
             out += "\\r";
         } else if (ch == '\t') {
             out += "\\t";
         } else if (static_cast<uint8_t>(ch) <= 0x1f) {
             char buf[8];
             snprintf(buf, sizeof buf, "\\u%04x", ch);
             out += buf;
         } else if (static_cast<uint8_t>(ch) == 0xe2 && static_cast<uint8_t>(value[i + 1]) == 0x80 &&
                    static_cast<uint8_t>(value[i + 2]) == 0xa8) {
             out += "\\u2028";
             i += 2;
         } else if (static_cast<uint8_t>(ch) == 0xe2 && static_cast<uint8_t>(value[i + 1]) == 0x80 &&
                    static_cast<uint8_t>(value[i + 2]) == 0xa9) {
             out += "\\u2029";
             i += 2;
         } else {
             out += ch;
         }
     }
     out += '"';
 }
dump() [6/7]
static void json11::dump (const Json::array & values, std::string & out) static
Definition at line 345 of file json11.h.
{
     bool first = true;
     out += "[";
     for (const auto& value : values) {
         if (!first) out += ", ";
         value.dump(out);
         first = false;
     }
     out += "]";
 }
dump() [7/7]
static void json11::dump (const Json::object & values, std::string & out) static
Definition at line 356 of file json11.h.
References json11::Json::dump().
{
     bool first = true;
     out += "{";
     for (const auto& kv : values) {
         if (!first) out += ", ";
         dump(kv.first, out);
         out += ": ";
         kv.second.dump(out);
         first = false;
     }
     out += "}";
 }
esc()
static std::string json11::esc (char c) inline static
Definition at line 639 of file json11.h.
Referenced by json11::Json::parse().
{
     char buf[12];
     if (static_cast<uint8_t>(c) >= 0x20 && static_cast<uint8_t>(c) <= 0x7f) {
         snprintf(buf, sizeof buf, "'%c' (%d)", c, c);
     } else {
         snprintf(buf, sizeof buf, "(%d)", c);
     }
     return std::string(buf);
 }
in_range()
static bool json11::in_range (long x, long lower, long upper) inline static
Definition at line 649 of file json11.h.
{
     return (x >= lower && x <= upper);
 }
parse_multi()
std::vector<Json> json11::parse_multi (const std::string & in, std::string::size_type & parser_stop_pos, std::string & err, JsonParse strategy) inline
Definition at line 1086 of file json11.h.
References err.
{
     JsonParser parser{in, 0, err, false, strategy};
     parser_stop_pos = 0;
     std::vector<Json> json_vec;
     while (parser.i != in.size() && !parser.failed) {
         json_vec.push_back(parser.parse_json(0));
         if (parser.failed) {
             break;
         }
         // Check for another object
         parser.consume_garbage();
         if (parser.failed) {
             break;
         }
         parser_stop_pos = parser.i;
     }
     return json_vec;
 }
static_null()
static const Json& json11::static_null () static
Definition at line 508 of file json11.h.
Referenced by json11::JsonValue::operator[](), json11::JsonArray::operator[](), and json11::JsonObject::operator[]().
{
     // This has to be separate, not in Statics, because Json() accesses statics().null.
     static const Json json_null;
     return json_null;
 }
statics()
static const Statics& json11::statics () static
Definition at line 503 of file json11.h.
Referenced by json11::JsonValue::array_items(), json11::JsonValue::object_items(), and json11::JsonValue::string_value().
{
     static const Statics s{};
     return s;
 }
Variable Documentation
max_depth
const int json11::max_depth = 200 static
Definition at line 265 of file json11.h.