souffle: souffle::evaluator Namespace Reference
souffle::evaluator Namespace Reference
Data Structures
struct lxor_infix
Functions
template<typename A >
bool lxor (A x, A y)
template<typename A >
lxor_infix::curry< A > operator+ (A x, lxor_infix)
template<typename A , typename F >
void runRange (A from, A to, A step, F &&go)
template<typename A , typename F >
void runRange (A from, A to, F &&go)
template<typename A >
A symbol2numeric (const std::string &src)
Function Documentation
lxor()
template<typename A > bool souffle::evaluator::lxor (A x, A y)
Definition at line 66 of file EvaluatorUtil.h.
Referenced by souffle::evaluator::lxor_infix::curry< A >::operator+().
                     {
     return (x || y) && (!x != !y);
 }
operator+()
template<typename A > lxor_infix::curry<A> souffle::evaluator::operator+ (A x, lxor_infix)
Definition at line 86 of file EvaluatorUtil.h.
{
     return lxor_infix::curry<A>{x};
 }
runRange() [1/2]
template<typename A , typename F > void souffle::evaluator::runRange (A from, A to, A step, F && go)
Definition at line 26 of file EvaluatorUtil.h.
References GO.
Referenced by runRange().
{
 #define GO(x) go(Tuple<RamDomain, 1>{ramBitCast(x)})
     if (0 < step) {
         for (auto x = from; x < to; x += step) {
             GO(x);
         }
     } else if (step < 0) {
         for (auto x = from; to < x; x += step) {
             GO(x);
         }
     } else if (from != to) {
         // `step = 0` edge case, only if non-empty range
         GO(from);
     }
 #undef GO
 }
runRange() [2/2]
template<typename A , typename F > void souffle::evaluator::runRange (A from, A to, F && go)
Definition at line 44 of file EvaluatorUtil.h.
References runRange().
{
     return runRange(from, to, A(from <= to ? 1 : -1), std::forward<F>(go));
 }
symbol2numeric()
template<typename A > A souffle::evaluator::symbol2numeric (const std::string & src)
Definition at line 49 of file EvaluatorUtil.h.
References souffle::fatal(), tinyformat::format(), souffle::RamFloatFromString(), souffle::RamSignedFromString(), and souffle::RamUnsignedFromString().
{
     try {
         if constexpr (std::is_same_v<RamFloat, A>) {
             return RamFloatFromString(src);
         } else if constexpr (std::is_same_v<RamSigned, A>) {
             return RamSignedFromString(src);
         } else if constexpr (std::is_same_v<RamUnsigned, A>) {
             return RamUnsignedFromString(src);
         }
     } catch (...) {
         tfm::format(std::cerr, "error: wrong string provided by `to_number(\"%s\")` functor.\n", src);
         raise(SIGFPE);
         fatal("");  // UNREACHABLE: `raise` lacks a no-return attribute
     }
 };