souffle: tinyformat::detail Namespace Reference
tinyformat::detail Namespace Reference
Data Structures
struct convertToInt
struct convertToInt< T, true >
class FormatArg
class FormatListN
class FormatListN< 0 >
struct formatValueAsType
struct formatValueAsType< T, fmtT, true >
struct is_convertible
struct is_wchar
struct is_wchar< const wchar_t * >
struct is_wchar< const wchar_t[n]>
struct is_wchar< wchar_t * >
struct is_wchar< wchar_t[n]>
Functions
void formatImpl (std::ostream &out, const char *fmt, const detail::FormatArg *args, int numArgs)
template<typename T >
void formatTruncated (std::ostream &out, const T &value, int ntrunc)
int parseIntAndAdvance (const char *&c)
bool parseWidthOrPrecision (int &n, const char *&c, bool positionalMode, const detail::FormatArg *args, int &argIndex, int numArgs)
const char * printFormatStringLiteral (std::ostream &out, const char *fmt)
const char * streamStateFromFormat (std::ostream &out, bool &positionalMode, bool &spacePadPositive, int &ntrunc, const char *fmtStart, const detail::FormatArg *args, int &argIndex, int numArgs)
Function Documentation
formatImpl()
void tinyformat::detail::formatImpl (std::ostream & out, const char * fmt, const detail::FormatArg * args, int numArgs) inline
Definition at line 863 of file tinyformat.h.
References tinyformat::detail::FormatArg::format(), i, printFormatStringLiteral(), streamStateFromFormat(), and TINYFORMAT_ERROR.
Referenced by tinyformat::vformat().
 {
     // Saved stream state
     std::streamsize origWidth = out.width();
     std::streamsize origPrecision = out.precision();
     std::ios::fmtflags origFlags = out.flags();
     char origFill = out.fill();
     // "Positional mode" means all format specs should be of the form "%n$..."
     // with `n` an integer. We detect this in `streamStateFromFormat`.
     bool positionalMode = false;
     int argIndex = 0;
     while (true) {
         fmt = printFormatStringLiteral(out, fmt);
         if (*fmt == '\0') {
             if (!positionalMode && argIndex < numArgs) {
                 TINYFORMAT_ERROR("tinyformat: Not enough conversion specifiers in format string");
             }
             break;
         }
         bool spacePadPositive = false;
         int ntrunc = -1;
         const char* fmtEnd = streamStateFromFormat(out, positionalMode, spacePadPositive, ntrunc, fmt,
                                                    args, argIndex, numArgs);
         // NB: argIndex may be incremented by reading variable width/precision
         // in `streamStateFromFormat`, so do the bounds check here.
         if (argIndex >= numArgs) {
             TINYFORMAT_ERROR("tinyformat: Too many conversion specifiers in format string");
             return;
         }
         const FormatArg& arg = args[argIndex];
         // Format the arg into the stream.
         if (!spacePadPositive) {
             arg.format(out, fmt, fmtEnd, ntrunc);
         }
         else {
             // The following is a special case with no direct correspondence
             // between stream formatting and the printf() behaviour.  Simulate
             // it crudely by formatting into a temporary string stream and
             // munging the resulting string.
             std::ostringstream tmpStream;
             tmpStream.copyfmt(out);
             tmpStream.setf(std::ios::showpos);
             arg.format(tmpStream, fmt, fmtEnd, ntrunc);
             std::string result = tmpStream.str(); // allocates... yuck.
             for (char & i : result) {
                 if (i == '+')
                     i = ' ';
             }
             out << result;
         }
         if (!positionalMode)
             ++argIndex;
         fmt = fmtEnd;
     }
     // Restore stream state
     out.width(origWidth);
     out.precision(origPrecision);
     out.flags(origFlags);
     out.fill(origFill);
 }
formatTruncated()
template<typename T > void tinyformat::detail::formatTruncated (std::ostream & out, const T & value, int ntrunc) inline
Definition at line 283 of file tinyformat.h.
References tinyformat::detail::is_convertible< T1, T2 >::value.
Referenced by tinyformat::formatValue().
 {
     std::ostringstream tmp;
     tmp << value;
     std::string result = tmp.str();
     out.write(result.c_str(), (std::min)(ntrunc, static_cast<int>(result.size())));
 }
parseIntAndAdvance()
int tinyformat::detail::parseIntAndAdvance (const char *& c) inline
Definition at line 552 of file tinyformat.h.
References i.
Referenced by parseWidthOrPrecision(), and streamStateFromFormat().
 {
     int i = 0;
     for (;*c >= '0' && *c <= '9'; ++c)
         i = 10*i + (*c - '0');
     return i;
 }
parseWidthOrPrecision()
bool tinyformat::detail::parseWidthOrPrecision (int & n, const char *& c, bool positionalMode, const detail::FormatArg * args, int & argIndex, int numArgs) inline
Definition at line 565 of file tinyformat.h.
References parseIntAndAdvance(), TINYFORMAT_ERROR, and tinyformat::detail::FormatArg::toInt().
Referenced by streamStateFromFormat().
 {
     if (*c >= '0' && *c <= '9') {
         n = parseIntAndAdvance(c);
     }
     else if (*c == '*') {
         ++c;
         n = 0;
         if (positionalMode) {
             int pos = parseIntAndAdvance(c) - 1;
             if (*c != '$')
                 TINYFORMAT_ERROR("tinyformat: Non-positional argument used after a positional one");
             if (pos >= 0 && pos < numArgs)
                 n = args[pos].toInt();
             else
                 TINYFORMAT_ERROR("tinyformat: Positional argument out of range");
             ++c;
         }
         else {
             if (argIndex < numArgs)
                 n = args[argIndex++].toInt();
             else
                 TINYFORMAT_ERROR("tinyformat: Not enough arguments to read variable width or precision");
         }
     }
     else {
         return false;
     }
     return true;
 }
printFormatStringLiteral()
const char* tinyformat::detail::printFormatStringLiteral (std::ostream & out, const char * fmt) inline
Definition at line 603 of file tinyformat.h.
Referenced by formatImpl().
 {
     const char* c = fmt;
     for (;; ++c) {
         if (*c == '\0') {
             out.write(fmt, c - fmt);
             return c;
         }
         else if (*c == '%') {
             out.write(fmt, c - fmt);
             if (*(c+1) != '%')
                 return c;
             // for "%%", tack trailing % onto next literal section.
             fmt = ++c;
         }
     }
 }
streamStateFromFormat()
const char* tinyformat::detail::streamStateFromFormat (std::ostream & out, bool & positionalMode, bool & spacePadPositive, int & ntrunc, const char * fmtStart, const detail::FormatArg * args, int & argIndex, int numArgs) inline
Definition at line 655 of file tinyformat.h.
References parseIntAndAdvance(), parseWidthOrPrecision(), TINYFORMAT_ASSERT, and TINYFORMAT_ERROR.
Referenced by formatImpl().
 {
     TINYFORMAT_ASSERT(*fmtStart == '%');
     // Reset stream state to defaults.
     out.width(0);
     out.precision(6);
     out.fill(' ');
     // Reset most flags; ignore irrelevant unitbuf & skipws.
     out.unsetf(std::ios::adjustfield | std::ios::basefield |
                std::ios::floatfield | std::ios::showbase | std::ios::boolalpha |
                std::ios::showpoint | std::ios::showpos | std::ios::uppercase);
     bool precisionSet = false;
     bool widthSet = false;
     int widthExtra = 0;
     const char* c = fmtStart + 1;
     // 1) Parse an argument index (if followed by '$') or a width possibly
     // preceded with '0' flag.
     if (*c >= '0' && *c <= '9') {
         const char tmpc = *c;
         int value = parseIntAndAdvance(c);
         if (*c == '$') {
             // value is an argument index
             if (value > 0 && value <= numArgs)
                 argIndex = value - 1;
             else
                 TINYFORMAT_ERROR("tinyformat: Positional argument out of range");
             ++c;
             positionalMode = true;
         }
         else if (positionalMode) {
             TINYFORMAT_ERROR("tinyformat: Non-positional argument used after a positional one");
         }
         else {
             if (tmpc == '0') {
                 // Use internal padding so that numeric values are
                 // formatted correctly, eg -00010 rather than 000-10
                 out.fill('0');
                 out.setf(std::ios::internal, std::ios::adjustfield);
             }
             if (value != 0) {
                 // Nonzero value means that we parsed width.
                 widthSet = true;
                 out.width(value);
             }
         }
     }
     else if (positionalMode) {
         TINYFORMAT_ERROR("tinyformat: Non-positional argument used after a positional one");
     }
     // 2) Parse flags and width if we did not do it in previous step.
     if (!widthSet) {
         // Parse flags
         for (;; ++c) {
             switch (*c) {
                 case '#':
                     out.setf(std::ios::showpoint | std::ios::showbase);
                     continue;
                 case '0':
                     // overridden by left alignment ('-' flag)
                     if (!(out.flags() & std::ios::left)) {
                         // Use internal padding so that numeric values are
                         // formatted correctly, eg -00010 rather than 000-10
                         out.fill('0');
                         out.setf(std::ios::internal, std::ios::adjustfield);
                     }
                     continue;
                 case '-':
                     out.fill(' ');
                     out.setf(std::ios::left, std::ios::adjustfield);
                     continue;
                 case ' ':
                     // overridden by show positive sign, '+' flag.
                     if (!(out.flags() & std::ios::showpos))
                         spacePadPositive = true;
                     continue;
                 case '+':
                     out.setf(std::ios::showpos);
                     spacePadPositive = false;
                     widthExtra = 1;
                     continue;
                 default:
                     break;
             }
             break;
         }
         // Parse width
         int width = 0;
         widthSet = parseWidthOrPrecision(width, c, positionalMode,
                                          args, argIndex, numArgs);
         if (widthSet) {
             if (width < 0) {
                 // negative widths correspond to '-' flag set
                 out.fill(' ');
                 out.setf(std::ios::left, std::ios::adjustfield);
                 width = -width;
             }
             out.width(width);
         }
     }
     // 3) Parse precision
     if (*c == '.') {
         ++c;
         int precision = 0;
         parseWidthOrPrecision(precision, c, positionalMode,
                               args, argIndex, numArgs);
         // Presence of `.` indicates precision set, unless the inferred value
         // was negative in which case the default is used.
         precisionSet = precision >= 0;
         if (precisionSet)
             out.precision(precision);
     }
     // 4) Ignore any C99 length modifier
     while (*c == 'l' || *c == 'h' || *c == 'L' ||
            *c == 'j' || *c == 'z' || *c == 't') {
         ++c;
     }
     // 5) We're up to the conversion specifier character.
     // Set stream flags based on conversion specifier (thanks to the
     // boost::format class for forging the way here).
     bool intConversion = false;
     switch (*c) {
         case 'u': case 'd': case 'i':
             out.setf(std::ios::dec, std::ios::basefield);
             intConversion = true;
             break;
         case 'o':
             out.setf(std::ios::oct, std::ios::basefield);
             intConversion = true;
             break;
         case 'X':
             out.setf(std::ios::uppercase);
             // Falls through
         case 'x': case 'p':
             out.setf(std::ios::hex, std::ios::basefield);
             intConversion = true;
             break;
         case 'E':
             out.setf(std::ios::uppercase);
             // Falls through
         case 'e':
             out.setf(std::ios::scientific, std::ios::floatfield);
             out.setf(std::ios::dec, std::ios::basefield);
             break;
         case 'F':
             out.setf(std::ios::uppercase);
             // Falls through
         case 'f':
             out.setf(std::ios::fixed, std::ios::floatfield);
             break;
         case 'A':
             out.setf(std::ios::uppercase);
             // Falls through
         case 'a':
 #           ifdef _MSC_VER
             // Workaround https://developercommunity.visualstudio.com/content/problem/520472/hexfloat-stream-output-does-not-ignore-precision-a.html
             // by always setting maximum precision on MSVC to avoid precision
             // loss for doubles.
             out.precision(13);
 #           endif
             out.setf(std::ios::fixed | std::ios::scientific, std::ios::floatfield);
             break;
         case 'G':
             out.setf(std::ios::uppercase);
             // Falls through
         case 'g':
             out.setf(std::ios::dec, std::ios::basefield);
             // As in boost::format, let stream decide float format.
             out.flags(out.flags() & ~std::ios::floatfield);
             break;
         case 'c':
             // Handled as special case inside formatValue()
             break;
         case 's':
             if (precisionSet)
                 ntrunc = static_cast<int>(out.precision());
             // Make %s print Booleans as "true" and "false"
             out.setf(std::ios::boolalpha);
             break;
         case 'n':
             // Not supported - will cause problems!
             TINYFORMAT_ERROR("tinyformat: %n conversion spec not supported");
             break;
         case '\0':
             TINYFORMAT_ERROR("tinyformat: Conversion spec incorrectly "
                              "terminated by end of string");
             return c;
         default:
             break;
     }
     if (intConversion && precisionSet && !widthSet) {
         // "precision" for integers gives the minimum number of digits (to be
         // padded with zeros on the left).  This isn't really supported by the
         // iostreams, but we can approximately simulate it with the width if
         // the width isn't otherwise used.
         out.width(out.precision() + widthExtra);
         out.setf(std::ios::internal, std::ios::adjustfield);
         out.fill('0');
     }
     return c+1;
 }