souffle: tinyformat Namespace Reference
tinyformat Namespace Reference
Namespaces
detail
Data Structures
class FormatList
List of template arguments format(), held in a type-opaque way.
Typedefs
using FormatListRef = const FormatList &
Reference to type-opaque format list for passing to vformat()
Functions
void format (std::ostream &out, const char *fmt)
std::string format (const char *fmt)
template<typename T >
void formatValue (std::ostream &out, const char *, const char *fmtEnd, int ntrunc, const T &value)
Format a value into a stream, delegating to operator<< by default.
detail::FormatListN< 0 > makeFormatList ()
void printf (const char *fmt)
void printfln (const char *fmt)
void vformat (std::ostream &out, const char *fmt, FormatListRef list)
Format list of arguments to the stream according to the given format string.
Typedef Documentation
FormatListRef
using tinyformat::FormatListRef = typedef const FormatList &
Reference to type-opaque format list for passing to vformat()
Definition at line 952 of file tinyformat.h.
Function Documentation
format() [1/2]
void tinyformat::format (std::ostream & out, const char * fmt) inline
Definition at line 1085 of file tinyformat.h.
References makeFormatList(), and vformat().
Referenced by souffle::ParserDriver::addDeprecatedTag(), souffle::ParserDriver::addTag(), souffle::AstSemanticCheckerImpl::checkRecordType(), souffle::AstSemanticCheckerImpl::checkRelationDeclaration(), souffle::AstSemanticCheckerImpl::checkSubsetType(), souffle::AstSemanticCheckerImpl::checkUnionType(), souffle::TypeEnvironmentAnalysis::createType(), souffle::Synthesiser::emitCode(), souffle::fatal(), format(), souffle::Synthesiser::generateCode(), souffle::getTypeQualifier(), souffle::makeInfoRelation(), souffle::AstFunctorDeclaration::print(), souffle::SubsetType::print(), souffle::RamIntrinsicOperator::print(), souffle::UnionType::print(), souffle::RecordType::print(), printf(), printfln(), souffle::evaluator::symbol2numeric(), souffle::ExplainProvenance::valueShow(), vformat(), souffle::TypeChecker::visitAtom(), and souffle::TypeChecker::visitTypeCast().
 {
     vformat(out, fmt, makeFormatList());
 }
format() [2/2]
std::string tinyformat::format (const char * fmt) inline
Definition at line 1090 of file tinyformat.h.
References format().
 {
     std::ostringstream oss;
     format(oss, fmt);
     return oss.str();
 }
formatValue()
template<typename T > void tinyformat::formatValue (std::ostream & out, const char * , const char * fmtEnd, int ntrunc, const T & value) inline
Format a value into a stream, delegating to operator<< by default.
Users may override this for their own types. When this function is called, the stream flags will have been modified according to the format string. The format specification is provided in the range [fmtBegin, fmtEnd). For truncating conversions, ntrunc is set to the desired maximum number of characters, for example "%.7s" calls formatValue with ntrunc = 7.
By default, formatValue() uses the usual stream insertion operator operator<< to format the type T, with special cases for the c and p conversions.
Definition at line 324 of file tinyformat.h.
References tinyformat::detail::formatTruncated(), and tinyformat::detail::is_convertible< T1, T2 >::value.
Referenced by tinyformat::detail::FormatArg::formatImpl().
 {
 #ifndef TINYFORMAT_ALLOW_WCHAR_STRINGS
     // Since we don't support printing of wchar_t using "%ls", make it fail at
     // compile time in preference to printing as a void* at runtime.
     using DummyType = typename detail::is_wchar<T>::tinyformat_wchar_is_not_supported;
     (void) DummyType(); // avoid unused type warning with gcc-4.8
 #endif
     // The mess here is to support the %c and %p conversions: if these
     // conversions are active we try to convert the type to a char or const
     // void* respectively and format that instead of the value itself.  For the
     // %p conversion it's important to avoid dereferencing the pointer, which
     // could otherwise lead to a crash when printing a dangling (const char*).
     const bool canConvertToChar = detail::is_convertible<T,char>::value;
     const bool canConvertToVoidPtr = detail::is_convertible<T, const void*>::value;
     if (canConvertToChar && *(fmtEnd-1) == 'c')
         detail::formatValueAsType<T, char>::invoke(out, value);
     else if (canConvertToVoidPtr && *(fmtEnd-1) == 'p')
         detail::formatValueAsType<T, const void*>::invoke(out, value);
 #ifdef TINYFORMAT_OLD_LIBSTDCPLUSPLUS_WORKAROUND
     else if (detail::formatZeroIntegerWorkaround<T>::invoke(out, value)) /**/;
 #endif
     else if (ntrunc >= 0) {
         // Take care not to overread C strings in truncating conversions like
         // "%.4s" where at most 4 characters may be read.
         detail::formatTruncated(out, value, ntrunc);
     }
     else
         out << value;
 }
makeFormatList()
detail::FormatListN<0> tinyformat::makeFormatList () inline
Definition at line 1024 of file tinyformat.h.
Referenced by format(), tinyformat::detail::FormatListN< 0 >::FormatListN(), and vformat().
 {
     return detail::FormatListN<0>();
 }
printf()
void tinyformat::printf (const char * fmt) inline
Definition at line 1097 of file tinyformat.h.
References format().
Referenced by genJsonAtoms(), souffle::CmdOptions::parse(), souffle::profile::Tui::runCommand(), and vformat().
 {
     format(std::cout, fmt);
 }
printfln()
void tinyformat::printfln (const char * fmt) inline
Definition at line 1102 of file tinyformat.h.
References format().
Referenced by vformat().
 {
     format(std::cout, fmt);
     std::cout << '\n';
 }
vformat()
void tinyformat::vformat (std::ostream & out, const char * fmt, FormatListRef list) inline
Format list of arguments to the stream according to the given format string.
The name vformat() is chosen for the semantic similarity to vprintf(): the list of format arguments is held in a single function argument.
Definition at line 1043 of file tinyformat.h.
References format(), tinyformat::detail::formatImpl(), tinyformat::FormatList::m_args, tinyformat::FormatList::m_N, makeFormatList(), printf(), and printfln().
Referenced by format(), and tinyformat::FormatList::FormatList().
 {
     detail::formatImpl(out, fmt, list.m_args, list.m_N);
 }