souffle: testutil Namespace Reference
testutil Namespace Reference
Functions
template<typename T >
std::vector< T > generateRandomVector (const size_t vectorSize, const int seed=3)
template<class T >
void ignore (const T &)
Function Documentation
generateRandomVector()
template<typename T > std::vector<T> testutil::generateRandomVector (const size_t vectorSize, const int seed = 3)
Definition at line 39 of file test.h.
{
     std::vector<T> values(vectorSize);
     std::default_random_engine randomGenerator(seed);
     if constexpr (std::is_floating_point<T>::value) {
         // For distribution bonds, following must hold:
         // a ≤ b and b − a ≤ numeric_limits<RealType>::max()
         // (in particular: if given values bounds, it will crash).
         // TODO (darth_tytus): Investigate a better solution.
         std::uniform_real_distribution<T> distribution(-1000, 1000);
         std::generate(values.begin(), values.end(),
                 [&distribution, &randomGenerator]() { return distribution(randomGenerator); });
         return values;
     } else {
         std::uniform_int_distribution<T> distribution(
                 std::numeric_limits<T>::lowest(), std::numeric_limits<T>::max());
         std::generate(values.begin(), values.end(),
                 [&distribution, &randomGenerator]() { return distribution(randomGenerator); });
         return values;
     }
 }
ignore()
template<class T > void testutil::ignore (const T &)
Definition at line 64 of file test.h.
Referenced by souffle::EquivalenceRelation< t_tuple< 2 > >::extend(), souffle::getGroundedTerms(), and souffle::test::TEST().
 {}