souffle: souffle::Table< T, blockSize >::Block Struct Reference
souffle::Table< T, blockSize >::Block Struct Reference
Public Member Functions
const T & append (const T &element)
Block ()
bool isFull () const
Data Fields
T data [blockSize]
Block * next
std::size_t used = 0
Detailed Description
template<typename T, unsigned blockSize = 4096>
struct souffle::Table< T, blockSize >::Block
Definition at line 27 of file Table.h.
Constructor & Destructor Documentation
Block()
template<typename T, unsigned blockSize = 4096> souffle::Table< T, blockSize >::Block::Block () inline
Definition at line 32 of file Table.h.
Referenced by souffle::Table< T, blockSize >::insert().
 : next(nullptr) {}
Member Function Documentation
append()
template<typename T, unsigned blockSize = 4096> const T& souffle::Table< T, blockSize >::Block::append (const T & element) inline
Definition at line 38 of file Table.h.
References souffle::Table< T, blockSize >::Block::used.
Referenced by souffle::Table< T, blockSize >::insert().
{
             const T& res = data[used];
             data[used] = element;
             used++;
             return res;
         }
isFull()
template<typename T, unsigned blockSize = 4096> bool souffle::Table< T, blockSize >::Block::isFull () const inline
Definition at line 34 of file Table.h.
Referenced by souffle::Table< T, blockSize >::insert().
{
             return used == blockSize;
         }
Field Documentation
data
template<typename T, unsigned blockSize = 4096> T souffle::Table< T, blockSize >::Block::data[blockSize]
Definition at line 30 of file Table.h.
Referenced by souffle::Table< T, blockSize >::iterator::operator*().
next
template<typename T, unsigned blockSize = 4096> Block* souffle::Table< T, blockSize >::Block::next
Definition at line 28 of file Table.h.
Referenced by souffle::Table< T, blockSize >::clear(), souffle::Table< T, blockSize >::insert(), and souffle::Table< T, blockSize >::iterator::operator++().
used
template<typename T, unsigned blockSize = 4096> std::size_t souffle::Table< T, blockSize >::Block::used = 0
Definition at line 29 of file Table.h.
Referenced by souffle::Table< T, blockSize >::Block::append(), and souffle::Table< T, blockSize >::iterator::operator++().
The documentation for this struct was generated from the following file:
Table.h