souffle: souffle::RuleBody::literal Struct Reference
souffle::RuleBody::literal Struct Reference
Public Member Functions
literal clone () const
literal (bool negated, std::unique_ptr< AstLiteral > atom)
Data Fields
std::unique_ptr< AstLiteral > atom
bool negated
Detailed Description
Definition at line 61 of file ParserUtils.h.
Constructor & Destructor Documentation
literal()
souffle::RuleBody::literal::literal (bool negated, std::unique_ptr< AstLiteral > atom) inline
Definition at line 62 of file ParserUtils.h.
Referenced by clone().
 : negated(negated), atom(std::move(atom)) {}
Member Function Documentation
clone()
literal souffle::RuleBody::literal::clone () const inline
Definition at line 70 of file ParserUtils.h.
References souffle::clone(), and literal().
{
             return literal(negated, souffle::clone(atom));
         }
Field Documentation
atom
std::unique_ptr<AstLiteral> souffle::RuleBody::literal::atom
Definition at line 68 of file ParserUtils.h.
Referenced by souffle::RuleBody::equal().
negated
bool souffle::RuleBody::literal::negated
Definition at line 65 of file ParserUtils.h.
Referenced by souffle::RuleBody::equal(), and souffle::RuleBody::negated().
The documentation for this struct was generated from the following file:
ast/ParserUtils.h