souffle: souffle::GenericIndex< Structure >::GenericIndexView Struct Reference
souffle::GenericIndex< Structure >::GenericIndexView Struct Reference
Public Member Functions
bool contains (const TupleRef &tuple) const override
Tests whether the given entry is contained in this index.
bool contains (const TupleRef &low, const TupleRef &high) const override
Tests whether any element in the given range is contained in this index.
GenericIndexView (const GenericIndex &index)
size_t getArity () const override
Return arity size of the index.
Stream range (const TupleRef &low, const TupleRef &high) const override
Obtains a stream for the given range within this index.
Public Member Functions inherited from souffle::IndexView
virtual ~IndexView ()=default
Data Fields
Hints hints
const GenericIndex & index
Detailed Description
template<typename Structure>
struct souffle::GenericIndex< Structure >::GenericIndexView
Definition at line 371 of file InterpreterIndex.cpp.
Constructor & Destructor Documentation
GenericIndexView()
template<typename Structure> souffle::GenericIndex< Structure >::GenericIndexView::GenericIndexView (const GenericIndex & index) inline
Definition at line 375 of file InterpreterIndex.cpp.
 : index(index) {}
Member Function Documentation
contains() [1/2]
template<typename Structure> bool souffle::GenericIndex< Structure >::GenericIndexView::contains (const TupleRef & entry) const inline override virtual
Tests whether the given entry is contained in this index.
Implements souffle::IndexView.
Definition at line 377 of file InterpreterIndex.cpp.
References souffle::TupleRef::asTuple(), souffle::GenericIndex< Structure >::data, souffle::Order::encode(), and souffle::GenericIndex< Structure >::order.
{
             return index.data.contains(index.order.encode(tuple.asTuple<Arity>()), hints);
         }
contains() [2/2]
template<typename Structure> bool souffle::GenericIndex< Structure >::GenericIndexView::contains (const TupleRef & low, const TupleRef & high) const inline override virtual
Tests whether any element in the given range is contained in this index.
Implements souffle::IndexView.
Definition at line 381 of file InterpreterIndex.cpp.
References souffle::GenericIndex< Structure >::bounds().
{
             return !index.bounds(low, high, hints).empty();
         }
getArity()
template<typename Structure> size_t souffle::GenericIndex< Structure >::GenericIndexView::getArity () const inline override virtual
Return arity size of the index.
Implements souffle::IndexView.
Definition at line 390 of file InterpreterIndex.cpp.
{
             return Arity;
         }
range()
template<typename Structure> Stream souffle::GenericIndex< Structure >::GenericIndexView::range (const TupleRef & low, const TupleRef & high) const inline override virtual
Obtains a stream for the given range within this index.
Implements souffle::IndexView.
Definition at line 385 of file InterpreterIndex.cpp.
References souffle::range< Iter >::begin(), souffle::GenericIndex< Structure >::bounds(), souffle::range< Iter >::end(), and souffle::GenericIndex< Structure >::order.
{
             auto range = index.bounds(low, high, hints);
             return std::make_unique<Source>(index.order, range.begin(), range.end());
         }
Field Documentation
hints
template<typename Structure> Hints souffle::GenericIndex< Structure >::GenericIndexView::hints mutable
Definition at line 373 of file InterpreterIndex.cpp.
index
template<typename Structure> const GenericIndex& souffle::GenericIndex< Structure >::GenericIndexView::index
Definition at line 372 of file InterpreterIndex.cpp.
The documentation for this struct was generated from the following file:
interpreter/InterpreterIndex.cpp