souffle: souffle::detail::comparator< T > Struct Template Reference
souffle::detail::comparator< T > Struct Template Reference
A generic comparator implementation as it is used by a b-tree based on types that can be less-than and equality comparable.
#include <BTree.h>
Public Member Functions
bool equal (const T &a, const T &b) const
bool less (const T &a, const T &b) const
int operator() (const T &a, const T &b) const
Compares the values of a and b and returns -1 if a<b, 1 if a>b and 0 otherwise.
Detailed Description
template<typename T>
struct souffle::detail::comparator< T >
A generic comparator implementation as it is used by a b-tree based on types that can be less-than and equality comparable.
Definition at line 47 of file BTree.h.
Member Function Documentation
equal()
template<typename T> bool souffle::detail::comparator< T >::equal (const T & a, const T & b) const inline
Definition at line 58 of file BTree.h.
Referenced by souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, true, WeakComparator, Updater >::find(), and souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, true, WeakComparator, Updater >::lower_bound().
{
         return a == b;
     }
less()
template<typename T> bool souffle::detail::comparator< T >::less (const T & a, const T & b) const inline
Definition at line 55 of file BTree.h.
Referenced by souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, true, WeakComparator, Updater >::covers(), souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, true, WeakComparator, Updater >::coversUpperBound(), and souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, true, WeakComparator, Updater >::insert().
{
         return a < b;
     }
operator()()
template<typename T> int souffle::detail::comparator< T >::operator() (const T & a, const T & b) const inline
Compares the values of a and b and returns -1 if a<b, 1 if a>b and 0 otherwise.
Definition at line 52 of file BTree.h.
{
         return (a > b) - (a < b);
     }
The documentation for this struct was generated from the following file:
BTree.h