souffle: souffle::detail::binary_search Struct Reference
souffle::detail::binary_search Struct Reference
A binary search strategy for looking up keys in b-tree nodes.
#include <BTree.h>
Public Member Functions
binary_search ()=default
Required user-defined default constructor.
template<typename Key , typename Iter , typename Comp >
Iter lower_bound (const Key &k, Iter a, Iter b, Comp &comp) const
Obtains a reference to the first element in the given range that is not less than the given key.
template<typename Key , typename Iter , typename Comp >
Iter operator() (const Key &k, Iter a, Iter b, Comp &comp) const
Obtains an iterator pointing to some element within the given range that is equal to the given key, if available.
template<typename Key , typename Iter , typename Comp >
Iter upper_bound (const Key &k, Iter a, Iter b, Comp &comp) const
Obtains a reference to the first element in the given range that such that the given key is less than the referenced element.
Detailed Description
A binary search strategy for looking up keys in b-tree nodes.
Definition at line 127 of file BTree.h.
Constructor & Destructor Documentation
binary_search()
souffle::detail::binary_search::binary_search () default
Required user-defined default constructor.
Member Function Documentation
lower_bound()
template<typename Key , typename Iter , typename Comp > Iter souffle::detail::binary_search::lower_bound (const Key & k, Iter a, Iter b, Comp & comp) const inline
Obtains a reference to the first element in the given range that is not less than the given key.
Definition at line 167 of file BTree.h.
References souffle::test::count().
{
         Iter c;
         auto count = b - a;
         while (count > 0) {
             auto step = count >> 1;
             c = a + step;
             if (comp(*c, k) < 0) {
                 a = ++c;
                 count -= step + 1;
             } else {
                 count = step;
             }
         }
         return a;
     }
operator()()
template<typename Key , typename Iter , typename Comp > Iter souffle::detail::binary_search::operator() (const Key & k, Iter a, Iter b, Comp & comp) const inline
Obtains an iterator pointing to some element within the given range that is equal to the given key, if available.
If multiple elements are equal to the given key, an undefined instance will be obtained (no guaranteed lower or upper boundary). If no such element is present, a reference to the first element not less than the given key will be returned.
Definition at line 142 of file BTree.h.
References souffle::test::count().
{
         Iter c;
         auto count = b - a;
         while (count > 0) {
             auto step = count >> 1;
             c = a + step;
             auto r = comp(*c, k);
             if (r == 0) {
                 return c;
             }
             if (r < 0) {
                 a = ++c;
                 count -= step + 1;
             } else {
                 count = step;
             }
         }
         return a;
     }
upper_bound()
template<typename Key , typename Iter , typename Comp > Iter souffle::detail::binary_search::upper_bound (const Key & k, Iter a, Iter b, Comp & comp) const inline
Obtains a reference to the first element in the given range that such that the given key is less than the referenced element.
Definition at line 188 of file BTree.h.
References souffle::test::count().
{
         Iter c;
         auto count = b - a;
         while (count > 0) {
             auto step = count >> 1;
             c = a + step;
             if (comp(k, *c) >= 0) {
                 a = ++c;
                 count -= step + 1;
             } else {
                 count = step;
             }
         }
         return a;
     }
The documentation for this struct was generated from the following file:
BTree.h