souffle: souffle::TypeVisitor< R > Struct Template Reference
souffle::TypeVisitor< R > Struct Template Reference
A visitor for Types.
Public Member Functions
R operator() (const Type &type) const
virtual R visit (const Type &type) const
virtual R visitType (const Type &) const
virtual ~TypeVisitor ()=default
Detailed Description
template<typename R>
struct souffle::TypeVisitor< R >
A visitor for Types.
Definition at line 81 of file TypeSystem.cpp.
Constructor & Destructor Documentation
~TypeVisitor()
template<typename R > virtual souffle::TypeVisitor< R >::~TypeVisitor () virtual default
Member Function Documentation
operator()()
template<typename R > R souffle::TypeVisitor< R >::operator() (const Type & type) const inline
Definition at line 84 of file TypeSystem.cpp.
{
         return visit(type);
     }
visit()
template<typename R > virtual R souffle::TypeVisitor< R >::visit (const Type & type) const inline virtual
Reimplemented in souffle::VisitOnceTypeVisitor< R >.
Definition at line 91 of file TypeSystem.cpp.
References souffle::fatal(), FORWARD, and souffle::Record.
Referenced by souffle::getGreatestCommonSubtypes(), and souffle::VisitOnceTypeVisitor< R >::visit().
{
         FORWARD(Constant);
         FORWARD(Subset);
         FORWARD(Union);
         FORWARD(Record);
         fatal("Unsupported type encountered!");
     }
visitType()
template<typename R > virtual R souffle::TypeVisitor< R >::visitType (const Type &) const inline virtual
Definition at line 111 of file TypeSystem.cpp.
{
         return R();
     }
The documentation for this struct was generated from the following file:
ast/TypeSystem.cpp