souffle: souffle::RecordType Struct Reference
souffle::RecordType Struct Reference
A record type combining a list of fields into a new, aggregated type.
#include <TypeSystem.h>
Public Member Functions
const std::vector< const Type * > & getFields () const
void print (std::ostream &out) const override
void setFields (std::vector< const Type *> newFields)
Public Member Functions inherited from souffle::Type
const AstQualifiedName & getName () const
const TypeEnvironment & getTypeEnvironment () const
bool operator!= (const Type &other) const
bool operator< (const Type &other) const
bool operator== (const Type &other) const
Type (const Type &other)=delete
virtual ~Type ()=default
Protected Member Functions
RecordType (const TypeEnvironment &environment, const AstQualifiedName &name, const std::vector< const Type *> fields={})
Protected Member Functions inherited from souffle::Type
Type (const TypeEnvironment &environment, AstQualifiedName name)
Protected Attributes
std::vector< const Type * > fields
Protected Attributes inherited from souffle::Type
const TypeEnvironment & environment
A reference to the type environment this type is associated to.
AstQualifiedName name
Friends
class TypeEnvironment
Detailed Description
A record type combining a list of fields into a new, aggregated type.
Definition at line 163 of file TypeSystem.h.
Constructor & Destructor Documentation
RecordType()
souffle::RecordType::RecordType (const TypeEnvironment & environment, const AstQualifiedName & name, const std::vector< const Type *> fields = {}) inline protected
Definition at line 180 of file TypeSystem.h.
References souffle::Type::Type().
                                                   {})
             : Type(environment, name), fields(fields) {}
Member Function Documentation
getFields()
const std::vector<const Type*>& souffle::RecordType::getFields () const inline
Definition at line 169 of file TypeSystem.h.
References souffle::Type::print().
Referenced by souffle::getTypeQualifier().
{
         return fields;
     }
print()
void souffle::RecordType::print (std::ostream & out) const override virtual
Reimplemented from souffle::Type.
Reimplemented in souffle::SubsetRecordType.
Definition at line 35 of file TypeSystem.cpp.
References tinyformat::format(), souffle::Type::getName(), and souffle::join().
{
     out << tfm::format("%s = (%s)", getName(),
             join(fields, ", ",
                     [&](std::ostream& out, const Type* fieldType) { out << fieldType->getName(); }));
 }
setFields()
void souffle::RecordType::setFields (std::vector< const Type *> newFields) inline
Definition at line 165 of file TypeSystem.h.
Referenced by souffle::TypeEnvironmentAnalysis::createType(), and souffle::test::TEST().
{
         fields = std::move(newFields);
     }
Friends And Related Function Documentation
TypeEnvironment
friend class TypeEnvironment friend
Definition at line 176 of file TypeSystem.h.
Field Documentation
fields
std::vector<const Type*> souffle::RecordType::fields protected
Definition at line 178 of file TypeSystem.h.
The documentation for this struct was generated from the following files:
ast/TypeSystem.h
ast/TypeSystem.cpp