souffle: souffle::NullaryIndex::NullaryIndexView Struct Reference
souffle::NullaryIndex::NullaryIndexView Struct Reference
Public Member Functions
bool contains (const TupleRef &entry) const override
Tests whether the given entry is contained in this index.
bool contains (const TupleRef &low, const TupleRef &high) const override
Tests whether any element in the given range is contained in this index.
size_t getArity () const override
Return arity size of the index.
NullaryIndexView (const NullaryIndex &index)
Stream range (const TupleRef &low, const TupleRef &high) const override
Obtains a stream for the given range within this index.
Public Member Functions inherited from souffle::IndexView
virtual ~IndexView ()=default
Data Fields
const NullaryIndex & index
Detailed Description
Definition at line 214 of file InterpreterIndex.cpp.
Constructor & Destructor Documentation
NullaryIndexView()
souffle::NullaryIndex::NullaryIndexView::NullaryIndexView (const NullaryIndex & index) inline
Definition at line 217 of file InterpreterIndex.cpp.
 : index(index) {}
Member Function Documentation
contains() [1/2]
bool souffle::NullaryIndex::NullaryIndexView::contains (const TupleRef & entry) const inline override virtual
Tests whether the given entry is contained in this index.
Implements souffle::IndexView.
Definition at line 219 of file InterpreterIndex.cpp.
References souffle::NullaryIndex::contains().
{
             return index.contains(entry);
         }
contains() [2/2]
bool souffle::NullaryIndex::NullaryIndexView::contains (const TupleRef & low, const TupleRef & high) const inline override virtual
Tests whether any element in the given range is contained in this index.
Implements souffle::IndexView.
Definition at line 223 of file InterpreterIndex.cpp.
References souffle::NullaryIndex::contains().
{
             return index.contains(low, high);
         }
getArity()
size_t souffle::NullaryIndex::NullaryIndexView::getArity () const inline override virtual
Return arity size of the index.
Implements souffle::IndexView.
Definition at line 231 of file InterpreterIndex.cpp.
{
             return 0;
         }
range()
Stream souffle::NullaryIndex::NullaryIndexView::range (const TupleRef & low, const TupleRef & high) const inline override virtual
Obtains a stream for the given range within this index.
Implements souffle::IndexView.
Definition at line 227 of file InterpreterIndex.cpp.
References souffle::NullaryIndex::range().
{
             return index.range(low, high);
         }
Field Documentation
index
const NullaryIndex& souffle::NullaryIndex::NullaryIndexView::index
Definition at line 215 of file InterpreterIndex.cpp.
The documentation for this struct was generated from the following file:
interpreter/InterpreterIndex.cpp