// Souffle - A Datalog Compiler
// Copyright (c) 2016, The Souffle Developers. All rights reserved
// Licensed under the Universal Permissive License v 1.0 as shown at:
// - https://opensource.org/licenses/UPL
// - <souffle root>/licenses/SOUFFLE-UPL.txt

// Test allowed range for binary integers
.decl Binary (n:unsigned)
.output Binary

Binary(0b1).

#if RAM_DOMAIN_SIZE == 32
Binary(0b11111111111111111111111111111111 + 1).
#elif RAM_DOMAIN_SIZE == 64
Binary(0b1111111111111111111111111111111111111111111111111111111111111111 + 1).
#endif
