// Souffle - A Datalog Compiler
// Copyright (c) 2020, The Souffle Developers. All rights reserved
// Licensed under the Universal Permissive License v 1.0 as shown at:
// - https://opensource.org/licenses/UPL
// - <souffle root>/licenses/SOUFFLE-UPL.txt

//
// Aggregate 4
//
// Test if aggregation works correctly with float, unsigned and symbol
//

.decl A(x:unsigned)
.decl B(x:unsigned)
.decl C(x:unsigned)
.output C

A(1).
B(1) :- false.

C(y) :- y = sum a : A(a).
C(y) :- y = sum a : B(a).
