// Souffle - A Datalog Compiler
// Copyright (c) 2020, The Souffle Developers. All rights reserved
// Licensed under the Universal Permissive License v 1.0 as shown at:
// - https://opensource.org/licenses/UPL
// - <souffle root>/licenses/SOUFFLE-UPL.txt

// Test reading of a simple record. 

.type pair = [first: number, second: number]

.decl A(x: pair)
.input A()

.decl B(x: pair)
B(x) :- A(x).

.output B()
