/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class SwigInterface {
  public static void loadInput(map_string_string val, String prog_ins, String rel_name, String rel_name_out) {
    SwigInterfaceJNI.loadInput(map_string_string.getCPtr(val), val, prog_ins, rel_name, rel_name_out);
  }

  public static SWIGSouffleProgram newInstance(String name) {
    long cPtr = SwigInterfaceJNI.newInstance(name);
    return (cPtr == 0) ? null : new SWIGSouffleProgram(cPtr, false);
  }

}
