

.type pair = [ a:number, b:number ]

.decl s ( p : pair )

s(*pair[1,2]).
s(*pair[2,3]).
s(*pair[3,1]).

.decl res ( s : symbol )
.output res ()

res("11") :- s(*pair[1,1]).
res("12") :- s(*pair[1,2]).
res("13") :- s(*pair[1,3]).
res("21") :- s(*pair[2,1]).
res("22") :- s(*pair[2,2]).
res("23") :- s(*pair[2,3]).
res("31") :- s(*pair[3,1]).
res("32") :- s(*pair[3,2]).
res("33") :- s(*pair[3,3]).
