// Souffle - A Datalog Compiler
// Copyright (c) 2020, The Souffle Developers. All rights reserved
// Licensed under the Universal Permissive License v 1.0 as shown at:
// - https://opensource.org/licenses/UPL
// - <souffle root>/licenses/SOUFFLE-UPL.txt

// Program Minimisation 2
// Checks that singleton-relation reduction works

.decl A,B,C,D,E(x:number)
.decl F(x:number, y:number)
.decl G(x:number)

F(0,0).
F(1,2).

// these two are equivalent
A(a) :- F(a, _).
B(x) :- F(x, y).

// but not to this
C(a) :- F(_, a).

// these two are equivalent
D(x) :- F(x, x).
E(y) :- F(y, y).

G(x) :- A(x).
G(x) :- B(x).
G(x) :- C(x).
G(x) :- D(x).
G(x) :- E(x).

.output G()
